---
sidebar: sidebar 
permalink: authentication-access-control/enable-webauthn-mfa-task.html 
keywords: mfa, multi-factor, authentication, authorization, webauthn, FIDO2, hardware key, enable, system manager 
summary: System Managerユーザに対してWebAuthn MFAを有効にすることができます。 
---
= ONTAP System Managerのユーザまたはグループに対してWebAuthn MFAを有効にする
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
ONTAP管理者は、[WebAuthn MFA]オプションを有効にして新しいユーザまたはグループを追加するか、既存のユーザまたはグループに対してオプションを有効にすることで、System Managerのユーザまたはグループに対してWebAuthn MFAを有効にできます。


NOTE: ユーザまたはグループの2番目の認証方式としてWebAuthn MFAを有効にすると、System Managerに次回ログインしたときに、ユーザ（またはそのグループ内のすべてのユーザ）にハードウェアFIDO2デバイスの登録が求められます。この登録はユーザーのローカルオペレーティングシステムによって処理され、通常はセキュリティキーの挿入、パスキーの作成、セキュリティキーのタッチ（サポートされている場合）で構成されます。



== 新しいユーザまたはグループの作成時にWebAuthn MFAを有効にする

System ManagerまたはONTAP CLIを使用して、WebAuthn MFAを有効にして新しいユーザまたはグループを作成できます。

[role="tabbed-block"]
====
.System Manager
--
. [* Cluster]>[Settings]（設定）*を選択します。
. [ユーザとロール]*の横にある矢印アイコンを選択します。
. [Users]*で[Add]*を選択します。
. ユーザまたはグループの名前を指定し、* Role *のドロップダウンメニューでロールを選択します。
. ユーザまたはグループのログイン方法とパスワードを指定します。
+
WebAuthn MFAは、ユーザに対しては「password」、「domain」、または「nsswitch」、グループに対しては「domain」または「nsswitch」のログイン方法をサポートしています。

. [MFA for HTTP]列で、*[Enabled]*を選択します。
. [ 保存（ Save ） ] を選択します。


--
.CLI
--
. WebAuthn MFAを有効にして新しいユーザまたはグループを作成します。
+
次の例では、2番目の認証方式として「publickey」を選択してWebAuthn MFAを有効にしています。

+
[source, console]
----
security login create -user-or-group-name <user_or_group_name> \
                     -authentication-method domain \
                     -second-authentication-method publickey \
                     -application http \
                     -role admin
----


--
====


== 既存のユーザまたはグループに対してWebAuthn MFAを有効にする

既存のユーザまたはグループに対してWebAuthn MFAを有効にすることができます。

[role="tabbed-block"]
====
.System Manager
--
. [* Cluster]>[Settings]（設定）*を選択します。
. [ユーザとロール]*の横にある矢印アイコンを選択します。
. ユーザとグループのリストで、編集するユーザまたはグループのオプションメニューを選択します。
+
WebAuthn MFAは、ユーザに対しては「password」、「domain」、または「nsswitch」、グループに対しては「domain」または「nsswitch」のログイン方法をサポートしています。

. そのユーザの* MFA for HTTP *列で* Enabled *を選択します。
. [ 保存（ Save ） ] を選択します。


--
.CLI
--
. 既存のユーザまたはグループを変更して、そのユーザまたはグループに対してWebAuthn MFAを有効にします。
+
次の例では、2番目の認証方式として「publickey」を選択してWebAuthn MFAを有効にしています。

+
[source, console]
----
security login modify -user-or-group-name <user_or_group_name> \
                     -authentication-method domain \
                     -second-authentication-method publickey \
                     -application http \
                     -role admin
----


--
====


== 詳細

これらのコマンドについては、ONTAPのマニュアルページを参照してください。

* https://docs.netapp.com/us-en/ontap-cli/security-login-create.html["security login create"^]
* https://docs.netapp.com/us-en/ontap-cli/security-login-modify.html["security login modify"^]

