---
sidebar: sidebar 
permalink: authentication-access-control/manage-webauthn-settings-credentials.html 
keywords: mfa, multi-factor, authentication, authorization, webauthn, FIDO2, hardware key, credentials, manage, system manager, settings, configuration, credential 
summary: WebAuthn MFAのグローバル設定を表示したり、ユーザクレデンシャルを管理したりできます。 
---
= ONTAP WebAuthn MFA設定の表示とクレデンシャルの管理
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
ONTAP管理者は、クラスタ全体のWebAuthn MFA設定を表示し、WebAuthn MFAのユーザおよびグループのクレデンシャルを管理できます。



== WebAuthn MFAのクラスタ設定を表示します。

ONTAP CLIを使用して、WebAuthn MFAのクラスタ設定を表示できます。

.手順
. WebAuthn MFAのクラスタ設定を表示します。必要に応じて、引数を使用してStorage VMを指定できます `vserver`。
+
[source, console]
----
security webauthn show -vserver <storage_vm_name>
----




== サポートされている公開鍵WebAuthn MFAアルゴリズムの表示

Storage VMまたはクラスタのWebAuthn MFAでサポートされている公開鍵アルゴリズムを表示できます。

.手順
. サポートされている公開鍵WebAuthn MFAアルゴリズムを列挙します。必要に応じて、引数を使用してStorage VMを指定できます `vserver`。
+
[source, console]
----
security webauthn supported-algorithms show -vserver <storage_vm_name>
----




== 登録済みWebAuthn MFAクレデンシャルの表示

ONTAP管理者は、すべてのユーザの登録済みWebAuthnクレデンシャルを表示できます。この手順を使用する管理者以外のユーザは、自分の登録済みWebAuthnクレデンシャルのみを表示できます。

.手順
. 登録されたWebAuthn MFAクレデンシャルを表示します。
+
[source, console]
----
security webauthn credentials show
----




== 登録済みWebAuthn MFAクレデンシャルの削除

登録済みのWebAuthn MFAクレデンシャルを削除できます。これは、ユーザーのハードウェアキーが紛失したり、盗まれたり、使用されなくなったりした場合に便利です。ユーザーが元のハードウェアオーセンティケータを持っていて、新しいものに置き換えたい場合は、登録されたクレデンシャルを削除することもできます。クレデンシャルを削除すると、ユーザは交換用オーセンティケータを登録するように求められます。


NOTE: ユーザの登録済みクレデンシャルを削除しても、そのユーザのWebAuthn MFAは無効になりません。ユーザがハードウェアオーセンティケータを紛失し、交換する前にログインする必要がある場合は、次の手順とユーザの手順を使用してクレデンシャルを削除するlink:disable-webauthn-mfa-task.html["WebAuthn MFAを無効にする"]必要があります。

[role="tabbed-block"]
====
.System Manager
--
. [* Cluster]>[Settings]（設定）*を選択します。
. [ユーザとロール]*の横にある矢印アイコンを選択します。
. ユーザとグループのリストで、クレデンシャルを削除するユーザまたはグループのオプションメニューを選択します。
. [HTTPクレデンシャルのMFAを削除する]*を選択します。
. 「 * 削除」を選択します。


--
.CLI
--
. 登録済みクレデンシャルを削除します。次の点に注意してください。
+
** 必要に応じて、ユーザのStorage VMを指定できます。省略すると、クラスタレベルでクレデンシャルが削除されます。
** 必要に応じて、クレデンシャルを削除するユーザのユーザ名を指定できます。省略すると、現在のユーザのクレデンシャルが削除されます。
+
[source, console]
----
security webauthn credentials delete -vserver <storage_vm_name> -username <username>
----




--
====


== 詳細

これらのコマンドについては、ONTAPのマニュアルページを参照してください。

* https://docs.netapp.com/us-en/ontap-cli/security-webauthn-show.html["security webauthn show"^]
* https://docs.netapp.com/us-en/ontap-cli/security-webauthn-supported-algorithms-show.html["サポートされるセキュリティwebauthn - algorithms show"^]
* https://docs.netapp.com/us-en/ontap-cli/security-webauthn-credentials-show.html["security webauthn credentials show"^]
* https://docs.netapp.com/us-en/ontap-cli/security-webauthn-credentials-delete.html["セキュリティwebauthnクレデンシャルの削除"^]

