---
sidebar: sidebar 
permalink: authentication-access-control/webauthn-mfa-overview.html 
keywords: mfa, multi-factor, authentication, authorization, webauthn, FIDO2, hardware key 
summary: WebAuth.16.1以降では、ONTAPユーザに対してONTAP 9 MFAを有効にできます。 
---
= WebAuthn多要素認証の概要
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
ONTAP 9 .16.1以降では、管理者がにログインするユーザに対してWebAuthn多要素認証（MFA）を有効にすることができます。これにより、2つ目の認証形式としてFIDO2キー（YubiKeyなど）を使用したSystem Managerログインが有効になります。デフォルトでは、新規および既存のONTAPユーザに対してWebAuthn MFAは無効になっています。

WebAuthn MFAは、最初の認証方式に次のタイプの認証を使用するユーザおよびグループでサポートされます。

* ユーザ：パスワード、ドメイン、またはnsswitch
* グループ:ドメインまたはnsswitch


ユーザの2つ目の認証方式としてWebAuthn MFAを有効にすると、System Managerにログインしたときにハードウェア認証サーバを登録するように求められます。登録後、秘密鍵はオーセンティケータに格納され、公開鍵はONTAPに格納されます。

ONTAPは、ユーザごとに1つのWebAuthnクレデンシャルをサポートします。ユーザがオーセンティケータを失い、オーセンティケータを交換する必要がある場合、ONTAP管理者はそのユーザのWebAuthnクレデンシャルを削除して、ユーザが次回のログイン時に新しいオーセンティケータを登録できるようにする必要があります。


NOTE: 2つ目の認証方式としてWebAuthn MFAを有効にしているユーザは"https://myontap.example.com"[]、IPアドレス（など"https://192.168.100.200"[]）ではなくFQDN（など）を使用してSystem Managerにアクセスする必要があります。WebAuthn MFAが有効なユーザの場合、IPアドレスを使用してSystem Managerにログインしようとすると拒否されます。
