---
permalink: s3-config/assess-networking-requirements-task.html 
sidebar: sidebar 
keywords: assess, networking, requirements 
summary: クライアントにS3ストレージを提供する前に、ネットワークが正しく設定されてS3のプロビジョニング要件を満たしていることを確認する必要があります。 
---
= ONTAP S3ネットワーク要件を評価する
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
クライアントにS3ストレージを提供する前に、ネットワークが正しく設定されてS3のプロビジョニング要件を満たしていることを確認する必要があります。

.開始する前に
次のクラスタ ネットワーク オブジェクトを設定する必要があります。

* 物理ポートと論理ポート
* ブロードキャスト ドメイン
* サブネット（必要な場合）
* IPspace（必要に応じて、デフォルトのIPspaceに追加）
* フェイルオーバー グループ（必要に応じて、各ブロードキャスト ドメインのデフォルトのフェイルオーバー グループに追加）
* 外部ファイアウォール


.タスク概要
リモートのFabricPool大容量（クラウド）階層およびS3クライアントの場合は、データSVMを使用し、データLIFを設定する必要があります。FabricPoolクラウド階層の場合は、クラスタ間LIFも設定する必要があります。ただしクラスタのピアリングは必要ありません。

ローカルFabricPool容量階層の場合、システムSVM（「`Cluster`」と呼ばれます）を使用する必要がありますが、LIF設定には2つのオプションがあります：

* クラスタLIFを使用する。
+
この場合、LIFについて追加の設定は必要ありませんが、クラスタLIFのトラフィックが増加します。また、他のクラスタからローカル階層にアクセスすることはできません。

* データLIFとクラスタ間LIFを使用する。
+
この場合、LIFをS3プロトコルに対して有効にするなどの追加の設定が必要ですが、リモートのFabricPoolクラウド階層として他のクラスタからもローカル階層にアクセスできるようになります。



.手順
. 利用可能な物理ポートおよび仮想ポートを表示します。
+
`network port show`

+
** 可能な場合は、データ ネットワークの速度が最高であるポートを使用する必要があります。
** 最大限のパフォーマンスを得るためには、データ ネットワーク内のすべてのコンポーネントのMTU設定が同じである必要があります。


. サブネット名を使用してLIFのIPアドレスとネットワーク マスク値を割り当てる場合は、そのサブネットが存在し、十分な数のアドレスが使用可能であることを確認します。
+
`network subnet show`

+
サブネットには、同じレイヤー3サブネットに属するIPアドレスのプールが含まれます。サブネットは `network subnet create`コマンドを使用して作成されます。

+
 `network subnet show`の詳細については、link:https://docs.netapp.com/us-en/ontap-cli/network-subnet-show.html["ONTAPコマンド リファレンス"^]を参照してください。

. 使用可能なIPspaceを表示します。
+
`network ipspace show`

+
デフォルトのIPspaceまたはカスタムのIPspaceを使用できます。

. IPv6アドレスを使用する場合は、IPv6がクラスタで有効になっていることを確認します。
+
`network options ipv6 show`

+
必要に応じて、 `network options ipv6 modify` コマンドを使用して IPv6 を有効にすることができます。



.関連情報
* link:https://docs.netapp.com/us-en/ontap-cli/network-port-show.html["network port show"^]
* link:https://docs.netapp.com/us-en/ontap-cli/search.html?q=network+options+ipv6["ネットワークオプションIPv6"^]
* link:https://docs.netapp.com/us-en/ontap-cli/network-ipspace-show.html["network ipspace show"^]
* link:https://docs.netapp.com/us-en/ontap-cli/network-subnet-create.html["ネットワークサブネットの作成"^]

