---
permalink: s3-config/create-data-lifs-task.html 
sidebar: sidebar 
keywords: tr-4814, create, data, lifs 
summary: 新しいSVMを作成した場合は、S3アクセス専用のLIFとしてデータLIFを作成する必要があります。 
---
= ONTAP S3用のデータLIFの作成
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
新しいSVMを作成した場合は、S3アクセス専用のLIFとしてデータLIFを作成する必要があります。

.開始する前に
* 基盤となる物理または論理ネットワークポートの管理 `up`ステータスがに設定されている必要があります。の詳細については `up`、をlink:https://docs.netapp.com/us-en/ontap-cli/up.html["ONTAPコマンド リファレンス"^]参照してください。
* サブネット名を使用してLIFのIPアドレスとネットワークマスク値を割り当てる場合は、そのサブネットがすでに存在している必要があります。
+
サブネットには、同じレイヤ3サブネットに属するIPアドレスのプールが含まれています。コマンドを使用して作成し `network subnet create`ます。

* LIFサービスポリシーがすでに存在している必要があります。
* ベストプラクティスとして、データアクセスに使用するLIF（data-s3-server）と管理処理に使用するLIF（management-https）を別 々 に配置することを推奨します。同じLIFで両方のサービスを有効にしないでください。
* DNSレコードには、data-s3-serverが関連付けられているLIFのIPアドレスだけを含める必要があります。他のLIFのIPアドレスがDNSレコードに指定されている場合、ONTAP S3要求が他のサーバから処理され、予期しない応答やデータの損失が発生する可能性があります。


.タスクの内容
* 同じネットワークポートにIPv4とIPv6の両方のLIFを作成できます。
* クラスタに多数のLIFがある場合は、コマンドを使用してクラスタでサポートされるLIFの容量を確認するか、コマンド（advanced権限レベル）を使用して各ノードでサポートされるLIFの容量を `network interface capacity details show`確認できます `network interface capacity show`。
* リモートのFabricPool容量（クラウド）階層化を有効にする場合は、クラスタ間LIFも設定する必要があります。


.手順
. LIFを作成します。
+
`network interface create -vserver _svm_name_ -lif _lif_name_ -service-policy _service_policy_names_ -home-node _node_name_ -home-port _port_name_ {-address _IP_address_ -netmask _IP_address_ | -subnet-name _subnet_name_} -firewall-policy data -auto-revert {true|false}`

+
** `-home-node`は、LIFに対してコマンドを実行したときにLIFが戻るノードです `network interface revert`。
+
オプションを使用して、LIFをホームノードおよびホームポートに自動的にリバートするかどうかを指定することもできます `-auto-revert`。

** `-home-port`は、LIFに対してコマンドを実行したときにLIFが戻る物理ポートまたは論理ポートです `network interface revert`。
** オプションと `-netmask`オプションでIPアドレスを指定することも、オプションでサブネットからの割り当てを有効にすることも `-subnet_name`できます `-address`。
** サブネットを使用してIPアドレスとネットワークマスクを指定した場合、サブネットにゲートウェイが定義されていると、そのサブネットを使用してLIFを作成するときに、ゲートウェイへのデフォルトルートがSVMに自動的に追加されます。
** IPアドレスを手動で（サブネットを使用せずに）割り当てる場合、クライアントまたはドメインコントローラが別のIPサブネットにあるときに、ゲートウェイへのデフォルトルートの設定が必要になることがあります。SVM内での静的ルートの作成に関する詳細については、をlink:https://docs.netapp.com/us-en/ontap-cli/network-route-create.html["ONTAPコマンド リファレンス"^]参照し `network route create`てください。
** オプションには `-firewall-policy`、LIFのロールと同じデフォルトを使用し `data`ます。
+
必要に応じて、あとからカスタムファイアウォールポリシーを作成して追加できます。

+

NOTE: ONTAP 9 10.1以降では、ファイアウォールポリシーが廃止され、LIFのサービスポリシーに全面的に置き換えられました。詳細については、を参照してください link:../networking/configure_firewall_policies_for_lifs.html["LIFのファイアウォールポリシーを設定する"]。

** `-auto-revert`起動時、管理データベースのステータスが変わったとき、ネットワーク接続が確立されたときなどの状況で、データLIFがホームノードに自動的にリバートされるかどうかを指定できます。デフォルトの設定はです `false`が、環境内のネットワーク管理ポリシーに応じてに設定できます `false`。
** オプションは、 `-service-policy`作成したデータサービスポリシーと管理サービスポリシー、およびその他の必要なポリシーを指定します。


. オプションでIPv6アドレスを割り当てる場合 `-address`は、次の手順を実行します。
+
.. コマンドを使用して `network ndp prefix show`、さまざまなインターフェイスで学習されたRAプレフィックスのリストを表示します。
+
コマンドは `network ndp prefix show`、advanced権限レベルで使用できます。

.. 形式を使用し `prefix:id`て、IPv6アドレスを手動で作成します。
+
`prefix`は、さまざまなインターフェイスで学習されたプレフィックスです。

+
を生成するには `id`、ランダムな64ビット16進数を選択します。



. コマンドを使用して、LIFが正常に作成されたことを確認します `network interface show`。
. 設定したIPアドレスに到達できることを確認します。
+
[cols="2*"]
|===
| 対象 | 使用方法 


 a| 
IPv4アドレス
 a| 
`network ping`



 a| 
IPv6アドレス
 a| 
`network ping6`

|===


.例
次のコマンドは、サービスポリシーが割り当てられたS3データLIFを作成する方法を示してい `my-S3-policy`ます。

[listing]
----
network interface create -vserver svm1.example.com -lif lif2 -home-node node2 -homeport e0d -service-policy my-S3-policy -subnet-name ipspace1
----
次のコマンドは、cluster-1内のすべてのLIFを表示します。datalif1とdatalif3のデータLIFにはIPv4アドレスを設定し、datalif4にはIPv6アドレスを設定しています。

[listing]
----
cluster-1::> network interface show

            Logical    Status     Network          Current      Current Is
Vserver     Interface  Admin/Oper Address/Mask     Node         Port    Home
----------- ---------- ---------- ---------------- ------------ ------- ----
cluster-1
            cluster_mgmt up/up    192.0.2.3/24     node-1       e1a     true
node-1
            clus1        up/up    192.0.2.12/24    node-1       e0a     true
            clus2        up/up    192.0.2.13/24    node-1       e0b     true
            mgmt1        up/up    192.0.2.68/24    node-1       e1a     true
node-2
            clus1        up/up    192.0.2.14/24    node-2       e0a     true
            clus2        up/up    192.0.2.15/24    node-2       e0b     true
            mgmt1        up/up    192.0.2.69/24    node-2       e1a     true
vs1.example.com
            datalif1     up/down  192.0.2.145/30   node-1       e1c     true
vs3.example.com
            datalif3     up/up    192.0.2.146/30   node-2       e0c     true
            datalif4     up/up    2001::2/64       node-2       e0c     true
5 entries were displayed.
----