---
permalink: s3-config/index.html 
sidebar: sidebar 
keywords: decide, s3, configuration, client, access 
summary: このコンテンツでは、 ONTAP 9 の CLI コマンドを使用して、 SVM のバケットに格納されているオブジェクトへの S3 クライアントアクセスを設定する方法を説明します。 
---
= CLI を使用した S3 の設定の概要
:icons: font
:imagesdir: ../media/


[role="lead"]
このコンテンツでは、 ONTAP 9 の CLI コマンドを使用して、 SVM のバケットに格納されているオブジェクトへの S3 クライアントアクセスを設定する方法を説明します。例と高度な設定オプションが含まれています。

S3 オブジェクトストレージを設定する場合は、このコンテンツを使用します。想定している状況は次のとおりです。

* ONTAP を実行している既存のクラスタから S3 オブジェクトストレージを提供する。
+
ONTAP 環境は、ハードウェアや管理の追加なしで既存のクラスタの S3 機能を利用する場合に適しています。300TB を超える環境の場合、ネットアップの解決策ソフトウェアは、オブジェクトストレージ向けの主力製品である StorageGRID として引き続き提供されます。

* ONTAP System Manager や自動スクリプトツールではなく、コマンドラインインターフェイス（ CLI ）を使用する必要がある。
+
[NOTE]
====
バケットに使用するアグリゲートを指定できるようにするには、 CLI を使用する必要があります。

====
* すべての選択肢について検討するのではなく、ベストプラクティスに従う。
+
コマンド構文の詳細については、 CLI ヘルプおよび ONTAP のマニュアルページを参照してください。

* 背景にある概念について詳しく確認する必要はありません。
+
ONTAP 追加情報テクノロジおよび外部サービスとのやり取りについては、 ONTAP リファレンスライブラリおよびテクニカルレポート（ TR ）を参照してください。

* SVM 管理者権限ではなくクラスタ管理者権限を持っている。

