---
permalink: s3-config/ontap-version-support-s3-concept.html 
sidebar: sidebar 
keywords: tr-4814, ontap, version, support, s3, object, storage, AWS S3, Azure S3, cloud volumes ontap, aws, azure 
summary: ONTAPは、ONTAP 9.8以降、オンプレミス環境向けのS3オブジェクト ストレージをサポートします。Cloud Volumes ONTAPは、ONTAP 9.9.1以降、クラウド環境向けのS3オブジェクト ストレージをサポートします。 
---
= S3 オブジェクト ストレージの ONTAP バージョンとプラットフォームのサポート
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
S3オブジェクト ストレージは、ONTAP 9.8以降を使用するすべてのAFF、FAS、ONTAP Selectプラットフォームでサポートされます。

FC、iSCSI、NFS、NVMe_oF、SMBなどの他のプロトコルと同様に、S3をONTAPで使用するには、ライセンスのインストールが必要です。S3ライセンスは無料ですが、ONTAP 9.8にアップグレードするシステムにはインストールする必要があります。S3ライセンスは、NetAppサポートサイトのlink:https://mysupport.netapp.com/site/systems/master-license-keys/ontaps3["マスターライセンスキーページ"^]からダウンロードできます。

新しいONTAP 9.8以降のシステムには、S3のライセンスがプリインストールされています。



== Cloud Volumes ONTAP

ONTAP S3の設定と機能はCloud Volumes ONTAPでもオンプレミス環境と同じですが、1つだけ違いがあります。

* Cloud Volumes ONTAPでバケットを作成する際には、CLIの手順を使用して、基盤となるFlexGroupボリュームで使用されるアグリゲートが単一のノードのものに限定されるようにしてください。各ノードは地理的に離れたアベイラビリティ ゾーンに配置され、レイテンシの問題の影響を受けやすいため、複数のノードのアグリゲートを使用するとパフォーマンスが低下するおそれがあります。


|===
| クラウド プロバイダ | ONTAPバージョン 


| Google Cloud | ONTAP 9.12.1以降 


| AWS | ONTAP 9.11.0以降 


| Azure | ONTAP 9.9.1以降 
|===


== Amazon FSx for NetApp ONTAP

S3オブジェクト ストレージは、ONTAP 9.11以降を使用するAmazon FSx for NetAppサービスでサポートされます。



== MetroClusterでのS3のサポート

ONTAP 9.14.1以降では、MetroCluster IP構成およびFC構成のミラーされたアグリゲートのSVMでS3オブジェクト ストレージ サーバを有効にできます。

ONTAP 9.12.1以降では、MetroCluster IP構成のミラーされていないアグリゲート内のSVMでS3オブジェクトストレージサーバを有効にできます。MetroCluster IP構成におけるミラーされていないアグリゲートの制限事項の詳細については、link:https://docs.netapp.com/us-en/ontap-metrocluster/install-ip/considerations_unmirrored_aggrs.html["ミラーされていないアグリゲートに関する考慮事項"^]を参照してください。

SnapMirror S3 はMetroCluster構成ではサポートされていません。



== ONTAP 9.7でのS3のパブリック プレビュー

ONTAP 9.7では、S3オブジェクトストレージがパブリックプレビューとして導入されました。このバージョンは本番環境向けではなく、ONTAP 9.8以降では更新されなくなります。本番環境でS3オブジェクトストレージをサポートしているのは、ONTAP 9.8以降のリリースのみです。

ONTAP 9.7のパブリック プレビューで作成したS3バケットはONTAP 9.8以降でも使用できますが、拡張機能は利用できません。ONTAP 9.7のパブリック プレビューで作成したバケットがある場合は、強化された機能サポート、セキュリティ、パフォーマンスを使用できるよう、バケットのコンテンツをONTAP 9.8のバケットに移行してください。
