---
permalink: s3-config/ontap-version-support-s3-concept.html 
sidebar: sidebar 
keywords: ontap, version, support, s3, object, storage, AWS S3, Azure S3, cloud volumes ontap, aws, azure 
summary: ONTAP ONTAP 9.8以降、オンプレミス環境でS3オブジェクトストレージをサポート。Cloud Volumes ONTAP は、ONTAP 9.9..1以降、クラウド環境でS3オブジェクトストレージをサポートします。 
---
= S3 オブジェクトストレージでの ONTAP バージョンのサポート
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
ONTAP ONTAP 9.8以降、オンプレミス環境でS3オブジェクトストレージをサポート。Cloud Volumes ONTAP は、ONTAP 9.9..1以降、クラウド環境でS3オブジェクトストレージをサポートします。



== Cloud Volumes ONTAP によるS3のサポート

ONTAP S3はオンプレミス環境と同じようにCloud Volumes ONTAP で設定、機能します。ただし、次の点が異なります。

* 基盤となるアグリゲートは1つのノードだけで構成する必要があります。の詳細を確認してください link:create-svm-s3-task.html["CVO環境でのバケットの作成"]。


|===
| クラウドプロバイダ | ONTAP バージョン 


| Azure | ONTAP 9.9.1以降 


| AWS | ONTAP 9.11.0以降 


| Google Cloud | 現在サポートされていません 
|===


== ONTAP 9.7のS3パブリックプレビュー

ONTAP 9.7 では、 S3 オブジェクトストレージがパブリックプレビューとして導入されました。このバージョンは本番環境用ではなく、 ONTAP 9.8 以降では更新されません。本番環境で S3 オブジェクトストレージをサポートするのは、 ONTAP 9.8 以降のリリースだけです。

9.7 パブリックプレビューで作成した S3 バケットは、 ONTAP 9.8 以降で使用できますが、機能拡張は利用できません。9.7 パブリックプレビューで作成したバケットがある場合は、それらのバケットの内容を 9.8 バケットに移行して、機能のサポート、セキュリティ、パフォーマンスの強化を行う必要があります。
