---
permalink: snaplock/commit-files-worm-state-manual-task.html 
sidebar: sidebar 
keywords: commit, file, worm, manually, nfs, cifs, read, only, automatically, program, appendable, nfs, cifs, chunk, vam 
summary: ファイルをWORM（Write Once、Read Many）にコミットするには、手動でコミットするか、自動的にコミットします。追記可能WORMファイルを作成することもできます。 
---
= ファイルをWORM状態にコミット
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
ファイルをWORM（Write Once、Read Many）にコミットするには、手動でコミットするか、自動的にコミットします。追記可能WORMファイルを作成することもできます。



== ファイルをWORM状態に手動でコミット

ファイルを手動でWORM状態にコミットするには、ファイルを読み取り専用にします。ファイルの読み取り/書き込み属性は、NFSまたはCIFSで適切なコマンドやプログラムを使用して読み取り専用に変更できます。ファイルの書き込みが完了してファイルが途中でコミットされないようにする場合や、ボリューム数が多いために自動コミットスキャナの拡張に問題がある場合は、ファイルを手動でコミットすることを選択できます。

.必要なもの
* コミットするファイルがSnapLockボリューム上にある必要があります。
* ファイルは書き込み可能である必要があります。


.タスクの内容
ボリュームComplianceClock時間は、コマンドまたはプログラムの実行時にファイルのフィールドに書き込まれ `ctime`ます。ComplianceClock時間に基づいて、ファイルの保持期限に達したかどうかが決まります。

.手順
. 適切なコマンドまたはプログラムを使用して、ファイルの読み書き属性を読み取り専用に変更します。
+
UNIXシェルで、次のコマンドを使用して、という名前のファイルを読み取り専用にし `document.txt`ます。

+
[listing]
----
chmod -w document.txt
----
+
Windowsシェルで、次のコマンドを使用して、という名前のファイルを読み取り専用にし `document.txt`ます。

+
[listing]
----
attrib +r document.txt
----




== ファイルをWORM状態に自動的にコミット

SnapLockの自動コミット機能を使用すると、ファイルをWORMに自動的にコミットできます。自動コミット機能では、自動コミット期間中に変更されなかったファイルがSnapLock ボリュームのWORM状態にコミットされます。自動コミット機能は、デフォルトでは無効になっています。

.必要なもの
* 自動コミットするファイルがSnapLockボリューム上に存在している必要があります。
* SnapLockボリュームはオンラインである必要があります。
* SnapLockボリュームは読み書き可能ボリュームである必要があります。


[NOTE]
====
SnapLockの自動コミット機能は、ボリューム内のすべてのファイルをスキャンし、自動コミットの要件を満たしている場合はファイルをコミットします。ファイルが自動コミットできる状態になってから、SnapLock自動コミットスキャナによって実際にコミットされるまでに、時間がかかることがあります。ただし、ファイルは自動コミットの対象になった時点からファイルシステムによる削除や変更から保護されます。

====
.タスクの内容
_autocommit_period _ は、ファイルが自動コミットされるまでに、ファイルに変更がないようにする期間を指定します。この期間が経過する前にファイルが変更された場合、自動コミット期間はもう一度最初からカウントされます。

自動コミット期間に指定できる値は次のとおりです。

|===
| 値 | 単位 | 脚注 


 a| 
なし
 a| 
-
 a| 
デフォルトです。



 a| 
5-5256000
 a| 
分
 a| 
-



 a| 
1-87600
 a| 
時間
 a| 
-



 a| 
1～3650
 a| 
日
 a| 
-



 a| 
1 ~ 120
 a| 
月
 a| 
-



 a| 
1 ~ 10
 a| 
年
 a| 
-

|===
[NOTE]
====
最小値は5分、最大値は10年です。

====
.手順
. SnapLockボリューム上のファイルをWORM状態に自動コミットします。
+
`*volume snaplock modify -vserver _SVM_name_ -volume _volume_name_ -autocommit-period _autocommit_period_*`

+
すべてのオプションの一覧については、コマンドのマニュアルページを参照してください。

+
次のコマンドは、5時間変更がないかぎり、SVM vs1のボリューム上のファイルを自動コミットし `vol1`ます。

+
[listing]
----
cluster1::>volume snaplock modify -vserver vs1 -volume vol1 -autocommit-period 5hours
----




== 追記可能WORMファイルの作成

追記可能WORMファイルには、ログエントリと同様に段階的に書き込まれたデータが保持されます。追記可能 WORM ファイルは、適切なコマンドやプログラムを使用して作成するか、 SnapLock のボリュームアペンドモード機能を使用してデフォルトで作成できます。



== コマンドまたはプログラムを使用して追記可能WORMファイルを作成する

追記可能WORMファイルは、NFSまたはCIFSで適切なコマンドやプログラムを使用して作成できます。追記可能WORMファイルには、ログエントリと同様に段階的に書き込まれたデータが保持されます。データは256KBのチャンク単位でファイルに追加されます。各チャンクが書き込まれると、前のチャンクがWORM方式で保護されます。このファイルは保持期間が経過するまで削除できません。

.必要なもの
追記可能WORMファイルはSnapLockボリュームに格納する必要があります。

.タスクの内容
データは、アクティブな256KBチャンクに順番に書き込まれる必要はありません。ファイルの n * 256KB+1 バイトにデータが書き込まれると、 1 つ前の 256KB セグメントが WORM 方式で保護されます。

現在アクティブな256KBチャンクを超える順序付けされていない書き込みは、アクティブな256KBチャンクが最新のオフセットにリセットされ、古いオフセットへの書き込みが「読み取り専用ファイルシステム（ROFS）」エラーで失敗します。書き込みオフセットは、クライアントアプリケーションによって異なります。追記可能WORMファイル書き込みセマンティクスに準拠していないクライアントが原因で、書き込み内容が誤って終了する可能性があります。したがって、順序付けされていない書き込みのオフセット制限に従うか、ファイルシステムを同期モードでマウントして同期書き込みを確保することを推奨します。

.手順
. 適切なコマンドまたはプログラムを使用して、必要な保持期限を指定した空のファイルを作成します。
+
UNIXシェルで、次のコマンドを使用して、という名前のゼロ長ファイルに保持期限を2020年11月21日午前6時に設定し `document.txt`ます。

+
[listing]
----
touch -a -t 202011210600 document.txt
----
. 適切なコマンドまたはプログラムを使用して、ファイルの読み書き属性を読み取り専用に変更します。
+
UNIXシェルで、次のコマンドを使用して、という名前のファイルを読み取り専用にし `document.txt`ます。

+
[listing]
----
chmod 444 document.txt
----
. 適切なコマンドまたはプログラムを使用して、ファイルの読み書き属性を書き込み可能に戻します。
+
[NOTE]
====
ファイルにデータがないため、この手順はコンプライアンスリスクとはみなされません。

====
+
UNIXシェルで、次のコマンドを使用して、という名前のファイルを書き込み可能にし `document.txt`ます。

+
[listing]
----
chmod 777 document.txt
----
. 適切なコマンドまたはプログラムを使用して、ファイルへのデータの書き込みを開始します。
+
UNIXシェルで、次のコマンドを使用してにデータを書き込み `document.txt`ます。

+
[listing]
----
echo test data >> document.txt
----
+
[NOTE]
====
ファイルにデータを追加する必要がなくなったら、ファイル権限を読み取り専用に戻してください。

====




== ボリュームアペンドモードを使用して追記可能WORMファイルを作成する

ONTAP 9.3 以降では、 SnapLock のボリュームアペンドモード（ VAM ）機能を使用して、追記可能 WORM ファイルをデフォルトで作成できます。追記可能WORMファイルには、ログエントリと同様に段階的に書き込まれたデータが保持されます。データは256KBのチャンク単位でファイルに追加されます。各チャンクが書き込まれると、前のチャンクがWORM方式で保護されます。このファイルは保持期間が経過するまで削除できません。

.必要なもの
* 追記可能WORMファイルはSnapLockボリュームに格納する必要があります。
* SnapLockボリュームがアンマウントされていて、Snapshotコピーとユーザが作成したファイルが空である必要があります。


.タスクの内容
データは、アクティブな256KBチャンクに順番に書き込まれる必要はありません。ファイルの n * 256KB+1 バイトにデータが書き込まれると、 1 つ前の 256KB セグメントが WORM 方式で保護されます。

ボリュームに自動コミット期間を指定した場合、追記可能WORMファイルに変更がなかった期間が自動コミット期間を超えると、そのファイルはWORM状態にコミットされます。

[NOTE]
====
VAMはSnapLock監査ログボリュームではサポートされません。

====
.手順
. VAMを有効にします。
+
`*volume snaplock modify -vserver _SVM_name_ -volume _volume_name_ -is-volume-append-mode-enabled true|false*`

+
すべてのオプションの一覧については、コマンドのマニュアルページを参照してください。

+
次のコマンドは、SVM``vs1``のボリュームでVAMを有効にし `vol1`ます。

+
[listing]
----
cluster1::>volume snaplock modify -vserver vs1 -volume vol1 -is-volume-append-mode-enabled true
----
. 適切なコマンドまたはプログラムを使用して、書き込み権限を持つファイルを作成します。
+
ファイルはデフォルトで追記可能WORMです。


