---
permalink: snaplock/create-snaplock-aggregate-task.html 
sidebar: sidebar 
keywords: create, snaplock, aggregate, compliance, enterprise, mode, volumes 
summary: 'ボリューム `-snaplock-type`オプションを使用して、ComplianceまたはEnterpriseのSnapLockボリューム タイプを指定します。ONTAP 9.10.1より前のリリースでは、別個のSnapLockアグリゲートを作成する必要があります。ONTAP 9.10.1以降では、SnapLockボリュームと非SnapLockボリュームが同じアグリゲート上に存在できるようになりました。そのため、ONTAP 9.10.1を使用している場合は、別個のSnapLockアグリゲートを作成する必要はありません。' 
---
= ONTAP SnapLockアグリゲートを作成する
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
ボリューム `-snaplock-type`オプションを使用して、ComplianceまたはEnterpriseのSnapLockボリューム タイプを指定します。ONTAP 9.10.1より前のリリースでは、別個のSnapLockアグリゲートを作成する必要があります。ONTAP 9.10.1以降では、SnapLockボリュームと非SnapLockボリュームが同じアグリゲート上に存在できるようになりました。そのため、ONTAP 9.10.1を使用している場合は、別個のSnapLockアグリゲートを作成する必要はありません。

.開始する前に
* このタスクを実行するには、クラスタ管理者である必要があります。
* ノード上のSnapLock link:../system-admin/install-license-task.html["ライセンスをインストールする必要があります"]。このライセンスはlink:../system-admin/manage-licenses-concept.html#licenses-included-with-ontap-one["ONTAP One"]に含まれています。
* link:../snaplock/initialize-complianceclock-task.html["ノード上のコンプライアンスクロックを初期化する必要があります"]。
* ディスクを「`root`」、「`data1`」、および「`data2`」としてパーティション分割している場合は、スペアディスクが使用可能であることを確認する必要があります。


.アップグレード時の考慮事項
ONTAP 9.10.1にアップグレードすると、既存のSnapLockおよび非SnapLockアグリゲートがSnapLockボリュームと非SnapLockボリュームの両方をサポートするようにアップグレードされますが、既存のSnapLockボリュームの属性は自動的には更新されません。たとえば、data-compaction、cross-volume-dedupe、cross-volume-background-dedupeの各フィールドは変更されません。既存のアグリゲートに作成された新しいSnapLockボリュームには非SnapLockボリュームと同じデフォルト値が使用され、新しいボリュームとアグリゲートにはプラットフォームに応じて異なるデフォルト値が適用されます。

.リバートに関する考慮事項
ONTAP 9.10.1よりも前のバージョンにリバートする必要がある場合は、すべてのSnapLock Complianceボリューム、SnapLock Enterpriseボリューム、およびSnapLockボリュームをそれぞれのSnapLockアグリゲートに移動する必要があります。

.タスク概要
* SyncMirrorオプションを指定してComplianceアグリゲートを作成することはできません。
* ミラーされたComplianceアグリゲートをMetroCluster構成に作成できるのは、アグリゲートをSnapLock監査ログ ボリュームのホストとして使用する場合だけです。
+
[NOTE]
====
MetroCluster構成では、SnapLock Enterpriseは、ミラーされたアグリゲートとミラーされていないアグリゲートでサポートされます。SnapLock Complianceは、ミラーされていないアグリゲートでのみサポートされます。

====


.手順
. SnapLockアグリゲートを作成します。
+
[source, cli]
----
storage aggregate create -aggregate <aggregate_name> -node <node_name> -diskcount <number_of_disks> -snaplock-type <compliance|enterprise>
----
+
次のコマンドは、 `node1`上の3つのディスクを使用して `aggr1`という名前のSnapLock `Compliance`アグリゲートを作成します：

+
[listing]
----
cluster1::> storage aggregate create -aggregate aggr1 -node node1 -diskcount 3 -snaplock-type compliance
----
+
 `storage aggregate create`の詳細については、link:https://docs.netapp.com/us-en/ontap-cli/storage-aggregate-create.html["ONTAPコマンド リファレンス"^]をご覧ください。


