---
permalink: snaplock/create-snaplock-volume-task.html 
sidebar: sidebar 
keywords: snaplock, volume, shanpshot, copy, create, complianceclock, file, worm, compliance, enterprise 
summary: 'WORM 状態にコミットするファイルまたは Snapshot コピーに対しては、 SnapLock ボリュームを作成する必要があります。ONTAP 9.10.1 以降では、アグリゲートの種類に関係なく、作成するすべてのボリュームがデフォルトで SnapLock 以外のボリュームとして作成されます。SnapLock ボリュームを明示的に作成するには "-snaplock-type" オプションを使用して "Compliance または Enterprise のいずれかを SnapLock タイプとして指定する必要がありますデフォルトでは、 SnapLock タイプは「 non-snaplock" 」に設定されています。' 
---
= SnapLock ボリュームを作成してマウント
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
WORM 状態にコミットするファイルまたは Snapshot コピーに対しては、 SnapLock ボリュームを作成する必要があります。ONTAP 9.10.1 以降では、アグリゲートの種類に関係なく、作成するすべてのボリュームがデフォルトで SnapLock 以外のボリュームとして作成されます。SnapLock ボリュームを明示的に作成するには '-snaplock-type' オプションを使用して 'Compliance または Enterprise のいずれかを SnapLock タイプとして指定する必要がありますデフォルトでは、 SnapLock タイプは「 non-snaplock' 」に設定されています。

.必要なもの
* SnapLock アグリゲートがオンラインになっている必要があります。
* ノードに SnapLock ライセンスがインストールされている必要があります。
* ノードの ComplianceClock を初期化しておく必要があります。


.このタスクについて
適切な SnapLock 権限を使用すれば、いつでも Enterprise ボリュームの削除や名前変更を行うことができます。Compliance ボリュームの削除は保持期間が終了するまでは実行できません。Compliance ボリュームの名前は一切変更できません。

SnapLock ボリュームはクローニングできますが、 SnapLock ボリューム上のファイルはクローニングできません。クローンボリュームの SnapLock タイプは親ボリュームと同じになります。

[NOTE]
====
LUN は SnapLock ボリュームではサポートされていません。従来のテクノロジを使用して SnapLock ボリュームに LUN を移動することは可能ですが、サポートされている処理ではなく、 SnapLock ボリューム上の LUN に関するその他の処理も実行できません。

====
この作業は、ONTAP システムマネージャまたはONTAP CLIを使用して実行します。

[role="tabbed-block"]
====
.System Manager の略
--
ONTAP 9.12.1以降では、System Managerを使用してSnapLock ボリュームを作成できます。

.手順
. [*Storage]>[Volumes]に移動し、[*Add]をクリックします。
. [ボリュームの追加*]ウィンドウで、[*その他のオプション*]をクリックします。
. ボリュームの名前とサイズなど、新しいボリューム情報を入力します。
. 「* SnapLock を有効にする*」を選択し、SnapLock タイプとして「Compliance」または「Enterprise」を選択します。
. [ファイルの自動コミット*]セクションで、[変更済み]を選択し、ファイルが自動的にコミットされるまでに変更されないようにする時間を入力します。最小値は 5 分、最大値は 10 年です。
. [*データ保持期間]セクションで、最小保持期間と最大保持期間を選択します。
. デフォルトの保持期間を選択します。
. [ 保存（ Save ） ] をクリックします。
. [* Volumes]ページで新しいボリュームを選択し、SnapLock 設定を確認します。


--
.CLI の使用
--
. SnapLock ボリュームを作成します。
+
` * volume create -vserver _svm_name _ -volume_name_-aggregate _aggregate_name _ * -snaplock-type compliance | enterprise-volume

+
すべてのオプションの一覧については、コマンドのマニュアルページを参照してください。SnapLock ボリュームには、「 -nvfail 」、「 -atime-update 」、「 -is-autobalance eligible 」、「 -space-mgmt-try-first 」、「 vmalign 」の各オプションはありません。

+
次のコマンドは 'vs1' の aggr1 に 'vol1' という名前の SnapLock Compliance ボリュームを作成します

+
[listing]
----
cluster1::> volume create -vserver vs1 -volume vol1 -aggregate aggr1 -snaplock-type compliance
----


--
====


== SnapLock ボリュームをマウント

NAS クライアントからアクセスできるように、 SnapLock ボリュームを SVM ネームスペースのジャンクションパスにマウントすることができます。

.必要なもの
SnapLock ボリュームはオンラインである必要があります。

.このタスクについて
* SnapLock ボリュームは SVM のルートにしかマウントできません。
* 通常のボリュームを SnapLock ボリュームにマウントすることはできません。


.手順
. SnapLock ボリュームをマウントします。
+
` * volume mount -vserver_svm_name_-volume_name_-junction-path _ -junction-path _ *

+
すべてのオプションの一覧については、コマンドのマニュアルページを参照してください。

+
次に、「 vol1 」という名前の SnapLock ボリュームを「 vs1 」ネームスペースのジャンクションパス「 /sales 」にマウントするコマンドを示します。

+
[listing]
----
cluster1::> volume mount -vserver vs1 -volume vol1 -junction-path /sales
----

