---
permalink: snaplock/create-snaplock-volume-task.html 
sidebar: sidebar 
keywords: snaplock, volume, shanpshot, copy, create, complianceclock, file, worm, compliance, enterprise 
summary: 'ファイルやスナップショットをWORM状態にコミットするには、SnapLockボリュームを作成する必要があります。ONTAP 9.10.1以降では、アグリゲートの種類に関係なく、作成されるすべてのボリュームはデフォルトで非SnapLockボリュームとして作成されます。明示的にSnapLockボリュームを作成するには、 `-snaplock-type`オプションを使用し、SnapLockタイプとしてComplianceまたはEnterpriseのいずれかを指定する必要があります。デフォルトでは、SnapLockタイプは `non-snaplock`に設定されています。' 
---
= ONTAP SnapLockボリュームを作成してマウントする
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
ファイルやスナップショットをWORM状態にコミットするには、SnapLockボリュームを作成する必要があります。ONTAP 9.10.1以降では、アグリゲートの種類に関係なく、作成されるすべてのボリュームはデフォルトで非SnapLockボリュームとして作成されます。明示的にSnapLockボリュームを作成するには、 `-snaplock-type`オプションを使用し、SnapLockタイプとしてComplianceまたはEnterpriseのいずれかを指定する必要があります。デフォルトでは、SnapLockタイプは `non-snaplock`に設定されています。

.開始する前に
* SnapLockアグリゲートがオンラインになっている必要があります。
* link:../system-admin/manage-license-task.html["SnapLockライセンスがインストールされていることを確認する"]する必要があります。SnapLockライセンスがノードにインストールされていない場合は、link:../system-admin/install-license-task.html["インストール"]する必要があります。このライセンスはlink:../system-admin/manage-licenses-concept.html["ONTAP One"]に含まれています。ONTAP Oneより前のバージョンでは、SnapLockライセンスはSecurity and Complianceバンドルに含まれていました。Security and Complianceバンドルは現在提供されていませんが、引き続き有効です。現在必須ではありませんが、既存のお客様はlink:../system-admin/download-nlf-task.html["ONTAP Oneにアップグレード"]を選択できます。
* link:../snaplock/initialize-complianceclock-task.html["ノード上のコンプライアンスクロックを初期化する必要があります"]。


.タスク概要
SnapLockの適切な権限があれば、Enterpriseボリュームはいつでも破棄または名前変更できます。Complianceボリュームの削除は保持期間が終了するまでは実行できません。Complianceボリュームの名前は一切変更できません。

SnapLockボリュームはクローニングできますが、SnapLockボリュームのファイルはクローニングできません。クローン ボリュームのSnapLockタイプは親ボリュームと同じになります。

[NOTE]
====
LUNはSnapLockボリュームではサポートされません。LUNは、非SnapLockボリューム上で作成されたスナップショットがSnapLockヴォールト関係の一部として保護のためにSnapLockボリュームに転送される場合にのみ、SnapLockボリュームでサポートされます。LUNは読み取り / 書き込みSnapLockボリュームではサポートされません。ただし、改ざん防止スナップショットは、LUNを含むSnapMirrorソースボリュームとデスティネーションボリュームの両方でサポートされます。

====
このタスクは、ONTAP System ManagerまたはONTAP CLIを使用して実行します。

[role="tabbed-block"]
====
.System Manager
--
ONTAP 9.12.1以降では、System Managerを使用してSnapLockボリュームを作成できます。

.手順
. *ストレージ > ボリューム* に移動し、*追加* をクリックします。
. *ボリュームの追加*ウィンドウで、*その他のオプション*をクリックします。
. 新しいボリュームの情報（ボリュームの名前とサイズなど）を入力します。
. *SnapLockを有効にする*を選択し、SnapLockタイプ（ComplianceまたはEnterprise）を選択します。
. *ファイルの自動コミット*セクションで*変更済み*を選択し、ファイルが変更されずに保持される期間を入力すると、その期間経過後に自動的にコミットされます。最小値は5分、最大値は10年です。
. *Data Retention*セクションで、最小および最大保持期間を選択します。
. デフォルトの保持期間を選択します。
. *保存*をクリックします。
. *ボリューム* ページで新しいボリュームを選択し、SnapLock 設定を確認します。


--
.CLI
--
. SnapLockボリュームを作成します。
+
[source, cli]
----
volume create -vserver <SVM_name> -volume <volume_name> -aggregate <aggregate_name> -snaplock-type <compliance|enterprise>
----
+
 `volume create`の詳細については、link:https://docs.netapp.com/us-en/ontap-cli/volume-create.html["ONTAPコマンド リファレンス"^]を参照してください。次のオプションはSnapLockボリュームでは使用できません： `-nvfail`、 `-atime-update`、 `-is-autobalance-eligible`、 `-space-mgmt-try-first`、および `vmalign`。

+
次のコマンドは、 `vs1`上の `aggr1`に `vol1`という名前のSnapLock `Compliance`ボリュームを作成します：

+
[listing]
----
cluster1::> volume create -vserver vs1 -volume vol1 -aggregate aggr1 -snaplock-type compliance
----


--
====


== SnapLockボリュームのマウント

NASクライアントからアクセスできるように、SnapLockボリュームをSVMネームスペースのジャンクション パスにマウントすることができます。

.開始する前に
SnapLockがオンラインである必要があります。

.タスク概要
* SnapLockボリュームはSVMのルートにしかマウントできません。
* 通常のボリュームをSnapLockボリュームにマウントすることはできません。


.手順
. SnapLockボリュームをマウントします。
+
`*volume mount -vserver _SVM_name_ -volume _volume_name_ -junction-path _path_*`

+
 `volume mount`の詳細については、link:https://docs.netapp.com/us-en/ontap-cli/volume-mount.html["ONTAPコマンド リファレンス"^]をご覧ください。

+
次のコマンドは、SnapLockボリューム `vol1`を `vs1`名前空間内のジャンクションパス `/sales`にマウントします：

+
[listing]
----
cluster1::> volume mount -vserver vs1 -volume vol1 -junction-path /sales
----

