---
permalink: snaplock/create-snaplock-aggregate-task.html 
sidebar: sidebar 
keywords: create, snaplock, aggregate, compliance, enterprise, mode, volumes 
summary: ボリュームのタイプとして Compliance または Enterprise SnapLock を指定するには 'volume-snaplock-type オプションを使用しますONTAP 9.10.1 よりも前のリリースでは、別の SnapLock アグリゲートを作成する必要があります。ONTAP 9.10.1 以降では、 SnapLock ボリュームと非 SnapLock ボリュームを同じアグリゲート上に配置できるため、 ONTAP 9.10.1 を使用している場合に別の SnapLock アグリゲートを作成する必要がなくなりました。 
---
= SnapLock アグリゲートを作成する
:icons: font
:imagesdir: ../media/


[role="lead"]
ボリュームのタイプとして Compliance または Enterprise SnapLock を指定するには 'volume-snaplock-type オプションを使用しますONTAP 9.10.1 よりも前のリリースでは、別の SnapLock アグリゲートを作成する必要があります。ONTAP 9.10.1 以降では、 SnapLock ボリュームと非 SnapLock ボリュームを同じアグリゲート上に配置できるため、 ONTAP 9.10.1 を使用している場合に別の SnapLock アグリゲートを作成する必要がなくなりました。

.必要なもの
* このタスクを実行するには、クラスタ管理者である必要があります。
* ノードに SnapLock ライセンスがインストールされている必要があります。
* ノードの ComplianceClock を初期化しておく必要があります。
* ディスクを「 root 」、「 data1 」、および「 `d ata2` 」としてパーティショニングした場合、スペアディスクが利用可能であることを確認する必要があります。


ONTAP 9.10.1 にアップグレードすると、既存の SnapLock アグリゲートおよび非 SnapLock アグリゲートが SnapLock ボリュームと非 SnapLock ボリュームの両方の存在をサポートするようにアップグレードされますが、既存の SnapLock ボリュームの属性は自動的には更新されません。たとえば、データコンパクション、ボリューム間重複排除、およびボリューム間バックグラウンド重複排除のフィールドは変更されません。既存のアグリゲートに作成された新しい SnapLock ボリュームのデフォルト値は SnapLock 以外のボリュームと同じで、新しいボリュームおよびアグリゲートのデフォルト値はプラットフォームごとに異なります。

9.10.1 より前のバージョンの ONTAP にリバートする必要がある場合は、すべての SnapLock Compliance ボリューム、 SnapLock Enterprise ボリューム、および SnapLock ボリュームをそれぞれ独自の SnapLock アグリゲートに移動する必要があります。

.このタスクについて
* FlexArray LUN に対して Compliance アグリゲートを作成することはできませんが、 FlexArray Compliance アグリゲートは SnapLock LUN でサポートされます。
* SyncMirror オプションを使用して Compliance アグリゲートを作成することはできません。
* ミラーされた Compliance アグリゲートを MetroCluster 構成に作成できるのは、アグリゲートを SnapLock 監査ログボリュームのホストとして使用する場合だけです。
+
[NOTE]
====
MetroCluster 構成では、ミラーされたアグリゲートとミラーされていないアグリゲートで SnapLock Enterprise がサポートされます。SnapLock Compliance は、ミラーされていないアグリゲートでのみサポートされます。

====


.手順
. SnapLock アグリゲートを作成します。
+
` * storage aggregate create -aggregate _aggregate_name -- node_name_disks_disks_disks_--snaplock-type compliance | enterprise * 」

+
すべてのオプションの一覧については、コマンドのマニュアルページを参照してください。

+
次のコマンドは 'node1 に 3 つのディスクを持つ 'aggr1 という名前の SnapLock Compliance アグリゲートを作成します

+
[listing]
----
cluster1::> storage aggregate create -aggregate aggr1 -node node1 -diskcount 3 -snaplock-type compliance
----

