---
permalink: snaplock/hold-tamper-proof-files-indefinite-period-task.html 
sidebar: sidebar 
keywords: legal, hold, feature, compliance, mode, worm, files, retain 
summary: ONTAP 9.3 以降では、リーガルホールド機能を使用して訴訟期間中に Compliance モードの WORM ファイルを保持できます。 
---
= 訴訟時にリーガルホールドを使用してWORMファイルを保持
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
ONTAP 9.3以降では、_Legal Hold_featureを使用して、ComplianceモードのWORMファイルを訴訟の期間にわたって保持できます。

.必要なもの
* このタスクを実行するには、SnapLock管理者である必要があります。
+
link:create-compliance-administrator-account-task.html["SnapLock管理者アカウントの作成"]

* セキュアな接続（SSH、コンソール、またはZAPI）でログインしておく必要があります。


.タスクの内容
リーガルホールドの対象となるファイルは、保持期間が無期限のWORMファイルのように動作します。リーガルホールド期間の終了日を指定するのは、お客様の責任です。

リーガルホールドの対象となるファイル数は、ボリュームで使用可能なスペースによって異なります。

.手順
. リーガルホールドを開始します。
+
`*snaplock legal-hold begin -litigation-name _litigation_name_ -volume _volume_name_ -path _path_name_*`

+
次のコマンドは、のすべてのファイルに対してリーガルホールドを開始し `vol1`ます。

+
[listing]
----
cluster1::>snaplock legal-hold begin -litigation-name litigation1 -volume vol1 -path /
----
. リーガルホールドの終了：
+
`*snaplock legal-hold end -litigation-name _litigation_name_ -volume _volume_name_ -path _path_name_*`

+
次のコマンドは、のすべてのファイルのリーガルホールドを終了し `vol1`ます。

+
[listing]
----
cluster1::>snaplock legal-hold end -litigation-name litigation1 -volume vol1 -path /
----

