---
permalink: snaplock/index.html 
sidebar: sidebar 
keywords: decide, about, archive, compliance, snaplock, unmodified, file, worm, storage, snap lock, mirror, unmirror. license, compliance clock, regulatory, governance, rules, govern, MAV, multi-admin verification, supported, unsupported 
summary: NetApp SnapLockテクノロジを使用して、規制やガバナンスに準拠するために変更不可能な状態でファイルを保管することができます。 
---
= ONTAP SnapLockについて学ぶ
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
SnapLockは、規制やガバナンスに準拠するためにWORMストレージを使用して変更不可能な状態でファイルを保管する組織向けの、ハイパフォーマンスなコンプライアンス ソリューションです。

データの削除、変更、名前変更を防止でき、SEC 17a-4（f）、HIPAA、FINRA、CFTC、GDPRなどの規制に準拠することができます。専用のボリュームを作成して、指定した保持期間または永久にファイルを消去および書き換え不可能な状態で保存およびコミットできます。SnapLockでは、CIFSやNFSなどの標準オープン ファイル プロトコルにより、ファイル レベルでこのようなデータ保持を実行できます。サポートされるオープン ファイル プロトコルは、NFS（バージョン2、3、4）とCIFS（SMB 1.0、2.0、3.0）です。

SnapLockを使用すると、ファイルとスナップショットをWORMストレージにコミットし、WORM保護されたデータの保持期間を設定できます。SnapLock WORMストレージはNetAppスナップショット技術を使用し、SnapMirrorレプリケーションとSnapVaultバックアップを基盤技術として活用することで、データのバックアップ・リカバリ保護を実現します。WORMストレージの詳細については、こちらをご覧ください：link:https://www.netapp.com/pdf.html?item=/media/6158-tr4526pdf.pdf["NetApp SnapLockを使用した準拠のWORMストレージ - TR-4526"^]

アプリケーションを使用してNFSまたはCIFS経由でファイルをWORM状態にコミットするか、SnapLock自動コミット機能を使用してファイルを自動的にWORM状態にコミットすることができます。ログ情報のように増分的に書き込まれるデータを保持するには、_WORM追記可能ファイル_を使用できます。詳細については、link:commit-files-worm-state-manual-task.html#create-a-worm-appendable-file["ボリューム アペンド モードを使用した追記可能WORMファイルの作成"]を参照してください。

SnapLockでサポートされるデータ保護方法は、ほとんどのコンプライアンス要件に対応します。

* セカンダリストレージ上のスナップショットをWORM保護するために、SnapLock for SnapVault を使用できます。link:commit-snapshot-copies-worm-concept.html["スナップショットをWORMにコミットする"] を参照してください。
* SnapMirrorを使用して、災害復旧のためにWORMファイルを別の地理的な場所に複製できます。link:mirror-worm-files-task.html["WORMファイルのミラーリング"]を参照してください。


SnapLockは、ONTAPのライセンスベースの機能です。1つのライセンスで、SnapLockを、SEC Rule 17a-4(f)などの外部規制を満たす厳格なコンプライアンスモードと、デジタル資産の保護に関する社内規制を満たすより緩やかなエンタープライズモードで使用できます。SnapLockライセンスは、link:../system-admin/manage-licenses-concept.html#licenses-included-with-ontap-one["ONTAP One"]ソフトウェアスイートの一部です。

SnapLockは、すべてのAFFおよびFASシステム、さらにONTAP Selectでサポートされています。SnapLockはソフトウェアのみのソリューションではなく、ハードウェアとソフトウェアが統合されたソリューションです。この違いは、SEC 17a-4（f）のような統合されたハードウェアとソフトウェアのソリューションを要求する厳格なWORM規制にとって重要です。詳細については、link:https://www.sec.gov/rules/interp/34-47806.htm["SECによる電子記憶媒体の使用に関するブローカー・ディーラー向けガイダンス"^]を参照してください。



== SnapLockの機能

SnapLockの設定が完了したら、次のタスクを実行できます。

* link:commit-files-worm-state-manual-task.html["ファイルのWORM状態へのコミット"]
* link:commit-snapshot-copies-worm-concept.html["セカンダリ ストレージのWORMにSnapshotをコミットする"]
* link:mirror-worm-files-task.html["ディザスタ リカバリ用のWORMファイルのミラーリング"]
* link:hold-tamper-proof-files-indefinite-period-task.html["リーガル ホールドを使用した訴訟期間中のWORMファイルの保持"]
* link:delete-worm-files-concept.html["privileged delete機能を使用したWORMファイルの削除"]
* link:set-retention-period-task.html["ファイルの保持期間の設定"]
* link:move-snaplock-volume-concept.html["SnapLockボリュームの移動"]
* link:snapshot-lock-concept.html["ランサムウェア攻撃から保護するためにSnapshotをロックする"]
* link:create-audit-log-task.html["監査ログでの snapLock の使用を確認する"]
* link:snaplock-apis-reference.html["SnapLock APIの使用"]




== SnapLockのComplianceモードとEnterpriseモード

SnapLockのComplianceモードとEnterpriseモードの最も大きな違いは、WORMファイルの保護レベルです。

|===


| SnapLockモード | 保護レベル | 保持中のWORMファイルの削除 


 a| 
Complianceモード
 a| 
ディスク レベル
 a| 
削除できません



 a| 
Enterpriseモード
 a| 
ファイル レベル
 a| 
コンプライアンス管理者が監査済みの「特権削除」手順を使用して削除できる

|===
保持期間が経過したあとに不要となったファイルは手動で削除する必要があります。一度WORM状態にコミットされたファイルは、ComplianceモードかEnterpriseモードかに関係なく、保持期間が経過したあとも変更することはできません。

WORMファイルは保持期間中も保持期間後も移動できません。WORMファイルはコピーできますが、コピーしたファイルはWORM状態にはなりません。

次の表に、SnapLockのComplianceモードとEnterpriseモードでサポートされる機能の違いを示します。

|===


| 機能 | SnapLock Compliance | SnapLock Enterprise 


 a| 
privileged deleteを使用したファイルの有効化と削除
 a| 
いいえ
 a| 
はい



 a| 
ディスクの再初期化
 a| 
いいえ
 a| 
はい



 a| 
保持期間中のSnapLockアグリゲートとボリュームの破棄
 a| 
いいえ
 a| 
○（SnapLock監査ログ ボリュームを除く）



 a| 
アグリゲートまたはボリュームの名前変更
 a| 
いいえ
 a| 
はい



 a| 
NetApp以外のディスクの使用
 a| 
いいえ
 a| 
いいえ



 a| 
監査ログでのSnapLockボリュームの使用
 a| 
はい
 a| 
○（ONTAP 9.5以降）

|===


== SnapLockでサポートされる機能とされない機能

次の表は、SnapLock ComplianceモードとSnapLock Enterpriseモードでサポートされる機能を示しています。

|===


| 機能 | SnapLock Compliance に対応 | SnapLock Enterprise に対応 


 a| 
整合性グループ
 a| 
いいえ
 a| 
いいえ



 a| 
暗号化されたボリューム
 a| 
はい、xref:Encryption[暗号化とSnapLock]について詳しくご覧ください。
 a| 
はい、xref:Encryption[暗号化とSnapLock]について詳しくご覧ください。



 a| 
SnapLockアグリゲート上のFabricPool
 a| 
いいえ
 a| 
はい、ONTAP 9.8以降で可能です。xref:FabricPool on SnapLock Enterprise aggregates[SnapLock Enterpriseアグリゲート上のFabricPool]の詳細をご覧ください。



 a| 
Flash Poolアグリゲート
 a| 
○
 a| 
○



 a| 
FlexClone
 a| 
SnapLockボリュームはクローニングできますが、SnapLockボリュームのファイルはクローニングできません。
 a| 
SnapLockボリュームはクローニングできますが、SnapLockボリュームのファイルはクローニングできません。



 a| 
FlexGroupボリューム
 a| 
はい、ONTAP 9.11.1 以降で可能です。<<flexgroup>>の詳細をご覧ください。
 a| 
はい、ONTAP 9.11.1 以降で可能です。<<flexgroup>>の詳細をご覧ください。



 a| 
LUN
 a| 
いいえ。SnapLockを使用したxref:LUN support[LUNのサポート]の詳細については、こちらをご覧ください。
 a| 
いいえ。SnapLockを使用したxref:LUN support[LUNのサポート]の詳細については、こちらをご覧ください。



 a| 
MetroCluster構成
 a| 
はい、ONTAP 9.3以降で可能です。xref:MetroCluster support[MetroClusterのサポート]の詳細をご覧ください。
 a| 
はい、ONTAP 9.3以降で可能です。xref:MetroCluster support[MetroClusterのサポート]の詳細をご覧ください。



 a| 
マルチ管理者認証（MAV）
 a| 
はい、ONTAP 9.13.1 以降で可能です。xref:Multi-admin verification (MAV) support[MAVのサポート]の詳細をご覧ください。
 a| 
はい、ONTAP 9.13.1 以降で可能です。xref:Multi-admin verification (MAV) support[MAVのサポート]の詳細をご覧ください。



 a| 
SAN
 a| 
いいえ
 a| 
いいえ



 a| 
Single File SnapRestore
 a| 
いいえ
 a| 
はい



 a| 
SnapMirrorアクティブ同期
 a| 
いいえ
 a| 
いいえ



 a| 
SnapRestore
 a| 
いいえ
 a| 
はい



 a| 
SMTape
 a| 
いいえ
 a| 
いいえ



 a| 
SnapMirror Synchronous
 a| 
いいえ
 a| 
いいえ



 a| 
SSD
 a| 
○
 a| 
○



 a| 
Storage Efficiency機能
 a| 
はい、ONTAP 9.9.1以降で可能です。xref:Storage efficiency[ストレージ効率のサポート]の詳細をご覧ください。
 a| 
はい、ONTAP 9.9.1以降で可能です。xref:Storage efficiency[ストレージ効率のサポート]の詳細をご覧ください。

|===


== SnapLock Enterpriseアグリゲート上のFabricPool

ONTAP 9.8以降では、FabricPoolがSnapLock Enterpriseアグリゲートでサポートされます。ただし、アカウント チームがProduct Variance Requestを申請して、パブリック クラウドまたはプライベート クラウドに階層化されたFabricPoolのデータは、クラウド管理者が削除できるためSnapLockでは保護されないことを承諾する必要があります。

[NOTE]
====
FabricPoolでパブリック クラウドまたはプライベート クラウドに階層化されたデータはクラウド管理者が削除できるため、SnapLockでは保護されなくなりました。

====


== FlexGroupボリューム

ONTAP 9.11.1以降、SnapLockではFlexGroupボリュームがサポートされますが、次の機能はサポートされません。

* リーガル ホールド
* イベントベースの保持
* SnapLock for SnapVault（ONTAP 9.12.1以降でサポート）


また、次の点についても理解しておく必要があります。

* FlexGroupボリュームのボリューム コンプライアンス クロック（VCC）は、ルート コンスティチュエントのVCCによって決まります。すべての非ルート コンスティチュエントのVCCは、ルートのVCCと密接に同期されます。
* SnapLockの設定プロパティは、FlexGroup全体に対してのみ設定されます。個々のコンスティチュエントに、デフォルトの保持期限や自動コミット期間などの設定プロパティを指定することはできません。




== LUNのサポート

LUNは、非SnapLockボリューム上で作成されたスナップショットがSnapLock vaultリレーションシップの一部として保護のためにSnapLockボリュームに転送されるシナリオにおいてのみ、SnapLockボリュームでサポートされます。LUNは読み取り / 書き込みSnapLockボリュームではサポートされません。ただし、改ざん防止スナップショットは、LUNを含むSnapMirrorソースボリュームとデスティネーションボリュームの両方でサポートされます。



== MetroClusterのサポート

MetroCluster構成でのSnapLockのサポートは、SnapLock ComplianceモードとSnapLock Enterpriseモードで異なります。

.SnapLock Compliance
* ONTAP 9.3以降では、ミラーされていないMetroClusterアグリゲートでSnapLock Complianceがサポートされます。
* ONTAP 9.3以降、ミラーされたアグリゲートでは、SnapLock監査ログ ボリュームのホストとして使用する場合に限りSnapLock Complianceがサポートされます。
* MetroClusterを使用して、プライマリ サイトとセカンダリ サイトにSVM固有のSnapLock構成をレプリケートできます。


.SnapLock Enterprise
* SnapLock Enterprise アグリゲートがサポートされています。
* ONTAP 9.3以降では、privileged deleteを使用するSnapLock Enterpriseアグリゲートがサポートされます。
* MetroClusterを使用して、両方のサイトにSVM固有のSnapLock構成をレプリケートできます。


.MetroCluster構成とコンプライアンス クロック
MetroCluster構成では、Volume Compliance Clock（VCC;ボリューム コンプライアンス クロック）とSystem Compliance Clock（SCC;システム コンプライアンス クロック）の2つのコンプライアンス クロック メカニズムが使用されます。VCCとSCCはすべてのSnapLock構成で使用できます。ノードに新しいボリュームを作成すると、ボリュームのVCCはそのノードの現在のSCCの値に初期化されます。ボリューム作成後のボリュームとファイルの保持期限の追跡には、常にVCCが使用されます。

ボリュームを別のサイトにレプリケートすると、ボリュームのVCCも一緒にレプリケートされます。ボリュームのスイッチオーバー（サイトAからサイトB）が発生した場合、VCCの更新はサイトBで継続されますが、サイトAのSCCはサイトAがオフラインになると停止します。

サイトAがオンラインに戻ってボリュームのスイッチバックが実行されると、サイトAのSCCのクロックが再開されますが、ボリュームのVCCは引き続き更新されます。VCCは継続的に更新されるため、スイッチオーバーやスイッチバックの処理に関係なくファイルの保持期限はSCCに依存せず、期限が延びることはありません。



== マルチ管理者認証（MAV）のサポート

ONTAP 9.13.1以降、クラスタ管理者はクラスタ上でマルチ管理者検証を明示的に有効にすることで、一部のSnapLock操作を実行する前にクォーラム承認を必須にすることができます。MAVを有効にすると、SnapLockボリュームプロパティ（default-retention-time、minimum-retention-time、maximum-retention-time、volume-append-mode、autocommit-period、privileged-delete）でクォーラム承認が必要になります。link:../multi-admin-verify/index.html#how-multi-admin-verification-works["MAV"]の詳細をご覧ください。



== ストレージ効率

ONTAP 9.9.1 以降、SnapLock は、SnapLock ボリュームおよびアグリゲートに対して、データ圧縮、ボリューム間重複排除、アダプティブ圧縮などのストレージ効率化機能をサポートしています。ストレージ効率化の詳細については、link:../concepts/storage-efficiency-overview.html["ONTAP Storage Efficiencyの概要"] を参照してください。



== 暗号化

ONTAPは、ストレージ メディアの転用、返却、置き忘れ、盗難に際して保存データが読み取られることがないようにソフトウェア ベースとハードウェア ベースの暗号化テクノロジを提供します。

*免責事項：*NetAppは、認証キーを紛失した場合、または認証失敗回数が規定の制限を超え、ドライブが永久にロックされた場合、自己暗号化ドライブまたはボリューム上のSnapLock保護されたWORMファイルの復旧を保証することはできません。認証失敗に対する対策はお客様の責任となります。

[NOTE]
====
暗号化されたボリュームはSnapLockアグリゲートでサポートされます。

====


== 7-Modeからの移行

7-Mode Transition Toolのコピーベースの移行（CBT）機能を使用して、SnapLockボリュームを7-ModeからONTAPに移行できます。デスティネーション ボリュームのSnapLockモード（ComplianceまたはEnterprise）とソース ボリュームのSnapLockモードが一致している必要があります。コピーフリーの移行（CFT）はSnapLockボリュームの移行には使用できません。
