---
permalink: snaplock/snaplock-apis-reference.html 
sidebar: sidebar 
keywords: snaplock, api, zephyr, xml, scripts, workflow 
summary: Zephyr API を使用して、 SnapLock 機能をスクリプトやワークフローオートメーションと統合することができます。API は、 HTTP 、 HTTPS 、および Windows DCE / RPC を介した XML メッセージングを使用します。 
---
= SnapLock API
:icons: font
:imagesdir: ../media/


[role="lead"]
Zephyr API を使用して、 SnapLock 機能をスクリプトやワークフローオートメーションと統合することができます。API は、 HTTP 、 HTTPS 、および Windows DCE / RPC を介した XML メッセージングを使用します。



== file-fingerprint - 中止

ファイルフィンガープリント処理を中止します。



== file-fingerprint -dump を実行します

ファイルフィンガープリント情報を表示します。



== file-fingerprint -get-iter

ファイルフィンガープリント処理のステータスを表示します。



== file-fingerprint -start の算出

ファイルフィンガープリントを生成します。



== snaplock-archive-vserver-log

アクティブな監査ログファイルをアーカイブします。



== snaplock-create -vserver -log

SVM の監査ログ設定を作成します。



== snaplock-delete -vserver -log

SVM の監査ログ設定を削除します。



== snaplock-file-privileged-delete-delete

privileged delete 処理を実行します。



== snaplock-get-file-retention

ファイルの保持期間を取得します。



== snaplock-get-node-compliance-clock では

ノードの ComplianceClock の日付と時刻を取得します。



== snaplock-get-vserver -active-log-file-iter

アクティブなログファイルのステータスを表示します。



== snaplock-get-vserver -log-iter

監査ログ設定を表示します。



== snaplock-modify -vserver -log

SVM の監査ログ設定を変更します。



== snaplock-set-file-retention

ファイルの保持期限を設定します。



== snaplock-set-node-compliance-clock のいずれかです

ノードの ComplianceClock の日付と時刻を設定します。



== snaplock-volume-set-privileged-delete

SnapLock Enterprise ボリュームで privileged-delete オプションを設定します。



== volume-get-snaplock-attrs

SnapLock ボリュームの属性を取得します。



== volume-set-snaplock-attrs

SnapLock ボリュームの属性を設定します。
