---
permalink: nfs-trunking/client-mount-task.html 
sidebar: sidebar 
keywords: NFS, servers, network, NFS trunking, data shares, Linux, VMware, mounts 
summary: トランキングをサポートするLinuxおよびVMwareクライアントは、トランキングが有効になっているONTAP NFSサーバからボリュームまたはデータ共有をマウントできます。 
---
= NFSトランキング用にONTAPボリュームまたはデータ共有をマウント
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
トランキングをサポートするLinuxおよびVMwareクライアントは、トランキングが有効になっているONTAP NFSv4.1サーバからボリュームまたはデータ共有をマウントできます。

クライアントでmountコマンドを入力する場合は、トランキンググループ内の各LIFのIPアドレスを入力する必要があります。

詳細はこちらをご覧ください link:index.html#supported-clients["サポートされるクライアント"]。

[role="tabbed-block"]
====
.Linuxクライアントの要件
--
トランキンググループ内の接続ごとに、個別のマウントポイントが必要です。

次のようなコマンドを使用して、エクスポートしたボリュームをマウントします。

`mount lif1_ip:/vol-test /mnt/test1 -o vers=4.1,max_connect=16`

`mount lif2_ip:/vol-test /mnt/test2 -o vers=4.1,max_connect=16`

version(`vers`）の値は以降である必要があります `4.1`。

この `max_connect`値は、トランキンググループ内の接続数に対応します。

--
.VMwareクライアントの要件
--
トランキンググループ内の各接続のIPアドレスを含むMOUNTステートメントが必要です。

次のようなコマンドを使用して、エクスポートしたデータストアをマウントします。

`#esxcli storage nfs41 -H lif1_ip, lif2_ip -s /mnt/sh are1 -v nfs41share`

 `-H`値はトランキンググループ内の接続に対応しています。

--
====