---
permalink: nfs-trunking/create-exports-task.html 
sidebar: sidebar 
keywords: servers, network, NFS trunking, NIC, export policies, rule, Linux, VMware, datastores, client 
summary: データ共有へのクライアント アクセスを提供するには、ボリュームを1つ以上作成し、少なくとも1つのルールが設定されたエクスポート ポリシーをボリュームに設定する必要があります。 
---
= ONTAPボリュームエクスポートポリシーを作成する
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
データ共有へのクライアント アクセスを提供するには、ボリュームを1つ以上作成し、少なくとも1つのルールが設定されたエクスポート ポリシーをボリュームに設定する必要があります。

クライアントのエクスポート要件：

* Linuxクライアントでは、トランキング接続ごと（つまりLIFごと）に、それぞれ独立したマウントとマウント ポイントが必要です。
* VMwareクライアントでは、エクスポートされたボリュームに対して、複数のLIFが指定されたマウント ポイントが1つだけ必要です。
+
VMwareクライアントでは、エクスポート ポリシーにルート アクセスが必要です。



.手順
. エクスポート ポリシーを作成します。
+
`vserver export-policy create -vserver _svm_name_ -policyname _policy_name_`

+
ポリシー名に指定できる文字数は最大256文字です。

. エクスポート ポリシーが作成されたことを確認します。
+
`vserver export-policy show -policyname _policy_name_`

+
.例
次のコマンドは、vs1という名前のSVM上にexp1という名前のエクスポート ポリシーを作成し、その作成を確認します：

+
`vs1::> vserver export-policy create -vserver vs1 -policyname exp1`

. エクスポート ルールを作成して既存のエクスポート ポリシーに追加します。
+
`vserver export-policy rule create -vserver _svm_name_ -policyname _policy_name_ -ruleindex _integer_ -protocol nfs4 -clientmatch { _text | "text,text,…"_ } -rorule _security_type_ -rwrule _security_type_ -superuser _security_type_ -anon _user_ID_`

+
 `-clientmatch`パラメータは、エクスポートをマウントするトランキング対応のLinuxまたはVMwareクライアントを識別する必要があります。

+
link:../nfs-config/add-rule-export-policy-task.html["エクスポートルールを作成します。"]の詳細

. ジャンクション ポイントを設定してボリュームを作成します。
+
`volume create -vserver _svm_name_ -volume _volume_name_ -aggregate _aggregate_name_-size {integer[KB|MB|GB|TB|PB]} -security-style unix -user _user_name_or_number_ -group _group_name_or_number_ -junction-path _junction_path_ -policy _export_policy_name_`

+
link:../nfs-config/create-volume-task.html["ボリュームを作成します。"]について学ぶ

. 目的のジャンクション ポイントでボリュームが作成されたことを確認します。
+
`volume show -vserver _svm_name_ -volume _volume_name_ -junction-path`


