---
permalink: nfs-trunking/index.html 
sidebar: sidebar 
keywords: NFSv4.1, trunking, Linux, VMware, FlexGroup, volumes, multipathing, AI/ML, rdma, data lake 
summary: ONTAP 9.14.1以降では、v4.1以降を実行するNFSクライアントでセッショントランキング機能を利用してNFSサーバへの複数の接続を開くことができます。これにより、データ転送速度が向上し、マルチパスによる耐障害性が実現します。 
---
= NFSトランキングの概要
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
ONTAP 9.14.1以降では、セッショントランキングを利用してNFSサーバ上の異なるLIFへの複数の接続を開くことができるため、データ転送速度が向上し、マルチパスによる耐障害性が実現します。

トランキングは、FlexVolボリュームをトランキング対応のクライアント（特にVMwareおよびLinuxクライアント）にエクスポートする場合や、NFS over RDMA、TCP、pNFSにエクスポートする場合に便利です。

ONTAP 9.14.1では、トランキングは1つのノードのLIFに制限されます。トランキングは複数のノードにまたがるLIFにはできません。

FlexGroupボリュームはトランキングでサポートされています。これによりパフォーマンスは向上しますが、FlexGroupボリュームへのマルチパスアクセスはシングルノードでしか設定できません。

このリリースのマルチパスでは、セッショントランキングのみがサポートされます。



== トランキングの使用方法

トランキングによるマルチパスのメリットを活用するには、トランキング対応NFSサーバがあるSVMに関連付けられた一連のLIF（_trunking group_と呼ばれます）が必要です。トランキンググループ内のLIFは、クラスタの同じノードにホームポートがあり、それらのホームポートに配置されている必要があります。トランキンググループ内のすべてのLIFが同じフェイルオーバーグループのメンバーであることを推奨します。

ONTAPでは、1つのクライアントからノードあたり最大16のトランク接続がサポートされます。

クライアントがトランキング対応サーバからエクスポートをマウントする場合、クライアントはトランキンググループ内のLIFのIPアドレスの数を指定します。クライアントが最初のLIFに接続したあとに追加されたLIFは、NFSv4.1セッションに追加され、トランキンググループの要件を満たしている場合にのみトランキングに使用されます。クライアントは、独自のアルゴリズム（ラウンドロビンなど）に基づいて、複数の接続にNFS処理を分散します。

最大のパフォーマンスを得るには、シングルパスエクスポートではなく、マルチパスエクスポート専用のSVMでトランキングを設定します。つまり、トランキングが有効なクライアントのみにエクスポートが提供されているSVM内のNFSサーバでのみトランキングを有効にします。



== サポートされるクライアント

ONTAP NFSv4.1サーバは、NFSv4.1セッショントランキングに対応したすべてのクライアントとのトランキングをサポートしています。

次のクライアントは、ONTAP 9.14.1でテスト済みです。

* VMware-ESXi 7.0U3F以降
* Linux - Red Hat Enterprise Linux（RHEL）8.8および9.3



NOTE: NFSサーバでトランキングが有効になっている場合、トランキングをサポートしていないNFSクライアントでエクスポートされた共有にアクセスすると、パフォーマンスが低下することがあります。これは、SVMデータLIFへの複数のマウントに使用されるTCP接続が1つだけであるためです。



== NFSトランキングとnconnectの違い

ONTAP 9.8 以降では、 NFSv4.1 が有効になっている場合、 nconnect 機能がデフォルトで使用できます。nconnect対応クライアントでは、1つのNFSマウントで、1つのLIFを介して複数のTCP接続（最大16）を確立できます。

一方、トランキングは_multipathing_functionalityで、複数のLIFを介して複数のTCP接続を提供します。環境に追加のNICを使用できる場合は、トランキングによってnconnectの機能を超えた並列処理とパフォーマンスが向上します。

の詳細を確認してください link:../nfs-admin/ontap-support-nfsv41-concept.html["nconnect："]
