---
permalink: nfs-trunking/update-network-task.html 
sidebar: sidebar 
keywords: NFS, servers, network, prepare, NFS trunking, LIF, trunking group, NIC 
summary: NFSトランキングを利用するには、トランク接続ごとに複数のNICに複数のLIFを配置する必要があります。 
---
= ONTAP NFSトランキング用のネットワークの更新
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
NFSv4.1トランキングを利用するには、トランキンググループ内のLIFが同じノードに配置され、同じノードにホームポートがある必要があります。LIFは、同じノードのフェイルオーバーグループに設定する必要があります。

.タスクの内容
LIFとNICを1対1でマッピングするとパフォーマンスが最大限に向上しますが、トランキングを有効にする必要はありません。少なくとも2つのNICをインストールするとパフォーマンスが向上しますが、必須ではありません。

トランキンググループ内のLIFはすべて同じフェイルオーバーグループに属している必要があります。同じノードのフェイルオーバーグループにLIFが設定されている場合、そのノードでコントローラのフェイルオーバーが発生するとLIFがオフラインになることがあります。同じノードのフェイルオーバーグループにLIFが設定されておらず、別のノードにフェイルオーバーされると、トランキングは機能しなくなります。

フェイルオーバーグループの接続（および基盤となるNIC）を追加または削除するときは、常にトランキングフェイルオーバーグループを調整する必要があります。

.開始する前に
* フェイルオーバーグループを作成するには、NICに関連付けられているポート名を確認しておく必要があります。
* すべてのポートが同じノード上にある必要があります。


.手順
. 使用するネットワークポートの名前とステータスを確認します。
+
`network port show`

. トランキングフェイルオーバーグループを作成するか、既存のフェイルオーバーグループを変更します。
+
`network interface failover-groups create -vserver <svm_name> -failover-group <failover_group_name> -targets <ports_list>`

+
`network interface failover-groups modify -vserver <svm_name> -failover-group <failover_group_name> -targets <ports_list>`

+

NOTE: フェイルオーバーグループは必須ではありませんが、使用することを強く推奨します。

+
** `<svm_name>`は、NFSサーバが含まれているSVMの名前です。
** `<ports_list>`は、フェイルオーバーグループに追加するポートのリストです。
+
ポートはの形式で追加され `<node_name>:<port_number>`ます（例：） `node1:e0c`。

+
次のコマンドは、SVM vs1のフェイルオーバーグループを作成し `fg3`てポートを3つ追加します。

+
`network interface failover-groups create -vserver vs1 -failover-group fg3 -targets cluster1-01:e0c,cluster1-01:e0d,cluster1-01:e0e`

+
詳細はこちらlink:../networking/configure_failover_groups_and_policies_for_lifs_overview.html["フェイルオーバーグループ："]



. 必要に応じて、トランキンググループのメンバー用に追加のLIFを作成します。
+
`network interface create -vserver <svm_name> -lif <lif_name> -home-node <node_name> -home-port <port_name> -address <IP_address> -netmask <IP_address> [-service-policy <policy>] [-auto-revert <true|false>]`

+
** `-home-node`- network interface revertコマンドをLIFで実行したときにLIFが戻るノード。
+
オプションを使用すると、LIFをホームノードおよびホームポートに自動的にリバートするかどうかを指定できます `-auto-revert`。

** `-home-port`は、network interface revertコマンドをLIFに対して実行したときにLIFが戻る物理ポートまたは論理ポートです。
** オプションと `-netmask`オプションでIPアドレスを指定できます `-address`。
** IPアドレスを手動で（サブネットを使用せずに）割り当てるときに、クライアントまたはドメインコントローラが別のIPサブネットにある場合は、ゲートウェイへのデフォルトルートの設定が必要になることがあります。SVM内の静的ルートの作成について `network route create`は、コマンドページを参照してください。の詳細については `network route create`、をlink:https://docs.netapp.com/us-en/ontap-cli/network-route-create.html["ONTAPコマンド リファレンス"^]参照してください。
** `-service-policy`- LIFのサービスポリシー。ポリシーを指定しない場合は、デフォルトポリシーが自動的に割り当てられます。コマンドを使用し `network interface service-policy show`て、使用可能なサービスポリシーを確認します。
** `-auto-revert`-起動時、管理データベースのステータスが変わったとき、ネットワーク接続が確立されたときなどの状況で、データLIFがホームノードに自動的にリバートされるかどうかを指定します。*デフォルト設定はfalse *ですが、環境内のネットワーク管理ポリシーに応じてtrueに設定できます。
+
トランキンググループに追加するLIFごとに、この手順を繰り返します。

+
次のコマンドは、ノードの `cluster1_01`ポートに `e0c`SVM用 `vs1`にを作成し `lif-A`ます。

+
`network interface create -vserver vs1 -lif lif-A -service-policy default-intercluster -home-node cluster1_01 -home-port e0c -address 192.0.2.0`

+
詳細はこちらlink:../networking/create_lifs.html["LIFの作成"]



. LIFが作成されたことを確認します。
+
[source, cli]
----
network interface show
----
. 設定したIPアドレスに到達できることを確認します。
+
[cols="25,75"]
|===
| 対象 | 使用方法 


| IPv4アドレス | `network ping` 


| IPv6アドレス | `network ping6` 
|===


の詳細については `network interface`、をlink:https://docs.netapp.com/us-en/ontap-cli/search.html?q=network+interface["ONTAPコマンド リファレンス"^]参照してください。
