---
permalink: cloud/manage-ontap-concept.html 
sidebar: sidebar 
keywords: manage, ontap, cloud 
summary: 自社データセンターとクラウドのどちらで ONTAP を使用している場合でも、同じインターフェイスを使用してストレージを管理できます。つまり、クラウドで ONTAP を管理する方法をすでに知っているということです。また、 Cloud Volumes ONTAP の導入や使用の簡単なグラフィカルインターフェイスとして、最新の使いやすい GUI も用意されています。Cloud Volumes ONTAP または Cloud Volumes Service の高度な管理が必要になる場合があります。これには、 ONTAP System Manager 、コマンドラインインターフェイス（ CLI ）、または REST API を使用できます。 
---
= クラウドで ONTAP を管理
:icons: font
:imagesdir: ../media/


[role="lead"]
自社データセンターとクラウドのどちらで ONTAP を使用している場合でも、同じインターフェイスを使用してストレージを管理できます。つまり、クラウドで ONTAP を管理する方法をすでに知っているということです。また、 Cloud Volumes ONTAP の導入や使用の簡単なグラフィカルインターフェイスとして、最新の使いやすい GUI も用意されています。Cloud Volumes ONTAP または Cloud Volumes Service の高度な管理が必要になる場合があります。これには、 ONTAP System Manager 、コマンドラインインターフェイス（ CLI ）、または REST API を使用できます。

* ONTAP システム・マネージャ * は Cloud Volumes ONTAP または Cloud Volumes Service システム上で実行されるため、管理タスクを実行できます。

* ONTAP CLI* を使用すると、すべての管理コマンドを実行できます。高度なタスクを実行する場合や、 CLI を使い慣れている場合は、 CLI の使用を推奨します。CLI には Secure Shell （ SSH ）を使用して接続します。

* ONTAP REST API * を使用すると、 Cloud Volume の作成と管理、およびプロビジョニングスクリプトとツールの開発が可能になります。Web ユーザインターフェイスから使用できる ONTAP 機能は、 REST API からも使用できます。状況によっては、このプログラムによるインターフェイスが役立つ場合もあります。特に開発者は、 Cloud Manager の処理に関連するプロセスを自動化できるため便利です。

* 関連情報 *

https://docs.netapp.com/us-en/occm/task_connecting_to_otc.html#connecting-to-oncommand-system-manager["Cloud Volumes ONTAP に接続しています"]

https://cloud.netapp.com/blog/cloud-automation-with-cloud-volumes-ontap-rest["Cloud Volumes ONTAP と REST によるクラウド自動化"]

https://docs.netapp.com/us-en/occm/api.html["Cloud Manager REST API"]
