---
permalink: flexcache/add-license-task.html 
sidebar: sidebar 
keywords: add, flexcache, license, flex cache, volume, limit, capacity, term 
summary: ONTAP 9.6 以前を実行している場合は、 System Manager を使用して、容量ベースおよび期間ベースのライセンスである FlexCache ライセンスをインストールする必要があります。 
---
= FlexCache ライセンスを追加する
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
ONTAP 9.6 以前を実行している場合は、 System Manager を使用して、容量ベースおよび期間ベースのライセンスである FlexCache ライセンスをインストールする必要があります。

.このタスクについて
FlexCache ライセンスはクラスタ規模のライセンスです。このライセンスには、クラスタ内で FlexCache ボリュームを使用するために購入した使用量の制限が設定されています。クラスタ全体での FlexCache ボリュームのスペース使用量がこの制限容量を超えないようにする必要があります。ライセンスの使用量の制限を増やす必要がある場合は、営業担当者にお問い合わせください。

ONTAP 9.7以降では、FlexCache機能がONTAPに組み込まれており、ライセンスやアクティブ化は不要になりました。 

.手順
. NetApp Support Siteから FlexCache ライセンスのネットアップライセンスファイルをダウンロードします。
+
https://mysupport.netapp.com/site/global/dashboard["ネットアップサポート"]

. System Manager を使用して、 FlexCache ライセンスをクラスタにアップロードします。
+
.. [ * 構成 * （ Configurations * ） ] > [ * クラスタ * （ * Cluster * ） ] > [ * ライセンス * （ * Licenses * ） ]
.. [ * パッケージ * ] ウィンドウで、 [ * 追加 ] をクリックします。
.. [ * ライセンスパッケージの追加 * ] ダイアログボックスで、 [ * ファイルの選択 * ] をクリックしてダウンロードしたネットアップライセンスファイルを選択し、 [ * 追加 ] をクリックしてファイルをクラスタにアップロードします。



