---
permalink: flexcache/audit-flexcache-volumes-concept.html 
sidebar: sidebar 
keywords: considerations, auditing, flexcache, volumes 
summary: ONTAP 9.7 以降では、 FPolicy でのネイティブの ONTAP 監査とファイルポリシー管理を使用して、 FlexCache 関係の NFS ファイルアクセスイベントを監査できます。CIFS を使用する FlexCache では、 FPolicy はサポートされません。標準の監査と FPolicy は、 FlexVol ボリュームと同じ CLI コマンドで設定および管理されます。ただし、 FlexCache ボリュームにはいくつかの動作があります。 
---
= FlexCache ボリュームの監査に関する考慮事項
:icons: font
:imagesdir: ../media/


[role="lead"]
ONTAP 9.7 以降では、 FPolicy でのネイティブの ONTAP 監査とファイルポリシー管理を使用して、 FlexCache 関係の NFS ファイルアクセスイベントを監査できます。CIFS を使用する FlexCache では、 FPolicy はサポートされません。標準の監査と FPolicy は、 FlexVol ボリュームと同じ CLI コマンドで設定および管理されます。ただし、 FlexCache ボリュームにはいくつかの動作があります。

* * ネイティブ監査 *
+
** FlexCache ボリュームを監査ログのデスティネーションとして使用することはできません。
** FlexCache に対する読み取りと書き込みを監査する場合は、キャッシュ SVM と元の SVM の両方で監査を設定する必要があります。
+
これは、ファイルシステム操作が処理される場所で監査されるためです。つまり、読み取りはキャッシュ SVM で監査され、書き込みは元の SVM で監査されます。

** 書き込み処理の元を追跡するために、 SVM UUID と MSID が監査ログに追加され、書き込みが開始された FlexCache ボリュームが識別されます。
** システムアクセス制御リスト（ SACL ）は NFSv4 または SMB プロトコルを使用してファイルに設定できますが、 FlexCache ボリュームでは NFSv3 のみがサポートされます。そのため、 SACL を設定できるのは元のボリュームのみです。


* * FPolicy *
+
** FlexCache ボリュームへの書き込みは元のボリュームでコミットされますが、 FPolicy 設定はキャッシュボリュームへの書き込みを監視します。これは、元のボリュームに対する書き込みが監査される標準の監査とは異なります。
** キャッシュと送信元の SVM で ONTAP を同じ FPolicy 設定する必要はありませんが、 2 つの同様の設定を導入することを推奨します。そのためには、元の SVM のように設定され、新しいポリシーのスコープがキャッシュ SVM に制限されているキャッシュ用の新しい FPolicy ポリシーを作成します。



