---
permalink: flexcache/enable-file-access-time-updates-task.html 
sidebar: sidebar 
keywords: atime, atime-update, flexcache, flex cache, access time 
summary: 'FlexCache ボリュームで「-atime-update」フィールドを有効にして、ファイルアクセス時間の更新を許可することができます。アクセス時間の更新期間は"-atime-update-period"属性を使用して設定することもできますatime更新期間は、atime更新を実行する頻度と、元のボリュームに更新を伝播できるタイミングを制御します。' 
---
= ファイルアクセス時間の更新を有効にします
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
ONTAP 9.11.1以降では、FlexCache ボリュームの「-atime-update」フィールドを有効にして、ファイルアクセス時間の更新を許可できます。アクセス時間の更新期間は'-atime-update-period'属性を使用して設定することもできます「-atime-update-period」属性は、アクセス時間の更新を実行する頻度と、その更新を元のボリュームに伝播できるタイミングを制御します。



== 概要

ONTAP には'-atime-update'というボリューム・レベルのフィールドがあり'読み取り'readlink'READDIRを使用して読み込まれたファイルとディレクトリのアクセス・タイム更新を管理できますアクセス頻度の低いファイルとディレクトリのデータライフサイクルの決定にはatimeが使用されます。アクセス頻度の低いファイルは最終的にアーカイブストレージに移行され、あとでテープに移動されることもあります。

atime更新フィールドは、既存および新規に作成されたFlexCache ボリュームではデフォルトで無効になります。9.11.1よりも前のONTAP リリースでFlexCache ボリュームを使用している場合は、atime更新フィールドを無効にして、元のボリュームで読み取り処理が実行されるときにキャッシュが不要に削除されないようにする必要があります。ただし、大規模なFlexCache キャッシュでは、管理者が特別なツールを使用してデータを管理し、ホットデータがキャッシュに残ってコールドデータがパージされるのを確保します。atime更新を無効にする場合は実行できません。ただし、ONTAP 9.11.1以降では、「-atime-update」と「-atime-update-period」をイネーブルにし、キャッシュされたデータの管理に必要なツールを使用できます。



== 作業を開始する前に

すべてのFlexCache でONTAP 9.11.1以降が実行されている必要があります。



== このタスクについて

「-atime-update-period」を86400秒に設定すると、ファイル上で実行される読み取りと同様の操作の数に関係なく、24時間ごとに1回のアクセス時間更新を行うことはできません。

「-atime-update-period」を0に設定すると、各読み取りアクセスの送信元にメッセージが送信されます。その後、元のFlexCache は各に、パフォーマンスに影響するatimeが古いことを通知します。

.手順
. ファイルアクセス時間の更新を有効にし、更新頻度を設定します。
+
volume modify -volume vol_name -vserver_svm_name_-atime-update true -atime-update-period_seconds_`

+
次の例では、「-atime-update」をイネーブルにし、「-atime-update-period」を86400秒または24時間に設定します。

+
[listing]
----
c1: volume modify -volume origin1 vs1_c1 -atime-update true -atime-update-period 86400
----
. 「-atime-update」が有効になっていることを確認します。
+
volume show -volume _vol_name --fields atime-update、atime-update-period

+
[listing]
----
c1::*> volume show -volume cache1_origin1 -fields atime-update,atime-update-period
vserver volume         atime-update atime-update-period
------- -------------- ------------ -------------------
vs2_c1  cache1_origin1 true         86400
----

