---
permalink: flexcache/enable-file-access-time-updates-task.html 
sidebar: sidebar 
keywords: atime, atime-update, flexcache, flex cache, access time 
summary: 'を有効にすることができます `-atime-update` ファイルアクセス時間の更新を許可するFlexCache ボリュームのフィールド。でアクセス時間の更新期間を設定することもできます `-atime-update-period` 属性（Attribute）：atime更新期間は、atime更新を実行する頻度と、元のボリュームに更新を伝播できるタイミングを制御します。' 
---
= ファイルアクセス時間の更新を有効にします
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
ONTAP 9.11.1以降では、を有効にすることができます `-atime-update` ファイルアクセス時間の更新を許可するFlexCache ボリュームのフィールド。でアクセス時間の更新期間を設定することもできます `-atime-update-period` 属性（Attribute）：。 `-atime-update-period` 属性は、アクセス時間の更新を実行する頻度と、更新がいつ元のボリュームに反映されるかを制御します。



== 概要

ONTAP には、というボリュームレベルのフィールドがあります `-atime-update`READ、READLINK、READDIRを使用して読み取られたファイルおよびディレクトリのアクセス時間の更新を管理します。アクセス頻度の低いファイルとディレクトリのデータライフサイクルの決定にはatimeが使用されます。アクセス頻度の低いファイルは最終的にアーカイブストレージに移行され、あとでテープに移動されることもあります。

atime更新フィールドは、既存および新規に作成されたFlexCache ボリュームではデフォルトで無効になります。9.11.1よりも前のONTAP リリースでFlexCache ボリュームを使用している場合は、atime更新フィールドを無効にして、元のボリュームで読み取り処理が実行されるときにキャッシュが不要に削除されないようにする必要があります。ただし、大規模なFlexCache キャッシュでは、管理者が特別なツールを使用してデータを管理し、ホットデータがキャッシュに残ってコールドデータがパージされるのを確保します。atime更新を無効にする場合は実行できません。ただし、ONTAP 9.11.1以降では、を有効にすることができます `-atime-update` および `-atime-update-period,` キャッシュされたデータの管理に必要なツールを使用します。



== 作業を開始する前に

すべてのFlexCache でONTAP 9.11.1以降が実行されている必要があります。



== このタスクについて

設定 `-atime-update-period` 86400秒に設定すると、ファイルに対して実行された読み取りに類似した操作の数に関係なく、24時間ごとに1回のアクセス時間更新が許可されます。

を設定します `-atime-update-period` 0にすると、読み取りアクセスごとにメッセージが送信元に送信されます。その後、元のFlexCache は各に、パフォーマンスに影響するatimeが古いことを通知します。

.手順
. ファイルアクセス時間の更新を有効にし、更新頻度を設定します。
+
`volume modify -volume vol_name -vserver _SVM_name_ -atime-update true -atime-update-period _seconds_`

+
次に、を有効にする例を示します `-atime-update` とセット `-atime-update-period` 86400秒（24時間）まで：

+
[listing]
----
c1: volume modify -volume origin1 vs1_c1 -atime-update true -atime-update-period 86400
----
. 確認します `-atime-update` 有効：
+
`volume show -volume _vol_name_ -fields atime-update,atime-update-period`

+
[listing]
----
c1::*> volume show -volume cache1_origin1 -fields atime-update,atime-update-period
vserver volume         atime-update atime-update-period
------- -------------- ------------ -------------------
vs2_c1  cache1_origin1 true         86400
----

