---
permalink: flexcache/global-file-locking-task.html 
sidebar: sidebar 
keywords: global file locking, flexcache, relationship 
summary: 可用性よりも一貫性を優先したい場合は、FlexCacheボリューム上でグローバル ファイル ロックを有効にすることができます。 
---
= ONTAP FlexCacheボリュームでグローバルファイルロックを有効にする
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
ONTAP 9.10.1以降では、グローバル ファイル ロックを適用して、関連するすべてのキャッシュ ファイルの読み取りを防止できます。

グローバル ファイル ロックが有効な場合、すべてのFlexCacheボリュームがオンラインになるまで元のボリュームに対する変更は保留になります。FlexCacheボリュームがオフラインの場合は変更が保留になってタイムアウトする可能性があるため、グローバル ファイル ロックを有効にするのは、キャッシュと元のボリュームの間の接続の信頼性が確立されている場合だけにしてください。

.開始する前に
* グローバル ファイル ロックを使用するには、元のボリュームとすべての関連するキャッシュを含むクラスタでONTAP 9.9.1以降が実行されている必要があります。グローバル ファイル ロックは、新規または既存のFlexCacheボリュームに対して有効にできます。いずれかのボリュームでコマンドを実行すると、関連付けられているすべてのFlexCacheボリュームに適用されます。
* グローバル ファイル ロックを有効にするにはadvanced権限レベルが必要です。
* ONTAP 9.9.1より前のバージョンにリバートする場合は、まず元のボリュームと関連キャッシュでグローバルファイルロックを無効にする必要があります。無効にするには、元のボリュームから次のコマンドを実行します： `volume flexcache prepare-to-downgrade -disable-feature-set 9.10.0`
* グローバル ファイル ロックを有効にするプロセスは、元のボリュームに既存のキャッシュがあるかどうかによって異なります。
+
** <<enable-gfl-new>>
** <<enable-gfl-existing>>






== 新しいFlexCacheボリュームに対するグローバル ファイル ロックの有効化

.手順
.  `-is-global-file-locking`true に設定してFlexCacheボリュームを作成します：
+
`volume flexcache create volume _volume_name_ -is-global-file-locking-enabled true`

+

NOTE:  `-is-global-file-locking`のデフォルト値は「`false`」です。ボリューム上で後続の `volume flexcache create`コマンドを実行する場合は、必ず `-is-global-file-locking enabled`を「`true`」に設定して渡す必要があります。





== 既存のFlexCacheボリュームに対するグローバル ファイル ロックの有効化

.手順
. グローバル ファイル ロックは元のボリュームから設定する必要があります。
. 元のボリュームに他の既存の関係（SnapMirrorなど）があってはなりません。既存の関係がある場合は関連付けを解除する必要があります。コマンドの実行時に、すべてのキャッシュとボリュームが接続されている必要があります。接続ステータスを確認するには、次のコマンドを実行します。
+
`volume flexcache connection-status show`

+
リストされているすべてのボリュームのステータスは `connected.`と表示されます。詳細については、link:view-connection-status-origin-task.html["FlexCache関係のステータスを表示する"]またはlink:synchronize-properties-origin-volume-task.html["元のFlexCacheボリュームのプロパティを同期する"]を参照してください。

. キャッシュに対してグローバル ファイル ロックを有効にします。
+
`volume flexcache origin config show/modify -volume _volume_name_ -is-global-file-locking-enabled true`



.関連情報
* link:https://docs.netapp.com/us-en/ontap-cli/["ONTAPコマンド リファレンス"^]

