---
permalink: volumes/change-existing-quota-limits-task.html 
sidebar: sidebar 
keywords: modify, resize, quota limits 
summary: 既存のクォータのサイズを変更する場合、影響を受けるすべてのボリューム上のクォータのサイズを変更できます。この処理は、これらのボリューム上のクォータを再初期化するよりも高速です。 
---
= クォータ制限を変更（サイズ変更）します
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
既存のクォータのサイズを変更する場合、影響を受けるすべてのボリューム上のクォータのサイズを変更できます。この処理は、これらのボリューム上のクォータを再初期化するよりも高速です。

.このタスクについて
クォータが適用されている Storage Virtual Machine （ SVM 、旧 Vserver ）で、既存のクォータのサイズ制限を変更するか、すでに派生クォータが存在するターゲットに対してクォータを追加または削除します。

.手順
. を使用します `vserver show` コマンドにを指定します `-instance` SVMに現在割り当てられているポリシーの名前を確認するためのパラメータ。
. 次のいずれかの操作を実行してクォータルールを変更します。
+
** を使用します `volume quota policy rule modify` コマンドを使用して、既存のクォータルールのディスク制限またはファイル制限を変更します。
** を使用します `volume quota policy rule create` コマンドを使用して、現在派生クォータが存在するターゲット（ユーザ、グループ、またはqtree）に対する明示的クォータルールを作成します。
** を使用します `volume quota policy rule delete` コマンドを使用して、デフォルトクォータを持つターゲット（ユーザ、グループ、またはqtree）に対する明示的クォータルールを削除します。


. を使用します `volume quota policy rule show` コマンドを使用して、クォータルールが正しく設定されていることを確認します。
. を使用します `volume quota resize` クォータを変更した各ボリュームでコマンドを実行し、各ボリュームで変更をアクティブ化します。
+
サイズ変更プロセスは、次のいずれかの方法で監視できます。

+
** を使用する場合 `volume quota resize` コマンドを使用すると、を追加できます `-foreground` フォアグラウンドでサイズ変更ジョブを実行するためのパラメータ。（デフォルトでは、このジョブはバックグラウンドで実行されます）。
+
バックグラウンドでジョブが実行されると、を使用して進捗状況を監視できます `job show` コマンドを実行します

** を使用できます `volume quota show` コマンドを使用してサイズ変更ステータスを監視します。


. を使用します `volume quota show -instance` コマンドを使用して、サイズ変更に失敗したクォータルールなどのサイズ変更エラーを確認します。
+
特に ' 派生クォータがまだ存在しないターゲットの明示的クォータを追加した後でクォータのサイズを変更すると発生する "new definition" エラーをチェックします

. を使用します `volume quota report` クォータレポートを表示して、適用クォータが要件を満たしていることを確認するコマンド。

