---
permalink: volumes/change-maximum-number-files-allowed-concept.html 
sidebar: sidebar 
keywords: considerations, changing, maximum number of files, allowed, flexvol volume, maximum, files, file 
summary: FlexVolには、格納できるファイルの最大数があります。この最大値は変更できますが、この値がボリュームに与える影響に注意してください。 
---
= ONTAPのFlexVolボリュームに許可される最大ファイル数
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
FlexVolには、格納できるファイルの最大数があります。この最大値は変更できますが、変更する前に、この変更がボリュームに与える影響を理解しておく必要があります。

データに大量のファイルや大容量のディレクトリが必要な場合は、ONTAPファイルまたはディレクトリの容量を拡張できます。ただし、これらの容量を拡張する前に、制限事項と注意事項を理解しておく必要があります。

ボリュームに収容できるファイルの数は、ボリューム内のinodeの数によって決まります。a_inode_は ' ファイルに関する情報を含むデータ構造ですボリュームには、プライベートinodeとパブリックinodeの両方があります。パブリックinodeは、ユーザに表示されるファイルに使用されます。プライベートinodeは、ONTAPによって内部的に使用されるファイルに使用されます。変更できるのは、ボリュームのパブリックinodeの最大数だけです。プライベートinodeの数は変更できません。

ONTAP は、ボリュームサイズに基づいて、新しく作成するボリュームのパブリック inode の最大数をボリュームサイズ 32KB あたり 1 個の inode に自動的に設定します。管理者によって直接、またはONTAPのオートサイズ機能を通じてボリュームのサイズが拡張された場合、ボリュームサイズが約680GBに達するまでは、32KBあたり少なくとも1個のinodeという基準で必要に応じてパブリックinodeの最大数もONTAPによって拡張されます。

ONTAP 9.13.1より前のバージョンでは、ボリュームのサイズを680GBよりも大きくしても、ONTAPでは21、251、126個を超えるinodeは自動的に作成されないため、inodeは増えません。ボリュームサイズに関係なく、デフォルトよりも多くのファイルが必要な場合は、volume modifyコマンドを使用して、ボリュームのinodeの最大数を増やすことができます。

ONTAP 9.13.1以降では、ボリュームが680GBを超えていても、ボリュームスペース32KBあたりinodeは1つになるため、inodeの最大数は引き続き増加します。この増加は、ボリュームがinodeの最大値である2、040、109、451に達するまで続きます。

パブリックinodeの最大数を減らすこともできます。パブリックinodeの数を減らすと、inodeに割り当てられるスペースの量は変化しますが、パブリックinodeファイルが消費できるスペースの最大量は減少します。inode用に割り当てられたスペースがボリュームに戻されることはありません。したがって、inodeの最大数を現在割り当てられているinodeの数より少なくしても、割り当てられているinodeで使用されているスペースは返されません。

.詳細情報
* xref:display-file-inode-usage-task.html[ボリュームのファイルとinodeの使用量を確認する]

