---
permalink: volumes/commands-manage-quota-rules-policies-reference.html 
sidebar: sidebar 
keywords: commands to, manage, quota rules, quota policies, command, commands, quota, quotas, policy, policies 
summary: ' `volume quota policy rule`コマンドを使用するとクォータ ルールを設定でき、 `volume quota policy`コマンドと一部の `vserver`コマンドを使用するとクォータ ポリシーを設定できます。' 
---
= クォータ ルールとクォータ ポリシーを管理するためのコマンド
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
 `volume quota policy rule`コマンドを使用するとクォータルールを設定でき、 `volume quota policy`コマンドと一部の `vserver`コマンドを使用するとクォータポリシーを設定できます。必要な操作に応じて、以下のコマンドを使用してクォータルールとクォータポリシーを管理してください：


NOTE: 次のコマンドは、FlexVolに対してのみ実行できます。



== クォータ ルールの管理用コマンド

[cols="2*"]
|===
| 状況 | 使用するコマンド 


 a| 
新しいクォータルールを作成する
 a| 
`volume quota policy rule create`



 a| 
既存のクォータルールを削除する
 a| 
`volume quota policy rule delete`



 a| 
既存のクォータルールを変更する
 a| 
`volume quota policy rule modify`



 a| 
設定されたクォータ ルールに関する情報を表示する
 a| 
`volume quota policy rule show`

|===


== クォータ ポリシーの管理用コマンド

[cols="2*"]
|===
| 状況 | 使用するコマンド 


 a| 
クォータ ポリシーとそのクォータ ポリシーに含まれるクォータ ルールを複製する
 a| 
`volume quota policy copy`



 a| 
新しい空のクォータ ポリシーを作成する
 a| 
`volume quota policy create`



 a| 
現在Storage Virtual Machine（SVM）に割り当てられていない既存のクォータ ポリシーを削除する
 a| 
`volume quota policy delete`



 a| 
クォータ ポリシーの名前を変更する
 a| 
`volume quota policy rename`



 a| 
クォータ ポリシーに関する情報を表示する
 a| 
`volume quota policy show`



 a| 
クォータ ポリシーをSVMに割り当てる
 a| 
`vserver modify -quota-policy _policy_name_`



 a| 
SVMに割り当てられているクォータ ポリシーの名前を表示する
 a| 
`vserver show`

|===
この手順で説明されているコマンドの詳細については、link:https://docs.netapp.com/us-en/ontap-cli/["ONTAPコマンド リファレンス"^]を参照してください。

.関連情報
* link:https://docs.netapp.com/us-en/ontap-cli/search.html?q=volume+quota+policy["ボリューム クォータ ポリシー"^]
* link:https://docs.netapp.com/us-en/ontap-cli/vserver-modify.html["vserver modify -quota-policy policy_name"^]
* link:https://docs.netapp.com/us-en/ontap-cli/vserver-show.html["vserver show"^]

