---
permalink: volumes/commands-configure-deletion-flexclone-reference.html 
sidebar: sidebar 
keywords: commands for, configuring, deletion of, flexclone files, configure, command, delete, deletion, files, file 
summary: クライアントがNetApp Manageability SDKを使用せずにFlexCloneファイルを削除する場合、ボリューム ファイル クローン削除コマンドを使用して、FlexVolボリュームからFlexCloneファイルをより迅速に削除できます。 
---
= FlexCloneファイルの削除の設定用コマンド
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
クライアントがNetApp Manageability SDKを使用せずにFlexCloneファイルを削除する場合、 `volume file clone deletion`コマンドを使用して、FlexVolボリュームからFlexCloneファイルをより迅速に削除できるようにします。FlexCloneファイルの拡張子および最小サイズは、より迅速な削除を可能にするために使用されます。

 `volume file clone deletion`コマンドを使用して、ボリューム内のFlexCloneファイルについて、サポートされる拡張子のリストと最小サイズ要件を指定できます。要件を満たすFlexCloneファイルに対してのみ、高速削除方式が使用されます。要件を満たさないFlexCloneファイルに対しては、低速削除方式が使用されます。

クライアントがNetApp Manageability SDKを使用してボリュームからFlexCloneファイルとFlexClone LUNを削除する場合は、常に高速削除方式が使用されるため、拡張子とサイズの要件は適用されません。

[cols="2*"]
|===
| 目的 | 使用するコマンド 


 a| 
ボリュームでサポートされる拡張子のリストに拡張子を追加する
 a| 
`volume file clone deletion add-extension`



 a| 
高速削除方式を使用してボリュームから削除できるFlexCloneファイルの最小サイズを変更する
 a| 
`volume file clone deletion modify`



 a| 
ボリュームでサポートされる拡張子リストから拡張子を削除する
 a| 
`volume file clone deletion remove-extension`



 a| 
サポートされる拡張子のリストと、クライアントが高速削除方式を使用してボリュームから削除できるFlexCloneファイルの最小サイズを表示する
 a| 
`volume file clone deletion show`

|===
この手順で説明されているコマンドの詳細については、link:https://docs.netapp.com/us-en/ontap-cli/["ONTAPコマンド リファレンス"^]を参照してください。

.関連情報
* link:https://docs.netapp.com/us-en/ontap-cli/search.html?q=volume+file+clone+deletion["volume file clone deletion"^]

