---
permalink: volumes/commands-display-quotas-reference.html 
sidebar: sidebar 
keywords: commands for, display, displaying, information about, quotas 
summary: コマンドを使用して、適用されたクォータとリソース使用量を含むクォータ レポートを表示したり、クォータの状態とエラーに関する情報、またはクォータ ポリシーとクォータ ルールに関する情報を表示したりできます。 
---
= クォータに関する情報を表示するための ONTAP コマンド
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
コマンドを使用して、適用されたクォータとリソース使用量を含むクォータ レポートを表示したり、クォータの状態とエラーに関する情報、またはクォータ ポリシーとクォータ ルールに関する情報を表示したりできます。

次のコマンドは、FlexVolに対してのみ実行できます。

[cols="2*"]
|===
| 状況 | 使用するコマンド 


 a| 
強制クォータに関する情報を表示する
 a| 
`volume quota report`



 a| 
クォータ ターゲットのリソース使用量（ディスク容量とファイル数）を表示します
 a| 
`volume quota report`



 a| 
ファイルへの書き込みが許可された場合に影響を受けるクォータ制限を決定する
 a| 
`volume quota report`と `-path`パラメータ



 a| 
 `on`、 `off`、 `initializing`などのクォータ状態を表示します。
 a| 
`volume quota show`



 a| 
クォータ メッセージのログ記録に関する情報を表示する
 a| 
`volume quota show`と `-logmsg`パラメータ



 a| 
クォータの初期化とサイズ変更中に発生したエラーを表示する
 a| 
`volume quota show`と `-instance`パラメータ



 a| 
クォータ ポリシーに関する情報を表示する
 a| 
`volume quota policy show`



 a| 
クォータルールに関する情報を表示する
 a| 
`volume quota policy rule show`



 a| 
Storage Virtual Machine（SVM、旧Vserver）に割り当てられているクォータ ポリシーの名前を表示する
 a| 
`vserver show`と `-instance`パラメータ

|===
 `volume quota`の詳細については、link:https://docs.netapp.com/us-en/ontap-cli/search.html?q=volume+quota["ONTAPコマンド リファレンス"^]を参照してください。



== ONTAP volume quota policy rule showコマンドとvolume quota reportコマンドを使用するタイミング

どちらのコマンドもクォータに関する情報を表示しますが、 `volume quota policy rule show`は構成されたクォータ ルールを迅速に表示するのに対し、 `volume quota report`コマンドはより多くの時間とリソースを消費し、強制されたクォータとリソース使用量を表示します。

 `volume quota policy rule show`コマンドは、次の目的に役立ちます：

* アクティブ化する前にクォータ ルールの設定を確認する
+
このコマンドは、クォータが初期化されているかサイズ変更されているかに関係なく、設定されているすべてのクォータ ルールを表示します。

* システム リソースに影響を与えずにクォータ ルールをすばやく表示する
+
ディスクおよびファイルの使用量が表示されないため、このコマンドはクォータ レポートほどリソースを消費しません。

* SVMに割り当てられていないクォータ ポリシー内のクォータ ルールを表示する


 `volume quota policy rule show`の詳細については、link:https://docs.netapp.com/us-en/ontap-cli/volume-quota-policy-rule-show.html["ONTAPコマンド リファレンス"^]を参照してください。

 `volume quota report`コマンドは、次の目的に役立ちます：

* 派生クォータを含む適用クォータを表示する
* 派生クォータの影響を受けるターゲットも含め、有効なすべてのクォータで使用されているディスク スペースとファイル数を表示する
+
（デフォルト クォータの場合、結果の派生クォータに照らして使用量が追跡されるため、使用量は「0」と表示されます）。

* ファイルへの書き込みを許可するタイミングに影響するクォータ制限を特定する
+
 `-path`パラメータを `volume quota report`コマンドに追加します。



[NOTE]
====
クォータ レポートの生成には大量のリソースが消費されます。クラスタ内の多数のFlexVolに対して実行すると、完了までに時間がかかることがあります。SVM内の個々のボリュームのクォータ レポートを表示する方が効率的です。

====
 `volume quota report`の詳細については、link:https://docs.netapp.com/us-en/ontap-cli/volume-quota-report.html["ONTAPコマンド リファレンス"^]を参照してください。
