---
permalink: volumes/control-io-performance-qos-task.html 
sidebar: sidebar 
keywords: control, monitor, i/o performance, flexvol volumes, using storage qos 
summary: FlexVol ボリュームへの入出力（ I/O ）パフォーマンスは、ストレージ QoS ポリシーグループにボリュームを割り当てることによって制御できます。I/O パフォーマンスを制御することで、ワークロードが特定のパフォーマンス目標を達成できるようにしたり、他のワークロードに悪影響を与えるワークロードを抑制したりできます。 
---
= ストレージ QoS を使用して、 FlexVol ボリュームへの I/O パフォーマンスを制御および監視します
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
FlexVol ボリュームへの入出力（ I/O ）パフォーマンスは、ストレージ QoS ポリシーグループにボリュームを割り当てることによって制御できます。I/O パフォーマンスを制御することで、ワークロードが特定のパフォーマンス目標を達成できるようにしたり、他のワークロードに悪影響を与えるワークロードを抑制したりできます。

ポリシーグループは最大スループット制限（ 100MB/s など）を適用します。ポリシーグループは最大スループットを指定せずに作成することもでき、ワークロードの制御に先立ってパフォーマンスを監視できます。

SVM 、 LUN 、およびファイルをポリシーグループに割り当てることもできます。

ポリシーグループへのボリュームの割り当てについては、次の要件に注意してください。

* ボリュームは、ポリシーグループが属する SVM に含まれている必要があります。
+
SVM は、ポリシーグループを作成するときに指定します。

* ボリュームをポリシーグループに割り当てた場合、そのボリュームに含まれる SVM またはそのボリュームの子 LUN や子ファイルをポリシーグループに割り当てることはできなくなります。


ストレージ QoS の使用方法の詳細については、を参照してください link:../system-admin/index.html["システムアドミニストレーションリファレンス"]。

.手順
. ポリシーグループを作成するには 'qos policy-group create コマンドを使用します
. ボリュームをポリシーグループに割り当てるには 'volume create コマンドまたは volume modify コマンドに -qos-policy-group パラメータを指定して使用します
. パフォーマンス・データを表示するには 'qos statistics コマンドを使用します
. 必要に応じて 'qos policy-group modify コマンドを使用して ' ポリシーグループの最大スループット制限を調整します

