---
permalink: volumes/control-io-performance-qos-task.html 
sidebar: sidebar 
keywords: control, monitor, i/o performance, flexvol volumes, using storage qos, qos, performance, throttle, flexvol, policy, policy group 
summary: ストレージQoSポリシーグループを使用してFlexVolボリュームのI/Oパフォーマンスを制御し、ワークロードを管理できます。 
---
= ストレージQoSを使用したFlexVolへのI/Oパフォーマンスの制御と監視
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
FlexVolへの入出力（I/O）パフォーマンスは、ボリュームをストレージQoSポリシー グループに割り当てることで制御できます。I/Oパフォーマンスを制御することで、ワークロードが特定のパフォーマンス目標を達成できるようにしたり、他のワークロードに悪影響を及ぼすワークロードを調整したりすることができます。

.タスク概要
ポリシーグループは、最大スループット制限（例：100 MB/s）を適用します。最大スループットを指定せずにポリシーグループを作成することもできます。これにより、ワークロードを制御する前にパフォーマンスを監視できます。また、オプションで最小スループット制限を指定することもできます。

SVM、LUN、ファイルをポリシー グループに割り当てることもできます。

ポリシー グループへのボリュームの割り当てについては、次の要件に注意してください。

* ボリュームは、ポリシー グループが属するSVMに含まれている必要があります。
+
SVMはポリシー グループの作成時に指定します。

* ONTAP 9.18.1以降では、QoSポリシーが設定されているSVMに含まれるボリュームにQoSポリシーを割り当てることができます。ネストされたQoSポリシーを使用する場合は、最も制限の厳しいポリシーが適用されます。
* ONTAP 9.14.0 以降では、QoS ポリシーを持つボリュームに含まれる qtree にポリシーを割り当てることができます。


Storage QoS の使用方法の詳細については、link:../system-admin/index.html["システム アドミニストレーション リファレンス"]を参照してください。

.手順
.  `qos policy-group create`コマンドを使用してポリシーグループを作成します。
.  `volume create`コマンドまたは `volume modify`パラメータ付きの `-qos-policy-group`コマンドを使用して、ボリュームをポリシー グループに割り当てます。
.  `qos statistics`コマンドを使用してパフォーマンスデータを表示します。
. 必要に応じて、 `qos policy-group modify`コマンドを使用してポリシーグループの最大スループット制限を調整します。


.関連情報
* link:https://docs.netapp.com/us-en/ontap-cli/search.html?q=qos+policy-group["qos policy-group"^]
* リンク：https://docs.netapp.com/us-en/ontap-cli/qos-policy-group-create.html［qos policy-group create］
* link:https://docs.netapp.com/us-en/ontap-cli/volume-create.html["volume create"^]
* link:https://docs.netapp.com/us-en/ontap-cli/volume-modify.html["volume modify"^]
* link:https://docs.netapp.com/us-en/ontap-cli/search.html?q=qos+statistics["qos統計"^]

