---
permalink: volumes/create-flexclone-file-flexclone-lun-task.html 
sidebar: sidebar 
keywords: create, flexclone file, flexclone lun, efficient, clone 
summary: FlexVolまたはFlexCloneボリューム内のファイルとLUNのクローンを、スペース効率に優れた方法で短時間で作成できます。 
---
= ONTAPでFlexCloneファイルまたはFlexClone LUNを作成する
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
コマンドを使用すると、FlexVolまたはFlexCloneボリュームに存在するファイルやLUNのクローンを、スペースを効率よく、時間をかけずに作成できます `volume file clone create`。

.開始する前に
* クラスタにFlexCloneライセンスがインストールされている必要があります。このライセンスはに含まれていlink:../system-admin/manage-licenses-concept.html#licenses-included-with-ontap-one["ONTAP One"]ます。
* サブLUNのクローニングまたはサブファイルのクローニングに複数のブロック範囲を使用する場合は、ブロック番号が重複しないようにする必要があります。
* 適応圧縮が有効なボリュームでサブLUNまたはサブファイルを作成する場合は、ブロック範囲がミスアライメントされないようにする必要があります。
+
つまり、ソースの開始ブロック番号とデスティネーションの開始ブロック番号が、偶数または奇数のいずれかでアライメントされている必要があります。



.タスクの内容
SVM管理者は、クラスタ管理者によって割り当てられたPrivilegesに応じて、FlexCloneファイルおよびFlexClone LUNを作成できます。

クローンを作成および変更するときに、FlexCloneファイルおよびFlexClone LUNの自動削除設定を指定できます。デフォルトでは、自動削除設定は無効になっています。

既存のFlexCloneファイルまたはFlexClone LUNをクローンの作成時に上書きするには、 `volume file clone create`コマンドでパラメータを指定し `-overwrite-destination`ます。

スプリット負荷の最大値に達すると、FlexCloneファイルおよびFlexClone LUNの作成要求の受け入れが一時的に停止し、エラーメッセージが表示されます。 `EBUSY`ノードのスプリット負荷が最大値を下回ると、FlexCloneファイルおよびFlexClone LUNの作成要求の受け入れが再開されます。クローンの作成に必要な容量がノードに確保されてから、次の作成要求を行うようにしてください。

.手順
. コマンドを使用して、FlexCloneファイルまたはFlexClone LUNを作成し `volume file clone create`ます。
+
次の例は、ボリュームvol1内の親ファイルfile1_sourceのFlexCloneファイルfile1_cloneを作成する方法を示しています。

+
[listing]
----
cluster1::> volume file clone create -vserver vs0 -volume vol1 -source-path /file1_source -destination-path /file1_clone
----
+
の詳細については `volume file clone create`、をlink:https://docs.netapp.com/us-en/ontap-cli/volume-file-clone-create.html["ONTAPコマンド リファレンス"^]参照してください。



.関連情報
link:../concepts/manual-pages.html["ONTAPコマンド リファレンス"]
