---
permalink: volumes/default-tree-quotas-volume-create-concept.html 
sidebar: sidebar 
keywords: default, tree quotas, flexvol volume, create, derived tree quotas, derived, quota, tree 
summary: FlexVol上にデフォルト ツリー クォータを作成すると、そのボリューム内のすべてのqtreeに、対応する派生ツリー クォータが自動的に作成されます。 
---
= FlexVolのデフォルト ツリー クォータによる派生ツリー クォータの作成
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
FlexVol上にデフォルト ツリー クォータを作成すると、そのボリューム内のすべてのqtreeに、対応する派生ツリー クォータが自動的に作成されます。

これらの派生ツリー クォータには、デフォルトのツリー クォータと同じ制限があります。追加のクォータが存在しない場合は、制限によって次のような影響があります。

* ユーザは、ボリューム全体に割り当てられているスペースと同じだけqtree内のスペースを使用できます（ただし、ルートまたは別のqtree内のスペースを使用してボリュームの制限を超えていない場合）。
* ボリューム全体を使用するように各qtreeを拡張できます。


ボリューム上のデフォルト ツリー クォータは、ボリュームに追加されるすべての新しいqtreeに引き続き適用されます。新しいqtreeが作成されるたびに、派生ツリー クォータも作成されます。

すべての派生クォータと同様に、派生ツリー クォータは次のように動作します。

* ターゲットに明示的クォータがない場合にのみ作成されます。
* クォータレポートには表示されますが、 `volume quota policy rule show`コマンドでクォータルールを表示した場合には表示されません。link:https://docs.netapp.com/us-en/ontap-cli/volume-quota-policy-rule-show.html["ONTAPコマンド リファレンス"^]の `volume quota policy rule show`の詳細を確認してください。


.派生ツリー クォータの例
3つのqtree（proj1、proj2、およびproj3）を含むボリュームがあります。唯一のツリー クォータは、proj1 qtreeに対する明示的クォータで、それによってディスク サイズが10GBに制限されます。ボリュームにデフォルト ツリー クォータを作成し、そのボリュームのクォータを再初期化すると、クォータ レポートに4つのツリー クォータが表示されます。

[listing]
----
                                    ----Disk----  ----Files-----   Quota
Volume   Tree      Type    ID        Used  Limit    Used   Limit   Specifier
-------  --------  ------  -------  -----  -----  ------  ------   ---------
vol1     proj1     tree    1           0B   10GB       1       -   proj1
vol1               tree    *           0B   20GB       0       -   *
vol1     proj2     tree    2           0B   20GB       1       -   proj2
vol1     proj3     tree    3           0B   20GB       1       -   proj3
...
----
最初の行は、proj1 qtreeに対する元の明示的クォータを示しています。このクォータは変更されません。

2行目は、ボリュームの新しいデフォルトのツリークォータを示しています。クォータ指定子のアスタリスク（*）は、これがデフォルトのクォータであることを示しています。このクォータは、作成したクォータルールの結果です。

最後の2行は、proj2およびproj3 qtreeの新しい派生ツリー クォータを示しています。これらのクォータは、ボリュームのデフォルト ツリー クォータの結果としてONTAPによって自動的に作成されました。これらの派生ツリー クォータには、ボリュームのデフォルト ツリー クォータと同じ20GBのディスク制限が設定されます。proj1 qtreeにはすでに明示的クォータが設定されていたため、ONTAPによってproj1 qtreeの派生ツリー クォータは作成されていません。
