---
permalink: volumes/delete-snapshot-copies-automatic-task.html 
sidebar: sidebar 
keywords: delete, snapshot, copies, automatically, flexclone luns, automatic, lun, luns 
summary: スペース使用率を管理するために、SnapshotとFlexClone LUNを自動的に削除するポリシーを定義できます。 
---
= Snapshotの自動作成とLUN削除を有効にしてスペースを管理します
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
スナップショットとFlexClone LUNを自動的に削除するポリシーを定義して有効化できます。スナップショットとFlexClone LUNを自動的に削除することで、スペースの使用率を管理しやすくなります。

.タスク概要
読み取り/書き込みボリュームのスナップショットと、読み取り/書き込み親ボリュームのFlexClone LUNを自動的に削除できます。読み取り専用ボリューム（SnapMirrorデスティネーションボリュームなど）のスナップショットの自動削除を設定することはできません。

.手順
.  `volume snapshot autodelete modify`コマンドを使用して、Snapshotを自動的に削除するためのポリシーを定義し、有効にします。
+
 `volume snapshot autodelete modify`とニーズを満たすポリシーの定義の詳細については、link:https://docs.netapp.com/us-en/ontap-cli/volume-snapshot-autodelete-modify.html["ONTAPコマンド リファレンス"^]をご覧ください。

+
次のコマンドは、Snapshotの自動削除を有効にし、vs0.example.comストレージ仮想マシン（SVM）の一部であるvol3ボリュームのトリガーを `snap_reserve`に設定します：

+
[listing]
----
cluster1::> volume snapshot autodelete modify -vserver vs0.example.com
-volume vol3 -enabled true -trigger snap_reserve
----
+
次のコマンドは、vs0.example.comストレージ仮想マシン（SVM）の一部であるvol3ボリュームのSnapshotの自動削除と、自動削除対象としてマークされたFlexClone LUNの自動削除を有効にします：

+
[listing]
----
cluster1::> volume snapshot autodelete modify -vserver vs0.example.com
-volume vol3 -enabled true -trigger volume -commitment try -delete-order
oldest_first -destroy-list lun_clone,file_clone
----
+
[NOTE]
====
アグリゲートレベルのスナップショットはボリュームレベルのスナップショットとは異なる動作をし、ONTAPによって自動的に管理されます。アグリゲートスナップショットを削除するオプションは常に有効になっており、スペース使用率の管理に役立ちます。

アグリゲートのトリガーパラメータが `snap_reserve`に設定されている場合、予約済みスペースがしきい値容量を超えるまでSnapshotは保持されます。したがって、トリガーパラメータが `snap_reserve`に設定されていない場合でも、コマンド内のSnapshotによって使用されているスペースは `0`と表示されます。これは、これらのSnapshotは自動的に削除されるためです。また、アグリゲート内のSnapshotによって使用されているスペースは空きスペースとみなされ、コマンドの使用可能スペースパラメータに含まれます。

====

