---
permalink: volumes/determine-space-usage-volume-aggregate-concept.html 
sidebar: sidebar 
keywords: determine, space usage, volume, aggregate 
summary: ONTAPを使用すると、ボリューム、アグリゲート内のボリュームのフットプリント、およびアグリゲートに基づいてスペース消費量を判断できます。 
---
= ONTAPでのボリュームまたはアグリゲートのスペース使用量を確認する
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
ONTAPである機能を有効にすると、想定よりも多くのスペースが消費されることがあります。ONTAPでは、消費されるスペースを、ボリューム、アグリゲート内のボリュームのフットプリント、およびアグリゲートの3つの観点から判断できます。



== スペース割り当ての表示

ボリューム、アグリゲート、またはその両方でのスペース消費またはスペース不足により、ボリュームのスペースが不足することがあります。スペース使用量の機能別の内訳をさまざまな観点から確認することで、調整や無効化が必要な機能や、その他の対処（アグリゲートやボリュームのサイズ拡張など）を講じておくべきかどうかを判断できます。

スペース使用量は、以下の観点から詳細に確認できます。

* ボリュームのスペース使用量
+
Snapshotによる使用量など、ボリューム内のスペース使用量の詳細が表示されます。

+
コマンドを使用し `volume show-space`て、ボリュームのスペース使用量を確認します。

+
の詳細については `volume show-space`、をlink:https://docs.netapp.com/us-en/ontap-cli/volume-show-space.html["ONTAPコマンド リファレンス"^]参照してください。

+
ONTAP 9 14.1以降では、が有効になっているボリュームについて、xref:enable-temperature-sensitive-efficiency-concept.html[温度に基づくStorage Efficiency（TSSE）]コマンドによって報告されるボリュームで使用されているスペース量 `volume show-space -physical used`には、TSSEによって実現されるスペース削減量が含まれます。

* アグリゲート内のボリュームの占有量
+
ボリュームのメタデータも含め、アグリゲートで各ボリュームが使用しているスペースの量に関する詳細を把握できます。

+
コマンドを使用して `volume show-footprint`、アグリゲートに対するボリュームの占有量を確認します。

+
の詳細については `volume show-footprint`、をlink:https://docs.netapp.com/us-en/ontap-cli/volume-show-footprint.html["ONTAPコマンド リファレンス"^]参照してください。

* アグリゲートのスペース使用量
+
アグリゲートに含まれるすべてのボリュームのボリューム占有量、アグリゲートSnapshot用にリザーブされたスペース、およびその他のアグリゲートメタデータの合計が表示されます。

+
WAFLでは、アグリゲート レベルのメタデータおよびパフォーマンス用に総ディスク スペースの10%が予約されます。アグリゲート内のボリュームを維持するためのスペースはWAFLリザーブから使用され、変更することはできません。

+
ONTAP 9.12.1以降では、30TBを超えるアグリゲートのWAFLリザーブが、AFFプラットフォームおよびFAS500fプラットフォームの10%から5%に削減されました。ONTAP 9.14.1以降では、これと同じ削減効果がすべてのFASプラットフォームのアグリゲートに適用されるため、アグリゲートの使用可能スペースが5%増加します。

+
コマンドを使用し `storage aggregate show-space`て、アグリゲートのスペース使用量を確認します。

+
の詳細については `storage aggregate show-space`、をlink:https://docs.netapp.com/us-en/ontap-cli/storage-aggregate-show-space.html["ONTAPコマンド リファレンス"^]参照してください。



テープバックアップや重複排除などの特定の機能では、ボリュームとアグリゲートの両方から直接メタデータ用のスペースが使用されます。これらの機能では、ボリュームとボリュームのフットプリントの観点でスペース使用量が異なります。

.関連情報
* link:https://kb.netapp.com/Advice_and_Troubleshooting/Data_Storage_Software/ONTAP_OS/Space_Usage["ナレッジベースの記事：スペース使用量"^]
* link:https://www.netapp.com/blog/free-up-storage-capacity-upgrade-ontap/["ONTAP 9にアップグレードすることで、ストレージ容量の5%を解放できます。12.1"^]




== ボリュームメタデータとデータ指標のレポート

これまで、いくつかのボリュームスペース指標では、消費された合計データ量がメタデータとユーザデータの2つの指標の組み合わせとして報告されてきました。ONTAP 9 .15.1以降では、メタデータとユーザデータのメトリックが別 々 にレポートされます。これをサポートするために、2つの新しいメタデータカウンタが導入されました。

* 合計-メタデータ
+
このカウンタは、ボリューム内のメタデータの合計サイズを表示します。アグリゲートに格納されているボリュームメタデータは含まれません。レポートそれは別 々 にユーザーによって割り当てられた論理データを決定するのに役立ちます。

* メタデータ容量の合計
+
ボリュームに格納されているメタデータとアグリゲートに格納されているボリュームメタデータの合計です。アグリゲート内のボリュームのメタデータフットプリントの合計が表示されます。それを別 々 に報告することは、ユーザーによって割り当てられた物理データを決定するのに役立ちます。



また、いくつかの既存のカウンタが更新され、メタデータコンポーネントが削除されてユーザデータのみが表示されるようになりました。

* ユーザデータ
* ボリュームのデータ容量


これらの変更により、ユーザによって消費されるデータを、より正確に確認できるようになります。これには、より正確にチャージバックを決定できることなど、いくつかのメリットがあります。
