---
permalink: volumes/determine-space-usage-volume-aggregate-concept.html 
sidebar: sidebar 
keywords: determine, space usage, volume, aggregate 
summary: ある機能を ONTAP で有効にすると、想定以上のスペースが消費されることがあります。ONTAP では、消費されるスペースを、ボリューム、アグリゲート内のボリュームのフットプリント、およびアグリゲートの 3 つの観点から判定できます。 
---
= ボリュームまたはアグリゲートのスペース使用量を判定します
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
ある機能を ONTAP で有効にすると、想定以上のスペースが消費されることがあります。ONTAP では、消費されるスペースを、ボリューム、アグリゲート内のボリュームのフットプリント、およびアグリゲートの 3 つの観点から判定できます。

ボリューム、アグリゲート、またはその両方でのスペース消費またはスペース不足により、ボリュームのスペースが不足することがあります。スペース使用量の機能別の内訳をさまざまな観点から確認することで、調整や無効化、またはその他の対処（アグリゲートやボリュームのサイズ拡張など）が必要な機能を判断できます。

スペース使用量は、以下の観点から詳細に確認できます。

* ボリュームのスペース使用量
+
Snapshot コピーによる使用量も含めて、ボリューム内のスペース使用量の詳細を確認できます。

+
ボリュームのスペース使用量は、を使用して確認できます `volume show-space` コマンドを実行します

* アグリゲート内のボリュームの占有量
+
ボリュームのメタデータも含め、包含アグリゲートで各ボリュームが使用しているスペースの量に関する詳細を把握できます。

+
アグリゲートを使用したボリュームの占有量は、で確認できます `volume show-footprint` コマンドを実行します

* アグリゲートのスペース使用量
+
アグリゲートに含まれるすべてのボリュームのボリュームフットプリント、アグリゲート Snapshot コピーにリザーブされたスペース、およびその他のアグリゲートメタデータの合計です。

+
WAFL では、アグリゲートレベルのメタデータとパフォーマンス用に合計ディスクスペースの10%がリザーブされます。アグリゲート内のボリュームを維持するために使用されるスペースは、WAFL リザーブから除外され、変更することはできません。

+
ONTAP 9.12.1以降では、All Flash FAS （AFF ）およびFAS500fプラットフォームの場合、30TBを超えるアグリゲートのWAFL リザーブが10%から5%に削減され、アグリゲートの使用可能スペースが増加します。

+
アグリゲートのスペース使用量は、で確認できます `storage aggregate show-space` コマンドを実行します



テープバックアップおよび重複排除などの特定の機能は、ボリュームからとアグリゲートから直接、メタデータ用のスペースを使用します。これらの機能については、ボリュームとボリュームのフットプリントで異なるスペース使用量が表示されます。

.関連情報
link:https://kb.netapp.com/Advice_and_Troubleshooting/Data_Storage_Software/ONTAP_OS/Space_Usage["ナレッジベースの記事：スペースの使用状況"]

link:https://www.netapp.com/blog/free-up-storage-capacity-upgrade-ontap/["ONTAP 9.12.1にアップグレードして、ストレージ容量の5%を解放します"]
