---
permalink: volumes/determine-space-usage-volume-aggregate-concept.html 
sidebar: sidebar 
keywords: determine, space usage, volume, aggregate 
summary: ある機能を ONTAP で有効にすると、想定以上のスペースが消費されることがあります。ONTAP では、消費されるスペースを、ボリューム、アグリゲート内のボリュームのフットプリント、およびアグリゲートの 3 つの観点から判定できます。 
---
= ボリュームまたはアグリゲートのスペース使用量を判定します
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
ある機能をONTAPで有効にすると、想定よりも多くのスペースが消費される可能性があります。ONTAP では、消費されるスペースを、ボリューム、アグリゲート内のボリュームのフットプリント、およびアグリゲートの 3 つの観点から判定できます。

ボリューム、アグリゲート、またはその両方でのスペース消費またはスペース不足により、ボリュームのスペースが不足することがあります。スペース使用量の機能別の内訳をさまざまな観点から確認することで、調整や無効化が必要な機能や、その他の処理（アグリゲートやボリュームのサイズ拡張など）が必要かどうかを判断できます。

スペース使用量は、以下の観点から詳細に確認できます。

* ボリュームのスペース使用量
+
Snapshot コピーによる使用量も含めて、ボリューム内のスペース使用量の詳細を確認できます。

+
を使用します `volume show-space` コマンドを使用してボリュームのスペース使用量を確認します。

+
ONTAP 9.14.1以降、ボリューム xref:enable-temperature-sensitive-efficiency-concept.html[温度に基づくStorage Efficiency（TSSE）] Enabledに設定されている場合、によって報告されるボリュームで使用されているスペースの量。 `volume show-space -physical used` コマンドには、TSSEによって実現されるスペース削減量が含まれます。

* アグリゲート内のボリュームの占有量
+
ボリュームのメタデータも含め、包含アグリゲートで各ボリュームが使用しているスペースの量に関する詳細を把握できます。

+
を使用します `volume show-footprint` コマンドを使用して、ボリュームとアグリゲートのフットプリントを確認します。

* アグリゲートのスペース使用量
+
アグリゲートに含まれるすべてのボリュームのボリュームフットプリント、アグリゲート Snapshot コピーにリザーブされたスペース、およびその他のアグリゲートメタデータの合計です。

+
WAFL では、アグリゲートレベルのメタデータとパフォーマンス用に合計ディスクスペースの10%がリザーブされます。  アグリゲート内のボリュームを維持するために使用されるスペースは、WAFL リザーブから除外され、変更することはできません。

+
ONTAP 9.12.1以降では、30TBを超えるアグリゲートのWAFLリザーブが、AFFプラットフォームおよびFAS500fプラットフォームの10%から5%に削減されました。  ONTAP 9.14.1以降では、すべてのFASプラットフォームで環境アグリゲートが削減され、アグリゲートで使用可能なスペースが5%増加しました。

+
を使用します `storage aggregate show-space` コマンドを使用してアグリゲートのスペース使用量を確認します。



テープバックアップおよび重複排除などの特定の機能は、ボリュームからとアグリゲートから直接、メタデータ用のスペースを使用します。これらの機能については、ボリュームとボリュームのフットプリントで異なるスペース使用量が表示されます。

.関連情報
* link:https://kb.netapp.com/Advice_and_Troubleshooting/Data_Storage_Software/ONTAP_OS/Space_Usage["ナレッジベースの記事：スペース使用量"]
* link:https://www.netapp.com/blog/free-up-storage-capacity-upgrade-ontap/["ONTAP 9.12.1にアップグレードして、ストレージ容量の5%を解放します"]

