---
permalink: volumes/df-command-file-size-concept.html 
sidebar: sidebar 
keywords: df, command, file, size, reporting, reports, space, usage, qtree, quota 
summary: dfコマンドでのスペース使用量のレポート方法は、クォータの設定によって異なります。 
---
= df コマンドによるファイルサイズの表示
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
での方法 `df` コマンドでは、スペース使用量は、qtreeを含むボリュームでクォータが有効になっているか無効になっているか、qtree内のクォータ使用量が追跡されているかという2つの条件によって報告されます。

qtreeを含むボリュームでクォータが有効になっている場合、およびqtree内のクォータ使用量が追跡されると、によって報告されるスペース使用量が追跡されます `df` コマンドは、クォータレポートで指定された値に等しくなります。この場合、クォータ使用量では、ディレクトリ、 ACL 、ストリームディレクトリ、およびメタファイルによって使用されるブロックが除外されます。

ボリュームでクォータが有効になっていない場合、または qtree にクォータルールが設定されていない場合、報告されるスペース使用量には、ボリューム内の他の qtree を含むボリューム全体のディレクトリ、 ACL 、ストリームディレクトリ、およびメタファイルによって使用されるブロックが含まれます。この場合、によって報告されるスペース使用量 `df` コマンドがクォータを追跡するときに報告される想定値を超えています。

を実行すると `df` コマンドを実行すると、クォータ使用量が追跡されるqtreeのマウントポイントから、クォータレポートの値と同じスペース使用量が表示されます。ほとんどの場合、ツリークォータルールにディスクのハードリミットが設定されている場合、によって報告される合計サイズ `df` コマンドはディスク制限に等しく、使用可能なスペースはクォータのディスク制限とクォータ使用量の差に等しくなります。

ただし、で報告される使用可能なスペースが表示される場合もあります `df` コマンドは、ボリューム全体で使用可能なスペースと同じになる場合があります。この状況は、 qtree にハードディスク制限が設定されていない場合に発生することがあります。ONTAP 9.9.1以降では、ボリューム全体で使用可能なスペースが残りのツリークォータスペースよりも少ない場合にも発生することがあります。これらのいずれかの状況が発生した場合、によって報告される合計サイズ `df` コマンドは、qtree内で使用されているクォータにFlexVol ボリュームで使用可能なスペースを加えたものです。

[NOTE]
====
合計サイズは、 qtree ディスクの制限サイズでもボリュームの設定サイズでもありません。また、他の qtree 内の書き込みアクティビティや、バックグラウンドのストレージ効率化アクティビティによっても異なります。

====
.で使用されているスペース使用量の例 `df` コマンドとクォータレポート
次のクォータレポートには、 qtree Alice の場合はディスク制限が 1 GB 、 qtree bob の場合は 2 GB 、 qtree Project1 の場合は制限がないことが示されています。

[listing]
----
C1_vsim1::> quota report -vserver vs0
Vserver: vs0
                                    ----Disk----  ----Files-----   Quota
Volume   Tree      Type    ID        Used  Limit    Used   Limit   Specifier
-------  --------  ------  -------  -----  -----  ------  ------   ---------
vol2     alice     tree    1
                                  502.0MB    1GB       2       -   alice
vol2     bob       tree    2
                                   1003MB    2GB       2       -   bob
vol2     project1  tree    3
                                  200.8MB      -       2       -   project1
vol2               tree    *           0B      -       0       -   *
4 entries were displayed.
----
次の例は、の出力です `df` qtreeに対するコマンドAliceとBobは、クォータレポートと同じ使用済みスペース、およびディスク制限と同じ合計サイズ（1Mブロック単位）を報告します。これは、 alice と bob の qtree のクォータルールにディスク制限が定義されており、ボリュームの使用可能スペース（ 1211MB ）が qtree alice （ 523MB ）と qtree bob （ 1045MB ）のツリークォータスペースよりも大きいためです。

[listing]
----
linux-client1 [~]$ df -m /mnt/vol2/alice
Filesystem          1M-blocks  Used Available Use% Mounted on
172.21.76.153:/vol2      1024   502       523  50% /mnt/vol2

linux-client1 [~]$ df -m /mnt/vol2/bob
Filesystem          1M-blocks  Used Available Use% Mounted on
172.21.76.153:/vol2      2048  1004      1045  50% /mnt/vol2
----
次の例は、の出力です `df` qtree Project1に対するコマンドでは、クォータレポートと同じ使用済みスペースが報告されますが、合計サイズは、ボリューム全体の使用可能スペース（1211MB）をqtree Project1（201MB）のクォータ使用量に加算して合計1412MBになります。これは、 qtree Project1 のクォータルールにディスクの制限がないためです。

[listing]
----
linux-client1 [~]$ df -m /mnt/vol2/project1
Filesystem          1M-blocks  Used Available Use% Mounted on
172.21.76.153:/vol2      1412   201      1211  15% /mnt/vol2
----
[NOTE]
====
次に、の出力例を示します `df` ボリューム全体に対してコマンドを実行すると、Project1と同じ使用可能スペースが報告されます。

[listing]
----
linux-client1 [~]$ df -m /mnt/vol2
Filesystem          1M-blocks  Used Available Use% Mounted on
172.21.76.153:/vol2      2919  1709      1211  59% /mnt/vol2
----
====