---
permalink: volumes/disable-deduplication-volume-task.html 
sidebar: sidebar 
keywords: disabling, deduplication, volume 
summary: ポストプロセス重複排除とインライン重複排除は、ボリュームで個別に無効にすることができます。 
---
= ボリュームの重複排除を無効にする
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
ポストプロセス重複排除とインライン重複排除は、ボリュームで個別に無効にすることができます。

.必要なもの
ボリューム上で現在アクティブになっているボリューム効率化処理を停止します。 `volume efficiency stop`

の詳細については `volume efficiency stop`、をlink:https://docs.netapp.com/us-en/ontap-cli/volume-efficiency-stop.html["ONTAPコマンド リファレンス"^]参照してください。

.タスクの内容
ボリュームでデータ圧縮が有効になっている場合は、コマンドを実行して `volume efficiency off`データ圧縮を無効にします。の詳細については `volume efficiency off`、をlink:https://docs.netapp.com/us-en/ontap-cli/volume-efficiency-off.html["ONTAPコマンド リファレンス"^]参照してください。

.選択肢
* コマンドを使用し `volume efficiency off`て、ポストプロセス重複排除とインライン重複排除の両方を無効にします。
+
次のコマンドは、ボリュームVolAでポストプロセス重複排除とインライン重複排除の両方を無効にします。

+
`volume efficiency off -vserver vs1 -volume VolA`

* オプションをに設定して `inline only`コマンドを `-policy`実行し `volume efficiency modify`、ポストプロセス重複排除を無効にします。ただし、インライン重複排除は有効なままです。
+
次のコマンドは、ボリューム VolA でポストプロセス重複排除を無効にします。ただし、インライン重複排除は有効なままになります。

+
`volume efficiency modify -vserver vs1 -volume VolA -policy inline-only`

* オプションをに設定して `false`コマンドを `-inline-deduplication`実行し、 `volume efficiency modify`インライン重複排除のみを無効にします。
+
次のコマンドは、ボリューム VolA でインライン重複排除だけを無効にします。

+
`volume efficiency modify -vserver vs1 -volume VolA -inline-deduplication false`

+
の詳細については `volume efficiency modify`、をlink:https://docs.netapp.com/us-en/ontap-cli/volume-efficiency-modify.html["ONTAPコマンド リファレンス"^]参照してください。


