---
permalink: volumes/disable-deduplication-volume-task.html 
sidebar: sidebar 
keywords: disabling, deduplication, volume 
summary: ポストプロセス重複排除とインライン重複排除は、ボリュームで個別に無効にすることができます。 
---
= ボリュームの重複排除の無効化
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
ポストプロセス重複排除とインライン重複排除は、ボリュームで個別に無効にすることができます。

.開始する前に
ボリューム上で現在アクティブなボリューム効率化処理を停止します： `volume efficiency stop`

 `volume efficiency stop`の詳細については、link:https://docs.netapp.com/us-en/ontap-cli/volume-efficiency-stop.html["ONTAPコマンド リファレンス"^]を参照してください。

.タスク概要
ボリュームでデータ圧縮が有効になっている場合、 `volume efficiency off`コマンドを実行するとデータ圧縮が無効になります。 `volume efficiency off`の詳細については、link:https://docs.netapp.com/us-en/ontap-cli/volume-efficiency-off.html["ONTAPコマンド リファレンス"^]を参照してください。

.オプション
*  `volume efficiency off`コマンドを使用して、ポストプロセス重複排除とインライン重複排除の両方を無効にします。
+
次のコマンドは、ボリュームVolAでポストプロセス重複排除とインライン重複排除の両方を無効にします。

+
`volume efficiency off -vserver vs1 -volume VolA`

*  `volume efficiency modify`コマンドを `-policy`オプションを `inline only`に設定して使用すると、ポストプロセス重複排除は無効になりますが、インライン重複排除は有効なままになります。
+
次のコマンドは、ポストプロセス重複排除を無効にしますが、ボリュームVolAのインライン重複排除は有効なままです：

+
`volume efficiency modify -vserver vs1 -volume VolA -policy inline-only`

* インライン重複排除のみを無効にするには、 `-inline-deduplication`オプションを `false`に設定した `volume efficiency modify`コマンドを使用します。
+
次のコマンドは、ボリューム VolA のインライン重複排除のみを無効にします：

+
`volume efficiency modify -vserver vs1 -volume VolA -inline-deduplication false`

+
 `volume efficiency modify`の詳細については、link:https://docs.netapp.com/us-en/ontap-cli/volume-efficiency-modify.html["ONTAPコマンド リファレンス"^]をご覧ください。


