---
permalink: volumes/enable-disable-background-deduplication-aff-task.html 
sidebar: sidebar 
keywords: manage, aggregate-level, background, deduplication, aff systems 
summary: ボリュームのアグリゲートレベルの重複排除を有効または無効にするか、またはこの機能が有効になっているかどうかを確認します。 
---
= AFFシステムでアグリゲートレベルのバックグラウンド重複排除を管理します。
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
アグリゲートレベルの重複排除は、同じアグリゲートに属するボリューム間で重複するブロックを排除します。ONTAP 9.3 以降では、 AFF システムでアグリゲートレベルの重複排除をバックグラウンドで実行できます。この機能は、新規に作成したすべてのボリューム、およびボリュームのバックグラウンド重複排除をオンにしてアップグレードしたすべてのボリュームに対してデフォルトで有効になります。

.タスクの内容
この処理は、変更ログがある程度いっぱいになった時点で自動的にトリガーされます。スケジュールもポリシーも関連付けられません。

ONTAP 9.4 以降では、 AFF ユーザがアグリゲートレベルの重複排除スキャンを実行して、アグリゲート内のボリューム間で既存データの重複を排除することもできます。オプションを指定してコマンドを `-scan-old-data=true`実行すると、スキャナを起動でき `storage aggregate efficiency cross-volume-dedupe start`ます。

[listing]
----
cluster-1::> storage aggregate efficiency cross-volume-dedupe start -aggregate aggr1 -scan-old-data true
----
重複排除スキャンには時間がかかることがあります。この処理はオフピークの時間帯に実行することを推奨します。

[NOTE]
====
アグリゲートレベルのバックグラウンド重複排除は、ボリューム間バックグラウンド重複排除とも呼ばれます。

====
の詳細については `storage aggregate efficiency cross-volume-dedupe start`、をlink:https://docs.netapp.com/us-en/ontap-cli/storage-aggregate-efficiency-cross-volume-dedupe-start.html["ONTAPコマンド リファレンス"^]参照してください。

.手順
. AFF システムでアグリゲートレベルのバックグラウンド重複排除を管理します。
+
[cols="2*"]
|===
| 状況 | 使用するコマンド 


 a| 
アグリゲートレベルのバックグラウンド重複排除を有効にする
 a| 
`volume efficiency modify -vserver <vserver_name\> -volume <vol_name\> -cross-volume-background-dedupe true`



 a| 
アグリゲートレベルのバックグラウンド重複排除を無効にします
 a| 
`volume efficiency modify -vserver <vserver_name\> -volume <vol_name\> -cross-volume-background-dedupe false`



 a| 
アグリゲートレベルのバックグラウンド重複排除のステータスを表示します
 a| 
`aggregate efficiency cross-volume-dedupe show`

|===


この手順で説明されているコマンドの詳細については、をlink:https://docs.netapp.com/us-en/ontap-cli/["ONTAPコマンド リファレンス"^]参照してください。
