---
permalink: volumes/enable-disable-background-deduplication-aff-task.html 
sidebar: sidebar 
keywords: manage, aggregate-level, background, deduplication, aff systems 
summary: ボリュームのアグリゲート レベルの重複排除を有効または無効にするか、この機能がオンになっているかどうかを確認します。 
---
= AFFシステムでのアグリゲートレベルのバックグラウンド重複排除の管理
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
アグリゲートレベルの重複排除では、同じアグリゲートに属するボリューム間の重複ブロックを排除します。ONTAP 9.3以降では、AFFシステムでアグリゲートレベルの重複排除をバックグラウンドで実行できます。この機能は、新規に作成されたすべてのボリューム、およびボリュームのバックグラウンド重複排除をオンにしてアップグレードされたすべてのボリュームに対してデフォルトで有効になります。

.タスク概要
この処理は、変更ログの割合が十分に多い場合に自動的にトリガーされます。この処理にはスケジュールもポリシーも関連付けられません。

ONTAP 9.4以降、AFFユーザはアグリゲートレベルの重複排除スキャナを実行して、アグリゲート内のボリューム間で重複する既存データを排除できるようになりました。 `storage aggregate efficiency cross-volume-dedupe start`コマンドを `-scan-old-data=true`オプションとともに使用して、スキャナを起動できます：

[listing]
----
cluster-1::> storage aggregate efficiency cross-volume-dedupe start -aggregate aggr1 -scan-old-data true
----
重複排除スキャンには時間がかかる場合があります。この処理はオフピークの時間帯に実行することを推奨します。

[NOTE]
====
アグリゲートレベルのバックグラウンド重複排除は、ボリューム間バックグラウンド重複排除とも呼ばれます。

====
 `storage aggregate efficiency cross-volume-dedupe start`の詳細については、link:https://docs.netapp.com/us-en/ontap-cli/storage-aggregate-efficiency-cross-volume-dedupe-start.html["ONTAPコマンド リファレンス"^]をご覧ください。

.手順
. AFFシステムでのアグリゲートレベルのバックグラウンド重複排除の管理
+
[cols="2*"]
|===
| 状況 | このコマンドを使用する 


 a| 
アグリゲートレベルのバックグラウンド重複排除を有効にする
 a| 
`volume efficiency modify -vserver <vserver_name\> -volume <vol_name\> -cross-volume-background-dedupe true`



 a| 
アグリゲートレベルのバックグラウンド重複排除を無効にする
 a| 
`volume efficiency modify -vserver <vserver_name\> -volume <vol_name\> -cross-volume-background-dedupe false`



 a| 
アグリゲートレベルのバックグラウンド重複排除のステータスを表示する
 a| 
`aggregate efficiency cross-volume-dedupe show`

|===


この手順で説明されているコマンドの詳細については、link:https://docs.netapp.com/us-en/ontap-cli/["ONTAPコマンド リファレンス"^]を参照してください。

.関連情報
* link:https://docs.netapp.com/us-en/ontap-cli/volume-efficiency-modify.html["volume efficiency modify"^]
* link:https://docs.netapp.com/us-en/ontap-cli/storage-aggregate-efficiency-cross-volume-dedupe-show.html["アグリゲート効率 クロスボリューム重複排除の表示"^]

