---
permalink: volumes/enable-large-vol-file-support-task.html 
sidebar: sidebar 
keywords: create, modify, volume, large file, large volume 
summary: 新しいボリュームの作成時や既存のボリュームの変更時に、大容量のボリュームやファイルのサポートを有効にすることができます。 
---
= ONTAPで大容量ファイルと大容量ファイルのサポートを有効にする
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
ONTAP 9.12.1 P2以降では、新しいボリュームを作成したり既存のボリュームを変更したりして、サポートされる最大ボリュームサイズを300TB、最大サイズを60PB、最大ファイル（LUN）サイズを128TBに変更したりできますlink:../flexgroup/definition-concept.html["FlexGroupボリューム"]。

.開始する前に
* ONTAP 9 .12.1 P2以降がクラスタにインストールされている。
* SnapMirror関係にあるソースクラスタで大容量ボリュームのサポートを有効にする場合は、ソースボリュームをホストするクラスタとデスティネーションボリュームをホストするクラスタにONTAP 9 .12.1 P2以降がインストールされている必要があります。
* クラスタ管理者またはSVM管理者である。
* この手順で説明されているコマンドの詳細については、をlink:https://docs.netapp.com/us-en/ontap-cli/["ONTAPコマンド リファレンス"^]参照してください。




== 新しいボリュームを作成する

.ステップ
. 大容量ボリュームでファイルのサポートが有効になっているボリュームを作成します。
+
[source, cli]
----
volume create -vserver <svm_name> -volume <volume_name> -aggregate <aggregate_name> -is-large-size-enabled true
----


.例
次の例は、大容量ボリュームとファイルサイズのサポートを有効にして新しいボリュームを作成します。

[listing]
----
volume create -vserver vs1 -volume big_vol1 -aggregate aggr1 -is-large-size-enabled true
----


== 既存のボリュームを変更する

.ステップ
. ボリュームを変更して、大容量ボリュームとファイルのサポートを有効にします。
+
[source, cli]
----
volume modify -vserver <svm_name> -volume <volume_name> -is-large-size-enabled true
----
+
.例
次の例は、大容量のボリュームとファイルサイズをサポートするように既存のボリュームを変更します。

+
[listing]
----
volume modify -vserver vs2 -volume data_vol -is-large-size-enabled true
----
. ボリュームを再マウントして新しい設定をアクティブ化します。
+
[source, cli]
----
volume unmount -vserver <svm_name> -volume <volume_name>
----
+
[source, cli]
----
volume mount -vserver <svm_name> -volume <volume_name>
----


.関連情報
* link:../volumes/create-volume-task.html["ボリュームの作成"]
* link:https://docs.netapp.com/us-en/ontap-cli/["コマンドリファレンス"]

