---
permalink: volumes/enable-storage-efficiency-visualization-concept.html 
sidebar: sidebar 
keywords: storage, efficiency, visualization, storage aggregate 
summary: システム内のすべてのアグリゲートのストレージ効率をさまざまなビューで確認できます。 
---
= ストレージ効率情報の表示
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
コマンドを使用して `storage aggregate show-efficiency`、システム内のすべてのアグリゲートのストレージ効率化に関する情報を表示します。

 `storage aggregate show-efficiency`コマンドには、コマンドオプションを渡すことで呼び出すことができる3つの異なるビューがあります。



== デフォルトビュー

デフォルトビューには、各アグリゲートの総削減率が表示されます。

`cluster1::> storage aggregate show-efficiency`



== 詳細ビュー

コマンドオプションを使用して詳細ビューを表示し `-details`ます。このビューには次の情報が表示されます。

* 各アグリゲートの総削減率
* Snapshotコピーを除いた総削減率
* 次の効率化テクノロジ別の削減率の内訳：ボリュームの重複排除、ボリュームの圧縮、Snapshotコピー、クローン、データ コンパクション、アグリゲートのインライン重複排除


`cluster1::> storage aggregate show-efficiency -details`



== アドバンスト ビュー

アドバンスト ビューは詳細ビューと似ていますが、使用済みの論理容量と物理容量の詳細がどちらも表示されます。

このコマンドは、advanced権限レベルで実行する必要があります。コマンドを使用してadvanced権限に切り替えます `set -privilege advanced`。

コマンドプロンプトがに変わります `cluster::*>`。

`cluster1::> set -privilege advanced`

コマンドオプションを使用して、アドバンストビューを呼び出し `-advanced`ます。

`cluster1::*> storage aggregate show-efficiency -advanced`

単一のアグリゲートの削減比率を個別に表示するには、コマンドを実行し `-aggregate _aggregate_name_`ます。このコマンドは、advanced権限レベルだけでなく、adminレベルでも実行できます。

`cluster1::> storage aggregate show-efficiency -aggregate aggr1`
