---
permalink: volumes/explicit-quotas-concept.html 
sidebar: sidebar 
keywords: how to, use, explicit, quotas 
summary: 明示的クォータは、特定のクォータ ターゲットに対してクォータを指定する場合、または特定のターゲットに対するデフォルト クォータを上書きする場合に使用できます。 
---
= 明示的クォータの使用方法
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
明示的クォータは、特定のクォータ ターゲットに対してクォータを指定する場合、または特定のターゲットに対するデフォルト クォータを上書きする場合に使用できます。

明示的クォータは、特定のユーザ、グループ、またはqtreeの制限を指定します。同じターゲットに設定されているデフォルト クォータがある場合は、明示的クォータによって置き換えられます。

派生ユーザ クォータを持つユーザに明示的ユーザ クォータを追加する場合は、デフォルト ユーザ クォータと同じユーザ マッピング設定を使用する必要があります。同じユーザ マッピング設定を使用しないと、クォータのサイズの変更時に、明示的ユーザ クォータが新しいクォータとみなされて拒否されます。

明示的クォータが影響するのは、同じレベル（ボリュームまたはqtree）のデフォルト クォータだけです。たとえば、qtreeの明示的ユーザ クォータが、そのqtreeを含むボリュームのデフォルト ユーザ クォータに影響することはありません。ただし、このqtreeの明示的ユーザ クォータは、そのqtreeのデフォルト ユーザ クォータを上書きします（制限を置き換えます）。

.明示的クォータの例
次のクォータ ルールでは、vol1の全ユーザのスペースを50MBに制限するというデフォルト ユーザ クォータが定義されています。ただし、jsmithというユーザだけは、明示的クォータ（太字）によりスペース制限が80MBに設定されています。

[listing]
----
cluster1::> volume quota policy rule create -vserver vs0 -volume vol1 -policy-name default -type user -target "" -qtree "" -disk-limit 50m

cluster1::> volume quota policy rule create -vserver vs0 -volume vol1 -policy-name default -type user -target "jsmith" -qtree "" -disk-limit 80m

cluster1::> volume quota policy rule show -vserver vs0 -volume vol1

Vserver: vs0               Policy: default           Volume: vol1
                                               Soft             Soft
                         User         Disk     Disk   Files    Files
Type   Target    Qtree   Mapping     Limit    Limit   Limit    Limit  Threshold
-----  --------  ------- -------  --------  -------  ------  -------  ---------
user   ""        ""      off          50MB        -       -        -          -
user   jsmith    ""      off          80MB        -       -        -          -
----
次のクォータ ルールは、4つのIDで表される指定されたユーザを、vol1ボリューム内の550MBのディスク スペースと10,000個のファイルに制限します：

[listing]
----
cluster1::> volume quota policy rule create -vserver vs0 -volume vol1 -policy-name default -type user -target " jsmith,corp\jsmith,engineering\john smith,S-1-5-32-544" -qtree "" -disk-limit 550m -file-limit 10000

cluster1::> volume quota policy rule show -vserver vs0 -volume vol1

Vserver: vs0               Policy: default           Volume: vol1
                                               Soft             Soft
                         User         Disk     Disk   Files    Files
Type   Target    Qtree   Mapping     Limit    Limit   Limit    Limit  Threshold
-----  --------  ------- -------  --------  -------  ------  -------  ---------
user   "jsmith,corp\jsmith,engineering\john smith,S-1-5-32-544"
                 ""      off         550MB        -   10000        -          -
----
次のクォータ ルールでは、eng1グループが、proj1 qtree内で使用できるディスク スペースを150MBに、ファイル数を無制限に制限しています。

[listing]
----
cluster1::> volume quota policy rule create -vserver vs0 -volume vol2 -policy-name default -type group -target "eng1" -qtree "proj1" -disk-limit 150m

cluster1::> volume quota policy rule show -vserver vs0 -volume vol2

Vserver: vs0               Policy: default           Volume: vol2
                                               Soft             Soft
                         User         Disk     Disk   Files    Files
Type   Target    Qtree   Mapping     Limit    Limit   Limit    Limit  Threshold
-----  --------  ------- -------  --------  -------  ------  -------  ---------
group  eng1      proj1   off         150MB        -       -        -          -
----
次のクォータ ルールは、vol2ボリューム内のproj1 qtreeを750MBのディスク領域と75,000個のファイルに制限します：

[listing]
----
cluster1::> volume quota policy rule create -vserver vs0 -volume vol2 -policy-name default -type tree -target "proj1" -disk-limit 750m -file-limit 75000

cluster1::> volume quota policy rule show -vserver vs0 -volume vol2

Vserver: vs0               Policy: default           Volume: vol2
                                               Soft             Soft
                         User         Disk     Disk   Files    Files
Type   Target    Qtree   Mapping     Limit    Limit   Limit    Limit  Threshold
-----  --------  ------- -------  --------  -------  ------  -------  ---------
tree   proj1     ""      -           750MB        -   75000        -          -
----