---
permalink: volumes/flexvol-reclaim-free-space-autodelete-concept.html 
sidebar: sidebar 
keywords: how, flexvol, volume, reclaim, free, space, autodelete, setting 
summary: FlexVol volumeの自動削除設定を有効にすると、FlexCloneファイルとFlexClone LUNを自動的に削除し、ボリューム内の空きスペースを再利用することができます。 
---
= FlexVolと自動削除による空きスペースの再生 - 概要
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
FlexVolの自動削除設定を有効にすると、FlexCloneファイルおよびFlexClone LUNを自動的に削除できます。自動削除を有効にすると、ボリュームがフルに近くなったときに、指定した量の空きスペースをボリュームに再生できます。

ボリュームの空きスペースが一定のしきい値を下回ったときにFlexCloneファイルおよびFlexClone LUNの削除を自動的に開始し、指定した量の空きスペースが再生されたときにクローンの削除を自動的に停止するようにボリュームを設定できます。クローンの自動削除を開始するしきい値を指定することはできませんが、あるクローンを削除対象に含めるかどうかや、ボリュームの空きスペースの目標量を指定することはできます。

ボリューム内の空き領域が特定のしきい値を下回り、次の_両方_の要件が満たされると、ボリュームはFlexCloneファイルとFlexClone LUNを自動的に削除します：

* 自動削除機能が、FlexCloneファイルおよびFlexClone LUNを含むボリュームに対して有効になっている。
+
 `volume snapshot autodelete modify`コマンドを使用して、FlexVolボリュームの自動削除機能を有効にできます。ボリュームでFlexCloneファイルとFlexClone LUNを自動的に削除するには、 `-trigger`パラメータを `volume`または `snap_reserve`に設定する必要があります。link:https://docs.netapp.com/us-en/ontap-cli/volume-snapshot-autodelete-modify.html["ONTAPコマンド リファレンス"^]の `volume snapshot autodelete modify`の詳細をご覧ください。

* 自動削除機能が、FlexCloneファイルおよびFlexClone LUNに対して有効になっている。
+
 `file clone create`コマンドに `-autodelete`パラメータを指定することで、FlexCloneファイルまたはFlexClone LUNの自動削除を有効にできます。これにより、クローンの自動削除を無効にし、他のボリューム設定がクローン設定を上書きしないようにすることで、特定のFlexCloneファイルとFlexClone LUNを保持できます。link:https://docs.netapp.com/us-en/ontap-cli/search.html?q=file+clone+create["ONTAPコマンド リファレンス"^]で `file clone create`の詳細を確認してください。


