---
permalink: volumes/flexclone-efficient-copies-concept.html 
sidebar: sidebar 
keywords: use, flexclone, volumes, create, efficient, copies, flexvol volumes 
summary: FlexCloneボリュームは、親FlexVol volumeの書き込み可能でスペース効率に優れたポイントインタイムコピーで、データ保護などの目的で管理できます。 
---
= FlexCloneボリュームの使用の概要
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
FlexCloneボリュームは、親FlexVol volumeの書き込み可能なポイントインタイムコピーです。FlexCloneボリュームは共通のデータについて親FlexVolと同じデータブロックを共有するため、スペース効率に優れています。FlexCloneボリュームの作成に使用されるSnapshotコピーも親ボリュームと共有されます。

既存のFlexCloneボリュームをクローニングして、別のFlexCloneボリュームを作成できます。LUNとLUNクローンを含むFlexVol volumeのクローンを作成することもできます。

FlexCloneボリュームを親ボリュームからスプリットすることもできます。ONTAP 9 .4以降では、AFFシステムのボリュームギャランティがnonである場合、FlexCloneのスプリット処理では物理ブロックが共有され、データはコピーされません。したがって、AFFシステムのFlexCloneボリュームのスプリットは、ONTAP 9 .4以降のリリースの他のFASシステムのFlexCloneスプリット処理よりも高速です。

2種類のFlexClone（読み書き可能FlexCloneボリュームとデータ保護FlexCloneボリューム）を作成できます。通常のFlexVol volumeの読み書き可能FlexCloneボリュームは作成できますが、データ保護FlexCloneボリュームの作成にはSnapVaultセカンダリボリュームのみを使用する必要があります。
