---
permalink: volumes/logical-space-reporting-concept.html 
sidebar: sidebar 
keywords: what, logical, space, reporting, shows 
summary: ボリュームで論理スペースのレポートを有効にすると、ボリュームの合計スペースに加えて使用済みの論理スペースと使用可能な論理スペースの量も表示されます。また、 Linux および Windows クライアントシステムのユーザは、使用済みの物理スペースと使用可能な物理スペースではなく、使用済みの論理スペースと使用可能な論理スペースを確認できます。 
---
= 論理スペースレポートの内容
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
ボリュームで論理スペースのレポートを有効にすると、ボリュームの合計スペースに加えて使用済みの論理スペースと使用可能な論理スペースの量も表示されます。また、 Linux および Windows クライアントシステムのユーザは、使用済みの物理スペースと使用可能な物理スペースではなく、使用済みの論理スペースと使用可能な論理スペースを確認できます。

定義：

* 物理スペースとは、ボリュームで使用可能または使用されているストレージの物理ブロックのことです。
* 論理スペースとは、ボリューム内の使用可能なスペースのことです。
* 使用済みの論理スペースに加えて、設定済みの Storage Efficiency 機能（重複排除や圧縮など）による削減効果も表示されます。


ONTAP 9.5 以降では、論理スペースの適用とスペースのレポートを有効にすることができます。

有効にすると ' 論理スペース・レポートには 'volume show コマンドを使用して次のパラメータが表示されます

[cols="25%,75%"]
|===
| パラメータ | 意味 


 a| 
「 -logical-used 」と入力します
 a| 
使用済み論理サイズが指定した値に一致するボリュームに関する情報のみを表示します。この値には、 Storage Efficiency 機能で削減されたすべてのスペースと物理的に使用されているスペースが含まれます。Snapshot リザーブは含まれませんが、 Snapshot オーバーフローは考慮されます。



 a| 
「 -logical-Used-by-afs` 」
 a| 
アクティブファイルシステムで使用されている論理サイズが指定した値に一致するボリュームに関する情報のみを表示します。この値は、 Snapshot リザーブを超過する Snapshot オーバーフローの量によって「 -logical-used 」の値とは異なります。



 a| 
「 -logical-available 」と入力します
 a| 
論理スペースのレポートのみが有効になっている場合は、使用可能な物理スペースのみが表示されます。スペースのレポートと適用の両方が有効な場合、 Storage Efficiency 機能によって削減されたスペースを考慮して現在使用可能な空きスペースの量が表示されます。これには Snapshot リザーブは含まれません。



 a| 
「 -logical-used - percent 」と入力します
 a| 
ボリュームの Snapshot リザーブを除いた、プロビジョニングされたサイズに対する現在の「 -logical-used 」値の割合を表示します。

「 -logical-Used-by-AFS 」の値にはボリューム内の削減効果が含まれているため、この値は 100% よりも大きくなります。ボリュームの「 -logical-Used-by-af' 」の値には、使用済みスペースとしての Snapshot オーバーフローは含まれていません。ボリュームの「 -dphysical-used 」の値には、 Snapshot オーバーフローが使用済みスペースとして含まれます。



 a| 
` - 使用済み」
 a| 
Storage Efficiency 機能で削減されたスペースを考慮せずに使用されているスペースが表示されます。

|===
CLI で論理スペースのレポートを有効にすると、 Logical Used Space （ % ）値と Logical Space 値も System Manager に表示されます

クライアント・システムでは ' 次のシステム・ディスプレイに論理スペースが使用済みスペースとして表示されます

* * Linux システムでの df * 出力
* Windows システムの Windows エクスプローラを使用したプロパティの領域の詳細。


[NOTE]
====
論理スペースの適用なしで論理スペースのレポートが有効になっている場合は、クライアントシステムに表示される合計容量が、プロビジョニングされたスペースよりも大きくなる可能性があります。

====