---
permalink: volumes/logical-space-enforcement-concept.html 
sidebar: sidebar 
keywords: what, logical, space, enforcement, does 
summary: ONTAP 9.5以降で論理スペースの強制を有効にすると、ボリュームがいっぱいになったとき、またはほぼいっぱいになったときにユーザーに通知されます。 
---
= 論理スペースの適用
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
論理スペースの適用により、ボリュームがフルまたはほぼフルになったときにユーザに通知されます。ONTAP 9.5以降で論理スペースの適用機能が有効な場合、ONTAPはボリューム内の使用済み論理ブロック数をカウントすることで、使用可能な残りのスペースを算出します。ボリュームに使用可能なスペースがない場合、ENOSPC（スペース不足）エラー メッセージが返されます。

論理スペースの適用から、ボリュームの使用可能スペースについて3種類のアラートが返されます。

* `Monitor.vol.full.inc.sav`：このアラートは、ボリューム内の論理スペースの 98% が使用されているときにトリガーされます。
* `Monitor.vol.nearFull.inc.sav`：このアラートは、ボリューム内の論理スペースの 95% が使用されているときにトリガーされます。
* `Vol.log.overalloc.inc.sav`：このアラートは、ボリュームで使用されている論理スペースがボリュームの合計サイズより大きい場合にトリガーされます。
+
このアラートは、過剰に割り当てられた論理ブロックによってボリュームがすでに使用されているため、ボリュームのサイズを大きくしても、使用可能なスペースが作成されない可能性があることを示します。



[NOTE]
====
合計（論理スペース）は、論理スペース強制によるボリュームのSnapshot予約を除くプロビジョニングされたスペースと等しくする必要があります。

====
詳細については、link:../volumes/configure-automatic-provide-space-when-full-task.html["ボリュームがフルになったときにスペースを自動的に確保するための設定"]を参照してください。
