---
permalink: volumes/ls-command-space-usage-concept.html 
sidebar: sidebar 
keywords: how, ls command, accounts, space, usage 
summary: クォータレポートは、ファイルのサイズのみを表示するlsコマンドの出力とは異なる場合があります。この出力には、ファイルによって使用される間接ブロックは含まれません。 
---
= lsコマンドとクォータレポートのスペース使用量の不一致
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
 `ls`コマンドを使用してUNIXクライアントにマウントされたFlexVol volumeの内容を表示する場合、出力に表示されるファイルサイズは、ファイルのデータブロックのタイプに応じて、ボリュームのクォータレポートに表示されるスペース使用量と異なることがあります。

コマンドの出力 `ls`には、ファイルサイズのみが表示され、ファイルで使用される間接ブロックは含まれません。ファイルの空ブロックも、コマンドの出力に含まれます。

したがって、空ブロックがないファイルの場合、コマンドによって表示されるサイズは `ls`、クォータレポートのディスク使用量よりも少なくなる可能性があります。これは、クォータレポートに間接ブロックが含まれるためです。逆に、ファイルに空ブロックがある場合、コマンドによって表示されるサイズは `ls`、クォータレポートで指定されたディスク使用量よりも多くなることがあります。

コマンドの出力 `ls`には、ファイルサイズのみが表示され、ファイルで使用される間接ブロックは含まれません。ファイルの空ブロックも、コマンドの出力に含まれます。

.lsコマンドとクォータレポートにおけるスペース使用量の違いの例
次のクォータレポートには、 qtree q1 の制限が 10MB であると表示されています。

[listing]
----

                                      ----Disk----  ----Files-----   Quota
  Volume   Tree      Type    ID        Used  Limit    Used   Limit   Specifier
  -------  --------  ------  -------  -----  -----  ------  ------   ---------
  vol1     q1          tree    user1   10MB  10MB        1       -   q1

...
----
UNIXクライアントからコマンドを使用して表示した場合、次の例に示すように、同じqtree内のファイルのサイズがクォータ制限を超えることがあります `ls`。

[listing]
----
[user1@lin-sys1 q1]$ ls -lh
-rwxr-xr-x  1 user1 nfsuser  **27M** Apr 09  2013 file1
----
の詳細については `ls`、をlink:https://docs.netapp.com/us-en/ontap-cli/search.html?q=ls["ONTAPコマンド リファレンス"^]参照してください。
