---
permalink: volumes/manage-inline-data-compaction-aff-task.html 
sidebar: sidebar 
keywords: manage, inline, data, compaction, aff, systems 
summary: AFFシステムでインラインデータコンパクションをボリュームレベルで制御するには、volume efficiency modifyコマンドを使用します。 
---
= AFF システムのインラインデータコンパクションを管理します
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
AFF システムでインラインデータコンパクションをボリュームレベルで制御するには、を使用します `volume efficiency modify` コマンドを実行しますAFF システム上のすべてのボリュームでは、データコンパクションがデフォルトで有効になっています。

.作業を開始する前に
データコンパクションを使用するには、ボリュームのスペースギャランティをに設定する必要があります `none`。これは AFF システムのデフォルトです。

[NOTE]
====
AFF 以外のデータ保護ボリュームでは、デフォルトのスペースギャランティが none に設定されます。

====
.手順
. ボリュームのスペースギャランティ設定を確認するには、次の手順を実行します。
+
`volume show -vserver vserver_name -volume volume_name –fields space-guarantee`

. データコンパクションを有効にするには、次の
+
`volume efficiency modify -vserver vserver_name -volume volume_name -data-compaction true`

. データコンパクションを無効にする場合：
+
`volume efficiency modify -vserver vserver_name -volume volume_name -data-compaction false`

. データコンパクションのステータスを表示するには：
+
`volume efficiency show -instance`



.例
`cluster1::> volume efficiency modify -vserver vs1 -volume vol1 -data-compaction true` `cluster1::> volume efficiency modify -vserver vs1 -volume vol1 -data-compaction false`
