---
permalink: volumes/move-between-secondary-adaptive-compression-task.html 
sidebar: sidebar 
keywords: move, secondary compression, adaptive compression 
summary: データの読み取り量に応じて、二次圧縮と適応圧縮を切り替えることができます。ランダムリードの量が多く、高いパフォーマンスが要求されるシステムには、適応圧縮が適しています。データがシーケンシャルに書き込まれ、圧縮で多くの量を削減することが要求される場合は、二次圧縮が適しています。 
---
= 二次圧縮と適応圧縮を切り替えます
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
データの読み取り量に応じて、二次圧縮と適応圧縮を切り替えることができます。ランダムリードの量が多く、高いパフォーマンスが要求されるシステムには、適応圧縮が適しています。データがシーケンシャルに書き込まれ、圧縮で多くの量を削減することが要求される場合は、二次圧縮が適しています。

.このタスクについて
デフォルトの圧縮形式は、使用するアグリゲートとプラットフォームに基づいて選択されます。

.手順
. ボリュームの効率化を無効にします。
+
`volume efficiency off`

+
たとえば、次のコマンドは、ボリュームvol1の効率化を無効にします。

+
`volume efficiency off -vserver vs1 -volume vol1`

. advanced 権限レベルに切り替えます。
+
`set -privilege advanced`

. 圧縮データを解凍します。
+
`volume efficiency undo`

+
たとえば、次のコマンドは、ボリュームvol1上の圧縮データを解凍します。

+
`volume efficiency undo -vserver vs1 -volume vol1 -compression true`

+
[NOTE]
====
圧縮データを格納するための十分なスペースがボリュームにあることを確認する必要があります。

====
. admin 権限レベルに切り替えます。
+
`set -privilege admin`

. 処理のステータスがアイドルであることを確認します。
+
`volume efficiency show`

+
たとえば、次のコマンドは、ボリュームvol1に対する効率化処理のステータスを表示します。

+
`volume efficiency show -vserver vs1 -volume vol1`

. ボリュームの効率化を有効にします。
+
`volume efficiency on` たとえば、次のコマンドは、ボリュームvol1で効率化を有効にします。

+
`volume efficiency on -vserver vs1 -volume vol1`

. データ圧縮を有効にして、圧縮形式を設定します。
+
`volume efficiency modify`

+
たとえば、次のコマンドは、ボリュームvol1でデータ圧縮を有効にし、圧縮形式を二次圧縮に設定します。

+
`volume efficiency modify -vserver vs1 -volume vol1 -compression true -compression-type secondary`

+
[NOTE]
====
この手順では、ボリュームで二次圧縮が有効になるだけで、ボリューム上のデータは圧縮されません。

** AFF システムで既存のデータを圧縮するには、バックグラウンド圧縮スキャナを実行する必要があります。
** Flash Pool アグリゲートまたは HDD アグリゲートで既存のデータを圧縮するには、バックグラウンド圧縮を実行する必要があります。


====
. オプション：インライン圧縮を有効にします。
+
`volume efficiency modify`

+
たとえば、次のコマンドは、ボリュームvol1でインライン圧縮を有効にします。

+
`volume efficiency modify -vserver vs1 -volume vol1 -inline-compression true`


