---
permalink: volumes/move-volume-concept.html 
sidebar: sidebar 
keywords: how, move, flexvol, volume, works 
summary: 処理中のFlexVol volumeの移動とクライアントアクセスの各フェーズについて理解します。 
---
= FlexVol volumeの移動の概要
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
容量利用率やパフォーマンスの向上、およびサービスレベル契約を満たすために、ボリュームを移動またはコピーできます。FlexVol ボリュームの移動の仕組みを理解しておくと、ボリュームの移動がサービスレベル契約を満たすかどうかの判断や、ボリューム移動がボリューム移動プロセスのどの段階にあるかを把握するのに役立ちます。

FlexVolボリュームは、1つのアグリゲートまたはノードから同じStorage Virtual Machine（SVM）内の別のアグリゲートまたはノードに移動されます。ボリュームを移動しても、移動中にクライアントアクセスが中断されることはありません。


NOTE: ボリューム移動処理のカットオーバーフェーズ中は、 FlexVol ボリュームの FlexClone ファイルまたは FlexClone LUN を作成することはできません。

ボリュームの移動は次のように複数のフェーズで行われます。

* 新しいボリュームがデスティネーションアグリゲート上に作成されます。
* 元のボリュームのデータが新しいボリュームにコピーされます。
+
この間、元のボリュームはそのままで、クライアントからアクセス可能です。

* 移動プロセスの最後に、クライアントアクセスが一時的にブロックされます。
+
この間にソースボリュームからデスティネーションボリュームへの最終レプリケーションが実行され、ソースボリュームとデスティネーションボリュームの ID がスワップされ、デスティネーションボリュームがソースボリュームに変更されます。

* 移動が完了すると、クライアントトラフィックが新しいソースボリュームにルーティングされ、クライアントアクセスが再開されます。


クライアントアクセスのブロックはクライアントが中断とタイムアウトを認識する前に終了するため、移動によってクライアントアクセスが中断されることはありません。デフォルトでは、クライアントアクセスは30秒間ブロックされます。アクセスが拒否されている間にボリューム移動操作が完了しなかった場合、この最終フェーズは中止されてクライアントアクセスが許可されます。デフォルトでは、最終フェーズは3回試行されます。3回目の試行後、システムは1時間待機してから最後のフェーズシーケンスを再試行します。ボリューム移動処理の最後のフェーズは、ボリューム移動が完了するまで実行されます。
