---
permalink: volumes/ndmp-dump-flexclone-files-luns-concept.html 
sidebar: sidebar 
keywords: how, ndmp, works, flexclone files, flexclone luns 
summary: NDMPはFlexCloneファイルとFlexClone LUNの論理レベルで動作します。すべてのFlexCloneファイルまたはLUNは個別のファイルまたはLUNとしてバックアップされます。 
---
= FlexCloneファイルおよびFlexClone LUNとNDMP
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
NDMPはFlexCloneファイルとFlexClone LUNの論理レベルで動作します。すべてのFlexCloneファイルまたはLUNは個別のファイルまたはLUNとしてバックアップされます。

NDMPサービスを使用して、FlexCloneファイルやFlexCloneLUNを含むqtreeまたはFlexVol volumeをバックアップする場合、親エンティティとクローンエンティティ間のブロック共有は保持されず、クローンエンティティは個別のファイルまたはLUNとしてテープにバックアップされます。スペースの節約効果は失われます。そのため、バックアップ先のテープには、増加したデータ量を保存できる十分な空き容量が必要です。リストア時には、すべてのFlexCloneファイルおよびFlexCloneLUNが個別の物理ファイルおよびLUNとしてリストアされます。ブロック共有のメリットを復元するには、ボリュームで重複排除を有効にすることができます。

[NOTE]
====
FlexCloneファイルとFlexClone LUNをFlexVol volumeの既存のスナップショットから作成している場合、バックグラウンドで実行されるブロック共有プロセスが完了するまで、ボリュームをテープにバックアップすることはできません。ブロック共有プロセスの進行中にボリュームでNDMPを使用すると、しばらくしてから操作を再試行するように求めるメッセージが表示されます。このような状況では、ブロック共有の完了後にテープ バックアップ操作が成功するように、再試行を続ける必要があります。

====