---
permalink: volumes/qtrees-partition-your-volumes-concept.html 
sidebar: sidebar 
keywords: volumes, volume partitioning, qtrees, flexvol volumes, performance, metrics, extended performance monitoring 
summary: qtreeを使用すると、FlexVolを小さなセグメントにパーティショニングして、それぞれ個別に管理できます。qtreeによって有効になるボリューム パーティショニングを使用すると、プロジェクト、ユーザ、またはグループごとにストレージをより細かく管理できます。qtreeを使用すると、クォータ、セキュリティ形式、およびCIFS oplockの管理を効率化できます。 
---
= qtreeとONTAP FlexVolのパーティショニング
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
qtreeを使用すると、FlexVolを小さなセグメントにパーティショニングして、それぞれ個別に管理できます。qtreeによって有効になるボリューム パーティショニングを使用すると、プロジェクト、ユーザ、またはグループごとにストレージをより細かく管理できます。qtreeを使用すると、クォータ、セキュリティ形式、およびCIFS oplockの管理を効率化できます。


NOTE: ONTAPは、各ボリュームに*qtree0*という名前のデフォルトのqtreeを作成します。特定のqtreeにデータを配置しない場合、そのデータはqtree0に配置されます。



== 一般的な制限事項

本番環境でqtreeを使用する前に、qtreeの制限事項を理解しておく必要があります。また、拡張qtreeパフォーマンス監視機能を使用する場合は、<<運用と制限事項>>を確認してください。

* qtree名の最大文字数は64文字です。
* qtree名に一部の特殊な文字（カンマやスペースなど）を使用すると、その他のONTAP機能に問題が発生する可能性があるので、使用しないでください。
* 異なるqtree間でディレクトリを移動することはできません。qtree間で移動できるのはファイルだけです。
* qtreeレベルの共有とボリュームレベルの共有を同じFlexVolまたはSCVMMプールに作成すると、qtreeはFlexVol共有上のディレクトリとして表示されます。それらを誤って削除しないように注意する必要があります。




== qtreeの管理および設定用コマンド

ONTAP CLIを使用して、qtreeを管理および設定することができます。目的に応じて、次のコマンドを使用してqtreeを管理する必要があります。

[NOTE]
====
このコマンド `volume rehost`により、同じボリュームを対象とする他の同時管理操作が失敗する可能性があります。

====
|===


| 状況 | 使用するコマンド 


 a| 
qtreeを作成する
 a| 
`volume qtree create`



 a| 
フィルタリングされたqtreeリストを表示する
 a| 
`volume qtree show`



 a| 
qtreeを削除する
 a| 
`volume qtree delete`


NOTE: qtreeが空であるか `-force true`フラグが使用されていない限り、このコマンドは失敗します。



 a| 
qtreeのUNIXの権限を変更する
 a| 
`volume qtree modify -unix-permissions`



 a| 
qtreeのCIFS oplock設定を変更する
 a| 
`volume qtree oplocks`



 a| 
qtreeのセキュリティ設定を変更する
 a| 
`volume qtree security`



 a| 
qtreeの名前を変更する
 a| 
`volume qtree rename`



 a| 
qtreeの統計情報を表示する
 a| 
`volume qtree statistics`



 a| 
qtreeの統計情報をリセットする
 a| 
`volume qtree statistics -reset`

|===


== 拡張qtreeパフォーマンス監視

ONTAP 9.16.1以降では、ONTAP REST APIを使用して、レイテンシ指標や履歴統計などの拡張qtree監視機能にアクセスできます。

ONTAP REST APIには、qtreeに関連するエンドポイントがいくつか含まれています。ONTAP 9.16.1より前のバージョンでは、1秒あたりのIO処理数（IOPS）や、読み取り、書き込み、その他の処理のスループットなど、qtreeのリアルタイム統計にアクセスできました。

ONTAP 9.16.1以降では、拡張qtreeパフォーマンス監視を使用して、NFSv3、NFSv4.0、NFSv4.1、NFSv4.2、pNFS（技術的にはNFSv4.1およびNFSv4.2の一部）、およびCIFSのリアルタイムのレイテンシ統計、IOPSおよびスループットを監視できます。また、統計を収集してアーカイブし、過去のパフォーマンス データを表示できます。

この拡張監視により、ストレージ管理者はシステム パフォーマンスをより詳細に把握できます。このデータを使用することで、サービス品質の向上に取り組む際に、使用率の高いqtreeや、潜在的なボトルネックなどの領域を特定できます。長期的な傾向など、これらの指標を分析できれば、より多くの情報に基づいてデータ主体の意思決定を下すことができます。



=== 運用と制限事項

本番環境で拡張qtreeパフォーマンス監視機能を使用する前に、制限事項など、いくつかの運用特性を考慮する必要があります。

.再マウントが必要
qtree拡張監視を有効にしたあと、影響を受けるボリュームを再マウントしてこの機能をアクティブ化する必要があります。

.統計の可用性
拡張パフォーマンス監視を有効にしても、統計データはすぐには使用できません。これには、IOPS、スループット、レイテンシの統計が含まれます。qtreeのこのデータが表示されるまでに最大5分かかることがあります。

.クラスタあたりのqtree数
ONTAPクラスタでは、最大50,000個のqtreeに対して拡張パフォーマンス モニタリングを有効にできます。



=== ONTAP REST APIを使用した拡張指標へのアクセス

ONTAP 9.16.1以降では、ONTAP REST APIを使用して、qtree拡張パフォーマンス監視にアクセスできます。基本機能は、次のようにいくつかのカテゴリに分類されます。

.拡張パフォーマンス監視の有効化と無効化
 `ext_performance_monitoring.enabled`プロパティにアクセスするには、エンドポイント `/api/storage/qtrees`で拡張監視機能を有効または無効にすることができます。新しいqtreeを作成するか、既存のqtreeを設定するかに応じて、POSTメソッドとPATCHメソッドを使用できます。

.グローバル監視の指標と設定の取得
 `/api/storage/qtrees`エンドポイントにいくつかの新しいグローバル プロパティが追加されました。これらのフィールドはGETメソッドを使用して取得できます。

.特定のqtreeの指標の取得
エンドポイントで GET メソッドを使用して `/api/storage/qtrees/{volume.uuid}/{id}/metrics`、特定のボリュームで定義されている特定の qtree の新しい統計およびメトリックのプロパティを取得できます。



=== アップグレードとリバート

ONTAP 9.16.1でこの機能を有効にすると、制限なしで後続のONTAPリリースにアップグレードできます。ただし、2つのシナリオを考慮する必要があります。

.9.16.1へのアップグレードとバージョンが混在するクラスタの処理
クラスタの有効なクラスタ バージョン（ECV）が9.16.1になるまで、拡張パフォーマンス モニタリング機能は使用できません（つまり、 `ext_performance_monitoring.enabled`を `true`に設定できません）。

.9.16.1からのリバート
いずれかのqtreeのプロパティ `ext_performance_monitoring.enabled`が `true`に設定されている場合、9.16.1から9.15.1へのリバートは許可されません。リバート処理はブロックされます。ベスト プラクティスとして、以前のONTAPリリースにリバートする前に、すべてのqtreeの `ext_performance_monitoring.enabled`を `false`に設定してください。



=== 詳細情報

ONTAP REST API https://docs.netapp.com/us-en/ontap-automation/whats-new.html["ONTAP REST APIの新機能"^]の詳細については、ONTAP自動化ドキュメントを参照してください。ONTAP REST API https://docs.netapp.com/us-en/ontap-automation/reference/api_reference.html["qtreeエンドポイント"^]の詳細については、ONTAP自動化ドキュメントも確認してください。
