---
permalink: volumes/quota-report-quotas-effect-concept.html 
sidebar: sidebar 
keywords: how, use, quota report, see, quotas in effect 
summary: クォータレポートを表示して、明示的に作成したクォータよりも有効になっているクォータを確認します。 
---
= クォータレポートを使用して有効なクォータを確認する
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
クォータはさまざまな方法で作用するため、明示的に作成したクォータよりも多くのクォータが有効になります。有効なクォータを確認するには、クォータレポートを表示します。

次の例は、FlexVol volume vol1と、そのボリュームに含まれるqtree q1に適用されている各種クォータのクォータレポートを表示します。

.qtreeにユーザクォータが指定されていない例
この例では、ボリュームvol1に含まれるqtree q1が1つあります。管理者が3つのクォータを作成しました。

* vol1に対するデフォルトのツリークォータ制限は400MB
* vol1に対して100MBのデフォルトユーザクォータ制限
* ユーザjsmith用にvol1に対して200MBの明示的ユーザクォータ制限


これらのクォータのクォータルールは、次の例のようになります。

[listing]
----
cluster1::*> volume quota policy rule show -vserver vs1 -volume vol1

Vserver: vs1               Policy: default           Volume: vol1
                                               Soft             Soft
                         User         Disk     Disk   Files    Files
Type   Target    Qtree   Mapping     Limit    Limit   Limit    Limit  Threshold
-----  --------  ------- -------  --------  -------  ------  -------  ---------
tree   ""        ""      -           400MB        -       -        -          -
user   ""        ""      off         100MB        -       -        -          -
user   jsmith    ""      off         200MB        -       -        -          -
----
これらのクォータのクォータレポートの例を次に示します。

[listing]
----
cluster1::> volume quota report
Vserver: vs1
                                    ----Disk----  ----Files-----   Quota
Volume   Tree      Type    ID        Used  Limit    Used   Limit   Specifier
-------  --------  ------  -------  -----  -----  ------  ------   ---------
vol1     -          tree   *           0B  400MB       0       -   *
vol1     -          user   *           0B  100MB       0       -   *
vol1     -          user   jsmith    150B  200MB       7       -   jsmith
vol1     q1         tree   1           0B  400MB       6       -   q1
vol1     q1         user   *           0B  100MB       0       -
vol1     q1         user   jsmith      0B  100MB       5       -
vol1     -          user   root        0B    0MB       1       -
vol1     q1         user   root        0B    0MB       8       -
----
クォータレポートの最初の3行には、管理者が指定した3つのクォータが表示されます。これらのクォータのうち2つはデフォルトクォータであるため、ONTAPによって自動的に派生クォータが作成されます。

4行目には、vol1のすべてのqtree（この例ではq1のみ）のデフォルトツリークォータから派生するツリークォータが表示されます。

5行目には、ボリュームにデフォルトユーザクォータが存在することによってqtreeに作成されるデフォルトユーザクォータとqtreeクォータが表示されます。

6行目には、qtreeのjsmithに作成される派生ユーザクォータが表示されます。これは、qtreeにはデフォルトユーザクォータ（5行目）があり、ユーザjsmithがそのqtreeのファイルを所有しているためです。qtree q1のユーザjsmithに適用される制限は、明示的ユーザクォータ制限（200MB）では決定されません。これは、明示的ユーザクォータ制限がボリュームに対して適用されるため、qtreeの制限には影響しないためです。代わりに、qtreeの派生ユーザクォータ制限は、qtreeのデフォルトユーザクォータ（100MB）で決定されます。

最後の2行には、そのボリュームおよびqtreeのデフォルトユーザクォータから派生するその他のユーザクォータが表示されます。rootユーザがボリュームとqtreeの両方にファイルを所有しているため、ボリュームとqtreeの両方のrootユーザに派生ユーザクォータが作成されました。rootユーザはクォータに関して特別な扱いを受けるため、rootユーザの派生クォータは追跡クォータのみです。

.qtreeにユーザクォータを指定した例
この例は前の例に似ていますが、管理者がqtreeに2つのクォータを追加している点が異なります。

ボリュームは1つ（vol1）、qtreeは1つ（q1）です。管理者が次のクォータを作成しました。

* vol1に対するデフォルトのツリークォータ制限は400MB
* vol1に対して100MBのデフォルトユーザクォータ制限
* ユーザjsmithのためにvol1に対して200MBの明示的ユーザクォータ制限
* qtree q1に対する50MBのデフォルトユーザクォータ制限
* ユーザjsmithのためにqtree q1に対して75MBの明示的ユーザクォータ制限


これらのクォータのクォータルールは次のようになります。

[listing]
----
cluster1::> volume quota policy rule show -vserver vs1 -volume vol1

Vserver: vs1               Policy: default           Volume: vol1
                                               Soft             Soft
                         User         Disk     Disk   Files    Files
Type   Target    Qtree   Mapping     Limit    Limit   Limit    Limit  Threshold
-----  --------  ------- -------  --------  -------  ------  -------  ---------
tree   ""        ""      -           400MB        -       -        -          -
user   ""        ""      off         100MB        -       -        -          -
user   ""        q1      off          50MB        -       -        -          -
user   jsmith    ""      off         200MB        -       -        -          -
user   jsmith    q1      off          75MB        -       -        -          -
----
これらのクォータのクォータレポートは次のようになります。

[listing]
----

cluster1::> volume quota report
Vserver: vs1
                                    ----Disk----  ----Files-----   Quota
Volume   Tree      Type    ID        Used  Limit    Used   Limit   Specifier
-------  --------  ------  -------  -----  -----  ------  ------   ---------
vol1     -          tree   *           0B  400MB       0       -   *
vol1     -          user   *           0B  100MB       0       -   *
vol1     -          user   jsmith   2000B  200MB       7       -   jsmith
vol1     q1         user   *           0B   50MB       0       -   *
vol1     q1         user   jsmith      0B   75MB       5       -   jsmith
vol1     q1         tree   1           0B  400MB       6       -   q1
vol1     -          user   root        0B    0MB       2       -
vol1     q1         user   root        0B    0MB       1       -
----
クォータレポートの最初の5行には、管理者によって作成された5つのクォータが表示されます。これらのクォータの一部はデフォルトクォータであるため、ONTAPによって自動的に派生クォータが作成されます。

6行目には、vol1のすべてのqtree（この例ではq1のみ）のデフォルトツリークォータから派生するツリークォータが表示されます。

最後の2行には、そのボリュームおよびqtreeのデフォルトユーザクォータから派生するユーザクォータが表示されます。rootユーザがボリュームとqtreeの両方にファイルを所有しているため、ボリュームとqtreeの両方のrootユーザに派生ユーザクォータが作成されました。rootユーザはクォータに関して特別な扱いを受けるため、rootユーザの派生クォータは追跡クォータのみです。

次の理由により、他のデフォルトクォータまたは派生クォータは作成されませんでした。

* このユーザにはすでに両方のレベルで明示的クォータが設定されているため、ボリュームとqtreeの両方にファイルを所有していても、jsmithユーザに派生ユーザクォータは作成されませんでした。
* このボリュームまたはqtreeに他のユーザがファイルを所有していないため、他のユーザに派生ユーザクォータは作成されませんでした。
* qtreeにはすでにデフォルトユーザクォータが設定されているため、このボリュームのデフォルトユーザクォータによってqtreeにデフォルトユーザクォータが作成されませんでした。

