---
permalink: volumes/quotas-activated-concept.html 
sidebar: sidebar 
keywords: quotas, how quotas are activated, quota activation 
summary: 新しいクォータおよび既存のクォータに対する変更を有効にするには、アクティブ化する必要があります。アクティブ化はボリュームレベルで実行されます。クォータのアクティブ化の仕組みを理解しておくと、システム停止を抑えてクォータを管理するのに役立ちます。 
---
= クォータをアクティブ化する方法の概要
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
新しいクォータおよび既存のクォータに対する変更を有効にするには、アクティブ化する必要があります。アクティブ化はボリュームレベルで実行されます。クォータのアクティブ化の仕組みを理解しておくと、システム停止を抑えてクォータを管理するのに役立ちます。

クォータは、 _initializing （有効にする）または _resizing _ でアクティブ化されます。クォータを無効にして再度有効にすることを再初期化と呼びます。

アクティブ化にかかる時間とアクティブ化がクォータ適用に及ぼす影響は、アクティブ化のタイプによって異なります。

* 初期化プロセスは、ジョブとボリュームのファイルシステム全体のクォータスキャンの2つの部分で `quota on`構成されます。スキャンは、ジョブが正常に完了した後に開始され `quota on`ます。クォータスキャンには時間がかかることがあります。ボリュームのファイル数が多いほど、スキャンにかかる時間は長くなります。スキャンが完了するまで、クォータのアクティブ化は完了せず、クォータも適用されません。
* サイズ変更プロセスにはジョブのみが含まれ `quota resize`ます。サイズ変更にはクォータスキャンが含まれないため、クォータの初期化よりも短時間で完了します。サイズ変更プロセス中もクォータは引き続き適用されます。


デフォルトでは `quota on`、および `quota resize`ジョブはバックグラウンドで実行されるため、他のコマンドを同時に使用できます。

アクティブ化プロセスのエラーと警告は、イベント管理システムに送信されます。パラメータをコマンドまたは `volume quota resize`コマンドとともに `volume quota on`使用する `-foreground`と、ジョブが完了するまでコマンドは戻りません。これは、スクリプトから再初期化する場合に便利です。あとでエラーや警告を表示するには、パラメータを指定してコマンドを `-instance`使用し `volume quota show`ます。

クォータのアクティブ化は、停止およびリブート後も維持されます。クォータのアクティブ化プロセスは、ストレージシステムデータの可用性には影響しません。
