---
permalink: volumes/quota-notifications-concept.html 
sidebar: sidebar 
keywords: understanding, quota, notifications 
summary: クォータ通知は Event Management System （ EMS ；イベント管理システム）に送信されるメッセージであり、 SNMP トラップとしても設定されます。 
---
= クォータ通知について
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
クォータ通知は Event Management System （ EMS ；イベント管理システム）に送信されるメッセージであり、 SNMP トラップとしても設定されます。

通知は次のイベントに対応して送信されます。

* つまり、ハードクォータに達したときに、クォータを超えようとしたときです
* ソフトクォータを超えています
* ソフトクォータを超過しなくなりました


しきい値は他のソフトクォータとは若干異なります。しきい値を指定した場合に通知がトリガーされるのは、しきい値を超えた場合だけです。しきい値を超えた場合は

ハードクォータ通知は volume quota modify コマンドを使用して設定できます。不必要なメッセージが送信されないように、通知を完全にオフにしたり、頻度を変更したりすることができます。

ソフトクォータ通知は、冗長なメッセージが生成される可能性は低く、通知が唯一の目的であるため、設定できません。

次の表に、クォータが EMS システムに送信するイベントを示します。

[cols="2*"]
|===
| 発生する状況 | EMS に送信されるイベント 


 a| 
ツリークォータのハードリミットに達した
 a| 
`wafl.quota.qtree.exceeded`



 a| 
ボリューム上のユーザクォータのハードリミットに達した
 a| 
`wafl.quota.user.exceeded` （UNIXユーザの場合）
`wafl.quota.user.exceeded.win` （Windowsユーザの場合）



 a| 
qtree 上のユーザクォータのハードリミットに達した
 a| 
`wafl.quota.userQtree.exceeded` （UNIXユーザの場合）
`wafl.quota.userQtree.exceeded.win` （Windowsユーザの場合）



 a| 
ボリューム上のグループクォータのハードリミットに達した
 a| 
`wafl.quota.group.exceeded`



 a| 
qtree 上のグループクォータのハードリミットに達した
 a| 
`wafl.quota.groupQtree.exceeded`



 a| 
しきい値を含むソフトリミットを超えている
 a| 
`quota.softlimit.exceeded`



 a| 
ソフトリミットを超過しなくなりました
 a| 
`quota.softlimit.normal`

|===
次の表に、クォータで生成される SNMP トラップを示します。

[cols="2*"]
|===
| 発生する状況 | 送信される SNMP トラップ 


 a| 
ハードリミットに達しました
 a| 
quotaExceeded です



 a| 
しきい値を含むソフトリミットを超えている
 a| 
quotaExceeded および softQuotaExceeded です



 a| 
ソフトリミットを超過しなくなりました
 a| 
quotaNormal および softQuotaNormal です

|===
[NOTE]
====
通知には、 qtree 名ではなく qtree の ID 番号が含まれます。を使用して、qtree名をID番号に関連付けることができます `volume qtree show -id` コマンドを実行します

====