---
permalink: volumes/rehost-snapmirror-relationship-task.html 
sidebar: sidebar 
keywords: rehost, volumes, snapmirror, relationship 
summary: SnapMirror関係の一部として定義されているボリュームをリホストできます。関係をリホストする前に考慮する必要があるいくつかの問題があります。 
---
= SnapMirror関係にあるボリュームをリホストする
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
SnapMirror関係の一部として定義されているボリュームをリホストできます。関係をリホストする前に考慮する必要があるいくつかの問題があります。

.このタスクについて
* リホストはシステム停止を伴う処理です。
* リホスト処理が失敗した場合は、ソースボリュームでボリュームのポリシーおよび関連するルールを再設定しなければならない場合があります。
* 次のボリュームポリシー、ポリシールール、および構成はリホスト処理後にソースボリュームから失われるため、リホスト後のボリュームで手動で再設定する必要があります。
+
** ボリュームと qtree のエクスポートポリシー
** ウィルス対策ポリシー
** ボリューム効率化ポリシー
** Quality of Service （ QoS ；サービス品質）ポリシー
** Snapshot ポリシー
** クォータルール
** ns-switch とネームサービスの設定のエクスポートポリシーとルール
** ユーザ ID とグループ ID




.作業を開始する前に
* ボリュームはオンラインである必要があります。
* ボリューム移動や LUN 移動などのボリューム管理操作は実行しないでください。
* リホストするボリュームへのデータアクセスを停止する必要があります。
* リホストするボリュームのデータアクセスをサポートするようにターゲット SVM の ns-switch とネームサービスを設定する必要があります。
* ボリュームのユーザ ID とグループ ID をターゲット SVM で使用可能であるか、またはホストするボリュームで変更する必要があります。


.手順
. SnapMirror 関係のタイプを記録します。
+
`snapmirror show`

+
これは、ボリュームのリホストが失敗した場合に SnapMirror 関係のタイプに関する情報が失われないようにするための予防的な手順です。

. デスティネーションクラスタから、 SnapMirror 関係を削除します。
+
`snapmirror delete`

+
SnapMirror 関係は解除しないでください。解除するとデスティネーションボリュームのデータ保護機能が失われ、リホスト処理の完了後に関係を再確立できません。

. ソースクラスタから、 SnapMirror 関係情報を削除します。
+
`snapmirror release relationship-info-only true`

+
を設定します `relationship-info-only` パラメータの値 `true` Snapshotコピーを削除せずにソースの関係情報を削除します。

. advanced 権限レベルに切り替えます。
+
`set -privilege advanced`

. デスティネーション SVM でボリュームをリホストします。
+
`volume rehost -vserver source_svm -volume vol_name -destination-vserver destination_svm`

. SVM ピア関係が存在しない場合は、ソース SVM とデスティネーション SVM 間に SVM ピア関係を作成します。
+
`vserver peer create`

. ソースボリュームとデスティネーションボリューム間に SnapMirror 関係を作成します。
+
`snapmirror create`

+
を実行する必要があります `snapmirror create` DPボリュームをホストしているSVMからコマンドを実行します。リホストしたボリュームは、 SnapMirror 関係のソースまたはデスティネーションにすることができます。

. SnapMirror 関係を再同期

