---
permalink: volumes/rehost-smb-task.html 
sidebar: sidebar 
keywords: rehost, cifs volumes, smb 
summary: SMBプロトコルを使用してデータを提供するボリュームを再ホストします。 
---
= SMBボリュームのリホスト
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
SMBプロトコルを使用してデータを提供するボリュームをリホストできます。リホスト処理後もクライアントが引き続きデータにアクセスできるようにするには、ポリシーと関連するルールを手動で設定する必要があります。

.タスク概要
* リホストはシステム停止を伴う処理です。
* リホスト処理が失敗した場合は、ソース ボリュームでボリュームのポリシーおよび関連するルールを再設定しなければならない場合があります。
* ソースSVMとデスティネーションSVMのActive Directoryドメインが異なる場合は、ボリューム上のオブジェクトへのアクセスが失われる可能性があります。
* ONTAP 9.8以降では、NetApp Volume Encryption（NVE）を使用したボリュームのリホストがサポートされています。オンボードキーマネージャを使用している場合、リホスト処理中に暗号化されたメタデータが変更されます。ユーザデータは変更されません。
+
ONTAP 9.8以前を使用している場合は、リホスト処理を実行する前にボリュームの暗号化を解除する必要があります。



* ソースSVMにローカル ユーザとローカル グループが含まれている場合、ファイルとディレクトリに対して設定された権限（ACL）はボリュームのリホスト処理後に無効になります。
+
監査ACL（SACL）についても同様です。

* 次のボリューム ポリシー、ポリシー ルール、および構成はリホスト処理後にソース ボリュームから失われるため、リホスト後のボリュームで手動で再設定する必要があります。
+
** ボリュームとqtreeのエクスポート ポリシー
** ウィルス対策ポリシー
** ボリューム効率化ポリシー
** サービス品質（QoS）ポリシー
** Snapshotポリシー
** クォータ ルール
** ns-switchおよびネーム サービス構成のエクスポート ポリシーとルール
** ユーザIDとグループID




.開始する前に
* ボリュームがオンラインである必要があります。
* ボリューム管理処理（ボリュームの移動、LUNの移動など）を実行中のボリュームはリホストできません。
* リホストするボリュームへのデータ アクセスを停止する必要があります。
* リホストするボリュームのデータ アクセスをサポートするようにターゲットSVMのns-switchとネーム サービスを設定する必要があります。
* ソースSVMとデスティネーションSVMのActive DirectoryドメインとDNSドメインが同じであることが必要です。
* ボリュームのユーザIDとグループIDをターゲットSVMで使用可能であるか、またはホストするボリュームで変更する必要があります。
+

NOTE: ローカル ユーザとローカル グループが設定されていて、それらのユーザまたはグループに対して権限が設定されたボリューム上にファイルとディレクトリがある場合、それらの権限は無効になります。



.手順
. ボリュームのリホスト処理が失敗した場合にCIFS共有の情報が失われないように、CIFS共有に関する情報を記録します。
. 親ボリュームからボリュームをアンマウントします。
+
`volume unmount`

. advanced権限レベルに切り替えます。
+
`set -privilege advanced`

. デスティネーションSVMでボリュームをリホストします。
+
`volume rehost -vserver _source_svm_ -volume _vol_name_ -destination-vserver _destination_svm_`

. デスティネーションSVMの適切なジャンクション パスにボリュームをマウントします。
+
`volume mount`

. リホストしたボリューム用のCIFS共有を作成します。
+
`vserver cifs share create`

. ソースSVMとデスティネーションSVMでDNSドメインが異なる場合は、新しいユーザとグループを作成します。
. 新しいデスティネーションSVMのLIFとリホストしたボリュームへのジャンクション パスで、CIFSクライアントを更新します。


.終了後の操作
ポリシーおよび関連するルールをリホストしたボリュームに手動で再設定する必要があります。

https://docs.netapp.com/us-en/ontap-system-manager-classic/smb-config/index.html["SMB設定"]

https://docs.netapp.com/us-en/ontap-system-manager-classic/nas-multiprotocol-config/index.html["SMBおよびNFSのマルチプロトコルの設定"]
