---
permalink: volumes/rehost-smb-task.html 
sidebar: sidebar 
keywords: rehost, cifs volumes, smb 
summary: SMBプロトコルを使用してデータを提供するボリュームをリホストします。 
---
= SMBボリュームをリホストする
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
SMBプロトコルを使用してデータを提供するボリュームをリホストできます。リホスト処理後もクライアントが引き続きデータにアクセスできるようにするには、ポリシーと関連するルールを手動で設定する必要があります。

.タスクの内容
* リホストはシステム停止を伴う処理です。
* リホスト処理が失敗した場合は、ソースボリュームでボリュームポリシーと関連ルールの再設定が必要になることがあります。
* ソース SVM とデスティネーション SVM の Active Directory ドメインが異なる場合は、ボリューム上のオブジェクトへのアクセスが失われる可能性があります。
* ONTAP 9.8以降では、NetApp Volume Encryption（NVE）を使用するボリュームのリホストがサポートされます。オンボードキーマネージャを使用している場合は、リホスト処理中に暗号化されたメタデータが変更されます。ユーザデータは変更されません。
+
ONTAP 9.8以前を使用している場合は、リホスト処理を実行する前にボリュームの暗号化を解除する必要があります。



* ソース SVM にローカルユーザとローカルグループが含まれている場合、ファイルとディレクトリに対して設定された権限（ ACL ）はボリュームのリホスト処理後に無効になります。
+
監査ACL（SACL）についても同様です。

* 次のボリュームポリシー、ポリシールール、および構成はリホスト処理後にソースボリュームから失われるため、リホストしたボリュームで手動で再設定する必要があります。
+
** ボリュームとqtreeのエクスポートポリシー
** ウィルス対策ポリシー
** ボリューム効率化ポリシー
** Quality of Service （ QoS ；サービス品質）ポリシー
** Snapshotポリシー
** クォータルール
** ns-switch とネームサービスの設定のエクスポートポリシーとルール
** ユーザ ID とグループ ID




.開始する前に
* ボリュームはオンラインである必要があります。
* ボリューム管理処理（ボリュームの移動やLUNの移動など）を実行していないことを確認してください。
* リホストするボリュームへのデータアクセスを停止する必要があります。
* リホストするボリュームのデータアクセスをサポートするようにターゲット SVM の ns-switch とネームサービスを設定する必要があります。
* ソース SVM とデスティネーション SVM の Active Directory ドメインと DNS ドメインが同じであることが必要です。
* ボリュームのユーザ ID とグループ ID をターゲット SVM で使用可能であるか、またはホストするボリュームで変更する必要があります。
+

NOTE: ローカルユーザとローカルグループが設定されていて、それらのユーザまたはグループに対して権限が設定されているボリューム上にファイルとディレクトリがある場合、それらの権限は無効になります。



.手順
. ボリュームのリホスト処理が失敗した場合にCIFS共有の情報が失われないように、CIFS共有に関する情報を記録します。
. 親ボリュームからボリュームをアンマウントします。
+
`volume unmount`

. advanced権限レベルに切り替えます。
+
`set -privilege advanced`

. デスティネーション SVM でボリュームをリホストします。
+
`volume rehost -vserver _source_svm_ -volume _vol_name_ -destination-vserver _destination_svm_`

. デスティネーションSVMの適切なジャンクションパスにボリュームをマウントします。
+
`volume mount`

. リホストしたボリューム用のCIFS共有を作成します。
+
`vserver cifs share create`

. ソース SVM とデスティネーション SVM で DNS ドメインが異なる場合は、新しいユーザとグループを作成します。
. 新しいデスティネーション SVM の LIF とリホストしたボリュームへのジャンクションパスで、 CIFS クライアントを更新します。


.終了後
ポリシーおよび関連するルールをリホストしたボリュームに手動で再設定する必要があります。

https://docs.netapp.com/us-en/ontap-system-manager-classic/smb-config/index.html["SMBの設定"]

https://docs.netapp.com/us-en/ontap-system-manager-classic/nas-multiprotocol-config/index.html["SMBオヨヒNFSノマルチフロトコルセツテイ"]
