---
permalink: volumes/rehost-san-task.html 
sidebar: sidebar 
keywords: rehost, san volumes 
summary: マッピングされたLUNを介してデータを提供するSANボリュームをリホストします。 
---
= SANボリュームをリホストする
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
マッピングされたLUNを介してデータを提供するSANボリュームをリホストできます。デスティネーションSVMでイニシエータグループ（igroup）を再作成したあと、ボリュームのリホスト処理で同じSVMでボリュームを自動的に再マッピングできます。

.このタスクについて
* リホストはシステム停止を伴う処理です。
* リホスト処理が失敗した場合は、ソースボリュームでボリュームのポリシーおよび関連するルールを再設定しなければならない場合があります。
* ONTAP 9.8以降では、NetApp Volume Encryption（NVE）を使用するボリュームのリホストがサポートされます。オンボードキーマネージャを使用している場合は、リホスト処理中に暗号化されたメタデータが変更されます。ユーザデータは変更されません。
+
ONTAP 9.8以前を使用している場合は、リホスト処理を実行する前にボリュームの暗号化を解除する必要があります。



* 次のボリュームポリシー、ポリシールール、および構成はリホスト処理後にソースボリュームから失われるため、リホスト後のボリュームで手動で再設定する必要があります。
+
** ウィルス対策ポリシー
** ボリューム効率化ポリシー
** Quality of Service （ QoS ；サービス品質）ポリシー
** Snapshot ポリシー
** ns-switch とネームサービスの設定のエクスポートポリシーとルール
** ユーザ ID とグループ ID




.作業を開始する前に
* ボリュームはオンラインである必要があります。
* ボリューム移動や LUN 移動などのボリューム管理操作は実行しないでください。
* ボリュームまたは LUN にアクティブな I/O がないことを確認します。
* デスティネーション SVM に同じ名前でイニシエータが異なる igroup がないことを確認しておく必要があります。
+
igroup の名前が同じ場合は、どちらか（ソースまたはデスティネーション）の SVM で igroup の名前を変更する必要があります。

* を有効にしておく必要があります `force-unmap-luns` オプション
+
** のデフォルト値 `force-unmap-luns` オプションはです `false`。
** を設定しても、警告メッセージや確認メッセージは表示されません `force-unmap-luns` オプションをに設定します `true`。




.手順
. ターゲットボリュームの LUN マッピング情報を記録します。
+
`lun mapping show volume _volume_ vserver _source_svm_`

+
これは、ボリュームのリホストが失敗した場合に LUN マッピングに関する情報が失われないようにするための予防的な手順です。

. ターゲットボリュームに関連付けられている igroup を削除します。
. デスティネーション SVM にターゲットボリュームをリホストします。
+
`volume rehost -vserver _source_svm_ -volume _volume_name_ -destination-vserver _destination_svm_`

. ターゲットボリュームのLUNを適切なigroupにマッピングします。
+
** ボリュームのリホストではターゲットボリュームにLUNが保持されますが、LUNのマッピングは解除されたままです。
** LUN のマッピングにはデスティネーション SVM のポートセットを使用します。
** 状況に応じて `auto-remap-luns` オプションはに設定されています `true`を指定すると、リホスト後にLUNが自動的にマッピングされます。



