---
permalink: volumes/rehost-san-task.html 
sidebar: sidebar 
keywords: rehost, san volumes 
summary: マップされたLUNを通じてデータを提供するSANボリュームを再ホストします。 
---
= SANボリュームのリホスト
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
マッピングされたLUNを介してデータを提供するSANボリュームをリホストできます。デスティネーションSVMのイニシエータ グループ（igroup）を再作成したら、ボリュームのリホスト処理によって同じSVMでボリュームを自動的に再マッピングできます。

.タスク概要
* リホストはシステム停止を伴う処理です。
* リホスト処理が失敗した場合は、ソース ボリュームでボリュームのポリシーおよび関連するルールを再設定しなければならない場合があります。
* ONTAP 9.8以降では、NetApp Volume Encryption（NVE）を使用したボリュームのリホストがサポートされています。オンボードキーマネージャを使用している場合、リホスト処理中に暗号化されたメタデータが変更されます。ユーザデータは変更されません。
+
ONTAP 9.8以前を使用している場合は、リホスト処理を実行する前にボリュームの暗号化を解除する必要があります。



* 次のボリューム ポリシー、ポリシー ルール、および構成はリホスト処理後にソース ボリュームから失われるため、リホスト後のボリュームで手動で再設定する必要があります。
+
** ウィルス対策ポリシー
** ボリューム効率化ポリシー
** サービス品質（QoS）ポリシー
** Snapshotポリシー
** ns-switchおよびネーム サービス構成のエクスポート ポリシーとルール
** ユーザIDとグループID




.開始する前に
* ボリュームはオンラインである必要があります。
* ボリューム管理処理（ボリュームの移動、LUNの移動など）を実行中のボリュームはリホストできません。
* ボリュームまたはLUNにアクティブなI/Oがある場合はリホストできません。
* デスティネーションSVMに同じ名前でイニシエータが異なるigroupがないことを確認しておく必要があります。
+
igroup名が同じ場合は、どちらか（ソースまたはデスティネーション）のSVMでigroupの名前を変更する必要があります。

*  `force-unmap-luns`オプションを有効にする必要があります。
+
**  `force-unmap-luns`オプションのデフォルト値は `false`です。
**  `force-unmap-luns`オプションを `true`に設定すると、警告や確認メッセージは表示されません。




.手順
. ターゲット ボリュームのLUNマッピング情報を記録します。
+
`lun mapping show volume _volume_ vserver _source_svm_`

+
これは、ボリュームのリホストが失敗した場合にLUNマッピングに関する情報が失われないようにするための予防的な手順です。

+
 `lun mapping show volume`の詳細については、link:https://docs.netapp.com/us-en/ontap-cli/lun-mapping-show.html["ONTAPコマンド リファレンス"^]をご覧ください。

. ターゲット ボリュームに関連付けられているigroupを削除します。
. デスティネーションSVMにターゲット ボリュームをリホストします。
+
`volume rehost -vserver _source_svm_ -volume _volume_name_ -destination-vserver _destination_svm_`

. ターゲット ボリューム上のLUNを適切なigroupにマッピングします。
+
** ボリュームの再ホストにより、ターゲットボリューム上のLUNは保持されますが、LUNはマップされていないままになります。
** LUNをマッピングするときに、デスティネーションSVMポートセットを使用します。
**  `auto-remap-luns`オプションが `true`に設定されている場合、再ホスト後にLUNが自動的にマッピングされます。



