---
permalink: volumes/rehost-nfs-volumes-task.html 
sidebar: sidebar 
keywords: rehost, nfs, volumes 
summary: NFSプロトコルを使用してデータを提供するボリュームをリホストできます。 
---
= NFSボリュームをリホストする
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
NFSプロトコルを使用してデータを提供するボリュームをリホストできます。リホスト処理後もクライアントが引き続きデータにアクセスできるようにするには、ボリュームをSVMのエクスポートポリシーに関連付け、ポリシーと関連ルールを手動で設定する必要があります。

.タスクの内容
* リホストはシステム停止を伴う処理です。
* リホスト処理が失敗した場合は、ソースボリュームでボリュームポリシーと関連ルールの再設定が必要になることがあります。
* ONTAP 9.8以降では、NetApp Volume Encryption（NVE）を使用するボリュームのリホストがサポートされます。オンボードキーマネージャを使用している場合は、リホスト処理中に暗号化されたメタデータが変更されます。ユーザデータは変更されません。
+
ONTAP 9.8以前を使用している場合は、リホスト処理を実行する前にボリュームの暗号化を解除する必要があります。



* 次のボリュームポリシー、ポリシールール、および構成はリホスト処理後にソースボリュームから失われるため、リホストしたボリュームで手動で再設定する必要があります。
+
** ボリュームとqtreeのエクスポートポリシー
** ウィルス対策ポリシー
** ボリューム効率化ポリシー
** Quality of Service （ QoS ；サービス品質）ポリシー
** Snapshotポリシー
** クォータルール
** ns-switch とネームサービスの設定のエクスポートポリシーとルール
** ユーザ ID とグループ ID




.開始する前に
* ボリュームはオンラインである必要があります。
* ボリューム管理処理（ボリュームの移動やLUNの移動など）を実行していないことを確認してください。
* リホストするボリュームへのデータアクセスを停止する必要があります。
* リホストするボリュームのデータアクセスをサポートするようにターゲット SVM の ns-switch とネームサービスを設定する必要があります。
* ボリュームのユーザ ID とグループ ID をターゲット SVM で使用可能であるか、またはホストするボリュームで変更する必要があります。


.手順
. ボリュームのリホスト処理が失敗した場合に NFS ポリシーの情報が失われないように、 NFS エクスポートポリシーに関する情報を記録します。
. 親ボリュームからボリュームをアンマウントします。
+
`volume unmount`

. advanced権限レベルに切り替えます。
+
`set -privilege advanced`

. デスティネーション SVM でボリュームをリホストします。
+
`volume rehost -vserver _source_svm_ -volume _volume_name_ -destination-vserver _destination_svm_`

+
デスティネーション SVM のデフォルトのエクスポートポリシーがリホストしたボリュームに適用されます。

. エクスポートポリシーを作成します。
+
`vserver export-policy create`

. リホストしたボリュームのエクスポートポリシーをユーザ定義のエクスポートポリシーに更新します。
+
`volume modify`

. デスティネーションSVMの適切なジャンクションパスにボリュームをマウントします。
+
`volume mount`

. デスティネーション SVM で NFS サービスが実行されていることを確認します。
. リホストしたボリュームへのNFSアクセスを再開します。
. NFS クライアントのクレデンシャルと LIF の構成を更新して、デスティネーション SVM の LIF を反映させます。
+
これは、ボリュームのアクセスパス（LIFとジャンクションパス）が変更されているためです。



.終了後
ポリシーおよび関連するルールをリホストしたボリュームに手動で再設定する必要があります。詳細については、を参照してください https://docs.netapp.com/us-en/ontap-system-manager-classic/nfs-config/index.html["NFSの設定"] 。
