---
permalink: volumes/resizing-concept.html 
sidebar: sidebar 
keywords: when to, use, resizing 
summary: クォータのサイズ変更はクォータ初期化よりも高速であるため、可能なかぎりサイズ変更を使用してください。ただし、サイズ変更を使用できるのは、クォータに対する特定の種類の変更に限られます。 
---
= サイズ変更を使用できる場合
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
クォータのサイズ変更はクォータ初期化よりも高速であるため、可能なかぎりサイズ変更を使用してください。ただし、サイズ変更を使用できるのは、クォータに対する特定の種類の変更に限られます。

次の種類の変更をクォータルールに加えた場合、クォータのサイズを変更できます。

* 既存のクォータを変更する場合
+
たとえば、既存のクォータの制限を変更する場合などです。

* デフォルトクォータまたはデフォルト追跡クォータが適用されているクォータターゲットにクォータを追加した場合
* デフォルトクォータまたはデフォルト追跡クォータのエントリが指定されているクォータを削除した場合
* 別々のユーザクォータを 1 つのマルチユーザクォータに統合した場合


[NOTE]
====
クォータの大幅な変更を行った場合は、完全な再初期化を実行して、すべての変更を確実に有効にしてください。

====
[NOTE]
====
サイズを変更しようとしてサイズ変更処理では反映できないクォータの変更があった場合、 ONTAP は警告を発行します。ストレージシステムが特定のユーザ、グループ、または qtree のディスク使用量を追跡しているかどうかは、クォータレポートから判断できます。クォータレポートにクォータが表示される場合、ストレージシステムは、クォータターゲットによって所有されているディスクスペースとファイル数を追跡しています。

====
.サイズ変更によって有効にできるクォータ変更の例
一部のクォータルール変更は、サイズ変更によって有効にできます。次のクォータを考えてみましょう。

[listing]
----

#Quota Target type             disk  files thold sdisk sfile
#------------ ----             ----  ----- ----- ----- -----
*             user@/vol/vol2    50M   15K
*             group@/vol/vol2  750M   85K
*             tree@/vol/vol2      -     -
jdoe          user@/vol/vol2/  100M   75K
kbuck         user@/vol/vol2/  100M   75K
----
次の変更を行ったとします。

* デフォルトユーザターゲットのファイル数を増やします。
* デフォルトユーザクォータよりも多くのディスク制限が必要な新規ユーザ boris への、新しいユーザクォータの追加
* kbuck ユーザの明示的クォータエントリの削除。この新しいユーザに必要なのは、デフォルトクォータ制限だけになります。


これらの変更により、クォータは次のようになります。

[listing]
----

#Quota Target type             disk  files thold sdisk sfile
#------------ ----             ----  ----- ----- ----- -----
*             user@/vol/vol2    50M   25K
*             group@/vol/vol2  750M   85K
*             tree@/vol/vol2      -     -
jdoe          user@/vol/vol2/  100M   75K
boris         user@/vol/vol2/  100M   75K
----
サイズ変更によって、これらの変更がすべてアクティブ化されます。完全なクォータ再初期化は必要ありません。
