---
permalink: volumes/resume-efficiency-operation-checkpoint-task.html 
sidebar: sidebar 
keywords: resume, halted, efficiency, operation 
summary: システムの停止やリブートのために効率化処理が停止した場合は、 volume efficiency start コマンドでチェックポイントオプションを使用して、同じポイントから効率化処理を再開できます。これにより、効率化処理を最初からやり直す必要がなくなるため、時間とリソースを節約できます。 
---
= 停止した効率化処理を再開します
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
システムの停止やリブートのために効率化処理が停止した場合は、を使用して同じポイントから効率化処理を再開できます `volume efficiency start` チェックポイントオプションを指定したコマンド。これにより、効率化処理を最初からやり直す必要がなくなるため、時間とリソースを節約できます。

.このタスクについて
ボリュームで重複排除のみを有効にした場合は、データに対して重複排除が実行されます。ボリュームで重複排除とデータ圧縮の両方を有効にした場合は、データ圧縮が先に実行され、そのあとに重複排除が実行されます。

ボリュームのチェックポイントの詳細は、で確認できます `volume efficiency show` コマンドを実行します

デフォルトでは、効率化処理はチェックポイントから再開されます。ただし、前回の効率化処理（が実行されたフェーズ）に対応するチェックポイントがある場合は `volume efficiency start``-scan-old-dataコマンドが実行される）が24時間を超過している場合、効率化処理は前回のチェックポイントから自動的には再開されません。この場合、効率化処理は最初から開始されます。ただし、前回のスキャン以降、該当ボリュームで重要な変更が行われていないことがわかっている場合、を使用して、強制的に前回のチェックポイントから処理を続行できます `-use-checkpoint` オプション

.ステップ
. を使用します `volume efficiency start` コマンドにを指定します `-use-checkpoint` 効率化処理を再開するオプションです。
+
次のコマンドは、ボリューム VolA 上の新しいデータに対して効率化処理を再開します。

+
`volume efficiency start -vserver vs1 -volume VolA -use-checkpoint true`

+
次のコマンドは、ボリューム VolA 上の既存データに対して効率化処理を再開します。

+
`volume efficiency start -vserver vs1 -volume VolA -scan-old-data true -use-checkpoint true`


