---
permalink: volumes/space-display-quota-report-unix-client-concept.html 
sidebar: sidebar 
keywords: difference, space usage, displayed, quota report, unix client 
summary: FlexVol または qtree のクォータレポートに表示される使用済みディスクスペースの値が、 UNIX クライアントに表示される同じボリュームまたは qtree の使用済みスペースの値と異なる場合があります。使用量の値が異なる理由は、クォータレポートと UNIX コマンドがそれぞれ異なる方法でボリュームまたは qtree 内のデータブロックを計算するためです。 
---
= クォータレポートと UNIX クライアントの概要に表示されるスペース使用量の相違
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
FlexVol または qtree のクォータレポートに表示される使用済みディスクスペースの値が、 UNIX クライアントに表示される同じボリュームまたは qtree の使用済みスペースの値と異なる場合があります。使用量の値が異なる理由は、クォータレポートと UNIX コマンドがそれぞれ異なる方法でボリュームまたは qtree 内のデータブロックを計算するためです。

たとえば、空のデータブロック（データが書き込まれていないブロック）のあるファイルがボリュームに含まれている場合、ボリュームのクォータレポートでは、スペース使用量のレポート作成時に空のデータブロックはカウントされません。ただし、ボリュームがUNIXクライアントにマウントされている場合は、の出力にファイルが表示されます `ls` コマンドでは、空のデータブロックもスペース使用量に含まれます。そのため、を参照してください `ls` クォータレポートに表示されるスペース使用量と比較すると、コマンドによって出力されるファイルサイズの方が大きくなります。

同様に、クォータレポートに表示されるスペース使用量の値は、などのUNIXコマンドの実行結果の値と異なる場合があります `df` および `du`。



== クォータレポートのディスクスペースとファイル使用量の表示

FlexVol または qtree のクォータレポートに指定される使用済みファイル数とディスクスペース容量は、ボリュームまたは qtree 内のすべての inode に対応する使用済みデータブロックの数によって決まります。

ブロック数には、通常のファイルとストリームファイルで使用される直接ブロックと間接ブロックの両方が含まれます。ディレクトリ、アクセス制御リスト（ ACL ）、ストリームディレクトリ、およびメタファイルによって使用されるブロックは、クォータレポートの使用済みブロック数には含められません。UNIX のスパースファイルの場合、空のデータブロックはクォータレポートに含まれません。

クォータサブシステムは、ユーザが制御できるファイルシステムの要素だけを考慮して設計されています。クォータの計算から除外されるスペースの例は、ディレクトリ、ACL、およびSnapshotスペースです。クォータは、制限を適用するために使用されます。保証は適用されず、アクティブなファイルシステムでのみ機能します。クォータは、特定のファイルシステム構成体はカウントしません。また、ストレージ効率化（圧縮や重複排除など）も考慮しません。
