---
permalink: volumes/split-flexclone-from-parent-task.html 
sidebar: sidebar 
keywords: split, flexclone, volume, parent, volume, clone 
summary: FlexCloneボリュームを親からスプリットして、クローンを通常のFlexVol volumeにすることができます。 
---
= FlexCloneボリュームを親ボリュームからスプリットします。
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
FlexCloneボリュームを親からスプリットして、クローンを通常のFlexVol volumeにすることができます。

クローンスプリット処理はバックグラウンドで実行されます。スプリット中は、クローンおよび親のデータにアクセスできます。ONTAP 9.4以降では、スペース効率が維持されます。スプリットプロセスではメタデータのみが更新され、IOは最小限に抑えられます。データブロックはコピーされません。

.タスクの内容
* スプリット処理中は、FlexCloneボリュームの新しいSnapshotを作成できません。
* データ保護関係に属しているか負荷共有ミラーに属しているFlexCloneボリュームは、親ボリュームからスプリットすることはできません。
* スプリットの実行中にFlexCloneボリュームをオフラインにすると、スプリット処理が中断されます。FlexCloneボリュームをオンラインに戻すと、スプリット処理が再開されます。
* スプリット後は、親FlexVol volumeとクローンの両方で、それぞれのボリュームギャランティに基づいたスペースの完全な割り当てが必要になります。
* FlexCloneを親ボリュームからスプリットしたあとは、この2つを再結合することはできません。
* ONTAP 9 .4以降では、AFFシステムのボリュームギャランティがnonである場合、FlexCloneのスプリット処理では物理ブロックが共有され、データはコピーされません。したがって、AFFシステムのFlexCloneボリュームのスプリットは、ONTAP 9 .4以降の他のFASシステムのFlexCloneスプリット処理よりも高速です。AFFシステムでのFlexCloneスプリット処理の改善には、次の利点があります。
+
** 親からクローンをスプリットしたあともストレージ効率が維持されます。
** 既存のSnapshotは削除されません。
** 処理時間が短縮されます。
** FlexCloneボリュームは、クローン階層の任意のポイントからスプリットできます。




.開始する前に
* クラスタ管理者である必要があります。
* FlexCloneボリュームは、スプリット処理の開始時にオンラインになっている必要があります。
* スプリットが成功するには、親ボリュームがオンラインである必要があります。


.手順
. スプリット処理を完了するために必要な空きスペースの量を確認します。
+
`volume clone show -estimate -vserver _vserver_name_ -flexclone _clone_volume_name_ -parent-volume _parent_vol_name_`

+
次の例は、FlexCloneボリューム「clone1」を親ボリューム「vol1」からスプリットするために必要な空きスペースに関する情報を表示します。

+
[listing]
----
cluster1::> volume clone show -estimate -vserver vs1 -flexclone clone1 -parent-volume volume1
                             Split
Vserver   FlexClone       Estimate
--------- ------------- ----------
vs1       clone1           40.73MB
----
. FlexCloneボリュームとその親を含むアグリゲートに十分なスペースがあることを確認します。
+
.. FlexCloneボリュームとその親を含むアグリゲートの空きスペースの量を確認します。
+
`storage aggregate show`

.. 包含アグリゲートに十分な空きスペースがない場合は、アグリゲートにストレージを追加します。
+
`storage aggregate add-disks`



. スプリット処理を開始します。
+
`volume clone split start -vserver _vserver_name_ -flexclone _clone_volume_name_`

+
次の例は、FlexCloneボリューム「Clone1」を親ボリューム「vol1」からスプリットするプロセスを開始する方法を示しています。

+
[listing]
----
cluster1::> volume clone split start -vserver vs1 -flexclone clone1

Warning: Are you sure you want to split clone volume clone1 in Vserver vs1 ?
{y|n}: y
[Job 1617] Job is queued: Split clone1.
----
. FlexCloneスプリット処理のステータスを監視します。
+
`volume clone split show -vserver _vserver_name_ -flexclone _clone_volume_name_`

+
次の例は、AFFシステムでのFlexCloneスプリット処理のステータスを表示します。

+
[listing]
----
cluster1::> volume clone split show -vserver vs1 -flexclone clone1
                                              Inodes                   Blocks
                                     ---------------------    ---------------------
Vserver   FlexClone    Processed Total    Scanned  Updated      % Inode   % Block
                                                                 Complete  Complete
vs1       clone1        0         0       411247   153600         0        37
----
. スプリットボリュームがFlexCloneボリュームでなくなったことを確認します。
+
`volume show -volume _volume_name_ -fields clone-volume`

+
FlexClone以外のボリュームの場合、オプションの値 `clone-volume`は「false」です。

+
次の例は、親からスプリットしたボリューム「Clone1」がFlexCloneボリュームでないかどうかを確認する方法を示しています。

+
[listing]
----
cluster1::> volume show -volume clone1 -fields clone-volume
vserver volume **clone-volume**
------- ------ **------------**
vs1     clone1 **false**
----

