---
permalink: encryption-at-rest/assign-authentication-keys-seds-onboard-task.html 
sidebar: sidebar 
keywords: assign, data, authentication, key, fips, drive, sed, onboard, key, management 
summary: storage encryption disk modify コマンドを使用して、 FIPS ドライブまたは SED にデータ認証キーを割り当てることができます。このキーは、クラスタノードでドライブ上のデータにアクセスするときに使用します。 
---
= FIPSドライブまたはSEDへのデータ認証キーの割り当て（オンボードキー管理）
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
コマンドを使用して、FIPSドライブまたはSEDにデータ認証キーを割り当てることができます `storage encryption disk modify`。このキーは、クラスタノードでドライブ上のデータにアクセスするときに使用します。

.タスクの内容
自己暗号化ドライブは、認証キーIDがデフォルト以外の値に設定されている場合にのみ、不正アクセスから保護されます。SASドライブの標準のデフォルト値は、キーIDが0x0のManufacturer Secure ID（MSID；メーカーのセキュアID）です。NVMeドライブの場合、標準のデフォルト値はnullキーで、空のキーIDで表されます。このキーIDを自己暗号化ドライブに割り当てると、認証キーIDがデフォルト以外の値に変更されます。

.開始する前に
このタスクを実行するには、クラスタ管理者である必要があります。

.手順
. FIPSドライブまたはSEDにデータ認証キーを割り当てます。
+
`storage encryption disk modify -disk _disk_ID_ -data-key-id _key_ID_`

+
完全なコマンド構文については、コマンドのマニュアルページを参照してください。

+
[NOTE]
====
キーIDは、コマンドを使用して表示できます `security key-manager key query -key-type NSE-AK`。

====
+
[listing]
----
cluster1::> storage encryption disk modify -disk 0.10.* -data-key-id 0000000000000000020000000000010019215b9738bc7b43d4698c80246db1f4

Info: Starting modify on 14 disks.
      View the status of the operation by using the
      storage encryption disk show-status command.
----
. 認証キーが割り当てられたことを確認します。
+
`storage encryption disk show`

+
コマンド構文全体については、マニュアルページを参照してください。

+
[listing]
----
cluster1::> storage encryption disk show
Disk    Mode Data Key ID
-----   ---- ----------------------------------------------------------------
0.0.0   data 0000000000000000020000000000010019215b9738bc7b43d4698c80246db1f4
0.0.1   data 0000000000000000020000000000010059851742AF2703FC91369B7DB47C4722
[...]
----

