---
permalink: encryption-at-rest/assign-authentication-keys-seds-external-task.html 
sidebar: sidebar 
keywords: assign, data, authentication, key, fips, drive, sed, external, key, management 
summary: storage encryption disk modify コマンドを使用して、 FIPS ドライブまたは SED にデータ認証キーを割り当てることができます。このキーは、クラスタノードでドライブ上の暗号化されたデータをロックまたはロック解除するときに使用します。 
---
= ONTAP外部キー管理を使用してFIPSドライブまたはSEDにデータ認証キーを割り当てる
:allow-uri-read: 


[role="lead"]
コマンドを使用して、FIPSドライブまたはSEDにデータ認証キーを割り当てることができます `storage encryption disk modify`。このキーは、クラスタノードでドライブ上の暗号化されたデータをロックまたはロック解除するときに使用します。

.タスクの内容
自己暗号化ドライブは、認証キーIDがデフォルト以外の値に設定されている場合にのみ、不正アクセスから保護されます。SASドライブの標準のデフォルト値は、キーIDが0x0のManufacturer Secure ID（MSID；メーカーのセキュアID）です。NVMeドライブの場合、標準のデフォルト値はnullキーで、空のキーIDで表されます。このキーIDを自己暗号化ドライブに割り当てると、認証キーIDがデフォルト以外の値に変更されます。

この手順はシステムの停止を伴いません。

.開始する前に
このタスクを実行するには、クラスタ管理者である必要があります。

.手順
. FIPSドライブまたはSEDにデータ認証キーを割り当てます。
+
`storage encryption disk modify -disk _disk_ID_ -data-key-id _key_ID_`

+
の詳細については `storage encryption disk modify`、をlink:https://docs.netapp.com/us-en/ontap-cli/storage-encryption-disk-modify.html["ONTAPコマンド リファレンス"^]参照してください。

+
[NOTE]
====
キーIDは、コマンドを使用して表示できます `security key-manager query -key-type NSE-AK`。

====
+
[listing]
----
cluster1::> storage encryption disk modify -disk 0.10.* -data-key-id <id_value>

Info: Starting modify on 14 disks.
      View the status of the operation by using the
      storage encryption disk show-status command.
----
. 認証キーが割り当てられたことを確認します。
+
`storage encryption disk show`

+
の詳細については `storage encryption disk show`、をlink:https://docs.netapp.com/us-en/ontap-cli/storage-encryption-disk-show.html["ONTAPコマンド リファレンス"^]参照してください。

+
[listing]
----
cluster1::> storage encryption disk show
Disk    Mode Data Key ID
-----   ---- ----------------------------------------------------------------
0.0.0   data <id_value>
0.0.1   data <id_value>
[...]
----


.関連情報
* link:https://docs.netapp.com/us-en/ontap-cli/storage-encryption-disk-show.html["storage disk show | more"^]
* link:https://docs.netapp.com/us-en/ontap-cli/storage-encryption-disk-show-status.html["ストレージ暗号化ディスクステータス表示"^]

