---
permalink: encryption-at-rest/change-key-management-passphrase-task.html 
sidebar: sidebar 
keywords: changing, onboard, key, management, passphrase 
summary: オンボード キー管理パスフレーズを定期的に変更してください。新しいパスフレーズは、ストレージ システム外の安全な場所に保管してください。 
---
= ONTAPオンボードキー管理パスフレーズを変更する
:allow-uri-read: 


[role="lead"]
NetAppでは、オンボードキー管理パスフレーズを定期的に変更することを推奨しています。新しいパスフレーズは、ストレージシステム外の安全な場所に保管する必要があります。

.開始する前に
* このタスクを実行するには、クラスタ管理者またはSVMの管理者である必要があります。
* このタスクを実行するにはadvanced権限が必要です。
* 新しいパスフレーズを設定する前に、現在使用されているオンボードキー管理パスフレーズを入力する必要があります。
* MetroCluster環境では、ローカル クラスタでパスフレーズを更新した後、パートナー クラスタでパスフレーズの更新を同期します。


.手順
. advanced権限レベルに切り替えます。
+
`set -privilege advanced`

. オンボードキー管理パスフレーズを変更します。使用するコマンドは、実行している ONTAP のバージョンによって異なります。
+
コマンドを入力した後、プロンプトに応答して現在のパスフレーズ、新しいパスフレーズ、そして確認のために新しいパスフレーズを再度入力してください。

+
[role="tabbed-block"]
====
.ONTAP 9.6以降
--
`security key-manager onboard update-passphrase`

--
.ONTAP 9.5以前
--
`security key-manager update-passphrase`

--
====
. プロンプトが表示されたら、現在のパスフレーズを入力してください。
. 32～256文字の新しいパスフレーズを入力するか、「`cc-mode`」の場合は64～256文字のパスフレーズを入力してください。
+
指定された「`cc-mode`」パスフレーズが64文字未満の場合、キー マネージャーのセットアップ操作でパスフレーズ プロンプトが再度表示されるまでに5秒の遅延が発生します。

. パスフレーズの確認画面が表示されたら、新しいパスフレーズを再入力してください。
. MetroCluster構成の場合は、パートナー クラスタで更新されたパスフレーズを同期します。
+
.. ONTAPバージョンに適したコマンドを選択して、パートナー クラスタのパスフレーズを同期します：
+
[role="tabbed-block"]
====
.ONTAP 9.6以降
--
`security key-manager onboard sync`

--
.ONTAP 9.5以前
--
*** ONTAP 9.5 では、次のコマンドを実行します。
+
`security key-manager setup -sync-metrocluster-config`

*** ONTAP 9.4 以前では、ローカル クラスタでパスフレーズを更新した後、20 秒待ってから、パートナー クラスタで次のコマンドを実行します：
+
`security key-manager setup`



--
====
.. プロンプトが表示されたら、新しいパスフレーズを入力します。
+
両方のクラスターで同じパスフレーズを使用する必要があります。





.終了後の操作
将来使用するために、オンボード キー管理パスフレーズをストレージ システム外部の安全な場所にコピーします。

オンボードキー管理パスフレーズを変更するたびに、キー管理情報を手動でバックアップします。

.関連情報
* link:backup-key-management-information-manual-task.html["オンボード キー管理情報の手動バックアップ"]
* link:https://docs.netapp.com/us-en/ontap-cli/security-key-manager-onboard-update-passphrase.html["セキュリティキー・マネージャーオンボードのパスフレーズ更新"^]

