---
permalink: encryption-at-rest/change-key-management-passphrase-task.html 
sidebar: sidebar 
keywords: changing, onboard, key, management, passphrase 
summary: オンボードキー管理パスフレーズを定期的に変更してください。新しいパスフレーズをストレージ システム外部の安全な場所に保存します。 
---
= ONTAPオンボードキー管理パスフレーズを変更する
:allow-uri-read: 


[role="lead"]
NetApp、オンボード キー管理パスフレーズを定期的に変更することを推奨しています。新しいパスフレーズは、ストレージ システム外の安全な場所に保存する必要があります。

.開始する前に
* このタスクを実行するには、クラスタ管理者またはSVM管理者である必要があります。
* このタスクには高度なPrivilegesが必要です。
* MetroCluster環境では、ローカル クラスタでパスフレーズを更新した後、パートナー クラスタでパスフレーズの更新を同期します。


.手順
. advanced権限レベルに切り替えます。
+
`set -privilege advanced`

. オンボード キー管理パスフレーズを変更します。使用するコマンドは、実行しているONTAP のバージョンによって異なります。
+
[role="tabbed-block"]
====
.ONTAP 9.6以降
--
`security key-manager onboard update-passphrase`

--
.ONTAP 9.5以前
--
`security key-manager update-passphrase`

--
====
. 32 〜 256 文字のパスフレーズを入力します。「`cc-mode`」の場合は 64 〜 256 文字のパスフレーズを入力します。
+
指定された "cc-mode" パスフレーズが 64 文字未満の場合、キー管理ツールのセットアップ操作によってパスフレーズのプロンプトが再表示されるまでに 5 秒の遅延が発生します。

. パスフレーズの確認のプロンプトでパスフレーズをもう一度入力します。
. MetroCluster構成の場合は、パートナー クラスタで更新されたパスフレーズを同期します。
+
.. ONTAPバージョンに適したコマンドを選択して、パートナー クラスタのパスフレーズを同期します。
+
[role="tabbed-block"]
====
.ONTAP 9.6以降
--
`security key-manager onboard sync`

--
.ONTAP 9.5以前
--
*** ONTAP 9.5 では、次のコマンドを実行します。
+
`security key-manager setup -sync-metrocluster-config`

*** ONTAP 9.4 以前では、ローカル クラスタでパスフレーズを更新した後、20 秒待ってから、パートナー クラスタで次のコマンドを実行します。
+
`security key-manager setup`



--
====
.. プロンプトが表示されたら新しいパスフレーズを入力します。
+
両方のクラスターで同じパスフレーズを使用する必要があります。





.終了後
将来使用するために、オンボード キー管理パスフレーズをストレージ システム外部の安全な場所にコピーします。

オンボード キー管理パスフレーズを変更するたびに、キー管理情報を手動でバックアップします。

.関連情報
* link:backup-key-management-information-manual-task.html["オンボードキー管理情報の手動でのバックアップ"]
* link:https://docs.netapp.com/us-en/ontap-cli/security-key-manager-onboard-update-passphrase.html["security key-manager onboard update-passphrase（セキュリティキー管理ツールオンボード更新パスフレーズ）"^]

