---
permalink: encryption-at-rest/change-key-management-passphrase-task.html 
sidebar: sidebar 
keywords: changing, onboard, key, management, passphrase 
summary: オンボードキー管理パスフレーズを定期的に変更してください。新しいパスフレーズをストレージ システム外部の安全な場所に保存します。 
---
= ONTAPオンボードキー管理パスフレーズを変更する
:allow-uri-read: 


[role="lead"]
オンボードキー管理パスフレーズを定期的に変更してください。新しいパスフレーズをストレージ システム外部の安全な場所に保存します。

.開始する前に
* このタスクを実行するには、クラスタ管理者またはSVM管理者である必要があります。
* このタスクには高度なPrivilegesが必要です。
* ONTAP MetroCluster環境を管理している場合は、両方のクラスタでパスフレーズを更新する必要があります。


.手順
. advanced権限レベルに切り替えます。
+
`set -privilege advanced`

. オンボードキー管理のパスフレーズを変更します。
+
[cols="25,75"]
|===


| ONTAPバージョン | 使用するコマンド 


 a| 
ONTAP 9.6以降
 a| 
`security key-manager onboard update-passphrase`



 a| 
ONTAP 9.5以前
 a| 
`security key-manager update-passphrase`

|===
. 32 〜 256 文字のパスフレーズを入力します。「`cc-mode`」の場合は 64 〜 256 文字のパスフレーズを入力します。
+
指定された "cc-mode" パスフレーズが 64 文字未満の場合、キー管理ツールのセットアップ操作によってパスフレーズのプロンプトが再表示されるまでに 5 秒の遅延が発生します。

. パスフレーズの確認のプロンプトでパスフレーズをもう一度入力します。


.終了後
あとで使用できるように、ストレージシステムの外部の安全な場所にオンボードキー管理のパスフレーズをコピーしておく必要があります。

オンボードキー管理のパスフレーズを変更するときは、キー管理情報を手動でバックアップする必要があります。

.関連情報
* link:backup-key-management-information-manual-task.html["オンボードキー管理情報の手動バックアップ"]
* link:https://docs.netapp.com/us-en/ontap-cli/security-key-manager-onboard-update-passphrase.html["security key-manager onboard update-passphrase（セキュリティキー管理ツールオンボード更新パスフレーズ）"^]

