---
permalink: encryption-at-rest/delete-encrypted-volume-task.html 
sidebar: sidebar 
keywords: deleting, encrypted, volume 
summary: volume delete コマンドを使用して、暗号化されたボリュームを削除できます。 
---
= ONTAPで暗号化されたボリュームを削除する
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
コマンドを使用すると、暗号化されたボリュームを削除できます `volume delete`。

.開始する前に
* このタスクを実行するには、クラスタ管理者である必要があります。または、クラスタ管理者から権限を委譲されたSVM管理者を指定することもできます。詳細については、を参照してください link:delegate-volume-encryption-svm-administrator-task.html["volume moveコマンドの実行権限を委譲する"]。
* ボリュームはオフラインである必要があります。


.ステップ
. 暗号化されたボリュームを削除します。
+
`volume delete -vserver _SVM_name_ -volume _volume_name_`

+
の詳細については `volume delete`、をlink:https://docs.netapp.com/us-en/ontap-cli/volume-delete.html["ONTAPコマンド リファレンス"^]参照してください。

+
次のコマンドは、という名前の暗号化されたボリュームを削除し `vol1`ます。

+
[listing]
----
cluster1::> volume delete -vserver vs1 -volume vol1
----
+
削除の確認を求められたら、と入力し `yes`ます。

+
ボリュームの暗号化キーは24時間後に削除されます。

+
オプションとともに `-force true`使用して、 `volume delete`ボリュームを削除し、対応する暗号化キーをただちに破棄します。このコマンドには高度なPrivilegesが必要です。の詳細については `volume delete`、をlink:https://docs.netapp.com/us-en/ontap-cli/volume-delete.html["ONTAPコマンド リファレンス"^]参照してください。



.終了後
コマンドの実行後、コマンドを使用して、削除したボリュームを保持期間内にリカバリ `volume delete`できます `volume recovery-queue`。

`volume recovery-queue _SVM_name_ -volume _volume_name_`

https://kb.netapp.com/Advice_and_Troubleshooting/Data_Storage_Software/ONTAP_OS/How_to_use_the_Volume_Recovery_Queue["ボリュームリカバリ機能の使用方法"]
