---
permalink: encryption-at-rest/delete-encrypted-volume-task.html 
sidebar: sidebar 
keywords: deleting, encrypted, volume 
summary: volume delete コマンドを使用して、暗号化されたボリュームを削除できます。 
---
= 暗号化されたボリュームを削除する
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
を使用できます `volume delete` 暗号化されたボリュームを削除するコマンド。

.必要なもの
* このタスクを実行するには、クラスタ管理者であるか、クラスタ管理者から権限を委譲された SVM 管理者である必要があります。
+
link:delegate-volume-encryption-svm-administrator-task.html["volume move コマンドの実行権限の委譲"]

* ボリュームはオフラインである必要があります。


.ステップ
. 暗号化されたボリュームを削除します。
+
`volume delete -vserver SVM_name -volume volume_name`

+
コマンド構文全体については、コマンドのマニュアルページを参照してください。

+
次のコマンドは、という名前の暗号化されたボリュームを削除します `vol1`：

+
[listing]
----
cluster1::> volume delete -vserver vs1 -volume vol1
----
+
入力するコマンド `yes` 削除の確認を求めるプロンプトが表示されたら、

+
24 時間後にボリュームの暗号化キーが削除されます。

+
使用 `volume delete` を使用 `-force true` ボリュームを削除して対応する暗号化キーをただちに破棄するオプション。このコマンドには advanced 権限が必要です。詳細については、のマニュアルページを参照してください。



.完了後
を使用できます `volume recovery-queue` を実行したあとの保持期間中に削除したボリュームをリカバリするコマンド `volume delete` コマンドを実行します

`volume recovery-queue SVM_name -volume volume_name`

https://kb.netapp.com/Advice_and_Troubleshooting/Data_Storage_Software/ONTAP_OS/How_to_use_the_Volume_Recovery_Queue["ボリュームリカバリ機能の使用方法"]
