---
permalink: encryption-at-rest/destroy-nse-disks-task.html 
sidebar: sidebar 
keywords: fips, drive, sed, inaccessible, destroy, psid, physical secure ID, nrd plus, encrypt, 
summary: 'FIPS ドライブまたは SED 上のデータを永続的にアクセス不能にし、ドライブを再利用する必要がない場合は、 `storage encryption disk destroy`コマンドを使用してディスクを破棄できます。' 
---
= ONTAPでFIPSドライブまたはSEDを破棄する
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
FIPS ドライブまたは SED 上のデータを永続的にアクセス不能にし、ドライブを再利用する必要がない場合は、 `storage encryption disk destroy`コマンドを使用してディスクを破棄できます。

.タスク概要
FIPSドライブまたはSEDを破壊すると、システムはディスク暗号化キーを未知のランダム値に設定し、ドライブを不可逆的にロックします。これにより、ディスクは事実上使用できなくなり、ディスク上のデータにも永久にアクセスできなくなります。ただし、ディスクのラベルに記載されている物理セキュアID（PSID）を使用して、ディスクを工場出荷時の設定にリセットすることができます。詳細については、link:return-self-encrypting-disks-keys-not-available-task.html["認証キーが失われた場合にFIPSドライブまたはSEDを使用可能な状態に戻す"]をご覧ください。


NOTE: （故障）ディスク返却不要サービス（NRD Plus）を契約している場合を除き、FIPSドライブまたはSEDは破棄しないでください。ディスクを破棄すると保証が無効になります。

.開始する前に
このタスクを実行するには、クラスタ管理者である必要があります。

.手順
. 保持しておく必要があるデータを別のディスクのアグリゲートにすべて移行します。
. 破棄する FIPS ドライブまたは SED 上のアグリゲートを削除します：
+
`storage aggregate delete -aggregate aggregate_name`

+
[listing]
----
cluster1::> storage aggregate delete -aggregate aggr1
----
+
 `storage aggregate delete`の詳細については、link:https://docs.netapp.com/us-en/ontap-cli/storage-aggregate-delete.html["ONTAPコマンド リファレンス"^]をご覧ください。

. 破棄する FIPS ドライブまたは SED のディスク ID を特定します：
+
`storage encryption disk show`

+
 `storage encryption disk show`の詳細については、link:https://docs.netapp.com/us-en/ontap-cli/storage-encryption-disk-show.html["ONTAPコマンド リファレンス"^]を参照してください。

+
[listing]
----
cluster1::> storage encryption disk show
Disk    Mode Data Key ID
-----   ---- ----------------------------------------------------------------
0.0.0   data <id_value>
0.0.1   data <id_value>
1.10.2  data <id_value>
[...]
----
. ディスクを破壊します：
+
`storage encryption disk destroy -disk disk_id`

+
 `storage encryption disk destroy`の詳細については、link:https://docs.netapp.com/us-en/ontap-cli/storage-encryption-disk-destroy.html["ONTAPコマンド リファレンス"^]をご覧ください。

+
[NOTE]
====
処理を続行する前に確認のフレーズを入力するように求められます。画面に表示されたフレーズを正確に入力します。

====
+
[listing]
----
cluster1::> storage encryption disk destroy -disk 1.10.2

Warning: This operation will cryptographically destroy 1 spare or broken
         self-encrypting disks on 1 node.
         You cannot reuse destroyed disks unless you revert
         them to their original state using the PSID value.
         To continue, enter
          destroy disk
         :destroy disk

Info: Starting destroy on 1 disk.
      View the status of the operation by using the
      "storage encryption disk show-status" command.
----


.関連情報
* link:https://docs.netapp.com/us-en/ontap-cli/storage-encryption-disk-destroy.html["ストレージ暗号化ディスク破壊"^]
* link:https://docs.netapp.com/us-en/ontap-cli/storage-encryption-disk-show.html["storage disk show | more"^]
* link:https://docs.netapp.com/us-en/ontap-cli/storage-encryption-disk-show-status.html["storage encryption disk show-status"^]

