---
permalink: encryption-at-rest/destroy-nse-disks-task.html 
sidebar: sidebar 
keywords: fips, drive, sed, inaccessible, destroy, psid, physical secure ID, nrd plus, encrypt, 
summary: 'FIPSドライブまたはSEDのデータに永久にアクセスできない状態にし、ドライブを再利用する必要もない場合は、コマンドを使用してディスクを破棄できます `storage encryption disk destroy`。' 
---
= ONTAPでのFIPSドライブまたはSEDの破棄
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
FIPSドライブまたはSEDのデータに永久にアクセスできない状態にし、ドライブを再利用する必要もない場合は、コマンドを使用してディスクを破棄できます `storage encryption disk destroy`。

.タスクの内容
FIPSドライブまたはSEDを破棄すると、ディスク暗号化キーが不明なランダム値に設定され、ドライブが完全にロックされます。これにより、ディスクが実質的に使用できない状態になり、ディスクのデータに永久にアクセスできなくなります。ただし、ディスクのラベルに印刷されているPhysical Secure ID（PSID；物理的なセキュアID）を使用して、ディスクを工場出荷時の設定にリセットすることができます。詳細については、を参照してください link:return-self-encrypting-disks-keys-not-available-task.html["認証キーが失われた場合にFIPSドライブまたはSEDを使用可能な状態に戻す"]。


NOTE: 障害ディスク返却不要サービス（NRD Plus）を利用している場合を除き、FIPSドライブまたはSEDは破棄しないでください。ディスクを破棄すると保証が無効になります。

.開始する前に
このタスクを実行するには、クラスタ管理者である必要があります。

.手順
. 保持する必要があるデータを別のディスク上のアグリゲートに移行します。
. 破棄する FIPS ドライブまたは SED のアグリゲートを削除します。
+
`storage aggregate delete -aggregate aggregate_name`

+
[listing]
----
cluster1::> storage aggregate delete -aggregate aggr1
----
+
の詳細については `storage aggregate delete`、をlink:https://docs.netapp.com/us-en/ontap-cli/storage-aggregate-delete.html["ONTAPコマンド リファレンス"^]参照してください。

. 破棄する FIPS ドライブまたは SED のディスク ID を確認します。
+
`storage encryption disk show`

+
の詳細については `storage encryption disk show`、をlink:https://docs.netapp.com/us-en/ontap-cli/storage-encryption-disk-show.html["ONTAPコマンド リファレンス"^]参照してください。

+
[listing]
----
cluster1::> storage encryption disk show
Disk    Mode Data Key ID
-----   ---- ----------------------------------------------------------------
0.0.0   data <id_value>
0.0.1   data <id_value>
1.10.2  data <id_value>
[...]
----
. ディスクを破棄します。
+
`storage encryption disk destroy -disk disk_id`

+
の詳細については `storage encryption disk destroy`、をlink:https://docs.netapp.com/us-en/ontap-cli/storage-encryption-disk-destroy.html["ONTAPコマンド リファレンス"^]参照してください。

+
[NOTE]
====
続行する前に確認のフレーズを入力するように求められます。画面に表示されたフレーズを正確に入力します。

====
+
[listing]
----
cluster1::> storage encryption disk destroy -disk 1.10.2

Warning: This operation will cryptographically destroy 1 spare or broken
         self-encrypting disks on 1 node.
         You cannot reuse destroyed disks unless you revert
         them to their original state using the PSID value.
         To continue, enter
          destroy disk
         :destroy disk

Info: Starting destroy on 1 disk.
      View the status of the operation by using the
      "storage encryption disk show-status" command.
----

