---
permalink: encryption-at-rest/emergency-shred-data-disks-storage-encryption-task.html 
sidebar: sidebar 
keywords: sanitize, fips, drive, sed, psid, physical secure ID, nrd plus, emergency 
summary: セキュリティに関する緊急事態が発生した場合は、ストレージ システムまたはKMIPサーバへの給電が遮断されていても、FIPSドライブまたはSEDへのアクセスをただちに禁止できます。 
---
= ONTAPのFIPSドライブまたはSEDで緊急データ消去を実行
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
セキュリティに関する緊急事態が発生した場合は、ストレージ システムまたはKMIPサーバへの給電が遮断されていても、FIPSドライブまたはSEDへのアクセスをただちに禁止できます。

.開始する前に
* 使用しているKMIPサーバに給電されていない場合は、KMIPサーバに簡単に破棄できる認証アイテム（スマート カードやUSBドライブなど）が設定されている必要があります。
* このタスクを実行するには、クラスタ管理者である必要があります。


.手順
. FIPSドライブまたはSEDのデータの緊急時のシュレッディングを実行します。
+
|===


| 状況 2+| 操作 


 a| 
ストレージ システムに給電されており、ストレージ システムを適切な手順でオフラインにする時間がある
 a| 
.. ストレージ システムがHAペアとして設定されている場合は、テイクオーバーを無効にします。
.. すべてのアグリゲートをオフラインにしてから削除します。
.. 権限レベルを詳細に設定します：+
`set -privilege advanced`
.. ドライブが FIPS 準拠モードの場合は、ノードの FIPS 認証キー ID をデフォルトの MSID に戻します：+
`storage encryption disk modify -disk * -fips-key-id 0x0`
.. ストレージ システムを停止します。
.. メンテナンス モードでブートします。
.. ディスクを完全消去するか破棄します。
+
*** ディスク上のデータにアクセスできないようにしながらもディスクを再利用できるようにするには、ディスクをサニタイズします：+
`disk encrypt sanitize -all`
*** ディスク上のデータにアクセスできないようにし、ディスクを保存する必要がない場合は、ディスクを破棄します：
`disk encrypt destroy disk_id1 disk_id2 …`


+

NOTE:  `disk encrypt sanitize`コマンドと `disk encrypt destroy`コマンドはメンテナンスモード専用です。これらのコマンドは各HAノードで実行する必要があり、破損したディスクでは使用できません。

.. パートナー ノードに対して同じ手順を繰り返します。これで、ストレージ システムは永続的に無効な状態になり、すべてのデータが消去されます。システムを再度使用するには、再設定する必要があります。




 a| 
ストレージ システムに給電されており、データをただちにシュレッディングする必要がある
 a| 
.. *ディスク上のデータにアクセスできないようにしながらもディスクを再利用できるようにするには、ディスクをサニタイズします：*
.. ストレージ システムがHAペアとして設定されている場合は、テイクオーバーを無効にします。
.. 権限レベルをadvancedに設定します。
+
`set -privilege advanced`

.. ドライブがFIPS準拠モードの場合は、ノードのFIPS認証キーIDをデフォルトのMSIDに戻します。
+
`storage encryption disk modify -disk * -fips-key-id 0x0`

.. ディスクをサニタイズします：
+
`storage encryption disk sanitize -disk * -force-all-states true`


 a| 
.. *ディスク上のデータにアクセスできないようにし、ディスクを保存する必要がない場合は、ディスクを破壊します：*
.. ストレージ システムがHAペアとして設定されている場合は、テイクオーバーを無効にします。
.. 権限レベルをadvancedに設定します。
+
`set -privilege advanced`

.. ディスクを破壊します：
`storage encryption disk destroy -disk * -force-all-states true`




 a| 
ストレージ システムがパニック状態になります。これで、ストレージ システムは永続的に無効な状態になり、すべてのデータが消去されます。システムを再度使用するには、再設定する必要があります。



 a| 
KMIPサーバに給電されているが、ストレージ システムには給電されていない
 a| 
.. KMIPサーバにログインします。
.. アクセスを禁止するデータを含むFIPSドライブまたはSEDに関連付けられているすべてのキーを破棄します。これにより、ストレージ システムからディスク暗号化キーにアクセスできなくなります。




 a| 
KMIPサーバまたはストレージ システムに給電されていない
 a| 
KMIPサーバ用の認証アイテム（スマート カードなど）を破棄します。これにより、ストレージ システムからディスク暗号化キーにアクセスできなくなります。

|===


.関連情報
* link:https://docs.netapp.com/us-en/ontap-cli/storage-encryption-disk-destroy.html["ストレージ暗号化ディスク破壊"^]
* link:https://docs.netapp.com/us-en/ontap-cli/storage-encryption-disk-modify.html["ストレージ暗号化ディスクの変更"^]
* link:https://docs.netapp.com/us-en/ontap-cli/storage-encryption-disk-sanitize.html["ストレージ暗号化ディスク完全消去"^]

