---
permalink: encryption-at-rest/enable-encryption-new-volume-task.html 
sidebar: sidebar 
keywords: encryption, new volume, NAE, NVE, volume create 
summary: 新しいボリュームで暗号化を有効にするには、volume create コマンドを使用できます。 
---
= ONTAPで新しいボリュームの暗号化を有効にする
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
 `volume create`コマンドを使用して、新しいボリュームで暗号化を有効にすることができます。

.タスク概要
NetApp ボリューム暗号化（NVE）と、ONTAP 9.6以降ではNetApp アグリゲート暗号化（NAE）を使用してボリュームを暗号化できます。NAEとNVEの詳細については、xref:configure-netapp-volume-encryption-concept.html[ボリューム暗号化の概要]を参照してください。

この手順で説明されているコマンドの詳細については、link:https://docs.netapp.com/us-en/ontap-cli/["ONTAPコマンド リファレンス"^]を参照してください。

新しいボリュームの暗号化を有効にする手順は、使用しているONTAPのバージョンと環境によって異なります。

* ONTAP 9.4以降では、オンボードキーマネージャのセットアップ時に `cc-mode`を有効にすると、 `-encrypt true`を指定したかどうかに関係なく、 `volume create`コマンドで作成したボリュームが自動的に暗号化されます。
* ONTAP 9.6以前のリリースでは、暗号化を有効にするには `-encrypt true`と `volume create`コマンドを使用する必要があります（ `cc-mode`を有効にしていない場合）。
* ONTAP 9.6でNAEボリュームを作成する場合は、アグリゲートレベルでNAEを有効にする必要があります。このタスクの詳細については、xref:enable-aggregate-level-encryption-nve-license-task.html[VEライセンスでアグリゲートレベルの暗号化を有効にする]を参照してください。
* ONTAP 9.7以降では、link:../encryption-at-rest/install-license-task.html["VEライセンス"]とオンボードまたは外部キー管理を使用している場合、新規作成されたボリュームはデフォルトで暗号化されます。デフォルトでは、NAEアグリゲートに作成される新規ボリュームは、NVEではなくNAEタイプになります。
+
** ONTAP 9.7以降のリリースでは、NAEアグリゲートにボリュームを作成する `volume create`コマンドに `-encrypt true`を追加すると、そのボリュームはNAEではなくNVE暗号化されます。NAEアグリゲート内のすべてのボリュームは、NVEまたはNAEのいずれかで暗号化する必要があります。





NOTE: NAEアグリゲートではプレーンテキスト ボリュームがサポートされません。

.手順
. 新しいボリュームを作成し、そのボリュームで暗号化を有効にするかどうかを指定します。新しいボリュームがNAEアグリゲートに配置する場合、デフォルトでNAEで暗号化されます。
+
[cols="25,75"]
|===


| 作成するには... | 使用するコマンド 


 a| 
NAEボリューム
 a| 
`volume create -vserver _SVM_name_ -volume _volume_name_ -aggregate _aggregate_name_`



 a| 
NVEボリューム
 a| 
`volume create -vserver _SVM_name_ -volume _volume_name_ -aggregate _aggregate_name_ -encrypt true` +


NOTE: NAEがサポートされていないONTAP 9.6以前では、 `-encrypt true`ボリュームをNVEで暗号化することを指定します。ボリュームがNAEアグリゲート内に作成されるONTAP 9.7以降では、 `-encrypt true`NAEのデフォルトの暗号化タイプをオーバーライドして、代わりにNVEボリュームを作成します。



 a| 
プレーンテキスト ボリューム
 a| 
`volume create -vserver _SVM_name_ -volume _volume_name_ -aggregate _aggregate_name_ -encrypt false`

|===
+
 `volume create`の詳細については、link:https://docs.netapp.com/us-en/ontap-cli/volume-create.html["ONTAPコマンド リファレンス"^]を参照してください。

. ボリュームで暗号化が有効になっていることを確認します。
+
`volume show -is-encrypted true`

+
 `volume show`の詳細については、link:https://docs.netapp.com/us-en/ontap-cli/volume-show.html["ONTAPコマンド リファレンス"^]をご覧ください。



.結果
ノードの暗号化キーの格納にKMIPサーバを使用している場合は、ボリュームを暗号化すると暗号化キーがサーバに自動的に「プッシュ」されます。
