---
permalink: encryption-at-rest/enable-external-key-management-96-later-nve-task.html 
sidebar: sidebar 
keywords: enabling, external key management, ontap 9.6, later, nve 
summary: 1 つ以上の KMIP サーバを使用して、暗号化されたデータにアクセスする際にクラスタで使用するキーを安全に保管できます。ONTAP 9.6 以降では、 1 つ以上の KMIP サーバを使用して、特定の SVM が暗号化されたデータにアクセスする際に使用するキーを安全に保管できます。 
---
= ONTAP 9.6 以降で外部キー管理を有効にする（ NVE ）
:icons: font
:imagesdir: ../media/


[role="lead"]
1 つ以上の KMIP サーバを使用して、暗号化されたデータにアクセスする際にクラスタで使用するキーを安全に保管できます。ONTAP 9.6 以降では、 1 つ以上の KMIP サーバを使用して、特定の SVM が暗号化されたデータにアクセスする際に使用するキーを安全に保管できます。

.必要なもの
* KMIP SSL クライアント証明書とサーバ証明書をインストールしておく必要があります。
* このタスクを実行するには、クラスタ管理者または SVM の管理者である必要があります。
* MetroCluster 環境で外部キー管理を有効にする場合は、外部キー管理を有効にする前に MetroCluster が完全に設定されている必要があります。


1 つのクラスタまたは SVM に最大 4 つの KMIP サーバを接続できます。冗長性とディザスタリカバリのために、少なくとも 2 台のサーバを使用することを推奨します。

外部キー管理のスコープによって、キー管理サーバの保護対象がクラスタ内のすべての SVM になるか、選択した SVM のみになるかが決まります。

* クラスタ内のすべての SVM に対して外部キー管理を設定するには、 _cluster scop_ を使用します。クラスタ管理者は、サーバに格納されているすべてのキーにアクセスできます。
* ONTAP 9.6 以降では、 _svm scop_ を使用して、クラスタ内のデータ SVM に外部キー管理を設定できます。各テナントが異なる SVM （または SVM のセット）を使用してデータを提供するマルチテナント環境には、この方法が最適です。特定のテナントの SVM 管理者だけが、そのテナントのキーにアクセスできます。
* マルチテナント環境の場合は、次のコマンドを使用して、 _MT_EK_MGMT_ のライセンスをインストールします。
+
「システムライセンス追加 - ライセンスコード <MT_EK_MGMT ライセンスコード >` 」

+
コマンド構文全体については、コマンドのマニュアルページを参照してください。



同じクラスタで両方のスコープを使用できます。1 つの SVM に対してキー管理サーバが設定されている場合、 ONTAP はそれらのサーバのみを使用してキーを保護します。それ以外 ONTAP の場合は、クラスタに対して設定されたキー管理サーバでキーが保護されます。

オンボードキー管理はクラスタスコープで設定でき、外部キー管理は SVM スコープで設定できます。「 securitykey-manager key migrate 」コマンドを使用すると、クラスタスコープのオンボードキー管理から SVM スコープの外部キー管理ツールにキーを移行できます。

.手順
. クラスタのキー管理ツールの接続を設定します。
+
「 security key-manager external enable -vserver admin_svm -key_servers host_name | ip_address ： port 、……」 -client-cert client_certificate-server-ca-cert-certserver_CA_certificates 」と入力します

+
[NOTE]
====
「 securitykey-manager external enable 」コマンドは、「 securitykey-manager setup 」コマンドに代わるものです。クラスタ・ログイン・プロンプトでこのコマンドを実行すると '_admin_svm_name はデフォルトで現在のクラスタの管理 SVM に設定されますクラスタスコープを設定するには、クラスタ管理者である必要があります。「 securitykey-manager external modify 」コマンドを実行して、外部キー管理設定を変更できます。

====
+
次のコマンドは 'cluster1 の外部キー管理を 3 台の外部キー・サーバで有効にします最初のキーサーバはホスト名とポートで指定し、 2 番目のキーサーバは IP アドレスとデフォルトポートで指定し、 3 番目のキーサーバは IPv6 アドレスとポートで指定します。

+
[listing]
----
clusterl::> security key-manager external enable -vserver cluster1 -key-servers ks1.local:15696,10.0.0.10,[fd20:8b1e:b255:814e:32bd:f35c:832c:5a09]:1234 -client-cert AdminVserverClientCert -server-ca-certs AdminVserverServerCaCert
----
. キー管理ツールとして SVM を設定します。
+
「 securitykey-manager external enable -vserver SVM-key-servers host_name | ip_address ： port 、……」 -client-cert client_certificate-server-ca-cert-certserver_CA_certificates 」と入力します

+
[NOTE]
====
このコマンドを SVM のログインプロンプトで実行すると、「 S vm 」はデフォルトで現在の SVM に設定されます。SVM スコープを設定するには、クラスタ管理者または SVM 管理者である必要があります。「 securitykey-manager external modify 」コマンドを実行して、外部キー管理設定を変更できます。

====
+
次のコマンドは、デフォルトポート 5696 をリスンする 1 つのキーサーバを使用して、「 vm1 」の外部キー管理を有効にします。

+
[listing]
----
svm1l::> security key-manager external enable -vserver svm1 -key-servers keyserver.svm1.com -client-cert SVM1ClientCert -server-ca-certs SVM1ServerCaCert
----
. 最後の手順をその他の SVM に対して繰り返します。
+
[NOTE]
====
さらに、「 securitykey-manager external add servers 」コマンドを使用して、追加の SVM を設定することもできます。「 securitykey-manager external add servers 」コマンドは、「 securitykey-manager add 」コマンドに代わるコマンドです。コマンド構文全体については、マニュアルページを参照してください。

====
. 設定したすべての KMIP サーバが接続されていることを確認します。
+
「 securitykey-manager external show-status -node node_name 」

+
[NOTE]
====
「 securitykey-manager external show-status 」コマンドは、「 securitykey-manager show -status 」コマンドに代わるコマンドです。コマンド構文全体については、マニュアルページを参照してください。

====
+
[listing]
----
cluster1::> security key-manager external show-status

Node  Vserver  Key Server                                     Status
----  -------  ---------------------------------------        -------------
node1
      svm1
               keyserver.svm1.com:5696                        available
      cluster1
               10.0.0.10:5696                                 available
               fd20:8b1e:b255:814e:32bd:f35c:832c:5a09:1234   available
               ks1.local:15696                                available
node2
      svm1
               keyserver.svm1.com:5696                        available
      cluster1
               10.0.0.10:5696                                 available
               fd20:8b1e:b255:814e:32bd:f35c:832c:5a09:1234   available
               ks1.local:15696                                available

8 entries were displayed.
----

