---
permalink: encryption-at-rest/key-management-servers-not-reachable-boot-concept.html 
sidebar: sidebar 
keywords: what, happens, key management servers, not reachable, boot, process 
summary: ONTAP は、NSE 用に設定されたストレージ システムがブート プロセス中に指定されたキー管理サーバのいずれにもアクセスできない場合に、望ましくない動作を回避するために特定の予防措置を講じます。 
---
= ONTAPブートプロセス中にキー管理サーバにアクセスできない場合の動作
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
ONTAP は、NSE 用に設定されたストレージ システムがブート プロセス中に指定されたキー管理サーバのいずれにもアクセスできない場合に、望ましくない動作を回避するために特定の予防措置を講じます。

ストレージシステムがNSE用に設定され、SEDのキーが再設定されてロックされ、SEDの電源がオンになっている場合、ストレージシステムは、データにアクセスする前に、キー管理サーバーから必要な認証キーを取得して、SEDに対して認証を行う必要があります。

ストレージシステムは、指定されたキー管理サーバへの接続を最大3時間試行します。その時間が経過してもいずれのサーバにも接続できない場合、ブートプロセスは停止し、ストレージシステムは停止します。

ストレージシステムが指定されたキー管理サーバへの接続に成功した場合、最大15分間SSL接続の確立を試行します。ストレージシステムが指定されたキー管理サーバとのSSL接続を確立できない場合、ブートプロセスは停止し、ストレージシステムは停止します。

ストレージシステムがキー管理サーバへの接続を試行している間、失敗した接続試行に関する詳細情報がCLIに表示されます。Ctrl+Cキーを押すことで、いつでも接続試行を中断できます。

セキュリティ対策として、SEDへの無許可のアクセス試行回数には上限があり、試行回数が上限に達すると既存データへのアクセスは無効になります。指定されたどのキー管理サーバにもアクセスできず、適切な認証キーを取得できない場合、ストレージ システムはデフォルト キーでの認証のみ試行できますが、その場合、認証が失敗してパニック状態になります。パニック状態になった場合に自動的にリブートするように構成されている場合、ストレージ システムはブート ループに入り、SEDでの認証は繰り返し失敗します。

このようなシナリオでストレージ システムが停止するのは、ストレージ システムがブート ループに入ることを回避し、上限を超えて連続して認証に失敗したためにSEDが永続的にロックされて意図しないデータ損失が発生することを回避するための設計です。ロックアウト保護の上限とタイプは、SEDの仕様とタイプによって異なります。

[cols="30,15,55"]
|===


| SEDタイプ | ロックアウトにつながる認証の連続失敗回数 | 安全限界に達したときのロックアウト保護タイプ 


 a| 
HDD
 a| 
1024
 a| 
永続的。適切な認証キーが再び利用可能になったとしても、データを回復することはできません。



 a| 
X440_PHM2800MCTO 800GB NSE SSD（ファームウェアリビジョン NA00 または NA01）
 a| 
5
 a| 
一時的。ロックアウトはディスクの電源を入れ直すまでのみ有効です。



 a| 
X577_PHM2800MCTO 800GB NSE SSD（ファームウェアリビジョン NA00 または NA01）
 a| 
5
 a| 
一時的。ロックアウトはディスクの電源を入れ直すまでのみ有効です。



 a| 
X440_PHM2800MCTO 800GB NSE SSD（ファームウェアリビジョンが高いもの）
 a| 
1024
 a| 
永続的。適切な認証キーが再び利用可能になったとしても、データを回復することはできません。



 a| 
X577_PHM2800MCTO 800GB NSE SSD（ファームウェアリビジョンが高いもの）
 a| 
1024
 a| 
永続的。適切な認証キーが再び利用可能になったとしても、データを回復することはできません。



 a| 
その他すべてのSSDモデル
 a| 
1024
 a| 
永続的。適切な認証キーが再び利用可能になったとしても、データを回復することはできません。

|===
すべての SED タイプでは、認証が成功すると試行回数がゼロにリセットされます。

指定されたキー管理サーバーに到達できないためにストレージ システムが停止するというシナリオに遭遇した場合は、ストレージ システムの起動を続行する前に、まず通信障害の原因を特定して修正する必要があります。
