---
permalink: encryption-at-rest/modify-external-key-server-96-later-task.html 
sidebar: sidebar 
keywords: modifying, external key management, server, properties 
summary: ONTAP 9.6 以降では、 security key-manager external modify -server コマンドを使用して、外部キー管理サーバの I/O タイムアウトとユーザ名を変更できます。 
---
= 外部キー管理サーバのプロパティを変更します
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
ONTAP 9.6以降では、を使用できます `security key-manager external modify-server` コマンドを使用して、外部キー管理サーバのI/Oタイムアウトとユーザ名を変更します。

.作業を開始する前に
* このタスクを実行するには、クラスタ管理者または SVM の管理者である必要があります。
* このタスクを実行するには advanced 権限が必要です。
* MetroCluster 環境では、管理SVMの両方のクラスタで上記の手順を繰り返す必要があります。


.手順
. ストレージシステムで、 advanced 権限レベルに切り替えます。
+
`set -privilege advanced`

. クラスタの外部キー管理サーバのプロパティを変更します。
+
`security key-manager external modify-server -vserver admin_SVM -key-server host_name|IP_address:port,... -timeout 1...60 -username user_name`

+
[NOTE]
====
タイムアウト値は秒単位で表されます。ユーザ名を変更すると、新しいパスワードの入力を求められます。クラスタのログインプロンプトでコマンドを実行すると、 `_admin_SVM_` デフォルトでは、現在のクラスタの管理SVMが使用されます。外部キー管理サーバのプロパティを変更するには、クラスタ管理者である必要があります。

====
+
次のコマンドは、のタイムアウト値を45秒に変更します `cluster1` デフォルトポート5696をリスンしている外部キー管理サーバ：

+
[listing]
----
clusterl::> security key-manager external modify-server -vserver cluster1 -key-server ks1.local -timeout 45
----
. SVM の外部キー管理サーバのプロパティを変更します（ NVE のみ）。
+
`security key-manager external modify-server -vserver SVM -key-server host_name|IP_address:port,... -timeout 1...60 -username user_name`

+
[NOTE]
====
タイムアウト値は秒単位で表されます。ユーザ名を変更すると、新しいパスワードの入力を求められます。SVMのログインプロンプトでコマンドを実行すると、 `_SVM_` デフォルトは現在のSVMです。外部キー管理サーバのプロパティを変更するには、クラスタ管理者または SVM 管理者である必要があります。

====
+
のユーザ名とパスワードを変更するコマンドの例を次に示します `svm1` デフォルトポート5696をリスンしている外部キー管理サーバ：

+
[listing]
----
svml::> security key-manager external modify-server -vserver svm11 -key-server ks1.local -username svm1user
Enter the password:
Reenter the password:
----
. 最後の手順をその他の SVM に対して繰り返します。

