---
permalink: encryption-at-rest/move-encrypted-volume-task.html 
sidebar: sidebar 
keywords: moving, encrypted, volume 
summary: volume move start コマンドを使用して、暗号化されたボリュームを移動できます。移動したボリュームは、同じアグリゲートまたは別のアグリゲートに配置できます。 
---
= ONTAPで暗号化されたボリュームを移動する
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
 `volume move start`コマンドを使用して、暗号化されたボリュームを移動できます。移動したボリュームは、同じアグリゲートまたは別のアグリゲートに配置できます。

.タスク概要
デスティネーション ノードまたはデスティネーション ボリュームでボリューム暗号化がサポートされていない場合、移動は失敗します。

 `-encrypt-destination`オプションは、 `volume move start`暗号化されたボリュームの場合、デフォルトでtrueに設定されます。宛先ボリュームを暗号化しないことを指定する必要があるのは、ボリューム上のデータが誤って暗号化解除されないようにするためです。

.開始する前に
このタスクを実行するには、クラスタ管理者である必要があります。

.手順
. 既存の暗号化されたボリュームを移動し、ボリュームのデータを暗号化されたままにします。
+
`volume move start -vserver _SVM_name_ -volume _volume_name_ -destination-aggregate _aggregate_name_`

+
 `volume move start`の詳細については、link:https://docs.netapp.com/us-en/ontap-cli/volume-move-start.html["ONTAPコマンド リファレンス"^]を参照してください。

+
次のコマンドは、 `vol1`という名前の既存のボリュームを宛先アグリゲート `aggr3`に移動し、ボリューム上のデータを暗号化されたままにします（：）

+
[listing]
----
cluster1::> volume move start -vserver vs1 -volume vol1 -destination-aggregate aggr3
----
. ボリュームで暗号化が有効になっていることを確認します。
+
`volume show -is-encrypted true`

+
 `volume show`の詳細については、link:https://docs.netapp.com/us-en/ontap-cli/volume-show.html["ONTAPコマンド リファレンス"^]をご覧ください。

+
次のコマンドは、 `cluster1`の暗号化されたボリュームを表示します：

+
[listing]
----
cluster1::> volume show -is-encrypted true

Vserver  Volume  Aggregate  State  Type  Size  Available  Used
-------  ------  ---------  -----  ----  -----  --------- ----
vs1      vol1    aggr3     online    RW  200GB    160.0GB  20%
----

