---
permalink: encryption-at-rest/move-encrypted-volume-task.html 
sidebar: sidebar 
keywords: moving, encrypted, volume 
summary: 暗号化されたボリュームを移動するには、 volume move start コマンドを使用します。ボリュームを移動するアグリゲートは同じアグリゲートでも別のアグリゲートでもかまいません。 
---
= 暗号化されたボリュームを移動します
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
を使用できます `volume move start` 暗号化されたボリュームを移動するコマンド。ボリュームを移動するアグリゲートは同じアグリゲートでも別のアグリゲートでもかまいません。

.このタスクについて
デスティネーションノードまたはデスティネーションボリュームでボリューム暗号化がサポートされていない場合、移動は失敗します。

。 `-encrypt-destination` のオプション `volume move start` 暗号化されたボリュームの場合、デフォルトはtrueです。デスティネーションボリュームを暗号化しないように指定すると、ボリューム上のデータの暗号化が誤って解除されることがなくなります。

.作業を開始する前に
このタスクを実行するには、クラスタ管理者である必要があります。または、クラスタ管理者から権限を委譲されたSVM管理者を指定することもできます。詳細については、を参照してください link:delegate-volume-encryption-svm-administrator-task.html["volume moveコマンドの実行権限を委譲する"]。

.手順
. 既存の暗号化されたボリュームを移動し、ボリュームのデータを暗号化されたままにします。
+
`volume move start -vserver _SVM_name_ -volume _volume_name_ -destination-aggregate _aggregate_name_`

+
コマンド構文全体については、コマンドのマニュアルページを参照してください。

+
次のコマンドは、という名前の既存のボリュームを移動します `vol1` デスティネーションアグリゲートに移動します `aggr3` ボリューム上のデータは暗号化されたままになります。

+
[listing]
----
cluster1::> volume move start -vserver vs1 -volume vol1 -destination-aggregate aggr3
----
. ボリュームで暗号化が有効になっていることを確認します。
+
`volume show -is-encrypted true`

+
コマンド構文全体については、コマンドのマニュアルページを参照してください。

+
次のコマンドは、の暗号化されたボリュームを表示します `cluster1`：

+
[listing]
----
cluster1::> volume show -is-encrypted true

Vserver  Volume  Aggregate  State  Type  Size  Available  Used
-------  ------  ---------  -----  ----  -----  --------- ----
vs1      vol1    aggr3     online    RW  200GB    160.0GB  20%
----

