---
permalink: encryption-at-rest/purge-data-encrypted-asynchronous-snapmirror-task.html 
sidebar: sidebar 
keywords: securely, purging, scrub, data, encrypted, volume, nve, netapp, volume encryption, snapmirror, asynchronous 
summary: ONTAP 9 .8以降では、セキュアパージを使用して、SnapMirror非同期関係にあるNVE対応ボリュームのデータを無停止で「スクラビング」できます。 
---
= SnapMirror非同期関係を使用して暗号化されたONTAPボリュームからデータをスクラブする
:allow-uri-read: 


[role="lead"]
ONTAP 9 .8以降では、セキュアパージを使用して、SnapMirror非同期関係にあるNVE対応ボリュームで無停止でデータを「スクラビング」できます。

.開始する前に
* このタスクを実行するには、クラスタ管理者である必要があります。
* このタスクには高度なPrivilegesが必要です。


.タスクの内容
削除されたファイル内のデータ量によっては、セキュアパージが完了するまでに数分から数時間かかることがあります。処理のステータスは、コマンドを使用して確認できます `volume encryption secure-purge show`。処理を終了するには、コマンドを使用し `volume encryption secure-purge abort`ます。


NOTE: SANホストでセキュアパージを実行するには、パージするファイルを含むLUN全体を削除するか、パージするファイルに属するブロックに対してLUNに穴を開ける必要があります。LUNを削除できない場合や、ホストオペレーティングシステムでLUNのホールパンチングがサポートされていない場合は、セキュアパージを実行できません。

.手順
. ストレージシステムで、advanced権限レベルに切り替えます。
+
`set -privilege advanced`

. セキュアパージを実行するファイルまたはLUNを削除します。
+
** NASクライアントで、セキュアパージを実行するファイルを削除します。
** SANホストで、セキュアパージを実行するLUNを削除するか、パージするファイルに属するブロックに対してLUNでホールパンチングを実行します。


. 非同期関係のデスティネーションボリュームをセキュアパージする準備をします。
+
`volume encryption secure-purge start -vserver _SVM_name_ -volume _volume_name_ -prepare true`

+
SnapMirror非同期関係の各ボリュームに対してこの手順を繰り返します。

. セキュアパージを実行するファイルがSnapshotに含まれている場合は、Snapshotを削除します。
+
`snapshot delete -vserver _SVM_name_ -volume _volume_name_ -snapshot`

. セキュアパージを実行するファイルがベースSnapshotに含まれている場合は、次の手順を実行します。
+
.. SnapMirror非同期関係のデスティネーションボリュームにSnapshotを作成します。
+
`volume snapshot create -snapshot snapshot_name -vserver _SVM_name_ -volume _volume_name_`

.. SnapMirrorを更新してベースSnapshotを転送します。
+
`snapmirror update -source-snapshot _snapshot_name_ -destination-path _destination_path_`

+
SnapMirror非同期関係の各ボリュームに対してこの手順を繰り返します。

.. 手順（a）と（b）を、ベースSnapshotの数に1を加えた値に繰り返します。
+
たとえば、ベースSnapshotが2つある場合は、手順（a）と（b）を3回繰り返します。

.. ベースSnapshotが存在することを確認します。+
`snapshot show -vserver _SVM_name_ -volume _volume_name_`
.. ベースSnapshotを削除します。+
`snapshot delete -vserver _svm_name_ -volume _volume_name_ -snapshot snapshot`


. 削除したファイルのセキュアパージを実行します。
+
`volume encryption secure-purge start -vserver _svm_name_ -volume _volume_name_`

+
SnapMirror非同期関係の各ボリュームに対してこの手順を繰り返します。

+
次のコマンドは、 SVM 「 vs1 」上の「 vol1 」にある削除済みファイルを安全にパージします。

+
[listing]
----
cluster1::> volume encryption secure-purge start -vserver vs1 -volume vol1
----
. セキュアパージ処理のステータスを確認します。
+
`volume encryption secure-purge show`



.関連情報
* link:https://docs.netapp.com/us-en/ontap-cli/snapmirror-update.html["snapmirror update"^]

