---
permalink: encryption-at-rest/purge-data-encrypted-volume-without-snapmirror-task.html 
sidebar: sidebar 
keywords: secure, purge, scrub, data, encrypted, volume, nve, netapp, volume, encryption, snapmirror 
summary: ONTAP 9.4 以降では、セキュアパージを使用して、 NVE 対応ボリューム上のデータを無停止で「スクラビング」できます。 
---
= SnapMirror 関係なしで暗号化されたボリューム上のデータをセキュアにパージします
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
ONTAP 9.4 以降では、 NVE 対応ボリューム上で、システムを停止することなく「 crub 」データにセキュアパージを使用できます。

.必要なもの
* このタスクを実行するには、クラスタ管理者である必要があります。
* このタスクを実行するには advanced 権限が必要です。


削除されたファイルのデータ量によっては、セキュアパージが完了するまでに数分から数時間かかることがあります。volume encryption secure-purge show コマンドを使用して、処理のステータスを表示できます。volume encryption secure-purge abort コマンドを使用して、処理を終了できます。

[NOTE]
====
SAN ホストでセキュアパージを実行するには、パージするファイルを含む LUN 全体を削除するか、パージするファイルに属するブロックの LUN で穴を開ける必要があります。LUN を削除できない場合や、ホストオペレーティングシステムで LUN のパンチ穴がサポートされていない場合は、セキュアパージを実行できません。

====
.手順
. セキュアパージするファイルまたは LUN を削除します。
+
** NAS クライアントで、セキュアパージするファイルを削除します。
** SAN ホストで、パージするファイルに属するブロックのために、 LUN から安全にパージまたはパンチ穴を開ける LUN を削除します。


. ストレージシステムで、 advanced 権限レベルに切り替えます。
+
「 advanced 」の権限が必要です

. 安全にパージするファイルがスナップショットにある場合は、スナップショットを削除します。
+
「 snapshot-delete -vserver SVM_name -volume vol_name -snapshot 」という Snapshot コピーを削除しました

. 削除したファイルを安全にパージします。
+
'volume encryption secure-purge start -vserver svm_name -volume volume_name

+
次のコマンドは 'vs1` 上の 'vol1' の削除されたファイルを安全にパージします

+
[listing]
----
cluster1::> volume encryption secure-purge start -vserver vs1 -volume vol1
----
. セキュアパージ処理のステータスを確認します。
+
volume encryption secure-purgeshow


