---
permalink: encryption-at-rest/restore-onboard-key-management-encryption-keys-task.html 
sidebar: sidebar 
keywords: restoring, onboard, key management encryption 
summary: 場合によっては、オンボードキー管理の暗号化キーのリストアが必要になることがあります。キーのリストアが必要であることを確認したら、オンボードキーマネージャセットアップウィザードを実行してキーをリストアできます。 
---
= オンボードキー管理の暗号化キーをリストア
:icons: font
:imagesdir: ../media/


[role="lead"]
場合によっては、オンボードキー管理の暗号化キーのリストアが必要になることがあります。キーのリストアが必要であることを確認したら、オンボードキーマネージャセットアップウィザードを実行してキーをリストアできます。

.必要なもの
* NSE で外部キー管理（ KMIP ）サーバを使用している場合は、外部キー管理ツールのデータベースを削除しておく必要があります。
+
xref:delete-key-management-database-task.adoc[外部キー管理からオンボードキー管理への移行]

* このタスクを実行するには、クラスタ管理者である必要があります。


ONTAP 9.6 以降では、「 securitykey-manager key query -node node 」コマンドを使用して、キーのリストアが必要かどうかを確認できます。

ONTAP 9.5 以前では、「 securitykey-manager key show 」コマンドを使用して、キーのリストアが必要かどうかを確認できます。

.手順
. ONTAP 9.8 以降を実行していて、ルート・ボリュームが暗号化されている場合は、次の手順を実行します。
+
ONTAP 9.7 以前を実行している場合、または ONTAP 9.8 以降を実行していて、ルートボリュームが暗号化されていない場合は、この手順を省略してください。

+
.. ノードをブート・メニューで '(10) Set onboard key management recovery secrets オプションを選択します
.. このオプションを使用するには 'y' を入力します
.. プロンプトで、クラスタのオンボードキー管理のパスフレーズを入力します。
.. プロンプトで、バックアップキーのデータを入力します。
+
ノードがブートメニューに戻ります。

.. ブート・メニューから ' オプション (1) Normal Boot を選択します


. キーをリストアします。
+
|===
| ONTAP バージョン | 使用するコマンド 


 a| 
ONTAP 9.6 以降
 a| 
「セキュリティキーマネージャオンボード同期」



 a| 
ONTAP 9.5 以前
 a| 
「 securitykey manager setup -node node 」を参照してください

|===
+
コマンド構文全体については、マニュアルページを参照してください。

+
ONTAP 9.6 の次のコマンドを使用して、オンボードキー階層のキーを同期します。

+
[listing]
----
cluster1::> security key-manager onboard sync

Enter the cluster-wide passphrase for onboard key management in Vserver "cluster1"::    <32..256 ASCII characters long text>
----
. パスフレーズのプロンプトで、クラスタのオンボードキー管理のパスフレーズを入力します。

