---
permalink: encryption-at-rest/secure-purge-data-encrypted-volume-concept.html 
sidebar: sidebar 
keywords: secure, purge, scrub, data, encrypted, volume, nve, netapp 
summary: 'ONTAP 9 4以降では、セキュアパージを使用して、NVE対応ボリュームのデータを無停止でスクラビングできます。暗号化されたボリュームのデータをスクラビングすると、物理メディアからデータをリカバリできなくなります。たとえば、ブロックが上書きされたときにデータのトレースが残っていた場合 `spillage,`や、空になるテナントのデータを安全に削除した場合などです。' 
---
= 暗号化されたボリューム上のデータのセキュアパージの概要
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
ONTAP 9 4以降では、セキュアパージを使用して、NVE対応ボリュームのデータを無停止でスクラビングできます。暗号化されたボリュームのデータをスクラビングすることで、「柱」、「ブロックが上書きされたときにデータトレースが残されている」などの物理メディアからデータをリカバリすることができなくなります。また、解約するテナントのデータを安全に削除することもできます。

セキュアパージは、NVE対応ボリューム上で以前に削除されたファイルに対してのみ機能します。暗号化されていないボリュームはスクラビングできません。キーの提供には、オンボードキーマネージャではなく、KMIPサーバを使用する必要があります。



== セキュアパージを使用する場合の考慮事項

* NetApp Aggregate Encryption（NAE）が有効になっているアグリゲートで作成したボリュームでは、セキュアパージはサポートされません。
* セキュアパージは、NVE対応ボリューム上で以前に削除されたファイルに対してのみ機能します。
* 暗号化されていないボリュームはスクラビングできません。
* キーの提供には、オンボードキーマネージャではなく、KMIPサーバを使用する必要があります。


セキュアパージの動作は、ONTAPのバージョンによって異なります。

[role="tabbed-block"]
====
.ONTAP 9.8以降
--
* セキュアパージはMetroClusterとFlexGroupでサポートされています。
* パージするボリュームがSnapMirror関係のソースである場合は、SnapMirror関係を解除してセキュアパージを実行する必要はありません。
* 再暗号化の方法は、SnapMirrorデータ保護を使用するボリュームとSnapMirrorデータ保護（DP）を使用しないボリューム、またはSnapMirror拡張データ保護を使用するボリュームで異なります。
+
** SnapMirrorデータ保護（DP）モードを使用するボリュームでは、デフォルトでボリューム移動再暗号化方式を使用してデータが再暗号化されます。
** SnapMirrorデータ保護を使用しないボリューム、またはSnapMirror XDP（拡張データ保護）モードを使用するボリュームでは、インプレース再暗号化方式がデフォルトで使用されます。
** これらのデフォルト値は、コマンドを使用して変更でき `secure purge re-encryption-method [volume-move|in-place-rekey]`ます。


* デフォルトでは、セキュアパージ処理の実行中に、FlexVolボリューム内のすべてのSnapshotコピーが自動的に削除されます。デフォルトでは、FlexGroupおよびSnapMirrorデータ保護を使用するボリューム内のSnapshotは、セキュアパージ処理で自動的に削除されません。これらのデフォルト値は、コマンドを使用して変更でき `secure purge delete-all-snapshots [true|false]`ます。


--
.ONTAP 9 .7以前：
--
* セキュアパージでは、次の項目はサポートされません。
+
** FlexClone
** SnapVault
** FabricPool


* パージするボリュームがSnapMirror関係のソースである場合は、ボリュームをパージする前にSnapMirror関係を解除する必要があります。
+
ボリューム内に使用中のSnapshotコピーがある場合は、ボリュームをパージする前にSnapshotコピーを解放する必要があります。たとえば、FlexCloneボリュームを親からスプリットする必要がある場合があります。

* セキュアパージ機能を呼び出すと、ボリューム移動がトリガーされ、パージされていない残りのデータが新しいキーで再暗号化されます。
+
移動されたボリュームは現在のアグリゲートに残ります。古いキーは自動的に破棄されるため、パージされたデータをストレージメディアからリカバリできません。



--
====