---
permalink: encryption-at-rest/unencrypt-volume-data-task.html 
sidebar: sidebar 
keywords: unencrypting, volume, data 
summary: volume move start コマンドを使用して、ボリュームデータの移動と暗号化解除を行うことができます。 
---
= ボリュームデータの暗号化を解除します
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
を使用できます `volume move start` ボリュームデータを移動および暗号化解除するコマンド。

.作業を開始する前に
このタスクを実行するには、クラスタ管理者である必要があります。または、クラスタ管理者から権限を委譲されたSVM管理者を指定することもできます。詳細については、を参照してください link:delegate-volume-encryption-svm-administrator-task.html["volume move コマンドの実行権限を委譲します"]。

.手順
. 既存の暗号化されたボリュームを移動し、ボリュームのデータの暗号化を解除します。
+
`volume move start -vserver _SVM_name_ -volume volume_name -destination-aggregate _aggregate_name_ -encrypt-destination false`

+
コマンド構文全体については、コマンドのマニュアルページを参照してください。

+
次のコマンドは、という名前の既存のボリュームを移動します `vol1` デスティネーションアグリゲートに移動します `aggr3` ボリューム上のデータの暗号化を解除します。

+
[listing]
----
cluster1::> volume move start -vserver vs1 -volume vol1 -destination-aggregate aggr3 -encrypt-destination false
----
+
ボリュームの暗号化キーが削除されます。ボリュームのデータの暗号化が解除されます。

. ボリュームで暗号化が無効になっていることを確認します。
+
`volume show -encryption`

+
コマンド構文全体については、コマンドのマニュアルページを参照してください。

+
次のコマンドは、ボリュームが上にあるかどうかを表示します `cluster1` 暗号化：

+
[listing]
----
cluster1::> volume show -encryption

Vserver  Volume   Aggregate   State    Encryption State
-------  ------   ---------   -----    ----------------
vs1      vol1     aggr1       online   none
----

