---
sidebar: sidebar 
permalink: s3-snapshots/delete-s3-snapshot.html 
keywords: s3 snapshots, delete S3 snapshots 
summary: 不要になった S3 スナップショットを削除して、バケット内のストレージ スペースを解放できます。 
---
= ONTAP S3スナップショットを削除する
:hardbreaks:
:toclevels: 1
:allow-uri-read: 
:toclevels: 1
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
不要になったS3 Snapshotを削除して、バケット内のストレージ スペースを解放できます。S3 Snapshotを手動で削除したり、S3バケットに関連付けられたSnapshotポリシーを変更して、スケジュールで保持されるSnapshotの数を変更したりできます。

S3バケットのスナップショットポリシーは、従来のONTAPスナップショットポリシーと同じ削除ルールに従います。スナップショットポリシーの作成の詳細については、link:../data-protection/create-snapshot-policy-task.html["Snapshotポリシーの作成"]を参照してください。

.タスク概要
* あるバージョンのオブジェクト（バージョン管理されたバケット内のもの）や、1つのオブジェクト（バージョン管理されていないバケットのもの）が複数のSnapshotにキャプチャされている場合、そのオブジェクトを保護している最後のSnapshotが削除されるまで、そのオブジェクトはファイル システムから削除されません。
* Snapshotがあるオブジェクトを含むS3バケットを削除するには、そのバケット内のすべてのオブジェクトのSnapshotをすべて削除しておく必要があります。
* クラスタをONTAP 9.16.1より前のONTAPバージョンに戻す必要がある場合は、すべてのバケットのS3スナップショットがすべて削除されていることを確認してください。また、 `vserver object-store-server bucket clear-snapshot-metadata`コマンドを実行してS3バケットのスナップショット メタデータを削除する必要がある場合もあります。詳細については、link:../s3-snapshots/delete-s3-snapshot.html#clear-s3-snapshots-metadata["S3 Snapshotメタデータのクリア"]を参照してください。
* Snapshotをバッチで削除すると、複数のSnapshotにキャプチャされた多数のオブジェクトを削除できるため、個別にSnapshotを削除する場合よりも多くのスペースが効果的に解放されます。その結果、より多くのスペースをストレージ オブジェクト用に再利用できます。


.手順
. 特定のS3 Snapshotを削除するには、以下のコマンドを実行します。
+
[listing]
----
vserver object-store-server bucket snapshot delete -vserver <svm_name> -bucket <bucket_name> -snapshot <snapshot_name>
----
. バケット内のすべてのS3 Snapshotを削除するには、以下のコマンドを実行します。
+
[listing]
----
vserver object-store-server bucket snapshot delete -vserver <svm_name> -bucket <bucket_name> -snapshot *
----




== S3 Snapshotメタデータのクリア

S3 Snapshotでは、Snapshotメタデータもバケット内で生成されます。Snapshotメタデータは、すべてのSnapshotがバケットから削除されても、バケット内に残ります。Snapshotメタデータがあると、以下の処理がブロックされます。

* ONTAP 9.16.1より前のバージョンのONTAPへのクラスタのリバート
* バケットでのSnapMirror S3の設定


これらの処理を実行する前に、バケットからすべてのSnapshotメタデータをクリアする必要があります。

.開始する前に
メタデータのクリアを開始する前に、バケットからすべてのS3 Snapshotを削除しておく必要があります。

.手順
. バケットからSnapshotメタデータをクリアするには、このコマンドを実行します。


[listing]
----
vserver object-store-server bucket clear-snapshot-metadata -vserver <svm_name> -bucket <bucket_name>
----