---
permalink: s3-multiprotocol/nas-data-requirements-client-access-reference.html 
sidebar: sidebar 
keywords: s3, mapping, directory, access, configuration, object, nas, bucket 
summary: S3アクセス用にNASファイルとディレクトリをマッピングすると、NASの標準的な動作が一部変更される点を理解しておくことが重要です。 
---
= NASデータのS3クライアントアクセス要件
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
NASファイルとディレクトリをS3アクセス用にマッピングする場合は、互換性が確保されていない問題がいくつかあることに注意してください。NASファイル階層は、S3 NASバケットを使用して階層を提供する前に調整しなければならない場合があります。

S3 NASバケットは、S3バケット構文を使用してディレクトリをマッピングすることでNASディレクトリへのS3アクセスを提供し、ディレクトリツリー内のファイルはオブジェクトとみなされます。オブジェクト名は、S3バケットの設定で指定されたディレクトリに相対的な、ファイルのスラッシュで区切られたパス名です。

このマッピングは、S3 NASバケットを使用してファイルとディレクトリにサービスを提供する際にいくつかの要件を適用します。

* S3の名前は1024バイトに制限されているため、長いパス名を持つファイルにS3を使用してアクセスすることはできません。
* ファイル名とディレクトリ名は255文字に制限されているため、オブジェクト名には、連続する255文字以外の文字（「/」）を使用できません
* バックスラッシュ（「\」）で区切られたSMBパス名は、s3にはスラッシュ（「/」）ではなく、オブジェクト名として表示されます。
* 有効なS3オブジェクト名のペアの一部は、マッピングされたNASディレクトリツリーに共存できません。たとえば、有効なS3オブジェクト名「part1/part2」と「part1/part2/part3」は、NASディレクトリツリーに同時に存在できないファイルにマッピングされます。「part1/part2」は、最初の名前に含まれるファイルで、もう一方の名前に含まれるディレクトリです。
+
** 「part1/part2」が既存のファイルの場合、「part1/part2/part3」のS3作成は失敗します。
** "part1/part2/part3"が既存のファイルの場合、"part1/part2"のS3作成または削除が失敗します。
** 既存のオブジェクトの名前と一致するS3オブジェクトの作成によって、（バージョン管理されていないバケット内の）既存のオブジェクトが置き換えられます。これはNASを保持するが、完全に一致する必要があります。上記の例では、名前が競合している間は原因 によって既存のオブジェクトが削除されないため、これらのオブジェクトは削除されません。




オブジェクトストアは非常に多くの任意の名前をサポートするように設計されていますが、NASディレクトリ構造では、非常に多数の名前が1つのディレクトリに配置されているとパフォーマンスの問題が発生する可能性があります。特に、名前にスラッシュ（/）文字が含まれていない場合、名前はすべてNASマッピングのルートディレクトリに配置されます。NASに対応していない名前を多用するアプリケーションは、NASマッピングではなく実際のオブジェクトストアバケットでホストされる方が適切です。
