---
permalink: ndmp/configure-lifs-node-scoped-task.html 
sidebar: sidebar 
keywords: configure, lif 
summary: ノードとバックアップアプリケーションの間のデータ接続と制御接続の確立に使用される LIF を特定する必要があります。LIF を特定したら、その LIF に対してファイアウォールポリシーとフェイルオーバーポリシーが設定されていることを確認する必要があります。 
---
= LIF を設定
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
ノードとバックアップアプリケーションの間のデータ接続と制御接続の確立に使用される LIF を特定する必要があります。LIF を特定したら、その LIF に対してファイアウォールポリシーとフェイルオーバーポリシーが設定されていることを確認する必要があります。


NOTE: ONTAP 9.10.1以降では、ファイアウォールポリシーは廃止され、完全にLIFのサービスポリシーに置き換えられました。詳細については、を参照してください link:../networking/configure_firewall_policies_for_lifs.html["LIF のファイアウォールポリシーを設定します"]。

.手順
. を使用して、ノードでホストされているクラスタ間LIFを特定します `network interface show` コマンドにを指定します `-role` パラメータ
+
[listing]
----
cluster1::> network interface show -role intercluster

            Logical    Status     Network            Current       Current Is
Vserver     Interface  Admin/Oper Address/Mask       Node          Port    Home
----------- ---------- ---------- ------------------ ------------- ------- ----
cluster1    IC1        up/up      192.0.2.65/24      cluster1-1    e0a     true
cluster1    IC2        up/up      192.0.2.68/24      cluster1-2    e0b     true
----
. クラスタ間 LIF で NDMP に対してファイアウォールポリシーが有効になっていることを確認します。
+
.. を使用して、NDMPに対してファイアウォールポリシーが有効になっていることを確認します `system services firewall policy show` コマンドを実行します
+
次のコマンドは、クラスタ間 LIF のファイアウォールポリシーを表示します。

+
[listing]
----
cluster1::> system services firewall policy show -policy intercluster

Vserver     Policy       Service    Allowed
-------     ------------ ---------- -------------------
cluster1    intercluster dns        -
                         http       -
                         https      -
                         **ndmp       0.0.0.0/0, ::/0**
                         ndmps      -
                         ntp        -
                         rsh        -
                         ssh        -
                         telnet     -
9 entries were displayed.
----
.. ファイアウォールポリシーが有効になっていない場合は、を使用してファイアウォールポリシーを有効にします `system services firewall policy modify` コマンドにを指定します `-service` パラメータ
+
次のコマンドは、クラスタ間 LIF のファイアウォールポリシーを有効にします。

+
[listing]
----
cluster1::> system services firewall policy modify -vserver cluster1 -policy intercluster -service ndmp 0.0.0.0/0
----


. クラスタ間 LIF のフェイルオーバーポリシーが適切に設定されていることを確認します。
+
.. クラスタ間LIFのフェイルオーバーポリシーがに設定されていることを確認します `local-only` を使用します `network interface show -failover` コマンドを実行します
+
[listing]
----
cluster1::> network interface show -failover
            Logical          Home              Failover     Failover
Vserver     Interface        Node:Port         Policy       Group
--------    ---------------  ----------------- ------------ --------
cluster1    **IC1               cluster1-1:e0a    local-only   Default**
                                                    Failover Targets:
                                                    .......
            **IC2               cluster1-2:e0b    local-only   Default**
                                                    Failover Targets:
                                                    .......
cluster1-1  cluster1-1_mgmt1 cluster1-1:e0m    local-only    Default
                                                    Failover Targets:
                                                    .......
----
.. フェイルオーバーポリシーが適切に設定されていない場合は、を使用してフェイルオーバーポリシーを変更します `network interface modify` コマンドにを指定します `-failover-policy` パラメータ
+
[listing]
----
cluster1::> network interface modify -vserver cluster1 -lif IC1 -failover-policy local-only
----



