---
permalink: ndmp/configure-backup-user-cluster-task.html 
sidebar: sidebar 
keywords: configure, backup, user, cluster 
summary: バックアップ アプリケーションからSVMを対象としたNDMPを認証するには、十分な権限とNDMPパスワードを持つ管理ユーザが必要です。 
---
= ONTAP NDMP認証のバックアップ ユーザーを有効にする
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
バックアップ アプリケーションからSVMを対象としたNDMPを認証するには、十分な権限とNDMPパスワードを持つ管理ユーザが必要です。

.タスク概要
バックアップの管理ユーザ用にNDMPパスワードを生成する必要があります。バックアップの管理ユーザはクラスタ レベルまたはSVMレベルで有効にすることができます。必要に応じて、新しいユーザを作成することもできます。デフォルトでは、次のロールを持つユーザがNDMPバックアップを認証できます。

* クラスター全体： `admin`または `backup`
* 個別 SVM: `vsadmin` または `vsadmin-backup`


NISユーザまたはLDAPユーザを使用している場合は、それぞれのサーバにユーザが存在している必要があります。Active Directoryユーザは使用できません。

.手順
. 現在の管理ユーザと権限を表示します。
+
`security login show`

+
 `security login show`の詳細については、link:https://docs.netapp.com/us-en/ontap-cli/security-login-show.html["ONTAPコマンド リファレンス"^]を参照してください。

. 必要に応じて、 `security login create`コマンドとクラスタ全体または個々の SVM 権限の適切なロールを使用して、新しい NDMP バックアップ ユーザーを作成します。
+
 `-user-or-group-name`パラメータには、ローカル バックアップ ユーザー名、NIS または LDAP ユーザー名を指定できます。

+
次のコマンドは、クラスター全体の `backup`ロールを持つバックアップ ユーザー `backup_admin1`を作成します：

+
`cluster1::> security login create -user-or-group-name backup_admin1 -application ssh -authmethod password -role backup`

+
次のコマンドは、個々の SVM の `vsadmin-backup`ロールを持つバックアップ ユーザー `vsbackup_admin1`を作成します：

+
`cluster1::> security login create -user-or-group-name vsbackup_admin1 -application ssh -authmethod password -role vsadmin-backup`

+
新しいユーザのパスワードを入力し、確認のためにもう一度入力します。

+
 `security login create`の詳細については、link:https://docs.netapp.com/us-en/ontap-cli/security-login-create.html["ONTAPコマンド リファレンス"^]をご覧ください。

.  `vserver services ndmp generate password`コマンドを使用して、管理SVMのパスワードを生成します。
+
生成されたパスワードは、バックアップ アプリケーションによるNDMP接続の認証で必要になります。

+
[listing]
----
cluster1::> vserver services ndmp generate-password -vserver cluster1 -user backup_admin1

 Vserver: cluster1
    User: backup_admin1
Password: qG5CqQHYxw7tE57g
----

