---
permalink: ndmp/configure-backup-user-cluster-task.html 
sidebar: sidebar 
keywords: configure, backup, user, cluster 
summary: バックアップアプリケーションからSVMを対象としたNDMPを認証するには、十分な権限を持つ管理ユーザとNDMPパスワードが必要です。 
---
= NDMP認証のバックアップユーザを有効にします
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
バックアップアプリケーションからSVMを対象としたNDMPを認証するには、十分な権限を持つ管理ユーザとNDMPパスワードが必要です。

バックアップ管理ユーザ用のNDMPパスワードを生成する必要があります。バックアップ管理者ユーザは、クラスタレベルまたはSVMレベルで有効にすることができます。必要に応じて、新しいユーザを作成することもできます。デフォルトでは、次のロールを持つユーザがNDMPバックアップに対して認証できます。

* クラスタ全体： `admin` または `backup`
* 個 々 のSVM： `vsadmin` または `vsadmin-backup`


NISユーザまたはLDAPユーザを使用する場合は、それぞれのサーバ上にそのユーザが存在している必要があります。Active Directory ユーザは使用できません。

.手順
. 現在の管理者ユーザと権限を表示します。
+
「 securitylogin show 」を参照してください

. 必要に応じて、を使用して新しいNDMPバックアップユーザを作成します `security login create` コマンドおよびクラスタ全体または個 々 のSVMの権限に該当するロール。
+
-user-or-group-name パラメータには ' ローカル・バックアップ・ユーザ名 ' または NIS または LDAP ユーザ名を指定できます

+
次に、バックアップユーザを作成するコマンドを示します `backup_admin1` を使用 `backup` クラスタ全体での役割：

+
`cluster1::> security login create -user-or-group-name backup_admin1 -application ssh -authmethod password -role backup`

+
次に、バックアップユーザを作成するコマンドを示します `vsbackup_admin1` を使用 `vsadmin-backup` 個 々 のSVMのロール：

+
`cluster1::> security login create -user-or-group-name vsbackup_admin1 -application ssh -authmethod password -role vsadmin-backup`

+
新しいユーザのパスワードを入力し、確認のためにもう一度入力します。

. 「 vserver services ndmp generate password 」コマンドを使用して、管理 SVM のパスワードを生成します。
+
生成されたパスワードは、バックアップアプリケーションによる NDMP 接続の認証で必要になります。

+
[listing]
----
cluster1::> vserver services ndmp generate-password -vserver cluster1 -user backup_admin1

 Vserver: cluster1
    User: backup_admin1
Password: qG5CqQHYxw7tE57g
----

