---
permalink: ndmp/index.html 
sidebar: sidebar 
keywords: decide, ndmp, configuration, network, data, management, protocol, backup, back up 
summary: サードパーティ製バックアップアプリケーションを使用してデータをテープに直接バックアップするには、 Network Data Management Protocol （ NDMP ；ネットワークデータ管理プロトコル）を使用するように ONTAP 9 クラスタを簡単に設定します。 
---
= NDMP構成の概要
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
サードパーティ製バックアップアプリケーションを使用してデータをテープに直接バックアップするには、 Network Data Management Protocol （ NDMP ；ネットワークデータ管理プロトコル）を使用するように ONTAP 9 クラスタを簡単に設定します。

バックアップアプリケーションがCluster Aware Backup（CAB）をサポートしている場合は、SVMを対象としたNDMPまたはノードを対象としたNDMPを設定できます。

* SVMを対象としたNDMPをクラスタ（管理SVM）レベルでは、クラスタの複数のノードでホストされているすべてのボリュームをバックアップできます。可能であれば、SVMを対象としたNDMPを推奨します。
* ノードを対象としたNDMPを使用すると、そのノードでホストされているすべてのボリュームをバックアップできます。


バックアップアプリケーションがCABをサポートしていない場合は、ノードを対象としたNDMPを使用する必要があります。

SVMを対象としたNDMPとノードを対象としたNDMPは相互に排他的であり、同じクラスタでは設定できません。


NOTE: ノードを対象としたNDMPは、ONTAP 9で廃止されました。

詳細については、をご覧ください link:../tape-backup/cluster-aware-backup-extension-concept.html["クラスタ対応バックアップ（ CAB ）"]。

NDMPを設定する前に、次の点を確認します。

* サードパーティ製バックアップアプリケーション（データ管理アプリケーションまたは DMA とも呼ばれる）がある。
* クラスタ管理者である。
* テープデバイスとオプションのメディアサーバがインストールされている。
* テープデバイスがクラスタに直接接続ではなく Fibre Channel （ FC ；ファイバチャネル）スイッチを介して接続されている。
* 少なくとも 1 つのテープデバイスの Logical Unit Number （ LUN ；論理ユニット番号）が 0 である。

