---
permalink: consistency-groups/clone-task.html 
sidebar: sidebar 
keywords: consistency groups, consistency group, clone 
summary: ONTAP 9.12.1 以降では、コンシステンシ グループを複製して、コンシステンシ グループの構成とボリュームのコピーを作成できます。 
---
= ONTAPコンシステンシグループのクローンを作成する
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
ONTAP 9.12.1以降では、整合性グループをクローニングして、整合性グループとその内容のコピーを作成できます。整合性グループをクローニングすると、整合性グループの設定、メタデータ（アプリケーション タイプなど）、およびすべてのボリュームとその内容（ファイル、ディレクトリ、LUN、NVMeネームスペースなど）のコピーが作成されます。

.タスク概要
整合性グループのクローンを作成する場合、現在の構成でクローンを作成できますが、ボリュームの内容はそのままにするか、既存の整合性グループのSnapshotに基づいてクローンを作成できます。

クローニングする場合、整合性グループ全体をクローニングする必要があります。階層関係内の子整合性グループを個別にクローニングすることはできません。クローニングできるのは、完全な整合性グループ設定のみです。

整合性グループのクローニング時に、次のコンポーネントはクローニングされません。

* igroup
* LUNマップ
* NVMeサブシステム
* NVMeネームスペースのサブシステム マップ


.開始する前に
* コンシステンシ グループをクローンする場合、共有名が指定されていないと、ONTAP はクローン ボリュームに対して SMB 共有を作成しません。* ジャンクション パスが指定されていない場合、クローン コンシステンシ グループはマウントされません。
* 整合性グループの現在の構成ボリュームを反映していないスナップショットに基づいて整合性グループのクローンを作成しようとすると、操作は失敗します。
* 整合性グループのクローニング後、適切なマッピング処理を実行する必要があります。
+
詳細については、xref:../task_san_map_igroups_to_multiple_luns.html[複数のLUNへのigroupのマッピング]またはxref:../san-admin/map-nvme-namespace-subsystem-task.html[サブシステムへのNVMeネームスペースのマッピング]を参照してください。

* 整合性グループのクローニングは、SnapMirrorアクティブ同期関係の整合性グループや、DPボリュームが関連付けられている整合性グループではサポートされません。


[role="tabbed-block"]
====
.System Manager
--
.手順
. *Storage > Consistency groups*を選択します。
. *Consistency Group*メニューから、クローンを作成するコンシステンシ グループを選択します。
. 整合性グループの概要ページの右上で、*Clone* を選択します。
. クローニング後の新しい整合性グループの名前を入力するか、デフォルトの名前をそのまま使用します。
+
.. link:../concepts/thin-provisioning-concept.html["*シンプロビジョニング*"^]を有効にするかどうかを選択します。
.. コンシステンシ グループをそのソースから切り離し、クローンされたコンシステンシ グループに追加のディスク領域を割り当てる場合は、*Split Clone* を選択します。


. 整合性グループを現在の状態で複製するには、*新しいスナップショットの追加* を選択します。
+
スナップショットに基づいて整合性グループのクローンを作成するには、*既存のスナップショットを使用する*を選択します。このオプションを選択すると、新しいサブメニューが開きます。クローン処理のベースとして使用するスナップショットを選択します。

. *Clone*を選択します。
. *Consistency Group* メニューに戻り、整合性グループが複製されたことを確認します。


--
.CLI
--
ONTAP 9.14.1以降では、CLIとクラスタ管理者のクレデンシャルを使用して整合性グループをクローニングできます。

.開始する前に
* このタスクを実行するには、admin権限レベルが必要です。
* ONTAP 9.15.1以降では、admin権限レベルのすべてのユーザがこのタスクを実行できます。ONTAP 9.14.1では、このタスクを実行するには、クラスタ管理者またはSVMの管理者である必要があります。


.整合性グループのクローニング
.  `consistency-group clone create`コマンドは、現在のポイントインタイムステータスで整合性グループのクローンを作成します。スナップショットに基づいてクローン操作を実行するには、 `-source-snapshot`パラメータを指定します。
+
`consistency-group clone create -vserver _svm_name_ -consistency-group _clone_name_ -source-consistency-group _consistency_group_name_ [-source-snapshot _snapshot_name_]`

+
 `consistency-group clone create`の詳細については、link:https://docs.netapp.com/us-en/ontap-cli/search.html?q=consistency-group+clone+create["ONTAPコマンド リファレンス"^]を参照してください。



--
====
.次の手順
* xref:../task_san_map_igroups_to_multiple_luns.html[複数のLUNへのigroupのマッピング]
* xref:../san-admin/map-nvme-namespace-subsystem-task.html[サブシステムへのNVMeネームスペースのマッピング]

