---
sidebar: sidebar 
permalink: concept_dp_overview.html 
keywords: netapp, ontap, protection, overview, data, protect, loss, backup, back up, types, mirror, vault, snapmirror, snapvault, SVM, storage VM, LIF, network interface, intercluster, single file snap restore, metrocluster, sfsr, disaster recovery, SnapMirror, protection policy, vault relationship, mirror relationship, relationship, snapshot, Snapshot copy, policy, schedule, replica, standards compliance, vault, default protection policy, asynchronous policy, synchronous policy, custom policy 
summary: Snapshot コピー、ミラー、バックアップ、ミラーとバックアップ関係を作成および管理して、データを保護します。 
---
= System Manager によるデータ保護の概要
:toc: macro
:hardbreaks:
:toclevels: 1
:toc: 
:toclevels: 1
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/
:toc-position: content


[role="lead"]
このセクションのトピックでは、 ONTAP 9.7 以降のリリースの System Manager を使用してデータ保護を設定および管理する方法について説明します。

従来の System Manager （ ONTAP 9.7 以前でのみ使用可能）を使用している場合は、次のトピックを参照してください。

* https://docs.netapp.com/us-en/ontap-sm-classic/online-help-96-97/concept_managing_data_protection.html["データ保護の管理"^]


Snapshot コピー、ミラー、バックアップ、ミラーとバックアップ関係を作成および管理して、データを保護します。

SnapMirror は、地理的に離れたサイトのプライマリストレージからセカンダリストレージへのフェイルオーバー用に設計されたディザスタリカバリテクノロジです。名前のとおり、 SnapMirror はセカンダリストレージに作業データのレプリカ（ミラー）を作成します。プライマリサイトで災害が発生した場合でも、セカンダリストレージからデータを引き続き提供できます。

a_vault_ は、基準への準拠およびその他のガバナンス関連の目的で、ディスクツーディスクの Snapshot コピーレプリケーションを実現するように設計されています。SnapMirror 関係では、通常、ソースボリューム内の Snapshot コピーだけがデスティネーションに含まれますが、 SnapVault デスティネーションはより長期間にわたって作成されたポイントインタイムの Snapshot コピーを保持します。

ONTAP 9.10.1 以降では、 S3 SnapMirror を使用して S3 バケット間にデータ保護関係を作成できます。デスティネーションバケットは、ローカルまたはリモートの ONTAP システム、あるいは StorageGRID や AWS などの ONTAP 以外のシステムで使用できます。詳細については、を参照してください link:s3-snapmirror/index.html["S3 SnapMirror の概要"]。
