---
sidebar: sidebar 
permalink: concept_security_overview.html 
keywords: netapp, ontap, security, overview, secure data, data, cluster, access, storage, virus scanning, encryption, WORM storage, client authentication, client authorization, administrator authentication, RBAC, role-based access control, login, log in, antivirus, anti-virus, Vscan, SnapLock, regulation 
summary: System Manager では、 ONTAP 標準のセキュリティ方式が使用されます 
---
= セキュリティの最大化
:toc: macro
:hardbreaks:
:toclevels: 1
:toc: 
:toclevels: 1
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/
:toc-position: content


[role="lead"]
このセクションのトピックでは、 ONTAP 9.7 以降のリリースで ONTAP System Manager を使用してクラスタセキュリティを管理する方法を説明します。

ONTAP CLI を使用してクラスタのセキュリティを管理する場合は、次の内容を参照してください。

* link:http://docs.netapp.com/ontap-9/topic/com.netapp.doc.pow-adm-auth-rbac/home.html["管理者認証と RBAC パワーガイド"]
* link:http://docs.netapp.com/ontap-9/topic/com.netapp.doc.dot-cm-acg/home.html["『 Antivirus Configuration Guide 』を参照して"]
* link:http://docs.netapp.com/ontap-9/topic/com.netapp.doc.pow-nve/home.html["NetApp Encryption パワーガイド』を参照してください"]


ONTAP 9.7 以前のリリースで OnCommand System Manager を使用してクラスタのセキュリティを管理している場合は、 ONTAP リリースの内容を参照してください。

* link:http://docs.netapp.com/ontap-9/topic/com.netapp.doc.onc-sm-help-960/home.html["System Manager 9.6 および 9.7 を使用したクラスタ管理"]
* link:http://docs.netapp.com/ontap-9/topic/com.netapp.doc.onc-sm-help-950/home.html["System Manager 9.5 を使用したクラスタの管理"]
* link:http://docs.netapp.com/ontap-9/topic/com.netapp.doc.onc-sm-help-930/home.html["System Manager 9.3 および 9.4 を使用したクラスタの管理"]
* link:http://docs.netapp.com/ontap-9/topic/com.netapp.doc.onc-sm-help-900/home.html["System Manager 9.2 以前を使用したクラスタの管理"]




== System Manager のセキュリティの概要を参照してください

System Manager では、 ONTAP 標準の方法を使用して、クライアントや管理者によるストレージへのアクセスを保護し、ウィルスから保護します。保存データの暗号化や WORM ストレージでは、高度なテクノロジも使用できます。



=== クライアントの認証と許可

ONTAP では、信頼できるソースで ID を検証してクライアントマシンおよびユーザを認証します。ONTAP は、ユーザのクレデンシャルとファイルまたはディレクトリに対して設定されている権限を比較して、ユーザにファイルまたはディレクトリへのアクセスを許可します。



=== 管理者認証と RBAC

管理者は、ローカルまたはリモートのログインアカウントを使用してクラスタおよび Storage VM に対して自身を認証します。管理者がアクセスできるコマンドは、ロールベースアクセス制御（ RBAC ）に基づいて決まります。



=== ウィルススキャン

ストレージシステムに統合されたウィルス対策機能を使用して、ウィルスやその他の悪意のあるプログラムからデータを保護することができます。ONTAP ウィルススキャン（ _vscan ）は、クラス最高のサードパーティ製ウィルス対策ソフトウェアと ONTAP 機能を組み合わせたもので、どのファイルをスキャンするか、いつスキャンするかを柔軟に制御できます。



=== 暗号化

ONTAP は、ストレージメディアの転用、返却、置き忘れ、盗難に際して保存データが読み取られることがないようにソフトウェアベースとハードウェアベースの暗号化テクノロジを提供します。



=== WORM ストレージ

_ 解決策 _ は、規制やガバナンスに準拠するために変更不可能な状態で重要なファイルを保管するために _write one_,_read many （ WORM ） _storage を使用する組織向けの、ハイパフォーマンスなコンプライアンス SnapLock です。
