---
sidebar: sidebar 
permalink: concept_administration_overview.html 
keywords: netapp, ontap, administration, overview, cluster, node, local tier, aggregate, svm, storage vm, service level, volume, qtree, LUN, automatic aggregate selection, vserver, protocol, quota, disk, HA pair, dashboard, subnet, domain, interface, mirroring, vaulting, storage 
summary: System Manager を使用して、ストレージシステムおよびストレージオブジェクトを管理したり、ストレージシステムに関連する一般的な管理タスクを Web ブラウザから実行したりできます。 
---
= System Manager の管理の概要
:toc: macro
:hardbreaks:
:toclevels: 1
:allow-uri-read: 
:toc: 
:toclevels: 1
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/
:toc-position: content


[role="lead"]
System Manager は、グラフィカルな管理インターフェイスで、 Web ブラウザを使用して、ストレージシステムおよびストレージオブジェクト（ディスク、ボリューム、ストレージ階層など）を管理したり、ストレージシステムに関連する一般的な管理タスクを実行したりできます。

このセクションで説明する手順は、 ONTAP 9.7 以降のリリースの System Manager を使用してクラスタを管理する場合に役立ちます。

[NOTE]
====
* ONTAP 9.8 以降、 System Manager は実行ファイルとしては提供されなくなりました。 Web サービスとして ONTAP ソフトウェアに搭載されており、デフォルトで有効になっていて、ブラウザからアクセスできます。
* ONTAP 9.6 以降では、 System Manager の名前が変更されています。ONTAP 9.5 以前では、 OnCommand システムマネージャと呼ばれていました。ONTAP 9.6 以降では、 System Manager と呼ばれます。
* 従来の System Manager （ ONTAP 9.7 以前でのみ使用可能）を使用している場合は、を参照してください  https://["System Manager Classic （ ONTAP 9.0 から 9.7 ）"^]


====
System Manager のダッシュボードを使用すると、重要なアラートと通知、ストレージ階層とボリュームの効率性と容量、クラスタで使用可能なノード、 HA ペアのノードのステータス、最もアクティブなアプリケーションとオブジェクト、 およびクラスタまたはノードのパフォーマンス指標。

System Manager では、次のような多くの一般的な作業を実行できます。

* クラスタを作成し、ネットワークを設定し、クラスタのサポートの詳細を設定する。
* ディスク、ローカル階層、ボリューム、 qtree などのストレージオブジェクトを構成し、管理する クォータが含まれます。
* SMB および NFS などのプロトコルを設定し、ファイル共有をプロビジョニングする
* FC 、 FCoE 、 NVMe 、 iSCSI などのプロトコルをブロックアクセス用に設定する。
* サブネット、ブロードキャストドメイン、データ / 管理インターフェイス、インターフェイスグループなどのネットワークコンポーネントを作成および設定する。
* ミラー関係とバックアップ関係をセットアップおよび管理する。
* クラスタ管理、ストレージノード管理、および Storage Virtual Machine （ Storage VM ）管理の処理を実行する。
* Storage VM の作成と設定、 Storage VM に関連付けられたストレージオブジェクトの管理、および Storage VM サービスの管理を行う。
* クラスタでハイアベイラビリティ（ HA ）構成を監視および管理する。
* ノードに対してその状態に関係なくリモートでログイン、管理、監視、および管理を行うようにサービスプロセッサを設定します。




== System Manager の用語

System Manager では、 ONTAP の一部の主要機能について、 CLI とは異なる用語が使用されます。

* * ローカルティア * –データを保存する物理ソリッドステート・ドライブまたはハードディスク・ドライブのセット。これらはアグリゲートとして認識されていることがあります。実際、 ONTAP CLI を使用している場合は、ローカル階層を表す用語として「 _aggregate_used 」が表示されます。
* * クラウド階層 * – ONTAP で使用されるクラウド内のストレージで、何らかの理由でデータをオンプレミスに保存する必要がある場合。FabricPool のクラウド部分について考えている場合は、すでにその点を把握しています。また、 StorageGRID システムを使用している場合は、クラウドがオフプレミスになっているとは限りません。（オンプレミスでのクラウドレベルのエクスペリエンスは、 _private_cloud_ と呼ばれています）。
* * Storage VM * – ONTAP 内で実行される仮想マシンで、クライアントにストレージサービスとデータサービスを提供します。これは、 _ SVM _ または _ SVM _ であることがわかります。
* * ネットワーク・インターフェイス * - 物理ネットワーク・ポートに割り当てられたアドレスとプロパティ。これは、 _ 論理インターフェイス（ LIF ） _ であることがわかります。
* * Pause * - 処理を停止するアクション。ONTAP 9.8 より前のバージョンの System Manager では、 _quiesce と呼ぶこともあります。

