---
sidebar: sidebar 
permalink: concept_administration_overview.html 
keywords: netapp, system manager, ontap, administration, overview, cluster, node, local tier, aggregate, svm, storage vm, service level, volume, qtree, LUN, automatic aggregate selection, vserver, protocol, quota, disk, HA pair, dashboard, subnet, domain, interface, mirroring, vaulting, storage, html5 
summary: System Manager を使用すると、Web ブラウザからストレージ システムとストレージ オブジェクトを管理し、ストレージ システムに関連する一般的な管理タスクを実行できます。 
---
= ONTAP System Managerを使用したクラスタ管理について学習します
:hardbreaks:
:toclevels: 1
:allow-uri-read: 
:toclevels: 1
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
System Managerは、HTML5ベースのグラフィカルな管理インターフェイスで、ストレージ システムおよびストレージ オブジェクト（ディスク、ボリューム、ストレージ階層など）の管理やストレージ システムに関連する一般的な管理作業をWebブラウザを使用して実行できます。

[NOTE]
====
* System ManagerはWebサービスとしてONTAPソフトウェアに搭載されており、デフォルトで有効になっていて、ブラウザからアクセスできます。
* System Managerは、ONTAP 9.6から名称が変更されています。ONTAP 9.5以前はOnCommand System Managerでしたが、ONTAP 9.6からはSystem Managerと呼ばれます。
* クラシック System Manager （ ONTAP 9.7 以前でのみ使用可能）を使用している場合は、 https://docs.netapp.com/us-en/ontap-system-manager-classic/index.html["System Manager Classic（ONTAP 9.0～9.7）"^]を参照してください。


====
System Managerのダッシュボードでは、重要なアラートと通知、ストレージ階層およびボリュームの効率性と容量、クラスタで使用可能なノード、HAペアを構成するノードのステータス、最もアクティブなアプリケーションやオブジェクト、クラスタやノードのパフォーマンス指標に関する情報を一目で確認できます。

ONTAP 9.7 以降のリリースの System Manager を使用すると、次のような多くの一般的なタスクを実行できます：

* クラスタの作成、ネットワークの設定、およびクラスタ用のサポート情報の設定を行う。
* ディスク、ローカル階層、ボリューム、qtree、クォータなどのストレージ オブジェクトを構成し、管理する。
* SMBやNFSなどのプロトコルを設定し、ファイル共有をプロビジョニングする。
* FC、FCoE、NVMe、iSCSIなどのプロトコルをブロック アクセス用に設定する。
* サブネット、ブロードキャスト ドメイン、データ / 管理インターフェイス、インターフェイス グループなどのネットワーク コンポーネントを作成および設定する。
* ミラー関係とバックアップ関係をセットアップおよび管理する。
* クラスタ管理、ストレージ ノード管理、およびStorage Virtual Machine（Storage VM）管理の処理を実行する。
* Storage VMの作成と設定、Storage VMに関連付けられたストレージ オブジェクトの管理、およびStorage VMサービスの管理を行う。
* クラスタでハイアベイラビリティ（HA）構成を監視および管理する。
* サービス プロセッサを設定して、ノードに対してその状態に関係なくリモートからログイン、管理、および監視を実行する。




== System Managerの用語

System Managerでは、ONTAPの一部の主要機能について、CLIとは異なる用語が使用されます。

* *ローカル層*：データを保存する物理的なソリッドステートドライブまたはハードディスクドライブのセット。これらはアグリゲートと呼ばれることもあります。実際、ONTAP CLIを使用する場合、ローカル層を表すために_アグリゲート_という用語が今でも使用されています。
* *クラウド層*：ONTAP がいくつかの理由からデータの一部をオフプレミスで保管したい場合に利用するクラウド内のストレージです。FabricPool のクラウド部分を思い浮かべているなら、既にお分かりでしょう。また、StorageGRID システムを使用している場合は、クラウドは必ずしもオフプレミスではない可能性があります。（オンプレミスでクラウドのような環境を実現することは、_プライベート クラウド_と呼ばれます。）
* *ストレージVM*：ONTAP内で実行され、クライアントにストレージおよびデータサービスを提供する仮想マシン。_SVM_または_vserver_と呼ばれることもあります。
* *ネットワーク インターフェイス*：物理ネットワーク ポートに割り当てられたアドレスとプロパティ。_論理インターフェイス（LIF）_とも呼ばれます。
* *一時停止*：処理を停止するアクション。ONTAP 9.8より前のバージョンのSystem Managerでは、「休止」と呼んでいた可能性があります。

