---
sidebar: sidebar 
permalink: concept_administration_overview.html 
keywords: netapp, system manager, ontap, administration, overview, cluster, node, local tier, aggregate, svm, storage vm, service level, volume, qtree, LUN, automatic aggregate selection, vserver, protocol, quota, disk, HA pair, dashboard, subnet, domain, interface, mirroring, vaulting, storage, html5 
summary: System Managerでは、ストレージシステムとストレージオブジェクトを管理したり、ストレージシステムに関連する一般的な管理タスクをWebブラウザから実行したりできます。 
---
= ONTAP System Managerを使用したクラスタ管理について学習します
:hardbreaks:
:toclevels: 1
:allow-uri-read: 
:toclevels: 1
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
System Managerは、HTML5ベースのグラフィカルな管理インターフェイスで、ストレージシステムとストレージオブジェクト（ディスク、ボリューム、ストレージ階層など）の管理やストレージシステムに関連する一般的な管理タスクの実行にWebブラウザを使用できます。

[NOTE]
====
* System ManagerはWebサービスとしてONTAPソフトウェアに搭載されており、デフォルトで有効になっていて、ブラウザからアクセスできます。
* ONTAP 9では、System Managerの名前が変更されています。6.ONTAP 9 .5以前ではOnCommand System Managerと呼ばれていた。ONTAP 9 .6以降では、System Managerと呼ばれています。
* 従来のSystem Manager（ONTAP 9.7以前でのみ使用可能）を使用している場合は、  https://docs.netapp.com/us-en/ontap-system-manager-classic/index.html["System Managerクラシック（ONTAP 9 .0 ~ 9.7）"^]


====
System Managerのダッシュボードでは、重要なアラートと通知、ストレージ階層とボリュームの効率性と容量、クラスタで使用可能なノード、HAペアを構成するノードのステータス、最もアクティブなアプリケーションとオブジェクト、クラスタやノードのパフォーマンス指標に関する情報を一目で確認できます。

ONTAP 9.7以降のSystem Managerでは、次のような多くの一般的なタスクを実行できます。

* クラスタを作成し、ネットワークを設定し、クラスタのサポート情報を設定します。
* ディスク、ローカル階層、ボリューム、qtree、クォータなどのストレージオブジェクトを設定および管理します。
* SMBやNFSなどのプロトコルを設定し、ファイル共有をプロビジョニングする。
* FC、FCoE、NVMe、iSCSIなどのプロトコルをブロックアクセス用に設定する。
* サブネット、ブロードキャストドメイン、データインターフェイスと管理インターフェイス、インターフェイスグループなどのネットワークコンポーネントを作成および設定します。
* ミラー関係とバックアップ関係をセットアップおよび管理する。
* クラスタ管理、ストレージノード管理、およびStorage Virtual Machine（Storage VM）管理の処理を実行する。
* Storage VMの作成と設定、Storage VMに関連付けられたストレージオブジェクトの管理、およびStorage VMサービスの管理を行う。
* クラスタのハイアベイラビリティ（HA）構成を監視および管理します。
* サービスプロセッサを設定して、ノードの状態に関係なく、ノードへのログイン、管理、監視、および管理を行う。




== System Managerの用語

ONTAPキーの一部の機能については、System Managerで使用される用語がCLIとは異なります。

* *ローカル階層*：データを格納する一連の物理ソリッドステートドライブまたはハードディスクドライブ。アグリゲートと呼ばれることもあります。ONTAP CLIでは、ローカル階層を表すために_aggregate_usedという用語が引き続き使用されます。
* *クラウド階層*：いくつかの理由で一部のデータをオフプレミスに配置する場合に、ONTAPで使用されるクラウド内のストレージ。FabricPoolのクラウド部分について考えている場合は、すでに理解しています。また、StorageGRIDシステムを使用している場合は、クラウドがオフプレミスであるとは限りません。（オンプレミスでのクラウドレベルのエクスペリエンスは、 _private_cloud_ と呼ばれています）。
* * Storage VM *：クライアントにストレージとデータサービスを提供する、ONTAP内で実行される仮想マシン。これは「_SVM_」や「_Vserver_」と呼ばれます。
* *ネットワーク インターフェイス*: 物理ネットワーク ポートに割り当てられたアドレスとプロパティ。以前は「_論理インターフェイス（LIF）_」と呼んでいました。
* *一時停止*：処理を停止するアクション。ONTAP9.8より前のバージョンのSystem Managerでは、「休止」と呼んでいた可能ONTAPがあります。

