---
sidebar: sidebar 
permalink: concept_cloud_overview.html 
keywords: netapp, ontap, cloud, FabricPool, Fabric Pool, NDAS, cloud volumes, data availability services, install, installing, cluster, set up, setup, configure, disk, data port, guided setup, local tier, aggregate, Alibaba, Amazon, Google Cloud, IBM Cloud, Microsoft Azure Blob, All Flash, StorageGRID, all SSD, tiering, cloud tier 
summary: FabricPool を使用すると、アクセス頻度に応じてデータを自動的に階層化できます。 
---
= クラウドまで拡張できます
:toc: macro
:hardbreaks:
:toclevels: 1
:toc: 
:toclevels: 1
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/
:toc-position: content


[role="lead"]
このセクションのトピックでは、 ONTAP 9.7 以降のリリースで ONTAP System Manager を使用してクラウド階層を設定および管理する方法を説明します。

ONTAP CLI を使用してクラウド階層を設定および管理する場合は、次のコンテンツを参照してください。

* link:http://docs.netapp.com/ontap-9/topic/com.netapp.doc.dot-mgng-stor-tier-fp/home.html["FabricPool を使用したストレージ階層の管理"]
* link:http://docs.netapp.com/ontap-9/topic/com.netapp.doc.pow-s3-cg/home.html["S3 構成パワーガイド"]


OnCommand 9.5-9.7 リリース用の従来の ONTAP System Manager を使用してクラウド階層を設定および管理している場合は、 ONTAP リリースのコンテンツを参照してください。

* link:http://docs.netapp.com/ontap-9/topic/com.netapp.doc.onc-sm-help-960/home.html["System Manager 9.6 および 9.7 を使用したクラスタ管理"]
* link:http://docs.netapp.com/ontap-9/topic/com.netapp.doc.onc-sm-help-950/home.html["System Manager 9.5 を使用したクラスタの管理"]




== クラウドの概要

FabricPool を使用すると、アクセス頻度に応じてデータを自動的に階層化できます。

FabricPool は、オールフラッシュ（オール SSD ）アグリゲートを高パフォーマンス階層として、オブジェクトストアをクラウド階層として使用するハイブリッドストレージ解決策です。FabricPool を使用すると、パフォーマンス、効率、保護を犠牲にすることなくストレージコストを削減できます。

クラウド階層は、 NetApp StorageGRID または ONTAP S3 （ ONTAP 9.8 以降）に配置することも、次のいずれかのサービスプロバイダに配置することもできます。

* Alibaba クラウド
* Amazon S3
* Google Cloud
* IBM クラウド
* Microsoft Azure Blob Storage


video::Vs1-WMvj9fI[youtube, width=848,height=480]