---
sidebar: sidebar 
permalink: concept_rest_overview.html 
keywords: netapp, ontap, rest, rest api, rest api log, api log, rest overview 
summary: REST APIログには、System ManagerからONTAPに対して発行されたAPI呼び出しが記録されます。このログを使用して、ONTAPのさまざまな管理タスクを実行するために必要なAPI呼び出しの性質と順序を把握できます。 
---
= System ManagerによるREST APIの管理
:hardbreaks:
:toclevels: 1
:allow-uri-read: 
:toclevels: 1
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
REST APIログには、System ManagerからONTAPに対して発行されたAPI呼び出しが記録されます。このログを使用して、ONTAPのさまざまな管理タスクを実行するために必要な呼び出しの性質と順序を把握できます。



== System ManagerでのREST APIとAPIログの使用方法

System ManagerからONTAPに対してREST API呼び出しを実行する方法はいくつかあります。



=== System ManagerからAPI呼び出しが実行されるタイミング

ここでは、System ManagerがONTAP REST API呼び出しを実行するタイミングの最も重要な例を示します。



==== ページの自動更新

ダッシュボードページなどに表示されている情報を更新するために、API呼び出しがバックグラウンドで自動的に実行されます。



==== ユーザによる表示操作

System ManagerのUIから特定のストレージリソースまたは一連のリソースを表示すると、API呼び出しが実行されます。



==== ユーザによる更新操作

API呼び出しは、System Manager UIからONTAPリソースを追加、変更、または削除するときに実行されます。



=== API呼び出しの再実行

ログエントリをクリックして、API呼び出しを手動で再実行することもできます。これにより、呼び出しからのJSON出力の生データが表示されます。



== 詳細情報

* link:https://docs.netapp.com/us-en/ontap-automation/["ONTAP 9自動化のドキュメント"^]

