---
permalink: insights-configure-native-fpolicy-task.html 
sidebar: sidebar 
keywords: system manager, fpolicy, file extensions, native, best practice, best practise, configure, disallow 
summary: .11.1以降では、ネイティブの実装を推奨するInsightを受け取った場合は、Storage VMおよびボリュームにそのONTAP 9を設定できます。 
---
= ネイティブFPolicyの設定
:hardbreaks:
:toclevels: 1
:allow-uri-read: 
:toclevels: 1
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
.11.1以降では、ネイティブの実装を推奨するInsightを受け取った場合は、Storage VMおよびボリュームにそのONTAP 9を設定できます。

.開始する前に
System Manager Insightsにアクセスすると、*[ベストプラクティスの適用]*で、ネイティブのFPolicyが設定されていないことを示すメッセージが表示されることがあります。

FPolicy設定タイプの詳細については、を参照してくださいlink:./nas-audit/fpolicy-config-types-concept.html["FPolicy設定タイプ"]。

.手順
. System Manager で、左側のナビゲーション列の * Insights * をクリックします。
. [ベストプラクティスの適用]*で、*[ネイティブFPolicyは設定されていません]*を探します。
. アクションを実行する前に、次のメッセージをお読みください。
+
[IMPORTANT]
====
*拡張機能をブロックすると、予期しない結果になる可能性があります。*.11.1以降では、System Managerを使用して、Storage VMのネイティブONTAP 9を有効にすることができます。FPolicyネイティブモードでは、特定のファイル拡張子を許可または禁止できます。System Managerでは、過去にランサムウェア攻撃で使用されたファイル拡張子が3、000を超えることを推奨しています。これらの拡張子の一部は、環境内の正規のファイルによって使用されている可能性があり、ブロックすると、予期しない問題が発生する可能性があります。

したがって、環境のニーズに合わせて拡張子のリストを変更することを強くお勧めします。を参照してください https://kb.netapp.com/onprem/ontap/da/NAS/How_to_remove_a_file_extension_from_a_native_FPolicy_configuration_created_by_System_Manager_using_System_Manager_to_recreate_the_policy["System Managerを使用してポリシーを再作成するためにSystem Managerで作成されたネイティブFPolicyの設定からファイル拡張子を削除する方法"^]。

====
. [修正]*をクリックします。
. ネイティブFPolicyを適用するStorage VMを選択します。
. Storage VMごとに、ネイティブFPolicyを受け取るボリュームを選択します。
. [*Configure*] をクリックします。

