---
settings:
  name: ONTAP 9
  internal:
    pdf_enabled: true
  prod:
    pdf_enabled: true
    harmony_enabled: true
    langs: ja-jp,us-en,zh-cn
  search: ontap, ontap-metrocluster, ontap-sm-classic, ontap-fli, ontap-flexarray,
    ontap-automation
sidebar:
  entries:
  - title: ONTAP のドキュメント
    url: "/index.html"
  - title: リリースノート
    url: https://library.netapp.com/ecm/ecm_download_file/ECMLP2492508
  - section: introduction-concepts
  - section: setup-upgrade
  - section: cluster-admin
  - section: volume-admin
  - section: network-management
  - section: nas-management
  - section: san-management
  - section: object-storage-management
  - section: security-encryption
  - section: data-protection-disaster-recovery
  - section: event-performance-monitoring
  - title: 通知
    url: "/reference_legal_notices.html"
