---
settings:
  name: ONTAP 9
  internal:
    pdf_enabled: true
  prod:
    pdf_enabled: true
    harmony_enabled: false
    lipi_enabled: false
  search: ontap, ontap-metrocluster, ontap-fli, ontap-automation, ontap-cli
  langs: ja-jp,us-en,de-de,es-es,fr-fr,it-it,pt-br,ko-kr,zh-cn,zh-tw
sidebar:
  entries:
  - title: ONTAPのドキュメント
    url: "/index.html"
  - section: release-notes
  - section: introduction-concepts
  - section: setup-upgrade
  - section: cluster-admin
  - section: volume-admin
  - section: network-management
  - section: nas-management
  - section: san-management
  - section: object-storage-management
  - section: authentication-access-control
  - section: security-encryption
  - section: data-protection-disaster-recovery
  - section: event-performance-monitoring
  - title: ONTAPのマニュアルページ
    url: "/concepts/manual-pages.html"
  - title: 法的通知
    url: "/legal-notices.html"
product-family:
  name: ONTAP
  repo: ontap-family
