---
sidebar: sidebar 
permalink: task_nas_file_system_analytics_enable.html 
keywords: capacity analytics, data visualization, File System Analytics, System Manager, storage, explorer 
summary: 容量分析などの使用状況データを収集して表示するには、 File System Analytics を有効にする必要があります。 
---
= File System Analytics を有効にします
:toc: macro
:hardbreaks:
:toclevels: 1
:allow-uri-read: 
:toc: 
:toclevels: 1
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/
:toc-position: content


[role="lead"]
容量分析などの使用状況データを収集して表示するには、 File System Analytics を有効にする必要があります。

ファイルシステム分析は、新しいボリュームを作成するとき、またはボリュームのあるシステムを ONTAP 9.8 以降にアップグレードするときに有効にできます。アップグレード後、分析を有効にする前に、すべてのアップグレードプロセスが完了していることを確認します。



== 手順

ボリュームのサイズと内容によっては、 ONTAP がボリューム内の既存データを処理する間、分析を有効にするのに時間がかかることがあります。完了すると、 System Manager に進捗状況が表示され、分析データが表示されます。初期化の進行状況についてより詳細な情報が必要な場合は、 ONTAP CLI コマンドの volume analytics show を使用してください。

ファイルシステム分析は、 ONTAP システムマネージャ、 ONTAP CLI 、または ONTAP REST API を使用して有効にできます。

[role="tabbed-block"]
====
.System Manager の略
--
|===
| ONTAP 9.8 および 9.9.1 では | ONTAP 9.10.1 以降でサポートされます 


| 1. 「 * Storage 」 > 「 Volumes 」を選択します。2. 目的のボリュームを選択し、 * エクスプローラ * を選択します。3. 「 * 分析を有効にする * 」または「 * 分析を無効にする * 」を選択します。 | 1. 「 * Storage 」 > 「 Volumes 」を選択します。2. 目的のボリュームを選択します。個別のボリューム・メニューから、 * ファイル・システム > エクスプローラ * を選択します。3. 「 * 分析を有効にする * 」または「 * 分析を無効にする * 」を選択します。 
|===
--
.CLI の使用
--
.CLI でファイルシステム分析を有効にするには、次の手順を実行します
. 次のコマンドを実行します。 'volume analytics on -vserver _SVM_name -volume_name_[-foreground ｛ true|false ｝ ] デフォルトでは、このコマンドはフォアグラウンドで実行されます。 ONTAP は進行状況を表示し、完了すると分析データを表示します。より正確な情報が必要な場合は、 -foreground false オプションを使用してバックグラウンドでコマンドを実行し、 volume analytics show コマンドを使用して CLI で初期化の進行状況を表示できます。
. ファイルシステム分析を有効にしたあと、 ONTAP システムマネージャまたは ONTAP REST API を使用して分析データを表示します。


--
====