---
sidebar: sidebar 
permalink: task_san_configure_protection_for_business_continuity.html 
keywords: netapp, ontap, System Manager, LUNs, source cluster, protect, protection, storage VM, volume, volumes, source, destination, cluster, IOPS activity 
summary: ビジネス継続性の保護を設定するには、 ONTAP ソースクラスタで LUN を選択し、整合グループに追加します。ソースクラスタのブラウザから System Manager を開き、ビジネス継続性の保護の設定を開始します。 
---
= ビジネス継続性の保護を構成します
:toc: macro
:hardbreaks:
:toclevels: 1
:allow-uri-read: 
:toc: 
:toclevels: 1
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/
:toc-position: content


[role="lead"]
ビジネス継続性の保護を設定するには、 ONTAP ソースクラスタで LUN を選択し、整合グループに追加します。ソースクラスタのブラウザから System Manager を開き、ビジネス継続性の保護の設定を開始します。

このワークフローは、 ONTAP 9.8 および 9.9 向けに設計されています。ONTAP 9.10.1 以降では、まず整合グループを作成し、次に SM-BC をリモート保護として使用することを推奨します。



== このタスクについて

* LUN は同じ Storage VM に存在する必要があります。
* LUN は異なるボリュームに配置できます。
* ソースとデスティネーションのクラスタを同じにすることはできません。
* デフォルト IPspace は、クラスタピア関係を確立するために SM-BC で必要です。カスタム IPspace はサポートされません。


.手順
. 保護する LUN を選択し ' 保護グループに追加します * 保護 > 概要 > ビジネス継続性のための保護 > LUN の保護 *
. ソースクラスタで保護する LUN を 1 つ以上選択してください。
. デスティネーションクラスタと SVM を選択
. * 初期化関係 * がデフォルトで選択されています。[ 保存（ Save ） ] をクリックして保護を開始します。
. [Dashboard] > [Performance] に移動して、 LUN の IOPS アクティビティを確認します。
. デスティネーションクラスタで、 System Manager を使用して、ビジネス継続性関係の保護が同期されていることを確認します。 * Protection > Relationships * 。

