---
sidebar: sidebar 
permalink: task_admin_view_submit_support_cases.html 
keywords: support, case, view, submit, active iq, telemetry, log, logging 
summary: ONTAP 9.9.1以降では、クラスタに関連付けられているActive IQ からサポートケースを表示したり、新しいサポートケースの送信に必要な情報を確認したりできます。ONTAP 9.10.1以降ではテレメトリログを有効にすることができるため、サポート担当者による問題のトラブルシューティングに役立ちます。 
---
= サポートケースの表示と送信
:toc: macro
:hardbreaks:
:toclevels: 1
:allow-uri-read: 
:toc: 
:toclevels: 1
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/
:toc-position: content


[role="lead"]
ONTAP 9.9.1以降では、クラスタに関連付けられているActive IQ でサポートケースを確認できます。NetApp Support Siteで新しいサポートケースを送信するために必要なクラスタの詳細をコピーすることもできます。ONTAP 9.10.1以降ではテレメトリログを有効にすることができるため、サポート担当者による問題のトラブルシューティングに役立ちます。


NOTE: ファームウェアの更新に関するアラートを受信するには、Active IQ Unified Manager に登録する必要があります。を参照してください link:https://netapp.com/support-and-training/documentation/active-iq-unified-manager["Active IQ Unified Manager のドキュメント"^]。

.手順
. System Manager で、 * Support * を選択します。
+
このクラスタに関連付けられている、開いているサポートケースのリストが表示されます。

. 次のリンクをクリックして手順を実行します。
+
** * ケース番号 * ：ケースの詳細を参照してください。
** * NetApp Support Siteにアクセス * ：NetApp Support Siteの「 My AutoSupport 」ページに移動して、ナレッジベースの記事を参照したり、新しいサポートケースを送信したりできます。
** * My Cases * ：NetApp Support Siteの * My Cases * ページに移動します。
** * クラスタの詳細を表示 * ：新しいケースを送信するときに必要な情報を表示してコピーします。






== テレメトリログを有効にします

ONTAP 9.10.1以降では、System Managerを使用してテレメトリロギングを有効にできます。テレメトリログが許可されている場合、System Managerによってログに記録されるメッセージには、メッセージをトリガーした正確なプロセスを示す特定のテレメトリ識別子が与えられます。そのプロセスに関連して発行されるメッセージはすべて同じ識別子を持ち、運用ワークフローの名前と番号（例：「add-volume - 1941290」）で構成されます。

パフォーマンスの問題が発生した場合はテレメトリログを有効にすると、サポート担当者はメッセージが発行されたプロセスをより簡単に識別できます。メッセージにテレメトリーIDが追加されると、ログファイルはわずかに拡大されます。

.手順
. System Managerで、* Cluster > Settings *の順に選択します。
. [* UI設定*（UI Settings）]セクションで、[*テレメータのログを許可する*（Allow Telemetry logging *）]チェックボックスをオンにし

