---
sidebar: sidebar 
permalink: task_metrocluster_troubleshooting.html 
keywords: system manager, troubleshoot, error, event, problem, metrocluster, maintenance, fix, correction, health, check 
summary: メンテナンスを実施したり、問題からリカバリしたりするために、ある MetroCluster サイトから別のサイトにスイッチオーバーできます。 
---
= IP MetroCluster 設定に関する問題のトラブルシューティングを行う
:hardbreaks:
:toclevels: 1
:allow-uri-read: 
:toclevels: 1
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
ONTAP 9.8 以降では、 System Manager によって IP MetroCluster 構成の健全性が監視されるため、発生する可能性のある問題を特定して修正できます。



== MetroCluster ヘルスチェックの概要

System Manager は、 IP MetroCluster 構成の健常性を定期的にチェックします。  ダッシュボードで MetroCluster セクションを表示すると、通常は「 MetroCluster systems are healthy 」というメッセージが表示されます。

ただし、問題が発生すると、メッセージにイベント数が表示されます。そのメッセージをクリックすると、次のコンポーネントの健全性チェックの結果を確認できます。

* ノード
* Network Interface の略
* ティア（ストレージ）
* クラスタ
* 接続
* ボリューム
* Configuration Replication （設定レプリケーション）


[ ステータス * ] 列は問題のあるコンポーネントを示し、 [ 詳細 * ] 列は問題の解決方法を示します。



== MetroCluster のトラブルシューティング

.手順
. System Manager で、 * Dashboard * を選択します。
. 「 * MetroCluster * 」セクションで、メッセージを確認します。
+
.. MetroCluster 構成が正常であることを示すメッセージが表示され、クラスタと ONTAP メディエーターの間の接続が正常である（チェックマーク付きで表示）場合は、修正する問題はありません。
.. メッセージにイベント数がリストされている場合、または接続がダウンした（「 X 」で表示）場合は、次の手順に進みます。


. イベント数を示すメッセージをクリックします。
+
MetroCluster 正常性レポートが表示されます。

. レポートに表示される問題のトラブルシューティングを、 *Details* 列の推奨事項を使用して行います。
. すべての問題を修正したら、 * MetroCluster の正常性を確認 * をクリックします。
+

NOTE: MetroCluster ヘルスチェックでは大量のリソースが使用されるため、チェックを実行する前にすべてのトラブルシューティングタスクを実行することをお勧めします。

+
MetroCluster の健全性チェックがバックグラウンドで実行されます。  他のタスクは、終了するまで待つことができます。


