---
sidebar: sidebar 
permalink: task_nas_provision_flexgroup.html 
keywords: netapp, ontap, provision, provisioning, nas, large file systems, using, FlexGroup, windows, servers, cifs, smb, FlexVol volume limits, load distribution, work load, workload, balancing, data 
summary: FlexGroup ボリュームは拡張性に優れた NAS コンテナで、ハイパフォーマンスと自動負荷分散を実現します。FlexGroupボリュームは、FlexVolの制限をはるかに超える大容量（ペタバイト単位）を提供し、管理オーバーヘッドを発生させることはありません。 
---
= FlexGroup を使用して大規模ファイルシステム用の NAS ストレージをプロビジョニング
:hardbreaks:
:toclevels: 1
:allow-uri-read: 
:toclevels: 1
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
FlexGroup ボリュームは拡張性に優れた NAS コンテナで、ハイパフォーマンスと自動負荷分散を実現します。FlexGroupボリュームは、FlexVolの制限をはるかに超える大容量（ペタバイト単位）を提供し、管理オーバーヘッドを発生させることはありません。

このセクションのトピックでは、 ONTAP 9.7 以降のリリースで System Manager を使用して FlexGroup ボリュームを管理する方法を説明します。従来の System Manager （ ONTAP 9.7 以前でのみ使用可能）を使用している場合は、次のトピックを参照してください。

* https://docs.netapp.com/us-en/ontap-system-manager-classic/online-help-96-97/task_creating_flexgroup_volumes.html["FlexGroup ボリュームを作成します"^]


ONTAP 9.9.1以降では、2つ以上のFlexGroup のSnapMirrorファンアウト関係（最大8つのファンアウトレッグ）がサポートされます。System Manager では、 SnapMirror カスケード FlexGroup ボリューム関係はサポートされません。

ONTAP は、 FlexGroup ボリュームの作成に必要なローカル階層を自動的に選択します。

ONTAP 9 8以降では、ストレージのプロビジョニング時にデフォルトでQoSが有効になります。プロビジョニングプロセス中またはあとで、QoSを無効にしたり、カスタムのQoSポリシーを選択したりできます。

.手順
. [ ストレージ ] 、 [ ボリューム ] の順にクリックします。
. [ 追加（ Add ） ] をクリックします。
. [ * その他のオプション * ] をクリックし、 [ * ボリュームデータをクラスタに分散する * ] を選択します。
+

NOTE: ONTAP 9.8以降を実行していて、QoSを無効にするかカスタムQoSポリシーを選択する場合は、*[その他のオプション]*をクリックし、*[ストレージと最適化]*で*[パフォーマンスサービスレベル]*を選択します。





== ビデオ



=== FlexGroup ボリュームを作成および管理します

video::gB-yF1UTv2I[youtube,width=848,height=480]


== FlexGroup ボリューム-少ないリソースでより多くの成果を達成

video::0B4nlChf0b4[youtube,width=848,height=480]