---
sidebar: sidebar 
permalink: task_cp_monitor_cluster_performance_ci.html 
keywords: netapp, ontap, cluster, performance, monitor, monitoring, headroom, cpu, cpus, data infrastructure insights, troubleshoot, optimize, private data center, Kafka, MongoDB, Nginx, Active IQ Unified Manager, cluster performance, monitor performance 
summary: Data Infrastructure Insights を使用すると、パブリック クラウドやプライベート データ センターを含むすべてのリソースを監視、トラブルシューティング、最適化できます。 
---
= ONTAP Data Infrastructure Insightsでクラスタのパフォーマンスを監視する
:hardbreaks:
:toclevels: 1
:allow-uri-read: 
:toclevels: 1
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
NetApp Data Infrastructure Insightsは、インフラ全体を可視化する監視ツールです。パブリッククラウドやプライベートデータセンターを含むすべてのリソースを監視、トラブルシューティング、最適化できます。



== データインフラストラクチャインサイトには2つのエディションがあります

Data Infrastructure Insights Basic Editionは、NetApp Data Fabric資産の監視と最適化に特化して設計されています。環境内のHCIやAll Flash FAS（AFF）を含むすべてのNetAppリソース間の接続に関する高度な分析機能を無料で提供します。

Data Infrastructure Insights Standard Editionは、NetApp Data Fabric対応のインフラコンポーネントだけでなく、マルチベンダーおよびマルチクラウド環境にも重点を置いています。充実した機能により、100を超えるサービスとリソースのサポートにアクセスできます。

オンプレミスのデータセンターから複数のパブリッククラウドまでリソースが分散している今日の環境では、アプリケーション自体からストレージアレイのバックエンドディスクまでの全体像を把握することが重要です。さらに、アプリケーション監視（Kafka、MongoDB、Nginxなど）もサポートされるため、最適な利用率と最適なリスクバッファで運用するために必要な情報や知識を得ることができます。

BasicとStandardのどちらのエディションも、NetApp Active IQ Unified Managerと連携できます。ActiveIQ Unified Managerをご利用のお客様は、Data Infrastructure Insightsのユーザーインターフェース内で統合情報を確認できます。ActiveIQ Unified Managerに投稿された通知は見逃されることなく、Data Infrastructure Insightsのイベントと相関分析できます。つまり、両方のメリットを享受できるのです。



== すべてのリソースを監視、トラブルシューティング、最適化

Data Infrastructure Insightsは、問題解決にかかる時間を大幅に短縮し、エンドユーザーへの影響を未然に防ぎます。また、クラウドインフラストラクチャのコスト削減にも役立ちます。実用的なインテリジェンスでデータを保護することで、内部脅威への露出を軽減します。

Data Infrastructure Insightsは、パブリッククラウドからデータセンターまで、ハイブリッドインフラストラクチャ全体を一元的に可視化します。特定のニーズに合わせてカスタマイズ可能なダッシュボードを瞬時に作成できます。また、組織のニーズに具体的かつ関連性の高い、ターゲットを絞った条件付きアラートも作成できます。

高度な異常検出機能により、問題が発生する前にプロアクティブに解決できます。リソースの競合や利用率の低下が自動的に表示されるため、影響を受けているワークロードをすばやくリストアできます。環境内のさまざまなコンポーネントの関係が自動的に階層化されて可視化されるため、迅速なトラブルシューティングが可能です。

環境全体から未使用のリソースや放置されたリソースを洗い出し、インフラの規模を適切に調整して全体的な支出を最適化する方法を探ることができます。

Data Infrastructure Insightsは、システムトポロジを視覚化し、Kubernetesアーキテクチャの理解を深めます。Kubernetesクラスターの健全性（問題のあるノードなど）を監視し、問題が見つかった場合は拡大表示できます。

Data Infrastructure Insights は、内部脅威に関する実用的な情報を提供する高度な機械学習と異常検出を通じて、悪意のあるユーザーや侵害を受けたユーザーによる組織のデータの悪用から保護するのに役立ちます。

Data Infrastructure InsightsはKubernetesメトリクスを可視化し、ポッド、ノード、クラスター間の関係を完全に把握するのに役立ちます。クラスターや稼働中のポッドの健全性、そして現在処理中の負荷を評価できるため、K8Sクラスターを自在に制御し、デプロイメントの健全性とコストの両方をコントロールできます。

.関連リンク
* link:https://docs.netapp.com/us-en/cloudinsights/task_cloud_insights_onboarding_1.html["データインフラストラクチャインサイトを使い始める"^]

