---
sidebar: sidebar 
permalink: task_cp_monitor_cluster_performance_um.html 
keywords: netapp, ontap, cluster, performance, monitor, monitoring, unified manager, active IQ, headroom, cpu, cpus, latency, maximize availability, AFF storage, FAS storage, scalability, supportability, support, security, data management 
summary: NetApp Active IQ Unified Manager を使用すると、システム管理を簡易化し、ストレージの健常性を監視できます。 
---
= Unified Managerを使用したクラスタパフォーマンスの監視
:hardbreaks:
:toclevels: 1
:allow-uri-read: 
:toclevels: 1
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Active IQ Unified Managerを使用すると、可用性を最大限に高め、NetApp AFFおよびFASのストレージインフラの制御を維持して、拡張性、サポート性、パフォーマンス、セキュリティを向上させることができます。

Active IQ Unified Managerはシステムの健全性を継続的に監視してアラートを送信するため、ITスタッフのリソースを解放できます。単一のダッシュボードからストレージのステータスを瞬時に確認し、推奨される対処方法に従って問題に迅速に対処できます。

検出と監視を行い、通知を受け取ることで、ストレージをプロアクティブに管理して迅速に問題を解決できるため、データ管理が簡易化されます。ペタバイト規模のデータを単一のダッシュボードから監視し、大規模なデータを管理できるため、管理効率が向上します。

Active IQ Unified Managerを使用すると、パフォーマンスデータと高度な分析を使用してパフォーマンスを最適化し、変動するビジネスニーズに対応できます。レポート機能を使用すると、標準のレポートにアクセスしたり、ビジネス固有のニーズに合わせてカスタムの運用レポートを作成したりできます。

関連リンク：

* link:https://docs.netapp.com/us-en/active-iq-unified-manager/storage-mgmt/concept_introduction_to_unified_manager.html["Active IQ Unified Managerの詳細はこちら"^]
* link:https://docs.netapp.com/us-en/active-iq-unified-manager/install-vapp/qsg-vapp.html["Active IQ Unified Manager for VMwareの利用を開始する"^]
* link:https://docs.netapp.com/us-en/active-iq-unified-manager/install-linux/qsg-linux.html["Active IQ Unified Manager for Linusの使用を開始する"^]
* link:https://docs.netapp.com/us-en/active-iq-unified-manager/install-windows/qsg-windows.html["Active IQ Unified Manager for Windowsの使用を開始する"^]

