---
sidebar: sidebar 
permalink: task_cp_monitor_cluster_performance_ci.html 
keywords: netapp, ontap, cluster, performance, monitor, monitoring, headroom, cpu, cpus, Cloud Insights, troubleshoot, optimize, private data center, Kafka, MongoDB, Nginx, Active IQ Unified Manager, cluster performance, monitor performance 
summary: Cloud Insights を使用すると、パブリッククラウドやプライベートデータセンターなど、すべてのリソースの監視、トラブルシューティング、最適化を行うことができます。 
---
= Cloud Insights を使用してクラスタパフォーマンスを監視する
:toc: macro
:hardbreaks:
:toclevels: 1
:allow-uri-read: 
:toc: 
:toclevels: 1
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/
:toc-position: content


[role="lead"]
NetApp Cloud Insights は、インフラ全体を可視化する監視ツールです。Cloud Insights を使用すると、パブリッククラウドやプライベートデータセンターなど、すべてのリソースの監視、トラブルシューティング、最適化を行うことができます。



== Cloud Insights には 2 つのエディションがあります

Cloud Insights 基本エディションは、ネットアップデータファブリック資産の監視と最適化を目的に設計されています。HCI を含むネットアップのすべてのリソースと、環境内の All Flash FAS （ AFF ）間の接続を無償で分析します。

Cloud Insights Standard エディションは、ネットアップデータファブリックに対応したインフラコンポーネントだけでなく、マルチベンダー / マルチクラウド環境にも焦点を当てています。豊富な機能により、 100 を超えるサービスとリソースのサポートにアクセスできます。

今日の世界では、オンプレミスのデータセンターから複数のパブリッククラウドにリソースを活用しているため、アプリケーション自体からストレージアレイのバックエンドディスクまで、完全なイメージを把握することが重要です。さらに、アプリケーションの監視（ Kafka 、 MongoDB 、 Nginx など）もサポートされているため、最適な利用率レベルと完全なリスクバッファで運用するために必要な情報と知識を得ることができます。

どちらのエディション（ Basic および Standard ）も NetApp Active IQ Unified Manager と統合できます。Active IQ Unified Manager を使用しているお客様は、 Cloud Insights のユーザインターフェイス内で参加情報を確認できます。Active IQ Unified Manager に投稿された通知は見過ごされず、 Cloud Insights のイベントと関連付けることができます。つまり、両方の世界を最大限に活用できます。



== すべてのリソースの監視、トラブルシューティング、最適化を行います

Cloud Insights を使用すると、問題の解決にかかる時間を大幅に短縮し、エンドユーザへの影響を防ぐことができます。  また、クラウドインフラのコスト削減にも役立ちます。  実用的な情報でデータを保護することで、内部の脅威にさらされる危険性が軽減されます。

Cloud Insights を使用すると、パブリッククラウドからデータセンターまで、ハイブリッドインフラ全体を 1 箇所で可視化できます。  必要に応じてカスタマイズできる関連ダッシュボードを瞬時に作成できます。また、組織のニーズに合わせて、ターゲットを絞ったアラートや条件付きアラートを作成することもできます。

高度な異常検出機能により、問題が発生する前にプロアクティブに解決できます。  リソースの競合と低下を自動的に確認して、影響を受けたワークロードを迅速にリストアできます。  スタック内のさまざまなコンポーネント間の関係を自動的に構築することで、トラブルシューティングがより迅速になります。

使用されていないリソースや放置されたリソースを環境全体で特定することで、インフラの規模を適正化し、支出全体を最適化する機会を見つけ出すことができます。

Cloud Insights は、システムトポロジを可視化し、 Kubernetes アーキテクチャを把握します。Kubernetes クラスタの健常性を監視できます。問題が発生しているノードを監視し、問題が発生したときにズームインすることができます。

Cloud Insights は、高度な機械学習と異常検出機能により、悪意のあるユーザや侵害されたユーザによる組織データの不正利用を防止し、内部の脅威に関する実用的な情報を提供します。

Cloud Insights は Kubernetes 指標を可視化することで、ポッド、ノード、クラスタ間の関係を完全に把握できるようになります。クラスタまたは作業ポッドの正常性、および現在処理中の負荷を評価できます。これにより、 K8S クラスタのコマンドを実行し、展開の健全性とコストの両方を制御できます。
