---
sidebar: sidebar 
permalink: task_admin_add_cache_to_local_tier.html 
keywords: add, expand, cache, add cache, local tier, hybrid, flashpool, flash pool, increase performance, aggregate, HDD, SSD, working data set, dataset, convert an existing aggregate 
summary: SSD を追加して既存のアグリゲートを Flash Pool アグリゲートに変換し、キャッシュをプロビジョニングすることができます。Flash Pool アグリゲートを使用すると、作業データセットにはフラッシュを導入して高性能なキャッシュを利用しながら、アクセス頻度が低いデータには低コストの HDD を使用することができます。 
---
= ローカル階層にキャッシュを追加してください
:toc: macro
:hardbreaks:
:toclevels: 1
:toc: 
:toclevels: 1
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/
:toc-position: content


[role="lead"]
ソリッドステートドライブ（ SSD ）キャッシュをプロビジョニングするには、 SSD を追加して既存のローカル階層（アグリゲート）を Flash Pool アグリゲートに変換します。Flash Pool アグリゲートを使用すると、作業データセットには Flash を高性能なキャッシュとして導入しながら、アクセス頻度が低いデータには低コストの HDD を使用できます。

SSD キャッシュをプロビジョニングしてローカル階層に追加するプロセスは、インストールされている ONTAP のバージョンによって異なります。

[cols="40,60"]
|===
| 使用する ONTAP のバージョン | 実行する手順 


| ONTAP 9.8 以降 | <<Use the CLI to create an SSD storage pool>> 


| ONTAP 9.7 | <<Use System Manager to add an SSD cache (ONTAP 9.7 only)>> 
|===


== CLI を使用して SSD ストレージプールを作成してください

ONTAP 9.8 以降の CLI を使用して、 2~4 つの Flash Pool アグリゲートに SSD キャッシュを提供する SSD ストレージプールを作成します。

.手順
. ディスクとアグリゲートパワーガイドの手順を実行します。 link:https://docs.netapp.com/ontap-9/topic/com.netapp.doc.dot-cm-psmg/GUID-D3BFC47A-5545-4D94-A6E8-265057F58230.html["SSD ストレージプールを作成する"]。




== System Manager を使用して SSD キャッシュを追加する（ ONTAP 9.7 のみ）

.手順
. [*]( クラシックバージョンに戻る )* をクリックします。
. ストレージ > アグリゲートとディスク > アグリゲート * をクリックします。
. ローカル階層（アグリゲート）を選択し、 * Actions > Add Cache * をクリックします。
. キャッシュソースとして、「ストレージプール」または「専用 SSD 」を選択します。
. （新しいエクスペリエンスに切り替える） * をクリックします。
. Storage > Tiers * をクリックして、新しいアグリゲートのサイズを確認します。

