---
sidebar: sidebar 
permalink: task_nas_file_system_analytics_view.html 
keywords: netapp, ontap, data, file, files, system, analytics, explorer, File System Analytics, File System Analytics Explorer, volume, volumes, System Manager, system manager explorer, directory, directories, subdirectory, subdirectories, object, tree, subtree, tree view, history, historical data, active data, inactive data 
summary: File System Analytics を有効にすると、 System Manager のエクスプローラタブに選択したボリュームのデフォルトビューが表示され、ボリュームのルートディレクトリの内容が各サブツリーで使用されているスペースでソートされて表示されます。 
---
= ファイルシステムのアクティビティを表示します
:toc: macro
:hardbreaks:
:toclevels: 1
:toc: 
:toclevels: 1
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/
:toc-position: content


[role="lead"]
ファイルシステム分析を有効にすると、デフォルトで、選択したボリュームのルートディレクトリの内容を各サブツリーで使用されている間隔でソートして表示できます

ファイルシステムオブジェクトをクリックすると、ファイルシステムを参照したり、ディレクトリ内の各オブジェクトの詳細情報を表示したりできます。ディレクトリの情報をグラフィカルに表示することもできます。時間の経過とともに、各サブツリーの履歴データが表示されます。ディレクトリ数が 3000 を超える場合、使用済みスペースはソートされません。ONTAP 9.10.1 以降では、を使用したリアルタイムのパフォーマンストラブルシューティング用に、指定したボリューム内のホットファイル、ディレクトリ、クライアント、およびユーザを表示できます <<Activity Tracking>>。



== エクスプローラ（ Explorer ）

File System Analytics * Explorer * 画面は、次の 3 つの領域で構成されています。

* ディレクトリとサブディレクトリのツリービュー。名前、サイズ、変更履歴、アクセス履歴を示す展開可能なリスト。
* ファイル。ディレクトリリストで選択したオブジェクトの名前、サイズ、アクセス日時を表示します。
* ディレクトリリストで選択したオブジェクトのアクティブデータと非アクティブデータの比較。
+
ONTAP 9.9..1 以降では、レポートする範囲をカスタマイズできます。デフォルトは 1 年です。これらのカスタマイズ内容に基づいて、ボリュームの移動や階層化ポリシーの変更などの対処を実行できます。



デフォルトでは、アクセス時間が表示されます。ただし 'volume modify コマンドで -atime-update オプションを false に設定することにより ' ボリューム・デフォルトが CLI から変更された場合は ' 最終変更時刻のみが表示されます例：

* ツリービューには、 * アクセス履歴 * は表示されません。
* ファイルビューが変更されます。
* アクティブ / 非アクティブデータ表示は、変更された時間（「 m time 」）に基づいて行われます。


これらの表示を使用して、次のことを確認できます。

* ファイルシステムの場所が最も多くのスペースを消費している
* ディレクトリおよびサブディレクトリ内のファイル数やサブディレクトリ数など、ディレクトリツリーに関する詳細情報
* 古いデータを含むファイルシステムの場所（スクラッチ、一時、ログツリーなど）


ファイルシステムの分析結果を解釈するときは、次の点に注意してください。

* ファイルシステム分析では、データの処理量ではなく、データの使用状況と使用状況が表示されます。たとえば、最近アクセスされたファイルや変更されたファイルによる大量のスペース消費は、必ずしもシステムの処理負荷が高いことを示すわけではありません。
* [ ボリュームエクスプローラ ] タブでのファイルシステム分析のためのスペース消費の計算方法は、他のツールとは異なる場合があります。特に、ボリュームで Storage Efficiency 機能が有効になっている場合、ボリューム概要 * で報告される消費量と大きく異なる可能性があります。これは、 * ボリュームエクスプローラ * タブには効率化による削減効果がないためです。
* ディレクトリ表示のスペースに制限があるため、 _List View_ で 8 レベルを超えるディレクトリ階層を表示することはできません。8 レベルを超えるディレクトリを詳細に表示するには、 _Graphical View_ に切り替え、目的のディレクトリを見つけて、 _List View_ に切り替える必要があります。これにより、ディスプレイに画面スペースが追加されます。


* 手順 *

|===


| ONTAP 9.8 および 9.9 の場合 | ONTAP 9.10.1 以降でサポートされます 


| [* ストレージ ] 、 [ ボリューム ] の順にクリックし、目的のボリュームを選択して、 [* エクスプローラ *] をクリックします。 | [* Storage] > [Volumes] を選択し、目的のボリュームを選択します。個別のボリューム・メニューから、 * ファイル・システム > エクスプローラ * を選択します。 
|===


== アクティビティの追跡

ONTAP 9.10.1 以降では、アクティビティトラッキングでホットオブジェクトを識別できます。アクティビティ追跡では、次の 4 つのカテゴリでモニタリングが可能です。

* ディレクトリ
* ファイル
* クライアント
* ユーザ


監視対象のカテゴリごとに、アクティビティ追跡に読み取り IOPS 、書き込み IOPS 、読み取りスループット、書き込みスループットが表示されます。アクティビティトラッキングに関するクエリーは、過去 5 秒間にシステムに表示されたホットスポットに関連する 10 ～ 15 秒ごとに更新されます。

アクティビティ追跡情報は概算値であり、データの正確性は受信 I/O トラフィックの分散に依存します。

System Manager でアクティビティ追跡を表示している場合は、展開したボリュームのメニューだけがアクティブに更新されます。ボリュームのビューが縮小されている場合、ボリュームの表示が展開されるまで表示は更新されません。更新を停止するには、 * 更新を一時停止 * ボタンを使用します。アクティビティデータは CSV 形式でダウンロードでき、選択したボリュームについて収集されたすべてのポイントインタイムデータが表示されます。

.手順
. Storage > Volumes （ストレージ）を選択します。目的のボリュームを選択します。個々のボリュームメニューから、ファイルシステムを選択し、アクティビティタブを選択します。
. 上位のディレクトリ、ファイル、クライアント、およびユーザに関する個々のレポートを表示するには、 * Activity Tracking * がオンになっていることを確認します。
. 更新を行わずにデータをより詳細に分析するには、 * 更新を一時停止 * を選択します。データをダウンロードして、レポートの CSV レコードを取得することもできます。

