---
permalink: tape-backup/assign-tape-aliases-concept.html 
sidebar: sidebar 
keywords: aliasing, ppn, physical, path, name, sn, serial, number, medium, changer, alias, name 
summary: エイリアシングにより、デバイスの識別プロセスが簡素化されます。エイリアス設定では、テープまたはメディアチェンジャのPhysical Path Name（PPN；物理パス名）またはSerial Number（SN；シリアル番号）を、変更可能な永続的なエイリアス名にバインドします。 
---
= テープのエイリアス設定の概要
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
エイリアシングにより、デバイスの識別プロセスが簡素化されます。エイリアス設定では、テープまたはメディアチェンジャのPhysical Path Name（PPN；物理パス名）またはSerial Number（SN；シリアル番号）を、変更可能な永続的なエイリアス名にバインドします。

次の表に、テープのエイリアス設定を使用して、テープドライブ（またはテープライブラリやメディアチェンジャ）に常に単一のエイリアス名を関連付ける方法を示します。

|===
| シナリオ | エイリアスの再割り当て 


 a| 
システムのリブート時
 a| 
テープドライブには、以前のエイリアスが自動的に再割り当てされます。



 a| 
テープデバイスを別のポートに移動するタイミング
 a| 
エイリアスは、新しいアドレスを指すように調整できます。



 a| 
複数のシステムで特定のテープデバイスを使用する場合
 a| 
ユーザは、エイリアスをすべてのシステムで同じに設定できます。

|===
[NOTE]
====
Data ONTAP 8 .1.xからData ONTAP 8 .2.xにアップグレードする場合、Data ONTAP 8 .2.xのテープエイリアス機能によって既存のテープエイリアス名が変更されます。このような場合は、バックアップアプリケーションでテープエイリアス名を更新しなければならないことがあります。

====
テープエイリアスを割り当てることで、バックアップデバイスの論理名（st0やmc1など）と、ポート、テープドライブ、またはメディアチェンジャに永続的に割り当てられた名前を関連付けることができます。

[NOTE]
====
st0とst00は異なる論理名です。

====
[NOTE]
====
論理名とシリアル番号は、デバイスへのアクセスにのみ使用されます。デバイスにアクセスすると、物理パス名を使用してすべてのエラーメッセージが返されます。

====
エイリアスに使用できる名前には、物理パス名とシリアル番号の2種類があります。
