---
permalink: tape-backup/commands-manage-drives-media-changers-reference.html 
sidebar: sidebar 
keywords: manage, tape, drive, media, changer, operation, cluster, cartridge, position, online, offline, reset, clear 
summary: クラスタ内のテープ ドライブとメディア チェンジャーに関する情報の表示、テープ ドライブのオンライン化とオフライン化、テープ ドライブ カートリッジ位置の変更、テープ ドライブ エイリアス名の設定とクリア、テープ ドライブのリセットを行うコマンドがあります。また、テープ ドライブ統計情報の表示とリセットも可能です。 
---
= テープ ドライブ、メディア チェンジャー、およびテープ ドライブ操作を管理するための ONTAP コマンド
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
クラスタ内のテープ ドライブとメディア チェンジャーに関する情報の表示、テープ ドライブのオンライン化とオフライン化、テープ ドライブ カートリッジ位置の変更、テープ ドライブ エイリアス名の設定とクリア、テープ ドライブのリセットを行うコマンドがあります。また、テープ ドライブ統計情報の表示とリセットも可能です。

|===
| 状況 | 使用するコマンド 


 a| 
テープ ドライブをオンラインにする
 a| 
`storage tape online`



 a| 
テープ ドライブまたはメディア チェンジャーのエイリアス名をクリアする
 a| 
`storage tape alias clear`



 a| 
テープ ドライブのテープ トレース処理を有効または無効にします
 a| 
`storage tape trace`



 a| 
テープ ドライブのカートリッジ位置を変更する
 a| 
`storage tape position`



 a| 
テープ ドライブをリセットする
 a| 
`storage tape reset`

[NOTE]
====
このコマンドは、advanced権限レベルでのみ使用できます。

====


 a| 
テープ ドライブまたはメディア チェンジャのエイリアス名を設定する
 a| 
`storage tape alias set`



 a| 
テープ ドライブをオフラインにする
 a| 
`storage tape offline`



 a| 
すべてのテープ ドライブとメディア チェンジャに関する情報を表示する
 a| 
`storage tape show`



 a| 
クラスタに接続されているテープ ドライブに関する情報を表示します
 a| 
* `storage tape show-tape-drive`
* `system node hardware tape drive show`




 a| 
クラスタに接続されているメディア チェンジャに関する情報を表示します
 a| 
`storage tape show-media-changer`



 a| 
クラスタに接続されたテープ ドライブに関するエラー情報を表示します
 a| 
`storage tape show-errors`



 a| 
クラスタ内の各ノードに接続されているすべての ONTAP 認定およびサポートされているテープ ドライブを表示します
 a| 
`storage tape show-supported-status`



 a| 
クラスタ内の各ノードに接続されているすべてのテープ ドライブとメディア チェンジャーのエイリアスを表示します。
 a| 
`storage tape alias show`



 a| 
テープ ドライブの統計情報の読み取り値をゼロにリセットする
 a| 
`storage stats tape zero` `tape_name`

このコマンドはノードシェルで使用する必要があります。



 a| 
ONTAPでサポートされるテープドライブを表示
 a| 
`storage show tape supported [-v]`

このコマンドはノードシェルで使用する必要があります。 `-v`オプションを使用すると、各テープ ドライブの詳細を表示できます。



 a| 
テープ デバイス統計情報を表示して、テープのパフォーマンスを理解し、使用パターンを確認する
 a| 
`storage stats tape` `tape_name`

このコマンドはノードシェルで使用する必要があります。

|===
.関連情報
* link:https://docs.netapp.com/us-en/ontap-cli/search.html?q=storage+tape["ストレージ テープ"^]
* link:https://docs.netapp.com/us-en/ontap-cli/storage-tape-show.html["storage tape show"^]
* link:https://docs.netapp.com/us-en/ontap-cli/storage-tape-show-supported-status.html["storage tape show-supported-status"^]
* link:https://docs.netapp.com/us-en/ontap-cli/storage-tape-show-tape-drive.html["storage tape show-tape-drive"^]
* link:https://docs.netapp.com/us-en/ontap-cli/storage-tape-alias-clear.html["ストレージ テープ エイリアス クリア"^]
* link:https://docs.netapp.com/us-en/ontap-cli/storage-tape-alias-set.html["ストレージ テープ エイリアス セット"^]
* link:https://docs.netapp.com/us-en/ontap-cli/storage-tape-alias-show.html["storage tape エイリアスの表示"^]
* link:https://docs.netapp.com/us-en/ontap-cli/storage-tape-trace.html["ストレージ テープ トレース"^]

