---
permalink: tape-backup/commands-verify-library-connections-reference.html 
sidebar: sidebar 
keywords: commands, verify, tape, library, connections, storage, system 
summary: ストレージ システムとそのストレージ システムに接続されているテープ ライブラリ構成との間の接続パスに関する情報を表示できます。この情報は、テープ ライブラリ構成への接続パスを確認する場合や、接続パスに関連する問題のトラブルシューティングを行う場合に使用します。 
---
= テープ ライブラリ接続を確認するための ONTAP コマンド
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
ストレージ システムとそのストレージ システムに接続されているテープ ライブラリ構成との間の接続パスに関する情報を表示できます。この情報は、テープ ライブラリ構成への接続パスを確認する場合や、接続パスに関連する問題のトラブルシューティングを行う場合に使用します。

テープ ライブラリに関する次の詳細情報を表示して、新しいテープ ライブラリを追加 / 作成したあとや、テープ ライブラリへのシングルパス アクセスまたはマルチパス アクセスで障害が発生したパスをリストアしたあとに、テープ ライブラリの接続を確認できます。この情報は、パス関連のエラーのトラブルシューティングを行う場合や、テープ ライブラリへのアクセスが失敗した場合にも使用できます。

* テープ ライブラリの接続先のノード
* デバイスID
* NDMPパス
* テープ ライブラリ名
* ターゲット ポートとイニシエータ ポートのID
* 各ターゲット ポートまたはFCイニシエータ ポートのテープ ライブラリへのシングルパス アクセスまたはマルチパス アクセス
* 「`Path Errors`」や「`Path Qual`」などのパス関連のデータ整合性の詳細
* LUNグループとLUN数


|===
| 状況 | 使用するコマンド 


 a| 
クラスタ内のテープ ライブラリに関する情報を表示する
 a| 
`system node hardware tape library show`



 a| 
テープ ライブラリのパス情報を表示する
 a| 
`storage tape library path show`



 a| 
各イニシエータ ポートのテープ ライブラリのパス情報を表示する
 a| 
`storage tape library path show-by-initiator`



 a| 
ストレージのテープ ライブラリとクラスタ間の接続情報を表示する
 a| 
`storage tape library config show`

|===
.関連情報
* link:https://docs.netapp.com/us-en/ontap-cli/storage-tape-library-config-show.html["ストレージ テープ ライブラリ構成表示"^]
* link:https://docs.netapp.com/us-en/ontap-cli//system-node-hardware-tape-library-show.html["system node hardware テープ ライブラリ show"^]
* link:https://docs.netapp.com/us-en/ontap-cli//storage-tape-library-path-show.html["ストレージ テープ ライブラリ パスの表示"^]
* link:https://docs.netapp.com/us-en/ontap-cli//storage-tape-library-path-show-by-initiator.html["ストレージ テープ ライブラリ パス show-by-initiator"^]

