---
permalink: tape-backup/commands-verify-library-connections-reference.html 
sidebar: sidebar 
keywords: commands, verify, tape, library, connections, storage, system 
summary: ストレージシステムとそのストレージシステムに接続されているテープライブラリの構成との間の接続パスに関する情報を表示できます。この情報は、テープライブラリの構成への接続パスを確認する場合や、接続パスに関連する問題のトラブルシューティングを行う場合に使用します。 
---
= テープライブラリの接続を確認するコマンド
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
ストレージシステムとそのストレージシステムに接続されているテープライブラリの構成との間の接続パスに関する情報を表示できます。この情報は、テープライブラリの構成への接続パスを確認する場合や、接続パスに関連する問題のトラブルシューティングを行う場合に使用します。

テープライブラリに関する次の詳細情報を表示して、新しいテープライブラリを追加または作成したあとや、テープライブラリへのシングルパスアクセスまたはマルチパスアクセスで障害が発生したパスをリストアしたあとに、テープライブラリの接続を確認できます。この情報は、パス関連のエラーのトラブルシューティングを行う場合や、テープライブラリへのアクセスが失敗した場合にも使用できます。

* テープライブラリの接続先のノードを指定します
* デバイス ID
* NDMPパス
* テープライブラリの名前
* ターゲットポートとイニシエータポートの ID
* 各ターゲットポートまたは FC イニシエータポートのテープライブラリへのシングルパスアクセスまたはマルチパスアクセス
* パス関連のデータ整合性の詳細（「パスエラー」や「パス品質」など）
* LUN グループと LUN 数


|===
| 状況 | 使用するコマンド 


 a| 
クラスタ内のテープライブラリに関する情報を表示します
 a| 
`system node hardware tape library show`



 a| 
テープライブラリのパス情報を表示します
 a| 
`storage tape library path show`



 a| 
各イニシエータポートのテープライブラリのパス情報を表示します
 a| 
`storage tape library path show-by-initiator`



 a| 
ストレージのテープライブラリとクラスタの間の接続情報を表示します
 a| 
`storage tape library config show`

|===
これらのコマンドの詳細については、マニュアルページを参照してください。
