---
permalink: tape-backup/dump-volume-move-concept.html 
sidebar: sidebar 
keywords: dump, works, volume, move, tape, backup, restore, storage, system 
summary: ストレージ システムで最終フェーズ（カットオーバー）が開始されるまでは、テープ バックアップおよびリストア処理とボリューム移動を並行して実行できます。最終フェーズのあとは、移動中のボリュームで新しいテープ バックアップおよびリストア処理を実行することはできません。ただし、現在の処理は完了するまで引き続き実行されます。 
---
= ONTAPボリューム移動でのダンプの仕組み
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
ストレージ システムで最終フェーズ（カットオーバー）が開始されるまでは、テープ バックアップおよびリストア処理とボリューム移動を並行して実行できます。最終フェーズのあとは、移動中のボリュームで新しいテープ バックアップおよびリストア処理を実行することはできません。ただし、現在の処理は完了するまで引き続き実行されます。

次の表は、ボリューム移動処理後のテープ バックアップおよびリストア処理の動作を示しています。

|===
| tape backupおよび復元操作を実行している場合は... | 操作 


 a| 
Storage Virtual Machine（SVM）を対象としたNDMPモード（CAB拡張がバックアップ アプリケーションでサポートされている場合）
 a| 
バックアップ ポリシーを再設定しなくても、読み取り / 書き込みボリュームおよび読み取り専用ボリュームで増分テープ バックアップおよびリストア処理を引き続き実行できます。



 a| 
SVMを対象としたNDMPモード（CAB拡張がバックアップ アプリケーションでサポートされていない場合）
 a| 
バックアップ ポリシーで設定されたLIFを、デスティネーション アグリゲートをホストするノードに移行する場合は、読み取り / 書き込みボリュームおよび読み取り専用ボリュームで増分テープ バックアップおよびリストア処理を引き続き実行できます。それ以外の場合は、ボリューム移動後にベースライン バックアップを実行してから増分バックアップ処理を実行する必要があります。

|===
[NOTE]
====
ボリュームを移動する場合に、デスティネーション ノード上の別のSVMに属しているボリュームの名前が移動対象のボリュームの名前と同じであると、移動対象のボリュームの増分バックアップ処理を実行できません。

====