---
permalink: tape-backup/dump-backup-restore-operations-mcc-config-concept.html 
sidebar: sidebar 
keywords: dump, backup, restore, opartion, metrocluster, configuration, switchback, switchover 
summary: MetroCluster 構成でダンプバックアップおよびリストア処理を実行するには、スイッチオーバー処理またはスイッチバック処理の実行時にダンプ処理が受ける影響について理解しておく必要があります。 
---
= MetroCluster 構成でダンプバックアップおよびリストア処理が受ける影響
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
MetroCluster 構成でダンプバックアップおよびリストア処理を実行するには、スイッチオーバー処理またはスイッチバック処理の実行時にダンプ処理が受ける影響について理解しておく必要があります。



== ダンプバックアップまたはリストア処理のあとにスイッチオーバーが行われる場合

クラスタ 1 とクラスタ 2 の 2 つのクラスタがあるとします。クラスタ 1 でダンプバックアップまたはリストア処理を実行しているときに、クラスタ 1 からクラスタ 2 へのスイッチオーバーが開始されると、次のような結果になります。

* の値の場合 `override-vetoes` オプションはです `false`を指定すると、スイッチオーバーが中止され、バックアップまたはリストア処理が続行されます。
* オプションの値がの場合 `true`を指定すると、ダンプバックアップまたはリストア処理が中止され、スイッチオーバーが続行されます。




== ダンプバックアップまたはリストア処理のあとにスイッチバックが行われる場合

クラスタ 1 からクラスタ 2 へのスイッチオーバーが実行され、クラスタ 2 でダンプバックアップまたはリストア処理が開始されます。クラスタ 2 にあるボリュームがダンプ処理によってバックアップまたはリストアされます。この時点で、クラスタ 2 からクラスタ 1 へのスイッチバックが開始されると、次のような結果になります。

* の値の場合 `override-vetoes` オプションはです `false`をクリックすると、スイッチバックがキャンセルされ、バックアップまたはリストア処理が続行されます。
* オプションの値がの場合 `true`を選択すると、バックアップ処理またはリストア処理が中止され、スイッチバックが続行されます。




== スイッチオーバーまたはスイッチバックの実行中にダンプバックアップまたはリストア処理が開始された場合

クラスタ 1 からクラスタ 2 へのスイッチオーバーの実行中に、クラスタ 1 でダンプバックアップまたはリストア処理が開始されると、そのバックアップまたはリストア処理は失敗し、スイッチオーバーが続行されます。

クラスタ 2 からクラスタ 1 へのスイッチバックの実行中に、クラスタ 2 でダンプバックアップまたはリストア処理が開始されると、そのバックアップまたはリストア処理は失敗し、スイッチバックが続行されます。
