---
permalink: tape-backup/environment-variables-concept.html 
sidebar: sidebar 
keywords: environment, variable, information, backup, restore, operation, ndmp, application, storage, system 
summary: 環境変数は、 NDMP 対応のバックアップアプリケーションとストレージシステムの間でバックアップまたはリストア処理に関する情報をやり取りするために使用されます。 
---
= ONTAP NDMP でサポートされている環境変数について学習します
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
環境変数は、 NDMP 対応のバックアップアプリケーションとストレージシステムの間でバックアップまたはリストア処理に関する情報をやり取りするために使用されます。

たとえば、バックアップアプリケーションのバックアップをユーザが指定した場合、 `/vserver1/vol1/dir1`バックアップアプリケーションはFILESYSTEM環境変数をに設定し `/vserver1/vol1/dir1`ます。同様に、ユーザがバックアップをレベル1バックアップにするように指定した場合、バックアップアプリケーションはLEVEL環境変数を1に設定します。

[NOTE]
====
環境変数の設定と確認は、通常、バックアップ管理者に対して透過的に行われます。つまり、バックアップアプリケーションによって環境変数が自動的に設定されます。

====
バックアップ管理者が環境変数を指定することはほとんどありませんが、環境変数の値をバックアップアプリケーションで設定した値から変更して、機能上またはパフォーマンス上の問題の特性を特定したり、対処したりすることができます。たとえば、管理者がファイル履歴の生成を一時的に無効にして、バックアップアプリケーションによるファイル履歴情報の処理がパフォーマンスの問題や機能上の問題の原因になっているかどうかを確認できます。

多くのバックアップアプリケーションには、環境変数を上書きまたは変更したり、追加の環境変数を指定したりする手段が用意されています。詳細については、バックアップアプリケーションのマニュアルを参照してください。



== ONTAPでサポートされる環境変数

ONTAP は、関連付けられたデフォルト値を持つ環境変数をサポートしています。ただし、これらのデフォルト値は手動で変更できます。

バックアップアプリケーションによって設定された値を手動で変更すると、アプリケーションが想定外の動作をする可能性があります。これは、バックアップ アプリケーションの想定とは異なるバックアップまたはリストア処理が行われるためです。ただし、状況によっては、適切な変更によって問題の特定や回避に役立つ場合があります。

次の表に、動作がダンプとSMTapeで共通で、ダンプとSMTapeでのみサポートされる環境変数を示します。また、 ONTAP でサポートされる環境変数が使用された場合の動作の説明も記載されています。

[NOTE]
====
ほとんどの場合、値を持つ変数 `Y`も受け入れ、 `N`受け入れ `T`ます `F`。

====


== ダンプとSMTapeでサポートされる環境変数

|===
| 環境変数 | 有効な値 | デフォルト | 説明 


 a| 
デバッグ
 a| 
`Y`または `N`
 a| 
`N`
 a| 
デバッグ情報を出力するように指定します。



 a| 
ファイルシステム
 a| 
`string`
 a| 
`none`
 a| 
バックアップされるデータのルートのパス名を指定します。



 a| 
NDMP_VERSION
 a| 
`return_only`
 a| 
`none`
 a| 
NDMP_VERSION 変数は変更しないでください。NDMP_VERSION 変数はバックアップ処理によって作成され、 NDMP のバージョンを返します。

ONTAP は、内部使用のため、および情報としてバックアップアプリケーションに渡すために、バックアップ時に NDMP_VERSION 変数を設定します。NDMP セッションの NDMP バージョンは、この変数では設定されません。



 a| 
pathname_separator
 a| 
`return_value`
 a| 
`none`
 a| 
パス名の区切り文字を指定します。

この文字は、バックアップ対象のファイルシステムによって異なります。ONTAP の場合、文字 "`/`" はこの変数に割り当てられます。NDMP サーバでは、この変数を設定してからテープバックアップ処理を開始します。



 a| 
タイプ
 a| 
`dump`または `smtape`
 a| 
`dump`
 a| 
テープバックアップおよびリストア処理の実行がサポートされているバックアップのタイプを指定します。



 a| 
詳細
 a| 
`Y`または `N`
 a| 
`N`
 a| 
テープバックアップまたはリストア処理の実行中のログメッセージの数を増やします。

|===


== ダンプ用にサポートされる環境変数

|===
| 環境変数 | 有効な値 | デフォルト | 説明 


 a| 
acl_start
 a| 
`return_only`
 a| 
`none`
 a| 
ACL_START 変数は、バックアップ処理によって作成され、直接アクセスリストアまたは再開可能 NDMP バックアップ処理で使用されるオフセット値を示します。

オフセット値は、ダンプファイル内で ACL データ（ Pass V ）が始まるバイトオフセットであり、バックアップ終了時に返されます。直接アクセスリストア処理でバックアップデータを正しくリストアするには、開始時に ACL_START 値がリストア処理に渡されなければなりません。NDMP 再開可能バックアップ処理では、 ACL_START 値を使用して、バックアップストリームで再開できない部分の開始位置をバックアップアプリケーションに伝えます。



 a| 
BASE_DATE
 a| 
`0` `-1`、、または `DUMP_DATE`値
 a| 
`-1`
 a| 
増分バックアップの開始日を指定します。

に設定する `-1`と、BASE_DATEインクリメンタル指定子は無効になります。レベル0バックアップでに設定すると `0`、増分バックアップが有効になります。最初のバックアップ後、前回の増分バックアップの DUMP_DATE 変数の値が BASE_DATE 変数に代入されます。

これらの変数は、 LEVEL または UPDATE に基づく増分バックアップに代わるものです。



 a| 
直販
 a| 
`Y`または `N`
 a| 
`N`
 a| 
リストアの際に、テープ全体をスキャンするのではなく、ファイルデータがある場所まで直接早送りするように指定します。

直接アクセスリカバリを使用するには、バックアップアプリケーションが位置情報を提供する必要があります。この変数がに設定されている場合、 `Y`バックアップアプリケーションはファイル名またはディレクトリ名と位置情報を指定します。



 a| 
dmp_name
 a| 
`string`
 a| 
`none`
 a| 
複数サブツリーバックアップの名前を指定します。

この変数は、複数サブツリーバックアップに必須です。



 a| 
DUMP_DATE
 a| 
`return_value`
 a| 
`none`
 a| 
この変数を直接変更することはありません。BASE_DATE変数が以外の値に設定されている場合、バックアップによって作成され `-1`ます。

DUMP_DATE 変数は、ダンプソフトウェアによって計算された 32 ビットの時刻値の前に 32 ビットのレベル値を付けることによって生成されます。レベルは、 BASE_DATE 変数に最後に渡されたレベル値から増分されます。作成された値は、次回の増分バックアップの BASE_DATE 値として使用されます。



 a| 
ENHANCED_DAR_ENABLED 環境
 a| 
`Y`または `N`
 a| 
`N`
 a| 
拡張 DAR 機能が有効になっているかどうかを示します。拡張DAR機能は、ディレクトリDARおよびNTストリームを含むファイルのDARをサポートします。パフォーマンスが向上します。

リストア時に拡張 DAR 機能を使用できるのは、次の条件が満たされている場合のみです。

* ONTAP で拡張 DAR がサポートされている。
* バックアップ時にファイル履歴が有効である（ HIST=Y ）。
* この `ndmpd.offset_map.enable`オプションはに設定されてい `on`ます。
* リストア時にENHANCED_DAR_ENABLED変数がに設定されている `Y`。




 a| 
シヨカイ
 a| 
`pattern_string`
 a| 
`none`
 a| 
データのバックアップ時に除外するファイルまたはディレクトリを指定します。

除外リストは、ファイル名またはディレクトリ名をカンマで区切ったリストです。ファイルまたはディレクトリの名前がリスト内の名前の 1 つに一致した場合、バックアップから除外されます。

除外リストで名前を指定する際に適用されるルールは次のとおりです。

* 正確なファイル名またはディレクトリ名を使用する必要があります。
* ワイルドカード文字であるアスタリスク（ * ）は、文字列の最初または最後の文字にする必要があります。
+
使用できるアスタリスクの数は文字列ごとに 2 つです。

* ファイル名またはディレクトリ名のカンマの前にバックスラッシュを付ける必要があります。
* 除外リストに含めることができる名前は 32 個までです。


[NOTE]
====
NON_QUOTA_TREEを同時に設定した場合、バックアップから除外するように指定したファイルまたはディレクトリは除外されません `Y`。

====


 a| 
展開する
 a| 
`Y`、 `N`、または `E`
 a| 
`N`
 a| 
バックアップデータセットのサブツリーをリストアするように指定します。

バックアップアプリケーションでは、抽出するサブツリーの名前を指定します。指定されたファイルが、内容がバックアップされたディレクトリに一致する場合、ディレクトリは再帰的に抽出されます。

DARを使用せずにリストア時にファイル、ディレクトリ、またはqtreeの名前を変更するには、EXTRACT環境変数をに設定する必要があります `E`。



 a| 
extract_acl
 a| 
`Y`または `N`
 a| 
`Y`
 a| 
リストア処理でバックアップファイルの ACL がリストアされるように指定します。

デフォルトでは、 DAR （ DIRECT=Y ）を除いて、データをリストアするときに ACL がリストアされます。



 a| 
[-force]
 a| 
`Y`または `N`
 a| 
`N`
 a| 
デスティネーションボリュームで使用可能なボリュームスペースと inode をリストア処理で確認する必要があるかどうかを指定します。

この変数をに設定する `Y`と、デスティネーションパスで使用可能なボリュームスペースとinodeのチェックがリストア処理でスキップされます。

デスティネーションボリュームのボリュームスペースまたは inode が不足している場合は、デスティネーションボリュームで使用可能なボリュームスペースと inode で許容される量のデータがリストア処理によってリカバリされます。ボリュームスペースと inode を使用できない場合は、リストア処理が停止します。



 a| 
霧
 a| 
`Y`または `N`
 a| 
`N`
 a| 
ファイル履歴情報をバックアップアプリケーションに送信するように指定します。

ほとんどの市販のバックアップアプリケーションでは、HIST変数がに設定されてい `Y`ます。バックアップ処理の速度を上げる場合や、ファイル履歴の収集に関する問題のトラブルシューティングを行う場合は、この変数をに設定します `N`。

[NOTE]
====
バックアップアプリケーションでファイル履歴がサポートされていない場合は、HIST変数をに設定しないで `Y`ください。

====


 a| 
IGNORE_CTime
 a| 
`Y`または `N`
 a| 
`N`
 a| 
前回の増分バックアップ以降に変更されたのが ctime 値だけである場合は、ファイルを増分バックアップしないことを指定します。

ウィルススキャンソフトウェアなどの一部のアプリケーションは、ファイルやファイル属性が変更されていなくても、 inode 内のファイルの ctime 値を変更します。その結果、変更されていないファイルが増分バックアップによってバックアップされることがあります。この `IGNORE_CTIME`変数を指定する必要があるのは、ctime値が変更されたために増分バックアップに許容できない時間またはスペースが使用されている場合だけです。

[NOTE]
====
この `NDMP dump`コマンドは、デフォルトでに `false`設定され `IGNORE_CTIME`ます。に設定する `true`と、次のデータが失われる可能性があります。

. ボリュームレベルの増分でがtrueに設定されている `ndmpcopy`場合、 `IGNORE_CTIME`ファイルが削除され、ソースのqtree間で移動されます。
. ボリュームレベルの増分ダンプでがtrueに設定されている場合 `IGNORE_CTIME`、ファイルが削除され、増分リストア時にソースのqtree間で移動されます。


この問題を回避するには、 `IGNORE_CTIME`ボリュームレベルまたは `ndmpcopy`でをfalseに設定する必要があります `NDMP dumps`。

====


 a| 
IGNORE_qtrees
 a| 
`Y`または `N`
 a| 
`N`
 a| 
リストア処理でバックアップ qtree から qtree 情報をリストアしないことを指定します。



 a| 
「レベル」
 a| 
`0`-`31`
 a| 
`0`
 a| 
バックアップレベルを指定します。

レベル 0 では、データセット全体がコピーされます。0 より大きい値で指定された増分バックアップレベルでは、前回の増分バックアップ以降に新規作成または変更されたすべてのファイルがコピーされます。たとえば、レベル 1 では、レベル 0 バックアップ以降に新規または変更されたファイルがバックアップされ、レベル 2 ではレベル 1 バックアップ以降に新規または変更されたファイルがバックアップされます。



 a| 
リスト
 a| 
`Y`または `N`
 a| 
`N`
 a| 
データを実際にはリストアせずに、バックアップファイル名と inode 番号を一覧表示します。



 a| 
リスト qtree
 a| 
`Y`または `N`
 a| 
`N`
 a| 
データを実際にはリストアせずに、バックアップ qtree を一覧表示します。



 a| 
multi_subtree_names
 a| 
`string`
 a| 
`none`
 a| 
バックアップが複数のサブツリーであることを指定します。

複数のサブツリーは、改行で区切られた null で終わるサブツリー名のリストの文字列で指定されます。サブツリーは、共通のルートディレクトリを基準とした相対パス名で指定されます。このパス名は、リストの最後の要素として指定する必要があります。

この変数を使用する場合は、 DMP_NAME 変数も使用する必要があります。



 a| 
NDMP_Unicode_FH
 a| 
`Y`または `N`
 a| 
`N`
 a| 
ファイルの NFS 名のほかに Unicode 名もファイル履歴情報に含めるように指定します。

このオプションは、ほとんどのバックアップアプリケーションでは使用されないため、バックアップアプリケーションがこれらの追加のファイル名を受け取るように設計されている場合以外は設定しないでください。HIST 変数も設定する必要があります。



 a| 
no_ACLs
 a| 
`Y`または `N`
 a| 
`N`
 a| 
データのバックアップ時に ACL をコピーしないように指定します。



 a| 
NON_QUOTA_TREE
 a| 
`Y`または `N`
 a| 
`N`
 a| 
データのバックアップ時に qtree 内のファイルおよびディレクトリを無視するように指定します。

に設定する `Y`と、FILESYSTEM変数で指定されたデータセット内のqtree内の項目はバックアップされません。この変数は、 FILESYSTEM 変数でボリューム全体が指定された場合のみ有効になります。NON_QUOTA_TREE 変数は、レベル 0 バックアップでのみ機能し、 MULTI_SUBTREE_NAMES 変数が指定された場合は機能しません。

[NOTE]
====
NON_QUOTA_TREEを同時に設定した場合、バックアップから除外するように指定したファイルまたはディレクトリは除外されません `Y`。

====


 a| 
NOWRITE
 a| 
`Y`または `N`
 a| 
`N`
 a| 
リストア処理でデータをディスクに書き込まないように指定します。

この変数はデバッグに使用されます。



 a| 
再帰的
 a| 
`Y`または `N`
 a| 
`Y`
 a| 
DAR リストア中にディレクトリエントリが拡張されるように指定します。

DIRECTおよびENHANCED_DAR_ENABLED環境変数も有効（に設定）する必要があります `Y`。RECURSIVE変数が無効になっている（に設定されている）場合は `N`、ディレクトリの内容ではなく、元のソースパス内のすべてのディレクトリの権限とACLのみがテープからリストアされます。RECURSIVE変数がに設定されている場合、またはRECOVER_FULL_PATHS変数がに設定されて `Y`いる場合、 `N`リカバリパスは元のパスで終了する必要があります。

[NOTE]
====
RECURSIVE 変数が無効で、複数のリカバリパスがある場合には、すべてのリカバリパスを最長のリカバリパス内に含める必要があります。それ以外の場合は、エラーメッセージが表示されます。

====
たとえば、すべてのリカバリパスがに含まれているため、次のリカバリパスは有効 `foo/dir1/deepdir/myfile`です。

* `/foo`
* `/foo/dir`
* `/foo/dir1/deepdir`
* `/foo/dir1/deepdir/myfile`


次のリカバリパスは無効です。

* `/foo`
* `/foo/dir`
* `/foo/dir1/myfile`
* `/foo/dir2`
* `/foo/dir2/myfile`




 a| 
RECOVER_FULL_paths
 a| 
`Y`または `N`
 a| 
`N`
 a| 
フルリカバリパスの権限および ACL が、 DAR のあとでリストアされるように指定します。

DIRECTおよびENHANCED_DAR_ENABLEDも有効（に設定）する必要があります `Y`。recover_full_pathsがに設定されている場合、 `Y`リカバリパスは元のパスで終了する必要があります。デスティネーションボリュームにすでにディレクトリが存在する場合は、権限および ACL はテープからリストアされません。



 a| 
更新
 a| 
`Y`または `N`
 a| 
`Y`
 a| 
レベルベースの増分バックアップを有効にするために、メタデータ情報を更新します。

|===


== SMTape 用にサポートされる環境変数

|===
| 環境変数 | 有効な値 | デフォルト | 説明 


 a| 
BASE_DATE
 a| 
`DUMP_DATE`
 a| 
`-1`
 a| 
増分バックアップの開始日を指定します。

 `BASE_DATE`は、参照スナップショット識別子の文字列表現です。SMTapeでは、文字列を使用して `BASE_DATE`参照Snapshotを特定します。

 `BASE_DATE`は、ベースラインバックアップには必要ありません。増分バックアップの場合は、前回のベースラインバックアップまたは増分バックアップの変数の値が `DUMP_DATE`変数に代入され `BASE_DATE`ます。

バックアップアプリケーションは、前回のSMTapeのベースラインバックアップまたは増分バックアップの値を割り当て `DUMP_DATE`ます。



 a| 
DUMP_DATE
 a| 
`return_value`
 a| 
`none`
 a| 
SMTapeバックアップの終了時に、DUMP_DATEには、そのバックアップに使用されるSnapshotを識別する文字列識別子が含まれます。このスナップショットは、次回の増分バックアップの参照スナップショットとして使用できます。

結果の DUMP_DATE の値が、次回の増分バックアップの BASE_DATE 値として使用されます。



 a| 
smtape _backup_set_ID
 a| 
`string`
 a| 
`none`
 a| 
ベースラインバックアップに関連付けられた増分バックアップのシーケンスを識別します。

バックアップセット ID は、ベースラインバックアップで生成される 128 ビットの一意の ID です。バックアップアプリケーションは、増分バックアップ時にこのIDを変数に入力として割り当て `SMTAPE_BACKUP_SET_ID`ます。



 a| 
smtape snapshot _name
 a| 
ボリューム内の有効なSnapshot
 a| 
`Invalid`
 a| 
SMTAPE_SNAPSHOT_NAME変数をSnapshotに設定すると、そのSnapshotとその古いSnapshotがテープにバックアップされます。

増分バックアップの場合、この変数は増分スナップショットを指定します。BASE_DATE変数は、ベースラインSnapshotを指定します。



 a| 
smtape delete _snapshot
 a| 
`Y`または `N`
 a| 
`N`
 a| 
SMTAPE_DELETE_SNAPSHOT変数がに設定されている場合は、バックアップ処理の完了後にSMTapeで自動的に作成されたSnapshotがSMTape `Y`によって削除されます。ただし、バックアップアプリケーションで作成されたSnapshotは削除されません。



 a| 
smtape break _mirror
 a| 
`Y`または `N`
 a| 
`N`
 a| 
SMTAPE_BREAK_MIRROR変数をに設定する `Y`と、リストアが成功すると、タイプがのボリュームが `DP`ボリュームに変更され `RW`ます。

|===