---
permalink: tape-backup/format-tape-config-file-concept.html 
sidebar: sidebar 
keywords: format, tape, configuration, file, vendor, id, product, compression, type, drive 
summary: テープ構成ファイルの形式は、テープドライブのベンダーID、製品ID、圧縮形式の詳細などのフィールドで構成されています。このファイルには、テープドライブの自動ロード機能を有効にしたり、テープドライブのコマンドタイムアウト値を変更したりするためのオプションのフィールドも含まれています。 
---
= ONTAPテープ構成ファイルの形式
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
テープ構成ファイルの形式は、テープドライブのベンダーID、製品ID、圧縮形式の詳細などのフィールドで構成されています。このファイルには、テープドライブの自動ロード機能を有効にしたり、テープドライブのコマンドタイムアウト値を変更したりするためのオプションのフィールドも含まれています。

次の表に、テープ構成ファイルの形式を示します。

|===
| 項目 | サイズ | 説明 


 a| 
`vendor_id`（文字列）。
 a| 
最大8バイト
 a| 
コマンドで表示されるベンダーID `SCSI Inquiry`。



 a| 
`product_id`（文字列）。
 a| 
最大16バイト
 a| 
コマンドで報告される製品ID `SCSI Inquiry`。



 a| 
`id_match_size`（数値）
 a| 
 a| 
識別されるテープドライブの検出に使用される製品IDのバイト数。Inquiryデータの製品IDの最初の文字から始まります。



 a| 
`vendor_pretty`（文字列）。
 a| 
最大16バイト
 a| 
このパラメータを使用する場合は、コマンドによって返される文字列を指定します `storage tape show -device-names`。値を指定しないと、INQ_VENDOR_IDと表示されます。



 a| 
`product_pretty`（文字列）。
 a| 
最大16バイト
 a| 
このパラメータを使用する場合は、コマンドによって返される文字列を指定します `storage tape show -device-names`。値を指定しないと、INQ_PRODUCT_IDと表示されます。

|===
[NOTE]
====
 `vendor_pretty`フィールドと `product_pretty`フィールドはオプションですが、いずれかのフィールドに値が設定されている場合は、もう一方のフィールドにも値が設定されている必要があります。

====
次の表に、、 `m`、、 `h`などのさまざまな圧縮形式の説明、密度コード、および圧縮アルゴリズムを示し `l` `a`ます。

|===
| 項目 | サイズ | 説明 


 a| 
`{l | m | h | a}_description=(string)`
 a| 
最大24バイト
 a| 
ノードシェルコマンドに対して出力される文字列。 `sysconfig -t`特定の密度設定の特性を示します。



 a| 
`{l | m | h | a}_density=(hex codes)`
 a| 
 a| 
l、m、h、またはaの目的の密度コードに対応するSCSIモードページブロック記述子で設定される密度コード。



 a| 
`{l | m | h | a}_algorithm=(hex codes)`
 a| 
 a| 
密度コードと目的の密度特性に対応する、SCSI圧縮モードページで設定する圧縮アルゴリズム。

|===
次の表に、テープ構成ファイルで使用できるオプションのフィールドを示します。

|===
| フィールド | 説明 


 a| 
`autoload=(Boolean yes/no)`
 a| 
テープドライブに自動ロード機能がある場合は、このフィールドがに設定され `yes`ます。つまり、テープカートリッジを挿入すると、（start/stop unit）コマンドを実行しなくても、テープドライブの準備が整います。 `SCSI load`このフィールドのデフォルトはです `no`。



 a| 
`cmd_timeout_0x`
 a| 
個々のタイムアウト値。このフィールドは、テープドライバでデフォルトとして使用されているタイムアウト値とは異なるタイムアウト値を指定する場合にのみ使用する必要があります。このサンプルファイルには、テープドライブで使用されるデフォルトのSCSIコマンドタイムアウト値が記載されています。タイムアウト値は、分（m）、秒（s）、またはミリ秒（ms）で指定できます。

[NOTE]
====
このフィールドは変更しないでください。

====
|===
テープ構成ファイルはNetAppサポートサイトからダウンロードして表示できます。

.テープ構成ファイル形式の例
HP LTO5 Ultriumテープドライブのテープ構成ファイルの形式は次のとおりです。

`vendor_id`="HP"

`product_id`="Ultrium 5-SCSI"

`id_match_size`= 9

`vendor_pretty`="Hewlett-Packard"

`product_pretty`="LTO-5"

`l_description`="LTO-3（ro）/ 4 4 / 800GB "

`l_density`= 0x00

`l_algorithm`= 0x00

`m_description`="LTO-3（ro）/ 4 8 / 1600GB CMP "

`m_density`= 0x00

`m_algorithm`= 0x01

`h_description`="LTO-5 1600GB"

`h_density`= 0x58

`h_algorithm`= 0x00

`a_description`="LTO-5 3200GB CMP"

`a_density`= 0x58

`a_algorithm`= 0x01

`autoload`="はい"

.関連情報
* https://mysupport.netapp.com/site/tools/tool-eula/5f4d322319c1ab1cf34fd063["ネットアップのツール：テープデバイス構成ファイル"^]
* link:https://docs.netapp.com/us-en/ontap-cli/storage-tape-show.html["ストレージテープショー"^]

