---
permalink: tape-backup/increment-chains-concept.html 
sidebar: sidebar 
keywords: increment, chain, backups, path, restore 
summary: 増分チェーンとは、同じパスの一連の増分バックアップです。任意のレベルのバックアップをいつでも指定できるため、バックアップとリストアを効率的に実行するには、増分チェーンについて理解しておく必要があります。31レベルの増分バックアップ処理を実行できます。 
---
= 増分チェーンとONTAP NDMPについて学ぶ
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
増分チェーンとは、同じパスの一連の増分バックアップです。任意のレベルのバックアップをいつでも指定できるため、バックアップとリストアを効率的に実行するには、増分チェーンについて理解しておく必要があります。31レベルの増分バックアップ処理を実行できます。

漸増チェーンには次の2種類があります。

* 連続した増分チェーン。レベル0から始まり、後続のバックアップごとに1ずつ増加する一連の増分バックアップです。
* 連続しない増分チェーン。増分バックアップでは、レベルがスキップされるか、連続していないレベル（0、2、3、1、4、より一般的には0、1、1、0、1、0、1、2、1、2など）があります。


増分バックアップでは、よりレベルが低い最新のバックアップがベースとして使用されます。たとえば、バックアップレベル0、2、3、1、4のシーケンスでは、2つの増分チェーン（0、2、3および0、1、4）が提供されます。次の表に、増分バックアップのベースを示します。

|===
| バックアップ順序 | 増分レベル | 漸増チェーン | ベース | バックアップされるファイル 


 a| 
1
 a| 
0
 a| 
両方
 a| 
ストレージシステム上のファイル
 a| 
バックアップパスのすべてのファイル



 a| 
2
 a| 
2
 a| 
0、2、3
 a| 
Level-0バックアップ
 a| 
レベル0バックアップ以降に作成されたバックアップパスのファイル



 a| 
3
 a| 
3
 a| 
0、2、3
 a| 
レベル2バックアップ
 a| 
レベル2バックアップ以降に作成されたバックアップパスのファイル



 a| 
4
 a| 
1
 a| 
0、1、4
 a| 
レベル0バックアップ（レベル1バックアップよりも低い最新レベルであるため）
 a| 
レベル0バックアップ以降に作成されたバックアップパスのファイル（レベル2およびレベル3バックアップのファイルを含む）



 a| 
5
 a| 
4
 a| 
0、1、4
 a| 
レベル1バックアップ（レベル0、レベル2、またはレベル3のバックアップよりも下位レベルで最新であるため）
 a| 
レベル1バックアップ以降に作成されたファイル

|===