---
permalink: tape-backup/manage-svm-scoped-ndmp-mode-concept.html 
sidebar: sidebar 
keywords: manage, svm, scope, ndmp, flexvol, volumes, vserver, modify 
summary: NDMPオプションとコマンドを使用すると、SVM単位でNDMPを管理できます。vserver services ndmp modify コマンドを使用すると、 NDMP オプションを変更できます。SVMを対象としたNDMPモードでは、ユーザ認証がロールベースアクセス制御メカニズムと統合されます。 
---
= FlexVolボリュームのSVMを対象としたNDMPモードの管理ONTAPでの概要
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
NDMPオプションとコマンドを使用すると、SVM単位でNDMPを管理できます。NDMPオプションは、コマンドを使用して変更できます `vserver services ndmp modify`。SVMを対象としたNDMPモードでは、ユーザ認証がロールベースアクセス制御メカニズムと統合されます。

コマンドを使用して、許可するプロトコルまたは許可しないプロトコルのリストにNDMPを追加できます `vserver modify`。デフォルトでは、NDMPは許可されるプロトコルのリストに含まれています。許可しないプロトコルのリストにNDMPが追加されると、NDMPセッションを確立できません。

オプションを使用すると、NDMPデータ接続を確立するLIFタイプを制御できます `-preferred-interface-role`。NDMPデータ接続の確立時に、このオプションで指定したLIFタイプに属するIPアドレスがNDMPによって選択されます。IPアドレスがこれらのどのLIFタイプにも属していない場合は、NDMPデータ接続を確立できません。の詳細については `vserver services ndmp modify`、をlink:https://docs.netapp.com/us-en/ontap-cli/vserver-services-ndmp-modify.html["ONTAPコマンド リファレンス"^]参照してください。

.関連情報
xref:commands-manage-svm-scoped-ndmp-reference.adoc[SVMを対象としたNDMPモードの管理用コマンド]

xref:cluster-aware-backup-extension-concept.adoc[Cluster Aware Backup拡張の機能]

xref:svm-scoped-ndmp-mode-concept.adoc[SVMを対象としたNDMPモードとは]

link:../system-admin/index.html["システム管理"]
