---
permalink: tape-backup/manage-svm-scoped-ndmp-mode-concept.html 
sidebar: sidebar 
keywords: manage, svm, scope, ndmp, flexvol, volumes, vserver, modify 
summary: NDMP オプションとコマンドを使用して、 SVM 単位で NDMP を管理できます。vserver services ndmp modify コマンドを使用すると、 NDMP オプションを変更できます。SVM を対象とした NDMP モードでは、ユーザ認証がロールベースアクセス制御メカニズムに統合されます。 
---
= FlexVol ボリュームの SVM を対象とした NDMP モードの概要を管理します
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
NDMP オプションとコマンドを使用して、 SVM 単位で NDMP を管理できます。NDMPオプションは、を使用して変更できます `vserver services ndmp modify` コマンドを実行しますSVM を対象とした NDMP モードでは、ユーザ認証がロールベースアクセス制御メカニズムに統合されます。

を使用して、許可するプロトコルまたは許可しないプロトコルのリストにNDMPを追加できます `vserver modify` コマンドを実行しますデフォルトでは、 NDMP は許可するプロトコルのリストに含まれています。許可しないプロトコルのリストに NDMP が追加されると、 NDMP セッションを確立できません。

NDMPデータ接続を確立するLIFのタイプは、を使用して制御できます `-preferred-interface-role` オプションNDMP データ接続の確立時には、このオプションで指定した LIF タイプに属する IP アドレスが NDMP によって選択されます。IP アドレスがどの LIF タイプにも属していない場合は、 NDMP データ接続を確立できません。詳細については、を参照してください `-preferred-interface-role` オプションについては、マニュアルページを参照してください。

詳細については、を参照してください `vserver services ndmp modify` コマンドのマニュアルページを参照してください。

.関連情報
xref:commands-manage-svm-scoped-ndmp-reference.adoc[SVM を対象とした NDMP モードを管理するためのコマンド]

xref:cluster-aware-backup-extension-concept.adoc[Cluster Aware Backup 拡張の動作]

link:../concepts/index.html["ONTAP の概念"]

xref:svm-scoped-ndmp-mode-concept.adoc[SVM を対象とした NDMP モードとは]

link:../system-admin/index.html["システム管理"]
