---
permalink: tape-backup/ndmp-extensions-supported-reference.html 
sidebar: sidebar 
keywords: ndmp, extensions, supported, ontap, v4, protocols, core, modify, extension 
summary: NDMP v4 は、 NDMP v4 プロトコルの中核部分を変更することなく、 NDMP v4 プロトコルの機能拡張を可能にするメカニズムを備えています。ONTAP でサポートされる NDMP v4 の拡張機能を確認しておく必要があります。 
---
= ONTAPでサポートされるNDMPの拡張機能
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
NDMP v4 は、 NDMP v4 プロトコルの中核部分を変更することなく、 NDMP v4 プロトコルの機能拡張を可能にするメカニズムを備えています。ONTAP でサポートされる NDMP v4 の拡張機能を確認しておく必要があります。

ONTAP でサポートされる NDMP v4 の拡張機能は次のとおりです。

* クラスタ対応バックアップ（CAB）
+
[NOTE]
====
この拡張機能は、 SVM を対象とした NDMP モードでのみサポートされます。

====
* IPv6 のサポートのための Connection Address Extension （ CAE ）
* 拡張クラス 0x2050
+
この拡張機能は、再開可能なバックアップ処理と Snapshot Management Extension をサポートします。

+
[NOTE]
====
この `NDMP_SNAP_RECOVER`メッセージは'Snapshot Management Extensionsの一部であり'リカバリ・オペレーションを開始し'リカバリされたデータをローカル・スナップショットからローカル・ファイル・システムの場所に転送するために使用されますONTAP では、このメッセージをボリュームと通常のファイルのリカバリのみに使用できます。

この `NDMP_SNAP_DIR_LIST`メッセージを使用すると、ボリュームのSnapshotを参照できます。参照処理の実行中にノンストップオペレーションが行われた場合、バックアップアプリケーションで参照処理を再開する必要があります。

====
* NDMP 再開可能バックアップ拡張機能
+
NDMP の Restartable Backup Extension （ RBE ）機能を使用すると、障害発生前のデータストリームの既知のチェックポイントからバックアップを再開できます。


