---
permalink: tape-backup/ndmp-management-concept.html 
sidebar: sidebar 
keywords: understand, ndmp, flexvol, volume, network, data, management, protocol, storage, devices, systems, tape, library 
summary: Network Data Management Protocol （ NDMP ；ネットワークデータ管理プロトコル）は、ストレージシステムやテープライブラリなど、プライマリストレージデバイスとセカンダリストレージデバイスとの間で、バックアップやリカバリなどのデータ転送を制御するための標準化されたプロトコルです。 
---
= FlexVol ボリュームの NDMP について
:icons: font
:imagesdir: ../media/


[role="lead"]
Network Data Management Protocol （ NDMP ；ネットワークデータ管理プロトコル）は、ストレージシステムやテープライブラリなど、プライマリストレージデバイスとセカンダリストレージデバイスとの間で、バックアップやリカバリなどのデータ転送を制御するための標準化されたプロトコルです。

ストレージシステム上で NDMP のサポートを有効にすると、バックアップまたはリカバリ操作に使用する NDMP 対応のネットワーク接続型バックアップアプリケーション（ Data Management Applications_or_DMA_ とも呼ばれる）、データサーバ、およびテープサーバとの通信をストレージシステムが実行できるようになります。すべてのネットワーク通信は、 TCP / IP または TCP / IPv6 ネットワーク経由で行われます。NDMP は、テープドライブとメディアチェンジャの低レベルの制御も行います。

ノードを対象とした NDMP モードと Storage Virtual Machine （ SVM ）を対象とした NDMP モードのどちらでもテープによるバックアップとリストア処理を実行できます。

NDMP を使用する際の考慮事項、環境変数のリスト、およびサポートされている NDMP テープバックアップトポロジを把握しておく必要があります。拡張 DAR 機能を有効または無効にすることもできます。ONTAP でストレージシステムへの NDMP アクセス認証にサポートされている認証方式は、プレーンテキストとチャレンジの 2 つです。

xref:environment-variables-supported-concept.adoc[ONTAP でサポートされる環境変数]
