---
permalink: tape-backup/ndmp-concept.html 
sidebar: sidebar 
keywords: ncmp, considerations, using, service, storage, system 
summary: ストレージシステム上で NDMP サービスを開始する際の考慮事項について説明します。 
---
= NDMP 使用時の考慮事項
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
ストレージシステム上で NDMP サービスを開始する際の考慮事項について説明します。

* 接続されたテープドライブを使用して各ノードでサポートされるバックアップとリストアの同時実行数は、合計で最大 16 個です。
* NDMP サービスでは、 NDMP バックアップアプリケーションからの要求に応じてファイル履歴データを生成できます。
+
バックアップアプリケーションは、ファイル履歴を使用して、選択したデータのサブセットだけをバックアップイメージから最適にリカバリします。ファイル履歴の生成と処理は、ストレージシステムとバックアップアプリケーションの両方で時間がかかり、 CPU が占有されることがあります。

+
[NOTE]
====
SMTape では、ファイル履歴はサポートされていません。

====
+
バックアップ・イメージ全体がリカバリされる災害復旧用にデータ保護が設定されている場合は ' ファイル履歴の生成を無効にして ' バックアップ時間を短縮できますNDMP のファイル履歴の生成を無効にできるかどうかについては、バックアップアプリケーションのマニュアルを参照してください。

* すべての LIF タイプでは、 NDMP のファイアウォールポリシーがデフォルトで有効になっています。
* ノードを対象とした NDMP モードで FlexVol をバックアップするには、バックアップアプリケーションを使用して、ボリュームを所有するノードでバックアップを開始する必要があります。
+
ただし、ノードルートボリュームをバックアップすることはできません。

* ファイアウォールポリシーで許可されている場合は、任意の LIF から NDMP バックアップを実行できます。
+
データ LIF を使用する場合は、フェイルオーバーに設定されていない LIF を選択する必要があります。NDMP 処理中にデータ LIF がフェイルオーバーすると、 NDMP 処理は失敗するため、再実行する必要があります。

* ノードを対象とした NDMP モードおよび Storage Virtual Machine （ SVM ）を対象とした NDMP モードで CAB 拡張がサポートされていない場合、 NDMP データ接続では、 NDMP 制御接続と同じ LIF を使用します。
* LIF の移行中は、進行中のバックアップおよびリストア処理が中断されます。
+
LIF の移行が完了したら、バックアップとリストアの処理を開始する必要があります。

* NDMP バックアップ・パスの形式は '____vserver_name / volume_name / path_name です
+
`_path_name_` はオプションで ' ディレクトリ ' ファイル ' または Snapshot コピーのパスを指定します

* ダンプエンジンを使用して SnapMirror デスティネーションをテープにバックアップする場合は、ボリューム内のデータだけがバックアップされます。
+
ただし、 SMTape を使用して SnapMirror デスティネーションをテープにバックアップする場合は、メタデータもバックアップされます。SnapMirror 関係および関連するメタデータはテープにバックアップされません。そのため、リストア時には、そのボリュームのデータだけがリストアされますが、関連する SnapMirror 関係はリストアされません。



xref:cluster-aware-backup-extension-concept.adoc[Cluster Aware Backup 拡張の動作]

link:../concepts/index.html["ONTAP の概念"]

link:../system-admin/index.html["システム管理"]
