---
permalink: tape-backup/physical-path-names-concept.html 
sidebar: sidebar 
keywords: physical, path, names, ppn, numerical, address, tape, drive, electrical 
summary: PPN は、 ONTAP がテープドライブおよびテープライブラリに割り当てる数値アドレスです。 PPN は、テープドライブおよびテープライブラリが、ストレージシステム上のどの SCSI-2 / 3 アダプタまたはスイッチ（特定の場所）に接続されているかに基づいて割り当てられます。PPN は、「エレクトリカル名」とも呼ばれます。 
---
= 物理パス名とは
:icons: font
:imagesdir: ../media/


[role="lead"]
PPN は、 ONTAP がテープドライブおよびテープライブラリに割り当てる数値アドレスです。 PPN は、テープドライブおよびテープライブラリが、ストレージシステム上のどの SCSI-2 / 3 アダプタまたはスイッチ（特定の場所）に接続されているかに基づいて割り当てられます。PPN は、「エレクトリカル名」とも呼ばれます。

直接接続されたデバイスの PPN は、「 host_adapter 」という形式になります。「デバイス ID 」 LUN です

[NOTE]
====
LUN の値は、テープまたはメディア・チェンジャの LUN の値が 0 以外の場合にのみ表示されます。つまり、 LUN の値が 0 の場合、 PPN の「 lun 」の部分は表示されません。

====
たとえば、 PPN が 8.6 となっている場合、ホストアダプタ番号が 8 、デバイス ID が 6 、論理ユニット番号（ LUN ）が 0 であることを示します。

SAS テープデバイスも直接接続されたデバイスです。たとえば、 PPN が 5c.4 となっている場合、ストレージシステムでは、 SAS HBA がスロット 5 で接続されており、 SAS テープが SAS HBA のポート C に接続されており、デバイス ID が 4 であることを示します。

ファイバチャネルスイッチ接続デバイスの PPN は、「スイツチ： port_id 」の形式になります。「デバイス ID 」 LUN です

たとえば、 PPN が MY_SWITCH ： 5.3L2 となっている場合、スイッチ MY_SWITCH のポート 5 にテープドライブが接続されており、そのテープドライブのデバイス ID が 3 、 LUN が 2 であることを示します。

LUN はドライブで決定されます。ファイバチャネル、 SCSI テープドライブ / ライブラリ、およびディスクには PPN が使用されます。

テープドライブおよびライブラリの PPN が変更されるのは、スイッチ名を変更した場合、テープドライブまたはライブラリを移動したり再設定したりした場合のみです。リブート後も PPN は変更されません。たとえば、 MY_SWITCH ： 5.3L2 という名前のテープドライブを取り外して、デバイス ID および LUN が同じである新しいテープドライブをスイッチ MY_SWITCH のポート 5 に接続した場合、引き続き、 MY_SWITCH ： 5.3L2 という名前を使用して新しいテープドライブにアクセスできます。
