---
permalink: tape-backup/restart-dump-backup-concept.html 
sidebar: sidebar 
keywords: restart, dump, backup, internal, external, tape, write, errors, power, outages, accidental, user, interruptions, internal, inconsistency 
summary: ダンプ バックアップは、テープ書き込みエラー、停電、ユーザーによる偶発的な中断、ストレージ システムの内部不整合など、内部または外部のエラーにより完了しない場合があります。これらの理由のいずれかでバックアップが失敗した場合は、バックアップを再開できます。 
---
= ONTAPダンプバックアップを再開するタイミング
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
ダンプ バックアップは、テープ書き込みエラー、停電、ユーザーによる偶発的な中断、ストレージ システムの内部不整合など、内部または外部のエラーにより完了しない場合があります。これらの理由のいずれかでバックアップが失敗した場合は、バックアップを再開できます。

ストレージ システムのトラフィックが集中する時間帯を避けたり、テープ ドライブなどのストレージ システム上の他の限られたリソースの競合を避けたりするために、バックアップを中断して再開することができます。より緊急な復元（またはバックアップ）で同じテープ ドライブが必要な場合は、長時間のバックアップを中断して後で再開できます。再開可能なバックアップは、再起動後も保持されます。中止したテープへのバックアップを再開できるのは、以下の条件を満たす場合のみです：

* 中止されたバックアップはフェーズIVにあります。
* dumpコマンドによってロックされたすべての関連Snapshotが利用可能です。
* ファイル履歴を有効にする必要があります。


このようなダンプ操作が中止され、再開可能な状態のままになっている場合、関連するスナップショットはロックされます。これらのスナップショットは、バックアップ コンテキストが削除された後に解放されます。バックアップ コンテキストのリストは、 `vserver services ndmp restartable backup show`コマンドを使用して表示できます。

[listing]
----
cluster::> vserver services ndmpd restartable-backup show
Vserver     Context Identifier                   Is Cleanup Pending?
----------- ------------------------------------ -------------------
vserver1 330e6739-0179-11e6-a299-005056bb4bc9 false
vserver1 481025c1-0179-11e6-a299-005056bb4bc9 false
vserver2 5cf10132-0179-11e6-a299-005056bb4bc9 false
3 entries were displayed.

cluster::> vserver services ndmpd restartable-backup show -vserver vserver1 -context-id 330e6739-0179-11e6-a299-005056bb4bc9

                       Vserver: vserver1
            Context Identifier: 330e6739-0179-11e6-a299-005056bb4bc9
                   Volume Name: /vserver1/vol1
           Is Cleanup Pending?: false
            Backup Engine Type: dump
Is Snapshot Auto-created?: true
                     Dump Path: /vol/vol1
   Incremental Backup Level ID: 0
                     Dump Name: /vserver1/vol1
     Context Last Updated Time: 1460624875
               Has Offset Map?: true
                 Offset Verify: true
       Is Context Restartable?: true
              Is Context Busy?: false
                  Restart Pass: 4
              Status of Backup: 2
            Snapshot Name: snapshot_for_backup.1
          State of the Context: 7

cluster::>"
----