---
permalink: tape-backup/restart-dump-backup-concept.html 
sidebar: sidebar 
keywords: restart, dump, backup, internal, external, tape, write, errors, power, outages, accidental, user, interruptions, internal, inconsistency 
summary: テープ書き込みエラー、停電、ユーザによる誤った操作、ストレージシステム内部の不整合など、内外のさまざまなエラーが原因で、ダンプバックアップが完了しないことがあります。これらのいずれかの理由でバックアップに失敗した場合に、バックアップを再開できます。 
---
= ONTAPダンプバックアップを再開するタイミング
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
テープ書き込みエラー、停電、ユーザによる誤った操作、ストレージシステム内部の不整合など、内外のさまざまなエラーが原因で、ダンプバックアップが完了しないことがあります。これらのいずれかの理由でバックアップに失敗した場合に、バックアップを再開できます。

ストレージシステム上のトラフィックが大量に発生する時間を避けるため、またはテープドライブなどのストレージシステム上の限られたリソース間の競合を回避するために、バックアップを中断して再開することができます。より緊急性の高いリストア（またはバックアップ）で同じテープドライブが必要な場合は、長いバックアップを中断してあとで再開できます。再開可能なバックアップはリブート後も維持されます。中止されたテープへのバックアップは、次の条件に該当する場合にのみ再開できます。

* 中止されたバックアップがフェーズ 4 である
* dumpコマンドでロックされた、関連付けられているすべてのSnapshotを使用できます。
* ファイル履歴が有効になっている必要があります。


このようなダンプ処理が中止され、再開可能な状態のままになると、関連するSnapshotがロックされます。これらのスナップショットは、バックアップコンテキストが削除された後に解放されます。バックアップコンテキストのリストを表示するには、コマンドを使用し `vserver services ndmp restartable backup show`ます。

[listing]
----
cluster::> vserver services ndmpd restartable-backup show
Vserver     Context Identifier                   Is Cleanup Pending?
----------- ------------------------------------ -------------------
vserver1 330e6739-0179-11e6-a299-005056bb4bc9 false
vserver1 481025c1-0179-11e6-a299-005056bb4bc9 false
vserver2 5cf10132-0179-11e6-a299-005056bb4bc9 false
3 entries were displayed.

cluster::> vserver services ndmpd restartable-backup show -vserver vserver1 -context-id 330e6739-0179-11e6-a299-005056bb4bc9

                       Vserver: vserver1
            Context Identifier: 330e6739-0179-11e6-a299-005056bb4bc9
                   Volume Name: /vserver1/vol1
           Is Cleanup Pending?: false
            Backup Engine Type: dump
Is Snapshot Copy Auto-created?: true
                     Dump Path: /vol/vol1
   Incremental Backup Level ID: 0
                     Dump Name: /vserver1/vol1
     Context Last Updated Time: 1460624875
               Has Offset Map?: true
                 Offset Verify: true
       Is Context Restartable?: true
              Is Context Busy?: false
                  Restart Pass: 4
              Status of Backup: 2
            Snapshot Copy Name: snapshot_for_backup.1
          State of the Context: 7

cluster::>"
----