---
permalink: tape-backup/serial-numbers-concept.html 
sidebar: sidebar 
keywords: serial, numbers, sn, tape, drive, medium, changer, wwn 
summary: シリアル番号（ SN ）は、テープドライブやメディアチェンジャに割り当てられる一意の識別子です。ONTAP では、 WWN ではなく SN に基づいてエイリアスが生成されます。 
---
= シリアル番号とは
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
シリアル番号（ SN ）は、テープドライブやメディアチェンジャに割り当てられる一意の識別子です。ONTAP では、 WWN ではなく SN に基づいてエイリアスが生成されます。

SN はテープドライブやメディアチェンジャに割り当てられる一意の識別子なので、テープドライブやメディアチェンジャに接続するパスが複数あってもエイリアスは変わりません。これにより、ストレージシステムでは、テープライブラリの構成で同じテープドライブまたはメディアチェンジャを追跡できます。

テープドライブまたはメディアチェンジャの接続先のファイバチャネルスイッチの名前を変更しても、テープドライブまたはメディアチェンジャの SN は変わりません。ただし、テープライブラリでは、既存のテープドライブを新しいものに交換すると、 ONTAP によって新しいエイリアスが生成されます。これは、テープドライブの SN が変わるためです。また、既存のテープドライブをテープライブラリ内の新しいスロットに移動したり、テープドライブのLUNを再マッピングしたりすると、ONTAPはそのテープドライブ用の新しいエイリアスを生成します。

[NOTE]
====
新しく生成されたエイリアスを使用してバックアップアプリケーションを更新する必要があります。

====
テープデバイスのSNは、次の形式を使用します。 `SN[xxxxxxxxxx]L[X]`

`x`は英数字です。LはテープデバイスのLUNです。``X``LUNが0の場合、文字列のL``X``部分は表示されません。

各 SN は最大 32 文字で構成されます。 SN の形式では大文字と小文字は区別されません。
