---
permalink: tape-backup/smtape-engine-concept.html 
sidebar: sidebar 
keywords: smtape, disaster, recovery, solution, blocks, data, tape, qtree, subtree, volume, license, baseline, differential, incremental, backup 
summary: SMTapeは、データのブロックをテープにバックアップするONTAPのディザスタリカバリソリューションです。SMTapeを使用して、ボリュームのバックアップをテープに対して実行できます。ただし、qtreeレベルまたはサブツリーレベルでのバックアップは実行できません。SMTapeは、ベースライン バックアップ、差分バックアップ、増分バックアップをサポートしています。SMTapeにはライセンスは必要ありません。 
---
= FlexVolボリューム用のONTAP SMTapeエンジンについて
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
SMTapeは、データのブロックをテープにバックアップするONTAPのディザスタリカバリソリューションです。SMTapeを使用して、ボリュームのバックアップをテープに対して実行できます。ただし、qtreeレベルまたはサブツリーレベルでのバックアップは実行できません。SMTapeは、ベースライン バックアップ、差分バックアップ、増分バックアップをサポートしています。SMTapeにはライセンスは必要ありません。

NDMP準拠のバックアップ アプリケーションを使用して、SMTapeバックアップおよびリストア処理を実行できます。SMTapeを選択すると、Storage Virtual Machine（SVM）を対象とするNDMPモードでのみバックアップおよびリストア処理を実行できます。

[NOTE]
====
SMTapeバックアップまたはリストア セッションの実行中は、リバート プロセスはサポートされません。セッションが終了するまで待つか、NDMPセッションを中止する必要があります。

====
SMTapeを使用すると、255個のSnapshotをバックアップできます。それ以降のベースライン、増分、または差分バックアップでは、古いバックアップ済みSnapshotを削除する必要があります。

ベースライン復元を実行する前に、データの復元先となるボリュームが `DP`タイプであり、制限状態になっている必要があります。復元が成功すると、このボリュームは自動的にオンラインになります。その後は、バックアップを実行した順序で、このボリュームに対して増分復元または差分バックアップを実行できます。
