---
permalink: tape-backup/smtape-backup-restore-operations-mcc-config-concept.html 
sidebar: sidebar 
keywords: smtape, backup, restore, operation, metrocluster, configuration, switchover, switchback 
summary: MetroCluster 構成で SMTape バックアップおよびリストア処理を実行するには、スイッチオーバー処理またはスイッチバック処理の実行時に SMTape 処理が受ける影響について理解しておく必要があります。 
---
= MetroCluster構成でSMTapeバックアップおよびリストア処理が受ける影響
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
MetroCluster 構成で SMTape バックアップおよびリストア処理を実行するには、スイッチオーバー処理またはスイッチバック処理の実行時に SMTape 処理が受ける影響について理解しておく必要があります。



== SMTape バックアップまたはリストア処理のあとにスイッチオーバーが行われる場合

クラスタ 1 とクラスタ 2 の 2 つのクラスタがあるとします。クラスタ 1 で SMTape バックアップまたはリストア処理を実行しているときに、クラスタ 1 からクラスタ 2 へのスイッチオーバーが開始されると、次のような結果になります。

* このオプションの値がに設定されて `false`いる場合 `–override-vetoes`は、スイッチオーバープロセスが中止され、バックアップまたはリストア処理が続行されます。
* このオプションの値がに設定されている場合 `true`は、SMTapeバックアップまたはリストア処理が中止され、スイッチオーバープロセスが続行されます。




== SMTape バックアップまたはリストア処理のあとにスイッチバックが行われる場合

クラスタ 1 からクラスタ 2 へのスイッチオーバーが実行され、クラスタ 2 で SMTape バックアップまたはリストア処理が開始されます。クラスタ 2 にあるボリュームが SMTape 処理によってバックアップまたはリストアされます。この時点で、クラスタ 2 からクラスタ 1 へのスイッチバックが開始されると、次のような結果になります。

* このオプションの値がに設定されて `false`いる場合は `–override-vetoes`、スイッチバックプロセスが中止され、バックアップまたはリストア処理が続行されます。
* このオプションの値がの場合は `true`、バックアップまたはリストア処理が中止され、スイッチバックプロセスが続行されます。




== スイッチオーバーまたはスイッチバックの実行中に SMTape バックアップまたはリストア処理が開始された場合

クラスタ 1 からクラスタ 2 へのスイッチオーバープロセスの実行中に、クラスタ 1 で SMTape バックアップまたはリストア処理が開始されると、そのバックアップまたはリストア処理は失敗し、スイッチオーバーが続行されます。

クラスタ 2 からクラスタ 1 へのスイッチバックプロセスの実行中に、クラスタ 2 で SMTape バックアップまたはリストア処理が開始されると、そのバックアップまたはリストア処理は失敗し、スイッチバックが続行されます。
