---
permalink: tape-backup/smtape-backup-restore-operations-mcc-config-concept.html 
sidebar: sidebar 
keywords: smtape, backup, restore, operation, metrocluster, configuration, switchover, switchback 
summary: MetroCluster構成でSMTapeバックアップおよびリストア処理を実行する前に、スイッチオーバーまたはスイッチバック処理が発生したときにSMTape処理がどのように影響を受けるかを理解しておく必要があります。 
---
= ONTAP MetroCluster構成におけるSMTapeバックアップおよびリストア操作への影響
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
MetroCluster構成でSMTapeバックアップおよびリストア処理を実行する前に、スイッチオーバーまたはスイッチバック処理が発生したときにSMTape処理がどのように影響を受けるかを理解しておく必要があります。



== SMTapeバックアップまたはリストア処理後のスイッチオーバー

クラスタ1とクラスタ2という2つのクラスタがあるとします。クラスタ1でのSMTapeバックアップまたは復元操作中に、クラスタ1からクラスタ2へのスイッチオーバーが開始されると、次の処理が実行されます：

*  `–override-vetoes`オプションの値が `false`の場合、スイッチオーバー プロセスは中止され、バックアップまたは復元操作は続行されます。
* オプションの値が `true`の場合、SMTapeバックアップまたはリストア処理は中止され、スイッチオーバー プロセスが続行されます。




== SMTapeバックアップまたはリストア処理後のスイッチバック

クラスタ 1 からクラスタ 2 へのスイッチオーバーが実行され、クラスタ 2 で SMTape バックアップまたは復元操作が開始されます。SMTape 操作は、クラスタ 2 にあるボリュームをバックアップまたは復元します。この時点で、クラスタ 2 からクラスタ 1 へのスイッチバックが開始されると、次の処理が行われます：

*  `–override-vetoes`オプションの値が `false`の場合、スイッチバック プロセスは中止され、バックアップまたは復元操作は続行されます。
* オプションの値が `true`の場合、バックアップまたは復元操作は中止され、スイッチバック プロセスが続行されます。




== スイッチオーバーまたはスイッチバック中に開始されたSMTapeバックアップまたはリストア操作

クラスタ 1 からクラスタ 2 へのスイッチオーバー プロセス中に、クラスタ 1 で SMTape バックアップまたはリストア処理が開始されると、バックアップまたはリストア処理は失敗し、スイッチオーバーは続行されます。

クラスタ 2 からクラスタ 1 へのスイッチバック プロセス中に、クラスタ 2 から SMTape バックアップまたはリストア処理が開始されると、バックアップまたはリストア処理は失敗し、スイッチバックが続行されます。
