---
permalink: tape-backup/user-authentication-svm-scoped-ndmp-mode-concept.html 
sidebar: sidebar 
keywords: user, authentication, svm, ndmp, node, vsadmin, backup, role, storage, virutal, machine, user 
summary: Storage Virtual Machine（SVM）を対象としたNDMPモードでは、NDMPユーザ認証がロールベースアクセス制御と統合されます。SVM のコンテキストでは、 NDMP ユーザのロールは「 vsadmin 」または「 vsadmin-backup 」である必要があります。クラスタのコンテキストでは、 NDMP ユーザには「 admin 」または「 backup 」のいずれかのロールが必要です。 
---
= SVM スコープの NDMP モードでのONTAPユーザー認証
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Storage Virtual Machine（SVM）を対象としたNDMPモードでは、NDMPユーザ認証がロールベースアクセス制御と統合されます。SVM のコンテキストでは、 NDMP ユーザには「 vsadmin 」または「 vsadmin-backup 」のいずれかのロールが必要です。クラスタのコンテキストでは 'admin' または backup のいずれかのロールが NDMP ユーザーに割り当てられている必要があります

これらの事前定義されたロール以外に ' カスタム・ロールに関連づけられたユーザー・アカウントを NDMP 認証に使用することもできますただし ' カスタム・ロールのコマンド・ディレクトリには vserver services ndmp フォルダがあり ' フォルダのアクセス・レベルが none でない場合に限られますこのモードでは、特定のユーザアカウント用のNDMPパスワードを生成する必要があります。このパスワードは、ロールベースアクセス制御を使用して作成されます。adminロールまたはbackupロールのクラスタユーザは、ノード管理LIF、クラスタ管理LIF、またはクラスタ間LIFにアクセスできます。vsadmin-backupロールまたはvsadminロールのユーザは、そのSVMのデータLIFにのみアクセスできます。そのため、ユーザのロールによって、バックアップおよびリストア処理に使用できるボリュームとテープデバイスが異なります。

このモードでは、NISユーザとLDAPユーザのユーザ認証もサポートされます。そのため、NISユーザとLDAPユーザは、共通のユーザIDとパスワードを使用して複数のSVMにアクセスできます。ただし、NDMP認証ではActive Directoryユーザはサポートされません。

このモードでは、ユーザ・アカウントは SSH アプリケーションと「ユーザ・パスワード」認証方式に関連付けられている必要があります。

.関連情報
xref:commands-manage-svm-scoped-ndmp-reference.adoc[SVMを対象としたNDMPモードの管理用コマンド]

link:../system-admin/index.html["システム管理"]
