---
permalink: software_setup/index.html 
sidebar: sidebar 
keywords: ontap, software, setup, deciding, decide, if, whether, use, cli, cluster, System Manager, IPv6, HA, root volumes, FlexArray 
summary: ソフトウェアのセットアップ 
---
= ONTAPクラスタセットアップの開始
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
System ManagerまたはONTAPコマンドラインインターフェイス（CLI）を使用して、新しいONTAPクラスタをセットアップできます。作業を開始する前に、クラスタ管理インターフェイスのポートやIPアドレスなど、クラスタセットアップを完了するために必要な情報を収集しておく必要があります。

.タスクの内容
この手順は、FAS、AFF、および現在のASAシステムに適用されます。ASA R2システム（ASA A1K、ASA A70、またはASA A90）がある場合は、に従ってlink:https://docs.netapp.com/us-en/asa-r2/install-setup/initialize-ontap-cluster.html["以下の手順を実行します"^]ONTAPクラスタをセットアップします。ASA R2システムは、SANのみのお客様に特化したシンプルなONTAPエクスペリエンスを提供します。

NetAppでは、を推奨していlink:../task_configure_ontap.html["System Managerを使用して新しいクラスタをセットアップする"]ます。System Managerでは、ノード管理IPアドレスの割り当て、クラスタの初期化、ローカル階層の作成、プロトコルの設定、初期ストレージのプロビジョニングなど、クラスタのセットアップと設定のワークフローをシンプルかつ簡単に実行できます。

これはlink:task_create_the_cluster_on_the_first_node.html["ONTAP CLIを使用したクラスタのセットアップ"]、MetroCluster構成でONTAP 9 .7以前を実行している場合にのみ必要です。

ONTAP 9.13.1以降では、AFF A800およびFAS8700プラットフォームで、IPv6のみのネットワーク環境でONTAP CLIを使用して新しいクラスタを作成および設定することもできます。.13.0以前またはONTAP 9 .13.1以降のその他のプラットフォームでIPv6を使用する必要がある場合は、ONTAP 9 Managerを使用してIPv4以降を使用して新しいクラスタを作成できます。link:convert-ipv4-to-ipv6-task.html["IPv6に変換します"]



== クラスタセットアップに必要なもの

クラスタのセットアップでは、各ノードのセットアップを設定するために必要な情報を収集し、最初のノードにクラスタを作成して、残りのノードをクラスタに追加します。

まずは、クラスタセットアップワークシートに関連するすべての情報を収集してください。

クラスタセットアップワークシートを使用すると、クラスタセットアッププロセスで必要となる値を記録できます。デフォルト値が指定されている場合は、その値を使用するか、独自の値を入力できます。



=== システムテフオルト

システムのデフォルトは、プライベートクラスタネットワークのデフォルト値です。これらのデフォルト値を使用することを推奨します。ただし、これらの値が要件を満たしていない場合は、テーブルを使用して独自の値を記録できます。


NOTE: ネットワークスイッチを使用するように構成されたクラスタでは、各クラスタスイッチで9000 MTUサイズを使用する必要があります。

[cols="2*"]
|===
| 情報の種類 | 自分の価値観 


| プライベートクラスタネットワークのポート |  


| クラスタネットワークのネットマスク |  


| クラスタインターフェイスの IP アドレス（各ノードの各クラスタネットワークポート用）：各ノードの IP アドレスは同じサブネット上にある必要があります。 |  
|===


=== クラスタ情報

[cols="2*"]
|===
| 情報の種類 | 自分の価値観 


| クラスタ名の 1 文字目はアルファベットにする必要があります。最大文字数は 44 文字です。名前には次の特殊文字を使用できます。
`.` `-` `_` |  
|===


=== 機能のライセンスキー

初回購入のソフトウェアまたはアドオンソフトウェアのライセンスキーは、NetApp Support Siteの「 * My Support * > * Software Licenses 」にあります。

[cols="2*"]
|===
| 情報の種類 | 自分の価値観 


| 機能のライセンスキー |  
|===


=== 管理Storage Virtual Machine（SVM）

[cols="2*"]
|===
| 情報の種類 | 自分の価値観 


 a| 
クラスタ管理者のパスワード

クラスタ管理者がコンソールにアクセスするとき、またはセキュアなプロトコルを介してアクセスするときにクラスタから入力を求められる、管理者アカウントのパスワードです。


NOTE: セキュリティ上の理由から、このワークシートにパスワードを記入することは推奨されません。

パスワードのデフォルトのルールは次のとおりです。

* 8文字以上である必要があります。
* 英文字と数字がそれぞれ1文字以上含まれている必要があります。

 a| 



 a| 
クラスタ管理インターフェイスポート

データネットワークに接続されている物理ポート。クラスタ管理者はこのポートを使用してクラスタを管理できます。
 a| 



 a| 
クラスタ管理インターフェイスのIPアドレス

クラスタ管理インターフェイスの一意のIPv4アドレスまたはIPv6アドレス。クラスタ管理者は、このアドレスを使用して管理SVMにアクセスし、クラスタを管理します。通常、このアドレスはデータネットワーク上にある必要があります。

このIPアドレスは、組織でIPアドレスを割り当てる管理者から取得できます。

例：192.0.2.66
 a| 



 a| 
クラスタ管理インターフェイスのネットマスク（ IPv4 ）

クラスタ管理ネットワークの有効なIPv4アドレスの範囲を定義するサブネットマスク。

例：255.255.255.0
 a| 



 a| 
クラスタ管理インターフェイスのネットマスクの長さ（IPv6）

クラスタ管理インターフェイスでIPv6アドレスを使用する場合のプレフィックス長。クラスタ管理ネットワークの有効なIPv6アドレスの範囲を定義します。

例：64
 a| 



 a| 
クラスタ管理インターフェイスのデフォルトゲートウェイ

クラスタ管理ネットワーク上のルータのIPアドレス。
 a| 



 a| 
DNSトメインメイ

ネットワークのDNSドメインの名前。

ドメイン名には英数字を使用する必要があります。複数のDNSドメイン名を入力するには、カンマまたはスペースでそれぞれの名前を区切ります。
 a| 



 a| 
ネーム サーバのIPアドレス

DNSネーム サーバのIPアドレスです。各アドレスをカンマまたはスペースで区切ります。
 a| 

|===


=== ノード情報（クラスタ内の各ノード用）

[cols="2*"]
|===
| 情報の種類 | 自分の価値観 


 a| 
コントローラの物理的な場所（オプション）

コントローラの物理的な場所の説明です。このノードをクラスタ内のどこに配置するかを示す概要を使用します（例： Lab 5 、 Row 7 、 Rack B` ）。
 a| 



 a| 
ノード管理インターフェイスポート

ノード管理ネットワークに接続されている物理ポートで、クラスタ管理者はこのポートを使用してノードを管理できます。
 a| 



 a| 
ノード管理インターフェイスのIPアドレス

管理ネットワーク上のノード管理インターフェイスに対する一意のIPv4アドレスまたはIPv6アドレスです。ノード管理インターフェイス ポートをデータ ポートとして定義している場合、このIPアドレスはデータ ネットワーク上で一意のIPアドレスである必要があります。

このIPアドレスは、組織でIPアドレスを割り当てる管理者から取得できます。

例：192.0.2.66
 a| 



 a| 
ノード管理インターフェイスのネットマスク（IPv4）

ノード管理ネットワークの有効なIPアドレスの範囲を定義するサブネットマスク。

ノード管理インターフェイスポートをデータポートとして定義している場合は、ネットマスクをデータネットワークのサブネットマスクにする必要があります。

例：255.255.255.0
 a| 



 a| 
ノード管理インターフェイスのネットマスクの長さ（IPv6）

ノード管理インターフェイスでIPv6アドレスを使用する場合のプレフィックス長です。ノード管理ネットワークの有効なIPv6アドレスの範囲を定義するプレフィックス長です。

例：64
 a| 



 a| 
ノード管理インターフェイスのデフォルトゲートウェイ

ノード管理ネットワーク上のルータのIPアドレス。
 a| 

|===


=== NTPサーバの情報

[cols="2*"]
|===
| 情報の種類 | 自分の価値観 


 a| 
NTPサーバのアドレス

サイトのNetwork Time Protocol（NTP；ネットワークタイムプロトコル）サーバのIPアドレス。これらのサーバは、クラスタ全体で時間を同期するために使用されます。
 a| 

|===