---
permalink: software_setup/index.html 
sidebar: sidebar 
keywords: ontap, software, setup, deciding, decide, if, whether, use, cli, cluster, System Manager, IPv6, HA, root volumes, FlexArray 
summary: Software Setup（ソフトウェアセットアップ） 
---
= ONTAPクラスタセットアップの開始
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
System ManagerまたはONTAPコマンドラインインターフェイス（CLI）を使用して、新しいONTAPクラスタをセットアップできます。  作業を開始する前に、クラスタ管理インターフェイスのポートやIPアドレスなど、クラスタセットアップを完了するために必要な情報を収集しておく必要があります。

.このタスクについて
この手順は、FAS、AFF、および現在のASAシステムに適用されます。ASA R2システム（ASA A1K、ASA A70、またはASA A90）がある場合は、に従ってlink:https://docs.netapp.com/us-en/asa-r2/install-setup/initialize-ontap-cluster.html["以下の手順を実行します"^]ONTAPクラスタをセットアップします。ASA R2システムは、SANのみのお客様に特化したシンプルなONTAPエクスペリエンスを提供します。

NetAppでは、 link:../task_configure_ontap.html["System Managerを使用して新しいクラスタをセットアップする"]。  System Managerでは、ノード管理IPアドレスの割り当て、クラスタの初期化、ローカル階層の作成、プロトコルの設定、初期ストレージのプロビジョニングなど、クラスタのセットアップと設定のワークフローをシンプルかつ簡単に実行できます。

これはlink:task_create_the_cluster_on_the_first_node.html["ONTAP CLIを使用したクラスタのセットアップ"]、MetroCluster構成でONTAP 9 .7以前を実行している場合にのみ必要です。

IPv6.13.1以降のAFF A800およびFAS8700プラットフォームでは、ONTAP 9 ONTAP CLIを使用して、IPv6のみのネットワーク環境で新しいクラスタを作成および設定することもできます。.13.0以前またはONTAP 9 .13.1以降のその他のプラットフォームでIPv6を使用する必要がある場合は、ONTAP 9 Managerを使用してIPv4以降を使用して新しいクラスタを作成できます。link:convert-ipv4-to-ipv6-task.html["IPv6に変換します"]



== クラスタセットアップに必要なもの

クラスタのセットアップでは、各ノードをセットアップするために必要な情報を収集し、最初のノードにクラスタを作成し、残りのノードをクラスタに追加します。

まず、クラスタセットアップワークシートに関連するすべての情報を収集します。

クラスタセットアップワークシートを使用して、クラスタセットアッププロセスで必要となる値を記録できます。デフォルト値が指定されている場合は、その値を使用することも、独自の値を入力することもできます。



=== システムのデフォルト設定

システムのデフォルトは、プライベートクラスタネットワークのデフォルト値です。これらのデフォルト値を使用することを推奨します。ただし、これらの値が要件に合わない場合は、次の表を使用して独自の値を記録できます。


NOTE: ネットワークスイッチを使用するように設定されたクラスタの場合、各クラスタスイッチで 9000 MTU サイズを使用する必要があります。

[cols="2*"]
|===
| 情報の種類 | 値を入力します 


| プライベートクラスタネットワークのポート |  


| クラスタネットワークのネットマスク |  


| クラスタインターフェイスのIPアドレス（各ノードの各クラスタネットワークポート用）

各ノードのIPアドレスが同じサブネット上にある必要があります。 |  
|===


=== クラスタ情報

[cols="2*"]
|===
| 情報の種類 | 値を入力します 


| クラスタ名

名前の1文字目はアルファベットにする必要があり、最大文字数は44文字です。名前には次の特殊文字を含めることができます。

`.` `-` `_` |  
|===


=== 機能ライセンスキー

初回購入のソフトウェアまたはアドオンソフトウェアのライセンスキーは、NetApp Support Siteの「 * My Support * > * Software Licenses 」にあります。

[cols="2*"]
|===
| 情報の種類 | 値を入力します 


| 機能ライセンスキー |  
|===


=== 管理 Storage Virtual Machine （ SVM ）

[cols="2*"]
|===
| 情報の種類 | 値を入力します 


 a| 
クラスタ管理者のパスワード

クラスタ管理者がコンソールにアクセスするとき、またはセキュアなプロトコルを介してアクセスするときにクラスタから入力を求められる、管理者アカウントのパスワードです。


NOTE: セキュリティ上の理由から、このワークシートにパスワードを記録することは推奨されません。

パスワードのデフォルトのルールは次のとおりです。

* パスワードは 8 文字以上にする必要があります。
* アルファベットと数字をそれぞれ 1 文字以上含む。

 a| 



 a| 
クラスタ管理インターフェイスポート

データネットワークに接続されている物理ポートです。クラスタ管理者はこのポートを使用してクラスタを管理できます。
 a| 



 a| 
クラスタ管理インターフェイスの IP アドレス

クラスタ管理インターフェイスの一意の IPv4 アドレスまたは IPv6 アドレスです。クラスタ管理者は、このアドレスを使用して管理 SVM にアクセスし、クラスタを管理します。通常、このアドレスはデータネットワーク上になければなりません。

この IP アドレスは、組織内で IP アドレスの割り当てを担当している管理者から取得できます。

例： 192.0.2.66
 a| 



 a| 
クラスタ管理インターフェイスのネットマスク（ IPv4 ）

クラスタ管理ネットワークの有効な IPv4 アドレスの範囲を定義するサブネットマスクです。

例：255.255.255.0
 a| 



 a| 
クラスタ管理インターフェイスのネットマスクの長さ（ IPv6 ）

クラスタ管理インターフェイスで IPv6 アドレスを使用する場合のプレフィックス長です。クラスタ管理ネットワークの有効な IPv6 アドレスの範囲を定義するプレフィックス長を指定します。

例：64
 a| 



 a| 
クラスタ管理インターフェイスのデフォルトゲートウェイ

クラスタ管理ネットワーク上のルータの IP アドレスです。
 a| 



 a| 
DNS ドメイン名

ネットワークの DNS ドメインの名前です。

ドメイン名には英数字を使用する必要があります。複数の DNS ドメイン名を入力するには、カンマまたはスペースでそれぞれの名前を区切ります。
 a| 



 a| 
ネームサーバの IP アドレス

DNS ネームサーバの IP アドレスです。各アドレスをカンマまたはスペースで区切ります。
 a| 

|===


=== ノード情報（クラスタ内の各ノード）

[cols="2*"]
|===
| 情報の種類 | 値を入力します 


 a| 
コントローラの物理的な場所（オプション）

コントローラの物理的な場所の概要。このノードをクラスタ内のどこに配置するかを示す概要を使用します（例： Lab 5 、 Row 7 、 Rack B` ）。
 a| 



 a| 
ノード管理インターフェイスポート

ノード管理ネットワークに接続されている物理ポートで、クラスタ管理者はこのポートを使用してノードを管理できます。
 a| 



 a| 
ノード管理インターフェイスの IP アドレス

管理ネットワーク上のノード管理インターフェイスに対する一意の IPv4 アドレスまたは IPv6 アドレスです。ノード管理インターフェイスポートをデータポートとして定義している場合、この IP アドレスはデータネットワーク上で一意の IP アドレスである必要があります。

この IP アドレスは、組織内で IP アドレスの割り当てを担当している管理者から取得できます。

例： 192.0.2.66
 a| 



 a| 
ノード管理インターフェイスのネットマスク（ IPv4 ）

ノード管理ネットワークの有効な IP アドレスの範囲を定義するサブネットマスクです。

ノード管理インターフェイスポートをデータポートとして定義している場合、ネットマスクはそのデータネットワークのサブネットマスクである必要があります。

例：255.255.255.0
 a| 



 a| 
ノード管理インターフェイスのネットマスクの長さ（ IPv6 ）

ノード管理インターフェイスで IPv6 アドレスを使用する場合のプレフィックス長です。ノード管理ネットワークの有効な IPv6 アドレスの範囲を定義するプレフィックス長を指定します。

例：64
 a| 



 a| 
ノード管理インターフェイスのデフォルトゲートウェイ

ノード管理ネットワークのルータの IP アドレスです。
 a| 

|===


=== NTP サーバの情報

[cols="2*"]
|===
| 情報の種類 | 値を入力します 


 a| 
NTP サーバアドレス

サイトの Network Time Protocol （ NTP ；ネットワークタイムプロトコル）サーバの IP アドレスです。これらのサーバは、クラスタ全体で時間を同期するために使用されます。
 a| 

|===