---
permalink: software_setup/reference_commands_for_managing_ntp_servers.html 
sidebar: sidebar 
keywords: ontap, software, setup, commands, managing, symmetric, authentication, ntp, servers 
summary: ONTAP 9.5 以降では、ネットワークタイムプロトコル（ NTP; ネットワークタイムプロトコル）バージョン 3 がサポートされます。NTPv3にはSHA-1キーを使用した対称認証が含まれているため、ネットワークセキュリティが向上します。 
---
= NTPサーバの対称認証の管理用コマンド
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
ONTAP 9 .5以降では、ネットワークタイムプロトコル（NTP）バージョン3がサポートされます。NTPv3にはSHA-1キーを使用した対称認証が含まれているため、ネットワークセキュリティが向上します。

[cols="2*"]
|===
| 作業 | 使用するコマンド 


 a| 
対称認証を使用せずにNTPサーバを設定する
 a| 
`cluster time-service ntp server create -server server_name`



 a| 
対称認証を使用してNTPサーバを設定する
 a| 
`cluster time-service ntp server create -server server_ip_address -key-id key_id`



 a| 
既存のNTPサーバに対して対称認証を有効にする

必要なキーIDを追加することで、既存のNTPサーバを変更して認証を有効にすることができます。
 a| 
`cluster time-service ntp server modify -server server_name -key-id key_id`



 a| 
共有NTPキーを設定する
 a| 
`cluster time-service ntp key create -id shared_key_id -type shared_key_type -value shared_key_value`

* 注：共有キーは ID で参照されます。ID、そのタイプ、および値がノードとNTPサーバの両方で同じである必要があります。



 a| 
不明なキーIDでNTPサーバを設定する
 a| 
`cluster time-service ntp server create -server server_name -key-id key_id`



 a| 
NTPサーバで設定されていないキーIDでサーバを設定します。
 a| 
`cluster time-service ntp server create -server server_name -key-id key_id`

* 注： * キー ID 、タイプ、および値は、 NTP サーバに設定されているキー ID 、タイプ、および値と同じである必要があります。



 a| 
対称認証を無効にする
 a| 
`cluster time-service ntp server modify -server server_name -authentication disabled`

|===