---
sidebar: sidebar 
permalink: software_setup/setup-cluster.html 
keywords: install, installing, cluster, set up, setup, configure, disk, data ports, guided setup, local tiers, aggregate, vserver, volume, configuring ONTAP on a new cluster, configuring a new cluster, assign a node-management IP address, node, DNS server, host name, hostname, NTP server, synchronize time, create a local tier, configure protocol, SSD, provision storage, add LUN, add volume, add namespace, volume, vserver, configure ONTAP on a new cluster, configuration 
summary: System Managerのシンプルなワークフローを使用して、クラスタをセットアップし、ストレージを設定することができます。 
---
= ONTAPクラスタを作成してノードを追加する
:hardbreaks:
:toclevels: 1
:allow-uri-read: 
:toclevels: 1
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
NetAppでは、新しいクラスタを作成する際にSystem Managerを使用することを推奨しています。System Managerは、クラスタのセットアップのためのシンプルで簡単なワークフローを提供します。ONTAPコマンドラインインターフェイス（CLI）を使用する必要があるのは、MetroCluster構成でONTAP 9.7以前を実行している場合、または特定のプラットフォームでIPv6専用クラスタを設定する必要がある場合のみです。

.タスク概要
この手順はlink:https://docs.netapp.com/us-en/ontap-systems-family/index.html["AFF、ASA、FAS"^]およびlink:https://docs.netapp.com/us-en/ontap-afx/index.html["AFXシステム"^]に適用されます。ASA r2システム（ASA A1K、ASA A90、ASA A70、ASA A50、ASA A30、ASA A20、またはASA C30）をお使いの場合は、link:https://docs.netapp.com/us-en/asa-r2/install-setup/initialize-ontap-cluster.html["これらの手順"^]に従ってSystem ManagerでONTAPクラスタをセットアップしてください。ASA r2システムは、SANのみのお客様に特化した、簡素化されたONTAPエクスペリエンスを提供します。

ONTAP 9.13.1以降では、ONTAP CLIを使用したクラスタの初期セットアップ時に、AFF A800およびFAS8700プラットフォーム上の管理LIFにIPv6アドレスを割り当てることができます。ONTAP 9.13.1より前のONTAPリリース、または他のプラットフォーム上のONTAP 9.13.1以降の場合は、System Managerを使用してIPv4アドレスでクラスタを作成し、クラスタのセットアップが完了した後にlink:convert-ipv4-to-ipv6-task.html["IPv6に変換する"]アドレスを割り当てる必要があります。


NOTE: System Manager は ONTAP 9.6 以前で IPv6 ネットワークを必要とする導入をサポートしていません。

.開始する前に
* プラットフォーム モデルのインストールおよびセットアップ手順に従って、新しいストレージ システムをインストールし、ケーブル接続し、電源をオンにしておく必要があります。
+
link:https://docs.netapp.com/us-en/ontap-systems/index.html["ONTAPハードウェアシステムのドキュメント"^]を参照してください。

* クラスタスイッチがシステムインストールの一部である場合は、新しいストレージシステムのクラスタポートに対するクラスタスイッチモデルの配線と構成の考慮事項を確認してください。link:https://docs.netapp.com/us-en/ontap-systems-switches/index.html["ONTAP ハードウェアシステムのスイッチのドキュメント"^]を参照してください。
+
.. * Supported switches *タイルで* Cluster Switches *または* Shared Switches *を選択します。
.. スイッチモデルの *Install* ドキュメントを選択します。
.. *ケーブル接続と構成の考慮事項を確認する*トピックを検索し、ストレージシステムについて確認してください。


* link:gather_cluster_setup_information.html["必要な情報を収集する"]を使用してクラスタのセットアップを完了します。
* クラスタの各ノードにクラスタ内通信用のクラスタ ネットワーク インターフェイスが設定されている必要があります。
* CLI を使用して IPv6 を設定する場合は、SSH を使用してシステムにアクセスできるように、ベースマネジメントコントローラ（BMC）で IPv6 を設定する必要があります。


.手順
[role="tabbed-block"]
====
.System Manager
--
. ノード管理IPアドレスの割り当て
+
** Windowsコンピュータ
+
... Windows コンピューターをコントローラーと同じサブネットに接続します。
+
これにより、ノード管理 IP アドレスがシステムに自動的に割り当てられます。

... *ネットワーク* ドライブを開いてノードを検出します。
... ノードを選択して、クラスタ セットアップ ウィザードを起動します。


** Windows以外のコンピューター
+
... クラスタに追加するすべてのノードの電源をオンにします。
+
これは、クラスタセットアップの検出を有効にするために必要です。

... 第1ノードのコンソールに接続します。
+
ノードがブートし、クラスタ セットアップ ウィザードがコンソール上で起動されます。

+
[listing]
----
Welcome to the cluster setup wizard....
----
... AutoSupportのステートメントを承認します。
+
[listing]
----
Type yes to confirm and continue {yes}: yes
----
+
AutoSupportはデフォルトでは有効になります。

... 画面の指示に従って、ノードに管理IPアドレスを割り当てます。
... Web ブラウザで、設定したノード管理 IP アドレスを入力します："https://node-management-IP"[]
+
クラスタの残りのノードは自動的に検出されます。





. *ストレージ システムの初期化* で、クラスタ名と管理パスワードを入力します。
. *ネットワーク*で、クラスタ管理IPアドレス、サブネットマスク、ゲートウェイを入力します。
. ドメイン ネーム サービスを使用してホスト名を解決する場合は、*ドメイン ネーム サービス（DNS）を使用する*を選択し、DNS サーバー情報を入力します。
. ネットワーク タイム プロトコル（NTP）を使用してクラスター全体の時刻を同期する場合は、［その他］で［タイム サービス（NTP）を使用する］を選択し、NTP サーバー情報を入力します。
. *Submit*を選択します。


--
.ONTAP CLI
--
. クラスタに追加するすべてのノードの電源をオンにします。
+
この作業はクラスタ セットアップで検出を可能にするために必要です。

. 第1ノードのコンソールに接続します。
+
ノードがブートし、クラスタ セットアップ ウィザードがコンソール上で起動されます。

+
[listing]
----
Welcome to the cluster setup wizard....
----
. AutoSupportのステートメントを承認します。
+
[listing]
----
Type yes to confirm and continue {yes}: yes
----
+
AutoSupportはデフォルトでは有効になります。

. 画面の指示に従って、ノードに管理IPアドレスを割り当てます。
+
ONTAP 9.13.1以降では、A800およびFAS8700プラットフォーム上の管理LIFにIPv6アドレスを割り当てることができます。ONTAP 9.13.1より前のリリース、または他のプラットフォーム上の9.13.1以降では、管理LIFにIPv4アドレスを割り当て、クラスタのセットアップ完了後にIPv6に変換する必要があります。

. 続行するには *Enter* を押してください。
+
[listing]
----
Do you want to create a new cluster or join an existing cluster? {create, join}:
----
. 新しいクラスタを作成します：
+
.. 入力 `create`
.. システムのデフォルトを受け入れるか、独自の値を入力します。
.. セットアップが完了したら、クラスターにログインし、クラスターがアクティブであり、最初のノードが正常であることを確認します： `cluster show`
+
次の例では、クラスタとその第1ノード（cluster1-01）が健全で、クラスタへの参加条件を満たしていることを示しています。

+
[listing]
----
cluster1::> cluster show
Node                  Health  Eligibility
--------------------- ------- ------------
cluster1-01           true    true
----
+
必要に応じて、 `cluster setup`コマンドを使用してクラスタ セットアップ ウィザードにアクセスし、管理 SVM またはノード SVM に入力した値を変更できます。



. ノードをクラスタに追加します：
+
一度に1つのノードをクラスタに追加できます。各ノードの追加処理を完了し、次のノードの追加を開始する前に、そのノードがクラスタの一部である必要があります。

+
FAS2720に搭載されているNL-SASドライブが24台以下の場合は、パフォーマンスを最適化するために、ストレージ構成のデフォルトがアクティブ / パッシブに設定されていることを確認してください。詳細については、link:../disks-aggregates/setup-active-passive-config-root-data-task.html["ルートデータパーティショニングを使用してノードにアクティブ / パッシブ構成を設定する"]のドキュメントをご覧ください。

+
.. クラスタに追加するノードにログインします。
+
コンソールでクラスタ セットアップ ウィザードが起動します。

+
[listing]
----
Welcome to the cluster setup wizard....
----
.. AutoSupportのステートメントを承認します。
+

NOTE: AutoSupportはデフォルトでは有効になります。



+
[listing]
----
Type yes to confirm and continue {yes}: yes
----
+
.. 画面の指示に従ってノードにIPアドレスを割り当てます。
+
ONTAP 9.13.1以降では、A800およびFAS8700プラットフォーム上の管理LIFにIPv6アドレスを割り当てることができます。ONTAP 9.13.1より前のリリース、または他のプラットフォーム上の9.13.1以降では、管理LIFにIPv4アドレスを割り当て、クラスタのセットアップ完了後にIPv6に変換する必要があります。

.. 続行するには *Enter* を押してください。
+
[listing]
----
Do you want to create a new cluster or join an existing cluster? {create, join}:
----
.. 入力 `join`
.. 画面の指示に従ってノードをセットアップし、クラスタに追加します。
.. セットアップが完了したら、ノードが正常であり、クラスターに参加する資格があることを確認します： `cluster show`
+
次の例は、2つ目のノード（cluster1-02）をクラスタに追加したあとのクラスタを示しています。

+
[listing]
----
cluster1::> cluster show
Node                  Health  Eligibility
--------------------- ------- ------------
cluster1-01           true    true
cluster1-02           true    true
----


. 残りの各ノードを追加するには、手順 7 を繰り返します。


--
====
.次の手順
* 必要であれば、link:convert-ipv4-to-ipv6-task.html["IPv4からIPv6に変換する"]。
* link:task_check_cluster_with_config_advisor.html["Active IQ Config Advisorを実行して構成を検証し、一般的な構成エラーをチェックします。"]。

