---
permalink: software_setup/task_check_cluster_with_config_advisor.html 
sidebar: sidebar 
keywords: ontap, software, setup, check, cluster, digital advisor, active iq, config, advisor 
summary: 新しいクラスタにノードをすべて追加したら、Active IQ Config Advisorを実行して構成を検証し、一般的な構成エラーがないかを確認する必要があります。 
---
= ONTAP クラスタを Digital Advisor Config Advisor で確認する
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
新しいクラスタにノードをすべて追加したら、Active IQ Config Advisorを実行して構成を検証し、一般的な構成エラーがないかを確認する必要があります。

Config Advisorは、ラップトップ、仮想マシン、またはサーバにインストールするWebベースのアプリケーションで、Windows、Linux、Macの各プラットフォームで動作します。

Config Advisorは、一連のコマンドを実行して、インストール環境を検証し、クラスタやストレージ スイッチを含む構成の全体的な健全性をチェックします。

. Active IQ Config Advisorをダウンロードしてインストールします。
+
link:https://mysupport.netapp.com/site/tools/tool-eula/activeiq-configadvisor["Active IQ Config Advisor"^]

. Digital Advisorを起動し、プロンプトが表示されたらパスフレーズを設定します。
. 設定を確認して、*保存*をクリックします。
. *「目標」*ページで、*「ONTAP導入後の検証」*をクリックします。
. ガイド モードまたはエキスパート モードを選択します。
+
ガイド モードを選択すると、接続されているスイッチが自動的に検出されます。

. クラスタのクレデンシャルを入力します。
. （オプション）*Form Validate*をクリックします。
. データの収集を開始するには、*保存して評価* をクリックします。
. データ収集が完了したら、*ジョブ モニター > アクション* で、*データ ビュー* アイコンをクリックして収集されたデータを表示し、*結果* アイコンをクリックして結果を表示します。
. Config Advisorで特定された問題を解決します。

