---
permalink: software_setup/task_create_an_svm_using_ontap_template.html 
sidebar: sidebar 
keywords: ontap, software, setup, provision, svm, preconfigured, template 
summary: ONTAP 9.3 以降では、設定済みテンプレートを使用して SVM を作成およびプロビジョニングできます。テンプレートで定義されているパラメータに値を指定する必要があります。 
---
= 設定済みの ONTAP テンプレートを使用して SVM をプロビジョニング
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
ONTAP 9.3 以降では、設定済みテンプレートを使用して SVM を作成およびプロビジョニングできます。テンプレートで定義されているパラメータに値を指定する必要があります。

.作業を開始する前に
必要な機能のライセンスがすべてクラスタにインストールされている必要があります。

.このタスクについて
SVM の設定に使用できる設定済みテンプレートは、 VserverEnvironmentSetup です。VserverEnvironmentSetup テンプレートを使用して次の設定を行うことができます。

* SVM のセキュリティ形式、言語設定、 IPspace
* プロトコル
* データ LIF
* ネットワークルート
* DNS の設定
* Active Directory の設定
* NIS の設定
* LDAP クライアントおよびサーバの設定
* CIFS サーバ


VserverEnvironmentSetup テンプレートは読み取り専用です。このテンプレートのデフォルトのパラメータ値は変更できません。テンプレート内のいずれかのパラメータのデフォルト値を変更する場合は、テンプレートをコピーしてから、パラメータのデフォルト値を変更する必要があります。

.手順
. SVMの作成と設定に使用するテンプレートで定義されているパラメータの値を確認し、メモします。 `template parameter show`
+
[listing]
----
cluster1::> template parameter show

  Template: VserverEnvironmentSetup
Permission: readonly
                                 Default      Read
Parameter           Type         Value        Only Description
------------------- ------------ ------------ ---- ----------------------------
vserver             string       -            no   Vserver Name
security_style      string       unix         no   Vserver Security Style
language            string       C.UTF-8      no   Vserver Language
ipspace             string       Default      no   Vserver IPSpace
protocols           enum         -            no   Protocols to configure
   Allowed Values: nfs, cifs, iscsi, fcp
data_lif            array of lifInfoStruct
                                 -            yes  Data LIF Info Struct
data_lif[#].ipaddr  IPAddress    -            no   IP Addr
data_lif[#].netmask IPAddress    -            no   NetMask
data_lif[#].protocol
                    string       -            no   LIF Protocol
data_lif[#].homenode
                    string       -            no   Node Name
data_lif[#].homeport
                    string       -            no   Port
gateway             array of IPAddress
                                 -            yes  Gateway
gateway[#]          IPAddress                 no   Gateway
search_domain       string       -            no   Search Domain
dns_server          string       -            no   DNS IP Addresses List
ad_admin_name       string       -            no   AD Admin Name
ad_admin_passwd     string       ***          no   AD Admin Passwd
ad_domain           string       -            no   AD Domain
ad_ou               string       CN=Computers no   Organizational Name
wg_name             string       -            no   WG Name
nis_domain          string       -            no   NIS Domains
nis_ipaddr          string       -            no   NIS IP Address
ldap_server         string       -            no   LDAP Server IP
ldap_base_dn        string       -            no   LDAP Base DN
client_config       string       -            no   LDAP Client Config
cifs_server         string       -            no   CIFS Server Name
26 entries were displayed.
----
. テンプレート内のパラメータのデフォルト値を変更する場合は、既存のテンプレートをカスタマイズします。
+
.. テンプレートをコピーします。
+
`template copy -name template_name -destination_name new_template_name`

+
[listing]
----
cluster1::> template copy -name VserverEnvironmentSetup -destination-name template1
----
+
新しいテンプレートは読み取り / 書き込み可能です。

.. 変更するパラメータのデフォルト値を変更します。
+
`template parameter modify -template template_name -name parameter_name -default-value new_default_value`

+
[listing]
----
cluster1::> template parameter modify -template template1 -name security_style -default-value ntfs
----


. テンプレート内のパラメータに値を指定して SVM をプロビジョニングします。
+
`template provision -name template_name`

+
[listing]
----
cluster-1::> template provision -name template1
	    Press Ctrl+C to abort.
	    ********************
	    * Setup of vserver *
	    ********************
	    Vserver Name: vs0
	    Vserver Language [C.UTF-8]:
	    Vserver Security Style [ntfs]:
	    Vserver IPSpace [Default]:

	    ******************************
	    * Setup of network.interface *
	    ******************************
	    Enter number of instances for object network.interface: 2
	    (1/2)LIF Protocol: nfs
	    (1/2)IP Addr: 1.1.1.1
	    (1/2)NetMask: 255.255.255.0
	    (1/2)Node Name: node1-vsim1
	    (1/2)Port: e0c
	    (2/2)LIF Protocol: nfs
	    (2/2)IP Addr: 1.1.1.1
	    (2/2)NetMask: 255.255.255.0
	    (2/2)Node Name: node1-vsim1
	    (2/2)Port: e0c

	    ***************************
	    * Setup of network.routes *
	    ***************************
	    Enter number of instances for object network.routes: 1
	    (1/1)Gateway: 1.1.1.1

	    ***********************
	    * Setup of access.dns *
	    ***********************
	    Search Domain: netapp.com
	    DNS IP Addresses List: 1.1.1.1

	    *************************
	    * Setup of security.nis *
	    *************************
	    NIS Domains: netapp.com
	    NIS IP Address: 1.1.1.1

	    *********************
	    * Setup of security *
	    *********************
	    LDAP Client Config: ldapconfig
	    LDAP Server IP: 1.1.1.1
	    LDAP Base DN: dc=examplebasedn

	    **********************
	    * Setup of protocols *
	    **********************
	    Protocols to configure: nfs
	    [Job 15] Configuring vserver for vs0 (100%)
----

