---
permalink: software_setup/task_decide_where_to_send_important_event_notifications.html 
sidebar: sidebar 
keywords: ontap, software, setup, decide, where, send, important, event, notifications 
summary: 重要な EMS イベントの通知について設定するときは、通知を E メールアドレス、 syslog サーバ、 SNMP トラップホストのいずれに送信するかを事前に決めておく必要があります。 
---
= 重要なイベント通知の送信先を決定します
:icons: font
:imagesdir: ../media/


[role="lead"]
重要な EMS イベントの通知について設定するときは、通知を E メールアドレス、 syslog サーバ、 SNMP トラップホストのいずれに送信するかを事前に決めておく必要があります。

サーバやアプリケーションなどの他のシステムで記録されたイベントを集約するためにすでに syslog サーバを使用している場合は、ストレージシステムの重要なイベントの通知にもその syslog サーバを使用すると簡単です。

syslog サーバがまだない場合は、重要なイベントの通知に E メールを使用すると便利です。

イベント通知をすでに SNMP トラップホストに転送している場合は、そのトラップホストで重要なイベントについても監視できます。

* イベント通知を送信するように EMS を設定します。
+
[cols="2*"]
|===
| 状況 | 参照先 


 a| 
EMS の重要なイベント通知を E メールアドレスに送信します
 a| 
xref:task_configure_important_ems_events_to_send_email_notifications.html[重要な EMS イベントの通知を E メールで送信するための設定]



 a| 
EMS の重要なイベント通知を syslog サーバに転送します
 a| 
xref:task_configure_important_ems_events_to_forward_notifications_to_a_syslog_server.html[重要な EMS イベントの通知を syslog サーバに転送するための設定]



 a| 
EMS のイベント通知を SNMP トラップホストに転送する
 a| 
xref:task_configure_snmp_traphosts_to_receive_event_notifications.html[SNMP トラップホストでイベント通知を受信するように設定する]

|===

