---
permalink: software_setup/task_decide_where_to_send_important_event_notifications.html 
sidebar: sidebar 
keywords: ontap, software, setup, decide, where, send, important, event, notifications 
summary: 重要なEMSイベントの通知を設定する前に、通知をEメールアドレス、syslogサーバ、SNMPトラップホストのいずれに送信するかを決める必要があります。 
---
= 重要なイベント通知の送信先を決定
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
重要なEMSイベントの通知を設定する前に、通知をEメールアドレス、syslogサーバ、SNMPトラップホストのいずれに送信するかを決める必要があります。

サーバやアプリケーションなど、他のシステムで記録されたイベントを集約するためにすでにsyslogサーバを使用している場合は、ストレージシステムからの重要なイベントの通知にもそのsyslogサーバを使用すると簡単です。

syslogサーバがまだない場合は、重要なイベントの通知にEメールを使用する方が簡単です。

イベント通知をすでにSNMPトラップホストに転送している場合は、そのトラップホストで重要なイベントが発生していないか監視できます。

* イベント通知を送信するようにEMSを設定します。
+
[cols="2*"]
|===
| 状況 | 参照先 


 a| 
EMSの重要なイベント通知をEメールアドレスに送信する
 a| 
xref:task_configure_important_ems_events_to_send_email_notifications.html[重要なEMSイベントの通知をEメールで送信するための設定]



 a| 
EMSの重要なイベント通知をsyslogサーバに転送する
 a| 
xref:task_configure_important_ems_events_to_forward_notifications_to_a_syslog_server.html[重要なEMSイベントの通知をsyslogサーバに転送するための設定]



 a| 
EMSのイベント通知をSNMPトラップホストに転送する場合
 a| 
xref:task_configure_snmp_traphosts_to_receive_event_notifications.html[イベント通知を受信するためのSNMPトラップホストの設定]

|===

