---
permalink: software_setup/task_create_the_cluster_on_the_first_node.html 
sidebar: sidebar 
keywords: ontap, software, setup, create, cluster, first, node, autosupport, CLI 
summary: クラスタセットアップウィザードを使用して、第 1 ノードにクラスタを作成できます。このウィザードを使用して、ノードを接続するクラスタネットワークの構成、クラスタ管理Storage Virtual Machine（SVM）の作成、機能ライセンスキーの追加、第1ノードのノード管理インターフェイスの作成を行うことができます。 
---
= ONTAPの最初のノードにクラスタを作成
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
クラスタセットアップウィザードを使用して、第 1 ノードにクラスタを作成できます。このウィザードを使用して、ノードを接続するクラスタネットワークの構成、クラスタ管理Storage Virtual Machine（SVM）の作成、機能ライセンスキーの追加、第1ノードのノード管理インターフェイスの作成を行うことができます。


NOTE: この手順は、FAS、AFF、および現在のASAシステムに適用されます。ASA R2システム（ASA A1K、ASA A90、ASA A70、ASA A50、ASA A30、またはASA A20）がある場合は、link:https://docs.netapp.com/us-en/asa-r2/install-setup/initialize-ontap-cluster.html["以下の手順を実行します"^]System Managerを使用してONTAPクラスタをセットアップします。ASA R2システムは、SANのみのお客様に特化したシンプルなONTAPエクスペリエンスを提供します。

.開始する前に
* 使用しているプラットフォームモデルの設置とセットアップの手順に従って、新しいストレージシステムを設置し、ケーブル接続して電源をオンにしておく必要があります。を参照してください https://docs.netapp.com/us-en/ontap-systems/index.html["AFFおよびFASのドキュメント"^]。
* クラスタ内通信用に、クラスタの各ノードにクラスタネットワークインターフェイスが設定されている必要があります。
* クラスタでIPv6を設定する場合は、ベース管理コントローラ（BMC）でIPv6を設定して、SSHを使用してシステムにアクセスできるようにする必要があります。


.手順
. クラスタに追加するすべてのノードの電源をオンにします。これは、クラスタセットアップの検出を有効にするために必要です。
. 最初のノードのコンソールに接続します。
+
ノードがブートし、クラスタセットアップウィザードがコンソール上で起動されます。

+
[listing]
----
Welcome to the cluster setup wizard....
----
. AutoSupportステートメントを確認します。
+
[listing]
----
Type yes to confirm and continue {yes}: yes
----
+

NOTE: AutoSupportはデフォルトで有効になっています。

. 画面の指示に従って、ノードにIPアドレスを割り当てます。
+
ONTAP 9.13.1以降では、A800およびFAS8700プラットフォームの管理LIFにIPv6アドレスを割り当てることができます。9.13.1より前のONTAPリリースまたは他のプラットフォームの9.13.1以降では、管理LIFにIPv4アドレスを割り当て、クラスタのセットアップ完了後にIPv6に変換する必要があります。

. Enter * を押して続行します。
+
[listing]
----
Do you want to create a new cluster or join an existing cluster? {create, join}:
----
. 新しいクラスタを作成します。 `create`
. システムのデフォルトを受け入れるか、独自の値を入力します。
. セットアップが完了したら、ONTAP CLIコマンドを入力してクラスタにログインし、クラスタがアクティブで、第1ノードが正常であることを確認します。 `cluster show`
+
次の例は、最初のノード（cluster1-01）が正常に機能しており、参加条件を満たしているクラスタを示しています。

+
[listing]
----
cluster1::> cluster show
Node                  Health  Eligibility
--------------------- ------- ------------
cluster1-01           true    true
----
+
コマンドを使用すると、クラスタセットアップウィザードにアクセスして、管理SVMまたはノードSVMに対して入力した値を変更できます `cluster setup`。



.終了後
必要に応じて、link:convert-ipv4-to-ipv6-task.html["IPv4からIPv6に変換します"]
