---
permalink: asa/overview.html 
sidebar: sidebar 
keywords: all flash san array, asa, san, array, software, configuration, configure, configuring, setup, set up, limitations, restrictions, nvme, mcc ip, persistent ports, host, settings, utilities, ways to identify 
summary: NetAppオールフラッシュSANアレイ（ASA）はONTAP 9.7以降で使用できます。  ASAは、実績のあるAFF ネットアッププラットフォームを基盤としたオールフラッシュのSAN専用ソリューションです。 
---
= オールフラッシュSANアレイソフトウェア構成の概要
:toc: macro
:hardbreaks:
:toclevels: 1
:allow-uri-read: 
:toc: 
:toclevels: 1
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/
:toc-position: content


[role="lead"]
NetAppオールフラッシュSANアレイ（ASA）はONTAP 9.7以降で使用できます。  ASAは、実績のあるAFF ネットアッププラットフォームを基盤としたオールフラッシュのSAN専用ソリューションです。

ASAプラットフォームでは、マルチパスに対称アクティブ/アクティブ構成を使用します。すべてのパスはアクティブ / 最適化されているため、ストレージフェイルオーバー時に、ホストは ALUA によるフェイルオーバーパスの移行を待機しなくても I/O を再開できますこれにより、フェイルオーバーにかかる時間が短縮されます。



== ASA をセットアップする

オールフラッシュSANアレイ（ASA）のセットアップ手順は手順、ASA以外のシステムと同じです。

System Manager では、クラスタの初期化、ローカル階層の作成、プロトコルの設定、および ASA 用のストレージのプロビジョニングに必要な手順を実行することができます。

xref:../software_setup/concept_decide_whether_to_use_ontap_cli.html[ONTAPクラスタセットアップの開始]。



== ASA ホストの設定とユーティリティ

オールフラッシュSANアレイ（ASA）をセットアップするためのホスト設定は、他のすべてのSANホストと同じです。

はダウンロードできます link:https://mysupport.netapp.com/NOW/cgi-bin/software["NetApp Host Utilities ソフトウェア"^] サポートサイトから特定のホストにアクセスできるようにします。



== ASA システムの識別方法

ASA システムは、 System Manager または ONTAP のコマンドラインインターフェイス（ CLI ）を使用して識別できます。

* * System Managerダッシュボード*で：*[クラスタ]>[概要]*をクリックし、システムノードを選択します。
+
パーソナリティ * は「 * All SAN Array * 」と表示されます。

* * CLIから*： `san config show` コマンドを実行します
+
「 All SAN Array 」の値は、 ASA システムでは true を返します。



.関連情報
* link:https://www.netapp.com/pdf.html?item=/media/85671-tr-4968.pdf["テクニカルレポート4968：『NetApp All-SAN Array Data Availability and Integrity』"^]
* link:http://www.netapp.com/us/media/tr-4080.pdf["テクニカルレポート4080：『Best Practices for Scalable SAN ONTAP 9』"^]

