---
sidebar: sidebar 
permalink: high-availability/ha_automatic_giveback_commands.html 
keywords: ontap, high, availability, ha, pair, automatic, giveback, commands 
summary: 自動ギブバックコマンド 
---
= 自動ギブバックコマンド
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
デフォルトでは、オフラインのノードがオンラインに戻った時点でテイクオーバーパートナーノードがストレージを自動的にギブバックするため、ハイアベイラビリティペア関係がリストアされます。ほとんどの場合、これが望ましい動作です。自動ギブバックを無効にする必要がある場合：テイクオーバーの原因 を調査してからギブバックする場合は、デフォルト以外の設定のやり取りについて確認しておく必要があります。

|===


| 状況 | 使用するコマンド 


 a| 
自動ギブバックを有効にして、テイクオーバーされたノードのブート後、 Waiting for giveback 状態に達し、 Auto giveback 期間が終了するまでの待機時間が経過した時点でギブバックが実行されるようにします。

デフォルト設定は true です。
 a| 
`storage failover modify ‑node _nodename_ ‑auto‑giveback true`



 a| 
自動ギブバックを無効にするデフォルト設定は true です。

*注：*このパラメータをfalseに設定しても、パニック時のテイクオーバー後の自動ギブバックは無効になりません。パニック時のテイクオーバー後の自動ギブバックは、を設定して無効にする必要があります `‑auto‑giveback‑after‑panic` パラメータをfalseに設定します。
 a| 
`storage failover modify ‑node _nodename_ ‑auto‑giveback false`



 a| 
パニック時のテイクオーバーのあとに実行される自動ギブバックを無効にします（この設定はデフォルトで有効になります）。
 a| 
`storage failover modify ‑node _nodename_ ‑auto‑giveback‑after‑panic false`



 a| 
自動ギブバックが開始されるまでの待機時間（秒）を設定します（デフォルトは 600 秒）。このオプションで指定した待機時間が経過するまでは、自動ギブバックは実行されません。
 a| 
`storage failover modify ‑node _nodename_ ‑delay‑seconds _seconds_`

|===


== storage failover modify コマンドの設定による自動ギブバックへの影響

自動ギブバックの処理は、 storage failover modify コマンドのパラメータの設定によって異なります。

次の表に、のデフォルト設定を示します `storage failover modify` パニック以外のテイクオーバーイベントに適用されるコマンドパラメータ。

|===


| パラメータ | デフォルト設定です 


 a| 
`-auto-giveback _true_ | _false_`
 a| 
`_true_`



 a| 
`-delay-seconds _integer_ (seconds)`
 a| 
600



 a| 
`-onreboot _true_ | _false_`
 a| 
`_true_`

|===
次の表に、の組み合わせを示します `-onreboot` および `-auto-giveback` パラメータは、パニック以外のテイクオーバーイベントの自動ギブバックに適用されます。

|===


| `storage failover modify` 使用するパラメータ | テイクオーバーの原因 | 自動ギブバックの実行 


 a| 
`-onreboot _true_`

`-auto-giveback _true_`
| reboot コマンド | はい。 


| halt コマンド、またはサービスプロセッサからの電源再投入 | はい。 


 a| 
`-onreboot _true_`

`-auto-giveback _false_`
| reboot コマンド | はい。 


| halt コマンド、またはサービスプロセッサからの電源再投入 | いいえ 


 a| 
`-onreboot _false_`

`-auto-giveback _true_`
| reboot コマンド | 該当なし
この場合、テイクオーバーは実行されません。 


| halt コマンド、またはサービスプロセッサからの電源再投入 | はい。 


 a| 
`-onreboot _false_`

`-auto-giveback _false_`
| reboot コマンド | いいえ 


| halt コマンド、またはサービスプロセッサからの電源再投入 | いいえ 
|===
。 `-auto-giveback` パラメータは、パニックおよびその他すべての自動テイクオーバー後のギブバックを制御します。状況に応じて `-onreboot` パラメータはに設定されます `true` リブートが原因でテイクオーバーが発生すると、がどちらであるかに関係なく、常に自動ギブバックが実行されます `-auto-giveback` パラメータはに設定されます `true`。

。 `-onreboot` Parameter環境 がリブートし、ONTAP から実行されたコマンドが停止します。をクリックします `-onreboot` パラメータがfalseに設定されている場合、ノードがリブートしてもテイクオーバーは実行されません。そのため、があるかどうかに関係なく、自動ギブバックは実行されません `-auto-giveback` パラメータがtrueに設定されている。クライアントのアクセスが中断します。



== パニック時に適用される自動ギブバックパラメータの組み合わせとその影響

次の表に、を示します `storage failover modify` パニック状態に適用されるコマンドパラメータは次のとおりです。

|===


| パラメータ | デフォルト設定です 


 a| 
`-onpanic _true | false_`
 a| 
`_true_`



 a| 
`-auto-giveback-after-panic _true | false_`

（権限： advanced ）
 a| 
`_true_`



 a| 
`-auto-giveback _true | false_`
 a| 
`_true_`

|===
次の表に、のパラメータの組み合わせを示します `storage failover modify` コマンドは、パニック時の自動ギブバックに適用されます。

[cols="60,40"]
|===


| `storage failover` 使用するパラメータ | パニック発生後の自動ギブバックの実行 


| `-onpanic true`
`-auto-giveback true`
`-auto-giveback-after-panic true` | はい。 


| `-onpanic true`
`-auto-giveback true`
`-auto-giveback-after-panic false` | はい。 


| `-onpanic true`
`-auto-giveback false`
`-auto-giveback-after-panic true` | はい。 


| `-onpanic true`
`-auto-giveback false`
`-auto-giveback-after-panic false` | いいえ 


| `-onpanic false`
状況 `-onpanic` がに設定されます `false`に設定されている値に関係なく、テイクオーバー/ギブバックは実行されません `-auto-giveback` または `-auto-giveback-after-panic` | いいえ 
|===

NOTE: テイクオーバーが発生する原因としては、パニックに関連しない障害が考えられます。  a_failure_は、ノードとそのパートナー間の通信が失われたときに実行されます。これは、_ハートビートlost_とも呼ばれます。障害が原因でテイクオーバーが発生した場合は、によってギブバックが制御されます `-onfailure` ではなくパラメータを使用します `-auto-giveback-after-panic parameter`。


NOTE: ノードでパニックが発生すると、パートナーノードにパニックパケットが送信されます。  何らかの理由でパートナーノードがパニックパケットを受信しなかった場合、パニック状態と誤って解釈される可能性があります。  パニックパケットを受信しなかった場合、パートナーノードは通信が失われたことだけを認識し、パニック状態になったことは通知しません。  この場合、パートナーノードはパニック状態ではなく障害として通信の喪失を処理し、ギブバックはによって制御されます `-onfailure` パラメータ（ではなく） `-auto-giveback-after-panic parameter`）。

詳細については、を参照してください `storage failover modify` パラメータについては、を参照してください link:https://docs.netapp.com/us-en/ontap-cli-9131/storage-failover-modify.html["ONTAP のマニュアルページ"]。
