---
sidebar: sidebar 
permalink: high-availability/ha_manual_takeover.html 
keywords: ontap, high, availability, ha, pair, manual, takeover, moving, move, epislon, manually, initiated 
summary: パートナーでメンテナンスが必要な場合、およびその他の同様の状況では、テイクオーバーを手動で実行できます。 
---
= ONTAP手動テイクオーバーコマンド
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
パートナーでメンテナンスが必要な場合、およびその他の同様の状況では、テイクオーバーを手動で実行できます。テイクオーバーの実行に使用するコマンドは、パートナーの状態に応じて異なります。

|===


| 状況 | 使用するコマンド 


| パートナー ノードをテイクオーバーする | `storage failover takeover` 


| テイクオーバー（テイクオーバーを実行中のノードにパートナーのアグリゲートを移動する）の進捗を監視する | `storage failover show‑takeover` 


| クラスタ内のすべてのノードのストレージ フェイルオーバー ステータスを表示する | `storage failover show` 


| LIFを移行せずにパートナー ノードをテイクオーバーする | `storage failover takeover ‑skip‑lif‑migration‑before‑takeover true` 


| ディスクが一致していなくてもパートナー ノードをテイクオーバーする | `storage failover takeover -allow-disk-inventory-mismatch true` 


| ONTAPのバージョンが一致しない場合でもパートナー ノードを引き継ぎます。*注：*このオプションは、無停止のONTAPアップグレード プロセス中にのみ使用されます。 | `storage failover takeover ‑option allow‑version‑mismatch` 


| アグリゲートの再配置を実行せずにパートナー ノードをテイクオーバーする | `storage failover takeover ‑bypass‑optimization true` 


| パートナーによるストレージ リソースの正常終了を待たずにパートナー ノードをテイクオーバーする | `storage failover takeover ‑option immediate` 
|===
[NOTE]
====
即時オプションを指定したstorage failoverコマンドを発行する前に、次のコマンドを使用してデータLIFを別のノードに移行する必要があります： `network interface migrate-all -node _node_`

 `network interface migrate-all`の詳細については、link:https://docs.netapp.com/us-en/ontap-cli/network-interface-migrate-all.html["ONTAPコマンド リファレンス"^]をご覧ください。

最初にデータLIFを移行せずに `storage failover takeover ‑option immediate`コマンドを指定すると、 `skip‑lif‑migration‑before‑takeover`オプションが指定されていない場合でも、ノードからのデータLIFの移行が大幅に遅延します。

同様に、immediate オプションを指定すると、bypass‑optimization オプションが _false_ に設定されている場合でも、ネゴシエートされたテイクオーバー最適化はバイパスされます。

====


== テイクオーバーを手動で開始する場合のイプシロンの移動

手動で開始したテイクオーバーによって、ストレージ システムの1つのノードで予期しないノード障害が発生するとクラスタ全体のクォーラムが失われる可能性がある場合は、イプシロンを移動する必要があります。

.タスク概要
計画メンテナンスを実行するには、HAペアの一方のノードをテイクオーバーする必要があります。残りのノードで予期せぬクライアントデータの中断を防ぐため、クラスタ全体のクォーラムを維持する必要があります。場合によっては、テイクオーバーを実行すると、予期せぬノード障害が1つ発生すればクラスタ全体のクォーラムが失われる可能性があります。

この状況は、テイクオーバーするノードにイプシロンが設定されている場合や、イプシロンが設定されたノードが健全な状態でない場合に発生します。クラスタの耐障害性を高めるには、テイクオーバーするノード以外の健全なノードにイプシロンを移動します。通常はHAパートナーに移動します。

クォーラム投票には、正常かつ適格なノードのみが参加します。クラスター全体のクォーラムを維持するには、N/2を超える投票が必要です（_N_は正常かつ適格なオンラインノードの合計数を表します）。オンラインノードが偶数個のクラスターでは、イプシロンは割り当てられたノードのクォーラム維持に対する投票重みを追加します。


NOTE: クラスタ構成の投票は `cluster modify ‑eligibility false`コマンドを使用して変更できますが、ノード構成の復元やノードの長期メンテナンスなどの状況を除き、これを避ける必要があります。ノードを不適格に設定すると、ノードが適格にリセットされて再起動されるまで、SANデータの提供が停止されます。ノードが不適格になると、そのノードへのNASデータアクセスも影響を受ける可能性があります。

.手順
. クラスタの状態を確認し、テイクオーバーするノード以外の健全なノードにイプシロンが設定されていることを確認します。
+
.. 高度な権限レベルに変更し、高度なモード プロンプト（*>）が表示されたら続行することを確認します：
+
`set -privilege advanced`

.. イプシロンが設定されているノードを特定します。
+
`cluster show`

+
次の例では、Node1にイプシロンが設定されています。

+
|===


| ノード | 健全性 | 資格 | イプシロン 


 a| 
Node1 Node2
 a| 
true true
 a| 
true true
 a| 
真 偽

|===
+
テイクオーバーするノードにイプシロンが設定されていない場合は、手順4に進みます。

+
 `cluster show`の詳細については、link:https://docs.netapp.com/us-en/ontap-cli/cluster-show.html["ONTAPコマンド リファレンス"^]をご覧ください。



. テイクオーバーするノードからイプシロンを削除します。
+
`cluster modify -node Node1 -epsilon false`

. パートナー ノード（この例ではNode2）にイプシロンを割り当てます。
+
`cluster modify -node Node2 -epsilon true`

. テイクオーバー処理を実行します。
+
`storage failover takeover -ofnode _node_name_`

. admin権限レベルに戻ります。
+
`set -privilege admin`



.関連情報
* link:https://docs.netapp.com/us-en/ontap-cli/storage-failover-show.html["storage failover show"^]
* link:https://docs.netapp.com/us-en/ontap-cli/storage-failover-takeover.html["storage failover takeover"^]

