---
sidebar: sidebar 
permalink: high-availability/ha_manual_giveback.html 
keywords: ontap, high, availability, ha, pair, manual, giveback, interrupted, vetoed, veto, commands, performing, perform 
summary: パートナーノードのプロセスを終了する標準ギブバック、または強制ギブバックを実行できます。 
---
= 手動ギブバックコマンド
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
パートナーノードのプロセスを終了する標準ギブバック、または強制ギブバックを実行できます。


NOTE: ギブバックを実行する前に、で説明するように、障害が発生したドライブをテイクオーバーされたシステムから取り外す必要があります link:../disks-aggregates/index.html["ディスクとアグリゲートの管理"]。



== ギブバックが中断された場合

ギブバックプロセス中にテイクオーバーノードで障害が発生したり停電が発生したりした場合、そのプロセスは停止します。障害が修復されるか電源が回復するまで、テイクオーバーノードはテイクオーバーモードに戻ります。

ただし、障害がギブバックのどの段階で発生したかによって、これとは異なる動作になります。障害や停電が部分的なギブバック状態の間（ルートアグリゲートのギブバックの完了後）に発生した場合、ノードはテイクオーバーモードには戻りません。部分的なギブバックモードに戻ります。この場合、プロセスを完了するには、ギブバック処理をもう一度実行します。



== ギブバックが拒否された場合

ギブバックが拒否された場合、 EMS メッセージを調べて原因を特定する必要があります。その理由に応じて、拒否を無視しても問題がないかどうかを判断することができます。

「 storage failover show-giveback 」コマンドを実行すると、ギブバックの進捗が表示されます。ギブバックが拒否された場合は、拒否したサブシステムも表示されます。拒否の中には、無視してもかまわないソフトなものと、強制しても無視できないハードなものがあります。次の表に、無視できないソフトな拒否と、推奨される対処方法を示します。

次のコマンドを使用して、ギブバックの拒否に関する EMS の詳細を確認できます。

event log show -node * -event gb *



== ルートアグリゲートのギブバック

次の拒否は、アグリゲートの再配置処理には適用されません。

[cols="35,65"]
|===


| 拒否しているサブシステムモジュールです | 回避策 


 a| 
vFiler_low_level
 a| 
拒否の原因となっている SMB セッションを終了するか、開いているセッションを確立した SMB アプリケーションをシャットダウンします。

この拒否原因を無視すると、 SMB を使用しているアプリケーションが突然切断され、データが失われる可能性があります。



 a| 
ディスクチェック
 a| 
ギブバックを実行する前に、障害が発生したかバイパスされたディスクをすべて取り外します。ディスクの完全消去を実行中の場合は、処理が完了するまで待ちます。

この拒否を無視すると、容量確保の競合やディスクにアクセスできないことが原因でアグリゲートやボリュームがオフラインになり、原因が停止する可能性があります。

|===


== SFO アグリゲートのギブバックを実行します

次の拒否は、アグリゲートの再配置処理には適用されません。

[cols="35,65"]
|===


| 拒否しているサブシステムモジュールです | 回避策 


 a| 
ロックマネージャ
 a| 
ファイルを開いている SMB アプリケーションを適切な手順でシャットダウンするか、それらのボリュームを別のアグリゲートに移動します。

この拒否を無視すると、 SMB のロック状態が解除され、システムの停止やデータの損失の原因になります。



 a| 
ロックマネージャ NDO
 a| 
ロックがミラーされるまで待ちます。

この拒否を無視すると、 Microsoft Hyper-V 仮想マシンの処理が停止します。



| RAID の場合  a| 
EMS メッセージを調べて拒否の原因を特定します。

nvfile が原因である場合は、オフラインのボリュームおよびアグリゲートをオンラインにします。

ディスクの追加処理またはディスク所有権の再割り当て処理を実行中の場合は、それらの処理が完了するまで待ちます。

アグリゲートの名前または UUID の競合が原因である場合は、問題のトラブルシューティングを行ってその問題を解決します。

ミラーの再同期、ミラーの検証、またはディスクのオフライン化が原因で拒否された場合は無視してかまいません。これらの処理は、ギブバック後に再開されます。



| ディスクインベントリ  a| 
トラブルシューティングを行って、問題の原因を特定し、解決します。

移行中のアグリゲートに属するディスクは、デスティネーションノードで認識できないことがあります。

ディスクにアクセスできないと、アグリゲートまたはボリュームにアクセスできない可能性があります。



| ボリューム移動処理  a| 
トラブルシューティングを行って、問題の原因を特定し、解決します。

この拒否は、重要なカットオーバーフェーズ中にボリューム移動処理が中止されるのを防止します。カットオーバー中にジョブが中止されると、ボリュームにアクセスできなくなる可能性があります。

|===


=== 手動ギブバックを実行するためのコマンドです

HA ペアのノードで、メンテナンスが完了したあとやテイクオーバーの原因となった問題を解決したあとに元の所有者にストレージを戻すには、手動でギブバックを開始します。

|===


| 状況 | 使用するコマンド 


 a| 
パートナーノードにストレージをギブバックします
| 「 storage failover giveback ‑ ofd_nodename 


 a| 
パートナーがギブバック待機モードになっていなくてもストレージをギブバックします
 a| 
「 storage failover giveback ‑ ofd_nodename _`‑ require ‑ partner ‑ waiting false

このオプションは、長時間クライアントが停止しても問題がない場合にのみ使用してください。



| ギブバック処理がプロセスで拒否されてもストレージをギブバックする（強制的にギブバックを実行する）  a| 
「 storage failover giveback ‑ ofd_nodename_`‑ override ‑ override-vetoes true

このオプションを使用すると、クライアントの停止が長引いたり、ギブバックの完了後にアグリゲートとボリュームがオンラインに復帰しない可能性があります。



| CFO アグリゲート（ルートアグリゲート）だけをギブバックする  a| 
「 storage failover giveback ‑ ofd_nodename

「‑ only ‑ cfo ‑ aggregates true 」



| ギブバックコマンドを実行したあとにギブバックの進捗を監視します問題 | 'storage failover show ‑ giveback 
|===