---
sidebar: sidebar 
permalink: high-availability/index.html 
keywords: high availability, ha, overview 
summary: テイクオーバーとは、ノードがパートナーのストレージの制御を引き継ぐプロセスです。ギブバックとは、ストレージがパートナーに返されるプロセスです。 
---
= ONTAPクラスタにおけるHAペア管理について学ぶ
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
クラスタ ノードは、フォールト トレランスとノンストップ オペレーションを実現するためにハイアベイラビリティ（HA）ペアとして構成されます。ノードに障害が発生した場合や定期的なメンテナンスのためにノードを停止する必要がある場合、パートナーがストレージをテイクオーバーしてデータの提供を続けることができます。ノードがオンラインに戻ると、パートナーはストレージを返します。

HA ペア コントローラ構成は、一致するストレージ コントローラのペア (ローカル ノードとパートナー ノード) で構成されます。各ノードは、パートナーのディスク シェルフに接続されています。HAペアの一方のノードでエラーが発生してデータ処理が停止すると、その障害のステータスがパートナーによって検出され、そのコントローラのすべてのデータ処理がテイクオーバーされます。

_Takeover は、ノードがパートナーのストレージの制御を引き継ぐプロセスです。

_giveback_ は、ストレージがパートナーに返されるプロセスです。

デフォルトでは、次のいずれかの状況で自動的にテイクオーバーが実行されます。

* ノードでソフトウェアまたはシステムの障害が発生し、パニックが発生した場合。HAペアコントローラは、対応するパートナーノードに自動的にフェイルオーバーされます。パートナーがパニック状態から回復してブートされると、ノードで自動的にギブバックが実行され、パートナーは通常動作に戻ります。
* ノードでシステム障害が発生し、そのノードをリブートできない。たとえば、停電が原因でノードに障害が発生した場合、HAペアコントローラがパートナーノードに自動的にフェイルオーバーされ、稼働しているストレージコントローラからデータが提供されます。



NOTE: ノードのストレージへの電源も同時に喪失した場合は、標準テイクオーバーは実行できません。

* ノードのパートナーからハートビート メッセージが届かない場合。この状況は、パートナーでハードウェアまたはソフトウェア障害（インターコネクト障害など）が発生し、パニック状態にはならなかったものの、正常に機能しなくなった場合に発生します。
* パラメータまたは `-inhibit-takeover true`パラメータを使用せずに一方のノードを停止した場合 `-f`



NOTE: クラスタHAが有効な2ノードクラスタで、パラメータを使用してノードを停止またはリブート `‑inhibit‑takeover true`すると、クラスタHAを無効にしてからオンラインのままにするノードにイプシロンを割り当てないかぎり、両方のノードでデータの提供が停止します。

* パラメータを使用せずに一方のノードをリブートした場合 `‑inhibit‑takeover true`（ `‑onboot`コマンドのパラメータは `storage failover`デフォルトで有効になっています）。
* リモート管理デバイス（サービスプロセッサ）でパートナーノードの障害が検出された場合。これは、ハードウェアアシストテイクオーバーを無効にした場合は該当しません。


コマンドを使用してテイクオーバーを手動で開始することもできます `storage failover takeover`。

ONTAP 9.18.1 以降では、HA ペア ノード間の暗号化通信を設定できます。詳細については、link:ha-pair-encryption.html["ONTAP HAトラフィックの暗号化を構成する"] 。



== クラスタの耐障害性と診断の強化

ONTAP 9.9.1以降では、耐障害性と診断機能が次のように追加され、クラスタの運用が改善されています。

* *ポートの監視と回避*：2ノードスイッチレスクラスタ構成では、全体的なパケット損失（接続の損失）が発生するポートを回避します。ONTAP 9 8.1以前では、この機能はスイッチ経由の構成でのみ使用できました。
* *ノードの自動フェイルオーバー*：クラスタネットワーク経由でデータを提供できないノードは、ディスクを所有しないでください。代わりに、パートナーが正常に稼働している場合は、そのHAパートナーがテイクオーバーします。
* *接続の問題を分析するコマンド*：次のコマンドを使用して、パケット損失が発生しているクラスタパスを表示します。 `network interface check cluster-connectivity show`
+
の詳細については `network interface check cluster-connectivity show`、をlink:https://docs.netapp.com/us-en/ontap-cli/network-interface-check-cluster-connectivity-show.html["ONTAPコマンド リファレンス"^]参照してください。


