---
permalink: nas-audit/additional-information-reference.html 
sidebar: sidebar 
keywords: additional information 
summary: SMBクライアント アクセスをテストしたあと、SMBの高度な設定を行ったり、SANアクセスを追加したりできます。NFSクライアント アクセスをテストしたあと、NFSの高度な設定を行ったり、SANアクセスを追加したりできます。プロトコル アクセスが完了したら、SVMのルート ボリュームを保護する必要があります。 
---
= ONTAP SVMに関する追加情報の入手先
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
SMBクライアント アクセスをテストしたあと、SMBの高度な設定を行ったり、SANアクセスを追加したりできます。NFSクライアント アクセスをテストしたあと、NFSの高度な設定を行ったり、SANアクセスを追加したりできます。プロトコル アクセスが完了したら、SVMのルート ボリュームを保護する必要があります。



== SMB設定

SMBアクセスについてさらに詳しく設定するには、以下を参照してください。

* link:../smb-admin/index.html["SMBの管理"]
+
SMBプロトコルを使用したファイル アクセスを設定および管理する方法について説明しています。

* https://www.netapp.com/pdf.html?item=/media/16326-tr-4191pdf.pdf["NetApp テクニカルレポート 4191：Clustered Data ONTAP 8.2 Windows ファイルサービスのベストプラクティスガイド"^]
+
SMBの導入やその他のWindowsファイル サービスの機能の概要に加え、ONTAP向けの推奨事項や基本的なトラブルシューティング情報を紹介しています。

* https://www.netapp.com/pdf.html?item=/media/19673-tr-3740.pdf["NetAppテクニカル レポート3740：『SMB 2 Next-Generation CIFS Protocol in Data ONTAP』"^]
+
SMB 2の機能について、設定に関する詳細やONTAPでの実装に関する情報を紹介しています。





== NFSの設定

NFSアクセスについてさらに詳しく設定するには、以下を参照してください。

* link:../nfs-admin/index.html["NFSの管理"]
+
NFSプロトコルを使用したファイル アクセスを設定および管理する方法について説明しています。

* https://www.netapp.com/pdf.html?item=/media/10720-tr-4067.pdf["NetAppテクニカル レポート4067：『NFS Best Practice and Implementation Guide』"^]
+
NFSv3およびNFSv4の運用ガイドであり、NFSv4を中心にONTAPオペレーティング システムの概要を説明しています。

* https://www.netapp.com/pdf.html?item=/media/16328-tr-4668pdf.pdf["NetAppテクニカル レポート4668：『Name Services Best Practices Guide』"^]
+
LDAP、NIS、DNS、およびローカル ユーザ / グループ ファイルを認証用に設定する際の、ベストプラクティス、制限、推奨事項、および考慮事項をまとめています。

* https://www.netapp.com/pdf.html?item=/media/19384-tr-4616.pdf["NetApp テクニカルレポート 4616：ONTAP における NFS Kerberos と Microsoft Active Directory"]
* https://www.netapp.com/pdf.html?item=/media/19423-tr-4835.pdf["NetAppテクニカルレポート4835：ONTAPでLDAPを設定する方法"]
* https://www.netapp.com/pdf.html?item=/media/16398-tr-3580pdf.pdf["NetAppテクニカル レポート3580：『NFSv4の拡張内容とベスト・プラクティス・ガイド - Data ONTAPでの実装』"^]
+
ONTAPを実行するシステムに接続されたAIX、Linux、またはSolarisクライアントにNFSv4のコンポーネントを実装する際のベストプラクティスを紹介しています。





== ルート ボリュームの保護

SVMでプロトコルを設定したら、ルート ボリュームを保護してください。

* link:../data-protection/index.html["データ保護"]
+
負荷共有ミラーを作成してSVMルート ボリュームを保護する方法について説明しています。これは、NAS対応のSVMに対するNetAppのベストプラクティスです。また、SVMルート ボリュームを負荷共有ミラーから昇格させてボリュームの障害や消失からリカバリする簡単な方法についても説明しています。


