---
permalink: nas-audit/audit-symlinks-hard-links-concept.html 
sidebar: sidebar 
keywords: considerations, audit, symlinks, hard links 
summary: シンボリックリンクおよびハードリンクを監査する場合は、一定の考慮事項に注意する必要があります。 
---
= シンボリックリンクおよびハードリンクを監査する際の考慮事項
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
シンボリックリンクおよびハードリンクを監査する場合は、一定の考慮事項に注意する必要があります。

監査レコードには、 ObjectName タグで特定される監査対象オブジェクトへのパスなど、監査されるオブジェクトに関する情報が格納されます。シンボリックリンクおよびハード・リンクのパスが ObjectName タグにどのように記録されるかに注意する必要があります。



== シンボリックリンク

シンボリックリンクとは、ターゲットと呼ばれるデスティネーションオブジェクトの場所へのポインタを含む、独立した inode を持つファイルです。シンボリックリンクを介してオブジェクトにアクセスする際、 ONTAP は、シンボリックリンクを自動的に解釈し、ボリューム内のターゲットオブジェクトへの、プロトコルに依存しない本来のパスに従います。

次の出力例には、 2 つのシンボリックリンクが示されており、どちらも「 target.txt 」というファイルを指しています。一方のシンボリックリンクは相対シンボリックリンクであり、他方は絶対シンボリックリンクです。どちらかのシンボリックリンクが監査された場合 ' 監査イベントの ObjectName タグに 'target.txt' ファイルへのパスが格納されます

[listing]
----
[root@host1 audit]# ls -l
total 0
lrwxrwxrwx 1 user1 group1 37 Apr  2 10:09 softlink_fullpath.txt -> /data/audit/target.txt
lrwxrwxrwx 1 user1 group1 10 Apr  2 09:54 softlink.txt -> target.txt
-rwxrwxrwx 1 user1 group1 16 Apr  2 10:05 target.txt
----


== ハードリンク

ハードリンクは、ファイルシステム上の既存のファイルに名前を関連付けるディレクトリエントリです。ハードリンクは元のファイルの inode の場所を指しています。ONTAP ONTAP は、シンボリックリンクの解釈方法と同様に、ハードリンクを解釈し、ボリューム内のターゲットオブジェクトへの本来のパスに従います。ハード・リンク・オブジェクトへのアクセスが監査されると、監査イベントにより、ハード・リンク・パスではなく、この正規の絶対パスが ObjectName タグに記録されます。
