---
permalink: nas-audit/auditing-events-concept.html 
sidebar: sidebar 
keywords: audit, nas, events, svms 
summary: NAS イベントの監査は、 Storage Virtual Machine （ SVM ）で特定の CIFS および NFS イベントを追跡してログに記録できるセキュリティ対策です。これは、潜在的なセキュリティの問題を追跡するのに役立ち、セキュリティ違反が発生した場合の証拠になります。Active Directory の集約型アクセスポリシーのステージングおよび監査によってこれらを実装した場合の結果を確認することもできます。 
---
= SVM での NAS イベントの監査の概要
:icons: font
:imagesdir: ../media/


[role="lead"]
NAS イベントの監査は、 Storage Virtual Machine （ SVM ）で特定の CIFS および NFS イベントを追跡してログに記録できるセキュリティ対策です。これは、潜在的なセキュリティの問題を追跡するのに役立ち、セキュリティ違反が発生した場合の証拠になります。Active Directory の集約型アクセスポリシーのステージングおよび監査によってこれらを実装した場合の結果を確認することもできます。



== CIFS イベント

次のイベントを監査できます。

* SMB ファイルおよびフォルダのアクセスイベント
+
監査が有効になっている SVM に属する FlexVol ボリュームに格納されているオブジェクトに対する SMB によるファイルおよびフォルダアクセスイベントを監査できます。

* CIFS ログオンおよびログオフイベント
+
SVM 上にある CIFS サーバでの CIFS ログオンおよびログオフイベントを監査できます。

* 集約型アクセスポリシーのステージングイベント
+
提案された集約型アクセスポリシーによって適用された権限を使用した CIFS サーバ上のオブジェクトへの有効なアクセスを監査できます。集約型アクセスポリシーのステージングによって監査を行うと、集約型アクセスポリシーを導入する前に、その影響を確認できます。

+
集約型アクセスポリシーのステージングによる監査は、 Active Directory の GPO を使用してセットアップされます。ただし、 SVM の監査の設定は、集約型アクセスポリシーステージングイベントを監査するように設定されている必要があります。

+
CIFS サーバでダイナミックアクセス制御を有効にせずに、監査設定で集約型アクセスポリシーのステージングを有効にすることはできますが、集約型アクセスポリシーのステージングイベントが生成されるのは、ダイナミックアクセス制御が有効になっている場合だけです。ダイナミックアクセス制御は、 CIFS サーバオプションを使用して有効にします。デフォルトでは有効になっていません。





== NFS イベント

SVM 上に格納されているオブジェクトに対するファイルおよびディレクトリの NFSv4 アクセスイベントを監査できます。
