---
permalink: nas-audit/configure-fpolicy-ssl-connections-concept.html 
sidebar: sidebar 
keywords: additional information, configure, fpolicy, external engines, ssl authenticated, connections 
summary: SSL サーバへの接続時に追加情報を使用するように FPolicy 外部エンジンを設定する場合は、いくつかの FPolicy を把握しておく必要があります。 
---
= 追加情報 SSL 認証接続を使用するための FPolicy 外部エンジンの設定について
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
SSL サーバへの接続時に追加情報を使用するように FPolicy 外部エンジンを設定する場合は、いくつかの FPolicy を把握しておく必要があります。



== SSL サーバ認証

SSL サーバ認証用の FPolicy 外部エンジンを設定する場合には、外部エンジンを作成する前に、 FPolicy サーバ証明書の署名を行った認証局（ CA ）のパブリック証明書をインストールする必要があります。



== 相互認証

Storage Virtual Machine （ SVM ）のデータ LIF を外部 FPolicy サーバに接続する際に SSL 相互認証を使用するように FPolicy 外部エンジンを設定する場合は、外部エンジンを作成する前に、次の手順を実行します。 FPolicy サーバ証明書に署名した CA のパブリック証明書を、 SVM の認証用のパブリック証明書およびキーファイルとともにインストールする必要があります。インストールした証明書を FPolicy ポリシーが使用している間は、この証明書を削除しないでください。

FPolicy が相互認証に使用している間に証明書を削除すると、その証明書を使用する、無効になった FPolicy ポリシーを再度有効にすることはできません。この状況では、同じ設定で証明書を新規作成して SVM にインストールしても、 FPolicy ポリシーを再度有効にすることはできません。

証明書が削除されている場合は、新しい証明書をインストールして、その新しい証明書を使用する FPolicy 外部エンジンを新規作成し、 FPolicy ポリシーを変更して再度有効にする FPolicy ポリシーに、新しい外部エンジンを関連付ける必要があります。



== SSL の証明書をインストールします

FPolicy サーバ証明書に署名した CA のパブリック証明書をインストールするには、「 -type 」パラメータに「 client_ca 」を指定して「 securitycertificate install 」コマンドを実行します。SVM の認証に必要な秘密鍵と公開証明書をインストールするには '-type パラメータを 'server' に設定して 'securitycertificate install' コマンドを使用します
