---
permalink: nas-audit/create-persistent-stores.html 
sidebar: sidebar 
keywords: create, persistent store, fpolicy, asynchronous, non, mandatory 
summary: ONTAP 9.14.1 以降では、FPolicy を使用すると、非同期の非必須ポリシーのファイル アクセス イベントをキャプチャするための永続ストアを設定できます。 
---
= ONTAP FPolicy永続ストアを作成する
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
永続ストアは、クライアントのI/O処理とFPolicy通知処理を分離することで、クライアントのレイテンシを削減するのに役立ちます。ONTAP 9.14.1以降では、FPolicyを使用してlink:persistent-stores.html["永続ストア"]を設定し、SVM内の非同期の非必須ポリシーのファイルアクセスイベントをキャプチャできます。同期（必須または非必須）および非同期の必須設定はサポートされていません。

ONTAP 9.15.1 以降、FPolicy 永続ストアの設定が簡素化されました。 `persistent-store create`コマンドは、SVM のボリューム作成を自動化し、永続ストア用のボリュームを設定します。

永続的ストアの作成方法は、ONTAPリリースによって2種類に分かれます。

* ONTAP 9.15.1 以降：永続ストアを作成すると、ONTAP は同時にボリュームの作成と設定を自動的に行います。これにより、FPolicy 永続ストアの設定が簡素化され、すべてのベストプラクティスが実装されます。
* ONTAP 9.14.1：ボリュームを手動で作成および設定し、新しく作成したボリュームの永続ストアを作成します。


SVMごとに設定できる永続的ストアは1つだけです。ポリシーの提供パートナーが異なる場合でも、各SVM上のすべてのFPolicy設定に単一の永続的ストアを使用する必要があります。



== 永続的ストアの作成（ONTAP 9.15.1以降）

ONTAP 9.15.1以降では、 `fpolicy persistent-store create`コマンドを使用して、インラインボリュームの作成と設定を含むFPolicy永続ストアを作成できます。ONTAPは、ボリュームへの外部ユーザープロトコル アクセス（CIFS/NFS）を自動的にブロックします。

.開始する前に
* 永続的ストアの作成先となるSVMには、アグリゲートを1つ以上用意しておく必要があります。
* SVM用アグリゲートへのアクセス権と、ボリューム作成のための十分な権限が必要です。


.手順
. 永続的ストアを作成します。この際、ボリュームが自動的に作成および設定されます。
+
`vserver fpolicy persistent-store create -vserver <vserver> -persistent-store <name> -volume <volume_name> -size <size> -autosize-mode <off|grow|grow_shrink>`

+
**  `vserver`パラメータは SVM の名前です。
**  `persistent-store`パラメータは永続ストアの名前です。
**  `volume`パラメーターは永続ストア ボリュームの名前です。
+

NOTE: 既存の空のボリュームを使用する場合は、 `volume show` コマンドを使用してそのボリュームを検索し、ボリューム パラメータで指定します。

**  `size`パラメーターは、外部サーバー（パートナー アプリケーション）に配信されないイベントを保持する期間に基づいています。
+
たとえば、1秒あたり30,000件の通知があるクラスタで、イベントを30分間維持する場合のサイズは、次のように計算します。

+
必要なボリューム サイズ = 30000 x 30 x 60 x 0.6KB（平均通知レコード サイズ）= 32400000 KB = 約32 GB

+
おおよその通知レートを確認するには、FPolicy パートナー アプリケーションにアクセスするか、FPolicy カウンター `requests_dispatched_rate`を使用します。

+

NOTE: 既存のボリュームを使用する場合、sizeパラメータは省略可能です。sizeパラメータの値を指定すると、ボリュームのサイズが指定したものに変更されます。

**  `autosize-mode`パラメータは、ボリュームの自動サイズ調整モードを指定します。サポートされている自動サイズ調整モードは次のとおりです：
+
*** off - スペースの使用状況が変化しても、サイズの拡張も縮小も行いません。
*** grow - ボリュームのスペースの使用量が拡張しきい値を超えた場合に、ボリュームを自動的に拡張します。
*** grow_shrink - スペース使用量の増減に合わせてボリュームを拡張または縮小します。




. FPolicyポリシーを作成し、そのポリシーに永続ストア名を追加します。詳細については、link:create-fpolicy-policy-task.html["FPolicyポリシーの作成"]を参照してください。




== 永続的ストアの作成（ONTAP 9.14.1）

ボリュームを作成してから、そのボリュームを使用する永続的ストアを作成します。その後、新しく作成したボリュームに対する外部ユーザのプロトコル アクセス（CIFSおよびNFS）をブロックできます。

.手順
. 永続ストア用にプロビジョニングできる空のボリュームを SVM に作成します：
+
`volume create -vserver <SVM Name> -volume <volume> -state <online> -policy <default> -unix-permissions <777> -size <value> -aggregate <aggregate name> -snapshot-policy <none>`

+
十分な RBAC 権限（ボリュームを作成するための）を持つ管理者ユーザーが、必要なサイズのボリューム（volume cli コマンドまたは REST API を使用）を作成し、そのボリュームの名前を persistent store create CLI コマンドまたは REST API の `-volume`として指定することが想定されています。

+
**  `vserver`パラメータは SVM の名前です。
**  `volume`パラメーターは永続ストア ボリュームの名前です。
**  `state`パラメータは、ボリュームを使用できるようにするためにオンラインに設定する必要があります。
**  `policy`パラメータは、既に設定されている場合、FPolicyサービスポリシーに設定されます。設定されていない場合は、後で `volume modify`コマンドを使用してポリシーを追加できます。
**  `unix-permissions` パラメータはオプションです。
**  `size`パラメーターは、外部サーバー（パートナー アプリケーション）に配信されないイベントを保持する期間に基づいています。
+
たとえば、1秒あたり30,000件の通知があるクラスタで、イベントを30分間維持する場合のサイズは、次のように計算します。

+
必要なボリューム サイズ = 30000 x 30 x 60 x 0.6KB（平均通知レコード サイズ）= 32400000 KB = 約32 GB

+
おおよその通知レートを確認するには、FPolicy パートナー アプリケーションにアクセスするか、FPolicy カウンター `requests_dispatched_rate`を使用します。

** aggregateパラメータは、FlexVolボリュームを使用する場合は必須です。それ以外の場合は省略可能です。
**  `snapshot-policy`パラメータは none に設定する必要があります。これにより、スナップショットが誤って復元されて現在のイベントが失われることがなくなり、イベント処理が重複する可能性も回避されます。
+
既存の空のボリュームを使用する場合は、 `volume show`コマンドを使用してボリュームを検索し、 `volume modify`コマンドを使用して必要な変更を加えます。永続ストアのポリシー、サイズ、および `snapshot-policy`パラメータが正しく設定されていることを確認してください。



. 永続ストアを作成します：
+
`vserver fpolicy persistent store create -vserver <SVM> -persistent-store <PS_name> -volume <volume>`

+
**  `vserver`パラメータは SVM の名前です。
**  `persistent-store`パラメータは永続ストアの名前です。
**  `volume`パラメーターは永続ストア ボリュームの名前です。


. FPolicyポリシーを作成し、そのポリシーに永続ストア名を追加します。詳細については、link:create-fpolicy-policy-task.html["FPolicyポリシーの作成"]を参照してください。

