---
permalink: nas-audit/create-persistent-stores.html 
sidebar: sidebar 
keywords: create, persistent store, fpolicy, asynchronous, non, mandatory 
summary: ONTAP 9.14.1以降では、FPolicyで永続的ストアを設定して、非同期の非必須ポリシーのファイルアクセスイベントをキャプチャできます。 
---
= FPolicy永続的ストアの作成
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
永続的ストアを使用すると、クライアントI/O処理とFPolicy通知処理を分離して、クライアントのレイテンシを低減できます。ONTAP 9.14.1以降では、FPolicyを使用して link:persistent-stores.html["永続的ストア"] SVM内の非同期非必須ポリシーのファイルアクセスイベントをキャプチャする。同期（必須または非必須）および非同期の必須構成はサポートされていません。

ONTAP 9.15.1以降では、FPolicyの永続的ストアの設定が簡易化されています。。 `persistent-store create` コマンドを実行すると、SVM用のボリュームの作成が自動化され、永続的ストア用のボリュームが設定されます。

永続ストアを作成するには、ONTAPのリリースに応じて次の2つの方法があります。

* ONTAP 9.15.1以降：永続ストアを作成すると、ONTAPでボリュームが自動的に作成されて設定されます。これにより、FPolicyの永続的ストアの設定が簡素化され、すべてのベストプラクティスが実装されます。
* ONTAP 9.14.1：ボリュームを手動で作成して設定し、新しく作成したボリューム用の永続的ストアを作成します。


各SVMに設定できる永続的ストアは1つだけです。ポリシーが別 々 のパートナーのものであっても、この単一の永続的ストアをそのSVM上のすべてのFPolicy設定に使用する必要があります。



== 永続ストアの作成（ONTAP 9.15.1以降）

ONTAP 9.15.1以降では、 `fpolicy persistent-store create` インラインボリュームの作成および設定を行うFPolicy永続ストアを作成するコマンド。ONTAPは、外部ユーザプロトコルアクセス（CIFS / NFS）からボリュームを自動的にブロックします。

.作業を開始する前に
* 永続的ストアを作成するSVMには、アグリゲートが少なくとも1つ必要です。
* SVMで使用可能なアグリゲートへのアクセスと、ボリュームを作成するための十分な権限が必要です。


.手順
. 永続的ストアを作成します。これにより、ボリュームが自動的に作成および設定されます。
+
`vserver fpolicy persistent-store create -vserver <vserver> -persistent-store <name> -volume <volume_name> -size <size> -autosize-mode <off|grow|grow_shrink>`

+
** 。 `vserver` parameterは、SVMの名前です。
** 。 `persistent-store` parameterは、永続ストアの名前です。
** 。 `volume` parameterは、永続的ストアボリュームの名前です。
+

NOTE: 既存の空のボリュームを使用する場合は、 `volume show` コマンドを使用して検索し、volumeパラメータで指定します。

** 。 `size` パラメータは、外部サーバ（パートナーアプリケーション）に配信されないイベントを保持する期間に基づいています。
+
たとえば、1秒あたり30Kの通知があるクラスタで30分間のイベントを維持する場合は、次のコマンドを実行します。

+
必要なボリュームサイズ= 30000 x 30 x 60 x 0.6KB（通知レコードの平均サイズ）= 32400000 KB =~32GB

+
おおよその通知速度を確認するには、FPolicyパートナーアプリケーションに連絡するか、FPolicyカウンタを利用します。 `requests_dispatched_rate`。

+

NOTE: 既存のボリュームを使用する場合、sizeパラメータはオプションです。sizeパラメータに値を指定すると、指定したサイズに一致するボリュームが変更されます。

** 。 `autosize-mode` パラメータは、ボリュームのオートサイズモードを指定します。次のオートサイズモードがサポートされています。
+
*** off -使用済みスペースの量に応じてボリュームのサイズが拡張または縮小されません。
*** grow -ボリュームの使用済みスペースが拡張しきい値を超えると、ボリュームは自動的に拡張されます。
*** grow_shrink -使用済みスペースの量に応じてボリュームのサイズが拡張または縮小されます。




. FPolicyポリシーを作成し、そのポリシーに永続ストア名を追加します。詳細については、を参照してください link:create-fpolicy-policy-task.html["FPolicy ポリシーを作成します"]。




== 永続ストアの作成（ONTAP 9.14.1）

ボリュームを作成し、そのボリュームを使用する永続的ストアを作成できます。作成したボリュームを外部ユーザプロトコルアクセス（CIFS / NFS）からブロックできます。

.手順
. 永続ストア用にプロビジョニング可能な空のボリュームをSVMに作成します。
+
`volume create -vserver <SVM Name> -volume <volume> -state <online> -policy <default> -unix-permissions <777> -size <value> -aggregate <aggregate name> -snapshot-policy <none>`

+
（ボリュームを作成するための）十分なRBAC権限を持つ管理者ユーザは、必要なサイズのボリュームを（volume CLIコマンドまたはREST APIを使用して）作成し、そのボリュームの名前を `-volume` 永続的ストアでは、CLIコマンドまたはREST APIを作成します。

+
** 。 `vserver` parameterは、SVMの名前です。
** 。 `volume` parameterは、永続的ストアボリュームの名前です。
** 。 `state` ボリュームを使用できるようにするには、パラメータをonlineに設定する必要があります。
** 。 `policy` FPolicyサービスポリシーがすでに設定されている場合は、パラメータがに設定されます。そうでない場合は、 `volume modify` あとでコマンドを実行してポリシーを追加します。
** 。 `unix-permissions` パラメータはオプションです。
** 。 `size` パラメータは、外部サーバ（パートナーアプリケーション）に配信されないイベントを保持する期間に基づいています。
+
たとえば、1秒あたり30Kの通知があるクラスタで30分間のイベントを維持する場合は、次のコマンドを実行します。

+
必要なボリュームサイズ= 30000 x 30 x 60 x 0.6KB（通知レコードの平均サイズ）= 32400000 KB =~32GB

+
おおよその通知速度を確認するには、FPolicyパートナーアプリケーションに連絡するか、FPolicyカウンタを利用します。 `requests_dispatched_rate`。

** FlexVolボリュームの場合はaggregateパラメータが必要です。それ以外の場合は必須ではありません。
** 。 `snapshot-policy` パラメータはnoneに設定する必要があります。これにより、スナップショットが誤ってリストアされて現在のイベントが失われることがなくなり、イベント処理の重複を防ぐことができます。
+
既存の空のボリュームを使用する場合は、 `volume show` コマンドを使用して検索し、 `volume modify` コマンドを使用して必要な変更を行います。ポリシー、サイズ、 `snapshot-policy` 永続ストアのパラメータが正しく設定されている。



. 永続ストアを作成します。
+
`vserver fpolicy persistent store create -vserver <SVM> -persistent-store <PS_name> -volume <volume>`

+
** 。 `vserver` parameterは、SVMの名前です。
** 。 `persistent-store` parameterは、永続ストアの名前です。
** 。 `volume` parameterは、永続的ストアボリュームの名前です。


. FPolicyポリシーを作成し、そのポリシーに永続ストア名を追加します。詳細については、を参照してください link:create-fpolicy-policy-task.html["FPolicy ポリシーを作成します"]。

