---
permalink: nas-audit/create-fpolicy-external-engine-task.html 
sidebar: sidebar 
keywords: create, fpolicy, external engine 
summary: FPolicy の設定を作成するには、最初に外部エンジンを作成する必要があります。外部エンジンは、 FPolicy で外部 FPolicy サーバへの接続を確立および管理する方法を定義します。内部の ONTAP エンジン（標準の外部エンジン）を単純なファイルブロッキングに使用している設定の場合は、 FPolicy 外部エンジンを別途設定する必要がないため、この手順の実行は不要です。 
---
= FPolicy 外部エンジンを作成します
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
FPolicy の設定を作成するには、最初に外部エンジンを作成する必要があります。外部エンジンは、 FPolicy で外部 FPolicy サーバへの接続を確立および管理する方法を定義します。内部の ONTAP エンジン（標準の外部エンジン）を単純なファイルブロッキングに使用している設定の場合は、 FPolicy 外部エンジンを別途設定する必要がないため、この手順の実行は不要です。

.必要なもの
。 link:fpolicy-external-engine-config-worksheet-reference.html["外部エンジン"] ワークシートを記入する必要があります。

.このタスクについて
外部エンジンが MetroCluster 構成で使用されている場合は、ソースサイトでの FPolicy サーバの IP アドレスをプライマリサーバとして指定する必要があります。デスティネーションサイトでの FPolicy サーバの IP アドレスは、セカンダリサーバとして指定する必要があります。

.手順
. vserver fpolicy policy external-engine create コマンドを使用して FPolicy 外部エンジンを作成します。
+
次のコマンドは、 Storage Virtual Machine （ SVM ） vs1.example.com 上に外部エンジンを作成します。FPolicy サーバとの外部通信に認証は必要ありません。

+
vserver fpolicy policy external-engine create -vserver-name vs1.example.com -engine-name engine1 -primary-servers 10.1.1.2 、 10.1.1.3 -port 6789-ssl-option no-auth

. vserver fpolicy policy external-engine show コマンドを使用して FPolicy 外部エンジンの設定を確認します。
+
次のコマンドは、 SVM vs1.example.com で設定されているすべての外部エンジンに関する情報を表示します。

+
vserver fpolicy policy external-engine show -vserver vs1.example.com

+
[listing]
----

                                Primary        Secondary          External
Vserver            Engine       Servers        Servers       Port Engine Type
---------------    -----------  -------------- ----------- ------ -----------
vs1.example.com    engine1      10.1.1.2,      -             6789 synchronous
                                10.1.1.3
----
+
次のコマンドは、 SVM vs1.example.com 上の「 engine1 」という外部エンジンに関する詳細情報を表示します。

+
vserver fpolicy policy external-engine show -vserver vs1.example.com -engine-name engine1

+
[listing]
----

                              Vserver: vs1.example.com
                               Engine: engine1
              Primary FPolicy Servers: 10.1.1.2, 10.1.1.3
       Port Number of FPolicy Service: 6789
            Secondary FPolicy Servers: -
                 External Engine Type: synchronous
SSL Option for External Communication: no-auth
           FQDN or Custom Common Name: -
         Serial Number of Certificate: -
                Certificate Authority: -
----

