---
permalink: nas-audit/create-security-trace-filters-task.html 
sidebar: sidebar 
keywords: create, security trace filters 
summary: Storage Virtual Machine（SVM）でSMBとNFSのクライアント処理を検出し、フィルタに一致するすべてのアクセスチェックをトレースするセキュリティトレースフィルタを作成できます。セキュリティトレースの結果を使用して、設定の検証やアクセスに関する問題のトラブルシューティングを行うことができます。 
---
= セキュリティトレースフィルタを作成する
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Storage Virtual Machine（SVM）でSMBとNFSのクライアント処理を検出し、フィルタに一致するすべてのアクセスチェックをトレースするセキュリティトレースフィルタを作成できます。セキュリティトレースの結果を使用して、設定の検証やアクセスに関する問題のトラブルシューティングを行うことができます。

.タスクの内容
vserver security trace filter createコマンドには、次の2つの必須パラメータがあります。

[cols="35,65"]
|===


| 必須パラメータ | 説明 


 a| 
`-vserver` `vserver_name`
 a| 
SVM 名 _

セキュリティトレースフィルタを適用するファイルやフォルダが格納されているSVMの名前。



 a| 
`-index` `index_number`
 a| 
フィルタインデックス番号 _

フィルタに適用するインデックス番号。トレースフィルタはSVMごとに10個まで使用できます。このパラメータに指定できる値は1~10です。

|===
オプションのフィルタパラメータをいくつか使用すると、セキュリティトレースのフィルタをカスタマイズして、セキュリティトレースの結果を絞り込むことができます。

[cols="35,65"]
|===


| フィルタパラメータ | 説明 


 a| 
`-client-ip` `IP_Address`
 a| 
IPアドレスを指定します。このIPアドレスからSVMにアクセスしているユーザが対象です。



 a| 
`-path` `path`
 a| 
パーミッショントレースフィルタを適用するパスを指定します。の値 `-path`には、次のいずれかの形式を使用できます。

* 共有またはエクスポートのルートから始まる完全パス
* 共有のルートに対する相対パス


パス値には、NFS形式のディレクトリUNIX形式のディレクトリ区切り文字を使用する必要があります。



 a| 
`-windows-name` `win_user_name`または `-unix-name``unix_user_name`
 a| 
アクセス要求をトレースするWindowsユーザ名またはUNIXユーザ名を指定できます。ユーザ名変数では大文字と小文字は区別されません。同じフィルタにWindowsユーザ名とUNIXユーザ名の両方を指定することはできません。

[NOTE]
====
トレースできるのはSMBおよびNFSのアクセスイベントですが、mixedセキュリティ形式またはUNIXセキュリティ形式のデータに対してアクセスチェックを実行するときに、マッピングされたUNIXユーザおよびUNIXグループが使用されることがあります。

====


 a| 
`-trace-allow`{`yes`|`no`}
 a| 
セキュリティトレースフィルタでは、拒否イベントのトレースが常に有効になります。必要に応じて、許可イベントをトレースすることもできます。許可イベントをトレースするには、このパラメータをに設定し `yes`ます。



 a| 
`-enabled`{`enabled`|`disabled`}
 a| 
セキュリティトレースフィルタを有効または無効にすることができます。デフォルトでは、セキュリティトレースフィルタは有効になっています。



 a| 
`-time-enabled` `integer`
 a| 
フィルタのタイムアウトを指定できます。指定した時間が経過すると、フィルタは無効になります。

|===
.手順
. セキュリティトレースフィルタを作成します。
+
`vserver security trace filter create -vserver vserver_name -index index_numberfilter_parameters`

+
`filter_parameters`は、オプションのフィルタパラメータのリストです。

+
詳細については、コマンドのマニュアルページを参照してください。

. セキュリティトレースフィルタエントリを確認します。
+
`vserver security trace filter show -vserver vserver_name -index index_number`



.例
次のコマンドは、IPアドレス10.10.10.7から共有パスのファイルにアクセスするすべてのユーザを対象としたセキュリティトレースフィルタを作成し `\\server\share1\dir1\dir2\file.txt`ます。フィルタでは、オプションに完全なパスが使用され `-path`ます。データへのアクセスに使用されるクライアントのIPアドレスは10.10.10.7です。フィルタは30分後にタイムアウトします。

[listing]
----
cluster1::> vserver security trace filter create -vserver vs1 -index 1 -path /dir1/dir2/file.txt -time-enabled 30 -client-ip 10.10.10.7
cluster1::> vserver security trace filter show -index 1
Vserver  Index   Client-IP            Path            Trace-Allow  Windows-Name
-------- -----  -----------  ----------------------   -----------  -------------
vs1        1    10.10.10.7   /dir1/dir2/file.txt          no       -
----
次のコマンドは、オプションの相対パスを使用してセキュリティトレースフィルタを作成し `-path`ます。このフィルタは、「 joe 」という名前の Windows ユーザのアクセスをトレースします。Joeは共有パスのファイルにアクセスしています `\\server\share1\dir1\dir2\file.txt`。許可イベントと拒否イベントをトレースします。

[listing]
----
cluster1::> vserver security trace filter create -vserver vs1 -index 2 -path /dir1/dir2/file.txt -trace-allow yes -windows-name mydomain\joe

cluster1::> vserver security trace filter show -vserver vs1 -index 2
                                 Vserver: vs1
                            Filter Index: 2
              Client IP Address to Match: -
                                    Path: /dir1/dir2/file.txt
                       Windows User Name: mydomain\joe
                          UNIX User Name: -
                      Trace Allow Events: yes
                          Filter Enabled: enabled
               Minutes Filter is Enabled: 60
----