---
permalink: nas-audit/create-fpolicy-external-engine-task.html 
sidebar: sidebar 
keywords: create, fpolicy, external engine 
summary: FPolicy設定の作成を開始するには、外部エンジンを作成する必要があります。外部エンジンは、FPolicyが外部FPolicyサーバへの接続を確立および管理する方法を定義します。内部のONTAPエンジン（標準の外部エンジン）を単純なファイルブロッキングに使用している設定の場合は、FPolicy外部エンジンを別途設定する必要はなく、この手順を実行する必要もありません。 
---
= FPolicy外部エンジンの作成
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
FPolicy設定の作成を開始するには、外部エンジンを作成する必要があります。外部エンジンは、FPolicyが外部FPolicyサーバへの接続を確立および管理する方法を定義します。内部のONTAPエンジン（標準の外部エンジン）を単純なファイルブロッキングに使用している設定の場合は、FPolicy外部エンジンを別途設定する必要はなく、この手順を実行する必要もありません。

.必要なもの
link:fpolicy-external-engine-config-worksheet-reference.html["外部エンジン"]ワークシートを完成させる必要があります。

.タスクの内容
外部エンジンがMetroCluster設定で使用されている場合は、ソースサイトでFPolicyサーバのIPアドレスをプライマリサーバとして指定する必要があります。デスティネーションサイトのFPolicyサーバのIPアドレスは、セカンダリサーバとして指定する必要があります。

.手順
. コマンドを使用してFPolicy外部エンジンを作成し `vserver fpolicy policy external-engine create`ます。
+
次のコマンドは、Storage Virtual Machine（SVM）vs1.example.com上に外部エンジンを作成します。FPolicyサーバとの外部通信に認証は必要ありません。

+
`vserver fpolicy policy external-engine create -vserver-name vs1.example.com -engine-name engine1 -primary-servers 10.1.1.2,10.1.1.3 -port 6789 -ssl-option no-auth`

. コマンドを使用してFPolicy外部エンジンの設定を確認します `vserver fpolicy policy external-engine show`。
+
次のコマンドは、SVM vs1.example.comで設定されているすべての外部エンジンに関する情報を表示します。

+
`vserver fpolicy policy external-engine show -vserver vs1.example.com`

+
[listing]
----

                                Primary        Secondary          External
Vserver            Engine       Servers        Servers       Port Engine Type
---------------    -----------  -------------- ----------- ------ -----------
vs1.example.com    engine1      10.1.1.2,      -             6789 synchronous
                                10.1.1.3
----
+
次のコマンドは、 SVM vs1.example.com 上の「 engine1 」という外部エンジンに関する詳細情報を表示します。

+
`vserver fpolicy policy external-engine show -vserver vs1.example.com -engine-name engine1`

+
[listing]
----

                              Vserver: vs1.example.com
                               Engine: engine1
              Primary FPolicy Servers: 10.1.1.2, 10.1.1.3
       Port Number of FPolicy Service: 6789
            Secondary FPolicy Servers: -
                 External Engine Type: synchronous
SSL Option for External Communication: no-auth
           FQDN or Custom Common Name: -
         Serial Number of Certificate: -
                Certificate Authority: -
----

