---
permalink: nas-audit/create-auditing-config-task.html 
sidebar: sidebar 
keywords: create, audit, configuration 
summary: ファイルおよびディレクトリイベントの監査を開始する前に、監査の設定をStorage Virtual Machine（SVM）で作成する必要があります。 
---
= 監査の設定を作成する
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Storage Virtual Machine（SVM）上でファイルとディレクトリの監査の設定を作成するには、使用可能な設定オプションについて理解し、設定を計画し、設定を行って有効にします。その後、監査の設定に関する情報を表示して、設定した設定が適切かどうかを確認できます。

ファイルおよびディレクトリイベントの監査を開始する前に、監査の設定をStorage Virtual Machine（SVM）で作成する必要があります。

.開始する前に
集約型アクセスポリシーステージングの監査の設定を作成する場合は、SVM上にSMBサーバが存在している必要があります。

[NOTE]
====
* 監査の設定では、SMBサーバでダイナミックアクセス制御を有効にしなくても集約型アクセスポリシーのステージングを有効にできますが、集約型アクセスポリシーのステージングイベントはダイナミックアクセス制御が有効になっている場合にのみ生成されます。
+
ダイナミックアクセス制御はSMBサーバオプションを使用して有効にします。デフォルトでは有効になっていません。

* コマンドのフィールドの引数が無効な場合（フィールドのエントリが無効である、エントリが重複している、エントリがないなど）、コマンドは監査フェーズの前に失敗します。
+
この場合、監査レコードは生成されません。



====
.タスクの内容
SVMがSVMディザスタリカバリのソースである場合、デスティネーションパスをルートボリュームに配置することはできません。

.ステップ
. 計画ワークシートの情報を使用して、ログサイズまたはスケジュールに基づいて監査ログのローテーションを行うための監査の設定を作成します。
+
[cols="30,70"]
|===


| 監査ログのローテーションの基準 | 入力するコマンド 


 a| 
ログサイズ
 a| 
`vserver audit create -vserver vserver_name -destination path -events [{file-ops|cifs-logon-logoff|cap-staging|file-share|authorization-policy-change|user-account|security-group|authorization-policy-change}] [-format {xml|evtx}] [-rotate-limit integer] [-rotate-size {integer[KB|MB|GB|TB|PB]}]`



 a| 
スケジュール
 a| 
`vserver audit create -vserver vserver_name -destination path -events [{file-ops|cifs-logon-logoff|cap-staging}] [-format {xml|evtx}] [-rotate-limit integer] [-rotate-schedule-month chron_month] [-rotate-schedule-dayofweek chron_dayofweek] [-rotate-schedule-day chron_dayofmonth] [-rotate-schedule-hour chron_hour] -rotate-schedule-minute chron_minute`

[NOTE]
====
 `-rotate-schedule-minute`時間に基づく監査ログのローテーションを設定する場合、パラメータは必須です。

====
|===


.例
次の例は、サイズに基づくローテーションを使用してファイル操作とSMBログオンおよびログオフイベント（デフォルト）を監査する監査の設定を作成します。ログ形式は（デフォルト）です `EVTX`。ログはディレクトリに保存され `/audit_log`ます。ログファイルの最大サイズはです `200 MB`。ログは、サイズが200MBに達するとローテーションされます。

[listing]
----
cluster1::> vserver audit create -vserver vs1 -destination /audit_log -rotate-size 200MB
----
次の例は、サイズに基づくローテーションを使用してファイル操作とSMBログオンおよびログオフイベント（デフォルト）を監査する監査の設定を作成します。ログ形式は（デフォルト）です `EVTX`。ログはディレクトリに保存され `/cifs_event_logs`ます。ログファイルのサイズの上限は `100 MB`（デフォルト）、ログのローテーションの上限は次のとおり `5`です。

[listing]
----
cluster1::> vserver audit create -vserver vs1 -destination /cifs_event_logs -rotate-limit 5
----
次の例は、時間に基づくローテーションを使用してファイル操作、CIFSのログオンおよびログオフイベント、集約型アクセスポリシーのステージングイベントを監査する監査の設定を作成します。ログ形式は（デフォルト）です `EVTX`。監査ログのローテーションは、毎月、すべての曜日の午後12時30分に実行されます。ログのローテーションの上限は次のとおりです `5`。

[listing]
----
cluster1::> vserver audit create -vserver vs1 -destination /audit_log -events file-ops,cifs-logon-logoff,file-share,audit-policy-change,user-account,security-group,authorization-policy-change,cap-staging -rotate-schedule-month all -rotate-schedule-dayofweek all -rotate-schedule-hour 12 -rotate-schedule-minute 30 -rotate-limit 5
----
.関連情報
* link:enable-audit-svm-task.html["SVMで監査を有効にする"]
* link:verify-auditing-config-task.html["監査の設定を確認する"]

