---
permalink: nas-audit/create-auditing-config-task.html 
sidebar: sidebar 
keywords: create, audit, configuration 
summary: ファイルおよびディレクトリイベントの監査を開始する前に、監査の設定を Storage Virtual Machine （ SVM ）で作成する必要があります。 
---
= 監査の設定を作成します
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Storage Virtual Machine （ SVM ）上でファイルとディレクトリの監査の設定を作成する作業には、使用可能な設定オプションの理解、設定の計画、設定の実行および有効化が含まれます。その後、監査の設定に関する情報を表示して、設定した内容が適切であることを確認できます。

ファイルおよびディレクトリイベントの監査を開始する前に、監査の設定を Storage Virtual Machine （ SVM ）で作成する必要があります。

.作業を開始する前に
集約型アクセスポリシーステージングの監査の設定を作成する場合は、SVM上にSMBサーバが存在している必要があります。

[NOTE]
====
* SMB サーバでダイナミックアクセス制御を有効にせずに、監査の設定で集約型アクセスポリシーのステージングを有効にすることはできますが、集約型アクセスポリシーのステージングイベントが生成されるのは、ダイナミックアクセス制御が有効になっている場合のみです。
+
ダイナミックアクセス制御はSMBサーバオプションを使用して有効にします。デフォルトでは有効になっていません。

* コマンド内のフィールドの引数が無効な場合、たとえばフィールドの無効なエントリ、重複するエントリ、存在しないエントリなどが考えられます。その場合、監査フェーズの前にコマンドが失敗します。
+
この場合、監査レコードは生成されません。



====
.このタスクについて
SVM が SVM ディザスタリカバリソースである場合、デスティネーションパスをルートボリューム上にすることはできません。

.ステップ
. 計画ワークシートの情報を使用して、ログサイズまたはスケジュールに基づいて監査ログのローテーションを行うための監査の設定を作成します。
+
[cols="30,70"]
|===


| 監査ログのローテーションの基準 | 入力するコマンド 


 a| 
ログサイズ
 a| 
`vserver audit create -vserver vserver_name -destination path -events [{file-ops|cifs-logon-logoff|cap-staging|file-share|authorization-policy-change|user-account|security-group|authorization-policy-change}] [-format {xml|evtx}] [-rotate-limit integer] [-rotate-size {integer[KB|MB|GB|TB|PB]}]`



 a| 
スケジュール
 a| 
`vserver audit create -vserver vserver_name -destination path -events [{file-ops|cifs-logon-logoff|cap-staging}] [-format {xml|evtx}] [-rotate-limit integer] [-rotate-schedule-month chron_month] [-rotate-schedule-dayofweek chron_dayofweek] [-rotate-schedule-day chron_dayofmonth] [-rotate-schedule-hour chron_hour] -rotate-schedule-minute chron_minute`

[NOTE]
====
。 `-rotate-schedule-minute` 時間に基づく監査ログのローテーションを設定する場合は、パラメータが必須です。

====
|===


.例
次の例は、サイズに基づくローテーションを使用してファイル操作とSMBログオンおよびログオフイベント（デフォルト）を監査する監査の設定を作成します。ログの形式はです `EVTX` （デフォルト）。ログはに保存されます `/audit_log` ディレクトリ。ログファイルの最大サイズはです `200 MB`。ログのサイズが 200MB になると、ログのローテーションが実行されます。

[listing]
----
cluster1::> vserver audit create -vserver vs1 -destination /audit_log -rotate-size 200MB
----
次の例は、サイズに基づくローテーションを使用してファイル操作とSMBログオンおよびログオフイベント（デフォルト）を監査する監査の設定を作成します。ログの形式はです `EVTX` （デフォルト）。ログはに保存されます `/cifs_event_logs` ディレクトリ。ログファイルの最大サイズはです `100 MB` （デフォルト）。ログのローテーションの上限はです `5`：

[listing]
----
cluster1::> vserver audit create -vserver vs1 -destination /cifs_event_logs -rotate-limit 5
----
次の例は、時間に基づくローテーションを使用してファイル操作、 CIFS ログオンおよびログオフイベント、集約型アクセスポリシーのステージングイベントを監査する監査の設定を作成します。ログの形式はです `EVTX` （デフォルト）。監査ログのローテーションが毎月、午後 12 時 30 分に実行されますそして毎日、午後 12 ： 30 に実行されます。ログのローテーションの上限はです `5`：

[listing]
----
cluster1::> vserver audit create -vserver vs1 -destination /audit_log -events file-ops,cifs-logon-logoff,file-share,audit-policy-change,user-account,security-group,authorization-policy-change,cap-staging -rotate-schedule-month all -rotate-schedule-dayofweek all -rotate-schedule-hour 12 -rotate-schedule-minute 30 -rotate-limit 5
----