---
permalink: nas-audit/display-enabled-fpolicy-policies-task.html 
sidebar: sidebar 
keywords: display, information, enabled fpolicy policies 
summary: 有効なFPolicyポリシーに関する情報を表示して、使用するように設定されている外部エンジン、ポリシーの優先度、およびFPolicyポリシーが関連付けられているStorage Virtual Machine（SVM）を確認できます。 
---
= 有効なFPolicyポリシーに関する情報を表示する
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
有効なFPolicyポリシーに関する情報を表示して、使用するように設定されている外部エンジン、ポリシーの優先度、およびFPolicyポリシーが関連付けられているStorage Virtual Machine（SVM）を確認できます。

.タスクの内容
いずれのパラメータも指定しない場合、次の情報が表示されます。

* SVM名
* ポリシー名
* ポリシーの優先度


コマンドパラメータを使用すると、指定した条件でコマンドの出力をフィルタリングできます。

.ステップ
. 適切なコマンドを使用して、有効なFPolicyポリシーに関する情報を表示します。
+
[cols="35,65"]
|===


| 情報を表示する有効なポリシー | 入力するコマンド 


 a| 
クラスタのポリシー
 a| 
`vserver fpolicy show-enabled`



 a| 
指定したSVMのポリシー
 a| 
`vserver fpolicy show-enabled -vserver vserver_name`



 a| 
指定したポリシー名のポリシー
 a| 
`vserver fpolicy show-enabled -policy-name policy_name`



 a| 
指定したシーケンス番号のファイル
 a| 
`vserver fpolicy show-enabled -priority integer`

|===


.例
次の例は、クラスタの有効なFPolicyポリシーに関する情報を表示します。

[listing]
----
cluster1::> vserver fpolicy show-enabled
Vserver                 Policy Name               Priority

----------------------- ------------------------- ----------
vs1.example.com         pol_native                native
vs1.example.com         pol_native2               native
vs1.example.com         pol1                      2
vs1.example.com         pol2                      4
----