---
permalink: nas-audit/enable-disable-fpolicy-policies-task.html 
sidebar: sidebar 
keywords: enable, disable, fpolicy policies 
summary: 設定の完了後にFPolicyポリシーを有効にできます。ポリシーを有効にすると、優先度が設定され、ポリシーのファイルアクセスの監視が開始されます。ポリシーのファイルアクセスの監視を停止するには、FPolicyポリシーを無効にします。 
---
= FPolicyポリシーを有効または無効にする
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
設定の完了後にFPolicyポリシーを有効にできます。ポリシーを有効にすると、優先度が設定され、ポリシーのファイルアクセスの監視が開始されます。ポリシーのファイルアクセスの監視を停止するには、FPolicyポリシーを無効にします。

.開始する前に
FPolicyポリシーを有効にする前に、FPolicyの設定を完了しておく必要があります。

.タスクの内容
* Storage Virtual Machine（SVM）で複数のポリシーを有効にし、複数のポリシーを同じファイルアクセスイベントに登録している場合は、優先度が使用されます。
* 標準のエンジン設定を使用するポリシーは、ポリシーを有効にするときに割り当てられたシーケンス番号に関係なく、他のエンジンのポリシーよりも優先度が高くなります。
* FPolicyポリシーの優先度を変更する場合は、ポリシーを無効にしてから、新しいシーケンス番号を使用して再度有効にする必要があります。


.ステップ
. 適切な操作を実行します。
+
[cols="35,65"]
|===


| 状況 | 入力するコマンド 


 a| 
FPolicyポリシーを有効にする
 a| 
`vserver fpolicy enable -vserver-name vserver_name -policy-name policy_name -sequence-number integer`



 a| 
FPolicyポリシーを無効にする
 a| 
`vserver fpolicy disable -vserver-name vserver_name -policy-name policy_name`

|===

