---
permalink: nas-audit/fpolicy-config-types-concept.html 
sidebar: sidebar 
keywords: fpolicy, configuration types 
summary: FPolicy の基本設定には 2 つのタイプがあります。一方の設定では、通知を受けて処理と対応を行う外部 FPolicy サーバを使用します。もう一方の設定では外部 FPolicy サーバを使用しません。代わりに、 ONTAP 内部のネイティブ FPolicy サーバを使用して、拡張子に基づく単純なファイルブロッキングを行います。 
---
= FPolicy の設定タイプ
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
FPolicy の基本設定には 2 つのタイプがあります。一方の設定では、通知を受けて処理と対応を行う外部 FPolicy サーバを使用します。もう一方の設定では外部 FPolicy サーバを使用しません。代わりに、 ONTAP 内部のネイティブ FPolicy サーバを使用して、拡張子に基づく単純なファイルブロッキングを行います。

* * 外部 FPolicy サーバ構成 *
+
FPolicy サーバに通知が送信され、そのサーバが要求をスクリーニングし、要求されたファイル操作をノードで許可するかどうかを決定するルールを適用します。同期ポリシーの場合、 FPolicy サーバは、要求されたファイル操作を許可またはブロックする応答をノードに送信します。

* * ネイティブ FPolicy サーバ構成 *
+
通知は内部的にスクリーニングされます。要求は、 FPolicy スコープで設定されているファイル拡張子に基づいて許可または拒否されます。





== を使用してネイティブ FPolicy 設定を作成する場合

ネイティブの FPolicy 設定では、 ONTAP に組み込まれている FPolicy エンジンを使用して、ファイルの拡張子に基づいてファイル操作を監視およびブロックします。この解決策には、外部 FPolicy サーバ（ FPolicy サーバ）は必要ありません。ネイティブファイルブロッキングの設定は、このシンプルな解決策がすべて必要な場合に適しています。

ネイティブファイルブロッキングを使用すると、設定した処理およびフィルタリングイベントに一致するすべてのファイル処理を監視したうえで、特定の拡張子を持つファイルへのアクセスを拒否することができます。これがデフォルトの設定です。

この設定では、ファイルの拡張子のみに基づいてファイルへのアクセスをブロックすることができます。たとえば、「 m 」という拡張子を含むファイルをブロックするには、「 m p3 」というターゲットファイル拡張子を持つ特定の操作の通知を送信するようにポリシーを設定します。このポリシーは、通知を生成する操作に対する「 m p3 」ファイル要求を拒否するように設定されています。

次の環境ネイティブ FPolicy の設定：

* FPolicy サーバベースファイルスクリーニングでサポートされているフィルタとプロトコルのセットが、ネイティブファイルブロッキングでもサポートされます。
* ネイティブファイルブロッキングと FPolicy サーバベースファイルスクリーニングアプリケーションは同時に設定できます。
+
そのためには、 Storage Virtual Machine （ SVM ）に 2 つの FPolicy ポリシーを設定します。 1 つはネイティブファイルブロッキングのために設定したポリシーで、もう 1 つは FPolicy のサーバベースのファイルスクリーニングのために設定したポリシーです。

* ネイティブファイルブロッキング機能では、ファイルの内容ではなく、拡張子のみに基づいてファイルがスクリーニングされます。
* シンボリックリンクの場合、ネイティブファイルブロッキングは、ルートファイルのファイル拡張子を使用します。




== 外部 FPolicy サーバを使用する設定を作成する状況

通知の処理と管理に外部 FPolicy サーバを使用する FPolicy 設定は、ファイル拡張子に基づく単純なファイルブロッキング以上が必要なユースケースに対して、堅牢なソリューションを提供します。

ファイルアクセスイベントの監視と記録、クォータサービスの提供、単純なファイル拡張子以外の条件に基づくファイルブロッキング、階層型ストレージ管理アプリケーションを使用したデータ移行サービスの提供など、目的に応じて外部 FPolicy サーバを使用する設定を作成する必要があります。 または、 Storage Virtual Machine （ SVM ）の一部のデータのみを監視するきめ細かいポリシーセットを提供することもできます。
