---
permalink: nas-audit/modify-security-trace-filters-task.html 
sidebar: sidebar 
keywords: modify, security trace filters 
summary: トレースされたアクセスイベントを特定する際に使用するオプションのフィルタパラメータを変更するには、既存のセキュリティトレースフィルタを変更します。 
---
= セキュリティトレースフィルタを変更します。
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
トレースされたアクセスイベントを特定する際に使用するオプションのフィルタパラメータを変更するには、既存のセキュリティトレースフィルタを変更します。

.タスクの内容
変更するセキュリティトレースフィルタを特定するには、フィルタを適用したStorage Virtual Machine（SVM）の名前とフィルタのインデックス番号を指定します。オプションのフィルタパラメータはすべて変更できます。

.手順
. セキュリティトレースフィルタを変更します。
+
`vserver security trace filter modify -vserver vserver_name -index index_numberfilter_parameters`

+
** `vserver_name`は、セキュリティトレースフィルタを適用するSVMの名前です。
** `index_number`は、フィルタに適用するインデックス番号です。このパラメータに指定できる値は1~10です。
** `filter_parameters`は、オプションのフィルタパラメータのリストです。


. セキュリティトレースフィルタエントリを確認します。
+
`vserver security trace filter show -vserver vserver_name -index index_number`



.例
次の例は、インデックス番号 1 のセキュリティトレースフィルタを変更します。このフィルタは、任意のIPアドレスから共有パスを持つファイルにアクセスしているすべてのユーザのイベントをトレースし `\\server\share1\dir1\dir2\file.txt`ます。フィルタでは、オプションに完全なパスが使用され `-path`ます。許可イベントと拒否イベントをトレースします。

[listing]
----
cluster1::> vserver security trace filter modify -vserver vs1 -index 1 -path /dir1/dir2/file.txt -trace-allow yes

cluster1::> vserver security trace filter show -vserver vs1 -index 1
                                 Vserver: vs1
                            Filter Index: 1
              Client IP Address to Match: -
                                    Path: /dir1/dir2/file.txt
                       Windows User Name: -
                          UNIX User Name: -
                      Trace Allow Events: yes
                          Filter Enabled: enabled
               Minutes Filter is Enabled: 60
----