---
permalink: nas-audit/persistent-stores.html 
sidebar: sidebar 
keywords: overview, persistent store, fpolicy 
summary: ONTAP 9.14.1以降では、FPolicyで永続的ストアを設定して、SVM内の非同期（必須ではない）ポリシーのファイルアクセスイベントをキャプチャできます。永続的ストアを使用すると、クライアントI/O処理とFPolicy通知処理を分離して、クライアントのレイテンシを低減できます。同期および非同期の必須構成はサポートされていません。 
---
= FPolicyの永続的ストア
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
ONTAP 9.14.1以降では、FPolicyで永続的ストアを設定して、SVM内の非同期（必須ではない）ポリシーのファイルアクセスイベントをキャプチャすることができます。永続的ストアを使用すると、クライアントI/O処理とFPolicy通知処理を分離して、クライアントのレイテンシを低減できます。同期（必須または必須でない）および非同期の必須構成はサポートされていません。

この機能は、FPolicy外部モードでのみ使用できます。この機能をサポートするには、使用するパートナーアプリケーションが必要です。このFPolicy設定がサポートされていることをパートナーと協力して確認する必要があります。



== ベストプラクティス

クラスタ管理者は、FPolicyが有効になっている各SVMで永続的ストア用のボリュームを設定する必要があります。永続ストアが設定されている場合、一致するすべてのFPolicyイベントがキャプチャされ、FPolicyパイプライン内でさらに処理されて外部サーバに送信されます。

永続ストアは、予期しないリブートが発生した場合、またはFPolicyを無効にして再度有効にした場合に、最後のイベントを受信した時点のままになります。テイクオーバー処理が完了すると、新しいイベントがパートナーノードに格納されて処理されます。ギブバック処理のあと、ノードのテイクオーバーの発生時に残っている可能性がある未処理のイベントの処理が永続的ストアで再開されます。ライブイベントは、未処理のイベントよりも優先されます。

永続的ストアボリュームが同じSVM内のノード間で移動した場合、まだ処理されていない通知も新しいノードに移動します。再実行する必要があります `fpolicy persistent-store create` ボリュームの移動後にいずれかのノードでコマンドを実行し、保留中の通知が外部サーバに配信されるようにします。

永続的ストアボリュームはSVM単位でセットアップします。FPolicyが有効なSVMごとに、永続的ストアボリュームを作成する必要があります。

FPolicyで最大トラフィック量を監視すると想定されるLIFがあるノードに永続的ストアボリュームを作成します。

永続的ストアに蓄積された通知がプロビジョニングされたボリュームのサイズを超えると、FPolicyは該当するEMSメッセージを含む受信通知を破棄し始めます。

永続的なストアのボリューム名とボリューム作成時に指定したジャンクションパスが一致している必要があります。

Snapshotポリシーをに設定 `none` 対象のボリュームではなく `default`。これは、Snapshotが誤ってリストアされて現在のイベントが失われることがないようにし、イベント処理が重複しないようにするためです。

永続的なイベントレコードが誤って破損したり削除されたりしないように、外部ユーザプロトコルアクセス（CIFS / NFS）で永続的ストアボリュームにアクセスできないようにします。これには、FPolicyを有効にしたあとにONTAPでボリュームをアンマウントしてジャンクションパスを削除すると、ユーザプロトコルアクセスができなくなります。

詳細については、を参照してください link:https://docs.netapp.com/us-en/ontap/nas-audit/create-persistent-stores.html["永続ストアの作成"]。
