---
permalink: nas-audit/plan-fpolicy-scope-config-concept.html 
sidebar: sidebar 
keywords: plan, fpolicy, scope, configuration 
summary: FPolicyスコープを設定する前に、スコープを作成することの意味を理解する必要があります。また、スコープの構成要素を理解する必要があります。さらに、スコープの優先規則についても理解する必要があります。この情報は、設定する値を計画するのに役立ちます。 
---
= ONTAP FPolicyスコープ設定について学ぶ
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
FPolicyスコープを設定する前に、スコープを作成することの意味を理解する必要があります。また、スコープの構成要素を理解する必要があります。さらに、スコープの優先規則についても理解する必要があります。この情報は、設定する値を計画するのに役立ちます。



== FPolicyスコープを作成することの意味

FPolicyスコープを作成することは、FPolicyポリシーの適用範囲を定義することを意味します。Storage Virtual Machine（SVM）は基本の適用範囲です。FPolicyポリシーのスコープを作成する場合、スコープが適用されるFPolicyポリシーを定義する必要があり、さらにスコープを適用するSVMを指定する必要があります。

指定したSVM内にスコープをさらに制限するためのパラメータが数多くあります。スコープに含めるものを指定したり、スコープから除外するものを指定することでスコープを制限することができます。有効なポリシーにスコープを適用すると、ポリシー イベントのチェックがこのコマンドで定義したスコープに適用されます。

「`include`」オプションで一致が見つかったファイル アクセス イベントに対して通知が生成されます。「`exclude`」オプションで一致が見つかったファイル アクセス イベントに対しては通知は生成されません。

FPolicyスコープの構成では、次の設定情報を定義します。

* SVM名
* ポリシー名
* 監視対象または対象外にする共有
* 監視対象または対象外にするエクスポート ポリシー
* 監視対象または対象外にするボリューム
* 監視対象または対象外にするファイル拡張子
* ディレクトリ オブジェクトのファイル拡張子を監視対象にするかどうか


[NOTE]
====
クラスタのFPolicyポリシーのスコープには、特に考慮すべき事項があります。クラスタのFPolicyポリシーは、クラスタ管理者が管理SVM用に作成するポリシーです。クラスタ管理者がそのクラスタのFPolicyポリシーのスコープも作成する場合、SVM管理者はそれと同じポリシーのスコープを作成することはできません。ただし、クラスタ管理者がクラスタのFPolicyポリシーのスコープを作成しない場合は、すべてのSVM管理者がそのクラスタ ポリシーのスコープを作成することができます。SVM管理者がそのクラスタのFPolicyポリシーのスコープを作成した場合、クラスタ管理者はそれ以降、その同じクラスタ ポリシーのクラスタ スコープを作成することはできません。これは、クラスタ管理者が同じクラスタ ポリシーのスコープを上書きできないためです。

====


== スコープの優先規則について

スコープの構成では、次の優先規則が適用されます。

*  `-shares-to-include`パラメータに共有が含まれていて、共有の親ボリュームが `-volumes-to-exclude`パラメータに含まれている場合、 `-volumes-to-exclude`は `-shares-to-include`よりも優先されます。
* エクスポート ポリシーが `-export-policies-to-include`パラメータに含まれており、エクスポート ポリシーの親ボリュームが `-volumes-to-exclude`パラメータに含まれている場合、 `-volumes-to-exclude`は `-export-policies-to-include`よりも優先されます。
* 管理者は `-file-extensions-to-include`リストと `-file-extensions-to-exclude`リストの両方を指定できます。
+
 `-file-extensions-to-exclude`パラメータは、 `-file-extensions-to-include`パラメータがチェックされる前にチェックされます。





== FPolicyスコープの設定内容

以下はFPolicyスコープの設定に使用できるパラメータのリストです。設定を計画する際に使用してください。

[NOTE]
====
スコープに含める共有、エクスポート ポリシー、ボリューム、およびファイル拡張子を設定する際、include および exclude パラメータに「`?`" and "`*`」などのメタ文字を含めることができます。正規表現の使用はサポートされていません。

====
[cols="70,30"]
|===


| 情報の種類 | オプション 


 a| 
_SVM_

FPolicyスコープを作成するSVMの名前を指定します。

各FPolicy設定は、単一のSVM内で定義されます。FPolicyポリシーの構成要素となる外部エンジン、ポリシー イベント、ポリシーのスコープ、およびポリシーを、すべて同じSVMに関連付ける必要があります。
 a| 
`-vserver` `vserver_name`



 a| 
_ポリシー名_

スコープをアタッチするFPolicyポリシーの名前を指定します。既存のFPolicyポリシーを指定する必要があります。
 a| 
`-policy-name` `policy_name`



 a| 
_含める共有_

カンマで区切って複数の共有を指定し、FPolicyポリシーの監視対象となるスコープに含めます。
 a| 
`-shares-to-include` `share_name`, ...



 a| 
_除外する共有_

カンマで区切って複数の共有を指定し、FPolicyポリシーの監視対象となるスコープから除外します。
 a| 
`-shares-to-exclude` `share_name`, ...



 a| 
_含めるボリューム_ スコープが適用される FPolicy ポリシーを監視するボリュームのコンマ区切りリストを指定します。
 a| 
`-volumes-to-include` `volume_name`, ...



 a| 
_除外するボリューム_

カンマで区切って複数のボリュームを指定し、FPolicyポリシーの監視対象となるスコープから除外します。
 a| 
`-volumes-to-exclude` `volume_name`、...



 a| 
_含めるエクスポート ポリシー_

カンマで区切って複数のエクスポート ポリシーを指定し、FPolicyポリシーの監視対象となるスコープに含めます。
 a| 
`-export-policies-to-include` `export_policy_name`、...



 a| 
_除外する Export ポリシー_

カンマで区切って複数のエクスポート ポリシーを指定し、FPolicyポリシーの監視対象となるスコープから除外します。
 a| 
`-export-policies-to-exclude` `export_policy_name`, ...



 a| 
_含めるファイル拡張子_

カンマで区切って複数のファイル拡張子を指定し、FPolicyポリシーの監視対象となるスコープに含めます。
 a| 
`-file-extensions-to-include` `file_extensions`, ...



 a| 
除外するファイル拡張子

カンマで区切って複数のファイル拡張子を指定し、FPolicyポリシーの監視対象となるスコープから除外します。
 a| 
`-file-extensions-to-exclude` `file_extensions`, ...



 a| 
_ディレクトリのファイル拡張子チェックは有効になっていますか？_

ファイル名拡張子のチェックをディレクトリ オブジェクトにも適用するかどうかを指定します。このパラメータを `true`に設定した場合、ディレクトリ オブジェクトは通常のファイルと同じ拡張子チェックの対象となります。このパラメータを `false`に設定した場合、ディレクトリ名の拡張子は照合されず、名前の拡張子が一致しない場合でもディレクトリに関する通知が送信されます。

スコープが割り当てられている FPolicy ポリシーがネイティブ エンジンを使用するように設定されている場合、このパラメータを `true`に設定する必要があります。
 a| 
`-is-file-extension-check-on-directories-enabled` {`true`| `false`|}

|===