---
permalink: nas-audit/plan-fpolicy-policy-config-concept.html 
sidebar: sidebar 
keywords: plan, fpolicy, policy, configuration 
summary: FPolicy ポリシーを設定する前に、ポリシーの作成時に必要なパラメータや、特定のオプションパラメータを設定する理由について理解しておく必要があります。この情報は、各パラメータに設定する値を決定するのに役立ちます。 
---
= FPolicy ポリシーの設定の概要を計画
:icons: font
:imagesdir: ../media/


[role="lead"]
FPolicy ポリシーを設定する前に、ポリシーの作成時に必要なパラメータや、特定のオプションパラメータを設定する理由について理解しておく必要があります。この情報は、各パラメータに設定する値を決定するのに役立ちます。

FPolicy ポリシーを作成する際には、このポリシーと次のポリシーを関連付けます。

* Storage Virtual Machine （ SVM ）
* 1 つ以上の FPolicy イベント
* FPolicy 外部エンジン


いくつかのオプションポリシー設定を構成することもできます。



== FPolicy ポリシーの設定項目

FPolicy ポリシーで使用できる必須パラメータとオプションパラメータを次に示します。これは設定について計画するときに役立ちます。

[cols="4*"]
|===
| 情報のタイプ | オプション | 必須 | デフォルト 


 a| 
SVM 名 _

FPolicy ポリシーを作成する SVM の名前を指定します。
 a| 
「 -vserver `vserver_name` 」
 a| 
はい。
 a| 
なし



 a| 
_ ポリシー名 _

FPolicy ポリシーの名前を指定します。

この名前に指定できる文字数は最大 256 文字です。

[NOTE]
====
MetroCluster または SVM ディザスタリカバリ設定でポリシーを設定する場合、この名前は最大 200 文字にする必要があります。

====
名前には、次の ASCII 文字の任意の組み合わせを含めることができます。

* 「 a 」 ～ 「 z 」
* 「 A 」 ～ 「 Z 」
* 0 ～ 9
* "`_`","`-`","`.")

 a| 
「 -policy-name 」「 policy_name 」
 a| 
はい。
 a| 
なし



 a| 
_ イベント名 _

FPolicy ポリシーに関連付けるイベントをカンマ区切りのリストで指定します。

* 1 つのポリシーに複数のイベントを関連付けることができます。
* イベントはプロトコルに固有です。
* 1 つのポリシーで複数のプロトコルのファイルアクセスイベントを監視するには、ポリシーで監視する各プロトコルのイベントを作成し、それらのイベントをポリシーに関連付けます。
* 既存のイベントを指定する必要があります。

 a| 
`-events`event_name`,...
 a| 
はい。
 a| 
なし



 a| 
_ 外部エンジン名 _

FPolicy ポリシーに関連付ける外部エンジンの名前を指定します。

* 外部エンジンには、ノードから FPolicy サーバに通知を送信するための必要な情報が格納されています。
* 単純なファイルブロッキングを行うために ONTAP の標準の外部エンジンを使用したり、より高度なファイルブロッキングとファイル管理を行うために外部 FPolicy サーバ（ FPolicy サーバ）を使用するように設定された外部エンジンを使用したりするように FPolicy を設定できます。
* 標準の外部エンジンを使用する場合は、このパラメータに値を指定しないか、値として「 native 」を指定できます。
* FPolicy サーバを使用する場合は、外部エンジンの設定がすでに存在している必要があります。

 a| 
「 -engine 」「 engine_name 」
 a| 
○（ポリシーで内部の ONTAP 標準エンジンを使用しない場合）
 a| 
「ネイティブ」



 a| 
_ は必須のスクリーニングです _

必須のファイルアクセススクリーニングを要求するかどうかを指定します。

* 必須のスクリーニング設定は、プライマリサーバとセカンダリサーバがすべて停止した場合や、指定した時間内に FPolicy サーバからの応答を得られない場合に、ファイルアクセスイベントをどのように処理するかを決定します。
* true に設定すると ' ファイル・アクセス・イベントは拒否されます
* false に設定すると ' ファイル・アクセス・イベントが許可されます

 a| 
`-is-Mandatory `{`true|`false`}
 a| 
いいえ
 a| 
「真」



 a| 
権限付きアクセスを許可する _

権限付きデータ接続による監視対象のファイルやフォルダに対する権限付きアクセスを FPolicy サーバに許可するかどうかを指定します。

設定されている場合、 FPolicy サーバは権限付きデータ接続を使用して、監視対象データが格納されている SVM のルートにあるファイルにアクセスできます。

権限付きデータアクセスの場合は、クラスタで CIFS のライセンスが有効になっていて、 FPolicy サーバへの接続に使用されるすべてのデータ LIF で、「 cifs 」が許可されているプロトコルの 1 つとして設定されている必要があります。

ポリシーで権限付きアクセスを許可する場合は、 FPolicy サーバで権限付きアクセスに使用するアカウントのユーザ名も指定する必要があります。
 a| 
--allow-privileged-access `{`yes`|`no`}
 a| 
No （パススルーリードが有効になっていない場合）
 a| 
「いいえ」



 a| 
_ 特権ユーザ名 _

FPolicy サーバが権限付きデータアクセスで使用するアカウントのユーザ名を指定します。

* このパラメータの値は、「ドメイン \ ユーザ名」の形式にする必要があります。
* allow-privileged-access が「 no 」に設定されている場合、このパラメータの値は無視されます。

 a| 
`-privileged-user-name`user_name`
 a| 
No （権限付きアクセスが有効になっていない場合）
 a| 
なし



 a| 
_allow passthrough-read _

FPolicy サーバによってセカンダリストレージ（オフラインファイル）にアーカイブされているファイルを対象としたパススルーリードサービスを FPolicy サーバが提供できるかどうかを指定します。

* パススルーリードは、オフラインファイルのデータをプライマリストレージにリストアすることなく読み取るための手段です。
+
パススルーリードでは、読み取り要求に応答する前にファイルをプライマリストレージにリコールする必要がないため、応答遅延が短縮されます。また、パススルーリードでは、読み取り要求を満たすためだけにリコールされるファイルによってストレージ領域を浪費する必要がなくなるため、ストレージ効率が最適化されます。

* 有効になっている場合、 FPolicy サーバはパススルーリード専用に開かれている別の権限付きデータチャネルを使用してファイルにデータを提供します。
* パススルーリードを設定する場合は、権限付きアクセスを許可するようにポリシーも設定する必要があります。

 a| 
「 -is-passthrough-read 」が有効になっています
 a| 
いいえ
 a| 
「偽」

|===