---
permalink: nas-audit/plan-auditing-config-concept.html 
sidebar: sidebar 
keywords: plan, audit, configuration, svm, rotate, logs, size, schedule, rotation, dr, disaster recovery 
summary: Storage Virtual Machine （ SVM ）で監査を設定する前に、使用可能な設定オプションを理解し、各オプションに設定する値を計画する必要があります。この情報は、ビジネスニーズを満たす監査の設定に役立ちます。 
---
= 監査の設定を計画
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Storage Virtual Machine （ SVM ）で監査を設定する前に、使用可能な設定オプションを理解し、各オプションに設定する値を計画する必要があります。この情報は、ビジネスニーズを満たす監査の設定に役立ちます。

すべての監査の設定に共通する設定パラメータがあります。

また、統合および変換された監査ログのローテーション時に使用する方法を指定するために使用できるパラメータもあります。監査の設定を行う際には、次の 3 つの方法のいずれかを指定できます。

* ログサイズに基づいてログをローテーションします
+
ログのローテーションに使用されるデフォルトの方法です。

* スケジュールに基づいたログのローテーション
* ログのサイズとスケジュール（先にイベントが発生した方）に基づいてログのローテーションを実行
F


[]
====
ログローテーションの方法を少なくとも 1 つ設定する必要があります。

====


== すべての監査設定に共通するパラメータ

監査の設定の作成時に指定する必要がある 2 つの必須パラメータがあります。また、指定できるオプションのパラメータが 3 つあります。

[cols="40,30,10,10,10"]
|===


| 情報のタイプ | オプション | 必須 | 含める | 値を入力します 


 a| 
SVM 名 _

監査の設定を作成する SVM の名前。SVM はすでに存在している必要があります。
 a| 
`-vserver` `vserver_name`
 a| 
はい。
 a| 
はい。
 a| 



 a| 
_ ログデスティネーションパス _

変換された監査ログを格納するディレクトリを指定します。通常は専用のボリュームまたは qtree です。パスは SVM ネームスペースにすでに存在している必要があります。

パスには、最大 864 文字の文字列を指定できます。パスには読み取り / 書き込みアクセス権が必要です。

パスが有効でない場合、監査の設定コマンドは失敗します。

SVM が SVM ディザスタリカバリソースである場合、ログのデスティネーションパスをルートボリュームにすることはできません。これは、ルートボリュームのコンテンツがディザスタリカバリ先にレプリケートされないためです。

FlexCache ボリュームをログのデスティネーション（ ONTAP 9.7 以降）として使用することはできません。
 a| 
`-destination` `text`
 a| 
はい。
 a| 
はい。
 a| 



 a| 
_ 監査するイベントのカテゴリ _

監査するイベントのカテゴリを指定します。監査できるイベントカテゴリは次のとおりです。

* ファイルアクセスイベント（ SMB と NFSv4 の両方）
* SMBロクオンオヨヒログオフイヘント
* 集約型アクセスポリシーのステージングイベント
+
集約型アクセスポリシーのステージングイベントは、Windows Server 2012 Active Directoryドメイン以降で使用できます。

* ファイル共有カテゴリイベント
* ポリシー変更イベントの監査
* ローカルユーザアカウント管理イベント
* セキュリティグループ管理イベント
* 認証ポリシー変更イベント


デフォルトでは、ファイルアクセスイベントとSMBログオンおよびログオフイベントが監査されます。

*注：*を指定する前に `cap-staging` イベントカテゴリとしては、SVMにSMBサーバが存在している必要があります。SMB サーバでダイナミックアクセス制御を有効にせずに、監査の設定で集約型アクセスポリシーのステージングを有効にすることはできますが、集約型アクセスポリシーのステージングイベントが生成されるのは、ダイナミックアクセス制御が有効になっている場合のみです。ダイナミックアクセス制御はSMBサーバオプションを使用して有効にします。デフォルトでは有効になっていません。
 a| 
`-events` {`file-ops`|`cifs-logon-logoff`|`cap-staging`|`file-share`|`audit-policy-change`|`user-account`|`security-group`|`authorization-policy-change`｝
 a| 
いいえ
 a| 
 a| 



 a| 
_ ログファイル出力形式 _

監査ログの出力形式を指定します。出力形式にはONTAP固有のものを指定できます `XML` またはMicrosoft Windows `EVTX` ログ形式。デフォルトの出力形式はです `EVTX`。
 a| 
`-format` {`xml`|`evtx`｝
 a| 
いいえ
 a| 
 a| 



 a| 
ログファイルのローテーションの上限 _

保持する監査ログファイルの数を指定します。これにより、その数からあふれた最も古いログファイルがローテーションから外されます。たとえば、の値を入力した場合などです `5`では、最後の5つのログファイルが保持されます。

の値 `0` すべてのログファイルが保持されることを示します。デフォルト値は0です。
 a| 
`-rotate-limit` `integer`
 a| 
いいえ
 a| 
 a| 

|===


== 監査イベントログのローテーションをいつ行うかを決定するためのパラメータ

* ログサイズに基づいてログを回転 *

デフォルトでは、サイズに基づいた監査ログのローテーションが行われます。

* デフォルトのログサイズは 100MB です。
* デフォルトのログローテーション方法とデフォルトのログサイズを使用する場合、ログローテーションに関する特定のパラメータを設定する必要はありません。
* ログサイズのみに基づいて監査ログのローテーションを行う場合は、次のコマンドを使用しての設定を解除します `-rotate-schedule-minute` パラメータ： `vserver audit modify -vserver vs0 -destination / -rotate-schedule-minute -`


デフォルトのログサイズを使用しない場合は、を設定できます `-rotate-size` カスタムログサイズを指定するパラメータ：

[cols="40,30,10,10,10"]
|===


| 情報のタイプ | オプション | 必須 | 含める | 値を入力します 


 a| 
_ ログファイルサイズ制限 _

監査ログファイルの最大サイズを指定します。
 a| 
`-rotate-size` {`integer`[KB|MB|GB|TB|PB]｝
 a| 
いいえ
 a| 
 a| 

|===
* スケジュールに基づいてログを回転 *

スケジュールに基づいた監査ログのローテーションを選択した場合は、時間に基づくローテーションパラメータを任意に組み合わせて使用することで、ログのローテーションをスケジュールすることができます。

* 時間に基づくローテーションを使用する場合は、 `-rotate-schedule-minute` パラメータは必須です。
* それ以外の時間ベースのローテーションパラメータは、すべてオプションです。
* ローテーションスケジュールは、時間に関連するすべての値を使用して計算されます。
+
たとえば、のみを指定した場合 `-rotate-schedule-minute` パラメータを指定すると、監査ログファイルのローテーションは、毎月のすべての曜日の毎時間、指定した分に行われます。

* 時間ベースのローテーションパラメータを1つまたは2つだけ指定した場合（例： `-rotate-schedule-month` および `-rotate-schedule-minutes`）を指定すると、ログファイルのローテーションは、指定した月にのみ、すべての曜日の毎時間、指定した分に行われます。
+
たとえば、監査ログのローテーションを、 1 月、 3 月、 8 月の毎週月曜日、水曜日、土曜日の 10 時 30 分に実行するように指定できます

* 両方に値を指定する場合は `-rotate-schedule-dayofweek` および `-rotate-schedule-day`では、これらは独立して考慮されます。
+
たとえば、を指定した場合などです `-rotate-schedule-dayofweek` 金曜日およびとして `-rotate-schedule-day` 13と指定すると、監査ログのローテーションは、13日の金曜日だけでなく、毎週金曜日と指定した月の13日にも実行されます。

* スケジュールのみに基づいて監査ログのローテーションを行う場合は、次のコマンドを使用しての設定を解除します `-rotate-size` パラメータ： `vserver audit modify -vserver vs0 -destination / -rotate-size -`


次に示す使用可能な監査パラメータのリストを使用して、監査イベントログのローテーションのスケジュール設定に使用する値を決定できます。

[cols="40,30,10,10,10"]
|===


| 情報のタイプ | オプション | 必須 | 含める | 値を入力します 


 a| 
ログローテーションスケジュール： Month_

監査ログのローテーションを実行する月を指定します。

有効な値はです `January` から `December`および `all`。たとえば、監査ログのローテーションが 1 月、 3 月、 8 月に行われるように指定できます。
 a| 
`-rotate-schedule-month` `chron_month`
 a| 
いいえ
 a| 
 a| 



 a| 
ログローテーションスケジュール：曜日 _

監査ログのローテーションを実行する日（曜日）を指定します。

有効な値はです `Sunday` から `Saturday`および `all`。たとえば、監査ログのローテーションを火曜日と金曜日に、またはすべての曜日に実行するように指定できます。
 a| 
`-rotate-schedule-dayofweek` `chron_dayofweek`
 a| 
いいえ
 a| 
 a| 



 a| 
ログローテーションスケジュール： Day _

監査ログのローテーションを実行する日にちを指定します。

指定できる値の範囲は、です `1` から `31`。たとえば、監査ログのローテーションを毎月 10 日と 20 日に、またはすべての日に実行するように指定できます。
 a| 
`-rotate-schedule-day` `chron_dayofmonth`
 a| 
いいえ
 a| 
 a| 



 a| 
ログローテーションスケジュール： Hour _

監査ログのローテーションを実行する時間を決めます。

指定できる値の範囲は、です `0` （午前0時）から `23` （午後11時）。を指定します `all` 監査ログのローテーションを1時間ごとに実行します。たとえば、監査ログのローテーションが 6 （午前 6 時）と 18 （午後 6 時）に行われるように指定できます。
 a| 
`-rotate-schedule-hour` `chron_hour`
 a| 
いいえ
 a| 
 a| 



 a| 
ログローテーションスケジュール：分 _

監査ログのローテーションを実行する分を決めます。

指定できる値の範囲は、です `0` 終了： `59`。たとえば、監査ログのローテーションが 30 分に行われるように指定できます。
 a| 
`-rotate-schedule-minute` `chron_minute`
 a| 
スケジュールベースのログローテーションを設定している場合は Yes 、それ以外の場合は No にします
 a| 
 a| 

|===
* ログサイズとスケジュールに基づいてログを回転 *

両方のを設定すると、ログサイズとスケジュールに基づいてログファイルのローテーションを行うことができます `-rotate-size` パラメータと時間ベースのローテーションパラメータを任意の組み合わせで指定できます。例：if `-rotate-size` は10 MBに設定されており `-rotate-schedule-minute` が15に設定されている場合、ログファイルのサイズが10MBに達したとき、または1時間15分ごと（いずれか早い方）にログファイルがローテーションされます。
