---
permalink: nas-audit/plan-fpolicy-policy-config-concept.html 
sidebar: sidebar 
keywords: plan, fpolicy, policy, configuration 
summary: FPolicyポリシーを設定する前に、必要なパラメータと、特定のオプションパラメータを設定する理由を理解しておく必要があります。 
---
= ONTAP FPolicyポリシー設定について学ぶ
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
FPolicyポリシーを設定する前に、ポリシーの作成時に必要なパラメータと、特定のオプションパラメータを設定する理由を理解しておく必要があります。この情報は、各パラメータに設定する値を決定するのに役立ちます。

FPolicyポリシーを作成するときは、このポリシーを次のように関連付けます。

* Storage Virtual Machine（SVM）
* 1つ以上のFPolicyイベント
* FPolicy外部エンジン


いくつかのオプションのポリシー設定を構成することもできます。



== FPolicyポリシーの設定内容

FPolicyポリシーの必須パラメータとオプションパラメータを次に示します。これは、設定を計画するのに役立ちます。

[cols="40,20,20,20"]
|===


| 情報の種類 | オプション | 必須 | デフォルト 


 a| 
SVM 名 _

FPolicyポリシーを作成するSVMの名前を指定します。
 a| 
`-vserver` `vserver_name`
 a| 
〇
 a| 
なし



 a| 
_ ポリシー名 _

FPolicyポリシーの名前を指定します。

名前の最大文字数は256文字です。

[NOTE]
====
MetroClusterまたはSVMディザスタリカバリ設定でポリシーを設定する場合、この名前は最大200文字にする必要があります。

====
名前には、次のASCII文字の任意の組み合わせを含めることができます。

* `a`から `z`
* `A`から `Z`
* `0`から `9`
* "`_`"、"`.`"-`", and "`

 a| 
`-policy-name` `policy_name`
 a| 
〇
 a| 
なし



 a| 
_ イベント名 _

FPolicyポリシーに関連付けるイベントをカンマで区切って指定します。

* 1つのポリシーに複数のイベントを関連付けることができます。
* イベントはプロトコルに固有です。
* 1つのポリシーで複数のプロトコルのファイル アクセス イベントを監視するには、ポリシーで監視する各プロトコルのイベントを作成し、それらのイベントをポリシーに関連付けます。
* 既存のイベントを指定する必要があります。

 a| 
`-events` `event_name`はい。
 a| 
〇
 a| 
なし



 a| 
_永続ストア_

ONTAP 9 .14.1以降では、このパラメータは、SVM内の非同期（必須ではない）ポリシーのファイルアクセスイベントをキャプチャする永続ストアを指定します。
 a| 
`-persistent-store` `persistent_store_name`
 a| 
いいえ
 a| 
なし



 a| 
_ 外部エンジン名 _

FPolicyポリシーに関連付ける外部エンジンの名前を指定します。

* 外部エンジンには、ノードからFPolicyサーバに通知を送信するために必要な情報が格納されています。
* 単純なファイルブロッキングを行うためにONTAPの標準の外部エンジンを使用したり、より高度なファイルブロッキングとファイル管理を行うために外部FPolicyサーバ（FPolicyサーバ）を使用するように設定された外部エンジンを使用したりするようにFPolicyを設定できます。
* 標準の外部エンジンを使用する場合は、このパラメータの値を指定しないか、値としてを指定できます `native`。
* FPolicyサーバを使用する場合は、外部エンジンの設定がすでに存在している必要があります。

 a| 
`-engine` `engine_name`
 a| 
○（ポリシーで内部のONTAP標準エンジンを使用しない場合）
 a| 
`native`



 a| 
_ は必須のスクリーニングです _

必須のファイルアクセススクリーニングを要求するかどうかを指定します。

* この必須スクリーニング設定は、プライマリサーバとセカンダリサーバがすべて停止した場合や、指定した時間内にFPolicyサーバからの応答を得られない場合に、ファイルアクセスイベントをどのように処理するかを決定します。
* に設定する `true`と、ファイルアクセスイベントが拒否されます。
* に設定する `false`と、ファイルアクセスイベントが許可されます。

 a| 
`-is-mandatory`{`true`|`false`}
 a| 
いいえ
 a| 
`true`



 a| 
権限付きアクセスを許可する _

権限付きデータ接続を使用した監視対象のファイルやフォルダに対する権限付きアクセスをFPolicyサーバに許可するかどうかを指定します。

設定されている場合、FPolicyサーバは権限付きデータ接続を使用して、監視対象データが格納されているSVMのルートにあるファイルにアクセスできます。

権限付きデータアクセスの場合は、クラスタでSMBのライセンスが有効になっている必要があり、FPolicyサーバへの接続に使用されるすべてのデータLIFが、許可されているプロトコルの1つとして設定されている必要があり `cifs`ます。

ポリシーで権限付きアクセスを許可する場合は、FPolicyサーバで権限付きアクセスに使用するアカウントのユーザ名も指定する必要があります。
 a| 
`-allow-privileged-access`{`yes`|`no`}
 a| 
×（パススルーリードが有効になっていない場合）
 a| 
`no`



 a| 
_ 特権ユーザ名 _

FPolicyサーバが権限付きデータアクセスに使用するアカウントのユーザ名を指定します。

* このパラメータの値は、「ドメイン \ ユーザ名」の形式にする必要があります。
* がに設定されて `no`いる場合 `-allow-privileged-access`、このパラメータに設定されている値は無視されます。

 a| 
`-privileged-user-name` `user_name`
 a| 
×（権限付きアクセスが有効になっていない場合）
 a| 
なし



 a| 
_allow passthrough-read _

FPolicyサーバによってセカンダリストレージ（オフラインファイル）にアーカイブされたファイルに対して、FPolicyサーバがパススルーリードサービスを提供できるかどうかを指定します。

* パススルーリードは、オフラインファイルのデータをプライマリストレージにリストアすることなく読み取る方法です。
+
パススルーリードでは、読み取り要求に応答する前にファイルをプライマリストレージにリコールする必要がないため、応答レイテンシが短縮されます。さらに、パススルーリードでは、読み取り要求を満たすためだけにリコールされるファイルによってプライマリストレージスペースを消費する必要がなくなるため、ストレージ効率が最適化されます。

* 有効にすると、FPolicyサーバはパススルーリード専用に開かれた別の権限付きデータチャネルを介してファイルのデータを提供します。
* パススルーリードを設定する場合は、権限付きアクセスを許可するようにポリシーも設定する必要があります。

 a| 
`-is-passthrough-read-enabled`{`true`|`false`}
 a| 
いいえ
 a| 
`false`

|===