---
permalink: nas-audit/requirements-best-practices-fpolicy-concept.html 
sidebar: sidebar 
keywords: requirements, considerations, best practices, configure, fpolicy 
summary: Storage Virtual Machine （ SVM ）で FPolicy の設定を作成して設定する前に、 FPolicy の設定に関する一定の要件、考慮事項、およびベストプラクティスについて確認しておく必要があります。 
---
= FPolicy を設定するための要件、考慮事項、およびベストプラクティス
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
SVMでFPolicyの設定を作成して設定する前に、FPolicyの設定に関する一定の要件、考慮事項、およびベストプラクティスについて確認しておく必要があります。

FPolicy 機能の設定には、コマンドラインインターフェイス（ CLI ）または API を使用します。



== FPolicy を設定するための要件

Storage Virtual Machine （ SVM ）で FPolicy を設定して有効にする前に、一定の要件について確認しておく必要があります。

* クラスタ内のすべてのノードで、 FPolicy がサポートされているバージョンの ONTAP が実行されている必要があります。
* ONTAP の標準の FPolicy エンジンを使用しない場合は、外部 FPolicy サーバ（ FPolicy サーバ）をインストールしておく必要があります。
* FPolicy ポリシーが有効になっている SVM のデータ LIF からアクセスできるサーバに、 FPolicy サーバがインストールされている必要があります。
+

NOTE: ONTAP 9.8以降では、ONTAP により、を追加して、アウトバウンドFPolicy接続用のクライアントLIFサービスを利用できます `data-fpolicy-client` サービス https://["LIFとサービスポリシーの詳細については、こちらをご覧ください"]。

* FPolicy ポリシーの外部エンジンの設定で、 FPolicy サーバの IP アドレスがプライマリサーバまたはセカンダリサーバとして設定されている必要があります。
* FPolicy サーバで権限付きデータチャネルを使用してデータにアクセスする場合は、次の追加要件を満たす必要があります。
+
** クラスタで SMB のライセンスが有効になっている必要があります。
+
権限付きデータアクセスは SMB 接続を使用して実行されます。

** 権限付きデータチャネルを使用してファイルにアクセスするためのユーザクレデンシャルが設定されている必要があります。
** FPolicy サーバが FPolicy の設定で指定されたクレデンシャルで実行されている。
** FPolicyサーバとの通信に使用されるすべてのデータLIFをで設定する必要があります `cifs` 許可されているプロトコルの1つとして指定します。
+
これには、パススルーリード接続で使用される LIF も含まれます。







== FPolicy を設定する際のベストプラクティスと推奨事項

Storage Virtual Machine （ SVM ）で FPolicy を設定するときは、 FPolicy の設定によって監視のパフォーマンスが向上し、要件を満たす結果が得られるようにするため、設定に関するベストプラクティスと推奨事項を理解しておく必要があります。

* レイテンシを最小限に抑え、広帯域幅接続を確保するために、外部 FPolicy サーバ（ FPolicy サーバ）は広帯域幅接続が確保されたクラスタの近くに配置する必要があります。
* 特にポリシーが同期スクリーニング用に設定されている場合は、 FPolicy サーバの通知処理の耐障害性と高可用性を確保するために、 FPolicy 外部エンジンを複数の FPolicy サーバで構成する必要があります。
* 設定を変更する前に、 FPolicy ポリシーを無効にすることを推奨します。
+
たとえば、有効になっているポリシーに設定された FPolicy 外部エンジンの IP アドレスを追加または変更する場合は、まずポリシーを無効にしてください。

* SVM がクライアント要求に応答する際のレイテンシの原因となる可能性がある FPolicy サーバの過負荷状態を防ぐために、クラスタノードと FPolicy サーバの比率を最適化する必要があります。
+
最適な比率は、 FPolicy サーバが使用されているアプリケーションによって異なります。





== パススルーリードのアップグレードおよびリバートに関する考慮事項

パススルーリードをサポートしている ONTAP リリースへのアップグレードまたはパススルーリードをサポートしていないリリースへのリバートを行う前に、アップグレードおよびリバートに関する考慮事項を把握しておく必要があります。



=== をアップグレードして

FPolicy パススルーリードをサポートしている ONTAP のバージョンにすべてのノードをアップグレードしたあと、クラスタはパススルーリードを使用できるようになります。ただし、既存の FPolicy 設定ではパススルーリードがデフォルトで無効になっています。既存の FPolicy 設定でパススルーリードを使用するには、 FPolicy ポリシーを無効にして設定を変更してから、設定を再度有効にする必要があります。



=== 復元しています

FPolicy をサポートしていない ONTAP のバージョンにリバートする前に、以下の条件を満たす必要があります。

* パススルーリードを使用しているすべてのポリシーを無効にしてから、影響を受ける設定を変更してパススルーリードを使用しないようにする必要があります。
* クラスタの FPolicy 機能を無効にする場合は、クラスタ上のすべての FPolicy ポリシーを無効にする必要があります。

