---
permalink: nas-audit/requirements-considerations-concept.html 
sidebar: sidebar 
keywords: audit, requirements, considerations 
summary: Storage Virtual Machine （ SVM ）で監査を設定して有効にする前に、一定の要件と考慮事項について理解しておく必要があります。 
---
= 監査の要件と考慮事項
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Storage Virtual Machine （ SVM ）で監査を設定して有効にする前に、一定の要件と考慮事項について理解しておく必要があります。

* 監査を有効にした SVM は、クラスタで最大 50 個までサポートされます。
* 監査は、 SMB または NFS のライセンスとは関係ありません。
+
クラスタにSMBとNFSのライセンスがインストールされていない場合でも、監査を設定して有効にすることができます。

* NFS 監査では、セキュリティ ACE （タイプ U ）をサポートしています。
* NFS 監査では、モードビットと監査 ACE の間のマッピングはありません。
+
ACL をモードビットに変換する場合、監査 ACE はスキップされます。モードビットを ACL に変換する場合、監査 ACE は生成されません。

* 監査の設定で指定するディレクトリが存在している必要があります。
+
存在しない場合、監査の設定を作成するコマンドは失敗します。

* 監査の設定で指定するディレクトリは、次の要件を満たしている必要があります。
+
** ディレクトリにシンボリックリンクを含めることはできません。
+
監査の設定で指定するディレクトリにシンボリックリンクが含まれている場合、監査の設定を作成するコマンドは失敗します。

** 絶対パスを使用してディレクトリを指定する必要があります。
+
相対パスは指定しないでください（例：）。 `/vs1/../`。



* 監査は、ステージングボリューム内に利用可能なスペースがあるかどうかに依存します。
+
監査対象のボリュームを含むアグリゲートのステージングボリュームに十分なスペースを確保できるよう注意する必要があります。

* 監査は、変換されたイベントログの格納先ディレクトリを含むボリューム内に利用可能なスペースがあるかどうかに依存します。
+
イベントログの格納に使用するボリュームに十分なスペースを確保できるよう注意する必要があります。を使用して、監査ディレクトリに保持するイベントログの数を指定できます `-rotate-limit` 監査の設定を作成する際のパラメータ。これは、ボリューム内のイベントログ用に十分なスペースを確保するのに役立ちます。

* 監査の設定では、SMBサーバでダイナミックアクセス制御を有効にしなくても集約型アクセスポリシーのステージングを有効にできますが、集約型アクセスポリシーのステージングイベントを生成するには、ダイナミックアクセス制御を有効にする必要があります。
+
ダイナミックアクセス制御は、デフォルトでは有効になっていません。





== 監査を有効にする際のアグリゲートスペースに関する考慮事項

監査の設定が作成されていてクラスタ内の少なくとも 1 つの Storage Virtual Machine （ SVM ）で監査が有効になっている場合、監査サブシステムは、既存のすべてのアグリゲートと、作成されるすべての新しいアグリゲートにステージングボリュームを作成します。クラスタ上で監査を有効にする際は、アグリゲートスペースに関する考慮事項に注意する必要があります。

アグリゲートに十分な空き容量がない場合、ステージングボリュームの作成に失敗することがあります。これは、監査の設定を作成したときに、既存のアグリゲートにステージングボリュームを格納するための十分なスペースがない場合に発生することがあります。

SVM で監査を有効にする前に、既存のアグリゲート上にステージングボリューム用の十分なスペースがあることを確認する必要があります。
