---
permalink: nas-audit/restrictions-fpolicy-mcc-svm-disaster-recovery-concept.html 
sidebar: sidebar 
keywords: restrictions, cluster-scoped, fpolicy, external engines, metrocluster, svm disaster recovery configurations 
summary: クラスタを対象としたFPolicy外部エンジンを作成するには、クラスタStorage Virtual Machine（SVM）をそのエンジンに割り当てます。ただし、MetroClusterまたはSVMディザスタリカバリ設定でクラスタ対象の外部エンジンを作成する場合は、SVMがFPolicyサーバとの外部通信に使用する認証方式を選択する際に一定の制限事項があります。 
---
= MetroClusterおよびSVMディザスタリカバリ設定を使用するクラスタ対象FPolicy外部エンジンの制限事項
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
クラスタを対象としたFPolicy外部エンジンを作成するには、クラスタStorage Virtual Machine（SVM）をそのエンジンに割り当てます。ただし、MetroClusterまたはSVMディザスタリカバリ設定でクラスタ対象の外部エンジンを作成する場合は、SVMがFPolicyサーバとの外部通信に使用する認証方式を選択する際に一定の制限事項があります。

外部FPolicyサーバの作成時に選択できる認証オプションには、認証なし、SSLサーバ認証、およびSSL相互認証の3つがあります。外部FPolicyサーバがデータSVMに割り当てられている場合に認証オプションを選択する際の制限事項はありませんが、クラスタ対象のFPolicy外部エンジンを作成する際には制限事項があります。

[cols="75,25"]
|===


| 構成 | 許可されるかどうか 


 a| 
MetroClusterまたはSVMディザスタリカバリと、認証を行わないクラスタ対象FPolicy外部エンジン（SSL未設定）
 a| 
〇



 a| 
MetroClusterまたはSVMディザスタリカバリと、SSLサーバまたはSSL相互認証を備えたクラスタ対象FPolicy外部エンジン
 a| 
いいえ

|===
* SSL認証を使用するクラスタ対象FPolicy外部エンジンが存在し、MetroClusterまたはSVMディザスタリカバリ設定を作成する場合は、認証を使用しないようにこの外部エンジンを変更するか、MetroClusterまたはSVMディザスタリカバリ設定を作成する前に外部エンジンを削除する必要があります。
* MetroClusterまたはSVMディザスタリカバリ設定がすでに存在する場合、ONTAPにより、SSL認証を使用するクラスタ対象FPolicy外部エンジンの作成が阻止されます。

