---
permalink: nas-audit/show-commands-work-concept.html 
sidebar: sidebar 
keywords: show commands, work 
summary: show コマンドの仕組みについて理解しておくと、 FPolicy の設定に関する情報を表示する際に役立ちます。 
---
= show コマンドの仕組み
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
FPolicyの設定に関する情報を表示する際には、の仕組みを理解しておくと役立ちます `show` コマンドは機能します。

A `show` パラメータを追加せずにコマンドを実行すると、情報が要約形式で表示されます。さらに、すべて `show` コマンドには、同じ2つのオプションパラメータを同時に指定することはできません。 `-instance` および `-fields`。

を使用する場合 `-instance` パラメータにを指定します `show` コマンドを使用すると、詳細情報がリスト形式で表示されます。場合によっては、詳細出力には時間がかかることがあり、不要な情報が含まれることもあります。を使用できます `-fields` `fieldname[,fieldname...]` 指定したフィールドの情報のみが表示されるように出力をカスタマイズするためのパラメータ。指定できるフィールドを確認するには、と入力します `?` の後 `-fields` パラメータ

[NOTE]
====
の出力 `show` コマンドにを指定します `-fields` パラメータには、要求されたフィールドに関連する他の関連フィールドや必要なフィールドが表示される場合があります。

====
間隔 `show` コマンドには、その出力をフィルタリングして、コマンド出力に表示される情報の範囲を絞り込むことができる1つ以上のオプションパラメータがあります。コマンドで使用できるオプションパラメータを確認するには、と入力します `?` の後 `show` コマンドを実行します

。 `show` コマンドでは、UNIX形式のパターンおよびワイルドカードがサポートされ、コマンドパラメータ引数の複数の値を照合できます。たとえば、ワイルドカード演算子（ * ）、 NOT 演算子（ ! ）、 OR 演算子（ | ）、範囲演算子（ integer...integer ）、 less-than 演算子（ < ）、 greater-than 演算子（ > ）、 less-than-or-equal-to 演算子（ \<= ）、 greater-than-or-equal-to 演算子（ >= ）を指定する場合に使用できます。

UNIX形式のパターンおよびワイルドカードの使用の詳細については、を参照してください xref:../system-admin/command-line-interface-concept.html[ONTAP コマンドラインインターフェイスを使用する]。
