---
permalink: nas-audit/show-commands-work-concept.html 
sidebar: sidebar 
keywords: show commands, work 
summary: FPolicy 設定に関する情報を表示するときに、show コマンドの動作を理解しておくと役立ちます。 
---
= ONTAP FPolicy の show コマンドについて学ぶ
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
FPolicy 設定に関する情報を表示する際、 `show`コマンドの動作を理解しておくと役立ちます。

 `show`追加パラメータのないコマンドは、情報を要約形式で表示します。さらに、すべての `show`コマンドには、互いに排他的な2つのオプションパラメータ、 `-instance`および `-fields`があります。

 `-instance`パラメータを `show`コマンドで使用すると、コマンド出力には詳細情報がリスト形式で表示されます。場合によっては、詳細出力が長くなり、必要以上の情報が含まれることがあります。 `-fields` `fieldname[,fieldname...]`パラメータを使用して出力をカスタマイズし、指定したフィールドの情報のみを表示することができます。 `-fields`パラメータの後に `?`を入力することで、指定できるフィールドを特定できます。

[NOTE]
====
 `show`コマンドの出力に `-fields`パラメータを指定すると、要求されたフィールドに関連するその他の関連フィールドや必要なフィールドが表示される場合があります。

====
すべての `show`コマンドには、出力をフィルタリングし、コマンド出力に表示される情報の範囲を絞り込むための1つ以上のオプションパラメータがあります。 `show`コマンドの後に `?`と入力することで、コマンドで使用できるオプションパラメータを確認できます。

 `show`コマンドはUNIX形式のパターンとワイルドカードをサポートしており、コマンドパラメータ引数で複数の値を一致させることができます。例えば、ワイルドカード演算子（*）、NOT演算子（!）、OR演算子（|）、範囲演算子（integer...integer）、小なり演算子（<), the greater-than operator (>）、小なりイコール演算子（\<=), and the greater-than or equal to operator (>=）を値指定時に使用できます。

UNIX スタイルのパターンとワイルドカードの使用の詳細については、xref:../system-admin/command-line-interface-concept.html[ONTAPコマンドライン インターフェイスの使用]を参照してください。
