---
permalink: nas-audit/smb-events-audit-concept.html 
sidebar: sidebar 
keywords: smb events, audited 
summary: ONTAP は、ファイルおよびフォルダのアクセスイベント、ログオンおよびログオフイベント、集約型アクセスポリシーのステージングイベントなどの SMB イベントを監査できます。どのようなアクセスイベントを監査できるか理解しておくと、イベントログの結果を解釈するときに役立ちます。 
---
= 監査できる SMB イベントの概要
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
ONTAP は、ファイルおよびフォルダのアクセスイベント、ログオンおよびログオフイベント、集約型アクセスポリシーのステージングイベントなどの SMB イベントを監査できます。どのようなアクセスイベントを監査できるか理解しておくと、イベントログの結果を解釈するときに役立ちます。

ONTAP 9.2 以降では、次の SMB イベントが監査対象として追加されました。

[cols="20,25,35,20"]
|===


| イベント ID （ EVT / EVTX ） | イベント | 説明 | カテゴリ 


 a| 
4670
 a| 
オブジェクト権限が変更されました
 a| 
オブジェクトアクセス：権限が変更された。
 a| 
ファイルアクセス



 a| 
4907
 a| 
オブジェクトの監査設定が変更されました
 a| 
オブジェクトアクセス：監査設定が変更された。
 a| 
ファイルアクセス



 a| 
4913
 a| 
オブジェクトの集約型アクセスポリシーが変更されました
 a| 
オブジェクトへのアクセス： CAP が変更された。
 a| 
ファイルアクセス

|===
ONTAP 9.0 以降では、次の SMB イベントを監査できます。

[cols="20,25,35,20"]
|===


| イベント ID （ EVT / EVTX ） | イベント | 説明 | カテゴリ 


 a| 
540/4624
 a| 
アカウントがログオンに成功しました
 a| 
ログオン/ログオフ：ネットワーク（SMB）ログオン。
 a| 
ログオンおよびログオフ



 a| 
529/4625
 a| 
アカウントがログオンに失敗しました
 a| 
ログオン / ログオフ：ユーザ名が不明またはパスワードが無効です。
 a| 
ログオンおよびログオフ



 a| 
530/4625
 a| 
アカウントがログオンに失敗しました
 a| 
ログオン / ログオフ：アカウントログオンの時間制限です。
 a| 
ログオンおよびログオフ



 a| 
531/4625
 a| 
アカウントがログオンに失敗しました
 a| 
ログオン / ログオフ：アカウントは現在無効になっています。
 a| 
ログオンおよびログオフ



 a| 
532/4625
 a| 
アカウントがログオンに失敗しました
 a| 
ログオン / ログオフ：ユーザアカウントの有効期限が切れています。
 a| 
ログオンおよびログオフ



 a| 
533/4625
 a| 
アカウントがログオンに失敗しました
 a| 
ログオン / ログオフ：ユーザはこのコンピュータにログオンできません。
 a| 
ログオンおよびログオフ



 a| 
534/4625
 a| 
アカウントがログオンに失敗しました
 a| 
ログオン / ログオフ：ユーザはログオンを許可されていません。
 a| 
ログオンおよびログオフ



 a| 
535/4625
 a| 
アカウントがログオンに失敗しました
 a| 
ログオン / ログオフ：ユーザのパスワードが期限切れです。
 a| 
ログオンおよびログオフ



 a| 
537/4625
 a| 
アカウントがログオンに失敗しました
 a| 
ログオン / ログオフ：上記以外の理由でログオンが失敗しました。
 a| 
ログオンおよびログオフ



 a| 
539/4625
 a| 
アカウントがログオンに失敗しました
 a| 
ログオン / ログオフ：アカウントのロックアウト。
 a| 
ログオンおよびログオフ



 a| 
538/4634
 a| 
アカウントがログオフされました
 a| 
ログオン / ログオフ：ローカルまたはネットワークユーザのログオフ。
 a| 
ログオンおよびログオフ



 a| 
560/4656
 a| 
オブジェクトを開く / オブジェクトを作成
 a| 
オブジェクトへのアクセス：オブジェクト（ファイルまたはディレクトリ）が開きます。
 a| 
ファイルアクセス



 a| 
563/4659.
 a| 
削除するためにオブジェクトを開く
 a| 
オブジェクトへのアクセス：削除するためにオブジェクト（ファイルまたはディレクトリ）へのハンドルが要求された。
 a| 
ファイルアクセス



 a| 
564 / 4660
 a| 
オブジェクトを削除します
 a| 
オブジェクトへのアクセス：オブジェクト（ファイルまたはディレクトリ）を削除します。ONTAP は、 Windows クライアントがオブジェクト（ファイルまたはディレクトリ）の削除を試みるとこのイベントを生成します。
 a| 
ファイルアクセス



 a| 
567/4663
 a| 
オブジェクトの読み取り / オブジェクトの書き込み / オブジェクトの属性の取得 / オブジェクトの属性の設定
 a| 
オブジェクトへのアクセス：オブジェクトへのアクセスの試み（読み取り、書き込み、属性の取得、属性の設定）。

* 注： * このイベントでは、 ONTAP はオブジェクトに対する最初の SMB 読み取り操作と SMB 書き込み操作（の成功または失敗）を監査します。これにより、 1 つのクライアントが、あるオブジェクトを開き、そのオブジェクトに対して連続的に多数の読み取りまたは書き込みを行っても、 ONTAP が余計にログエントリを書き込むことがなくなります。
 a| 
ファイルアクセス



 a| 
NA / 4664
 a| 
ハードリンク
 a| 
オブジェクトへのアクセス：ハードリンクの作成が試行されました。
 a| 
ファイルアクセス



 a| 
NA / 4818
 a| 
提案された集約型アクセスポリシーでは、現在の集約型アクセスポリシーと同じアクセス権限が付与されません
 a| 
オブジェクトへのアクセス：集約型アクセスポリシーのステージング。
 a| 
ファイルアクセス



 a| 
NA / NA Data ONTAP イベント ID 9999
 a| 
オブジェクト名を変更します
 a| 
オブジェクトへのアクセス：オブジェクトの名前変更。これは ONTAP イベントです。Windows では現在、単一イベントとしてサポートされていません。
 a| 
ファイルアクセス



 a| 
NA/NA Data ONTAPイベントID 9998
 a| 
オブジェクトのリンク解除
 a| 
オブジェクトへのアクセス：オブジェクトのリンクが解除される。これは ONTAP イベントです。Windows では現在、単一イベントとしてサポートされていません。
 a| 
ファイルアクセス

|===


== イベント 4656 に関する追加情報

。 `HandleID` 監査でタグを付けます `XML` イベントには、アクセスされたオブジェクト（ファイルまたはディレクトリ）のハンドルが含まれます。。 `HandleID` EVTX 4656イベントのタグには、オープンイベントが新しいオブジェクトを作成するためのものか、既存のオブジェクトを開くためのものかによって、異なる情報が含まれます。

* openイベントが新しいオブジェクト（ファイルまたはディレクトリ）を作成するためのオープン要求である場合は、 `HandleID` 監査XMLイベントのタグに空が表示されます `HandleID` （例： `<Data Name="HandleID">00000000000000;00;00000000;00000000</Data>` ）。
+
。 `HandleID` が空の理由は、（新しいオブジェクトを作成するための）OPEN要求が、実際のオブジェクトの作成が行われる前、およびハンドルが存在する前に監査されるためです。同じオブジェクトの後続の監査対象イベントは、で適切なオブジェクトハンドルを持ちます `HandleID` タグ。

* オープンイベントが既存のオブジェクトを開くためのオープン要求である場合、監査イベントには、でそのオブジェクトの割り当てられたハンドルが割り当てられます `HandleID` タグ（例： `<Data Name="HandleID">00000000000401;00;000000ea;00123ed4</Data>` ）。

