---
permalink: nas-audit/synchronous-asynchronous-notifications-concept.html 
sidebar: sidebar 
keywords: synchronous, asynchronous, notifications 
summary: FPolicy は、 FPolicy インターフェイスを介して外部 FPolicy サーバに通知を送信します。通知は同期モードまたは非同期モードで送信されます。通知モードによって、 FPolicy サーバへの通知送信後の ONTAP の動作が決まります。 
---
= 同期通知および非同期通知とは
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
FPolicy は、 FPolicy インターフェイスを介して外部 FPolicy サーバに通知を送信します。通知は同期モードまたは非同期モードで送信されます。通知モードによって、 FPolicy サーバへの通知送信後の ONTAP の動作が決まります。

* * 非同期通知 *
+
非同期通知では、 FPolicy サーバからの応答を待たずにノードでの処理を継続できるため、システムの全体的なスループットが向上します。この種類の通知は、通知の評価結果に基づいて FPolicy サーバで処理を行う必要がないアプリケーションに適しています。たとえば、 Storage Virtual Machine （ SVM ）管理者がファイルアクセスのアクティビティを監視および監査する場合などに使用されます。

+
非同期モードで動作している FPolicy サーバでネットワーク停止が発生した場合、停止中に生成された FPolicy 通知はストレージノードに格納されます。FPolicy サーバがオンラインに戻ると、サーバは格納された通知に関するアラートを受け取り、ストレージノードから通知を読み込むことができます。停止中に通知を保存できる期間は、最大 10 分に設定できます。

+
ONTAP 9.14.1以降では、FPolicyで永続的ストアを設定して、SVM内の非同期（必須ではない）ポリシーのファイルアクセスイベントをキャプチャすることができます。永続的ストアを使用すると、クライアントI/O処理とFPolicy通知処理を分離して、クライアントのレイテンシを低減できます。同期（必須または必須でない）および非同期の必須構成はサポートされていません。

* * 同期通知 *
+
同期モードで実行するように設定した場合は、すべての通知について FPolicy サーバからの確認応答を受け取ってからでないと、クライアントの処理を続行できません。このタイプの通知は、通知の評価結果に基づいて処理を行う必要がある場合に使用されます。たとえば、要求を許可するかどうかを外部 FPolicy サーバで指定された条件に基づいて判断する場合などに使用されます。





== 同期アプリケーションおよび非同期アプリケーション

FPolicy アプリケーションにはさまざまな用途があり、非同期と同期の両方に対応しています。

非同期アプリケーションとは、ファイルまたはディレクトリへのアクセスや Storage Virtual Machine （ SVM ）上のデータが外部 FPolicy サーバによって変更されないアプリケーションです。例：

* ファイルアクセスと監査ログ
* ストレージリソース管理


同期アプリケーションとは、データアクセスやデータが外部 FPolicy サーバによって変更されるアプリケーションです。例：

* クォータ管理
* ファイルアクセスブロッキング
* ファイル・アーカイブと階層型ストレージ管理
* 暗号化サービスと復号化サービス
* 圧縮サービスと展開サービス

