---
permalink: nas-audit/troubleshoot-auditing-staging-volume-concept.html 
sidebar: sidebar 
keywords: troubleshoot, audit, stage, volume space, issues 
summary: ステージングボリュームや監査イベントログを格納するボリュームに十分なスペースがない場合、問題が発生することがあります。十分なスペースがないと新しい監査レコードを作成できないため、クライアントからデータにアクセスできず、アクセス要求が失敗します。ボリュームのスペースに関するこれらの問題について、トラブルシューティングを行って解決する方法を確認しておく必要があります。 
---
= 監査およびステージング用のボリュームのスペースに関する問題のトラブルシューティングを行います
:icons: font
:imagesdir: ../media/


[role="lead"]
ステージングボリュームや監査イベントログを格納するボリュームに十分なスペースがない場合、問題が発生することがあります。十分なスペースがないと新しい監査レコードを作成できないため、クライアントからデータにアクセスできず、アクセス要求が失敗します。ボリュームのスペースに関するこれらの問題について、トラブルシューティングを行って解決する方法を確認しておく必要があります。



== イベントログボリュームに関連するスペースの問題のトラブルシューティングを行います

イベントログファイルを含むボリュームでスペースが不足すると、監査でログレコードをログファイルに変換できなくなります。その結果、クライアントアクセスに失敗します。イベントログボリュームのスペースに関する問題のトラブルシューティング方法を把握しておく必要があります。

* Storage Virtual Machine （ SVM ）管理者およびクラスタ管理者は、ボリュームとアグリゲートの使用量と設定に関する情報を表示して、ボリュームでスペースが不足していないかを確認できます。
* イベントログを含むボリュームでスペースが不足している場合、 SVM 管理者およびクラスタ管理者は、いくつかのイベントログファイルを削除するかボリュームのサイズを大きくすることで、スペースに関する問題を解決できます。
+
[NOTE]
====
イベントログボリュームを含むアグリゲートがいっぱいになっている場合は、ボリュームのサイズを大きくする前に、アグリゲートのサイズを大きくする必要があります。アグリゲートのサイズを大きくすることができるのは、クラスタ管理者だけです。

====
* 監査の設定を変更して、イベントログファイルのデスティネーションパスを別のボリューム上のディレクトリに変更できます。
+
[NOTE]
====
次の場合、データアクセスは拒否されます。

** デスティネーションディレクトリが削除されている場合。
** デスティネーションディレクトリをホストするボリュームのファイルリミットが最大レベルに達している場合。


====


ボリュームに関する情報の表示方法とボリュームサイズの拡張方法の詳細については、を参照してください link:../volumes/index.html["論理ストレージ管理"]

アグリゲートに関する情報の表示方法とアグリゲートの管理方法の詳細については、を参照してください link:../disks-aggregates/index.html["ディスクとアグリゲートの管理"]。



== ステージングボリュームに関するスペースの問題のトラブルシューティングを行います

Storage Virtual Machine （ SVM ）のステージングファイルを含むボリュームのいずれかでスペースが不足すると、監査でログレコードをステージングファイルに書き込むことができなくなります。その結果、クライアントアクセスに失敗します。この問題のトラブルシューティングを行うには、ボリュームの使用量に関する情報を表示して、 SVM で使用されているステージングボリュームのいずれかがいっぱいになっていないかを確認する必要があります。

統合イベントログファイルを含むボリュームに十分なスペースがあるにもかかわらず、スペース不足が原因でクライアントアクセスに失敗する場合は、ステージングボリュームでスペースが不足している可能性があります。SVM 管理者は、クラスタ管理者に問い合わせて、 SVM のステージングファイルを含むステージングボリュームでスペースが不足していないかを確認する必要があります。ステージングボリュームのスペース不足が原因で監査イベントを生成できない場合は、監査サブシステムによって EMS イベントが生成されます。「 No space left on device 」というメッセージが表示されます。ステージングボリュームに関する情報を表示できるのは、クラスタ管理者だけです。 SVM 管理者はこの操作を実行できません

すべてのステージングボリューム名は「 mDV_AUD_」 で始まり、そのあとにステージングボリュームを含むアグリゲートの UUID が続きます。次に、管理 SVM 上にある 4 個のシステムボリュームの例を示します。これらのボリュームは、クラスタ内でデータ SVM のファイルサービスの監査の設定の作成時に自動的に作成されたものです。

[listing]
----
cluster1::> volume show -vserver cluster1
Vserver   Volume       Aggregate    State      Type       Size  Available Used%
--------- ------------ ------------ ---------- ---- ---------- ---------- -----
cluster1  MDV_aud_1d0131843d4811e296fc123478563412
                       aggr0        online     RW          2GB     1.90GB    5%
cluster1  MDV_aud_8be27f813d7311e296fc123478563412
                       root_vs0     online     RW          2GB     1.90GB    5%
cluster1  MDV_aud_9dc4ad503d7311e296fc123478563412
                       aggr1        online     RW          2GB     1.90GB    5%
cluster1  MDV_aud_a4b887ac3d7311e296fc123478563412
                       aggr2        online     RW          2GB     1.90GB    5%
4 entries were displayed.
----
ステージングボリュームでスペースが不足している場合は、ボリュームのサイズを大きくすることで、スペースに関する問題を解決できます。

[NOTE]
====
ステージングボリュームを含むアグリゲートがいっぱいになっている場合は、ボリュームのサイズを大きくする前に、アグリゲートのサイズを大きくする必要があります。アグリゲートのサイズを拡張できるのは、クラスタ管理者だけです。 SVM 管理者はこの操作を行うことができません

====
使用可能なスペースが 2GB 未満のアグリゲートがあると、 SVM の監査の作成に失敗します。SVM の監査の作成に失敗した場合、作成されたステージングボリュームは削除されます。

link:../concepts/index.html["ONTAP の概念"]
link:../volumes/index.html["論理ストレージ管理"]
link:../disks-aggregates/index.html["ディスクとアグリゲートの管理"]
