---
permalink: nas-audit/troubleshoot-auditing-staging-volume-concept.html 
sidebar: sidebar 
keywords: troubleshoot, audit, stage, volume space, issues 
summary: ステージングボリュームまたは監査イベントログを含むボリュームでスペースが不足していると、問題が発生する可能性があります。十分なスペースがないと新しい監査レコードを作成できないため、クライアントからデータにアクセスできず、アクセス要求が失敗します。ボリュームのスペースに関するこれらの問題について、トラブルシューティングを行って問題を解決する方法を確認しておく必要があります。 
---
= ONTAPの監査とステージングボリュームのスペースに関する問題のトラブルシューティング
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
ステージングボリュームまたは監査イベントログを含むボリュームでスペースが不足していると、問題が発生する可能性があります。十分なスペースがないと新しい監査レコードを作成できないため、クライアントからデータにアクセスできず、アクセス要求が失敗します。ボリュームのスペースに関するこれらの問題について、トラブルシューティングを行って問題を解決する方法を確認しておく必要があります。



== イベントログボリュームに関連するスペースの問題をトラブルシューティングする

イベントログファイルを含むボリュームのスペースが不足すると、監査でログレコードをログファイルに変換できません。その結果、クライアントアクセスが失敗します。イベントログボリュームに関連するスペースの問題のトラブルシューティング方法を把握しておく必要があります。

* Storage Virtual Machine（SVM）管理者およびクラスタ管理者は、ボリュームとアグリゲートの使用量と設定に関する情報を表示して、ボリュームでスペースが不足していないかを確認できます。
* イベント ログを含むボリュームでスペースが不足している場合、SVM管理者およびクラスタ管理者は、いくつかのイベント ログ ファイルを削除するかボリュームのサイズを大きくすることで、スペースに関する問題を解決できます。
+
[NOTE]
====
イベント ログ ボリュームを含むアグリゲートがいっぱいになっている場合は、ボリュームのサイズを大きくする前に、アグリゲートのサイズを大きくする必要があります。アグリゲートのサイズを大きくすることができるのは、クラスタ管理者だけです。

====
* 監査設定を変更して、イベント ログ ファイルのデスティネーション パスを別のボリューム上のディレクトリに変更できます。
+
[NOTE]
====
次の場合はデータへのアクセスが拒否されます。

** デスティネーション ディレクトリが削除されている
** デスティネーション ディレクトリをホストするボリュームのファイル リミットが最大レベルに達している


====


詳細については以下を参照してください。

* link:../volumes/index.html["ボリュームに関する情報の表示方法とボリュームサイズの拡張方法"]です。
* link:../disks-aggregates/index.html["アグリゲートに関する情報の表示方法とアグリゲートの管理方法"]です。




== ステージングボリュームに関するスペースの問題のトラブルシューティング

Storage Virtual Machine（SVM）のステージングファイルを含むボリュームのいずれかでスペースが不足すると、監査でログレコードをステージングファイルに書き込むことができなくなります。その結果、クライアントアクセスが失敗します。この問題のトラブルシューティングを行うには、ボリュームの使用量に関する情報を表示して、SVMで使用されているステージングボリュームのいずれかがいっぱいになっていないかを確認する必要があります。

統合イベントログファイルを含むボリュームに十分なスペースがあるにもかかわらず、スペース不足が原因でクライアントアクセスに失敗する場合は、ステージングボリュームのスペースが不足している可能性があります。SVM管理者は、ユーザに問い合わせて、SVMのステージングファイルを含むステージングボリュームでスペースが不足していないかどうかを確認する必要があります。ステージングボリュームのスペース不足が原因で監査イベントを生成できない場合は、監査サブシステムによってEMSイベントが生成されます。次のメッセージが表示されます。 `No space left on device`ステージングボリュームに関する情報を表示できるのは、管理者だけです。SVM管理者はこの操作を実行できません。

すべてのステージングボリューム名はで始まり `MDV_aud_`、そのあとにステージングボリュームを含むアグリゲートのUUIDが続きます。次の例は、管理SVM上にある4つのシステムボリュームを示しています。これらのボリュームは、クラスタ内でデータSVMのファイルサービスの監査の設定が作成されたときに自動的に作成されたものです。

[listing]
----
cluster1::> volume show -vserver cluster1
Vserver   Volume       Aggregate    State      Type       Size  Available Used%
--------- ------------ ------------ ---------- ---- ---------- ---------- -----
cluster1  MDV_aud_1d0131843d4811e296fc123478563412
                       aggr0        online     RW          5GB     4.75GB    5%
cluster1  MDV_aud_8be27f813d7311e296fc123478563412
                       root_vs0     online     RW          5GB     4.75GB    5%
cluster1  MDV_aud_9dc4ad503d7311e296fc123478563412
                       aggr1        online     RW          5GB     4.75GB    5%
cluster1  MDV_aud_a4b887ac3d7311e296fc123478563412
                       aggr2        online     RW          5GB     4.75GB    5%
4 entries were displayed.
----
ステージングボリュームでスペースが不足している場合は、ボリュームのサイズを大きくすることで、スペースに関する問題を解決できます。

[NOTE]
====
ステージングボリュームを含むアグリゲートがいっぱいの場合は、ボリュームのサイズを拡張する前に、アグリゲートのサイズを拡張する必要があります。アグリゲートのサイズを拡張できるのは、クラスタ管理者だけです。SVM管理者はこの操作を実行できません。

====
2GB未満（ONTAP 9.14.1以前）または5GB（ONTAP 9.151以降）の使用可能なスペースがあるアグリゲートが1つ以上あると、SVMの監査の作成が失敗します。SVMの監査の作成に失敗すると、作成されていたステージングボリュームが削除されます。
