---
permalink: nas-audit/two-parts-fpolicy-solution-concept.html 
sidebar: sidebar 
keywords: two parts, fpolicy, solution 
summary: FPolicyソリューションには2つの要素があります。ONTAP FPolicyフレームワークは、クラスタでのアクティビティを管理し、外部FPolicyサーバに通知を送信します。外部 FPolicy サーバは、 ONTAP FPolicy から送信された通知を処理します。 
---
= FPolicyソリューションの2つの要素とは
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
FPolicyは、パートナーソリューションを通じてStorage Virtual Machine（SVM）上のファイルアクセスイベントの監視と管理に使用されるファイルアクセス通知フレームワークです。パートナーソリューションは、データガバナンスとコンプライアンス、ランサムウェア対策、データモビリティなど、さまざまなユースケースへの対応を支援します。

パートナーソリューションには、NetAppがサポートするサードパーティソリューションとNetApp製品のワークロードセキュリティとCloud Data Senseの両方が含まれます。

FPolicyソリューションには2つの要素があります。ONTAP FPolicyフレームワークは、クラスタでのアクティビティを管理し、パートナーアプリケーション（外部FPolicyサーバ）に通知を送信します。外部FPolicyサーバは、お客様のユースケースに対応するために、ONTAP FPolicyから送信された通知を処理します。

ONTAPフレームワークでは、FPolicyの設定の作成と管理、ファイルイベントの監視、および外部FPolicyサーバへの通知の送信を行います。ONTAP FPolicy は、外部 FPolicy サーバと Storage Virtual Machine （ SVM ）ノードの間の通信を可能にするインフラを提供します。

FPolicyフレームワークは、外部FPolicyサーバに接続し、クライアントアクセスの結果として特定のファイルシステムイベントが発生した場合にFPolicyサーバに通知を送信します。外部FPolicyサーバは、これらの通知を処理し、ノードに応答を送信します。通知処理の結果として実行される処理は、アプリケーション、およびノードと外部サーバの間の通信が非同期であるか同期であるかによって異なります。
