---
permalink: nas-audit/view-audit-event-logs-concept.html 
sidebar: sidebar 
keywords: view, audit event logs 
summary: 監査イベントログを使用して、ファイルセキュリティが適切であるかどうか、ファイルやフォルダへの不適切なアクセス試行がなかったかどうかを確認できます。EVTX または XML ファイル形式で保存された監査イベントログを表示したり処理したりできます。 
---
= 監査イベントログを表示する
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
監査イベントログを使用して、ファイルセキュリティが適切であるかどうか、ファイルやフォルダへの不適切なアクセス試行がなかったかどうかを確認できます。に保存された監査イベントログを表示および処理できます `EVTX` または `XML` ファイル形式。

* `EVTX` ファイル形式
+
変換されたを開くことができます `EVTX` Microsoftイベントビューアを使用して、保存されたファイルとしてイベントログを監査します。

+
イベントビューアでイベントログを表示する際に使用できるオプションは 2 つあります。

+
** 全般表示
+
イベントレコードには、すべてのイベントに共通する情報が表示されます。このバージョンの ONTAP では、イベントレコードに関するイベント固有のデータは表示されません。詳細表示を使用して、イベント固有のデータを表示できます。

** 詳細ビュー
+
フレンドリ表示と XML 表示を使用できます。フレンドリ表示と XML 表示には、すべてのイベントに共通の情報とイベントレコードのイベント固有のデータの両方が表示されます。



* `XML` ファイル形式
+
表示と処理が可能です `XML` をサポートする他社製アプリケーションの監査イベントログ `XML` ファイル形式。XML スキーマと XML フィールドの定義に関する情報があれば、 XML 表示ツールを使用して監査ログを表示できます。XML スキーマおよび定義の詳細については、を参照してください https://library.netapp.com/ecm/ecm_get_file/ECMLP2875022["ONTAP 監査スキーマリファレンス"]。





== イベントビューアを使用したアクティブな監査ログの表示方法

クラスタで監査の統合プロセスを実行している場合、統合プロセスにより、監査を有効にした SVM のアクティブな監査ログファイルに新しいレコードが追加されます。このアクティブな監査ログは、 SMB 共有でアクセスして Microsoft イベントビューアで開くことができます。

イベントビューアには、既存の監査レコードが表示されるだけでなく、コンソールウィンドウの内容を更新するオプションもあります。アクティブな監査ログにアクセスするために使用される共有で oplock が有効になっているかどうかに応じて、新たに追加されたログをイベントビューアで表示できるかどうかが異なります。

[cols="30,70"]
|===


| 共有での oplock の設定 | 動作 


 a| 
有効
 a| 
その時点までに書き込まれたイベントを含むログがイベントビューアに表示されます。更新処理を実行してもログは更新されず、統合プロセスで追加された新しいイベントは表示されません。



 a| 
無効
 a| 
その時点までに書き込まれたイベントを含むログがイベントビューアに表示されます。更新処理を実行すると、ログが更新され、統合プロセスで追加された新しいイベントが表示されます。

|===
[NOTE]
====
この情報は、にのみ適用されます `EVTX` イベントログ。 `XML` イベントログは、SMBを介してブラウザで、または任意のXMLエディタまたはビューアを使用してNFSで表示できます。

====