---
permalink: san-config/benefits-vlans-iscsi-concept.html 
sidebar: sidebar 
keywords: benefits, vlans, iscsi, configurations, static, dynamic, security, limit, available, paths 
summary: VLAN は、ブロードキャストドメインにグループ化されたスイッチポートのグループで構成されます。VLAN は、単一のスイッチに設定することも、複数のスイッチシャーシにまたがって設定することもできます。静的な VLAN と動的な VLAN を使用すると、 IP ネットワークインフラ内でのセキュリティの強化、問題の切り分け、および使用可能なパスの制限が可能になります。 
---
= iSCSI 構成で VLAN を使用する利点
:icons: font
:imagesdir: ../media/


[role="lead"]
VLAN は、ブロードキャストドメインにグループ化されたスイッチポートのグループで構成されます。VLAN は、単一のスイッチに設定することも、複数のスイッチシャーシにまたがって設定することもできます。静的な VLAN と動的な VLAN を使用すると、 IP ネットワークインフラ内でのセキュリティの強化、問題の切り分け、および使用可能なパスの制限が可能になります。

大規模な IP ネットワークインフラに VLAN を実装する利点は次のとおりです。

* セキュリティの向上：
+
VLAN を使用すると、イーサネットネットワークまたは IP SAN のノード間のアクセスが制限されるため、既存のインフラを利用しながらセキュリティを強化できます。

* 問題を切り分けることで、イーサネットネットワークや IP SAN の信頼性が高まります。
* 問題の範囲を制限することで、問題解決時間を短縮できます。
* 特定の iSCSI ターゲットポートへの使用可能なパスの数が削減されます。
* ホストで使用されるパスの最大数が削減されます。
+
パスが多すぎると再接続の時間が遅くなります。ホストにマルチパス解決策がない場合は、 VLAN を使用して 1 つのパスのみを許可できます。





== 動的 VLANs

動的な VLAN は MAC アドレスに基づいています。VLAN は、 VLAN に含めるメンバーの MAC アドレスを指定して定義できます。

動的な VLAN は柔軟性に優れており、デバイスがスイッチに物理的に接続されている物理ポートにマッピングする必要はありません。ケーブルを別のポートに接続するときに VLAN を再構成する必要はありません。



== 静的な VLAN

静的な VLAN はポートベースです。スイッチポートとスイッチポートを使用して、 VLAN とそのメンバーを定義します。

静的な VLAN を使用すると、 MAC （メディアアクセス制御）のスプーフィングを使用した VLAN への不正アクセスを防止できるため、セキュリティが向上します。ただし、第三者がスイッチに物理的にアクセスできる場合は、ケーブルを交換してネットワークアドレスを再設定することでアクセスが可能になります。

環境によっては、静的な VLAN は動的な VLAN よりも簡単に作成および管理できます。静的な VLAN では、 48 ビットの MAC アドレスではなく、スイッチとポートの識別子のみを指定する必要があるからです。また、 VLAN の識別子をスイッチのポート範囲のラベルとして設定することもできます。
