---
permalink: san-config/commands-manage-fc-adapters-reference.html 
sidebar: sidebar 
keywords: commands, managing, fc adapters 
summary: FC コマンドを使用して、ストレージコントローラの FC ターゲットアダプタ、 FC イニシエータアダプタ、およびオンボード FC アダプタを管理できます。FC アダプタの管理に使用するコマンドは、 FC プロトコルと FC-NVMe プロトコルで同じです。 
---
= FC アダプタの管理用コマンド
:icons: font
:imagesdir: ../media/


[role="lead"]
FC コマンドを使用して、ストレージコントローラの FC ターゲットアダプタ、 FC イニシエータアダプタ、およびオンボード FC アダプタを管理できます。FC アダプタの管理に使用するコマンドは、 FC プロトコルと FC-NVMe プロトコルで同じです。

FC イニシエータアダプタのコマンドは、ノードレベルでのみ機能します。FC イニシエータ・アダプタ・コマンドを使用するには、事前に「 run -node _node_name _ 」コマンドを使用する必要があります。



== FC ターゲットアダプタの管理用コマンド

[cols="2*"]
|===
| 状況 | 使用するコマンド 


 a| 
ノードの FC アダプタ情報を表示する
 a| 
「 network fcp adapter show 」のように表示されます



 a| 
FC ターゲットアダプタのパラメータを変更する
 a| 
「 network fcp adapter modify 」というメッセージが表示されます



 a| 
FC プロトコルトラフィック情報を表示します
 a| 
「 run -node _node_name _sysstat -f 」を指定します



 a| 
FC プロトコルの実行時間を表示します
 a| 
'run-node_name _uptime



 a| 
アダプタの設定とステータスを表示します
 a| 
'run -node _node_name sysconfig -v _adapter_`



 a| 
拡張カードが取り付けられていること、および構成にエラーがないかどうかを確認します
 a| 
'run-node_node_name _sysconfig -ac



 a| 
コマンドのマニュアルページを表示します
 a| 
「 command _ 名」

|===


== FC イニシエータアダプタの管理用コマンド

[cols="2*"]
|===
| 状況 | 使用するコマンド 


 a| 
ノードのすべてのイニシエータおよびそのアダプタの情報を表示する
 a| 
'run -node node_name _storage show adapter



 a| 
アダプタの設定とステータスを表示します
 a| 
'run -node _node_name sysconfig -v _adapter_`



 a| 
拡張カードが取り付けられていること、および構成にエラーがないかどうかを確認します
 a| 
'run-node_node_name _sysconfig -ac

|===


== オンボード FC アダプタの管理用コマンド

[cols="2*"]
|===
| 状況 | 使用するコマンド 


 a| 
オンボード FC ポートのステータスを表示します
 a| 
「 system node hardware unified-connect show 」を参照してください

|===