---
permalink: san-config/determine-supported-hosts-iscsi-config-task.html 
sidebar: sidebar 
keywords: determine, supported, number, hosts, iscsi, configurations 
summary: iSCSI 構成で接続できる SAN ホストの最大数は、クラスタの各ノードに接続されるホストの数、ホストあたりのイニシエータ数、ホストあたりのログイン数、クラスタ内のノード数など、クラスタのさまざまな属性の組み合わせによって大きく異なります。 
---
= iSCSI 構成でサポートされるホスト数を確認します
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
iSCSI 構成で接続できる SAN ホストの最大数は、クラスタの各ノードに接続されるホストの数、ホストあたりのイニシエータ数、ホストあたりのログイン数、クラスタ内のノード数など、クラスタのさまざまな属性の組み合わせによって大きく異なります。

.このタスクについて
ノードに直接または 1 つ以上のスイッチを介して接続できるホストの数は、使用可能なイーサネットポートの数で決まります。使用可能なイーサネットポートの数は、コントローラのモデル、およびコントローラにインストールされているアダプタの数とタイプによって決まります。コントローラおよびアダプタでサポートされるイーサネットポートの数は、 _ Hardware Universe _ で確認できます。

マルチノードクラスタ構成の場合は、ノードあたりの iSCSI セッションの数に基づいて、クラスタにホストを追加できるかどうかを判断する必要があります。ノードあたりの iSCSI セッションの最大数をクラスタが下回っている場合は、引き続きクラスタにホストを追加できます。ノードあたりの iSCSI セッションの最大数は、クラスタ内のコントローラのタイプによって異なります。

.手順
. ノードのターゲットポータルグループをすべて特定します。
. ノードのすべてのターゲットポータルグループについて、それぞれ iSCSI セッションの数を確認します。
+
`iscsi session show -tpgroup _tpgroup_`

+
コマンド出力の一番下に表示されたエントリ数が、そのターゲットポータルグループの iSCSI セッション数です。

. 各ターゲットポータルグループについて、表示された iSCSI セッション数を記録します。
. ノードの各ターゲットポータルグループの iSCSI セッション数を追加します。
+
この値がノードの iSCSI セッションの総数になります。


