---
permalink: san-config/determine-supported-nodes-task.html 
sidebar: sidebar 
keywords: determine, number, supported, nodes, san configurations 
summary: ONTAPでサポートされるクラスタあたりのノード数は、ONTAPのバージョン、クラスタ内のストレージ コントローラのモデル、およびクラスタ ノードのプロトコルによって異なります。 
---
= ONTAPクラスタごとにサポートされるノードとSANホストの最大数を決定する
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
クラスタあたりでサポートされるノード数は ONTAP のバージョン、コントローラのモデル、およびクラスタ ノードのプロトコルによって異なります。クラスタに接続できる SAN ホストの最大数も、特定の構成によって異なります。



== クラスタごとにサポートされる最大ノード数を決定する

クラスター内のいずれかのノードがFC、FC-NVMe、FCoE、またはiSCSI用に設定されている場合、そのクラスターはSANノードの制限に従います。クラスター内のコントローラに基づくノード制限は、_Hardware Universe_に記載されています。

.手順
.  https://hwu.netapp.com["NetApp Hardware Universe"^]に進みます。
. 左上の*ホーム*の横にある*プラットフォーム*を選択し、プラットフォームの種類を選択します。
. ONTAP のバージョンを選択します。
+
プラットフォームを選択するための新しい列が表示されます。

. ソリューションで使用するプラットフォームを選択します。
. *仕様を選択*で、*すべて選択*の選択を解除します。
. *クラスターあたりの最大ノード数（NAS/SAN）* を選択します。
. *Show Results*をクリックします。


.結果
選択したプラットフォームのクラスタあたりの最大ノード数が表示されます。



== クラスタがより多くのFCホストをサポートできるかどうかを判断する

FC および FC-NVMe 構成の場合、システム内のイニシエーター-ターゲット ネクサス（ITN）の数を使用して、クラスターにさらにホストを追加できるかどうかを判断する必要があります。

ITNは、ホストのイニシエータからストレージ システムのターゲットまでの1つのパスを表します。FCおよびFC-NVMe構成では、ノードあたりのITNの最大数は2,048です。ITNの最大数を下回っている場合は、クラスターにホストを追加し続けることができます。

クラスターで使用されている ITN の数を確認するには、クラスター内の各ノードに対して次の手順を実行します。

.手順
. 特定のノード上のすべての LIF を識別します。
. ノードのすべてのLIFに対して次のコマンドを実行します。
+
[source, cli]
----
fcp initiator show -fields wwpn, lif
----
+
コマンド出力の下部に表示されるエントリの数は、その LIF の ITN の数を表します。

. 各 LIF に表示される ITN の数を記録します。
. クラスタ内のすべてのノード上の各 LIF の ITN の数を追加します。
+
この合計は、クラスター内の ITN の数を表します。





== クラスタがより多くのiSCSIホストをサポートできるかどうかを判断する

ノードに直接接続できるホストの台数、または1台以上のスイッチを介して接続できるホストの台数は、利用可能なイーサネットポートの数によって異なります。利用可能なイーサネットポートの数は、コントローラのモデルと、コントローラに搭載されているアダプタの数と種類によって決まります。コントローラとアダプタでサポートされるイーサネットポートの数は、_Hardware Universe_で確認できます。

すべてのマルチノード クラスタ構成において、クラスタにホストを追加できるかどうかを判断するには、ノードあたりの iSCSI セッション数を確認する必要があります。クラスタの iSCSI セッション数がノードあたりの最大セッション数を下回っている限り、クラスタにホストを追加し続けることができます。ノードあたりの iSCSI セッションの最大数は、クラスタ内のコントローラの種類によって異なります。

.手順
. ノード上のすべてのターゲット ポータル グループを特定します。
. ノード上のすべてのターゲット ポータル グループの iSCSI セッションの数を確認します：
+
[source, cli]
----
iscsi session show -tpgroup _tpgroup_
----
+
コマンド出力の下部に表示されるエントリの数は、そのターゲット ポータル グループのiSCSIセッションの数を表します。

. 各ターゲット ポータル グループに表示される iSCSI セッションの数を記録します。
. ノード上の各ターゲット ポータル グループの iSCSI セッション数を追加します。
+
合計はノード上のiSCSIセッションの数を表します。


