---
permalink: san-config/iscsi-config-concept.html 
sidebar: sidebar 
keywords: considerations, iscsi, configurations 
summary: iSCSI 構成をセットアップする際は、次の点を考慮してください。 
---
= iSCSI 構成の概要に関する考慮事項
:icons: font
:imagesdir: ../media/


[role="lead"]
iSCSI 構成をセットアップする際は、次の点を考慮してください。

* iSCSI 構成は、シングルノードまたは HA ペアで構成できます。
+
直接接続またはイーサネットスイッチの使用がサポートされています。どちらのタイプの接続でも、 LIF を作成する必要があります

* SAN をサポートする Storage Virtual Machine （ SVM ）ごとに管理 LIF を 1 つ設定する必要があります。
* HA ペアによって所有されている LUN へのアクセスに使用されているパスは、選択的 LUN マッピング（ SLM ）で制限されます。
+
これは、 ONTAP リリースで作成された LUN のデフォルトの動作です。

* ALUA を使用した LUN へのアクセスにホストで使用される「アクティブ / 最適化」パスと「アクティブ / 非最適化」パスについては、 HA ペアがレポートノードとして定義されます。
* 冗長性を確保し、複数のパス間の MPIO を実現するために、 iSCSI 構成のすべての SVM でノードごとに少なくとも 2 つの LIF を作成して別々のイーサネットネットワークに配置することを推奨します。
* HA ペアの各ノードから 1 つ以上の iSCSI パスを作成し、 HA ペアで処理する LUN に論理インターフェイス（ LIF ）を使用してアクセスできるようにする必要があります。
+
ノードで障害が発生した場合、 LIF は障害が発生したパートナーノードの IP アドレスを引き継ぎません。代わりに、 MPIO ソフトウェアが、ホストの ALUA を使用して、 LIF 経由で LUN にアクセスするための適切なパスを選択します。

* VLAN を使用すると、セキュリティの強化やネットワークの信頼性の向上など、 iSCSI に求められるメリットを実現することができます。

