---
permalink: san-config/set-queue-depths-vmware-hosts-task.html 
sidebar: sidebar 
keywords: set, queue, depths, vmware, hosts 
summary: HBA のタイムアウト設定を変更するには、 esxcfg-module コマンドを使用してください。esx.conf ファイルを手動で更新することは推奨されません。 
---
= VMware ホストでのキュー深度の設定
:icons: font
:imagesdir: ../media/


[role="lead"]
HBA のタイムアウト設定を変更するには 'esxcfg-module コマンドを使用してください手動で 'esx.conf ファイルを更新することは推奨されません



== QLogic HBA の最大キュー深度を設定します

.手順
. root ユーザとしてサービスコンソールにログオンします。
. vmkload_mod -l コマンドを使用して ' どの Qlogic HBA モジュールが現在ロードされているかを確認します
. Qlogic HBA の単一インスタンスの場合は、次のコマンドを実行します。
+
#esxcfg-module -s ql2xmaxqdepth=64 qla2300_707

+
[NOTE]
====
この例では qla2300_707 が使用されています。vmkload_mod -l の出力に基づいて ' 適切なモジュールを使用してください

====
. 次のコマンドを使用して変更を保存します。
+
「 #/usr/sbin/esxcfg-boot -b

. 次のコマンドを使用してサーバをリブートします。
+
#reboot

. 次のコマンドを使用して変更を確認します。
+
.. #esxcfg-module -g qla2300_707`
.. qla2300_707 enabled=1 options ='ql2xmaxqdepth=64'`






== Emulex HBA のキュー深度を変更するには、次の手順を実行します

.手順
. root ユーザとしてサービスコンソールにログオンします。
. vmkload_mod -l grep lpfcdd コマンドを使用して ' どの Emulex HBA が現在ロードされているかを確認します
. Emulex HBA の単一インスタンスの場合は、次のコマンドを入力します。
+
#esxcfg-module -s lpfc0_lun_queue_depth=16 lpfcdd_7xx

+
[NOTE]
====
HBA のモジュールに応じて、最後の部分には lpfcdd_7xx または lpfcdd_732 を指定します。このコマンドでは lpfcdd_7xx モジュールを指定しています。vmkload_mod -l の出力に基づいて ' 適切なモジュールを使用してください

====
+
このコマンドを実行すると、 lpfc0 で表される HBA に対して LUN のキュー深度を 16 に設定します。

. Emulex HBA の複数のインスタンスの場合は、次のコマンドを実行します。
+
「 a esxcfg-module -s 」 lpfc0_lun_queue_depth=16 lpfc1_lun_queue_depth=16 「 lpfcdd_7xx

+
lpfc0 に対する LUN のキュー深度と lpfc1 に対する LUN のキュー深度が 16 に設定されます。

. 次のコマンドを入力します。
+
#esxcfg-boot -b

. # reboot を使用して再起動します

