---
permalink: san-config/update-qlogic-hba-queue-depths-linux-host-task.html 
sidebar: sidebar 
keywords: updating, qlogic, hba, queue, depths, linux, host 
summary: Linux ホストでは QLogic ドライバのデバイスキュー深度を更新できます。更新をリブート後も維持するには、新しい RAM ディスクイメージを作成してホストをリブートする必要があります。QLogic HBA のキュー深度を変更するには、 QLogic HBA の管理 GUI またはコマンドラインインターフェイス（ CLI ）を使用します。 
---
= Linux ホストで QLogic HBA のキュー深度を更新します
:icons: font
:imagesdir: ../media/


[role="lead"]
Linux ホストでは QLogic ドライバのデバイスキュー深度を更新できます。更新をリブート後も維持するには、新しい RAM ディスクイメージを作成してホストをリブートする必要があります。QLogic HBA のキュー深度を変更するには、 QLogic HBA の管理 GUI またはコマンドラインインターフェイス（ CLI ）を使用します。

このタスクでは、 QLogic HBA の CLI を使用して QLogic HBA のキュー深度を変更する方法を示します

.手順
. 変更するデバイスキュー深度パラメータを確認します。
+
「 modinfo qla2xxx | grep ql2xmaxqdepth 」です

+
変更できるのは 'ql2xmaxqdepth' キュー深度パラメータだけですこれは 'LUN ごとに設定できる最大キュー深度を示しますRHEL 7.5 以降のデフォルト値は 64 です。RHEL 7.4 以前のデフォルト値は 32 です。

+
[listing]
----
root@localhost ~]# modinfo qla2xxx|grep ql2xmaxqdepth
parm:       ql2xmaxqdepth:Maximum queue depth to set for each LUN. Default is 64. (int)
----
. デバイスのキュー深度の値を更新します。
+
** 永続的に変更する場合は、次の手順を実行します。
+
... キュー深度を更新するには、 Red Hat Enterprise Linux 5.x システムの場合は「 /etc/modprobe.conf 」ファイルに、 Red Hat Enterprise Linux 6.x または 7.x システムの場合は「 /etc/modprobe.d/sscsi.conf 」ファイル、 SUSE Linux Enterprise Server 11.x または maxq2xxx システムの場合は「 qla_depth 」オプションにキュー深度パラメータを追加します
... 新しい RAM ディスクイメージを作成し、ホストをリブートして、リブート後も更新内容を維持します。
+
詳細については、使用している Linux オペレーティングシステムのバージョンに対応した『 _System Administration Reference Guide 』を参照してください。



** 現在のセッションだけでパラメータを変更する場合は、次のコマンドを実行します。
+
`echo new_queue_depth>/sys/module/qla2xxx /parameters/ql2xmaxqdepth`

+
次の例では、キュー深度を 128 に設定します。

+
[listing]
----
echo 128 > /sys/module/qla2xxx/parameters/ql2xmaxqdepth
----


. キュー深度の値が更新されたことを確認します。
+
「 cat /sys/module/qla2xxx /parameters/ql2xmaxqdepth 」

+
キュー深度の現在の値が表示されます。

. QLogic HBA BIOS からファームウェア・パラメータ Execution Throttle を更新して 'QLogic HBA のキュー深度を変更します
+
.. QLogic HBA の管理 CLI にログインします。
+
/opt/QLogic_Corporation/QConvergeConsoleCLI/qaucli

.. メイン・メニューから ' Adapter Configuration オプションを選択します
+
[listing]
----
[root@localhost ~]# /opt/QLogic_Corporation/QConvergeConsoleCLI/qaucli
Using config file: /opt/QLogic_Corporation/QConvergeConsoleCLI/qaucli.cfg
Installation directory: /opt/QLogic_Corporation/QConvergeConsoleCLI
Working dir: /root

QConvergeConsole

        CLI - Version 2.2.0 (Build 15)

    Main Menu

    1:  Adapter Information
    **2:  Adapter Configuration**
    3:  Adapter Updates
    4:  Adapter Diagnostics
    5:  Monitoring
    6:  FabricCache CLI
    7:  Refresh
    8:  Help
    9:  Exit


        Please Enter Selection: 2
----
.. アダプタ構成パラメータのリストから 'HBA Parameters オプションを選択します
+
[listing]
----
1:  Adapter Alias
    2:  Adapter Port Alias
    **3:  HBA Parameters**
    4:  Persistent Names (udev)
    5:  Boot Devices Configuration
    6:  Virtual Ports (NPIV)
    7:  Target Link Speed (iiDMA)
    8:  Export (Save) Configuration
    9:  Generate Reports
   10:  Personality
   11:  FEC
(p or 0: Previous Menu; m or 98: Main Menu; ex or 99: Quit)
        Please Enter Selection: 3
----
.. HBA ポートのリストから、必要な HBA ポートを選択します。
+
[listing]
----
Fibre Channel Adapter Configuration

    HBA Model QLE2562 SN: BFD1524C78510
      1: Port   1: WWPN: 21-00-00-24-FF-8D-98-E0 Online
      2: Port   2: WWPN: 21-00-00-24-FF-8D-98-E1 Online
    HBA Model QLE2672 SN: RFE1241G81915
      3: Port   1: WWPN: 21-00-00-0E-1E-09-B7-62 Online
      4: Port   2: WWPN: 21-00-00-0E-1E-09-B7-63 Online


        (p or 0: Previous Menu; m or 98: Main Menu; ex or 99: Quit)
        Please Enter Selection: 1
----
+
HBA ポートの詳細が表示されます。

.. HBA Parameters メニューから 'Display HBA Parameters オプションを選択して 'Execution Throttle' オプションの現在の値を表示します
+
[Execution Throttle] オプションのデフォルト値は 65535 です

+
[listing]
----
HBA Parameters Menu

=======================================================
HBA           : 2 Port: 1
SN            : BFD1524C78510
HBA Model     : QLE2562
HBA Desc.     : QLE2562 PCI Express to 8Gb FC Dual Channel
FW Version    : 8.01.02
WWPN          : 21-00-00-24-FF-8D-98-E0
WWNN          : 20-00-00-24-FF-8D-98-E0
Link          : Online
=======================================================

    1:  Display HBA Parameters
    2:  Configure HBA Parameters
    3:  Restore Defaults


        (p or 0: Previous Menu; m or 98: Main Menu; x or 99: Quit)
        Please Enter Selection: 1
--------------------------------------------------------------------------------
HBA Instance 2: QLE2562 Port 1 WWPN 21-00-00-24-FF-8D-98-E0 PortID 03-07-00
Link: Online
--------------------------------------------------------------------------------
Connection Options             : 2 - Loop Preferred, Otherwise Point-to-Point
Data Rate                      : Auto
Frame Size                     : 2048
Hard Loop ID                   : 0
Loop Reset Delay (seconds)     : 5
Enable Host HBA BIOS           : Enabled
Enable Hard Loop ID            : Disabled
Enable FC Tape Support         : Enabled
Operation Mode                 : 0 - Interrupt for every I/O completion
Interrupt Delay Timer (100us)  : 0
**Execution Throttle             : 65535**
Login Retry Count              : 8
Port Down Retry Count          : 30
Enable LIP Full Login          : Enabled
Link Down Timeout (seconds)    : 30
Enable Target Reset            : Enabled
LUNs Per Target                : 128
Out Of Order Frame Assembly    : Disabled
Enable LR Ext. Credits         : Disabled
Enable Fabric Assigned WWN     : N/A

Press <Enter> to continue:
----
.. Enter * を押して続行します。
.. HBA Parameters メニューから Configure HBA Parameters オプションを選択して 'HBA パラメータを変更します
.. パラメータの設定メニューから ' スロットルの実行オプションを選択し ' このパラメータの値を更新します
+
[listing]
----
Configure Parameters Menu

=======================================================
HBA           : 2 Port: 1
SN            : BFD1524C78510
HBA Model     : QLE2562
HBA Desc.     : QLE2562 PCI Express to 8Gb FC Dual Channel
FW Version    : 8.01.02
WWPN          : 21-00-00-24-FF-8D-98-E0
WWNN          : 20-00-00-24-FF-8D-98-E0
Link          : Online
=======================================================

    1:  Connection Options
    2:  Data Rate
    3:  Frame Size
    4:  Enable HBA Hard Loop ID
    5:  Hard Loop ID
    6:  Loop Reset Delay (seconds)
    7:  Enable BIOS
    8:  Enable Fibre Channel Tape Support
    9:  Operation Mode
   10:  Interrupt Delay Timer (100 microseconds)
   11:  Execution Throttle
   12:  Login Retry Count
   13:  Port Down Retry Count
   14:  Enable LIP Full Login
   15:  Link Down Timeout (seconds)
   16:  Enable Target Reset
   17:  LUNs per Target
   18:  Enable Receive Out Of Order Frame
   19:  Enable LR Ext. Credits
   20:  Commit Changes
   21:  Abort Changes


        (p or 0: Previous Menu; m or 98: Main Menu; x or 99: Quit)
        Please Enter Selection: 11
Enter Execution Throttle [1-65535] [65535]: 65500
----
.. Enter * を押して続行します。
.. Configure Parameters メニューから、 Commit Changes オプションを選択して変更を保存します。
.. メニューを終了します。




link:../system-admin/index.html["システム管理"]
