---
permalink: upgrade/concept_when_you_need_to_update_the_disk_qualification_package.html 
sidebar: sidebar 
keywords: upgrade, ontap, dqp, disk, qualification, package 
summary: Disk Qualification Package （ DQP ）は、新しく認定されたドライブに対する完全なサポートを追加するためのパッケージです。ドライブファームウェアを更新したり、新しいタイプやサイズのドライブをクラスタに追加したりする前に、 DQP を更新する必要があります。また、四半期ごとや半年ごとなど、 DQP も定期的に更新することを推奨します。 
---
= Disk Qualification Package の更新が必要なタイミング
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Disk Qualification Package （ DQP ）は、新しく認定されたドライブに対する完全なサポートを追加するためのパッケージです。

ONTAP では、ディスクドライブが通常とは異なる方法で処理されます。たとえば、ONTAP では、メーカーが指定したセクターサイズとは異なるセクターサイズが割り当てられます。DQPには、新しく認定されたすべてのドライブに対するONTAP の適切なパラメータが含まれています。そのため、新しく認定されたドライブの情報が含まれないDQPを使用してONTAP のバージョンを実行している場合、ONTAP にはドライブを適切に設定するための情報が含まれていません。

DQPは、次の場合にダウンロードしてインストールする必要があります。また、四半期ごとや半年ごとなど、 DQP も定期的に更新することを推奨します。

* 新しいバージョンの ONTAP にアップグレードするとき
+
ONTAP のアップグレードの一環として DQP が更新されることはありません。

* 新しいタイプやサイズのドライブをノードに追加したとき
+
たとえば、 1TB のドライブを使用している環境で 2TB のドライブを追加した場合、 DQP の最新版がないかどうかを確認する必要があります。

* ディスクファームウェアを更新するたびに更新されます
* 新しいディスクファームウェアや DQP ファイルが利用可能になったとき


https://mysupport.netapp.com/site/downloads/firmware/disk-drive-firmware/download/DISKQUAL/ALL/qual_devices.zip["ネットアップのダウンロード： Disk Qualification Package"^]

https://mysupport.netapp.com/site/downloads/firmware/disk-drive-firmware["ネットアップのダウンロード：ディスクドライブファームウェア"]
