---
permalink: upgrade/concept_considerations_for_session_oriented_protocols.html 
sidebar: sidebar 
keywords: ontap, upgrade, update, considerations, session-oriented, protocols 
summary: クラスタおよびセッション指向プロトコルは、アップグレードの実行中、特定領域のクライアントおよびアプリケーションに原因の悪影響を及ぼす可能性があります。 
---
= セッション指向プロトコルに関する考慮事項
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
クラスタおよびセッション指向プロトコルは、アップグレードの実行中、特定領域のクライアントおよびアプリケーションに原因の悪影響を及ぼす可能性があります。

セッション指向プロトコルを使用する場合は、次の点を考慮してください。

* SMB
+
SMBv3 で継続的可用性（ CA ）共有を提供する場合は、自動無停止アップグレード方式（ System Manager または CLI を使用）を使用できます。クライアントによる中断は発生しません。

+
SMBv1 または SMBv2 を使用して共有を提供する場合、または SMBv3 を使用する CA 以外の共有を提供する場合は、アップグレードのテイクオーバー処理とリブート処理の実行時にクライアントセッションが中断されます。アップグレードの開始前に、ユーザにセッションを終了するように通知してください。

+
詳細については、を参照してください link:https://www.netapp.com/pdf.html?item=/media/16338-tr-4100pdf.pdf["TR-4100 ：『 Nondisruptive Operations with SMB File Shares ONTAP 9.x 』"^]。

+
Hyper-V および SQL Server over SMB はノンストップオペレーション（ NDO ）をサポートします。Hyper-V または SQL Server over SMB 解決策を設定した場合は、 ONTAP のアップグレード中にもアプリケーションサーバおよびそれに格納された仮想マシンやデータベースをオンラインのまま維持し、継続的可用性を実現します。

* NFSv4.x に対応している
+
NFSv4.x クライアントは、 NFSv4.x の通常のリカバリ手順を使用してアップグレードを実行する際に発生するネットワークの切断から自動的にリカバリします。このプロセスでは、アプリケーションの I/O が一時的に遅延することがあります。

* NDMP
+
状態が失われるので、クライアントユーザは操作を再試行する必要があります。

* バックアップとリストア
+
状態が失われるので、クライアントユーザは操作を再試行する必要があります。

+

IMPORTANT: アップグレードの実行中および開始直前は、バックアップまたはリストアを開始しないでください。データが失われる可能性があります。

* アプリケーション（ Oracle や Exchange など）
+
影響はアプリケーションによって異なります。タイムアウトベースのアプリケーションでは、タイムアウトの値を ONTAP のリブート時間よりも長く設定することで、悪影響を最小限に抑えることができます。


