---
permalink: upgrade/concept_mixed_version_requirements.html 
sidebar: sidebar 
keywords: ontap, upgrade, mixed, version, clusters, mixed-version nodes, requirements 
summary: バージョンが混在したONTAPクラスタは、2つの異なるメジャーONTAPリリース（ONTAP 9.8と9.12.1など）を実行するノードで構成されます。バージョンの混在ONTAPクラスタは、特定のシナリオでのみNetAppでサポートされます。 
---
= バージョンが混在したONTAPクラスタ
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
バージョンが混在したONTAPクラスタは、2つの異なるメジャーONTAPリリースを一定期間実行するノードで構成されます。  たとえば、ONTAP 9.8と9.12.1を実行するノードで構成されたクラスタは、バージョンが混在したクラスタです。  同様に、ノードでONTAP 9.9.1と9.13.1が実行されているクラスタは、バージョンが混在したクラスタです。  NetAppでは、一定期間、特定のシナリオにおいて、バージョンの異なるONTAPクラスタが混在してサポートされます。

ONTAPクラスタに複数のバージョンが混在する一般的なシナリオを次に示します。

* 大規模なクラスタでのONTAPソフトウェアのアップグレード
* クラスタに新しいノードを追加する場合は、ONTAPソフトウェアのアップグレードが必要です


AFF AシリーズおよびCシリーズ、ASA、FAS、Cシリーズシステムなど、NetAppプラットフォームシステムをサポートする 環境 ONTAPのバージョン情報。この情報は、9.12.0などのONTAPクラウドリリース（9.x.0）には適用されません。



== バージョンが混在したONTAPクラスタの要件

クラスタに複数のONTAPバージョンが混在する状態にする必要がある場合は、重要な要件と制限事項に注意する必要があります。

* 1つのクラスタに同時に使用できるメジャーONTAPバージョンは2つまでです。同じONTAPリリースのPパッチレベルまたはDパッチレベルが異なるノード（ONTAP 9.9.1P1と9.9.1P5など）を含むクラスタは、バージョンが混在したONTAPクラスタとはみなされません。
* クラスタに複数のバージョンが混在している間は、アップグレードプロセスやデータ移行プロセスに必要なコマンドを除き、クラスタの処理や構成を変更するコマンドは実行しないでください。  たとえば、LIFの移行、ストレージの計画的フェイルオーバー処理、大規模オブジェクトの作成や破棄などのアクティビティは、アップグレードとデータ移行が完了するまで実行しないでください。
* クラスタが最適に動作するためには、クラスタに複数のバージョンが混在した状態になるまでの時間をできるだけ短くする必要があります。  クラスタに複数のバージョンが混在した状態を維持できる最大期間は、クラスタ内の最も低いONTAPバージョンによって異なります。
+
[cols="2*"]
|===
| バージョンが混在したクラスタで実行されているONTAPの最下位バージョンが次の場合： | その後、最大でバージョンが混在した状態のままにすることができます 


| ONTAP 9.8以降 | 90日 


| ONTAP 9.7以前 | 7日 
|===
* ONTAP 9.8以降では、複数のバージョンが混在したONTAPクラスタで最大5つのメジャーリリースを使用できます。たとえば、バージョンが混在したONTAPクラスタでは、ONTAP 9.8と9.12.1を実行しているノードや、ONTAP 9.9.1と9.13.1を実行しているノードを使用できます。ONTAP 9.8と9.13.1を実行するノードを含むバージョンが混在したONTAPクラスタは、6つのメジャーリリースにわたるクラスタで構成されるため、サポートされません。




== 大規模クラスタのONTAPバージョンの更新

バージョンが混在したクラスタ状態になるシナリオの1つは、複数のノードを含むクラスタのONTAPバージョンをアップグレードして、ONTAP 9の新しいバージョンで利用できる機能を利用することです。大規模なクラスタのONTAPバージョンをアップグレードする必要がある場合は、クラスタ内の各ノードをアップグレードする間、一定期間バージョンが混在したクラスタ状態になります。



== 新しいノードをクラスタに追加しています

バージョンが混在したクラスタ状態になるもう1つのシナリオは、クラスタに新しいノードを追加することです。クラスタに新しいノードを追加して容量を拡張したり、コントローラを完全に交換するプロセスで新しいノードを追加したりできます。どちらの場合も、既存のコントローラから新しいシステムの新しいノードにデータを移行できるようにする必要があります。

クラスタに新しいノードを追加する予定で、それらのノードにクラスタで現在実行されているバージョンよりも新しいバージョンのONTAPが必要な場合は、新しいノードを追加する前に、クラスタ内の既存のノードでサポートされるソフトウェアのアップグレードを実行する必要があります。

既存のすべてのノードを、クラスタに追加するノードに必要な最小バージョンのONTAPにアップグレードするのが理想的です。ただし、既存のノードの一部で新しいバージョンのONTAPがサポートされていないためにこれができない場合は、アップグレードプロセスの一環として、限られた時間だけバージョンが混在した状態にする必要があります。新しいコントローラに必要な最小ONTAPバージョンをサポートしていないノードがある場合は、次の手順を実行する必要があります。

. link:https://docs.netapp.com/us-en/ontap/upgrade/concept_upgrade_methods.html["アップグレード"] 新しいコントローラで必要な最小ONTAPバージョンをサポートしていないノードが、新しいコントローラでサポートされる最大ONTAPバージョンまで。
+
たとえば、ONTAP 9.5を実行しているFAS8000で、ONTAP 9.12.1を実行している新しいCシリーズプラットフォームを追加する場合は、FAS8000をONTAP 9.8（ONTAPでサポートされる最大バージョン）にアップグレードする必要があります。

. 新しいノードをクラスタに追加します。
+
ONTAPコマンドclusterを使用します `add-node -allow-mixed-version-join` advanced権限レベルで実行し、新しいノードに追加します。

. アップグレードできないノードから、上位のバージョンのONTAPを実行しているノードにデータを移行します。
. link:https://docs.netapp.com/us-en/ontap/system-admin/remov-nodes-cluster-concept.html["サポート対象外のノードをクラスタから削除します"^]。
. link:https://docs.netapp.com/us-en/ontap/upgrade/concept_upgrade_methods.html["アップグレード"] クラスタ内の残りのノードを新しいノードと同じバージョンに変更します。
+
必要に応じて、クラスタ全体（新しいノードを含む）を link:https://kb.netapp.com/Support_Bulletins/Customer_Bulletins/SU2["推奨される最新のパッチリリース"] 新しいノードで実行されているONTAPのバージョン。



データ移行の詳細については、以下を参照してください。

* link:https://docs.netapp.com/us-en/ontap-systems-upgrade/upgrade/upgrade-create-aggregate-move-volumes.html["アグリゲートを作成してボリュームを新しいノードに移動"^]
* link:https://docs.netapp.com/us-en/ontap-metrocluster/transition/task_move_linux_iscsi_hosts_from_mcc_fc_to_mcc_ip_nodes.html#setting-up-new-iscsi-connections["SANボリュームの移動用に新しいiSCSI接続をセットアップします"^]
* link:https://docs.netapp.com/us-en/ontap/encryption-at-rest/encrypt-existing-volume-task.html["暗号化を使用してボリュームを移動する"^]

