---
permalink: upgrade/concept_mixed_version_requirements.html 
sidebar: sidebar 
keywords: ontap, upgrade, mixed, version, requirements 
summary: ONTAP 9.3以降では、デフォルトで、既存のノードで実行されているバージョンと異なるバージョンのONTAP を実行している新しいノードをクラスタに追加することはできません。 
---
= 異なるバージョンの混在に関する要件
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
ONTAP 9.3以降では、デフォルトで、既存のノードで実行されているバージョンと異なるバージョンのONTAP を実行している新しいノードをクラスタに追加することはできません。

既存のクラスタのノードで実行されている ONTAP よりもあとのバージョンの が実行されている新しいノードをクラスタに追加する場合は、既存のクラスタのノードをそれ以降のバージョンにアップグレードしてから、新しいノードを追加する必要があります。

クラスタに異なるバージョンが混在した状態は推奨されませんが、一時的にやむを得ずバージョンが混在した状態になる場合があります。たとえば、既存のクラスタの特定のノードで新しいバージョンの ONTAP がサポートされない場合は、そのバージョンの ONTAP にアップグレードすると、一時的に異なるバージョンが混在した状態になります。この場合は、新しいバージョンのONTAP をサポートするノードをアップグレードしてから、次のコマンドを使用して、アップグレードするONTAP のバージョンをサポートしていないノードを削除する必要があります。

[cols="2"]
|===
| ONTAP バージョン | コマンドを実行します 


 a| 
ONTAP 9.3
 a| 
`cluster unjoin -skip-last-low-version-node-check`



 a| 
ONATP 9.4以降
 a| 
`cluster remove-node -skip-last-low-version-node-check`

|===
また、機器更改や停止を伴うアップグレードを行う際にも、一時的に異なるバージョンが混在した状態になります。このような場合は、ONTAP のデフォルトの動作を上書きして、を使用して別のバージョンのノードを追加できます `cluster add-node -allow-mixed-version-join` advanced権限のコマンド。

バージョンが混在した状態にする必要がある場合は、できるだけ速やかにアップグレードを完了する必要があります。

ONTAP 9.8以降では、クラスタ内の他のHAペアとは異なるリリースのONTAPバージョンをHAペアで90日以上実行することはできません。ONTAP 9.7以前のHAペアで、クラスタ内の他のHAペアとは異なるリリースのONTAPバージョンを7日以上実行しないでください。

クラスタが正しく動作するためには、クラスタに異なるバージョンが混在する期間を可能なかぎり短くする必要があります。

クラスタに異なるバージョンが混在した状態の間は、アップグレードに必要なコマンドを除き、クラスタの処理や構成を変更するコマンドは実行しないでください。
