---
permalink: upgrade/download-software-image.html 
sidebar: sidebar 
keywords: ontap, software, image, download, downloading, upgrade 
summary: 現在のONTAPバージョンに応じて、アップグレードの対象となるONTAPソフトウェア イメージを HTTPs、HTTP または FTP サーバー、あるいはローカル フォルダにダウンロードできます。 
---
= アップグレード前にONTAPソフトウェアイメージをダウンロードする
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
ONTAPをアップグレードする前に、まずはターゲットのONTAPソフトウェア イメージをNetAppサポート サイトからダウンロードする必要があります。ONTAPのリリースに応じて、ネットワーク上のHTTP / HTTPS / FTP各サーバかローカル フォルダに、ONTAPソフトウェア イメージをダウンロードします。

[cols="2"]
|===
| 実行中の場合... | イメージをダウンロードできる場所 


| ONTAP 9.6以降  a| 
* HTTPS サーバー + サーバーの CA 証明書をローカル システムにインストールする必要があります。
* ローカル フォルダ
* HTTPサーバまたはFTPサーバ




| ONTAP 9.4以降  a| 
* ローカル フォルダ
* HTTPサーバまたはFTPサーバ




| ONTAP 9.0以降 | HTTPサーバまたはFTPサーバ 
|===
.タスク概要
* link:concept_upgrade_paths.html#types-of-upgrade-paths["直接マルチホップアップグレードパス"]を使用して自動無停止アップグレード（ANDU）を実行する場合は、link:download-software-image.html["ダウンロード"]アップグレードに必要な中間ONTAPバージョンのソフトウェアパッケージとターゲットONTAPバージョンのソフトウェアパッケージの両方をダウンロードする必要があります。たとえば、ONTAP 9.8からONTAP 9.13.1にアップグレードする場合は、ONTAP 9.12.1とONTAP 9.13.1の両方のソフトウェアパッケージをダウンロードする必要があります。アップグレードパスで中間ソフトウェアパッケージのダウンロードが必要かどうかを確認するには、link:concept_upgrade_paths.html#supported-upgrade-paths["サポートされているアップグレード パス"]を参照してください。
* NetApp Volume Encryptionを搭載したシステムをONTAP 9.5以降にアップグレードする場合は、規制対象外の国用の（NetApp Volume Encryptionを含む）ONTAPソフトウェア イメージをダウンロードする必要があります。
+
規制対象国用のONTAPソフトウェア イメージを使用してNetApp Volume Encryptionを搭載したシステムをアップグレードすると、システムがパニック状態になり、ボリュームへのアクセスが失われます。

* ファームウェア用にソフトウェア パッケージを別途ダウンロードする必要はありません。クラスタのファームウェア更新はONTAPソフトウェアのアップグレード パッケージに含まれており、各ノードのブート デバイスにコピーされます。その後、新しいファームウェアがアップグレード プロセス中にインストールされます。


.手順
. NetAppサポート サイトのlink:https://mysupport.netapp.com/site/products/all/details/ontap9/downloads-tab["ソフトウェアのダウンロード"^]領域で対象のONTAPソフトウェアを見つけます。
+
ONTAP Selectアップグレードの場合は、*ONTAP Selectノード アップグレード*を選択します。

. ソフトウェア イメージ（97_q_image.tgzなど）を適切な場所にコピーします。
+
ONTAPのリリースに応じて、HTTP、HTTPS、またはFTPサーバ上のディレクトリ（ここからイメージをローカル システムに提供）、あるいはストレージ システム上のローカル フォルダにコピーします。


