---
permalink: upgrade/index.html 
sidebar: sidebar 
keywords: upgrade overview, upgrade, digital advisor, summary, upgrade ontap, upgrading ontap, upgrade, upgrading, ontap, software, on-premise, prepare, preparation, major upgrade, minor upgrade, patch upgrade, upgrade assistance, upgrade help, upgrade technical support 
summary: ONTAPをアップグレードすると、新しい機能や拡張された機能を利用できます。推奨される手順に従って、アップグレードを準備してから開始してください。 
---
= ONTAPのアップグレードの概要
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
ONTAPソフトウェアをアップグレードすると、ONTAPの新機能や強化された機能を活用して、コストの削減、重要なワークロードの高速化、セキュリティの強化、組織で利用できるデータ保護の範囲の拡大を実現できます。

ONTAPのメジャーアップグレードでは、ONTAPの番号が小さいリリースから大きいリリースに移行します。たとえば、クラスタをONTAP 9 .8からONTAP 9 .12.1にアップグレードします。  マイナー（またはパッチ）アップグレードでは、同じ番号のリリース内で、下位のONTAPバージョンから上位のONTAPバージョンに移行します。たとえば、クラスタをONTAP 9 .12.1P1から9.12.1P4にアップグレードする場合などです。

始めるには、する必要がありますlink:prepare.html["アップグレードを準備"]。Active IQデジタルアドバイザ(デジタルアドバイザとも呼ばれます)の有効なSupportEdge契約がある場合は、次のlink:create-upgrade-plan.html["Upgrade Advisorを使用したアップグレード計画"]手順を実行してください。Upgrade Advisorは、クラスタを評価し、構成に固有のアップグレードプランを作成することで、不確実性とリスクを最小限に抑えるためのインテリジェンスを提供します。

アップグレードの準備が完了したら、を使用してアップグレードを実行することを推奨しlink:task_upgrade_andu_sm.html["System Managerからの自動無停止アップグレード（ANDU）"]ます。ANDUは、ONTAPの高可用性（HA）フェイルオーバーテクノロジを活用して、アップグレード中もクラスタが中断することなくデータを提供し続けます。


NOTE: ONTAP 9 12.1以降では、System ManagerはBlueXP  と完全に統合されています。システムにBlueXP  が設定されている場合は、BlueXP  作業環境を使用してアップグレードできます。

ONTAPソフトウェアのアップグレードについてサポートが必要な場合は、NetAppプロフェッショナルサービスをご利用link:https://www.netapp.com/pdf.html?item=/media/8144-sd-managed-upgrade-service.pdf["マネージドアップグレードサービス"^]ください。このサービスの利用をご希望の場合は、NetAppの営業担当者またはにお問い合わせくださいlink:https://www.netapp.com/forms/sales-contact/["ネットアップの営業問い合わせフォームを送信する"^]。マネージドアップグレードサービスおよびその他のタイプのアップグレードサポートは、追加料金なしで利用できlink:https://www.netapp.com/pdf.html?item=/media/8845-supportedge-expert-service.pdf["SupportEdge Expertサービス"^]ます。
