---
permalink: upgrade/index.html 
sidebar: sidebar 
keywords: upgrade overview, upgrade, digital advisor, summary, upgrade ontap, upgrading ontap, upgrade, upgrading, ontap, software, on-premise, prepare, preparation, major upgrade, minor upgrade, patch upgrade, upgrade assistance, upgrade help, upgrade technical support 
summary: ONTAPをアップグレードすると、新機能や拡張機能を活用できるようになります。アップグレードを開始する前に、推奨手順に従って準備を進めてください。 
---
= ONTAPアップグレードについて学ぶ
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
ONTAPソフトウェアをアップグレードすると、ONTAPの新機能や強化された機能がもたらす、コストの削減、重要なワークロードの高速化、セキュリティの強化、データが保護される範囲の拡大といったメリットを、組織全体で享受できます。

ONTAPのメジャー アップグレードとは、ONTAPのリリース番号が小さいものから大きなものへの移行です。たとえば、クラスタをONTAP 9.8からONTAP 9.12.1にアップグレードする場合です。マイナー（またはパッチ）アップグレードは、同じリリース番号内での、下位バージョンから上位バージョンへのONTAPの移行です。たとえば、クラスタをONTAP 9.12.1P1から9.12.1P4にアップグレードする場合です。

まず、アップグレードの準備をする必要があります。Active IQ Digital Advisor（Digital Advisorとも呼ばれます）の有効なSupportEdge契約をお持ちの場合は、link:create-upgrade-plan.html["Upgrade Advisorでアップグレードを準備する"]してください。Upgrade Advisorは、クラスタを評価し、構成に応じたアップグレード計画を作成することで、不確実性とリスクを最小限に抑えるのに役立つインテリジェンスを提供します。Active IQ Digital Advisorの有効なSupportEdge契約をお持ちでない場合は、link:prepare.html["Upgrade Advisorを使用せずにアップグレードを準備する"]してください。

アップグレードの準備ができたら、link:task_upgrade_andu_sm.html["System Managerからの自動無停止アップグレード（ANDU）"]を使用してアップグレードを実行することをお勧めします。ANDUはONTAPの高可用性（HA）フェイルオーバー テクノロジを活用して、アップグレード中にクラスタが中断することなく引き続きデータを提供することを保証します。


NOTE: ONTAP 9.12.1以降、System ManagerはNetApp Consoleと完全に統合されています。システムにConsoleが設定されている場合は、「システム」ページからアップグレードできます。

ONTAPソフトウェアのアップグレードに関するサポートが必要な場合は、NetAppプロフェッショナル サービスがlink:https://www.netapp.com/pdf.html?item=/media/8144-sd-managed-upgrade-service.pdf["マネージドアップグレードサービス"^]を提供します。このサービスをご利用になりたい場合は、NetApp営業担当者またはlink:https://www.netapp.com/forms/sales-contact/["NetAppの販売問い合わせフォームを送信する"^]にお問い合わせください。マネージド アップグレード サービスおよびその他のアップグレード サポートは、link:https://www.netapp.com/pdf.html?item=/media/8845-supportedge-expert-service.pdf["SupportEdge Expertサービス"^]をご利用のお客様に追加料金なしでご利用いただけます。

.関連情報
* link:concept_upgrade_paths.html["サポートされているアップグレード パス"]

