---
permalink: upgrade/install-software-manual-upgrade.html 
sidebar: sidebar 
keywords: ontap, software, image, download, downloading, install, installing. manual, manually 
summary: 手動アップグレード用の ONTAP ソフトウェア パッケージをダウンロードしたら、アップグレードを開始する前にローカルにインストールする必要があります。 
---
= 手動アップグレードのためのONTAPソフトウェア パッケージのインストール
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
手動アップグレード用のONTAPソフトウェア パッケージをダウンロードしたら、アップグレードを開始する前に、ローカルにインストールする必要があります。

.手順
. 権限レベルを advanced に設定し、続行するかどうかを尋ねられたら *y* と入力します： `set -privilege advanced`
+
詳細プロンプト（(`*>`）が表示されます。

. イメージをインストールします。
+
[cols="2"]
|===
| 構成 | 使用するコマンド 


 a| 
** MetroCluster以外
** 2ノード MetroCluster

 a| 
[source, cli]
----
system node image update -node * -package <location> -replace-package true -setdefault true -background true
----
`<location>`は、ONTAPのバージョンに応じて、Webサーバーまたはローカルフォルダを指定できます。link:https://docs.netapp.com/us-en/ontap-cli/system-node-image-update.html["ONTAPコマンド リファレンス"^]の `system node image update`の詳細をご覧ください。

このコマンドは、すべてのノードにソフトウェア イメージを同時にインストールします。各ノードにイメージを 1 つずつインストールする場合は、 `-background` パラメータを指定しないでください。



 a| 
** 4ノードMetroCluster
** 8ノードMetroCluster構成

 a| 
[source, cli]
----
system node image update -node * -package <location> -replace-package true -background true -setdefault false
----
このコマンドは両方のクラスタで発行する必要があります。

このコマンドは、拡張クエリを使用して、代替イメージとしてインストールされるターゲットのソフトウェア イメージを変更します。

|===
. プロンプトが表示されたら `y`を押して続行します。
. ソフトウェア イメージが各ノードにインストールされたことを確認します。
+
[source, cli]
----
system node image show-update-progress -node *
----
+
このコマンドは、ソフトウェアイメージのインストールの現在のステータスを表示します。すべてのノードの*Run Status*が*Exited*、*Exit Status*が*Success*と報告されるまで、このコマンドを実行し続けてください。

+
system node image updateコマンドが失敗して、エラーまたは警告メッセージが表示されることがあります。その場合は、エラーまたは警告をすべて解決すると再度コマンドを実行できます。

+
次の例では、2ノード クラスタの両方のノードにソフトウェア イメージをインストールし、処理が成功しています。

+
[listing]
----
cluster1::*> system node image show-update-progress -node *
There is no update/install in progress
Status of most recent operation:
        Run Status:     Exited
        Exit Status:    Success
        Phase:          Run Script
        Exit Message:   After a clean shutdown, image2 will be set as the default boot image on node0.
There is no update/install in progress
Status of most recent operation:
        Run Status:     Exited
        Exit Status:    Success
        Phase:          Run Script
        Exit Message:   After a clean shutdown, image2 will be set as the default boot image on node1.
2 entries were acted on.
----

