---
permalink: upgrade/prepare.html 
sidebar: sidebar 
keywords: upgrade, ontap, prepare, digital advisor, preparation, before you upgrade, plan, upgrade overview, upgrade summary 
summary: ONTAPのアップグレードを準備すると、アップグレードのリスクや障害を特定して軽減し、構成に適用される特別な考慮事項を考慮することができます。 
---
= Upgrade Advisorを使用せずにONTAPソフトウェアのアップグレードを準備する
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
ONTAPソフトウェアのアップグレードを適切に準備することで、アップグレードプロセスを開始する前に、アップグレードの潜在的なリスクや障害を特定して軽減することができます。アップグレードの準備中に、アップグレード前に考慮する必要がある特別な考慮事項を特定することもできます。たとえば、クラスタでSSL FIPSモードが有効になっていて、管理者アカウントで認証にSSH公開鍵を使用している場合は、ホストキーのアルゴリズムがターゲットのONTAPリリースでサポートされていることを確認する必要があります。

の有効なSupportEdge契約がある場合はlink:https://docs.netapp.com/us-en/active-iq/upgrade_advisor_overview.html["Digital Advisor"^]、link:create-upgrade-plan.html["Upgrade Advisorを使用したアップグレード計画"]を参照してください。Active IQデジタルアドバイザ（デジタルアドバイザとも呼ばれます）にアクセスできない場合は、次の手順を実行してONTAPアップグレードの準備を行う必要があります。

. link:choose-target-version.html["ターゲットのONTAPリリースを選択"]です。
. ターゲットリリースのを確認しますlink:../release-notes/index.html["ONTAPリリースノート"]。
+
「アップグレードに関する注意事項」セクションでは、新しいリリースにアップグレードする前に把握しておく必要がある潜在的な問題について説明します。「新機能」および「既知の問題と制限」セクションでは、新しいリリースへのアップグレード後の新しいシステム動作について説明します。

. link:confirm-configuration.html["ハードウェア構成に対するONTAPのサポートの確認"]です。
+
ハードウェアプラットフォーム、クラスタ管理スイッチ、およびMetroCluster IPスイッチがターゲットリリースをサポートしている必要があります。クラスタがSAN用に構成されている場合は、SAN構成が完全にサポートされている必要があります。

. link:task_check_for_common_configuration_errors_using_config_advisor.html["Active IQ Config Advisorを使用して、一般的な構成エラーがないことを確認します。"]
. サポートされているONTAPを参照してlink:concept_upgrade_paths.html#supported-upgrade-paths["アップグレードパス"]、直接アップグレードが可能か、アップグレードを段階的に完了する必要があるかを確認します。
. link:task_verifying_the_lif_failover_configuration.html["LIFフェイルオーバーの設定を確認する"]です。
+
アップグレードを実行する前に、クラスタのフェイルオーバーポリシーとフェイルオーバーグループが正しく設定されていることを確認する必要があります。

. link:concept_verify_svm_routing.html["SVMルーティング設定の確認"]です。
. link:special-considerations.html["特別な考慮事項の確認"]をクリックします。
+
クラスタに特定の構成がある場合は、ONTAPソフトウェアのアップグレードを開始する前に特定の操作を実行する必要があります。

. link:reboot-sp-bmc.html["SPまたはBMCをリブートする"]です。

