---
permalink: upgrade/reboot-sp-bmc.html 
sidebar: sidebar 
keywords: ontap, upgrade, how, firmware, updated, during, digital advisor 
summary: ONTAPのアップグレード前にファームウェアを更新する必要はありません。クラスタのファームウェアはONTAPアップグレードパッケージに含まれており、アップグレードプロセスの一環としてインストールされます。 
---
= SPまたはBMCをリブートしてONTAPアップグレード時のファームウェア更新を準備する
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
ONTAPのアップグレード前にファームウェアを手動で更新する必要はありません。クラスタのファームウェアはONTAPアップグレードパッケージに含まれており、各ノードのブートデバイスにコピーされます。新しいファームウェアは、アップグレードプロセスの一環としてインストールされます。

クラスタ内の次のコンポーネントのファームウェアのバージョンがONTAPアップグレードパッケージにバンドルされているファームウェアより古い場合は、自動的に更新されます。

* BIOS / Loader
* サービスプロセッサ（SP）またはベースボード管理コントローラ（BMC）
* ストレージシェルフ
* ディスク
* Flash Cache


スムーズに更新できるよう準備するには、アップグレードを開始する前にSPまたはBMCをリブートする必要があります。

ONTAP CLI、 SP 、またはBMCを使用して再起動します。

[role="tabbed-block"]
====
.CLI
--
. SPまたはBMCを再起動します。
+
[source, cli]
----
system service-processor reboot-sp -node <node_name>
----


--
.SP
--
. SPを再起動します。
+
[source, cli]
----
sp reboot
----


--
.BMC
--
. BMCを再起動します。
+
[source, cli]
----
bmc reboot
----


--
====
一度に1つのSPまたはBMCだけをリブートします。リブートしたSPまたはBMCが完全にリサイクルされるまで待ってから、次のSPまたはBMCをリブートします。

ONTAPのアップグレード間のアップグレードも可能ですlink:../update/firmware-task.html["ファームウェアを手動で更新します"]。Digital Advisorをお持ちの場合は可能ですlink:https://activeiq.netapp.com/system-firmware/["ONTAP イメージに現在含まれているファームウェアバージョンのリストを表示します"^]。

更新されたファームウェアバージョンは次のとおりです。

* link:https://mysupport.netapp.com/site/downloads/firmware/system-firmware-diagnostics["システムファームウェア（BIOS、BMC、SP）"^]
* link:https://mysupport.netapp.com/site/downloads/firmware/disk-shelf-firmware["シェルフファームウェア"^]
* link:https://mysupport.netapp.com/site/downloads/firmware/disk-drive-firmware["ディスクおよびFlash Cacheファームウェア"^]

