---
permalink: upgrade/remove-ems-lif-service-task.html 
sidebar: sidebar 
keywords: ontap, upgrade, after, post, ems, event, management, system, lifs, messages, not, delivered 
summary: EMSを使用している場合は、ONTAP 9.7以前から9.8以降にアップグレードしたあとに、特定のネットワークサービスポリシーからEMS LIFサービスの削除が必要になることがあります。 
---
= ONTAPのアップグレード後にネットワークサービスポリシーからEMS LIFサービスを削除する
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
ONTAP 9.7以前からONTAP 9.8以降にアップグレードする前にイベント管理システム（EMS）メッセージが設定されている場合、アップグレード後にEMSメッセージが配信されないことがあります。

アップグレードでは、EMS LIFサービスであるmanagement-emsが既存のすべてのサービスポリシーに追加されます。これにより、いずれかのサービスポリシーに関連付けられているLIFからEMSメッセージを送信できます。選択したLIFにイベント通知の送信先に到達できない場合、メッセージは配信されません。

これを回避するには、アップグレード後に、デスティネーションへの到達可能性を提供しないネットワークサービスポリシーからEMS LIFサービスを削除する必要があります。

.手順
. EMSメッセージの送信に使用するLIFと関連するネットワークサービスポリシーを特定します。
+
[source, cli]
----
network interface show -fields service-policy -services management-ems
----
+
[listing]
----
vserver        lif            service-policy
-------------- ------------ ------------------
cluster-1      cluster_mgmt
                                      default-management
cluster-1      node1-mgmt
                                      default-management
cluster-1      node2-mgmt
                                      default-management
cluster-1      inter_cluster
                                      default-intercluster
4 entries were displayed.
----
. 各LIFがEMSデスティネーションに接続されているかどうかを確認します。
+
[source, cli]
----
network ping -lif <lif_name> -vserver <svm_name> -destination <destination_address>
----
+
各ノードでこの手順を実行します。

+
.例
[listing]
----
cluster-1::> network ping -lif node1-mgmt -vserver cluster-1 -destination 10.10.10.10
10.10.10.10 is alive

cluster-1::> network ping -lif inter_cluster -vserver cluster-1 -destination 10.10.10.10
no answer from 10.10.10.10
----
. advanced権限レベルに切り替えます。
+
[source, cli]
----
set advanced
----
. 到達可能性がないLIFについては、対応するサービスポリシーからmanagement-ems LIFサービスを削除します。
+
[source, cli]
----
network interface service-policy remove-service -vserver <svm_name> -policy <service_policy_name> -service management-ems
----
. management-ems LIFが、EMSデスティネーションに到達できるようにするLIFにのみ関連付けられていることを確認します。
+
[source, cli]
----
network interface show -fields service-policy -services management-ems
----


.関連リンク
link:https://docs.netapp.com/us-en/ontap/networking/lifs_and_service_policies96.html#service-policies-for-system-svms.["LIFとサービス ポリシー（ONTAP 9.6以降）"]
