---
permalink: upgrade/task_verifying_the_san_configuration.html 
sidebar: sidebar 
keywords: ontap, upgrade, verify, verifying, san, configuration 
summary: SANクラスタをアップグレードする前に、適切な数の直接パスと間接パスを使用して各ホストが設定されていること、および各ホストが適切なLIFに接続されていることを確認する必要があります。 
---
= SANホスト構成の確認 - ONTAPのアップグレード前
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
SAN環境でONTAPのアップグレードを実行すると、直接パスが変更されます。SANクラスタをアップグレードする前に、適切な数の直接パスと間接パスを使用して各ホストが設定されていること、および各ホストが適切なLIFに接続されていることを確認する必要があります。

.手順
. 各ホストで、十分な数の直接パスと間接パスが設定されていること、およびそれぞれのパスがアクティブであることを確認します。
+
各ホストには、クラスタ内のそれぞれのノードへのパスが必要です。

. 各ホストがそれぞれのノード上のLIFに接続されていることを確認します。
+
アップグレード後の比較用に、イニシエータの一覧を記録してください。ONTAP 9.11.1以降を実行している場合は、System Managerを使用すると、CLIよりもはるかに明確に接続ステータスを表示できます。

+
[role="tabbed-block"]
====
.System Manager
--
.. System Manager で、*ホスト > SAN イニシエーター グループ* をクリックします。
+
イニシエータ グループ（igroup）のリストが表示されます。リストが1ページに収まらない場合は、ページ右下にあるページ番号をクリックして次のページを表示できます。

+
igroupに関するさまざまな情報が各列に表示されます。9.11.1以降では、igroupの接続ステータスも表示されます。ステータス アラートにカーソルを合わせると詳細が表示されます。



--
.CLI
--
** iSCSIイニシエータのリストを表示します。
+
[source, cli]
----
iscsi initiator show -fields igroup,initiator-name,tpgroup
----
** FCイニシエータのリストを表示します。
+
[source, cli]
----
fcp initiator show -fields igroup,wwpn,lif
----


--
====

