---
permalink: upgrade/task_verifying_storage_health_verifying_that_the_cluster_is_ready.html 
sidebar: sidebar 
keywords: ontap, upgrade, upgrading, verify, verifying, storage, health 
summary: クラスタのアップグレード前とアップグレード後に、ディスク、アグリゲート、およびボリュームのステータスを確認する必要があります。 
---
= ストレージの健常性を確認
:hardbreaks:
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
クラスタのアップグレード前とアップグレード後に、ディスク、アグリゲート、およびボリュームのステータスを確認する必要があります。

. ディスクのステータスを確認します。
+
[cols="2*"]
|===
| 確認する項目 | 手順 


 a| 
破損ディスク
 a| 
.. 破損ディスクを表示します。
`storage disk show -state broken`
.. 破損ディスクを取り外すか交換します。




 a| 
メンテナンス中または再構築中のディスク
 a| 
.. 保守、保留、または再構築の状態のディスクを表示します。
`storage disk show -state maintenance|pending|reconstructing`
.. メンテナンスまたは再構築の処理が完了するまで待ってから次に進みます。


|===
. 状態を表示して、すべてのアグリゲートがオンラインであることを確認します。
`storage aggregate show -state !online`このコマンドを実行すると、オンラインでないアグリゲートが表示されます。メジャーアップグレードまたはリバートの実行前と実行後には、すべてのアグリゲートがオンラインになっている必要があります。
+
[listing]
----
cluster1::> storage aggregate show -state !online
There are no entries matching your query.
----
. 次のコマンドを実行して、すべてのボリュームがオンラインであることを確認します。 _not_online
`volume show -state !online`メジャーアップグレードまたはリバートの実行前と実行後には、すべてのボリュームがオンラインになっている必要があります。
+
[listing]
----
cluster1::> volume show -state !online
There are no entries matching your query.
----
. 整合性のないボリュームがないことを確認します。
`volume show -is-inconsistent true`サポート技術情報の記事を参照してください link:https://kb.netapp.com/Advice_and_Troubleshooting/Data_Storage_Software/ONTAP_OS/Volume_Showing_WAFL_Inconsistent["「WAFL inconsistent」を示すボリューム"] を参照してください。


.関連情報
link:../volumes/index.html["論理ストレージ管理"]
