---
permalink: upgrade/task_updating_a_two_node_metrocluster_configuration_in_ontap_9_2_and_earlier.html 
sidebar: sidebar 
keywords: ontap, upgrade, two-node, metrocluster, mcc, 9.2, earlier 
summary: 9.2以前を実行している2ノードMetroCluster構成の場合は、この手順をONTAPのアップグレードに使用してください。 
---
= ONTAP 9.2以前での2ノードMetroCluster構成の手動無停止アップグレード
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
2 ノード MetroCluster 構成の ONTAP は、無停止でアップグレードできます。この方法には、ネゴシエートスイッチオーバーの開始、「 failed 」サイトでのクラスタの更新、スイッチバックの開始、もう一方のサイトのクラスタでの処理の繰り返しの手順が含まれます。

[NOTE]
====
この手順は、 ONTAP 9.2 以前を実行している 2 ノード MetroCluster 構成専用です。

ONTAP 9.3以降を実行している2ノードMetroCluster構成の場合は、 xref:task_upgrade_andu_sm.html[System Manager を使用した自動無停止アップグレード]。

====
. 権限レベルをadvancedに設定します。続行するかどうかを尋ねられたら、「* y *」と入力します。 `set -privilege advanced`
+
advancedプロンプトが表示されます (`*>`）が表示されます。

. アップグレードするクラスタで、新しいONTAP ソフトウェアイメージをデフォルトとしてインストールします。 `system node image update -package package_location -setdefault true -replace-package true`
+
[listing]
----
cluster_B::*> system node image update -package http://www.example.com/NewImage.tgz -setdefault true -replace-package true
----
. ターゲットのソフトウェアイメージがデフォルトのイメージとして設定されたことを確認します。 `system node image show`
+
次の例はそれを示しています `NewImage` デフォルトのイメージとして設定されています。

+
[listing]
----
cluster_B::*> system node image show
                    Is      Is                           Install
Node     Image      Default Current Version              Date
-------- -------    ------- ------- -------------------- -------------------
node_B_1
         OldImage  false   true    X.X.X                MM/DD/YYYY TIME
         NewImage  true    false   Y.Y.Y                MM/DD/YYYY TIME
2 entries were displayed.
----
. ターゲットのソフトウェアイメージがデフォルトのイメージとして設定されていない場合は、変更します。 `system image modify {-node * -iscurrent false} -isdefault true`
. すべてのクラスタSVMが健全な状態であることを確認します。 `metrocluster vserver show`
. 更新されていないクラスタで、ネゴシエートスイッチオーバーを開始します。 `metrocluster switchover`
+
この処理には数分かかることがあります。MetroCluster operation show コマンドを使用して、スイッチオーバーが完了したことを確認できます。

+
次の例では ' ネゴシエート・スイッチオーバーがリモート・クラスタ（ "cluster_a" ）上で実行されますこれにより ' ローカルクラスタ ("`cluster_B`") が停止し ' 更新できるようになります

+
[listing]
----
cluster_A::> metrocluster switchover

Warning: negotiated switchover is about to start. It will stop all the data
         Vservers on cluster "cluster_B" and
         automatically re-start them on cluster
         "cluster_A". It will finally gracefully shutdown
         cluster "cluster_B".
Do you want to continue? {y|n}: y
----
. すべてのクラスタSVMが健全な状態であることを確認します。 `metrocluster vserver show`
. 「Surviving」クラスタ上のデータアグリゲートを再同期します。 `metrocluster heal -phase aggregates`
+
MetroCluster IP 構成を ONTAP 9.5 以降にアップグレードすると、アグリゲートの状態は短時間 degraded になったあとに再同期されて mirrored に戻ります。

+
[listing]
----
cluster_A::> metrocluster heal -phase aggregates
[Job 130] Job succeeded: Heal Aggregates is successful.
----
. 修復処理が正常に完了したことを確認します。 `metrocluster operation show`
+
[listing]
----
cluster_A::> metrocluster operation show
Operation: heal-aggregates
State: successful
Start Time: MM/DD/YYYY TIME
End Time: MM/DD/YYYY TIME
Errors: -
----
. 「Surviving」クラスタのルートアグリゲートを再同期します。 `metrocluster heal -phase root-aggregates`
+
[listing]
----
cluster_A::> metrocluster heal -phase root-aggregates
[Job 131] Job succeeded: Heal Root Aggregates is successful.
----
. 修復処理が正常に完了したことを確認します。 `metrocluster operation show`
+
[listing]
----
cluster_A::> metrocluster operation show
Operation: heal-root-aggregates
State: successful
Start Time: MM/DD/YYYY TIME
End Time: MM/DD/YYYY TIME
Errors: -
----
. 停止したクラスタで、LOADERプロンプトからノードをブートします。 `boot_ontap`
. ブートプロセスの終了を待ってから、すべてのクラスタSVMが健全な状態であることを確認します。 `metrocluster vserver show`
. 「Surviving」クラスタからスイッチバックを実行します。 `metrocluster switchback`
. スイッチバックが正常に完了したことを確認します。 `metrocluster operation show`
+
[listing]
----
cluster_A::> metrocluster operation show
Operation: switchback
State: successful
Start Time: MM/DD/YYYY TIME
End Time: MM/DD/YYYY TIME
Errors: -
----
. すべてのクラスタSVMが健全な状態であることを確認します。 `metrocluster vserver show`
. もう一方のクラスタで、ここまでのすべての手順を繰り返します。
. MetroCluster 構成が正常であることを確認します。
+
.. 構成を確認します。 `metrocluster check run`
+
[listing]
----
cluster_A::> metrocluster check run
Last Checked On: MM/DD/YYYY TIME
Component           Result
------------------- ---------
nodes               ok
lifs                ok
config-replication  ok
aggregates          ok
4 entries were displayed.

Command completed. Use the "metrocluster check show -instance"
command or sub-commands in "metrocluster check" directory for
detailed results.
To check if the nodes are ready to do a switchover or switchback
operation, run "metrocluster switchover -simulate" or "metrocluster
switchback -simulate", respectively.
----
.. より詳細な結果を表示するには、MetroCluster check runコマンドを使用します。
.. 権限レベルを advanced に設定します。 `set -privilege advanced`
.. スイッチオーバー処理をシミュレートします。 `metrocluster switchover -simulate`
.. スイッチオーバーのシミュレーション結果を確認します。 `metrocluster operation show`
+
[listing]
----
cluster_A::*> metrocluster operation show
    Operation: switchover
        State: successful
   Start time: MM/DD/YYYY TIME
     End time: MM/DD/YYYY TIME
       Errors: -
----
.. admin 権限レベルに戻ります。 `set -privilege admin`
.. もう一方のクラスタで上記の手順を繰り返します。




アップグレード後の手順をすべて実行してください。

.関連情報
link:https://docs.netapp.com/us-en/ontap-metrocluster/disaster-recovery/concept_dr_workflow.html["MetroCluster によるディザスタリカバリ"]
