---
permalink: upgrade/task_reviewing_pre_update_resources.html 
sidebar: sidebar 
keywords: ontap, upgrade, resources, review, before 
summary: ONTAP ソフトウェアを更新する前に、解決すべき問題やターゲットリリースでの新しいシステム動作について理解し、ハードウェアのサポートを確認するには、リソースを確認する必要があります。 
---
= アップグレード前にお読みください
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
を使用しない場合は link:https://aiq.netapp.com/["Active IQ"^] Upgrade Advisor では、 ONTAP ソフトウェアをアップグレードする前に、ネットアップのリソースをいくつか確認する必要があります。これらのリソースは、解決すべき問題やターゲットリリースでの新しいシステム動作について理解し、ハードウェアのサポートを確認するのに役立ちます。

. ターゲットリリースの _Release Notes_ を確認します。
+
https://library.netapp.com/ecm/ecm_download_file/ECMLP2492508["ONTAP 9 リリースノート"]

+
「重要な注意事項」セクションでは、新しいリリースにアップグレードする前に注意すべき潜在的な問題について説明します。「新機能と変更された機能」および「既知の問題と制限」セクションでは、新しいリリースへのアップグレード後の新しいシステム動作について説明します。

. 使用しているハードウェアプラットフォームとクラスタおよび管理スイッチがターゲットリリースでサポートされていることを確認します。
+
一時的な状態でアップグレードできますが、最終的には NX-OS （クラスタネットワークスイッチ）、 IOS （管理ネットワークスイッチ）、および RCF ソフトウェアのバージョンがアップグレード先の ONTAP のバージョンに対応している必要があります。

+
https://hwu.netapp.com["NetApp Hardware Universe の略"^]

. 使用しているMetroCluster IPスイッチがターゲットリリースでサポートされていることを確認します。
+
https://mysupport.netapp.com/matrix["NetApp Interoperability Matrix Tool で確認できます"^]

. ターゲットの ONTAP リリースに対応したバージョン以上のソフトウェアがクラスタスイッチと管理スイッチにない場合は、サポートされているソフトウェアバージョンにアップグレードしてください。
+
** https://mysupport.netapp.com/site/info/broadcom-cluster-switch["ネットアップのダウンロード：Broadcomクラスタスイッチ"^]
** https://mysupport.netapp.com/site/info/cisco-ethernet-switch["ネットアップのダウンロード：Ciscoイーサネットスイッチ"^]
** https://mysupport.netapp.com/site/info/netapp-cluster-switch["ネットアップのダウンロード：ネットアップクラスタスイッチ"^]


. クラスタが SAN 用に構成されている場合は、 SAN 構成が完全にサポートされていることを確認します。
+
ターゲットの ONTAP ソフトウェアバージョン、ホスト OS およびパッチ、必須の Host Utilities ソフトウェア、マルチパスソフトウェア、アダプタドライバおよびファームウェアなど、すべての SAN コンポーネントがサポートされている必要があります。

+
https://mysupport.netapp.com/matrix["NetApp Interoperability Matrix Tool で確認できます"^]

. 7-Mode Transition Tool を使用して 7-Mode から移行する場合は、ツールがアップグレード先の ONTAP バージョンへの移行をサポートしていることを確認してください。
+
アップグレード先の ONTAP バージョンをサポートする 7-Mode Transition Tool をアップグレードする前に、ツール内のすべてのプロジェクトが完了または中止状態である必要があります。

+
link:https://docs.netapp.com/us-en/ontap-7mode-transition/install-admin/index.html["7-Mode Transition Tool のインストールと管理"]


