---
permalink: upgrade/task_enabling_and_reverting_lifs_to_home_ports_preparing_the_ontap_software_for_the_update.html 
sidebar: sidebar 
keywords: ontap, upgrade, enabling, enable, revert, reverting, lifs, home, ports, 
summary: リブートを実行すると、一部の LIF が割り当てられているフェイルオーバーポートに移行されることがあります。クラスタのアップグレードの前後に、ホームポートにない LIF を有効にしてリバートする必要があります。 
---
= アップグレード前に、すべての LIF がホームポートにあることを確認してください
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
リブートを実行すると、一部の LIF が割り当てられているフェイルオーバーポートに移行されることがあります。クラスタのアップグレードの前後に、ホームポートにない LIF を有効にしてリバートする必要があります。

ホームポートが動作している場合は、 network interface revert コマンドによって、現在ホームポートにない LIF がホームポートにリバートされます。LIF のホームポートは LIF の作成時に指定します。指定されているホームポートは、 network interface show コマンドを使用して確認できます。

. すべての LIF のステータスを表示します。「 network interface show 」
+
Storage Virtual Machine （ SVM ）のすべての LIF のステータスを表示する例を次に示します。

+
[listing]
----
cluster1::> network interface show -vserver vs0
            Logical    Status     Network            Current       Current Is
Vserver     Interface  Admin/Oper Address/Mask       Node          Port    Home
----------- ---------- ---------- ------------------ ------------- ------- ----
vs0
            data001    down/down  192.0.2.120/24     node0         e0e     true
            data002    down/down  192.0.2.121/24     node0         e0f     true
            data003    down/down  192.0.2.122/24     node0         e2a     true
            data004    down/down  192.0.2.123/24     node0         e2b     true
            data005    down/down  192.0.2.124/24     node0         e0e     false
            data006    down/down  192.0.2.125/24     node0         e0f     false
            data007    down/down  192.0.2.126/24     node0         e2a     false
            data008    down/down  192.0.2.127/24     node0         e2b     false
8 entries were displayed.
----
+
Status Admin ステータスが down になっている LIF や Is home ステータスが false になっている LIF がある場合は次の手順に進みます。

. データ LIF を有効にします。「 network interface modify ｛ -role data ｝ -status-admin up
+
[listing]
----
cluster1::> network interface modify {-role data} -status-admin up
8 entries were modified.
----
. LIF をそれぞれのホームポートにリバートします。「 network interface revert *
+
このコマンドを実行すると、すべての LIF がそれぞれのホームポートにリバートされます。

+
[listing]
----
cluster1::> network interface revert *
8 entries were acted on.
----
. すべての LIF がそれぞれのホームポートにあることを確認します。「 network interface show 」
+
次の例では、 SVM vs0 のすべての LIF がそれぞれのホームポートにあります。

+
[listing]
----
cluster1::> network interface show -vserver vs0
            Logical    Status     Network            Current       Current Is
Vserver     Interface  Admin/Oper Address/Mask       Node          Port    Home
----------- ---------- ---------- ------------------ ------------- ------- ----
vs0
            data001      up/up    192.0.2.120/24     node0         e0e     true
            data002      up/up    192.0.2.121/24     node0         e0f     true
            data003      up/up    192.0.2.122/24     node0         e2a     true
            data004      up/up    192.0.2.123/24     node0         e2b     true
            data005      up/up    192.0.2.124/24     node1         e0e     true
            data006      up/up    192.0.2.125/24     node1         e0f     true
            data007      up/up    192.0.2.126/24     node1         e2a     true
            data008      up/up    192.0.2.127/24     node1         e2b     true
8 entries were displayed.
----

