---
permalink: upgrade/task_verifying_the_lif_failover_configuration.html 
sidebar: sidebar 
keywords: ontap, upgrade, verifying, verify, lif, failover, configuration 
summary: アップグレードを実行する前に、フェイルオーバーポリシーとフェイルオーバーグループが正しく設定されていることを確認してください。 
---
= LIFフェイルオーバーの設定を確認する
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
ONTAPをアップグレードする前に、クラスタのフェイルオーバーポリシーとフェイルオーバーグループが正しく設定されていることを確認する必要があります。

アップグレードプロセスでは、LIFはアップグレード方式に基づいて移行されます。アップグレード方法に応じて、LIFフェイルオーバーポリシーが使用される場合と使用されない場合があります。

クラスタにノードが8つ以上ある場合は、バッチ方式を使用して自動アップグレードが実行されます。バッチアップグレード方式では、クラスタを複数のバッチに分割し、最初のバッチに含まれるノードセットをアップグレードし、そのノードのハイアベイラビリティ（HA）パートナーをアップグレードしてから、残りのバッチについても同じ処理を繰り返します。ONTAP 9 .7以前でバッチ方式が使用される場合、LIFはアップグレードするノードのHAパートナーに移行されます。ONTAP 9 .8以降でバッチ方式が使用される場合は、LIFが他のバッチグループに移行されます。

クラスタのノードが8つ未満の場合は、ローリング方式を使用して自動アップグレードが実行されます。ローリングアップグレード方式では、HAペアの各ノードでフェイルオーバー処理を開始し、フェイルオーバーしたノードを更新してギブバックを開始します。この処理をクラスタ内のHAペアごとに繰り返します。ローリング方式が使用される場合、LIFはLIFフェイルオーバーポリシーの定義に従ってフェイルオーバーターゲットノードに移行されます。

.手順
. 各データLIFのフェイルオーバーポリシーを表示します。
+
[cols="2*"]
|===
| ONTAPのバージョン | 使用するコマンド 


| 9.6以降  a| 
`network interface show -service-policy \*data* -failover`



| 9.5以前  a| 
`network interface show -role data -failover`

|===
+
次の例は、2つのデータLIFを含む2ノードクラスタのデフォルトのフェイルオーバー設定を示しています。

+
[listing]
----
cluster1::> network interface show -role data -failover
         Logical         Home                  Failover        Failover
Vserver  Interface       Node:Port             Policy          Group
-------- --------------- --------------------- --------------- ---------------
vs0
         lif0            node0:e0b             nextavail       system-defined
                         Failover Targets: node0:e0b, node0:e0c,
                                           node0:e0d, node0:e0e,
                                           node0:e0f, node1:e0b,
                                           node1:e0c, node1:e0d,
                                           node1:e0e, node1:e0f
vs1
         lif1            node1:e0b             nextavail       system-defined
                         Failover Targets: node1:e0b, node1:e0c,
                                           node1:e0d, node1:e0e,
                                           node1:e0f, node0:e0b,
                                           node0:e0c, node0:e0d,
                                           node0:e0e, node0:e0f
----
+
「 * Failover Targets * 」フィールドには、各 LIF のフェイルオーバーターゲットが優先順位の高いものから順番に表示されます。たとえば、「lif0」がホームポート（node0のe0b）からフェイルオーバーすると、node0のポートe0cへのフェイルオーバーが最初に試行されます。lif0がe0cにフェイルオーバーできない場合は、node0のポートe0dなどへのフェイルオーバーが試行されます。

. SAN LIF以外のLIFでフェイルオーバーポリシーが* disabled *に設定されている場合は、コマンドを使用して `network interface modify`フェイルオーバーを有効にします。
. それぞれの LIF について、 LIF のホームノードのアップグレード時に稼働したままにする別のノードのデータポートが「 * Failover Targets * 」フィールドに含まれていることを確認します。
+
フェイルオーバーグループにフェイルオーバーターゲットを追加するには、コマンドを使用し `network interface failover-groups modify`ます。

+
.例
[listing]
----
network interface failover-groups modify -vserver vs0 -failover-group fg1 -targets sti8-vsim-ucs572q:e0d,sti8-vsim-ucs572r:e0d
----


.関連情報
link:../networking/networking_reference.html["ネットワークおよびLIFの管理"]
