---
permalink: upgrade/task_preparing_to_upgrade_nodes_using_netapp_storage_encryption_with_external_key_management_servers.html 
sidebar: sidebar 
keywords: ontap, upgrade, prepare, preparing, nodes, netapp, storage, encryption, nse, external, key management, servers 
summary: ONTAP 9.2 以前で NetApp Storage Encryption \ （ NSE\ ）を使用しており、 ONTAP 9.3 以降にアップグレードする場合は、アップグレードを実行する前に、コマンドラインインターフェイス \ （ CLI\ ）を使用して既存の外部キー管理 \ （ kmip\ ）サーバ接続を削除する必要があります。 
---
= アップグレードの前に、既存の外部キー管理サーバ接続を削除します
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
ONTAP 9.2 以前のバージョンで NetApp Storage Encryption （ NSE ）を使用しており、 ONTAP 9.3 以降にアップグレードする場合は、アップグレードを実行する前にコマンドラインインターフェイス（ CLI ）を使用して既存の外部キー管理（ KMIP ）サーバの接続を削除する必要があります。

. NSE ドライブがロック解除されて開いていること、デフォルトのメーカーセキュア ID である「 0x0 」に設定されていることを確認します。
+
storage encryption disk show -disk *

. advanced 権限モードに切り替えます。
+
「 advanced 」の権限が必要です

. デフォルトのメーカーセキュア ID 「 0x0 」を使用して、 FIPS キーを自己暗号化ディスク（ SED ）に割り当てます。「 storage encryption disk modify -fips-key-id 0x0 -disk * 」
. すべてのディスクへの FIPS キーの割り当てが完了したことを確認します。「 storage encryption disk show -status 」
. すべてのディスクの「 mode 」が「 data 」に設定されていることを確認します。「 storage encryption disk show 」
. 設定された KMIP サーバを表示します。「 securitykey-manager show
. 設定されている KMIP サーバを削除します。「 securitykey-manager delete -address kmip_address 」
. 外部キー管理ツールの構成を削除します： 'securitykey-manager delete -kmip-config
+

NOTE: この手順で NSE 証明書が削除されることはありません。



アップグレードの完了後に、 KMIP サーバの接続を再設定する必要があります。

xref:task_reconfiguring_kmip_servers_connections_after_upgrading_to_ontap_9_3_or_later.adoc[ONTAP 9.3 以降へのアップグレード後に行う KMIP サーバ接続の再設定]
