---
permalink: upgrade/task_updating_an_ontap_cluster_disruptively.html 
sidebar: sidebar 
keywords: ontap, upgrade, disruptively 
summary: 新しいONTAPリリースにアップグレードする際にクラスタをオフラインにしてもかまわない場合は、停止を伴うアップグレード方式を使用できます。 
---
= CLIを使用した停止を伴うONTAP手動アップグレード
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
新しいONTAPリリースにアップグレードする際にクラスタをオフラインにしてもかまわない場合は、停止を伴うアップグレード方式を使用できます。この方式では、各HAペアのストレージ フェイルオーバーを無効にして、クラスタ内の各ノードをリブートし、完了したらストレージ フェイルオーバーを再度有効にします。

* link:download-software-image.html["ダウンロード"]してlink:install-software-manual-upgrade.html["インストール"]する必要があります。
* SAN環境を使用している場合は、すべてのSANクライアントをシャットダウンするか、アップグレードが完了するまで一時停止する必要があります。
+
停止を伴うアップグレードの前にSANクライアントをシャットダウンまたは一時停止しないと、クライアント ファイルシステムやアプリケーションでエラーが発生し、アップグレードの完了後に手動でのリカバリが必要になる可能性があります。



停止を伴うアップグレードでは、各HAペアのストレージ フェイルオーバーを無効にして各ノードを更新するため、ダウンタイムが必要です。ストレージ フェイルオーバーを無効にすると、各ノードはシングルノード クラスタとして動作します。したがって、そのノードに関連するシステム サービスは、システムをリブートするまで中断されます。

.手順
. 権限レベルを admin から advanced に設定し、続行するかどうかを尋ねられたら *y* と入力します：
+
[source, cli]
----
set -privilege advanced
----
+
詳細プロンプト（(`*>`）が表示されます。

. 新しいONTAPソフトウェア イメージをデフォルトのイメージとして設定します。
+
[source, cli]
----
system image modify {-node * -iscurrent false} -isdefault true
----
+
このコマンドは、拡張クエリを使用して、代替イメージとしてインストールされるターゲットのONTAPソフトウェア イメージが各ノードのデフォルトのイメージになるように変更します。

. 新しいONTAPソフトウェア イメージがデフォルトのイメージとして設定されたことを確認します。
+
[source, cli]
----
system image show
----
+
次の例では、image2が新しいONTAPバージョンで、両方のノードでデフォルトのイメージとして設定されています。

+
[listing]
----
cluster1::*> system image show
                 Is      Is                Install
Node     Image   Default Current Version    Date
-------- ------- ------- ------- --------- -------------------
node0
         image1  false   true    X.X.X     MM/DD/YYYY TIME
         image2  true    false   Y.Y.Y     MM/DD/YYYY TIME
node1
         image1  false   true    X.X.X     MM/DD/YYYY TIME
         image2  true    false   Y.Y.Y     MM/DD/YYYY TIME
4 entries were displayed.
----
. 次のいずれかの手順を実行します。
+
[cols="2*"]
|===
| クラスタが次で構成されている場合： | 操作 


 a| 
1ノード
 a| 
次の手順に進みます。



 a| 
2ノード
 a| 
.. クラスタ ハイアベイラビリティを無効にします。
+
[source, cli]
----
cluster ha modify -configured false
----
+
プロンプトが表示されたら `y`を押して続行します。

.. HAペアのストレージ フェイルオーバーを無効にします。
+
[source, cli]
----
storage failover modify -node * -enabled false
----




 a| 
3ノード以上
 a| 
クラスタの各HAペアのストレージ フェイルオーバーを無効にします。

[source, cli]
----
storage failover modify -node * -enabled false
----
|===
. クラスタ内のノードをリブートします。
+
[source, cli]
----
system node reboot -node nodename -ignore-quorum-warnings
----
+

IMPORTANT: 複数のノードを一度にリブートしないでください。

+
ノードが新しいONTAPイメージでブートします。ONTAPログイン プロンプトが表示され、リブート プロセスが完了したことが示されます。

. ノードまたはノード セットが新しいONTAPイメージでリブートされたら、権限レベルをadvancedに設定します。
+
[source, cli]
----
set -privilege advanced
----
+
続行するかどうかを確認するメッセージが表示されたら、*y*を入力します

. 新しいソフトウェアが実行されていることを確認します。
+
[source, cli]
----
system node image show
----
+
次の例では、image1が新しいONTAPバージョンで、node0で現在のバージョンとして設定されています。

+
[listing]
----
cluster1::*> system node image show
                 Is      Is                 Install
Node     Image   Default Current Version    Date
-------- ------- ------- ------- --------   -------------------
node0
         image1  true    true    X.X.X       MM/DD/YYYY TIME
         image2  false   false   Y.Y.Y      MM/DD/YYYY TIME
node1
         image1  true    false   X.X.X      MM/DD/YYYY TIME
         image2  false   true    Y.Y.Y      MM/DD/YYYY TIME
4 entries were displayed.
----
. アップグレードが正常に完了したことを確認します。
+
.. 権限レベルをadvancedに設定します。
+
[source, cli]
----
set -privilege advanced
----
.. 各ノードのアップグレード ステータスが完了になっていることを確認します。
+
[source, cli]
----
system node upgrade-revert show -node nodename
----
+
ステータスがcompleteと表示される必要があります。

+
ステータスが完了していない場合は、link:http://mysupport.netapp.com/["NetAppサポートに問い合わせる"^]直ちに実行してください。

.. admin権限レベルに戻ります。
+
[source, cli]
----
set -privilege admin
----


. 追加するノードごとに、手順5～8を繰り返します。
. クラスタが2つ以上のノードで構成されている場合は、クラスタ内の各HAペアのストレージ フェイルオーバーを有効にします。
+
[source, cli]
----
storage failover modify -node * -enabled true
----
. クラスタが2つのノードだけで構成されている場合は、クラスタ ハイアベイラビリティを有効にします。
+
[source, cli]
----
cluster ha modify -configured true
----


.関連情報
* link:https://docs.netapp.com/us-en/ontap-cli/storage-failover-modify.html["storage failover modify"^]

