---
permalink: upgrade/task_setting_the_desired_nt_acl_permissions_display_level_for_nfs_clients.html 
sidebar: sidebar 
keywords: ontap, upgrade, setting, set, desired, nt, acl, permissions, display, level, nfs, clients 
summary: ONTAP 8.3.0 からアップグレードしたあとの、 NFS クライアントに対する NT ACL 権限のデフォルトの表示処理が変わりました。設定を確認し、必要に応じて環境に適した設定に変更する必要があります。ONTAP 8.3.1 以降からアップグレードする場合は、この作業は必要ありません。 
---
= NFS クライアントの NT ACL 権限の表示レベルの設定
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
ONTAP 8.3.0 からアップグレードしたあとの、 NFS クライアントに対する NT ACL 権限のデフォルトの表示処理が変わりました。設定を確認し、必要に応じて環境に適した設定に変更する必要があります。ONTAP 8.3.1 以降からアップグレードする場合は、この作業は必要ありません。

マルチプロトコル環境の ONTAP では、 NT ACL によってすべてのユーザに付与されるアクセス権に基づいて、 NTFS セキュリティ形式のファイルおよびディレクトリの権限が NFS クライアントに表示されます。ONTAP 8.3.0 では、 ONTAP クライアントに表示される権限が、 NT ACL によって付与される最大アクセス権に基づいていました。アップグレード後は、 NT ACL によって付与される最小アクセス権に基づいて権限が表示されるようにデフォルト設定が変更されます。環境の新規および既存の Storage Virtual Machine （ SVM ）が変更されます。

. 権限レベルを advanced に設定します。 `set -privilege advanced`
. NFSクライアントのNT ACL権限を表示するための設定を確認します。 `vserver nfs show -vserver vserver_name -fields ntacl-display-permissive-perms`
+
ONTAP 8.3.0 からのアップグレード後は、この新しいパラメータの値が無効になるため、 ONTAP には最小限の権限が表示されます。

. 最大権限を表示する場合は、必要に応じて各SVMの設定を個別に変更します。 `vserver nfs modify -vserver vserver_name -ntacl-display-permissive-perms enabled`
. 変更が有効になったことを確認します。 `vserver nfs show -vserver vserver_name -fields ntacl-display-permissive-perms`
. admin 権限レベルに戻ります。 `set -privilege admin`

