---
permalink: upgrade/when-to-upgrade.html 
sidebar: sidebar 
keywords: upgrade, ontap, when to upgrade, major upgrade, feature upgrade, minor upgrade, patch release, patch upgrade, service upgrade, service update, critical, patch, release dates, support levels, full support, limited, support, self-service support 
summary: ONTAPを定期的にアップグレードします。アップグレードすると、新しい機能や拡張された機能を利用して、既知の問題に対する最新の修正を実装できます。 
---
= ONTAPはいつアップグレードすればよいですか。
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
ONTAPソフトウェアは定期的にアップグレードする必要があります。ONTAPをアップグレードすると、新しい機能や拡張された機能を利用して、既知の問題に対する最新の修正を実装できます。



== ONTAPのメジャーアップグレード

ONTAPのメジャーアップグレードまたは機能リリースには通常、次のものが含まれます。

* ONTAPの新機能
* 主なインフラの変更（NetApp WAFLの運用やRAIDの運用の基本的な変更など）
* NetAppが開発した新しいハードウェアシステムのサポート
* 新しいネットワークインターフェイスカードやホストバスアダプタなどの交換ハードウェアコンポーネントのサポート


新しいONTAPリリースには、3年間のフルサポートが適用されます。NetAppでは、一般提供（GA）後1年間最新リリースを実行し、フルサポート期間内の残りの時間を使用して新しいONTAPリリースへの移行を計画することを推奨しています。



== ONTAPパッチアップグレード

パッチアップグレードでは、重大なバグをタイムリーに修正できます。ONTAPの次のメジャーフィーチャーリリースまで待つことはできません。重要でないパッチのアップグレードは、3~6カ月ごとに適用する必要があります。重要なパッチのアップグレードは、できるだけ早く適用する必要があります。

ONTAPリリースの詳細については、を参照してlink:https://kb.netapp.com/Support_Bulletins/Customer_Bulletins/SU2["推奨される最小パッチレベル"^]ください。



== ONTAPのリリース日

ONTAP 9 .8リリース以降、NetAppではONTAPリリースを暦年に2回提供しています。計画は変更される可能性がありますが、新しいONTAPリリースは暦年の第2四半期と第4四半期に提供する予定です。この情報は、最新のONTAPリリースを利用するためのアップグレード期間を計画する際に使用します。

[cols="50,50"]
|===
| バージョン | リリース日 


 a| 
9.16.1
 a| 
2024年11月



 a| 
9.15.1
 a| 
2024年5月



 a| 
9.14.1
 a| 
2024年1月



 a| 
9.13.1
 a| 
2023年6月



 a| 
9.12.1
 a| 
2023年2月



 a| 
9.11.1
 a| 
2022年7月



 a| 
9.10.1
 a| 
2022年1月



 a| 
9.9.1
 a| 
2021年6月



 a| 

NOTE: ONTAP 9.10.1より前のバージョンを実行している場合は、限定サポートまたはセルフサービスサポートを利用している可能性があります。フルサポートのバージョンへのアップグレードを検討してください。使用しているONTAPのバージョンのサポートレベルは、で確認できます https://mysupport.netapp.com/site/info/version-support#ontap_svst["NetAppサポートサイト"^]。

|===


== ONTAPのサポートレベル

特定のバージョンのONTAPで利用できるサポートのレベルは、ソフトウェアのリリース時期によって異なります。

[cols="20,10,10,10,10,10,10,10,10"]
|===
| サポートレベル 3+| フルサポート 2+| 限定サポート 3+| セルフサービスサポート 


 a| 
年
 a| 
1
 a| 
2
 a| 
3
 a| 
4
 a| 
5
 a| 
6
 a| 
7
 a| 
8



 a| 
オンライン ドキュメントへのアクセス
 a| 
〇
 a| 
〇
 a| 
〇
 a| 
〇
 a| 
〇
 a| 
〇
 a| 
〇
 a| 
〇



 a| 
テクニカル サポート
 a| 
〇
 a| 
〇
 a| 
〇
 a| 
〇
 a| 
〇
 a| 
 a| 
 a| 



 a| 
根本原因の分析
 a| 
〇
 a| 
〇
 a| 
〇
 a| 
〇
 a| 
〇
 a| 
 a| 
 a| 



 a| 
ソフトウェアのダウンロード
 a| 
〇
 a| 
〇
 a| 
〇
 a| 
〇
 a| 
〇
 a| 
 a| 
 a| 



 a| 
サービスアップデート（パッチリリース[P-releases]）
 a| 
〇
 a| 
〇
 a| 
〇
 a| 
 a| 
 a| 
 a| 
 a| 



 a| 
脆弱性に関するアラート
 a| 
〇
 a| 
〇
 a| 
〇
 a| 
 a| 
 a| 
 a| 
 a| 

|===
.関連情報
* 学びlink:../release-notes/index.html["現在サポートされているONTAPリリースの新機能"^]、
* 詳細については、をご覧ください link:https://kb.netapp.com/Support_Bulletins/Customer_Bulletins/SU2["推奨される最小ONTAPリリース"^]。
* 詳細については、をご覧ください link:https://mysupport.netapp.com/site/info/version-support["ONTAPソフトウェアバージョンのサポート"^]。
* の詳細については、をlink:https://mysupport.netapp.com/site/info/ontap-release-model["ONTAPリリースモデル"^]参照してください。

