---
permalink: zero-trust/zero-trust-overview.html 
sidebar: sidebar 
keywords: tr-4829, zero trust, netapp, ontap, architect, data centric, fpolicy 
summary: ゼロトラストは従来、マイクロコアと境界（MCAP）を構築してデータ、サービス、アプリケーション、資産を保護するネットワーク中心のアプローチであり、セグメンテーションゲートウェイと呼ばれる制御機能を備えていました。 
---
= NetAppとゼロトラスト
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
ゼロトラストは、従来、マイクロコアと境界（MCAP）を構築してデータ、サービス、アプリケーション、資産を保護するネットワーク中心のアプローチであり、セグメンテーションゲートウェイと呼ばれる制御機能を備えていました。NetApp ONTAPは、ゼロトラストに対してデータ主体のアプローチを採用しています。このアプローチでは、ストレージ管理システムが、お客様のデータへのアクセスを保護および監視するためのセグメンテーションゲートウェイになります。特に、FPolicyゼロトラストエンジンとFPolicyパートナーエコシステムは、正常なデータアクセスパターンと異常なデータアクセスパターンを詳細に把握し、内部の脅威を特定するためのコントロールセンターとなります。


NOTE: 2024年7月より、以前にPDFとして公開されていたテクニカルレポート_TR-4829：『NetApp and Zero Trust：Enabling a data-centric Zero Trust model_』のコンテンツが、ONTAPのその他の製品ドキュメントに統合されました。

データは組織が所有する最も重要な資産です。2022年の調査によると、内部の脅威はデータ漏えいの18%の原因です https://enterprise.verizon.com/resources/reports/dbir/["Verizon Data Breach Investigationsレポート"^]。NetApp ONTAPデータ管理ソフトウェアを使用して、業界をリードするゼロトラストコントロールをデータに導入することで、組織は警戒を強化できます。



== ゼロトラストとは

ゼロトラストモデルは、Forrester Researchの[John Kindervag^]によって最初に開発されました。外部からではなく内部からのネットワークセキュリティを想定しています。 Inside-Out Zero Trustアプローチは、マイクロコアと境界（MCAP）を特定します。MCAPは、包括的な制御セットで保護するデータ、サービス、アプリケーション、資産の内部定義です。安全な外部境界の概念は廃止されています。信頼され、境界を介して正常に認証されることが許可されているエンティティは、組織を攻撃に対して脆弱にする可能性があります。内部関係者は、定義上、すでに安全な境界内にいます。従業員、請負業者、およびパートナーは内部関係者であり、組織のインフラストラクチャ内で役割を実行するための適切な制御で運用できるようにする必要があります。

ゼロトラストは、2019年9月に国防総省に約束する技術として言及されました https://media.defense.gov/2019/Jul/12/2002156622/-1/-1/1/DOD-DIGITAL-MODERNIZATION-STRATEGY-2019.PDF["FY19-23 DoDのデジタル最新化戦略"^]。Zero Trustは、「データ漏えいを阻止するためにアーキテクチャ全体にセキュリティを組み込むサイバーセキュリティ戦略です。このデータ中心のセキュリティモデルは、信頼できるネットワーク、デバイス、ペルソナ、またはプロセスという概念を排除し、最小特権アクセスの概念の下で認証および承認ポリシーを可能にするマルチ属性ベースの信頼レベルに移行します。ゼロトラストを実装するには、既存のインフラストラクチャを使用して、よりシンプルで効率的な方法でセキュリティを実装する方法を再考する必要があります。

2020年8月、NISTは(ZTA)を発表しまし https://csrc.nist.gov/publications/detail/sp/800-207/final["Special Pub 800-207ゼロトラストアーキテクチャ"^] た。ZTAは、ネットワークセグメントではなくリソースの保護に重点を置いています。これは、ネットワークの場所がリソースのセキュリティ体制の主要なコンポーネントではなくなったためです。リソースとはデータとコンピューティングです。ZTA戦略は、エンタープライズネットワークアーキテクト向けです。ZTAでは、元のForresterの概念から新しい用語がいくつか導入されています。ポリシー決定ポイント（PDP）およびポリシー施行ポイント（PEP）と呼ばれる保護メカニズムは、Forresterセグメンテーションゲートウェイに似ています。ZTAでは、次の4つの導入モデルを導入

* デバイスエージェントまたはゲートウェイベースの展開
* Enclaveベースの導入（Forrester MCAPに似ています）
* リソースポータルベースの導入
* デバイスアプリケーションのサンドボックス化


このドキュメントの目的のために、NIST ZTAではなくForrester Researchの概念と用語を使用しています。



== セキュリティリソース

脆弱性とインシデントの報告、NetAppのセキュリティ対応、および顧客の機密性の詳細については、を参照してください https://www.netapp.com/company/trust-center/security/["NetAppセキュリティポータル"^]。
