---
permalink: zero-trust/zero-trust-automation-orchestration.html 
sidebar: sidebar 
keywords: tr-4829, zero trust, ontap, netapp, security, automation, orchestration, control, ansible 
summary: 自動化により、組織はゼロトラストの導入を手動の手順にとどまらず拡張して、自動化された不正なアクティビティから防御できます。 
---
= ONTAPの外部にあるNetAppセキュリティの自動化とオーケストレーションの制御
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
自動化を使用すると、最小限の人間の支援でプロセスや手順を実行できます。自動化により、組織はゼロトラスト環境を手動の手順をはるかに超えて拡張し、自動化された不正なアクティビティから保護できます。

Ansibleは、オープンソースのソフトウェアプロビジョニング、構成管理、アプリケーション導入ツールです。多くのUnixライクなシステムで動作し、Microsoft Windowsと同様にUnixライクなシステムの両方を構成することができる。システム構成を記述するための独自の宣言言語が含まれています。AnsibleはMichael DeHaanによって書かれ、2015年にRed Hatに買収された。Ansibleはエージェントレスで、SSHまたはWindowsリモート管理（リモートPowerShell実行可能）を使用して一時的にリモート接続し、タスクを実行します。NetAppはさらに多くの製品を開発し https://www.netapp.com/us/getting-started-with-netapp-approved-ansible-modules/index.aspx["ONTAPソフトウェア向け150個のAnsibleモジュール"^]、Ansible自動化フレームワークとのさらなる統合を可能にしています。NetApp向けのAnsibleモジュールは、必要な状態を定義してターゲットのNetApp環境にリレーする方法に関する一連の指示を提供します。モジュールは、ライセンスのセットアップ、アグリゲートとStorage Virtual Machineの作成、ボリュームの作成、Snapshotのリストアなどのタスクをサポートするように構築されています。Ansibleのロールは https://github.com/NetApp/ansible/tree/master/nar_ontap_security_ucd_guide["GitHubで公開"^] 、NetApp DoD Unified Capabilities（UC）Deployment Guideに固有のものです。

利用可能なモジュールのライブラリを使用することで、Ansibleプレイブックを簡単に開発し、独自のアプリケーションやビジネスニーズに合わせてカスタマイズして、日常的なタスクを自動化できます。作成したプレイブックを実行して指定したタスクを実行することで、時間を節約し、生産性を向上させることができます。NetAppでは、サンプルのプレイブックを作成して共有しています。プレイブックは直接使用することも、ニーズに合わせてカスタマイズすることもできます。

Cloud Insightsは、インフラ全体を可視化できるインフラ監視ツールです。Cloud Insightsを使用すると、パブリッククラウドインスタンスやプライベートデータセンターを含む、すべてのリソースの監視、トラブルシューティング、最適化を実行できます。Cloud Insightsを使用すると、平均問題解決時間を90%短縮し、クラウドの問題の80%がエンドユーザに影響を及ぼすのを防止できます。また、実用的な情報に基づいてデータを保護することで、クラウドインフラのコストを平均33%削減し、内部の脅威によるリスクを軽減できます。Cloud Insightsのストレージワークロードセキュリティ機能を使用すると、内部の脅威が原因でユーザの異常な行動が発生した場合に、AIやMLを使用したユーザ行動分析でアラートを生成できます。ONTAPの場合、ストレージワークロードセキュリティはゼロトラストFPolicyエンジンを使用します。
