---
permalink: performance-admin/add-alerts-task.html 
sidebar: sidebar 
keywords: add, alerts 
summary: 特定のイベントが生成されたときに通知するようにアラートを設定できます。アラートは、単一のリソース、リソースのグループ、または特定の重大度タイプのイベントについて設定することができます。通知を受け取る頻度を指定したり、アラートにスクリプトを関連付けたりできます。 
---
= ONTAP Active IQ Unified Managerアラートを追加する
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
特定のイベントが生成されたときに通知するようにアラートを設定できます。アラートは、単一のリソース、リソースのグループ、または特定の重大度タイプのイベントについて設定することができます。通知を受け取る頻度を指定したり、アラートにスクリプトを関連付けたりできます。

.開始する前に
* イベント生成時に Active IQ Unified Manager サーバからユーザに通知を送信できるように、通知に使用するユーザの E メールアドレス、 SMTP サーバ、 SNMP トラップホストなどを設定しておく必要があります。
* アラートをトリガーするリソースとイベント、および通知するユーザのユーザ名またはEメールアドレスを確認しておく必要があります。
* イベントに基づいてスクリプトを実行する場合は、[スクリプト]ページを使用してUnified Managerにスクリプトを追加しておく必要があります。
* アプリケーション管理者またはストレージ管理者のロールが必要です。


.タスクの内容
ここで説明するように、[Alert Setup]ページからアラートを作成するだけでなく、イベントを受信したあとに[Event Details]ページから直接アラートを作成することもできます。

.手順
. 左側のナビゲーションペインで、 * Storage Management * > * Alert Setup * をクリックします。
. [* Alert Setup* ] ページで、 [* Add] をクリックします。
. [ * アラートの追加 * ] ダイアログボックスで、 [ * 名前 * ] をクリックし、アラートの名前と概要を入力します。
. [* リソース ] をクリックし、アラートに含めるリソースまたはアラートから除外するリソースを選択します。
+
[ * 次を含む名前（ * Name Contains ） ] フィールドでテキスト文字列を指定してフィルタを設定し、リソースのグループを選択できます。指定したテキスト文字列に基づいて、フィルタルールに一致するリソースのみが使用可能なリソースのリストに表示されます。指定するテキスト文字列では、大文字と小文字が区別されます。

+
あるリソースが対象に含めるルールと除外するルールの両方に該当する場合は、除外するルールが優先され、除外されたリソースに関連するイベントについてはアラートが生成されません。

. [*Events] をクリックし、アラートをトリガーするイベント名またはイベントの重大度タイプに基づいてイベントを選択します。
+
[TIP]
====
複数のイベントを選択するには、Ctrlキーを押しながら選択します。

====
. [*Actions] をクリックし、通知するユーザを選択し、通知頻度を選択し、 SNMP トラップをトラップレシーバに送信するかどうかを選択し、アラートが生成されたときに実行するスクリプトを割り当てます。
+
[NOTE]
====
ユーザに指定したEメールアドレスを変更し、アラートを編集用に再度開くと、変更したEメールアドレスが以前に選択したユーザにマッピングされなくなるため、[Name]フィールドには何も表示されません。また、[ユーザ]ページで選択したユーザのEメールアドレスを変更しても、変更したEメールアドレスは更新されません。

====
+
SNMPトラップを使用してユーザに通知することもできます。

. [ 保存（ Save ） ] をクリックします。


.アラートの追加例
次の例は、次の要件を満たすアラートを作成する方法を示しています。

* アラート名： HealthTest
* リソース：名前に「abc」を含むすべてのボリュームを対象にし、名前に「xyz」を含むすべてのボリュームを除外します。
* イベント：健全性に関するすべての重大イベントを含む
* アクション：「sample@domain.com」、「テスト」スクリプトが含まれており、15分ごとにユーザに通知する必要があります。


[Add Alert]ダイアログボックスで、次の手順を実行します。

. [名前]*をクリックし、*[アラート名]*フィールドにと入力します `HealthTest`。
. [* リソース ] をクリックし、 [ 含める ] タブで、ドロップダウン・リストから [* ボリューム ] を選択します。
+
.. [名前に次の文字を含む]フィールドにと入力し `abc`、名前に「abc」を含むボリュームを表示します。
.. [Available Resources]領域で*+*を選択し<<All Volumes whose name contains 'abc'>>、[Selected Resources]領域に移動します。
.. [除外]*をクリックし、*[名前に次の文字を含む]*フィールドにと入力し `xyz`、*[追加]*をクリックします。


. [* イベント *] をクリックし、 [ イベントの重要度 ] フィールドから [* クリティカル *] を選択します。
. [Matching Events] 領域から [*All Critical Events] を選択し、 [Selected Events] 領域に移動します。
. [Actions]*をクリックし、[Alert These Users]フィールドにと入力します `sample@domain.com`。
. 15 分ごとにユーザに通知するには、「 * 15 分ごとに通知する」を選択します。
+
指定した期間、受信者に繰り返し通知を送信するようにアラートを設定できます。アラートに対してイベント通知をアクティブにする時間を決める必要があります。

. 実行するスクリプトの選択メニューで、 * テスト * スクリプトを選択します。
. [ 保存（ Save ） ] をクリックします。

