---
permalink: performance-admin/check-network-settings-task.html 
sidebar: sidebar 
keywords: check, mtu, network, setting, storage, system 
summary: ストレージシステムのネットワーク設定がクライアントや他のネットワークエンドポイントと同じでない場合は、設定を変更することができます。管理ネットワークの MTU 設定は 1500 に設定されていますが、データネットワークの MTU サイズは 9000 にしてください。 
---
= ストレージシステムの MTU ネットワーク設定を確認
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
ストレージシステムのネットワーク設定がクライアントや他のネットワークエンドポイントと同じでない場合は、設定を変更することができます。管理ネットワークの MTU 設定は 1500 に設定されていますが、データネットワークの MTU サイズは 9000 にしてください。



== このタスクについて

管理トラフィックを処理する e0M ポートを除き、ブロードキャストドメイン内のすべてのポートの MTU サイズが同じです。ポートがブロードキャストドメインの一部である場合は、を使用します `broadcast-domain modify` コマンドを使用して、変更したブロードキャストドメイン内のすべてのポートのMTUを変更します。

NICやデータスイッチなどの中間ネットワークデバイスは、ネットワークエンドポイントよりも大きなMTUサイズに設定できます。詳細については、を参照してください link:../performance-admin/check-network-settings-data-switches-task.html["データスイッチのネットワーク設定を確認します"]。

.手順
. ストレージシステムの MTU ポート設定を確認します。
+
`network port show -instance`

. ポートで使用されているブロードキャストドメインのMTUを変更します。
+
`network port broadcast-domain modify -ipspace _ipspace_ -broadcast-domain _broadcast_domain_ -mtu _new _mtu_`



.例
次の例では、MTUポート設定を9000に変更します。

[listing]
----
network port broadcast-domain modify -ipspace Cluster -broadcast-domain Cluster -mtu 9000
----