---
permalink: performance-admin/download-deploying-unified-manager-task.html 
sidebar: sidebar 
keywords: download, deploy, active iq unified manager 
summary: ソフトウェアをインストールするには、仮想アプライアンス（VA）インストールファイルをダウンロードし、VMware vSphere Clientを使用してVMware ESXiサーバに導入する必要があります。VAはOVAファイルで使用できます。 
---
= ONTAP Active IQ Unified Managerをダウンロードして導入する
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
ソフトウェアをインストールするには、仮想アプライアンス（VA）インストールファイルをダウンロードし、VMware vSphere Clientを使用してVMware ESXiサーバに導入する必要があります。VAはOVAファイルで使用できます。

.手順
. NetApp Support Siteソフトウェアのダウンロード * ページにアクセスし、 Active IQ Unified Manager を探します。
+
https://mysupport.netapp.com/products/index.html[]

. [Select Platform* （プラットフォームの選択） ] ドロップダウンメニューで [* VMware vSphere* （ VMware vSphere * ） ] を選択し、 [* Go!* （実行） ] をクリックします
. 「OVA」ファイルを、VMware vSphere Clientからアクセス可能なローカルまたはネットワーク上の場所に保存します。
. VMware vSphere Client で、 * File * > * Deploy OVF Template * をクリックします。
. 「OVA」ファイルを探し、ウィザードを使用してESXiサーバに仮想アプライアンスを導入します。
+
ウィザードの * Properties * タブを使用して、静的な構成情報を入力できます。

. VMの電源をオンにします。
. 最初の起動プロセスを表示するには、 * Console * タブをクリックします。
. プロンプトに従って、VMにVMware Toolsをインストールします。
. タイムゾーンを設定します。
. メンテナンスユーザの名前とパスワードを入力します。
. VMコンソールに表示されるURLに移動します。

