---
permalink: performance-admin/index.html 
sidebar: sidebar 
keywords: performance, manage, management, monitor, monitoring, issues 
summary: 基本的なパフォーマンスの監視と管理のタスクを設定し、一般的なパフォーマンスの問題を特定して解決することができます。 
---
= パフォーマンスの監視と管理の概要
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
基本的なパフォーマンスの監視と管理のタスクを設定し、一般的なパフォーマンスの問題を特定して解決することができます。

次の想定条件に該当する場合は、以下の手順に従ってクラスタのパフォーマンスを監視および管理してください。

* すべての選択肢について検討するのではなく、ベストプラクティスに従う。
* ONTAP コマンドラインインターフェイスに加え、 Active IQ Unified Manager （旧 OnCommand Unified Manager ）を使用して、システムのステータスとアラートを表示し、クラスタのパフォーマンスを監視し、根本原因分析を実施する。
* ストレージサービス品質（ QoS ）の設定に ONTAP コマンドラインインターフェイスを使用している。
+
QoS は、 System Manager 、 NSLM 、 WFA 、 VSC （ VMware プラグイン）、および API でも設定できます。

* Linux または Windows ベースのインストールではなく、仮想アプライアンスを使用して Unified Manager をインストールする。
* DHCP ではなく静的な設定を使用してソフトウェアをインストールする。
* ONTAP コマンドには、 advanced 権限レベルでアクセスできます。
* 「 admin 」ロールを持つクラスタ管理者である。


.関連情報
上記の想定条件に該当しない場合は、次の資料を参照してください。

* http://docs.netapp.com/ocum-98/topic/com.netapp.doc.onc-um-isg/home.html["Active IQ Unified Manager 9.8 のインストール"]
* link:../system-admin/index.html["システム管理"]

