---
permalink: performance-admin/measure-latency-throughput-nodes-task.html 
sidebar: sidebar 
keywords: check, throughput, latency, between, nodes 
summary: network test-path コマンドを使用して、ネットワークのボトルネックを特定したり、ノード間のネットワークパスのパフォーマンスを事前に確認したりできます。このコマンドは、クラスタ間のノード間でもクラスタ内のノード間でも実行できます。 
---
= ノード間のスループットとレイテンシを確認
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
を使用できます `network test-path` コマンドを使用してネットワークのボトルネックを特定したり、ノード間のネットワークパスを事前に確認したりできます。このコマンドは、クラスタ間のノード間でもクラスタ内のノード間でも実行できます。

.必要なもの
* このタスクを実行するには、クラスタ管理者である必要があります。
* このタスクを実行するには、 advanced 権限レベルのコマンドが必要です。
* クラスタ間のパスの場合、ソースクラスタとデスティネーションクラスタがピアリングされている必要があります。


.このタスクについて
ノード間のネットワークパフォーマンスが、パス構成に対して期待される値にならない場合があります。たとえば、ソースクラスタとデスティネーションクラスタの間のリンクが 10GbE の場合でも、 SnapMirror レプリケーション処理による大量のデータ転送では 1Gbps の伝送速度が観察されることがあります。

を使用できます `network test-path` ノード間のスループットとレイテンシを測定するコマンド。このコマンドは、クラスタ間のノード間でもクラスタ内のノード間でも実行できます。

[NOTE]
====
このテストはネットワークパスが一杯になるまでデータを投入するため、システムがビジーでなく、ノード間のネットワークトラフィックが集中していないときに実行してください。テストは 10 秒後にタイムアウトします。このコマンドは、 ONTAP 9 のノード間でのみ実行できます。

====
。 `session-type` オプションは、ネットワークパスで実行する処理のタイプを指定します。たとえば、リモートデスティネーションへのSnapMirrorレプリケーションの場合は「AsyncMirrorRemote」と指定します。タイプによって、テストで使用されるデータの量が決まります。次の表に、セッションタイプを示します。

|===


| セッションタイプ（ Session Type ） | 説明 


 a| 
AsyncMirrorLocal です
 a| 
SnapMirrorによって同じクラスタ内のノード間で使用される設定



 a| 
AsyncMirrorRemote
 a| 
異なるクラスタのノード間のSnapMirrorで使用される設定（デフォルトタイプ）



 a| 
RemoteDataTransfer
 a| 
ONTAP が同じクラスタ内のノード間のリモートデータアクセスに使用する設定（たとえば、別のノードのボリュームに格納されたファイルを取得するためのノードへのNFS要求）

|===
.手順
. advanced 権限レベルに切り替えます。
+
`set -privilege advanced`

. ノード間のスループットとレイテンシを測定します。
+
`network test-path -source-node _source_nodename_ |local -destination-cluster _destination_clustername_ -destination-node _destination_nodename_ -session-type Default|AsyncMirrorLocal|AsyncMirrorRemote|SyncMirrorRemote|RemoteDataTransfer`

+
ソースノードはローカルクラスタにある必要があります。デスティネーションノードはローカルクラスタまたはピアクラスタに含めることができます。の値は「local」です `-source-node` コマンドを実行するノードを指定します。

+
次のコマンドは、間のSnapMirrorタイプのレプリケーション処理のスループットとレイテンシを測定します `node1` ローカルクラスタおよび `node3` オン `cluster2`：

+
[listing]
----
cluster1::> network test-path -source-node node1 -destination-cluster cluster2 -destination-node node3 -session-type AsyncMirrorRemote
Test Duration:      10.88 secs
Send Throughput:    18.23 MB/sec
Receive Throughput: 18.23 MB/sec
MB sent:            198.31
MB received:        198.31
Avg latency in ms:  2301.47
Min latency in ms:  61.14
Max latency in ms:  3056.86
----
. admin 権限に戻ります。
+
`set -privilege admin`



.完了後
パス構成に対して期待される値を得られない場合は、ノードのパフォーマンス統計の確認、ツールを使用したネットワークの問題の切り分け、スイッチ設定の確認などを行います。
