---
permalink: peering/configure-intercluster-lifs-share-data-ports-task.html 
sidebar: sidebar 
keywords: configure, intercluster, lifs, shared, data, ports 
summary: データネットワークと共有するポートにクラスタ間 LIF を設定できます。これにより、クラスタ間ネットワークに必要なポート数を減らすことができます。 
---
= 共有データポートにクラスタ間 LIF を設定します
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
データネットワークと共有するポートにクラスタ間 LIF を設定できます。これにより、クラスタ間ネットワークに必要なポート数を減らすことができます。

.手順
. クラスタ内のポートの一覧を表示します。
+
`network port show`

+
コマンド構文全体については、マニュアルページを参照してください。

+
次の例は、のネットワークポートを示しています `cluster01`：

+
[listing]
----

cluster01::> network port show
                                                             Speed (Mbps)
Node   Port      IPspace      Broadcast Domain Link   MTU    Admin/Oper
------ --------- ------------ ---------------- ----- ------- ------------
cluster01-01
       e0a       Cluster      Cluster          up     1500   auto/1000
       e0b       Cluster      Cluster          up     1500   auto/1000
       e0c       Default      Default          up     1500   auto/1000
       e0d       Default      Default          up     1500   auto/1000
cluster01-02
       e0a       Cluster      Cluster          up     1500   auto/1000
       e0b       Cluster      Cluster          up     1500   auto/1000
       e0c       Default      Default          up     1500   auto/1000
       e0d       Default      Default          up     1500   auto/1000
----
. システム SVM にクラスタ間 LIF を作成します。
+
|===
| オプション | 説明 


 a| 
* ONTAP 9.6 以降： *
 a| 
`network interface create -vserver _system_SVM_ -lif _LIF_name_ -service-policy default-intercluster -home-node _node_ -home-port port -address _port_IP_ -netmask _netmask_`



 a| 
* ONTAP 9.5 以前： *
 a| 
`network interface create -vserver _system_SVM_ -lif _LIF_name_ -role intercluster -home-node _node_ -home-port _port_ -address _port_IP_ -netmask _netmask_`

|===
+
コマンド構文全体については、マニュアルページを参照してください。

+
次の例は、クラスタ間LIFを作成します `cluster01_icl01` および `cluster01_icl02`：

+
[listing]
----

cluster01::> network interface create -vserver cluster01 -lif cluster01_icl01 -service-
policy default-intercluster -home-node cluster01-01 -home-port e0c -address 192.168.1.201
-netmask 255.255.255.0

cluster01::> network interface create -vserver cluster01 -lif cluster01_icl02 -service-
policy default-intercluster -home-node cluster01-02 -home-port e0c -address 192.168.1.202
-netmask 255.255.255.0
----
. クラスタ間 LIF が作成されたことを確認します。
+
|===
| オプション | 説明 


 a| 
* ONTAP 9.6 以降： *
 a| 
`network interface show -service-policy default-intercluster`



 a| 
* ONTAP 9.5 以前： *
 a| 
`network interface show -role intercluster`

|===
+
コマンド構文全体については、マニュアルページを参照してください。

+
[listing]
----
cluster01::> network interface show -service-policy default-intercluster
            Logical    Status     Network            Current       Current Is
Vserver     Interface  Admin/Oper Address/Mask       Node          Port    Home
----------- ---------- ---------- ------------------ ------------- ------- ----
cluster01
            cluster01_icl01
                       up/up      192.168.1.201/24   cluster01-01  e0c     true
            cluster01_icl02
                       up/up      192.168.1.202/24   cluster01-02  e0c     true
----
. クラスタ間 LIF が冗長構成になっていることを確認します。
+
|===
| オプション | 説明 


 a| 
* ONTAP 9.6 以降： *
 a| 
`network interface show –service-policy default-intercluster -failover`



 a| 
* ONTAP 9.5 以前： *
 a| 
`network interface show -role intercluster -failover`

|===
+
コマンド構文全体については、マニュアルページを参照してください。

+
次の例は、クラスタ間LIFを示しています `cluster01_icl01` および `cluster01_icl02` をクリックします `e0c` ポートはにフェイルオーバーします `e0d` ポート：

+
[listing]
----
cluster01::> network interface show -service-policy default-intercluster –failover
         Logical         Home                  Failover        Failover
Vserver  Interface       Node:Port             Policy          Group
-------- --------------- --------------------- --------------- --------
cluster01
         cluster01_icl01 cluster01-01:e0c   local-only      192.168.1.201/24
                            Failover Targets: cluster01-01:e0c,
                                              cluster01-01:e0d
         cluster01_icl02 cluster01-02:e0c   local-only      192.168.1.201/24
                            Failover Targets: cluster01-02:e0c,
                                              cluster01-02:e0d
----

