---
permalink: peering/enable-cluster-peering-encryption-existing-task.html 
sidebar: sidebar 
keywords: enable, cluster, peering, encryption, existing, peer, relationship 
summary: ONTAP 9.6 以降では、新しく作成されるすべてのクラスタピア関係で、クラスタピアリングの暗号化がデフォルトで有効になります。クラスタピアリングの暗号化では、事前共有キー（ PSK ）と Transport Security Layer （ TLS ）を使用して、クラスタ間ピアリング通信が保護されます。これにより、ピアクラスタ間のセキュリティが強化されます。 
---
= 既存のピア関係でクラスタピアリングの暗号化を有効にします
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
ONTAP 9.6 以降では、新しく作成されるすべてのクラスタピア関係で、クラスタピアリングの暗号化がデフォルトで有効になります。クラスタピアリングの暗号化では、事前共有キー（ PSK ）と Transport Security Layer （ TLS ）を使用して、クラスタ間ピアリング通信が保護されます。これにより、ピアクラスタ間のセキュリティが強化されます。

.このタスクについて
ピアクラスタを ONTAP 9.6 以降にアップグレードする場合、 ONTAP 9.5 以前でピア関係が作成されているときは、アップグレード後にクラスタピアリングの暗号化を手動で有効にする必要があります。クラスタピアリングの暗号化を有効にするには、ピア関係の両方のクラスタで ONTAP 9.6 以降が実行されている必要があります。

.手順
. デスティネーションクラスタで、ソースクラスタとの通信の暗号化を有効にします。
+
`cluster peer modify _source_cluster_ -auth-status-admin use-authentication -encryption-protocol-proposed tls-psk`

. プロンプトが表示されたらパスフレーズを入力します。
. データ保護のソースクラスタで、データ保護のデスティネーションクラスタとの通信の暗号化を有効にします。
+
`cluster peer modify _data_protection_destination_cluster_ -auth-status-admin use-authentication -encryption-protocol-proposed tls-psk`

. プロンプトが表示されたら、デスティネーションクラスタで入力したパスフレーズを入力します。

