---
permalink: peering/peering-basics-concept.html 
sidebar: sidebar 
keywords: peer, basics 
summary: 'ピア関係にあるクラスタとSVMは、クラスタ間論理インターフェイス（LIF）を使用してクラスタ間ネットワークを介して通信します。クラスタ間LIFは、"intercluster-core"ネットワーク インターフェイス サービスをサポートするLIFであり、通常は"default-intercluster"ネットワーク インターフェイス サービス ポリシーを使用して作成されます。ピア関係にあるクラスタ内のすべてのノードにクラスタ間LIFを作成する必要があります。' 
---
= ONTAPピアリングの基本
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
SnapMirrorを使用してスナップショットをレプリケートする前に、ソース クラスタとデスティネーション クラスタ間、およびソース SVM とデスティネーション SVM 間に_ピア関係_を作成する必要があります。ピア関係は、クラスタと SVM が安全にデータを交換できるようにするネットワーク接続を定義します。

ピア関係にあるクラスタとSVMは、_クラスタ間論理インターフェイス（LIF）_を使用してクラスタ間ネットワークを介して通信します。クラスタ間LIFは、「intercluster-core」ネットワーク・インターフェイス・サービスをサポートするLIFであり、通常は「default-intercluster」ネットワーク・インターフェイス・サービス・ポリシーを使用して作成されます。ピア関係にあるクラスタ内のすべてのノードにクラスタ間LIFを作成する必要があります。

クラスタ間LIFは、LIFが割り当てられているシステムSVMに属するルートを使用します。システムSVMは、クラスタレベルの通信用にIPspace内に自動的に作成されます。

ファンアウトとカスケードの両方のトポロジがサポートされます。カスケード トポロジの場合、クラスタ間ネットワークを作成する必要があるのは、プライマリ クラスタとセカンダリ クラスタの間、およびセカンダリ クラスタとターシャリ クラスタの間のみです。プライマリ クラスタとターシャリ クラスタの間にクラスタ間ネットワークを作成する必要はありません。

[NOTE]
====
管理者は、default-interclusterサービス ポリシーからintercluster-coreサービスを削除することが可能です（ただし推奨されません）。この場合、「default-intercluster」を使用してLIFを作成しても、そのLIFはクラスタ間LIFにはなりません。default-interclusterサービス ポリシーにintercluster-coreサービスが含まれていることを確認するには、次のコマンドを使用します。

`network interface service-policy show -policy default-intercluster`

 `network interface service-policy show`の詳細については、link:https://docs.netapp.com/us-en/ontap-cli/network-interface-service-policy-show.html["ONTAPコマンド リファレンス"^]を参照してください。

====