---
permalink: peering/remove-snapmirror-encryption-existing-relationship-task.html 
sidebar: sidebar 
keywords: remove, cluster, peering, encryption, existing, peer, relationship 
summary: デフォルトでは、 ONTAP 9.6 以降で作成されるすべてのピア関係でクラスタピアリングの暗号化が有効になります。クラスタ間ピアリング通信に暗号化を使用しない場合は、暗号化を無効にできます。 
---
= 既存のピア関係からクラスタピアリングの暗号化を削除します
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
デフォルトでは、 ONTAP 9.6 以降で作成されるすべてのピア関係でクラスタピアリングの暗号化が有効になります。クラスタ間ピアリング通信に暗号化を使用しない場合は、暗号化を無効にできます。

.手順
. デスティネーションクラスタで、クラスタピアリングの暗号化を中止するようにソースクラスタとの通信を変更します。
+
** 認証を維持したまま暗号化を解除するには、「+」を入力します
`cluster peer modify _source_cluster_ -auth-status-admin use-authentication -encryption none`
** 暗号化と認証を解除するには、「+」と入力します
`cluster peer modify _source_cluster_ -auth-status no-authentication`


. プロンプトが表示されたらパスフレーズを入力します。
. ソースクラスタで、デスティネーションクラスタとの通信の暗号化を無効にします。
+
** 認証を維持したまま暗号化を解除するには、「+」を入力します
`cluster peer modify _destination_cluster_ -auth-status-admin use-authentication -encrypt none`
** 暗号化と認証を解除するには、「+」と入力します
`cluster peer modify _destination_cluster_ -auth-status no-authentication`


. プロンプトが表示されたら、デスティネーションクラスタで入力したパスフレーズを入力します。

