---
permalink: peering/shared-dedicated-ports-intercluster-concept.html 
sidebar: sidebar 
keywords: use, shared, dedicated, ports, network, bandwidth, replication, interval, availability 
summary: クラスタ間通信専用のポートを使用することも、データネットワークで使用するポートを共有することもできます。ポートを共有するかどうかを決定する際には、ネットワーク帯域幅、レプリケーション間隔、およびポートの可用性を考慮する必要があります。 
---
= 共有または専用のONTAPポートを使用する
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
クラスタ間通信専用のポートを使用することも、データネットワークで使用するポートを共有することもできます。ポートを共有するかどうかを決定する際には、ネットワーク帯域幅、レプリケーション間隔、およびポートの可用性を考慮する必要があります。

[NOTE]
====
一方のピア クラスタでポートを共有し、もう一方のクラスタでは専用ポートを使用することができます。

====


== ネットワーク帯域幅

高速ネットワーク（10GbEなど）を採用している場合、データ アクセスに使用されるものと同じ10GbEポートでレプリケーションを実行しても、ローカルLANの帯域幅が不足することはあまりありません。

それでも、利用可能なWAN帯域幅とLAN帯域幅を比較する必要があります。利用可能なWAN帯域幅が10 GbEを大幅に下回る場合は、専用ポートの使用が必要になる可能性があります。

[TIP]
====
このルールの唯一の例外は、クラスタ内のすべてのノードまたは多くのノードがデータをレプリケートする場合です。この場合、帯域幅の使用率は通常、ノード間で分散されます。

====
専用ポートを使用していない場合は、通常、レプリケーション ネットワークの最大転送単位（MTU）サイズは、データ ネットワークのMTUサイズと同じになります。



== レプリケーション間隔

レプリケーションがオフピーク時に行われる場合、10GbE LAN接続がなくてもレプリケーションにデータ ポートを使用できるはずです。

通常の営業時間中にレプリケーションを行う場合は、レプリケーションされるデータの量と、データプロトコルとの競合を引き起こすほどの帯域幅が必要かどうかを考慮する必要があります。データプロトコル（SMB、NFS、iSCSI）によるネットワーク使用率が50%を超える場合は、ノードフェイルオーバーが発生してもパフォーマンスが低下しないように、クラスタ間通信に専用ポートを使用する必要があります。



== ポートを使用可能か

レプリケーション トラフィックがデータ トラフィックに干渉していると判断した場合は、クラスタ間LIFを同じノード上の他のクラスタ間対応共有ポートに移行できます。

VLANポートをレプリケーション専用にすることもできます。ポートの帯域幅は、すべてのVLANとベース ポートで共有されます。
