---
permalink: peering/shared-dedicated-ports-intercluster-concept.html 
sidebar: sidebar 
keywords: use, shared, dedicated, ports, network, bandwidth, replication, interval, availability 
summary: クラスタ間通信には専用のポートを使用することも、データネットワークで使用されているポートを共有することもできます。ポートを共有するかどうかを判断する際は、ネットワーク帯域幅、レプリケーション間隔、およびポートの可用性を考慮する必要があります。 
---
= 共有ポートまたは専用ポートを使用します
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
クラスタ間通信には専用のポートを使用することも、データネットワークで使用されているポートを共有することもできます。ポートを共有するかどうかを判断する際は、ネットワーク帯域幅、レプリケーション間隔、およびポートの可用性を考慮する必要があります。

[NOTE]
====
ピア関係にある一方のクラスタではポートを共有し、もう一方のクラスタでは専用ポートを使用することができます。

====


== ネットワーク帯域幅

10GbE のように高速なネットワークの場合は、データアクセスに使用されるのと同じ 10GbE ポートを使用してレプリケーションを実行するためのローカル LAN 帯域幅が十分にあると考えられます。

その場合も、 LAN 側と WAN 側の使用帯域幅を比較する必要があります。WAN 側で使用可能な帯域幅が 10GbE よりも大幅に狭い場合、専用ポートを使用しなければならないことがあります。

[TIP]
====
ただし、クラスタのすべてまたは多数のノードでデータをレプリケートする場合は例外で、この場合は一般に帯域幅がノード間で分散して使用されます。

====
専用ポートを使用しない場合、一般にレプリケーションネットワークの最大転送単位（ MTU ）サイズはデータネットワークの MTU サイズと同じにします。



== レプリケーション間隔

ピーク時を避けてレプリケーションを実施する場合は、 10GbE LAN 接続がなくてもデータポートを使用できるはずです。

通常の業務時間にレプリケーションを実施する場合は、レプリケートされるデータの量と、原因がデータプロトコルと競合するために必要な帯域幅を考慮する必要があるかどうかを検討する必要があります。データプロトコル（ SMB 、 NFS 、 iSCSI ）によるネットワーク利用率が 50% を超える場合は、ノードのフェイルオーバーが発生してもパフォーマンスの低下を招かないよう、クラスタ間通信に専用のポートを使用します。



== ポートの可用性

レプリケーショントラフィックがデータトラフィックの妨げになる場合は、同じノード上にある他の任意のクラスタ間対応共有ポートにクラスタ間 LIF を移行できます。

VLAN ポートをレプリケーション専用にすることもできます。ポートの帯域幅は、すべての VLAN とベースポートで共有されます。
