---
permalink: san-admin/address-issues-when-luns-go-offline-concept.html 
sidebar: sidebar 
keywords: ways, address, issues, when, luns, go, offline 
summary: 書き込みに利用できるスペースがない場合、LUNはデータの整合性を維持するためにオフラインになります。LUNがスペース不足でオフラインになる理由はさまざまですが、いくつかの方法でこの問題に対処できます。 
---
= LUNがオフラインになった場合の問題の対処方法
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
書き込みに利用できるスペースがない場合、LUNはデータの整合性を維持するためにオフラインになります。LUNがスペース不足でオフラインになる理由はさまざまですが、いくつかの方法でこの問題に対処できます。

[cols="2*"]
|===
| もし... | 次の操作を実行できます。 


 a| 
アグリゲートがフルである
 a| 
* ディスクを追加します。
*  `volume modify`コマンドを使用して、使用可能な領域があるボリュームを縮小します。
* 使用可能なスペースがあるスペース保証ボリュームがある場合は、 `volume modify`コマンドを使用してボリュームのスペース保証を `none`に変更します。




 a| 
ボリュームはフルだが、アグリゲートには使用可能なスペースがある
 a| 
* スペース ギャランティ ボリュームの場合は、 `volume modify`コマンドを使用してボリュームのサイズを増やします。
* シンプロビジョニングされたボリュームの場合は、 `volume modify` コマンドを使用してボリュームの最大サイズを増やします。
+
ボリュームの自動拡張が有効になっていない場合は、 `volume modify -autogrow-mode`を使用して有効にします。

*  `volume snapshot delete`コマンドを使用してスナップショットを手動で削除するか、 `volume snapshot autodelete modify`コマンドを使用してスナップショットを自動的に削除します。


|===
.関連情報
link:../disks-aggregates/index.html["ディスクとローカル階層（アグリゲート）の管理"]

link:../volumes/index.html["論理ストレージ管理"]
