---
permalink: san-admin/address-issues-when-luns-go-offline-concept.html 
sidebar: sidebar 
keywords: ways, address, issues, when, luns, go, offline 
summary: 書き込みに使用できるスペースがない場合、LUNはデータの整合性を維持するためにオフラインになります。LUNのスペースが不足してオフラインになる原因はさまざまですが、いくつかの方法で問題に対処できます。 
---
= LUNがオフラインになった場合の問題の対処方法
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
書き込みに使用できるスペースがない場合、LUNはデータの整合性を維持するためにオフラインになります。LUNのスペースが不足してオフラインになる原因はさまざまですが、いくつかの方法で問題に対処できます。

[cols="2*"]
|===
| 状況 | 可能です 


 a| 
アグリゲートがフルです
 a| 
* ディスクを追加します。
* コマンドを使用して `volume modify`、使用可能なスペースがあるボリュームを縮小します。
* 使用可能なスペースがあるスペースギャランティボリュームがある場合は、コマンドを使用して `volume modify`ボリュームのスペースギャランティをに変更します `none`。




 a| 
ボリュームがフルですが、包含アグリゲートに利用可能なスペースがあります
 a| 
* スペースギャランティボリュームの場合は、コマンドを使用し `volume modify`てボリュームのサイズを拡張します。
* シンプロビジョニングボリュームの場合は、コマンドを使用し `volume modify`てボリュームの最大サイズを拡張します。
+
ボリュームの自動拡張が有効になっていない場合は、を使用 `volume modify -autogrow-mode`して有効にします。

* コマンドを使用してSnapshotコピーを手動で削除する `volume snapshot delete`か、コマンドを使用し `volume snapshot autodelete modify`てSnapshotコピーを自動的に削除します。


|===
.関連情報
link:../disks-aggregates/index.html["ディスクとローカル階層（アグリゲート）の管理"]

link:../volumes/index.html["論理ストレージ管理"]
