---
permalink: san-admin/asa-iscsi-lif-fo-task.html 
sidebar: sidebar 
keywords: failover, iscsi, all san array, cli, system manager, auto-revert, revert network interface 
summary: ONTAP 9.11.1以降にアップグレードした場合は、ONTAP 9.10.1以前で作成したすべてのiSCSI LIFでLIFの自動フェイルオーバーを手動で有効にする必要があります。 
---
= iSCSI LIFの自動フェイルオーバーの有効化または無効化
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
ONTAP 9.11.1以降にアップグレードした場合は、ONTAP 9.10.1以前で作成したすべてのiSCSI LIFでLIFの自動フェイルオーバーを手動で有効にする必要があります。

ONTAP 9 .11.1以降では、オールフラッシュSANアレイプラットフォームでiSCSI LIFに対してLIFの自動フェイルオーバーを有効にすることができます。ストレージフェイルオーバーが発生すると、iSCSI LIFはホームノードまたはポートからHAパートナーノードまたはポートに自動的に移行され、フェイルオーバーの完了後に再び移行されます。または、iSCSI LIFのポートが正常な状態でなくなった場合、そのLIFは現在のホームノードの正常なポートに自動的に移行され、ポートが正常な状態に戻った時点で元のポートに戻ります。を使用すると、iSCSIで実行されているSANワークロードは、フェイルオーバー後にI/Oサービスを迅速に再開できます。

ONTAP 9 .11.1以降では、次のいずれかの条件に該当する場合、新しく作成したiSCSI LIFでLIFの自動フェイルオーバーがデフォルトで有効になります。

* SVMにiSCSI LIFがありません
* LIFの自動フェイルオーバーがSVMのすべてのiSCSI LIFで有効になっている




== iSCSI LIFの自動フェイルオーバーの有効化

ONTAP 9.10.1以前で作成したiSCSI LIFでは、デフォルトでLIFの自動フェイルオーバーが有効になっていません。SVM上にLIFの自動フェイルオーバーが有効になっていないiSCSI LIFがある場合、新しく作成したLIFでもLIFの自動フェイルオーバーは有効になりません。LIFの自動フェイルオーバーが有効になっていない状態でフェイルオーバーが発生すると、iSCSI LIFは移行されません。

詳細については、をご覧ください link:../networking/configure_lifs_cluster_administrators_only_overview.html#lif-failover-and-giveback["LIFのフェイルオーバーとギブバック"]。

.ステップ
. iSCSI LIFの自動フェイルオーバーを有効にします。
+
[source, cli]
----
network interface modify -vserver <SVM_name> -lif <iscsi_lif> -failover-policy sfo-partner-only -auto-revert true
----
+
SVM上のすべてのiSCSI LIFを更新するには、の代わりに `lif`を使用し `-lif*`ます。





== iSCSI LIFの自動フェイルオーバーを無効にする

ONTAP 9 10.1以前で作成したiSCSI LIFに対するiSCSI LIFの自動フェイルオーバーを有効にしていた場合は、無効にすることもできます。

.ステップ
. iSCSI LIFの自動フェイルオーバーを無効にします。
+
[source, cli]
----
network interface modify -vserver <SVM_name> -lif <iscsi_lif> -failover-policy disabled -auto-revert false
----
+
SVM上のすべてのiSCSI LIFを更新するには、の代わりに `lif`を使用し `-lif*`ます。



.関連情報
* link:../networking/create_a_lif.html["LIFの作成"]
* シユトウlink:../networking/migrate_a_lif.html["LIFを移行する"]
* シユトウlink:../networking/revert_a_lif_to_its_home_port.html["LIFをホームポートにリバートします。"]
* link:../networking/configure_failover_settings_on_a_lif.html["LIFのフェイルオーバーを設定する"]

