---
permalink: san-admin/commands-manage-fc-adapters-reference.html 
sidebar: sidebar 
keywords: commands, managing, fc, adapters 
summary: FCコマンドを使用して、ストレージ コントローラのFCターゲット アダプタ、FCイニシエータ アダプタ、およびオンボードFCアダプタを管理できます。FCプロトコルとFC-NVMeプロトコルのFCアダプタの管理には、同じコマンドを使用します。 
---
= FCアダプタの管理用コマンド
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
FCコマンドを使用して、ストレージ コントローラのFCターゲット アダプタ、FCイニシエータ アダプタ、およびオンボードFCアダプタを管理できます。FCプロトコルとFC-NVMeプロトコルのFCアダプタの管理には、同じコマンドを使用します。

FCイニシエータアダプタコマンドはノードレベルでのみ機能します。FCイニシエータアダプタコマンドを使用する前に、 `run -node _node_name_`コマンドを使用する必要があります。



== FC ターゲット アダプタを管理するためのコマンド

[cols="2*"]
|===
| 状況 | 使用するコマンド 


 a| 
ノード上のFCアダプタ情報を表示する
 a| 
`network fcp adapter show`



 a| 
FCターゲット アダプタパラメータを変更する
 a| 
`network fcp adapter modify`



 a| 
FCプロトコルのトラフィック情報を表示する
 a| 
`run -node _node_name_ sysstat -f`



 a| 
FCプロトコルの実行時間を表示します
 a| 
`run -node _node_name_ uptime`



 a| 
ディスプレイ アダプタの設定とステータス
 a| 
`run -node _node_name_ sysconfig -v _adapter_`



 a| 
インストールされている拡張カードと構成エラーの有無を確認します
 a| 
`run -node _node_name_ sysconfig -ac`



 a| 
コマンドのマニュアル ページを表示する
 a| 
`man <command_name>`

|===


== FCイニシエータ アダプタを管理するためのコマンド

[cols="2*"]
|===
| 状況 | 使用するコマンド 


 a| 
ノード内のすべてのイニシエーターとそのアダプターの情報を表示します
 a| 
`run -node _node_name_ storage show adapter`



 a| 
ディスプレイ アダプタの設定とステータス
 a| 
`run -node _node_name_ sysconfig -v _adapter_`



 a| 
インストールされている拡張カードと構成エラーの有無を確認します
 a| 
`run -node _node_name_ sysconfig -ac`

|===


== オンボード FC アダプタを管理するためのコマンド

[cols="2*"]
|===
| 状況 | 使用するコマンド 


 a| 
オンボードFCポートのステータスを表示する
 a| 
`run -node _node_name_ system hardware unified-connect show`

|===
.関連情報
* link:https://docs.netapp.com/us-en/ontap-cli/search.html?q=network+fcp+adapter["ネットワーク FCP アダプタ"^]

