---
permalink: san-admin/configure-return-fqdn-host-iscsi-discovery-task.html 
sidebar: sidebar 
keywords: configure, iscsi, lifs, return, fqdn, host, sendtargets discovery operation 
summary: ONTAP 9以降では、ホストOSから送信されたiSCSI SendTargets検出処理に対してFully Qualified Domain Name（FQDN;完全修飾ドメイン名）を返すようにiSCSI LIFを設定できます。FQDNを返すように設定すると、ホストOSとストレージ サービスの間にNetwork Address Translation（NAT;ネットワークアドレス変換）デバイスがある場合に便利です。 
---
= ホストによるiSCSI SendTargets検出処理に対してFQDNを返すためのiSCSI LIFの設定
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
ONTAP 9以降では、ホストOSから送信されたiSCSI SendTargets検出処理に対してFully Qualified Domain Name（FQDN;完全修飾ドメイン名）を返すようにiSCSI LIFを設定できます。FQDNを返すように設定すると、ホストOSとストレージ サービスの間にNetwork Address Translation（NAT;ネットワークアドレス変換）デバイスがある場合に便利です。

.タスク概要
IPアドレスはNATデバイスを挟んだ反対側では認識されませんが、FQDNであれば両方で認識されます。

[NOTE]
====
FQDN値の互換性のある最大文字数は、すべてのホストOSで128文字です。

====
.手順
. 権限の設定をadvancedに変更します。
+
`set -privilege advanced`

. FQDNを返すようにiSCSI LIFを設定します。
+
`vserver iscsi interface modify -vserver _SVM_name_ -lif _iscsi_LIF_name_ -sendtargets_fqdn FQDN`

+
次の例では、FQDNとしてstoragehost-005.example.comを返すようにiSCSI LIFを設定しています。

+
`vserver iscsi interface modify -vserver vs1 -lif vs1_iscsi1 -sendtargets-fqdn storagehost-005.example.com`

. sendtargetsがFQDNになっていることを確認します。
+
`vserver iscsi interface show -vserver _SVM_name_ -fields sendtargets-fqdn`

+
この例では、sendtargets-fqdn出力フィールドにstoragehost-005.example.comが表示されています。

+
[listing]
----
cluster::vserver*> vserver iscsi interface show -vserver vs1 -fields sendtargets-fqdn
vserver lif        sendtargets-fqdn
------- ---------- ---------------------------
vs1     vs1_iscsi1 storagehost-005.example.com
vs1     vs1_iscsi2 storagehost-006.example.com
----


.関連情報
link:../concepts/manual-pages.html["ONTAPコマンド リファレンス"]
