---
permalink: san-admin/copy-luns-concept.html 
sidebar: sidebar 
keywords: considerations, copying, luns 
summary: LUN をコピーする場合は、いくつかの考慮事項に注意する必要があります。 
---
= LUN のコピーに関する注意事項
:icons: font
:imagesdir: ../media/


[role="lead"]
LUN をコピーする場合は、いくつかの考慮事項に注意する必要があります。

クラスタ管理者は、「 lun copy 」コマンドを使用して、クラスタ内の Storage Virtual Machine （ SVM ）間で LUN をコピーできます。クラスタ管理者は、 SVM 間の LUN コピー処理を実行する前に、「 vserver peer create 」コマンドを使用して SVM ピア関係を確立する必要があります。ソースボリューム内に SIS クローン用の十分なスペースが必要です。

スナップショット・コピー内の LUN は 'lun copy コマンドのソース LUN として使用できます「 lun copy 」コマンドを使用して LUN をコピーすると、 LUN コピーに対する読み取りと書き込みがすぐに可能になります。LUN コピーの作成によってソース LUN が変更されることはありません。ソース LUN と LUN コピーは、 LUN シリアル番号の異なる一意の LUN として存在します。ソース LUN に対する変更は LUN コピーに反映されず、 LUN コピーに対する変更はソース LUN に反映されません。ソース LUN の LUN マッピングは新しい LUN にコピーされないため、 LUN コピーをマッピングする必要があります。

Snapshot コピーによるデータ保護はボリュームレベルで行われます。そのため、ソース LUN のボリュームとは異なるボリュームに LUN をコピーする場合、デスティネーション LUN にはデスティネーションボリュームのデータ保護形式が適用されます。デスティネーションボリューム用の Snapshot コピーが確立されていない場合、 LUN コピーの Snapshot コピーは作成されません。

LUN のコピーはノンストップオペレーションです。

次の種類の LUN はコピーできません。

* ファイルから作成された LUN
* NVFAIL 状態の LUN
* 負荷共有関係にある LUN
* プロトコルエンドポイントクラスの LUN

