---
permalink: san-admin/copy-luns-concept.html 
sidebar: sidebar 
keywords: considerations, copying, luns, before 
summary: LUNをコピーする前に、次の点に注意してください。 
---
= LUNをコピーする前に理解しておくべきこと
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
LUNをコピーする前に、次の点に注意してください。

クラスタ管理者は、を使用して、クラスタ内のStorage Virtual Machine（SVM）間でLUNをコピーできます `lun copy` コマンドを実行しますクラスタ管理者は、を使用してStorage Virtual Machine（SVM）ピア関係を確立する必要があります `vserver peer create` SVM間のLUNコピー処理を実行する前のコマンド。ソースボリューム内に SIS クローン用の十分なスペースが必要です。

Snapshotコピー内のLUNをのソースLUNとして使用できます `lun copy` コマンドを実行しますを使用してLUNをコピーする場合 `lun copy` コマンドを実行すると、LUNコピーの読み取りと書き込みがすぐに可能になります。LUN コピーの作成によってソース LUN が変更されることはありません。ソース LUN と LUN コピーは、 LUN シリアル番号の異なる一意の LUN として存在します。ソース LUN に対する変更は LUN コピーに反映されず、 LUN コピーに対する変更はソース LUN に反映されません。ソース LUN の LUN マッピングは新しい LUN にコピーされないため、 LUN コピーをマッピングする必要があります。

Snapshot コピーによるデータ保護はボリュームレベルで行われます。そのため、ソース LUN のボリュームとは異なるボリュームに LUN をコピーする場合、デスティネーション LUN にはデスティネーションボリュームのデータ保護形式が適用されます。デスティネーションボリューム用の Snapshot コピーが確立されていない場合、 LUN コピーの Snapshot コピーは作成されません。

LUN のコピーはノンストップオペレーションです。

次の種類の LUN はコピーできません。

* ファイルから作成された LUN
* NVFAIL 状態の LUN
* 負荷共有関係にある LUN
* プロトコルエンドポイントクラスの LUN

