---
permalink: san-admin/create-nvme-namespace-subsystem-task.html 
sidebar: sidebar 
keywords: create, nvme, namespace, subsystem 
summary: NVMe プロトコルを使用するシステムでは、 NVMe のネームスペースとサブシステムを 1 つ以上作成する必要があります。各ネームスペースを NVMe サブシステムにマッピングして、ホストシステムからのデータアクセスを許可することができます。 
---
= NVMe ストレージをプロビジョニングする
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
特定のホストの手順 を使用できない場合は、次の手順に従って、NVMeでサポートされるすべてのホストのネームスペースを作成し、ストレージをプロビジョニングします。

ネームスペースは、 Linux では SCSI ディスクデバイスとして表示されます。

この手順は、既存の Storage VM に新しいネームスペースを作成します。Storage VM が NVMe 用に設定され、 FC または TCP 転送がすでにセットアップされている必要があります。

ONTAP 9.8 以降では、ストレージをプロビジョニングすると QoS がデフォルトで有効になります。QoS を無効にするか、プロビジョニングプロセス中またはあとからカスタムの QoS ポリシーを選択できます。

[role="tabbed-block"]
====
.System Manager の略
--
ONTAP System Manager（9.7以降）を使用して、NVMeプロトコルを使用してストレージを提供するネームスペースを作成します。

.手順
. System Manager で、 * Storage > NVMe 名前空間 * をクリックし、 * Add * をクリックします。
+
新しいサブシステムを作成する必要がある場合は、 * その他のオプション * をクリックします。

. ONTAP 9.8 以降を実行していて、 QoS を無効にする場合やカスタムの QoS ポリシーを選択する場合は、「その他のオプション」をクリックし、「 * ストレージおよび最適化 * 」で「 * パフォーマンスサービスレベル * 」を選択します。


. FC スイッチを WWPN でゾーニングイニシエータごとに 1 つのゾーンを使用し、各ゾーンにすべてのターゲットポートを含めます。
. ホストで、新しいネームスペースを検出します。
. ネームスペースを初期化し、ファイルシステムでフォーマットします。
. ホストがネームスペースに対してデータの書き込みと読み取りを実行できることを確認します。


--
.CLI の使用
--
ONTAP のCLIを使用して、NVMeプロトコルを使用してストレージを提供するネームスペースを作成します。

この手順 は、NVMeプロトコル用に設定済みの既存のStorage VMにNVMeネームスペースとサブシステムを作成し、ネームスペースをサブシステムにマッピングしてホストシステムからのデータアクセスを許可します。

NVMe用にStorage VMを設定する必要がある場合は、を参照してください link:configure-svm-nvme-task.html["NVMe 用に SVM を設定します"]。

.手順
. SVM が NVMe 用に設定されていることを確認します。
+
`vserver show -vserver _SVM_name_ -fields allowed-protocols`

+
`NVMe` の下にが表示されます `allowed-protocols` 列（Column）：

. NVMe ネームスペースを作成します。
+
`vserver nvme namespace create -vserver _SVM_name_ -path _path_ -size _size_of_namespace_ -ostype _OS_type_`

. NVMe サブシステムを作成します。
+
`vserver nvme subsystem create -vserver _SVM_name_ -subsystem _name_of_subsystem_ -ostype _OS_type_`

+
NVMe サブシステムの名前では大文字と小文字が区別されます。1~96文字で指定する必要があります。特殊文字を使用できます。

. サブシステムが作成されたことを確認します。
+
`vserver nvme subsystem show -vserver _SVM_name_`

+
。 `nvme` サブシステムがの下に表示されます `Subsystem` 列（Column）：

. ホストから NQN を取得します。
. ホストの NQN をサブシステムに追加します。
+
`vserver nvme subsystem host add -vserver _SVM_name_ -subsystem _subsystem_name_ -host-nqn _Host_NQN_:subsystem._subsystem_name_`

. ネームスペースをサブシステムにマッピングします。
+
`vserver nvme subsystem map add -vserver _SVM_name_ -subsystem _subsystem_name_ -path _path_`

+
ネームスペースは、 1 つのサブシステムにのみマッピングできます。

. ネームスペースがサブシステムにマッピングされていることを確認します。
+
`vserver nvme namespace show -vserver _SVM_name_ -instance`

+
サブシステムがとして表示される必要があります `Attached subsystem`。



--
====


== NVMe サブシステムについて

NVMe サブシステムには、 1 つ以上のコントローラ、 1 つ以上のネームスペース、 1 つ以上の不揮発性メモリ（ NVM ）サブシステムポート（ FC-NVMe または RDMA トランスポートポート）、 NVM ストレージメディア、およびコントローラと NVM ストレージメディア間のインターフェイスが含まれます。コントローラのマッピングと管理のために、 NVM サブシステムは ONTAP の SVM にマッピングされます。

NVMe over Fabric （ NVMeoF ）サブシステムは、 FreeBSD カーネルに属する独立したカーネルオブジェクトです。NVMeoF サブシステムは次のコンポーネントと連携します。

* BCOMKA 、 FCT 、 VDOM などの SAN コンポーネント
* WAFL
* CM 、 ASUP 、 EMS などの RAS コンポーネント


NVMeoF サブシステムとの連携は、いずれも ONTAP で検出された現在の定義とパターンに従います。
