---
permalink: san-admin/create-flexclone-luns-snapshot-copy-volume-task.html 
sidebar: sidebar 
keywords: create, flexclone, luns, snapshot, copy, volume 
summary: ボリューム内の Snapshot コピーを使用して、 LUN の FlexClone コピーを作成できます。LUN の FlexClone コピーは読み書き可能です。 
---
= ボリューム内の Snapshot コピーから FlexClone LUN を作成します
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
ボリューム内の Snapshot コピーを使用して、 LUN の FlexClone コピーを作成できます。LUN の FlexClone コピーは読み書き可能です。

.必要なもの
FlexClone ライセンスがインストールされている必要があります。

.このタスクについて
FlexClone LUN は、親 LUN のスペースリザベーション属性を継承します。スペースリザーブされた FlexClone LUN には、親のスペースリザーブ LUN と同量のスペースが必要です。FlexClone LUN のスペースをリザーブしない場合は、クローンに対する変更を保存するために十分なスペースがボリュームに必要です。

.手順
. LUN がマッピングされていないか、書き込まれていないことを確認します。
. LUN が含まれているボリュームの Snapshot コピーを作成します。
+
'volume snapshot create -vserver_name_-volume_name_-snapshot_snapshot_name_`

+
クローニングする LUN の Snapshot コピー（元の Snapshot コピー）を作成する必要があります。

. Snapshot コピーから FlexClone LUN を作成します。
+
'file clone create -vserver_name_-volume_name_-source-path_source_path_-snapshot-name _snapshot_name __ -destination-path destination_path _

+
FlexClone LUN を自動削除できるようにする必要がある場合は '-autodelete true を含めますセミシックプロビジョニングを使用してこの FlexClone LUN をボリューム内に作成する場合は、すべての FlexClone LUN で自動削除を有効にする必要があります。

. FlexClone LUN が正しいことを確認します。
+
「 lun show -vserver vserver_name _ 」のように表示されます

+
[listing]
----

Vserver Path                      State    Mapped    Type     Size
------- ----------------------    -------- --------- -------- -------
vs1     /vol/vol1/lun1_clone      online   unmapped windows   47.07MB
vs1     /vol/vol1/lun1_snap_clone online   unmapped windows   47.07MB
----

