---
permalink: san-admin/create-luns-mapping-igroups-task.html 
sidebar: sidebar 
keywords: create, luns, mapping, igroups 
summary: SAN 環境の構成の一環として、 LUN を作成し、イニシエータグループ（ igroup ）を作成して、 LUN を igroup にマッピングする必要があります。 
---
= LUN を作成して igroup にマッピングします
:icons: font
:imagesdir: ../media/


[role="lead"]
SAN 環境の構成の一環として、 LUN を作成し、イニシエータグループ（ igroup ）を作成して、 LUN を igroup にマッピングする必要があります。

.必要なもの
* アグリゲート、ボリューム、および Storage Virtual Machine （ SVM ）を作成しておく必要があります。
* FC または iSCSI によるブロックアクセスを有効にしておく必要があります。
* クラスタ内のすべてのノードに SAN LIF を作成しておく必要があります。


LUN を作成するときは、 LUN の OS タイプを指定する必要があります。LUN の実際のサイズは、 LUN の OS タイプによって多少異なります。LUN の作成後に LUN の OS タイプを変更することはできません。

各 LUN のメタデータ用として、 LUN を含むアグリゲートに約 64KB のスペースが必要です。LUN の作成時には、 LUN を含むアグリゲートに LUN のメタデータ用の十分なスペースがあることを確認する必要があります。アグリゲートに LUN のメタデータ用のスペースが十分にないと、一部のホストが LUN にアクセスできなくなる可能性があります。

ONTAP 9.4 以前では、必要に応じて LUN を元のサイズの 10 倍まで拡張できます。たとえば、 100GB で作成した LUN は 1 、 000GB まで拡張できます。LUN のサイズの上限である 16TB を超えることはできません。この制限は、 ONTAP 9.5 以降には適用されません。

[NOTE]
====
LUN の実際の最大サイズが 16TB の場合とは異なります。ONTAP では、制限値の端数が切り捨てられます。

====
LUN の作成時、 Asymmetric Logical Unit Access （ ALUA ；非対称論理ユニットアクセス）は常に有効になります。ALUA の設定は変更できません。

.手順
. LUN を作成します。
+
lun create -vserver vserver_name -volume _volume_name -- lun_name_size_lun_size_-ostype ostype _lun_ostype -space-reserve enabled|disabled

+
LUN 名は 255 文字以内で、スペースは使用できません。

+
ホスト・オペレーティング・システムが Windows 2008 以降の場合は、 ostype として「 windows_2008 」を使用してください。「 pace - reserve 」オプションはデフォルトでイネーブルになっています。スペースリザーブなしの LUN が必要な場合は、「 space-reserve 」オプションを「 disabled 」に設定する必要があります。

+
[NOTE]
====
NVFAIL オプションは、ボリュームで LUN が作成されると、自動的に有効になります。

====
. igroup を作成します。
+
igroup create -vserver_name_-igroup igroup_name -protocol fcp | iscsi | mixed -ostype lun_ostype _ -initiator_name_`

+
ホスト・オペレーティング・システムが Windows 2008 以降の場合は、 ostype として「 windows_2008 」を使用してください。

. LUN を igroup にマッピングします。
+
lun mapping create -vserver_name_-volume_name_-lun_lun_name -igroup_igroup_name _ -igroup_igroup_name _

. LUN が正しく設定されていることを確認します。
+
「 lun show -vserver vserver_name _ 」のように表示されます



link:../disks-aggregates/index.html["ディスクおよびアグリゲートの管理"]

link:../volumes/index.html["論理ストレージ管理"]

link:../networking/index.html["Network Management の略"]
