---
permalink: san-admin/data-protection-methods-reference.html 
sidebar: sidebar 
keywords: data, protection, methods, san, environments, snapmirror business continuity, smbc, snapshot copy, mirror, update, flexclone luns, license required, snapvault, backups, snapdrive, windows, unix 
summary: データを保護するには、データのコピーを作成して、偶発的な削除、アプリケーションのクラッシュ、データの破損、災害が発生した場合にデータをリストアできるようにします。ONTAPは、データ保護とバックアップのニーズに応じて、データを保護するためのさまざまな方法を提供します。 
---
= SAN環境向けのONTAPデータ保護方法
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
データを保護するには、データのコピーを作成して、偶発的な削除、アプリケーションのクラッシュ、データの破損、災害が発生した場合にデータをリストアできるようにします。ONTAPは、データ保護とバックアップのニーズに応じて、データを保護するためのさまざまな方法を提供します。



== SnapMirrorアクティブ同期

ONTAP 9 .9.1の一般提供開始以降では、目標復旧時間ゼロ（ゼロRTO）または透過的アプリケーションフェイルオーバー（TAF）が提供され、SAN環境でビジネスクリティカルなアプリケーションを自動的にフェイルオーバーできます。SnapMirrorアクティブな同期を実行するには、2つのAFFクラスタまたは2つのオールフラッシュSANアレイ（ASA）クラスタを使用する構成にONTAPメディエーター1.2がインストールされている必要があります。

link:../snapmirror-active-sync/index.html["SnapMirrorアクティブ同期"^]



== Snapshot

LUNの複数のバックアップを手動または自動で作成、スケジュール、および保守できます。Snapshotは、最小限の追加ボリュームスペースのみを使用し、パフォーマンスコストは発生しません。LUNデータを誤って変更または削除してしまった場合でも、最新のSnapshotからデータを簡単かつ迅速にリストアできます。



== FlexClone LUN（FlexCloneのライセンスが必要）

アクティブボリュームまたはSnapshot内にある別のLUNの書き込み可能なポイントインタイムコピーを提供します。クローンとその親は、相互に影響を及ぼさずに個別に変更できます。



== SnapRestore（ライセンスが必要）

ボリューム全体のSnapshotから、スペース効率に優れた高速データリカバリを必要に応じて実行できます。SnapRestoreを使用すると、ストレージシステムをリブートしなくても、LUNを以前保存した状態にリストアできます。



== データ保護ミラー コピー（SnapMirrorのライセンスが必要）

非同期のディザスタリカバリを提供します。これにより、ボリューム上のデータのSnapshotを定期的に作成し、それらのSnapshotをローカルまたはワイドエリアネットワーク経由でパートナーボリューム（通常は別のクラスタ上）にコピーして保持できます。ソースボリューム上のデータが破損した場合や失われた場合には、パートナーボリューム上のミラーコピーを使用して、最後のSnapshotの時点のデータをすぐに使用およびリストアできます。



== SnapVaultバックアップ（SnapMirrorのライセンスが必要）

ストレージ効率に優れた、長期間保持できるバックアップを提供します。SnapVault関係を使用すると、ボリュームの選択したSnapshotをデスティネーションボリュームにバックアップし、保持することができます。

テープ バックアップおよびアーカイブ処理を行っている場合は、SnapVaultセカンダリ ボリュームにすでにバックアップされているデータに対してそれらの処理を実行できます。



== SnapDrive for WindowsまたはSnapDrive for UNIX（SnapDriveのライセンスが必要）

LUNへのアクセスを構成し、LUNを管理し、WindowsホストまたはUNIXホストからストレージシステムのスナップショットを直接管理します。



== ネイティブ テープ バックアップ / リカバリ

ONTAPはほとんどの既存のテープ ドライブに対応しており、テープ ベンダーが新しいデバイスのサポートを動的に追加するための方策も用意されています。ONTAPはRemote Magnetic Tape（RMT）プロトコルもサポートしているため、RMT対応システムへのバックアップやリカバリも可能です。

.関連情報
http://mysupport.netapp.com/documentation/productlibrary/index.html?productID=30050["NetAppのマニュアル：「SnapDrive for UNIX」"^] http://mysupport.netapp.com/documentation/productlibrary/index.html?productID=30049["NetAppのマニュアル：「SnapDrive for Windows（現在のリリース）」"^] link:../tape-backup/index.html["テープバックアップを使用したデータ保護"]
