---
permalink: san-admin/flexclone-luns-protect-your-data-concept.html 
sidebar: sidebar 
keywords: use, flexclone, luns, protect, your, data 
summary: FlexClone LUNは、アクティブボリューム内やSnapshotコピー内にある別のLUNの書き込み可能なポイントインタイムコピーです。クローンとその親は、相互に影響を及ぼさずに個別に変更できます。 
---
= FlexClone LUNを使用したデータ保護の概要
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
FlexClone LUNは、アクティブボリューム内やSnapshotコピー内にある別のLUNの書き込み可能なポイントインタイムコピーです。クローンとその親は、相互に影響を及ぼさずに個別に変更できます。

FlexClone LUNは、最初は親LUNとスペースを共有します。デフォルトでは、FlexClone LUNは親LUNのスペースリザーブ属性を継承します。たとえば、親LUNがスペースリザーブなしの場合、FlexClone LUNもデフォルトでスペースリザーブなしになります。ただし、スペースリザーブLUNである親からスペースリザーブなしのFlexClone LUNを作成することはできます。

LUNクローンを作成すると、バックグラウンドでブロック共有が発生し、ブロック共有が完了するまでボリュームのSnapshotコピーを作成できません。

コマンドを使用して、ボリュームでFlexClone LUNの自動削除機能を有効にする必要があります `volume snapshot autodelete modify`。そうしないと、FlexClone LUNを自動的に削除するように設定されていても、ボリュームでFlexCloneの自動削除が設定されていない場合、FlexClone LUNは削除されません。

FlexClone LUNを作成すると、FlexClone LUNの自動削除機能はデフォルトで無効になります。FlexClone LUNを自動的に削除するには、FlexClone LUNごとに手動で有効にする必要があります。ボリュームのセミシックプロビジョニングを使用している場合に、このオプションが提供する「ベストエフォート」の書き込み保証が必要な場合は、 _ALL_FlexClone LUN を自動削除できるようにする必要があります。

[NOTE]
====
SnapshotコピーからFlexClone LUNを作成すると、スペース効率に優れたバックグラウンドプロセスを使用して、LUNがSnapshotコピーから自動的にスプリットされます。そのため、LUNがSnapshotコピーに依存したり、追加のスペースを消費したりすることはありません。このバックグラウンドスプリットが完了しておらず、Snapshotコピーが自動的に削除された場合、そのFlexClone LUNに対してFlexCloneの自動削除機能が無効になっていても、そのFlexClone LUNは削除されます。バックグラウンドスプリットの完了後は、Snapshotコピーが削除されても、FlexClone LUNは削除されません。

====
.関連情報
link:../volumes/index.html["論理ストレージ管理"]
