---
permalink: san-admin/host-side-management-concept.html 
sidebar: sidebar 
keywords: understand, host-side, space, management 
summary: シンプロビジョニング環境において、ホストファイルシステムで解放されたスペースをストレージシステム側で管理するプロセスを担っているのがホスト側のスペース管理です。 
---
= SANホスト側のスペース管理
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
シンプロビジョニング環境において、ホストファイルシステムで解放されたスペースをストレージシステム側で管理するプロセスを担っているのがホスト側のスペース管理です。

ホストファイルシステムでは、新しいデータの格納に使用できるブロックはどれか、また、有効なデータを含んでいるため上書きしてはならないブロックはどれかを追跡するための情報がメタデータに記録されます。このメタデータは LUN 内に格納されます。ホストファイルシステム内でファイルが削除されると、ファイルシステムのメタデータが更新され、削除されたファイルのブロックが空きスペースとしてマークされます。ファイルシステム内の合計空きスペースが再計算され、新しく解放されたブロック分のスペースが組み入れられます。ストレージシステム側では、こうしたメタデータの更新が、ホストによって実行される他の書き込みとまったく相違ないものとして認識されます。このため、ストレージシステム側では、削除が行われた事実が検知されません。

その結果、ホスト側と基盤のストレージシステム側で報告される空きスペース容量に不一致が生じます。たとえば、新しくプロビジョニングされた 200GB の LUN がストレージシステムによってホストに割り当てられているとします。ホストとストレージシステムの両方で、 200GB の空きスペースが報告されます。ホストに 100GB のデータが書き込まれた場合。この時点で、ホストとストレージシステムの両方で、使用済みスペースが 100GB 、未使用スペースが 100GB と報告されます。

次に、ホストから 50GB のデータが削除されました。この時点で、ホストは使用済みスペースが 50GB 、未使用スペースが 150GB であると報告します。ただし、ストレージシステムから報告される使用済みスペースは 100GB 、未使用スペースは 100GB です。

ホスト側のスペース管理では、さまざまな方法を使用して、ホストとストレージシステム間のスペースの差分を調整します。



== SnapCenter によるホスト管理の簡易化

SnapCenter ソフトウェアを使用すると、 iSCSI ストレージや FC ストレージに関連する管理作業とデータ保護作業を簡単に行うことができます。SnapCenter は、 Windows ホストと UNIX ホストに対応するオプションの管理パッケージです。

SnapCenter ソフトウェアを使用すると、ストレージプールから簡単に仮想ディスクを作成して複数のストレージシステムに分散したり、ストレージのプロビジョニングタスクを自動化したりできます。また、ホストのデータと整合性のある Snapshot コピーや Snapshot コピーからのクローンの作成プロセスが簡易化されます。

詳細については、ネットアップ製品のドキュメントを参照してください https://docs.netapp.com/us-en/snapcenter/index.html["SnapCenter"]。

.関連リンク
link:enable-space-allocation-scsi-thin-provisioned-luns-task.html["SCSI シンプロビジョニング LUN のスペース割り当てを有効にします"]
