---
permalink: san-admin/igroups-concept.html 
sidebar: sidebar 
keywords: understand, igroups 
summary: initiator group（igroup;イニシエータ グループ）は、FCプロトコル ホストWWPNまたはiSCSIホスト ノード名のテーブルです。igroupを定義してLUNにマッピングし、どのイニシエータがLUNにアクセスできるかを制御できます。 
---
= igroupについて
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
initiator group（igroup;イニシエータ グループ）は、FCプロトコル ホストWWPNまたはiSCSIホスト ノード名のテーブルです。igroupを定義してLUNにマッピングし、どのイニシエータがLUNにアクセスできるかを制御できます。

通常は、ホストのイニシエータ ポートまたはソフトウェア イニシエータがすべてLUNにアクセスできることが必要とされます。マルチパス ソフトウェアを使用しているか、またはクラスタ ホストがある場合、各イニシエータ ポートまたは各クラスタ ホストのソフトウェア イニシエータは同じLUNへの冗長パスを必要とします。

LUNにアクセスできるイニシエータを指定するigroupはLUNの作成前後どちらでも作成できますが、LUNをigroupにマッピングするためにはigroupを作成しておく必要があります。

igroupには複数のイニシエータを含めることができ、複数のigroupに同じイニシエータを含めることができます。ただし、同じイニシエータを持つ複数のigroupに1つのLUNをマッピングすることはできません。1つのイニシエータを、ostypeが異なる複数のigroupのメンバーにすることはできません。



== igroupによるLUNアクセスの提供例

複数のigroupを作成して、ホストで利用できるLUNを定義することができます。たとえば、ホスト クラスタを使用している場合は、いくつかのigroupを使用して、クラスタ内の1つのホストだけ、またはすべてのホストに特定のLUNが認識されるように設定できます。

次の表は、ストレージ システムにアクセスする4つのホストを、4つのigroupによってLUNにアクセスできるようにする方法を示しています。クラスタ化されたホスト（Host3およびHost4）は、どちらも同じigroup（group3）のメンバーであり、このigroupにマッピングされているLUNにアクセスできます。group4というigroupにはHost4のWWPNが含まれ、パートナーには表示されないローカルな情報が格納されます。

[cols="4*"]
|===
| HBA WWPN、IQN、またはEUIを持つホスト | igroup | igroupに追加されたWWPN、IQN、EUI | igroupにマッピングされたLUN 


 a| 
Host1、シングルパス（iSCSIソフトウェア イニシエータ）

iqn.1991-05.com.microsoft:host1
 a| 
グループ1
 a| 
iqn.1991-05.com.microsoft:host1
 a| 
`/vol/vol2/lun1`



 a| 
Host2、マルチパス（HBA 2個）

10:00:00:00:c9:2b:6b:3c

10:00:00:00:c9:2b:02:3c
 a| 
group2
 a| 
10:00:00:00:c9:2b:6b:3c

10:00:00:00:c9:2b:02:3c
 a| 
`/vol/vol2/lun2`



 a| 
Host3、マルチパス、Host4でクラスタ構成

10:00:00:00:c9:2b:32:1b

10:00:00:00:c9:2b:41:02
 a| 
group3
 a| 
10:00:00:00:c9:2b:32:1b

10:00:00:00:c9:2b:41:02

10:00:00:00:c9:2b:51:2c

10:00:00:00:c9:2b:47:a2
 a| 
`/vol/vol2/qtree1/lun3`



 a| 
Host4、マルチパス、クラスタ構成（Host3には認識されない）

10:00:00:00:c9:2b:51:2c

10:00:00:00:c9:2b:47:a2
 a| 
group4
 a| 
10:00:00:00:c9:2b:51:2c

10:00:00:00:c9:2b:47:a2
 a| 
`/vol/vol2/qtree2/lun4` `/vol/vol2/qtree1/lun5`

|===