---
permalink: san-admin/igroups-concept.html 
sidebar: sidebar 
keywords: understand, igroups 
summary: initiator group （ igroup ；イニシエータグループ）は、 FC プロトコルホスト WWPN または iSCSI ホストノード名のテーブルです。igroup を定義して LUN にマッピングし、どのイニシエータが LUN にアクセスできるかを制御できます。 
---
= igroup について
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
initiator group （ igroup ；イニシエータグループ）は、 FC プロトコルホスト WWPN または iSCSI ホストノード名のテーブルです。igroup を定義して LUN にマッピングし、どのイニシエータが LUN にアクセスできるかを制御できます。

通常は、ホストのイニシエータポートまたはソフトウェアイニシエータがすべて LUN にアクセスできることが必要とされます。マルチパスソフトウェアを使用しているか、またはクラスタホストがある場合、各イニシエータポートまたは各クラスタホストのソフトウェアイニシエータは同じ LUN への冗長パスを必要とします。

LUN にアクセスできるイニシエータを指定する igroup は LUN の作成前後どちらでも作成できますが、 LUN を igroup にマッピングするには igroup を作成しておく必要があります。

igroup には複数のイニシエータを含めることができ、複数の igroup に同じイニシエータを含めることができます。ただし、同じイニシエータを持つ複数の igroup に 1 つの LUN をマッピングすることはできません。1 つのイニシエータを、 ostype が異なる複数の igroup のメンバーにすることはできません。



== igroup による LUN アクセスの提供例

複数の igroup を作成して、ホストで利用できる LUN を定義することができます。たとえば、ホストクラスタを使用している場合、いくつかの igroup を使用して、クラスタ内の 1 つのホストだけ、またはすべてのホストに特定の LUN が認識されるように設定できます。

次の表に、ストレージシステムにアクセスする 4 つのホストについて、 4 つの igroup によって LUN にアクセスできるようにする方法を示します。クラスタ化したホスト（ Host3 および Host4 ）は、両方とも同一 igroup （ group3 ）のメンバーであり、この igroup にマッピングされている LUN にアクセスできます。group4 という igroup には Host4 の WWPN が含まれ、パートナーには表示されないローカルな情報が格納されます。

[cols="4*"]
|===
| HBA WWPN 、 IQN 、または EUI のホスト | igroup 数 | igroup に追加されている WWPN 、 IQN 、 EUI | igroup にマッピングされている LUN 


 a| 
Host1 、シングルパス（ iSCSI ソフトウェアイニシエータ）

iqn.1991-05.com.microsoft:host1
 a| 
グループ 1
 a| 
iqn.1991-05.com.microsoft:host1
 a| 
`/vol/vol2/lun1`



 a| 
Host2 、マルチパス（ HBA × 2 ）

10 ： 00 ： 00 ： 00 ： c9 ： 2b ： 6b ： 3c

10 ： 00 ： 00 ： 00 ： c9 ： 2b ： 02 ： 3c
 a| 
グループ2
 a| 
10 ： 00 ： 00 ： 00 ： c9 ： 2b ： 6b ： 3c

10 ： 00 ： 00 ： 00 ： c9 ： 2b ： 02 ： 3c
 a| 
`/vol/vol2/lun2`



 a| 
Host3 、マルチパス、ホスト 4 でクラスタ構成

10：00：00：00：c9：2b：32：1b

10 ： 00 ： 00 ： 00 ： c9 ： 2b ： 41 ： 02
 a| 
グループ 3
 a| 
10：00：00：00：c9：2b：32：1b

10 ： 00 ： 00 ： 00 ： c9 ： 2b ： 41 ： 02

10：00：00：00：c9：2b：51：2c

10 ： 00 ： 00 ： 00 ： c9 ： 2b ： 47 ： A2
 a| 
`/vol/vol2/qtree1/lun3`



 a| 
Host4 、マルチパス、クラスタ構成（ Host3 には認識されない）

10：00：00：00：c9：2b：51：2c

10 ： 00 ： 00 ： 00 ： c9 ： 2b ： 47 ： A2
 a| 
グループ 4
 a| 
10：00：00：00：c9：2b：51：2c

10 ： 00 ： 00 ： 00 ： c9 ： 2b ： 47 ： A2
 a| 
`/vol/vol2/qtree2/lun4` `/vol/vol2/qtree1/lun5`

|===