---
permalink: san-admin/iscsi-endpoint-isolation-concept.html 
sidebar: sidebar 
keywords: iscsi, endpoint, isolation, add, remove, initiator, address, range 
summary: ONTAP 9 .1以降では、既存のiSCSIセキュリティコマンドが拡張され、IPアドレスの範囲または複数のIPアドレスを指定できるようになりました。 
---
= iSCSIエンドポイントの分離
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
ONTAP 9 .1以降では、既存のiSCSIセキュリティコマンドが拡張され、IPアドレスの範囲または複数のIPアドレスを指定できるようになりました。

すべてのiSCSIイニシエータは、ターゲットとのセッションまたは接続を確立する際に、発信元IPアドレスを提供する必要があります。この新機能は、発信元IPアドレスがサポート対象外または不明な場合にイニシエータがクラスタにログインできないようにすることで、一意の識別方式を提供します。サポート対象外または不明なIPアドレスから発信されたイニシエータではログインがiSCSIセッションレイヤで拒否されるため、イニシエータはクラスタ内のLUNまたはボリュームにアクセスできません。

既存のエントリの管理に役立つ2つの新しいコマンドを使用して、この新機能を実装します。



== イニシエータのアドレス範囲を追加する

iSCSIイニシエータのセキュリティ管理を改善するには、IPアドレスの範囲を追加するか、コマンドを使用して複数のIPアドレスを追加し `vserver iscsi security add-initiator-address-range`ます。

`cluster1::> vserver iscsi security add-initiator-address-range`



== イニシエータのアドレス範囲を削除する

IPアドレスの範囲または複数のIPアドレスを削除するには、コマンドを使用し `vserver iscsi security remove-initiator-address-range`ます。

`cluster1::> vserver iscsi security remove-initiator-address-range`
