---
permalink: san-admin/iscsi-endpoint-isolation-concept.html 
sidebar: sidebar 
keywords: iscsi, endpoint, isolation, add, remove, initiator, address, range 
summary: ONTAP 9.1 以降では、既存の iSCSI セキュリティコマンドが拡張され、 IP アドレスの範囲や複数の IP アドレスを受け入れることができるようになりました。 
---
= iSCSI エンドポイントの分離
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
ONTAP 9.1 以降では、既存の iSCSI セキュリティコマンドが拡張され、 IP アドレスの範囲や複数の IP アドレスを受け入れることができるようになりました。

すべての iSCSI イニシエータは、ターゲットとのセッションまたは接続を確立するときに、発信元 IP アドレスを提供する必要があります。元の IP アドレスがサポート対象外または不明な場合にイニシエータがクラスタにログインできないようにすることで、独自の識別を実現します。サポート対象外または不明な IP アドレスを発信したイニシエータは、 iSCSI セッションレイヤでログインが拒否されるため、クラスタ内の LUN やボリュームにアクセスできません。

この新しい機能を 2 つの新しいコマンドで実装して、既存のエントリを管理します。



== イニシエータのアドレス範囲を追加する

IP アドレス範囲を追加するか ' 複数の IP アドレスを vserver iscsi security add-initiator-address-range コマンドで追加することにより 'iSCSI イニシエータのセキュリティ管理を向上させます

'cluster1 ：：： > vserver iscsi security add -initiator-address-range



== イニシエータのアドレス範囲を削除する

「 vserver iscsi security remove-initiator-address-range 」コマンドを使用して、 IP アドレス範囲または複数の IP アドレスを削除します。

'cluster1 ：：： > vserver iscsi security remove-initiator-address-range
