---
permalink: san-admin/lif-movement-concept.html 
sidebar: sidebar 
keywords: considerations, san, lif, movement 
summary: クラスタにノードを追加したりクラスタからノードを削除するなど、クラスタの構成を変更する場合は、LIFを移動するだけで済みます。LIFを移動すれば、FCファブリックを再ゾーニングしたり、クラスタに接続されたホストとその新しいターゲット インターフェイスとの間に新しいiSCSIセッションを作成したりする必要がありません。 
---
= SAN LIFを移動する際の注意事項
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
クラスタにノードを追加したりクラスタからノードを削除するなど、クラスタの構成を変更する場合は、LIFを移動するだけで済みます。LIFを移動すれば、FCファブリックを再ゾーニングしたり、クラスタに接続されたホストとその新しいターゲット インターフェイスとの間に新しいiSCSIセッションを作成したりする必要がありません。

 `network interface move`コマンドを使用してSAN LIFを移動することはできません。SAN LIFの移動は、LIFをオフラインにし、別のホームノードまたはポートに移動してから、新しい場所でオンラインに戻すという手順で実行する必要があります。Asymmetric Logical Unit Access（ALUA）は、すべてのONTAP SANソリューションの一部として冗長パスと自動パス選択を提供します。そのため、LIFを移動のためにオフラインにしてもI/O中断は発生しません。ホストは単に再試行し、その後I/Oを別のLIFに移動します。

LIFの移動を使用すると、システムを停止することなく次のタスクを実行できます。

* クラスタの1個のHAペアを、LUNデータにアクセスするホストにはまったく支障のない形で、アップグレードしたHAペアに置き換える
* ターゲット インターフェイス カードをアップグレードする
* Storage Virtual Machine（SVM）のリソースをクラスタ内のノード セットから別のノード セットに移行する

