---
permalink: san-admin/lun-san-environments-concept.html 
sidebar: sidebar 
keywords: lun, guidelines, assigning, assign, ids, mapping, map, igroups 
summary: クラスタでLUNのセットアップを開始する前に、LUNに関する次のガイドラインを確認しておく必要があります。 
---
= LUNを作成する際の注意事項
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
クラスタでLUNのセットアップを開始する前に、LUNに関する次のガイドラインを確認しておく必要があります。



== LUNの実際のサイズが少し異なる理由

LUNのサイズについては、次の点に注意してください。

* LUNを作成する場合、LUNの実際のサイズはLUNのOSタイプによって多少異なります。LUNの作成後にLUNのOSタイプを変更することはできません。
* 最大LUNサイズでLUNを作成する場合は、LUNの実際のサイズが若干小さくなる可能性があることに注意してください。ONTAPは、制限を切り捨ててわずかに小さくします。
* 各LUNのメタデータ用に、包含アグリゲートに約64KBのスペースが必要です。LUNの作成時には、包含アグリゲートにLUNのメタデータ用の十分なスペースがあることを確認する必要があります。アグリゲートにLUNのメタデータ用のスペースが十分にないと、一部のホストがLUNにアクセスできなくなる可能性があります。




== LUN IDの割り当てに関するガイドライン

通常、デフォルトのLUN IDは0で始まり、LUNをマッピングするたびに1ずつ割り当てられます。ホストはLUN IDをLUNの場所とパス名に関連付けます。有効なLUN ID番号の範囲はホストによって異なります。詳細については、Host Utilitiesに付属のマニュアルを参照してください。



== LUNをigroupにマッピングする場合のガイドライン

* LUNは、igroupに一度だけマッピングできます。
* ベストプラクティスとして、1つのLUNをigroupを介して1つの特定のイニシエータにのみマッピングすることを推奨します。
* 1つのイニシエータを複数のigroupに追加できますが、イニシエータをマッピングできるLUNは1つだけです。
* 同じigroupにマッピングされた2つのLUNに同じLUN IDを使用することはできません。
* igroupとポートセットには、同じプロトコルタイプを使用する必要があります。

