---
permalink: san-admin/lun-san-environments-concept.html 
sidebar: sidebar 
keywords: lun, guidelines, assigning, assign, ids, mapping, map, igroups 
summary: クラスタで LUN のセットアップを開始する前に、 LUN に関するガイドラインを確認しておく必要があります。 
---
= LUNを作成する前に理解しておくべきこと
:allow-uri-read: 
:icons: font
:imagesdir: ../media/




== LUNの実際のサイズが少し異なる理由

LUNのサイズについては、次の点に注意してください。

* LUNを作成する場合、LUNの実際のサイズはLUNのOSタイプによって多少異なります。LUN の作成後に LUN の OS タイプを変更することはできません。
* 最大16TBのサイズのLUNを作成する場合、LUNの実際のサイズは少し小さくなる可能性があります。ONTAP では、制限値の端数が切り捨てられます。
* 各 LUN のメタデータ用として、 LUN を含むアグリゲートに約 64KB のスペースが必要です。LUN の作成時には、 LUN を含むアグリゲートに LUN のメタデータ用の十分なスペースがあることを確認する必要があります。アグリゲートに LUN のメタデータ用のスペースが十分にないと、一部のホストが LUN にアクセスできなくなる可能性があります。




== LUN ID の割り当てに関するガイドライン

通常、デフォルトの LUN ID は 0 で始まり、 LUN をマッピングするたびに 1 ずつ増加します。LUN ID は、ホストによって LUN の場所とパス名に関連付けられます。有効な LUN ID 番号の範囲は、ホストによって異なります。詳細については、 Host Utilities のマニュアルを参照してください。



== LUN を igroup にマッピングする場合のガイドラインを次に示します

* LUNは、igroupに一度だけマッピングできます。
* LUN は igroup を介して 1 つの特定のイニシエータにのみマッピングできます。
* 1 つのイニシエータを複数の igroup に追加できますが、そのイニシエータをマッピングできる LUN は 1 つだけです。
* 同じ igroup にマッピングされている 2 つの LUN に、同じ LUN ID を使用することはできません。
* igroup およびポートセットには、同じ種類のプロトコルを使用する必要があります。

