---
permalink: san-admin/manage-lifs-all-san-protocols-concept.html 
sidebar: sidebar 
keywords: manage, lifs, san protocols 
summary: LIFはSANホストに接続されています。ポートセットから削除したり、Storage Virtual Machine（SVM）内の別のノードに移動したり、LIFそのものを削除したりすることができます。 
---
= すべてのSANプロトコルのLIFの管理
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
SAN環境でクラスタのフェイルオーバー機能を利用するには、イニシエータでマルチパスI/O（MPIO）と非対称論理ユニット アクセス（ALUA）を使用する必要があります。ノードで障害が発生した場合、LIFは障害が発生したパートナー ノードのIPアドレスを引き継ぎません。代わりに、MPIOソフトウェアが、ホストのALUAを使用して、LIF経由でLUNにアクセスするための適切なパスを選択します。

HAペアのノードごとにiSCSIパスを1つ以上作成し、HAペアで処理するLUNに論理インターフェイス（LIF）を使用してアクセスできるように構成する必要があります。SANをサポートするStorage Virtual Machine（SVM）ごとに管理LIFを1つ設定する必要があります。

直接接続またはイーサネット スイッチを使用した接続がサポートされています。どちらのタイプの接続でも、LIFを作成する必要があります。

* SANをサポートするStorage Virtual Machine（SVM）ごとに管理LIFを1つ設定する必要があります。ノードあたり2つのLIFを設定できます。LIFは、iSCSI用のイーサネット ネットワークと分離するために、FCで使用するファブリックごとに1つ必要になります。


LIFが作成されたら、ポートセットから削除したり、Storage Virtual Machine（SVM）内の別のノードに移動したり、LIFそのものを削除したりすることができます。

.関連情報
* link:../networking/configure_lifs_cluster_administrators_only_overview.html#lif-failover-and-giveback["LIFの設定 - 概要"]
* link:../networking/create_a_lif.html["LIFの作成"]

