---
permalink: san-admin/microsoft-offloaded-data-transfer-odx-concept.html 
sidebar: sidebar 
keywords: microsoft, offloaded, data, transfer, odx 
summary: Microsoft Offloaded Data Transfer（ODX）（コピー オフロードとも呼ばれます）を使用すると、ホスト コンピューター経由でデータを転送せずに、ストレージ デバイス内または互換性のあるストレージ デバイス間で直接データを転送できます。 
---
= Microsoftオフロード データ転送（ODX）
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Microsoft Offloaded Data Transfer（ODX）は、_copy offload_ とも呼ばれ、ホスト コンピューター経由でデータを転送せずに、ストレージ デバイス内または互換性のあるストレージ デバイス間で直接データを転送することを可能にします。

VMwareとMicrosoftは、パフォーマンスとネットワーク スループットを向上させるために、コピー オフロード処理をサポートしています。コピー オフロード機能を使用するためには、VMwareとWindowsそれぞれのオペレーティング システム環境の要件を満たすようにシステムを構成する必要があります。

VMwareとMicrosoftのコピー オフロードを仮想環境で使用する場合は、LUNをアライメントする必要があります。LUNがアライメントされていないと、パフォーマンスが低下する可能性があります。link:io-misalignments-properly-aligned-luns-concept.html["非整列LUNの詳細"]。

ONTAPでは、SMBプロトコルとSANプロトコルの両方でODXをサポートしています。

ODX以外のファイル転送では、ソースからデータが読み取られ、ネットワーク経由でホストに転送されます。ホストは、データをネットワーク経由でデスティネーションに転送します。ODXファイル転送では、ホストを経由せずに、データがソースからデスティネーションに直接コピーされます。

ODXオフロード コピーはソースとデスティネーションの間で直接実行されるため、コピーが同じボリューム内で行われるとパフォーマンスが大幅に向上します。実現するパフォーマンスの向上には、同じボリュームでのコピー時間の短縮、クライアントでのCPUとメモリの使用量の削減、ネットワークI/O帯域幅の使用量の削減などが挙げられます。複数のボリュームにまたがってコピーを実行する場合は、ホストベースのコピーの場合ほど大幅にはパフォーマンスが向上しない可能性があります。

SAN環境でODXを使用できるのは、ホストとストレージ システムの両方でODXがサポートされている場合のみです。ODXがサポートされていて有効になっているクライアント コンピュータでは、ファイルの移動やコピーを行う際に、オフロード ファイル転送が自動的かつ透過的に使用されます。ODXは、ファイルをエクスプローラでドラッグ アンド ドロップしたか、コマンドラインのファイル コピー コマンドを使用したか、クライアント アプリケーションによってファイル コピー要求が開始されたかに関係なく使用されます。



== ODXの使用要件

コピー オフロードにODXを使用する場合は、ボリュームのサポートに関する考慮事項、システム要件、およびソフトウェア機能の要件について理解しておく必要があります。

ODXを使用するためのシステム要件は次のとおりです。

* ONTAP
+
サポート対象のバージョンのONTAPでは、ODXが自動的に有効になります。

* ソース ボリュームの最小サイズ：2GB
+
最適なパフォーマンスを確保するには、260GB以上のソース ボリュームが必要です。

* WindowsクライアントでのODXのサポート
+
ODXは、Windows Server 2012以降およびWindows 8以降でサポートされます。サポート対象のWindowsクライアントの最新情報については、Interoperability Matrixを参照してください。

+
https://mysupport.netapp.com/matrix["NetApp Interoperability Matrix Tool"^]

* コピー アプリケーションによるODXのサポート
+
データ転送を実行するアプリケーションがODXをサポートする必要があります。ODXがサポートされるアプリケーション処理は次のとおりです。

+
** 仮想ハードディスク（VHD）の作成と変換、スナップショットの管理、仮想マシン間のファイルのコピーなどのHyper-V管理操作
** エクスプローラ操作
** Windows PowerShellコピーコマンド
** Windows コマンド プロンプトのコピー コマンド Microsoft TechNet ライブラリには、Windows サーバーおよびクライアントでサポートされている ODX アプリケーションに関する詳細情報が含まれています。


* 圧縮されたボリュームを使用する場合は、圧縮グループ サイズを8Kにする必要があります。
+
32Kの圧縮グループ サイズはサポートされていません。



ODXを次のタイプのボリュームで使用することはできません。

* 容量が2GB未満のソース ボリューム
* 読み取り専用ボリューム
* link:../flexcache/supported-unsupported-features-concept.html["FlexCacheボリューム"]
+

NOTE: ODXはFlexCacheの元のボリュームでサポートされます。

* link:../san-admin/san-volumes-concept.html#semi-thick-provisioning-for-volumes["セミシックプロビジョニングされたボリューム"]




== 特殊なシステム ファイルの要件

qtree内のODXファイルは削除できます。テクニカルサポートから指示がない限り、その他のODXシステムファイルは削除または変更しないでください。

ODX機能を使用する場合、システムのすべてのボリュームにODXシステムファイルが存在します。これらのファイルにより、ODX転送中に使用されるデータのポイントインタイム表現が可能になります。以下のシステムファイルは、データがオフロードされたLUNまたはファイルを含む各ボリュームのルートレベルにあります：

* `.copy-offload`（隠しディレクトリ）
* `.tokens`（非表示の `.copy-offload`ディレクトリ下のファイル）


 `copy-offload delete-tokens -path dir_path -node _node_name_`コマンドを使用して、ODXファイルを含むqtreeを削除できます。



== ODXの使用事例

SVMでODXを使用する前にユースケースについて確認し、どのような場合にパフォーマンスが向上するかを判断できるようにしておく必要があります。

ODXをサポートするWindowsサーバおよびクライアントでは、リモート サーバ間でデータをコピーする際に、デフォルトでコピー オフロードが使用されます。WindowsサーバおよびクライアントでODXがサポートされていない場合や、ODXコピー オフロードが任意の時点で失敗した場合は、コピーまたは移動処理が従来の読み取りと書き込みの処理を使用して実行されます。

ODXコピーおよび移動の使用は、以下の事例でサポートされます。

* ボリューム内
+
ソースとデスティネーションのファイルまたはLUNは、同じボリューム内にあります。

* ボリュームが異なり、ノードとSVMは同じ
+
ソースとデスティネーションのファイルまたはLUNは、同じノード上の異なるボリュームにあります。データは同じSVMに所有されます。

* ボリュームとノードが異なり、SVMは同じ
+
ソースとデスティネーションのファイルまたはLUNは、異なるノード上の異なるボリュームにあります。データは同じSVMに所有されます。

* SVMが異なり、ノードは同じ
+
ソースとデスティネーションのファイルまたはLUNは、同じノード上の異なるボリュームにあります。データは異なるSVMに所有されます。

* SVMとノードが異なる
+
ソースとデスティネーションのファイルまたはLUNは、異なるノード上の異なるボリュームにあります。データは異なるSVMに所有されます。

* クラスタ間
+
ソースとデスティネーションのLUNは、異なるクラスタの異なるノード上の異なるボリュームにあります。これはSANでのみサポートされ、SMBでは機能しません。



さらに、いくつかの特殊なユースケースがあります。

* ONTAPのODXの実装では、ODXを使用してSMB共有とFC / iSCSI接続の仮想ドライブとの間でファイルをコピーできます。
+
Windowsエクスプローラ、Windows CLI（PowerShell）、Hyper-V、またはODXをサポートするその他のアプリケーションでODXコピー オフロードを使用すると、SMB共有と接続されたLUNが同じクラスタにある場合に、それらの間でシームレスにファイルをコピーまたは移動できます。

* Hyper-Vでは、さらに次のようなユースケースでもODXコピー オフロードが使用されます。
+
** Hyper-VでODXコピー オフロードのパススルーを使用して、仮想ハード ディスク（VHD）ファイル内およびVHDファイル間でのデータのコピー、または同じクラスタ内のマッピングされたSMB共有と接続されたiSCSI LUNの間でのデータのコピーを実行できます。
+
これにより、ゲスト オペレーティング システムからのコピーを基盤となるストレージに渡すことができます。

** 容量固定VHDを作成する際に、ODXを使用して、既知の初期化済みトークンによってディスクを初期化します。
** ソースとデスティネーションのストレージが同じクラスタにある場合に、ODXコピー オフロードを使用して、仮想マシンのストレージを移行します。


+
[NOTE]
====
Hyper-VでのODXコピー オフロードのパススルーの用途を活用するには、ゲスト オペレーティング システムでODXがサポートされている必要があります。また、ゲスト オペレーティング システムのディスクが、ODXをサポートするストレージ（SMBまたはSAN）から作成されたSCSIディスクである必要があります。ゲスト オペレーティング システムのディスクがIDEディスクの場合、ODXのパススルーはサポートされません。

====

