---
permalink: san-admin/modify-slm-reporting-nodes-task.html 
sidebar: sidebar 
keywords: modify, slm, reporting-nodes, list 
summary: LUN または LUN が含まれているボリュームを同じクラスタ内の別のハイアベイラビリティ（ HA ）ペアに移動する場合は、移動を開始する前に選択的 LUN マップ（ SLM ）のレポートノードリストを変更して、最適化されたアクティブな LUN パスを維持する必要があります。 
---
= SLM レポートノードリストを変更します
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
LUN または LUN が含まれているボリュームを同じクラスタ内の別のハイアベイラビリティ（ HA ）ペアに移動する場合は、移動を開始する前に選択的 LUN マップ（ SLM ）のレポートノードリストを変更して、最適化されたアクティブな LUN パスを維持する必要があります。

.手順
. デスティネーションノードとそのパートナーノードをアグリゲートまたはボリュームのレポートノードリストに追加します。
+
`lun mapping add-reporting-nodes -vserver _vserver_name_ -path _lun_path_ -igroup _igroup_name_ [-destination-aggregate _aggregate_name_|-destination-volume _volume_name_]`

+
一貫性のある命名規則がある場合は、を使用して、複数のLUNマッピングを同時に変更できます `*-igroup*` ではなく `igroup`。

. ホストを再スキャンして、新しく追加したパスを検出します。
. OS で必要な場合は、マルチパスネットワーク I/O （ MPIO ）構成に新しいパスを追加します。
. 必要な移動処理のためのコマンドを実行して、処理が完了するまで待ちます。
. I/O がアクティブパスまたは最適パス経由で処理されていることを確認します。
+
`lun mapping show -fields reporting-nodes`

. レポートノードリストから、前の LUN 所有者とそのパートナーノードを削除します。
+
`lun mapping remove-reporting-nodes -vserver _vserver_name_ -path _lun_path_ -igroup _igroup_name_ -remote-nodes`

. 既存の LUN マップから LUN が削除済みであることを確認します。
+
`lun mapping show -fields reporting-nodes`

. ホスト OS の古いデバイスのエントリを削除します。
. 必要に応じて、マルチパス構成ファイルを変更します。
. ホストを再スキャンして古いパスが削除されたことを確認します。+ ホストを再スキャンする手順については、ホストのマニュアルを参照してください。

