---
permalink: san-admin/nvme-namespaces-considerations-concept.html 
sidebar: sidebar 
keywords: nvme, namespaces, considerations, provisioning 
summary: SAN 環境で NVMe プロトコルをセットアップするには、 NVMe 用の SVM を設定し、ネームスペースとサブシステムを作成し、 NVMe/FC LIF を設定し、ネームスペースをサブシステムにマッピングする必要があります。 
---
= NVMe ネームスペースに関する考慮事項
:icons: font
:imagesdir: ../media/


[role="lead"]
SAN 環境で NVMe プロトコルをセットアップするには、 NVMe 用の SVM を設定し、ネームスペースとサブシステムを作成し、 NVMe/FC LIF を設定し、ネームスペースをサブシステムにマッピングする必要があります。NVMe ネームスペースを使用する場合は、一定の考慮事項に注意する必要があります。

* LUN のデータが失われた場合、ネームスペースからリストアすることはできません。また、その逆も同様です。
* ネームスペースのスペースギャランティはそれを含むボリュームのスペースギャランティと同じになります。
* ONTAP 9.6 以降では、ネームスペースで 512 バイトブロックと 4096 バイトブロックがサポートされます。
+
デフォルト値は 4096 です。ホストオペレーティングシステムで 4096 バイトブロックがサポートされていない場合のみ、 512 を使用してください。

* ネームスペースでは、次のものはサポートされません。
+
** 名前変更中です
+
ネームスペースの名前は変更できません。

** サイズ変更中です
+
ネームスペースのサイズは増やすことも減らすこともできません。

** ボリューム間での移動
** ボリューム間でのコピー






== NVMe ネームスペースについて

NVMe ネームスペースは、論理ブロックにフォーマット可能な不揮発性メモリ（ NVM ）の容量です。ネームスペースは、 Storage Virtual Machine で NVMe プロトコルが設定されている場合に使用され、 FC および iSCSI プロトコルの LUN に相当します。

NVMe ホストには、 1 つ以上のネームスペースがプロビジョニングされて接続されます。各ネームスペースがさまざまなブロックサイズをサポートできます。

NVMe プロトコルは、複数のコントローラ経由でネームスペースへのアクセスを提供します。ほとんどのオペレーティングシステムでサポートされている NVMe ドライバを使用すると、 Solid State Drive （ SSD ；ソリッドステートドライブ）ネームスペースは標準ブロックデバイスとして表示され、そのままでファイルシステムとアプリケーションを導入できます。

ネームスペース ID （ NSID ）は、コントローラがネームスペースへのアクセスを提供するために使用する識別子です。ホストまたはホストグループに対して NSID を設定する場合は、ホストからボリュームへのアクセスも設定します。論理ブロックは一度に 1 つのホストグループにのみマッピングでき、同じホストグループに複数の NSID が割り当てられることはありません。



=== NVMe ネームスペースの NVMe サブシステムのプロビジョニング

NVMe サブシステムには、 1 つ以上の NVMe コントローラ、ネームスペース、 NVM サブシステムポート、 NVM ストレージメディア、およびコントローラと NVM ストレージメディア間のインターフェイスが含まれます。NVMe ネームスペースを作成する際、 NVMe サブシステムをネームスペースにマッピングする方法を次の中から選択できます。

* * なし（デフォルト） * + NVMe サブシステムはネームスペースにマッピングされません。
* * 既存のサブシステム * + 既存の NVMe サブシステムを選択してネームスペースにマッピングできます。NVMe サブシステムはホスト OS と SVM のフィールドに基づいて表示されます。NVMe サブシステムの名前にポインタを合わせると、サブシステムに関する詳細が表示されます。
* * 新しいサブシステム * + を使用すると、新しい NVMe サブシステムを作成してネームスペースにマッピングできます。ホスト OS と SVM にサブシステムが作成されます。


サブシステムをプロビジョニングするには、次の詳細情報を指定します。

* * NVMe サブシステム名 * + NVMe サブシステム名では大文字と小文字が区別されます。1~96 文字で指定する必要があり、特殊文字を使用できます。
* * ホスト OS * + サブシステムの作成先のホスト OS タイプ。
* * ホスト NQN * + コントローラに接続されたホスト NVMe 修飾名。サブシステムには複数のホストを接続できるため、この列では値をカンマで区切って指定できます。

