---
permalink: san-admin/prevent-flexclone-file-lun-deleted-task.html 
sidebar: sidebar 
keywords: prevent, specific, flexclone file, flexclone lun, automatically, deleted 
summary: FlexClone ファイルおよび FlexClone LUN を自動的に削除するように FlexVol を設定すると、指定した条件を満たすすべてのクローンが削除される可能性があります。特定の FlexClone ファイルまたは FlexClone LUN を残したい場合は、それらを FlexClone の自動削除プロセスから除外できます。 
---
= 特定の FlexClone ファイルまたは FlexClone LUN を自動削除の対象から除外します
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
FlexClone ファイルおよび FlexClone LUN を自動的に削除するように FlexVol を設定すると、指定した条件を満たすすべてのクローンが削除される可能性があります。特定の FlexClone ファイルまたは FlexClone LUN を残したい場合は、それらを FlexClone の自動削除プロセスから除外できます。

.必要なもの
FlexClone ライセンスがインストールされている必要があります。

.このタスクについて
FlexClone ファイルまたは FlexClone LUN を作成すると、クローンの自動削除設定がデフォルトで無効になります。自動削除を無効にした FlexClone ファイルと FlexClone LUN は、ボリュームのスペースを再生するためにクローンを自動的に削除するように FlexVol を設定しても保持されます。

[NOTE]
====
を設定した場合は `commitment` ボリュームのレベルをに設定します `try` または `disrupt`特定のFlexCloneファイルまたはFlexClone LUNを個別に保持するには、それらのクローンの自動削除を無効にします。ただし、を設定した場合 `commitment` ボリュームのレベルをに設定します `destroy` 削除リストには次のものが含まれます `lun_clone,file_clone`では、ボリューム設定はクローン設定よりも優先され、クローンの自動削除設定に関係なく、すべてのFlexCloneファイルとFlexClone LUNが削除されます。

====
.手順
. を使用して、特定のFlexCloneファイルまたはFlexClone LUNを自動的に削除しないように設定します `volume file clone autodelete` コマンドを実行します
+
次の例は、 vol1 に含まれている FlexClone LUN lun1_clone の自動削除を無効にする方法を示しています。

+
[listing]
----
cluster1::> volume file clone autodelete -vserver vs1 -volume vol1 -clone-path lun1_clone -enable false
----
+
自動削除を無効にした FlexClone ファイルまたは FlexClone LUN は、ボリュームのスペース再生を目的とした自動削除の対象になりません。

. を使用して、FlexCloneファイルまたはFlexClone LUNで自動削除が無効になっていることを確認します `volume file clone show-autodelete` コマンドを実行します
+
次の例では、 FlexClone LUN lun1_clone の自動削除が false になっています。

+
[listing]
----
cluster1::> volume file clone show-autodelete -vserver vs1 -clone-path vol/vol1/lun1_clone
															Vserver Name: vs1
															Clone Path: vol/vol1/lun1_clone
															Autodelete Enabled: false
----

