---
permalink: san-admin/requirements-odx-concept.html 
sidebar: sidebar 
keywords: microsoft Offloaded Data Transfer, using, odx 
summary: コピーオフロードに ODX を使用する場合は、ボリュームのサポートに関する考慮事項、システム要件、およびソフトウェア機能の要件について理解しておく必要があります。 
---
= ODX を使用するための要件
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
コピーオフロードに ODX を使用する場合は、ボリュームのサポートに関する考慮事項、システム要件、およびソフトウェア機能の要件について理解しておく必要があります。

ODX を使用するためのシステム要件は次のとおりです。

* ONTAP
+
サポート対象のバージョンの ONTAP では、 ODX が自動的に有効になります。

* ソースボリュームの最小サイズは 2GB です
+
最適なパフォーマンスを確保するには、 260GB 以上のソースボリュームが必要です。

* 重複排除
+
ODX では、コピープロセスの一部として重複排除が実行されます。SVM で重複排除が発生しないようにする場合は、その SVM で ODX を無効にする必要があります。

* Windows クライアントでの ODX のサポート
+
ODX は、 Windows Server 2012 以降および Windows 8 以降でサポートされます。サポート対象の Windows クライアントの最新情報については、 Interoperability Matrix を参照してください。

+
https://["NetApp Interoperability Matrix Tool で確認できます"^]

* コピーアプリケーションによる ODX のサポート
+
データ転送を実行するアプリケーションが ODX をサポートする必要があります。ODX がサポートされるアプリケーション処理は次のとおりです。

+
** Virtual Hard Disk （ VHD ；仮想ハードディスク）の作成および変換、 Snapshot コピーの管理、仮想マシン間でのファイルのコピーなど、 Hyper-V の管理処理
** エクスプローラでの操作
** Windows PowerShell の copy コマンド
** Windows コマンドプロンプトのコピーコマンド Microsoft TechNet ライブラリに、 Windows サーバおよびクライアントでサポートされている ODX アプリケーションの詳細が記載されている。


* 圧縮されたボリュームを使用する場合は、圧縮グループサイズを 8K にする必要があります。
+
32K の圧縮グループサイズはサポートされていません。



ODX を次のタイプのボリュームで使用することはできません。

* 容量が 2GB 未満のソースボリューム
* 読み取り専用ボリューム
* link:../flexcache/supported-unsupported-features-concept.html["FlexCache ボリューム"]
* link:../san-admin/san-volumes-concept.html#semi-thick-provisioning-for-volumes["セミシックプロビジョニングされたボリューム"]

