---
permalink: san-admin/resolve-iscsi-error-messages-reference.html 
sidebar: sidebar 
keywords: resolve, iscsi, error messages, storage system 
summary: event log show コマンドを使用して確認できる、 iSCSI 関連のいくつかの一般的なエラーメッセージがあります。これらのメッセージの意味と、特定された問題の解決方法を把握する必要があります。 
---
= ストレージシステム上の iSCSI エラーメッセージを解決します
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
iSCSI関連の一般的なエラーメッセージは、で確認できます `event log show` コマンドを実行しますこれらのメッセージの意味と、特定された問題の解決方法を把握する必要があります。

次の表に、最も一般的なエラーメッセージと、それらを解決する手順を示します。

[cols="3*"]
|===
| メッセージ | 説明 | 対処方法： 


 a| 
`ISCSI: network interface identifier disabled for use; incoming connection discarded`
 a| 
このインターフェイスの iSCSI サービスが有効になっていません。
 a| 
を使用できます `iscsi interface enable` コマンドを実行してインターフェイスでiSCSIサービスを有効にします。例：

`iscsi interface enable -vserver vs1 -lif lif1`



 a| 
`ISCSI: Authentication failed for initiator nodename`
 a| 
指定されたイニシエータに対して CHAP が正しく設定されていません。
 a| 
CHAP 設定をチェックします。ストレージシステムのインバウンド設定とアウトバウンド設定には、同じユーザ名およびパスワードを使用できません。

* ストレージシステムのインバウンドクレデンシャルは、イニシエータのアウトバウンドクレデンシャルと一致する必要があります
* ストレージシステムのアウトバウンドクレデンシャルは、イニシエータのインバウンドクレデンシャルと一致する必要があります


|===