---
permalink: san-admin/restore-single-lun-snapshot-copy-task.html 
sidebar: sidebar 
keywords: restore, single lun, snapshot copy 
summary: スナップショットから単一のLUNを復元できます。そのLUNを含むボリューム全体を復元する必要はありません。LUNは、ボリューム内の既存の場所または新しいパスに復元できます。この操作では、ボリューム内の他のファイルやLUNに影響を与えることなく、単一のLUNのみが復元されます。ストリームを含むファイルを復元することもできます。 
---
= ONTAPスナップショットから単一のLUNを復元する
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
スナップショットから単一のLUNを復元できます。そのLUNを含むボリューム全体を復元する必要はありません。LUNは、ボリューム内の既存の場所または新しいパスに復元できます。この操作では、ボリューム内の他のファイルやLUNに影響を与えることなく、単一のLUNのみが復元されます。ストリームを含むファイルを復元することもできます。

.開始する前に
* 復元操作を完了するには、ボリュームに十分な空き容量が必要です：
+
** フラクショナル リザーブが0%のスペース リザーブLUNをリストアする場合、リストアするLUNと同じサイズのスペースが必要です。
** フラクショナル リザーブが100%のスペース リザーブLUNをリストアする場合、リストアするLUNの2倍のサイズのスペースが必要です。
** スペース リザーブなしのLUNをリストアする場合、リストアするLUNが実際に使用しているサイズのスペースのみが必要です。


* デスティネーション LUN のスナップショットが作成されている必要があります。
+
復元操作が失敗した場合、復元先のLUNが切り捨てられる可能性があります。このような場合は、Snapshotを使用してデータ損失を防ぐことができます。

* ソース LUN のスナップショットが作成されている必要があります。
+
稀に、LUNの復元に失敗し、ソースLUNが使用できなくなる場合があります。このような場合は、スナップショットを使用して、LUNを復元試行直前の状態に戻すことができます。

* デスティネーション LUN とソース LUN の OS タイプは同じである必要があります。
+
復元先 LUN の OS タイプが復元元 LUN と異なる場合、復元操作後にホストは復元先 LUN へのデータ アクセスを失う可能性があります。



.手順
. ホストから、LUNへのすべてのホスト アクセスを停止します。
. ホストが LUN にアクセスできないように、ホスト上の LUN をアンマウントします。
. LUNのマッピングを解除します。
+
[source, cli]
----
lun mapping delete -vserver <SVM_name> -volume <volume_name> -lun <lun_name> -igroup <igroup_name>
----
. LUN を復元するスナップショットを決定します：
+
[source, cli]
----
volume snapshot show -vserver <SVM_name> -volume <volume_name>
----
. LUN を復元する前に、LUN のスナップショットを作成します：
+
[source, cli]
----
volume snapshot create -vserver <SVM_name> -volume <volume_name> -snapshot <snapshot_name>
----
. ボリューム内の指定されたLUNを復元します：
+
[source, cli]
----
volume snapshot restore-file -vserver <SVM_name> -volume <volume_name> -snapshot <snapshot_name> -path <lun_path>
----
. 画面上の手順に従います。
. 必要に応じて、LUNをオンラインにします。
+
[source, cli]
----
lun modify -vserver <SVM_name> -path <lun_path> -state online
----
. 必要に応じて、LUNを再マッピングします。
+
[souce]
----
lun mapping create -vserver <SVM_name> -volume <volume_name> -lun <lun_name> -igroup <igroup_name>
----
. ホストからLUNを再マウントします。
. ホストから LUN へのアクセスを再開します。

