---
permalink: san-admin/restore-single-lun-snapshot-copy-task.html 
sidebar: sidebar 
keywords: restore, single lun, snapshot copy 
summary: ボリューム全体をリストアすることなく、Snapshotから単一のLUNをリストアすることができます。LUN は、元の場所またはボリューム内の新しいパスにリストアできます。この処理では、ボリューム内の他のファイルまたは LUN に影響を与えることなく、単一の LUN だけがリストアされます。ファイルは、ストリームを使用してリストアすることもできます。 
---
= Snapshotからの単一LUNのリストア
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
ボリューム全体をリストアすることなく、Snapshotから単一のLUNをリストアすることができます。LUN は、元の場所またはボリューム内の新しいパスにリストアできます。この処理では、ボリューム内の他のファイルまたは LUN に影響を与えることなく、単一の LUN だけがリストアされます。ファイルは、ストリームを使用してリストアすることもできます。

.必要なもの
* リストア処理を完了するには、ボリュームに十分なスペースが必要です。
+
** フラクショナルリザーブが0%のスペースリザーブLUNをリストアする場合は、リストアするLUNの1倍のサイズが必要です。
** フラクショナルリザーブが100%のスペースリザーブLUNをリストアする場合は、リストアするLUNの2倍のサイズが必要です。
** スペースリザーブなしのLUNをリストアする場合は、リストアするLUNで実際に使用されているスペースのみが必要です。


* デスティネーションLUNのSnapshotを作成しておく必要があります。
+
リストア処理が失敗すると、デスティネーション LUN が切り捨てられる可能性があります。このような場合は、Snapshotを使用してデータの損失を防ぐことができます。

* ソースLUNのスナップショットを作成しておく必要があります。
+
まれに、 LUN のリストアに失敗したときに、ソース LUN が使用不能になることがあります。この場合は、Snapshotを使用して、リストアを試みる直前の状態にLUNを戻すことができます。

* デスティネーション LUN とソース LUN の OS タイプが同じである必要があります。
+
デスティネーション LUN の OS タイプがソース LUN の OS タイプと異なる場合は、リストア処理後、ホストからデスティネーション LUN へのデータアクセスが失われる可能性があります。



.手順
. ホストから、 LUN へのホストアクセスをすべて停止します。
. ホスト上の LUN をアンマウントして、ホストが LUN にアクセスできないようにします。
. LUNのマッピングを解除します。
+
`lun mapping delete -vserver _vserver_name_ -volume _volume_name_ -lun _lun_name_ -igroup _igroup_name_`

. LUNのリストア先となるSnapshotを決定します。
+
`volume snapshot show -vserver _vserver_name_ -volume _volume_name_`

. LUNをリストアする前に、LUNのSnapshotを作成します。
+
`volume snapshot create -vserver _vserver_name_ -volume _volume_name_ -snapshot _snapshot_name_`

. ボリューム内の指定した LUN をリストアします。
+
`volume snapshot restore-file -vserver _vserver_name_ -volume _volume_name_ -snapshot _snapshot_name_ -path _lun_path_`

. 画面の手順に従います。
. 必要に応じて、LUNをオンラインにします。
+
`lun modify -vserver _vserver_name_ -path _lun_path_ -state online`

. 必要に応じて、LUNを再マッピングします。
+
`lun mapping create -vserver _vserver_name_ -volume _volume_name_ -lun _lun_name_ -igroup _igroup_name_`

. ホストから、 LUN を再マウントします。
. ホストから、 LUN へのアクセスを再開します。

