---
permalink: san-admin/restore-all-luns-volume-snapvault-backup-task.html 
sidebar: sidebar 
keywords: restore, luns, in a volume, snapvault, backup 
summary: ボリューム内の1つ以上のLUNをSnapVaultバックアップから復元する必要がある場合は、ボリューム全体を復元できます。ボリュームの復元は、ボリューム内のすべてのLUNに影響します。 
---
= ONTAP SnapVaultバックアップからボリューム内のすべてのLUNを復元する
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
ボリューム内の1つ以上のLUNをSnapVaultバックアップから復元する必要がある場合は、ボリューム全体を復元できます。ボリュームの復元は、ボリューム内のすべてのLUNに影響します。

.開始する前に
SnapVault関係を初期化する必要があり、SnapVaultセカンダリ ボリュームには復元する適切なスナップショットが含まれている必要があります。

.タスク概要
ボリューム全体を復元すると、ボリュームはスナップショット作成時の状態に戻ります。スナップショット後にボリュームにLUNが追加された場合、そのLUNは復元プロセス中に削除されます。

ボリュームをリストアした後も、LUNはリストア直前にマッピングされていたigroupにマッピングされたままです。LUNのマッピングは、スナップショット時のマッピングと異なる場合があります。ホストクラスタからのLUNの永続的な予約は保持されます。

.手順
. ボリューム内のすべての LUN への I/O を停止します。
. SnapVault セカンダリ ボリュームを含むセカンダリ ボリュームを確認します。
+
[source, cli]
----
snapmirror show
----
+
[listing]
----
cluster::> snapmirror show

Source         Dest     Mirror  Relation  Total             Last
Path     Type  Path     State   Status    Progress  Healthy Updated
-------- ---- --------- ------- --------- --------- ------- -------
vserverA:srcvolA
         XDP  vserverB:dstvolB
                        Snapmirrored
                                Idle       -         true    -
----
. 復元するスナップショットを特定します。
+
[source, cli]
----
volume snapshot show
----
+
[listing]
----
cluster::> volume snapshot show

Vserver  Volume  Snapshot               State Size   Total% Used%
-------- ------- ---------------------- ----- ------ ------ -----
vserverB
         dstvolB
                 snap2.2013-02-10_0010  valid  124KB     0%    0%
                 snap1.2013-02-10_0015 valid  112KB     0%    0%
                 snap2.2013-02-11_0010  valid  164KB     0%    0%
----
. 使用するSnapshotを指定します。
+
[source, cli]
----
snapmirror restore -destination-path <destination_path> -source-path <source_path> -source-snapshot <snapshot_name>
----
+
復元に指定する宛先は、復元先の元のボリュームです。

+
[listing]
----
cluster::> snapmirror restore -destination-path vserverA:srcvolA
  -source-path vserverB:dstvolB -source-snapshot daily.2013-02-10_0010

Warning: All data newer than Snapshot copy hourly.2013-02-11_1205 on
volume vserverA:src_volA will be deleted.
Do you want to continue? {y|n}: y
[Job 98] Job is queued: snapmirror restore from source
"vserverB:dstvolB" for the snapshot daily.2013-02-10_0010.
----
. ホスト クラスター全体で LUN を共有している場合は、影響を受けるホストから LUN の永続的な予約を復元します。




== SnapVaultバックアップからボリュームを復元する

次の例では、スナップショットの作成後に lun_D という LUN がボリュームに追加されました。スナップショットからボリューム全体を復元すると、lun_D は表示されなくなります。

 `lun show`コマンド出力には、プライマリ ボリューム srcvolA 内の LUN と、それらの LUN の読み取り専用コピーがSnapVault セカンダリ ボリューム dstvolB にあることが表示されます。SnapVault バックアップには lun_D のコピーは存在しません。

[listing]
----
cluster::> lun show
Vserver   Path                State   Mapped   Type          Size
--------- ------------------  ------- -------- --------      -------
vserverA  /vol/srcvolA/lun_A  online  mapped   windows  300.0GB
vserverA  /vol/srcvolA/lun_B  online  mapped   windows  300.0GB
vserverA  /vol/srcvolA/lun_C  online  mapped   windows  300.0GB
vserverA  /vol/srcvolA/lun_D  online  mapped   windows  250.0GB
vserverB  /vol/dstvolB/lun_A  online  unmapped windows  300.0GB
vserverB  /vol/dstvolB/lun_B  online  unmapped windows  300.0GB
vserverB  /vol/dstvolB/lun_C  online  unmapped windows  300.0GB

7 entries were displayed.

cluster::>snapmirror restore -destination-path vserverA:srcvolA
  -source-path vserverB:dstvolB
  -source-snapshot daily.2013-02-10_0010

Warning: All data newer than snapshot hourly.2013-02-11_1205
on volume vserverA:src_volA will be deleted.
Do you want to continue? {y|n}: y
[Job 98] Job is queued: snapmirror restore from source
"vserverB:dstvolB" for the snapshot daily.2013-02-10_0010.

cluster::> lun show
Vserver   Path                State   Mapped   Type          Size
--------- ------------------  ------- -------- --------      -------
vserverA  /vol/srcvolA/lun_A  online  mapped   windows  300.0GB
vserverA  /vol/srcvolA/lun_B  online  mapped   windows  300.0GB
vserverA  /vol/srcvolA/lun_C  online  mapped   windows  300.0GB
vserverB  /vol/dstvolB/lun_A  online  unmapped windows  300.0GB
vserverB  /vol/dstvolB/lun_B  online  unmapped windows  300.0GB
vserverB  /vol/dstvolB/lun_C  online  unmapped windows  300.0GB

6 entries were displayed.
----
SnapVault セカンダリ ボリュームからボリュームがリストアされた後、ソース ボリュームには lun_D が含まれなくなります。リストア後もソース ボリュームの LUN はマッピングされたままなので、再マッピングする必要はありません。

.関連情報
* link:https://docs.netapp.com/us-en/ontap-cli/snapmirror-restore.html["snapmirror restore"^]
* link:https://docs.netapp.com/us-en/ontap-cli/snapmirror-show.html["snapmirror show"^]

