---
permalink: san-admin/san-provisioning-nvme-concept.html 
sidebar: sidebar 
keywords: san, provisioning, nvme 
summary: ONTAP 9.4 以降では、 SAN 環境で NVMe/FC がサポートされます。NVMe/FC では、 FC および iSCSI で LUN をプロビジョニングして igroup にマッピングするのと同様に、ネームスペースとサブシステムをプロビジョニングし、ネームスペースをサブシステムにマッピングすることができます。 
---
= NVMe を使用した SAN プロビジョニング
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
ONTAP 9.4 以降では、 SAN 環境で NVMe/FC がサポートされます。NVMe/FC では、 FC および iSCSI で LUN をプロビジョニングして igroup にマッピングするのと同様に、ネームスペースとサブシステムをプロビジョニングし、ネームスペースをサブシステムにマッピングすることができます。

NVMe ネームスペースは、論理ブロックにフォーマット可能な不揮発性メモリの容量です。ネームスペースは FC および iSCSI プロトコルの LUN に相当し、 NVMe サブシステムは igroup に相当します。NVMe サブシステムはイニシエータに関連付けることができ、これにより関連付けられたイニシエータからサブシステム内のネームスペースにアクセスできるようになります。

[NOTE]
====
NVMe ネームスペースは、機能的には LUN に似ていますが、 LUN でサポートされるすべての機能がサポートされるわけではあり

====
ONTAP 9.5 以降では、 NVMe を使用したホスト側のデータアクセスをサポートするにはライセンスが必要です。ONTAP 9.4 で NVMe が有効になっている場合、 ONTAP 9.5 へのアップグレード後に 90 日間の猶予期間中にライセンスを取得する必要があります。ライセンスを有効にするには、次のコマンドを使用します。

「 system license add -license-code_nvme_license_key_` 」というエラーが表示されます

.関連情報
http://www.netapp.com/us/media/tr-4684.pdf["ネットアップテクニカルレポート 4684 ：『 Implementing and Configuring Modern SANs with NVMe/FC 』"]
