---
permalink: san-admin/transition-config-concept.html 
sidebar: sidebar 
keywords: considerations, transitioning, san, configurations, capabilities, restrictions, transitioned, luns 
summary: SAN 環境では、 7-Mode ボリュームを ONTAP に移行する際にサービスの中断が必要です。移行を完了するには、ホストをシャットダウンする必要があります。移行後は、ホスト構成を更新してから、 ONTAP でデータの提供を開始する必要があります。 
---
= SAN 構成の移行に関する考慮事項
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
SAN 環境では、 7-Mode ボリュームを ONTAP に移行する際にサービスの中断が必要です。移行を完了するには、ホストをシャットダウンする必要があります。移行後は、ホスト構成を更新してから、 ONTAP でデータの提供を開始する必要があります

ホストをシャットダウンできる時間帯にメンテナンスのスケジュールを設定して、移行を完了する必要があります。



== 移行した LUN の機能と制限

Data ONTAP 7-Mode から ONTAP に移行された LUN には、 LUN の管理方法に影響を及ぼす特定の機能と制限があります。

移行した LUN では、次の操作を実行できます。

* lun show コマンドを使用して、 LUN を表示します
* 「 transition 7-mode show 」コマンドを使用して、 7-Mode ボリュームから移行した LUN のインベントリを表示します
* 7-Mode Snapshot コピーからボリュームをリストアします
+
ボリュームをリストアすると、 Snapshot コピーにキャプチャされたすべての LUN が移行されます

* 「 snapshot-restore-file 」コマンドを使用して、 7-Mode Snapshot コピーから単一の LUN をリストアします
* 7-Mode Snapshot コピー内の LUN のクローンを作成します
* 7-Mode Snapshot コピーにキャプチャされた LUN から特定の範囲のブロックをリストアする
* 7-Mode Snapshot コピーを使用して、ボリュームの FlexClone を作成します


移行した LUN では、次の操作を実行することはできません。

* ボリューム内にキャプチャされた Snapshot コピーでバックアップされた LUN クローンにアクセスします


link:https://docs.netapp.com/us-en/ontap-7mode-transition/copy-based/index.html["コピーベースの移行"]
