---
permalink: san-admin/troubleshoot-iscsi-luns-not-visible-reference.html 
sidebar: sidebar 
keywords: troubleshoot, iscsi luns, not visible, host 
summary: iSCSI LUNは、ホストではローカルディスクとして表示されます。ストレージシステムのLUNをホストでディスクとして使用できない場合は、構成設定を確認する必要があります。 
---
= ホストでiSCSI LUNが表示されない場合のトラブルシューティング
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
iSCSI LUNは、ホストではローカルディスクとして表示されます。ストレージシステムのLUNをホストでディスクとして使用できない場合は、構成設定を確認する必要があります。

[cols="1, 3"]
|===
| 構成設定 | 対処方法： 


 a| 
ケーブル接続
 a| 
ホストとストレージシステムの間のケーブルが正しく接続されていることを確認します。



 a| 
ネットワーク接続
 a| 
ホストとストレージシステムの間にTCP / IP接続が確立されていることを確認します。

* ストレージシステムのコマンドラインから、iSCSIに使用されているホストインターフェイスをpingします。
+
`ping –node _node_name_ -destination _host_ip_address_for_iSCSI_`

* ホストのコマンドラインから、iSCSIに使用されているストレージシステムインターフェイスをpingします。
+
`ping –node _node_name_ -destination _host_ip_address_for_iSCSI_`





 a| 
システム要件
 a| 
構成のコンポーネントが認定されていることを確認します。また、ホストオペレーティングシステム（OS）のサービスパックレベル、イニシエータバージョン、ONTAPバージョンなどのシステム要件を満たしていることも確認してください。Interoperability Matrixに最新のシステム要件が記載されています。



 a| 
ジャンボフレーム
 a| 
ご使用の構成でジャンボフレームを使用している場合は、ネットワークパス（ホストのイーサネットNIC、ストレージシステム、スイッチ）上のすべてのデバイスでジャンボフレームが有効になっていることを確認します。



 a| 
iSCSIサービスステータス
 a| 
iSCSIサービスのライセンスが設定され、ストレージシステムで開始されていることを確認します。



 a| 
イニシエータログイン
 a| 
イニシエータがストレージシステムにログインしていることを確認します。ログインしているイニシエータがコマンド出力に表示されない場合は `iscsi initiator show`、ホストのイニシエータ設定を確認します。また、ストレージシステムがイニシエータのターゲットとして設定されていることを確認します。



 a| 
iSCSIノード名（IQN）
 a| 
正しいイニシエータのノード名をigroup設定で使用していることを確認します。ホストでは、イニシエータのツールとコマンドを使用してイニシエータのノード名を表示できます。igroupおよびホストに設定されているイニシエータのノード名が一致している必要があります。



 a| 
LUNマツヒンク
 a| 
LUNがigroupにマッピングされていることを確認します。ストレージシステムコンソールでは、次のいずれかのコマンドを使用できます。

* `lun mapping show`すべてのLUN、およびLUNがマッピングされているigroupを表示します。
* `lun mapping show -igroup`特定のigroupにマッピングされているLUNを表示します。




 a| 
iSCSI LIFの有効化
 a| 
iSCSI論理インターフェイスが有効になっていることを確認します。

|===
.関連情報
* https://mysupport.netapp.com/matrix["NetApp Interoperability Matrix Tool"^]
* link:https://docs.netapp.com/us-en/ontap-cli/lun-mapping-show.html["lun mapping show"^]

