---
permalink: san-admin/volume-config-options-concept.html 
sidebar: sidebar 
keywords: san, volume, configuration, options 
summary: LUN が含まれているボリュームに対してさまざまなオプションを設定する必要があります。ボリュームオプションの設定方法によって、ボリューム内の LUN で使用可能なスペースの量が決まります。 
---
= SAN ボリュームの構成オプション
:icons: font
:imagesdir: ../media/


[role="lead"]
LUN が含まれているボリュームに対してさまざまなオプションを設定する必要があります。ボリュームオプションの設定方法によって、ボリューム内の LUN で使用可能なスペースの量が決まります。



== 自動拡張

自動拡張は有効または無効にすることができます。有効にすると、 ONTAP では、ボリュームのサイズを事前設定した最大サイズまで自動的に拡張できます。ボリュームの自動拡張をサポートするには、使用可能なスペースを包含アグリゲートに確保する必要があります。そのため、自動拡張を有効にする場合は、包含アグリゲートの空きスペースを監視し、必要に応じて追加してください。

自動拡張は、 Snapshot の作成時にはトリガーできません。自動拡張が有効になっていても、ボリュームに十分なスペースがないと Snapshot の作成は失敗します。

自動拡張が無効な場合、ボリュームのサイズに変更はありません。



== 自動縮小

自動縮小は有効または無効にすることができます。有効にすると、 ONTAP では、ボリュームで消費されたスペースの量が事前設定したしきい値を下回った場合に、ボリューム全体のサイズを自動的に縮小できます。これにより、ボリュームで未使用の空きスペースの自動的な解放が開始されて、ストレージ効率が向上します。



== Snapshot の自動削除

Snapshot の自動削除では、次のいずれかの場合に、 Snapshot コピーが自動的に削除されます。

* ボリュームがフルに近い状態の場合
* Snapshot リザーブスペースがフルに近い状態の場合
* オーバーライトリザーブスペースがフルの場合


古いものから順に、または新しいものから順に Snapshot コピーを削除するように Snapshot の自動削除を設定できます。Snapshot の自動削除では、クローンボリュームや LUN 内の Snapshot コピーにリンクされている Snapshot コピーは削除されません。

自動拡張と Snapshot の自動削除の両方が有効な場合にボリュームで追加のスペースが必要になると、デフォルトでは、 ONTAP は最初に自動拡張をトリガーして、必要なスペースを確保しようとします。自動拡張で十分なスペースを確保できない場合は、 Snapshot の自動削除がトリガーされます。



== Snapshot リザーブ

Snapshot リザーブは、 Snapshot コピー用にリザーブされるボリューム内のスペースの量を定義します。Snapshot リザーブに割り当てられたスペースを他の目的に使用することはできません。Snapshot リザーブ用に割り当てられたすべてのスペースが使用された場合、 Snapshot コピーはボリューム上の追加スペースを消費します。
