---
permalink: smb-config/commands-manage-ntp-servers-reference.html 
sidebar: sidebar 
keywords: ontap, network, time, protocol, ntp, version, support, ntpv3, symmetric, authentication, sha, security, commands for managing symmetric authentication on ntp servers 
summary: ONTAP 9 .5以降では、ネットワークタイムプロトコル（NTP）バージョン3がサポートされます。NTPv3にはSHA-1キーを使用した対称認証が含まれているため、ネットワークセキュリティが向上します。 
---
= NTPサーバの対称認証の管理用コマンド
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
ONTAP 9 .5以降では、ネットワークタイムプロトコル（NTP）バージョン3がサポートされます。NTPv3にはSHA-1キーを使用した対称認証が含まれているため、ネットワークセキュリティが向上します。

|===
| 作業 | 使用するコマンド 


 a| 
対称認証を使用せずにNTPサーバを設定する
 a| 
`cluster time-service ntp server create` `-server` `server_name`



 a| 
対称認証を使用してNTPサーバを設定する
 a| 
`cluster time-service ntp server create` `-server` `server_ip_address` `-key-id` `key_id`



 a| 
既存のNTPサーバの対称認証を有効にする必要なキーIDを追加することで、既存のNTPサーバを変更して認証を有効にすることができます。
 a| 
`cluster time-service ntp server modify` `-server` `server_name` `-key-id` `key_id`



 a| 
共有NTPキーを設定する
 a| 
`cluster time-service ntp key create` `-id` `shared_key_id` `-type` `shared_key_type` `-value` `shared_key_value`

[NOTE]
====
共有キーはIDで参照されます。ID、そのタイプ、および値がノードとNTPサーバの両方で同じである必要があります。

====


 a| 
不明なキーIDでNTPサーバを設定する
 a| 
`cluster time-service ntp server create` `-server` `server_name` `-key-id` `key_id`



 a| 
NTPサーバで設定されていないキーIDでサーバを設定します。
 a| 
`cluster time-service ntp server create` `-server` `server_name` `-key-id` `key_id`

[NOTE]
====
キーID、タイプ、および値は、NTPサーバに設定されているキーID、タイプ、および値と同じである必要があります。

====


 a| 
対称認証を無効にする
 a| 
`cluster time-service ntp server modify` `-server` `server_name` `-authentication disabled`

|===