---
permalink: smb-config/create-volume-task.html 
sidebar: sidebar 
keywords: create, volume, junction, point, properties, property, command, create a volume 
summary: volume create コマンドを使用して、ボリュームを作成し、ジャンクションポイントやその他のプロパティを指定できます。 
---
= ボリュームを作成します
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
を使用して、ボリュームを作成し、ジャンクションポイントやその他のプロパティを指定できます `volume create` コマンドを実行します

.作業を開始する前に
SVM のセキュリティ形式は NTFS である必要があります。また、 SMB が設定されて実行されている必要があります。

.このタスクについて
クライアントがデータを使用できるようにするには、ボリュームに _junction path_ を含める必要があります。ジャンクションパスは、新しいボリュームを作成するときに指定できます。ジャンクションパスを指定せずにボリュームを作成する場合は、を使用してSVMネームスペースにボリュームを_mount_する必要があります `volume mount` コマンドを実行します

.手順
. ジャンクションポイントを指定してボリュームを作成します。 `volume create -vserver vserver_name -volume volume_name -aggregate aggregate_name -size {integer[KB|MB|GB|TB|PB]} -security-style ntfs -junction-path junction_path]`
+
の選択 `-junction-path` 次のようなものがあります。

+
** ルートの直下。例： `/new_vol`
+
新しいボリュームを作成し、 SVM のルートボリュームに直接マウントされるように指定することができます。

** 既存のディレクトリの下（例： `/existing_dir/new_vol`
+
新しいボリュームを作成し、ディレクトリとして表現されている既存のボリューム（既存の階層内）にマウントされるように指定できます。



+
新しいディレクトリ（新しいボリュームの下の新しい階層）にボリュームを作成する場合は、次のように指定します。 `/new_dir/new_vol`その後、SVMルートボリュームにジャンクションされた新しい親ボリュームを作成しておく必要があります。その後、新しい親ボリューム（新しいディレクトリ）のジャンクションパスに新しい子ボリュームを作成します。

. 目的のジャンクションポイントでボリュームが作成されたことを確認します。 `volume show -vserver vserver_name -volume volume_name -junction`


.例
次のコマンドは、 SVM vs1.example.com およびアグリゲート aggr1 上に、 users1 という名前の新しいボリュームを作成します。新しいボリュームは、で使用できます `/users`。ボリュームのサイズは 750GB で、ボリュームギャランティのタイプは volume （デフォルト）です。

[listing]
----
cluster1::> volume create -vserver vs1.example.com -volume users -aggregate aggr1 -size 750g -junction-path /users
[Job 1642] Job succeeded: Successful

cluster1::> volume show -vserver vs1.example.com -volume users -junction
                          Junction                 Junction
Vserver           Volume  Active   Junction Path   Path Source
----------------- ------- -------- --------------- -----------
vs1.example.com   users1  true     /users          RW_volume
----
次のコマンドでは、「 home4` 」という名前の新しいボリュームを SVM 「 vs1.example.com`" 」およびアグリゲート「 aggr1 」に作成します。ディレクトリ `/eng/` はvs1 SVMのネームスペースにすでに存在し、新しいボリュームはで使用できるようになります `/eng/home`をクリックします。これがのホームディレクトリになります `/eng/` ネームスペース：ボリュームのサイズは750GBで、ボリュームギャランティのタイプはです `volume` （デフォルト）。

[listing]
----
cluster1::> volume create -vserver vs1.example.com -volume home4 -aggregate aggr1 -size 750g -junction-path /eng/home
[Job 1642] Job succeeded: Successful

cluster1::> volume show -vserver vs1.example.com -volume home4 -junction
                         Junction                 Junction
Vserver          Volume  Active   Junction Path   Path Source
---------------- ------- -------- --------------- -----------
vs1.example.com  home4   true     /eng/home       RW_volume
----