---
permalink: smb-config/create-share-access-control-lists-task.html 
sidebar: sidebar 
keywords: configure, configuring, share, permission, create, access, control, list, acl, smb, enable, level, access, user, group, create smb share access control lists 
summary: SMB共有のAccess Control List（ACL;アクセス制御リスト）を作成して共有権限を設定すると、ユーザとグループの共有に対するアクセス レベルを制御できます。 
---
= ONTAP SMB共有アクセス制御リストを作成する
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
SMB共有のAccess Control List（ACL;アクセス制御リスト）を作成して共有権限を設定すると、ユーザとグループの共有に対するアクセス レベルを制御できます。

.開始する前に
共有へのアクセスを許可するユーザーまたはグループを決定する必要があります。

.タスク概要
ローカルまたはドメインのWindowsユーザまたはグループ名を使用して共有レベルのACLを設定できます。

新しいACLを作成する前に、セキュリティ上のリスクがあるデフォルトの共有ACL `Everyone / Full Control`を削除する必要があります。

ワークグループ モードでは、ローカル ドメイン名はSMBサーバ名です。

.手順
. デフォルトの共有 ACL を削除します：``vserver cifs share access-control delete -vserver _vserver_name_ -share _share_name_ -user-or-group everyone``
. 新しいACLを設定します。
+
|===
| ...を使用してACLを構成する場合は、... | コマンドを入力してください... 


 a| 
Windowsユーザ
 a| 
`vserver cifs share access-control create -vserver _vserver_name_ -share _share_name_ -user-group-type windows -user-or-group _Windows_domain_name\\user_name_ -permission access_right`



 a| 
Windowsグループ
 a| 
`vserver cifs share access-control create -vserver _vserver_name_ -share _share_name_ -user-group-type windows -user-or-group _Windows_group_name_ -permission access_right`

|===
.  `vserver cifs share access-control show`コマンドを使用して、共有に適用されたACLが正しいことを確認します。


.例
次のコマンドは、「`vs1.example.com`」SVM 上の「`sales`」共有に対する `Change`権限を「`Sales Team`」Windows グループに付与します：

[listing]
----
cluster1::> vserver cifs share access-control create -vserver vs1.example.com -share sales -user-or-group "Sales Team" -permission Change

cluster1::> vserver cifs share access-control show
                 Share       User/Group              User/Group  Access
Vserver          Name        Name                    Type        Permission
---------------- ----------- --------------------    ---------   -----------
vs1.example.com  c$          BUILTIN\Administrators  windows     Full_Control
vs1.example.com  sales       DOMAIN\"Sales Team"     windows     Change
----
次のコマンドは、「`Tiger Team`」という名前のローカル Windows グループに `Change`権限を付与し、「`Sue Chang`」という名前のローカル Windows ユーザーに `Full_Control`権限を付与します（「`vs1`」SVM 上の「`datavol5`」共有）：

[listing]
----
cluster1::> vserver cifs share access-control create -vserver vs1 -share datavol5 -user-group-type windows -user-or-group "Tiger Team" -permission Change

cluster1::> vserver cifs share access-control create -vserver vs1 -share datavol5 -user-group-type windows -user-or-group "Sue Chang" -permission Full_Control

cluster1::> vserver cifs share access-control show -vserver vs1
               Share       User/Group                  User/Group  Access
Vserver        Name        Name                        Type        Permission
-------------- ----------- --------------------------- ----------- -----------
vs1            c$          BUILTIN\Administrators      windows     Full_Control
vs1            datavol5    DOMAIN\"Tiger Team"         windows     Change
vs1            datavol5    DOMAIN\"Sue Chang"          windows     Full_Control
----