---
permalink: smb-config/create-svms-data-access-task.html 
sidebar: sidebar 
keywords: svm, cluster, data, access, smb, client, create, create an svm 
summary: クラスタ内にSMBクライアントにデータ アクセスを提供するSVMが1つもない場合は、作成する必要があります。 
---
= SMBデータアクセスを提供するためのONTAP SVMを作成する
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
クラスタ内にSMBクライアントにデータ アクセスを提供するSVMが1つもない場合は、作成する必要があります。

.開始する前に
* ONTAP 9.13.1以降では、ストレージVMの最大容量を設定できます。また、SVMの容量がしきい値に近づいた場合にアラートを設定することもできます。詳細については、xref:../volumes/manage-svm-capacity.html[SVMの容量の管理]を参照してください。


.手順
. SVM を作成します。 `vserver create -vserver _svm_name_ -rootvolume _root_volume_name_ -aggregate _aggregate_name_ -rootvolume-security-style ntfs -language C.UTF-8 -ipspace _ipspace_name_`
+
**  `-rootvolume-security-style`オプションには NTFS 設定を使用します。
** デフォルトの C.UTF-8 `-language` オプションを使用します。
**  `ipspace`設定はオプションです。


. 新しく作成された SVM の構成とステータスを確認します： `vserver show -vserver _vserver_name_`
+
 `Allowed Protocols`フィールドには CIFS を含める必要があります。このリストは後で編集できます。

+
 `Vserver Operational State`フィールドには `running`状態が表示される必要があります。 `initializing`状態が表示される場合、ルート ボリュームの作成などの中間操作が失敗したことを意味し、SVMを削除して再作成する必要があります。



.例
次のコマンドは、IPspace `ipspaceA`内のデータ アクセス用の SVM を作成します：

[listing]
----
cluster1::> vserver create -vserver vs1.example.com -rootvolume root_vs1 -aggregate aggr1
-rootvolume-security-style ntfs -language C.UTF-8 -ipspace ipspaceA

[Job 2059] Job succeeded:
Vserver creation completed
----
次のコマンドは、1GBのルートボリュームを持つSVMが作成され、自動的に起動されて `running`状態になっていることを示しています。ルートボリュームにはルールが含まれていないデフォルトのエクスポート ポリシーが適用されているため、作成時にルートボリュームはエクスポートされません。

[listing]
----
cluster1::> vserver show -vserver vs1.example.com
                                    Vserver: vs1.example.com
                               Vserver Type: data
                            Vserver Subtype: default
                               Vserver UUID: b8375669-19b0-11e5-b9d1-00a0983d9736
                                Root Volume: root_vs1
                                  Aggregate: aggr1
                                 NIS Domain: -
                 Root Volume Security Style: ntfs
                                LDAP Client: -
               Default Volume Language Code: C.UTF-8
                            Snapshot Policy: default
                                    Comment:
                               Quota Policy: default
                List of Aggregates Assigned: -
 Limit on Maximum Number of Volumes allowed: unlimited
                        Vserver Admin State: running
                  Vserver Operational State: running
   Vserver Operational State Stopped Reason: -
                          Allowed Protocols: nfs, cifs, fcp, iscsi, ndmp
                       Disallowed Protocols: -
                           QoS Policy Group: -
                                Config Lock: false
                               IPspace Name: ipspaceA
----

NOTE: ONTAP 9.13.1以降では、アダプティブQoSポリシーグループテンプレートを設定して、SVM内のボリュームにスループットの下限と上限を適用できます。このポリシーは、SVMを作成した後にのみ適用できます。このプロセスの詳細については、xref:../performance-admin/adaptive-policy-template-task.html[アダプティブ ポリシー グループ テンプレートの設定]を参照してください。
