---
permalink: smb-config/create-server-workgroup-task.html 
sidebar: sidebar 
keywords: vserver, cifs, create, command, smb, server, workgroup, create an smb server in a workgroup 
summary: vserver cifs create コマンドを使用して、SVM 上に SMB サーバを作成し、そのサーバが属するワークグループを指定できます。 
---
= 指定されたワークグループを持つ ONTAP SVM 上に SMB サーバを作成します
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
 `vserver cifs create`コマンドを使用して、SVM 上に SMB サーバを作成し、そのサーバが属するワークグループを指定できます。

.開始する前に
データ処理に使用しているSVMおよびLIFが、SMBプロトコルを許可するように設定されている必要があります。LIFは、SVM上で設定されているDNSサーバに接続できる必要があります。

.タスク概要
ワークグループ モードのSMBサーバでは、次のSMB機能はサポートされません。

* SMB3監視プロトコル
* SMB3 CA共有
* SQL over SMB
* フォルダ リダイレクト
* 移動プロファイル
* グループ ポリシー オブジェクト（GPO）
* ボリュームSnapshotサービス（VSS）


 `vserver cifs`とオプションの構成パラメータおよび命名要件の詳細については、link:https://docs.netapp.com/us-en/ontap-cli/search.html?q=vserver+cifs["ONTAPコマンド リファレンス"^]を参照してください。

.手順
. クラスタで SMB のライセンスが付与されていることを確認します。 `system license show -package cifs`
+
SMB ライセンスはlink:../system-admin/manage-licenses-concept.html#licenses-included-with-ontap-one["ONTAP One"]に含まれています。ONTAP One をお持ちでなく、ライセンスがインストールされていない場合は、営業担当者にお問い合わせください。

+
SMBサーバを認証のみに使用する場合は、CIFSライセンスは必要ありません。

. ワークグループに SMB サーバを作成します： `vserver cifs create -vserver vserver_name -cifs-server cifs_server_name -workgroup workgroup_name [-comment text]`
+
次のコマンドは、ワークグループ "`workgroup01`" に SMB サーバー "`smb_server01`" を作成します：

+
[listing]
----
cluster1::> vserver cifs create -vserver vs1.example.com -cifs-server SMB_SERVER01 -workgroup workgroup01
----
.  `vserver cifs show`コマンドを使用して SMB サーバ構成を確認します。
+
次の例では、コマンド出力に、"`smb_server01`" という名前の SMB サーバが SVM vs1.example.com のワークグループ "`workgroup01`" に作成されたことが示されています：

+
[listing]
----
cluster1::> vserver cifs show -vserver vs0

                                          Vserver: vs1.example.com
                         CIFS Server NetBIOS Name: SMB_SERVER01
                    NetBIOS Domain/Workgroup Name: workgroup01
                      Fully Qualified Domain Name: -
                              Organizational Unit: -
Default Site Used by LIFs Without Site Membership: -
                                   Workgroup Name: workgroup01
                             Authentication Style: workgroup
                CIFS Server Administrative Status: up
                          CIFS Server Description:
                          List of NetBIOS Aliases: -
----


.終了後の操作
ワークグループ内のCIFSサーバに関しては、SVM上でローカル ユーザ、およびオプションでローカル グループを作成する必要があります。

.関連情報
link:../smb-admin/index.html["SMBの管理"]
