---
permalink: smb-config/create-volume-task.html 
sidebar: sidebar 
keywords: create, volume, junction, point, properties, property, command, create a volume 
summary: volume create コマンドを使用して、ボリュームを作成し、ジャンクションポイントやその他のプロパティを指定できます。 
---
= ボリュームの作成
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
コマンドを使用すると、ボリュームを作成し、ジャンクションポイントやその他のプロパティを指定できます `volume create`。

.タスクの内容
クライアントがデータを使用できるようにするには、ボリュームに _junction path_ を含める必要があります。ジャンクションパスは、新しいボリュームの作成時に指定できます。ジャンクションパスを指定せずにボリュームを作成する場合は、コマンドを使用して、SVMネームスペースでボリュームを_mount_theにする必要があります `volume mount`。

.開始する前に
* SMBがセットアップされて実行されている必要があります。
* SVMのセキュリティ形式はNTFSである必要があります。
* ONTAP 9.13.1以降では、容量分析とアクティビティ追跡を有効にしてボリュームを作成できます。容量またはアクティビティの追跡を有効にするには、を指定してコマンドを `-analytics-state`実行する `volume create`か、 `-activity-tracking-state`に設定します `on`。
+
容量分析とアクティビティ追跡の詳細については、を参照してください https://docs.netapp.com/us-en/ontap/task_nas_file_system_analytics_enable.html["ファイルシステム分析を有効にする"]。



.手順
. ジャンクションポイントを設定してボリュームを作成します。 `volume create -vserver _svm_name_ -volume _volume_name_ -aggregate _aggregate_name_ -size {integer[KB|MB|GB|TB|PB]} -security-style ntfs -junction-path _junction_path_]`
+
の選択肢は `-junction-path`次のとおりです。

+
** ルートの直下。例： `/new_vol`
+
新しいボリュームを作成し、 SVM のルートボリュームに直接マウントされるように指定することができます。

** 既存のディレクトリの下（例： `/existing_dir/new_vol`
+
新しいボリュームを作成し、ディレクトリとして表現されている既存のボリューム（既存の階層内）にマウントされるように指定できます。



+
たとえば、新しいディレクトリ（新しいボリュームの下の新しい階層）にボリュームを作成する場合は `/new_dir/new_vol`、SVMのルートボリュームにジャンクションされている新しい親ボリュームを最初に作成する必要があります。その後、新しい親ボリューム（新しいディレクトリ）のジャンクションパスに新しい子ボリュームを作成します。

. 目的のジャンクションポイントでボリュームが作成されたことを確認します。 `volume show -vserver _svm_name_ -volume _volume_name_ -junction`


.例
次のコマンドは、 SVM vs1.example.com およびアグリゲート aggr1 上に、 users1 という名前の新しいボリュームを作成します。新しいボリュームは、で使用でき `/users`ます。ボリュームのサイズは750GBで、ボリュームギャランティのタイプはvolume（デフォルト）です。

[listing]
----
cluster1::> volume create -vserver vs1.example.com -volume users -aggregate aggr1 -size 750g -junction-path /users
[Job 1642] Job succeeded: Successful

cluster1::> volume show -vserver vs1.example.com -volume users -junction
                          Junction                 Junction
Vserver           Volume  Active   Junction Path   Path Source
----------------- ------- -------- --------------- -----------
vs1.example.com   users1  true     /users          RW_volume
----
次のコマンドでは、「 home4` 」という名前の新しいボリュームを SVM 「 vs1.example.com`" 」およびアグリゲート「 aggr1 」に作成します。ディレクトリは `/eng/`vs1 SVMのネームスペース内にすでに存在し、新しいボリュームがで使用可能になります `/eng/home`。これがネームスペースのホームディレクトリになります。 `/eng/`ボリュームのサイズは750GBで、ボリュームギャランティのタイプは（デフォルト）です `volume`。

[listing]
----
cluster1::> volume create -vserver vs1.example.com -volume home4 -aggregate aggr1 -size 750g -junction-path /eng/home
[Job 1642] Job succeeded: Successful

cluster1::> volume show -vserver vs1.example.com -volume home4 -junction
                         Junction                 Junction
Vserver          Volume  Active   Junction Path   Path Source
---------------- ------- -------- --------------- -----------
vs1.example.com  home4   true     /eng/home       RW_volume
----