---
permalink: smb-config/create-local-groups-task.html 
sidebar: sidebar 
keywords: create, local, group, authorize, authorizing, access, data, associate, svm, smb, connection, assign, privilege, define, right, capabilities, capability, member, create local groups 
summary: SMB接続を介してSVMに関連付けられたデータへのアクセスを承認するために使用できるローカル グループを作成できます。また、グループのメンバーに付与するユーザ権限や機能を定義する権限を割り当てることもできます。 
---
= ローカルONTAP SMBグループを作成する
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
SMB接続を介してSVMに関連付けられたデータへのアクセスを承認するために使用できるローカル グループを作成できます。また、グループのメンバーに付与するユーザ権限や機能を定義する権限を割り当てることもできます。

.タスク概要
SVM の作成時に、ローカル グループ機能がデフォルトで有効になります。

ローカル グループを作成する際は、グループ名と、グループを関連付ける SVM を指定する必要があります。グループ名はローカル ドメイン名の有無にかかわらず指定でき、必要に応じてローカル グループの説明も指定できます。ローカル グループを別のローカル グループに追加することはできません。

 `vserver cifs users-and-groups local-group`とオプション パラメータおよび命名要件の詳細については、link:https://docs.netapp.com/us-en/ontap-cli/search.html?q=vserver+cifs+users-and-groups+local-group["ONTAPコマンド リファレンス"^]を参照してください。

.手順
. ローカル グループを作成します： `vserver cifs users-and-groups local-group create -vserver vserver_name -group-name group_name`
+
次のオプション パラメータが役に立つ場合があります：

+
** `-description`
+
ローカル グループの説明を指定します。



. グループが正常に作成されたことを確認します： `vserver cifs users-and-groups local-group show -vserver vserver_name`


.例
次の例では、SVM vs1 に関連付けられたローカル グループ "`SMB_SERVER01\engineering`" を作成します：

[listing]
----
cluster1::> vserver cifs users-and-groups local-group create -vserver vs1.example.com -group-name SMB_SERVER01\engineering

cluster1::> vserver cifs users-and-groups local-group show -vserver vs1.example.com
Vserver          Group Name                   Description
---------------- ---------------------------- ----------------------------
vs1.example.com  BUILTIN\Administrators       Built-in Administrators group
vs1.example.com  BUILTIN\Backup Operators     Backup Operators group
vs1.example.com  BUILTIN\Power Users          Restricted administrative privileges
vs1.example.com  BUILTIN\Users                All users
vs1.example.com  SMB_SERVER01\engineering
vs1.example.com  SMB_SERVER01\sales
----
.終了後の操作
新しいグループにメンバーを追加する必要があります。
