---
permalink: smb-config/index.html 
sidebar: sidebar 
keywords:  
summary: ONTAP 9 の CLI コマンドを使用して、新規または既存の SVM の新しいボリュームまたは qtree に格納されているファイルへの SMB クライアントアクセスを設定できます。 
---
= CLIヲシヨウシタSMBセツテイノカイヨウ
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
ONTAP 9 の CLI コマンドを使用して、新規または既存の SVM の新しいボリュームまたは qtree に格納されているファイルへの SMB クライアントアクセスを設定できます。

[NOTE]
====
_SMB_(Server Message Block) は、 Common Internet File System (CIFS) プロトコルの最新のダイアレクトです。ONTAP コマンドラインインターフェイス（ CLI ）および OnCommand 管理ツールでは、 _cifs_という メッセージが引き続き表示されます。

====
次の手順に従って、ボリュームまたは qtree への SMB アクセスを設定します。

* SMB のバージョン 2 以降を使用する必要がある。
* NFS クライアントではなく、 SMB クライアントのみを対象とする（マルチプロトコル構成ではない）。
* 新しいボリュームはNTFSファイル権限を使用して保護されます。
* SVM 管理者権限ではなくクラスタ管理者権限を持っている。
+
SVM と LIF を作成するにはクラスタ管理者権限が必要です。他の SMB 設定タスクには、 SVM 管理者権限で十分です。

* System Manager や自動スクリプトツールではなく、 CLI を使用する。
+
System Manager を使用して NAS マルチプロトコルアクセスを設定するには、を参照してください link:https://docs.netapp.com/us-en/ontap/task_nas_provision_nfs_and_smb.html["NFS と SMB の両方を使用して Windows と Linux の両方に NAS ストレージをプロビジョニングする"]。

* すべての選択肢について検討するのではなく、ベストプラクティスに従う。
+
コマンド構文の詳細については、 CLI ヘルプおよび ONTAP のマニュアルページを参照してください。



ONTAP の SMB プロトコル機能の範囲の詳細については、を参照してください link:../smb-admin/index.html["SMB リファレンスの概要"]。



== ONTAP でこれを行うその他の方法

|===


| 実行するタスク | 参照先 


| 再設計された System Manager （ ONTAP 9.7 以降で使用可能） | link:../task_nas_provision_windows_smb.html["SMB を使用して Windows サーバ用の NAS ストレージをプロビジョニングする"] 


| System Manager Classic （ ONTAP 9.7 以前で使用可能） | link:https://docs.netapp.com/us-en/ontap-sm-classic/smb-config/index.html["SMBセツテイノカイヨウ"^] 
|===