---
permalink: smb-config/index.html 
sidebar: sidebar 
keywords:  
summary: ONTAP 9のCLIコマンドを使用して、新規または既存のSVMの新しいボリュームまたはqtreeに格納されているファイルへのSMBクライアント アクセスを設定することができます。 
---
= ONTAP CLI を使用した SMB 構成について学習します
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
ONTAP 9のCLIコマンドを使用して、新規または既存のSVMの新しいボリュームまたはqtreeに格納されているファイルへのSMBクライアント アクセスを設定することができます。

[NOTE]
====
_SMB_（Server Message Block）は、Common Internet File System（CIFS）プロトコルの最新の方言を指します。ONTAPコマンドライン インターフェイス（CLI）およびOnCommand管理ツールには、引き続き_CIFS_が表示されます。

====
ここで説明する手順は、ボリュームまたはqtreeへのSMBアクセスを設定する場合に使用します。想定している状況は次のとおりです。

* SMBのバージョン2以降を使用する必要がある。
* NFSクライアントではなく、SMBクライアントのみを対象とする（マルチプロトコル構成ではない）。
* 新しいボリュームをNTFSファイル権限を使用して保護する。
* SVM管理者権限ではなくクラスタ管理者権限を保有している。
+
SVMとLIFを作成するにはクラスタ管理者権限が必要です。その他のSMB構成タスクには、SVM管理者権限で十分です。

* System Managerや自動スクリプト ツールではなく、CLIを使用する必要がある。
+
System Manager を使用して NAS マルチプロトコルアクセスを構成するには、link:../task_nas_provision_nfs_and_smb.html["NFSとSMBの両方を使用したWindowsおよびLinux用のNASストレージのプロビジョニング"]を参照してください。

* すべての選択肢について検討するのではなく、ベストプラクティスに従う。
+
この手順で説明されているコマンドの詳細については、link:https://docs.netapp.com/us-en/ontap-cli/["ONTAPコマンド リファレンス"^]を参照してください。



ONTAP SMB プロトコル機能の範囲の詳細については、link:../smb-admin/index.html["SMBリファレンス - 概要"]を参照してください。



== ONTAPでこの処理を行うその他の方法

|===


| タスクを実行するツール | 参照先 


| 新しいSystem Manager（ONTAP 9.7以降で使用可能） | link:../task_nas_provision_windows_smb.html["SMBを使用したWindowsサーバ用のNASストレージのプロビジョニング"] 


| System Manager Classic（ONTAP 9.7以前で使用可能） | link:https://docs.netapp.com/us-en/ontap-system-manager-classic/smb-config/index.html["SMB 構成の概要"^] 
|===