---
permalink: smb-config/open-export-policy-svm-root-volume-task.html 
sidebar: sidebar 
keywords: default, export, policy, svm, root, volume, rule, client, smb, rule, open the export policy of the svm root volume 
summary: SVMルート ボリュームのデフォルトのエクスポート ポリシーには、すべてのクライアントにSMB経由のアクセスを許可するルールが含まれている必要があります。このようなルールを追加しないと、SVMとそのボリュームに対するSMBクライアントのアクセスがすべて拒否されます。 
---
= ONTAP SVMルートボリュームのSMBエクスポート ポリシーを開きます
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
SVMルート ボリュームのデフォルトのエクスポート ポリシーには、すべてのクライアントにSMB経由のアクセスを許可するルールが含まれている必要があります。このようなルールを追加しないと、SVMとそのボリュームに対するSMBクライアントのアクセスがすべて拒否されます。

.タスク概要
新しいSVMが作成されると、SVMのルート ボリュームに対してデフォルトのエクスポート ポリシー（default）が自動的に作成されます。クライアントがSVM上のデータにアクセスできるようにするには、デフォルトのエクスポート ポリシーにルールを1つ以上作成する必要があります。

デフォルトのエクスポート ポリシーですべてのSMBアクセスが許可されていることを確認してから、ボリュームまたはqtreeごとにカスタムのエクスポート ポリシーを作成して各ボリュームへのアクセスを制限します。

.手順
. 既存の SVM を使用している場合は、デフォルトのルート ボリュームのエクスポート ルールを確認します： `vserver export-policy rule show`
+
コマンド出力は次のようになります：

+
[listing]
----

cluster::> vserver export-policy rule show -vserver vs1.example.com -policyname default -instance

                                    Vserver: vs1.example.com
                                Policy Name: default
                                 Rule Index: 1
                            Access Protocol: cifs
Client Match Hostname, IP Address, Netgroup, or Domain: 0.0.0.0/0
                             RO Access Rule: any
                             RW Access Rule: any
User ID To Which Anonymous Users Are Mapped: 65534
                   Superuser Security Types: any
               Honor SetUID Bits in SETATTR: true
                  Allow Creation of Devices: true
----
+
オープン アクセスを許可するルールが存在する場合、このタスクは完了です。存在しない場合は、次のステップに進みます。

. SVM ルート ボリュームのエクスポート ルールを作成します。 `vserver export-policy rule create -vserver vserver_name -policyname default -ruleindex 1 -protocol cifs -clientmatch 0.0.0.0/0 -rorule any -rwrule any -superuser any`
.  `vserver export-policy rule show`コマンドを使用してルールの作成を確認します。


.結果
これで、SVMで作成されたすべてのボリュームまたはqtreeに、SMBクライアントからアクセスできるようになりました。
