---
permalink: smb-config/requirements-create-share-concept.html 
sidebar: sidebar 
keywords: creating, create, smb, share, requirement, path, properties, property, home, directories, directory, requirements and considerations for creating an smb share 
summary: SMB 共有を作成する前に、特にホームディレクトリに関して、共有パスと共有プロパティの要件を理解しておく必要があります。 
---
= SMB共有の作成に関する要件と考慮事項
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
SMB 共有を作成する前に、特にホームディレクトリに関して、共有パスと共有プロパティの要件を理解しておく必要があります。

SMB共有を作成するには、クライアントがアクセスするディレクトリパス構造を（コマンドのオプションを `vserver cifs share create`使用して）指定する必要があり `-path`ます。ディレクトリパスは、 SVM ネームスペース内に作成したボリュームまたは qtree のジャンクションパスに相当します。ディレクトリパスと対応するジャンクションパスは、共有を作成する前に存在している必要があります。

共有パスには次の要件があります。

* ディレクトリパス名の最大文字数は255文字です。
* パス名にスペースが含まれている場合は、文字列全体を引用符で囲む必要があります（例： `"/new volume/mount here"`）。
* (`\\servername\sharename\filepath`共有のUNCパスの文字数が256文字を超えている場合（UNCパスの先頭のは除く）、Windowsの[プロパティ]ボックスの*[セキュリティ]*タブは使用できません。
+
これは、ONTAPの問題ではなく、Windowsクライアントの問題です。この問題を回避するには、UNCパスが256文字を超える共有を作成しないでください。



共有プロパティのデフォルト値は変更できます。

* すべての共有のデフォルトの初期プロパティは `oplocks`、、 `browsable`、 `changenotify`および `show-previous-versions`です。
* 共有の作成時、共有プロパティの指定はオプションです。
+
ただし、共有の作成時に共有プロパティを指定した場合、デフォルト値は使用されません。共有の作成時にパラメータを使用する場合 `-share-properties`は、共有に適用するすべての共有プロパティをカンマで区切って指定する必要があります。

* ホームディレクトリ共有を指定するには、プロパティを使用し `homedirectory`ます。
+
この機能を使用すると、接続するユーザと一連の変数に基づいてさまざまなディレクトリにマッピングされる共有を設定できます。ユーザごとに別個の共有を作成する必要はありません。 1 つの共有を設定し、いくつかのホームディレクトリパラメータを指定して、エントリポイント（共有）とユーザのホームディレクトリ（ SVM 上のディレクトリ）間のユーザの関係を定義します。

+
[NOTE]
====
共有の作成後にこのプロパティを追加または削除することはできません。

====


ホームディレクトリの共有には次の要件があります。

* SMBホームディレクトリを作成する前に、コマンドを使用して、ホームディレクトリ検索パスを少なくとも1つ追加する必要があります `vserver cifs home-directory search-path add`。
* パラメータの `-share-properties`値をに指定するホームディレクトリ共有で `homedirectory`は、（Windowsユーザ名）動的変数を共有名に含める必要があります `%w`。
+
共有名には、さらに（ドメイン名）動的変数（など `%d/%w`）を含めることも、静的な部分（など `home1_%w`）を含めることもできます `%d`。

* 管理者またはユーザが他のユーザのホームディレクトリに接続するために共有を使用する場合（コマンドのオプションを使用）は `vserver cifs home-directory modify`、動的な共有名のパターンの先頭にチルダを付ける必要があり(`~`ます。


link:../smb-admin/index.html["SMBの管理"]および `vserver cifs share`のマニュアルページに追加情報が記載されています。
