---
permalink: smb-config/verify-protocol-enabled-task.html 
sidebar: sidebar 
keywords: configure, smb, svm, verify, protocol, enable, verify that the smb protocol is enabled on the svm 
summary: SVM で SMB を設定して使用する前に、プロトコルが有効になっていることを確認する必要があります。 
---
= SVM で SMB プロトコルが有効になっていることを確認します
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
SVM で SMB を設定して使用する前に、プロトコルが有効になっていることを確認する必要があります。

これは通常、 SVM のセットアップ時に実行します。ただし、セットアップ時にプロトコルを有効にしなかった場合には、あとで vserver add-protocols コマンドを使用して、このプロトコルを有効にできます。

[NOTE]
====
作成したプロトコルは、 LIF から追加または削除することはできません。

====
vserver remove-protocols コマンドを使用して、 SVM 上のプロトコルを無効にすることもできます。

.手順
. SVM で現在有効になっているプロトコルと無効になっているプロトコルを確認します。 vserver show -vserver vserver_name -protocols
+
vserver show-protocols コマンドを使用して、クラスタ内のすべての SVM で現在有効になっているプロトコルを表示することもできます。

. 必要に応じて、プロトコルを有効または無効にします。
+
** SMB プロトコルを有効にするには、「 vserver add-protocols -vserver vserver_name -protocols cifs 」という形式になります
** プロトコルを無効にするには、「 + vserver remove-protocols -vserver vserver_name -protocols protocol_name [ 、 protocol_name 、 ...] + 」を入力します


. 有効なプロトコルと無効なプロトコルが正しく更新されたことを確認します。 vserver show -vserver vserver_name -protocols


次のコマンドは、 vs1 という SVM で現在有効 / 無効（許可 / 不許可）になっているプロトコルを表示します。

[listing]
----
vs1::> vserver show -vserver vs1.example.com -protocols
Vserver           Allowed Protocols         Disallowed Protocols
-----------       ----------------------    -----------------------
vs1.example.com   cifs                       nfs, fcp, iscsi, ndmp
----
次のコマンドは、 vs1 という SVM で有効になっているプロトコルのリストに「 cifs 」を追加することで、 SMB 経由のアクセスを許可します。

[listing]
----
vs1::> vserver add-protocols -vserver vs1.example.com -protocols cifs
----