---
permalink: disks-aggregates/assign-aggregates-svms-task.html 
sidebar: sidebar 
keywords: assign, aggregate, local tier, svm, storage vm, vserver 
summary: Storage Virtual Machine（Storage VMまたはSVM、旧Vserver）に1つ以上のローカル階層（アグリゲート）を割り当てた場合、そのSVMのボリュームはそれらのローカル階層にのみ含めることができます。A 
---
= ローカル階層（アグリゲート）をStorage VM（SVM）に割り当て
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Storage Virtual Machine（Storage VMまたはSVM、旧Vserver）に1つ以上のローカル階層（アグリゲート）を割り当てた場合、そのStorage VM（SVM）のボリュームを含めることができます。

.開始する前に
Storage VMとそのStorage VMに割り当てるローカル階層を用意しておく必要があります。

.タスクの内容
Storage VMにローカル階層を割り当てると、Storage VM同士の分離に役立ちます。これはマルチテナンシー環境で特に重要になります。

.手順
. SVMにすでに割り当てられているローカル階層（アグリゲート）のリストを確認します。
+
`vserver show -fields aggr-list`

+
SVMに現在割り当てられているアグリゲートが表示されます。割り当てられているアグリゲートがない場合はと表示されます。

. 要件に応じて、割り当てられているアグリゲートを追加または削除します。
+
|===


| 状況 | 使用するコマンド 


 a| 
追加のアグリゲートを割り当てる
 a| 
`vserver add-aggregates`



 a| 
アグリゲートの割り当てを解除する
 a| 
`vserver remove-aggregates`

|===
+
表示されているアグリゲートがSVMに割り当てられるか、SVMから削除されます。SVMに割り当てられていないアグリゲートを使用するボリュームがすでにSVMにある場合は、警告メッセージが表示されますが、コマンドは正常に完了します。SVMにすでに割り当てられているアグリゲートとコマンドで指定していないアグリゲートには影響はありません。



.例
次の例では、アグリゲートaggr1およびaggr2がSVM svm1に割り当てられます。

`vserver add-aggregates -vserver svm1 -aggregates aggr1,aggr2`
