---
permalink: disks-aggregates/commands-manage-aggregates-reference.html 
sidebar: sidebar 
keywords: commands, manage, aggregates 
summary: storage aggregate コマンドを使用して、アグリゲートを管理します。 
---
= アグリゲートの管理用コマンド
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
「 storage aggregate 」コマンドを使用して、アグリゲートを管理します。

|===
| 状況 | 使用するコマンド 


 a| 
すべての Flash Pool アグリゲートのキャッシュサイズを表示します
 a| 
「 storage aggregate show -fields hybrid-cache-size -total-hybrid-cache-size -total-size-sot合計 >0 」



 a| 
アグリゲートのディスクの情報とステータスを表示する
 a| 
「 storage aggregate show-status 」を参照してください



 a| 
ノードごとにスペアディスクを表示します
 a| 
「 storage aggregate show-spare-disks 」を参照してください



 a| 
クラスタ内のルートアグリゲートを表示する
 a| 
「 storage aggregate show -has-mroot true 」を返します



 a| 
アグリゲートの基本情報とステータスを表示します
 a| 
「 storage aggregate show



 a| 
アグリゲートで使用されているストレージのタイプを表示します
 a| 
「 storage aggregate show -fields storage-type 」を参照してください



 a| 
アグリゲートをオンラインにします
 a| 
「ストレージアグリゲートはオンライン」



 a| 
アグリゲートを削除します
 a| 
「 storage aggregate delete 」をクリックします



 a| 
アグリゲートを制限状態にします
 a| 
「ストレージアグリゲートの制限」を参照してください



 a| 
アグリゲートの名前を変更します
 a| 
「 storage aggregate rename 」をクリックします



 a| 
アグリゲートをオフラインにします
 a| 
「ストレージアグリゲートはオフライン」です



 a| 
アグリゲートの RAID タイプを変更します
 a| 
「 storage aggregate modify -raidtype 」

|===
http://docs.netapp.com/ontap-9/topic/com.netapp.doc.dot-cm-cmpr/GUID-5CB10C70-AC11-41C0-8C16-B4D0DF916E9B.html["ONTAP 9 のコマンド"]
