---
permalink: disks-aggregates/commands-manage-disks-reference.html 
sidebar: sidebar 
keywords: commands, manage, disks 
summary: storage disk コマンドと storage aggregate コマンドを使用して、ディスクを管理できます。 
---
= ディスクの管理用コマンドです
:icons: font
:imagesdir: ../media/


[role="lead"]
「 storage disk 」コマンドと「 storage aggregate 」コマンドを使用して、ディスクを管理できます。

[cols="2*"]
|===
| 状況 | 使用するコマンド 


 a| 
パーティショニングされたディスクを含むスペアディスクのリストを所有者別に表示します
 a| 
「 storage aggregate show-spare-disks 」を参照してください



 a| 
アグリゲートごとのディスクの RAID タイプ、現在の使用状況、および RAID グループを表示します
 a| 
「 storage aggregate show-status 」を参照してください



 a| 
スペアを含む RAID タイプ、現在の使用状況、アグリゲート、および RAID グループを表示する 物理ディスクの場合
 a| 
「 storage disk show -raid 」と表示されます



 a| 
障害が発生したディスクの一覧を表示します
 a| 
「 storage disk show -broken 」



 a| 
ディスクのクラスタ構成前の（ nodescope ）ドライブ名を表示する
 a| 
「 storage disk show -primary-paths 」（アドバンスト）



 a| 
特定のディスクまたはシェルフの LED を点灯します
 a| 
「ストレージ・ディスク・セット主導」



 a| 
特定のディスクに対するチェックサム方式を表示する
 a| 
「 storage disk show -fields checksum-compatibility 」を参照してください



 a| 
すべてのスペアディスクに対するチェックサム方式を表示する
 a| 
「 storage disk show -fields checksum-concompatibilion-container-type spare 」と表示されます



 a| 
ディスクの接続および配置の情報を表示します
 a| 
「 storage disk show -fields disk 、 primary-port 、 secondary-name 、 secondary-port 、 shelf 、 bay 」のように表示されます



 a| 
特定のディスクのクラスタ構成前のディスク名を表示する
 a| 
「 storage disk show -disk diskName -fields diskpathnames 」のように入力します



 a| 
Maintenance Center に割り当てられたディスクの一覧を表示する
 a| 
「 storage disk show -maintenance 」を選択します



 a| 
SSD の寿命を表示します
 a| 
「 storage disk show -ssd -wear 」を参照してください



 a| 
共有ディスクのパーティショニングを解除します
 a| 
「 storage disk unpartition 」（診断レベルで使用可能）



 a| 
初期化されていないすべてのディスクを初期化する
 a| 
「 storage disk zerospares 」と入力します



 a| 
指定した 1 つ以上のディスク上で進行中の完全消去プロセスを停止します
 a| 
「 system node run -node nodename command disk sanitize 」」というプロンプトが表示されます



 a| 
ストレージ暗号化に関するディスク情報を表示します
 a| 
「 storage encryption disk show 」のように表示されます



 a| 
リンクされたすべてのキー管理サーバから認証キーを取得します
 a| 
「セキュリティキーマネージャの復元」

|===
http://docs.netapp.com/ontap-9/topic/com.netapp.doc.dot-cm-cmpr/GUID-5CB10C70-AC11-41C0-8C16-B4D0DF916E9B.html["ONTAP 9 のコマンド"]
