---
permalink: disks-aggregates/commands-display-space-usage-reference.html 
sidebar: sidebar 
keywords: commands, display, space usage, information 
summary: storage aggregateコマンドとvolumeコマンドを使用して、ローカル層とボリューム、およびそれらのスナップショットでスペースがどのように使用されているかを確認します。 
---
= スペース使用情報を表示するための ONTAP コマンド
:hardbreaks:
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
 `storage aggregate`および `volume`コマンドを使用して、ローカル階層とボリューム、およびそれらのSnapshotでスペースがどのように使用されているかを確認します。


NOTE: ONTAP 9.7より前のバージョンでは、System Managerは_ローカル階層_を説明するために_aggregate_という用語を使用しています。ONTAPバージョンに関係なく、ONTAP CLIでは_aggregate_という用語が使用されます。ローカル階層の詳細については、link:../disks-aggregates/index.html["ディスクとローカル階層"]を参照してください。

|===


| 表示する情報 | 使用するコマンド 


 a| 
ローカル階層（使用済みスペースと使用可能スペースの割合、Snapshotリザーブサイズ、その他のスペース使用情報の詳細を含む）
 a| 
`storage aggregate show`

`storage aggregate show-space -fields snap-size-total,used-including-snapshot-reserve`



 a| 
ローカル層でのディスクとRAIDグループの使用方法、およびRAIDステータス
 a| 
`storage aggregate show-status`



 a| 
特定のスナップショットを削除した場合に回復されるディスク容量
 a| 
`volume snapshot compute-reclaimable`



 a| 
ボリュームによって使用されているスペースの量
 a| 
`volume show -fields size,used,available,percent-used`

`volume show-space`



 a| 
含まれるローカル階層内のボリュームによって使用されるスペースの量
 a| 
`volume show-footprint`

|===
.関連情報
* link:https://docs.netapp.com/us-en/ontap-cli/storage-aggregate-show.html["storage aggregate show"^]
* link:https://docs.netapp.com/us-en/ontap-cli/storage-aggregate-show-space.html["storage aggregate show-space"^]
* link:https://docs.netapp.com/us-en/ontap-cli/storage-aggregate-show-status.html["storage aggregate show-status"^]

