---
permalink: disks-aggregates/convert-raid-tec-dp-task.html 
sidebar: sidebar 
keywords: convert, raid-tec, raid-dp, raid policy 
summary: ローカル層のサイズを縮小し、トリプル パリティが不要になった場合は、RAID ポリシーをRAID-TECからRAID-DPに変換し、RAID パリティに必要なディスクの数を減らすことができます。 
---
= ONTAP RAID-TECからRAID-DPへの変換
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
ローカル層のサイズを縮小し、トリプル パリティが不要になった場合は、RAID ポリシーをRAID-TECからRAID-DPに変換し、RAID パリティに必要なディスクの数を減らすことができます。


NOTE: ONTAP 9.7より前のバージョンでは、System Managerは_ローカル階層_を説明するために_aggregate_という用語を使用しています。ONTAPバージョンに関係なく、ONTAP CLIでは_aggregate_という用語が使用されます。ローカル階層の詳細については、link:../disks-aggregates/index.html["ディスクとローカル階層"]を参照してください。

.開始する前に
RAID-TECの最大RAIDグループ サイズは、RAID-DPの最大RAIDグループ サイズよりも大きくなります。RAID-TECの最大グループ サイズがRAID-DPの制限内に収まらない場合、RAID-DPへの変換はできません。

.タスク概要
RAID タイプ間の変換の影響を理解するには、 `storage aggregate modify`コマンドの https://docs.netapp.com/us-en/ontap-cli/storage-aggregate-modify.html#parameters["parameters"^]を参照してください。

.手順
. ローカル層がオンラインであり、少なくとも 6 台のディスクがあることを確認します：
+
`storage aggregate show-status -aggregate _aggregate_name_`

. ローカル層をRAID-TECからRAID-DPに変換：
+
`storage aggregate modify -aggregate _aggregate_name_ -raidtype raid_dp`

. ローカル層の RAID ポリシーが RAID-DP であることを確認します：
+
`storage aggregate show _aggregate_name_`



.関連情報
* link:https://docs.netapp.com/us-en/ontap-cli/storage-aggregate-modify.html["storage aggregate modify"^]
* link:https://docs.netapp.com/us-en/ontap-cli/storage-aggregate-show-status.html["storage aggregate show-status"^]

