---
permalink: disks-aggregates/convert-raid-tec-dp-task.html 
sidebar: sidebar 
keywords: convert, raid-tec, raid-dp, raid policy 
summary: ローカル階層のサイズを縮小し、トリプルパリティが不要になった場合は、RAIDポリシーをRAID-TECからRAID-DPに変換して、RAIDパリティに必要なディスクの数を減らすことができます。 
---
= ONTAP RAID-TECからRAID-DPへの変換
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
ローカル階層のサイズを縮小し、トリプルパリティが不要になった場合は、RAIDポリシーをRAID-TECからRAID-DPに変換して、RAIDパリティに必要なディスクの数を減らすことができます。


NOTE: ONTAP 9.7より前のバージョンでは、ローカル階層を表すために_aggregate_という用語が使用されていました。ONTAPのバージョンに関係なく、ONTAP CLIでは_aggregate_という用語が使用されます。ローカル階層の詳細については、を参照してくださいlink:../disks-aggregates/index.html["ディスクとローカル階層"]。

.開始する前に
RAID-TECの最大RAIDグループサイズは、RAID-DPの最大RAIDグループサイズよりも大きくなります。最大RAID-TECグループサイズがRAID-DPの制限内に収まらない場合は、RAID-DPに変換できません。

.タスクの内容
RAIDタイプ間の変換の影響については、コマンドのを参照してください https://docs.netapp.com/us-en/ontap-cli/storage-aggregate-modify.html#parameters["パラメータ"^] `storage aggregate modify` 。

.手順
. ローカル階層がオンラインで、少なくとも6本のディスクがあることを確認します。
+
`storage aggregate show-status -aggregate _aggregate_name_`

. ローカル階層をRAID-TECからRAID-DPに変換します。
+
`storage aggregate modify -aggregate _aggregate_name_ -raidtype raid_dp`

. ローカル階層のRAIDポリシーがRAID-DPであることを確認します。
+
`storage aggregate show _aggregate_name_`



.関連情報
* link:https://docs.netapp.com/us-en/ontap-cli/storage-aggregate-modify.html["storage aggregate modify"^]

