---
permalink: disks-aggregates/correct-misaligned-spare-partitions-task.html 
sidebar: sidebar 
keywords: correct, misaligned, partition, disk 
summary: パーティション化されたディスクをローカル層に追加する場合、ルートパーティションとデータパーティションの両方を含むディスクを各ノードのスペアとして残しておく必要があります。残しておかないと、ノードに障害が発生した場合、ONTAPはコアをスペア データ パーティションにダンプできません。 
---
= ONTAPスペア パーティションの不整合を修正する
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
パーティション化されたディスクをローカル層に追加する場合、ルートパーティションとデータパーティションの両方を含むディスクを各ノードのスペアとして残しておく必要があります。残しておかないと、ノードに障害が発生した場合、ONTAPはコアをスペア データ パーティションにダンプできません。


NOTE: ONTAP 9.7より前のバージョンでは、System Managerは_ローカル階層_を説明するために_aggregate_という用語を使用しています。ONTAPバージョンに関係なく、ONTAP CLIでは_aggregate_という用語が使用されます。ローカル階層の詳細については、link:../disks-aggregates/index.html["ディスクとローカル階層"]を参照してください。

.開始する前に
同じノードが所有する同じタイプのディスクには、スペア データ パーティションとスペア ルート パーティションの両方が必要です。

.手順
. CLIを使用して、ノードのスペア パーティションを表示します。
+
`storage aggregate show-spare-disks -original-owner _node_name_`

+
どのディスクにスペア データ パーティション（spare_data）があり、どのディスクにスペア ルート パーティション（spare_root）があるかを確認してください。スペア パーティションには、 `Local Data Usable`または `Local Root Usable`列にゼロ以外の値が表示されます。

. スペア データ パーティションを含むディスクを、スペア ルート パーティションを含むディスクと交換します。
+
`storage disk replace -disk _spare_data_ -replacement _spare_root_ -action start`

+
いずれの方向にもデータを複製できますが、ルート パーティションの複製のほうが短時間で完了します。

. ディスク交換の進捗を監視します。
+
`storage aggregate show-status -aggregate _aggr_name_`

. 交換処理が完了したら、もう一度スペアを表示して、スペア ディスクが存在することを確認します。
+
`storage aggregate show-spare-disks -original-owner _node_name_`

+
「`Local Data Usable`」と `Local Root Usable`の両方の下に、使用可能なスペースを持つスペア ディスクが表示されます。



.例
ノードc1-01のスペア パーティションを表示して、スペア パーティションがアライメントされていないことを確認します。

[listing]
----
c1::> storage aggregate show-spare-disks -original-owner c1-01

Original Owner: c1-01
 Pool0
  Shared HDD Spares
                              Local    Local
                               Data     Root  Physical
 Disk    Type   RPM Checksum Usable   Usable      Size
 ------- ----- ---- -------- ------- ------- --------
 1.0.1   BSAS  7200 block    753.8GB     0B   828.0GB
 1.0.10  BSAS  7200 block         0B 73.89GB  828.0GB
----
ディスク交換ジョブを開始します。

[listing]
----
c1::> storage disk replace -disk 1.0.1 -replacement 1.0.10 -action start
----
交換処理が終了するのを待つ間に、処理の進捗を表示します。

[listing]
----
c1::> storage aggregate show-status -aggregate aggr0_1

Owner Node: c1-01
 Aggregate: aggr0_1 (online, raid_dp) (block checksums)
  Plex: /aggr0_1/plex0 (online, normal, active, pool0)
   RAID Group /aggr0_1/plex0/rg0 (normal, block checksums)
                                    Usable Physical
 Position Disk    Pool Type   RPM     Size     Size Status
 -------- ------- ---- ---- ----- -------- -------- ----------
 shared   1.0.1    0   BSAS  7200  73.89GB  828.0GB (replacing,copy in progress)
 shared   1.0.10   0   BSAS  7200  73.89GB  828.0GB (copy 63% completed)
 shared   1.0.0    0   BSAS  7200  73.89GB  828.0GB (normal)
 shared   1.0.11   0   BSAS  7200  73.89GB  828.0GB (normal)
 shared   1.0.6    0   BSAS  7200  73.89GB  828.0GB (normal)
 shared   1.0.5    0   BSAS  7200  73.89GB  828.0GB (normal)
----
交換処理が完了したら、スペア ディスクが存在することを確認します。

[listing]
----
ie2220::> storage aggregate show-spare-disks -original-owner c1-01

Original Owner: c1-01
 Pool0
  Shared HDD Spares
                             Local    Local
                              Data     Root  Physical
 Disk   Type   RPM Checksum Usable   Usable      Size
 ------ ----- ---- -------- -------- ------- --------
 1.0.1  BSAS  7200 block    753.8GB  73.89GB  828.0GB
----
.関連情報
* link:https://docs.netapp.com/us-en/ontap-cli/search.html?q=storage+aggregate+show["storage aggregate show"^]
* link:https://docs.netapp.com/us-en/ontap-cli/storage-disk-replace.html["storage disk replace"^]

