---
permalink: disks-aggregates/create-ssd-storage-pool-task.html 
sidebar: sidebar 
keywords: create, provision, ssd, storage, flash, pool, add, cache, local tier, aggregate 
summary: 2~4つのFlash Poolローカル階層（アグリゲート）にSSDキャッシュを提供するためのソリッドステートドライブ（SSD）ストレージプールを作成できます。 
---
= SSDストレージプールを作成して、ローカル階層（アグリゲート）にキャッシュを追加します
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
ソリッドステートドライブ（SSD）を追加することで、既存のローカル階層（アグリゲート）をFlash Poolローカル階層（アグリゲート）に変換してキャッシュをプロビジョニングできます。

2~4つのFlash Poolローカル階層（アグリゲート）にSSDキャッシュを提供するためのソリッドステートドライブ（SSD）ストレージプールを作成できます。Flash Pool アグリゲートを使用すると、作業データセットにはフラッシュを導入して高性能なキャッシュを利用しながら、アクセス頻度が低いデータには低コストの HDD を使用することができます。

.このタスクについて
* ストレージプールにディスクを作成または追加するときは、ディスクリストを指定する必要があります。
+
ストレージプールでは「 diskcount 」パラメータはサポートされません。

* ストレージプールで使用する SSD は同じサイズでなければなりません。


実行する手順 は、System ManagerまたはCLIを使用するインターフェイスによって異なります。

[role="tabbed-block"]
====
.System Manager の略
--
* System Managerを使用してSSDキャッシュを追加します（ONTAP 9.7のみ）*


NOTE: ONTAP 9.7以外のバージョンの場合は、CLI手順 を使用してください

.手順
. [*]( クラシックバージョンに戻る )* をクリックします。
. ストレージ > アグリゲートとディスク > アグリゲート * をクリックします。
. ローカル階層（アグリゲート）を選択し、 * Actions > Add Cache * をクリックします。
. キャッシュソースとして、「ストレージプール」または「専用 SSD 」を選択します。
. （新しいエクスペリエンスに切り替える） * をクリックします。
. Storage > Tiers * をクリックして、新しいアグリゲートのサイズを確認します。


--
.CLI の使用
--
* SSDストレージプールの作成にはCLIを使用*

.手順
. 使用可能なスペア SSD の名前を指定します。
+
「 storage aggregate show-spare-disks -disk-type SSD 」を参照してください

+
ストレージプールで使用される SSD は、 HA ペアのどちらのノードでも所有できます。

. ストレージプールを作成します。
+
「 storage pool create -storage-pool_sp_name 」 -disk-list_disk1_、 _disk2_,..."

. * オプション： * 新しく作成したストレージ・プールを検証します。
+
「 storage pool show -storage-pool_sp_name_` 」



--
====
ストレージプールが提供するストレージがまだどの Flash Pool キャッシュにも割り当てられていなくても、ストレージプールに配置された SSD は、クラスタではスペアとして表示されなくなります。SSD を単独のドライブとして RAID グループに追加することはできません。ストレージをプロビジョニングできるのは、 SSD が属しているストレージプールの割り当て単位を使用する場合に限られます。
