---
permalink: disks-aggregates/create-ssd-storage-pool-task.html 
sidebar: sidebar 
keywords: create, provision, ssd, storage, flash, pool, add, cache, local tier, aggregate 
summary: ソリッド ステート ドライブ（SSD）ストレージ プールを作成して、2 ～ 4 つの Flash Pool ローカル層に SSD キャッシュを提供できます。 
---
= SSD ストレージ プールを作成して ONTAP ローカル層にキャッシュを追加します
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
ソリッド ステート ドライブ（SSD）を追加して既存のローカル層を Flash Pool ローカル層に変換することで、キャッシュをプロビジョニングできます。

ソリッドステートドライブ（SSD）ストレージプールを作成し、2～4つのFlash Poolローカル層にSSDキャッシュを提供できます。Flash Poolローカル層により、作業データセットにはフラッシュを高性能キャッシュとして導入し、アクセス頻度の低いデータには低コストのHDDを使用できます。

.タスク概要
* ディスクを作成する場合や、ストレージ プールにディスクを追加する場合は、ディスク リストを指定する必要があります。
+
ストレージ プールは `diskcount`パラメーターをサポートしていません。

* ストレージ プールで使用されるSSDはすべて同じサイズでなければなりません。


[role="tabbed-block"]
====
.System Manager
--
.System Managerを使用したSSDキャッシュの追加（ONTAP 9.12.1以降）
[%collapsible%open]
=====
ONTAP 9.12.1以降では、System Managerを使用してSSDキャッシュを追加できます。


NOTE: ストレージ プールのオプションは、AFFシステムでは使用できません。

.手順
. *Cluster > Disks* をクリックし、*Show/Hide* をクリックします。
. *タイプ*を選択し、クラスターにスペア SSD が存在することを確認します。
. *Storage > Tiers* をクリックし、*Add Storage Pool* をクリックします。
. ディスク タイプを選択します。
. ディスク サイズを入力します。
. ストレージ プールに追加するディスクの数を選択します。
. 推定キャッシュ サイズを確認します。


=====
.System Managerを使用したSSDキャッシュの追加（ONTAP 9.7のみ）
[%collapsible%open]
=====

NOTE: ONTAP 9.7よりあと、またはONTAP 9.12.1より前のバージョンのONTAPを使用している場合は、CLIの手順を使用します。

.手順
. *[（クラシック バージョンに戻る）]*をクリックします。
. *Storage > Aggregates & Disks > Aggregates*をクリックします。
. ローカル層を選択し、*Actions > Add Cache*をクリックします。
. キャッシュ ソースとして「ストレージ プール」または「専用のSSD」を選択します。
. *(新しいエクスペリエンスに切り替える)*をクリックします。
. 新しいローカル層のサイズを確認するには、*ストレージ > 階層* をクリックします。


=====
--
.CLI
--
*CLI を使用して SSD ストレージ プールを作成する*

.手順
. 使用可能なスペアSSDの名前を確認します。
+
`storage aggregate show-spare-disks -disk-type SSD`

+
ストレージ プールで使用されるSSDは、HAペアのどちらのノードでも所有できます。

. ストレージ プールを作成します。
+
`storage pool create -storage-pool _sp_name_ -disk-list _disk1_,_disk2_,...`

. *オプション：* 新しく作成されたストレージプールを確認します。
+
`storage pool show -storage-pool _sp_name_`



--
====
.結果
ストレージ プールが提供するストレージがまだどのFlash Poolキャッシュにも割り当てられていなくても、ストレージ プールに配置されたSSDは、クラスタではスペアとして表示されなくなります。SSDを単独のドライブとしてRAIDグループに追加することはできません。ストレージをプロビジョニングできるのは、SSDが属しているストレージ プールの割り当て単位を使用する場合に限られます。

.関連情報
* link:https://docs.netapp.com/us-en/ontap-cli/search.html?q=storage+aggregate+show["storage aggregate show"^]
* link:https://docs.netapp.com/us-en/ontap-cli/storage-pool-create.html["ストレージ プールの作成"^]
* link:https://docs.netapp.com/us-en/ontap-cli/storage-pool-show.html["ストレージプールの表示"^]

