---
permalink: disks-aggregates/customize-size-raid-groups-task.html 
sidebar: sidebar 
keywords: raidsize, customize, raid groups 
summary: アグリゲートに含めるストレージの容量に応じて RAID グループのサイズを変更できます。 
---
= RAID グループのサイズをカスタマイズする
:icons: font
:imagesdir: ../media/


[role="lead"]
アグリゲートに含めるストレージの容量に応じて RAID グループのサイズを変更できます。

標準のアグリゲートの場合、 RAID グループのサイズはアグリゲート単位で変更します。Flash Pool アグリゲートの場合は、 SSD RAID グループと HDD RAID グループのサイズを別々に変更できます。

RAID グループのサイズ変更に関する注意事項を次に示します。

* デフォルトでは、最後に作成された RAID グループのディスクまたはアレイ LUN の数が新しい RAID グループのサイズよりも少ない場合、新しいサイズになるまで、最後に作成された RAID グループにディスクまたはアレイ LUN が追加されます。
* アグリゲート内の他のすべての既存 RAID グループのサイズは、明示的にディスクを追加しないかぎり変更されません。
* RAID グループの原因サイズを、アグリゲートの現在の RAID グループの最大サイズよりも大きくすることはできません。
* すでに作成されている RAID グループのサイズを縮小することはできません。
* 環境の新しいサイズ。アグリゲート内のすべての RAID グループ（ Flash Pool アグリゲートの場合は、該当するタイプの RAID グループ - SSD または HDD ）。


.手順
. 該当するコマンドを使用します。
+
|===


| 状況 | 入力するコマンド 


 a| 
Flash Pool アグリゲートの SSD RAID グループの最大サイズを変更します
 a| 
「 storage aggregate modify -aggregate aggr_name -cache-raid-group-size 」と入力します



 a| 
その他の RAID グループの最大サイズを変更します
 a| 
「 storage aggregate modify -aggregate aggr_name -maxraidsize 」のように表示されます

|===


アグリゲート n1_A4 の最大 RAID グループサイズを 20 本のディスクまたはアレイ LUN に変更するコマンドの例を次に示します。

「 storage aggregate modify -aggregate n1_A4 -maxraidsize 20 」を参照してください

Flash Pool アグリゲート n1_cache_a2 の SSD キャッシュ RAID グループの最大サイズを 24 に変更するコマンドの例を次に示します。

「 storage aggregate modify -aggregate n1_cache_a2 -cache-raid-group-size 24 」を参照してください
