---
permalink: disks-aggregates/decide-aggregate-creation-method-concept.html 
sidebar: sidebar 
keywords: decide, aggregate, create, add, method, local tier 
summary: ONTAP ではローカル階層（アグリゲート）の自動作成に関するベストプラクティスの推奨事項が提供されますが（自動プロビジョニングを使用）、推奨される構成が環境でサポートされているかどうかを確認する必要があります。サポートされていない場合は、使用するRAIDポリシーとディスク構成を決定し、ローカル階層を手動で作成する必要があります。 
---
= ローカル階層（アグリゲート）の作成に使用する方法を決定します。
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
ONTAPには、ローカル階層の自動追加（自動プロビジョニングを使用したアグリゲートの作成）に関するベストプラクティスの推奨事項がありますが、推奨される構成が環境でサポートされるかどうかを確認する必要があります。サポートされていない場合は、使用するRAIDポリシーとディスク構成を決定し、ローカル階層を手動で作成する必要があります。

ローカル階層を自動で作成する場合、クラスタ内の使用可能なスペア ディスクがONTAPで分析され、それらのスペア ディスクを使用してローカル階層を追加する方法がベストプラクティスに基づく推奨事項として生成されます。ONTAPに表示される推奨構成を確認し、それらの推奨構成を受け入れるか、手動でローカル階層を追加できます。



== ONTAPの推奨事項を受け入れる前に

ディスクが次のいずれかの状態である場合は、ONTAPによる推奨事項を受け入れる前にそれらに対処する必要があります。

* ディスクが不足している
* スペア ディスクの数が安定しない
* ディスクが割り当てられていない
* スペアが初期化されていない
* ディスクがメンテナンス テスト中である


の詳細については `storage aggregate auto-provision`、をlink:https://docs.netapp.com/us-en/ontap-cli/storage-aggregate-auto-provision.html["ONTAPコマンド リファレンス"^]参照してください。



== 手動方式を使用する必要がある場合

多くの場合、環境に最適なローカル階層のレイアウトが推奨されます。ただし、クラスタでONTAP 9 .1以前を実行している場合、または環境に次の構成が含まれている場合は、手動でローカル階層を作成する必要があります。


NOTE: ONTAP 9 .11.1以降では、System Managerを使用してローカル階層を手動で追加できます。

* サードパーティ製アレイLUNを使用するアグリゲート
* Cloud Volumes ONTAPまたはONTAP Selectを使用した仮想ディスク
* MetroClusterシステム
* SyncMirror
* MSATAディスク
* FlashPool階層（アグリゲート）
* 複数のタイプまたはサイズのディスクがノードに接続されている場合




== ローカル階層（アグリゲート）の作成方法の選択

使用する方法を選択します。

* link:create-aggregates-auto-provision-task.html["ローカル階層（アグリゲート）の自動追加（作成）"]
* link:create-aggregates-manual-task.html["ローカル階層（アグリゲート）の手動追加（作成）"]


.関連情報
* https://docs.netapp.com/us-en/ontap-cli["ONTAPコマンド リファレンス"^]

