---
permalink: disks-aggregates/determine-control-volume-space-aggregate-concept.html 
sidebar: sidebar 
keywords: determine, control. volume, space usage, aggregate 
summary: ローカル階層（アグリゲート）のスペースを最も使用しているFlexVol ボリュームと、具体的にボリュームのどの機能が最も使用しているかを確認することができます。 
---
= ローカル階層（アグリゲート）でのボリュームのスペース使用量を確認および制御する
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
ローカル階層（アグリゲート）のスペースを最も使用しているFlexVol ボリュームと、具体的にボリュームのどの機能が最も使用しているかを確認することができます。

。 `volume show-footprint` コマンドを使用すると、ボリュームによる占有量（包含アグリゲート内でのスペース使用量）に関する情報が表示されます。

。 `volume show-footprint` コマンドを実行すると、アグリゲート内の各ボリューム（オフラインボリュームを含む）のスペース使用量の詳細が表示されます。このコマンドは、の出力のギャップを埋めます `volume show-space` および `aggregate show-space` コマンド割合の値はいずれもアグリゲートサイズの割合で計算されます。

次の例は、を示しています `volume show-footprint` testvolという名前のボリュームに対するコマンド出力：

....
cluster1::> volume show-footprint testvol

      Vserver : thevs
      Volume  : testvol

      Feature                                   Used    Used%
      --------------------------------    ----------    -----
      Volume Data Footprint                  120.6MB       4%
      Volume Guarantee                        1.88GB      71%
      Flexible Volume Metadata               11.38MB       0%
      Delayed Frees                           1.36MB       0%
      Total Footprint                         2.01GB      76%
....
次の表に、の出力のキー行の一部を示します `volume show-footprint` コマンドを実行し、その機能によるスペース使用量を削減する方法を説明します。

|===


| 行 / 機能名 | 説明 / 行の内容 | 削減方法もあります 


 a| 
`Volume Data Footprint`
 a| 
アクティブファイルシステム内のボリュームのデータに使用されている包含アグリゲート内のスペースと、ボリュームの Snapshot コピーに使用されているスペースの合計。この行の値にはリザーブスペースは含まれません。
 a| 
* ボリュームからデータを削除します。
* ボリュームから Snapshot コピーを削除します。




 a| 
`Volume Guarantee`
 a| 
ボリュームによって以降の書き込み用にリザーブされているアグリゲート内のスペース。リザーブされるスペースの量はボリュームのギャランティタイプによって異なります。
 a| 
ボリュームのギャランティタイプをに変更しています `none`。



 a| 
`Flexible Volume Metadata`
 a| 
ボリュームのメタデータファイルに使用されているアグリゲート内のスペースの総容量。
 a| 
直接制御する方法はありません。



 a| 
`Delayed Frees`
 a| 
パフォーマンス目的で ONTAP が使用していた、すぐには解放できないブロック。SnapMirrorデスティネーションの場合、この行の値はになります `0` およびは表示されません。
 a| 
直接制御する方法はありません。



 a| 
`File Operation Metadata`
 a| 
ファイル処理メタデータ用にリザーブされているスペースの総容量。
 a| 
直接制御する方法はありません。



 a| 
`Total Footprint`
 a| 
ボリュームで使用されているアグリゲート内のスペースの合計。すべての行の合計です。
 a| 
いずれかの方法でボリュームによるスペース使用量を削減します。

|===
.関連情報
http://www.netapp.com/us/media/tr-3483.pdf["ネットアップテクニカルレポート 3483 ：『 NetApp の SAN または IP SAN 構成のエンタープライズ環境におけるシン プロビジョニング』"^]
