---
permalink: disks-aggregates/determine-space-usage-aggregate-concept.html 
sidebar: sidebar 
keywords: space, usage, aggregate, local tier, volume 
summary: 1つ以上のローカル階層内のすべてのボリュームによるスペース使用量を表示して、空きスペースを増やすための対処を行うことができます。 
---
= ONTAPローカル階層のスペース使用量を確認する
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
1つ以上のローカル階層内のすべてのボリュームによるスペース使用量を表示して、空きスペースを増やすための対処を行うことができます。


NOTE: ONTAP 9.7より前のバージョンでは、ローカル階層を表すために_aggregate_という用語が使用されていました。ONTAPのバージョンに関係なく、ONTAP CLIでは_aggregate_という用語が使用されます。ローカル階層の詳細については、を参照してくださいlink:../disks-aggregates/index.html["ディスクとローカル階層"]。

WAFLは、合計ディスクスペースの割合をローカル階層レベルのメタデータとパフォーマンス用にリザーブします。ローカル階層でボリュームの保持に使用されているスペースはWAFLリザーブから解放され、変更することはできません。

30TB未満のローカル階層では、WAFLによって合計ディスクスペースの10%がローカル階層レベルのメタデータとパフォーマンス用にリザーブされます。

ONTAP 9.12.1以降では、30TB以上のローカル階層では、ローカル階層レベルのメタデータとパフォーマンス用にリザーブされるディスクスペースが削減され、ローカル階層の使用可能スペースが5%増加します。このスペース削減効果は、プラットフォームとONTAPのバージョンによって異なります。

[cols="30,30,40"]
|===
| ONTAPによってローカル階層に30TB以上リザーブされているディスクスペース | プラットフォームに適用 | ONTAPノハアシヨン 


| 5% | All AFFおよびFASプラットフォーム | ONTAP 9.14.1以降 


| 5% | AFFプラットフォームとFAS500fプラットフォーム | ONTAP 9.12.1以降 


| 10% | すべてのプラットフォーム | ONTAP 9.11.1以降 
|===
コマンドを使用して、1つ以上のローカル階層内のすべてのボリュームによるスペース使用量を確認できます `aggregate show-space`。この情報から、格納されているローカル階層のスペースを最も消費しているボリュームを確認して、空きスペースを増やすための対処を行うことができます。

ローカル階層の使用済みスペースは、ローカル階層に含まれるFlexVolで使用されるスペースに直接影響されます。ボリュームのスペースを増やすための対処方法も、ローカル階層のスペースに影響します。


NOTE: ONTAP 9.15.1以降では、2つの新しいメタデータカウンタを使用できます。いくつかの既存のカウンタへの変更とともに、割り当てられたユーザデータの量をより明確に表示できます。詳細については、を参照してください link:../volumes/determine-space-usage-volume-aggregate-concept.html["ボリュームまたはローカル階層のスペース使用量を確認する"] 。

コマンド出力に表示される行は次のとおり `aggregate show-space`です。

* *ボリュームフットプリント*
+
ローカル階層内のすべてのボリュームフットプリントの合計。これには、格納先ローカル階層内のすべてのボリュームのすべてのデータおよびメタデータによって使用またはリザーブされているすべてのスペースが含まれます。

* *集計メタデータ*
+
ローカル階層で必要なファイルシステムメタデータ（割り当てビットマップやinodeファイルなど）の合計。

* * Snapshot リザーブ *
+
ローカル階層のSnapshot用にリザーブされているスペースの量（ボリュームサイズに基づいて決まります）。このスペースは使用済みとみなされ、ボリュームまたはローカル階層のデータやメタデータには使用できません。

* * Snapshotリザーブを使用できません*
+
ローカル階層のSnapshotリザーブ用に当初割り当てられていたスペースです。ローカル階層に関連付けられているボリュームで使用されているため、ローカル階層のSnapshotには使用できません。ローカル階層のSnapshotリザーブがゼロでないローカル階層に対してのみ実行できます。

* *合計使用量*
+
ボリューム、メタデータ、またはSnapshotによってローカル階層で使用またはリザーブされているすべてのスペースの合計。

* *合計使用物理容量*
+
将来使用するためにリザーブされているのではなく、現在データに使用されているスペースの量。ローカル階層のSnapshotで使用されているスペースが含まれます。



次の例は、Snapshotリザーブが5%のローカル階層に対するコマンドの出力を示して `aggregate show-space`います。スナップショット予約が0の場合、行は表示されません。

....
cluster1::> storage aggregate show-space

						Aggregate : wqa_gx106_aggr1

      Feature                                   Used      Used%
      --------------------------------    ----------     ------
      Volume Footprints                      101.0MB         0%
      Aggregate Metadata                       300KB         0%
      Snapshot Reserve                        5.98GB         5%

      Total Used                              6.07GB         5%
      Total Physical Used                    34.82KB         0%
....
.関連情報
* link:https://kb.netapp.com/Advice_and_Troubleshooting/Data_Storage_Software/ONTAP_OS/Space_Usage["ナレッジベースの記事：スペース使用量"^]
* link:https://www.netapp.com/blog/free-up-storage-capacity-upgrade-ontap/["ONTAP 9にアップグレードすることで、ストレージ容量の5%を解放できます。12.1"^]

