---
permalink: disks-aggregates/fast-zeroing-drives-concept.html 
sidebar: sidebar 
keywords: fast, zero, drives 
summary: ONTAP 9.4以降では、プロビジョニングの前にドライブ（SSDとHDDの両方）を短時間で自動的に初期化できます。この操作はプロビジョニングの完了までに時間がかかりません。 
---
= ドライブの高速初期化
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
システムにONTAP 9.4以降を新規にインストールし、システムをONTAP 9.4以降で再初期化した場合、_fast zeroing_is used to zero drivs.

高速初期化では、ドライブが数秒で初期化されます。プロビジョニングの前に自動的に実行されるため、スペアドライブを追加した場合に、システムの初期化、アグリゲートの作成、アグリゲートの拡張にかかる時間が大幅に短縮されます。

高速初期化_はSSDとHDDの両方でサポートされます。


NOTE: 高速初期化_は、ONTAP 9.3以前からアップグレードされたシステムではサポートされません。ONTAP 9.4以降を新規にインストールするかシステムを再初期化する必要があります。ONTAP 9.3以前では、ドライブはONTAP によって自動的に初期化されますが、プロセスにかかる時間は長くなります。

ドライブを手動で初期化する必要がある場合は、次のいずれかの方法を使用できます。ONTAP 9.4以降では、ドライブの手動初期化も数秒で完了します。

[role="tabbed-block"]
====
.CLI コマンド
--
*ドライブを高速に初期化するには、CLIコマンドを使用します。*

.このタスクについて
このコマンドを使用するには管理者権限が必要です。

.手順
. CLIコマンドを入力します。
+
「 storage disk zerospares 」と入力します



--
.ブートメニューのオプション
--
*ブートメニューから高速初期化ドライブ*のオプションを選択します

.このタスクについて
* 高速初期化機能拡張は、 ONTAP 9.4 よりも前のリリースからアップグレードされたシステムには対応していません。
* いずれかのノードに高速初期化済みドライブを含むローカル階層（アグリゲート）がある場合、そのクラスタをONTAP 9.2以前にリバートすることはできません。


.手順
. ブートメニューから、次のいずれかのオプションを選択します。
+
** （4）すべてのディスクをクリーンアップして初期化します
** （9a）すべてのディスクのパーティショニングを解除し、ディスクの所有権情報を削除します
** （9b）ストレージシステム全体を含むノードをクリーンアップして初期化します




--
====