---
permalink: disks-aggregates/fast-zeroing-drives-concept.html 
sidebar: sidebar 
keywords: fast, zero, drives 
summary: システムにONTAP 9.4以降を新規にインストールし、システムをONTAP 9.4以降で再初期化した場合、_fast zeroing_is used to zero drivs. 
---
= ONTAPドライブを手動で高速化
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
システムにONTAP 9.4以降を新規にインストールし、システムをONTAP 9.4以降で再初期化した場合、_fast zeroing_is used to zero drivs.

高速初期化では、ドライブが数秒で初期化されます。この処理はプロビジョニング前に自動的に実行されるため、スペアドライブを追加したときにシステムの初期化、ローカル階層の作成、またはローカル階層の拡張にかかる時間が大幅に短縮されます。

高速初期化_はSSDとHDDの両方でサポートされます。


NOTE: 高速初期化_は、ONTAP 9.3以前からアップグレードされたシステムではサポートされません。ONTAP 9 .4以降を新規にインストールするか、システムを再初期化する必要があります。ONTAP 9.3以前では、ONTAPによってドライブも自動的に初期化されますが、処理に時間がかかります。

ドライブを手動で初期化する必要がある場合は、次のいずれかの方法を使用できます。ONTAP 9.4以降では、ドライブの手動での初期化もわずか数秒で完了します。

[role="tabbed-block"]
====
.CLIコマンド
--
*ドライブを高速に初期化するには、CLIコマンドを使用します。*

.タスクの内容
このコマンドを使用するには管理者権限が必要です。

.手順
. CLIコマンドを入力します。
+
[source, cli]
----
storage disk zerospares
----


--
.ブート メニュー オプション
--
*ブートメニューから高速初期化ドライブ*のオプションを選択します

.タスクの内容
* 高速初期化の拡張機能では、ONTAP 9より前のリリースからアップグレードされたシステムはサポートされません。4.
* クラスタのいずれかのノードに高速初期化ドライブを含むローカル階層が含まれている場合、クラスタをONTAP 9.2以前にリバートすることはできません。


.手順
. ブートメニューから、次のいずれかのオプションを選択します。
+
** （4）設定を消去してすべてのディスクを初期化
** （9a）すべてのディスクのパーティショニングを解除し、ディスクの所有権情報を削除
** （9b）設定を消去し、ディスク全体を含むノードを初期化




--
====