---
permalink: disks-aggregates/flash-pool-aggregate-caching-policies-concept.html 
sidebar: sidebar 
keywords: cache, flash pool, policy, work 
summary: キャッシングポリシーは、 Flash Pool アグリゲート内のボリュームに適用されます。キャッシングポリシーを変更する前に、その機能を理解しておく必要があります。 
---
= Flash Pool アグリゲートのキャッシングポリシーの機能
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Flash Pool アグリゲートのボリュームに対するキャッシングポリシーで、作業データセットにはフラッシュを導入して高性能なキャッシュを利用しながら、アクセス頻度が低いデータには低コストの HDD を使用するように定義できます。複数の Flash Pool アグリゲートにキャッシュを提供する場合は、 Flash Pool SSD パーティショニングを使用して、 Flash Pool に含まれるアグリゲート間で SSD を共有します。

キャッシングポリシーは、 Flash Pool アグリゲート内のボリュームに適用されます。キャッシングポリシーを変更する前に、その機能を理解しておく必要があります。

ほとんどの場合、デフォルトのキャッシングポリシーである「 auto 」を使用することをお勧めします。キャッシングポリシーを変更する必要があるのは、別のポリシーを使用したほうがワークロードのパフォーマンスが向上する場合のみです。適切でないキャッシングポリシーを設定すると、ボリュームのパフォーマンスが大幅に低下しかねません。また、時間とともにパフォーマンスの低下が進むおそれがあります。

キャッシングポリシーは、読み取りキャッシングポリシーと書き込みキャッシングポリシーを組み合わせたものです。ポリシー名は、読み取りキャッシングポリシーと書き込みキャッシングポリシーの名前をハイフンでつないだものです。ポリシー名にハイフンが含まれていない場合 ' ライト・キャッシング・ポリシーは 'auto' ポリシーを除いて 'non` です

読み取りキャッシングポリシーは、 HDD に格納されたデータに加えて、データのコピーをキャッシュに格納することで、以降の読み取りパフォーマンスを最適化します。書き込み処理用にキャッシュにデータを挿入する読み取りキャッシングポリシーの場合、キャッシュは _write-through キャッシュとして機能します。

書き込みキャッシングポリシーを使用してキャッシュに挿入されたデータはキャッシュにのみ存在し、 HDD にコピーが格納されることはありません。Flash Pool キャッシュは RAID で保護されています。書き込みキャッシュを有効にすると、書き込み処理されたデータをキャッシュから即座に読み取ることができます。 HDD へのデータの書き込みは、時間が経過してそのデータがキャッシュから削除されるまで先送りされます。

volume create コマンドで「 -caching-policy 」パラメータを使用すると、 Flash Pool アグリゲートにあるボリュームのキャッシングポリシーを変更できます。Flash Pool アグリゲート上にボリュームを作成すると、デフォルトで「 auto 」キャッシングポリシーがそのボリュームに割り当てられます。

ボリュームを Flash Pool アグリゲートから単一層アグリゲートに移動すると、ボリュームのキャッシングポリシーが失われます。あとでボリュームを Flash Pool アグリゲートに戻すと、デフォルトのキャッシングポリシー「 auto 」が割り当てられます。Flash Pool アグリゲート間でボリュームを移動した場合は、キャッシングポリシーが維持されます。
