---
permalink: disks-aggregates/hot-spare-disks-work-concept.html 
sidebar: sidebar 
keywords: hot, spare disks, work 
summary: ホットスペアディスクとは、ストレージシステムに割り当てられているディスクで、 RAID グループでは使用されていないディスクを指します。データは格納されていませんが、すぐに使用できる状態になっています。 
---
= ホットスペアディスクの仕組み
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
ホットスペアディスクとは、ストレージシステムに割り当てられているディスクで、 RAID グループでは使用されていないディスクを指します。データは格納されていませんが、すぐに使用できる状態になっています。

RAID グループ内でディスク障害が発生すると、 RAID グループにホットスペアディスクが自動的に割り当てられ、障害ディスクと交換されます。障害ディスクのデータは、 RAID パリティディスクからホットスペア交換ディスク上にバックグラウンドで再構築されます。再構築アクティビティは /etc/messages' ファイルに記録され ' AutoSupport メッセージが送信されます

障害ディスクと同じサイズのホットスペアディスクがない場合、次に大きなサイズのディスクが選択され、交換対象のディスクのサイズに合わせて縮小されます。



== マルチディスクキャリアのディスクのスペアに関する要件

ストレージの冗長性を最適化し、 ONTAP によるディスクコピーの所要時間を最小限に抑えて、最適なディスクレイアウトを実現するためには、マルチディスクキャリアのディスクに対して適切な数のスペアを用意しておくことが不可欠です。

マルチディスクキャリアのディスクに対しては、常に 2 つ以上のホットスペアを用意しておく必要があります。Maintenance Center を使用できるようにし、同時に複数のディスク障害が発生した場合の問題を回避するには、 4 つ以上のホットスペアを用意して安定した運用を確保し、障害が発生したディスクを迅速に交換するようにします。

ONTAP では、同時に 2 つのディスクで障害が発生した場合に利用できるホットスペアが 2 つしかないと、障害が発生したディスクとそのキャリアメイトの両方のコンテンツをスペアディスクにスワップできないことがあります。このような状況を「ステールメイト」と呼びます。この場合、 EMS メッセージと AutoSupport メッセージで通知されます。交換用キャリアが使用できるようになったら、EMSメッセージに記載されている手順に従う必要があります。詳細については、ナレッジベースの記事を参照してください link:++https://kb.netapp.com/Advice_and_Troubleshooting/Data_Storage_Systems/FAS_Systems/Draft_-_RAID_Layout_Cannot_Be_Autocorrected_-_AutoSupport_message++["RAIDレイアウトを自動再配置できません- AutoSupport メッセージ"]
