---
permalink: disks-aggregates/methods-create-space-aggregate-concept.html 
sidebar: sidebar 
keywords: methods, create, space, aggregate 
summary: アグリゲートの空きスペースが不足すると、データの損失からボリュームのギャランティの無効化に至るさまざまな問題が発生する可能性があります。アグリゲートのスペースを増やす方法はいくつかあります。 
---
= アグリゲート内のスペースを作成する方法
:icons: font
:imagesdir: ../media/


[role="lead"]
アグリゲートの空きスペースがなくなると、データが失われたり、ボリュームのギャランティが無効になるなど、さまざまな問題が発生することがあります。アグリゲートのスペースを増やす方法はいくつかあります。

どの方法にもさまざまな影響があります。対処を実行する前に、ドキュメントの関連するセクションをお読みください。

アグリゲートのスペースを確保するための一般的ないくつかの方法について、影響が小さいものから順に次に示します。

* アグリゲートにディスクを追加します。
* 使用可能なスペースがある別のアグリゲートに一部のボリュームを移動します。
* アグリゲート内のボリュームギャランティが設定されたボリュームのサイズを縮小する。
+
これは、手動で行うことも、オートサイズ機能の「 autoshrink 」オプションを使用して行うこともできます。

* 大量のスペースを使用しているボリューム（大容量のリザーブファイルがある volume ギャランティタイプのボリューム）のギャランティタイプを「 none 」に変更して、アグリゲート内でそのボリュームが占めるスペースを少なくする。
+
ギャランティタイプが「 none 」のボリュームは、ギャランティタイプが「 volume 」のボリュームよりもアグリゲートの占有量が小さくなります。

* ボリュームのギャランティ・タイプが「 none 」の場合は、不要なボリュームの Snapshot コピーを削除します。
* 不要なボリュームを削除する。
* 重複排除や圧縮などのスペース削減機能を有効にします。
* 大量のメタデータを使用している機能を（一時的に）無効にする。

