---
permalink: disks-aggregates/relocate-aggregate-ownership-task.html 
sidebar: sidebar 
keywords: relocate, aggregate, ownership, local tier 
summary: ローカル層の所有権は、HA ペア内のノード間でのみ変更できます。 
---
= HAペア内のONTAPローカル層の所有権を再配置する
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
HA ペアのノード間で、ローカル層からのサービスを中断することなく、ローカル層の所有権を変更できます。


NOTE: ONTAP 9.7より前のバージョンでは、System Managerは_ローカル階層_を説明するために_aggregate_という用語を使用しています。ONTAPバージョンに関係なく、ONTAP CLIでは_aggregate_という用語が使用されます。ローカル階層の詳細については、link:../disks-aggregates/index.html["ディスクとローカル階層"]を参照してください。

HAペアでは、両方のノードのディスクまたはアレイLUNが物理的に相互接続され、それぞれのディスクまたはアレイLUNはどちらか一方のノードで所有されます。

テイクオーバーが発生すると、ローカル層内のすべてのディスクまたはアレイLUNの所有権は、一時的に一方のノードから別のノードへと変更されます。ただし、ローカル層の再配置操作によって所有権が永続的に変更される場合もあります（例：ロード バランシングのため）。所有権の変更は、データのコピー処理やディスクまたはアレイLUNの物理的な移動なしで行われます。

.タスク概要
* ローカル階層の再配置処理では、ボリューム数の制限がプログラムで検証されるため、手動でチェックする必要はありません。
+
ボリューム数がサポートされる上限を超えると、ローカル階層の再配置処理が失敗し、関連するエラー メッセージが表示されます。

* ソース ノードまたはデスティネーション ノードでシステムレベルの処理を実行中のときは、ローカル階層の再配置を開始しないでください。同様に、ローカル階層の再配置の実行中にシステムレベルの処理を開始することも避けてください。
+
システムレベルの処理には次のものが含まれます。

+
** Takeover
** ギブバック
** シャットダウン
** 別のローカル階層の再配置処理
** ディスク所有権の変更
** ローカル階層またはボリュームの設定操作
** ストレージ コントローラの交換
** ONTAPアップグレード
** ONTAPのリバート


* MetroCluster構成がある場合、ディザスタ リカバリ処理（_switchover_、_healing_、または_switchback_）の進行中は、ローカル階層の再配置を開始しないでください。
* MetroCluster構成を使用する場合に、切り替えられたローカル階層でローカル階層の再配置を開始すると、DRパートナーのボリューム数の制限を超えるため、処理が失敗する可能性があります。
* 破損しているかメンテナンス中のローカル層では、ローカル層の再配置を開始しないでください。
* ローカル階層の再配置を開始する前に、ソース ノードとデスティネーション ノードにコア ダンプを保存する必要があります。


.手順
. ノード上のローカル層を表示して、移動するローカル層を確認し、それらがオンラインで良好な状態であることを確認します：
+
`storage aggregate show -node _source-node_`

+
次のコマンドは、クラスター内の4つのノード上の6つのローカル層を表示します。すべてのローカル層はオンラインです。Node1とNode3はHAペアを形成し、Node2とNode4はHAペアを形成します。

+
[listing]
----
cluster::> storage aggregate show
Aggregate     Size Available Used% State   #Vols  Nodes  RAID Status
--------- -------- --------- ----- ------- ------ ------ -----------
aggr_0     239.0GB   11.13GB   95% online       1 node1  raid_dp,
                                                         normal
aggr_1     239.0GB   11.13GB   95% online       1 node1  raid_dp,
                                                         normal
aggr_2     239.0GB   11.13GB   95% online       1 node2  raid_dp,
                                                         normal
aggr_3     239.0GB   11.13GB   95% online       1 node2  raid_dp,
                                                         normal
aggr_4     239.0GB   238.9GB    0% online       5 node3  raid_dp,
                                                         normal
aggr_5     239.0GB   239.0GB    0% online       4 node4  raid_dp,
                                                         normal
6 entries were displayed.
----
. ローカル層の再配置を開始するコマンドを発行します。
+
`storage aggregate relocation start -aggregate-list _aggregate-1_, _aggregate-2_... -node _source-node_ -destination _destination-node_`

+
次のコマンドは、ローカル層aggr_1とaggr_2をNode1からNode3に移動します。Node3はNode1のHAパートナーです。ローカル層はHAペア内でのみ移動できます。

+
[listing]
----
cluster::> storage aggregate relocation start -aggregate-list aggr_1, aggr_2 -node node1 -destination node3
Run the storage aggregate relocation show command to check relocation status.
node1::storage aggregate>
----
.  `storage aggregate relocation show`コマンドを使用して、ローカル層の再配置の進行状況を監視します：
+
`storage aggregate relocation show -node _source-node_`

+
次のコマンドは、Node3 に移動されているローカル層の進行状況を表示します：

+
[listing]
----
cluster::> storage aggregate relocation show -node node1
Source Aggregate   Destination    Relocation Status
------ ----------- -------------  ------------------------
node1
       aggr_1      node3          In progress, module: wafl
       aggr_2      node3          Not attempted yet
2 entries were displayed.
node1::storage aggregate>
----
+
再配置が完了すると、このコマンドの出力には、再配置ステータスが「`Done`」の各ローカル層が表示されます。



.関連情報
* link:https://docs.netapp.com/us-en/ontap-cli/storage-aggregate-relocation-show.html["storage aggregate relocation show"^]
* link:https://docs.netapp.com/us-en/ontap-cli/storage-aggregate-relocation-start.html["storage aggregate relocation start"^]
* link:https://docs.netapp.com/us-en/ontap-cli/storage-aggregate-show.html["storage aggregate show"^]

