---
permalink: disks-aggregates/remove-ownership-disk-task.html 
sidebar: sidebar 
keywords: remove, ownership, disk 
summary: ONTAPは、ディスク所有権情報をディスクに書き込みます。スペアディスクまたはそのシェルフをノードから取り外す前に、所有権情報を削除して、別のノードに適切に統合できるようにする必要があります。 
---
= ONTAPのディスクから所有権を削除する
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
ONTAPは、ディスク所有権情報をディスクに書き込みます。スペアディスクまたはそのシェルフをノードから取り外す前に、所有権情報を削除して、別のノードに適切に統合できるようにする必要があります。


NOTE: ディスクがルート/データパーティショニング用にパーティショニングされていて、ONTAP 9 .10.1以降を実行している場合は、NetAppテクニカルサポートに連絡して所有権を削除してください。詳細については、を参照してくださいlink:https://kb.netapp.com/onprem/ontap/hardware/Error%3A_command_failed%3A_Failed_to_remove_the_owner_of_disk["技術情報アーティクル「Failed to remove the owner of disk」"^]。

.開始する前に
所有権を削除するディスクが次の要件を満たしている必要があります。

* スペア ディスクである。
+
ローカル階層で使用されているディスクから所有権を削除することはできません。

* Maintenance Centerに割り当てられていない。
* 完全消去の実行中ではない。
* 障害ディスクではない。
+
障害ディスクから所有権を削除する必要はありません。



.タスクの内容
ディスクの自動割り当てが有効になっている場合は、ノードからディスクを取り外す前に、ONTAPによって所有権が自動的に再割り当てされます。そのため、ディスクが取り外されるまで所有権の自動割り当てを無効にしてから再度有効にします。

.手順
. ディスク所有権の自動割り当てを有効にしている場合は、CLIを使用して無効にします。
+
`storage disk option modify -node _node_name_ -autoassign off`

. 必要に応じて、ノードのHAパートナーに対して同じ手順を繰り返します。
. ディスクからソフトウェア所有権情報を削除します。
+
`storage disk removeowner _disk_name_`

+
複数のディスクから所有権情報を削除するには、カンマで区切って指定します。

+
例：

+
....
storage disk removeowner sys1:0a.23,sys1:0a.24,sys1:0a.25
....
. ディスクがルート/データパーティショニング用にパーティショニングされていて、ONTAP 9 .9.1以前を実行している場合は、パーティションから所有権を削除します。
+
--
`storage disk removeowner -disk _disk_name_ -root true`

`storage disk removeowner -disk _disk_name_ -data true`

両方のパーティションがどのノードにも所有されなくなります。

--
. 以前にディスク所有権の自動割り当てを無効にした場合は、ディスクを取り外したあとまたは再割り当てしたあとに再度有効にします。
+
`storage disk option modify -node _node_name_ -autoassign on`

. 必要に応じて、ノードのHAパートナーに対して同じ手順を繰り返します。

