---
permalink: disks-aggregates/remove-ownership-disk-task.html 
sidebar: sidebar 
keywords: remove, ownership, disk 
summary: ONTAP は、ディスク所有権情報をディスクに書き込みます。スペアディスクまたはそのシェルフをノードから取り外す前に、所有権情報を削除して、別のノードに適切に統合できるようにする必要があります。 
---
= ディスクから所有権を削除します
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
ONTAP は、ディスク所有権情報をディスクに書き込みます。スペアディスクまたはそのシェルフをノードから取り外す前に、所有権情報を削除して、別のノードに適切に統合できるようにする必要があります。

.必要なもの
所有権を削除するディスクが次の要件を満たしている必要があります。

* スペアディスクである。
+
ローカル階層（アグリゲート）で使用されているディスクから所有権を削除することはできません。

* Maintenance Center に割り当てられていない。
* 完全消去の実行中ではない。
* 障害ディスクではない。
+
障害が発生したディスクから所有権を削除する必要はありません。



.このタスクについて
ディスクの自動割り当てが有効になっている場合は、ノードからディスクを取り外す前に、 ONTAP によって所有権が自動的に再割り当てされます。そのため、ディスクが取り外されるまで所有権の自動割り当てを無効にしてから再度有効にします。

.手順
. ディスク所有権の自動割り当てを有効にしている場合は、CLIを使用して無効にします。
+
「 storage disk option modify -node node_name -autoassign off

. 必要に応じて、ノードの HA パートナーで前述の手順を繰り返します。
. ディスクからソフトウェア所有権情報を削除します。
+
「 storage disk removeowner _disk_name _ 」を選択します

+
複数のディスクから所有権情報を削除するには、カンマで区切ったリストを使用します。

+
例

+
....
storage disk removeowner sys1:0a.23,sys1:0a.24,sys1:0a.25
....
. ディスクがルート / データパーティショニング用にパーティショニングされている場合は、次の両方のコマンドを入力してパーティションから所有権を削除します。
+
「 storage disk removeowner -disk disk_name -root true 」という文字が表示されます

+
「 storage disk removeowner -disk disk_name -data true 」という文字が表示されます

+
これで、両方のパーティションはどのノードからも所有されなくなります。

. ディスク所有権の自動割り当てを無効にしていた場合は、ディスクが取り外されたあと、または再割り当てされたあとに再度有効にします。
+
「 storage disk option modify -node node_name -autoassign on

. 必要に応じて、ノードの HA パートナーで前述の手順を繰り返します。

