---
permalink: disks-aggregates/root-data-partitioning-management-concept.html 
sidebar: sidebar 
keywords: additional, root-data, partitioning, management, options 
summary: ONTAP 9 .2以降では、ブートメニューから新しいルート/データパーティショニングオプションを使用できます。このオプションは、ルート/データパーティショニング用に設定されたディスクに追加の管理機能を提供します。 
---
= ルート/データパーティショニングの追加の管理オプション
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
ONTAP 9 .2以降では、ブートメニューから新しいルート/データパーティショニングオプションを使用できます。このオプションは、ルート/データパーティショニング用に設定されたディスクに追加の管理機能を提供します。

ブートメニューオプション9では、次の管理機能を使用できます。

* *すべてのディスクのパーティションを解除し、ディスクの所有権情報を削除します。*
+
このオプションは、ルート/データパーティショニング用に設定されたシステムを別の設定で再初期化する必要がある場合に役立ちます。

* *パーティショニングされたディスクを含むノードをクリーンアップして初期化します。*
+
このオプションは、次の場合に役立ちます。

+
** ルート/データパーティショニング用に設定されていないシステムをルート/データパーティショニング用に設定する
** ルート/データパーティショニング用に正しく設定されていないシステムを修正する必要がある
** 以前のバージョンのルート/データパーティショニング用に設定されたSSDのみが接続されたAFFプラットフォームまたはFASプラットフォームを使用しており、ルート/データパーティショニングを新しいバージョンにアップグレードしてストレージ効率を向上させる場合


* *構成を消去し、ディスク全体を含むノードを初期化します。*
+
このオプションは、次の処理が必要な場合に役立ちます。

+
** 既存のパーティションのパーティショニングを解除する
** ローカルディスクの所有権を削除する
** RAID-DPを使用してディスク全体を含むシステムを再初期化する



