---
permalink: disks-aggregates/root-data-partitioning-management-concept.html 
sidebar: sidebar 
keywords: additional, root-data, partitioning, management, options 
summary: ONTAP 9.2 以降では、ブートメニューから新しいルート / データパーティショニングオプションを使用できます。このオプションによって、ルート / データパーティショニング用に設定されたディスクに管理機能が追加されます。 
---
= ルート / データパーティショニングの追加の管理オプション
:icons: font
:imagesdir: ../media/


[role="lead"]
ONTAP 9.2 以降では、ブートメニューから新しいルート / データパーティショニングオプションを使用できます。このオプションによって、ルート / データパーティショニング用に設定されたディスクに管理機能が追加されます。

ブートメニューオプション 9 では、次の管理機能を使用できます。

* すべてのディスクのパーティショニングを解除し、ディスクの所有権情報を削除する
+
このオプションは、ルート / データパーティショニング用に設定されているシステムを別の設定を使用して再初期化する必要がある場合に便利です。

* 設定を消去し、パーティショニングされたディスクを含むノードを初期化する
+
このオプションは、次の場合に役立ちます。

+
** ルート / データパーティショニング用に設定されていないシステムをルート / データパーティショニング用に設定する
** ルート / データパーティショニング用に正しく設定されていないシステムを修正する必要があります
** SSD だけが接続されている AFF プラットフォームまたは FAS プラットフォームが以前のバージョンのルート / データパーティショニング用に設定されている状況で、ルート / データパーティショニングを新しいバージョンにアップグレードしてストレージ効率を向上する


* 設定を消去して、ディスク全体を含むノードを初期化します
+
このオプションは、次の処理が必要な場合に役立ちます。

+
** 既存のパーティションのパーティショニングを解除します
** ローカルディスクの所有権を削除する
** RAID-DP を使用して、ディスク全体を含むシステムを再初期化します



