---
permalink: disks-aggregates/sanitize-disk-maintenance-mode-task.html 
sidebar: sidebar 
keywords: sanitize, disk, maintenance mode, nodeshell, node shell, sanitization 
summary: ONTAP 9.6 以降では、メンテナンスモードでディスク完全消去を実行できます。これにより、運用を終了したシステムや動作していないシステムにおいて、 1 本または一連のディスクからデータを削除し、データをリカバリ不能にできます。 
---
= ディスクを完全消去する
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
ディスクを完全消去すると、運用を終了したシステムや動作していないシステムのディスクやディスクのセットからデータを削除し、データをリカバリできないようにすることができます。

CLIを使用してディスクを完全消去するには、次の2つの方法があります。

.ディスクの完全消去には、保守モードのコマンド（ONTAP 9.6以降のリリース）を使用します。
[%collapsible]
====
ONTAP 9.6 以降では、メンテナンスモードでディスク完全消去を実行できます。

.作業を開始する前に
* 自己暗号化ディスク（ SED ）を使用することはできません。
+
を使用する必要があります `storage encryption disk sanitize` SEDを完全消去するコマンド。

+
link:../encryption-at-rest/index.html["保存データの暗号化"]



.手順
. メンテナンスモードでブートします。
+
.. コマンドを入力して、現在のシェルを終了します `halt`。
+
LOADER プロンプトが表示されます。

.. コマンドを入力してメンテナンスモードに切り替えます `boot_ontap maint`。
+
情報が表示されると、保守モードのプロンプトが表示されます。



. 完全消去するディスクがパーティショニングされている場合は、各ディスクのパーティショニングを解除します。
+

NOTE: ディスクのパーティショニングを解除するコマンドはdiagレベルでのみ使用でき、ネットアップサポートの指示があった場合にのみ実行してください。作業を進める前に、ネットアップサポートに問い合わせることを推奨します。Knowledge Base記事も参照できます link:https://kb.netapp.com/Advice_and_Troubleshooting/Data_Storage_Systems/FAS_Systems/How_to_unpartition_a_spare_drive_in_ONTAP["ONTAP でスペアドライブのパーティショニングを解除する方法"^]

+
`disk unpartition _disk_name_`

. 指定したディスクを完全消去します。
+
`disk sanitize start [-p _pattern1_|-r [-p _pattern2_|-r [-p _pattern3_|-r]]] [-c _cycle_count_] _disk_list_`

+

NOTE: 完全消去中はノードの電源をオフにしたり、ストレージの接続を切断したり、ターゲットディスクを取り外したりしないでください。完全消去のフォーマットフェーズで処理が中断された場合、ディスクを完全消去してスペアプールに戻せる状態にするには、フォーマットフェーズを再起動して完了させる必要があります。完全消去プロセスを中止する必要がある場合は、を使用します `disk sanitize abort` コマンドを実行します指定したディスクで完全消去のフォーマットフェーズが進行中の場合、そのフェーズが完了するまで処理は中止されません。

+
 `-p` `_pattern1_` `-p` `_pattern2_` `-p` `_pattern3_` 1~3サイクルのユーザ定義の上書きパターンを16進数で指定します。このパターンは、完全消去するディスクに順に適用されます。デフォルトのパターンは 3 回で、最初のパスに 0x55 、 2 番目のパスに 0xaa 、 3 番目のパスに 0x3C が使用されます。

+
`-r` パターン化された上書きを、一部またはすべてのパスのランダムな上書きに置き換えます。

+
`-c` `_cycle_count_` 指定した上書きパターンを適用する回数を指定します。デフォルト値は 1 サイクルです。最大値は 7 サイクルです。

+
`_disk_list_` 完全消去するスペアディスクのIDを、スペースで区切って指定します。

. 必要に応じて、ディスク完全消去プロセスのステータスを確認します。
+
`disk sanitize status [_disk_list_]`

. 完全消去プロセスが完了したら、各ディスクのスペアステータスにディスクを戻します。
+
`disk sanitize release _disk_name_`

. メンテナンスモードを終了します。


====
.ディスクをノードシェルノードシェルのコマンドによって完全消去する（すべてのONTAP 9リリース）
[%collapsible]
====
ONTAP 9のすべてのバージョンで、ノードシェルコマンドを使用してディスク完全消去を有効にした場合、一部の下位レベルのONTAP コマンドが無効になります。ノードで有効にしたディスク完全消去を無効にすることはできません。

.作業を開始する前に
* ディスクはスペアディスクである必要があります。ノードに所有されており、ローカル階層（アグリゲート）で使用されていないディスクを指定する必要があります。
+
ディスクがパーティショニングされている場合、パーティションをローカル階層（アグリゲート）で使用することはできません。

* 自己暗号化ディスク（ SED ）を使用することはできません。
+
を使用する必要があります `storage encryption disk sanitize` SEDを完全消去するコマンド。

+
link:../encryption-at-rest/index.html["保存データの暗号化"]

* ストレージプールの一部であるディスクを使用することはできません。


.手順
. 完全消去するディスクがパーティショニングされている場合は、各ディスクのパーティショニングを解除します。
+
--

NOTE: ディスクのパーティショニングを解除するコマンドはdiagレベルでのみ使用でき、ネットアップサポートの指示があった場合にのみ実行してください。**作業を進める前に、ネットアップサポートに問い合わせることを強くお勧めします。**ナレッジベースの記事も参照できます link:https://kb.netapp.com/Advice_and_Troubleshooting/Data_Storage_Systems/FAS_Systems/How_to_unpartition_a_spare_drive_in_ONTAP["ONTAP でスペアドライブのパーティショニングを解除する方法"^]。

--
+
`disk unpartition _disk_name_`

. 完全消去するディスクを所有するノードのノードシェルに切り替えます。
+
`system node run -node _node_name_`

. ディスク完全消去を有効にします。
+
`options licensed_feature.disk_sanitization.enable on`

+
このコマンドは取り消すことができないため、確認を求められます。

. ノードシェルの advanced 権限レベルに切り替えます。
+
`priv set advanced`

. 指定したディスクを完全消去します。
+
`disk sanitize start [-p pattern1|-r [-p pattern2|-r [-p pattern3|-r]]] [-c cycle_count] disk_list`

+

NOTE: 完全消去中はノードの電源をオフにしたり、ストレージの接続を切断したり、ターゲットディスクを取り外したりしないでください。完全消去のフォーマットフェーズで処理が中断された場合、ディスクを完全消去してスペアプールに戻せる状態にするには、フォーマットフェーズを再起動して完了させる必要があります。完全消去プロセスを中止する必要がある場合は、 disk sanitize abort コマンドを使用します。指定したディスクで完全消去のフォーマットフェーズが進行中の場合、そのフェーズが完了するまで処理は中止されません。

+
`-p pattern1 -p pattern2 -p pattern3` 1~3サイクルのユーザ定義の上書きパターンを16進数で指定します。このパターンは、完全消去するディスクに順に適用されます。デフォルトのパターンは 3 回で、最初のパスに 0x55 、 2 番目のパスに 0xaa 、 3 番目のパスに 0x3C が使用されます。

+
`-r` パターン化された上書きを、一部またはすべてのパスのランダムな上書きに置き換えます。

+
`-c cycle_count` 指定した上書きパターンを適用する回数を指定します。

+
デフォルト値は 1 サイクルです。最大値は 7 サイクルです。

+
`disk_list` 完全消去するスペアディスクのIDを、スペースで区切って指定します。

. ディスク完全消去プロセスのステータスを確認するには、次のコマンドを入力します。
+
`disk sanitize status [disk_list]`

. 完全消去プロセスが完了したら、ディスクをスペア状態に戻します。
+
`disk sanitize release _disk_name_`

. ノードシェルの admin 権限レベルに戻ります。
+
`priv set admin`

. ONTAP CLI に戻ります。
+
`exit`

. すべてのディスクがスペア状態に戻ったかどうかを確認します。
+
`storage aggregate show-spare-disks`

+
[cols="1,2"]
|===


| 状況 | 作業 


| 完全消去したすべてのディスクがスペアとして表示されます | これで終了です。ディスクは完全消去され、スペア状態になります。 


| 完全消去した一部のディスクがスペアとして表示されない  a| 
次の手順を実行します。

.. advanced 権限モードに切り替えます。
+
`set -privilege advanced`

.. 完全消去した未割り当てのディスクを各ディスクの適切なノードに割り当てます。
+
`storage disk assign -disk _disk_name_ -owner _node_name_`

.. 各ディスクのディスクをスペア状態に戻します。
+
`storage disk unfail -disk _disk_name_ -s -q`

.. adminモードに戻ります。
+
`set -privilege admin`



|===


====
.結果
指定したディスクが完全消去され、ホットスペアとしてマーキングされます。完全消去したディスクのシリアル番号がに書き込まれます `/etc/log/sanitized_disks`。

指定したディスクの完全消去ログ（各ディスクで何が完了したかを示す）がに書き込まれます `/mroot/etc/log/sanitization.log`。
