---
permalink: disks-aggregates/sanitization-overview-concept.html 
sidebar: sidebar 
keywords: disks, disk sanitization, overwriting disks, disk sanitization process, formatting phase, pattern overwrite phase, data recovery 
summary: ディスク完全消去は、元のデータのリカバリが不可能になるように、指定したバイトパターンまたはランダムデータでディスクまたはSSDを上書きして、データを物理的に消去するプロセスです。完全消去プロセスを使用すると、ディスク上のデータをリカバリできなくなります。 
---
= ONTAPディスク完全消去の詳細
:allow-uri-read: 


[role="lead"]
ディスク完全消去は、元のデータのリカバリが不可能になるように、指定したバイトパターンまたはランダムデータでディスクまたはSSDを上書きして、データを物理的に消去するプロセスです。完全消去プロセスを使用すると、ディスク上のデータをリカバリできなくなります。

この機能は、すべてのONTAP 9リリースのノードシェルから、およびONTAP 9 .6以降のメンテナンスモードで使用できます。

ディスク完全消去プロセスでは、1回の処理で最大7サイクル、デフォルトまたはユーザ指定の3回の上書きパターンが使用されます。サイクルごとにランダムな上書きパターンが繰り返されます。

ディスク容量、パターン、およびサイクル数によっては、プロセスに数時間かかることがあります。完全消去はバックグラウンドで実行されます。完全消去プロセスは、開始、停止、およびステータスの表示が可能です。完全消去プロセスには、「フォーマットフェーズ」と「パターン上書きフェーズ」の2つのフェーズがあります。

.フォーマットフェーズ
次の表に示すように、フォーマットフェーズで実行される処理は、完全消去するディスクのクラスによって異なります。

|===


| ディスククラス | フォーマットフェーズ処理 


| 大容量HDD | スキップ 


| ハイパフォーマンスHDD | SCSIフォーマット処理 


| SSD | SCSI完全消去処理 
|===
.パターン上書きフェーズ
指定した上書きパターンが指定したサイクル数だけ反復されます。

完全消去プロセスが完了すると、指定したディスクは完全に消去された状態になります。自動的にスペアのステータスには戻りません。新たに完全消去したディスクを別のローカル階層に追加できるようにするには、完全消去したディスクをスペアプールに戻す必要があります。
