---
permalink: disks-aggregates/sanitize-disk-maintenance-mode-task.html 
sidebar: sidebar 
keywords: sanitize, disk, maintenance mode, nodeshell 
summary: ONTAP 9.6 以降では、メンテナンスモードでディスク完全消去を実行できます。これにより、運用を終了したシステムや動作していないシステムにおいて、 1 本または一連のディスクからデータを削除し、データをリカバリ不能にできます。 
---
= ディスクを完全消去する
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
ディスクを完全消去すると、運用を終了したシステムや動作していないシステムのディスクやディスクのセットからデータを削除し、データをリカバリできないようにすることができます。

ディスクを完全消去する方法は 2 つあります。

* ONTAP 9.6 以降のリリースでメンテナンスモードのコマンドを使用する。
* ONTAP 9 のすべてのリリースでノードシェルコマンドを使用する。




== 保守モードの方法

ONTAP 9.6 以降では、メンテナンスモードでディスク完全消去を実行できます。

.作業を開始する前に
* 自己暗号化ディスク（ SED ）を使用することはできません。
+
SED を完全消去するには、「 storage encryption disk sanitize 」コマンドを使用する必要があります。

+
link:../encryption-at-rest/index.html["保存データの暗号化"]



.手順
. メンテナンスモードでブートします。
. 完全消去するディスクがパーティショニングされている場合は、各ディスクのパーティショニングを解除します。
+
[NOTE]
====
ディスクのパーティショニングを解除するコマンドはdiagレベルでのみ使用でき、ネットアップサポートの指示があった場合にのみ実行してください。作業を進める前に、ネットアップサポートに問い合わせることを推奨します。

====
+
「 Disk unpartition disk_name 」という名前になります

. 指定したディスクを完全消去します。
+
'Disk sanitize start [-p_pattern1_|-r [-p _pattern2_|-r [-p _pattern3_|-r]]] [-c_cycle_count_]_disk_list _`

+

NOTE: 完全消去中はノードの電源をオフにしたり、ストレージの接続を切断したり、ターゲットディスクを取り外したりしないでください。完全消去のフォーマットフェーズで処理が中断された場合、ディスクを完全消去してスペアプールに戻せる状態にするには、フォーマットフェーズを再起動して完了させる必要があります。完全消去プロセスを中止する必要がある場合は、「 Disk sanitize abort 」コマンドを使用します。指定したディスクで完全消去のフォーマットフェーズが進行中の場合、そのフェーズが完了するまで処理は中止されません。

+
-p `_pattern1_``-p`_pattern2_`-p```_pattern3_` は '1 ～ 3 個のユーザ定義 16 進数上書きパターンのサイクルを指定しますこのサイクルは ' 完全消去するディスクに連続して適用できますデフォルトのパターンは 3 回で、最初のパスに 0x55 、 2 番目のパスに 0xaa 、 3 番目のパスに 0x3C が使用されます。

+
r は ' パターン化された上書きを ' パスの一部またはすべてに対してランダムな上書きで置き換えます

+
`-c`_cycle_count_` は、指定した上書きパターンが適用される回数を指定します。デフォルト値は 1 サイクルです。最大値は 7 サイクルです。

+
`_disk_list_ は ' 完全消去するスペア・ディスクの ID をスペースで区切って指定します

. 必要に応じて、ディスク完全消去プロセスのステータスを確認します。
+
「ディスクの完全消去ステータス」 [_disk_list_]

. 完全消去プロセスが完了したら、各ディスクのスペアステータスにディスクを戻します。
+
「 Disk sanitize relee_disk_name_` 」

. メンテナンスモードを終了します。




== ノードシェルメソッド

ノードシェルコマンドを使用してディスク完全消去を有効にすると、下位レベルの ONTAP コマンドがいくつか無効になります。ノードで有効にしたディスク完全消去を無効にすることはできません。

.作業を開始する前に
* ディスクはスペアディスクである必要があります。ノードに所有されており、アグリゲートで使用されていないディスクを指定する必要があります。
+
ディスクがパーティショニングされている場合、パーティションをアグリゲートで使用することはできません。

* 自己暗号化ディスク（ SED ）を使用することはできません。
+
SED を完全消去するには、「 storage encryption disk sanitize 」コマンドを使用する必要があります。

+
link:../encryption-at-rest/index.html["保存データの暗号化"]

* ストレージプールの一部であるディスクを使用することはできません。


.手順
. 完全消去するディスクを所有するノードのノードシェルに切り替えます。
+
'system node run -node _node_name _`

. ディスク完全消去を有効にします。
+
options licensed_feature.disk_sanitization.enable on `

+
このコマンドは取り消すことができないため、確認を求められます。

. ノードシェルの advanced 権限レベルに切り替えます。
+
「 priv set advanced 」のように設定します

. 完全消去するディスクがパーティショニングされている場合は、各ディスクのパーティショニングを解除します。
+
[NOTE]
====
ディスクのパーティショニングを解除するコマンドはdiagレベルでのみ使用でき、ネットアップサポートの指示があった場合にのみ実行してください。作業を進める前に、ネットアップサポートに問い合わせることを推奨します。

====
+
「disk unpartition_disk_name _」のようになります

. 指定したディスクを完全消去します。
+
'disk sanitize start [-p pattern1 |-r [-p pattern2 |-r [-p pattern3 |-r]]] [-c cycle_count] disk_list

+
[NOTE]
====
完全消去中はノードの電源をオフにしたり、ストレージの接続を切断したり、ターゲットディスクを取り外したりしないでください。完全消去のフォーマットフェーズで処理が中断された場合、ディスクを完全消去してスペアプールに戻せる状態にするには、フォーマットフェーズを再起動して完了させる必要があります。

完全消去プロセスを中止する必要がある場合は、 disk sanitize abort コマンドを使用します。指定したディスクで完全消去のフォーマットフェーズが進行中の場合、そのフェーズが完了するまで処理は中止されません。

====
+
-p pattern1 -p pattern2 -p pattern3 には '1 ～ 3 の 16 進数バイトの上書きパターンを指定します指定したパターンは ' 完全消去するディスクに順に適用されますデフォルトのパターンは 3 回で、最初のパスに 0x55 、 2 番目のパスに 0xaa 、 3 番目のパスに 0x3C が使用されます。

+
r は ' パターン化された上書きを ' パスの一部またはすべてに対してランダムな上書きで置き換えます

+
`-c cycle_count` は、指定した上書きパターンが適用される回数を指定します。

+
デフォルト値は 1 サイクルです。最大値は 7 サイクルです。

+
「 disk_list 」は、完全消去するスペアディスクの ID を、スペースで区切って指定します。

. ディスク完全消去プロセスのステータスを確認するには、次のコマンドを入力します。
+
「 disk sanitize status [disk_list] 」というステータスになります

. 完全消去プロセスが完了したら、ディスクをスペア状態に戻します。
+
Disk sanitize release disk_name

. ノードシェルの admin 権限レベルに戻ります。
+
'priv set admin

. ONTAP CLI に戻ります。
+
「 exit

. すべてのディスクがスペア状態に戻ったかどうかを確認します。
+
「 storage aggregate show-spare-disks 」を参照してください



[cols="1,2"]
|===


| 状況 | 作業 


| 完全消去したすべてのディスクがスペアとして表示されます | これで終了です。ディスクは完全消去され、スペア状態になります。 


| 完全消去した一部のディスクがスペアとして表示されない  a| 
次の手順を実行します。

. advanced 権限モードに切り替えます。
+
「 advanced 」の権限が必要です

. 完全消去した未割り当てのディスクを各ディスクの適切なノードに割り当てます。
+
storage disk assign -disk disk_name --owner_node_name

. 各ディスクのディスクをスペア状態に戻します。
+
storage disk unfail -disk disk_name -s -q

. admin モードに戻ります :+`set -privilege admin`


|===
指定したディスクが完全消去され、ホットスペアとしてマーキングされます。完全消去されたディスクのシリアル番号は '/etc/log/sanitized_disks' に書き込まれます
