---
permalink: disks-aggregates/sizing-raid-groups-concept.html 
sidebar: sidebar 
keywords: consideration, size, raid groups 
summary: 最適なRAIDグループサイズを設定するには、さまざまな要素について優先度を考慮する必要があります。設定するローカル階層（アグリゲート）にとって最も重要な要素を、RAIDのリカバリ速度、ドライブ障害によるデータ損失のリスクに対する保証、I/Oパフォーマンスの最適化、データストレージスペースの最大化の中から決定する必要があります。 
---
= RAIDグループのサイジングに関する考慮事項
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
最適なRAIDグループサイズを設定するには、さまざまな要素について優先度を考慮する必要があります。設定する（ローカル階層）アグリゲートにとって最も重要な要素（RAIDのリビルド速度、ドライブ障害によるデータ損失のリスクに対する保証、I/Oパフォーマンスの最適化、データストレージスペースの最大化）を決定する必要があります。

より大容量の RAID グループを作成すると ' パリティに使用されるストレージ容量（パリティの負荷）と同じ容量のデータ・ストレージに使用できる容量が最大化されます一方、大規模なRAIDグループでディスク障害が発生すると再構築時間が長くなり、パフォーマンスに影響が及ぶ期間が長くなります。また、RAIDグループ内のディスク数が多いほど、同じRAIDグループ内で複数のディスクに障害が発生する可能性が高くなります。



== HDDまたはアレイLUN RAIDグループ

HDDまたはアレイLUNを構成するRAIDグループのサイジングを行う際は、次のガイドラインに従う必要があります。

* ローカル階層（アグリゲート）内のすべてのRAIDグループでディスク数を同じにする必要があります。
+
1つのローカル階層上の複数のRAIDグループに含まれるディスク数の上限を50%以下にすることもできますが、パフォーマンスのボトルネックにつながる場合があるため、この方法を使用することを推奨します。

* RAIDグループのディスク数の推奨範囲は12~20です。
+
信頼性の高いパフォーマンスディスクでは、必要に応じて最大28のRAIDグループサイズをサポートできます。

* 上記の2つのガイドラインを満たすディスク数が複数ある場合は、より多くのディスク数を選択してください。




== Flash Poolローカル階層（アグリゲート）のSSD RAIDグループ

SSD RAIDグループサイズは、Flash Poolローカル階層（アグリゲート）のHDD RAIDグループのRAIDグループサイズと同じにすることはできません。通常は、パリティに必要なSSDの数を最小限に抑えるために、Flash Poolローカル階層のSSD RAIDグループは1つだけにします。



== SSDローカル階層（アグリゲート）のSSD RAIDグループ

SSDを構成するRAIDグループのサイジングを行う際は、次のガイドラインに従う必要があります。

* ローカル階層（アグリゲート）内のすべてのRAIDグループで同数のドライブを配置する必要があります。
+
RAIDグループは完全に同じサイズにする必要はありませんが、可能な場合は、同じローカル階層内に他のRAIDグループの半分未満のRAIDグループを配置しないようにしてください。

* RAID-DPの場合、RAIDグループサイズの推奨範囲は20~28です。

