---
permalink: flexgroup/aggregate-space-requirements-concept.html 
sidebar: sidebar 
keywords: guideline, aggregate, space, provision, flexgroup, volume 
summary: FlexGroup ボリュームのプロビジョニングでアグリゲートを選択する際の考慮事項と要件を確認しておく必要があります。 
---
= FlexGroup ボリュームをプロビジョニングする際のアグリゲートスペースに関するガイドライン
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
FlexGroup ボリュームのプロビジョニングでアグリゲートを選択する際の考慮事項と要件を確認しておく必要があります。

FlexGroup ボリュームで最適なパフォーマンスを実現するには、 FlexGroup ボリュームを作成する際に次のガイドラインを考慮する必要があります。

* FlexGroup ボリュームは、同一のハードウェアシステム上にあるアグリゲートでのみ構成される必要があります。
+
同一のハードウェアシステムを使用することで、 FlexGroup ボリューム全体のパフォーマンスを予測できるようになります。

* FlexGroup ボリュームは、同じディスクタイプおよび RAID グループ構成のアグリゲートで構成される必要があります。
+
安定したパフォーマンスを実現するには、すべてのアグリゲートがオール SSD 、オール HDD 、またはオールハイブリッドアグリゲートであることが必要です。また、 FlexGroup ボリュームを構成するすべてのアグリゲートでドライブ数と RAID グループ数が同じであることが必要です。

* FlexGroup ボリュームは、クラスタの一部でのみ構成することができます。
+
FlexGroup ボリュームをクラスタ全体にまたがるように設定する必要はありませんが、そのように設定すると、使用可能なハードウェアリソースをより有効に活用できます。

* FlexGroup ボリュームを作成する場合は、次の特性を持つアグリゲートに FlexGroup ボリュームを導入することを推奨します。
+
** シンプロビジョニングを使用する場合は特に、複数のアグリゲート間でほぼ同じ量の空きスペースを使用できます。
** FlexGroup ボリュームの作成後に、空きスペースの約 3% がアグリゲートメタデータ用に確保される。


* FAS システムの場合は、ノードごとに 2 つのアグリゲートを用意し、 AFF システムの場合は、 FlexGroup ボリュームのノードごとに 1 つのアグリゲートを用意することを推奨します。
* FlexGroup ボリュームごとに少なくとも 8 つのコンスティチュエントを作成して、 FAS システムの場合は 2 つ以上のアグリゲートに、 AFF システムの場合は 1 つ以上のアグリゲートに分散させる必要があります。


.関連情報
http://["ネットアップテクニカルレポート 4571 ：『 NetApp FlexGroup Best Practices and Implementation Guide 』"^]
