---
permalink: flexgroup/configure-automatic-grow-shrink-task.html 
sidebar: sidebar 
keywords: configure, flexgroup, volume, automatic, grow, shrink, size 
summary: ONTAP 9.3以降では、必要なスペースに応じてFlexGroupボリュームを自動的に拡張または縮小するように設定できます。 
---
= ONTAP FlexGroupボリュームのサイズを自動的に拡大縮小するように設定する
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
ONTAP 9.3以降では、必要なスペースに応じてFlexGroupボリュームを自動的に拡張または縮小するように設定できます。

.開始する前に
FlexGroupはオンラインである必要があります。

.タスク概要
FlexGroupボリュームのオートサイズには2つのモードがあります。

* ボリュームのサイズを自動で増やす（(`grow`モード）
+
自動拡張機能を使用すると、FlexGroupボリュームがスペース不足になることを防止できます（アグリゲートが追加のスペースを提供できる場合）。ボリュームの最大サイズを設定することができます。拡張は、ボリュームに書き込まれるデータ量と現在使用中のスペースの比率、およびしきい値設定に基づいて、自動的にトリガーされます。

+
デフォルトでは、ボリュームの最大サイズは、自動拡張を有効にした時点のサイズの120%まで拡張できます。120%よりも大きく拡張する必要がある場合は、必要に応じてボリュームの最大サイズを設定してください。

* ボリュームのサイズを自動縮小する（(`grow_shrink`モード）
+
自動縮小機能を使用すると、ボリュームが必要以上に拡張されるのを防止し、アグリゲート内の空きスペースを他のボリュームで利用できます。

+
自動縮小は、変化し続けるスペース需要に対応するために自動拡張とセットで使用され、単独で使用されることはありません。自動縮小を有効にした場合、自動拡張と自動縮小の処理が無限に繰り返されないように縮小動作が自動的に制御されます。



ボリュームが拡張されると、格納できるファイルの最大数が自動的に増える可能性があります。ボリュームが縮小されても格納できるファイルの最大数は変わらず、ボリュームが縮小前のファイルの最大数に対応するサイズよりも小さくなることはありません。そのため、自動縮小でボリュームを最初のサイズまで縮小できるとは限りません。

.手順
. ボリュームのサイズを自動的に拡大および縮小するように設定します： `volume autosize -vserver vserver_name -volume vol_name -mode [grow | grow_shrink]`
+
ボリュームを拡張または縮小する最大サイズ、最小サイズ、およびしきい値を指定することもできます。

+
次のコマンドは、 `fg1`というボリュームの自動サイズ変更を有効にします。ボリュームは、70% 使用時に最大サイズが 5 TB まで拡張されるように設定されています。

+
[listing]
----
cluster1::> volume autosize -volume fg1 -mode grow -maximum-size 5TB -grow-threshold-percent 70
vol autosize: volume "vs_src:fg1" autosize settings UPDATED.
----

