---
permalink: flexgroup/convert-flexvol-concept.html 
sidebar: sidebar 
keywords: consider, convert, flexvol, volume, flexgroup, autobalance, give back, giveback, revert, split, space limit, limit 
summary: FlexVol ボリュームを FlexGroup ボリュームに変換する前に、サポートされる機能と処理を確認しておく必要があります。 
---
= FlexVol ボリュームから FlexGroup ボリュームへの変換の概要を参照してください
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
FlexVol ボリュームをそのスペース制限を超えて拡張する場合は、 FlexVol ボリュームを FlexGroup ボリュームに変換できます。ONTAP 9.7 以降では、スタンドアロンの FlexVol ボリュームや SnapMirror 関係にある FlexVol ボリュームを FlexGroup ボリュームに変換できます。



== FlexVol ボリュームを FlexGroup ボリュームに変換する際の考慮事項

FlexVol ボリュームを FlexGroup ボリュームに変換する前に、サポートされる機能と処理を確認しておく必要があります。



== 変換中は処理がサポートされません

ボリューム変換の実行中は、次の処理は実行できません。

* ボリューム移動
* アグリゲートの自動負荷分散
* アグリゲートの再配置
* ハイアベイラビリティ構成での計画的なテイクオーバーとギブバック
* ハイアベイラビリティ構成での手動および自動のギブバック
* クラスタのアップグレードとリバート
* FlexClone ボリュームのスプリット
* ボリュームをリホスト
* ボリュームの変更とオートサイズ
* ボリュームの名前を変更
* アグリゲートにオブジェクトストアを接続しています
* MetroCluster 構成でのネゴシエートスイッチオーバー
* SnapMirror 処理
* Snapshot コピーからのリストア
* クォータの処理
* ストレージ効率化の処理


これらの処理は、変換の完了後に FlexGroup ボリュームに対して実行できます。



== FlexGroup ボリュームでサポートされない構成

* オフラインまたは制限状態のボリューム
* SVM ルートボリューム
* SAN
* SMB 1.0
* NVMe ネームスペース
* リモートの Volume Shadow Copy Service （ VSS ；ボリュームシャドウコピーサービス）

