---
permalink: flexgroup/convert-flexvol-volume-task.html 
sidebar: sidebar 
keywords: convert, flexvol, volume, flexgroup, conversion, flex vol, flex group, transitioned, 
summary: ONTAP 9.7 以降では、 FlexVol ボリュームから FlexGroup ボリュームへのインプレース変換が可能です。データコピーや追加のディスクスペースは必要ありません。 
---
= FlexVol ボリュームを FlexGroup ボリュームに変換します
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
ONTAP 9.7 以降では、 FlexVol ボリュームから FlexGroup ボリュームへのインプレース変換が可能です。データコピーや追加のディスクスペースは必要ありません。

.必要なもの
* ONTAP 9.8以降では、移行したボリュームをFlexGroup ボリュームに変換できます。移行したボリュームをFlexGroup に変換する場合は、技術情報アーティクルを参照してください link:https://kb.netapp.com/Advice_and_Troubleshooting/Data_Storage_Software/ONTAP_OS/How_To_Convert_a_Transitioned_FlexVol_to_FlexGroup["移行したFlexVol をFlexGroup に変換する方法"] を参照してください。
* 変換する FlexVol がオンラインになっている必要があります。
* FlexVol ボリュームの処理と設定が変換プロセスに対応している必要があります。
+
FlexVol ボリュームに互換性の問題があり、ボリュームの変換が中止された場合、エラーメッセージが生成されます。対処方法を実行し、変換を再試行できます。

* FlexVol ボリュームが非常に大きく（80~100TBなど）、非常にフル（80~100%）な場合は、変換せずにデータをコピーする必要があります。
+
[NOTE]
====
非常に大容量のFlexGroup を変換すると、FlexGroup ボリュームのメンバーコンスティチュエントがいっぱいになり、パフォーマンスの問題が生じる可能性があります。詳細については、TRで「When not to create a FlexGroup volume」を参照してください link:https://www.netapp.com/media/12385-tr4571.pdf["FlexGroup ボリューム-ベストプラクティスおよび実装ガイド"]。

====


.手順
. FlexVol ボリュームがオンラインであることを確認します。 `volume show vol_name -volume-style-extended,state`
+
[listing]
----
cluster-1::> volume show my_volume -fields volume-style-extended,state
vserver volume    state  volume-style-extended
------- --------- ------ ---------------------
vs0     my_volume online flexvol
----
. FlexVol ボリュームを問題なく変換できるかどうかを確認します。
+
.. advanced権限モードにログインします。 `set -privilege advanced`
.. 変換プロセスを確認します。 `volume conversion start -vserver vs1 -volume flexvol -check-only true`
+
ボリュームを変換する前に、すべてのエラーを修正する必要があります。

+
[NOTE]
====
FlexGroup ボリュームを FlexVol ボリュームに戻すことはできません。

====


. 変換を開始します。 `volume conversion start -vserver svm_name -volume vol_name`
+
[listing]
----
cluster-1::*> volume conversion start -vserver vs0 -volume my_volume

Warning: Converting flexible volume "my_volume" in Vserver "vs0" to a FlexGroup
         will cause the state of all Snapshot copies from the volume to be set
         to "pre-conversion". Pre-conversion Snapshot copies cannot be
         restored.
Do you want to continue? {y|n}: y
[Job 57] Job succeeded: success
----
. 変換が正常に完了したことを確認します。 `volume show vol_name -fields -volume-style-extended,state`
+
[listing]
----
cluster-1::*> volume show my_volume -fields volume-style-extended,state
vserver volume    state  volume-style-extended
------- --------- ------ ---------------------
vs0     my_volume online flexgroup
----


.結果
FlexVol ボリュームが単一メンバーの FlexGroup ボリュームに変換されます。

.完了後
必要に応じて、 FlexGroup ボリュームを拡張できます。
