---
permalink: flexgroup/convert-flexvol-concept.html 
sidebar: sidebar 
keywords: consider, convert, flexvol, volume, flexgroup, autobalance, give back, giveback, revert, split, space limit, limit 
summary: FlexVolボリュームをFlexGroupボリュームに変換する前に、サポートされる機能と処理について理解しておく必要があります。 
---
= ONTAP FlexVolボリュームからFlexGroupボリュームへの変換について
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
FlexVol volumeをスペース制限を超えて拡張する場合は、FlexVol volumeをFlexGroupボリュームに変換できます。ONTAP 9 .7以降では、スタンドアロンのFlexVolボリュームまたはSnapMirror関係にあるFlexVolボリュームをFlexGroupボリュームに変換できます。



== FlexVolボリュームをFlexGroupボリュームに変換する場合の考慮事項

知っておくべきlink:supported-unsupported-config-concept.html["サポートされている機能と操作"] FlexVolボリュームをFlexGroupボリュームに変換する前に、次の点を確認してください。



== 変換中にサポートされない処理

ボリューム変換の実行中は、次の処理は実行できません。

* ボリューム移動
* アグリゲートの自動負荷分散
* アグリゲートの再配置
* ハイアベイラビリティ構成での計画的なテイクオーバーとギブバック
* ハイアベイラビリティ構成での手動および自動のギブバック
* クラスタのアップグレードとリバート
* FlexCloneボリュームをスプリット
* ホリユウムノリホスト
* ボリュームの変更とオートサイズ
* ボリュームの名前変更
* アグリゲートへのオブジェクトストアの接続
* MetroCluster構成でのネゴシエートスイッチオーバー
* SnapMirrorの処理
* Snapshotカラノリストア
* クォータの処理
* ストレージ効率化の処理


これらの処理は、変換が成功したあとにFlexGroupボリュームに対して実行できます。



== FlexGroupでサポートされない構成

* オフラインまたは制限状態のボリューム
* SVMルートボリューム
* SAN
* SMB 1.0
* NVMeネエムスヘエス
* リモートのボリュームシャドウコピーサービス（VSS）

