---
permalink: flexgroup/create-snapvault-relationship-task.html 
sidebar: sidebar 
keywords: create, snapvault, relationship, flexgroup, volumes 
summary: SnapVault 関係を設定し、その関係に SnapVault ポリシーを割り当てて、 SnapVault バックアップを作成することができます。 
---
= FlexGroup ボリュームの SnapVault 関係を作成
:icons: font
:imagesdir: ../media/


[role="lead"]
SnapVault 関係を設定し、その関係に SnapVault ポリシーを割り当てて、 SnapVault バックアップを作成することができます。

FlexGroup ボリュームの SnapVault 関係の作成に関する考慮事項を確認しておく必要があります。

.手順
. ソース FlexGroup ボリュームと同じ数のコンスティチュエントで構成される「 D 」タイプのデスティネーション FlexGroup ボリュームを作成します。
+
.. ソースクラスタから、ソース FlexGroup ボリュームのコンスティチュエントの数を確認します。 volume show -volume volume_name * -is-constituent true
+
[listing]
----
cluster1::> volume show  -volume src* -is-constituent true
Vserver   Volume       Aggregate    State      Type       Size  Available Used%
--------- ------------ ------------ ---------- ---- ---------- ---------- -----
vss       src          -            online     RW         400TB   172.86GB  56%
vss       src__0001    Aggr_cmode   online     RW         25GB    10.86TB   56%
vss       src__0002    aggr1        online     RW         25TB    10.86TB   56%
vss       src__0003    Aggr_cmode   online     RW         25TB    10.72TB   57%
vss       src__0004    aggr1        online     RW         25TB    10.73TB   57%
vss       src__0005    Aggr_cmode   online     RW         25TB    10.67TB   57%
vss       src__0006    aggr1        online     RW         25TB    10.64TB   57%
vss       src__0007    Aggr_cmode   online     RW         25TB    10.63TB   57%
...
----
.. デスティネーションクラスタから、「 D 」タイプのデスティネーション FlexGroup を、ソース FlexGroup ボリュームと同じ数のコンスティチュエントで作成します。
+
[listing]
----
cluster2::> volume create -vserver vsd -aggr-list aggr1,aggr2 -aggr-list-multiplier 8 -size 400TB -type DP dst

Warning: The FlexGroup volume "dst" will be created with the following number of constituents of size 25TB: 16.
Do you want to continue? {y|n}: y
[Job 766] Job succeeded: Successful
----
.. デスティネーションクラスタから、デスティネーション FlexGroup ボリュームのコンスティチュエントの数を確認します。 volume show -volume volume_name * -is-constituent true
+
[listing]
----
cluster2::> volume show  -volume dst* -is-constituent true
Vserver   Volume       Aggregate    State      Type       Size  Available Used%
--------- ------------ ------------ ---------- ---- ---------- ---------- -----
vsd       dst          -            online     RW         400TB   172.86GB  56%
vsd       dst__0001    Aggr_cmode   online     RW         25GB    10.86TB   56%
vsd       dst__0002    aggr1        online     RW         25TB    10.86TB   56%
vsd       dst__0003    Aggr_cmode   online     RW         25TB    10.72TB   57%
vsd       dst__0004    aggr1        online     RW         25TB    10.73TB   57%
vsd       dst__0005    Aggr_cmode   online     RW         25TB    10.67TB   57%
vsd       dst__0006    aggr1        online     RW         25TB    10.64TB   57%
vsd       dst__0007    Aggr_cmode   online     RW         25TB    10.63TB   57%
...
----


. ジョブスケジュールを作成します。 'job schedule cron create -name job_name -month -dayofweek day-of-week day-of-month-day day-of-month -hour hour-hour minute'
+
「 -month 」、「 -dayofweek 」、「 -hour 」には、「 all 」を指定して、毎月、曜日、および時ごとにジョブを実行できます。

+
次の例は、土曜日の午前 3 時に実行する「 my_weekly 」というジョブスケジュールを作成します。

+
[listing]
----
cluster1::> job schedule cron create -name my_weekly -dayofweek "Saturday" -hour 3 -minute 0
----
. SnapVault ポリシーを作成し、 SnapVault ポリシーのルールを定義します。
+
.. SnapVault 関係に「 vault 」タイプのカスタムポリシーを作成します。「 snapmirror policy create -vserver SVM_name -policy policy_name -type vault
.. 初期化と更新の処理中に転送する Snapshot コピーを決定する SnapVault ポリシーのルールを定義します。「 snapmirror policy add-rule -vserver SVM_name -policy policy_on_rule -snapmirror-label -keep retention_count -schedule


+
カスタムポリシーを作成しない場合は、 SnapVault 関係に「 XDPDefault 」ポリシーを指定する必要があります。

. SnapVault 関係を作成します。「 snapmirror create -source-path src_SVM ： src_flexgroup -destination-path dest_SVM ： dest_flexgroup -type XDP -schedule schedule_name -policy XDPDefault
+
ONTAP 9.4 以前では、「 snapmirror create 」コマンドでポリシーを指定しなかった場合、デフォルトで「 MirrorAllSnapshots 」ポリシーが使用されます。ONTAP 9.5 では、「 snapmirror create 」コマンドでポリシーが指定されていない場合、デフォルトで「 M irroresstons 」ポリシーが使用されます。

+
[listing]
----
cluster2::> snapmirror create -source-path vss:srcFG -destination-path vsd:dstFG -type XDP -schedule Daily -policy XDPDefault
----
. デスティネーションクラスタから、ベースライン転送を実行して SnapVault 関係を初期化します。「 snapmirror initialize -destination-path dest_SVM ： dest_flexgroup
+
[listing]
----
cluster2::> snapmirror initialize -destination-path vsd:dst
Operation is queued: snapmirror initialize of destination "vsd:dst".
----

