---
permalink: flexgroup/create-snapmirror-relationship-task.html 
sidebar: sidebar 
keywords: create, snapmirror, relationship, flexgroup, volume 
summary: ディザスタリカバリ用にデータをレプリケートするために、ピア関係にある SVM のソース FlexGroup ボリュームとデスティネーション FlexGroup ボリュームの間で SnapMirror 関係を作成することができます。災害が発生した場合は、 FlexGroup ボリュームのミラーコピーを使用してデータをリカバリできます。 
---
= FlexGroup ボリュームの SnapMirror 関係を作成
:icons: font
:imagesdir: ../media/


[role="lead"]
ディザスタリカバリ用にデータをレプリケートするために、ピア関係にある SVM のソース FlexGroup ボリュームとデスティネーション FlexGroup ボリュームの間で SnapMirror 関係を作成することができます。災害が発生した場合は、 FlexGroup ボリュームのミラーコピーを使用してデータをリカバリできます。

クラスタと SVM のピア関係を作成しておく必要があります。

link:../peering/index.html["クラスタと SVM のピアリング"]

.このタスクについて
* FlexGroup ボリュームには、クラスタ間 SnapMirror 関係とクラスタ内 SnapMirror 関係の両方を作成することができます。
* ONTAP 9.3 以降では、 SnapMirror 関係にある FlexGroup ボリュームを拡張できます。
+
ONTAP 9.3 より前 FlexGroup のバージョンの ONTAP を使用している場合は、 SnapMirror 関係の確立後に FlexGroup ボリュームを拡張することはできませんが、容量を拡張することはできます。ONTAP 9.3 よりも前のリリースで SnapMirror 関係の解除後にソース FlexGroup ボリュームを拡張した場合は、デスティネーション FlexGroup へのベースライン転送を実行する必要があります。



.手順
. ソース FlexGroup ボリュームと同じ数のコンスティチュエントで構成される「 D 」タイプのデスティネーション FlexGroup ボリュームを作成します。
+
.. ソースクラスタから、ソース FlexGroup ボリュームのコンスティチュエントの数を確認します。 volume show -volume volume_name * -is-constituent true
+
[listing]
----
cluster1::> volume show  -volume srcFG* -is-constituent true
Vserver   Volume       Aggregate    State      Type       Size  Available Used%
--------- ------------ ------------ ---------- ---- ---------- ---------- -----
vss       srcFG          -            online     RW         400TB   172.86GB  56%
vss       srcFG__0001    Aggr_cmode   online     RW         25GB    10.86TB   56%
vss       srcFG__0002    aggr1        online     RW         25TB    10.86TB   56%
vss       srcFG__0003    Aggr_cmode   online     RW         25TB    10.72TB   57%
vss       srcFG__0004    aggr1        online     RW         25TB    10.73TB   57%
vss       srcFG__0005    Aggr_cmode   online     RW         25TB    10.67TB   57%
vss       srcFG__0006    aggr1        online     RW         25TB    10.64TB   57%
vss       srcFG__0007    Aggr_cmode   online     RW         25TB    10.63TB   57%
...
----
.. デスティネーションクラスタから、「 D 」タイプのデスティネーション FlexGroup を、ソース FlexGroup ボリュームと同じ数のコンスティチュエントで作成します。
+
[listing]
----
cluster2::> volume create -vserver vsd -aggr-list aggr1,aggr2 -aggr-list-multiplier 8 -size 400TB -type DP dstFG

Warning: The FlexGroup volume "dstFG" will be created with the following number of constituents of size 25TB: 16.
Do you want to continue? {y|n}: y
[Job 766] Job succeeded: Successful
----
.. デスティネーションクラスタから、デスティネーション FlexGroup ボリュームのコンスティチュエントの数を確認します。 volume show -volume volume_name * -is-constituent true
+
[listing]
----
cluster2::> volume show  -volume dstFG* -is-constituent true
Vserver   Volume        Aggregate    State      Type       Size  Available  Used%
--------- ------------  ------------ ---------- ---- ----------  ---------- -----
vsd       dstFG          -            online     DP         400TB   172.86GB  56%
vsd       dstFG__0001    Aggr_cmode   online     DP         25GB    10.86TB   56%
vsd       dstFG__0002    aggr1        online     DP         25TB    10.86TB   56%
vsd       dstFG__0003    Aggr_cmode   online     DP         25TB    10.72TB   57%
vsd       dstFG__0004    aggr1        online     DP         25TB    10.73TB   57%
vsd       dstFG__0005    Aggr_cmode   online     DP         25TB    10.67TB   57%
vsd       dstFG__0006    aggr1        online     DP         25TB    10.64TB   57%
vsd       dstFG__0007    Aggr_cmode   online     DP         25TB    10.63TB   57%
...
----


. ジョブスケジュールを作成します。 'job schedule cron create -name job_name -month -dayofweek day-of-week day-of-month-day day-of-month -hour hour-hour minute'
+
「 -month 」、「 -dayofweek 」、「 -hour 」の各オプションに「 all 」を指定すると、毎月、毎日、および 1 時間ごとにジョブを実行できます。

+
次の例は、土曜日の午前 3 時に実行する「 my_weekly 」というジョブスケジュールを作成します。

+
[listing]
----
cluster1::> job schedule cron create -name my_weekly -dayofweek "Saturday" -hour 3 -minute 0
----
. SnapMirror 関係に「 async-mirror 」タイプのカスタムポリシーを作成します。「 snapmirror policy create -vserver svm_name -policy snapmirror_policy-type async-mirror
+
カスタムポリシーを作成しない場合は、 SnapMirror 関係に「 MirrorAllSnapshots 」ポリシーを指定する必要があります。

. デスティネーションクラスタから、ソース FlexGroup ボリュームとデスティネーション FlexGroup ボリュームの間に SnapMirror 関係を作成します。「 snapmirror create -source-path src_svm ： src_flexgroup -destination-path dest_SVM ： dest_flexgroup -type XDP -policy snapmirror_policy -scheduled_name
+
FlexGroup ボリュームの SnapMirror 関係のタイプは「 xdp 」でなければなりません。

+
FlexGroup ボリュームの SnapMirror 関係にスロットル値を指定した場合、各コンスティチュエントに同じスロットル値が使用されます。スロットル値はコンスティチュエント間で分配されません。

+
[NOTE]
====
FlexGroup ボリュームでは、 Snapshot コピーの SnapMirror ラベルは使用できません。

====
+
ONTAP 9.4 以前では、「 snapmirror create 」コマンドでポリシーを指定しなかった場合、デフォルトで「 MirrorAllSnapshots 」ポリシーが使用されます。ONTAP 9.5 では、「 snapmirror create 」コマンドでポリシーが指定されていない場合、デフォルトで「 M irroresstons 」ポリシーが使用されます。

+
[listing]
----
cluster2::> snapmirror create -source-path vss:srcFG -destination-path vsd:dstFG -type XDP -policy MirrorAllSnapshots -schedule hourly
Operation succeeded: snapmirror create for the relationship with destination "vsd:dstFG".
----
. デスティネーションクラスタから、ベースライン転送を実行して SnapMirror 関係を初期化します。「 snapmirror initialize -destination-path dest_SVM ： dest_flexgroup
+
ベースライン転送の完了後は、 SnapMirror 関係のスケジュールに基づいて定期的にデスティネーション FlexGroup ボリュームが更新されます。

+
[listing]
----
cluster2::> snapmirror initialize -destination-path vsd:dstFG
Operation is queued: snapmirror initialize of destination "vsd:dstFG".
----
+
[NOTE]
====
ONTAP 9.3 を実行しているソースクラスタと ONTAP 9.2 以前を実行しているデスティネーションクラスタの FlexGroup ボリューム間に SnapMirror 関係を作成した場合、ソース FlexGroup ボリュームに qtree を作成すると SnapMirror の更新が失敗します。この状況からリカバリするには、 FlexGroup ボリューム内のデフォルト以外のすべての qtree を削除し、 FlexGroup ボリュームの qtree 機能を無効にしてから、 qtree 機能で有効化されたすべての Snapshot コピーを削除する必要があります。FlexGroup ボリュームで qtree 機能を有効にしている場合、 ONTAP 9.3 から以前のバージョンの ONTAP にリバートする前に以下の手順も実行する必要があります。  https://docs.netapp.com/us-en/ontap/revert/task_disabling_qtrees_in_flexgroup_volumes_before_reverting.html["リバート前に FlexGroup ボリュームの qtree 機能を無効にする"]

====


LIF やエクスポートポリシーなどの必要な設定を行って、デスティネーション SVM のデータアクセスを設定します。
