---
permalink: flexgroup/create-task.html 
sidebar: sidebar 
keywords: create, flexgroup, volume, flex group, aggregate, fabricpool, fabric pool 
summary: FlexGroupを作成するには、FlexGroupを作成するアグリゲートを手動で選択し、各アグリゲートのコンスティチュエントの数を指定します。 
---
= FlexGroupボリュームを作成する
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
FlexGroupを作成するには、FlexGroupを作成するアグリゲートを手動で選択し、各アグリゲートのコンスティチュエントの数を指定します。

.タスクの内容
FlexGroupボリュームを作成するためにアグリゲート内に必要なスペースを確認しておく必要があります。

FlexGroupボリュームを作成するときは、FlexGroupボリュームのパフォーマンスを最大限に高めるために、次のガイドラインを考慮する必要があります。

* FlexGroupボリュームは、同一のハードウェアシステム上にあるアグリゲートのみにまたがる必要があります。
+
同一のハードウェアシステムを使用すると、FlexGroupボリューム全体で予測可能なパフォーマンスを提供できます。

* FlexGroupボリュームは、ディスクタイプおよびRAIDグループ構成が同じアグリゲートで構成されている必要があります。
+
一貫したパフォーマンスを実現するには、すべてのアグリゲートがSSD、HDD、またはハイブリッドアグリゲートで構成されている必要があります。また、アグリゲートのドライブ数とRAIDグループ数は、FlexGroupボリューム全体で同じである必要があります。

* FlexGroupボリュームは、クラスタの一部にまたがることができます。
+
FlexGroupボリュームをクラスタ全体にまたがるように設定する必要はありませんが、その場合、使用可能なハードウェアリソースをより有効に活用できます。

* FlexGroupボリュームを作成するときは、FlexGroupボリュームを導入するアグリゲートに次の特性があることを推奨します。
+
** シンプロビジョニングを使用する場合は特に、複数のアグリゲート間でほぼ同じ量の空きスペースを使用できます。
** FlexGroup ボリュームの作成後に、空きスペースの約 3% がアグリゲートメタデータ用に確保される。


* FASシステムの場合は、ノードごとに2つのアグリゲートを使用することを推奨します。AFFシステムの場合は、FlexGroupのノードごとに1つのアグリゲートを使用する必要があります。
* FlexGroupボリュームごとに少なくとも8つのコンスティチュエントを作成し、FASシステムの場合は2つ以上のアグリゲートに、AFFシステムの場合は1つ以上のアグリゲートに分散します。


.開始する前に
* ONTAP 9.13.1以降では、容量分析とアクティビティ追跡を有効にしてボリュームを作成できます。容量またはアクティビティの追跡を有効にするには、を指定してコマンドを `-analytics-state`実行する `volume create`か、 `-activity-tracking-state`に設定します `on`。
+
容量分析とアクティビティ追跡の詳細については、を参照してください https://docs.netapp.com/us-en/ontap/task_nas_file_system_analytics_enable.html["ファイルシステム分析を有効にする"]。の詳細については `volume create`、をlink:https://docs.netapp.com/us-en/ontap-cli/volume-create.html["ONTAPコマンド リファレンス"^]参照してください。



.手順
. FlexGroupボリュームを作成します。 `volume create -vserver svm_name -volume flexgroup_name -aggr-list aggr1,aggr2,.. -aggr-list-multiplier constituents_per_aggr -size fg_size [–encrypt true] [-qos-policy-group qos_policy_group_name]`
+
** パラメータは `-aggr-list`、FlexGroupボリュームのコンスティチュエントに使用するアグリゲートのリストを指定します。
+
リスト内の各エントリによって、指定したアグリゲート上にコンスティチュエントが1つ作成されます。同じアグリゲートを複数回指定すると、そのアグリゲート上に複数のコンスティチュエントを作成できます。

+
FlexGroupボリューム全体で一貫したパフォーマンスが得られるように、ディスク タイプとRAIDグループ構成をすべてのアグリゲートで同じにする必要があります。

** パラメータは `-aggr-list-multiplier`、FlexGroupボリュームの作成時にパラメータで指定したアグリゲートを繰り返し実行する回数を指定します `-aggr-list`。
+
パラメータのデフォルト値 `-aggr-list-multiplier`は4です。

** パラメータは `size`、FlexGroupボリュームのサイズ（KB、MB、GB、TB、またはPB）を指定します。
** ONTAP 9.5 以降では、オール SSD アグリゲートのみを使用する FabricPool 用の FlexGroup ボリュームを作成できます。
+
FabricPool用のFlexGroupを作成するには、パラメータで指定するすべてのアグリゲート `-aggr-list`がFabricPoolである必要があります。FabricPoolのボリュームギャランティは常にに設定する必要があります `none`。FlexGroupボリュームに対して階層化ポリシーと階層化の最小クーリング期間を指定することもできます。

+
xref:../disks-aggregates/index.html[ディスクおよびアグリゲートの管理]

** ONTAP 9 .4以降では、FlexGroupボリュームにスループットの下限（最小QoS）とアダプティブQoSを指定できます。
+
link:../performance-admin/index.html["パフォーマンス管理"]

** ONTAP 9 .3以降では、FlexGroupボリュームにスループットの上限（最大QoS）を指定して、FlexGroupボリュームで消費できるパフォーマンスリソースを制限できます。
** ONTAP 9 .2以降では、FlexGroupボリュームで暗号化を有効にする場合、パラメータをに `true`設定でき `-encrypt`ます。
+
暗号化されたボリュームを作成するには、ボリューム暗号化ライセンスとキー管理ツールをインストールしておく必要があります。

+
[NOTE]
====
暗号化はFlexGroupボリュームの作成時に有効にする必要があります。既存のFlexGroupボリュームで暗号化を有効にすることはできません。

====
+
link:../encryption-at-rest/index.html["保存データの暗号化"]



+
[listing]
----
cluster-1::> volume create -vserver vs0 -volume fg2 -aggr-list aggr1,aggr2,aggr3,aggr1 -aggr-list-multiplier 2 -size 500TB

Warning: A FlexGroup "fg2" will be created with the following number of constituents of size 62.50TB: 8.
Do you want to continue? {y|n}: y

[Job 43] Job succeeded: Successful
----


この例では、FabricPoolのFlexGroupボリュームを作成する場合、すべてのアグリゲート（aggr1、aggr2、aggr3）がFabricPool内のアグリゲートである必要があります。ジャンクションパスを使用してFlexGroupボリュームをマウントします。 `volume mount -vserver vserver_name -volume vol_name -junction-path junction_path`

[listing]
----
cluster1::> volume mount -vserver vs0 -volume fg2 -junction-path /fg
----
.終了後
FlexGroupボリュームはクライアントからマウントする必要があります。

ONTAP 9 .6以前を実行していて、Storage Virtual Machine（SVM）でNFSv3とNFSv4の両方が設定されている場合、クライアントからのFlexGroupボリュームのマウントが失敗することがあります。その場合は、クライアントからFlexGroupをマウントするときに、NFSのバージョンを明示的に指定する必要があります。

[listing]
----
# mount -t nfs -o vers=3 192.53.19.64:/fg /mnt/fg2
# ls /mnt/fg2
file1  file2
----
.関連情報
https://www.netapp.com/pdf.html?item=/media/12385-tr4571pdf.pdf["NetAppテクニカルレポート4571：『NetApp FlexGroupベストプラクティスおよび実装ガイド』"^]
