---
permalink: flexgroup/create-svm-disaster-recovery-relationship-task.html 
sidebar: sidebar 
keywords: create, svm, disaster, recovery, svm dr, svm-dr, relationship, flexgroup, volume, flex group, flexclone, flex clone 
summary: FlexGroupボリュームを使用してSVM災害復旧（SVM DR）関係を作成し、冗長性を提供し、災害発生時にボリュームを復旧することができます。 
---
= ONTAP FlexGroupボリュームのSVMディザスタリカバリ関係を作成する
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
ONTAP 9.9.1以降では、FlexGroupボリュームを使用してSVMディザスタリカバリ（SVM DR）関係を作成できます。SVM DR関係は、SVM構成とそのデータを同期および複製することで冗長性を確保し、災害発生時にFlexGroupボリュームをリカバリする機能を提供します。SVM DRにはSnapMirrorライセンスが必要です。

.開始する前に
FlexGroup SVM DR関係は、以下の場合には作成できません。

* FlexClone FlexGroup構成が存在する。
* FlexGroupボリュームがカスケード関係の一部である。
* FlexGroupボリュームがファンアウト関係の一部であり、クラスタでONTAP 9.12.1より前のバージョンのONTAPが実行されている。（ONTAP 9.13.1以降では、ファンアウト関係がサポートされます）。


.タスク概要
* 両方のクラスタのすべてのノードで、SVM DRがサポートされる同じバージョンのONTAP（ONTAP 9.9.1以降）が実行されている必要があります。
* プライマリ サイトとセカンダリ サイトの間のSVM DR関係が健全で、プライマリとセカンダリ両方のSVMにFlexGroupボリューム用の十分なスペースがある必要があります。
* ONTAP 9.12.1以降では、FabricPool、FlexGroup、SVM DRを連携させることができます（ONTAP 9.12.1より前のリリースでは、これらの機能のうち2つを同時に使用できましたが、3つすべてを同時に使用することはできませんでした）。
* ファンアウト関係の一部であるFlexGroupボリュームでFlexGroup SVM DR関係を作成する場合は、以下の要件に注意してください。
+
** ソース クラスタとデスティネーション クラスタでONTAP 9.13.1以降が実行されている必要があります。
** FlexGroupボリュームを使用したSVM DRでは、8サイトへのSnapMirrorファンアウト関係がサポートされます。




SVM DR 関係の作成については、link:../data-protection/snapmirror-svm-replication-workflow-concept.html["SnapMirror SVMレプリケーションの管理"]を参照してください。

.手順
. SVM DR関係を作成するか、既存の関係を使用します。
+
link:../data-protection/replicate-entire-svm-config-task.html["SVMの設定全体のレプリケート"]

. 必要な数のコンスティチュエントを含むFlexGroupボリュームをプライマリ サイトに作成します。
+
link:create-task.html["FlexGroupボリュームの作成"]。

+
FlexGroupとそのすべてのコンスティチュエントが作成されてから次の作業に進んでください。

. FlexGroupボリュームをレプリケートするには、セカンダリ サイトの SVM を更新します： `snapmirror update -destination-path destination_svm_name: -source-path source_svm_name:`
+
スケジュールされたSnapMirror更新がすでに存在するかどうかを確認するには、次のように入力します `snapmirror show -fields schedule`

. セカンダリ サイトから、SnapMirror関係が正常であることを確認します： `snapmirror show`
+
[listing]
----
cluster2::> snapmirror show
                                                                       Progress
Source            Destination Mirror  Relationship   Total             Last
Path        Type  Path        State   Status         Progress  Healthy Updated
----------- ---- ------------ ------- -------------- --------- ------- --------
vs1:        XDP  vs1_dst:     Snapmirrored
                                      Idle           -         true    -
----
. セカンダリ サイトから、新しいFlexGroupボリュームとその構成要素が存在することを確認します： `snapmirror show -expand`
+
[listing]
----
cluster2::> snapmirror show -expand
                                                                       Progress
Source            Destination Mirror  Relationship   Total             Last
Path        Type  Path        State   Status         Progress  Healthy Updated
----------- ---- ------------ ------- -------------- --------- ------- --------
vs1:        XDP  vs1_dst:     Snapmirrored
                                      Idle           -         true    -
vs1:fg_src  XDP  vs1_dst:fg_src
                              Snapmirrored
                                      Idle           -         true    -
vs1:fg_src__0001
            XDP  vs1_dst:fg_src__0001
                              Snapmirrored
                                      Idle           -         true    -
vs1:fg_src__0002
            XDP  vs1_dst:fg_src__0002
                              Snapmirrored
                                      Idle           -         true    -
vs1:fg_src__0003
            XDP  vs1_dst:fg_src__0003
                              Snapmirrored
                                      Idle           -         true    -
vs1:fg_src__0004
            XDP  vs1_dst:fg_src__0004
                              Snapmirrored
                                      Idle           -         true    -
6 entries were displayed.
----


.関連情報
* link:https://docs.netapp.com/us-en/ontap-cli/snapmirror-show.html["snapmirror show"^]
* link:https://docs.netapp.com/us-en/ontap-cli/snapmirror-update.html["snapmirror update"^]

