---
permalink: flexgroup/create-svm-disaster-recovery-relationship-task.html 
sidebar: sidebar 
keywords: create, svm, disaster, recovery, relationship, flexgroup, volume, flex group, flexclone, flex clone 
summary: ONTAP 9.9.9以降では、FlexGroup ボリュームを使用してSVMディザスタリカバリ（SVM DR）関係を作成できます。SVM DR 関係は、 SVM の設定とそのデータを同期およびレプリケートすることで、災害発生時に冗長性を確保し、 FlexGroup をリカバリする機能を提供します。SVM DR には SnapMirror ライセンスが必要です。 
---
= FlexGroup ボリュームの SVM ディザスタリカバリ関係を作成します
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
ONTAP 9.9.9以降では、FlexGroup ボリュームを使用してSVMディザスタリカバリ（SVM DR）関係を作成できます。SVM DR 関係は、 SVM の設定とそのデータを同期およびレプリケートすることで、災害発生時に冗長性を確保し、 FlexGroup をリカバリする機能を提供します。SVM DR には SnapMirror ライセンスが必要です。

.作業を開始する前に
FlexGroup SVM DR 関係を作成できない場合は、次の条件に注意してください。

* FlexClone FlexGroup 設定が存在します
* FlexGroup ボリュームには FabricPool 構成が含まれています
* FlexGroup ボリュームは、ファンアウト関係またはカスケード関係の一部です


.このタスクについて
* 両方のクラスタのすべてのノードで、 SVM DR がサポートされているノードと同じバージョンの ONTAP を実行している必要があります（ ONTAP 9.9.1 以降）。
* プライマリサイトとセカンダリサイト間の SVM DR 関係が正常であり、 FlexGroup ボリュームをサポートするための十分なスペースがプライマリとセカンダリの両方の SVM に必要です。


SVM DR 関係の作成の詳細については、を参照してください https://docs.netapp.com/us-en/ontap/data-protection/snapmirror-svm-replication-workflow-concept.html["SnapMirror SVM レプリケーションを管理します"]。

.手順
. SVM DR 関係を作成するか、既存の関係を使用します。
+
https://docs.netapp.com/us-en/ontap/data-protection/replicate-entire-svm-config-task.html["SVM の設定全体をレプリケート"]

. 必要な数のコンスティチュエントを含む FlexGroup ボリュームをプライマリサイトに作成します。
+
link:create-task.html["FlexGroup ボリュームを作成します"]。

+
FlexGroup とそのすべてのコンスティチュエントが作成されるまで待ってから次に進みます。

. FlexGroup ボリュームをレプリケートするには、セカンダリサイトのSVMを更新します。 `snapmirror update -destination-path destination_svm_name: -source-path source_svm_name:`+スケジュールされたSnapMirror更新がすでに存在するかどうかを確認するには、を入力します `snapmirror show -fields schedule`
. セカンダリサイトで、SnapMirror関係が正常であることを確認します。 `snapmirror show`
+
[listing]
----
cluster2::> snapmirror show
                                                                       Progress
Source            Destination Mirror  Relationship   Total             Last
Path        Type  Path        State   Status         Progress  Healthy Updated
----------- ---- ------------ ------- -------------- --------- ------- --------
vs1:        XDP  vs1_dst:     Snapmirrored
                                      Idle           -         true    -
----
. セカンダリサイトで、新しいFlexGroup ボリュームとそのコンスティチュエントが存在することを確認します。 `snapmirror show -expand`
+
[listing]
----
cluster2::> snapmirror show -expand
                                                                       Progress
Source            Destination Mirror  Relationship   Total             Last
Path        Type  Path        State   Status         Progress  Healthy Updated
----------- ---- ------------ ------- -------------- --------- ------- --------
vs1:        XDP  vs1_dst:     Snapmirrored
                                      Idle           -         true    -
vs1:fg_src  XDP  vs1_dst:fg_src
                              Snapmirrored
                                      Idle           -         true    -
vs1:fg_src__0001
            XDP  vs1_dst:fg_src__0001
                              Snapmirrored
                                      Idle           -         true    -
vs1:fg_src__0002
            XDP  vs1_dst:fg_src__0002
                              Snapmirrored
                                      Idle           -         true    -
vs1:fg_src__0003
            XDP  vs1_dst:fg_src__0003
                              Snapmirrored
                                      Idle           -         true    -
vs1:fg_src__0004
            XDP  vs1_dst:fg_src__0004
                              Snapmirrored
                                      Idle           -         true    -
6 entries were displayed.
----

