---
permalink: flexgroup/create-unified-data-protection-relationship-task.html 
sidebar: sidebar 
keywords: create, unified, data, protection, relationship, flexgroup, volume, snap shot, snapshot, policy, policies, mirrorandvault, mirror-vault, mirrorallsnapshot, back up, backup, snapvault, snap vault 
summary: ONTAP 9.3以降では、SnapMirrorの一元化されたデータ保護関係を作成して設定することで、同じデスティネーション ボリュームにディザスタ リカバリとアーカイブを設定できます。 
---
= ONTAP FlexGroupボリュームの統合データ保護関係を作成する
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
ONTAP 9.3以降では、SnapMirrorの一元化されたデータ保護関係を作成して設定することで、同じデスティネーション ボリュームにディザスタ リカバリとアーカイブを設定できます。

.開始する前に
FlexGroupボリュームの一元化されたデータ保護関係の作成に関する考慮事項を確認しておく必要があります。

link:snapvault-backup-concept.html["FlexGroupボリュームのSnapVaultバックアップ関係および一元化されたデータ保護関係の作成に関する考慮事項"]

.手順
. ソースFlexGroupボリュームと同じ数の構成要素を持つタイプ `DP`のデスティネーションFlexGroupボリュームを作成します。
+
.. ソース クラスタから、ソースFlexGroupボリューム内のコンスティチュエントの数を確認します。 `volume show -volume volume_name* -is-constituent true`
+
[listing]
----
cluster1::> volume show  -volume srcFG* -is-constituent true
Vserver   Volume         Aggregate    State      Type       Size  Available  Used%
--------- ------------   ------------ ---------- ---- ----------  ---------- -----
vss       srcFG          -            online     RW         400TB   172.86GB  56%
vss       srcFG__0001    Aggr_cmode   online     RW         25GB    10.86TB   56%
vss       srcFG__0002    aggr1        online     RW         25TB    10.86TB   56%
vss       srcFG__0003    Aggr_cmode   online     RW         25TB    10.72TB   57%
vss       srcFG__0004    aggr1        online     RW         25TB    10.73TB   57%
vss       srcFG__0005    Aggr_cmode   online     RW         25TB    10.67TB   57%
vss       srcFG__0006    aggr1        online     RW         25TB    10.64TB   57%
vss       srcFG__0007    Aggr_cmode   online     RW         25TB    10.63TB   57%
...
----
.. デスティネーション クラスタから、ソースFlexGroupボリュームと同じ数の構成要素を持つタイプ `DP`のデスティネーションFlexGroupボリュームを作成します。
+
[listing]
----
cluster2::> volume create -vserver vsd -aggr-list aggr1,aggr2 -aggr-list-multiplier 8 -size 400TB -type DP dstFG

Warning: The FlexGroup volume "dstFG" will be created with the following number of constituents of size 25TB: 16.
Do you want to continue? {y|n}: y
[Job 766] Job succeeded: Successful
----
.. デスティネーション クラスタから、デスティネーションFlexGroupボリューム内の構成要素の数を確認します： `volume show -volume volume_name* -is-constituent true`
+
[listing]
----
cluster2::> volume show  -volume dstFG* -is-constituent true
Vserver   Volume       Aggregate    State      Type       Size  Available Used%
--------- ------------ ------------ ---------- ---- ---------- ---------- -----
vsd       dstFG          -            online     RW         400TB   172.86GB  56%
vsd       dstFG__0001    Aggr_cmode   online     RW         25GB    10.86TB   56%
vsd       dstFG__0002    aggr1        online     RW         25TB    10.86TB   56%
vsd       dstFG__0003    Aggr_cmode   online     RW         25TB    10.72TB   57%
vsd       dstFG__0004    aggr1        online     RW         25TB    10.73TB   57%
vsd       dstFG__0005    Aggr_cmode   online     RW         25TB    10.67TB   57%
vsd       dstFG__0006    aggr1        online     RW         25TB    10.64TB   57%
vsd       dstFG__0007    Aggr_cmode   online     RW         25TB    10.63TB   57%
...
----


. ジョブスケジュールを作成します： `job schedule cron create -name job_name -month month -dayofweek day_of_week -day day_of_month -hour hour -minute minute`
+
 `-month`、 `-dayofweek`、および `-hour`オプションでは、 `all`を指定して、それぞれ毎月、毎週毎日、および毎時間ジョブを実行できます。

+
次の例では、土曜日の午前3：00に実行される `my_weekly`という名前のジョブ スケジュールを作成します：

+
[listing]
----
cluster1::> job schedule cron create -name my_weekly -dayofweek "Saturday" -hour 3 -minute 0
----
. タイプ `mirror-vault`のカスタム ポリシーを作成し、ミラーおよびボールト ポリシーのルールを定義します：
+
.. 統合データ保護関係のタイプ `mirror-vault`のカスタム ポリシーを作成します： `snapmirror policy create -vserver svm_name -policy policy_name -type mirror-vault`
.. 初期化および更新処理中に転送されるSnapshotを決定するミラーおよびバックアップ ポリシーのルールを定義します： `snapmirror policy add-rule -vserver svm_name -policy policy_for_rule - snapmirror-label snapmirror-label -keep retention_count -schedule schedule`


+
カスタム ポリシーを指定しない場合は、統合データ保護関係に `MirrorAndVault`ポリシーが使用されます。

. 統一されたデータ保護関係を作成します： `snapmirror create -source-path src_svm:src_flexgroup -destination-path dest_svm:dest_flexgroup -type XDP -schedule schedule_name -policy MirrorAndVault`
+
ONTAP 9.4以前では、 `snapmirror create`コマンドでポリシーを指定しない場合は、 `MirrorAllSnapshots`ポリシーがデフォルトで使用されます。ONTAP 9.5では、 `snapmirror create`コマンドでポリシーを指定しない場合は、 `MirrorAndVault`ポリシーがデフォルトで使用されます。

+
[listing]
----
cluster2::> snapmirror create -source-path vss:srcFG -destination-path vsd:dstFG -type XDP -schedule Daily -policy MirrorAndVault
----
+
 `snapmirror create`の詳細については、link:https://docs.netapp.com/us-en/ontap-cli/snapmirror-create.html["ONTAPコマンド リファレンス"^]を参照してください。

. デスティネーション クラスタから、ベースライン転送を実行してユニファイド データ保護関係を初期化します： `snapmirror initialize -destination-path dest_svm:dest_flexgroup`
+
[listing]
----
cluster2::> snapmirror initialize -destination-path vsd:dstFG
Operation is queued: snapmirror initialize of destination "vsd:dstFG".
----


.関連情報
* link:https://docs.netapp.com/us-en/ontap-cli/snapmirror-create.html["snapmirror create"^]
* link:https://docs.netapp.com/us-en/ontap-cli/snapmirror-initialize.html["snapmirror initialize"^]
* link:https://docs.netapp.com/us-en/ontap-cli/snapmirror-policy-add-rule.html["snapmirror policy add-rule"^]
* link:https://docs.netapp.com/us-en/ontap-cli/snapmirror-policy-create.html["snapmirror policy create"^]

