---
permalink: flexgroup/enable-file-system-analytics-task.html 
sidebar: sidebar 
keywords: monitor, volume, ontap, file, system, analytics 
summary: この記事では、 CLI で容量分析やアクティビティ追跡などのファイルシステム分析機能を有効にして使用する方法について説明します。 
---
= File System Analytics を有効にします
:icons: font
:imagesdir: ../media/


[role="lead"]
File System Analytics フレームワークを使用すると、データの使用状況を監視できます。この記事では、容量分析のためにファイルシステム分析を有効にし、使用頻度の低いデータを監視して有効にする方法について説明します <<Activity Tracking>>。



== File System Analytics の略

ファイルシステム分析は、新しい FlexGroup または FlexVol ボリュームを作成するとき、またはシステムを ONTAP 9.8 以降にアップグレードするときに有効にできます。アップグレード後は、分析を有効にする前に、すべてのアップグレードプロセスが完了していることを確認してください。

ボリュームのサイズと内容によっては、 ONTAP がボリューム内の既存のデータを処理するまでに時間がかかることがあります。

.ステップ
. ファイルシステム分析を有効化：
+
'volume analytics on -vserver_svm_name_-volume_name_[-foreground {true|false }]

+
デフォルトでは、このコマンドはフォアグラウンドで実行されます。 ONTAP は進捗状況を表示し、完了すると分析データを表示します。より正確な情報が必要な場合は、「 -foreground false 」オプションを使用してバックグラウンドでコマンドを実行し、「 volume analytics show 」コマンドを使用して初期化の進行状況を表示できます。





== アクティビティの追跡

ONTAP 9.10.1 以降では、アクティビティ追跡を有効にして、ボリューム上の高トラフィックおよび高スループットアクティビティに関する情報を表示できます。

.ステップ
. アクティビティトラッキングを有効にする：
+
'volume activity tracking on -vsverver_svm_name_-volume_name_`

+
ボリュームのアクティビティ追跡状態がオンであるかオフであるかは、コマンドを使用して確認できます。

+
volume activity -tracking show -vsverver_svm_name -- volume_volume_name --state`



分析またはアクティビティ追跡のデータを表示するには、 ONTAP System Manager または ONTAP REST API を使用します。
