---
permalink: flexgroup/enable-storage-efficiency-task.html 
sidebar: sidebar 
keywords: enable, storage, efficiency, flexgroup, volume 
summary: 重複排除とデータ圧縮をFlexGroupボリューム上で一緒に、または個別に実行して、最適なスペース節約を実現できます。 
---
= ONTAP FlexGroupボリュームでストレージ効率を有効にする
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
重複排除とデータ圧縮をFlexGroupボリューム上で一緒に、または個別に実行して、最適なスペース節約を実現できます。

.開始する前に
FlexGroupはオンラインである必要があります。

.手順
. FlexGroupボリュームのストレージ効率を有効にします： `volume efficiency on -vserver svm_name -volume volume_name`
+
ストレージ効率化処理は、FlexGroupボリュームのすべてのコンスティチュエントで有効になります。

+
FlexGroupボリュームでストレージ効率を有効にした後にボリュームを拡張すると、新しいコンスティチュエントでストレージ効率が自動的に有効になります。

.  `volume efficiency modify`コマンドを使用して、FlexGroupボリューム上で必要なストレージ効率操作を有効にします。
+
FlexGroupボリュームに対して、インライン重複排除、ポストプロセス重複排除、インライン圧縮、およびポストプロセス圧縮を有効にできます。また、圧縮の種類（セカンダリまたはアダプティブ）を設定し、FlexGroupボリュームのスケジュールまたは効率化ポリシーを指定することもできます。

. ストレージ効率化処理の実行にスケジュールまたは効率化ポリシーを使用していない場合は、効率化処理を開始します： `volume efficiency start -vserver svm_name -volume volume_name`
+
ボリュームで重複排除とデータ圧縮が有効になっている場合、最初にデータ圧縮が実行され、その後重複排除が実行されます。FlexGroup ボリューム上で既に効率化操作が実行されている場合、このコマンドは失敗します。

. FlexGroupボリュームで有効になっている効率化処理を確認します： `volume efficiency show -vserver svm_name -volume volume_name`
+
[listing]
----
cluster1::> volume efficiency show -vserver vs1 -volume fg1
             Vserver Name: vs1
              Volume Name: fg1
              Volume Path: /vol/fg1
                    State: Enabled
                   Status: Idle
                 Progress: Idle for 17:07:25
                     Type: Regular
                 Schedule: sun-sat@0

...

             Compression: true
      Inline Compression: true
Incompressible Data Detection: false
      Constituent Volume: false
Compression Quick Check File Size: 524288000
           Inline Dedupe: true
         Data Compaction: false
----

