---
permalink: flexgroup/increase-capacity-task.html 
sidebar: sidebar 
keywords: increase, size, flexgroup, volume, flex group 
summary: ボリュームの既存の構成要素に容量を追加するか、新しいメンバーボリュームでFlexGroupボリュームを拡張して、FlexGroupボリュームサイズを増やします。 
---
= ONTAP FlexGroupボリュームのサイズを増やす
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
FlexGroupボリュームのサイズを増やすには、FlexGroupボリュームを構成する既存のすべてのメンバーボリューム（構成要素）に容量を追加するか、FlexGroupボリュームに新しいメンバーボリュームを追加して拡張します。FlexGroupボリュームには200を超えるメンバーボリュームを含めることはできません。

必要に応じて、FlexGroupボリューム内の個々のボリュームのサイズを増やすこともできます。

.開始する前に
アグリゲートに十分なスペースが必要です。

.タスク概要
より多くのスペースを追加したい場合は、FlexGroupボリューム全体のサイズを増やすことができます。FlexGroupボリュームのサイズを増やすと、そのFlexGroupボリュームを構成する既存のメンバーボリュームのサイズも変更されます。

パフォーマンスを向上させたい場合は、FlexGroupボリュームを拡張することができます。次のような状況では、FlexGroupボリュームを拡張して新しいメンバーボリュームを追加することを検討してください：

* クラスタに新しいノードが追加された。
* 既存のノードに新しいローカル階層（アグリゲート）が作成されました。
* FlexGroupボリュームの既存のメンバーボリュームがFlexVolのハードウェアの最大サイズ（100TB、またはlink:../volumes/enable-large-vol-file-support-task.html["大容量サポート"]が有効な場合は300TB）に達したため、追加のメンバーボリュームを追加せずにFlexGroupボリュームのサイズを変更することはできません。


[NOTE]
====
FlexGroupボリュームを変更してメンバーを追加すると、以前に作成されたスナップショットは「部分的」とみなされ、 `.snapshot`ディレクトリまたは*Previous Versions*タブからクライアントがアクセスできるようになります。

スナップショットが「部分的」とみなされる場合、SnapRestore操作には使用できません。ただし、部分的なスナップショットは `.snapshot`ディレクトリまたは*Previous Versions*タブから個々のファイルを復元するために使用できます。

====
ONTAP 9.3 より前のリリースでは、SnapMirror 関係が確立された後に FlexGroup ボリュームを拡張しないでください。ONTAP 9.3 より前のリリースで SnapMirror 関係を解除した後にソースの FlexGroup ボリュームを拡張した場合は、再度ベースライン転送を宛先の FlexGroup ボリュームに対して実行する必要があります。ONTAP 9.3 以降では、SnapMirror 関係にある FlexGroup ボリュームを拡張できます。

.手順
. 必要に応じて、FlexGroupに容量またはパフォーマンスを追加し、FlexGroupボリュームのサイズを増やします。
+
|===


| ...を増やしたい場合 | 操作 


 a| 
FlexGroupボリュームの容量
 a| 
FlexGroupボリュームのすべてのメンバーボリュームのサイズを変更します：

`volume modify -vserver <svm_name> -volume <fg_name> -size <new_size>`



 a| 
FlexGroupボリュームのパフォーマンス
 a| 
新しいメンバーボリューム（構成要素）を追加してFlexGroupボリュームを拡張します：

`+volume expand -vserver vserver_name -volume fg_name -aggr-list aggregate name,... [-aggr-list-multiplier constituents_per_aggr]+`

 `-aggr-list-multiplier`パラメータのデフォルト値は1です。

link:../fabricpool/index.html["FabricPool"]を使用してFlexGroupボリュームを拡張する場合、すべてのローカル層（アグリゲート）を同じクラウド層に接続する必要があります。

|===


既存のアグリゲート（ローカル層）またはメンバーボリュームが最大容量（それぞれ100/300TBまたは20億ファイル）に達していない場合は、メンバーボリュームを追加するのではなく、FlexGroupボリュームの全体的なサイズを増やすことをお勧めします。

ボリューム拡張は、既存のボリュームのサイズやファイル数を増やすことができない場合、またはFlexGroupが新しいハードウェアに拡張される場合にのみ使用してください。一貫したパフォーマンスを確保するには、すべてのノードに同じ数のメンバーボリュームを追加する必要があります。たとえば、既存のFlexGroupボリュームに8つのメンバーボリュームがあり、ノードごとに4つのメンバーボリュームがある場合、ノードごとに2つのメンバーを追加すると、12のメンバーボリューム（ノードごとに6つのメンバーボリューム）になります。

新しいノードに新しいメンバーを追加する際は、既存のノードと同様に、ノードあたりのメンバーボリューム数を一定に保つようにしてください。例えば、既存のFlexGroupボリュームに8つのメンバーボリュームがあり、ノードあたり4つのメンバーボリュームがある場合、FlexGroupボリュームを新しいノードに拡張する際には、4つのメンバーボリュームを追加して、合計12メンバーのFlexGroupボリュームにする必要があります。

FlexGroupボリュームに新しいメンバーを追加すると、取り込みヒューリスティックが変更され、新しい空のメンバーボリュームが優先され、新しいメンバーボリュームが既存のメンバーボリュームとバランスが取れるまで、新しいデータ取り込みの全体的なシステムパフォーマンスに影響する可能性があります。

.例
*既存メンバーボリュームの容量を増やす例*

次の例は、FlexGroupボリュームvolXに20TBのスペースを追加します。

[listing]
----
cluster1::> volume modify -vserver svm1 -volume volX -size +20TB
----
FlexGroupボリュームに16個のメンバーボリュームがある場合、各メンバーボリュームのスペースは1.25TB増加します。

*新規メンバーボリュームの追加によるパフォーマンス向上の例*

次の例は、FlexGroup ボリュームの基盤となるローカル層（アグリゲート）のそれぞれに 2 つずつ、合計 4 つのメンバー ボリュームを追加する方法を示しています `fg1`：

[listing]
----
cluster1::> volume expand -vserver svm1 -volume fg1 -aggr-list aggr1,aggr2 -aggr-list-multiplier 2
----
新しいメンバーボリュームのサイズは、既存のメンバーボリュームのサイズと同じです。

.個々のボリュームのサイズを増やす
FlexGroupボリューム内の個々のメンバーボリュームのサイズを増やす場合は、 `volume resize`コマンドを使用できます。

.手順
. 単一FlexGroupメンバーボリュームのサイズを増やす：
+
`volume size -volume <volume_name> -vserver <svm1> -new-size <new_size>`

+
次の例では、FlexGroupメンバーボリューム FG_0003 のサイズを 3.7GB に増やします：

+
[listing]
----
volume size -volume FG__0003 -vserver svm1 -new-size 3.7GB
vol size: Volume "svm1:FG__0003" size set to 3.70g.
----

