---
permalink: flexgroup/manage-client-async-dir-delete-task.html 
sidebar: sidebar 
keywords: perform, directory, enable, delete, asynchronous, client rights, SMB, NFS, share, flexvol, flex vol, flexgroup, flex group 
summary: 'ONTAP 9.11.1以降、ストレージ管理者はボリュームに対する権限を付与することで、NFSおよびSMBクライアントが非同期削除操作を実行できるようにすることができます。非同期削除を有効にすると、NFSクライアントは `mv`コマンドを使用し、SMBクライアントは `rename`コマンドを使用して、指定されたボリューム上のディレクトリを削除し、そのディレクトリをデフォルトで.ontaptrashbinという名前の隠しディレクトリに移動することができます。' 
---
= FlexGroupsを使用してONTAPディレクトリを非同期的に削除するクライアント権限を管理する
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
ONTAP 9.11.1以降、ストレージ管理者はボリュームに対する権限を付与することで、NFSおよびSMBクライアントが非同期削除操作を実行できるようにすることができます。クラスタで非同期削除が有効になっている場合、Linuxクライアントユーザーは `mv`コマンドを使用し、Windowsクライアントユーザーは `rename`コマンドを使用して、指定されたボリューム上のディレクトリを、デフォルトで.ontaptrashbinという名前の隠しディレクトリに移動することで削除できます。

権限はボリュームごとに付与されます。NFSクライアントユーザーには、NFSクライアントに対するルートアクセス権と、NFSエクスポートに対するスーパーユーザーアクセス権が必要です。

移動できるのはディレクトリのみです。.ontaptrashbinディレクトリにファイルを移動することはできません。

link:fast-directory-delete-asynchronous-task.html#delete-directories-asynchronously["ONTAPを使用してFlexGroupボリュームからディレクトリを非同期的に削除する方法について説明します"]。



== クライアントによるディレクトリの非同期削除の有効化

.手順
. クラスタ CLI から、advanced 権限モードに入ります： `-privilege advance`
. ボリュームのマウントポイントでクライアントの非同期削除を有効にし、必要に応じて、ゴミ箱ディレクトリの別名を指定します：
+
`volume file async-delete client enable volume _volname_ vserver _vserverName_ trashbinname _name_`

+
デフォルトのごみ箱名を使用する例：

+
[listing]
----
cluster1::*> volume file async-delete client enable -volume v1 -vserver  vs0

Info: Async directory delete from the client has been enabled on volume "v1" in
      Vserver "vs0".
----
+
別のごみ箱名を使用する例：

+
[listing]
----
cluster1::*> volume file async-delete client enable -volume test -trashbin .ntaptrash -vserver vs1

Success: Async directory delete from the client is enabled on volume "v1" in
      Vserver "vs0".
----
. クライアントによる非同期削除が有効であることを確認します。
+
`volume file async-delete client show`

+
例：

+
[listing]
----
cluster1::*> volume file async-delete client show

Vserver Volume      async-delete client TrashBinName
------------ ------------ ----------------------- -------------
vs1          vol1         Enabled          .ntaptrash
vs2          vol2         Disabled          -

2 entries were displayed.
----




== クライアントによるディレクトリの非同期削除の無効化

.手順
. クラスタCLIで、クライアントによるディレクトリの非同期削除を無効にします。
+
`volume file async-delete client disable volume _volname_ vserver _vserverName_`

+
例：

+
[listing]
----
cluster1::*> volume file async-delete client disable -volume vol1 -vserver vs1

       Success: Asynchronous directory delete client disabled successfully on volume.
----
. クライアントによる非同期削除が無効であることを確認します。
+
`volume file async-delete client show`

+
例：

+
[listing]
----
cluster1::*> volume file async-delete client show

Vserver      Volume      async-delete client      TrashBinName
------------ ------------ ----------------------- -------------
vs1          vol1         Disabled                -
vs2          vol2         Disabled                -

2 entries were displayed.
----

