---
permalink: flexgroup/move-constituents-task.html 
sidebar: sidebar 
keywords: constituents, flexgroup, volume, flex group, balancing, balance, traffic, free, space, aggregate, snapmirror, snap mirror, 
summary: FlexGroupボリュームのコンスティチュエントをアグリゲート間で移動して、特定のコンスティチュエントのトラフィックが多い場合に負荷を分散することができます。コンスティチュエントを移動すると、既存のコンスティチュエントのサイズを変更するためにアグリゲートのスペースを解放することもできます。 
---
= ONTAP FlexGroupからのコンスティチュエントの移動
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
FlexGroupボリュームのコンスティチュエントをアグリゲート間で移動して、特定のコンスティチュエントのトラフィックが多い場合に負荷を分散することができます。コンスティチュエントを移動すると、既存のコンスティチュエントのサイズを変更するためにアグリゲートのスペースを解放することもできます。

.開始する前に
SnapMirror関係にあるFlexGroupボリュームコンスティチュエントを移動する場合は、SnapMirror関係を初期化しておく必要があります。

.タスクの内容
FlexGroupボリュームのコンスティチュエントの拡張中は、ボリューム移動処理を実行できません。

.手順
. 移動するFlexGroupボリュームコンスティチュエントを特定します。
+
`volume show -vserver svm_name -is-constituent true`

+
[listing]
----
cluster1::> volume show -vserver vs2 -is-constituent true
Vserver   Volume       Aggregate    State      Type       Size  Available Used%
--------- ------------ ------------ ---------- ---- ---------- ---------- -----
vs2       fg1          -            online     RW        400TB    15.12TB   62%
vs2       fg1__0001    aggr1        online     RW         25TB     8.12MB   59%
vs2       fg1__0002    aggr2        online     RW         25TB     2.50TB   90%
...
----
. FlexGroupボリュームコンスティチュエントの移動先となるアグリゲートを特定します。
+
`volume move target-aggr show -vserver svm_name -volume vol_constituent_name`

+
使用可能なスペースが移動するFlexGroupボリュームコンスティチュエントのサイズよりも大きいアグリゲートを選択する必要があります。

+
[listing]
----
cluster1::> volume move target-aggr show -vserver vs2 -volume fg1_0002
Aggregate Name   Available Size   Storage Type
--------------   --------------   ------------
aggr2            467.9TB          hdd
node12a_aggr3    100.34TB         hdd
node12a_aggr2    100.36TB         hdd
node12a_aggr1    100.36TB         hdd
node12a_aggr4    100.36TB         hdd
5 entries were displayed.
----
. FlexGroupボリュームコンスティチュエントを目的のアグリゲートに移動できることを確認します。
+
`volume move start -vserver svm_name -volume vol_constituent_name -destination-aggregate aggr_name -perform-validation-only true`

+
[listing]
----
cluster1::> volume move start -vserver vs2 -volume fg1_0002 -destination-aggregate node12a_aggr3 -perform-validation-only true
Validation succeeded.
----
. FlexGroupボリュームコンスティチュエントを移動します。
+
`volume move start -vserver svm_name -volume vol_constituent_name -destination-aggregate aggr_name [-allow-mixed-aggr-types {true|false}]`

+
ボリューム移動処理はバックグラウンドプロセスとして実行されます。

+
ONTAP 9 5以降では、パラメータをに `true`設定することで、FlexGroupボリュームコンスティチュエントをFabric Poolから非Fabric Poolに（またはその逆に）移動できます `-allow-mixed-aggr-types`。デフォルトでは、この `-allow-mixed-aggr-types`オプションはに設定されて `false`います。

+
[NOTE]
====
FlexGroupでは、コマンドを使用して暗号化を有効にすることはできません `volume move`。

====
+
[listing]
----
cluster1::> volume move start -vserver vs2 -volume fg1_002 -destination-aggregate node12a_aggr3
----
+
[NOTE]
====
アクティブなSnapMirror処理が原因でボリューム移動処理が失敗した場合は、コマンドを使用してSnapMirror処理を中止する必要があります `snapmirror abort -h`。場合によっては、SnapMirrorの中止処理も失敗することがあります。その場合は、ボリューム移動処理を中止してから再試行してください。の詳細については `snapmirror abort`、をlink:https://docs.netapp.com/us-en/ontap-cli/snapmirror-abort.html["ONTAPコマンド リファレンス"^]参照してください。

====
. ボリューム移動処理の状態を確認します。
+
`volume move show -volume vol_constituent_name`

+
次の例は、ボリューム移動処理のレプリケーションフェーズを完了し、カットオーバーフェーズにあるFlexGroupコンスティチュエントボリュームの状態を示しています。

+
[listing]
----
cluster1::> volume move show -volume fg1_002
Vserver   Volume     State    Move Phase  Percent-Complete Time-To-Complete
--------- ---------- -------- ----------  ---------------- ----------------
vs2       fg1_002    healthy  cutover     -                -
----

