---
permalink: flexgroup/provision-automatically-task.html 
sidebar: sidebar 
keywords: provision, flexgroup, volume, automatic, create, flex group, aggregate, space 
summary: FlexGroupボリュームを作成する際に、ONTAPがローカル階層（アグリゲート）を自動選択してFlexGroupボリュームをプロビジョニングするように設定できます。ローカル階層は、最適なパフォーマンスを実現するためのベストプラクティスに基づいて選択されます。 
---
= ONTAP FlexGroupボリュームを自動的にプロビジョニングする
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
FlexGroupボリュームを作成する際に、基盤となるローカル階層（アグリゲート）を選択することで、ONTAPによるFlexGroupボリュームの自動プロビジョニングを選択できます。ローカル階層は、最適なパフォーマンスと容量を実現するためのベスト プラクティスに基づいて選択されます。

.開始する前に
クラスター内の各ノードには、少なくとも 1 つのローカル層が必要です。

[NOTE]
====
非アクティブなデータを階層化するFlexGroupボリュームを作成する場合、各ノードにはFabricPoolが有効になっているローカル階層が少なくとも1つ必要です。

====
.タスク概要
ONTAPは、各ノード上で使用可能なスペースが最も大きい2つのローカル階層を選択してFlexGroupボリュームを作成します。2つのローカル階層が利用できない場合、ONTAPはノードごとに1つのローカル階層を選択してFlexGroupボリュームを作成します。

ONTAP 9.15.1以降、FlexGroupボリュームを自動プロビジョニングする場合、ONTAPはバランス配置（BP）を使用してローカル階層とFlexGroupメンバー（構成）ボリュームのレイアウトを選択します。BPの特徴の1つは、「none」保証（シンプロビジョニング）FlexGroupボリュームを作成する際に、ローカル階層のオーバープロビジョニングを制限することです。FlexGroupボリューム全体のサイズはローカル階層の空き容量によって制限されますが、この制限は「volume」保証（シックプロビジョニング）FlexGroupボリュームの場合よりも高くなります。REST APIまたは `auto-provision-as`ONTAP CLIを使用してFlexGroupボリュームを作成すると、この制限によりスペース不足のためにプロビジョニングが失敗する可能性があります。これを回避するには、より小さなFlexGroupボリュームを作成するか、link:create-task.html["FlexGroupボリュームを作成し、ローカル層を手動で選択する"] `aggr-list`パラメータを使用して作成します。

.手順
. FlexGroupボリュームをプロビジョニングします。
+
`volume create -vserver svm_name -volume fg_vol_name –auto-provision-as flexgroup -size fg_size [–encrypt true] [-qos-policy-group qos_policy_group_name] [-support-tiering true] [-granular-data advanced]`

+
ONTAP 9.16.1 以降では、link:enable-adv-capacity-flexgroup-task.html["高度な容量バランス調整"] (`-granular-data advanced`（CLI 内）を有効にして、ファイルが 10GB を超える場合に複数のFlexGroupメンバー ボリュームにわたってデータを書き込むことができます。

+
ONTAP 9.5以降、FabricPoolが有効なローカル階層上にFlexGroupボリュームを作成できます。FabricPoolが有効なローカル階層上にFlexGroupボリュームを自動的にプロビジョニングするには、 `-support-tiering`パラメータを `true`に設定する必要があります。FabricPoolの場合、ボリューム保証は常に `none`に設定する必要があります。FlexGroupボリュームの階層化ポリシーおよび階層化の最小クーリング期間も指定できます。

+
link:../disks-aggregates/index.html["ディスクおよびアグリゲートの管理"]

+
FlexGroupボリュームのスループット上限（QoS Max）を指定できます。これにより、FlexGroupボリュームが消費できるパフォーマンス リソースが制限されます。ONTAP 9.4以降では、FlexGroupボリュームのスループット下限（QoS Min）とアダプティブQoSを指定できます。

+
link:../performance-admin/index.html["パフォーマンス管理"]

+
FlexGroupボリュームで暗号化を有効にする場合は、 `-encrypt`パラメータを `true`に設定できます。暗号化されたボリュームを作成するには、ボリューム暗号化ライセンスとキー マネージャをインストールしておく必要があります。

+

NOTE: 暗号化はFlexGroupボリュームの作成時に有効にする必要があります。既存のFlexGroupボリュームで暗号化を有効にすることはできません。

+
link:../encryption-at-rest/index.html["保存中のデータを暗号化"]

+
 `size`パラメータは、FlexGroupボリュームのサイズをKB、MB、GB、TB、またはPBで指定します。

+
次の例は、サイズが400TBのFlexGroupボリュームをプロビジョニングする方法を示しています：

+
[listing]
----
cluster-1::> volume create -vserver vs0 -volume fg –auto-provision-as flexgroup -size 400TB
Warning: The FlexGroup "fg" will be created with the following number of constituents of size 25TB: 16.
The constituents will be created on the following aggregates: aggr1,aggr2
Do you want to continue? {y|n}: y
[Job 34] Job succeeded: Successful
----
+
次の例は、スループットの上限が設定されたQoSポリシー グループを作成してFlexGroupボリュームに適用する方法を示しています。

+
[listing]
----
cluster1::> qos policy-group create -policy group pg-vs1 -vserver vs1 -max-throughput 5000iops
----
+
[listing]
----
cluster-1::> volume create -vserver vs0 -volume fg –auto-provision-as flexgroup -size 400TB -qos-policy-group pg-vs1
Warning: The FlexGroup "fg" will be created with the following number of constituents of size 25TB: 16.
The constituents will be created on the following aggregates: aggr1,aggr2
Do you want to continue? {y|n}: y
[Job 34] Job succeeded: Successful
----
+
次の例は、FabricPoolが有効なローカル階層上に400 TBのFlexGroupボリュームをプロビジョニングする方法を示しています：

+
[listing]
----
cluster-1::> volume create -vserver vs0 -volume fg –auto-provision-as flexgroup -size 400TB -support-tiering true -tiering-policy auto
Warning: The FlexGroup "fg" will be created with the following number of constituents of size 25TB: 16.
The constituents will be created on the following aggregates: aggr1,aggr2
Do you want to continue? {y|n}: y
[Job 34] Job succeeded: Successful
----
+
FlexGroupボリュームは、クラスタ内の各ノードに8つのメンバー ボリュームで作成されます。メンバー ボリュームは、各ノードの2つの最大のローカル階層に均等に分散されます。

+
デフォルトでは、FlexGroupボリュームは `volume`スペースギャランティ設定で作成されます（AFFシステムを除く）。AFFシステムの場合、デフォルトではFlexGroupボリュームは `none`スペースギャランティで作成されます。

. FlexGroupボリュームをジャンクション パスにマウントします。
+
`volume mount -vserver vserver_name -volume vol_name -junction-path junction_path`

+
[listing]
----
cluster1::> volume mount -vserver vs0 -volume fg2 -junction-path /fg2
----


.終了後の操作
クライアントからFlexGroupボリュームをマウントします。

ONTAP 9.6以前のバージョンでは、Storage Virtual Machine（SVM）でNFSv3とNFSv4の両方が設定されている場合、クライアントからのFlexGroupボリュームのマウントが失敗することがあります。その場合は、クライアントからFlexGroupボリュームをマウントする際に、NFSバージョンを明示的に指定する必要があります。

[listing]
----
# mount -t nfs -o vers=3 192.53.19.64:/fg2 /mnt/fg2
# ls /mnt/fg2
file1  file2
----
.関連情報
* link:https://docs.netapp.com/us-en/ontap-cli/qos-policy-group-create.html["qos policy-group create"^]

