---
permalink: flexgroup/quota-reporting-task.html 
sidebar: sidebar 
keywords: quota, flexgroup, volume, flex group, limit, snap mirror, snapmirror, qtree, user, group 
summary: ONTAP 9.4以前では、FlexGroupボリュームにクォータ ルールを適用してもレポートの対象となるだけで、クォータ制限を適用することはできませんでした。ONTAP 9.5以降では、FlexGroupボリュームに対するクォータ ルールに制限を適用できます。 
---
= ONTAP FlexGroupボリュームのクォータを使用する
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
ONTAP 9.4以前では、FlexGroupボリュームにクォータ ルールを適用してもレポートの対象となるだけで、クォータ制限を適用することはできませんでした。ONTAP 9.5以降では、FlexGroupボリュームに対するクォータ ルールに制限を適用できます。

.タスク概要
* ONTAP 9.5以降では、FlexGroupボリュームにハード リミット、ソフト リミット、しきい値制限の各クォータを指定できます。
+
これらの制限を指定して、特定のユーザ / グループ / qtreeが使用 / 作成できるスペースの量、ファイル数、あるいはその両方を制限できます。クォータ制限を指定すると、以下の各状況で警告メッセージが生成されます。

+
** 使用量が設定されているソフト リミットを超えた場合、警告メッセージが表示されますが、後続のトラフィックは引き続き許可されます。
+
その後使用量がソフト リミットを再び下回ると、解決済みのメッセージが表示されます。

** 使用量が設定されているしきい値制限を超えた場合、2つ目の警告メッセージが表示されます。
+
その後使用量がしきい値制限を下回っても、解決済みのメッセージは表示されません。

** 使用量が設定されているハード リミットに達した場合、トラフィックが拒否されて、それ以降はリソースを消費できなくなります。


* ONTAP 9.5では、SnapMirror関係のデスティネーションFlexGroupボリュームでクォータ ルールを作成またはアクティブ化することができません。
* クォータの初期化中はクォータは適用されず、クォータの初期化後に超過したクォータに関する通知が生成されることはありません。
+
クォータ初期化中にクォータ違反が発生したかどうかを確認するには、 `volume quota report` コマンドを使用できます。





== クォータのターゲットとタイプ

クォータにはユーザ、グループ、またはqtreeの3種類のタイプがあります。クォータ ターゲットは、クォータ制限が適用されるユーザ、グループ、またはqtreeを指定します。

次の表に、クォータ ターゲットの種類、各クォータ ターゲットに関連付けられているクォータのタイプ、および各クォータ ターゲットの指定方法を示します。

|===


| クォータ ターゲット | クォータ タイプ | ターゲットの表現方法 | 注記 


 a| 
ユーザ
 a| 
ユーザ クォータ
 a| 
UNIXユーザ名 UNIX UID

Windows 2000より前の形式のWindowsユーザ名

Windows SID
 a| 
ユーザ クォータは、特定のボリュームまたはqtreeに適用できます



 a| 
グループ
 a| 
グループ クォータ
 a| 
UNIXグループ名 UNIX GID
 a| 
グループ クォータは、特定のボリュームまたはqtreeに適用できます


NOTE: グループ クォータの適用にWindows IDは使用されません。



 a| 
qtree
 a| 
ツリー クォータ
 a| 
qtree名
 a| 
ツリー クォータは特定のボリュームに適用され、他のボリューム内のqtreeには影響しません



 a| 
`""`
 a| 
ユーザ クォータ  グループ クォータ

ツリー クォータ
 a| 
二重引用符（""）
 a| 
クォータ ターゲットが "" の場合、_デフォルト クォータ_ を意味します。デフォルト クォータの場合、クォータの種類は type フィールドの値によって決まります。

|===


== クォータ制限を超えたときのFlexGroupボリュームの動作

ONTAP 9.5以降では、FlexGroupボリュームでクォータ制限がサポートされます。FlexGroupボリュームとFlexVolでは、クォータ制限の適用方法にいくつかの違いがあります。

クォータ制限を超えたときのFlexGroupボリュームの動作は次のとおりです。

* FlexGroupボリュームのスペースとファイルの使用量が設定されているハード リミットを最大で5%上回っても、クォータ制限が適用されず、後続のトラフィックが拒否されない場合があります。
+
ONTAPでは、最大のパフォーマンスを実現するために、スペース消費量が設定されているハード リミットをわずかに超えてもクォータが適用されないことがあります。この超過分のスペース消費量は、設定されているハード リミット（1GBまたは65,536個のファイルのいずれか小さい方）の5%より多くなることはありません。

* クォータ制限に達したあとにユーザまたは管理者が一部のファイルやディレクトリを削除してクォータ使用量が制限を下回ると、クォータを消費する後続のファイル処理が遅れて再開されます（再開までの時間は5秒以内）。
* FlexGroupボリュームのスペースとファイルの合計使用量が設定されているクォータ制限を超えた場合、イベント ログ メッセージのロギングがわずかに遅れることがあります。
* FlexGroupボリュームの一部の構成要素がいっぱいになっても、クォータ制限に達していない場合は、"`no space`"エラーが発生する可能性があります。
* クォータのハード リミットが設定されているクォータ ターゲットで、ファイル / ディレクトリの名前変更やqtree間のファイル移動などの処理を実行すると、FlexVolで同様の処理を実行する場合に比べて時間がかかることがあります。




== FlexGroupボリュームに対するクォータの適用例

以下の各例では、ONTAP 9.5以降で制限が指定されたクォータを設定する方法を説明します。

.例1：ディスク制限によるクォータ ルールの適用
.  `user`タイプのクォータ ポリシー ルールを作成し、達成可能なソフト ディスク制限とハードディスク制限の両方を設定する必要があります。
+
[listing]
----
cluster1::> volume quota policy rule create -vserver vs0 -policy-name default -volume FG -type user -target "" -qtree "" -disk-limit 1T -soft-disk-limit 800G
----
. クォータ ポリシー ルールを確認します。
+
[listing]
----
cluster1::> volume quota policy rule show -vserver vs0 -policy-name default -volume FG

Vserver: vs0               Policy: default           Volume: FG

                                               Soft             Soft
                         User         Disk     Disk   Files    Files
Type   Target    Qtree   Mapping     Limit    Limit   Limit    Limit  Threshold
-----  --------  ------- -------  --------  -------  ------  -------  ---------
user   ""        ""      off           1TB    800GB       -        -          -
----
. 新しいクォータ ルールをアクティブ化するには、ボリュームのクォータを初期化します。
+
[listing]
----
cluster1::> volume quota on -vserver vs0 -volume FG -foreground true
[Job 49] Job succeeded: Successful
----
. クォータ レポートを使用して、FlexGroupボリュームのディスクとファイルの使用量を確認します。
+
[listing]
----
cluster1::> volume quota report -vserver vs0 -volume FG
Vserver: vs0

                                    ----Disk----  ----Files-----   Quota
Volume   Tree      Type    ID        Used  Limit    Used   Limit   Specifier
-------  --------  ------  -------  -----  -----  ------  ------   ---------
FG                 user    root      50GB      -       1       -
FG                 user    *         800GB    1TB      0       -   *
2 entries were displayed.
----


ディスクのハード リミットに達すると、クォータ ポリシー ルールのターゲット（この例ではユーザ）はファイルへのデータの書き込みをブロックされます。

.例2：複数のユーザに対してクォータ ルールを適用する
. クォータ ターゲットに複数のユーザー（UNIXユーザー、SMBユーザー、またはその両方の組み合わせ）が指定され、ルールに達成可能なソフト ディスク制限とハードディスク制限の両方が含まれる、 `user`タイプのクォータ ポリシー ルールを作成する必要があります。
+
[listing]
----
cluster1::> quota policy rule create -vserver vs0 -policy-name default -volume FG -type user -target "rdavis,ABCCORP\RobertDavis" -qtree "" -disk-limit 1TB -soft-disk-limit  800GB
----
. クォータ ポリシー ルールを確認します。
+
[listing]
----
cluster1::> quota policy rule show -vserver vs0 -policy-name default -volume FG

Vserver: vs0               Policy: default           Volume: FG

                                               Soft             Soft
                         User         Disk     Disk   Files    Files
Type   Target    Qtree   Mapping     Limit    Limit   Limit    Limit  Threshold
-----  --------  ------- -------  --------  -------  ------  -------  ---------
user   "rdavis,ABCCORP\RobertDavis"  "" off  1TB  800GB  -  -
----
. 新しいクォータ ルールをアクティブ化するには、ボリュームのクォータを初期化します。
+
[listing]
----
cluster1::> volume quota on -vserver vs0 -volume FG -foreground true
[Job 49] Job succeeded: Successful
----
. クォータの状態がアクティブであることを確認します。
+
[listing]
----
cluster1::> volume quota show -vserver vs0 -volume FG
              Vserver Name: vs0
               Volume Name: FG
               Quota State: on
               Scan Status: -
          Logging Messages: on
          Logging Interval: 1h
          Sub Quota Status: none
  Last Quota Error Message: -
Collection of Quota Errors: -
----
. クォータ レポートを使用して、FlexGroupボリュームのディスクとファイルの使用量を確認します。
+
[listing]
----
cluster1::> quota report -vserver vs0 -volume FG
Vserver: vs0

                                    ----Disk----  ----Files-----   Quota
Volume   Tree      Type    ID        Used  Limit    Used   Limit   Specifier
-------  --------  ------  -------  -----  -----  ------  ------   ---------
FG                 user    rdavis,ABCCORP\RobertDavis  0B  1TB  0  -   rdavis,ABCCORP\RobertDavis
----
+
クォータ制限は、クォータ ターゲットにリストされているすべてのユーザに適用されます。



ディスクのハード リミットに達すると、クォータ ターゲットにリストされているユーザはそれ以降のファイルへのデータの書き込みをブロックされます。

.例3：ユーザ マッピングを有効にしてクォータを適用する
. タイプ `user`のクォータ ポリシー ルールを作成し、 `user-mapping`を `on`に設定してクォータ ターゲットとして UNIX ユーザまたは Windows ユーザを指定し、達成可能なソフト ディスク制限とハードディスク制限の両方を含むルールを作成する必要があります。
+
UNIX ユーザと Windows ユーザ間のマッピングは、 `vserver name-mapping create`コマンドを使用して事前に設定する必要があります。

+
[listing]
----
cluster1::> quota policy rule create -vserver vs0 -policy-name default -volume FG -type user -target rdavis -qtree "" -disk-limit 1TB -soft-disk-limit  800GB -user-mapping on
----
. クォータ ポリシー ルールを確認します。
+
[listing]
----
cluster1::> quota policy rule show -vserver vs0 -policy-name default -volume FG

Vserver: vs0               Policy: default           Volume: FG

                                               Soft             Soft
                         User         Disk     Disk   Files    Files
Type   Target    Qtree   Mapping     Limit    Limit   Limit    Limit  Threshold
-----  --------  ------- -------  --------  -------  ------  -------  ---------
user   rdavis    ""      on           1TB    800GB       -        -          -
----
. 新しいクォータ ルールをアクティブ化するには、ボリュームのクォータを初期化します。
+
[listing]
----
cluster1::> volume quota on -vserver vs0 -volume FG -foreground true
[Job 49] Job succeeded: Successful
----
. クォータの状態がアクティブであることを確認します。
+
[listing]
----
cluster1::> volume quota show -vserver vs0 -volume FG
              Vserver Name: vs0
               Volume Name: FG
               Quota State: on
               Scan Status: -
          Logging Messages: on
          Logging Interval: 1h
          Sub Quota Status: none
  Last Quota Error Message: -
Collection of Quota Errors: -
----
. クォータ レポートを使用して、FlexGroupボリュームのディスクとファイルの使用量を確認します。
+
[listing]
----
cluster1::> quota report -vserver vs0 -volume FG
Vserver: vs0

                                    ----Disk----  ----Files-----   Quota
Volume   Tree      Type    ID        Used  Limit    Used   Limit   Specifier
-------  --------  ------  -------  -----  -----  ------  ------   ---------
FG                 user    rdavis,ABCCORP\RobertDavis  0B  1TB  0  -   rdavis
----
+
クォータ制限は、クォータ ターゲットにリストされているユーザと、そのユーザに対応するWindowsユーザまたはUNIXユーザの両方に適用されます。



ディスクのハード リミットに達すると、クォータ ターゲットにリストされているユーザと、そのユーザに対応するWindowsユーザまたはUNIXユーザは、それ以降のファイルへのデータの書き込みをブロックされます。

.例4：クォータが有効な場合のqtreeサイズの確認
.  `tree`タイプのクォータ ポリシー ルールを作成する必要があります。このルールには、達成可能なソフト ディスク制限とハードディスク制限の両方が含まれている必要があります。
+
[listing]
----
cluster1::> quota policy rule create -vserver vs0 -policy-name default -volume FG -type tree -target tree_4118314302 -qtree "" -disk-limit 48GB -soft-disk-limit 30GB
----
. クォータ ポリシー ルールを確認します。
+
[listing]
----
cluster1::> quota policy rule show -vserver vs0

Vserver: vs0               Policy: default           Volume: FG

                                               Soft             Soft
                         User         Disk     Disk   Files    Files
Type   Target    Qtree   Mapping     Limit    Limit   Limit    Limit  Threshold
-----  --------  ------- -------  --------  -------  ------  -------  ---------
tree   tree_4118314302  "" -          48GB        -      20        -
----
. 新しいクォータ ルールをアクティブ化するには、ボリュームのクォータを初期化します。
+
[listing]
----
cluster1::> volume quota on -vserver vs0 -volume FG -foreground true
[Job 49] Job succeeded: Successful
----
+
.. クォータ レポートを使用して、FlexGroupボリュームのディスクとファイルの使用量を確認します。
+
....
cluster1::> quota report -vserver vs0
Vserver: vs0
----Disk---- ----Files----- Quota
Volume Tree Type ID Used Limit Used Limit Specifier
------- -------- ------ ------- ----- ----- ------ ------ ---------
FG tree_4118314302 tree 1 30.35GB 48GB 14 20 tree_4118314302
....
+
クォータ制限は、クォータ ターゲットにリストされているユーザと、そのユーザに対応するWindowsユーザまたはUNIXユーザの両方に適用されます。



. NFSクライアントから `df`コマンドを使用して、合計スペース使用量、使用可能なスペース、および使用済みスペースを表示します。
+
[listing]
----
scsps0472342001# df -m /t/10.53.2.189/FG-3/tree_4118314302
Filesystem 1M-blocks Used Available Use% Mounted on
10.53.2.189/FG-3 49152 31078 18074 63% /t/10.53.2.189/FG-3
----
+
ハード リミットが指定されている場合、NFSクライアントでは次のようにスペース使用量が計算されます。

+
** ツリーの総スペース使用量=ハード リミット
** 空き領域 = ハード リミット - qtree領域使用量ハード リミットがない場合、領域使用量は NFS クライアントから次のように計算されます：
** スペース使用量=クォータ使用量
** 合計スペース = ボリューム内のクォータ使用量と物理空きスペースの合計


. SMB共有からは、Windowsエクスプローラを使用して、合計スペース使用量、使用可能なスペース、および使用済みスペースを表示します。
+
SMB共有では、スペース使用量の計算に関する次の考慮事項を理解しておく必要があります。

+
** 使用可能な合計スペースを計算する際には、ユーザおよびグループのユーザ クォータ ハード リミットが考慮されます。
** ツリー クォータ ルール、ユーザ クォータ ルール、およびグループ クォータ ルールの空き領域のうちの最小値が、SMB共有の空き領域として考慮されます。
** SMB の合計スペース使用量は可変であり、ツリー、ユーザ、およびグループ間の最小空きスペースに対応するハード リミットによって異なります。






== FlexGroupボリュームにルールと制限を適用する

.手順
. ターゲットのクォータルールを作成します： `volume quota policy rule create -vserver vs0 -policy-name quota_policy_of_the_rule -volume flexgroup_vol -type {tree|user|group} -target target_for_rule -qtree qtree_name [-disk-limit hard_disk_limit_size] [-file-limit hard_limit_number_of_files] [-threshold threshold_disk_limit_size] [-soft-disk-limit soft_disk_limit_size] [-soft-file-limit soft_limit_number_of_files]`
+
** FlexGroupボリュームのクォータターゲットタイプは `user`、 `group`、または `tree`になります。
** FlexGroupボリュームのクォータ ルールを作成する場合、パスはターゲットとしてサポートされません。
** ONTAP 9.5以降では、FlexGroupボリュームに対して、ハードディスク リミット、ハード ファイル リミット、ソフト ディスク リミット、ソフト ファイル リミット、およびしきい値リミットのクォータを指定できます。
+
ONTAP 9.4以前では、FlexGroupボリュームのクォータ ルールを作成する際に、ディスク リミット、ファイル リミット、ディスク リミットのしきい値、ディスクのソフト リミット、ファイルのソフト リミットを指定できません。





次の例では、ユーザ ターゲット タイプにデフォルトのクォータ ルールを作成します。

[listing]
----
cluster1::> volume quota policy rule create -vserver vs0 -policy-name quota_policy_vs0_1 -volume fg1 -type user -target "" -qtree ""
----
次の例では、qtree1という名前のqtreeにツリー クォータ ルールを作成します。

[listing]
----
cluster1::> volume quota policy rule create -policy-name default -vserver vs0 -volume fg1 -type tree -target "qtree1"
----
. 指定したFlexGroupボリュームのクォータを有効化します： `volume quota on -vserver svm_name -volume flexgroup_vol -foreground true`


[listing]
----
cluster1::> volume quota on -vserver vs0 -volume fg1 -foreground true
----
. クォータ初期化の状態を監視します： `volume quota show -vserver svm_name`


FlexGroupボリュームには `mixed`状態が表示される場合があります。これは、構成ボリュームのすべてがまだ同じ状態ではないことを示しています。

[listing]
----
cluster1::> volume quota show -vserver vs0
                                          Scan
Vserver    Volume        State            Status
---------  ------------  ---------------  ------
vs0        fg1           initializing         95%
vs0        vol1          off                   -
2 entries were displayed.
----
. アクティブなクォータを持つFlexGroupボリュームのクォータ レポートを表示します： `volume quota report -vserver svm_name -volume flexgroup_vol`
+
 `volume quota report`コマンドでFlexGroupボリュームのパスを指定することはできません。

+
次の例は、FlexGroupボリュームのユーザ クォータを示しています `fg1`：

+
....
cluster1::> volume quota report -vserver vs0 -volume fg1
  Vserver: vs0
                                      ----Disk----  ----Files-----   Quota
  Volume   Tree      Type    ID        Used  Limit    Used   Limit   Specifier
  -------  --------  ------  -------  -----  -----  ------  ------   ---------
  fg1                user    *           0B      -       0       -   *
  fg1                user    root       1GB      -       1       -   *
  2 entries were displayed.
....
+
次の例は、FlexGroupボリュームのツリー クォータを示しています `fg1`：

+
[listing]
----
cluster1::> volume quota report -vserver vs0 -volume fg1
Vserver: vs0

                                    ----Disk----  ----Files-----   Quota
Volume   Tree      Type    ID        Used  Limit    Used   Limit   Specifier
-------  --------  ------  -------  -----  -----  ------  ------   ---------
fg1      qtree1  tree      1         68KB      -      18       -   qtree1
fg1              tree      *           0B      -       0       -   *
2 entries were displayed.
----


.結果
クォータ ルールと制限はFlexGroupボリュームに適用されます。

使用量が設定されているハード リミットを最大5%超過するまで、クォータが適用されず、後続のトラフィックが拒否されないことがあります。

.関連情報
* https://docs.netapp.com/us-en/ontap-cli["ONTAPコマンド リファレンス"^]

