---
permalink: flexgroup/reverse-snapmirror-relationship-task.html 
sidebar: sidebar 
keywords: reverse, snapmirror, relation, flexgroup, volume, disaster, recovery 
summary: 災害によってSnapMirror関係のソースFlexGroupボリュームが使用不能になった場合、ソースFlexGroupボリュームの修復や交換を行っている間、デスティネーションのFlexGroupボリュームを使用してデータを提供できます。ソースFlexGroupボリュームがオンラインになった後、元のソースFlexGroupボリュームを読み取り専用のデスティネーションにして、SnapMirror関係を反転できます。 
---
= 災害復旧時にONTAP FlexGroupボリューム間でリバースSnapMirror関係を構築する
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
災害によってSnapMirror関係のソースFlexGroupボリュームが使用不能になった場合、ソースFlexGroupボリュームの修復や交換を行っている間、デスティネーションのFlexGroupボリュームを使用してデータを提供できます。ソースFlexGroupボリュームがオンラインになった後、元のソースFlexGroupボリュームを読み取り専用のデスティネーションにして、SnapMirror関係を反転できます。

.タスク概要
再同期が実行される前に、デスティネーション ボリューム上のアクティブなクォータ ルールはすべて非アクティブ化され、クォータ ルールは削除されます。

再同期操作が完了したら、 `volume quota policy rule create`コマンドと `volume quota modify`コマンドを使用してクォータ ルールを作成し、再アクティブ化することができます。

.手順
. 元のデスティネーションFlexGroupボリュームで、ソースFlexGroupボリュームとデスティネーションFlexGroupボリューム間のデータ保護ミラー関係を削除します： `snapmirror delete -destination-path svm_name:volume_name`
+
[listing]
----
cluster2::> snapmirror delete -destination-path vsd:dst
----
. 元のソースFlexGroupボリュームで、ソースFlexGroupボリュームから関係情報を削除します： `snapmirror release -destination-path svm_name:volume_name -relationship-info-only`
+
SnapMirror関係を削除した後、再同期操作を試みる前に、ソースFlexGroupボリュームから関係情報を削除する必要があります。

+
[listing]
----
cluster1::> snapmirror release -destination-path vsd:dst -relationship-info-only true
----
. 新しいデスティネーションFlexGroupボリュームで、ミラー関係を作成します： `snapmirror create -source-path src_svm_name:volume_name -destination-path dst_svm_name:volume_name -type XDP -policy MirrorAllSnapshots`
+
[listing]
----
cluster1::> snapmirror create -source-path vsd:dst -destination-path vss:src -type XDP -policy MirrorAllSnapshots
----
+
 `snapmirror create`の詳細については、link:https://docs.netapp.com/us-en/ontap-cli/snapmirror-create.html["ONTAPコマンド リファレンス"^]を参照してください。

. 新しいデスティネーションFlexGroupボリュームで、ソースFlexGroupを再同期します： `snapmirror resync -source-path svm_name:volume_name`
+
[listing]
----
cluster1::> snapmirror resync -source-path vsd:dst
----
. SnapMirror転送を監視します： `snapmirror show -expand`
+
[listing]
----
cluster2::> snapmirror show -expand
                                                                       Progress
Source            Destination Mirror  Relationship   Total             Last
Path        Type  Path        State   Status         Progress  Healthy Updated
----------- ---- ------------ ------- -------------- --------- ------- --------
vsd:dst       XDP  vss:src        Snapmirrored
                                      Idle           -         true    -
vss:dst__0001 XDP  vss:src__0001  Snapmirrored
                                      Idle           -         true    -
vsd:dst__0002 XDP  vss:src__0002  Snapmirrored
                                      Idle           -         true    -
vsd:dst__0003 XDP  vss:src__0003  Snapmirrored
                                      Idle           -         true    -
vsd:dst__0004 XDP  vss:src__0004  Snapmirrored
                                      Idle           -         true    -
vsd:dst__0005 XDP  vss:src__0005  Snapmirrored
                                      Idle           -         true    -
vsd:dst__0006 XDP  vss:src__0006  Snapmirrored
                                      Idle           -         true    -
vsd:dst__0007 XDP  vss:src__0007  Snapmirrored
                                      Idle           -         true    -
vsd:dst__0008 XDP  vss:src__0008  Snapmirrored
                                      Idle           -         true    -
...
----
+
各構成要素のSnapMirror関係ステータスが `Snapmirrored`として表示され、再同期が成功したことを示します。



.関連情報
* link:https://docs.netapp.com/us-en/ontap-cli/snapmirror-create.html["snapmirror create"^]
* link:https://docs.netapp.com/us-en/ontap-cli/snapmirror-delete.html["snapmirror delete"^]
* link:https://docs.netapp.com/us-en/ontap-cli/snapmirror-release.html["snapmirror release"^]
* link:https://docs.netapp.com/us-en/ontap-cli/snapmirror-resync.html["snapmirror resync"^]
* link:https://docs.netapp.com/us-en/ontap-cli/snapmirror-show.html["snapmirror show"^]

