---
permalink: flexgroup/transition-snapmirror-relationship-svm-dr-task.html 
sidebar: sidebar 
keywords: transition, flexgroup, snapmirror, relationship, svm, dr 
summary: 既存のFlexGroup SnapMirror関係を移行することで、FlexGroup SVM DR関係を作成できます。 
---
= ONTAP FlexGroup SnapMirror関係をSVM DRに移行
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
既存のFlexGroup SnapMirror関係を移行することで、FlexGroup SVM DR関係を作成できます。

.開始する前に
* FlexGroup Volume SnapMirror関係は正常な状態です。
* ソースとデスティネーションのFlexGroupボリュームの名前が同じです。


.手順
. SnapMirrorデスティネーションから、FlexGroupレベルのSnapMirror関係を再同期します。 `snapmirror resync`
. FlexGroup SVM DR SnapMirror関係を作成FlexGroup VolumeのSnapMirror関係に設定されているのと同じSnapMirrorポリシーを使用します。 `snapmirror create -destination-path dest_svm: -source-path src_svm: -identity-preserve true -policy MirrorAllSnapshots`
+
[NOTE]
====
レプリケーション関係を作成するときは、コマンドのオプションを `snapmirror create`使用する必要があります `-identity-preserve true`。

====
. 関係が解除されていることを確認します。 `snapmirror show -destination-path dest_svm: -source-path src_svm:`
+
[listing]
----
snapmirror show -destination-path fg_vs_renamed: -source-path fg_vs:

                                                                       Progress
Source            Destination Mirror  Relationship   Total             Last
Path        Type  Path        State   Status         Progress  Healthy Updated
----------- ---- ------------ ------- -------------- --------- ------- --------
fg_vs:        XDP  fg_vs1_renamed:     Broken-off
                                      Idle           -         true   -
----
. デスティネーションSVMを停止します。 `vserver stop -vserver vs_name`
+
[listing]
----
vserver stop -vserver fg_vs_renamed
[Job 245] Job is queued: Vserver Stop fg_vs_renamed.
[Job 245] Done
----
. SVM SnapMirror関係を再同期します。 `snapmirror resync -destination-path dest_svm: -source-path src_svm:`
+
[listing]
----
snapmirror resync -destination-path fg_vs_renamed: -source-path fg_vs:
Warning: This Vserver has volumes which are the destination of FlexVol or FlexGroup SnapMirror relationships. A resync on the Vserver SnapMirror relationship will cause disruptions in data access
----
. SVM DRレベルのSnapMirror関係が健全なアイドル状態になっていることを確認します。 `snapmirror show -expand`
. FlexGroup SnapMirror関係が健全な状態であることを確認します。 `snapmirror show`


.関連情報
* link:https://docs.netapp.com/us-en/ontap-cli/snapmirror-create.html["スナップミラー作成"^]

