---
permalink: flexcache-writeback/flexcache-write-back-overview.html 
sidebar: sidebar 
keywords: tr-4743, flexcache writeback, flexcache write-back, overview, technical report, netapp tr, ontap tr 
summary: ONTAP 9.15.1で導入されたFlexCacheライトバックは、キャッシュへの書き込み処理の代替モードです。 
---
= FlexCacheライトバックの概要
:allow-uri-read: 


[role="lead"]
ONTAP 9.15.1で導入されたFlexCacheライトバックは、キャッシュへの書き込み処理の代替モードです。ライトバックを使用すると、書き込みがキャッシュの安定したストレージにコミットされ、データが元のストレージに送信されるのを待たずにクライアントに確認応答が返されます。データは非同期的に元のデータにフラッシュされます。その結果、グローバルに分散されたファイルシステムが実現し、特定のワークロードや環境に対してローカルに近い速度で書き込みを実行できるようになり、パフォーマンスが大幅に向上します。


NOTE: ONTAP 9.12.1では、ライトバック機能がパブリックプレビューとして導入されました。これはライトバックバージョン1（wbv1）と呼ばれ、ライトバックバージョン2（wbv2）と呼ばれるONTAP 9.15.1のライトバックと同じと考えるべきではありません。


NOTE: 2024年7月以降、これまでPDFとして公開されていたテクニカルレポートの内容がONTAPの製品ドキュメントに統合されました。ONTAPのセキュリティに関するドキュメントに、TR-4743：『FlexCache in ONTAP 9.11.1』の内容が追加されました。



== ライトバックとライトアラウンド

FlexCacheはONTAP 9.5で導入されて以来、読み取り/書き込み可能なキャッシュですが、ライトアラウンドモードで動作します。キャッシュでの書き込みは、安定したストレージにコミットされるためにオリジンに送られました。送信元は、安定したストレージへの書き込みを正常にコミットしたあと、キャッシュへの書き込みを確認応答しました。その後、キャッシュはクライアントへの書き込みを確認応答します。このため、書き込みが行われるたびに、キャッシュと送信元の間のネットワークをトラバースするというペナルティが発生します。FlexCacheライトバックはこれを変更します。


NOTE: ONTAP 9.15.1にアップグレードすると、従来のライトアラウンドキャッシュをライトバックキャッシュに変換し、必要に応じてライトアラウンドに戻すことができます。ただし、これにより、問題が発生した場合に診断ログの読み取りが困難になる可能性があります。

|===
|  | ライトアラウンド | ライトバック 


| ONTAPバージョン | 9.6以上 | 9.15.1以上 


| ユースケース | 読み取り負荷の高いワークロード | 書き込み負荷の高いワークロード 


| データのコミット日時 | 由来 | キャッシュ 


| 顧客体験 | WANライク | lan-lke 


| 制限 | オリジンごとに100 | オリジンあたり10 


| https://en.wikipedia.org/wiki/CAP_theorem["キャップ定理"^] | 使用可能で、パーティションに耐性がある | 可用性と一貫性 
|===


== FlexCacheライトバックに関する用語

FlexCacheライトバックを使用する主な概念と用語を理解します。

[cols="12%,88%"]
|===
| 期間 | 定義（ Definition ） 


| [[dirty-data]]*ダーティデータ* | キャッシュの安定したストレージにコミットされたが、送信元にフラッシュされていないデータ。 


| *排他ロック委任(XLD)* | ファイル単位でキャッシュに付与されるプロトコルレベルのロック権限。この権限を使用すると、キャッシュがオリジンに接続せずにクライアントに排他的な書き込みロックを渡すことができます。 


| *共有ロック委任（SLD）* | ファイル単位でキャッシュに付与されるプロトコルレベルのロック権限。この権限を使用すると、キャッシュはオリジンに接続せずに共有読み取りロックをクライアントに渡すことができます。 


| *書き戻し* | FlexCache処理のモード。キャッシュへの書き込みがそのキャッシュの安定したストレージにコミットされ、クライアントに即座に確認応答が返されます。データは非同期的に元のデータに書き戻されます。 


| *書き替え* | FlexCache処理のモード。キャッシュへの書き込みが元のストレージに転送され、安定したストレージにコミットされます。コミットされると、送信元はキャッシュへの書き込みを確認応答し、キャッシュはクライアントへの書き込みを確認応答します。 


| *ダーティー・データ・レコード・システム（DDR）* | ライトバックが有効なキャッシュ内のダーティデータをファイル単位で追跡する独自のメカニズム。 


| *原点* | すべてのFlexCacheキャッシュボリュームのソースデータを含むFlexGroupまたはFlexVol。データは一元化された情報源であり、ロックをオーケストレーションし、データの整合性、通貨性、一貫性を100%保証します。 


| *キャッシュ* | FlexCacheオリジンのスパースキャッシュボリュームであるFlexGroup。 
|===


=== 一貫性、電流、一貫性

FlexCacheは、場所を問わず適切なデータを保持するためのネットアップのソリューションです。FlexCacheは常に100%の一貫性、電流、一貫性を備えています。

* *一貫性：*データはアクセスされる場所を問わず同じです。
* *現在：*データは常に最新です。
* *一貫性：*データは正しい/破損していません。

