---
sidebar: sidebar 
permalink: smbc/smbc_install_creating_a_consistency_group_relationship.html 
keywords: SM-BC, SMBC, consistency group, create, constituent 
summary: 同期整合グループ関係も確立する SnapMirror 整合グループを作成する必要があります。 
---
= 整合グループ関係を作成する
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
同期整合グループ関係も確立する SM-BC 整合グループを作成する必要があります。


NOTE: このワークフローは、 ONTAP 9.8 および 9.9.8.1 の環境ユーザを対象としています。ONTAP 9.10.1 以降の ONTAP CLI コマンドを使用しても整合グループは作成できますが、 System Manager または ONTAP REST API を使用して整合グループを管理することを推奨します。

.作業を開始する前に
次の前提条件と制約事項が適用されます。

* クラスタ管理者または Storage VM 管理者である必要があります
* SnapMirror Synchronous ライセンスが必要です
* デスティネーションボリュームのタイプは DP でなければなりません
* プライマリ Storage VM とセカンダリ Storage VM のピア関係が確立されている必要があります
* 整合性グループ内のコンスティチュエントボリュームはすべて、 1 つの Storage VM に含まれている必要があります
* ASA クラスタと非 ASA クラスタ間で SM-BC 整合グループ関係を確立することはできません
* 整合グループの名前は一意である必要があります


.このタスクについて
整合グループ関係はデスティネーションクラスタから作成する必要があります。を使用して最大12個のコンスティチュエントをマッピングできます `cg-item-mappings` のパラメータ `snapmirror create` コマンドを実行します

.手順
. 整合グループとコンスティチュエントの関係を作成します。この例では、コンスティチュエントボリューム vol1 と vol2 を含む cg_src と、コンスティチュエントボリューム vol1_DR と vol2 を含む cg_dist2 つの整合グループを作成しています。
+
`destination::> snapmirror create -source-path vs1_src:/cg/cg_src -destination-path vs1_dst:/cg/cg_dst -cg-item-mappings vol_src1:@vol_dst1,vol_src2:@vol_dst2 -policy AutomatedFailOver`


