---
permalink: s3-audit/plan-config-task.html 
sidebar: sidebar 
keywords: s3, audit, create, configure s3 audit 
summary: このタスクでは、 S3 監査で使用されるパラメータについて説明します。 
---
= S3 監査の設定を計画します
:allow-uri-read: 


[role="lead"]
S3 監査の設定用にいくつかのパラメータを指定するか、デフォルトを受け入れる必要があります。特に、適切な空きスペースを確保するために、どのログローテーションパラメータを使用するかを検討する必要があります。

構文の詳細については '*`vserver object-store-server audit create`* のマニュアルページを参照してください



== 一般パラメーター

監査の設定の作成時に指定する必要がある 2 つの必須パラメータがあります。また、指定できるオプションのパラメータが 3 つあります。

[cols="4,2,1"]
|===
| 情報のタイプ | オプション | 必須 


| _svm name_name 監査の設定を作成する SVM の名前。SVM がすでに存在し、 S3 に対して有効になっている必要があります。 | 「 -verserver_svm_name 」をクリックします | はい。 


| _Log destination path_ 変換された監査ログを格納する場所を指定します。パスが SVM 上に存在している必要があります。パスには、最大 864 文字の文字列を指定できます。パスには読み取り / 書き込みアクセス権が必要です。パスが有効でない場合、監査の設定コマンドは失敗します。 | 「 -destination_text_` 」を指定します | はい。 


| _ 監査するイベントのカテゴリ _ 次のイベントカテゴリを監査できます。 * data GetObject 、 PutObject 、および DeleteObject イベント * management PutBucket イベントおよび DeleteBucket イベントデフォルトは、データイベントのみを監査します。 | `-events { data { vbar} management },...` | いいえ 
|===
監査ログファイルの数を制御するには、次のいずれかのパラメータを入力します。値を入力しない場合は、すべてのログファイルが保持されます。

[cols="4,2,1"]
|===
| 情報のタイプ | オプション | 必須 


| _ ログファイルローテーションの上限 _ 保持する監査ログファイルの数を指定します。これにより、その数からあふれた最も古いログファイルがローテーションから外されます。たとえば、 5 という値を入力すると、最後の 5 つのログファイルが保持されます。値を 0 に設定すると、すべてのログファイルが保持されます。デフォルト値は 0. です。 | `-rotate-limit_integer_` | いいえ 


| _ ログファイル継続時間制限 _ 削除するまでにログファイルを保持できる期間を指定しますたとえば、 5d0h0m という値を入力すると、 5 日を超える古いログが削除されます。値を 0 に設定すると、すべてのログファイルが保持されます。デフォルト値は 0. です。 | ` -retention duration_integer_time_ ' | いいえ 
|===


== 監査ログローテーションのパラメータ

監査ログのローテーションは、サイズやスケジュールに基づいて実行できます。デフォルトでは、サイズに基づいた監査ログのローテーションが行われます。



=== ログサイズに基づいてログをローテーションします

デフォルトのログローテーション方法とデフォルトのログサイズを使用する場合、ログローテーションに関する特定のパラメータを設定する必要はありません。デフォルトのログサイズは 100MB です。

デフォルトのログ・サイズを使用しない場合は '-rotate-size パラメータを設定してカスタム・ログ・サイズを指定できます

ログ・サイズだけに基づいてローテーションをリセットする場合は ' 次のコマンドを使用して '-rotate-schedule-minute パラメータの設定を解除します

vserver audit modify -vserver _svm_name_-destination // rotate-schedule-minute



=== スケジュールに基づいたログのローテーション

スケジュールに基づいた監査ログのローテーションを選択した場合は、時間に基づくローテーションパラメータを任意に組み合わせて使用することで、ログのローテーションをスケジュールすることができます。

* 時間ベースのローテーションを使用する場合、 -rotate-schedule-minute パラメータは必須です。
* それ以外の時間ベースのローテーションパラメータは、すべてオプションです。
+
** 「 -rotate-schedule-month 」と入力します
** 「 -rotate-schedule-dayofweek 」と入力します
** 「 -rotate-schedule-day 」と入力します
** 「 -rotate-schedule-hour 」を参照してください


* ローテーションスケジュールは、時間に関連するすべての値を使用して計算されます。たとえば '-rotate-schedule-minute パラメータのみを指定した場合 ' 監査ログ・ファイルのローテーションは ' その年のすべての月のすべての曜日の毎時間 ' 指定された分に行われます
* 時間に基づくローテーションパラメータを 1 つまたは 2 つだけ指定した場合（例：「 -rotate-schedule-month 」および「 -rotate-schedule-minutes 」）、ログファイルのローテーションは、指定した月のすべての曜日の毎時間、指定した分にのみ行われます。
+
たとえば、監査ログのローテーションを、 1 月、 3 月、 8 月の毎週月曜日、水曜日、土曜日の 10 時 30 分に実行するように指定できます

* 「 -rotate-schedule-dayofweek 」と「 -rotate-schedule-day 」の両方に値を指定すると、値は独立して処理されます。
+
たとえば、「 -rotate-schedule-dayofweek 」に Friday を指定し、「 -rotate-schedule-day 」に 13 を指定すると、監査ログのローテーションは、 13 日の金曜日だけでなく、毎週金曜日、および指定した月の 13 日にも実行されます。

* スケジュールのみに基づいてローテーションをリセットする場合は、次のコマンドを使用して、「 -rotate-schedule-SIZE 」パラメータの設定を解除します。
+
vserver audit modify -vserver _svm_name -destination/-rotate-size -`





=== ログのサイズとスケジュールに基づいたログのローテーション

rotate-size パラメータと時間ベースのローテーションパラメータを任意の組み合わせで設定することで、ログファイルのローテーションをログサイズとスケジュールに基づいて行うことができます。たとえば、「 -rotate-schedule-minute 」が 10 MB に設定され、「 -rotate-schedule-minute 」が 15 に設定されている場合、ログファイルは、ログファイルのサイズが 10 MB に達するか、または 1 時間の 15 分（いずれかのイベントが発生した時点）になるとローテーションされます。
