---
permalink: s3-audit/plan-config-task.html 
sidebar: sidebar 
keywords: s3, audit, create, configure s3 audit 
summary: このタスクでは、 S3 監査で使用されるパラメータについて説明します。 
---
= S3 監査の設定を計画します
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
S3 監査の設定用にいくつかのパラメータを指定するか、デフォルトを受け入れる必要があります。特に、適切な空きスペースを確保するために、どのログローテーションパラメータを使用するかを検討する必要があります。

を参照してください *`vserver object-store-server audit create`*構文の詳細については、マニュアルページを参照してください。



== 一般パラメーター

監査の設定の作成時に指定する必要がある 2 つの必須パラメータがあります。また、指定できるオプションのパラメータが 3 つあります。

[cols="4,2,1"]
|===


| 情報のタイプ | オプション | 必須 


 a| 
SVM 名 _

監査の設定を作成する SVM の名前。

SVM がすでに存在し、 S3 に対して有効になっている必要があります。
 a| 
`-vserver _svm_name_`
 a| 
はい。



 a| 
_ ログデスティネーションパス _

変換された監査ログを格納する場所を指定します。パスが SVM 上に存在している必要があります。

パスには、最大 864 文字の文字列を指定できます。パスには読み取り / 書き込みアクセス権が必要です。

パスが有効でない場合、監査の設定コマンドは失敗します。
 a| 
`-destination _text_`
 a| 
はい。



 a| 
_ 監査するイベントのカテゴリ _

監査できるイベントカテゴリは次のとおりです。

* データ
GetObject、PutObject、およびDeleteObjectイベント
* 管理
PutBucketイベントとDeleteBucketイベント


デフォルトでは、データイベントのみが監査されます。
 a| 
`-events {data{vbar}management}, ...`
 a| 
いいえ

|===
監査ログファイルの数を制御するには、次のいずれかのパラメータを入力します。値を入力しない場合は、すべてのログファイルが保持されます。

[cols="4,2,1"]
|===


| 情報のタイプ | オプション | 必須 


 a| 
ログファイルのローテーションの上限 _

保持する監査ログファイルの数を指定します。これにより、その数からあふれた最も古いログファイルがローテーションから外されます。たとえば、 5 という値を入力すると、最後の 5 つのログファイルが保持されます。

値を 0 に設定すると、すべてのログファイルが保持されます。デフォルト値は0です。
 a| 
`-rotate-limit _integer_`
 a| 
いいえ



 a| 
_ログファイル継続時間制限_

ログファイルを削除するまでの保持期間を指定します。たとえば、 5d0h0m という値を入力すると、 5 日を超える古いログが削除されます。

値を 0 に設定すると、すべてのログファイルが保持されます。デフォルト値は0です。
 a| 
`-retention duration _integer_time_`
 a| 
いいえ

|===


== 監査ログローテーションのパラメータ

監査ログのローテーションは、サイズやスケジュールに基づいて実行できます。デフォルトでは、サイズに基づいた監査ログのローテーションが行われます。



=== ログサイズに基づいてログをローテーションします

デフォルトのログローテーション方法とデフォルトのログサイズを使用する場合、ログローテーションに関する特定のパラメータを設定する必要はありません。デフォルトのログサイズは 100MB です。

デフォルトのログサイズを使用しない場合は、を設定できます `-rotate-size` カスタムログサイズを指定するパラメータ。

ログサイズのみに基づいてローテーションをリセットする場合は、次のコマンドを使用しての設定を解除します `-rotate-schedule-minute` パラメータ：

`vserver audit modify -vserver _svm_name_ -destination / -rotate-schedule-minute -`



=== スケジュールに基づいたログのローテーション

スケジュールに基づいた監査ログのローテーションを選択した場合は、時間に基づくローテーションパラメータを任意に組み合わせて使用することで、ログのローテーションをスケジュールすることができます。

* 時間に基づくローテーションを使用する場合は、 `-rotate-schedule-minute` パラメータは必須です。
* それ以外の時間ベースのローテーションパラメータは、すべてオプションです。
+
** `-rotate-schedule-month`
** `-rotate-schedule-dayofweek`
** `-rotate-schedule-day`
** `-rotate-schedule-hour`


* ローテーションスケジュールは、時間に関連するすべての値を使用して計算されます。
たとえば、のみを指定した場合 `-rotate-schedule-minute` パラメータを指定すると、監査ログファイルのローテーションは、毎月のすべての曜日の毎時間、指定した分に行われます。
* 時間ベースのローテーションパラメータを1つまたは2つだけ指定した場合（例： `-rotate-schedule-month` および `-rotate-schedule-minutes`）を指定すると、ログファイルのローテーションは、指定した月にのみ、すべての曜日の毎時間、指定した分に行われます。
+
たとえば、監査ログのローテーションを、 1 月、 3 月、 8 月の毎週月曜日、水曜日、土曜日の 10 時 30 分に実行するように指定できます

* 両方に値を指定する場合は `-rotate-schedule-dayofweek` および `-rotate-schedule-day`では、これらは独立して考慮されます。
+
たとえば、を指定した場合などです `-rotate-schedule-dayofweek` 金曜日およびとして `-rotate-schedule-day` 13と指定すると、監査ログのローテーションは、13日の金曜日だけでなく、毎週金曜日と指定した月の13日にも実行されます。

* スケジュールのみに基づいてローテーションをリセットする場合は、次のコマンドを使用しての設定を解除します `-rotate-size parameter`：
+
`vserver audit modify -vserver _svm_name_ -destination / -rotate-size -`





=== ログのサイズとスケジュールに基づいたログのローテーション

rotate-size パラメータと時間ベースのローテーションパラメータを任意の組み合わせで設定することで、ログファイルのローテーションをログサイズとスケジュールに基づいて行うことができます。例：if `-rotate-size` は10 MBに設定されており `-rotate-schedule-minute` が15に設定されている場合、ログファイルのサイズが10MBに達したとき、または1時間15分ごと（いずれか早い方）にログファイルがローテーションされます。
