---
permalink: s3-audit/show-config-task.html 
sidebar: sidebar 
keywords: s3 audit, show, display 
summary: このタスクでは、CLI を使用して s3 監査に関する情報を表示する方法について説明します。 
---
= ONTAP S3監査設定を表示する
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
監査設定が完成したら、監査が適切に設定されて有効になっていることを確認できます。クラスタ内のすべてのオブジェクト ストアの監査設定に関する情報を表示することもできます。

.タスク概要
バケットとSVMの監査設定に関する情報を表示できます。

* バケット： `vserver object-store-server audit event-selector show`コマンドを使用する
+
このコマンドをパラメータなしで実行すると、オブジェクト ストアの監査設定があるクラスタ内のすべてのSVMのバケットについて、次の情報が表示されます。

+
** SVM名
** バケット名
** アクセスと権限の値


* SVM： `vserver object-store-server audit show`コマンドを使用する
+
このコマンドをパラメータなしで実行すると、オブジェクト ストアの監査設定があるクラスタ内のすべてのSVMについて、次の情報が表示されます。

+
** SVM名
** 監査の状態
** ターゲット ディレクトリ




 `-fields`パラメータを指定して、表示する監査構成情報を指定できます。

.手順
S3の監査設定に関する情報を表示します。

[cols="2,4"]
|===
| 変更対象 | 入力する内容 


| バケット | `vserver object-store-server audit event-selector show [-vserver _svm_name_] [_parameters_]` 


| SVM  a| 
`vserver object-store-server audit show [-vserver _svm_name_] [_parameters_]`

|===
.例
次の例は、単一のバケットの情報を表示します。

[listing]
----
cluster1::> vserver object-store-server audit event-selector show -vserver vs1 -bucket test-bucket
     Vserver     Bucket     Access          Permission
     ----------- ---------- --------------- ----------
     vs1         bucket1    read-only       allow-only
----
次の例は、SVMのすべてのバケットの情報を表示します。

[listing]
----
cluster1::> vserver object-store-server audit event-selector show -vserver vs1

     Vserver           :vs1
     Bucket            :test-bucket
     Access            :all
     Permission        :all
----
次の例は、すべてのSVMの名前、監査の状態、イベントの種類、ログ形式、およびターゲット ディレクトリを表示します。

[listing]
----
cluster1::> vserver object-store-server audit show

Vserver     State  Event Types Log Format Target Directory
----------- ------ ----------- ---------- --------------------
vs1         false  data        json       /audit_log
----
次の例は、すべてのSVMの名前、および監査ログの詳細情報を表示します。

[listing]
----
cluster1::> vserver object-store-server audit show -log-save-details

                  Rotation                           Rotation
      Vserver     File Size Rotation Schedule        Limit
      ----------- --------- ------------------------ --------
      vs1         100MB     -                        0
----
次の例は、すべてのSVMに関するすべての監査設定情報をリスト形式で表示します。

[listing]
----
cluster1::> vserver object-store-server audit show -instance

                             Vserver: vs1
                      Auditing state: true
                Log Destination Path: /audit_log
       Categories of Events to Audit: data
                          Log Format: json
                 Log File Size Limit: 100MB
        Log Rotation Schedule: Month: -
  Log Rotation Schedule: Day of Week: -
          Log Rotation Schedule: Day: -
         Log Rotation Schedule: Hour: -
       Log Rotation Schedule: Minute: -
                  Rotation Schedules: -
            Log Files Rotation Limit: 0
                  Log Retention Time: 0s
----