---
sidebar: sidebar 
permalink: s3-snapmirror/index.html 
keywords: s3 snapmirror buckets, snapmirror buckets SVM, s3 snapmirror data protection, hybrid cloud bundle, s3 snapmirror relationship, VM peering, cluster and storage VM peering, Fan-in deployments, data protection, s3 snapmirror policy, peering 
summary: ONTAP 9 .10.1以降では、使い慣れたSnapMirrorのミラーリングとバックアップの機能を使用して、ONTAP S3オブジェクトストアのバケットを保護できます。 
---
= SnapMirror S3の概要
:hardbreaks:
:toclevels: 1
:allow-uri-read: 
:toclevels: 1
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
ONTAP 9 .10.1以降では、SnapMirrorのミラーリングとバックアップの機能を使用してONTAP S3オブジェクトストアのバケットを保護できます。標準のSnapMirrorとは異なり、SnapMirror S3では、AWS S3などのNetApp以外のデスティネーションへのミラーリングとバックアップが可能です。

SnapMirror S3では、ONTAP S3バケットから次のデスティネーションへのアクティブなミラー階層とバックアップ階層がサポートされます。

[cols="50,25,25"]
|===
| ターゲット | アクティブなミラーとテイクオーバーのサポート | バックアップとリストアのサポート 


 a| 
ONTAP S3

* 同じSVM内のバケット
* 同じクラスタの異なるSVMのバケット
* 異なるクラスタのSVM内のバケット

| 〇 | 〇 


| StorageGRID | いいえ | 〇 


| AWS S3 | いいえ | 〇 


| Cloud Volumes ONTAP for Azure | 〇 | 〇 


| Cloud Volumes ONTAP for AWS | 〇 | 〇 


| Cloud Volumes ONTAP for Google Cloud | 〇 | 〇 
|===
ONTAP S3サーバ上の既存のバケットを保護することも、新しく作成したバケットですぐにデータ保護を有効にすることもできます。



== SnapMirror S3の要件

* ONTAPのバージョン
+
ソースクラスタとデスティネーションクラスタでONTAP 9 .10.1以降が実行されている必要があります。

* ライセンス
+
のアクセスを提供するには、ONTAPソースシステムとデスティネーションシステムに次のライセンスがソフトウェアスイートに含まれているlink:../system-admin/manage-licenses-concept.html["ONTAP One"]必要があります。

+
** ONTAP S3プロトコルとストレージ
** 他のNetAppオブジェクトストアターゲット（ONTAP S3、StorageGRID、Cloud Volumes ONTAP）をターゲットにするためのSnapMirror S3
** AWS S3などのサードパーティのオブジェクトストアをターゲットとするSnapMirror S3（で使用可能link:../data-protection/install-snapmirror-cloud-license-task.html["ONTAP One互換バンドル"]）


* ONTAP S3
+
** ONTAP S3サーバでソースとデスティネーションのSVMが実行されている必要があります。
** TLSアクセス用のCA証明書をS3サーバをホストするシステムにインストールすることを推奨しますが、必須ではありません。
+
*** S3サーバの証明書への署名に使用したCA証明書が、S3サーバをホストするクラスタの管理Storage VMにインストールされている必要があります。
*** 自己署名CA証明書または外部CAベンダーが署名した証明書を使用できます。
*** ソースまたはデスティネーションのStorage VMがHTTPSをリスンしていない場合は、CA証明書をインストールする必要はありません。




* ピアリング（ONTAP S3ターゲット用）
+
** クラスタ間LIFが設定されている（リモートONTAPターゲット用）必要があり、ソースクラスタとデスティネーションクラスタのクラスタ間LIFが、ソースとデスティネーションのS3サーバのデータLIFに接続できるようになります。
** ソースクラスタとデスティネーションクラスタがピア関係にある（リモートONTAPターゲットの場合）。
** ソースとデスティネーションのStorage VMがピア関係にある（すべてのONTAPターゲットに対して）。


* SnapMirrorポリシー
+
** すべてのSnapMirror S3関係にS3固有のSnapMirrorポリシーが必要ですが、複数の関係に同じポリシーを使用できます。
** 独自のポリシーを作成するか、次の値を含むデフォルトの * Continuous * ポリシーをそのまま使用できます。
+
*** Throttle（スループット/帯域幅の上限）-無制限。
*** 目標復旧時点までの時間： 1 時間（ 3600 秒）







NOTE: 2つのS3バケットがSnapMirror関係にある場合、オブジェクトの現在のバージョンが期限切れになる（削除される）ようにライフサイクルポリシーが設定されていると、同じ処理がパートナーバケットにレプリケートされることに注意してください。これは、パートナーバケットが読み取り専用またはパッシブの場合でも同様です。

* rootユーザキーSnapMirror S3関係にはStorage VMのrootユーザアクセスキーが必要です。ONTAPではデフォルトで割り当てられません。SnapMirror S3関係の初回作成時には、キーがソースとデスティネーションの両方のStorage VMに存在することを確認し、存在しない場合は再生成する必要があります。それらのキーを再生成する必要がある場合は、アクセスキーとシークレットキーのペアを使用するすべてのクライアントおよびSnapMirrorオブジェクトストアの設定が新しいキーで更新されていることを確認する必要があります。


S3サーバの設定については、次のトピックを参照してください。

* link:../task_object_provision_enable_s3_server.html["Storage VMでS3サーバを有効にする"]
* link:../s3-config/index.html["S3の設定プロセスの概要"]


クラスタとStorage VMのピアリングについては、次のトピックを参照してください。

* link:../task_dp_prepare_mirror.html["ミラーリングとバックアップの準備（System Manager、手順1~6）"]
* link:../peering/index.html["クラスタとSVMのピアリング（CLI）"]




== サポートされるSnapMirror関係

SnapMirror S3では、ファンアウト関係とカスケード関係がサポートされます。概要については、を参照してくださいlink:../data-protection/supported-deployment-config-concept.html["ファンアウト構成およびカスケード構成のデータ保護"]。

SnapMirror S3は、ファンイン環境（複数のソースバケットと1つのデスティネーションバケット間のデータ保護関係）をサポートしていません。SnapMirror S3では、複数のクラスタから単一のセカンダリクラスタへの複数のバケットミラーをサポートできますが、各ソースバケットにセカンダリクラスタ上の専用のデスティネーションバケットが必要です。



== S3バケットへのアクセスを制御

新しいバケットを作成するときに、ユーザとグループを作成してアクセスを制御できます。詳細については、次のトピックを参照してください。

* link:../task_object_provision_add_s3_users_groups.html["S3のユーザとグループの追加（System Manager）"]
* link:../s3-config/create-s3-user-task.html["S3ユーザの作成（CLI）"]
* link:../s3-config/create-modify-groups-task.html["S3グループの作成と変更（CLI）"]

