---
sidebar: sidebar 
permalink: s3-snapmirror/requirements-cloud-targets-concept.html 
keywords: requirements for cloud target relationships, ontap s3, snapmirror, s3, cloud target 
summary: ソースとターゲットの環境が、クラウドターゲットに対するSnapMirror S3バックアップ保護の要件を満たしていることを確認します。 
---
= ONTAP SnapMirror S3のクラウドターゲットの関係の要件
:hardbreaks:
:toclevels: 1
:allow-uri-read: 
:toclevels: 1
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
ソースとターゲットの環境が、クラウドターゲットに対するSnapMirror S3バックアップ保護の要件を満たしていることを確認します。

データバケットにアクセスするには、オブジェクトストアプロバイダとの有効なアカウントクレデンシャルが必要です。

クラスタをクラウドオブジェクトストアに接続する前に、クラスタ間LIFとIPspaceをクラスタに設定しておく必要があります。ローカルストレージからクラウドオブジェクトストアにデータをシームレスに転送できるように、各ノードにクラスタ間LIFを作成する必要があります。

StorageGRIDターゲットについて、次の情報を確認しておく必要があります。

* サーバ名（完全修飾ドメイン名（FQDN）またはIPアドレスで指定）
* バケット名。既存のバケットを指定する必要があります。
* アクセスキー
* シークレットキー


また、StorageGRIDサーバ証明書への署名に使用したCA証明書が、を使用してONTAP S3クラスタの管理Storage VMにインストールされている必要があり `security certificate install command`ます。詳細については、「link:../fabricpool/install-ca-certificate-storagegrid-task.html["CA 証明書をインストールしています"]StorageGRIDを使用する場合」を参照してください。

AWS S3ターゲットについて、次の情報を確認しておく必要があります。

* サーバ名（完全修飾ドメイン名（FQDN）またはIPアドレスで指定）
* バケット名。既存のバケットを指定する必要があります。
* アクセスキー
* シークレットキー


ONTAPクラスタの管理Storage VMのDNSサーバが、FQDN（使用する場合）をIPアドレスに解決できる必要があります。
