---
permalink: nvme/support-limitations.html 
sidebar: sidebar 
keywords: nvme, namespaces, considerations, provisioning 
summary: NVMeのサポートは、ONTAP のバージョン、プラットフォーム、構成によって異なります。 
---
= NVMeのサポートと制限
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
NVMeのサポートと制限は、ONTAP のバージョン、プラットフォーム、構成によって異なります。



== プロトコルのサポート

[cols="3*"]
|===


| プロトコル | 先頭のドキュメント | 許可者 


| TCP | ONTAP 9.10.1 | デフォルト 


| FCP | ONTAP 9.4 | デフォルト 
|===


== プラットフォームおよび構成のサポートと制限事項

NVMe-oFプロトコルのサポートは、プラットフォームや構成によって異なります。具体的な構成の詳細については、を参照してください link:https://imt.netapp.com/matrix/["NetApp Interoperability Matrix Tool で確認できます"]。


NOTE: ONTAP 9.12.1以降では、NVMe/FCで4ノードMetroCluster IP構成がサポートされます。9.12.1よりも前のNVMeでは、MetroCluster 構成はサポートされません。

[cols="2*"]
|===


| ONTAP で開始しています... | プラットフォーム 


| 9.12.1:  a| 
* FAS
* All Flash FAS （AFF ）
* All SAN Array（ASA ）プラットフォーム




| 9.9.1  a| 
* AFF
* ASA




| 9.4 | AFF プラットフォームのみ 
|===


== ネームスペースのサポートと制限

SAN 環境で NVMe プロトコルをセットアップするには、 NVMe 用の SVM を設定し、ネームスペースとサブシステムを作成し、 NVMe/FC LIF を設定し、ネームスペースをサブシステムにマッピングする必要があります。NVMeネームスペースを使用する場合は、次の点に注意してください。

* ONTAP 9.10.1 以降では、次のことが可能になります xref:../nvme/resize-namespace-task.html[ネームスペースのサイズを変更する]。ONTAP 9.10.1 より前のリリースでは、ネームスペースのサイズ変更はサポートされていません。
* ONTAP 9.6 以降では、ネームスペースで 512 バイトブロックと 4096 バイトブロックがサポートされます。
+
デフォルト値は 4096 です。ホストオペレーティングシステムで 4096 バイトブロックがサポートされていない場合のみ、 512 を使用してください。

* LUN のデータが失われた場合、ネームスペースからリストアすることはできません。また、その逆も同様です。
* ネームスペースのスペースギャランティはそれを含むボリュームのスペースギャランティと同じになります。
* ネームスペースでは、次のものはサポートされません。
+
** 名前変更中です
+
ネームスペースの名前は変更できません。

** ボリューム間での移動
** ボリューム間でのコピー



