---
permalink: nvme/support-limitations.html 
sidebar: sidebar 
keywords: nvme, namespaces, considerations, provisioning 
summary: NVMeのサポートは、ONTAP のバージョン、プラットフォーム、構成によって異なります。 
---
= NVMeのサポートと制限
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
NVMeのサポートと制限事項は、ONTAPのバージョン、プラットフォーム、構成によって異なります。具体的な構成の詳細については、を参照してください link:https://imt.netapp.com/matrix/["NetApp Interoperability Matrix Tool で確認できます"]。

プロトコルのサポート

[cols="3*"]
|===


| プロトコル | ONTAP で開始しています... | 許可者 


| TCP | 9.10.1 | デフォルト 


| FC | 9.4 | デフォルト 
|===
ONTAP 9.8以降では、同じStorage Virtual Machine（SVM）にSCSI、NAS、NVMeの各プロトコルを設定できます。
ONTAP 9.7以前では、SVMで使用できるプロトコルはNVMeのみです。



== プラットフォームおよび構成のサポートと制限事項

NVMe/FCプロトコルとNVMe/TCPプロトコルは次のようにサポートされます。  NVMe/FCは、32Gb FC HBAのみを搭載した以下のプラットフォームでサポートされます。

[cols="3*"]
|===


| ONTAP で開始しています... | プラットフォーム | クラスタあたりの最大ノード数 


| 9.12.1:  a| 
* AFF
* ASA
* Cシリーズ

| 12 


| 9.10.1  a| 
* AFF
* ASA

| 4. 


| 9.9.1  a| 
* AFF
* ASA

| 4. 


| 9.4 | AFFのみ | 4. 
|===


== MetroCluster 構成

ONTAP 9.12.1以降では、NVMe/FCで4ノードMetroCluster IP構成がサポートされます。9.12.1よりも前のNVMeでは、MetroCluster 構成はサポートされません。



== ネームスペースのサポートと制限

NVMeネームスペースのサポートは、ONTAPのバージョンによって異なります。

[cols="2*"]
|===


| ONTAP で開始しています... | NVMeネームスペースのサポート... 


| 9.10.1 | xref:../nvme/resize-namespace-task.html[サイズ変更中です]

ONTAP 9.10.1 より前のリリースでは、ネームスペースのサイズ変更はサポートされていません。 


| 9.8 | LUNとネームスペースは同じボリュームに混在させることができます。 


| 9.6  a| 
* 512バイトブロックと4、096バイトブロック
+
デフォルト値は 4096 です。ホストオペレーティングシステムで 4096 バイトブロックがサポートされていない場合のみ、 512 を使用してください。

* ネームスペースがマッピングされたボリュームの移動


|===
NVMeネームスペースを使用する場合は、次の点にも注意してください。

* LUN のデータが失われた場合、ネームスペースからリストアすることはできません。また、その逆も同様です。
* ネームスペースのスペースギャランティはそれを含むボリュームのスペースギャランティと同じになります。
* 7-ModeのData ONTAPからのボリューム移行では、ネームスペースを作成できません。
* ネームスペースでは、次のものはサポートされません。
+
** 名前変更中です
+
ネームスペースの名前は変更できません。

** ボリューム間での移動
** ボリューム間でのコピー
** オンデマンドコピー






== マルチパス HA ペアのフェイルオーバー / ギブバック

ONTAP 9.5以降では、マルチパスHAペアのフェイルオーバー/ギブバックがサポートされます。



== その他の制限事項

* ONTAP の次の機能は、 NVMe 構成ではサポートされません。
+
** 同期
** Virtual Storage Console の略


* 次の説明は、 ONTAP 9.4 を実行しているノードのみに該当します。
+
** NVMe の LIF とネームスペースは、同じノードでホストする必要があります。
** NVMe LIF を作成する前に、 NVMe サービスを作成する必要があります。




を参照してください https://hwu.netapp.com["NetApp Hardware Universe の略"^] をクリックしてください。

.関連情報
link:https://www.netapp.com/pdf.html?item=/media/10680-tr4080.pdf["最新SANのベストプラクティス"]
