= ONTAP 9.11.1RC1に関する考慮事項
:allow-uri-read: 




== ONTAP 9.11.1RC1に関する考慮事項

ONTAP バージョン9.11.1RC1の変更により、FIPS 140-2準拠管理モードではFIPS 140-2準拠のソフトウェアモジュールが使用されなくなりました。

ONTAP 9.11.1RC1では、HTTPSの管理プレーンとコントロールプレーンの接続に使用するOpenSSLのバージョンがアップグレードされました。このバージョンのOpenSSL（OpenSSL 3.x FIPSプロバイダ）では、FIPS 140-2暗号モジュール検証プログラム（CMVP）検証プロセスがまだ完了していません。

FIPS準拠モードが有効になっている場合、HTTPS接続に使用される暗号化アルゴリズムは、Cryptographic Algorithm Validation Program（CAVP）証明書A1938で発行されたOpenSSL 3.x FIPSプロバイダアルゴリズムと同じです。*この変更は、FIPS準拠モードに設定されているONTAP システムにのみ適用されます。*

この問題 は、ONTAP 9.11.1RC1でアップグレードされたOpenSSLモジュールがNISTによるFIPS 140-2検証を完了した時点で修正されます。ONTAP クラスタ管理コントロールプレーンでFIPS 140-2 CMVP認定モジュールを使用する必要がある環境では、9.11.1RC1にアップグレードしないことを推奨します。

NSE、NVE ONTAP 、NAEなどの保管テクノロジでは、OpenSSLに搭載されている暗号化モジュールとは異なる暗号化モジュールを使用するため、この機能はネットアップの暗号化には影響しません。

詳細については、を参照してください link:https://kb.netapp.com/Advice_and_Troubleshooting/Data_Storage_Software/ONTAP_OS/Upgrading_to_ONTAP_9.11.1RC1_results_in_FIPS_140-2_compliance_management_configuration_that_is_not_validated["ONTAP 9.11.1RC1にアップグレードすると、FIPS 140-2準拠の管理設定が検証されなくなります"^]。
