= 
:allow-uri-read: 


Windows を使用する SMB クライアントは、ファイルごとの読み取り専用ビットを設定できます。NFS クライアントは、ファイルごとの読み取り専用ビットを設定しません。 NFS クライアントは、ファイルごとの読み取り専用ビットを使用するプロトコル操作を行わないためです。

ONTAP は、 Windows を使用する SMB クライアントによってファイルが作成される際に、そのファイルに読み取り専用ビットを設定できます。ファイルが NFS クライアントと SMB クライアント間で共有されている場合も、 ONTAP は読み取り専用ビットを設定できます。一部のソフトウェアは、 NFS クライアントおよび SMB クライアントで使用される場合、読み取り専用ビットが有効になっている必要があります。

NFS クライアントと SMB クライアント間で共有されるファイルに対して、適切な読み取りおよび書き込み権限を保持するために、読み取り専用ビットが次の規則に従って処理されます。 ONTAP

* NFS は、読み取り専用ビットが有効になっているファイルを書き込み権限ビットが無効になっているファイルとして扱います。
* NFS クライアントがすべての書き込み権限ビットを無効にしたときに、これらのうち少なくとも 1 つが以前有効であったら、 ONTAP はそのファイルの読み取り専用ビットを有効にします。
* NFS クライアントがすべての書き込み権限ビットを有効にすると、 ONTAP はそのファイルの読み取り専用ビットを無効にします。
* あるファイルの読み取り専用ビットが有効になっているときに、 NFS クライアントがそのファイルの権限を調べようとすると、そのファイルの権限ビットは NFS クライアントには送信されず、代わりに書き込み権限ビットがマスクされた権限ビットが ONTAP クライアントに送信されます。
* ファイルの読み取り専用ビットが有効になっているときにSMBクライアントがその読み取り専用ビットを無効にすると、ONTAPはそのファイルに対する所有者の書き込み権限ビットを有効にします。
* 読み取り専用ビットが有効になっているファイルに書き込めるのは、 root のみです。


読み取り専用ビットは、ACL および Unix モード ビットと次のように相互作用します。

ファイルに読み取り専用ビットが設定されている場合:

* そのファイルの ACL は変更されません。NFSクライアントには、読み取り専用ビットが設定される前と同じ ACL が表示されます。
* ファイルへの書き込みアクセスを許可する Unix モード ビットはすべて無視されます。
* NFS クライアントと SMB クライアントはどちらもファイルを読み取ることはできますが、変更することはできません。
* ACLとUNIXモードビットは、読み取り専用ビットが優先されるため無視されます。つまり、ACLが書き込みアクセスを許可していても、読み取り専用ビットによって変更は禁止されます。


ファイルに読み取り専用ビットが設定されていない場合:

* ONTAP は、ACL と UNIX モード ビットに基づいてアクセスを決定します。
+
** ACL または UNIX モード ビットのいずれかが書き込みアクセスを拒否した場合、NFS および SMB クライアントはファイルを変更できません。
** ACL も UNIX モード ビットも書き込みアクセスを拒否しない場合は、NFS および SMB クライアントはファイルを変更できます。




[NOTE]
====
ファイル権限の変更は、 SMB クライアントではすぐに反映されますが、 NFS クライアントが属性のキャッシュを有効にしている場合は NFS クライアントではすぐに反映されないことがあります。

====