= 
:allow-uri-read: 


. を使用します `system license show` FCまたはiSCSIのライセンスがあるかどうかを確認するコマンド。
+
`system license show`

+
[listing]
----

Package           Type    Description           Expiration
 ----------------- ------- --------------------- --------------------
 Base              site    Cluster Base License  -
 NFS               site    NFS License           -
 CIFS              site    CIFS License          -
 iSCSI             site    iSCSI License         -
 FCP               site    FCP License           -
----
. FCまたはiSCSIのライセンスがない場合は、を使用してください `license add` コマンドを実行します
+
`license add -license-code _your_license_code_`

. SVMでプロトコルサービスを有効にします。
+
* iSCSIの場合：* `vserver iscsi create -vserver _vserver_name_ -target-alias _vserver_name_`

+
* FCの場合：* `vserver fcp create -vserver _vserver_name_ -status-admin up`

. 各ノードにSVM用のLIFを2つ作成します。
+
`network interface create -vserver _vserver_name_ -lif _lif_name_ -role data -data-protocol iscsi|fc -home-node _node_name_ -home-port _port_name_ -address _ip_address_ -netmask netmask`

+
ネットアップでは、データを提供するSVMごとに、ノードごとに少なくとも1つのiSCSIまたはFC LIFをサポートしています。ただし、冗長性を確保するには、ノードごとに2つのLIFが必要です。

. LIFが作成されたこと、および動作ステータスがになっていることを確認します `online`：
+
`network interface show -vserver _vserver_name_ _lif_name_`

. LUN を作成します。
+
`lun create -vserver vserver_name -volume _volume_name_ -lun _lun_name_ -size _lun_size_ -ostype linux -space-reserve enabled|disabled`

+
LUN 名は 255 文字以内で、スペースは使用できません。

+

NOTE: NVFAIL オプションは、ボリュームで LUN が作成されると、自動的に有効になります。

. igroup を作成します。
+
`igroup create -vserver _vserver_name_ -igroup _igroup_name_ -protocol fcp|iscsi|mixed -ostype linux -initiator _initiator_name_`

. LUN を igroup にマッピングします。
+
`lun mapping create -vserver _vserver_name_ -volume _volume_name_ -lun _lun_name_ -igroup _igroup_name_`

. LUN が正しく設定されていることを確認します。
+
`lun show -vserver _vserver_name_`

. link:san-admin/create-port-sets-binding-igroups-task.html["ポートセットを作成してigroupにバインドします"] （オプション）。
. ホストのマニュアルに記載されている手順に従って、特定のホストでブロックアクセスを有効にします。
. Host Utilities を使用して FC または iSCSI マッピングを完了し、ホスト上の LUN を検出します。

