---
sidebar: sidebar 
permalink: networking/add_or_remove_a_lif_from_a_load_balancing_zone.html 
keywords: lif, adding, add, create, creating, remove, removing, delete, deleting, load, balancing, zone, dns, svm, storage, virtual, add or remove a LIF from a load balancing zone, machine, add a lif, remove a single lif, remove all lifs 
summary: Storage Virtual Machine （ SVM ）の DNS ロードバランシングゾーンに対して LIF を追加または削除する 
---
= ロードバランシングゾーンに対するONTAP LIFの追加または削除
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
仮想マシン（SVM）のDNSロードバランシングゾーンに対してLIFを追加または削除できます。また、すべてのLIFをロードバランシングゾーンから同時に削除することもできます。

.開始する前に
* ロードバランシングゾーンのLIFはすべて同じSVMに属している必要があります。
* 1つのLIFが属することができるDNSロードバランシングゾーンは1つだけです。
* LIFが別 々 のサブネットに属している場合は、各サブネットのフェイルオーバーグループが設定されている必要があります。


.タスクの内容
管理ステータスがdownのLIFは、一時的にDNSロードバランシングゾーンから削除されます。LIFの管理ステータスがupに戻ると、LIFは自動的にDNSロードバランシングゾーンに追加されます。

.ステップ
ロードバランシングゾーンに対してLIFを追加または削除します。

[cols="30,70"]
|===


| 状況 | 入力するコマンド 


 a| 
LIFを追加する
 a| 
`network interface modify -vserver _vserver_name_ -lif _lif_name_ -dns-zone _zone_name_`例：
`network interface modify -vserver vs1 -lif data1 -dns-zone cifs.company.com`



 a| 
1 つの LIF を削除する
 a| 
`network interface modify -vserver _vserver_name_ -lif _lif_name_ -dns-zone none`例： `network interface modify -vserver vs1 -lif data1 -dns-zone none`



 a| 
すべての LIF を削除します
 a| 
`network interface modify -vserver _vserver_name_ -lif * -dns-zone none` 例：
`network interface modify -vserver vs0 -lif * -dns-zone none`ロードバランシングゾーンからSVMのすべてのLIFを削除することで、そのゾーンからSVMを削除できます。

|===
.関連情報
* link:https://docs.netapp.com/us-en/ontap-cli/network-interface-modify.html["network interface modify"^]

