---
sidebar: sidebar 
permalink: networking/add_or_remove_a_lif_from_a_load_balancing_zone.html 
keywords: lif, adding, add, create, creating, remove, removing, delete, deleting, load, balancing, zone, dns, svm, storage, virtual, add or remove a LIF from a load balancing zone, machine, add a lif, remove a single lif, remove all lifs 
summary: ストレージ仮想マシン（SVM）のDNSロード バランシング ゾーンにLIFを追加または削除する 
---
= ロード バランシング ゾーンへのONTAP LIFの追加または削除
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
Storage Virtual Machine（SVM）のDNSロード バランシング ゾーンに対してLIFを追加または削除できます。すべてのLIFをロード バランシング ゾーンから同時に削除することもできます。

.開始する前に
* ロード バランシング ゾーンのLIFは、すべて同じSVMに属している必要があります。
* LIFは1つのDNSロード バランシング ゾーンだけに含めることができます。
* サブネットの異なるLIFがある場合は、サブネットごとのフェイルオーバー グループが設定されている必要があります。


.タスク概要
管理ステータスがdownのLIFは一時的にDNSロード バランシング ゾーンから削除されます。LIFの管理ステータスがupに戻ると、自動的にDNSロード バランシング ゾーンに追加されます。

.手順
ロード バランシング ゾーンに対してLIFを追加または削除します。

[cols="30,70"]
|===


| 状況 | 入力する内容 


 a| 
LIFを追加する
 a| 
`network interface modify -vserver _vserver_name_ -lif _lif_name_ -dns-zone _zone_name_` 例：
`network interface modify -vserver vs1 -lif data1 -dns-zone cifs.company.com`



 a| 
単一のLIFを削除する
 a| 
`network interface modify -vserver _vserver_name_ -lif _lif_name_ -dns-zone none` 例： `network interface modify -vserver vs1 -lif data1 -dns-zone none`



 a| 
すべてのLIFを削除する
 a| 
`network interface modify -vserver _vserver_name_ -lif * -dns-zone none` 例：
`network interface modify -vserver vs0 -lif * -dns-zone none` ロード バランシング ゾーンから SVM を削除するには、そのゾーンから SVM 内のすべての LIF を削除します。

|===
.関連情報
* link:https://docs.netapp.com/us-en/ontap-cli/network-interface-modify.html["network interface modify"^]

