---
sidebar: sidebar 
permalink: networking/change_the_mtu_value_for_ports_in_a_broadcast_domain97.html 
keywords: modify, modifying, mtu, mtu_value, change, changing, broadcast, domain, ports, port, change the mtu value for ports in a broadcast domain 
summary: ブロードキャストドメインの MTU 値を変更して、ブロードキャストドメインのすべてのポートのその値を変更します 
---
= ブロードキャストドメインのポートの MTU 値を変更します
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
あるブロードキャストドメインの MTU 値を変更することにより、そのブロードキャストドメインのすべてのポートの MTU 値を変更できます。これは、ネットワークで行われたトポロジの変更をサポートするために実行できます。

.作業を開始する前に
管理トラフィックを処理する e0M ポートを除く、レイヤ 2 ネットワークに接続されているすべてのデバイスの MTU 値が一致している必要があります。

.このタスクについて
MTU 値を変更すると、影響を受けるポートを経由するトラフィックが一時的に中断されます。プロンプトが表示され、回答の MTU 値を変更するために「 y 」と入力する必要があります。

.ステップ
ブロードキャストドメインのすべてのポートの MTU 値を変更します。

....
network port broadcast-domain modify -broadcast-domain <broadcast_domain_name> -mtu <mtu_value> [-ipspace <ipspace_name>]
....
* `broadcast_domain` は、ブロードキャストドメインの名前です。
* `mtu` はIPパケットのMTUサイズです。通常は1500と9000です。
* `ipspace` は、このブロードキャストドメインが配置されているIPspaceの名前です。「 default 」 IPspace は、このオプションの値を指定しないかぎり使用されます。次のコマンドは、ブロードキャストドメイン「 bcast1 」のすべてのポートの MTU を 9000 に変更します。


....
network port broadcast-domain modify -broadcast-domain <Default-1> -mtu < 9000 >
Warning: Changing broadcast domain settings will cause a momentary data-serving interruption.
Do you want to continue? {y|n}: <y>
....