---
sidebar: sidebar 
permalink: networking/change_the_mtu_value_for_ports_in_a_broadcast_domain.html 
keywords: modify, modifying, mtu, mtu_value, change, changing, broadcast, domain, ports, port, change the mtu value for ports in a broadcast domain 
summary: ブロードキャスト ドメインの MTU 値を変更すると、ブロードキャスト ドメイン内のすべてのポートの MTU 値が変更されます 
---
= ONTAPブロードキャストドメイン内のポートのMTU値を変更する
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
あるブロードキャスト ドメインのMTU値を変更することにより、そのブロードキャスト ドメインのすべてのポートのMTU値を変更できます。この操作は、ネットワークに加えられたトポロジの変更を反映させるために行います。


NOTE: ブロードキャスト ドメイン ポートのMTU値を変更する手順は、ONTAP 9.7以前のバージョンでは異なります。ONTAP 9.7以前を実行しているネットワークでブロードキャスト ドメイン ポートのMTU値を変更する必要がある場合は、link:https://docs.netapp.com/us-en/ontap-system-manager-classic/networking-bd/change_the_mtu_value_for_ports_in_a_broadcast_domain97.html["ブロードキャスト ドメインのポートのMTU値の変更（ONTAP 9.7以前）"^]を参照してください。

.開始する前に
MTU値は、管理トラフィックを処理するe0Mポートを除き、そのレイヤ2ネットワークに接続されているすべてのデバイスで同じである必要があります。

.タスク概要
MTU値を変更すると、その影響を受けるポートを経由するトラフィックが一時的に中断されます。プロンプトが表示されるので、MTU値を変更するために「y」と入力する必要があります。

.手順
ブロードキャスト ドメインのすべてのポートのMTU値を変更します。

....
network port broadcast-domain modify -broadcast-domain <broadcast_domain_name> -mtu <mtu_value> [-ipspace <ipspace_name>]
....
* `broadcast_domain` は、ブロードキャスト ドメインの名前です。
* `mtu`は IP パケットの MTU サイズです。一般的な値は 1500 と 9000 です。
* `ipspace`このブロードキャスト ドメインが存在する IPspace の名前です。このオプションに値を指定しない限り、「Default」IPspace が使用されます。次のコマンドは、ブロードキャスト ドメイン bcast1 内のすべてのポートの MTU を 9000 に変更します：


....
network port broadcast-domain modify -broadcast-domain <Default-1> -mtu < 9000 >
Warning: Changing broadcast domain settings will cause a momentary data-serving interruption.
Do you want to continue? {y|n}: <y>
....
.関連情報
* link:https://docs.netapp.com/us-en/ontap-cli/network-port-broadcast-domain-modify.html["ネットワーク ポート ブロードキャスト ドメインの変更"^]

