---
sidebar: sidebar 
permalink: networking/commands_for_managing_snmp.html 
keywords: snmp, traps, traphosts, trap, traphost, manage, managing, users, user, configure, configuring, modify, modifying, set, setting, event, command, system snmp, security, options -option-name snmp.enable -option-value on, options -option-name snmp.enable -option-value off, commands for managing snmp, commands for managing snmp v1, v2c, and v3 users, commands for providing contact and location information, commands for managing SNMP communities, command for displaying snmp option values, commands for managing snmp traps and traphosts, commands for managing events related to snmp traps, system snmp, security login create, security snmpusers and security login show -application snmp, security login create, security login delete, security snmpusers and security login show -application snmp, security login modify, system snmp contact, system snmp location, system snmp community add, system snmp community delete, system snmp community show, system snmp show 
summary: SNMP 、 SNMP ユーザ、トラップ、トラップイベント、およびトラップホストを管理します 
---
= SNMP を管理するためのコマンド
:hardbreaks:
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
SNMP 、トラップ、およびトラップホストの管理には、「 system snmp 」コマンドを使用します。「 security」 コマンドを使用すると、 SVM 単位の SNMP ユーザを管理できます。SNMP トラップに関連するイベントを管理するには 'event' コマンドを使用します



== SNMP を設定するためのコマンド

[cols="2*"]
|===
| 状況 | 使用するコマンド 


| クラスタで SNMP を有効にします | 管理（ mgmt ）ファイアウォールポリシーで、 SNMP サービスの options -option-name snmp.enable -option-value を許可する必要があります。SNMP が許可されているかどうかを確認するには、 system services firewall policy show コマンドを使用します。 


| クラスタで SNMP を無効にします | options -option-name snmp.enable -option-value off 
|===


== SNMP v1 、 v2c 、および v3 ユーザを管理するコマンド

[cols="2*"]
|===
| 状況 | 使用するコマンド 


| SNMP ユーザを設定する | security login create を実行します 


| SNMP ユーザを表示します | security snmpusers および security login show -application snmp のように入力します 


| SNMP ユーザを削除する | security login delete のコマンドを実行します 


| SNMP ユーザのログイン方法のアクセス制御ロール名を変更します | セキュリティログインの変更 
|===


== 連絡先と場所の情報を提供するコマンド

[cols="2*"]
|===
| 状況 | 使用するコマンド 


| クラスタの連絡先の詳細を表示または変更する | システム SNMP の連絡先 


| クラスタの場所の詳細を表示または変更する | システム SNMP の場所 
|===


== SNMP コミュニティを管理するコマンド

[cols="2*"]
|===
| 状況 | 使用するコマンド 


| 1 つの SVM 、またはクラスタのすべての SVM に読み取り専用（ ro ）コミュニティを追加する | system snmp community add コマンド 


| 1 つまたはすべてのコミュニティを削除します | system snmp community delete 


| すべてのコミュニティのリストを表示します | system snmp community show のコマンドです 
|===
SVM は SNMP 標準の一部ではないので、データ LIF でのクエリにはネットアップのルート OID （ 1.3.6.1.4.1.789 ）を含める必要があります。たとえば、「 mpwalk -v 2c -c snmpNFS 10.238.19.14 1.3.6.1.4.1.789 」のように指定します。



== SNMP オプションの値を表示するコマンド

[cols="2*"]
|===
| 状況 | 使用するコマンド 


| クラスタの連絡先、連絡先、トラップホストを送信するようにクラスタが設定されているかどうか、トラップホストのリスト、コミュニティとアクセス制御の種類のリストなど、すべての SNMP オプションの現在の値を表示します | system snmp show コマンドを実行します 
|===


== SNMP のトラップおよびトラップホストを管理するコマンド

[cols="2*"]
|===
| 状況 | 使用するコマンド 


| クラスタからの SNMP トラップの送信を有効にします | System SNMP init-init 1 」のように入力します 


| クラスタからの SNMP トラップの送信を無効にします | System SNMP init-init 0 


| クラスタの特定のイベントに関する SNMP 通知を受信するトラップホストを追加します | system snmp traphost add コマンドを使用します 


| トラップホストを削除します | システムの SNMP トラップホストが削除された 


| トラップホストのリストを表示します | system snmp traphost show を使用します 
|===


== SNMP トラップに関連するイベントを管理するコマンド

[cols="2*"]
|===
| 状況 | 使用するコマンド 


 a| 
SNMP トラップ（ビルトイン）が生成されたイベントを表示します
 a| 
イベントルートの表示

SNMP に関連するイベントだけを表示するには、 -snmp-support true パラメータを使用します。

イベントが発生した理由や対処方法などの詳しい概要を表示するには、 instance -messagename <message> パラメータを使用します。

個々の SNMP トラップイベントを特定の送信先トラップホストにルーティングすることはできません。すべての SNMP トラップイベントが、すべての送信先トラップホストに送信されます。



 a| 
SNMP トラップ履歴レコードのリストを表示します。 SNMP トラップに送信されたイベント通知です
 a| 
イベントのフィリストーリーショー



 a| 
SNMP トラップ履歴レコードを削除します
 a| 
イベントの snmphistory delete

|===
「システム SNMP 」、「セキュリティ」、および「イベント」コマンドの詳細については、次のマニュアルページを参照してください。 http://docs.netapp.com/ontap-9/topic/com.netapp.doc.dot-cm-cmpr/GUID-5CB10C70-AC11-41C0-8C16-B4D0DF916E9B.html["ONTAP 9 のコマンド"^]
