---
sidebar: sidebar 
permalink: networking/commands_for_managing_firewall_service_and_policies.html 
keywords: manage, managing, firewall, fire, wall, service, policy, policies, commands for managing firewall service and policies, system services firewall, system services firewall policy, network interface modify, system services firewall modify, system services firewall show, system services firewall policy create, network interface modify -lif lifname -firewall-policy, system services firewall policy modify, system services firewall policy show, system services firewall policy clone, system services firewall policy delete 
summary: ファイアウォールサービスを管理します 
---
= ファイアウォールサービスおよびポリシーを管理するためのコマンド
:hardbreaks:
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
「 system services firewall 」コマンドを使用してファイアウォールサービスを管理したり、「 system services firewall policy 」コマンドでファイアウォールポリシーを管理したり、「 network interface modify 」コマンドで LIF のファイアウォール設定を管理したりできます。

|===


| 状況 | 使用するコマンド 


 a| 
ファイアウォールサービスを有効または無効にします
 a| 
「システムサービスファイアウォールの変更」



 a| 
ファイアウォールサービスの現在の設定を表示します
 a| 
「 system services firewall show



 a| 
ファイアウォールポリシーを作成するか、既存のファイアウォールポリシーにサービスを追加してください
 a| 
「システムサービスファイアウォールポリシー作成」を参照してください



 a| 
ファイアウォールポリシーを LIF に適用する
 a| 
network interface modify -lif lifname -firewall-policy を指定します



 a| 
ファイアウォールポリシーに関連付けられた IP アドレスとネットマスクを変更する
 a| 
「システムサービスファイアウォールポリシーの変更」



 a| 
ファイアウォールポリシーに関する情報を表示する
 a| 
「 system services firewall policy show 」を参照してください



 a| 
既存のファイアウォールポリシーとまったく同一の新しいポリシーを作成します
 a| 
「システムサービスファイアウォールポリシークローン」



 a| 
LIF で使用されていないファイアウォールポリシーを削除する
 a| 
「システムサービスファイアウォールポリシー削除」

|===
詳細については、の「 system services firewall 」、「 system services firewall policy 」、および「 network interface modify 」コマンドのマニュアルページを参照してください link:http://docs.netapp.com/ontap-9/topic/com.netapp.doc.dot-cm-cmpr/GUID-5CB10C70-AC11-41C0-8C16-B4D0DF916E9B.html["ONTAP 9 のコマンド"^]。
