---
sidebar: sidebar 
permalink: networking/commands_for_managing_snmp.html 
keywords: snmp, traps, traphosts, trap, traphost, manage, managing, users, user, configure, configuring, modify, modifying, set, setting, event, command, system snmp, security, options -option-name snmp.enable -option-value on, options -option-name snmp.enable -option-value off, commands for managing snmp, commands for managing snmp v1, v2c, and v3 users, commands for providing contact and location information, commands for managing SNMP communities, command for displaying snmp option values, commands for managing snmp traps and traphosts, commands for managing events related to snmp traps, system snmp, security login create, security snmpusers and security login show -application snmp, security login create, security login delete, security snmpusers and security login show -application snmp, security login modify, system snmp contact, system snmp location, system snmp community add, system snmp community delete, system snmp community show, system snmp show 
summary: SNMP 、 SNMP ユーザ、トラップ、トラップイベント、およびトラップホストを管理します 
---
= SNMP、トラップ、およびトラップホストを管理するためのONTAPコマンド
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
SNMP、トラップ、およびトラップホストを管理するには、コマンドを使用し `system snmp`ます。SVMのSNMPユーザを管理するには、コマンドを使用し `security`ます。SNMPトラップに関連するイベントを管理するには、コマンドを使用し `event`ます。



== SNMPの設定用コマンド

|===


| 状況 | 使用するコマンド 


 a| 
クラスタでSNMPを有効にする
 a| 
`options -option-name snmp.enable -option-value on`

管理（mgmt）ファイアウォールポリシーでSNMPサービスが許可されている必要があります。SNMPが許可されているかどうかを確認するには、system services firewall policy showコマンドを使用します。



 a| 
クラスタでSNMPを無効にする
 a| 
`options -option-name snmp.enable -option-value off`

|===


== SNMP v1、v2c、およびv3ユーザを管理するコマンド

|===


| 状況 | 使用するコマンド 


 a| 
SNMPユーザの設定
 a| 
`security login create`



 a| 
SNMP ユーザを表示します
 a| 
`security snmpusers and security login show -application snmp`



 a| 
SNMP ユーザを削除する
 a| 
`security login delete`



 a| 
SNMPユーザのログイン方法のアクセス制御ロール名を変更する
 a| 
`security login modify`

|===


== 連絡先と場所の情報を提供するコマンド

|===


| 状況 | 使用するコマンド 


 a| 
クラスタの連絡先の詳細を表示または変更する
 a| 
`system snmp contact`



 a| 
クラスタの場所の詳細を表示または変更する
 a| 
`system snmp location`

|===


== SNMPコミュニティの管理用コマンド

|===


| 状況 | 使用するコマンド 


 a| 
1 つの SVM 、またはクラスタのすべての SVM に読み取り専用（ ro ）コミュニティを追加する
 a| 
`system snmp community add`



 a| 
1 つまたはすべてのコミュニティを削除します
 a| 
`system snmp community delete`



 a| 
すべてのコミュニティのリストを表示します。
 a| 
`system snmp community show`

|===
SVMはSNMP標準の一部ではないため、データLIFでのクエリにはNetAppのルートOID（1.3.6.1.4.1.789）を含める必要があります。たとえば、のように指定します。 `snmpwalk -v 2c -c snmpNFS 10.238.19.14 1.3.6.1.4.1.789`



== SNMPオプション値を表示するコマンド

|===


| 状況 | 使用するコマンド 


 a| 
クラスタの連絡先、連絡先の場所、クラスタがトラップを送信するように設定されているかどうか、トラップホストのリスト、コミュニティのリスト、アクセス制御の種類など、すべてのSNMPオプションの現在の値を表示する
 a| 
`system snmp show`

|===


== SNMPトラップおよびトラップホストの管理用コマンド

|===


| 状況 | 使用するコマンド 


 a| 
クラスタから送信されるSNMPトラップを有効にする
 a| 
`system snmp init -init 1`



 a| 
クラスタからのSNMPトラップの送信を無効にする
 a| 
`system snmp init -init 0`



 a| 
クラスタ内の特定のイベントに関するSNMP通知を受信するトラップホストを追加する
 a| 
`system snmp traphost add`



 a| 
トラップホストを削除する
 a| 
`system snmp traphost delete`



 a| 
トラップホストのリストを表示します。
 a| 
`system snmp traphost show`

|===


== SNMPトラップに関連するイベントの管理用コマンド

|===


| 状況 | 使用するコマンド 


 a| 
SNMP トラップ（ビルトイン）が生成されたイベントを表示します
 a| 
`event route show`

SNMP関連のイベントのみを表示するには、パラメータを使用し `-snmp-support true`ます。

パラメータを使用して `instance -messagename <message>`、イベントが発生した理由と対処方法の詳細を表示します。

個 々 のSNMPトラップイベントを特定の送信先トラップホストにルーティングすることはできません。すべてのSNMPトラップイベントがすべての送信先トラップホストに送信されます。



 a| 
SNMP トラップ履歴レコードのリストを表示します。 SNMP トラップに送信されたイベント通知です
 a| 
`event snmphistory show`



 a| 
SNMP トラップ履歴レコードを削除します
 a| 
`event snmphistory delete`

|===
.関連情報
* link:https://docs.netapp.com/us-en/ontap-cli/search.html?q=system+snmp["システムSNMP"^]
* link:https://docs.netapp.com/us-en/ontap-cli/search.html?q=security["セキュリティ"^]
* link:https://docs.netapp.com/us-en/ontap-cli/search.html?q=event["イベント"^]

