---
sidebar: sidebar 
permalink: networking/commands_for_managing_failover_groups_and_policies.html 
keywords: manage, managing, failover, fail, over, group, policy, policies, groups, commands for managing failover groups and policies, network interface failover-groups, network interface modify, network interface failover-groups add-targets, network interface failover-groups remove-targets, network interface failover-groups modify, network interface modify -failover-group -failover-policy, network interface failover-groups show, rename, delete 
summary: フェイルオーバーグループを管理します 
---
= フェイルオーバーグループとポリシーを管理するためのコマンドです
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
を使用できます `network interface failover-groups` フェイルオーバーグループを管理するコマンド。を使用します `network interface modify` LIFのフェイルオーバーグループとフェイルオーバーポリシーを管理するコマンドです。

|===


| 状況 | 使用するコマンド 


 a| 
フェイルオーバーグループにネットワークポートを追加します
 a| 
`network interface failover-groups add-targets`



 a| 
フェイルオーバーグループからネットワークポートを削除します
 a| 
`network interface failover-groups remove-targets`



 a| 
フェイルオーバーグループのネットワークポートを変更する
 a| 
`network interface failover-groups modify`



 a| 
現在のフェイルオーバーグループを表示します
 a| 
`network interface failover-groups show`



 a| 
LIF のフェイルオーバーを設定する
 a| 
`network interface modify -failover-group -failover-policy`



 a| 
各 LIF で使用されているフェイルオーバーグループとフェイルオーバーポリシーを表示します
 a| 
`network interface show -fields failover-group, failover-policy`



 a| 
フェイルオーバーグループの名前を変更します
 a| 
`network interface failover-groups rename`



 a| 
フェイルオーバーグループを削除します
 a| 
`network interface failover-groups delete`

|===

NOTE: フェイルオーバーグループを変更した結果、クラスタ内のどの LIF も有効なフェイルオーバーターゲットを持たなくなってしまうと、 LIF がフェイルオーバーしようとしたときにシステムが停止する可能性があります。

詳細については、のマニュアルページを参照してください `network interface failover-groups` および `network interface modify` コマンド
