---
sidebar: sidebar 
permalink: networking/configure_snmpv3_users_in_a_cluster.html 
keywords: configure, configuration, configuring, setup, setting, set, up, snmp, snmpv3, users, user, cluster, security, secure, configure an snmpv3 user to run the snmp utilities from the snmp manager, security login create command, configure snmpv3 users in a cluster, snmpv3 security parameters, examples for different security levels, security level authpriv, fips mode, snmpwalk test, security level authnopriv 
summary: SNMP マネージャから SNMP ユーティリティを実行するための SNMPv3 ユーザを設定します 
---
= ONTAPクラスタでのSNMPv3ユーザの設定
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
SNMPv3は、SNMPv1やSNMPv2cに比べてセキュアなプロトコルです。SNMPv3を使用するには、SNMPマネージャからSNMPユーティリティを実行するようにSNMPv3ユーザを設定する必要があります。

.ステップ
使用 `security login create` SNMPv3 ユーザーを作成するコマンド。

次の情報を入力するように求められます。

* エンジン ID ：デフォルトで、推奨値はローカルエンジン ID です
* 認証プロトコル
* 認証パスワード
* プライバシー プロトコル
* プライバシー プロトコルのパスワード


.結果
SNMPv3ユーザは、ユーザ名とパスワードを使用してSNMPマネージャからログインし、SNMPユーティリティコマンドを実行できます。



== SNMPv3セキュリティパラメータ

SNMPv3には認証機能が含まれています。この機能を選択すると、コマンドを呼び出すときに、ユーザの名前、認証プロトコル、認証キー、および必要なセキュリティレベルの入力が必要になります。

次の表に、SNMPv3セキュリティパラメータを示します。

[cols="25,25,50"]
|===


| パラメータ | コマンドラインオプション | 説明 


 a| 
エンジン ID
 a| 
-e engineID
 a| 
SNMP エージェントのエンジン ID 。デフォルト値はlocal engineIDです（推奨）。



 a| 
securityName の略
 a| 
-u 名
 a| 
ユーザ名は 32 文字以内にする必要があります。



 a| 
authProtocol の略
 a| 
- a ｛ none | md5 | sha | SHA-256 ｝
 a| 
認証タイプには、 none 、 md5 、 SHA 、または SHA-256 を指定できます。



 a| 
authKey
 a| 
- パスフレーズ
 a| 
8 文字以上の長さのパスフレーズ



 a| 
セキュリティレベル
 a| 
-l ｛ authNoPriv | AuthPriv | noAuthNoPriv ｝
 a| 
セキュリティレベルには、「 Authentication 、 No Privacy 」、「 Authentication 、 Privacy 」、「 No Authentication 、 No Authentication 」のいずれかを指定できます。 プライバシーなし。



 a| 
privProtocol の略
 a| 
-x ｛ none | des | aes128 ｝
 a| 
プライバシープロトコルには、 none 、 des 、または aes128 を指定できます



 a| 
プライベートパスワード
 a| 
-X パスワード
 a| 
8 文字以上のパスワード。

|===


== さまざまなセキュリティレベルの例

次の例は、さまざまなセキュリティレベルで作成したSNMPv3ユーザが、SNMPクライアント側のコマンド（など）を使用してクラスタオブジェクトを照会する方法を示してい `snmpwalk`ます。

パフォーマンスを高めるには、テーブルから単一または少数のオブジェクトを取得するのではなく、テーブル内のすべてのオブジェクトを取得します。


NOTE: 認証プロトコルがSHAの場合は、5.3.1以降を使用する必要があります `snmpwalk`。



=== セキュリティレベル：authPriv

authPrivセキュリティレベルのSNMPv3ユーザを作成した場合の出力を次に示します。

....
security login create -user-or-group-name snmpv3user -application snmp -authentication-method usm
Enter the authoritative entity's EngineID [local EngineID]:
Which authentication protocol do you want to choose (none, md5, sha, sha2-256) [none]: md5

Enter the authentication protocol password (minimum 8 characters long):
Enter the authentication protocol password again:
Which privacy protocol do you want to choose (none, des, aes128) [none]: des
Enter privacy protocol password (minimum 8 characters long):
Enter privacy protocol password again:
....


==== FIPSモード

....
security login create -user-or-group-name snmpv3user -application snmp -authmethod usm
Enter the authoritative entity's EngineID [local EngineID]:
Which authentication protocol do you want to choose (sha, sha2-256) [sha]

Enter authentication protocol password (minimum 8 characters long):
Enter authentication protocol password again:
Which privacy protocol do you want to choose (aes128) [aes128]:
Enter privacy protocol password (minimum 8 characters long):
Enter privacy protocol password again:
....


==== snmpwalkテスト

このSNMPv3ユーザがsnmpwalkコマンドを実行した場合の出力を次に示します。

パフォーマンスを高めるには、テーブルから単一または少数のオブジェクトを取得するのではなく、テーブル内のすべてのオブジェクトを取得します。

....
$ snmpwalk -v 3 -u snmpv3user -a SHA -A password1! -x DES -X password1! -l authPriv 192.0.2.62 .1.3.6.1.4.1.789.1.5.8.1.2
Enterprises.789.1.5.8.1.2.1028 = "vol0"
Enterprises.789.1.5.8.1.2.1032 = "vol0"
Enterprises.789.1.5.8.1.2.1038 = "root_vs0"
Enterprises.789.1.5.8.1.2.1042 = "root_vstrap"
Enterprises.789.1.5.8.1.2.1064 = "vol1"
....


=== セキュリティレベル：authNoPriv

authNoPrivセキュリティレベルのSNMPv3ユーザを作成した場合の出力を次に示します。

....
security login create -user-or-group-name snmpv3user -application snmp -authmethod usm -role read-only
Enter the authoritative entity's EngineID [local EngineID]:
Which authentication protocol do you want to choose (none, md5, sha) [none]: md5
....


==== FIPSモード

FIPSでは、プライバシープロトコルに* none *を選択することはできません。そのため、authNoPriv SNMPv3ユーザをFIPSモードで設定することはできません。



==== snmpwalkテスト

このSNMPv3ユーザがsnmpwalkコマンドを実行した場合の出力を次に示します。

パフォーマンスを高めるには、テーブルから単一または少数のオブジェクトを取得するのではなく、テーブル内のすべてのオブジェクトを取得します。

....
$ snmpwalk -v 3 -u snmpv3user1 -a MD5 -A password1!  -l authNoPriv 192.0.2.62 .1.3.6.1.4.1.789.1.5.8.1.2
Enterprises.789.1.5.8.1.2.1028 = "vol0"
Enterprises.789.1.5.8.1.2.1032 = "vol0"
Enterprises.789.1.5.8.1.2.1038 = "root_vs0"
Enterprises.789.1.5.8.1.2.1042 = "root_vstrap"
Enterprises.789.1.5.8.1.2.1064 = "vol1"
....


=== セキュリティレベル：noAuthNoPriv

noAuthNoPrivセキュリティレベルのSNMPv3ユーザを作成した場合の出力を次に示します。

....
security login create -user-or-group-name snmpv3user -application snmp -authmethod usm -role read-only
Enter the authoritative entity's EngineID [local EngineID]:
Which authentication protocol do you want to choose (none, md5, sha) [none]: none
....


==== FIPSモード

FIPSでは、プライバシープロトコルに* none *を選択することはできません。



==== snmpwalkテスト

このSNMPv3ユーザがsnmpwalkコマンドを実行した場合の出力を次に示します。

パフォーマンスを高めるには、テーブルから単一または少数のオブジェクトを取得するのではなく、テーブル内のすべてのオブジェクトを取得します。

....
$ snmpwalk -v 3 -u snmpv3user2 -l noAuthNoPriv 192.0.2.62 .1.3.6.1.4.1.789.1.5.8.1.2
Enterprises.789.1.5.8.1.2.1028 = "vol0"
Enterprises.789.1.5.8.1.2.1032 = "vol0"
Enterprises.789.1.5.8.1.2.1038 = "root_vs0"
Enterprises.789.1.5.8.1.2.1042 = "root_vstrap"
Enterprises.789.1.5.8.1.2.1064 = "vol1"
....
の詳細については `security login create`、をlink:https://docs.netapp.com/us-en/ontap-cli/security-login-create.html["ONTAPコマンド リファレンス"^]参照してください。
