---
sidebar: sidebar 
permalink: networking/configure_failover_settings_on_a_lif.html 
keywords: configure, configuring, configuration, setup, set, up, failover, fail, over, group, policy, lif, configure failover settings on a lif, broadcast-domain-wide, system-defined, local-only, sfo-partner-only, disabled, network interface modify -vserver <vserver_name> -lif <lif_name> -failover-policy <failover_policy> -failover-group <failover_group>, examples of configuring failover settings and disabling failover 
summary: 特定のネットワークポートグループにフェイルオーバーするようにLIFを設定する 
---
= LIFでONTAPフェイルオーバー設定を構成する
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
フェイルオーバー ポリシーとフェイルオーバー グループをLIFに適用することにより、ネットワーク ポートの特定のグループにLIFがフェイルオーバーするように設定できます。また、LIFの別のポートへのフェイルオーバーを無効にすることもできます。

.タスク概要
* LIFを作成するとLIFフェイルオーバーがデフォルトで有効になり、使用可能なターゲット ポートのリストが、LIFのタイプとサービス ポリシーに基づくデフォルトのフェイルオーバー グループとフェイルオーバー ポリシーによって決まります。
+
9.5以降では、LIFを使用できるネットワーク サービスを定義するサービス ポリシーをLIFに指定できます。一部のネットワーク サービスでは、LIFのフェイルオーバーが制限されます。

+

NOTE: フェイルオーバーをそれまでよりも制限するようにLIFのサービス ポリシーを変更すると、LIFのフェイルオーバー ポリシーが自動的に更新されます。

* LIFのフェイルオーバーの動作は、network interface modifyコマンドの-failover-groupパラメータと-failover-policyパラメータの値を指定することによって変更できます。
* LIFの変更によって、LIFに有効なフェイルオーバー ターゲットがなくなる場合は警告メッセージが表示されます。
+
有効なフェイルオーバー ターゲットのないLIFがフェイルオーバーしようとすると、システムが停止する可能性があります。

* ONTAP 9.11.1以降、オールフラッシュSANアレイ（ASA）プラットフォームでは、新規に作成したStorage VM上に新規に作成するiSCSI LIFで、iSCSI LIFフェイルオーバーが自動的に有効になります。
+
さらに、link:../san-admin/asa-iscsi-lif-fo-task.html["既存の iSCSI LIF で iSCSI LIF フェイルオーバーを手動で有効にする"]ONTAP 9.11.1 以降にアップグレードする前に作成された LIF も対象となります。

* 次に、-failover-policyの設定によって、フェイルオーバー グループからどのターゲット ポートが選択されるかを示します。



NOTE: iSCSI LIF フェイルオーバーの場合、フェイルオーバーポリシー `local-only`、 `sfo-partner-only`、 `disabled`のみがサポートされます。

* `broadcast-domain-wide`フェイルオーバーグループ内のすべてのノードのすべてのポートに適用されます。
* `system-defined`LIF のホームノードと、クラスタ内の他の 1 つのノード（通常は SFO 以外のパートナー、存在する場合）のポートにのみ適用されます。
* `local-only`LIFのホームノード上のポートにのみ適用されます。
* `sfo-partner-only`LIFのホームノードとそのSFOパートナーのポートにのみ適用されます。
* `disabled` は、LIF がフェイルオーバー用に設定されていないことを示します。


.手順
既存のインターフェイスのフェイルオーバーを設定します。

....
network interface modify -vserver <vserver_name> -lif <lif_name> -failover-policy <failover_policy> -failover-group <failover_group>
....


== フェイルオーバーの設定例、および無効化の例

次のコマンドは、フェイルオーバー ポリシーをbroadcast-domain-wideに設定し、SVM vs3のdata1というLIFのフェイルオーバー ターゲットとして、フェイルオーバー グループfg3のポートを使用します。

....
network interface modify -vserver vs3 -lif data1 -failover-policy broadcast-domain-wide -failover-group fg3

network interface show -vserver vs3 -lif * -fields failover-group,failover-policy

vserver lif             failover-policy       failover-group
------- -------------- ---------------        --------------
vs3     data1          broadcast-domain-wide  fg3
....
次のコマンドは、SVM vs3のdata1というLIFのフェイルオーバーを無効にします。

....
network interface modify -vserver vs3 -lif data1 -failover-policy disabled
....
.関連情報
* link:https://docs.netapp.com/us-en/ontap-cli/search.html?q=network+interface["ネットワーク インターフェイス"^]

