---
sidebar: sidebar 
permalink: networking/configure_dynamic_dns_services.html 
keywords: dns, service, services, configuration, configure, configuring, set, up, setup, nfs, smb, cifs, active, directory, statistics, configure dns services for the svm before creating an nfs or smb server, ddns, vserver services name-service dns dynamic-update modify, vserver services name-service dns dynamic-update show 
summary: NFS または SMB サーバを作成する前に、 SVM 用の DNS サービスを設定してください 
---
= 動的 DNS サービスを設定する
:hardbreaks:
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Active Directory に統合された DNS サーバを DNS にある NFS または SMB サーバの DNS レコードに動的に登録する場合は、 SVM で動的 DNS （ DDNS ）を設定する必要があります。

SVM で DNS ネームサービスが設定されている必要があります。セキュア DDNS を使用する場合は、 Active Directory 統合 DNS ネームサーバを使用して、 SVM 用の NFS または SMB サーバまたは Active Directory アカウントを作成しておく必要があります。

一意の FQDN を指定する必要があります。


NOTE: DDNS 更新の RFC ルールに準拠していない SVM FQDN の設定エラーを回避するには、 RFC に準拠した FQDN 名を使用します。

.手順
. SVM で DDNS を設定します。
+
「 vserver services name-service dns dynamic-update modify -vserver _vserver_name __ is-enabled_[-use-secure ｛ true|false ｝ -vserver -fqdn_used_on_dns_update_`

+
「 vserver services name-service dns dynamic-update modify -vserver _vs1_-is-enabled_-use-secure_true_-vserver -fqdn _vs1.example.com_`

+
カスタマイズした FQDN の一部としてアスタリスクを使用することはできません。たとえば '*.netapp.com は無効です

. DDNS の設定が正しいことを確認します。
+
vserver services name-service dns dynamic-update show

+
....
Vserver  Is-Enabled Use-Secure Vserver FQDN      TTL
-------- ---------- ---------- ----------------- -------
vs1      true       true       vs1.example.com   24h
....

