---
sidebar: sidebar 
permalink: networking/configure_vlans_over_physical_ports.html 
keywords: configure, configuration, configuring, setup, setting, set, up, vlan, virtual, local, area, network, physical, port, logical, segmentation, configure vlans over physical ports, vlans provide logical segmentation of networks, create a vlan, network port vlan create, delete a vlan, network port vlan delete 
summary: VLAN は、ネットワークを論理的にセグメント化します 
---
= 物理ポートを介して VLAN を設定します
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
VLAN は、分離されたブロードキャストドメインを作成することで、ネットワークを論理的にセグメント化します。このブロードキャストドメインは、従来の物理的な境界ではなく、スイッチポートに基づいて定義されます。

VLAN は、複数の物理ネットワークセグメントにまたがることができます。VLAN に属するエンドステーションは、機能またはアプリケーションに基づいて関連付けられます。

たとえば、エンジニアリングや財務などの部門単位、またはリリース 1 やリリース 2 などのプロジェクト単位で、 VLAN のエンドステーションをまとめることができます。VLAN ではエンドステーションが物理的に近接して配置されることは重要ではないので、エンドステーションを地理的に分散させても、スイッチドネットワークにブロードキャストドメインを含めることができます。

VLAN の管理では、 VLAN を作成、削除、またはその情報を表示できます。


NOTE: スイッチのネイティブ VLAN と同じ識別子の VLAN をネットワークインターフェイス上に作成しないでください。たとえば、ネットワークインターフェイス e0b がネイティブ VLAN 10 に割り当てられている場合、そのインターフェイス上に VLAN e0b-10 を作成しないでください。



== VLAN を作成します

同じネットワークドメイン内の分離されたブロードキャストドメインを管理するためのVLANを作成するには、System Managerまたは「network port vlan create」コマンドを使用します。

次の要件を満たしていることを確認します。

* ネットワーク上に配置されたスイッチが、 IEEE 802.1Q 規格に準拠しているか、またはベンダー固有の VLAN を実装している。
* 複数の VLAN をサポートするには、エンドステーションが 1 つ以上の VLAN に属するように静的に設定されている必要があります。
* VLAN は、クラスタ LIF をホストしているポートに接続されていない。
* VLAN は、「 Cluster 」 IPspace に割り当てられているポートに接続されていない。
* VLAN は、メンバーポートのないインターフェイスグループポートには作成されません。


VLAN を作成すると、クラスタ内の指定したノードのネットワークポートにその VLAN が接続されます。

VLAN を初めてポートに設定したときに、ポートが停止してネットワーク接続が一時的に切断されることがあります。その後同じポートに VLAN を追加しても、ポートの状態には影響しません。


NOTE: スイッチのネイティブ VLAN と同じ識別子の VLAN をネットワークインターフェイス上に作成しないでください。たとえば、ネットワークインターフェイス e0b がネイティブ VLAN 10 に割り当てられている場合、そのインターフェイス上に VLAN e0b-10 を作成しないでください。

実行する手順 は、使用するインターフェイス（System ManagerまたはCLI）によって異なります。

[role="tabbed-block"]
====
.System Manager の略
--
* System Managerを使用してVLAN *を作成します

ONTAP 9.12.0以降では、ブロードキャストドメインを自動的に選択することも、リストから手動で選択することもできます。これまでは、レイヤ2接続に基づいて常にブロードキャストドメインが自動的に選択されていました。ブロードキャストドメインを手動で選択した場合は、ブロードキャストドメインを手動で選択すると接続が失われる可能性があることを示す警告が表示されます。

.手順
. Network > Ethernet port >+VLAN *を選択します。
. ドロップダウンリストからノードを選択します。
. 次のいずれかを選択します。
+
.. ONTAP to * automatically select broadcast domain（推奨）*。
.. リストからブロードキャストドメインを手動で選択します。


. VLANを形成するポートを選択します。
. VLAN IDを指定します。
. 変更を保存します。


--
.CLI の使用
--
* CLIを使用してVLAN *を作成します

特定の状況において、ハードウェア問題 またはソフトウェアの設定ミスを修正せずにデグレード状態のポートにVLANポートを作成する場合は、「network port modify」コマンドの「-ignore-health-status」パラメータを「true」に設定できます。

.手順
. VLAN を作成するには 'network port vlan create コマンドを使用します
. VLAN を作成するときは 'vlan-name' または 'port' オプションと 'vlan-id' オプションのいずれかを指定する必要がありますVLAN 名は、ポート（またはインターフェイスグループ）の名前と、ネットワークスイッチの VLAN の識別子をハイフンでつないだ形式です。たとえば、「 e0c-24 」や「 e1c-80 」は有効な VLAN 名です。


次に、ノード cluster-1-01 のネットワークポート e1c に接続された VLAN 「 e1c-80 」を作成する例を示します。

....
network port vlan create -node cluster-1-01 -vlan-name e1c-80
....
ONTAP 9.8 以降では、作成後約 1 分後に、 VLAN が適切なブロードキャストドメインに自動的に配置されます。ONTAP でこれを行わず、手動で VLAN をブロードキャストドメインに配置する場合は、「 vlan create 」コマンドの一部として「 -skip-broadcast-domain-placement 」パラメータを指定します。

このコマンドの詳細については、を参照してください http://docs.netapp.com/ontap-9/topic/com.netapp.doc.dot-cm-cmpr/GUID-5CB10C70-AC11-41C0-8C16-B4D0DF916E9B.html["ONTAP 9 のコマンド"^]。

--
====


== VLANを編集します

ブロードキャストドメインを変更したり、VLANを無効にしたりできます。

ONTAP 9.12.0以降では、ブロードキャストドメインを自動的に選択することも、リストから手動で選択することもできます。以前は、レイヤ2接続に基づいて、常に自動的にブロードキャストドメインが選択されていました。ブロードキャストドメインを手動で選択した場合は、ブロードキャストドメインを手動で選択すると接続が失われる可能性があることを示す警告が表示されます。

.手順
. Network > Ethernet port > VLAN *を選択します。
. 編集アイコンを選択します。
. 次のいずれかを実行します。
+
** リストから別のブロードキャストドメインを選択して、ブロードキャストドメインを変更します。
** [有効*]チェックボックスをオフにします。


. 変更を保存します。




== VLAN を削除します

NIC をスロットから取り外す前に、 VLAN の削除が必要になることがあります。VLAN を削除すると、その VLAN を使用しているすべてのフェイルオーバールールとフェイルオーバーグループから自動的に削除されます。

VLAN に関連付けられている LIF がないことを確認します。

ポートから最後の VLAN 原因を削除すると、そのポートからネットワークが一時的に切断される可能性があります。

実行する手順 は、使用するインターフェイス（System ManagerまたはCLI）によって異なります。

[role="tabbed-block"]
====
.System Manager の略
--
* System Managerを使用してVLANを削除します。*

.手順
. Network > Ethernet port > VLAN *を選択します。
. 削除するVLANを選択します。
. [ 削除（ Delete ） ] をクリックします。


--
.CLI の使用
--
* CLIを使用してVLAN *を削除します

VLAN を削除するには 'network port vlan delete コマンドを使用します

次に、ノード cluster-1-01 のネットワークポート e1c から VLAN 「 e1c-80 」を削除する例を示します。

....
network port vlan delete -node cluster-1-01 -vlan-name e1c-80
....
--
====