---
sidebar: sidebar 
permalink: networking/configure_virtual_ip_@vip@_lifs.html 
keywords: 'configure, configuration, configuring, setup, setting, set, up, virtual, vip, ip, lif, data, configure virtual IP (vip) lifs, set up border gateway protocol (bgp), use-peer-as-next-hop, asn-prepend-type, asn-prepend-count, community, network bgp peer-group, med, multi-exit discriminator, create a virtual ip (vip) data lif, commands for managing the BGP, network bgp, manage bgp configuration, manage bgp default values, manage bgp peer groups' 
summary: サブネット間で LIF をフェイルオーバーする 
---
= 仮想IP（VIP）LIFの設定
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
一部の次世代データセンターでは、サブネット間でLIFをフェイルオーバーする必要があるネットワークレイヤ3のメカニズムが使用されています。VIP.5以降では、VIPデータLIFおよび関連するルーティングプロトコルであるBorder Gateway Protocol（ONTAP 9；ボーダーゲートウェイプロトコル）がサポートされ、これらの次世代ネットワークにONTAPを参加させることができます。

.タスクの内容
VIPデータLIFは、どのサブネットにも属さず、同じIPspace内のBGP LIFをホストするすべてのポートから到達可能なLIFです。VIPデータLIFを使用すると、ホストは個 々 のネットワークインターフェイスに依存しなくなります。複数の物理アダプタがデータトラフィックを伝送するため、すべての負荷が単一のアダプタおよび関連するサブネットに集中することはありません。VIPデータLIFの存在は、ルーティングプロトコルであるBorder Gateway Protocol（BGP）を使用してピアルータにアドバタイズされます。

VIPデータLIFには次の利点があります。

* ブロードキャストドメインやサブネットをまたいで LIF を移動できます。各 VIP データ LIF の現在の場所が BGP を通じてルータに通知されるため、 VIP データ LIF をネットワークのどのサブネットにもフェイルオーバーできます。
* アグリゲートスループット： VIP データ LIF は、同時に複数のサブネットまたはポートに対してデータを送受信できるため、個々のポートの帯域幅を超えるアグリゲートスループットをサポートできます。




== Border Gateway Protocol（BGP;ボーダーゲートウェイプロトコル）のセットアップ

VIP LIFを作成する前に、BGPを設定する必要があります。BGPは、VIP LIFの存在をピアルータに通知するためのルーティングプロトコルです。

VIPBGPは、ONTAP 9ピアグループ化を使用してデフォルトルートの自動化を提供し、設定を簡素化します。

ONTAPには、BGPピアが同じサブネット上にある場合に、BGPピアをネクストホップルータとして使用してデフォルトルートを学習する簡単な方法があります。この機能を使用するには、属性をに `true`設定し `-use-peer-as-next-hop`ます。デフォルトでは、この属性はです `false`。

静的ルートが設定されている場合でも、自動化されたデフォルトルートよりも静的ルートが優先されます。

.開始する前に
設定されたAutonomous System Number（ASN；自律システム番号）のBGP接続をBGP LIFから受け入れるようにピアルータを設定する必要があります。


NOTE: ONTAPはルータからの着信ルートアナウンスを処理しません。したがって、クラスタにルートアップデートを送信しないようにピアルータを設定する必要があります。

.タスクの内容
BGPをセットアップするには、必要に応じてBGP設定を作成し、BGP LIFを作成し、BGPピアグループを作成します。ONTAPは、最初のBGPピアグループが特定のノードに作成されると、デフォルト値を使用してデフォルトのBGP設定を自動的に作成します。BGP LIFは、ピアルータとのBGP TCPセッションの確立に使用されます。ピアルータの場合、BGP LIFはVIP LIFに到達するためのネクストホップです。BGP LIFのフェイルオーバーは無効になっています。BGPピアグループは、ピアグループのIPspace内のすべてのSVMのVIPルートをアドバタイズします。

ONTAP 9 .8以降では、次のフィールドがコマンドに追加されてい `network bgp peer-group`ます。

* -asn-prepend-type
* -asn-prepend-count
* -コミュニティ


これらのBGP属性を使用すると、BGPピアグループのASパス属性およびコミュニティ属性を設定できます。

ONTAP 9 .9.1以降では、次のフィールドが追加されました。

* -ASN または -peer-ASN （ 4 バイト値）：属性自体は新規ではありませんが、現在は 4 バイトの整数を使用しています。
* -医療
* -use-peer-as-next-hop


パス優先順位付けのためのMulti-Exit Discriminator（MED）サポートを使用して、高度なルート選択を行うことができます。MEDは、トラフィックに最適なルートを選択するようにルータに指示するBGPアップデートメッセージのオプション属性です。MEDは符号なし32ビット整数（0～4294967295）です。小さい値が推奨されます。


NOTE: ONTAPは上記のBGPアトリビュートをサポートしていますが、ルータはこれらのアトリビュートを尊重する必要はありません。NetAppでは、ルータでサポートされている属性を確認し、それに応じてBGPピアグループを設定することを強く推奨します。詳細については、ルータが提供するBGPのマニュアルを参照してください。

.手順
. advanced権限レベルにログインします。
+
`set -privilege advanced`

. オプション：次のいずれかの操作を実行して、クラスタの BGP 設定を作成するか、デフォルトの BGP 設定を変更します。
+
.. BGP設定を作成します。
+
....
network bgp config create -node {node_name | local} -asn asn_integer -holdtime
hold_time -routerid local_router_IP_address
....
+
2バイトASNのサンプル：

+
....
network bgp config create -node node1 -asn 65502 -holdtime 180 -routerid 1.1.1.1
....
+
4バイトASNのサンプル：

+
....
network bgp config create -node node1 -asn 85502 -holdtime 180 -routerid 1.1.1.1
....
.. デフォルトのBGP設定を変更します。
+
....
network bgp defaults modify -asn asn_integer -holdtime hold_time
network bgp defaults modify -asn 65502
....
+
*** `asn_integer`ASNを指定します。.8以降では、ONTAP 9 for BGPは2バイトの非負整数をサポートしています。これは16ビットの数値です（使用可能な値は1～65534です）。.9.1以降では、ONTAP 9 for BGPは4バイトの非負整数（1-4294967295）をサポートしています。デフォルトのASNは65501です。ASN 23456は、4バイトのASN機能を通知しないピアとのONTAPセッション確立用に予約されています。
*** `hold_time`保持時間を秒単位で指定します。デフォルト値は180sです。




. システムSVM用のBGP LIFを作成します。
+
....
network interface create -vserver system_svm -lif lif_name -service-policy default-route-announce -home-node home_node -home-port home_port -address ip_address -netmask netmask
....
+
BGP LIFのサービスポリシー、または「management-bgp」サービスを含む任意のカスタムサービスポリシーを使用できます `default-route-announce`。

+
....
network interface create -vserver cluster1 -lif bgp1 -service-policy default-route-announce -home-node cluster1-01 -home-port e0c -address 10.10.10.100 -netmask 255.255.255.0
....
. リモートピアルータとのBGPセッションを確立するために使用するBGPピアグループを作成し、ピアルータにアドバタイズされるVIPルート情報を設定します。
+
例 1 ：自動デフォルトルートのないピアグループを作成する

+
この場合、管理者はBGPピアへのスタティックルートを作成する必要があります。

+
....
network bgp peer-group create -peer-group group_name -ipspace ipspace_name -bgp-lif bgp_lif -peer-address peer-router_ip_address -peer-asn 65502 -route-preference integer
-asn-prepend-type <ASN_prepend_type> -asn-prepend-count integer -med integer -community BGP community list <0-65535>:<0-65535>
....
+
....
network bgp peer-group create -peer-group group1 -ipspace Default -bgp-lif bgp1 -peer-address 10.10.10.1 -peer-asn 65502 -route-preference 100 -asn-prepend-type local-asn -asn-prepend-count 2 -med 100 -community 9000:900,8000:800
....
+
例 2 ：自動デフォルトルートを使用してピアグループを作成する

+
....
network bgp peer-group create -peer-group group_name -ipspace ipspace_name -bgp-lif bgp_lif -peer-address peer-router_ip_address -peer-asn 65502 -use-peer-as-next-hop true -route-preference integer -asn-prepend-type <ASN_prepend_type> -asn-prepend-count integer -med integer -community BGP community list <0-65535>:<0-65535>
....
+
....
network bgp peer-group create -peer-group group1 -ipspace Default -bgp-lif bgp1 -peer-address 10.10.10.1 -peer-asn 65502 -use-peer-as-next-hop true -route-preference 100 -asn-prepend-type local-asn -asn-prepend-count 2 -med 100 -community 9000:900,8000:800
....




== 仮想IP（VIP）データLIFを作成する

VIPデータLIFの存在は、ルーティングプロトコルであるBorder Gateway Protocol（BGP）を使用してピアルータにアドバタイズされます。

.開始する前に
* BGPピアグループをセットアップし、LIFを作成するSVMのBGPセッションをアクティブにしておく必要があります。
* SVMの発信VIPトラフィック用に、BGPルータまたはBGP LIFのサブネット内のその他のルータへの静的ルートを作成する必要があります。
* 発信VIPトラフィックが使用可能なすべてのルートを利用できるように、マルチパスルーティングをオンにする必要があります。
+
マルチパスルーティングがイネーブルになっていない場合、すべての発信VIPトラフィックは1つのインターフェイスから送信されます。



.手順
. VIPデータLIFを作成します。
+
....
network interface create -vserver svm_name -lif lif_name -role data -data-protocol
{nfs|cifs|iscsi|fcache|none|fc-nvme} -home-node home_node -address ip_address -is-vip true
....
+
コマンドでホームポートを指定しない場合は、VIPポートが自動的に選択され `network interface create`ます。

+
デフォルトでは、VIPデータLIFは、システムによってIPspaceごとに作成される「vip」という名前のブロードキャストドメインに属します。VIPブロードキャストドメインは変更できません。

+
VIPデータLIFは、IPspaceのBGP LIFをホストしているすべてのポートで同時に到達できます。ローカルノードにVIPのSVMに対するアクティブなBGPセッションがない場合、VIPデータLIFは、そのSVMに対してBGPセッションが確立されているノードの次のVIPポートにフェイルオーバーします。

. VIPデータLIFのSVMに対してBGPセッションのステータスがupになっていることを確認します。
+
....
network bgp vserver-status show

Node        Vserver  bgp status
	    ----------  -------- ---------
	    node1       vs1      up
....
+
あるノードのSVMのBGPステータスがの場合、 `down`VIPデータLIFは、そのSVMのBGPステータスがupになっている別のノードにフェイルオーバーします。すべてのノードでBGPステータスが設定されている場合は `down`、VIPデータLIFをどこでもホストできず、LIFステータスがdownになります。





== BGPの管理用コマンド

5以降では、コマンドを使用してONTAPでONTAP 9 `network bgp`セッションを管理します。



=== BGP設定を管理します。

|===


| 状況 | 使用するコマンド 


| BGP設定を作成する | network bgp config create 


| BGP設定を変更する | network bgp config modify 


| BGP設定を削除する | network bgp config delete 


| BGP設定を表示する | network bgp config show 


| VIP LIFのSVMに対するBGPステータスを表示する | network bgp vserver-status show 
|===


=== BGPのデフォルト値の管理

|===


| 状況 | 使用するコマンド 


| BGPのデフォルト値を変更する | network bgp defaults modify 


| BGPのデフォルト値を表示する | network bgp defaults show 
|===


=== BGPピアグループを管理します。

|===


| 状況 | 使用するコマンド 


| BGPピアグループを作成する | network bgp peer-group create 


| BGPピアグループを変更する | network bgp peer-group modify 


| BGPピア グループを削除する | network bgp peer-group delete 


| BGPピア グループの情報を表示する | network bgp peer-group show 


| BGPピア グループの名前を変更する | network bgp peer-group rename 
|===
.関連情報
https://docs.netapp.com/us-en/ontap-cli["ONTAPコマンド リファレンス"^]
