---
sidebar: sidebar 
permalink: networking/configure_network_security_using_federal_information_processing_standards_@fips@.html 
keywords: fips 140-2, compliant, ssl, connections, tlsv1.2, tlsv1.1, tlsv1, enable fips, disable fips, compliance status, SSL 
summary: すべての SSL 接続に対応した Federal Information Processing Standard （ FIPS ；連邦情報処理標準） 140-2 が準拠しています 
---
= 連邦情報処理標準（ FIPS ）を使用したネットワークセキュリティの設定
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
ONTAP は、すべての SSL 接続に対する連邦情報処理標準（ FIPS ） 140-2 に準拠しています。ONTAP では、 SSL FIPS モードを有効または無効にしたり、 SSL プロトコルをグローバルに設定したり、 RC4 などの弱い暗号を無効にしたりできます。

デフォルトでは、 ONTAP の SSL は、次のプロトコルを使用して FIPS 準拠が無効、 SSL プロトコルが有効な状態で設定されます。

* TLSv1（ONTAP 9.11.1以降）
* TLSv1.2
* TLSv1.1
* TLSv1


SSL FIPS モードがイネーブルの場合、 ONTAP から ONTAP 外部のクライアントまたはサーバコンポーネントへの SSL 通信には、 FIPS 準拠の SSL 用暗号が使用されます。

管理者アカウントが SSH 公開鍵を使用して SVM にアクセスできるようにする場合は、 SSL FIPS モードを有効にする前に、ホストキーアルゴリズムがサポートされていることを確認する必要があります。

*注：ONTAP 9.11.1以降では、ホストキーアルゴリズムのサポートが変更されています。

[cols="30,30,30"]
|===


| ONTAP リリース | サポートされているキータイプ | サポートされていないキータイプです 


 a| 
9.11.1以降
 a| 
ECDSA - sha2 - nistp256
 a| 
rsa-sha2-512+ rsa-sha2-256+ ssh-ed25519 + ssh-dss+ssh-rsa



 a| 
9.10.1以前
 a| 
ECDSA - sha2 -nistp256 + ssh-ed25519
 a| 
SSH-DSS + ssh-rsa

|===
FIPS を有効にする前に、サポートされるキーアルゴリズムを使用していない既存の SSH 公開鍵アカウントをサポート対象のキータイプで再設定する必要があります。再設定しないと、管理者認証は失敗します。

詳細については、を参照してください link:../authentication/enable-ssh-public-key-accounts-task.html["SSH 公開鍵アカウントを有効にします"]。

SSL FIPS モード設定の詳細については 'security config modify のマニュアルページを参照してください



== ONTAP 9.11.1RC1に関する考慮事項

ONTAP バージョン9.11.1RC1の変更により、FIPS 140-2準拠管理モードではFIPS 140-2準拠のソフトウェアモジュールが使用されなくなりました。

ONTAP 9.11.1RC1では、HTTPSの管理プレーンとコントロールプレーンの接続に使用するOpenSSLのバージョンがアップグレードされました。このバージョンのOpenSSL（OpenSSL 3.x FIPSプロバイダ）では、FIPS 140-2暗号モジュール検証プログラム（CMVP）検証プロセスがまだ完了していません。

FIPS準拠モードが有効になっている場合、HTTPS接続に使用される暗号化アルゴリズムは、Cryptographic Algorithm Validation Program（CAVP）証明書A1938で発行されたOpenSSL 3.x FIPSプロバイダアルゴリズムと同じです。*この変更は、FIPS準拠モードに設定されているONTAP システムにのみ適用されます。*

この問題 は、ONTAP 9.11.1RC1でアップグレードされたOpenSSLモジュールがNISTによるFIPS 140-2検証を完了した時点で修正されます。ONTAP クラスタ管理コントロールプレーンでFIPS 140-2 CMVP認定モジュールを使用する必要がある環境では、9.11.1RC1にアップグレードしないことを推奨します。

NSE、NVE ONTAP 、NAEなどの保管テクノロジでは、OpenSSLに搭載されている暗号化モジュールとは異なる暗号化モジュールを使用するため、この機能はネットアップの暗号化には影響しません。

詳細については、を参照してください link:https://kb.netapp.com/Advice_and_Troubleshooting/Data_Storage_Software/ONTAP_OS/Upgrading_to_ONTAP_9.11.1RC1_results_in_FIPS_140-2_compliance_management_configuration_that_is_not_validated["ONTAP 9.11.1RC1にアップグレードすると、FIPS 140-2準拠の管理設定が検証されなくなります"^]。



== FIPS を有効にします

システムのインストールまたはアップグレードの直後に、すべてのセキュアユーザがセキュリティ設定を調整することを推奨します。SSL FIPS モードがイネーブルの場合、 ONTAP から ONTAP 外部のクライアントまたはサーバコンポーネントへの SSL 通信には、 FIPS 準拠の SSL 用暗号が使用されます。


NOTE: FIPSが有効な場合、RSAキーの長さが4096の証明書をインストールまたは作成することはできません。

.手順
. advanced 権限レベルに切り替えます。
+
「 advanced 」の権限が必要です

. FIPS を有効にします。
+
「 securityconfig modify -interface ssl-is-fips-enabled true 」という記述があります

. 続行するかどうかを確認するメッセージが表示されたら 'y' を入力します
. ONTAP 9.8 以前を実行している場合は、クラスタ内の各ノードを 1 つずつ手動でリブートします。ONTAP 9.9..1 以降では、再起動は必要ありません。


ONTAP 9.9.1 以降を実行している場合は、警告メッセージは表示されません。

....
security config modify -interface SSL -is-fips-enabled true

Warning: This command will enable FIPS compliance and can potentially cause some non-compliant components to fail. MetroCluster and Vserver DR require FIPS to be enabled on both sites in order to be compatible.
Do you want to continue? {y|n}: y

Warning: When this command completes, reboot all nodes in the cluster. This is necessary to prevent components from failing due to an inconsistent security configuration state in the cluster. To avoid a service outage, reboot one node at a time and wait for it to completely initialize before rebooting the next node. Run "security config status show" command to monitor the reboot status.
Do you want to continue? {y|n}: y
....


== FIPS を無効にする

古いシステム構成を実行し続けている状況で、 ONTAP の設定で下位互換性を確保する場合は、 FIPS が無効な場合にのみ SSLv3 を有効にすることができます。

.手順
. advanced 権限レベルに切り替えます。
+
「 advanced 」の権限が必要です

. 次のように入力して FIPS を無効に
+
security config modify -interface SSL -is-fips-enabled false

. 続行するかどうかを確認するメッセージが表示されたら 'y' を入力します
. ONTAP 9.8 以前を実行している場合は、クラスタ内の各ノードを手動でリブートします。ONTAP 9.9..1 以降では、再起動は必要ありません。


ONTAP 9.9.1 以降を実行している場合は、警告メッセージは表示されません。

....
security config modify -interface SSL -supported-protocols SSLv3

Warning: Enabling the SSLv3 protocol may reduce the security of the interface, and is not recommended.
Do you want to continue? {y|n}: y

Warning: When this command completes, reboot all nodes in the cluster. This is necessary to prevent components from failing due to an inconsistent security configuration state in the cluster. To avoid a service outage, reboot one node at a time and wait for it to completely initialize before rebooting the next node. Run "security config status show" command to monitor the reboot status.
Do you want to continue? {y|n}: y
....


== FIPS 準拠ステータスを表示します

クラスタ全体で現在のセキュリティ設定が実行されているかどうかを確認することができます。

.手順
. クラスタ内の各ノードを 1 つずつリブートします。
+
すべてのクラスタノードを同時にリブートしないでください。クラスタ内のすべてのアプリケーションで新しいセキュリティ設定が実行されていること、および FIPS のオン / オフモード、プロトコル、暗号に対する変更がすべて反映されていることを確認するには、リブートが必要です。

. 現在の準拠ステータスを表示します。
+
「 securityconfig show 」を参照してください



....
security config show

          Cluster                                              Cluster Security
Interface FIPS Mode  Supported Protocols     Supported Ciphers Config Ready
--------- ---------- ----------------------- ----------------- ----------------
SSL       false      TLSv1_2, TLSv1_1, TLSv1 ALL:!LOW:!aNULL:  yes
                                             !EXP:!eNULL
....