---
sidebar: sidebar 
permalink: networking/configure_traphosts_to_receive_snmp_notifications.html 
keywords: configure, configuration, configuring, setup, setting, set, up, traphosts, trap, host, receive, snmp, notifications, configure traphosts to receive snmp notifications. system snmp traphost add 
summary: トラップ通知を受信するようにSNMPマネージャを設定する 
---
= ONTAPネットワーク上でSNMP用のトラップホストを設定する
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
クラスタでSNMPトラップが生成されたときに通知（SNMPトラップPDU）が届くように、トラップホスト（SNMPマネージャ）を設定できます。SNMPトラップホストのホスト名かIPアドレス（IPv4またはIPv6）を指定できます。

.開始する前に
* クラスタでSNMPとSNMPトラップが有効になっている必要があります。



NOTE: SNMPとSNMPトラップはデフォルトで有効になっています。

* クラスタでトラップホスト名を解決するようにDNSが設定されている必要があります。
* IPv6アドレスを使用してSNMPトラップホストを設定するには、クラスタでIPv6を有効にする必要があります。
* トラップホストを作成するときは、定義済みのユーザーベースのセキュリティ モデル（USM）の認証プロトコルとプライバシー資格情報を指定する必要があります。


.手順
SNMPトラップホストを追加します。

....
system snmp traphost add
....

NOTE: トラップを送信できるのは、1つ以上のSNMP管理ステーションがトラップホストとして指定されている場合だけです。

次のコマンドは、yyy.example.comという名前の新しいSNMPv3トラップホストを、既知のUSMユーザで追加します。

....
system snmp traphost add -peer-address yyy.example.com -usm-username MyUsmUser
....
次のコマンドは、ホストのIPv6アドレスを使用してトラップホストを追加します。

....
system snmp traphost add -peer-address 2001:0db8:1:1:209:6bff:feae:6d67
....