---
sidebar: sidebar 
permalink: networking/configure_dns_for_host-name_resolution.html 
keywords: configure, configuring, configuration, setup, set, setting, dns, local, remote, host, name, host-name, resolution, configure dns for host-name resolution, nsswitch.conf, configure an svm and data lifs for host-name resolution using an external dns server, vserver services name-service dns, vserver services name-service dns create, network interface modify -lif lifname -dns-zone, network interface create -lif lifname -dns-zone, vserver services name-service dns check, configure the name service switch table for host-name resolution 
summary: ホスト情報を取得するには、 DNS を使用してローカルソースまたはリモートソースにアクセスします 
---
= ホスト名解決に使用する DNS を設定します
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
ホスト情報を取得するには、 DNS を使用してローカルソースまたはリモートソースにアクセスします。これらのソースのいずれかまたは両方にアクセスするために DNS を設定する必要があります。

ONTAP がクライアントに適切なアクセスを許可するには、ホスト情報を検索できなければなりません。ネームサービスを設定して、 ONTAP がホスト情報を取得するためにローカルまたは外部の DNS サービスにアクセスできるようにします。

ONTAP では、に相当するテーブルにネームサービス設定情報が格納されます `/etc/nsswitch.conf` UNIXシステム上のファイル。



== 外部 DNS サーバを使用して、ホスト名解決のために SVM とデータ LIF を設定する

を使用できます `vserver services name-service dns` コマンドを使用してSVMでDNSを有効にし、ホスト名解決にDNSを使用するように設定します。ホスト名は外部 DNS サーバを使用して解決されます。

.作業を開始する前に
ホスト名を検索するために、サイト規模の DNS サーバが使用可能である必要があります。

単一点障害を回避するには、複数の DNS サーバを設定する必要があります。。 `vserver services name-service dns create` 入力したDNSサーバ名が1つだけの場合は警告が表示されます。

.このタスクについて
を参照してください xref:configure_dynamic_dns_services.html[動的 DNS サービスを設定する] SVMでの動的DNSの設定に関する詳細については、を参照してください。

.手順
. SVM で DNS を有効にします。
+
....
vserver services name-service dns create -vserver <vserver_name> -domains <domain_name> -name-servers <ip_addresses> -state enabled
....
+
次のコマンドは、 SVM vs1 で外部 DNS サーバを有効にします。

+
....
vserver services name-service dns create -vserver vs1.example.com -domains example.com -name-servers 192.0.2.201,192.0.2.202 -state enabled
....
+

NOTE: 。 `vserver services name-service dns create` コマンドは設定の自動検証を実行し、ONTAP がネームサーバに接続できない場合はエラーメッセージを報告します。

. を使用してネームサーバのステータスを検証します `vserver services name-service dns check` コマンドを実行します
+
....
vserver services name-service dns check -vserver vs1.example.com
                                    Name Server
Vserver             Name Server     Status       Status Details
-------------       --------------- ------------ --------------------------
vs1.example.com     10.0.0.50       up           Response time (msec): 2
vs1.example.com     10.0.0.51       up           Response time (msec): 2
....


DNSに関連するサービスポリシーの詳細については、を参照してください。 link:lifs_and_service_policies96.html["ONTAP 9.6 以降の LIF とサービスポリシー"]。



== ホスト名解決用のネームサービススイッチテーブルを設定します

ONTAP がホスト情報を取得するためにローカルまたは外部のネームサービスにアクセスできるようにするには、ネームサービススイッチテーブルを正しく設定する必要があります。

.作業を開始する前に
環境内のホストのマッピングでどのネームサービスを使用するかを決めておく必要があります。

.手順
. ネームサービススイッチテーブルに必要なエントリを追加します。
+
....
vserver services name-service ns-switch modify -vserver <vserver_name> -database <database_name> -source <source_names>
....
. ネームサービススイッチテーブルに想定されるエントリが適切な順序で格納されていることを確認します。
+
....
vserver services name-service ns-switch show -vserver <vserver_name>
....


.例
次の例は、SVM vs1のネームサービススイッチテーブル内のエントリを、ホスト名を解決するためにまずローカルのhostsファイルを使用し、次に外部DNSサーバを使用するように変更します。

....
vserver services name-service ns-switch modify -vserver vs1 -database hosts -sources files,dns
....