---
sidebar: sidebar 
permalink: networking/configure_dynamic_dns_services.html 
keywords: dns, service, services, configuration, configure, configuring, set, up, setup, nfs, smb, cifs, active, directory, statistics, configure dns services for the svm before creating an nfs or smb server, ddns, vserver services name-service dns dynamic-update modify, vserver services name-service dns dynamic-update show 
summary: NFS または SMB サーバを作成する前に、 SVM 用の DNS サービスを設定してください 
---
= 動的DNSサービスの設定
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Active Directory統合DNSサーバをDNSにあるNFSまたはSMBサーバのDNSレコードに動的に登録する場合は、SVMで動的DNS（DDNS）を設定する必要があります。

.開始する前に
SVMでDNSネームサービスが設定されている必要があります。セキュアなDDNSを使用する場合は、Active Directory統合DNSネームサーバを使用し、SVM用にNFSサーバまたはSMBサーバまたはActive Directoryアカウントを作成しておく必要があります。

.タスクの内容
一意の FQDN を指定する必要があります。


NOTE: DDNS更新に関するRFCルールに準拠していないSVM FQDNの設定エラーを回避するには、RFC準拠のFQDN名を使用してください。

.手順
. SVMでDDNSを設定します。
+
`vserver services name-service dns dynamic-update modify -vserver _vserver_name_ -is- enabled _true_ [-use-secure {true|false} -vserver-fqdn _FQDN_used_for_DNS_updates_`

+
`vserver services name-service dns dynamic-update modify -vserver _vs1_ -is-enabled _true_ - use-secure _true_ -vserver-fqdn _vs1.example.com_`

+
カスタマイズしたFQDNの一部としてアスタリスクを使用することはできません。たとえば、 `*.netapp.com`は無効です。

. DDNSの設定が正しいことを確認します。
+
`vserver services name-service dns dynamic-update show`

+
....
Vserver  Is-Enabled Use-Secure Vserver FQDN      TTL
-------- ---------- ---------- ----------------- -------
vs1      true       true       vs1.example.com   24h
....

