---
sidebar: sidebar 
permalink: networking/create_lifs.html 
keywords: create, creation, creating, add, adding, lifs, logical, interface, create lifs 
summary: SVM データをクライアントに提供するための LIF を作成します 
---
= LIFs を作成します
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
SVM は、 1 つ以上のネットワーク論理インターフェイス（ LIF ）を通じてクライアントにデータを提供します。データへのアクセスに使用するポートに LIF を作成する必要があります。

.ベストプラクティス
ONTAPに接続されたスイッチポートは、LIFの移行時の遅延を軽減するために、スパニングツリーエッジポートとして設定する必要があります。

.作業を開始する前に
このタスクを実行するには、クラスタ管理者である必要があります。

.このタスクについて
ONTAP 9.7 以降では、少なくとも 1 つの LIF が同じサブネットにすでに存在するかぎり、 ONTAP によって LIF のホームポートが自動的に選択されます。ONTAP は、そのサブネット内の他の LIF と同じブロードキャストドメイン内のホームポートを選択します。ホームポートは指定できますが、指定した IPspace のサブネットにまだ LIF がない場合を除き、指定する必要はありません。

SMBトラフィックを伝送するLIFを、ホームノードに自動的にリバートするように設定しないでください。Hyper-V over SMB または SQL Server over SMB でノンストップオペレーションを実現する解決策を SMB サーバでホストする場合、これは必須です。

.手順
. LIF に使用するブロードキャストドメインのポートを決定します。
+
`network port broadcast-domain show -ipspace _ipspace1_`

+
....
IPspace     Broadcast                       Update
Name        Domain name   MTU   Port List   Status Details
ipspace1
            default       1500
                                node1:e0d   complete
                                node1:e0e   complete
                                node2:e0d   complete
                                node2:e0e   complete
....
. LIF に使用するサブネットに未使用の IP アドレスが十分にあることを確認します。
+
`network subnet show -ipspace _ipspace1_`

. データへのアクセスに使用するポートに 1 つ以上の LIF を作成します。
+
`network interface create -vserver _vs1_ -lif _lif1_ -home-node _node1_ -home-port _e0d_ -service-policy _default-data-files_ -subnet-name _ipspace1_`

. LIF インターフェイスの設定が正しいことを確認します。
+
`network interface show -vserver vs1`

+
....
          Logical    Status     Network         Current   Current Is
Vserver   Interface  Admin/Oper Address/Mask    Node      Port    Home
--------- ---------- ---------- --------------- --------- ------- ----
vs1
           lif1       up/up      10.0.0.128/24   node1     e0d     true
....
. フェイルオーバーグループの設定が適切であることを確認します。
+
`network interface show -failover -vserver _vs1_`

+
....
         Logical    Home       Failover        Failover
Vserver  interface  Node:Port  Policy          Group
-------- ---------- ---------  ---------       --------
vs1
         lif1       node1:e0d  system-defined  ipspace1
Failover Targets: node1:e0d, node1:e0e, node2:e0d, node2:e0e
....

