---
sidebar: sidebar 
permalink: networking/determine_which_ports_can_be_used_for_a_broadcast_domains.html 
keywords: move, moving, broadcast, domain, ipspace, determining which ports can be used for a broadcast domain, before you can configure a broadcast domain to add to the new ipspace, you must determine what ports are available for the broadcast domain 
summary: 新しい IPspace に追加するブロードキャストドメインを設定する前に、ブロードキャストドメインに使用できるポートを確認する必要があります 
---
= ブロードキャストドメインに使用できるポートの確認（ONTAP 9.7以前）
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
新しい IPspace に追加するブロードキャストドメインを設定する前に、ブロードキャストドメインに使用できるポートを確認する必要があります。


NOTE: このタスクは、 ONTAP 9.8 ではなく、 ONTAP 9.1-9.7 に関連しています。

.作業を開始する前に
このタスクを実行するには、クラスタ管理者である必要があります。

.このタスクについて
* 使用できるポートは、物理ポート、 VLAN 、インターフェイスグループ（ ifgroup ）です。
* 新しいブロードキャストドメインに追加するポートを既存のブロードキャストドメインに割り当てることはできません。
* ブロードキャストドメインに追加するポートがすでに別のブロードキャストドメイン（たとえば、デフォルト IPspace 内のデフォルトブロードキャストドメイン）に割り当てられている場合は、そのブロードキャストドメインからポートを削除してから新しいブロードキャストドメインに割り当てる必要があります。
* LIF が割り当てられているポートをブロードキャストドメインから削除することはできません。
* クラスタ管理 LIF とノード管理 LIF はデフォルト IPspace 内のデフォルトブロードキャストドメインに割り当てられるため、これらの LIF に割り当てられているポートはデフォルトブロードキャストドメインから削除できません。


.手順
. 現在のポートの割り当てを確認します。
+
`network port show`

+
[listing]
----
Node   Port IPspace  Broadcast Domain Link   MTU  Admin/Oper
------ ---- -------  ---------------- ----- ----  ------------
node1
       e0a  Cluster  Cluster          up    9000  auto/1000
       e0b  Cluster  Cluster          up    9000  auto/1000
       e0c  Default  Default          up    1500  auto/1000
       e0d  Default  Default          up    1500  auto/1000
       e0e  Default  Default          up    1500  auto/1000
       e0f  Default  Default          up    1500  auto/1000
       e0g  Default  Default          up    1500  auto/1000
node2
       e0a  Cluster  Cluster          up    9000  auto/1000
       e0b  Cluster  Cluster          up    9000  auto/1000
       e0c  Default  Default          up    1500  auto/1000
       e0d  Default  Default          up    1500  auto/1000
       e0e  Default  Default          up    1500  auto/1000
       e0f  Default  Default          up    1500  auto/1000
       e0g  Default  Default          up    1500  auto/1000
----
+
この例では、コマンドの出力から次の情報が得られます。

+
** ポート `e0c`、 `e0d`、 `e0e`、 `e0f`および `e0g` 各ノードにはデフォルトのブロードキャストドメインが割り当てられています。
** これらのポートは、作成する IPspace のブロードキャストドメインで使用できる可能性があります。


. デフォルトブロードキャストドメイン内の、 LIF インターフェイスに割り当てられている、したがって新しいブロードキャストドメインに移動できないポートを確認します。
+
`network interface show`

+
[listing]
----
         Logical      Status     Network         Current   Current Is
Vserver  Interface    Admin/Oper Address/Mask    Node      Port    Home
-------  ----------   ---------- ------------   --------- -------  ----
Cluster
         node1_clus1  up/up       10.0.2.40/24   node1     e0a     true
         node1_clus2  up/up       10.0.2.41/24   node1     e0b     true
         node2_clus1  up/up       10.0.2.42/24   node2     e0a     true
         node2_clus2  up/up       10.0.2.43/24   node2     e0b     true

cluster1
         cluster_mgmt up/up       10.0.1.41/24   node1     e0c     true
         node1_mgmt   up/up       10.0.1.42/24   node1     e0c     true
         node2_mgmt   up/up       10.0.1.43/24   node2     e0c     true
----
+
次の例では、コマンドの出力から次の情報が得られます。

+
** ノードポートがポートに割り当てられます `e0c` 各ノードで、クラスタ管理LIFのホームノードがオンになっている `e0c` オン `node1`。
** ポート `e0d`、 `e0e`、 `e0f`および `e0g` 各ノードがLIFをホストしていないため、デフォルトのブロードキャストドメインから削除して、新しいIPspaceの新しいブロードキャストドメインに追加できます。



