---
sidebar: sidebar 
permalink: networking/display_network_connectivity_with_neighbor_discovery_protocols.html 
keywords: display, view, show, network, connectivity, neighbor, discovery, protocol, ndp, cdp, cisco, link, layer, lldp, display network connectivity with neighbor discovery protocols, use neighbor discovery protocols to view network connectivity between a pair of physical or virtual systems and their network interfaces, use cdp to detect network connectivity, considerations for using cdp, enable or disable cdp, view cdp neighbor information, example of showing and clearing statistics, use lldp to detect network connectivity, enable or disable lldp, view lldp neighbor information, adjust the interval for transmitting lldp advertisements 
summary: 近隣探索プロトコルを使用して、物理システムまたは仮想システムのペアとそのネットワーク インターフェイス間のネットワーク接続を表示します 
---
= ネイバー探索プロトコルを使用した ONTAP ネットワーク接続の表示
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
データセンターでは、ネイバー探索プロトコルを使用して、物理システムまたは仮想システムのペアとそのネットワークインターフェース間のネットワーク接続を表示できます。ONTAPは、Cisco Discovery Protocol（CDP）とLink Layer Discovery Protocol（LLDP）という2つのネイバー探索プロトコルをサポートしています。

近隣探索プロトコルによって、ネットワーク内の直接接続されているプロトコル対応デバイスが自動的に検出され、その情報が表示されるようになります。各デバイスがID、機能、および接続情報を通知します。この情報はイーサネット フレームでマルチキャストMACアドレスへ送信され、近隣のプロトコル対応デバイスで受信されます。

2つのデバイスどうしが近隣機器となるためには、各デバイスでプロトコルが有効で、正しく設定されている必要があります。探索プロトコルの機能は直接接続されたネットワークに限定されます。近隣機器には、スイッチ、ルーター、ブリッジなどのプロトコル対応デバイスが含まれます。ONTAPでは、2つの近隣探索プロトコルがサポートされます。これらは個別に使用することも一緒に使用することも可能です。

*Cisco Discovery Protocol（CDP）*

CDPは、Cisco Systemsが開発したリンク レイヤ プロトコルです。ONTAPでは、クラスタ ポートに対してこのプロトコルがデフォルトで有効になりますが、データ ポートに対しては明示的に有効にする必要があります。

*Link Layer Discovery Protocol（LLDP）*

LLDPは、ベンダーに依存しないプロトコルであり、IEEE 802.1AB規格のドキュメントで指定されています。このプロトコルは、すべてのポートに対して明示的に有効にする必要があります。
