---
sidebar: sidebar 
permalink: networking/display_interface_group_information_cluster_administrators_only.html 
keywords: 'display, view, show, interface, group, information, display interface group information (cluster administrators only), verify interface group configuration, network port ifgrp show' 
summary: インターフェイスグループの設定を確認 
---
= ONTAPインターフェース グループ情報を表示する
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
インターフェイス グループに関する情報を表示して、その設定を確認できます。

.タスク概要
次の情報が表示されます。

* インターフェイス グループが配置されているノード
* インターフェイス グループに含まれているネットワーク ポートのリスト
* インターフェイス グループの名前
* 分散機能（MAC、IP、ポート、シーケンシャル）
* インターフェイス グループのMAC（メディア アクセス制御）アドレス
* ポートのアクティビティ・ステータス、つまりポート全体がアクティブ（完全参加）か、一部がアクティブ（部分参加）か、1つもアクティブでないか


.手順
 `network port ifgrp show`コマンドを使用してインターフェース グループに関する情報を表示します。

 `-instance`パラメータを指定することで、各ノードの詳細情報を表示できます。 `-fields`パラメータを使用してフィールド名を指定することで、特定の情報を表示できます。

次のコマンドは、クラスタ内のすべてのインターフェイス グループに関する情報を表示します。

....
network port ifgrp show
         Port     Distribution                    Active
Node     IfGrp    Function     MAC Address        Ports   Ports
-------- -------- ------------ -----------------  ------- --------
cluster-1-01
         a0a      ip           02:a0:98:06:10:b2  full    e7a, e7b
cluster-1-02
         a0a      sequential   02:a0:98:06:10:ca  full    e7a, e7b
cluster-1-03
         a0a      port         02:a0:98:08:5b:66  full    e7a, e7b
cluster-1-04
         a0a      mac          02:a0:98:08:61:4e  full    e7a, e7b
....
次のコマンドは、1つのノードのインターフェイス グループに関する詳細情報を表示します。

....
network port ifgrp show -instance -node cluster-1-01

                 Node: cluster-1-01
 Interface Group Name: a0a
Distribution Function: ip
        Create Policy: multimode
          MAC Address: 02:a0:98:06:10:b2
   Port Participation: full
        Network Ports: e7a, e7b
             Up Ports: e7a, e7b
           Down Ports: -
....
 `network port ifgrp show`の詳細については、link:https://docs.netapp.com/us-en/ontap-cli/network-port-ifgrp-show.html["ONTAPコマンド リファレンス"^]を参照してください。
