---
sidebar: sidebar 
permalink: networking/display_information_about_failover_groups.html 
keywords: display, view, show, failover, fail, over, groups, display information about failover groups, view information about failover groups, network interface failover-groups show, network interface failover-groups show, network interface show 
summary: フェイルオーバーグループに関する情報を表示します 
---
= フェイルオーバーグループに関する情報を表示します
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
フェイルオーバーグループに関する情報を表示することができます。これには、各フェイルオーバーグループ内のノードとポートのリスト、フェイルオーバーの有効 / 無効、各 LIF に適用されているフェイルオーバーポリシーの種類が含まれます。

.手順
. network interface failover-groups show コマンドを使用して、各フェイルオーバーグループのターゲットポートを表示します。
+
次のコマンドは、 2 ノードクラスタのすべてのフェイルオーバーグループに関する情報を表示します。

+
....
network interface failover-groups show
                              Failover
Vserver        Group          Targets
-------------- -------------- ---------------------------------
Cluster
               Cluster
                              cluster1-01:e0a, cluster1-01:e0b,
                              cluster1-02:e0a, cluster1-02:e0b
vs1
               Default
                              cluster1-01:e0c, cluster1-01:e0d,
                              cluster1-01:e0e, cluster1-02:e0c,
                              cluster1-02:e0d, cluster1-02:e0e
....
. network interface failover-groups show コマンドを使用して、特定のフェイルオーバーグループのターゲットポートとブロードキャストドメインを表示します。
+
次のコマンドは、 SVM vs4 の data12 というフェイルオーバーグループに関する詳しい情報を表示します。

+
....
network interface failover-groups show -vserver vs4 -failover-group data12

       Vserver Name: vs4
Failover Group Name: data12
   Failover Targets: cluster1-01:e0f, cluster1-01:e0g, cluster1-02:e0f,
                     cluster1-02:e0g
   Broadcast Domain: Default
....
. network interface show コマンドを使用して、すべての LIF で使用されているフェイルオーバー設定を表示します。
+
次のコマンドは、各 LIF で使用されているフェイルオーバーポリシーとフェイルオーバーグループを表示します。

+
....
network interface show -vserver * -lif * -fields failover-group,failover-policy
vserver   lif                 failover-policy        failover-group
--------  ------------------  ---------------------  --------------
Cluster   cluster1-01_clus_1  local-only             Cluster
Cluster   cluster1-01_clus_2  local-only             Cluster
Cluster   cluster1-02_clus_1  local-only             Cluster
Cluster   cluster1-02_clus_2  local-only             Cluster
cluster1  cluster_mgmt        broadcast-domain-wide  Default
cluster1  cluster1-01_mgmt1   local-only             Default
cluster1  cluster1-02_mgmt1   local-only             Default
vs1       data1               disabled               Default
vs3       data2               system-defined         group2
....

