---
sidebar: sidebar 
permalink: networking/display_routing_information.html 
keywords: display, view, show, route, svm, storage, virtual, machine, display routing information, view information about the routing configuration for each svm on your cluster, network route show, network route show-lifs, network route active-entry show 
summary: クラスタ上の各SVMのルーティング設定に関する情報を表示します 
---
= ONTAPルーティング情報を表示する
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
クラスタ上のそれぞれのSVMについて、ルーティング設定に関する情報を表示できます。この情報は、クライアント アプリケーションやサービスとクラスタ内のノード上のLIFとの接続に問題がある場合のルーティングの問題を診断するのに役立ちます。

.手順
.  `network route show`コマンドを使用して、1つ以上のSVM内のルートを表示します。次の例は、vs0 SVMに設定されたルートを示しています：
+
....
network route show
  (network route show)
Vserver             Destination     Gateway         Metric
------------------- --------------- --------------- ------
vs0
                    0.0.0.0/0       172.17.178.1    20
....
.  `network route show-lifs`コマンドを使用して、1つ以上のSVM内のルートとLIFの関連付けを表示します。
+
次の例では、vs0というSVMが所有するルートとLIFの関連付けを表示しています。

+
....
network route show-lifs
  (network route show-lifs)

Vserver: vs0
Destination             Gateway                 Logical Interfaces
----------------------  --------------          --------------------
0.0.0.0/0               172.17.178.1            cluster_mgmt,
                                                LIF-b-01_mgmt1,
                                                LIF-b-02_mgmt1
....
+
 `network route show`および `network route show-lifs`の詳細については、link:https://docs.netapp.com/us-en/ontap-cli/search.html?q=network+route+show["ONTAPコマンド リファレンス"^]をご覧ください。

.  `network route active-entry show`コマンドを使用して、1つ以上のノード、SVM、サブネット、または指定された宛先を持つルートにインストールされているルートを表示します。
+
次の例では、特定のSVMに設定されたすべてのルートを表示しています。

+
....
network route active-entry show -vserver Data0

Vserver: Data0
Node: node-1
Subnet Group: 0.0.0.0/0
Destination             Gateway              Interface   Metric  Flags
----------------------  -------------------  ---------   ------  -----
127.0.0.1               127.0.0.1            lo              10  UHS
127.0.10.1              127.0.20.1           losk            10  UHS
127.0.20.1              127.0.20.1           losk            10  UHS

Vserver: Data0
Node: node-1
Subnet Group: fd20:8b1e:b255:814e::/64
Destination             Gateway              Interface   Metric  Flags
----------------------  -------------------  ---------   ------  -----
default                 fd20:8b1e:b255:814e::1
                                             e0d             20  UGS
fd20:8b1e:b255:814e::/64
                        link#4               e0d              0  UC

Vserver: Data0
Node: node-2
Subnet Group: 0.0.0.0/0
Destination             Gateway              Interface   Metric  Flags
----------------------  -------------------  ---------   ------  -----
127.0.0.1               127.0.0.1            lo              10  UHS

Vserver: Data0
Node: node-2
Subnet Group: 0.0.0.0/0
Destination             Gateway              Interface   Metric  Flags
----------------------  -------------------  ---------   ------  -----
127.0.10.1              127.0.20.1           losk            10  UHS
127.0.20.1              127.0.20.1           losk            10  UHS

Vserver: Data0
Node: node-2
Subnet Group: fd20:8b1e:b255:814e::/64
Destination             Gateway              Interface   Metric  Flags
----------------------  -------------------  ---------   ------  -----
default                 fd20:8b1e:b255:814e::1
                                             e0d             20  UGS
fd20:8b1e:b255:814e::/64
                        link#4               e0d              0  UC
fd20:8b1e:b255:814e::1  link#4               e0d              0  UHL
11 entries were displayed.
....
+
 `network route active-entry show`の詳細については、link:https://docs.netapp.com/us-en/ontap-cli/network-route-active-entry-show.html["ONTAPコマンド リファレンス"^]をご覧ください。


