---
sidebar: sidebar 
permalink: networking/display_network_connectivity_with_neighbor_discovery_protocols.html 
keywords: display, view, show, network, connectivity, neighbor, discovery, protocol, ndp, cdp, cisco, link, layer, lldp, display network connectivity with neighbor discovery protocols, use neighbor discovery protocols to view network connectivity between a pair of physical or virtual systems and their network interfaces, use cdp to detect network connectivity, considerations for using cdp, enable or disable cdp, view cdp neighbor information, example of showing and clearing statistics, use lldp to detect network connectivity, enable or disable lldp, view lldp neighbor information, adjust the interval for transmitting lldp advertisements 
summary: 近接探索プロトコルを使用して、物理または仮想システムのペアとそのネットワークインターフェイス間のネットワーク接続を表示します 
---
= 近接探索プロトコルによるネットワーク接続を表示します
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
データセンターでは、近接探索プロトコルを使用して、物理または仮想システムのペアとそのネットワークインターフェイス間のネットワーク接続を表示できます。ONTAP では、 2 つの近接探索プロトコルとして、 Cisco Discovery Protocol （ CDP ）と Link Layer Discovery Protocol （ LLDP ）がサポートされます。

近接探索プロトコルを使用すると、ネットワーク内の直接接続されているプロトコル対応デバイスを自動的に検出し、その情報を表示できます。各デバイスは、 ID 、機能、および接続情報をアドバタイズします。この情報はイーサネットフレームでマルチキャスト MAC アドレスへ送信され、近接するすべてのプロトコル対応デバイスで受信されます。

2 つのデバイスがネイバーになるには、各デバイスでプロトコルが有効になっていて、正しく設定されている必要があります検出プロトコルの機能は、直接接続されたネットワークに限定されます。近接機器には、スイッチ、ルータ、ブリッジなどのプロトコル対応デバイスが含まれます。ONTAP では、 2 つの近接探索プロトコルがサポートされます。これらは個別に使用することも一緒に使用することもでき

* シスコ検出プロトコル（ CDP ） *

CDP は、 Cisco Systems が開発したリンクレイヤプロトコルです。ONTAP では、クラスタポートに対してこのプロトコルがデフォルトで有効になりますが、データポートに対しては明示的に有効にする必要があります。

* リンク層検出プロトコル（ LLDP ） *

LLDP は、ベンダーに依存しないプロトコルであり、 IEEE 802.1AB 規格のドキュメントで指定されています。すべてのポートに対して明示的にイネーブルにする必要があります。
