---
sidebar: sidebar 
permalink: networking/index.html 
keywords: ontap, 9, network, management, documentation, guide, ontap 9 network management documentation, welcome to the ontap 9 network management documentation portal 
summary: ONTAP 9 ネットワーク管理ドキュメントポータルへようこそ 
---
= ONTAP 9 ネットワーク管理マニュアル
:hardbreaks:
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
System Manager を使用すると、ネットワークを視覚化し、ネットワークに関する統合データをダウンロードできます。詳細については、次のトピックを参照してください。

* link:https://docs.netapp.com/us-en/ontap/concept_admin_viewing_managing_network.html["ネットワークを表示および管理します"]
* link:https://docs.netapp.com/us-en/ontap/concept_admin_downloading_data_report.html["レポート用のネットワークデータをダウンロードします"]


ONTAP CLI を使用してネットワークを設定および管理することもできます。ONTAP 9 の CLI ネットワーク管理のマニュアルは、次の 3 つの主要な領域で構成されています。

link:set_up_nas_path_failover_98_and_later_cli.html["ONTAP 9.8 以降で NAS パスのフェイルオーバーを設定します"]

ONTAP 9.8 以降で確立されているベストプラクティスを使用して、 NAS パスのフェイルオーバーを設定する方法について説明します

link:set_up_nas_path_failover_9_to_97_cli.html["ONTAP 9.7 以前の場合は、 NAS パスのフェイルオーバーを設定します"]

ONTAP 9.7 以前で確立されているベストプラクティスを使用して NAS パスのフェイルオーバーを設定する方法について説明します。

link:networking_reference.html["ネットワーク関連資料"]

ネットワークのリファレンスドキュメントでは、クラスタで物理 / 仮想ネットワークポート（ VLAN およびインターフェイスグループ）、 IPv4 / IPv6 を使用する LIF 、ルーティング、およびホスト解決サービスを設定および管理する方法、ロードバランシングでネットワークトラフィックを最適化する方法、および SNMP を使用してクラスタを監視する方法について説明しています。特に記載がないかぎり、この情報は環境のすべてのバージョンの ONTAP 9 に関するものです。
