---
sidebar: sidebar 
permalink: networking/lifs_and_service_policies96.html 
keywords: service policies for system svms, lif service policies, lif, logical, interface, service, policy, policies, lifs and service policies in ontap 9.6 and later, assign service policies to lifs to specify the supported traffic, service policies for system svms, service policies for data svms, data-core service 
summary: LIF にサービスポリシーを割り当てて、サポートされるトラフィックを指定します 
---
= LIFとサービスポリシー（ONTAP 9 .6以降）
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
LIFのロールやファイアウォールポリシーの代わりに、LIFでサポートされるトラフィックの種類を決定するサービスポリシーをLIFに割り当てることができます。サービスポリシーは、LIFでサポートされる一連のネットワークサービスを定義します。ONTAPには、LIFに関連付けることができる一連の組み込みのサービスポリシーが用意されています。

サービスポリシーとその詳細を表示するには、次のコマンドを使用します。
`network interface service-policy show`

特定のサービスにバインドされていない機能では、システム定義の動作を使用してアウトバウンド接続用のLIFが選択されます。

サービスポリシーが空のLIF上のアプリケーションが予期せず動作することがあります。



== システムSVMのサービスポリシー

管理SVMとシステムSVMには、管理LIFやクラスタ間LIFなど、そのSVMのLIFに使用できるサービスポリシーが含まれています。これらのポリシーは、IPspaceの作成時にシステムによって自動的に作成されます。

次の表に、ONTAP 9時点でのシステムSVMのLIFの組み込みのポリシーを示します。それ以外のリリースの場合は、次のコマンドを使用してサービスポリシーとその詳細を表示します。

`network interface service-policy show`

[cols="20,20,20,40"]
|===


| ポリシー | 付属サービス | 同等のロール | 説明 


 a| 
デフォルト - intercluster
 a| 
インタークラスタコア、管理 - https ： //
 a| 
クラスタ間
 a| 
クラスタ間トラフィックを処理する LIF で使用されます。注：サービス intercluster-core は、 net-intercluster サービスポリシーという名前で ONTAP 9.5 から提供されています。



 a| 
default-route-announce
 a| 
management-bgp
 a| 
-
 a| 
BGP ピア接続を処理する LIF で使用されます。注： ONTAP 9.5 では net-route-announce サービスポリシーという名前で提供されています。



 a| 
default-management
 a| 
management-core、management-https、management-http、management-ssh、management-autosupport、 management-ems、management-dns-client、management-ad-client, management-ldap-client, management-nis-client, management-ntp-client, management-log-forwarding
 a| 
ノード管理、またはクラスタ管理
 a| 
システムを対象としたこの管理ポリシーを使用して、システムSVMが所有するノードとクラスタを対象とした管理LIFを作成します。これらのLIFは、DNS、AD、LDAP、またはNISサーバへのアウトバウンド接続に使用できるだけでなく、システム全体の代わりに実行されるアプリケーションをサポートするための追加の接続にも使用できます。ONTAP 9 12.1以降では、サービスを使用して、監査ログをリモートsyslogサーバに転送するために使用するLIFを制御でき `management-log-forwarding`ます。

|===
次の表に、ONTAP 9 .11.1以降でシステムSVMでLIFが使用できるサービスを示します。

[cols="25,25,50"]
|===


| サービス | フェイルオーバーの制限 | 説明 


 a| 
intercluster-core
 a| 
home-node-only
 a| 
中核となるクラスタ間サービス



 a| 
管理コア
 a| 
-
 a| 
中核となる管理サービス



 a| 
management-ssh
 a| 
-
 a| 
SSH管理アクセス用のサービス



 a| 
Management - http ： //
 a| 
-
 a| 
HTTP管理アクセス用のサービス



 a| 
管理 - HTTPS
 a| 
-
 a| 
HTTPS管理アクセス用のサービス



 a| 
management-autosupport
 a| 
-
 a| 
AutoSupport ペイロードの送信に関連するサービス



 a| 
management-bgp
 a| 
home-port - Only （ホームポートのみ）
 a| 
BGP ピアのやり取りに関連するサービス



 a| 
backup-ndmp-control の実行
 a| 
-
 a| 
NDMP バックアップ制御のためのサービス



 a| 
管理 - EMS
 a| 
-
 a| 
管理メッセージアクセス用のサービス



 a| 
management-ntp-client
 a| 
-
 a| 
ONTAP 9.10.1で導入されました。NTPクライアントアクセス用のサービス。



 a| 
management-ntp-server
 a| 
-
 a| 
ONTAP 9.10.1で導入されました。NTPサーバ管理アクセス用のサービス



 a| 
管理 - portmap
 a| 
-
 a| 
portmap 管理用のサービス



 a| 
management-srsh -server です
 a| 
-
 a| 
rsh サーバ管理のためのサービス



 a| 
management-snmp-server
 a| 
-
 a| 
SNMP サーバ管理用のサービス



 a| 
management-telnet-server
 a| 
-
 a| 
Telnet サーバ管理用のサービス



 a| 
管理-ログ転送
 a| 
-
 a| 
ONTAP 9.12.1で導入されました。監査ログ転送用のサービス

|===


== データSVMのサービス ポリシー

すべてのデータSVMに、そのSVMのLIFで使用できるサービス ポリシーが含まれています。

次の表は、ONTAP 9.11.1以降のデータSVMでLIFが使用可能な組み込みのポリシーの一覧です。その他のリリースのサービス ポリシーとその詳細を表示するには、次のコマンドを使用します。

`network interface service-policy show`

[cols="20,20,20,40"]
|===


| ポリシー | 付属サービス | 同等のデータプロトコル | 説明 


 a| 
default-management
 a| 
management-https、management-http、management-ssh、management-dns-client, management-ad-client, management-ldap-client、management-nis-client
 a| 
なし
 a| 
このSVMを対象とした管理ポリシーを使用して、データSVMが所有するSVM管理LIFを作成します。これらのLIFを使用して、SVM管理者にSSHまたはHTTPSアクセスを提供できます。必要に応じて、これらのLIFを外部DNS、AD、LDAP、またはNISサーバへのアウトバウンド接続に使用できます。



 a| 
default-data-blocks （デフォルトデータブロック）
 a| 
データコア、データ - iSCSI
 a| 
iSCSI
 a| 
ブロックベースのSANデータトラフィックを処理するLIFで使用されます。ONTAP 9.10.1以降、「default-data-blocks」ポリシーは廃止されました。代わりに「default-data-iscsi」サービス ポリシーを使用してください。



 a| 
default-data-files の形式で指定します
 a| 
data-filc-client, data-dns-server , data-fflexcache , data-cifs , data-nfs , management-dns-client、management-ad-client, management-ldap-client, management-nis-client
 a| 
NFS 、 CIFS 、 fcache
 a| 
default-data-filesポリシーを使用して、ファイルベースのデータプロトコルをサポートするNAS LIFを作成します。SVM内にLIFが1つしかない場合もあるため、このポリシーでは、LIFを外部のDNS、AD、LDAP、またはNISサーバへのアウトバウンド接続に使用できるようにします。これらの接続で管理LIFのみを使用する場合は、これらのサービスをこのポリシーから削除できます。



 a| 
default-data-iscsi
 a| 
データコア、データ - iSCSI
 a| 
iSCSI
 a| 
iSCSIデータトラフィックを処理するLIFで使用されます。



 a| 
default-data-nvme-tcpです
 a| 
データコア、データNVMe - TCP
 a| 
nvme-tcpが表示されます
 a| 
NVMe/FCデータトラフィックを処理するLIFで使用します。

|===
次の表に、データSVMで使用できる各サービスを、ONTAP 9 11.1以降のLIFのフェイルオーバーポリシーに適用される制限とともに示します。

[cols="25,25,50"]
|===


| サービス | フェイルオーバーの制限 | 説明 


 a| 
management-ssh
 a| 
-
 a| 
SSH管理アクセス用のサービス



 a| 
Management - http ： //
 a| 
-
 a| 
ONTAP 9.10.1 Services for HTTP管理アクセスで導入されました



 a| 
管理 - HTTPS
 a| 
-
 a| 
HTTPS管理アクセス用のサービス



 a| 
管理 - portmap
 a| 
-
 a| 
portmap 管理アクセス用のサービス



 a| 
management-snmp-server
 a| 
-
 a| 
SNMPサーバ管理アクセス用のONTAP 9.10.1サービスで導入されました



 a| 
データコア
 a| 
-
 a| 
コアデータサービス



 a| 
データ- NFS
 a| 
-
 a| 
NFSデータサービス



 a| 
データ- CIFS
 a| 
-
 a| 
CIFSデータサービス



 a| 
Data FlexCache
 a| 
-
 a| 
FlexCache データサービス



 a| 
データ - iSCSI
 a| 
AFF / FASの場合はホームポートのみ、ASAの場合はSFOパートナーのみ
 a| 
iSCSI データサービス



 a| 
backup-ndmp-control の実行
 a| 
-
 a| 
ONTAP 9.10.1 Backup NDMPでデータサービスの制御が導入されました



 a| 
data-dns-server
 a| 
-
 a| 
ONTAP 9.10.1で導入されたDNSサーバデータサービス



 a| 
data-fpolicy-client
 a| 
-
 a| 
ファイルスクリーニングポリシーデータサービス



 a| 
data-nvme-tcp を選択します
 a| 
home-port - Only （ホームポートのみ）
 a| 
ONTAP 9.10.1でNVMe TCPデータサービスが導入されました



 a| 
data-s3-server のように指定します
 a| 
-
 a| 
Simple Storage Service （ S3 ）サーバデータサービス

|===
データSVM内のLIFへのサービスポリシーの割り当てについて理解しておく必要があります。

* データサービスのリストを指定してデータSVMを作成すると、指定したサービスを使用して、そのSVMに組み込みの「default-data-files」および「default-data-blocks」サービスポリシーが作成されます。
* データサービスのリストを指定せずにデータSVMを作成すると、そのSVMに組み込みの「default-data-files」サービスポリシーと「default-data-blocks」サービスポリシーが、デフォルトのデータサービスのリストを使用して作成されます。
+
デフォルトのデータサービスのリストには、iSCSI、NFS、NVMe、SMB、FlexCacheの各サービスが含まれています。

* データプロトコルのリストを指定してLIFを作成すると、指定したデータプロトコルに相当するサービスポリシーがLIFに割り当てられます。
* 同等のサービスポリシーが存在しない場合は、カスタムサービスポリシーが作成されます。
* サービスポリシーやデータプロトコルのリストを指定せずにLIFを作成した場合、デフォルトでdefault-data-filesサービスポリシーがLIFに割り当てられます。




== data-coreサービス

data-coreサービスを使用すると、LIFのロール（ONTAP 9で廃止）ではなくサービスポリシーを使用してLIFを管理するようにアップグレードされたクラスタで、以前にdataロールのLIFを使用していたコンポーネントが想定どおりに動作するようになります。

data-coreをサービスとして指定してもファイアウォールのポートは開かれませんが、データSVMのすべてのサービスポリシーにこのサービスを含める必要があります。たとえば、default-data-filesサービスポリシーには、デフォルトで次のサービスが含まれています。

* データコア
* データ- NFS
* データ- CIFS
* Data FlexCache


data-coreサービスは、LIFを使用するすべてのアプリケーションが想定どおりに動作するようにポリシーに含める必要がありますが、残りの3つのサービスは必要に応じて削除できます。



== クライアント側のLIFサービス

ONTAP 9 .10.1以降では、ONTAPは複数のアプリケーションに対してクライアント側のLIFサービスを提供します。これらのサービスは、各アプリケーションの代わりにアウトバウンド接続に使用するLIFを制御します。

次の新しいサービスを使用すると、特定のアプリケーションのソースアドレスとして使用するLIFを管理者が制御できます。

[cols="25,25,50"]
|===


| サービス | SVM の制限事項 | 説明 


 a| 
management-ad-client
 a| 
-
 a| 
ONTAP 9.11.1以降では、ONTAP は外部ADサーバへのアウトバウンド接続にActive Directoryクライアントサービスを提供します。



| management-dns-client  a| 
-
 a| 
ONTAP 9.11.1以降では、ONTAPは外部のDNSサーバへのアウトバウンド接続用にDNSクライアントサービスを提供しています。



| 管理-LDAPクライアント  a| 
-
 a| 
ONTAP 9.11.1以降では、ONTAPは外部のLDAPサーバへのアウトバウンド接続用にLDAPクライアントサービスを提供しています。



| management-nis-client  a| 
-
 a| 
ONTAP 9.11.1以降では、ONTAPは外部のNISサーバへのアウトバウンド接続用にNISクライアントサービスを提供しています。



 a| 
management-ntp-client
 a| 
システムのみ
 a| 
ONTAP 9.10.1以降では、ONTAPは外部のNTPサーバへのアウトバウンド接続用にNTPクライアントサービスを提供しています。



 a| 
data-fpolicy-client
 a| 
データ専用
 a| 
ONTAP 9.8 以降では、 ONTAP はアウトバウンド FPolicy 接続のクライアントサービスを提供します。

|===
新しいサービスはそれぞれ自動的に組み込みのサービスポリシーの一部に含まれますが、管理者はそれらのサービスを組み込みのポリシーから削除したり、カスタムポリシーに追加して、各アプリケーションの代わりにアウトバウンド接続に使用するLIFを制御したりすることができます。
