---
sidebar: sidebar 
permalink: networking/lifs_and_service_policies96.html 
keywords: service policies for system svms, lif service policies, lif, logical, interface, service, policy, policies, lifs and service policies in ontap 9.6 and later, assign service policies to lifs to specify the supported traffic, service policies for system svms, service policies for data svms, data-core service 
summary: LIF にサービス ポリシーを割り当てて、サポートされるトラフィックを指定します。 
---
= ONTAP LIFとサービスポリシーについて学ぶ
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
（LIFのロールまたはファイアウォール ポリシーの代わりに）サービス ポリシーをLIFに割り当てて、LIFでサポートされるトラフィックの種類を設定できます。サービス ポリシーは、LIFでサポートされる一連のネットワーク サービスを定義します。ONTAPには、LIFに関連付けることができる一連の組み込みのサービス ポリシーが用意されています。


NOTE: ONTAP 9.7以前のバージョンでは、ネットワーク トラフィックの管理方法が異なります。ONTAP 9.7以前を実行しているネットワークでトラフィックを管理する必要がある場合は、link:https://docs.netapp.com/us-en/ontap-system-manager-classic/networking/lif_roles95.html["LIFのロール（ONTAP 9.5以前）"^]を参照してください。

次のコマンドを使用して、サービス ポリシーとその詳細を表示できます：
`network interface service-policy show`

 `network interface service-policy show`の詳細については、link:https://docs.netapp.com/us-en/ontap-cli/network-interface-service-policy-show.html["ONTAPコマンド リファレンス"^]を参照してください。

特定のサービスにバインドされていない機能では、システム定義の動作を使用してアウトバウンド接続用のLIFを選択します。

サービス ポリシーが空であるLIF上のアプリケーションは、予期しない動作をすることがあります。



== システムSVMのサービス ポリシー

管理SVMとシステムSVMには、SVMのLIF（管理LIFやクラスタ間LIFなど）に使用できるサービス ポリシーが含まれています。これらのポリシーは、IPspaceの作成時にシステムによって自動的に作成されます。

次の表は、ONTAP 9.12.1以降のシステムSVMのLIFに組み込まれているポリシーの一覧です。その他のリリースの場合は、次のコマンドを使用してサービス ポリシーとその詳細を表示します：

`network interface service-policy show`

[cols="20,20,20,40"]
|===


| ポリシー | 付属サービス | 同等の役割 | 概要 


 a| 
デフォルトインタークラスタ
 a| 
intercluster-core、management-https
 a| 
intercluster
 a| 
クラスタ間トラフィックを伝送する LIF によって使用されます。注：サービス intercluster-core は ONTAP 9.5 以降、net-intercluster サービス ポリシーという名前で使用できます。



 a| 
デフォルトルートアナウンス
 a| 
management-BGP
 a| 
-
 a| 
BGP ピア接続を伝送する LIF によって使用されます。注：ONTAP 9.5 以降では、net-route-announce サービス ポリシーという名前で使用できます。



 a| 
デフォルト管理
 a| 
management-core、management-https、management-http、management-ssh、management-autosupport、management-ems、management-dns-client、management-ad-client、management-ldap-client、management-nis-client、management-ntp-client、management-log-forwarding
 a| 
node-mgmt、またはcluster-mgmt
 a| 
このシステムスコープ管理ポリシーを使用して、システムSVMが所有するノードスコープおよびクラスタスコープの管理LIFを作成します。これらのLIFは、DNS、AD、LDAP、またはNISサーバへのアウトバウンド接続に加え、システム全体を代表して実行されるアプリケーションをサポートするための追加接続にも使用できます。ONTAP 9.12.1以降では、 `management-log-forwarding`サービスを使用して、監査ログをリモートsyslogサーバに転送するために使用するLIFを制御できます。

|===
次の表は、ONTAP 9.11.1 以降のシステム SVM で LIF が使用できるサービスを示しています：

[cols="25,25,50"]
|===


| サービス | フェイルオーバーの制限 | 概要 


 a| 
インタークラスタコア
 a| 
ホーム ノードのみ
 a| 
コアクラスタ間サービス



 a| 
管理コア
 a| 
-
 a| 
コア管理サービス



 a| 
管理-ssh
 a| 
-
 a| 
SSH管理アクセス用のサービス



 a| 
管理-http
 a| 
-
 a| 
HTTP管理アクセス用のサービス



 a| 
管理-https
 a| 
-
 a| 
HTTPS管理アクセス用のサービス



 a| 
management-AutoSupport
 a| 
-
 a| 
AutoSupportペイロードの投稿に関連するサービス



 a| 
management-BGP
 a| 
母港のみ
 a| 
BGP ピア インタラクションに関連するサービス



 a| 
バックアップ NDMP コントロール
 a| 
-
 a| 
NDMPバックアップ制御のサービス



 a| 
管理-ems
 a| 
-
 a| 
管理メッセージング アクセスのサービス



 a| 
管理-NTPクライアント
 a| 
-
 a| 
ONTAP 9.10.1 で導入されました。NTP クライアント アクセス用のサービスです。



 a| 
management-NTP サーバー
 a| 
-
 a| 
ONTAP 9.10.1で導入されました。NTPサーバ管理アクセスのサービス



 a| 
管理-portmap
 a| 
-
 a| 
ポートマップ管理サービス



 a| 
管理-rsh-サーバ
 a| 
-
 a| 
rshサーバー管理のサービス



 a| 
管理-SNMP-サーバ
 a| 
-
 a| 
SNMPサーバー管理のサービス



 a| 
管理-Telnet-サーバ
 a| 
-
 a| 
telnetサーバー管理のサービス



 a| 
管理ログ転送
 a| 
-
 a| 
ONTAP 9.12.1で導入されました。監査ログ転送のサービス

|===


== データSVMのサービス ポリシー

すべてのデータSVMに、そのSVMのLIFで使用できるサービス ポリシーが含まれています。

次の表は、ONTAP 9.11.1以降のデータSVMのLIFに組み込まれているポリシーの一覧です。その他のリリースの場合は、次のコマンドを使用してサービス ポリシーとその詳細を表示します：

`network interface service-policy show`

[cols="20,20,20,40"]
|===


| ポリシー | 付属サービス | 同等のデータ プロトコル | 概要 


 a| 
デフォルト管理
 a| 
data-core、management-https、management-http、management-ssh、management-dns-client、management-ad-client、management-ldap-client、management-nis-client
 a| 
なし
 a| 
このSVMを対象とする管理ポリシーを使用して、データSVMが所有するSVM管理LIFを作成します。これらのLIFは、SVM管理者にSSHまたはHTTPSアクセスを提供するために使用できます。必要に応じて、これらのLIFは外部DNS、AD、LDAP、またはNISサーバーへのアウトバウンド接続にも使用できます。



 a| 
デフォルトのデータブロック
 a| 
data-core、data-iscsi
 a| 
iscsi
 a| 
ブロック指向SANデータトラフィックを伝送するLIFで使用されます。ONTAP 9.10.1以降、「default-data-blocks」ポリシーは非推奨です。代わりに「default-data-iscsi」サービスポリシーを使用してください。



 a| 
デフォルトのデータファイル
 a| 
data-core、data-fpolicy-client、data-dns-server、data-flexcache、data-cifs、data-nfs、management-dns-client、management-ad-client、management-ldap-client、management-nis-client
 a| 
nfs、cifs、fcache
 a| 
ファイルベースのデータプロトコルをサポートするNAS LIFを作成するには、default-data-filesポリシーを使用します。SVMにLIFが1つしか存在しない場合もあるため、このポリシーにより、LIFを外部DNS、AD、LDAP、またはNISサーバへのアウトバウンド接続に使用できます。これらの接続で管理LIFのみを使用する場合は、このポリシーからこれらのサービスを削除できます。



 a| 
デフォルトデータiSCSI
 a| 
data-core、data-iscsi
 a| 
iscsi
 a| 
iSCSI データ トラフィックを伝送する LIF によって使用されます。



 a| 
デフォルトデータ NVMe-TCP
 a| 
data-core、data-nvme-tcp
 a| 
nvme-tcp
 a| 
NVMe/TCPデータトラフィックを伝送するLIFによって使用されます。

|===
次の表は、ONTAP 9.11.1以降、データSVMで使用できるサービスと、各サービスがLIFのフェイルオーバーポリシーに課す制限を示しています：

[cols="25,25,50"]
|===


| サービス | フェイルオーバーの制限 | 概要 


 a| 
管理-ssh
 a| 
-
 a| 
SSH管理アクセス用のサービス



 a| 
管理-http
 a| 
-
 a| 
ONTAP 9.10.1で導入されたHTTP管理アクセス用サービス



 a| 
管理-https
 a| 
-
 a| 
HTTPS管理アクセス用のサービス



 a| 
管理-portmap
 a| 
-
 a| 
portmap管理アクセス用のサービス



 a| 
管理-SNMP-サーバ
 a| 
-
 a| 
ONTAP 9.10.1で導入されたSNMPサーバ管理アクセス用のサービス



 a| 
data-core
 a| 
-
 a| 
コアデータサービス



 a| 
data-nfs
 a| 
-
 a| 
NFSデータサービス



 a| 
data-cifs
 a| 
-
 a| 
CIFSデータサービス



 a| 
data-flexcache
 a| 
-
 a| 
FlexCacheデータサービス



 a| 
データiSCSI
 a| 
AFF/FASの場合はhome-port-only、ASAの場合はsfo-partner-only
 a| 
iSCSIデータサービス



 a| 
バックアップ NDMP コントロール
 a| 
-
 a| 
ONTAP 9.10.1で導入 バックアップNDMPによるデータサービスの制御



 a| 
data-DNSサーバ
 a| 
-
 a| 
ONTAP 9.10.1で導入されたDNSサーバデータサービス



 a| 
data-fpolicyクライアント
 a| 
-
 a| 
ファイルスクリーニングポリシーデータサービス



 a| 
data-nvme-tcp
 a| 
母港のみ
 a| 
ONTAP 9.10.1で導入されたNVMe TCPデータサービス



 a| 
data-s3-server
 a| 
-
 a| 
Simple Storage Service（S3）サーバデータサービス

|===
データSVMのLIFに対するサービス ポリシーの割り当てについて、次の点に注意してください。

* データ サービスのリストを指定してデータSVMを作成した場合、そのSVMでは、指定したサービスを使用して組み込みの「default-data-files」サービス ポリシーと「default-data-blocks」サービス ポリシーが作成されます。
* データ サービスのリストを指定せずにデータSVMを作成した場合、そのSVMでは、デフォルトのデータ サービスのリストを使用して組み込みの「default-data-files」サービス ポリシーと「default-data-blocks」サービス ポリシーが作成されます。
+
デフォルトのデータ サービスのリストには、iSCSI、NFS、NVMe、SMB、FlexCacheの各サービスが含まれます。

* データ プロトコルのリストを指定してLIFを作成した場合、指定したデータ プロトコルと同等のサービス ポリシーがLIFに割り当てられます。
* 同等のサービス ポリシーが存在しない場合は、カスタム サービス ポリシーが作成されます。
* サービス ポリシーまたはデータ プロトコルのリストを指定せずにLIFを作成した場合、デフォルトでdefault-data-filesサービス ポリシーがLIFに割り当てられます。




== data-coreサービス

data-coreサービスは、LIFのロール（ONTAP 9.6で廃止）ではなくサービス ポリシーを使用してLIFを管理するようにアップグレードされたクラスタで、これまでdataロールのLIFを使用していたコンポーネントが想定どおりに機能するようにします。

data-coreをサービスとして指定してもファイアウォールのポートは開きませんが、データSVMのすべてのサービス ポリシーにこのサービスを含める必要があります。たとえば、default-data-filesサービス ポリシーには、デフォルトで次のサービスが含まれます。

* data-core
* data-nfs
* data-cifs
* data-flexcache


data-coreサービスはLIFを使用するすべてのアプリケーションが想定どおりに機能するために必要ですが、他の3つのサービスは不要であれば削除できます。



== クライアント側のLIFサービス

ONTAP 9.10.1以降では、複数のアプリケーションに対してクライアント側のLIFサービスが提供されます。これらのサービスは、各アプリケーションに代わって、アウトバウンド接続に使用するLIFを制御します。

管理者は、次の新しいサービスを使用して、特定のアプリケーションのソース アドレスとして使用するLIFを制御できます。

[cols="25,25,50"]
|===


| サービス | SVMの制限 | 概要 


 a| 
管理ADクライアント
 a| 
-
 a| 
ONTAP 9.11.1以降、ONTAPは外部ADサーバへのアウトバウンド接続用にActive Directoryクライアントサービスを提供します。



| management-dns-client  a| 
-
 a| 
ONTAP 9.11.1 以降、ONTAP は外部 DNS サーバへのアウトバウンド接続用の DNS クライアントサービスを提供します。



| management-ldap-client  a| 
-
 a| 
ONTAP 9.11.1以降、ONTAPは外部LDAPサーバへのアウトバウンド接続用のLDAPクライアントサービスを提供します。



| management-nis-client  a| 
-
 a| 
ONTAP 9.11.1 以降、ONTAPは外部NISサーバへのアウトバウンド接続用のNISクライアントサービスを提供します。



 a| 
管理-NTPクライアント
 a| 
システムのみ
 a| 
ONTAP 9.10.1 以降、ONTAP は外部 NTP サーバへのアウトバウンド接続用の NTP クライアント サービスを提供します。



 a| 
data-fpolicyクライアント
 a| 
data-only
 a| 
ONTAP 9.8以降、ONTAPはアウトバウンドFPolicy接続用のクライアントサービスを提供します。

|===
新しいサービスは一部の組み込みサービス ポリシーに自動的に含まれていますが、管理者はこれらのサービスを組み込みのポリシーから削除できます。またはカスタムのポリシーに追加して、各アプリケーションに代わってアウトバウンド接続に使用するLIFを制御することもできます。

.関連情報
* link:https://docs.netapp.com/us-en/ontap-cli/network-interface-service-policy-show.html["network interface service-policy show"^]

