---
sidebar: sidebar 
permalink: networking/modify_a_lif.html 
keywords: lif attributes, fc lifs, ip lifs, change lifs, change, changing, logical, interface, lif, modify a lif, modify a lif by changing its attributes 
summary: LIF の属性を変更して LIF を変更する 
---
= LIF を変更する
:hardbreaks:
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
LIF の属性は変更することができます。これには、ホームノードや現在のノード、管理ステータス、 IP アドレス、ネットマスク、フェイルオーバーポリシー、 ファイアウォールポリシー、およびサービスポリシーLIF のアドレスファミリーを IPv4 から IPv6 に変更することもできます。

.このタスクについて
* LIF の管理ステータスを down に変更すると、再び up に戻るまで、現行の NFSv4 ロックが維持されたままになります。
+
ロックされたファイルに他の LIF がアクセスしようとしたときにロックの競合が発生するのを防ぐには、 LIF の管理ステータスを down に設定する前に、 NFSv4 クライアントを別の LIF に移動する必要があります。

* FC LIF で使用されるデータプロトコルは変更できません。ただし、サービスポリシーに割り当てられているサービスを変更したり、 IP LIF に割り当てられているサービスポリシーを変更したりすることはできます。
+
FC LIF で使用されるデータプロトコルを変更するには、 LIF を削除して作成し直す必要があります。IP LIF にサービスポリシーを変更するには、更新が短時間停止します。

* ノードを対象とした管理 LIF のホームノードや現在のノードを変更することはできません。
* LIF の IP アドレスとネットワークマスク値を変更するためにサブネットを使用すると、指定したサブネットから IP アドレスが割り当てられます。 LIF の以前の IP アドレスが別のサブネットから割り当てられた場合は、そのサブネットに IP アドレスが返されます。
* LIF のアドレスファミリーを IPv4 から IPv6 に変更するには、 IPv6 アドレスのコロン表記を使用し、 -netmask-length パラメータの新しい値を追加する必要があります。
* 自動構成されたリンクローカル IPv6 アドレスは変更できません。
* LIF の変更によって、 LIF に有効なフェイルオーバーターゲットがなくなる場合は警告メッセージが表示されます。
+
有効なフェイルオーバーターゲットのない LIF がフェイルオーバーしようとすると、システムが停止する可能性があります。

* ONTAP 9.5 以降では、 LIF に関連付けられているサービスポリシーを変更できます。
+
ONTAP 9.5 では、クラスタ間および BGP ピアのサービスについてのみサービスポリシーがサポートされます。ONTAP 9.6 では、複数のデータサービスおよび管理サービスに対してサービスポリシーを作成できます。



.手順
. 「 network interface modify 」コマンドを使用して、 LIF の属性を変更します。
+
次の例は、 datalif2 という LIF の IP アドレスとネットワークマスクを、サブネット client1_sub の IP アドレスとネットワークマスク値に変更する例を示しています。

+
....
network interface modify -vserver vs1 -lif datalif2 -subnet-name client1_sub
....
+
次の例は、 LIF のサービスポリシーを変更する方法を示しています。

+
....
network interface modify -vserver siteA -lif node1_inter1 -service-policy example
....
. IP アドレスに到達できることを確認します。
+
[cols="2*"]
|===
| 使用するツール | 使用する方法 


 a| 
IPv4 アドレス
 a| 
「ネットワーク ping 」



 a| 
IPv6 アドレス
 a| 
「 network ping6 」

|===

