---
sidebar: sidebar 
permalink: networking/modify_mtu_setting_for_interface_group_ports.html 
keywords: modify, modifying, change, changing, mtu, modify mtu setting for interface group ports, modify the mtu of the broadcast domain 
summary: ブロードキャストドメインの MTU を変更します 
---
= ONTAPインターフェイスグループポートのMTU設定を変更します。
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
インターフェイスグループのMTUの設定を変更するには、ブロードキャストドメインのMTUを変更する必要があります。

VLANのMTUサイズは、基盤となるインターフェイスグループおよび物理ポートのブロードキャストドメインMTUと同じである必要があります。VLANに別のVLAN設定が必要な場合は、基になるブロードキャストドメインで指定されたサイズを超えないようにする必要があります。

.手順
. ブロードキャストドメインの設定を変更します。
+
`broadcast-domain modify -broadcast-domain _broadcast_domain_name_ -mtu _mtu_setting_`

+
次の警告メッセージが表示されます。

+
....
Warning: Changing broadcast domain settings will cause a momentary data-serving interruption.
Do you want to continue? {y|n}: y
....
. 「y」と入力して続行します。
. MTU設定が正しく変更されたことを確認します。
+
`network port show`



....
network port show
(network port show)
Node: vsim-01
                                                              Ignore
                                         Speed(Mbps) Health   Health
Port IPspace Broadcast Domain  Link  MTU Admin/Oper  Status   Status
---- ------- ----------------  ---- ---- ----------- -------- ------
a0a  Default Default-1         up   1300 auto/1000   healthy  false
e0a  Default Default-1         up   1300 auto/1000   healthy  false
e0b  Default Default           up   1500 auto/1000   healthy  false
e0c  Default Default           up   1500 auto/1000   healthy  false
e0d  Default Default           up   1500 auto/1000   healthy  false
5 entries were displayed.
....