---
sidebar: sidebar 
permalink: networking/modify_qos_marking_values.html 
keywords: change, changing, modify, modifying, qos, quality, service, marking, performance, modify qos marking values, change the qos marking values for different protocols, network qos-marking modify 
summary: 異なるプロトコルのQoSマーキング値を変更する 
---
= ONTAPネットワークQoSマーキング値を変更する
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
それぞれのIPspaceについて、さまざまなプロトコルのサービス品質（QoS）マーキング値を変更できます。

.開始する前に
クラスタ内のすべてのノードで同じバージョンのONTAPが実行されている必要があります。

.手順
 `network qos-marking modify`コマンドを使用してQoSマーキング値を変更します。

*  `–ipspace`パラメータは、QoS マーキングエントリを変更する IPspace を指定します。
*  `–protocol`パラメータは、QoS マーキングエントリを変更するプロトコルを指定します。
* この `–dscp`パラメータは、Differentiated Services Code Point（DSCP）値を指定します。指定可能な値の範囲は0~63です。
*  `-is-enabled`パラメータは、 `–ipspace`パラメータによって提供されるIPspace内の指定されたプロトコルのQoSマーキングを有効または無効にするために使用されます。


次のコマンドは、デフォルトIPspaceのNFSプロトコルのQoSマーキングを有効にします。

....
network qos-marking modify -ipspace Default -protocol NFS -is-enabled true
....
次のコマンドは、デフォルトIPspaceのNFSプロトコルのDSCP値を20に設定します。

....
network qos-marking modify -ipspace Default -protocol NFS -dscp 20
....
 `network qos-marking modify`とプロトコルの可能な値の詳細については、link:https://docs.netapp.com/us-en/ontap-cli/network-qos-marking-modify.html["ONTAPコマンド リファレンス"^]を参照してください。
