---
sidebar: sidebar 
permalink: networking/recover_from_an_incorrectly_configured_cluster_lif.html 
keywords: misconfigured, misconfigurations, incorrect, incorrectly, switch, switches, switched, cable, physical, wiring, wired, reachability, port, cluster, ontap 9.8 and later, recover from an incorrectly configured cluster lif, how to identify and correct a cluster that has been misconfigured, cluster create, network port, reachability show -detail, reset the home port 
summary: 誤って設定されたクラスタを特定して修正する方法 
---
= 正しく設定されていないONTAP LIFをリカバリする
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
クラスタネットワークがスイッチにケーブル接続されているが、Cluster IPspaceに設定されているすべてのポートがCluster IPspaceに設定されている他のポートに到達できない場合、クラスタを作成できません。

.タスクの内容
スイッチクラスタで、クラスタネットワークインターフェイス（LIF）が間違ったポートに設定されている場合、またはクラスタポートが間違ったネットワークに接続されている場合、 `cluster create`コマンドが次のエラーで失敗することがあります。

....
Not all local cluster ports have reachability to one another.
Use the "network port reachability show -detail" command for more details.
....
の詳細については `cluster create`、をlink:https://docs.netapp.com/us-en/ontap-cli/cluster-create.html["ONTAPコマンド リファレンス"^]参照してください。

コマンドの結果では `network port show`、クラスタLIFが設定されたポートに接続されているために、複数のポートがクラスタIPspaceに追加されたと表示されることがあります。しかし、  `network port reachability show -detail`コマンドは、どのポートが相互に接続されていないかを明らかにします。

の詳細については `network port show`、をlink:https://docs.netapp.com/us-en/ontap-cli/network-port-show.html["ONTAPコマンド リファレンス"^]参照してください。

クラスタLIFが設定されている他のポートに到達できないポートに設定されたクラスタLIFをリカバリするには、次の手順を実行します。

.手順
. クラスタLIFのホームポートを正しいポートにリセットします。
+
....
network port modify -home-port
....
+
の詳細については `network port modify`、をlink:https://docs.netapp.com/us-en/ontap-cli/network-port-modify.html["ONTAPコマンド リファレンス"^]参照してください。

. クラスタLIFが設定されていないポートをクラスタブロードキャストドメインから削除します。
+
....
network port broadcast-domain remove-ports
....
+
の詳細については `network port broadcast-domain remove-ports`、をlink:https://docs.netapp.com/us-en/ontap-cli/network-port-broadcast-domain-remove-ports.html["ONTAPコマンド リファレンス"^]参照してください。

. クラスタを作成します。
+
....
cluster create
....


.結果
クラスタの作成が完了すると、正しい設定が検出され、正しいブロードキャストドメインにポートが配置されます。

.関連情報
* link:https://docs.netapp.com/us-en/ontap-cli/network-port-reachability-show.html["network port reachability showの場合"^]

