---
sidebar: sidebar 
permalink: networking/recover_from_an_incorrectly_configured_cluster_lif.html 
keywords: misconfigured, misconfigurations, incorrect, incorrectly, switch, switches, switched, cable, physical, wiring, wired, reachability, port, cluster, ontap 9.8 and later, recover from an incorrectly configured cluster lif, how to identify and correct a cluster that has been misconfigured, cluster create, network port, reachability show -detail, reset the home port 
summary: 誤って設定されたクラスタを特定して修正する方法 
---
= ONTAP 9.8 以降：正しく設定されていないクラスタ LIF からリカバリします
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
クラスタネットワークがスイッチにケーブル接続されているが、クラスタ IPspace に設定されたすべてのポートがクラスタ IPspace に設定された他のポートに到達できない場合は、クラスタを作成できません。

.このタスクについて
スイッチクラスタで、クラスタネットワークインターフェイス（LIF）が間違ったポートに設定されている場合、またはクラスタポートが間違ったネットワークに接続されている場合は、が表示されます `cluster create` 次のエラーが表示されてコマンドが失敗することがあります。

....
Not all local cluster ports have reachability to one another.
Use the "network port reachability show -detail" command for more details.
....
の結果 `network port show` コマンドでは、クラスタLIFが設定されたポートに接続されているために、複数のポートがクラスタIPspaceに追加されたと表示されることがあります。ただし、の結果 `network port` `reachability show -detail` コマンドは、相互に接続されていないポートを表示します。

クラスタ LIF が設定された他のポートに到達できないポート上に設定されたクラスタ LIF をリカバリするには、次の手順を実行します。

.手順
. クラスタ LIF のホームポートを正しいポートにリセットします。
+
....
network port modify -home-port
....
. クラスタ LIF が設定されていないポートをクラスタブロードキャストドメインから削除します。
+
....
network port broadcast-domain remove-ports
....
. クラスタを作成します。
+
....
cluster create
....


.結果
クラスタの作成が完了すると、正しい設定が検出され、正しいブロードキャストドメインにポートが配置されます。
