---
sidebar: sidebar 
permalink: networking/snmp_traps.html 
keywords: snmp, trap, traphosts, asynchronous, notification, notify, alert, message, thresholds, failures, errors, fail, rfc 1215, built in, built-in, standard, snmp traps, use snmp traps to periodically check for operational thresholds or failures, standard snmp traps, system snmp authtrap, rfc 1215, coldstart, warmstart, linkdown, linkup, authenticationfailure, built-in snmp traps, traphost, diskfailedshutdown, cputoobusy, and volumenearlyfull 
summary: SNMP トラップを使用して、動作しきい値または障害を定期的にチェックします 
---
= SNMP トラップ
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
SNMP トラップは、 SNMP エージェントから SNMP マネージャに非同期通知として送信されたシステム監視情報をキャプチャします。

SNMP トラップには、標準、ビルトイン、およびユーザ定義の 3 種類があります。ユーザ定義トラップは、 ONTAP ではサポートされていません。

トラップを使用して、 MIB に定義された運用上のしきい値または障害を定期的にチェックすることができます。しきい値に到達するか、障害が検出されると、 SNMP エージェントは、イベントを警告するメッセージ（トラップ）をトラップホストに送信します。


NOTE: ONTAP は、 SNMPv1 トラップ、および ONTAP 9.1 以降の SNMPv3 トラップをサポートしています。ONTAP は、 SNMPv2c トラップおよび INFORM をサポートしていません。



== 標準 SNMP トラップ

これらのトラップは RFC 1215 で定義されています。ONTAP でサポートされている SNMP トラップは、 coldStart 、 warmStart 、 linkDown 、 linkUp 、および authenticationFailure の 5 つです。


NOTE: authenticationFailure トラップは、デフォルトで無効になっています。を使用する必要があります `system snmp authtrap` トラップをイネーブルにするコマンド。詳細については、次のマニュアルページを参照してください。 http://["ONTAP 9 のコマンド"^]



== 組み込みの SNMP トラップ

ビルトイントラップは ONTAP に事前定義されたトラップで、イベントの発生時にトラップホストリストのネットワーク管理ステーションに自動的に送信されます。diskFailedShutdown 、 cpuTooBusy 、 volumeNearlyFull など、これらのトラップはカスタム MIB で定義されています。

各ビルトイントラップは、一意のトラップコードで識別されます。
