---
sidebar: sidebar 
permalink: networking/use_lldp_to_detect_network_connectivity.html 
keywords: display, view, show, network, connectivity, neighbor, discovery, protocol, ndp, link, layer, lldp, use lldp to detect network connectivity, enable or disable lldp, view lldp neighbor information, adjust the interval for transmitting lldp advertisements 
summary: LLDPを使用したネットワーク接続の検出は、導入に関する考慮事項の確認、すべてのポートでのLLDPの有効化、近隣デバイスの表示、LLDPの設定値の調整（必要な場合）で構成されます。 
---
= LLDPを使用してONTAPネットワーク接続を検出する
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
LLDPを使用したネットワーク接続の検出は、導入に関する考慮事項の確認、すべてのポートでのLLDPの有効化、近隣デバイスの表示、LLDPの設定値の調整（必要な場合）で構成されます。

近隣デバイスに関する情報を表示するには、スイッチとルーターでもLLDPを有効にする必要があります。

現時点では、ONTAPは次のType-Length-Value構造（TLV）を報告します。

* シャーシID
* ポートID
* Time-To-Live（TTL）
* システム名
+
システム名TLVは、CNAデバイスでは送信されません。



X1143アダプタやUTA2オンボード ポートなどの特定の統合ネットワーク アダプタ（CNA）にはLLDPのオフロード サポートが含まれています。

* LLDPのオフロードは、Data Center Bridging（DCB）に使用されます。
* 表示される情報がクラスタとスイッチの間で異なる場合があります。
+
スイッチで表示されるシャーシIDとポートIDのデータは、CNAポートとCNA以外のポートで異なる場合があります。



例：

* CNA以外のポート：
+
** シャーシIDは、ノードのいずれかのポートの固定MACアドレスです。
** ポートIDは、ノードの対応するポートのポート名です。


* CNAポート：
+
** シャーシIDとポートIDは、ノードの対応するポートのMACアドレスです。




ただし、クラスタではこれらのポート タイプについて同じデータが表示されます。


NOTE: LLDPの仕様では、SNMP MIBによる、収集された情報へのアクセスを定義します。ただし、現時点では、ONTAPはLLDP MIBをサポートしていません。



== LLDPの有効化または無効化

LLDP対応の近隣デバイスを検出して通知を送信するには、クラスタの各ノードでLLDPが有効になっている必要があります。ONTAP 9.7以降では、ノードのすべてのポートでLLDPがデフォルトで有効になります。

.タスク概要
ONTAP 9.10.1 以前では、この `lldp.enable`オプションはノードのポート上で LLDP を有効にするか無効にするかを制御します：

* `on` すべてのポートで LLDP を有効にします。
* `off` すべてのポートで LLDP を無効にします。


ONTAP 9.11.1 以降では、 `lldp.enable`オプションは、ノードの非クラスタポートおよび非ストレージポートで LLDP を有効にするか無効にするかを制御します：

* `on`すべての非クラスタポートおよび非ストレージポートで LLDP を有効にします。
* `off`すべての非クラスタポートおよび非ストレージポートで LLDP を無効にします。


.手順
. クラスタ内の1つまたはすべてのノードの、現在のLLDP設定を表示します。
+
** 単一ノード： `run -node node_name options lldp.enable`
** すべてのノード：オプション `lldp.enable`


. クラスタ内の1つまたはすべてのノードで、すべてのポートのLLDPを有効または無効に設定します。
+
[cols="30,70"]
|===


| LLDPを有効または無効にする対象 | 入力する内容 


 a| 
1つのノード
 a| 
`run -node node_name options lldp.enable {on|off}`



 a| 
クラスタ内のすべてのノード
 a| 
`options lldp.enable {on|off}`

|===
+
** 1つのノード：
+
....
run -node node_name options lldp.enable {on|off}
....
** すべてのノード：
+
....
options lldp.enable {on|off}
....






== LLDP近隣情報の表示

クラスタのノードのポートにLLDP対応デバイスが接続されている場合は、そのポートの近隣デバイスの情報を表示することができます。近隣情報を表示するには、network device-discovery showコマンドを使用します。

.手順
. クラスタ内のノードのポートに接続されているすべてのLLDP対応デバイスの情報を表示します。
+
....
network device-discovery show -node node -protocol lldp
....
+
次のコマンドは、ノード cluster-1_01 のポートに接続されているネイバーを表示します。出力には、指定されたノードの各ポートに接続されている LLDP 対応デバイスがリストされます。 `-protocol`オプションを省略すると、CDP 対応デバイスも出力されます。

+
....
network device-discovery show -node cluster-1_01 -protocol lldp
Node/       Local  Discovered
Protocol    Port   Device                    Interface         Platform
----------- ------ ------------------------- ----------------  ----------------
cluster-1_01/lldp
            e2a    0013.c31e.5c60            GigabitEthernet1/36
            e2b    0013.c31e.5c60            GigabitEthernet1/35
            e2c    0013.c31e.5c60            GigabitEthernet1/34
            e2d    0013.c31e.5c60            GigabitEthernet1/33
....




== LLDP通知の送信間隔の調整

LLDP通知は、一定の間隔でLLDP近隣機器に送信されます。ネットワーク トラフィックの量やネットワーク トポロジの変化に応じて、LLDP通知の送信間隔を調整することができます。

.タスク概要
IEEEが推奨するデフォルトの送信間隔は30秒ですが、5～300秒の値を入力できます。

.手順
. クラスタ内の1つまたはすべてのノードについて、LLDP通知の現在の送信間隔を表示します。
+
** 1つのノード：
+
....
run -node <node_name> options lldp.xmit.interval
....
** すべてのノード：
+
....
options lldp.xmit.interval
....


. クラスタ内の1つまたはすべてのノードで、すべてのポートのLLDP通知の送信間隔を調整します。
+
** 1つのノード：
+
....
run -node <node_name> options lldp.xmit.interval <interval>
....
** すべてのノード：
+
....
options lldp.xmit.interval <interval>
....






== LLDP通知のTime-To-Live値の調整

Time-To-Live（TTL）とは、LLDP通知がLLDP対応の近隣デバイスのキャッシュに格納される時間です。TTLは各LLDPパケットで通知され、ノードがLLDPパケットを受信するたびに更新されます。発信LLDPフレームでTTLを変更できます。

.タスク概要
* TTL は、送信間隔(`lldp.xmit.interval`とホールド乗数(`lldp.xmit.hold`の積に 1 を加えた計算値です。
* デフォルトの保持の乗数値は4ですが、1～100の値を入力できます。
* IEEEが推奨するデフォルトのTTLは121秒ですが、送信間隔と保持の乗数の値を調整することにより、発信フレームの値を6～30001秒に指定できます。
* TTLが期限切れになる前にIPアドレスが削除された場合、LLDP情報はTTLが期限切れになるまでキャッシュされます。


.手順
. クラスタ内の1つまたはすべてのノードの現在の保持の乗数値を表示します。
+
** 1つのノード：
+
....
run -node <node_name> options lldp.xmit.hold
....
** すべてのノード：
+
....
options lldp.xmit.hold
....


. クラスタ内の1つまたはすべてのノードで、すべてのポートの保持の乗数値を調整します。
+
** 1つのノード：
+
....
run -node <node_name> options lldp.xmit.hold <hold_value>
....
** すべてのノード：
+
....
options lldp.xmit.hold <hold_value>
....






== LLDP統計情報の表示と消去

ネットワーク接続で発生する可能性のある問題を見つけるために、各ノードのクラスタ ポートと非クラスタ ポートのLLDP統計情報を確認できます。LLDP統計情報は、前回消去されたときからの累積値です。

.タスク概要
ONTAP 9.10.1以前の場合、クラスタ ポートではLLDPが常に有効になっているので、これらのポートのトラフィックに関するLLDP統計情報は常に表示されます。非クラスタ ポートのLLDP統計情報を表示するには、これらのポートでCDPを有効にする必要があります。

ONTAP 9.11.1以降の場合、クラスタ ポートとストレージ ポートではLLDPが常に有効になっているので、これらのポートのトラフィックに関するLLDP統計情報は常に表示されます。非クラスタ ポートと非ストレージ ポートのLLDP統計情報を表示するには、これらのポートでLLDPを有効にする必要があります。

.手順
ノードのすべてのポートに関する現在のLLDP統計情報を表示、または消去します。

[cols="40,60"]
|===


| 状況 | 入力する内容 


 a| 
LLDP統計情報を表示
 a| 
`run -node node_name lldp stats`



 a| 
LLDP統計情報を消去
 a| 
`run -node node_name lldp stats -z`

|===


=== 統計情報の表示と消去の例

次のコマンドは、消去する前のLLDP統計情報の例を示します。前回統計情報が消去されてから、送信および受信したパケットの総数が出力されています。

....
cluster-1::> run -node vsim1 lldp stats

RECEIVE
 Total frames:     190k  | Accepted frames:   190k | Total drops:         0
TRANSMIT
 Total frames:     5195  | Total failures:      0
OTHER
 Stored entries:      64
....
次のコマンドは、LLDP統計情報を消去します。

....
cluster-1::> The following command clears the LLDP statistics:
run -node vsim1 lldp stats -z
run -node node1 lldp stats

RECEIVE
 Total frames:        0  | Accepted frames:     0  | Total drops:         0
TRANSMIT
 Total frames:        0  | Total failures:      0
OTHER
 Stored entries:      64
....
統計情報を消去すると、次にLLDP通知が送信または受信された時点から情報が累積されていきます。
