---
permalink: concepts/client-protocols-concept.html 
sidebar: sidebar 
keywords: client protocols 
summary: ONTAPは、NFS、SMB、FC、FCoE、iSCSI、NVMe、S3など、業界標準の主要なクライアント プロトコルをすべてサポートしています。 
---
= クライアント プロトコル
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
ONTAPは、NFS、SMB、FC、FCoE、iSCSI、NVMe、S3など、業界標準の主要なクライアント プロトコルをすべてサポートしています。



== NFS

NFSは、UNIXおよびLinuxシステム向けの従来のファイル アクセス プロトコルです。クライアントは、次のプロトコルを使用してONTAPボリューム内のファイルにアクセスできます。

* NFSv3
* NFSv4
* NFSv4.2
* NFSv4.1
* pNFS


ファイル アクセスは、UNIX形式の権限、NTFS形式の権限、またはその両方の組み合わせを使用して制御できます。

クライアントは、同じファイルにNFSプロトコルとSMBプロトコルの両方を使用してアクセスできます。



== SMB

SMBは、Windowsシステム向けの従来のファイル アクセス プロトコルです。クライアントは、SMB 2.0、SMB 2.1、SMB 3.0、およびSMB 3.1.1の各プロトコルを使用してONTAPボリューム内のファイルにアクセスできます。NFSと同様に、複数の形式の権限の組み合わせがサポートされています。

SMB 1.0も使用可能ですが、ONTAP 9.3以降のリリースではデフォルトで無効になっています。



== FC

Fibre Channelは、ネットワークを使用した最初のブロック プロトコルです。ブロック プロトコルは、ファイルではなく、仮想ディスク全体をクライアントに提供します。従来のFCプロトコルは専用のFCネットワークとFCスイッチを使用し、クライアント コンピュータにFCネットワーク インターフェイスが必要です。

仮想ディスクはLUNとして表され、1つ以上のLUNがONTAPボリュームに格納されます。FC、FCoE、およびiSCSIの各プロトコルを使用して同じLUNにアクセスできますが、複数のクライアントから同じLUNにアクセスできるのは、クライアントが書き込みの競合を防ぐように設定されたクラスタに属している場合だけです。



== FCoE

FCoEは、FCプロトコルと基本的に同じですが、従来のFC転送の代わりにデータセンター クラスのイーサネット ネットワークを使用します。クライアントにはFCoE固有のネットワーク インターフェイスが必要です。



== iSCSI

iSCSIは、標準のイーサネット ネットワークで実行できるブロック プロトコルです。ほとんどのクライアント オペレーティング システムには、標準のイーサネット ポートで動作するソフトウェア イニシエータが搭載されています。iSCSIは、特定のアプリケーションにブロック プロトコルが必要な状況で、専用のFCネットワークがない場合に適しています。



== NVMe / FCとNVMe / TCP

NVMeは、フラッシュベースのストレージと連携するように設計された最も新しいブロック プロトコルです。スケーラブルなセッションを通じてレイテンシの大幅な低減と並列処理機能の強化を実現できるため、インメモリ データベースや分析など、低レイテンシと高スループットが求められるアプリケーションに適しています。

FCやiSCSIとは異なり、NVMeはLUNを使用しません。代わりに、ONTAPボリュームに格納されるネームスペースを使用します。NVMeネームスペースには、NVMeプロトコルでのみアクセスできます。



== S3

ONTAP 9.8以降では、ONTAPクラスタでONTAP Simple Storage Service（S3）サーバを有効にすることで、オブジェクト ストレージのデータをS3バケットを使用して提供できます。

ONTAPでは、S3オブジェクト ストレージを提供するオンプレミスのユースケース シナリオを2つサポートしています。

* FabricPoolによるローカル クラスタ（ローカル バケット階層）またはリモート クラスタ（クラウド階層）のバケットへの階層化。
* S3クライアント アプリケーションによるローカル クラスタまたはリモート クラスタのバケットへのアクセス。


[NOTE]
====
ONTAP S3は、追加のハードウェアや管理なしに既存のクラスタでS3機能を利用したい場合に最適です。300TBを超える環境では、NetApp StorageGRIDソフトウェアがNetAppのオブジェクト ストレージの主力ソリューションであり続けています。 https://docs.netapp.com/us-en/storagegrid-family/["StorageGRID"^]の詳細をご覧ください。

====