---
permalink: concepts/cloud-backup-support-traditional-backups-concept.html 
sidebar: sidebar 
keywords: cloud backup, support, traditional backups 
summary: ONTAP 9 .7以前でのみディスクツーディスクであったSnapMirrorおよびSnapVaultのデータ保護関係に加えて、より低コストで長期的なデータ保持を実現できるバックアップソリューションがいくつか登場しました。 
---
= クラウドバックアップと従来のバックアップのサポート
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
ONTAP 9 .7以前でのみディスクツーディスクであったSnapMirrorおよびSnapVaultのデータ保護関係に加えて、より低コストで長期的なデータ保持を実現できるバックアップソリューションがいくつか登場しました。

多くのサードパーティ製データ保護アプリケーションが、ONTAPで管理されるデータに対して従来のバックアップを提供しています。Veeam、Veritas、Commvaultなどが、ONTAPシステム向けの統合バックアップ機能を提供しています。

ONTAP 9.8以降では、SnapMirror Cloudで、ONTAPインスタンスからオブジェクトストレージエンドポイントへのSnapshotの非同期レプリケーションを実行できます。SnapMirrorのクラウドレプリケーションには、データ保護ワークフローのオーケストレーションと管理を行うための、ライセンスが必要です。SnapMirrorのクラウド関係は、ONTAPシステムからオンプレミスとパブリッククラウドのオブジェクトストレージターゲット（AWS S3、Google Cloud Storage Platform、Microsoft Azure Blob Storageなど）への移行がサポートされ、ベンダーのバックアップソフトウェアで効率性が向上します。サポートされる認定アプリケーションやオブジェクトストレージベンダーの一覧については、NetAppの担当者にお問い合わせください。

クラウドネイティブのデータ保護に関心がある場合は、 NetAppコンソールを使用して、オンプレミスのボリュームとパブリック クラウドのCloud Volumes ONTAPインスタンス間のSnapMirrorまたはSnapVault関係を構成できます。

コンソールは、Software as a Service (SaaS) モデルを使用してCloud Volumes ONTAPインスタンスのバックアップも提供します。ユーザーは、 NetApp Backup and Recovery を使用して、 Cloud Volumes ONTAPインスタンスを S3 および S3 準拠のパブリック クラウド オブジェクト ストレージにバックアップできます。

link:https://docs.netapp.com/us-en/storage-management-cloud-volumes-ontap/index.html["Cloud Volumes ONTAP のドキュメント"^]

link:https://docs.netapp.com/us-en/console-family/index.html["NetAppコンソールのドキュメント"^]

link:https://console.netapp.com/["NetAppコンソール"^]
