---
permalink: concepts/introducing-ontap-interfaces-concept.html 
sidebar: sidebar 
keywords: ontap interfaces, interfaces, system manager, bluexp, cli, rest api, ontapi 
summary: ONTAPデータ管理ソフトウェアには、ONTAPで保護されたデータの管理に使用できるさまざまなインターフェイスが用意されています。 
---
= ONTAPユーザインターフェイス
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
ONTAPデータ管理ソフトウェアには、ONTAPクラスタの管理に使用できる複数のインターフェイスが用意されています。これらのインターフェイスオプションを使用すると、さまざまなレベルのアクセスや機能を提供し、環境に応じてONTAPクラスタを柔軟に管理できます。

これらのインターフェイスのいずれかを使用して、ONTAPクラスタの管理やデータ管理処理を実行できます。



== ONTAP システムマネージャ

ONTAP System Managerは、Webベースのユーザインターフェイスで、シンプルでわかりやすい方法でクラスタを管理します。ストレージ構成、データ保護、ネットワークのセットアップと管理などの一般的な操作を管理できます。System Managerでは、リスクとクラスタのパフォーマンスを監視し、クラスタの問題に対処して問題を未然に先回りするのに役立つ分析情報も提供されます。 link:../concept_administration_overview.html["詳細はこちら。"]。

ONTAP 9.7では、ONTAPのSystem Managerインターフェイスが再設計され、より合理的でわかりやすいユーザエクスペリエンスが提供されました。このドキュメントサイトの手順では、再設計されたSystem Managerインターフェイスについて説明しています。これらのインターフェイスには、ONTAPリリースごとにさらに多くのオプションが用意されています。


NOTE: ONTAPのドキュメントでは、System Managerの古いインターフェイスを「System Managerクラシック」と呼んでいます。System Managerのクラシックインターフェイスを使用できる最後のONTAPリリースはONTAP 9.7です。



== BlueXP

ONTAP 9.12.1以降では、BlueXPのWebベースのインターフェイスを使用して、使い慣れたSystem Managerダッシュボードを使用しながら、単一のコントロールプレーンからハイブリッドマルチクラウドインフラを管理できます。BlueXPでは、クラウドストレージ（Cloud Volumes ONTAPなど）の作成と管理、ネットアップのデータサービス（Cloud Backupなど）の使用、多くのオンプレミスストレージデバイスやエッジストレージデバイスの制御を行うことができます。オンプレミスのONTAPシステムをBlueXPに追加すると、すべてのストレージとデータ資産を単一のインターフェイスから管理できます。 https://docs.netapp.com/us-en/bluexp-family/["詳細はこちら。"^]。



== ONTAP コマンドラインインターフェイス

。 link:../system-admin/index.html["ONTAPコマンドラインインターフェイス（CLI）"] は、クラスタ、ノード、SVMなどを使用して操作できるテキストベースのインターフェイスです。 link:../concepts/manual-pages.html["コマンド"]。CLIコマンドは、 link:../system-admin/cluster-svm-administrators-concept.html["ロールタイプ"]。ONTAP CLIには、SSHまたはクラスタ内のノードへのコンソール接続を介してアクセスできます。



== ONTAP REST API

ONTAP 9.6以降では、プログラムを使用してクラスタ処理を管理および自動化できるRESTful APIにアクセスできます。APIを使用して、ボリューム、Snapshot、アグリゲートの作成と管理、クラスタのパフォーマンスの監視など、ONTAPのさまざまな管理タスクを実行します。ONTAP REST APIには、curlなどのユーティリティを使用するか、Python、PowerShell、Javaなど、RESTクライアントをサポートする任意のプログラミング言語を使用して直接アクセスできます。 https://docs.netapp.com/us-en/ontap-automation/get-started/ontap_automation_options.html["詳細はこちら。"^]。


NOTE: ONTAPIは、ONTAP REST APIに先行する独自のONTAP APIです。ONTAPIインターフェイスは、ONTAP の今後のバージョンでは無効になる予定です。ONTAPIを使用している場合は、 https://docs.netapp.com/us-en/ontap-automation/migrate/ontapi_disablement.html["ONTAP REST APIへの移行"^]。



== NetAppのツールキットとフレームワーク

NetAppには、ONTAP REST APIを抽象化し、自動化コードの作成を容易にする特定の開発言語および環境用のクライアントツールキットが用意されています。
https://docs.netapp.com/us-en/ontap-automation/get-started/ontap_automation_options.html#client-software-toolkits["詳細はこちら。"^]。

これらのツールキットに加えて、フレームワークを使用して自動化コードを作成および展開できます。 https://docs.netapp.com/us-en/ontap-automation/get-started/ontap_automation_options.html#automation-frameworks["詳細はこちら。"^]。
