---
permalink: concepts/rdma-concept.html 
sidebar: sidebar 
keywords: Remote Direct Memory Access, NFS over RDMA, RoCE, intercluster 
summary: ONTAPのリモート ダイレクト メモリ アクセス（RDMA）ソリューションは、レイテンシの影響を受けやすい広帯域幅のワークロードをサポートします。RDMAを使用すると、ストレージシステムメモリとホストシステムメモリの間でデータを直接コピーできるため、CPUの中断やオーバーヘッドを回避できます。 
---
= RDMAの概要
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
ONTAPのリモート ダイレクト メモリ アクセス（RDMA）ソリューションは、レイテンシの影響を受けやすい広帯域幅のワークロードをサポートします。RDMAを使用すると、ストレージ システムとホスト システムのメモリ間でデータが直接コピーされるため、CPUの中断やオーバーヘッドを回避できます。



== NFS over RDMA

ONTAP 9 .10.1以降では、サポート対象のNVIDIA GPUを搭載したホストでGPUアクセラレーションワークロードにNVIDIA GPUDirect Storageを使用できるように設定できますlink:../nfs-rdma/index.html["NFS over RDMA"]。


NOTE: RDMA は SMB プロトコルではサポートされていません。



== クラスタインターコネクトRDMA

クラスタインターコネクトRDMAは、レイテンシを低減し、フェイルオーバー時間を短縮し、クラスタ内のノード間の通信を高速化します。

X1151AクラスタNICを使用する場合、ONTAP 9 .10.1以降では、特定のハードウェアシステムでクラスタインターコネクトRDMAがサポートされます。X91153A NICでは、ONTAP 9 13.1以降でクラスタインターコネクトRDMAもサポートされます。各ONTAPリリースでサポートされるシステムについては、表を参照してください。

|===
| システム | サポートされるONTAPバージョン 


 a| 
* AFF A50用
* AFF A30用
* AFF A20用
* AFF C80用
* AFF C60用
* AFF C30用
* ASA A50
* ASA A30
* ASA A20

| ONTAP 9.16.1以降 


 a| 
* AFF A1K用
* AFF A90用
* AFF A70用
* ASA A1K
* ASA A90
* ASA A70
* FAS90
* FAS70

| ONTAP 9.15.1以降 


 a| 
* AFF A400
* ASA A400

| ONTAP 9.10.1以降 


 a| 
* AFF A900用
* ASA A900
* FAS9500

| ONTAP 9.13.1以降 
|===
ストレージシステムが適切にセットアップされていれば、クラスタインターコネクトRDMAを使用するための追加の設定は必要ありません。
