---
permalink: concepts/rdma-concept.html 
sidebar: sidebar 
keywords: Remote Direct Memory Access, NFS over RDMA, RoCE, intercluster 
summary: NFS over RDMA と RDMA クラスタインターコネクトでは、 RDMA を利用して広帯域幅ワークロードのパフォーマンスが向上します。 
---
= RDMAの概要
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
ONTAPのリモート ダイレクト メモリ アクセス（RDMA）ソリューションは、レイテンシの影響を受けやすい広帯域幅のワークロードをサポートします。RDMAを使用すると、ストレージ システムとホスト システムのメモリ間でデータが直接コピーされるため、CPUの中断やオーバーヘッドを回避できます。



== NFS over RDMA

ONTAP 9 .10.1以降では、サポート対象のNVIDIA GPUを搭載したホストでGPUアクセラレーションワークロードにNVIDIA GPUDirect Storageを使用できるように設定できますlink:../nfs-rdma/index.html["NFS over RDMA"]。



== RDMAクラスタインターコネクト

RDMAクラスタインターコネクトは、レイテンシを低減し、フェイルオーバー時間を短縮し、クラスタ内のノード間の通信を高速化します。

X1151AクラスタNICを使用する場合、ONTAP 9 .10.1以降では、特定のハードウェアシステムでクラスタインターコネクトRDMAがサポートされます。X91153A NICでは、ONTAP 9 13.1以降でクラスタインターコネクトRDMAもサポートされます。各ONTAPリリースでサポートされるシステムについては、表を参照してください。

|===
| システム | サポートされるONTAPバージョン 


 a| 
* AFF A400
* ASA A400

| ONTAP 9.10.1以降 


 a| 
* AFF A900用
* ASA A900
* FAS9500

| ONTAP 9.13.1以降 
|===
ストレージ システムが適切にセットアップされていれば、追加の設定をしなくてもRDMAインターコネクトを使用できます。
