---
permalink: concepts/storage-efficiency-overview.html 
sidebar: sidebar 
keywords: storage efficiency, storage efficiencies, storage efficiency technologies, space utilization, space savings, optimizing, space optimization, minimizing, wasted space, reducing, footprint, thin provisioning, deduplication, zero block, zero-block, inline, deduplication, background deduplication, postprocessing, post-processing, compression, compaction, flex-clone technologies 
summary: Storage Efficiencyとは、ストレージリソースを最適化し、無駄なスペースを最小限に抑え、書き込みデータの物理的なフットプリントを削減することで、ストレージシステムが使用可能なスペースをどの程度効率的に使用するかを示す指標です。 
---
= ONTAPのStorage Efficiencyの概要
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Storage Efficiencyとは、ストレージリソースを最適化し、無駄なスペースを最小限に抑え、書き込みデータの物理的なフットプリントを削減することで、ストレージシステムが使用可能なスペースをどの程度効率的に使用するかを示す指標です。Storage Efficiencyが高いほど、最大限のデータを最小限のスペースに最小限のコストで格納できます。たとえば、重複するデータブロックとゼロでいっぱいのデータブロックを検出して排除するStorage Efficiencyテクノロジを利用すると、必要な物理ストレージの総容量が削減され、全体的なコストが削減されます。

ONTAPは、さまざまなStorage Efficiencyテクノロジを提供しています。このテクノロジを使用すると、データが消費する物理ハードウェアやクラウドストレージの量を削減できます。また、データの読み取り速度、データセットのコピー速度、VMのプロビジョニング速度など、システムのパフォーマンスも大幅に向上します。

.ONTAPのStorage Efficiencyテクノロジは次のとおりです。
* * シンプロビジョニング *
+
xref:thin-provisioning-concept.html[シンプロビジョニング]ボリュームまたはLUNのストレージを事前にリザーブするのではなく、必要に応じて割り当てることができます。現在使用されていないスペースをリザーブすることなく、潜在的な使用量に基づいてボリュームまたはLUNを過剰に割り当てることができるため、必要な物理ストレージの量が削減されます。

* * 重複排除 *
+
xref:deduplication-concept.html[重複排除]ボリュームに必要な物理ストレージの量を3つの方法で削減します。

+
** *ゼロブロック重複排除*
+
ゼロブロック重複排除は、すべてゼロでいっぱいになったデータブロックを検出して排除し、メタデータのみを更新します。ゼロブロックで一般的に使用されているスペースの100%が削減されます。ゼロブロック重複排除は、すべての重複排除ボリュームでデフォルトで有効になります。

** *インライン重複排除*
+
インライン重複排除は、重複するデータブロックを検出し、データがディスクに書き込まれる前に一意の共有ブロックへの参照に置き換えます。インライン重複排除により、VMのプロビジョニングが20~30%高速化されます。インライン重複排除は、ONTAPのバージョンとプラットフォームに応じて、ボリュームレベルまたはアグリゲートレベルで実行できます。AFFシステムおよびASAシステムではデフォルトで有効になっています。FASシステムでは、インライン重複排除を手動で有効にする必要があります。

** *バックグラウンド重複排除*
+
バックグラウンド重複排除も、重複するデータブロックを検出して一意の共有ブロックへの参照に置き換えますが、データがディスクに書き込まれたあとに実行することで、ストレージ効率がさらに向上します。ストレージシステムで特定の条件が満たされたときに実行されるように、バックグラウンド重複排除を設定できます。たとえば、ボリュームの利用率が10%に達したときにバックグラウンド重複排除を実行できます。バックグラウンド重複排除は手動でトリガーすることも、特定のスケジュールで実行されるように設定することもできます。AFFシステムおよびASAシステムではデフォルトで有効になっています。FASシステムでは、バックグラウンド重複排除を手動で有効にする必要があります。



+
重複排除は、ボリューム内と、アグリゲート内のボリューム間でサポートされます。通常、重複排除されたデータの読み取りがパフォーマンスに影響することはありません。

* * 圧縮 *
+
xref:compression-concept.html[圧縮]データブロックを圧縮グループに結合し、各ブロックを単一のブロックとして格納することで、ボリュームに必要な物理ストレージの量を削減します。読み取り要求または上書き要求を受信すると、ファイル全体ではなく、少数のブロックグループのみが読み取られます。このプロセスにより、読み取りと上書きのパフォーマンスが最適化され、圧縮されるファイルのサイズの拡張性が向上します。

+
圧縮は、インラインまたはポストプロセスで実行できます。インライン圧縮では、ディスクに書き込む前にメモリ内のデータを圧縮することで、スペースを即座に削減できます。ポストプロセス圧縮では、まずブロックが圧縮されていない状態でディスクに書き込まれ、次にスケジュールされた時刻にデータが圧縮されます。AFAシステムではデフォルトで有効になっています。他のすべてのシステムでは、手動で圧縮を有効にする必要があります。

* *圧縮*
+
コンパクションを使用すると、サイズが4KB未満のデータチャンクを作成して単一のブロックに結合することで、ボリュームに必要な物理ストレージの量が削減されます。コンパクションはデータがメモリに残っている間に実行されるため、ディスク上で不要なスペースが消費されることはありません。AFFシステムおよびASAシステムではデフォルトで有効になっています。FASシステムでは、手動でコンパクションを有効にする必要があります。

* * FlexCloneボリューム、ファイル、LUN *
+
xref:flexclone-volumes-files-luns-concept.html[FlexCloneテクノロジ]Snapshotメタデータを活用して、ボリューム、ファイル、LUNの書き込み可能なポイントインタイムコピーを作成します。コピーはデータブロックを親と共有し、変更がコピーまたはその親に書き込まれるまでメタデータに必要な分以外ストレージを消費しません。変更が書き込まれると、差分のみが保存されます。

+
従来の手法でコピーを作成すると数分から数時間かかりますが、FlexCloneテクノロジを使用すれば大規模なデータセットのコピーもほぼ瞬時に作成できます。

* *温度に敏感なストレージ効率*
+
ONTAPを使用すると link:../volumes/enable-temperature-sensitive-efficiency-concept.html["温度に敏感なストレージ効率"] 、ボリュームのデータへのアクセス頻度を評価し、その頻度とデータに適用される圧縮レベルをマッピングすることができます。アクセス頻度の低いコールドデータの場合は、大容量のデータブロックが圧縮されます。頻繁にアクセスされて上書きされるホットデータの場合は、小さいデータブロックが圧縮されるため、プロセスが効率化されます。

+
ONTAP 9.8で導入されたTemperature-Sensitive Storage Efficiency（TSSE）は、新しく作成したシンプロビジョニングAFFボリュームで自動的に有効になります。ハードウェアオフロードプロセッサを使用するONTAP 9.15.1で導入されたでは、この機能は有効になっていませんlink:builtin-storage-efficiency-concept.html["AFF A70、AFF A90、およびAFF A1Kプラットフォーム"]。

* * CPUまたは専用オフロード・プロセッサーのストレージ効率*
+
ONTAP 9 .15.1以降では、ONTAPがAFF A70、AFF A90、AFF A1K、FAS70、FAS90の各プラットフォームにデータコンパクション機能を提供してlink:builtin-storage-efficiency-concept.html["CPUまたは専用オフロードプロセッサのストレージ効率"]います。AFF A70、AFF A90、およびAFF A1Kシステムでは、Storage Efficiencyが自動的に有効になるため、設定は必要ありません。



これらのテクノロジのメリットを日常業務で最小限の労力で実現できます。たとえば、5、000人のユーザにホームディレクトリ用のストレージを提供する必要があり、任意のユーザが必要とする最大スペースが1GBであるとします。潜在的なストレージニーズに合わせて、5TBのアグリゲートを事前にリザーブすることもできます。ただし、ホームディレクトリの容量要件は組織によって大きく異なることもわかっています。組織用に合計スペースを5TBリザーブする代わりに、2TBのアグリゲートを作成できます。シンプロビジョニングを使用すると、名目上は各ユーザに1GBのストレージを割り当てることができますが、ストレージは必要に応じてのみ割り当てることができます。時間の経過とともにアグリゲートをアクティブに監視し、実際の物理サイズを必要に応じて増やすことができます。

別の例として、仮想デスクトップ間で大量の重複データが発生している仮想デスクトップインフラ（VDI）を使用しているとします。重複排除は、VDI全体で重複する情報ブロックを自動的に排除し、元のブロックへのポインタに置き換えることで、ストレージの使用量を削減します。他のONTAPのStorage Efficiencyテクノロジ（圧縮など）も、手動操作なしでバックグラウンドで実行できます。

ONTAPディスクパーティショニングテクノロジは、ストレージ効率も向上します。RAID DPテクノロジは、パフォーマンスを犠牲にしたり、ディスクミラーリングのオーバーヘッドを増大させたりすることなく、二重ディスク障害からデータを保護します。ONTAP 9を使用した高度なSSDパーティショニングにより、使用可能容量が約20%増加します。

NetAppは、オンプレミスのONTAPと同じStorage Efficiency機能をクラウドで提供します。オンプレミスのONTAPからクラウドにデータを移行する場合は、既存のストレージ効率が維持されます。たとえば、ビジネスクリティカルなデータを含むSQLデータベースを、オンプレミスシステムからクラウドに移行するとします。BlueXP  のデータレプリケーションを使用してデータを移行できます。また、移行プロセスの一環として、クラウド内のSnapshotに対して最新のオンプレミスポリシーを有効にすることもできます。
