---
permalink: concepts/support-industry-standard-technologies-concept.html 
sidebar: sidebar 
keywords: support, industry-standard, network, technologies 
summary: ONTAPは、すべての主要な業界標準ネットワークテクノロジをサポートしています。主なテクノロジには、IPspace、DNSロードバランシング、SNMPトラップなどがあります。 
---
= 業界標準のネットワークテクノロジのサポート
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
ONTAPは、すべての主要な業界標準ネットワークテクノロジをサポートしています。主なテクノロジには、IPspace、DNSロードバランシング、SNMPトラップなどがあります。

ブロードキャストドメイン、フェイルオーバーグループ、およびサブネットについては、をxref:nas-path-failover-concept.adoc[NASパスのフェイルオーバー]参照してください。



== IPspace

IPspace を使用すると、クラスタ内の仮想データサーバごとに個別の IP アドレススペースを作成できます。これにより、管理上分離されたネットワークドメインに属するクライアントは、同じIPアドレスサブネット範囲の重複するIPアドレスを使用してクラスタデータにアクセスできます。

たとえば、サービスプロバイダは、クラスタへのアクセスに同じIPアドレスを使用してテナントごとに異なるIPspaceを設定できます。



== DNSロオトハランシンク

DNS ロードバランシング _ を使用すると、使用可能なポートにユーザネットワークトラフィックを分散できます。DNSサーバは、インターフェイスにマウントされているクライアントの数に基づいて、トラフィック用のネットワークインターフェイスを動的に選択します。



== SNMPトラツフ

SNMP トラップ _ を使用すると、しきい値または障害を定期的にチェックできます。SNMPトラップは、SNMPエージェントからSNMPマネージャに非同期で送信されるシステム監視情報をキャプチャします。



== FIPS準拠

ONTAPは、すべてのSSL接続で連邦情報処理標準（FIPS）140-2に準拠しています。SSL FIPSモードをオンまたはオフにしたり、SSLプロトコルをグローバルに設定したり、RC4などの弱い暗号を無効にしたりできます。
