---
sidebar: sidebar 
permalink: concepts/sysmgr-integration-bluexp-concept.html 
keywords: netapp, ontap, system manager, experience, integrate, integration, bluexp, hybrid, cloud, dashboard, multicloud 
summary: BlueXPのSystem Managerを使用して、ONTAP 9.10.1以降のリリースを管理できます。この統合により、使い慣れたSystem Managerのユーザーインターフェースを維持しながら、統合されたコントロールプレーンを使用してハイブリッドマルチクラウドインフラストラクチャを効率的に監視できます。 
---
= ONTAP System ManagerとBlueXPを統合する
:hardbreaks:
:toclevels: 1
:allow-uri-read: 
:toclevels: 1
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
BlueXPのSystem Managerを使用して、ONTAP 9.10.1以降のリリースを管理できます。この統合により、使い慣れたSystem Managerのユーザーインターフェースを維持しながら、統合されたコントロールプレーンを使用してハイブリッドマルチクラウドインフラストラクチャを効率的に監視できます。

BlueXP を使用すると、クラウド ストレージ (Cloud Volumes ONTAP など) を作成および管理したり、NetApp データ サービス (Cloud Backup など) を使用したり、多数のオンプレミスおよびエッジ ストレージ デバイスを制御したりできます。

BlueXPでは、次の2つの方法でクラスタを検出および管理できます。

* System Manager による管理のための直接検出 (ONTAP 9.12.1 以降)
* コネクタを使用して検出する


コネクタは、お客様の環境にインストールされるソフトウェアです。これにより、System Manager を通じて管理機能にアクセスし、データ複製、バックアップとリカバリ、データ分類、データ階層化などの機能を提供する BlueXP クラウドサービスにアクセスできるようになります。

詳細については、をご覧ください link:https://docs.netapp.com/us-en/bluexp-ontap-onprem/index.html["BlueXPを使用したオンプレミスのONTAPクラスタ管理"^]。

.手順
. BlueXPにログインします。
+
.. BlueXP ログインをお持ちの場合は、それを使用してください。
.. 初めての場合は、「NetApp サポート サイトの資格情報を使用してログイン」を選択し、BlueXP ログイン ページで資格情報を入力します。


. BlueXPでコネクタまたは直接検出を使用してオンプレミスクラスタを検出します。詳細については、https://docs.netapp.com/us-en/bluexp-ontap-onprem/task-discovering-ontap.html[オンプレミスONTAPクラスタの検出^]をご覧ください。
+
.. 方法をご確認くださいlink:https://docs.netapp.com/us-en/bluexp-ontap-onprem/task-manage-ontap-direct.html["直接検出されたクラスターを管理する"^]。
.. 方法をご確認くださいlink:https://docs.netapp.com/us-en/bluexp-ontap-onprem/task-manage-ontap-connector.html["コネクタで検出されたクラスタを管理する"^]。


. System Managerを使用してオンプレミスクラスタを管理します。「My working environment」キャンバスでクラスタを選択し、「サービス」リストから「System Manager」をクリックします。
+
.. 詳細については、をご覧ください link:https://docs.netapp.com/us-en/bluexp-ontap-onprem/task-manage-ontap-direct.html["直接検出されたクラスターを管理する"^]。
.. 方法をご確認くださいlink:https://docs.netapp.com/us-en/bluexp-ontap-onprem/task-manage-ontap-connector.html["コネクタで検出されたクラスタを管理する"^]。






== BlueXP と ONTAP 9.12.1

注: ONTAP 9.12.1 を使用している場合は、BlueXP を試すように求めるメッセージが表示されます。

+ クラスターが BlueXP に接続している場合は、ログイン プロンプトが表示されます。

. [BlueXPに進む]をクリックして、BlueXPへのリンクをクリックします。
+

NOTE: システム設定で外部ネットワークがブロックされている場合は、BlueXP  にアクセスできません。BlueXPを使用してSystem Managerにアクセスするには、アドレス「cloudmanager.cloud.netapp.com`"」にシステムからアクセスできることを確認する必要があります。それ以外の場合は、ONTAPシステムにインストールされているバージョンのSystem Managerをプロンプトで使用できます。

. BlueXPログインページで、「NetApp Support Site 資格情報でログイン」を選択し、資格情報を入力します。
+
すでに BlueXP を使用しており、メールとパスワードを使用してログインしている場合は、代わりにそのログイン オプションを引き続き使用する必要があります。

+
https://docs.netapp.com/us-en/cloud-manager-setup-admin/task-logging-in.html["BlueXPへのログインの詳細をご覧ください"^]です。

. プロンプトが表示されたら、新しい BlueXP アカウントの名前を入力します。
+
ほとんどの場合、BlueXP  はクラスタのデータに基づいて自動的にアカウントを作成します。

. クラスタのクラスタ管理者のクレデンシャルを入力します。


.結果
System Managerが表示され、BlueXPからクラスタを管理することができます。



== BlueXP  の詳細はこちら

* https://docs.netapp.com/us-en/bluexp-setup-admin/concept-overview.html["BlueXPの概要"^]
* https://docs.netapp.com/us-en/cloud-manager-ontap-onprem/index.html["BlueXPを使用して、NetApp AFF およびFAS システムを管理できます"^]

