---
permalink: concepts/thin-provisioning-concept.html 
sidebar: sidebar 
keywords: thin provision 
summary: シンプロビジョニングされたボリュームまたはLUNでは、ストレージが事前にリザーブされません。代わりに、ストレージは必要に応じて動的に割り当てられます。ボリュームまたは LUN 内のデータが削除されると、空きスペースはストレージシステムに戻されます 
---
= シンプロビジョニング
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
ONTAPは、Snapshotに加えて、さまざまなStorage Efficiencyテクノロジを提供しています。主なテクノロジには、シンプロビジョニング、重複排除、圧縮、 FlexClone ボリューム、ファイル、 LUN の割り当てが可能です。Snapshotと同様に、すべてONTAPのWrite Anywhere File Layout（WAFL）上に構築されています。

_thin-provisioned_volumeまたはLUNは、ストレージが事前に予約されていないボリュームです。代わりに、ストレージは必要に応じて動的に割り当てられます。ボリュームまたは LUN 内のデータが削除されると、空きスペースはストレージシステムに戻されます

たとえば、 5 、 000 人のユーザにホームディレクトリ用のストレージを提供する必要があるとします。ホームディレクトリの消費スペースは、最大で 1GB と推定されます。

この状況では、 5TB の物理ストレージを購入することが考えられます。ホームディレクトリを格納するボリュームごとに、最もスペースを消費するユーザのニーズを満たす十分なスペースを確保します。

しかし実際には、ホームディレクトリに必要とされる容量はコミュニティによって大きく異なることもわかっています。ストレージを大量に消費するユーザごとに、ほとんど、またはまったく消費しないユーザが 10 人あります。

シンプロビジョニングを使用すると、使用しない可能性があるストレージを購入することなく、ストレージを大量に消費するユーザのニーズを満たすことができます。ストレージスペースは消費されるまで割り当てられないため、アグリゲートに含まれる5、000個のボリュームそれぞれに名目上1GBのサイズを割り当てることで、2TBのアグリゲートを「オーバーコミット」できます。

ライトユーザとヘビーユーザの比率が10：1であること、およびアグリゲートの空きスペースをアクティブに監視しているかぎり、スペース不足によってボリュームへの書き込みが失敗することはありません。
