---
permalink: nfs-admin/access-cache-concept.html 
sidebar: sidebar 
keywords: access, cache 
summary: ONTAPは、ボリュームまたはqtreeへのクライアントアクセス操作に対するエクスポートポリシールール評価の結果を保存するために、アクセスキャッシュを使用します。これにより、クライアントがI/O要求を送信するたびにエクスポートポリシールールの評価プロセスを実行するよりも、アクセスキャッシュから情報を取得する方がはるかに高速であるため、パフォーマンスが向上します。 
---
= ONTAP NFSアクセスキャッシュについて学ぶ
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
ONTAPは、ボリュームまたはqtreeへのクライアントアクセス操作に対するエクスポートポリシールール評価の結果を保存するために、アクセスキャッシュを使用します。これにより、クライアントがI/O要求を送信するたびにエクスポートポリシールールの評価プロセスを実行するよりも、アクセスキャッシュから情報を取得する方がはるかに高速であるため、パフォーマンスが向上します。

NFSクライアントがボリュームまたはqtree上のデータにアクセスするためにI/O要求を送信すると、ONTAPは各I/O要求を評価し、I/O要求を許可するか拒否するかを決定する必要があります。この評価には、ボリュームまたはqtreeに関連付けられたエクスポートポリシーのすべてのエクスポートポリシールールをチェックすることが含まれます。ボリュームまたはqtreeへのパスが1つ以上のジャンクションポイントを通過する場合、パス上の複数のエクスポートポリシーに対してこのチェックを実行する必要がある場合があります。

この評価は、初期マウント要求だけでなく、読み取り、書き込み、リスト、コピーなどの操作など、NFSクライアントから送信されるすべてのI/O要求に対して実行されることに注意してください。

ONTAPが適用可能なエクスポート ポリシー ルールを識別し、要求を許可するか拒否するかを決定した後、ONTAPはこの情報を格納するためのエントリをアクセス キャッシュに作成します。

NFSクライアントがI/O要求を送信すると、ONTAPはクライアントのIPアドレス、SVMのID、およびターゲットボリュームまたはqtreeに関連付けられたエクスポートポリシーを記録し、まずアクセスキャッシュで一致するエントリをチェックします。アクセスキャッシュに一致するエントリが存在する場合、ONTAPは保存されている情報を使用してI/O要求を許可または拒否します。一致するエントリが存在しない場合、ONTAPは前述のように、適用可能なすべてのポリシールールを評価する通常のプロセスを実行します。

アクティブに使用されていないアクセスキャッシュエントリは更新されません。これにより、外部ネームサーバーとの不要で無駄な通信が削減されます。

アクセスキャッシュから情報を取得する方が、すべてのI/O要求に対してエクスポートポリシールールの評価プロセス全体を実行するよりもはるかに高速です。そのため、アクセスキャッシュを使用すると、クライアントアクセスチェックのオーバーヘッドが削減され、パフォーマンスが大幅に向上します。
