---
permalink: nfs-admin/access-ntfs-volumes-qtrees-unknown-users-task.html 
sidebar: sidebar 
keywords: handle, nfs, access, ntfs, volumes, qtrees, unknown, unix, users 
summary: ONTAPは、NTFSセキュリティ形式のボリュームまたはqtreeへの接続を試みるUNIXユーザを識別できない場合、そのユーザをWindowsユーザに明示的にマッピングできません。このよう場合、そのユーザのアクセスを拒否してセキュリティを厳しくすることも、デフォルトのWindowsユーザにマッピングしてすべてのユーザに最低レベルのアクセスを保証することもできます。 
---
= 不明なUNIXユーザーによるONTAP NTFSボリュームまたはqtreeへのNFSアクセスを処理する
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
ONTAPは、NTFSセキュリティ形式のボリュームまたはqtreeへの接続を試みるUNIXユーザを識別できない場合、そのユーザをWindowsユーザに明示的にマッピングできません。このよう場合、そのユーザのアクセスを拒否してセキュリティを厳しくすることも、デフォルトのWindowsユーザにマッピングしてすべてのユーザに最低レベルのアクセスを保証することもできます。

.開始する前に
このオプションを有効にする場合は、デフォルトのWindowsユーザを設定しておく必要があります。

.タスク概要
UNIXユーザがNTFSセキュリティ形式のボリュームまたはqtreeへのアクセスを試みた場合、ONTAPがNTFSアクセス権を適切に評価できるように、まずそのUNIXユーザがWindowsユーザにマッピングされる必要があります。ただし、ONTAPが設定されているユーザ情報ネーム サービス ソースでそのUNIXユーザの名前をルックアップできなかった場合、特定のWindowsユーザにそのUNIXユーザを明示的にマッピングすることができません。このような不明なUNIXユーザは、次のいずれかの方法で処理できます。

* 不明なUNIXユーザに対してアクセスを拒否する。
+
NTFSボリュームまたはqtreeにアクセスしようとするすべてのUNIXユーザに明示的なマッピングを要求することで、より厳しいセキュリティを適用します。

* 不明なUNIXユーザをデフォルトのWindowsユーザにマッピングする。
+
セキュリティ性は低下しますが、すべてのユーザがデフォルトのWindowsユーザとしてNTFSボリュームまたはqtreeへの最低レベルのアクセスが保証されるため、利便性が向上します。



.手順
. 権限レベルをadvancedに設定します。
+
`set -privilege advanced`

. 次のいずれかを実行します。
+
[cols="35,65"]
|===


| 不明な UNIX ユーザーにデフォルトの Windows ユーザーを指定したい場合… | コマンドを入力してください... 


 a| 
有効
 a| 
`vserver nfs modify -vserver vserver_name -map-unknown-uid-to-default-windows-user enabled`



 a| 
無効
 a| 
`vserver nfs modify -vserver vserver_name -map-unknown-uid-to-default-windows-user disabled`

|===
. admin権限レベルに戻ります。
+
`set -privilege admin`


