---
permalink: nfs-admin/case-sensitivity-file-directory-multiprotocol-concept.html 
sidebar: sidebar 
keywords: case sensitivity, file, directory, name, multiprotocol, environment 
summary: ファイル名とディレクトリ名について、NFSクライアントでは大文字と小文字が区別されますが、SMBクライアントでは大文字と小文字が区別されず、同じ文字として扱われます。この違いがマルチプロトコル環境に及ぼす影響、およびSMB共有の作成時にパスを指定するときや、共有内のデータにアクセスするときにどのように対処すべきかを理解しておく必要があります。 
---
= ONTAP NFSマルチプロトコル環境におけるファイル名とディレクトリ名の大文字と小文字の区別について学習します
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
ファイル名とディレクトリ名について、NFSクライアントでは大文字と小文字が区別されますが、SMBクライアントでは大文字と小文字が区別されず、同じ文字として扱われます。この違いがマルチプロトコル環境に及ぼす影響、およびSMB共有の作成時にパスを指定するときや、共有内のデータにアクセスするときにどのように対処すべきかを理解しておく必要があります。

SMBクライアントが `testdir`という名前のディレクトリを作成した場合、SMBクライアントとNFSクライアントの両方でファイル名が `testdir`として表示されます。ただし、SMBユーザーが後から `TESTDIR`という名前のディレクトリを作成しようとした場合、SMBクライアントにとってその名前が既に存在するため、その名前は許可されません。NFSユーザーが後から `TESTDIR`という名前のディレクトリを作成した場合、NFSクライアントとSMBクライアントは、次のように異なるディレクトリ名を表示します：

* NFS クライアントでは、ディレクトリ名は大文字と小文字が区別されるため、 `testdir`と `TESTDIR`のように、作成されたとおりに両方のディレクトリ名が表示されます。
* SMBクライアントでは、2つのディレクトリを区別するために8.3形式の名前が使用されます。1つのディレクトリには基本ファイル名が付けられます。以降のディレクトリには8.3形式の名前が割り当てられます。
+
** SMB クライアントでは、 `testdir`および `TESTDI~1`が表示されます。
** ONTAP は、2 つのディレクトリを区別するために `TESTDI~1`ディレクトリ名を作成します。
+
この場合、Storage Virtual Machine（SVM）での共有の作成時または変更時に共有パスを指定するときは、8.3形式の名前を使用する必要があります。





ファイルについても同様に、SMBクライアントが `test.txt`を作成した場合、SMBクライアントとNFSクライアントの両方でファイル名が `text.txt`と表示されます。ただし、SMBユーザーが後から `Test.txt`を作成しようとしても、SMBクライアントにとってその名前が既に存在しているため、その名前は許可されません。NFSユーザーが後から `Test.txt`という名前のファイルを作成した場合、NFSクライアントとSMBクライアントでは、ファイル名が次のように異なって表示されます：

* NFS クライアントでは、ファイル名は大文字と小文字が区別されるため、作成されたときの `test.txt`と `Test.txt`の両方のファイル名が表示されます。
* SMBクライアントでは、2つのファイルを区別するために8.3形式の名前が使用されます。一方のファイルには基本ファイル名が付けられます。追加のファイルには、8.3形式のファイル名が割り当てられます。
+
** SMB クライアントでは、 `test.txt`および `TEST~1.TXT`が表示されます。
** ONTAPは、2つのファイルを区別するために `TEST~1.TXT`ファイル名を作成します。




[NOTE]
====
文字マッピングがvserver cifs character-mappingコマンドを使用して作成されている場合、通常は大文字と小文字が区別されないWindows検索で大文字と小文字が区別されるようになる可能性があります。つまり、文字マッピングが作成されていて、その文字マッピングがファイル名に使用されている場合にのみ、ファイル名検索で大文字と小文字が区別されます。

====