---
permalink: nfs-admin/commands-manage-nis-domain-config-reference.html 
sidebar: sidebar 
keywords: command, manage, nis, domain, configuration 
summary: ONTAP には、 NIS ドメイン設定を管理するためのコマンドが用意されています。 
---
= NIS ドメイン設定を管理するコマンドです
:icons: font
:imagesdir: ../media/


[role="lead"]
ONTAP には、 NIS ドメイン設定を管理するためのコマンドが用意されています。

[cols="35,65"]
|===


| 状況 | 使用するコマンド 


 a| 
NIS ドメイン設定を作成します
 a| 
「 vserver services name-service nis-domain create 」を参照してください



 a| 
NIS ドメイン設定を表示します
 a| 
vserver services name-service nis-domain show



 a| 
NIS ドメイン設定のバインドステータスを表示します
 a| 
vserver services name-service nis-domain show-bound です



 a| 
NIS 統計を表示します
 a| 
「 vserver services name-service nis-domain show-statistics 」 - advanced 以上の権限レベルで使用できます。



 a| 
NIS の統計を消去します
 a| 
「 vserver services name-service nis-domain clear-statistics 」は、 advanced 以上の権限レベルで使用できます。



 a| 
NIS ドメイン設定を変更する
 a| 
「 vserver services name-service nis-domain modify 」を参照してください



 a| 
NIS ドメイン設定を削除する
 a| 
vserver services name-service nis-domain delete



 a| 
ホスト単位のネットグループ検索でのキャッシュを有効にします
 a| 
「 vserver services name-service nis-domain netgroup-database config modify 」は、 advanced 以上の権限レベルで使用できます。

|===
詳細については、各コマンドのマニュアルページを参照してください。
