---
permalink: nfs-admin/config-options-ldap-directory-searches-concept.html 
sidebar: sidebar 
keywords: LDAP referral chasing 
summary: 環境にとって最も適した方法でLDAPサーバに接続するようにLDAPクライアントを構成することで、ユーザ、グループ、およびネットグループ情報を含め、LDAPディレクトリ検索を最適化することができます。デフォルトのLDAPベースおよびスコープ検索値で十分な状況や、カスタム値のほうが適切な場合に指定すべきパラメータを理解しておく必要があります。 
---
= LDAPディレクトリ検索のためのONTAP NFS設定オプション
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
環境にとって最も適した方法でLDAPサーバに接続するようにLDAPクライアントを構成することで、ユーザ、グループ、およびネットグループ情報を含め、LDAPディレクトリ検索を最適化することができます。デフォルトのLDAPベースおよびスコープ検索値で十分な状況や、カスタム値のほうが適切な場合に指定すべきパラメータを理解しておく必要があります。

ユーザ、グループ、およびネットグループ情報のLDAPクライアント検索オプションは、LDAPクエリの失敗、ひいてはストレージ システムへのクライアント アクセスの失敗を回避するのに役立ちます。また、クライアントのパフォーマンスに関する問題を回避するために、検索をできるだけ効率的なものにするのにも役立ちます。



== デフォルトのベースおよびスコープ検索値

LDAPベースは、LDAPクライアントがLDAPクエリを実行するために使用するデフォルトのベースDNです。ユーザ、グループ、ネットグループの検索を含むすべての検索は、ベースDNを使用して行われます。このオプションは、LDAPディレクトリが比較的小さくてすべての関連エントリが同じDN内にある場合に適しています。

カスタムベースDNを指定しない場合、デフォルトは `root`です。つまり、各クエリはディレクトリ全体を検索します。これによりLDAPクエリの成功率は最大化されますが、効率が悪く、大規模なLDAPディレクトリではパフォーマンスが大幅に低下する可能性があります。

LDAPベース スコープは、LDAPクライアントがLDAPクエリを実行するために使用するデフォルトのベース スコープです。ユーザ、グループ、ネットグループの検索を含むすべての検索は、ベース スコープを使用して行われます。LDAPクエリによる検索範囲を、名前付きエントリのみ、DNの1レベル下にあるエントリ、またはDNの下にあるサブツリー全体のどれにするかが決定されます。

カスタムベーススコープを指定しない場合、デフォルトは `subtree`です。つまり、各クエリはDN以下のサブツリー全体を検索します。これによりLDAPクエリの成功率は最大化されますが、効率が悪く、大規模なLDAPディレクトリではパフォーマンスが大幅に低下する可能性があります。



== カスタム ベースおよびスコープ検索値

必要に応じて、ユーザ、グループ、およびネットグループ検索で、別々のベースおよびスコープ値を指定できます。クエリの検索ベースおよびクエリをこうした形で制限すると、検索対象がLDAPディレクトリのより小さなサブセクションに制限されるため、パフォーマンスを大幅に向上できます。

カスタム ベースおよびスコープ値を指定した場合、ユーザ、グループ、およびネットグループ検索の全般的なデフォルト検索ベースおよびスコープは無視されます。カスタム ベースおよびスコープ値を指定するパラメータは、advanced権限レベルで使用できます。

[cols="35,65"]
|===


| LDAPクライアントパラメータ... | カスタムを指定します... 


 a| 
`-base-dn`
 a| 
すべてのLDAP検索のベースDN。必要に応じて複数の値を入力できます（たとえば、ONTAP 9.5以降のリリースでLDAPリファーラル追跡が有効になっている場合など）。



 a| 
`-base-scope`
 a| 
すべてのLDAP検索の基本スコープ。



 a| 
`-user-dn`
 a| 
すべてのLDAPユーザー検索のベースDN。このパラメータはユーザー名マッピング検索にも適用されます。



 a| 
`-user-scope`
 a| 
すべてのLDAPユーザー検索の基本スコープ。このパラメータはユーザー名マッピング検索にも適用されます。



 a| 
`-group-dn`
 a| 
すべてのLDAPグループ検索のベースDN。



 a| 
`-group-scope`
 a| 
すべてのLDAPグループ検索の基本スコープ。



 a| 
`-netgroup-dn`
 a| 
すべてのLDAPネットグループ検索のベースDN。



 a| 
`-netgroup-scope`
 a| 
すべてのLDAPネットグループ検索の基本スコープ。

|===


== 複数のカスタム ベースDN値

LDAPディレクトリが複雑な場合は、特定の情報を求めてLDAPディレクトリの複数の部分を検索するために複数のベースDNの指定が必要になる可能性があります。複数のユーザ、グループ、およびネットグループDNパラメータを指定するには、各パラメータをセミコロンで区切り、DN検索リスト全体を二重引用符（"）で囲みます。DNにセミコロンが含まれる場合、DNではセミコロンの直前にエスケープ文字（\）を追加する必要があります。

スコープは、対応するパラメータで指定されているDNのリスト全体に適用されることに注意してください。たとえば、3つの異なるユーザDNのリストとサブツリーをユーザ スコープで指定した場合は、LDAPユーザ検索により、指定された3つのDNのそれぞれでサブツリー全体が検索されます。

ONTAP 9.5以降では、LDAP _referral chasing_も指定できるようになりました。これにより、ONTAPのLDAPクライアントは、プライマリLDAPサーバからLDAPリファーラル応答が返されない場合に、他のLDAPサーバに検索要求を参照できます。クライアントはそのリファーラルデータを使用して、リファーラルデータに記述されているサーバからターゲットオブジェクトを取得します。参照先のLDAPサーバに存在するオブジェクトを検索するには、LDAPクライアント設定の一部として、参照先オブジェクトのbase-dnをbase-dnに追加します。ただし、参照先オブジェクトは、LDAPクライアント作成または変更時に（ `-referral-enabled true`オプションを使用して）リファーラル追跡が有効になっている場合にのみ検索されます。



== カスタムLDAP検索フィルター

LDAP設定オプションパラメータを使用して、カスタム検索フィルタを作成できます。 `-group-membership-filter`パラメータは、LDAPサーバからグループメンバーシップを検索する際に使用する検索フィルタを指定します。

有効なフィルターの例は次のとおりです：

[listing]
----
(cn=*99), (cn=1*), (|(cn=*22)(cn=*33))
----
link:https://www.netapp.com/media/19423-tr-4835.pdf["ONTAPでLDAPを設定する方法"^]についての詳細をご覧ください。
