---
permalink: nfs-admin/control-nfs-access-over-tcp-udp-task.html 
sidebar: sidebar 
keywords: control, nfs, access, tcp, udp 
summary: TCP および UDP 経由での Storage Virtual Machine （ SVM ）への NFS アクセスを有効または無効にするには、それぞれ -tcp および -udp パラメータを使用します。これにより、環境で NFS クライアントが TCP または UDP 経由でデータにアクセスできるかどうかを制御できます。 
---
= TCP および UDP 経由の NFS アクセスを制御します
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
TCPおよびUDP経由のStorage Virtual Machine（SVM）へのNFSアクセスを有効または無効にするには、を変更します `-tcp` および `-udp` パラメータを指定します。これにより、環境で NFS クライアントが TCP または UDP 経由でデータにアクセスできるかどうかを制御できます。

.このタスクについて
これらのパラメータは NFS のみに適用されます。補助プロトコルには影響しません。たとえば、 TCP 経由の NFS が無効になっていても、 TCP 経由でのマウント処理は成功します。TCP または UDP トラフィックを完全にブロックするには、エクスポートポリシールールを使用します。

[NOTE]
====
コマンドの失敗を防ぐために、 NFS に対して TCP を無効にする前に SnapDiff RPC サーバをオフにする必要があります。TCPを無効にするには、コマンドを使用します `vserver snapdiff-rpc-server off -vserver vserver name`。

====
.ステップ
. 次のいずれかを実行します。
+
[cols="30,70"]
|===


| 設定する NFS アクセスの状態 | 入力するコマンド 


 a| 
TCP 経由で有効化
 a| 
`vserver nfs modify -vserver vserver_name -tcp enabled`



 a| 
TCP 経由で無効化
 a| 
`vserver nfs modify -vserver vserver_name -tcp disabled`



 a| 
UDP 経由で有効化
 a| 
`vserver nfs modify -vserver vserver_name -udp enabled`



 a| 
UDP 経由で無効にしました
 a| 
`vserver nfs modify -vserver vserver_name -udp disabled`

|===

