---
permalink: nfs-admin/create-volumes-without-specifying-junction-task.html 
sidebar: sidebar 
keywords: create, data, volume, specify, junction, point 
summary: ジャンクション ポイントを指定せずにデータ ボリュームを作成できます。作成したボリュームは、自動的にはマウントされず、NASアクセス用の設定に使用することはできません。このボリュームに対してSMB共有またはNFSエクスポートを設定するには、まず、ボリュームをマウントする必要があります。 
---
= 特定のジャンクションポイントなしでONTAP NASボリュームを作成する
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
ジャンクション ポイントを指定せずにデータ ボリュームを作成できます。作成したボリュームは、自動的にはマウントされず、NASアクセス用の設定に使用することはできません。このボリュームに対してSMB共有またはNFSエクスポートを設定するには、まず、ボリュームをマウントする必要があります。

.開始する前に
* ボリュームを作成するアグリゲートがすでに存在している必要があります。
* ONTAP 9.13.1以降では、容量分析とアクティビティトラッキングを有効にしたボリュームを作成できます。容量またはアクティビティトラッキングを有効にするには、 `-analytics-state`または `-activity-tracking-state`を `on`に設定した `volume create`コマンドを発行します。
+
容量分析とアクティビティ追跡の詳細については、 https://docs.netapp.com/us-en/ontap/task_nas_file_system_analytics_enable.html["ファイルシステム分析の有効化"]を参照してください。link:https://docs.netapp.com/us-en/ontap-cli/volume-create.html["ONTAPコマンド リファレンス"^]の `volume create`の詳細を確認してください。



.手順
. 次のコマンドを使用して、ジャンクション ポイントが設定されていないボリュームを作成します。
+
`volume create -vserver vserver_name -volume volume_name -aggregate aggregate_name -size {integer[KB|MB|GB|TB|PB]} -security-style {ntfs|unix|mixed}`

+
ボリュームのセキュリティ形式の指定は省略可能です。セキュリティ形式を指定しない場合、Storage Virtual Machine（SVM）のルート ボリュームと同じセキュリティ形式を使用してボリュームが作成されます。ただし、ルート ボリュームのセキュリティ形式が、データ ボリュームには適切でないセキュリティ形式である場合もあります。解決が困難なファイル アクセスの問題ができるだけ発生しないように、ボリュームの作成時にセキュリティ形式を指定することを推奨します。

+
データボリュームをカスタマイズするために使用できるオプションパラメータは多数あります。link:https://docs.netapp.com/us-en/ontap-cli/volume-create.html["ONTAPコマンド リファレンス"^]の `volume create`の詳細をご覧ください。

. ジャンクション ポイントが設定されていないボリュームが作成されたことを確認します。
+
`volume show -vserver vserver_name -volume volume_name -junction`



.例
次の例では、ジャンクション ポイントにマウントされていない SVM vs1 上に「`sales`」という名前のボリュームを作成します：

[listing]
----
cluster1::> volume create -vserver vs1 -volume sales -aggregate aggr3 -size 20GB
[Job 3406] Job succeeded: Successful

cluster1::> volume show -vserver vs1 -junction
                     Junction                 Junction
Vserver   Volume     Active   Junction Path   Path Source
--------- ---------- -------- --------------- -----------
vs1       data       true     /data           RW_volume
vs1       home4      true     /eng/home       RW_volume
vs1       vs1_root   -        /               -
vs1       sales      -        -               -
----