---
permalink: nfs-admin/default-export-policy-svms-concept.html 
sidebar: sidebar 
keywords: default, export, policy, svm 
summary: 各SVMには、ルールを含まないデフォルトのエクスポートポリシーがあります。クライアントがSVM上のデータにアクセスするには、ルールを含むエクスポートポリシーが存在している必要があります。SVMに含まれる各FlexVolボリュームには、エクスポートポリシーが関連付けられている必要があります。 
---
= ONTAP NFS SVMのデフォルトのエクスポートポリシー
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
各SVMには、ルールを含まないデフォルトのエクスポートポリシーがあります。クライアントがSVM上のデータにアクセスするには、ルールを含むエクスポートポリシーが存在している必要があります。SVMに含まれる各FlexVolボリュームには、エクスポートポリシーが関連付けられている必要があります。

SVMを作成すると、ストレージシステムは `default`というデフォルトのエクスポートポリシーをSVMのルートボリューム用に自動的に作成します。クライアントがSVM上のデータにアクセスする前に、デフォルトのエクスポートポリシーに1つ以上のルールを作成する必要があります。または、ルールを含むカスタムエクスポートポリシーを作成することもできます。デフォルトのエクスポートポリシーは変更したり名前を変更したりできますが、削除することはできません。

FlexVolボリュームをそのSVMに作成すると、ストレージシステムによってボリュームが作成され、そのSVMのルートボリュームのデフォルトのエクスポートポリシーが関連付けられます。デフォルトでは、SVMに作成された各ボリュームには、ルートボリュームのデフォルトのエクスポートポリシーが関連付けられます。SVMに含まれるすべてのボリュームにデフォルトのエクスポートポリシーを使用することも、ボリュームごとに固有のエクスポートポリシーを作成することもできます。複数のボリュームに同じエクスポートポリシーを関連付けることもできます。
