---
permalink: nfs-admin/display-locks-task.html 
sidebar: sidebar 
keywords: display, information, lock 
summary: 現在のファイル ロックに関する情報を表示できます。これには、保持されているロックの種類とロックの状態、バイト範囲ロック、共有ロック モード、委譲ロック、およびoplockに関する詳細、およびロックが永続ハンドルまたは永続ハンドルで開かれているかどうかが含まれます。 
---
= ONTAP NFS SVMのロックに関する情報を表示します
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
現在のファイル ロックに関する情報を表示できます。これには、保持されているロックの種類とロックの状態、バイト範囲ロック、共有ロック モード、委譲ロック、およびoplockに関する詳細、およびロックが永続ハンドルまたは永続ハンドルで開かれているかどうかが含まれます。

.タスク概要
NFSv4またはNFSv4.1を通じて確立されたロックの場合、クライアントIPアドレスは表示できません。

デフォルトでは、このコマンドはすべてのロックに関する情報を表示します。コマンドパラメータを使用すると、特定のStorage Virtual Machine（SVM）のロックに関する情報を表示したり、他の基準でコマンドの出力をフィルタリングしたりできます。

 `vserver locks show`コマンドは、次の4種類のロックに関する情報を表示します：

* ファイルの一部のみをロックするバイト範囲ロック。
* 開いているファイルをロックする共有ロック。
* SMB 経由のクライアント側キャッシュを制御する便宜的ロック。
* NFSv4.x上のクライアント側キャッシュを制御する委任。


オプションパラメータを指定することで、各ロックの種類に関する重要な情報を確認できます。link:https://docs.netapp.com/us-en/ontap-cli/vserver-locks-show.html["ONTAPコマンド リファレンス"^]の `vserver locks show`の詳細をご覧ください。

.手順
.  `vserver locks show`コマンドを使用してロックに関する情報を表示します。


.例
以下の例は、パス `/vol1/file1`のファイルに対するNFSv4ロックの概要情報を表示します。sharelockのアクセス モードはwrite-deny_noneで、ロックは書き込み委譲で付与されました：

[listing]
----
cluster1::> vserver locks show

Vserver: vs0
Volume  Object Path               LIF         Protocol  Lock Type   Client
------- ------------------------- ----------- --------- ----------- -------
vol1    /vol1/file1               lif1        nfsv4     share-level -
               Sharelock Mode: write-deny_none
                                                        delegation  -
               Delegation Type: write
----
以下の例は、パス `/data2/data2_2/intro.pptx`のファイルに対するSMBロックに関するoplockおよびsharelockの詳細情報を表示します。IPアドレス10.3.1.3のクライアントに、共有ロックアクセスモードwrite-deny_noneで永続ハンドルが付与されています。batch oplockレベルでリースoplockが付与されています（

[listing]
----
cluster1::> vserver locks show -instance -path /data2/data2_2/intro.pptx

                   Vserver: vs1
                    Volume: data2_2
         Logical Interface: lif2
               Object Path: /data2/data2_2/intro.pptx
                 Lock UUID: 553cf484-7030-4998-88d3-1125adbba0b7
             Lock Protocol: cifs
                 Lock Type: share-level
   Node Holding Lock State: node3
                Lock State: granted
  Bytelock Starting Offset: -
    Number of Bytes Locked: -
     Bytelock is Mandatory: -
     Bytelock is Exclusive: -
     Bytelock is Superlock: -
          Bytelock is Soft: -
              Oplock Level: -
   Shared Lock Access Mode: write-deny_none
       Shared Lock is Soft: false
           Delegation Type: -
            Client Address: 10.3.1.3
             SMB Open Type: durable
         SMB Connect State: connected
SMB Expiration Time (Secs): -
         SMB Open Group ID: 78a90c59d45ae211998100059a3c7a00a007f70da0f8ffffcd445b0300000000

                   Vserver: vs1
                    Volume: data2_2
         Logical Interface: lif2
               Object Path: /data2/data2_2/test.pptx
                 Lock UUID: 302fd7b1-f7bf-47ae-9981-f0dcb6a224f9
             Lock Protocol: cifs
                 Lock Type: op-lock
   Node Holding Lock State: node3
                Lock State: granted
  Bytelock Starting Offset: -
    Number of Bytes Locked: -
     Bytelock is Mandatory: -
     Bytelock is Exclusive: -
     Bytelock is Superlock: -
          Bytelock is Soft: -
              Oplock Level: batch
   Shared Lock Access Mode: -
       Shared Lock is Soft: -
           Delegation Type: -
            Client Address: 10.3.1.3
             SMB Open Type: -
         SMB Connect State: connected
SMB Expiration Time (Secs): -
         SMB Open Group ID: 78a90c59d45ae211998100059a3c7a00a007f70da0f8ffffcd445b0300000000
----