---
permalink: nfs-admin/enable-disable-nfsv4-write-file-delegations-task.html 
sidebar: sidebar 
keywords: enable, disable, nfsv4, write, file, delegation 
summary: 書き込みファイル委譲を有効または無効にするには、-v4.0-write-delegation または -v4.1-write-delegation オプションを変更します。書き込みファイル委譲を有効にすると、ファイルのオープンとクローズに加えて、ファイルとレコードのロックに関連するメッセージオーバーヘッドを大幅に削減できます。 
---
= ONTAP SVMのNFSv4書き込みファイル委譲を有効または無効にする
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
書き込みファイル委譲を有効または無効にするには、``-v4.0-write-delegation``またはオプションを変更します。書き込みファイル委譲を有効にすると、ファイルの開閉に加えて、ファイルとレコードのロックに関連するメッセージのオーバーヘッドを大幅に削減できます。

.タスク概要
デフォルトでは、書き込みファイル委譲は無効になっています。

書き込みファイル委譲を有効にすることの欠点は、サーバの再起動、クライアントの再起動、またはネットワーク パーティションの発生後に、サーバとそのクライアントが委譲を回復するための追加タスクを実行する必要があることです。

.手順
. 次のいずれかを実行します。
+
[cols="2*"]
|===
| 状況 | 操作 


 a| 
NFSv4書き込みファイル委譲を有効にする
 a| 
次のコマンドを入力します： `vserver nfs modify -vserver vserver_name -v4.0-write-delegation enabled`



 a| 
NFSv4.1書き込みファイル委譲を有効にする
 a| 
次のコマンドを入力します： `vserver nfs modify -vserver vserver_name -v4.1-write-delegation enabled`



 a| 
NFSv4書き込みファイル委譲を無効にする
 a| 
次のコマンドを入力します： `vserver nfs modify -vserver vserver_name -v4.0-write-delegation disabled`



 a| 
NFSv4.1書き込みファイル委譲を無効にする
 a| 
次のコマンドを入力します： `vserver nfs modify -vserver vserver_name -v4.1-write-delegation disabled`

|===


.結果
ファイル委譲オプションへの変更はすぐに反映されます。NFSのリブートやリスタートは必要ありません。
