---
permalink: nfs-admin/flush-export-policy-caches-task.html 
sidebar: sidebar 
keywords: flush, export, policy, cache 
summary: エクスポート ポリシー キャッシュを手動でフラッシュ（vserver export-policy cache flush）すると、古くなった可能性のある情報が削除され、ONTAPが適切な外部リソースから最新の情報を取得するようになります。これにより、NFSエクスポートへのクライアント アクセスに関連するさまざまな問題を解決できます。 
---
= ONTAP NAS SVMのエクスポート ポリシー キャッシュをフラッシュする
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
ONTAPは、エクスポートポリシー関連情報を保存するために複数のエクスポートポリシーキャッシュを使用し、アクセスを高速化します。エクスポートポリシーキャッシュを手動でフラッシュする(`vserver export-policy cache flush`と、古くなった可能性のある情報が削除され、ONTAPが適切な外部リソースから最新の情報を取得するようになります。これにより、NFSエクスポートへのクライアントアクセスに関連するさまざまな問題を解決できます。

.タスク概要
エクスポート ポリシー キャッシュ情報は、次の理由により古くなっている可能性があります：

* エクスポート ポリシー ルールが最近変更された
* ネーム サーバでホスト名のレコードが最近変更された
* ネーム サーバでネットグループ エントリが最近変更された
* ネットグループの完全なロードを妨げていたネットワーク停止からのリカバリが行われた


.手順
. ネーム サービス キャッシュが有効になっていない場合は、アドバンス特権モードで次のいずれかのアクションを実行します：
+
[cols="2*"]
|===
| フラッシュする場合... | コマンドを入力してください... 


 a| 
すべてのエクスポート ポリシー キャッシュ（showmount を除く）
 a| 
`vserver export-policy cache flush -vserver vserver_name`



 a| 
エクスポート ポリシー ルール アクセス キャッシュ
 a| 
`vserver export-policy cache flush -vserver vserver_name -cache access`オプションの `-node`パラメータを含めて、アクセス キャッシュをフラッシュするノードを指定できます。



 a| 
ホスト名キャッシュ
 a| 
`vserver export-policy cache flush -vserver vserver_name -cache host`



 a| 
ネットグループ キャッシュ
 a| 
`vserver export-policy cache flush -vserver vserver_name -cache netgroup`ネットグループの処理はリソースを大量に消費します。古いネットグループが原因で発生したクライアント アクセスの問題を解決する場合にのみ、ネットグループ キャッシュをフラッシュしてください。



 a| 
showmountキャッシュ
 a| 
`vserver export-policy cache flush -vserver vserver_name -cache showmount`

|===
. 名前サービス キャッシュが有効になっている場合は、次のいずれかのアクションを実行します：
+
[cols="2*"]
|===
| フラッシュする場合... | コマンドを入力してください... 


 a| 
エクスポート ポリシー ルール アクセス キャッシュ
 a| 
`vserver export-policy cache flush -vserver vserver_name -cache access`オプションの `-node`パラメータを含めて、アクセス キャッシュをフラッシュするノードを指定できます。



 a| 
ホスト名キャッシュ
 a| 
`vserver services name-service cache hosts forward-lookup delete-all`



 a| 
ネットグループ キャッシュ
 a| 
`vserver services name-service cache netgroups ip-to-netgroup delete-all` `vserver services name-service cache netgroups members delete-all`ネットグループの処理はリソースを大量に消費します。古いネットグループが原因で発生したクライアント アクセスの問題を解決する場合にのみ、ネットグループ キャッシュをフラッシュしてください。



 a| 
showmountキャッシュ
 a| 
`vserver export-policy cache flush -vserver vserver_name -cache showmount`

|===

