---
permalink: nfs-admin/fpolicy-first-read-first-write-filters-concept.html 
sidebar: sidebar 
keywords: fpolicy, first, read, write, filter, work, nfs 
summary: 外部FPolicyサーバを使用してFPolicyが有効になっており、読み取り / 書き込み処理が監視対象イベントの場合、読み取り / 書き込み要求のトラフィックが多いとNFSクライアント側で応答時間が長くなります。NFSクライアントの場合、FPolicyでfirst-readフィルタとfirst-writeフィルタを使用すると、FPolicy通知の数が減り、パフォーマンスが向上します。 
---
= ONTAP FPolicy のファーストリードフィルタとファーストライトフィルタが NFS でどのように機能するかを学びます
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
外部FPolicyサーバを使用してFPolicyが有効になっており、読み取り / 書き込み処理が監視対象イベントの場合、読み取り / 書き込み要求のトラフィックが多いとNFSクライアント側で応答時間が長くなります。NFSクライアントの場合、FPolicyでfirst-readフィルタとfirst-writeフィルタを使用すると、FPolicy通知の数が減り、パフォーマンスが向上します。

NFSでは、クライアントはファイルのハンドルを取得することでI/Oを実行します。このハンドルは、サーバーとクライアントの再起動後も有効なままになる場合があります。そのため、クライアントはハンドルをキャッシュし、再度ハンドルを取得することなく、そのハンドルに対してリクエストを送信できます。通常のセッションでは、ファイルサーバーに大量の読み取り/書き込みリクエストが送信されます。これらのリクエストすべてに対して通知が生成されると、次のような問題が発生する可能性があります：

* 余計な通知処理のために負荷が増大し、応答時間が長くなる。
* サーバに影響のない通知も含め、多数の通知がFPolicyサーバに送信される。


クライアントから特定のファイルに対する読み取り / 書き込み要求を初めて受信すると、キャッシュ エントリが作成され、読み取り / 書き込みのカウンタが増分されます。この要求は初回読み取り / 書き込み処理とマーキングされ、FPolicyイベントが生成されます。NFSクライアント用のFPolicyフィルタを計画して作成する前に、FPolicyフィルタの基本的な仕組みを理解しておく必要があります。

* first-read：初回読み取りのクライアント要求をフィルタリングします。
+
このフィルタを NFS イベントに使用すると、 `-file-session-io-grouping-count`および `-file-session-io-grouping-duration`設定によって、FPolicy が処理される最初の読み取り要求が決定されます。

* first-write：初回書き込みのクライアント要求をフィルタリングします。
+
このフィルタを NFS イベントに使用すると、 `-file-session-io-grouping-count`および `-file-session-io-grouping-duration`設定によって、FPolicy が処理する最初の書き込み要求が決定されます。



次のオプションがNFSサーバのデータベースに追加されます。

[listing]
----


file-session-io-grouping-count: Number of I/O Ops on a File to Be Clubbed and Considered as One Session
for Event Generation
file-session-io-grouping-duration: Duration for Which I/O Ops on a File to Be Clubbed and Considered as
One Session for Event Generation
----