---
permalink: nfs-admin/handle-superuser-access-requests-concept.html 
sidebar: sidebar 
keywords: how, handle, superuser, access, request 
summary: エクスポートポリシーを設定する際には、ストレージシステムがユーザ ID が 0 のクライアントアクセス要求をスーパーユーザとして受信し、それに応じてエクスポートルールを設定する場合に必要な処理を考慮する必要があります。 
---
= スーパーユーザのアクセス要求を管理します。
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
エクスポートポリシーを設定する際には、ストレージシステムがユーザ ID が 0 のクライアントアクセス要求をスーパーユーザとして受信し、それに応じてエクスポートルールを設定する場合に必要な処理を考慮する必要があります。

UNIX の世界では、ユーザ ID 0 のユーザがスーパーユーザと呼ばれ、通常は root と呼ばれます。このユーザにはシステム上で無制限のアクセス権が与えられています。スーパーユーザ権限の使用は、システムやデータセキュリティの侵害などのいくつかの理由によってリスクを伴う可能性があります。

デフォルトでは、 ONTAP はユーザ ID が 0 のクライアントを匿名ユーザにマッピングします。ただし、エクスポートルールでパラメータを指定すると、ユーザIDが0のクライアントの処理方法をセキュリティタイプに応じて決定できます `- superuser`。パラメータに有効なオプションは次のとおりです `-superuser`。

* `any`
* `none`
+
これは、パラメータを指定しない場合のデフォルト設定 `-superuser`です。

* `krb5`
* `ntlm`
* `sys`


ユーザIDが0のクライアントは、パラメータの設定に応じて2つの方法で処理されます。 `-superuser`

[cols="2*"]
|===
|  `*-superuser*`パラメータとクライアントのセキュリティタイプ | クライアント 


 a| 
一致
 a| 
ユーザ ID 0 でスーパーユーザアクセス権を取得します。



 a| 
一致しません
 a| 
パラメータで指定したユーザIDと、割り当てられた権限を持つ匿名ユーザとしてアクセスを取得します `-anon`。これは、読み取り専用パラメータと読み取り/書き込みパラメータのどちらでオプションが指定されているかに関係あり `none`ません。

|===
クライアントがNTFSセキュリティ形式のボリュームにアクセスするためにユーザID 0を提示し、パラメータがに設定されている `none`場合 `-superuser`、ONTAPは匿名ユーザのネームマッピングを使用して適切なクレデンシャルを取得します。

.例
エクスポートポリシーには、次のパラメータを持つエクスポートルールが含まれています。

* `-protocol` `nfs3`
* `-clientmatch` `10.1.16.0/255.255.255.0`
* `-rorule` `any`
* `-rwrule` `krb5,ntlm`
* `-anon` `127`


クライアント#1は、IPアドレスが10.1.16.207、ユーザIDが746で、NFSv3プロトコルを使用してアクセス要求を送信し、Kerberos v5で認証されます。

クライアント#2は、IPアドレスが10.1.16.211、ユーザIDが0で、NFSv3プロトコルを使用してアクセス要求を送信し、AUTH_SYSで認証されています。

両方のクライアントでクライアントアクセスプロトコルとIPアドレスが一致している。読み取り専用パラメータでは、認証に使用したセキュリティタイプに関係なく、すべてのクライアントに読み取り専用アクセスが許可されます。ただし、読み取り/書き込みアクセス権を取得するのはクライアント#1だけです。これは、認証に承認済みのセキュリティタイプKerberos v5が使用されているためです。

クライアント #2 は、スーパーユーザアクセス権を取得できません。パラメータが指定されていないため、代わりに匿名にマッピングされ `-superuser`ます。つまり、デフォルトで `none`ユーザID 0が匿名にマッピングされ、自動的にマッピングされます。また、クライアント #2 はセキュリティタイプが読み取り / 書き込みパラメータと一致しなかったため、読み取り専用アクセス権のみを取得します。

.例
エクスポートポリシーには、次のパラメータを持つエクスポートルールが含まれています。

* `-protocol` `nfs3`
* `-clientmatch` `10.1.16.0/255.255.255.0`
* `-rorule` `any`
* `-rwrule` `krb5,ntlm`
* `-superuser` `krb5`
* `-anon` `0`


クライアント#1は、IPアドレスが10.1.16.207、ユーザIDが0で、NFSv3プロトコルを使用してアクセス要求を送信し、Kerberos v5で認証されます。

クライアント#2は、IPアドレスが10.1.16.211、ユーザIDが0で、NFSv3プロトコルを使用してアクセス要求を送信し、AUTH_SYSで認証されています。

両方のクライアントでクライアントアクセスプロトコルとIPアドレスが一致している。読み取り専用パラメータでは、認証に使用したセキュリティタイプに関係なく、すべてのクライアントに読み取り専用アクセスが許可されます。ただし、読み取り/書き込みアクセス権を取得するのはクライアント#1だけです。これは、認証に承認済みのセキュリティタイプKerberos v5が使用されているためです。クライアント#2は読み取り/書き込みアクセス権を取得しません。

このエクスポートルールでは、ユーザ ID が 0 のクライアントにスーパーユーザアクセスが許可されています。クライアント#1は、読み取り専用パラメータとパラメータのユーザIDおよびセキュリティタイプと一致しているため、スーパーユーザアクセスを取得します。 `-superuser`クライアント#2のセキュリティタイプが読み取り/書き込みパラメータまたはパラメータと一致しないため、読み取り/書き込みアクセス権もスーパーユーザアクセス権も取得されません。 `-superuser`代わりに、クライアント #2 は匿名ユーザにマッピングされます。この場合、ユーザ ID は 0 です。
