---
permalink: nfs-admin/improve-performance-ldap-directory-searches-task.html 
sidebar: sidebar 
keywords: improve, performance, ldap, directory, netgroup, host, search, ptr, forward, reverse, rfc 5952, export rule, 
summary: LDAP環境がホスト単位のネットグループ検索を許可するように設定されている場合は、この機能を利用するようにONTAPを設定し、ホスト単位のネットグループ検索を実行できます。これにより、ネットグループ検索にかかる時間が大幅に短縮され、ネットグループ検索時のレイテンシによるNFSクライアントアクセスの問題が軽減されます。 
---
= LDAPディレクトリのホスト単位のネットグループ検索のパフォーマンスの向上
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
LDAP環境がホスト単位のネットグループ検索を許可するように設定されている場合は、この機能を利用するようにONTAPを設定し、ホスト単位のネットグループ検索を実行できます。これにより、ネットグループ検索にかかる時間が大幅に短縮され、ネットグループ検索時のレイテンシによるNFSクライアントアクセスの問題が軽減されます。

.開始する前に
LDAPディレクトリにマップが含まれている必要があり `netgroup.byhost`ます。

DNSサーバには、NFSクライアントのフォワード（A）ルックアップレコードとリバース（PTR）ルックアップレコードの両方が含まれている必要があります。

ネットグループでIPv6アドレスを指定する場合は、常にRFC 5952で指定されているとおりに各アドレスを短縮および圧縮する必要があります。

.タスクの内容
NISサーバは、 `netgroup.byuser`、および `netgroup.byhost`という3つの独立したマップにネットグループ情報を格納します `netgroup`。マップと `netgroup.byhost`マップの目的は `netgroup.byuser`、ネットグループの検索速度を上げることです。ONTAPでは、マウントの応答時間を短縮するために、NISサーバ上でホスト単位のネットグループ検索を実行できます。

デフォルトでは、LDAPディレクトリにはNISサーバのようなマップがありません `netgroup.byhost`。ただし、サードパーティのツールを使用すれば、NISマップをLDAPディレクトリにインポートして、ホスト単位の高速ネットグループ検索を有効にすることができます `netgroup.byhost`。ホスト単位のネットグループ検索を許可するようにLDAP環境を設定している場合は、ONTAP LDAPクライアントにマップ名、DN、および検索範囲を設定して、ホスト単位のネットグループ検索を高速化できます `netgroup.byhost`。

ホスト単位のネットグループ検索の結果をより速く受け取ることで、ONTAPクライアントがエクスポートへのアクセスを要求したときに、エクスポートルールをより迅速に処理できるようになります。これにより、ネットグループ検索のレイテンシの問題が原因でアクセスが遅延する可能性が低くなります。

.手順
. LDAPディレクトリにインポートしたNISマップの完全な識別名を取得します `netgroup.byhost`。
+
マップDNは、インポートに使用したサードパーティツールによって異なります。最高のパフォーマンスを得るには、正確なマップDNを指定する必要があります。

. 権限レベルをadvancedに設定します。 `set -privilege advanced`
. Storage Virtual Machine（SVM）のLDAPクライアント設定でホスト単位のネットグループ検索を有効にします。 `vserver services name-service ldap client modify -vserver vserver_name -client-config config_name -is-netgroup-byhost-enabled true -netgroup-byhost-dn netgroup-by-host_map_distinguished_name -netgroup-byhost-scope netgroup-by-host_search_scope`
+
`-is-netgroup-byhost-enabled`{`true` `false`｝LDAPディレクトリのホスト単位のネットグループ検索を有効または無効にします。デフォルトはです `false`。

+
`-netgroup-byhost-dn` `netgroup-by-host_map_distinguished_name`LDAPディレクトリ内のマップの識別名を指定します `netgroup.byhost`。この値は、ホスト単位のネットグループ検索のベースDNを上書きします。このパラメータを指定しない場合、ONTAPは代わりにベースDNを使用します。

+
`-netgroup-byhost-scope`{`base`|`onelevel` `subtree`｝は、ホスト単位のネットグループ検索の検索範囲を指定します。このパラメータを指定しない場合のデフォルトのはです `subtree`。

+
LDAPクライアント設定がまだ存在しない場合は、コマンドを使用して新しいLDAPクライアント設定を作成するときにこれらのパラメータを指定することで、ホスト単位のネットグループ検索を有効にできます `vserver services name-service ldap client create`。

+
[NOTE]
====
ONTAP 9 .2以降では、 `-ldap-servers`フィールドがフィールドに置き換わります `-servers`。この新しいフィールドには、LDAPサーバのホスト名またはIPアドレスを指定できます。

====
. admin権限レベルに戻ります。 `set -privilege admin`


.例
次のコマンドは、「'ldap_corp'」という既存のLDAPクライアント設定を変更し、「'nisMapName="netgroup.byhost"、dc=corp、dc=example、dc=com`」というマップとデフォルトの検索範囲を `subtree`使用して、ホスト単位のネットグループ検索を有効にし `netgroup.byhost`ます。

[listing]
----
cluster1::*> vserver services name-service ldap client modify -vserver vs1 -client-config ldap_corp -is-netgroup-byhost-enabled true -netgroup-byhost-dn nisMapName="netgroup.byhost",dc=corp,dc=example,dc=com
----
.終了後
 `netgroup.byhost`ディレクトリ内のマップと `netgroup`マップは、クライアントアクセスに関する問題を回避するために、常に同期されている必要があります。

.関連情報
https://datatracker.ietf.org/doc/html/rfc5952["IETF RFC 5952 ：『 A Recommendation for IPv6 Address Text Representation 』"]
