---
permalink: nfs-admin/manage-nfsv4-storepool-controls-task.html 
sidebar: sidebar 
keywords: enable, disable, nfsv4, storepool, controls, limit, client, resource, blocked, 
summary: ONTAP 9.13以降、管理者は、クライアントごとのストアプールのリソース制限に達した場合にNFSサーバーがNFSクライアントへのリソースを拒否できるようにすることができます。 
---
= ONTAP NFSv4ストアプールの制限を管理する
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
ONTAP 9.13以降、管理者は、NFSv4サーバがクライアントごとのストアプール リソースの上限に達した場合に、NFSv4クライアントへのリソースの提供を拒否するようにNFSv4サーバを設定できます。クライアントがNFSv4ストアプール リソースを消費しすぎると、NFSv4ストアプール リソースが不足して他のNFSv4クライアントがブロックされる可能性があります。

この機能を有効にすると、ストアプール リソースのアクティブな消費状況をクライアントごとに表示することもできます。これにより、システム リソースを使い果たしているクライアントを特定しやすくなり、クライアントごとにリソース制限を課すことが可能になります。



== 消費済みストアプール リソース数の表示

この `vserver nfs storepool show`コマンドは、消費されたストアプールリソースの数を表示します。ストアプールは、NFSv4クライアントが使用するリソースのプールです。

.手順
. 管理者として、 `vserver nfs storepool show`コマンドを実行して、NFSv4クライアントのストアプール情報を表示します。


.例
以下は、NFSv4クライアントのストアプール情報の例です。

[listing]
----
cluster1::*> vserver nfs storepool show

Node: node1

Vserver: vs1

Data-Ip: 10.0.1.1

Client-Ip Protocol IsTrunked OwnerCount OpenCount DelegCount LockCount

-------------- --------- --------- ---------- ---------- ---------- ---------

10.0.2.1          nfs4.1     true    2 1 0 4

10.0.2.2          nfs4.2     true    2 1 0 4

2 entries were displayed.
----


== ストアプールの上限管理の有効化または無効化

管理者は、次のコマンドを使用して、ストアプールの上限管理を有効または無効にできます。

.手順
. 管理者として、次のいずれかの操作を実行します。
+
[cols="2*"]
|===
| 状況 | 入力するコマンド 


 a| 
ストアプールの上限管理を有効にする
 a| 
`vserver nfs storepool config modify -limit-enforce enabled`



 a| 
ストアプールの上限管理を無効にする
 a| 
`vserver nfs storepool config modify -limit-enforce disabled`

|===




== ブロックされたクライアントのリストを表示する

ストアプールの上限管理を有効にすると、管理者は、クライアントごとに設定されたリソースしきい値に達してブロックされているクライアントを確認できます。管理者は次のコマンドを使用して、ブロックされているクライアントを確認できます。

.手順
.  `vserver nfs storepool blocked-client show`コマンドを使用して、NFSv4のブロックされたクライアント リストを表示します。




== ブロック済みクライアント リストからのクライアントの削除

クライアントごとに設定されたしきい値に達したクライアントは切断され、ブロッククライアント キャッシュに追加されます。管理者は次のコマンドを使用して、ブロッククライアント キャッシュからクライアントを削除できます。キャッシュから削除したクライアントは、ONTAP NFSv4サーバに接続できるようになります。

.手順
.  `vserver nfs storepool blocked-client flush -client-ip <ip address>`コマンドを使用して、ストアプールのブロックされたクライアント キャッシュをフラッシュします。
.  `vserver nfs storepool blocked-client show`コマンドを使用して、クライアントがブロック クライアント キャッシュから削除されたことを確認します。


.例
次の例では、IPアドレスが「10.2.1.1」のブロックされているクライアントを、すべてのノードからフラッシュしています。

[listing]
----
cluster1::*>vserver nfs storepool blocked-client flush -client-ip 10.2.1.1

cluster1::*>vserver nfs storepool blocked-client show

Node: node1

Client IP
----------
10.1.1.1

1 entries were displayed.
----