---
permalink: nfs-admin/modify-credential-cache-time-to-live-reference.html 
sidebar: sidebar 
keywords: reason, modify, nfs, credential, cache, time, live 
summary: NFS クレデンシャルキャッシュの Time-To-Live （ TTL ）の変更が問題の解決に役立つ場合があります。どのような状況がこれに該当するか、またそうした変更がどのような影響を及ぼすかを理解しておく必要があります。 
---
= NFSクレテンシヤルキヤツシユノTime-To-Liveヲヘンコウスルリユ
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
ONTAP は、アクセス高速化とパフォーマンス向上のために、クレデンシャルキャッシュを使用して、 NFS エクスポートアクセスでのユーザ認証に必要な情報を格納します。情報を環境に合わせてカスタマイズするために、クレデンシャルキャッシュに保存する期間を設定できます。

NFS クレデンシャルキャッシュの Time-To-Live （ TTL ）の変更が問題の解決に役立つ場合があります。どのような状況がこれに該当するか、またそうした変更がどのような影響を及ぼすかを理解しておく必要があります。



== 理由

次の状況では、デフォルト TTL の変更を検討してください。

[cols="2*"]
|===
| 問題 | 修正アクション 


 a| 
環境内のネームサーバで ONTAP からの要求の負荷が高いためにパフォーマンスが低下している。
 a| 
キャッシュされている受理および拒否のクレデンシャルに対するTTLを大きくして、ONTAPからネームサーバへの要求数を減らします。



 a| 
ネームサーバ管理者が、以前に拒否されたNFSユーザへのアクセスを許可するように変更を加えました。
 a| 
キャッシュされている拒否のクレデンシャルに対するTTLを短くして、NFSユーザがアクセスできるようにONTAPが新しいクレデンシャルを外部ネームサーバに要求するまでの待機時間を短縮します。



 a| 
ネームサーバ管理者が、以前に許可されていたNFSユーザへのアクセスを拒否する変更を行いました。
 a| 
キャッシュされている受理されたクレデンシャルに対するTTLを短くして、ONTAPが新しいクレデンシャルを外部ネームサーバに要求してNFSユーザがアクセスを拒否されるようになるまでの時間を短縮します。

|===


== 結果

受理されたクレデンシャルと拒否されたクレデンシャルをキャッシュする期間を個別に変更できます。ただし、その利点と欠点の両方に注意する必要があります。

[cols="3*"]
|===
| 状況 | 利点は ... | 欠点は ... 


 a| 
受理のクレデンシャルのキャッシュ時間を長くする
 a| 
ONTAPがクレデンシャルの要求をネームサーバに送信する頻度が低下し、ネームサーバの負荷が軽減されます。
 a| 
以前はアクセスが許可されていたが今後は許可されなくなったNFSユーザに対して、アクセスを拒否するのにかかる時間が長くなります。



 a| 
受理された認証情報のキャッシュ時間を短くする
 a| 
以前はアクセスが許可されていたが今後は許可されなくなったNFSユーザに対して、アクセスを拒否するのにかかる時間が短縮されます。
 a| 
ONTAPがクレデンシャルの要求をネームサーバに送信する頻度が高くなり、ネームサーバの負荷が増大します。



 a| 
拒否されたクレデンシャルのキャッシュ時間を長くします
 a| 
ONTAPがクレデンシャルの要求をネームサーバに送信する頻度が低下し、ネームサーバの負荷が軽減されます。
 a| 
以前はアクセスが許可されていなかったが今後は許可されるようになるNFSユーザにアクセスを許可するのにかかる時間が長くなります。



 a| 
拒否されたクレデンシャルのキャッシュ時間を短くします
 a| 
以前はアクセスが許可されていなかったが今後は許可されるようになったNFSユーザにアクセスを許可するのにかかる時間が短縮されます。
 a| 
ONTAPがクレデンシャルの要求をネームサーバに送信する頻度が高くなり、ネームサーバの負荷が増大します。

|===