---
permalink: nfs-admin/modify-ports-used-nfsv3-services-task.html 
sidebar: sidebar 
keywords: modify, port, nfsv3, service 
summary: ストレージシステム上のNFSサーバは、マウントデーモンやNetwork Lock Managerなどのサービスを使用して、特定のデフォルトネットワークポートを介してNFSクライアントと通信します。ほとんどのNFS環境ではデフォルトポートは正しく機能し、変更は必要ありませんが、NFSv3環境で別のNFSネットワークポートを使用する場合は変更できます。 
---
= NFSv3サービスに使用するポートを変更します。
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
ストレージシステム上のNFSサーバは、マウントデーモンやNetwork Lock Managerなどのサービスを使用して、特定のデフォルトネットワークポートを介してNFSクライアントと通信します。ほとんどのNFS環境ではデフォルトポートは正しく機能し、変更は必要ありませんが、NFSv3環境で別のNFSネットワークポートを使用する場合は変更できます。

.開始する前に
ストレージシステムでNFSポートを変更するには、すべてのNFSクライアントがシステムに再接続する必要があるため、変更を行う前にこの情報をユーザに伝えておく必要があります。

.タスクの内容
NFSマウントデーモン、Network Lock Manager（NLM；ネットワークロックマネージャ）、Network Status Monitor（ネットワークステータスモニタ）、およびNFSクォータデーモンの各サービスで使用されるポートをStorage Virtual Machine（SVM）ごとに設定できます。ポート番号の変更は、TCPとUDPの両方でデータにアクセスするNFSクライアントに影響します。

NFSv4およびNFSv4.1のポートは変更できません。

.手順
. 権限レベルをadvancedに設定します。
+
`set -privilege advanced`

. NFSへのアクセスを無効にします。
+
`vserver nfs modify -vserver vserver_name -access false`

. 特定のNFSサービスのNFSポートを設定します。
+
`vserver nfs modify -vserver vserver_namenfs_port_parameterport_number`

+
[cols="3*"]
|===
| NFS ポートのパラメータ | 説明 | デフォルトポート 


 a| 
`-mountd-port`
 a| 
NFSマウントデーモン
 a| 
635



 a| 
`-nlm-port`
 a| 
ネットワークロックマネージャ
 a| 
4045



 a| 
`-nsm-port`
 a| 
ネットワークステータスモニタ
 a| 
4046



 a| 
`-rquotad-port`
 a| 
NFSクォータデーモン
 a| 
4049

|===
+
デフォルトのポート以外に、使用できるポート番号の範囲は1024~65535です。各NFSサービスは一意のポートを使用する必要があります。

. NFSへのアクセスを有効にします。
+
`vserver nfs modify -vserver vserver_name -access true`

. コマンドを使用し `network connections listening show`て、ポート番号の変更を確認します。
+
の詳細については `network connections listening show`、をlink:https://docs.netapp.com/us-en/ontap-cli/network-connections-listening-show.html["ONTAPコマンド リファレンス"^]参照してください。

. admin権限レベルに戻ります。
+
`set -privilege admin`



.例
次のコマンドは、vs1というSVMでNFSマウントデーモンのポートを1113に設定します。

....
vs1::> set -privilege advanced
Warning: These advanced commands are potentially dangerous; use
         them only when directed to do so by NetApp personnel.
Do you want to continue? {y|n}: y

vs1::*> vserver nfs modify -vserver vs1 -access false

vs1::*> vserver nfs modify -vserver vs1 -mountd-port 1113

vs1::*> vserver nfs modify -vserver vs1 -access true

vs1::*> network connections listening show
Vserver Name     Interface Name:Local Port        Protocol/Service
---------------- -------------------------------  ----------------
Node: cluster1-01
Cluster          cluster1-01_clus_1:7700          TCP/ctlopcp
vs1              data1:4046                       TCP/sm
vs1              data1:4046                       UDP/sm
vs1              data1:4045                       TCP/nlm-v4
vs1              data1:4045                       UDP/nlm-v4
vs1              data1:1113                       TCP/mount
vs1              data1:1113                       UDP/mount
...
vs1::*> set -privilege admin
....