---
permalink: nfs-admin/nfs-client-authentication-concept.html 
sidebar: sidebar 
keywords: ontap, nfs, client, authentication 
summary: NFS クライアントから SVM 上のデータにアクセスするためには、 NFS クライアントが正しく認証されている必要があります。ONTAP では、 UNIX クレデンシャルを設定されたネームサービスに照らしてチェックすることで、そのクライアントを認証します。 
---
= ONTAP による NFS クライアント認証の処理の概要
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
NFS クライアントから SVM 上のデータにアクセスするためには、 NFS クライアントが正しく認証されている必要があります。ONTAP では、 UNIX クレデンシャルを設定されたネームサービスに照らしてチェックすることで、そのクライアントを認証します。

NFS クライアントが SVM に接続すると、 ONTAP は、 SVM のネームサービス設定に応じて複数のネームサービスをチェックし、そのユーザの UNIX クレデンシャルを取得します。ONTAP でチェックできるのは、ローカルの UNIX アカウント、 NIS ドメイン、および LDAP ドメインのクレデンシャルです。ONTAP がユーザを認証できるように、このうちの少なくとも 1 つを設定しておく必要があります。複数 ONTAP のネームサービスと検索順序を指定できます。

UNIX のボリュームセキュリティ形式のみを使用する NFS 環境の場合、この設定だけで NFS クライアントから接続するユーザが認証され、適切なファイルアクセスが提供されます。

mixed、NTFS、またはunifiedのボリュームセキュリティ形式を使用している場合、ONTAPがUNIXユーザをWindowsドメインコントローラで認証するためにはSMBユーザ名を取得する必要があります。これには、ローカルのUNIXアカウントまたはLDAPドメインを使用して個 々 のユーザをマッピングするか、代わりにデフォルトのSMBユーザを使用します。ONTAPが検索するネームサービスの種類と検索順序を指定することも、デフォルトのSMBユーザを指定することもできます。
