---
permalink: nfs-admin/nfsv4-acls-concept.html 
sidebar: sidebar 
keywords: nfsv4, acls, work 
summary: NFSv4 ACL を使用しているクライアントは、システム上のファイルとディレクトリに ACL を設定し、その ACL を表示することができます。ACL が設定されているディレクトリ内にファイルやサブディレクトリを新しく作成すると、新しいファイルやサブディレクトリには、その ACL 内の ACE のうち、該当する継承フラグが指定された ACL エントリ（ ACE ）がすべて継承されます。 
---
= NFSv4 ACL の仕組み
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
NFSv4 ACL を使用しているクライアントは、システム上のファイルとディレクトリに ACL を設定し、その ACL を表示することができます。ACL が設定されているディレクトリ内にファイルやサブディレクトリを新しく作成すると、新しいファイルやサブディレクトリには、その ACL 内の ACE のうち、該当する継承フラグが指定された ACL エントリ（ ACE ）がすべて継承されます。

ファイルやディレクトリが NFSv4 要求によって作成される場合、作成されるファイルやディレクトリの ACL は、ファイル作成要求に ACL が含まれているか、または標準の UNIX ファイルアクセス権限のみが含まれているか、および親ディレクトリに ACL が設定されているかどうかによって異なります。

* 要求に ACL が含まれる場合は、その ACL が使用されます。
* 要求に標準 UNIX ファイルアクセス権限のみが含まれ、親ディレクトリに ACL がある場合、親ディレクトリの ACL の ACE に適切な継承フラグのタグが付けられていれば、それらの ACE が新しいファイルやディレクトリに継承されます。
+
[NOTE]
====
親の ACL は '-v4.0-acl が off' に設定されている場合でも継承されます

====
* 要求に標準の UNIX ファイルアクセス権限のみが含まれ、親ディレクトリに ACL がない場合は、クライアントのファイルモードを使用して標準の UNIX ファイルアクセス権限が設定されます。
* 要求に標準 UNIX ファイルアクセス権限のみが含まれ、親ディレクトリに継承できない ACL がある場合は、モードビットのみを使用して新しいオブジェクトが作成されます。


[NOTE]
====
「 vserver nfs 」または「 vserver export-policy rule 」ファミリーのコマンドで「 -chown-mode 」パラメータが「 restric` 」に設定されている場合、 NFSv4 ACL で設定されたディスク上の権限で root 以外のユーザにファイル所有権の変更が許可されていても、スーパーユーザしかファイル所有権を変更できません。詳細については、関連するマニュアルページを参照してください。

====