---
permalink: nfs-admin/ontap-name-services-concept.html 
sidebar: sidebar 
keywords: ontap, name, service 
summary: ONTAP は、ネームサービスを使用してユーザおよびクライアントに関する情報を取得します。ONTAP は、ストレージシステム上でデータにアクセスしたりストレージシステムを管理したりするユーザの認証や、混在環境でのユーザクレデンシャルのマッピングを行うために、この情報を使用します。 
---
= ONTAP でのネームサービスの使用方法
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
ONTAP は、ネームサービスを使用してユーザおよびクライアントに関する情報を取得します。ONTAP は、ストレージシステム上でデータにアクセスしたりストレージシステムを管理したりするユーザの認証や、混在環境でのユーザクレデンシャルのマッピングを行うために、この情報を使用します。

ストレージシステムを設定するときに、 ONTAP が認証用のユーザクレデンシャルを取得するために使用するネームサービスを指定する必要があります。ONTAP では、次のネームサービスをサポートしています。

* ローカルユーザ（ファイル）
* 外部 NIS ドメイン（ NIS ）
* 外部 LDAP ドメイン（ LDAP ）


を使用します `vserver services name-service ns-switch` ネットワーク情報を検索するソースとソースの検索順序をSVMに設定するコマンドファミリー。これらのコマンドは、と同等の機能を提供します `/etc/nsswitch.conf` UNIXシステム上のファイル。

NFS クライアントが SVM に接続すると、 ONTAP は指定されたネームサービスをチェックして、ユーザの UNIX クレデンシャルを取得します。ネームサービスが正しく設定されていて ONTAP が UNIX クレデンシャルを取得できる場合、 ONTAP はユーザの認証に成功します。

mixed セキュリティ形式の環境では、 ONTAP によるユーザクレデンシャルのマッピングが必要になる場合があります。ONTAP がユーザクレデンシャルを適切にマッピングできるようにするには、環境のネームサービスを適切に設定する必要があります。

ONTAP は、 SVM 管理者アカウントの認証にもネームサービスを使用します。ネームサービススイッチを設定または変更する際にはこの点を念頭に置いて、 SVM 管理者アカウントの認証を誤って無効にしないようにする必要があります。SVM管理ユーザの詳細については、を参照してください link:../authentication/index.html["管理者認証と RBAC"]。
