---
permalink: nfs-admin/ontap-name-services-concept.html 
sidebar: sidebar 
keywords: ontap, name, service 
summary: ONTAPは、ネームサービスを使用してユーザとクライアントに関する情報を取得します。ONTAPは、この情報を使用して、ストレージシステム上でデータにアクセスしたりストレージシステムを管理したりするユーザの認証や、混在環境でのユーザクレデンシャルのマッピングを行います。 
---
= ONTAP がネームサービスを使用する方法を学ぶ
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
ONTAPは、ネームサービスを使用してユーザとクライアントに関する情報を取得します。ONTAPは、この情報を使用して、ストレージシステム上でデータにアクセスしたりストレージシステムを管理したりするユーザの認証や、混在環境でのユーザクレデンシャルのマッピングを行います。

ストレージシステムを設定する場合は、ONTAPが認証用のユーザクレデンシャルを取得するために使用するネームサービスを指定する必要があります。ONTAPは次のネームサービスをサポートしています。

* ローカルユーザ（ファイル）
* 外部NISドメイン（NIS）
* 外部LDAPドメイン（LDAP）


ネットワーク情報を検索するソースやソースの検索順序をSVMで設定するには、コマンドファミリーを使用し `vserver services name-service ns-switch`ます。これらのコマンドは、UNIXシステムのファイルと同等の機能を提供し `/etc/nsswitch.conf`ます。

NFS クライアントが SVM に接続すると、 ONTAP は指定されたネームサービスをチェックして、ユーザの UNIX クレデンシャルを取得します。ネームサービスが正しく設定されていて、ONTAPがUNIXクレデンシャルを取得できる場合、ONTAPはユーザの認証に成功します。

mixedセキュリティ形式の環境では、ONTAPによるユーザクレデンシャルのマッピングが必要になる場合があります。ONTAPでユーザクレデンシャルが適切にマッピングされるようにするには、環境のネームサービスを適切に設定する必要があります。

ONTAP は、 SVM 管理者アカウントの認証にもネームサービスを使用します。ネームサービススイッチを設定または変更する際にはこの点を念頭に置いて、 SVM 管理者アカウントの認証を誤って無効にしないようにする必要があります。SVM管理ユーザの詳細については、を参照してくださいlink:../authentication/index.html["カンリシヤニンシヨウトRBAC"]。
