---
permalink: nfs-admin/ontap-support-nfsv42-concept.html 
sidebar: sidebar 
keywords: ontap, support, nfsv4.2 
summary: ONTAP 9.8 以降では、 NFSv4 4.2 クライアントのアクセスを許可するために、 NFSv4 4.2 プロトコルがサポートされています。 
---
= NFSv4 4.2 の ONTAP サポート
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
ONTAP 9.8 以降では、 NFSv4 4.2 クライアントのアクセスを許可するために、 NFSv4 4.2 プロトコルがサポートされています。

ONTAP 9.9.1 以降では、 NFSv4 4.2 がデフォルトで有効になっています。ONTAP 9.8 では、 Storage Virtual Machine （ SVM ）に NFS サーバを作成するときに「 -v4.1 」オプションを指定して「 enabled 」に設定することで、 v4.2 を有効にすることができます。NFSv4.1 を有効にすると、クライアントが v4.2 としてマウントされた状態で NFSv4.1 の機能を使用することもできます。

以下の NFSv4 4.2 のオプション機能がサポートされます。

* ONTAP 9.9.9 以降では、 NFSv4 4.2 を有効にすると、 とラベルされた必須アクセス制御（ MAC ）がサポートされます。
* NFSv4 4.2 のオプション機能は、 ONTAP の今後のリリースで追加される予定です。




== NFS v4.2 セキュリティラベルを有効にします

ONTAP 9.9..1 以降では、 NFS セキュリティラベルを有効にできます。デフォルトでは無効になっています。

NFS v4.2 セキュリティラベルでは、 ONTAP NFS サーバは必須アクセス制御（ MAC ）対応であり、クライアントから送信された sec_label 属性を保存および取得します。

詳細については、を参照してください https://tools.ietf.org/html/rfc7204["RFC7240"]

[NOTE]
====
NFS v4.2 のセキュリティラベルは、 NDMP ダンプ処理では現在サポートされていません。ファイルまたはディレクトリでセキュリティラベルが検出されると、ダンプは失敗します。

====
.手順
. 権限の設定を advanced に変更します。
+
「特権をアドバンス・レベル」

. セキュリティラベルを有効にする：
+
「 vserver nfs modify -vserver svm_name -v4.2 -seclabel enabled 」を参照してください


