---
permalink: nfs-admin/ontap-secures-file-directory-access-concept.html 
sidebar: sidebar 
keywords: file, restriction 
summary: ONTAPは、SVM上のファイルとディレクトリに対して要求されたアクションを実行する権限がエンティティに与えられているかどうかを判断するために、3つのセキュリティレベルを評価します。アクセスは、3つのセキュリティレベルの評価後に有効な権限によって決定されます。 
---
= ONTAP NAS SVMのファイルベースの制限について学習します
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
ONTAPは、SVM上のファイルとディレクトリに対して要求されたアクションを実行する権限がエンティティに与えられているかどうかを判断するために、3つのセキュリティレベルを評価します。アクセスは、3つのセキュリティレベルの評価後に有効な権限によって決定されます。

どのストレージ オブジェクトにも、最大 3 種類のセキュリティ レイヤーを含めることができます：

* エクスポート（NFS）および共有（SMB）セキュリティ
+
エクスポートおよび共有セキュリティは、特定のNFSエクスポートまたはSMB共有へのクライアント アクセスに適用されます。管理者権限を持つユーザは、SMBクライアントとNFSクライアントからエクスポートおよび共有レベルのセキュリティを管理できます。

* ストレージレベルのアクセス保護ファイルおよびディレクトリ セキュリティ
+
ストレージレベルのアクセス保護セキュリティは、SVMボリュームへのSMBおよびNFSクライアント アクセスに適用されます。NTFSのアクセス権のみがサポートされています。ONTAPがストレージレベルのアクセス保護が適用されているボリューム上のデータにアクセスするUNIXユーザのセキュリティ チェックを行うには、UNIXユーザがボリュームを所有するSVM上のWindowsユーザにマッピングされている必要があります。

+
[NOTE]
====
NFS または SMB クライアントからファイルまたはディレクトリのセキュリティ設定を表示すると、Storage-Level Access Guard セキュリティは表示されません。Storage-Level Access Guard セキュリティは、システム管理者（Windows または UNIX）であっても、クライアントから取り消すことはできません。

====
* NTFS、UNIX、およびNFSv4のネイティブのファイルレベルのセキュリティ
+
ストレージ オブジェクトを表すファイルやディレクトリには、ネイティブのファイルレベルのセキュリティが存在します。ファイルレベルのセキュリティはクライアントから設定できます。ファイル権限は、データへのアクセスにSMBとNFSのどちらを使用するかに関係なく有効です。


