---
permalink: nfs-admin/ontap-support-nfsv42-concept.html 
sidebar: sidebar 
keywords: ontap, support, nfsv4.2, MAC-labelled NFS, extended attributes, xattrs 
summary: NFSv4.2プロトコルがサポートされているのは、NFSv4.2対応クライアントのアクセスを許可するためですONTAP 9。 
---
= ONTAPのNFSv4.2サポートについて
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
ONTAP 9 .8以降では、ONTAPでNFSv4.2プロトコルがサポートされ、NFSv4.2対応クライアントのアクセスが許可されます。

ONTAP 9.9.1以降では、NFSv4.2がデフォルトで有効になっています。ONTAP 9.8では、以下を指定してv4.2を手動で有効にする必要があります。 `-v4.2`オプションを設定して `enabled`ストレージ仮想マシン (SVM) 上に NFS サーバーを作成する場合。NFSv4.1を有効にすると、クライアントはv4.2としてマウントした状態でNFSv4.1の機能を使用することができます。

ONTAPの以降のリリースでは、NFSv4.2のオプション機能のサポートが拡張されています。

[cols="2*"]
|===
| 最初の文字 | NFSv4.2のオプションの機能 


| ONTAP 9 12.1  a| 
* NFS拡張属性
* スパースファイル
* スペースリザベーション




| ONTAP 9 .9.1 | NFSラベルのMandatory Access Control（MAC；必須アクセス制御） 
|===


== NFS v4.2セキュリティラベル

ONTAP 9 .9.1以降では、NFSセキュリティラベルを有効にできます。デフォルトでは無効になっています。

NFS v4.2セキュリティラベルでは、ONTAP NFSサーバは必須アクセス制御（MAC）に対応し、クライアントから送信されたsec_label属性を格納および取得します。

詳細については、を参照してください link:https://tools.ietf.org/html/rfc7204["RFC 7240"^]。

.12.1以降では、ONTAP 9ダンプ処理でNFS v4.2セキュリティラベルがサポートされています。以前のリリースのファイルまたはディレクトリでセキュリティラベルが見つかった場合、ダンプは失敗します。

.手順
. 権限の設定をadvancedに変更します。
+
[source, cli]
----
set -privilege advanced
----
. セキュリティラベルを有効にします。
+
[source, cli]
----
vserver nfs modify -vserver <svm_name> -v4.2-seclabel enabled
----




== NFS拡張属性

ONTAP 9.12.1以降では、NFS拡張属性（xattrs）がデフォルトで有効になっています。

拡張属性は、最新のNFSクライアントで定義され、有効になっている標準のNFS属性です https://tools.ietf.org/html/rfc8276["RFC 8276"^]。ユーザ定義のメタデータをファイルシステムオブジェクトに添付するために使用でき、高度なセキュリティの導入に役立ちます。

NFS拡張属性は、現在のところNDMPダンプ処理ではサポートされていません。ファイルまたはディレクトリで拡張属性が検出されると、ダンプは続行されますが、それらのファイルまたはディレクトリの拡張属性はバックアップされません。

拡張属性を無効にする必要がある場合は、コマンドを使用し `vserver nfs modify -v4.2-xattrs disabled`ます。
