---
permalink: nfs-admin/requirements-configuring-kerberos-concept.html 
sidebar: sidebar 
keywords: requirement, configure, kerberos, nfs 
summary: NFSでKerberosを使用するための設定をシステムで行う前に、ネットワークおよびストレージの環境のいくつかの項目について、適切に設定されていることを確認する必要があります。 
---
= ONTAP NFSでKerberosを設定するための要件
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
NFSでKerberosを使用するための設定をシステムで行う前に、ネットワークおよびストレージの環境のいくつかの項目について、適切に設定されていることを確認する必要があります。

[NOTE]
====
環境を設定する手順は、クライアントで使用しているオペレーティング システム、ドメイン コントローラ、Kerberos、DNSなどのバージョンや種類によって異なります。このドキュメントでは、それらのすべてについては説明していません。詳細については、それぞれのコンポーネントの対応するドキュメントを参照してください。

Windows Server 2008 R2のActive DirectoryおよびLinuxホストを使用する環境でのONTAPとKerberos 5およびNFSv3 / NFSv4の設定方法に関する詳しい例については、テクニカル レポート4073を参照してください。

====
次の項目について事前に設定しておく必要があります。



== ネットワーク環境の要件

* Kerberos
+
KerberosをKey Distribution Center（KDC;キー配布センター）で設定しておく必要があります（たとえば、Windows Active DirectoryベースのKerberosまたはMIT Kerberos）。

+
NFSサーバは、マシン プリンシパルのプライマリ コンポーネントとして `nfs`を使用する必要があります。

* ディレクトリ サービス
+
Active DirectoryやOpenLDAPなどのセキュアなディレクトリ サービスを環境に導入し、SSL / TLS経由のLDAPを使用するように設定する必要があります。

* NTP
+
タイム サーバでNTPを実行している必要があります。これは、時刻のずれによるKerberos認証の失敗を回避するために必要です。

* ドメイン名解決（DNS）
+
それぞれのUNIXクライアントおよびSVM LIFについて、KDCの前方参照ゾーンと逆引き参照ゾーンに適切なサービス レコード（SRV）が登録されている必要があります。すべてのコンポーネントは、DNSで正しく解決できる必要があります。

* ユーザ アカウント
+
各クライアントは Kerberos レルム内にユーザーアカウントを持っている必要があります。NFSサーバーは、マシンプリンシパルのプライマリコンポーネントとして "`nfs`" を使用する必要があります。





== NFSクライアントの要件

* NFS
+
NFSv3またはNFSv4を使用してネットワーク経由で通信するように各クライアントが適切に設定されている必要があります。

+
クライアントでRFC1964およびRFC2203がサポートされている必要があります。

* Kerberos
+
Kerberos認証を使用するように各クライアントが適切に設定されている必要があります。詳細は次のとおりです。

+
** TGS 通信の暗号化が有効になっています。
+
非常にセキュリティ性の高いAES-256。

** TGT 通信に最も安全な暗号化タイプが有効になっています。
** Kerberos 領域とドメインが正しく設定されています。
** GSSが有効。
+
マシンのクレデンシャルを使用する場合：

**  `gssd`を `-n`パラメータを付けて実行しないでください。
**  `kinit`をrootユーザーとして実行しないでください。


* 各クライアントは、最新かつ更新済みバージョンのオペレーティング システムを使用している必要があります。
+
これにより、KerberosでのAES暗号化の互換性と信頼性が最大限確保されます。

* DNS
+
DNSを使用して名前が正しく解決されるように各クライアントが適切に設定されている必要があります。

* NTP
+
各クライアントがNTPサーバと同期されている必要があります。

* ホストとドメインの情報
+
各クライアントの `/etc/hosts`および `/etc/resolv.conf`ファイルには、それぞれ正しいホスト名とDNS情報が含まれている必要があります。

* keytabファイル
+
各クライアントについて、KDCのkeytabファイルが必要です。Realmは大文字で指定する必要があります。最高レベルのセキュリティを得るために、暗号化タイプをAES-256にする必要があります。

* オプション：パフォーマンスを最大限に高めるには、ローカル エリア ネットワークとの通信用とストレージ ネットワークとの通信用に、少なくとも2つのネットワーク インターフェイスを設定します。




== ストレージ システムの要件

* NFSライセンス
+
ストレージ システムに有効なNFSライセンスがインストールされている必要があります。

* CIFSライセンス
+
CIFSライセンスはオプションです。マルチプロトコルのネーム マッピングを使用する環境で、Windowsクレデンシャルのチェックを行う場合にのみ必要になります。純粋なUNIXのみの環境では必要ありません。

* SVM
+
システムでSVMを少なくとも1つ設定しておく必要があります。

* SVMでのDNS
+
各SVMでDNSを設定しておく必要があります。

* NFS サーバ
+
SVMでNFSを設定しておく必要があります。

* AES暗号化
+
最高レベルのセキュリティを得るために、KerberosでAES-256暗号化のみを許可するようにNFSサーバを設定する必要があります。

* SMB サーバ
+
マルチプロトコル環境の場合は、SVMでSMBを設定しておく必要があります。SMBサーバはマルチプロトコルのネーム マッピングに必要です。

* ボリューム
+
SVMで使用するルート ボリュームと少なくとも1つのデータ ボリュームを設定しておく必要があります。

* ルート ボリューム
+
SVMのルート ボリュームを次のように設定しておく必要があります。

+
[cols="2*"]
|===
| Name | 設定 


 a| 
セキュリティ形式
 a| 
UNIX



 a| 
UID
 a| 
rootまたはID 0



 a| 
GID
 a| 
rootまたはID 0



 a| 
UNIX権限
 a| 
777

|===
+
ルート ボリュームとは異なり、データ ボリュームのセキュリティ形式は任意に設定してかまいません。

* UNIXグループ
+
SVMで次のUNIXグループを設定しておく必要があります。

+
[cols="2*"]
|===
| グループ名 | グループID 


 a| 
daemon
 a| 
1



 a| 
root
 a| 
0



 a| 
pcuser
 a| 
65534（SVMを作成すると自動的に作成されます）

|===
* UNIXユーザ
+
SVMで次のUNIXユーザを設定しておく必要があります。

+
[cols="4*"]
|===
| ユーザ名 | ユーザーID | プライマリ グループID | コメント 


 a| 
nfs
 a| 
500
 a| 
0
 a| 
GSS INITフェーズで必要

NFSクライアント ユーザのSPNの最初のコンポーネントがユーザとして使用されます。



 a| 
pcuser
 a| 
65534
 a| 
65534
 a| 
NFSとCIFSのマルチプロトコルで必要

SVMの作成時に、ONTAPによって自動的に作成されてpcuserグループに追加されます。



 a| 
root
 a| 
0
 a| 
0
 a| 
マウントに必要

|===
+
NFSクライアント ユーザのSPNに対するKerberos-UNIXネーム マッピングがある場合は、nfsユーザは必要ありません。

* エクスポート ポリシーとエクスポート ルール
+
ルートボリューム、データボリューム、およびqtreeに必要なエクスポート ルールを含むエクスポート ポリシーを設定しておく必要があります。SVMのすべてのボリュームがKerberos経由でアクセスされる場合は、ルートボリュームのエクスポート ルール オプション `-rorule`、 `-rwrule`、および `-superuser`を `krb5`、 `krb5i`、または `krb5p`に設定できます。

* Kerberos-UNIXネーム マッピング
+
NFSクライアント ユーザのSPNによって識別されたユーザにroot権限を持たせる場合は、rootに対するネーム マッピングを作成する必要があります。



.関連情報
https://www.netapp.com/pdf.html?item=/media/19371-tr-4073.pdf["NetAppテクニカル レポート4073: 『Secure Unified Authentication』"^]

https://mysupport.netapp.com/matrix["NetApp Interoperability Matrix Tool"^]

link:../system-admin/index.html["システム管理"]

link:../volumes/index.html["論理ストレージ管理"]
