---
permalink: nfs-admin/security-types-client-access-levels-concept.html 
sidebar: sidebar 
keywords: security, type, determine, client, access, level 
summary: クライアントの認証に使用されるセキュリティタイプは、エクスポートルールで特別な役割を果たします。クライアントがボリュームまたは qtree にアクセスする際のレベルがセキュリティタイプによってどのように決定されるかについて理解しておく必要があります。 
---
= セキュリティタイプによるクライアントアクセスレベルの決定方法
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
クライアントの認証に使用されるセキュリティタイプは、エクスポートルールで特別な役割を果たします。クライアントがボリュームまたは qtree にアクセスする際のレベルがセキュリティタイプによってどのように決定されるかについて理解しておく必要があります。

アクセスレベルには、次の 3 つがあります。

. 読み取り専用です
. 読み書き可能です
. superuser （ユーザ ID が 0 のクライアントの場合）


セキュリティタイプに基づくアクセスレベルはこの順序で評価されるため、エクスポートルールでアクセスレベルパラメータを作成するときは、次のルールに従う必要があります。

[cols="2*"]
|===
| クライアントに必要なアクセスレベル | クライアントのセキュリティタイプと一致する必要があるアクセスパラメータ 


 a| 
標準ユーザの読み取り専用
 a| 
読み取り専用です (`-rorule`)



 a| 
標準ユーザの読み取り / 書き込み
 a| 
読み取り専用です (`-rorule`）および読み書き可能です (`-rwrule`)



 a| 
スーパーユーザの読み取り専用です
 a| 
読み取り専用です (`-rorule`）および `-superuser`



 a| 
スーパーユーザの読み取り / 書き込み
 a| 
読み取り専用です (`-rorule`）および読み書き可能です (`-rwrule`）および `-superuser`

|===
次に、これらの 3 つのアクセスパラメータのそれぞれで有効なセキュリティタイプを示します。

* `any`
* `none`
* `never`
+
このセキュリティタイプは、では使用できません `-superuser` パラメータ

* `krb5`
* `krb5i`
* `krb5p`
* `ntlm`
* `sys`


クライアントのセキュリティタイプを 3 つの各アクセスパラメータと照合したときの結果としては、次の 3 つが考えられます。

[cols="2*"]
|===
| クライアントのセキュリティタイプ | クライアント 


 a| 
アクセスパラメータで指定されたタイプと一致する。
 a| 
独自のユーザ ID を使用して、そのレベルのアクセス権を取得します。



 a| 
指定されたタイプと一致しないが、アクセスパラメータにオプションが含まれる `none`。
 a| 
は、指定されたユーザIDを持つ匿名ユーザとして、そのレベルのアクセス権を取得します `-anon` パラメータ



 a| 
指定されたタイプと一致しないが、アクセスパラメータにオプションが含まれていない `none`。
 a| 
は、そのレベルのアクセス権を取得しません。には適用されません `-superuser` パラメータ。常にが含まれるからです `none` 指定されていない場合も同様です。

|===
.例
エクスポートポリシーに、次のパラメータが指定されたエクスポートルールが含まれています。

* `-protocol` `nfs3`
* `-clientmatch` `10.1.16.0/255.255.255.0`
* `-rorule` `any`
* `-rwrule` `sys,krb5`
* `-superuser` `krb5`


クライアント #1 は、 IP アドレスが 10.1.16.207 、ユーザ ID が 0 で、 NFSv3 プロトコルを使用してアクセス要求を送信し、 Kerberos v5 で認証されます。

クライアント #2 は、 IP アドレスが 10.1.16.211 、ユーザ ID が 0 で、 NFSv3 プロトコルを使用してアクセス要求を送信し、 AUTH_SYS で認証されます。

クライアント #3 は、 IP アドレスが 10.1.16.234 、ユーザ ID が 0 で、 NFSv3 プロトコルを使用してアクセス要求を送信し、認証は行われていません（ AUTH_NONE ）。

3 つすべてのクライアントで、クライアントアクセスプロトコルと IP アドレスは一致しています。読み取り専用パラメータでは、セキュリティタイプに関係なく、読み取り専用アクセスがすべてのクライアントに許可されています。読み取り / 書き込みパラメータでは、読み取り / 書き込みアクセスが、 AUTH_SYS または Kerberos v5 で認証された、自身のユーザ ID を持つクライアントに許可されています。スーパーユーザパラメータでは、スーパーユーザアクセスが、 Kerberos v5 で認証された、ユーザ ID が 0 のクライアントに許可されています。

したがって、クライアント #1 は、 3 つすべてのアクセスパラメータに一致するため、スーパーユーザの読み取り / 書き込みアクセス権を取得します。クライアント #2 は、読み取り / 書き込みアクセス権を取得しますが、スーパーユーザアクセス権は取得できません。クライアント #3 は、読み取り専用アクセス権を取得しますが、スーパーユーザアクセス権は取得できません。
