---
permalink: nfs-admin/support-vmware-vstorage-over-nfs-concept.html 
sidebar: sidebar 
keywords: support, vmware, vStorage, nfs 
summary: ONTAP は、 NFS 環境で特定の VMware vStorage API for Array Integration （ VAAI ）機能をサポートしています。 
---
= VMware vStorage over NFS がサポートされるようになりました
:icons: font
:imagesdir: ../media/


[role="lead"]
ONTAP は、 NFS 環境で特定の VMware vStorage API for Array Integration （ VAAI ）機能をサポートしています。



== サポートされている機能

次の機能がサポートされます。

* コピーオフロード
+
ESXi ホストで、仮想マシンや仮想マシンディスク（ VMDK ）のコピーを、ホストを介さずにソースとデスティネーションのデータストア間で直接実行できます。これにより、 ESXi ホストの CPU サイクルやネットワーク帯域幅を節約できます。ソースボリュームがスパースボリュームの場合、コピーオフロードでスペース効率が保持されます。

* スペースリザベーション
+
スペースをリザーブして VMDK ファイル用のストレージスペースを確保します。





== 制限

NFS で VMware vStorage を使用する際には、次の制限事項があります。

* 次の場合にコピーオフロード処理が失敗することがあります。
+
** ソースボリュームまたはデスティネーションボリュームで wafliron を実行中に、ボリュームが一時的にオフラインになっている
** ソースボリュームまたはデスティネーションボリュームを移動しているとき
** ソースまたはデスティネーションの LIF を移動しているとき
** テイクオーバーまたはギブバック処理を実行しているとき
** スイッチオーバーまたはスイッチバック処理を実行しているとき


* 次のシナリオでは、ファイルハンドル形式の違いが原因でサーバ側のコピーが失敗する可能性があります。
+
qtree のエクスポートを現在行っているか、以前行っていた SVM から、これまでに qtree をエクスポートしたことがない SVM へのデータのコピーを試みます。上記の制限を回避するために、デスティネーション SVM で少なくとも 1 つの qtree をエクスポートすることができます。



* 関連情報 *

https://kb.netapp.com/Advice_and_Troubleshooting/Data_Storage_Software/ONTAP_OS/What_VAAI_offloaded_operations_are_supported_by_Data_ONTAP%3F["Data ONTAP では、 VAAI オフロード処理はどのようにサポートされていますか。"]
