---
permalink: nfs-admin/troubleshoot-name-service-issues-task.html 
sidebar: sidebar 
keywords: troubleshoot, name, service, issue 
summary: ネーム サービスの問題が原因でクライアントでアクセス エラーが発生した場合は、vserver services name-service getxxbyyy コマンド ファミリを使用してさまざまなネーム サービス検索を手動で実行し、検索の詳細と結果を調べてトラブルシューティングに役立てることができます。 
---
= ONTAP NAS SVMのネーム サービスの問題のトラブルシューティング
:hardbreaks:
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
名前サービスの問題によりクライアントでアクセス障害が発生した場合、 `vserver services name-service getxxbyyy`コマンド ファミリを使用してさまざまな名前サービス検索を手動で実行し、検索の詳細と結果を調べてトラブルシューティングに役立てることができます。

.タスク概要
* 各コマンドでは、次の情報を指定できます。
+
** 検索を実行するノードまたはStorage Virtual Machine（SVM）の名前。
+
特定のノードまたはSVMでネーム サービス ルックアップをテストして、ネーム サービス設定の問題の調査対象を絞り込むことができます。

** 検索に使用されたソースを表示するかどうか。
+
適切なソースが使用されたかどうかをチェックできます。



* ルックアップを実行するサービスは、設定されているネーム サービス スイッチの順序に基づいて選択されます。
* これらのコマンドはadvanced権限レベルで使用できます。


.手順
. 次のいずれかを実行します。


|===


| ...を取得するには | 使用するコマンド 


 a| 
ホスト名のIPアドレス
 a| 
`vserver services name-service getxxbyyy getaddrinfo`  `vserver services name-service getxxbyyy gethostbyname`（IPv4アドレスのみ）



 a| 
グループのメンバー（グループIDを指定）
 a| 
`vserver services name-service getxxbyyy getgrbygid`



 a| 
グループのメンバー（グループ名を指定）
 a| 
`vserver services name-service getxxbyyy getgrbyname`



 a| 
ユーザが属しているグループのリスト
 a| 
`vserver services name-service getxxbyyy getgrlist`



 a| 
IPアドレスのホスト名
 a| 
`vserver services name-service getxxbyyy getnameinfo`  `vserver services name-service getxxbyyy gethostbyaddr`（IPv4アドレスのみ）



 a| 
ユーザ情報（ユーザ名を指定）
 a| 
`vserver services name-service getxxbyyy getpwbyname` `-use-rbac`パラメータを `true`として指定することで、RBACユーザの名前解決をテストできます。



 a| 
ユーザ情報（ユーザIDを指定）
 a| 
`vserver services name-service getxxbyyy getpwbyuid` `-use-rbac`パラメータを `true`として指定することで、RBACユーザの名前解決をテストできます。



 a| 
クライアントのネットグループ メンバーシップ
 a| 
`vserver services name-service getxxbyyy netgrp`



 a| 
クライアントのネットグループ メンバーシップ（ホスト単位のネットグループ検索を使用）
 a| 
`vserver services name-service getxxbyyy netgrpbyhost`

|===
次の例は、ホストacast1.eng.example.comのIPアドレスを取得することでSVM vs1のDNSルックアップをテストします。

[listing]
----
cluster1::*> vserver services name-service getxxbyyy getaddrinfo -vserver vs1 -hostname acast1.eng.example.com -address-family all -show-source true
Source used for lookup: DNS
Host name: acast1.eng.example.com
Canonical Name: acast1.eng.example.com
IPv4: 10.72.8.29
----
次の例は、UIDが501768のユーザのユーザ情報を取得することでSVM vs1のNISルックアップをテストします。

[listing]
----
cluster1::*> vserver services name-service getxxbyyy getpwbyuid -vserver vs1 -userID 501768 -show-source true
Source used for lookup: NIS
pw_name: jsmith
pw_passwd: $1$y8rA4XX7$/DDOXAvc2PC/IsNFozfIN0
pw_uid: 501768
pw_gid: 501768
pw_gecos:
pw_dir: /home/jsmith
pw_shell: /bin/bash
----
次の例は、ldap1というユーザのユーザ情報を取得することでSVM vs1のLDAPルックアップをテストします。

[listing]
----
cluster1::*> vserver services name-service getxxbyyy getpwbyname -vserver vs1 -username ldap1 -use-rbac false -show-source true
Source used for lookup: LDAP
pw_name: ldap1
pw_passwd: {crypt}JSPM6yc/ilIX6
pw_uid: 10001
pw_gid: 3333
pw_gecos: ldap1 user
pw_dir: /u/ldap1
pw_shell: /bin/csh
----
次の例は、クライアントdnshost0がネットグループlnetgroup136のメンバーであるかどうかを調べることでSVM vs1のネットグループ検索をテストします。

[listing]
----
cluster1::*> vserver services name-service getxxbyyy netgrp -vserver vs1 -netgroup lnetgroup136 -client dnshost0 -show-source true
Source used for lookup: LDAP
dnshost0 is a member of lnetgroup136
----
. 実行したテストの結果を分析し、必要な措置を取ります。
+
[cols="2*"]
|===
| もし... | ...を確認してください。 


 a| 
ホスト名またはIPアドレスのルックアップに失敗したか、正しくない結果が返された
 a| 
DNS設定



 a| 
正しくないソースでルックアップが実行された
 a| 
ネーム サービス スイッチの設定



 a| 
ユーザまたはグループのルックアップに失敗したか、正しくない結果が返された
 a| 
** ネーム サービス スイッチの設定
** ソースの設定（ローカル ファイル、NISドメイン、LDAPクライアント）
** ネットワーク設定（LIF、ルートなど）




 a| 
ホスト名のルックアップに失敗したかタイムアウトになり、DNSの短縮名（例：host1）がDNSサーバで解決されない
 a| 
トップレベル ドメイン（TLD）クエリのDNS設定。 `-is-tld-query-enabled false`オプションを `vserver services name-service dns modify`コマンドに使用して、TLDクエリを無効にすることができます。

|===


.関連情報
https://www.netapp.com/pdf.html?item=/media/16328-tr-4668pdf.pdf["NetAppテクニカル レポート4668：『Name Services Best Practices Guide』"^]
