---
permalink: nfs-admin/verify-name-service-connections-task.html 
sidebar: sidebar 
keywords: verify, name, service, connection, dns, ldap, checker, check, configuration, configure 
summary: DNSおよびLDAPネームサーバがONTAPに接続されていることを確認できます。これらのコマンドは管理者権限レベルで使用できます。 
---
= ONTAP NAS SVMのネーム サービス接続を確認する
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
DNSおよびLightweight Directory Access Protocol（LDAP）ネームサーバがONTAPに接続されていることを確認できます。これらのコマンドは管理者権限レベルで使用できます。

.タスク概要
DNSまたはLDAPネーム サービスの設定が有効かどうかは、必要時にネーム サービス設定チェックを使用して確認できます。この検証チェックは、コマンドラインまたはSystem Managerで実行できます。

DNS設定の場合、すべてのサーバがテストされ、動作している必要があり、設定が有効とみなされます。LDAP設定の場合、いずれかのサーバが稼働していれば設定は有効です。ネーム サービス コマンドは、 `skip-config-validation`フィールドがtrue（デフォルトはfalse）でない限り、設定チェッカーを適用します。

.手順
. 適切なコマンドを使用してネーム サービスの設定を確認します。設定されているサーバのステータスがUIに表示されます。
+
|===


| 確認するには... | 使用するコマンド 


 a| 
DNSの設定ステータス
 a| 
`vserver services name-service dns check`



 a| 
LDAPの設定ステータス
 a| 
`vserver services name-service ldap check`

|===
+
[listing]
----
cluster1::> vserver services name-service dns check -vserver vs0

Vserver         Name Server     Status  Status Details
--------------  --------------- ------- -------------------------
 vs0            10.11.12.13     up      Response time (msec): 55
 vs0            10.11.12.14     up      Response time (msec): 70
 vs0            10.11.12.15     down    Connection refused.
+---------------------------------------------------------------+
----
+
[listing]
----
cluster1::> vserver services name-service ldap check -vserver vs0

| Vserver: vs0                                                |
| Client Configuration Name: c1                               |
| LDAP Status: up                                             |
| LDAP Status Details: Successfully connected to LDAP server "10.11.12.13".                                              |
----
+
設定されているサーバ（name-servers/ldap-servers）の少なくとも1つが到達可能でサービスを提供していれば、設定の検証は成功です。到達不能なサーバがある場合、警告が表示されます。


