---
sidebar: sidebar 
permalink: anti-ransomware/pause-task.html 
keywords: anti-ransomware, ransomware, pause anti-ransomware, pause anti-ransomware to exclude workload events 
summary: 異常なワークロードイベントが発生すると予想される場合は、ランサムウェア対策分析を一時的に一時的に停止して再開できます。 
---
= ランサムウェア対策を一時停止して、ワークロードイベントを分析対象から除外します
:toc: macro
:hardbreaks:
:toclevels: 1
:allow-uri-read: 
:toc: 
:toclevels: 1
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/
:toc-position: content


[role="lead"]
異常なワークロードイベントが発生すると予想される場合は、ランサムウェア対策分析を一時的に一時的に停止して再開できます。

.必要なもの
* ランサムウェア対策は学習モードまたはアクティブモードで実行されています。


ランサムウェア対策の一時停止中は、イベントはログに記録されず、新規書き込みの処理も行われません。ただし、分析処理はバックグラウンドで以前のログに対して続行されます。


NOTE: ランサムウェア対策無効化機能を使用して分析を一時停止しないでください。これにより、ボリュームでランサムウェア対策が無効になり、学習されたワークロードの動作に関する既存の情報がすべて失われます。これには学習期間の再開が必要です。



== System Manager の手順の略

. [* Storage] > [Volumes] をクリックし、ランサムウェア対策を一時停止するボリュームを選択します。
. Volumes Overview の Security タブで、 [Anti-Ransomware （ランサムウェア対策） ] ボックスの * Pause anti-Ransomware * （ランサムウェア対策の一時停止）をクリックします。




== CLI 手順の略

ボリュームでランサムウェアからの保護を一時停止します。

「 Security anti-Ransomware volume pause - vserver_svm_name_-volume_vol_name _ 」を実行します

処理を再開するには、 resume パラメータを使用します。

「 Security anti-Ransomware volume resume -vserver _svm_name_-volume_name_` 」をクリックします
