---
sidebar: sidebar 
permalink: anti-ransomware/switch-learning-to-active-mode.html 
keywords: ransomware, arp, mode, switch, active, learning, autonomous ransomware protection 
summary: NAS環境のARP 9.15.1以前では、ARP対応ボリュームを学習モードからアクティブモードに手動または自動で切り替えます。 
---
= 学習期間後にONTAP ARPでアクティブモードに切り替える
:allow-uri-read: 


[role="lead"]
NAS環境では、ARPが有効になっているボリュームを手動または自動で学習モードからアクティブモードに切り替えます。ONTAP 9.15.1以前でARPを使用している場合、またはONTAP 9.17.1以前のFlexGroupボリューム上でARPが実行されている場合は、モードを切り替える必要があります。

ARPが推奨される最低30日間の学習モードの実行を完了したら、手動でアクティブ モードに切り替えることができます。ONTAP 9.13.1以降では、ARPによって最適な学習期間が自動的に決定され、30日が経過しなくても自動的に切り替えが行われる場合があります。

ARP/AI保護機能付きARPを使用している場合、ARPは自動的にアクティブになります。学習期間は必要ありません。


NOTE: 既存のボリュームの場合、どちらのモードでも対象となるのは新しく書き込まれたデータだけで、ボリューム内の既存のデータは対象外です。それまでの正常なデータ トラフィックの特性は、ボリュームのARPを有効にしたあとの新しいデータに基づいて推定されるため、既存のデータはスキャンも分析もされません。



== 学習期間後のアクティブ モードへの手動切り替え

ONTAP 9.10.1～9.15.1（FlexGroupボリュームを使用するONTAP 9.17.1以前）の場合、学習期間が完了した後、System ManagerまたはONTAP CLIを使用して、ARP学習モードからアクティブモードに手動で移行できます。

.タスク概要
この手順で説明する学習期間後のアクティブモードへの手動移行は、NAS環境に固有のものです。

.手順
System ManagerまたはONTAP CLIを使用して、学習モードからアクティブモードに切り替えることができます。

[role="tabbed-block"]
====
.System Manager
--
. *ストレージ > ボリューム*を選択し、アクティブモードの準備ができているボリュームを選択します。
. *ボリューム*概要の*セキュリティ*タブで、ランサムウェア対策ボックスの*アクティブモードに切り替える*を選択します。
. *ランサムウェア対策*ボックスでボリュームのARP状態を確認できます。


--
.CLI
--
. 保護されたボリュームを変更してアクティブモードに切り替えます（まだ自動的に行われていない場合）：
+
[source, cli]
----
security anti-ransomware volume enable -volume <vol_name> -vserver <svm_name>
----
+
modify volumeコマンドを使用して、アクティブ モードに切り替えることもできます。

+
[source, cli]
----
volume modify -volume <vol_name> -vserver <svm_name> -anti-ransomware-state enabled
----
. ボリュームのARPの状態を確認します。
+
[source, cli]
----
security anti-ransomware volume show
----


--
====


== 学習モードからアクティブ モードへの自動切り替え

ONTAP 9.13.1以降、アダプティブ ラーニングがARP分析に追加され、学習モードからアクティブ モードへの切り替えは自動的に行われます。学習モードからアクティブ モードへARPを自動で切り替えるかどうかは、次のオプションの設定に基づいて決まります。

[listing]
----
 -anti-ransomware-auto-switch-minimum-incoming-data-percent
 -anti-ransomware-auto-switch-duration-without-new-file-extension
 -anti-ransomware-auto-switch-minimum-learning-period
 -anti-ransomware-auto-switch-minimum-file-count
 -anti-ransomware-auto-switch-minimum-file-extension
----
自動切り替えが有効になっている場合、すべての条件が満たされていなくても、最大30日後にボリュームは自動的にアクティブモードに切り替わります。この30日間の制限は固定されており、変更できません。

デフォルト値を含む ARP 設定オプションの詳細については、link:https://docs.netapp.com/us-en/ontap-cli/security-anti-ransomware-volume-auto-switch-to-enable-mode-show.html["ONTAPコマンド リファレンス"^]を参照してください。

.関連情報
* link:https://docs.netapp.com/us-en/ontap-cli/search.html?q=security+anti-ransomware+volume["セキュリティ・アンチランサムウェア・ボリューム"^]

