---
sidebar: sidebar 
permalink: anti-ransomware/use-cases-restrictions-concept.html 
keywords: anti-ransomware use cases and restrictions, anti-ransomware performance and frequency considerations, anti-ransomware workloads, anti-ransomware volume requirements, anti-ransomware performance, volumes, anti-ransomware encryption, anti-ransomware system configurations, autonomous ransomware protection, arp 
summary: 現在のリリースでは、ランサムウェア攻撃からの保護が NAS 環境に最も適しています。その他の環境は、今後のリリースでサポートされる予定です。 
---
= 自動ランサムウェア対策による保護のユースケースと考慮事項
:toc: macro
:hardbreaks:
:toclevels: 1
:allow-uri-read: 
:toc: 
:toclevels: 1
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/
:toc-position: content


[role="lead"]
ONTAP プラットフォームのサポート：

* ONTAP 9.10.1以降のすべてのオンプレミスONTAP システムで、Autonomous Ransomware Protection（ARP）機能を利用できます。
* ONTAP Select 9.13.1以降では、ONTAP SelectでARPを使用できます。


適切なワークロード：

* NFS ストレージ上のデータベース
* Windows または Linux のホームディレクトリ
+
学習期間中に検出されなかった拡張子のファイルが作成される可能性があるため、このワークロードでは誤検出の可能性が高くなります。

* 画像とビデオ
+
たとえば、医療記録や Electronic Design Automation （ EDA ）データなどです。



ONTAP 9.12.1以降では、ARPは次の構成で使用できます。

* ボリュームはSnapMirrorで保護されます
* SVMはSnapMirrorで保護されます
* 移行が有効になっているSVM（SVMのデータ移動）


不適切なワークロード：

* ファイルの作成または削除の頻度が高いワークロード（テスト / 開発ワークロードなど、数秒で数十万個のファイルを削除）
* ARPは、ファイルの作成、名前変更、または削除アクティビティの異常な急増を認識できるかどうかに依存します。アプリケーション自体がファイルアクティビティのソースである場合、ランサムウェアのアクティビティと効果的に区別することはできません
* アプリケーションまたはホストがデータARPを暗号化するワークロードは、受信データを暗号化データまたは暗号化なしデータと区別することによって異なります。アプリケーション自体がデータを暗号化している場合は、機能の有効性が低下します。ただし、この機能は、ファイルアクティビティ（削除、上書き、作成、または新しいファイル拡張子を使用した作成または名前変更）およびファイルタイプに基づいて動作します。


サポートされないシステム構成：

* SAN 環境
* ONTAP S3 環境
* NFS 上の VMDK です


ボリューム要件：

* 100% 未満
* ジャンクションパスがアクティブである必要があります


サポートされないボリュームタイプ：

* ボリュームをオフラインにします
* 制限されたボリューム
* SnapLock ボリューム
* FlexGroup ボリューム（ONTAP 9.13.1以降ではFlexGroup ボリュームがサポートされます）
* FlexCacheボリューム（ARPは元のFlexVolボリュームではサポートされますが、キャッシュボリュームではサポートされません）
* SAN-only ボリューム
* 停止しているStorage VMのボリューム
* Storage VMのルートボリューム




== SnapMirrorとARPの相互運用性

ONTAP 9.12.1以降では、SnapMirrorデスティネーションボリュームでARPがサポートされます。SnapMirrorソースボリュームがARP対応の場合、SnapMirrorデスティネーションボリュームには、ARP設定状態（ラーニング、有効化など）、ARPトレーニングデータ、およびARPで作成されたソースボリュームのSnapshotが自動的に取得されます。明示的な有効化は必要ありません。

デスティネーションボリュームは読み取り専用（RO）Snapshotコピーで構成されていますが、データに対してARP処理は実行されません。ただし、SnapMirrorデスティネーションボリュームが読み書き可能（rw）に変換されると、ARPはRW変換されたデスティネーションボリュームで自動的に有効になります。デスティネーションボリュームでは、ソースボリュームにすでに記録されている情報に加えて、ラーニング手順 を追加する必要はありません。

ONTAP 9.10.1および9.11.1では、ARP設定の状態、トレーニングデータ、およびSnapshotコピーがソースボリュームからデスティネーションボリュームに転送されません。したがって、SnapMirrorデスティネーションボリュームがRWに変換されると、変換後にデスティネーションボリュームのARPがラーニングモードで明示的に有効になる必要があります。



== ARPのパフォーマンスと周波数に関する考慮事項

ARP機能は、スループットおよびピークIOPSで測定されたシステムパフォーマンスへの影響を最小限に抑えることができます。ARP機能の影響は、ボリュームのワークロードに大きく依存します。一般的なワークロードまたは一般的なワークロードについては、以下の構成の制限が推奨されます。

[cols="30,20,30"]
|===
| ワークロードの特性 | ノードあたりの推奨されるボリューム数の上限 | ノード単位のボリューム制限を超えたときのパフォーマンスの低下：[*] 


| 大量の読み取り処理や、データの圧縮が可能です。 | 150 | 最大IOPSの4% 


| 大量の書き込みが発生し、データを圧縮することはできません。 | 60 | 最大IOPSの10% 
|===
合格：[*]推奨制限を超過したボリュームの数に関係なく、システムパフォーマンスはこれらの割合を超えて低下することはありません。

ARP分析は優先順位が付けられた順に実行されるため、保護されたボリュームの数が増えるにつれて、各ボリュームで分析がより頻繁に実行されます。



== ランサムウェアが検出された場合の自動 Snapshot コピーの動作

可能なかぎり最適なリカバリポイントを取得するために、ファイルの異常アクティビティを検出するとすぐに、ARPによって自動Snapshotコピーが作成されます。しかし、ARPはすぐにアラートにフラグを付けているわけではなく、疑わしいアクティビティがランサムウェアのプロファイルと一致していることを分析で確認してからアラートを生成する必要があります。この処理には最大 60 分かかることがあります。分析によってアクティビティが疑わしいと判断された場合はアラートは生成されませんが、自動的に作成された Snapshot コピーは少なくとも 2 日間ファイルシステムに存在したままとなります。

ONTAP 9.11.1以降では、ランサムウェア攻撃の疑いがある場合に自動的に生成されるARP Snapshotコピーの数と保持期間を制御できます。方法をご確認ください link:modify-automatic-shapshot-options-task.html["自動Snapshotコピーのオプションを変更します"]。



== Autonomous Ransomware Protection（ARP）で保護されたボリュームを使用した複数管理者による検証

ONTAP 9.13.1以降では、マルチ管理者検証（MAV）をイネーブルにしてARPによるセキュリティを強化できます。MAVを使用すると、少なくとも2人以上の認証された管理者が、保護されたボリュームでARPをオフにしたり、ARPを一時停止したり、疑わしい攻撃をfalse positiveとしてマークしたりする必要があります。方法をご確認ください link:../multi-admin-verify/enable-disable-task.html["ARPで保護されたボリュームのMAVを有効にします"^]。MAVグループの管理者を定義し、のMAVルールを作成する必要があります `security anti-ransomware volume disable`、 `security anti-ransomware volume pause`および `security anti-ransomware volume attack clear-suspect` 保護するARPコマンド。MAVグループの各管理者は、新しいルール要求とを承認する必要があります link:../multi-admin-verify/enable-disable-task.html["MAVルールを再度追加します"^] MAV設定内。
