---
sidebar: sidebar 
permalink: snapmirror-active-sync/cluster-config-task.html 
keywords: SM-BC, SMBC, cluster, peering, ONTAP, Mediator, ONTAP Cloud Mediator, initialize, snapmirror active sync 
summary: ONTAP Mediator またはONTAP Cloud Mediator をSnapMirror Active Sync と併用する場合は、まずクラスタが正しく設定されていることを確認する必要があります。 
---
= SnapMirror Active Sync 用にONTAPクラスタを構成する
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
SnapMirror Active Syncは、フェイルオーバー発生時にピアクラスタを使用してデータを保護します。SnapMirrorActive Sync用にONTAP MediatorまたはONTAP Cloud Mediatorを設定する前に、クラスタが正しく設定されていることを確認する必要があります。

.開始する前に
ONTAP Mediator またはONTAP Cloud Mediator を設定する前に、次の点を確認する必要があります。

. クラスター間にクラスター ピアリング関係が存在します。
+

NOTE: クラスタピア関係のSnapMirror Active SyncではデフォルトのIPspaceが必要です。カスタムIPspaceはサポートされません。

+
link:../peering/create-cluster-relationship-93-later-task.html["クラスタピア関係の作成"]

. SVM は各クラスター上に作成されます。
+
link:../smb-config/create-svms-data-access-task.html["SVMの作成"]

. 各クラスタの SVM 間にはピア関係が存在します。
+
link:../peering/create-intercluster-svm-peer-relationship-93-later-task.html["SVMピア関係の作成"]

. LUN 用のボリュームが存在します。
+
link:../smb-config/create-volume-task.html["ボリュームの作成"]

. クラスター内の各ノードに少なくとも 1 つの SAN LIF が作成されます。
+
link:../san-admin/manage-lifs-all-san-protocols-concept.html["クラスタSAN環境でのLIFに関する考慮事項"]

+
link:../networking/create_a_lif.html["LIFの作成"]

. 必要な LUN が作成され、igroup にマップされます。igroup は、LUN をアプリケーション ホスト上のイニシエーターにマップするために使用されます。
+
link:../san-admin/provision-storage.html["LUNの作成とigroupのマッピング"]

. アプリケーション ホストが再スキャンされ、新しい LUN が検出されます。

