---
sidebar: sidebar 
permalink: snapmirror-active-sync/delete-fails-takeover-task.html 
keywords: troubleshooting, SM-BC, SMBC, SnapMirror, delete, takeover, consistency group, snapmirror active sync 
summary: 'ONTAP 9.9.1がクラスタにインストールされている場合、  `snapmirror delete` SnapMirror アクティブ同期整合性グループ関係がテイクオーバー状態にある場合、コマンドは失敗します。' 
---
= ONTAP SnapMirrorの削除操作が引き継ぎ状態で失敗する
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
以下の情報を使用してください。  `snapmirror delete` SnapMirrorアクティブ同期整合性グループ関係がテイクオーバー状態にある場合、コマンドは失敗します。

.問題：
ONTAP 9.9.1がクラスタにインストールされている場合、  `snapmirror delete` SnapMirror アクティブ同期整合性グループ関係がテイクオーバー状態にある場合、コマンドは失敗します。

....
C2_cluster::> snapmirror delete  vs1:/cg/dd

Error: command failed: RPC: Couldn't make connection
....
.解決策
SnapMirror アクティブ同期関係のノードがテイクオーバー状態にある場合は、「-force」オプションを true に設定して SnapMirror の削除および解放操作を実行します。

....
C2_cluster::> snapmirror delete  vs1:/cg/dd -force true

Warning: The relationship between source "vs0:/cg/ss" and destination
         "vs1:/cg/dd" will be deleted, however the items of the destination
         Consistency Group might not be made writable, deletable, or modifiable
         after the operation. Manual recovery might be required.
Do you want to continue? {y|n}: y
Operation succeeded: snapmirror delete for the relationship with destination "vs1:/cg/dd".
....
.関連情報
* link:https://docs.netapp.com/us-en/ontap-cli/snapmirror-delete.html["SnapMirrorの削除"^]

