---
sidebar: sidebar 
permalink: snapmirror-active-sync/index.html 
keywords: SM-BC, SMBC, failover, terms, benefits, snapmirror active sync, TR-4878 
summary: SnapMirrorアクティブ シンクを使用して LUN でアプリケーションを保護し、アプリケーションの透過的なフェイルオーバーを可能にして、災害発生時のビジネス継続性を確保します。 
---
= ONTAP SnapMirror Active Syncについて学ぶ
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
SnapMirror アクティブ同期（ONTAP 9.15.1 より前は SnapMirror Business Continuity と呼ばれていました）は、完全なサイト障害が発生した場合でもビジネスサービスが機能し続けることを可能にします。このテクノロジーにより、アプリケーションは手動操作やカスタムスクリプトを使用せずに、セカンダリコピーにシームレスにフェイルオーバーできます。

SnapMirror active sync（SM-AS）は、よりきめ細かく、低コストで、使いやすいアプリケーションレベルの保護と自動フェイルオーバーを実現するように設計されています。SnapMirror active syncを使用すると、地理的に離れた場所にあるサイト間で、アプリケーションの複数のボリュームを同期的にレプリケートできます。プライマリに障害が発生した場合に自動的にセカンダリコピーにフェイルオーバーすることで、ティア1アプリケーションのビジネス継続性を確保します。

一部の国では、金融機関の規制により、企業はセカンダリ データ センターから定期的にサービスを受けることが義務付けられています。SnapMirror active sync は、高可用性クラスターにより、ビジネス継続性のためにこれらのデータ センターの切り替えを可能にします。

ONTAP 9.9.1 以降、SnapMirror アクティブ同期は AFF および ASA クラスタでサポートされています。プライマリクラスタとセカンダリクラスタは同じタイプ（AFF、ASA、または ASA r2）である必要があります。SnapMirror アクティブ同期は、iSCSI または FCP LUN、あるいは NVMe ネームスペースを使用するアプリケーションを保護します。

SnapMirror SANワークロード向けのアクティブ同期は、対称構成と非対称構成の両方をサポートします。ONTAP 9.9.1以降では、非対称構成がサポートされています。対称アクティブ / アクティブのサポートは、ONTAP 9.15.1で導入されました。対称アクティブ / アクティブ構成では、保護されたLUNの両方のコピーが双方向の同期レプリケーションによって読み取りおよび書き込みI/O操作を実行でき、各LUNコピーがローカルI/O要求に対応できます。

ONTAP 9.19.1 以降、SnapMirror Active Sync は、AFF クラスター（2 ノードのみ）または AFX クラスター（4 ノードのみ）において、NFS（v3 および v4）および SMB（2.x 以降）を使用して SVM レベルで NAS ワークロードをサポートし、プライマリでのみ読み取り / 書き込みアクセスが可能です。セカンダリ SVM およびそれに含まれるボリュームは NAS プロトコルを使用してアクセスすることはできませんが、セカンダリ ボリュームを別の SVM にクローンすることでアクセスできるようになります。


NOTE: 2024年7月より、これまでPDF形式で公開されていたテクニカルレポートの内容がONTAP製品ドキュメントに統合されました。ONTAP SnapMirror Active Syncドキュメントには、_TR-4878：SnapMirror Active Sync_の内容が含まれるようになりました。



[[benefits]]
== メリット

SnapMirrorアクティブ同期には次のようなメリットがあります。

* ビジネスクリティカルなアプリケーションの継続的可用性
* 重要なアプリケーションをプライマリ サイトとセカンダリ サイトで交互にホストすることが可能
* 整合性グループを使用して従属書き込み順序の整合性を維持し、シンプルなアプリケーション管理を実現する
* アプリケーションごとにフェイルオーバーをテストできる
* アプリケーションの可用性に影響を与えることなくミラー クローンを瞬時に作成できる
* 保護されているワークロードと保護されていないワークロードを同じONTAPクラスタに導入できる
* SAN構成の場合はLUN、NVMeネームスペース、NVMeサブシステム、またはストレージユニットのID、NAS構成の場合はボリュームのIDは同じままなので、アプリケーションはそれらを共有仮想デバイスとして認識します。
* セカンダリ クラスタを柔軟に再利用して、クローンを瞬時に作成することで、アプリケーションのパフォーマンスや可用性に影響を与えることなく、開発テスト、UAT、レポート作成にアプリケーションを使用できる


SnapMirror active sync を使用すると、SAN 構成のデータ LUN または NVMe 名前空間、および NAS 構成のボリュームを保護できます。これにより、災害発生時の事業継続を目的として、アプリケーションを透過的にフェイルオーバーできます。詳細については、link:use-cases-concept.html["ユースケース"]を参照してください。



[[key-concepts]]
== 主要な概念

SnapMirror active syncは、SAN構成では整合性グループを、NAS構成ではSVMを使用して、データのレプリケーションを確実に行います。SnapMirror active syncは、ONTAP Mediatorを使用するか、ONTAP 9.17.1以降ではCloud Mediatorを使用して、自動フェイルオーバーを実現し、災害発生時にもデータが確実に提供されるようにします。SnapMirror active syncの導入を計画する際には、SnapMirror active syncの基本的な概念とそのアーキテクチャを理解することが重要です。

.非対称と対称
対称的なアクティブ / アクティブ SAN クラスタ構成では、両方のサイトがアクティブな I/O のためにローカルストレージにアクセスできます。対称的なアクティブ / アクティブは、VMware vMSC、SQL を使用した Windows Failover Cluster、Oracle RAC などのクラスタアプリケーション向けに最適化されています。

非対称アクティブ / アクティブSAN構成では、セカンダリサイトのデータはLUN、ネームスペース、またはストレージユニットにプロキシされます。

詳細については、xref:architecture-concept.html[SnapMirrorアクティブ同期アーキテクチャ]を参照してください。

NAS構成ではプロキシは存在せず、セカンダリSVMは休止状態ですが、ボリュームを別のSVMにクローンすることでアクセスできるようになります。

.整合性グループ（SANのみ）
AFFおよびASAシステムでは、link:../consistency-groups/index.html["整合性グループ"]は、ビジネス継続性のために保護する必要があるアプリケーション ワークロードの整合性を保証するFlexVolボリュームの集合です。ASA r2システムでは、整合性グループはストレージ ユニットの集合です。

整合性グループの目的は、ボリュームまたはストレージユニットのコレクションのスナップショットイメージを同時に取得し、ある時点でのコレクションの「crash consistent state（障害など予期しないシャットダウン時と同様）」の状態のコピーを確保することです。整合性グループにより、データセットのすべてのボリュームが静止し、正確に同じ時点でスナップショットが作成されます。これにより、データセットをサポートするボリュームまたはストレージユニット全体で、データの整合性が保たれた復元ポイントが提供されます。これにより、整合性グループは依存関係にある書き込み順序の整合性を維持します。ビジネス継続性のためにアプリケーションを保護する場合は、このアプリケーションに対応するボリュームまたはストレージユニットのグループを整合性グループに追加して、ソースとデスティネーションの整合性グループ間にデータ保護関係を確立する必要があります。ソースとデスティネーションの整合性グループには、同じ数とタイプのボリュームが含まれている必要があります。

.SVMとFlexVolのサポート（SnapMirror NASのアクティブ同期）
ONTAP 9.19.1 では、NAS 向け SnapMirror アクティブ同期は、FlexVol ボリュームを含む SVM の保護をサポートします。SVM 内の整合グループまたは FlexGroup ボリュームは、NAS 構成の SnapMirror アクティブ同期ではサポートされていません。

.コンスティチュエント
SAN構成では、構成要素は個々のボリューム、LUN、またはNVMe名前空間（ONTAP 9.17.1以降）であり、SnapMirrorアクティブ同期関係で保護されている整合グループの一部です。

NAS構成では、構成要素はボリュームであり、それを含むSVMはSnapMirrorアクティブ同期関係で保護されるエンティティです。

.ONTAP Mediator
link:../mediator/index.html["ONTAP Mediator"]は、ピア接続されたONTAPクラスタとノードのヘルス情報を受信し、両者間のオーケストレーションを行い、各ノード/クラスタが正常かつ稼働しているかどうかを判断します。ONTAP Mediatorは、以下のヘルス情報を提供します：

* ピア関係にあるONTAPクラスタ
* ピア関係にあるONTAPクラスタ ノード
* フェイルオーバーユニット（SAN 関係の SnapMirror アクティブ同期の整合グループ、および NAS 関係の SnapMirror アクティブ同期の SVM に対応）。各フェイルオーバーユニットについて、次の情報が提供されます：
+
** レプリケーション状態：初期化なし、同期中、または同期外
** プライマリ コピーをホストしているクラスタ
** 処理コンテキスト（計画的フェイルオーバーに使用）




このONTAP Mediatorの健全性情報により、クラスタは障害のタイプを区別し、自動フェイルオーバーを実行するかどうかを判断できます。ONTAP Mediatorは、両方のONTAPクラスタ（プライマリおよびセカンダリ）とともに、SnapMirrorアクティブ同期クォーラムを構成する3つのメンバーの1つです。合意に至るには、クォーラムの2つ以上のメンバーが特定の処理に同意する必要があります。


NOTE: ONTAP 9.15.1以降、System ManagerはどちらのクラスタからでもSnapMirrorアクティブ同期関係のステータスを表示します。また、System ManagerでどちらのクラスタからでもONTAP Mediatorのステータスを監視することもできます。以前のリリースのONTAPでは、System Managerはソース クラスタからのSnapMirrorアクティブ同期関係のステータスを表示していました。

.ONTAP Cloud Mediator
ONTAP Cloud MediatorはONTAP 9.17.1以降で利用できます。ONTAP Cloud MediatorはONTAP Mediatorと同じサービスを提供しますが、NetApp Consoleを使用してクラウドでホストされる点が異なります。

.計画的フェイルオーバー
SnapMirrorアクティブ同期関係でのコピーの役割を変更する手動処理。プライマリ サイトがセカンダリ サイトに、セカンダリ サイトがプライマリ サイトになります。

.自動計画外フェイルオーバー（AUFO）
ミラー コピーへのフェイルオーバーを実行する自動処理。この処理には、プライマリ コピーが使用できないことを検出するためにONTAP Mediatorが必要です。

.プライマリファーストとプライマリバイアス
SnapMirrorアクティブ同期では、ネットワークが分割された場合のI/O処理にプライマリ コピーを優先するプライマリファーストの原則が使用されます。

プライマリバイアスとは、SnapMirrorアクティブ同期で保護されたデータセットの可用性を向上させる特別なクォーラムの実装です。どちらのクラスタからもONTAP Mediatorにアクセスできない場合に、プライマリ コピーが使用可能だと、プライマリバイアスが効果を発揮します。

プライマリーファーストとプライマリーバイアスは、ONTAP 9.11.1以降のSnapMirrorアクティブ同期SAN構成でサポートされています。プライマリコピーはSystem Managerで指定され、REST APIおよびCLIで出力されます。

.非同期（OOS）
アプリケーションI/Oがセカンダリ ストレージ システムにレプリケートされていない場合、**out of sync**として報告されます。out of sync状態とは、セカンダリ ボリュームがプライマリ（ソース）と同期されておらず、SnapMirrorレプリケーションが実行されていないことを意味します。

ミラー状態が `Snapmirrored`の場合、SnapMirror関係が確立され、データ転送が完了していることを示します。つまり、デスティネーション ボリュームはソース ボリュームと最新の状態です。

SnapMirrorアクティブ同期は自動再同期をサポートしており、コピーをInSync状態に戻すことができます。

ONTAP 9.15.1 以降、SnapMirror アクティブ同期はlink:interoperability-reference.html#fan-out-configurations["ファンアウト構成における自動再構成"]をサポートします。

.均一な構成と非均一な構成
* **均一なホストアクセス**とは、両サイトのホストが両サイトのストレージクラスタへのすべてのパスに接続されていることを意味します。サイト間パスは、距離をまたいで延伸されます。均一なホストアクセスは、SAN構成にのみ適用されます。
* **非均一ホストアクセス**とは、各サイトのホストが同じサイトのクラスタにのみ接続されることを意味します。サイト間パスとストレッチパスは接続されていません。



NOTE: 均一なホスト アクセスは、すべてのSnapMirrorアクティブ同期構成でサポートされます。不均一なホスト アクセスは、対称アクティブ / アクティブ構成でのみサポートされます。

.RPOゼロ
RPOはRecovery Point Objective（目標復旧時点）の略で、所定の期間内に許容可能とみなされるデータ損失量を指します。RPOゼロとは、データ損失が一切許容されないことを意味します。

.RTOゼロ
RTOはRecovery Time Objective（目標復旧時間）の略で、システム停止、障害、またはその他のデータ損失イベントが発生してから、アプリケーションが無停止で通常の処理に戻るまでに許容可能とみなされる時間です。RTOゼロとは、ダウンタイムが一切許容されないことを意味します。



[[snapmirror-active-sync-configuration-support-by-ontap-version]]
== ONTAPバージョンによるSnapMirrorアクティブ同期構成のサポート

SnapMirror active sync でサポートされるクラスタ、プロトコル、および構成の種類は、ONTAP のバージョンによって異なります。次の表に、アップデートが追加された ONTAP のバージョンと、それらのアップデートをサポートする構成を示します。

[cols="2*"]
|===
| ONTAPのバージョン | サポートを追加します 


| 9.19.1以降  a| 
* NFS
* SMB


NASプロトコルは、以下のクラスタタイプでサポートされています：

* AFF
* AFX




| 9.17.1以降  a| 
* VMwareホストワークロード向けNVMe




| 9.16.1以降  a| 
* ASA r2、2ノードクラスタ
* 対称アクティブ / アクティブ 4 ノードから 4 ノードの AFF または ASA クラスタ
+
対称アクティブ / アクティブ構成は、ONTAP 9.16.1以降において、2ノード対2ノードのクラスタに加えて、4ノード対4ノードのクラスタもサポートします。

+
ASA r2では、2ノード対2ノードのクラスタのみがサポートされています。





| 9.15.1以降  a| 
以下の構成タイプ：

* 対称アクティブ / アクティブ
+
対称的なアクティブ / アクティブ構成は、ONTAP 9.15.1 の 2 ノードクラスタをサポートします。





| 9.9.1以降  a| 
* AFF
* ASA （C シリーズのみ）


プロトコル：

* iSCSI
* FC


設定の種類：

* 非対称アクティブ / アクティブ


|===
プライマリ クラスタとセカンダリ クラスタは同じタイプである必要があります（link:../san-admin/learn-about-asa.html["ASA"]、link:https://docs.netapp.com/us-en/asa-r2/get-started/learn-about.html["ASA r2"^]、またはAFF）。

追加の設定情報については、以下を参照してください：

* link:prerequisites-reference.html["SnapMirror active sync の前提条件"]
* link:limits-reference.html["SnapMirror アクティブ同期オブジェクトの制限"]

