---
sidebar: sidebar 
permalink: snapmirror-active-sync/index.html 
keywords: SM-BC, SMBC, failover, terms, benefits, snapmirror active sync, TR-4878 
summary: SnapMirrorアクティブ シンクを使用して LUN でアプリケーションを保護し、アプリケーションの透過的なフェイルオーバーを可能にして、災害発生時のビジネス継続性を確保します。 
---
= ONTAP SnapMirror Active Syncについて学ぶ
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
SnapMirror Active Sync（SnapMirror Business Continuity（SM-BC）とも呼ばれる）は、完全なサイト障害が発生した場合でもビジネスサービスの機能を継続できるようにします。このテクノロジーにより、アプリケーションは手動による介入やカスタムスクリプトなしに、セカンダリコピーにシームレスにフェイルオーバーできます。

NetApp SnapMirror Active Sync（SM-AS）は、自動フェイルオーバー機能を備えた、よりきめ細やかで低コスト、そして使いやすいアプリケーションレベルの保護を実現するように設計されています。SnapMirror Active Syncにより、サイト全体の障害発生時でも、ミッションクリティカルなビジネスサービスの運用を継続できます。SnapMirror Active Syncを使用すると、地理的に分散したサイト間で、アプリケーションの複数のボリュームを（整合性グループに追加することで）同期的にレプリケートできます。プライマリコピーが中断された場合、セカンダリコピーに自動的にフェイルオーバーできるため、Tier 1アプリケーションのビジネス継続性を確保できます。

一部の国では、金融機関の規制により、企業はセカンダリ データ センターから定期的にサービスを受けることが義務付けられています。SnapMirror active sync は、高可用性クラスターにより、ビジネス継続性のためにこれらのデータ センターの切り替えを可能にします。

ONTAP 9.9.1以降で利用可能なSnapMirror Active Syncは、AFFおよびオールフラッシュSANアレイ（ASA）クラスタでサポートされています。プライマリクラスタとセカンダリクラスタは、ASA、ASA r2、またはAFFのいずれか同じタイプである必要があります。SnapMirror Active Syncは、iSCSIまたはFCP LUN、あるいはNVMeネームスペースを持つアプリケーションを保護します。

SnapMirror Active Syncは、対称構成と非対称構成の両方をサポートします。対称アクティブ / アクティブのサポートは、ONTAP 9.15.1で導入されました。対称アクティブ / アクティブ構成では、保護されたLUNの両方のコピーが双方向同期レプリケーションで読み取りおよび書き込みI/O処理を実行できるため、各LUNコピーがローカルI/O要求に対応できます。


NOTE: 2024年7月より、これまでPDF形式で公開されていたテクニカルレポートの内容がONTAP製品ドキュメントに統合されました。ONTAP SnapMirror Active Syncドキュメントには、_TR-4878：SnapMirror Active Sync_の内容が含まれるようになりました。



== メリット

SnapMirrorアクティブ同期には次のようなメリットがあります。

* ビジネスクリティカルなアプリケーションの継続的可用性
* 重要なアプリケーションをプライマリ サイトとセカンダリ サイトで交互にホストすることが可能
* 整合性グループを使用して従属書き込み順序の整合性を維持し、シンプルなアプリケーション管理を実現する
* アプリケーションごとにフェイルオーバーをテストできる
* アプリケーションの可用性に影響を与えることなくミラー クローンを瞬時に作成できる
* 保護されているワークロードと保護されていないワークロードを同じONTAPクラスタに導入できる
* LUN、NVMe 名前空間、NVMe サブシステム、またはストレージ ユニットの ID は同じままなので、アプリケーションはそれらを共有仮想デバイスとして認識します。
* セカンダリ クラスタを柔軟に再利用して、クローンを瞬時に作成することで、アプリケーションのパフォーマンスや可用性に影響を与えることなく、開発テスト、UAT、レポート作成にアプリケーションを使用できる


SnapMirror Active Syncを使用すると、データLUNまたはNVMeネームスペースを保護でき、災害発生時のビジネス継続性を確保するために、アプリケーションを透過的にフェイルオーバーできます。詳細については、link:use-cases-concept.html["ユースケース"]をご覧ください。



== 主要な概念

SnapMirror Active Syncは、整合性グループを使用してデータの複製を確実に行います。SnapMirror Active SyncはONTAP MediatorまたはONTAP 9.17.1以降ではCloud Mediatorを使用して自動フェイルオーバーを実現し、災害発生時でもデータが確実に提供されるようにします。SnapMirror Active Syncの導入を計画する際には、SnapMirror Active Syncとそのアーキテクチャの基本概念を理解することが重要です。

.非対称と対称
対称アクティブ / アクティブ構成では、両方のサイトがアクティブ I/O のためにローカル ストレージにアクセスできます。対称アクティブ / アクティブは、VMware vMSC、Windows Failover Cluster with SQL、Oracle RAC などのクラスタ化されたアプリケーションに最適化されています。

非対称アクティブ / アクティブ構成では、セカンダリ サイトのデータは LUN、ネームスペース、またはストレージ ユニットにプロキシされます。

詳細については、xref:architecture-concept.html[SnapMirrorアクティブ同期アーキテクチャ]を参照してください。

.整合性グループ
AFFおよびASAシステムでは、link:../consistency-groups/index.html["整合性グループ"]は、ビジネス継続性のために保護する必要があるアプリケーション ワークロードの整合性を保証するFlexVolボリュームの集合です。ASA r2システムでは、整合性グループはストレージ ユニットの集合です。

整合性グループの目的は、ボリュームまたはストレージユニットのコレクションのスナップショットイメージを同時に取得し、ある時点でのコレクションの「crash consistent state（障害など予期しないシャットダウン時と同様）」の状態のコピーを確保することです。整合性グループにより、データセットのすべてのボリュームが静止し、正確に同じ時点でスナップショットが作成されます。これにより、データセットをサポートするボリュームまたはストレージユニット全体で、データの整合性が保たれた復元ポイントが提供されます。これにより、整合性グループは依存関係にある書き込み順序の整合性を維持します。ビジネス継続性のためにアプリケーションを保護する場合は、このアプリケーションに対応するボリュームまたはストレージユニットのグループを整合性グループに追加して、ソースとデスティネーションの整合性グループ間にデータ保護関係を確立する必要があります。ソースとデスティネーションの整合性グループには、同じ数とタイプのボリュームが含まれている必要があります。

.コンスティチュエント
SnapMirrorアクティブ同期関係で保護されている整合性グループの一部である個々のボリューム、LUN、または NVMe 名前空間（ONTAP 9.17.1 以降）。

.ONTAP Mediator
link:../mediator/index.html["ONTAP Mediator"]は、ピア接続されたONTAPクラスタとノードのヘルス情報を受信し、両者間のオーケストレーションを行い、各ノード/クラスタが正常かつ稼働しているかどうかを判断します。ONTAP Mediatorは、以下のヘルス情報を提供します：

* ピア関係にあるONTAPクラスタ
* ピア関係にあるONTAPクラスタ ノード
* （SnapMirrorアクティブ同期関係にあるフェイルオーバー ユニットを定義する）整合性グループ。各整合性グループの次の情報が提供されます。
+
** レプリケーション状態：初期化なし、同期中、または同期外
** プライマリ コピーをホストしているクラスタ
** 処理コンテキスト（計画的フェイルオーバーに使用）




このONTAP Mediatorの健全性情報により、クラスタは障害のタイプを区別し、自動フェイルオーバーを実行するかどうかを判断できます。ONTAP Mediatorは、両方のONTAPクラスタ（プライマリおよびセカンダリ）とともに、SnapMirrorアクティブ同期クォーラムを構成する3つのメンバーの1つです。合意に至るには、クォーラムの2つ以上のメンバーが特定の処理に同意する必要があります。


NOTE: ONTAP 9.15.1以降、System ManagerはどちらのクラスタからでもSnapMirrorアクティブ同期関係のステータスを表示します。また、System ManagerでどちらのクラスタからでもONTAP Mediatorのステータスを監視することもできます。以前のリリースのONTAPでは、System Managerはソース クラスタからのSnapMirrorアクティブ同期関係のステータスを表示していました。

.ONTAP Cloud Mediator
ONTAP Cloud MediatorはONTAP 9.17.1以降で利用できます。ONTAP Cloud MediatorはONTAP Mediatorと同じサービスを提供しますが、NetApp Consoleを使用してクラウドでホストされる点が異なります。

.計画的フェイルオーバー
SnapMirrorアクティブ同期関係でのコピーの役割を変更する手動処理。プライマリ サイトがセカンダリ サイトに、セカンダリ サイトがプライマリ サイトになります。

.自動計画外フェイルオーバー（AUFO）
ミラー コピーへのフェイルオーバーを実行する自動処理。この処理には、プライマリ コピーが使用できないことを検出するためにONTAP Mediatorが必要です。

.プライマリファーストとプライマリバイアス
SnapMirrorアクティブ同期では、ネットワークが分割された場合のI/O処理にプライマリ コピーを優先するプライマリファーストの原則が使用されます。

プライマリバイアスとは、SnapMirrorアクティブ同期で保護されたデータセットの可用性を向上させる特別なクォーラムの実装です。どちらのクラスタからもONTAP Mediatorにアクセスできない場合に、プライマリ コピーが使用可能だと、プライマリバイアスが効果を発揮します。

ONTAP 9.15.1以降では、SnapMirrorアクティブ同期でプライマリファーストとプライマリバイアスがサポートされます。プライマリ コピーはSystem Managerで指定され、REST APIおよびCLIを使用して出力されます。

.非同期（OOS）
アプリケーションI/Oがセカンダリ ストレージ システムにレプリケートされていない場合、**out of sync**として報告されます。out of sync状態とは、セカンダリ ボリュームがプライマリ（ソース）と同期されておらず、SnapMirrorレプリケーションが実行されていないことを意味します。

ミラー状態が `Snapmirrored`の場合、SnapMirror関係が確立され、データ転送が完了していることを示します。つまり、デスティネーション ボリュームはソース ボリュームと最新の状態です。

SnapMirrorアクティブ同期は自動再同期をサポートしており、コピーをInSync状態に戻すことができます。

ONTAP 9.15.1 以降、SnapMirror アクティブ同期はlink:interoperability-reference.html#fan-out-configurations["ファンアウト構成における自動再構成"]をサポートします。

.均一な構成と非均一な構成
* **均一なホストアクセス** とは、両サイトのホストが両サイトのストレージ クラスタへのすべてのパスに接続されていることを意味します。サイト間パスは長距離にわたって拡張されます。
* **非均一ホストアクセス** とは、各サイトのホストが同じサイト内のクラスタにのみ接続されることを意味します。サイト間パスとストレッチパスは接続されません。



NOTE: 均一なホスト アクセスは、すべてのSnapMirrorアクティブ同期構成でサポートされます。不均一なホスト アクセスは、対称アクティブ / アクティブ構成でのみサポートされます。

.RPOゼロ
RPOはRecovery Point Objective（目標復旧時点）の略で、所定の期間内に許容可能とみなされるデータ損失量を指します。RPOゼロとは、データ損失が一切許容されないことを意味します。

.RTOゼロ
RTOはRecovery Time Objective（目標復旧時間）の略で、システム停止、障害、またはその他のデータ損失イベントが発生してから、アプリケーションが無停止で通常の処理に戻るまでに許容可能とみなされる時間です。RTOゼロとは、ダウンタイムが一切許容されないことを意味します。



== ONTAPバージョンによるSnapMirrorアクティブ同期構成のサポート

SnapMirrorアクティブ同期のサポートは、ONTAPのバージョンによって異なります：

[cols="4*"]
|===


| ONTAPのバージョン | サポートされているクラスタ | サポートされるプロトコル | サポートされている構成 


| 9.17.1以降  a| 
* AFF
* ASA
* Cシリーズ
* ASA r2

 a| 
* iSCSI
* FC
* VMware ワークロード向け NVMe

 a| 
* 非対称アクティブ / アクティブ



NOTE: 非対称アクティブ / アクティブは ASA r2 および NVMe をサポートしません。NVMe サポートの詳細については、link:../nvme/support-limitations.html["NVMeの構成、サポート、制限事項"]を参照してください。

* 対称アクティブ / アクティブ




| 9.16.1以降  a| 
* AFF
* ASA
* Cシリーズ
* ASA r2

 a| 
* iSCSI
* FC

 a| 
* 非対称アクティブ / アクティブ
* 対称アクティブ / アクティブ対称アクティブ / アクティブ構成は ONTAP 9.16.1 以降で 4 ノード クラスタをサポートします。ASA r2 では、 2 ノード クラスタのみがサポートされます。




| 9.15.1以降  a| 
* AFF
* ASA
* Cシリーズ

 a| 
* iSCSI
* FC

 a| 
* 非対称アクティブ / アクティブ
* 対称アクティブ / アクティブ対称アクティブ / アクティブ構成は ONTAP 9.15.1 で 2 ノード クラスタをサポートします。4 ノード クラスタは ONTAP 9.16.1 以降でサポートされます。




| 9.9.1以降  a| 
* AFF
* ASA
* Cシリーズ

 a| 
* iSCSI
* FC

 a| 
非対称アクティブ / アクティブ

|===
プライマリ クラスタとセカンダリ クラスタは同じタイプである必要があります（link:../san-admin/learn-about-asa.html["ASA"]、link:https://docs.netapp.com/us-en/asa-r2/get-started/learn-about.html["ASA r2"^]、またはAFF）。
