---
sidebar: sidebar 
permalink: snapmirror-active-sync/index.html 
keywords: SM-BC, SMBC, failover, terms, benefits, snapmirror active sync, TR-4878 
summary: SnapMirror Active Syncを使用してLUNでアプリケーションを保護し、アプリケーションが透過的にフェイルオーバーできるようにして、災害発生時のビジネス継続性を確保します。 
---
= ONTAP SnapMirrorアクティブ同期について学ぶ
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
SnapMirrorアクティブ シンク ( SnapMirror Business Continuity (SM-BC) とも呼ばれる) を使用すると、サイト全体に障害が発生した場合でもビジネス サービスが継続して機能できるようになります。このテクノロジーにより、手動による介入やカスタム スクリプトなしで、アプリケーションをシームレスにセカンダリ コピーにフェイルオーバーできます。

NetApp SnapMirror Active Sync (SM-as) は、自動フェイルオーバーを備えた、よりきめ細かく、低コストで、使いやすいアプリケーション レベルの保護を実現するように設計されています。  SnapMirrorアクティブ同期により、サイト全体の障害が発生した場合でも、ミッションクリティカルなビジネス サービスの運用を継続できます。 SnapMirrorアクティブ同期を使用すると、地理的に分散した場所にあるサイト間で、アプリケーションの複数のボリュームを（整合性グループに追加することで）同期的に複製できるようになりました。プライマリが停止した場合に自動的にセカンダリ コピーにフェイルオーバーできるため、ティア1アプリケーションのビジネス継続性を確保できます。

一部の国では、金融機関に対する規制により、企業はセカンダリ データ センターから定期的にサービスを受けることが義務付けられています。  SnapMirrorアクティブ同期は、高可用性クラスターを備えており、ビジネス継続性のためにこれらのデータセンターの切り替えを可能にします。

ONTAP 9.9.1 以降で利用可能なSnapMirrorアクティブ シンクは、 AFFおよびオールフラッシュ SAN アレイ (ASA) クラスタでサポートされます。プライマリ クラスタとセカンダリ クラスタは同じタイプ（ ASA、 ASA r2、またはAFF）である必要があります。  SnapMirrorアクティブ シンクは、iSCSI または FCP LUN または NVMe 名前空間を持つアプリケーションを保護します。

SnapMirrorアクティブ同期は、対称構成と非対称構成の両方をサポートします。対称アクティブ/アクティブのサポートは、 ONTAP 9.15.1 で導入されました。対称アクティブ/アクティブ構成では、保護された LUN の両方のコピーが双方向同期レプリケーションを使用して読み取りおよび書き込み I/O 操作を実行できるため、各 LUN コピーがローカル I/O 要求に対応できるようになります。


NOTE: 2024年7月以降、これまでPDFとして公開されていたテクニカルレポートの内容がONTAPの製品ドキュメントに統合されました。ONTAP SnapMirrorアクティブ同期のドキュメントに、「TR-4878：SnapMirrorアクティブ同期_」の内容が追加されました。



== メリット

SnapMirror Active Syncには次のようなメリットがあります。

* ビジネスクリティカルなアプリケーションの継続的可用性：
* 重要なアプリケーションをプライマリサイトとセカンダリサイトから交互にホストできます。
* 整合グループを使用して従属書き込み順序の整合性を確保し、アプリケーション管理を簡易化
* 各アプリケーションのフェイルオーバーをテストする機能。
* アプリケーションの可用性に影響を与えることなく、ミラークローンを瞬時に作成できます。
* 保護されているワークロードと保護されていないワークロードを同じONTAPクラスタに導入できる。
* LUN、NVMe 名前空間、NVMe サブシステム、またはストレージ ユニット ID は同じままなので、アプリケーションはそれらを共有仮想デバイスとして認識します。
* セカンダリクラスタを柔軟に再利用して、アプリケーションのパフォーマンスや可用性に影響を与えることなく、開発テスト、UAT、レポート作成に使用するクローンを瞬時に作成できます。


SnapMirror Active Syncを使用すると、データLUNまたはNVMeネームスペースを保護し、災害発生時にアプリケーションを透過的にフェイルオーバーしてビジネス継続性を確保できます。詳細については、 link:use-cases-concept.html["ユースケース"] 。



== 主な概念

SnapMirrorアクティブ同期は、整合性グループを使用して、データが確実に複製されるようにします。 SnapMirrorアクティブ シンクは、自動フェイルオーバーにONTAP Mediator を使用するか、 ONTAP 9.17.1 以降では Cloud Mediator を使用し、災害発生時にもデータが確実に提供されるようにします。SnapMirrorアクティブ同期の導入を計画する際は、SnapMirrorアクティブ同期とそのアーキテクチャの基本概念を理解しておくことが重要です。

.非対称性と対称性
対称アクティブ/アクティブ構成では、両方のサイトがアクティブI/Oのためにローカルストレージにアクセスできます。対称アクティブ/アクティブは、VMware vMSC、Windows Failover Cluster with SQL、Oracle RACなどのクラスタ化されたアプリケーションに最適化されています。

非対称アクティブ/アクティブ構成では、セカンダリ サイトのデータは LUN、名前空間、またはストレージ ユニットにプロキシされます。

詳細については、を参照してください xref:architecture-concept.html[SnapMirror Active Syncアーキテクチャ]。

.整合グループ
AFFおよびASAシステムの場合link:../consistency-groups/index.html["整合グループ"] FlexVolボリュームの集合であり、ビジネス継続性を確保するために保護する必要があるアプリケーションワークロードの整合性を保証します。ASAASAシステムでは、コンシステンシグループはストレージユニットの集合です。

整合性グループの目的は、ボリュームまたはストレージユニットのコレクションのスナップショットイメージを同時に取得し、ある時点でのコレクションのクラッシュ整合性コピーを確保することです。整合性グループにより、データセットのすべてのボリュームが休止され、同じ時点でのSnapshotが作成されます。これにより、データセットをサポートするボリュームまたはストレージユニット全体にわたって、データの整合性が保たれた復元ポイントが提供されます。整合性グループはこうして従属書き込み順序の整合性を維持します。ビジネス継続性のためにアプリケーションを保護する場合は、そのアプリケーションに対応するボリュームまたはストレージユニットのグループを整合性グループに追加し、ソースとデスティネーションの整合性グループ間にデータ保護関係を確立する必要があります。ソースとデスティネーションの整合性グループには、同じ数とタイプのボリュームを含める必要があります。

.コンスティチュエント
SnapMirrorアクティブ同期関係で保護されている整合性グループの一部である個々のボリューム、LUN、または NVMe 名前空間 ( ONTAP 9.17.1 以降)。

.ONTAP Mediator
そのlink:../mediator/index.html["ONTAP Mediator"]ピア接続されたONTAPクラスタとノードのヘルス情報を受信し、両者間のオーケストレーションを行い、各ノード/クラスタが正常で稼働しているかどうかを判断します。ONTAPONTAPは、以下のヘルス情報を提供します。

* ONTAPクラスタのピアリング
* ピアONTAPクラスタノード
* 整合グループ（SnapMirrorのアクティブな同期関係でフェイルオーバーユニットを定義）。整合グループごとに次の情報が表示されます。
+
** レプリケーションの状態：Uninitialized、In Sync、またはOut of Sync
** プライマリコピーをホストするクラスタ
** 操作コンテキスト（計画的フェイルオーバーに使用）




このONTAPメディエーターの健常性情報を使用すると、クラスタで障害のタイプを区別し、自動フェイルオーバーを実行するかどうかを判断できます。ONTAPメディエーターは、両方のONTAPクラスタ（プライマリおよびセカンダリ）とともにSnapMirrorアクティブ同期クォーラムを構成する3つのメンバーの1つです。合意に達するには、クォーラムの少なくとも2つの当事者が特定の処理に同意する必要があります。


NOTE: ONTAP 9.15.1以降では、どちらかのクラスタのSnapMirrorのアクティブな同期関係のステータスが表示されます。ONTAPメディエーターのステータスは、System Managerのどちらのクラスタからも監視できます。以前のリリースのONTAPでは、ソースクラスタのSnapMirrorのアクティブな同期関係のステータスが表示されていました。

.ONTAPクラウドメディエーター
ONTAP Cloud Mediatorは、 ONTAP 9.17.1以降で利用できます。ONTAPCloud Mediatorは、 ONTAPを使用してクラウドでホストされる点を除いて、 ONTAP Mediatorと同じサービスを提供します。

.計画的フェイルオーバー
SnapMirrorアクティブ同期関係でのコピーの役割を変更する手動処理。プライマリ サイトがセカンダリ サイトに、セカンダリ サイトがプライマリ サイトになります。

.自動計画外フェイルオーバー（AUFO）
ミラー コピーへのフェイルオーバーを実行する自動処理。この処理には、プライマリ コピーが使用できないことを検出するためにONTAP Mediatorが必要です。

.プライマリファーストとプライマリバイアス
SnapMirrorアクティブ同期では、ネットワークが分割された場合のI/O処理にプライマリ コピーを優先するプライマリファーストの原則が使用されます。

プライマリバイアスとは、SnapMirrorアクティブ同期で保護されたデータセットの可用性を向上させる特別なクォーラムの実装です。どちらのクラスタからもONTAP Mediatorにアクセスできない場合に、プライマリ コピーが使用可能だと、プライマリバイアスが効果を発揮します。

ONTAP 9.15.1以降では、SnapMirrorアクティブ同期でプライマリファーストとプライマリバイアスがサポートされます。プライマリ コピーはSystem Managerで指定され、REST APIおよびCLIを使用して出力されます。

.非同期（OOS）
アプリケーションI/Oがセカンダリ・ストレージ・システムにレプリケートされていない場合は'**out of sync**と報告されます非同期ステータスは、セカンダリボリュームがプライマリ（ソース）と同期されておらず、SnapMirrorレプリケーションが実行されていないことを示します。

ミラー状態が `Snapmirrored`これは、 SnapMirror関係が確立され、データ転送が完了したことを示します。つまり、宛先ボリュームはソース ボリュームと最新の状態になっています。

SnapMirror Active Syncは自動再同期をサポートしており、コピーをInSync状態に戻すことができます。

ONTAP 9 .15.1以降では、SnapMirrorアクティブ同期がサポートされてlink:interoperability-reference.html#fan-out-configurations["ファンアウト構成での自動再構成"]います。

.均一な構成と非均一な構成
* **均一なホストアクセス**は、両方のサイトのホストが両方のサイトのストレージクラスタへのすべてのパスに接続されていることを意味します。サイト間パスが複数の距離にわたってストレッチされている。
* **Non-uniform host access **は、各サイトのホストが同じサイトのクラスタにのみ接続されることを意味します。サイト間パスとストレッチパスは接続されません。



NOTE: 均一ホストアクセスは、すべてのSnapMirrorアクティブ同期配置でサポートされます。非均一ホストアクセスは、対称アクティブ/アクティブ配置でのみサポートされます。

.RPOゼロ
RPOはRecovery Point Objective（目標復旧時点）の略で、所定の期間内に許容可能とみなされるデータ損失量を指します。RPOゼロとは、データ損失が一切許容されないことを意味します。

.RTOゼロ
RTOはRecovery Time Objective（目標復旧時間）の略で、システム停止、障害、またはその他のデータ損失イベントが発生してから、アプリケーションが無停止で通常の処理に戻るまでに許容可能とみなされる時間です。RTOゼロとは、ダウンタイムが一切許容されないことを意味します。



== ONTAPバージョン別のSnapMirrorアクティブ同期構成のサポート

SnapMirror Active Sync のサポートは、 ONTAPのバージョンによって異なります。

[cols="4*"]
|===


| ONTAPのバージョン | サポートされているクラスター | サポートされるプロトコル | サポートされている構成 


| 9.17.1以降  a| 
* AFF
* ASA
* Cシリーズ
* ASA r2

 a| 
* iSCSI
* FC
* VMware ワークロード向け NVMe

 a| 
* 非対称アクティブ/アクティブ



NOTE: 非対称アクティブ/アクティブはASA r2とNVMeをサポートしていません。NVMeサポートの詳細については、以下を参照してください。 link:../nvme/support-limitations.html["NVMeの設定、サポート、制限事項"] 。

* 対称アクティブ/アクティブ




| 9.16.1以降  a| 
* AFF
* ASA
* Cシリーズ
* ASA r2

 a| 
* iSCSI
* FC

 a| 
* 非対称アクティブ/アクティブ
* 対称アクティブ/アクティブ 対称アクティブ/アクティブ構成は、 ONTAP 9.16.1 以降で 4 ノード クラスタをサポートします。  ASA r2 では、2 ノード クラスタのみがサポートされます。




| 9.15.1以降  a| 
* AFF
* ASA
* Cシリーズ

 a| 
* iSCSI
* FC

 a| 
* 非対称アクティブ/アクティブ
* 対称アクティブ/アクティブ 対称アクティブ/アクティブ構成は、 ONTAP 9.15.1 で 2 ノード クラスタをサポートします。4ノード クラスタはONTAP 9.16.1 以降でサポートされます。




| 9.9.1以降  a| 
* AFF
* ASA
* Cシリーズ

 a| 
* iSCSI
* FC

 a| 
非対称アクティブ/アクティブ

|===
プライマリクラスタとセカンダリクラスタは同じタイプである必要があります。 link:../san-admin/learn-about-asa.html["ASA"] 、 link:https://docs.netapp.com/us-en/asa-r2/get-started/learn-about.html["ASA r2"^] 、またはAFF。
