---
sidebar: sidebar 
permalink: snapmirror-active-sync/monitor-task.html 
keywords: SM-BC, SMBC, monitoring, Mediator status, EMS, errors, planned failover status, automatic unplanned failover status, , snapmirror active sync 
summary: 監視できるSnapMirrorアクティブ同期コンポーネントと操作はいくつかあります。 
---
= ONTAP SnapMirrorアクティブ同期操作を監視する
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
SnapMirrorアクティブ同期の以下の処理を監視すると、SnapMirrorアクティブ同期設定の健全性を確保できます。

* ONTAP Mediator
* 計画的フェイルオーバー処理
* 自動計画外フェイルオーバー処理
* SnapMirrorアクティブ同期の可用性



NOTE: ONTAP 9.15.1以降、System Managerは、どちらのクラスタからでもSnapMirrorアクティブ同期関係のステータスを表示します。また、System Managerでどちらのクラスタからでも ONTAPメディエーターのステータスを監視することもできます。



== ONTAP Mediator

通常の動作中、ONTAP Mediatorの状態は接続済みになっているはずです。それ以外の状態の場合は、エラーが発生している可能性があります。link:https://docs.netapp.com/us-en/ontap-ems-9131/sm-mediator-events.html["Event Management System（EMS）メッセージ"^]を確認して、エラーの内容と適切な修正措置を判断できます。



== 計画的フェイルオーバー処理

計画されたフェイルオーバー操作のステータスと進行状況は、 `snapmirror failover show`コマンドを使用して監視できます。例：

....
ClusterB::> snapmirror failover start -destination-path vs1:/cg/dcg1
....
フェイルオーバー操作が完了すると、新しいデスティネーション クラスタからSnapMirror保護ステータスを監視できます。例：

....
ClusterA::> snapmirror show
....
イベント メッセージと修正アクションの詳細については、link:https://docs.netapp.com/us-en/ontap-ems-9131/smbc-pfo-events.html["EMS リファレンス"^]を参照してください。



== 自動計画外フェイルオーバー処理

計画外の自動フェイルオーバー中に、 `snapmirror failover show`コマンドを使用して操作のステータスを監視できます。

....
ClusterB::> snapmirror failover show -instance
Start Time: 9/23/2020 22:03:29
         Source Path: vs1:/cg/scg3
    Destination Path: vs3:/cg/dcg3
     Failover Status: completed
        Error Reason:
            End Time: 9/23/2020 22:03:30
Primary Data Cluster: cluster-2
Last Progress Update: -
       Failover Type: unplanned
  Error Reason codes: -
....
イベント メッセージと修正アクションの詳細については、link:https://docs.netapp.com/us-en/ontap-ems-9131/smbc-aufo-events.html["EMS リファレンス"^]を参照してください。



== SnapMirrorアクティブ同期の可用性

SnapMirrorアクティブ同期関係の可用性は、プライマリ クラスタまたはセカンダリ クラスタ、あるいはその両方で一連のコマンドを使用して確認できます。

使用するコマンドには、プライマリ クラスタとセカンダリ クラスタの両方で接続とクォーラム ステータスを確認するための `snapmirror mediator show`コマンド、 `snapmirror show`コマンド、および `volume show`コマンドが含まれます。例：

....
SMBC_A::*> snapmirror mediator show
Mediator Address Peer Cluster     Connection Status Quorum Status
---------------- ---------------- ----------------- -------------
10.236.172.86    SMBC_B           connected         true

SMBC_B::*> snapmirror mediator show
Mediator Address Peer Cluster     Connection Status Quorum Status
---------------- ---------------- ----------------- -------------
10.236.172.86    SMBC_A           connected         true

SMBC_B::*> snapmirror show -expand
                                                                       Progress
Source            Destination Mirror  Relationship   Total             Last
Path        Type  Path        State   Status         Progress  Healthy Updated
----------- ---- ------------ ------- -------------- --------- ------- --------
vs0:/cg/cg1 XDP  vs1:/cg/cg1_dp Snapmirrored Insync -         true    -
vs0:vol1    XDP  vs1:vol1_dp  Snapmirrored Insync   -         true    -
2 entries were displayed.

SMBC_A::*> volume show -fields is-smbc-master,smbc-consensus,is-smbc-failover-capable -volume vol1
vserver volume is-smbc-master is-smbc-failover-capable smbc-consensus
------- ------ -------------- ------------------------ --------------
vs0     vol1   true           false                    Consensus

SMBC_B::*> volume show -fields is-smbc-master,smbc-consensus,is-smbc-failover-capable -volume vol1_dp
vserver volume  is-smbc-master is-smbc-failover-capable smbc-consensus
------- ------- -------------- ------------------------ --------------
vs1     vol1_dp false          true                     No-consensus
....
.関連情報
* link:https://docs.netapp.com/us-en/ontap-cli/snapmirror-failover-show.html["snapmirror failover show"^]
* link:https://docs.netapp.com/us-en/ontap-cli/snapmirror-failover-start.html["SnapMirrorフェイルオーバーの開始"^]
* link:https://docs.netapp.com/us-en/ontap-cli/snapmirror-mediator-show.html["SnapMirror Mediator show"^]

