---
sidebar: sidebar 
permalink: snapmirror-active-sync/monitor-task.html 
keywords: SM-BC, SMBC, monitoring, Mediator status, EMS, errors, planned failover status, automatic unplanned failover status, , snapmirror active sync 
summary: SnapMirrorのアクティブな同期のコンポーネントと処理は複数あり、監視できます。 
---
= ONTAPでのSnapMirrorのアクティブな同期処理の監視
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
次のSnapMirrorのアクティブな同期処理を監視して、SnapMirrorのアクティブな同期設定の健全性を確認できます。

* ONTAP Mediator
* 計画的フェイルオーバー処理
* 自動計画外フェイルオーバー処理
* SnapMirrorアクティブ同期の可用性



NOTE: ONTAP 9.15.1以降では、どちらかのクラスタのSnapMirrorのアクティブな同期関係のステータスが表示されます。ONTAPメディエーターのステータスは、System Managerのどちらのクラスタからも監視できます。



== ONTAP Mediator

通常運用時は、ONTAPメディエーターの状態は「connected」になります。それ以外の状態の場合は、エラー状態を示している可能性があります。では、エラーと適切な対処方法を確認できますlink:https://docs.netapp.com/us-en/ontap-ems-9131/sm-mediator-events.html["Event Management System（EMS；イベント管理システム）メッセージ"^]。



== 計画的フェイルオーバー処理

計画的フェイルオーバー処理のステータスと進捗状況は、コマンドを使用して監視できます `snapmirror failover show`。例：

....
ClusterB::> snapmirror failover start -destination-path vs1:/cg/dcg1
....
フェイルオーバー処理が完了したら、新しいデスティネーション クラスタからSnapMirror保護のステータスを監視できます。例：

....
ClusterA::> snapmirror show
....
イベントメッセージと対処方法については、を参照してlink:https://docs.netapp.com/us-en/ontap-ems-9131/smbc-pfo-events.html["EMSリファレンス"^]ください。



== 自動計画外フェイルオーバー処理

自動計画外フェイルオーバーの実行中は、コマンドを使用して処理のステータスを監視できます `snapmirror failover show`。

....
ClusterB::> snapmirror failover show -instance
Start Time: 9/23/2020 22:03:29
         Source Path: vs1:/cg/scg3
    Destination Path: vs3:/cg/dcg3
     Failover Status: completed
        Error Reason:
            End Time: 9/23/2020 22:03:30
Primary Data Cluster: cluster-2
Last Progress Update: -
       Failover Type: unplanned
  Error Reason codes: -
....
イベントメッセージと対処方法については、を参照してlink:https://docs.netapp.com/us-en/ontap-ems-9131/smbc-aufo-events.html["EMSリファレンス"^]ください。



== SnapMirrorアクティブ同期の可用性

SnapMirrorのアクティブな同期関係の可用性は、プライマリクラスタ、セカンダリクラスタ、またはその両方で一連のコマンドを使用して確認できます。

接続とクォーラムのステータスを確認するためのプライマリクラスタとセカンダリクラスタの両方でのコマンド、 `snapmirror show`および `volume show`コマンドが使用さ `snapmirror mediator show`れます。例：

....
SMBC_A::*> snapmirror mediator show
Mediator Address Peer Cluster     Connection Status Quorum Status
---------------- ---------------- ----------------- -------------
10.236.172.86    SMBC_B           connected         true

SMBC_B::*> snapmirror mediator show
Mediator Address Peer Cluster     Connection Status Quorum Status
---------------- ---------------- ----------------- -------------
10.236.172.86    SMBC_A           connected         true

SMBC_B::*> snapmirror show -expand
                                                                       Progress
Source            Destination Mirror  Relationship   Total             Last
Path        Type  Path        State   Status         Progress  Healthy Updated
----------- ---- ------------ ------- -------------- --------- ------- --------
vs0:/cg/cg1 XDP  vs1:/cg/cg1_dp Snapmirrored Insync -         true    -
vs0:vol1    XDP  vs1:vol1_dp  Snapmirrored Insync   -         true    -
2 entries were displayed.

SMBC_A::*> volume show -fields is-smbc-master,smbc-consensus,is-smbc-failover-capable -volume vol1
vserver volume is-smbc-master is-smbc-failover-capable smbc-consensus
------- ------ -------------- ------------------------ --------------
vs0     vol1   true           false                    Consensus

SMBC_B::*> volume show -fields is-smbc-master,smbc-consensus,is-smbc-failover-capable -volume vol1_dp
vserver volume  is-smbc-master is-smbc-failover-capable smbc-consensus
------- ------- -------------- ------------------------ --------------
vs1     vol1_dp false          true                     No-consensus
....