---
sidebar: sidebar 
permalink: snapmirror-active-sync/planned-failover-task.html 
keywords: SM-BC, testing failover, planned failover, maintenance, quorum, snapmirror active sync 
summary: 計画的フェイルオーバーを実行して、ディザスタ リカバリ設定をテストしたり、プライマリ クラスタのメンテナンスを実施したりできます。 
---
= SnapMirrorアクティブ同期関係にある ONTAP クラスタの計画的なフェイルオーバーを実行する
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
SnapMirrorアクティブ同期関係にあるONTAPクラスタの計画的フェイルオーバーでは、セカンダリ クラスタがプライマリ クラスタをテイクオーバーするように、プライマリ クラスタとセカンダリ クラスタのロールを切り替えます。フェイルオーバー中は、通常はセカンダリ クラスタがローカルで入出力要求を処理し、クライアントの処理は中断されません。

ディザスタリカバリ構成の健全性をテストしたり、プライマリクラスタのメンテナンスを実施したりするために、計画的なフェイルオーバーを実行することができます。

.タスク概要
計画的フェイルオーバーは、セカンダリ クラスタの管理者が開始します。この処理を実行するには、セカンダリ クラスタがプライマリをテイクオーバーするように、プライマリとセカンダリのロールを切り替える必要があります。新しいプライマリ クラスタがローカルで入出力要求の処理を開始できるようになり、クライアントの処理は中断されません。

.開始する前に
* SnapMirrorアクティブ同期関係が同期されている必要があります。
* ノンストップ オペレーションの実行中は、計画的フェイルオーバーを開始できません。ノンストップ オペレーションには、ボリュームの移動、アグリゲートの再配置、ストレージ フェイルオーバーなどがあります。
* ONTAP Mediatorが設定されて接続され、クォーラムを構成している必要があります。


.手順
計画的フェイルオーバーは、ONTAP CLIまたはSystem Managerを使用して実行できます。

[role="tabbed-block"]
====
.System Manager
--

IMPORTANT: ONTAP 9.8からONTAP 9.14.1では、SnapMirrorアクティブ同期はSnapMirror Business Continuity（SM-BC）と呼ばれます。

. System Manager で、**保護 > 概要 > 関係** を選択します。
. フェイルオーバーするSnapMirrorアクティブ同期関係を特定します。その名前の横にある `...`を選択し、次に**フェイルオーバー**を選択します。
. フェイルオーバーの状態を監視するには、ONTAP CLI で `snapmirror failover show`コマンドを使用します。


--
.CLI
--
. デスティネーション クラスタから、フェイルオーバー処理を開始します。
+
`snapmirror failover start -destination-path  <path>`

+
SAN構成におけるフェイルオーバーの例：

+
destination::>snapmirror failover start -destination-path vs1_dst:/cg/cg_dst

+
NAS構成におけるフェイルオーバーの例：

+
destination::>snapmirror failover start -destination-path vs_b:

. デスティネーション クラスタから、フェイルオーバーの進行状況を監視します。
+
`snapmirror failover show`

. フェイルオーバー処理が完了したら、デスティネーションからSnapMirror同期保護関係のステータスを監視できます。
+
`snapmirror show`



--
====
.関連情報
* link:https://docs.netapp.com/us-en/ontap-cli/snapmirror-failover-show.html["snapmirror failover show"^]
* link:https://docs.netapp.com/us-en/ontap-cli/snapmirror-failover-start.html["SnapMirrorフェイルオーバーの開始"^]
* link:https://docs.netapp.com/us-en/ontap-cli/snapmirror-show.html["snapmirror show"^]

