---
sidebar: sidebar 
permalink: snapmirror-active-sync/planned-failover-task.html 
keywords: SM-BC, testing failover, planned failover, maintenance, quorum, snapmirror active sync 
summary: 計画的フェイルオーバーを実行して、ディザスタリカバリ設定をテストしたり、プライマリクラスタでメンテナンスを実行したりできます。 
---
= SnapMirrorのアクティブな同期関係にあるクラスタの計画的フェイルオーバーを実行する
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
SnapMirrorのアクティブな同期関係にあるONTAPクラスタの計画的フェイルオーバーでは、プライマリクラスタからセカンダリクラスタにテイクオーバーされるように、プライマリクラスタとセカンダリクラスタのロールを切り替えます。フェイルオーバー中は、通常はセカンダリクラスタがクライアントの処理を中断せずにローカルで入出力要求を処理します。

計画的フェイルオーバーを実行して、ディザスタリカバリ構成の健全性をテストしたり、プライマリクラスタでメンテナンスを実行したりすることができます。

.タスクの内容
計画的フェイルオーバーは、セカンダリクラスタの管理者が開始します。この処理では、セカンダリクラスタがプライマリからテイクオーバーするように、プライマリとセカンダリのロールを切り替える必要があります。新しいプライマリクラスタでは、クライアントの処理を中断することなく、入出力要求の処理をローカルで開始できます。

.開始する前に
* SnapMirrorのアクティブな同期関係が同期されている必要があります。
* ノンストップオペレーションの実行中は、計画的フェイルオーバーを開始できません。ノンストップオペレーションには、ボリュームの移動、アグリゲートの再配置、ストレージフェイルオーバーなどがあります。
* ONTAPメディエーターが設定され、接続され、クォーラムを構成している必要があります。


.手順
計画的フェイルオーバーは、ONTAP CLIまたはSystem Managerを使用して実行できます。

[role="tabbed-block"]
====
.System Manager
--

IMPORTANT: ONTAP 9.14.1 から 9.8 では、 SnapMirror Active Sync はSnapMirror Business Continuity (SM-BC) と呼ばれます。

. System Managerで、[**Protection]>[Overview]>[Relationships]の順に選択します。
. フェイルオーバーするSnapMirrorのアクティブな同期関係を特定します。関係名の横にあるを選択し、[**Failover*]を選択し `...`ます。
. フェイルオーバーのステータスを監視するには、ONTAP CLIでを使用し `snapmirror failover show`ます。


--
.CLI
--
. デスティネーションクラスタから、フェイルオーバー処理を開始します。
+
`destination::>snapmirror failover start -destination-path   vs1_dst:/cg/cg_dst`

. フェイルオーバーの進行状況を監視します。
+
`destination::>snapmirror failover show`

. フェイルオーバー処理が完了したら、デスティネーションからSnapMirror同期保護関係のステータスを監視できます。
+
`destination::>snapmirror show`



--
====
.関連情報
* link:https://docs.netapp.com/us-en/ontap-cli/snapmirror-failover-show.html["スナップミラーフェイルオーバー表示"^]
* link:https://docs.netapp.com/us-en/ontap-cli/snapmirror-failover-start.html["スナップミラーフェイルオーバーの開始"^]
* link:https://docs.netapp.com/us-en/ontap-cli/snapmirror-show.html["snapmirror show"^]

