---
sidebar: sidebar 
permalink: snapmirror-active-sync/protect-task.html 
keywords: SM-BC, snapmirror business continuity, consistency group, remote protection, destination 
summary: ビジネス継続性のための保護を設定するには、ONTAPソースクラスタでLUNを選択して整合グループに追加します。 
---
= SnapMirrorのアクティブな同期で保護
:hardbreaks:
:toclevels: 1
:allow-uri-read: 
:toclevels: 1
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
SnapMirrorアクティブ同期は、非対称保護を提供し、ONTAP 9 .15.1以降では対称アクティブ/アクティブ保護を提供します。



== 非対称保護の設定

SnapMirrorアクティブ同期を使用した非対称保護を設定するには、ONTAPソース クラスタでLUNを選択し、整合性グループに追加します。

.開始する前に
* SnapMirror同期ライセンスが必要です。
* クラスタ管理者またはStorage VM管理者である必要があります。
* 整合性グループ内のコンスティチュエントボリュームは、すべて1つのStorage VM（SVM）に含まれている必要があります。
+
** LUNは異なるボリュームに配置できます。


* ソースとデスティネーションのクラスタを同じにすることはできません。
* ASAクラスタと非ASAクラスタの間にSnapMirrorアクティブ同期整合性グループ関係を確立することはできません。
* SnapMirrorアクティブ同期でクラスタ ピア関係を確立するには、デフォルトのIPspaceが必要です。カスタムのIPspaceはサポートされていません。
* 整合グループの名前は一意である必要があります。
* セカンダリ（デスティネーション）クラスタ上のボリュームのタイプはDPである必要があります。
* プライマリとセカンダリのSVMでピア関係が確立されている必要があります。


.手順
ONTAP CLIまたはSystem Managerを使用して整合グループを設定できます。

ONTAP 9 .10.1以降では、ONTAPで整合グループのエンドポイントとメニューが提供され、管理ユーティリティが追加されています。ONTAP 9 .10.1以降を使用している場合は、の手順をlink:../consistency-groups/protect-task.html["保護の設定"]参照してSnapMirrorのアクティブな同期関係を作成してくださいlink:../consistency-groups/configure-task.html["整合グループの設定"]。


IMPORTANT: ONTAP 9 .8~9.14.1では、SnapMirrorアクティブ同期をSnapMirrorビジネス継続性（SM-BC）と呼びます。

[role="tabbed-block"]
====
.System Manager
--
. プライマリクラスタで、*[保護]>[概要]>[ビジネス継続性のための保護]>[LUNの保護]*に移動します。
. 保護するLUNを選択し、保護グループに追加します。
. デスティネーションのクラスタとSVMを選択します。
. * 初期化関係 * がデフォルトで選択されています。[ 保存（ Save ） ] をクリックして保護を開始します。
. [Dashboard] > [Performance] に移動して、 LUN の IOPS アクティビティを確認します。
. デスティネーションクラスタで、 System Manager を使用して、ビジネス継続性関係の保護が同期されていることを確認します。 * Protection > Relationships * 。


--
.CLI
--
. デスティネーションクラスタから整合性グループ関係を作成
`destination::> snapmirror create -source-path _source-path_ -destination-path _destination-path_ -cg-item-mappings _volume-paths_ -policy _policy-name_`
+
コマンドのパラメータを `snapmirror create`使用して、最大12個のコンスティチュエントボリュームをマッピングできます `cg-item-mappings`。

+
次の例では、2つの整合グループ（と `vol2`、1つのミラーデスティネーション整合グループ） `cg_dst`を作成し `cg_src_ on the source with `vol1`ます。

+
`destination::> snapmirror create -source-path vs1_src:/cg/cg_src -destination-path vs1_dst:/cg/cg_dst -cg-item-mappings vol_src1:@vol_dst1,vol_src2:@vol_dst2 -policy AutomatedFailOver`

. デスティネーションクラスタから、整合性グループを初期化します。
+
`destination::>snapmirror initialize -destination-path _destination-consistency-group_`

. 初期化処理が正常に完了したことを確認します。ステータスはになります `InSync`。
+
`snapmirror show`

. 各クラスタにigroupを作成して、アプリケーションホストのイニシエータにLUNをマッピングします。
`lun igroup create -igroup _name_ -protocol _fcp|iscsi_ -ostype _os_ -initiator _initiator_name_`
. 各クラスタで、LUNをigroupにマッピングします。
+
`lun map -path _path_name_ -igroup _igroup_name_`

. コマンドを使用して、LUNマッピングが完了したことを確認します `lun map`。その後、アプリケーションホストで新しいLUNを検出できます。


--
====


== 対称アクティブ/アクティブ保護の設定

対称保護は、System ManagerまたはONTAP CLIを使用して確立できます。どちらのインターフェイスでも、には異なる手順がありますxref:index.html#key-concepts[均一なコンフィギュレーションと非均一なコンフィギュレーション]。

.開始する前に
* 両方のクラスタでONTAP 9 .15.1以降が実行されている必要があります。
* 対称アクティブ/アクティブ構成には保護ポリシーが必要 `AutomatedFailoverDuplex`です。または、をに `automated-failover-duplex`指定する `-type`こともできますxref:../data-protection/create-custom-replication-policy-concept.html[カスタムのSnapMirrorポリシーを作成する]。
* ONTAP 9.15.1では、対称アクティブ/アクティブ構成は2ノードクラスタでのみサポートされます。
* ONTAP 9.16.1 GA以降では、SnapMirror Active Syncで4ノードクラスタの対称アクティブ/アクティブ構成がサポートされます。
+
** 4ノードクラスタでSnapMirrorアクティブ同期を使用するには、ONTAP 9.16.1 GA以降を実行している必要があります。
** 4ノード構成を導入する前に、を実行する必要がありxref:../peering/create-cluster-relationship-93-later-task.adoc[クラスタピア関係を作成します。]ます。
** 4ノードクラスタのを確認しますxref:limits-reference.adoc[制限]。
** 2ノードクラスタにリバートする場合は、リバート前にSnapMirrorのアクティブな同期関係をクラスタから削除する必要があります。
** 4ノード構成を使用して、ストレージとコントローラをアップグレードできます。このプロセスは無停止で実行され、ボリュームを新しいノードに移動する間にクラスタを拡張します。詳細については、を参照してください link:upgrade-revert-task.html#refresh-a-cluster["クラスタをリフレッシュします。"]。




.手順
[role="tabbed-block"]
====
.System Manager
--
.統一された構成の手順
. プライマリサイトで、link:../consistency-groups/configure-task.html#create-a-consistency-group-with-new-luns-or-volumes["新しいLUNを使用して整合グループを作成します。"^]
+
.. 整合グループを作成するときは、ホストイニシエータを指定してigroupを作成します。
.. [**Enable SnapMirror *]チェックボックスをオンにして、ポリシーを選択します `AutomatedFailoverDuplex`。
.. 表示されるダイアログボックスで、[**replicate initiator groups**]チェックボックスを選択してigroupをレプリケートします。[**Edit proximity settings*]で、ホストの近接SVMを設定します。
.. **保存**を選択します。




.不均一な構成の手順
. プライマリサイトで、link:../consistency-groups/configure-task.html#create-a-consistency-group-with-new-luns-or-volumes["新しいLUNを使用して整合グループを作成します。"^]
+
.. 整合グループを作成するときは、ホストイニシエータを指定してigroupを作成します。
.. [**Enable SnapMirror *]チェックボックスをオンにして、ポリシーを選択します `AutomatedFailoverDuplex`。
.. [**Save*]を選択して、LUN、整合グループ、igroup、SnapMirror関係、igroupマッピングを作成します。


. セカンダリサイトでigroupを作成し、LUNをマッピングします。
+
.. ** Hosts**>** SAN Initiator Groups**に移動します。
.. 新しいigroupを作成するには、[**+Add*]を選択します。
.. ** Name **を指定し、** Host Operating System **を選択してから、** Initiator Group Members **を選択します。
.. 関係を初期化するには、[**Save*]を選択します。


. 新しいigroupをデスティネーションLUNにマッピングします。
+
.. **ストレージ**>** LUNs**に移動します。
.. igroupにマッピングするLUNをすべて選択します。
.. ** More **を選択してから** Map to Initiator Groups **を選択します。




--
.CLI
--
.統一された構成の手順
. アプリケーション内のすべてのボリュームをグループ化して新しいSnapMirror関係を作成します。双方向の同期レプリケーションを確立するためのポリシーを指定して `AutomatedFailOverDuplex`ください。
+
`snapmirror create -source-path <source_path> -destination-path <destination_path> -cg-item-mappings <source_volume:@destination_volume> -policy AutomatedFailOverDuplex`

. SnapMirror関係を初期化します。
`snapmirror initialize -destination-path <destination-consistency-group>`
. がおよび `Relationship Status`と表示される `SnapMirrored`のを待って、処理が成功したことを確認します `Mirrored State` `Insync`。
+
`snapmirror show -destination-path <destination_path>`

. ホストで、必要に応じて各クラスタにアクセスできるようにホスト接続を設定します。
. igroup設定を確立します。ローカル クラスタのイニシエータの優先パスを設定します。逆アフィニティを実現するために設定をピアクラスタにレプリケートするオプションを指定します。
+
`SiteA::> igroup create -vserver <svm_name> -ostype <os_type> -igroup <igroup_name> -replication-peer <peer_svm_name> -initiator <host>`

+

NOTE: ONTAP 9.16.1以降では、このコマンドでパラメータを使用し `-proximal-vserver local`ます。

+
`SiteA::> igroup add -vserver <svm_name> -igroup <igroup_name> -ostype <os_type> -initiator <host>`

+

NOTE: ONTAP 9.16.1以降では、このコマンドでパラメータを使用し `-proximal-vserver peer`ます。

. ホストからパスを検出し、優先クラスタからストレージLUNへのアクティブ / 最適化パスがホストに設定されていることを確認します。
. アプリケーションを導入し、VMワークロードをクラスタ間に分散して、必要な負荷分散を実現します。


.不均一な構成の手順
. アプリケーション内のすべてのボリュームをグループ化して新しいSnapMirror関係を作成します。双方向の同期レプリケーションを確立するには、必ず「AutomatedFailOverDuplex」ポリシーを指定してください。
+
`snapmirror create -source-path <source_path> -destination-path <destination_path> -cg-item-mappings <source_volume:@destination_volume> -policy AutomatedFailOverDuplex`

. SnapMirror関係を初期化します。
`snapmirror initialize -destination-path <destination-consistency-group>`
. がおよび `Relationship Status`と表示される `SnapMirrored`のを待って、処理が成功したことを確認します `Mirrored State` `Insync`。
+
`snapmirror show -destination-path <destination_path>`

. ホストで、必要に応じて各クラスタにアクセスできるようにホスト接続を設定します。
. ソースとデスティネーションの両方のクラスタでigroup構成を確立します。
+
`# primary site
SiteA::> igroup create -vserver <svm_name> -igroup <igroup_name> -initiator <host_1_name_>`

+
`# secondary site
SiteB::> igroup create -vserver <svm_name> -igroup <igroup_name> -initiator <host_2_name>`

. ホストからパスを検出し、優先クラスタからストレージLUNへのアクティブ / 最適化パスがホストに設定されていることを確認します。
. アプリケーションを導入し、VMワークロードをクラスタ間に分散して、必要な負荷分散を実現します。


--
====