---
sidebar: sidebar 
permalink: snapmirror-active-sync/protect-task.html 
keywords: SM-BC, snapmirror business continuity, consistency group, remote protection, destination, scsi, nvme 
summary: ビジネス継続性のための保護を設定するには、ONTAPソース クラスタでLUNを選択し、整合性グループに追加します。 
---
= ONTAP SnapMirror Active Syncで保護
:hardbreaks:
:toclevels: 1
:allow-uri-read: 
:toclevels: 1
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
SnapMirrorアクティブ同期は、非対称保護のほか、ONTAP 9.15.1以降では対称アクティブ / アクティブ保護も提供します。



== 非対称保護の設定

SnapMirrorアクティブ同期を使用した非対称保護を設定するには、ONTAPソース クラスタでLUNを選択し、整合性グループに追加します。

.開始する前に
* SnapMirror Synchronousライセンスが必要です。
* クラスタ管理者またはStorage VM管理者である必要があります。
* 整合性グループ内のコンスティチュエント ボリュームは、すべて1つのStorage VM（SVM）に含まれている必要があります。
+
** LUNが属するボリュームは同じである必要はありません。


* ソースとデスティネーションのクラスタを同じにすることはできません。
* ASAクラスタと非ASAクラスタの間にSnapMirrorアクティブ同期整合性グループ関係を確立することはできません。
* SnapMirrorアクティブ同期でクラスタ ピア関係を確立するには、デフォルトのIPspaceが必要です。カスタムのIPspaceはサポートされていません。
* 整合性グループの名前は一意である必要があります。
* セカンダリ（デスティネーション）クラスタ上のボリュームのタイプはDPでなければなりません。
* プライマリSVMとセカンダリSVMのピア関係が確立されている必要があります。


.手順
ONTAP CLIまたはSystem Managerを使用して整合性グループを設定できます。

ONTAP 9.10.1以降、ONTAPはSystem Managerにコンシステンシグループのエンドポイントとメニューを提供し、追加の管理ユーティリティを提供しています。ONTAP 9.10.1以降を使用している場合は、link:../consistency-groups/configure-task.html["整合性グループを設定する"]を参照してからlink:../consistency-groups/protect-task.html["保護を設定する"]を参照してSnapMirrorアクティブ同期関係を作成してください。


IMPORTANT: ONTAP 9.14.1から9.8では、SnapMirrorアクティブ同期はSnapMirror Business Continuity（SM-BC）と呼ばれます。

[role="tabbed-block"]
====
.System Manager
--
. プライマリ クラスタで、*[保護] > [概要] > [ビジネス継続性の保護] > [LUNの保護]* に移動します。
. 保護するLUNを選択し、保護グループに追加します。
. デスティネーションのクラスタとSVMを選択します。
. デフォルトでは*関係を初期化*が選択されています。保護を開始するには*保存*をクリックします。
. LUN の IOPS アクティビティを確認するには、* ダッシュボード > パフォーマンス * に移動します。
. デスティネーション クラスタで、System Manager を使用して、ビジネス継続性関係の保護が同期されていることを確認します：*保護 > 関係*。


--
.CLI
--
. デスティネーション クラスタから整合性グループ関係を作成します。
`destination::> snapmirror create -source-path _source-path_ -destination-path _destination-path_ -cg-item-mappings _volume-paths_ -policy _policy-name_`
+
 `snapmirror create`コマンドの `cg-item-mappings`パラメータを使用して、最大12個の構成ボリュームをマップできます。

+
次の例では、 `cg_src_ on the source with `vol1`と `vol2`の2つの整合性グループ、およびミラー化されたデスティネーション整合性グループ `cg_dst`を作成します。

+
`destination::> snapmirror create -source-path vs1_src:/cg/cg_src -destination-path vs1_dst:/cg/cg_dst -cg-item-mappings vol_src1:@vol_dst1,vol_src2:@vol_dst2 -policy AutomatedFailOverDuplex`

. デスティネーション クラスタから、整合性グループを初期化します。
+
`destination::>snapmirror initialize -destination-path _destination-consistency-group_`

. 初期化操作が正常に完了したことを確認してください。ステータスは `InSync`になります。
+
`snapmirror show`

. 各クラスタで igroup を作成し、LUN をアプリケーション ホスト上のイニシエーターにマップできるようにします。
`lun igroup create -igroup _name_ -protocol _fcp|iscsi_ -ostype _os_ -initiator _initiator_name_`
+
 `lun igroup create`の詳細については、link:https://docs.netapp.com/us-en/ontap-cli/lun-igroup-create.html["ONTAPコマンド リファレンス"^]を参照してください。

. 各クラスタで、LUNをigroupにマッピングします。
+
`lun map -path _path_name_ -igroup _igroup_name_`

.  `lun map`コマンドを実行して、LUNマッピングが正常に完了したことを確認します。その後、アプリケーションホスト上で新しいLUNを検出できます。


--
====


== 対称アクティブ / アクティブ保護の設定

対称保護は、System ManagerまたはONTAP CLIを使用して確立できます。どちらのインターフェースでも、xref:index.html#key-concepts[均一な構成と非均一な構成]の手順は異なります。

.開始する前に
* どちらのクラスタでも、ONTAP 9.15.1以降が実行されている必要があります。
* 対称アクティブ / アクティブ構成には `AutomatedFailoverDuplex`保護ポリシーが必要です。または、 `-type`が `automated-failover-duplex`である場合は、xref:../data-protection/create-custom-replication-policy-concept.html[カスタムSnapMirrorポリシーを作成する]を指定することもできます。
* ONTAP 9.15.1では、対称アクティブ / アクティブは2ノードクラスタでのみサポートされます。
* ONTAP 9.16.1 GA以降、SnapMirrorアクティブ同期は4ノードクラスタで対称アクティブ / アクティブ構成をサポートします。
+
** 4ノードクラスタでSnapMirror Active Syncを使用するには、ONTAP 9.16.1 GA以降を実行している必要があります。
** 4ノード構成を導入する前に、xref:../peering/create-cluster-relationship-93-later-task.adoc[クラスタ ピア関係を作成]する必要があります。
** 4ノードクラスタのxref:limits-reference.adoc[制限]を確認します。
** 2ノードクラスタに戻す場合は、戻す前にクラスタからSnapMirrorアクティブな同期関係を削除する必要があります。
** 4ノード構成を使用して、ストレージとコントローラーをアップグレードできます。このプロセスは中断を伴わず、ボリュームを新しいノードに移動しながらクラスタを拡張します。詳細については、link:upgrade-revert-task.html#refresh-a-cluster["クラスタを更新する"]をご覧ください。


* ONTAP 9.17.1以降では、両方のクラスタがONTAP 9.17.1以降を実行している場合にのみ、NVMe名前空間で対称アクティブ / アクティブ保護を設定できます。




== SCSI SnapMirrorアクティブ同期構成を使用した対称アクティブ / アクティブ保護の設定

.手順
System Manager または ONTAP CLI を使用して、SCSI プロトコル ホスト マッピングを使用した対称アクティブ / アクティブ保護を設定できます。

[role="tabbed-block"]
====
.System Manager
--
.均一な構成の手順
. プライマリサイトで、link:../consistency-groups/configure-task.html#create-a-consistency-group-with-new-luns-or-volumes["新しい LUN を使用して整合性グループを作成します。"^]
+
.. 整合性グループを作成する際は、igroupを作成するホスト イニシエータを指定します。
.. **SnapMirrorを有効にする**チェックボックスをオンにして、 `AutomatedFailoverDuplex`ポリシーを選択します。
.. 表示されるダイアログボックスで、igroup をレプリケートするには、「**イニシエータグループをレプリケートする**」チェックボックスをオンにします。「**近接設定の編集**」で、ホストの近接 SVM を設定します。
.. **保存**を選択します。




.不均一な構成の手順
. プライマリサイトで、link:../consistency-groups/configure-task.html#create-a-consistency-group-with-new-luns-or-volumes["新しい LUN を使用して整合性グループを作成します。"^]
+
.. 整合性グループを作成する際は、igroupを作成するホスト イニシエータを指定します。
.. **SnapMirrorを有効にする**チェックボックスをオンにして、 `AutomatedFailoverDuplex`ポリシーを選択します。
.. **保存**を選択して、LUN、整合性グループ、igroup、SnapMirror関係、およびigroupマッピングを作成します。


. セカンダリ サイトで、igroupを作成し、LUNをマッピングします。
+
.. **ホスト** > **SAN イニシエータ グループ** に移動します。
.. 新しい igroup を作成するには、**+ 追加**を選択します。
.. **名前** を入力し、**ホスト オペレーティング システム** を選択して、**イニシエーター グループ メンバー** を選択します。
.. 関係を初期化するには、**保存**を選択します。


. 新しいigroupをデスティネーションLUNにマッピングします。
+
.. **Storage** > **LUN** に移動します。
.. igroupにマッピングするLUNをすべて選択します。
.. **詳細**を選択し、**イニシエーター グループにマップ**を選択します。




--
.CLI
--
.均一な構成の手順
. アプリケーション内のすべてのボリュームをグループ化する新しいSnapMirror関係を作成します。双方向同期レプリケーションを確立するために `AutomatedFailOverDuplex`ポリシーを指定してください。
+
`snapmirror create -source-path <source_path> -destination-path <destination_path> -cg-item-mappings <source_volume:@destination_volume> -policy AutomatedFailOverDuplex`

+
例：次の例では、ソースに vol1 と vol2 を含む cg_src と、デスティネーションにミラー化された整合性グループ cg_dst という 2 つの整合性グループを作成します。

+
[listing]
----
destination::> snapmirror create -source-path vs1_src:/cg/cg_src -destination-path vs1_dst:/cg/cg_dst -cg-item-mappings vol_src1:@vol_dst1,vol_src2:@vol_dst2 -policy AutomatedFailOverDuplex
----
. SnapMirror 関係を初期化します：
`snapmirror initialize -destination-path <destination-consistency-group>`
.  `Mirrored State`が `SnapMirrored`として表示され、 `Relationship Status`が `Insync`として表示されるまで待機して、操作が成功したことを確認します。
+
`snapmirror show -destination-path <destination_path>`

. ホストで、必要に応じて、各クラスタにアクセスできるようホスト接続を設定します。
. igroupの設定を確立します。ローカルクラスタ上のイニシエータの優先パスを設定します。逆アフィニティのために、設定をピアクラスタにレプリケートするオプションを指定します。
+
`SiteA::> igroup create -vserver <svm_name> -ostype <os_type> -igroup <igroup_name> -replication-peer <peer_svm_name> -initiator <host>`

+

NOTE: ONTAP 9.16.1以降では、このコマンドで `-proximal-vserver local`パラメータを使用します。

+
`SiteA::> igroup add -vserver <svm_name> -igroup <igroup_name> -ostype <os_type> -initiator <host>`

+

NOTE: ONTAP 9.16.1以降では、このコマンドで `-proximal-vserver peer`パラメータを使用します。

. ホストからパスを検出し、優先クラスタからストレージLUNへのアクティブ / 最適化パスがホストに設定されていることを確認します。
. アプリケーションを導入し、VMワークロードをクラスタ間に分散して、必要な負荷分散を実現します。


.不均一な構成の手順
. アプリケーション内のすべてのボリュームをグループ化する新しいSnapMirror関係を作成します。双方向同期レプリケーションを確立するために `AutomatedFailOverDuplex`ポリシーを指定してください。
+
`snapmirror create -source-path <source_path> -destination-path <destination_path> -cg-item-mappings <source_volume:@destination_volume> -policy AutomatedFailOverDuplex`

+
例：次の例では、ソースに vol1 と vol2 を含む cg_src と、デスティネーションにミラー化された整合性グループ cg_dst という 2 つの整合性グループを作成します。

+
[listing]
----
destination::> snapmirror create -source-path vs1_src:/cg/cg_src -destination-path vs1_dst:/cg/cg_dst -cg-item-mappings vol_src1:@vol_dst1,vol_src2:@vol_dst2 -policy AutomatedFailOverDuplex
----
. SnapMirror 関係を初期化します：
`snapmirror initialize -destination-path <destination-consistency-group>`
.  `Mirrored State`が `SnapMirrored`として表示され、 `Relationship Status`が `Insync`として表示されるまで待機して、操作が成功したことを確認します。
+
`snapmirror show -destination-path <destination_path>`

. ホストで、必要に応じて、各クラスタにアクセスできるようホスト接続を設定します。
. ソースとデスティネーションの両方のクラスタでigroup設定を確立します。
+
`# primary site
SiteA::> igroup create -vserver <svm_name> -igroup <igroup_name> -initiator <host_1_name_>`

+
`# secondary site
SiteB::> igroup create -vserver <svm_name> -igroup <igroup_name> -initiator <host_2_name>`

. ホストからパスを検出し、優先クラスタからストレージLUNへのアクティブ / 最適化パスがホストに設定されていることを確認します。
. アプリケーションを導入し、VMワークロードをクラスタ間に分散して、必要な負荷分散を実現します。


--
====


== NVMeSnapMirrorアクティブ同期構成を使用して対称アクティブ / アクティブ保護を構成する

.開始する前に
対称アクティブ / アクティブ保護を構成するための要件に加えて、NVMeプロトコルを使用するときは、サポートされている構成とサポートされていない構成に注意する必要があります。

* 整合性グループには 1 つ以上のサブシステムを含めることができます。
* 整合性グループ内のボリュームには、複数のサブシステムからのネームスペースマップを設定できます。
* サブシステムは、複数の整合性グループに属する名前空間マップを持つことはできません。
* サブシステムには、整合性グループに属する名前空間マップと整合性グループに属さない名前空間マップを混在させることはできません。
* サブシステムには、同じ整合性グループに含まれるネームスペースマップが必要です。


.手順
ONTAP 9.17.1以降では、System ManagerまたはONTAP CLIを使用してコンシステンシ グループを作成し、NVMeプロトコル ホスト マッピングを使用して対称アクティブ / アクティブ保護を設定できます。

[role="tabbed-block"]
====
.System Manager
--
. プライマリ サイトで、link:../consistency-groups/configure-task.html#create-a-consistency-group-with-new-luns-or-volumes["新しいボリュームまたは NVMe 名前空間を使用して整合性グループを作成します。"^]
. *+Add*を選択し、*Using new NVMe namespaces*を選択します。
. 整合性グループ名を入力します。
. *詳細* を選択します。
. *保護*セクションで、*SnapMirrorを有効にする*を選択し、 `AutomatedFailoverDuplex`ポリシーを選択します。
. *ホスト マッピング* セクションで、*既存の NVMe サブシステム* または *新しい NVMe サブシステム* のいずれかを選択します。
. *近接*を選択して、近接SVMを変更します。デフォルトでは、ソースSVMが選択されています。
. 必要に応じて、別の NVMe サブシステムを追加します。


--
.CLI
--
. アプリケーションで使用されるすべてのNVMeネームスペースを含むすべてのボリュームをグループ化する新しいSnapMirror関係を作成します。 `AutomatedFailOverDuplex`ポリシーを指定して、双方向同期レプリケーションを確立してください。
+
`snapmirror create -source-path <source_path> -destination-path <destination_path> -cg-item-mappings <source_volume:@destination_volume> -policy AutomatedFailOverDuplex`

+
例：

+
[listing]
----
DST::> snapmirror create -source-path vs_src:/cg/cg_src_1 -destination-path vs_dst:/cg/cg_dst_1 -cg-item-mappings vs_src_vol1:@vs_dst_vol1,vs_src_vol2:@vs_dst_vol2 -policy AutomatedFailOverDuplex
----
. SnapMirror 関係を初期化します：
`snapmirror initialize -destination-path <destination-consistency-group>`
+
例：

+
[listing]
----
DST::> snapmirror initialize -destination-path vs1:/cg/cg_dst_1
----
.  `Mirrored State`が `SnapMirrored`として表示され、 `Relationship Status`が `Insync`として表示されるまで待機して、操作が成功したことを確認します。
+
`snapmirror show -destination-path <destination_path>`

+
プライマリ ボリューム内のNVMe名前空間に関連付けられたNVMeサブシステムは、セカンダリ クラスタに自動的にレプリケートされます。

. ホストで、必要に応じて、各クラスタにアクセスできるようホスト接続を設定します。
. 各ホストに近接するSVMを指定します。これにより、優先クラスタからのパスを使用してNVMeネームスペースへのホストアクセスが可能になります。これは、プライマリ クラスタ内のSVM_または_DRクラスタ内のSVMのいずれかになります。
+
次のコマンドは、SVM VS_A がホスト H1 に近いことを示し、VS_A を近位 SVM として設定します：

+
`SiteA::> vserver nvme subsystem host add -subsystem ss1 -host-nqn <H1_NQN> -proximal-vservers <VS_A>`

+
次のコマンドは、SVM VS_B がホスト H2 に近いことを示し、VS_B を近位 SVM として設定します：

+
`SiteB::> vserver nvme subsystem host add -subsystem ss1 -host-nqn <H2_NQN> -proximal-vservers <VS_B>`

. ホストからパスを検出し、優先クラスターからストレージへのアクティブ / 最適化されたパスがホストにあることを確認します。
. アプリケーションを導入し、VMワークロードをクラスタ間に分散して、必要な負荷分散を実現します。


--
====
.関連情報
* link:https://docs.netapp.com/us-en/ontap-cli/snapmirror-create.html["snapmirror create"^]
* link:https://docs.netapp.com/us-en/ontap-cli/snapmirror-initialize.html["snapmirror initialize"^]
* link:https://docs.netapp.com/us-en/ontap-cli/snapmirror-show.html["snapmirror show"^]

