---
sidebar: sidebar 
permalink: snapmirror-active-sync/upgrade-revert-task.html 
keywords: upgrade, revert, snapmirror active sync, SMBC, SM-BC 
summary: ONTAPのアップグレードまたはリバートは、SnapMirrorアクティブ同期関係に影響します。特にONTAP 9.9.1以降または9.7以前に移行する場合です。 
---
= ONTAP SnapMirror Active Syncによるアップグレードと復元
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
SnapMirror Active SyncはONTAP 9.9.1以降でサポートされています。ONTAPクラスタまたはコントローラのアップグレードとリバートは、アップグレードまたはリバートするONTAPのバージョンに応じて、SnapMirror Active Sync関係に影響を及ぼします。



== クラスタを更新する

ONTAP 9.16.1以降、SnapMirror active syncは対称型アクティブ / アクティブ構成の4ノードクラスタをサポートします。4ノードクラスタを使用して、コントローラとストレージをアップグレードできます。

.開始する前に
* link:protect-task.html#configure-symmetric-activeactive-protection["4ノードクラスタの要件"]を確認します。
* 技術更新プロセス中に非対称構成を作成できますが、更新が完了したら対称構成に戻す必要があります。
* これらの手順は、50個以下の整合性グループと400個以下のボリュームエンドポイントを持つ既存の4ノード構成に適用されます。


.手順
. link:../volumes/move-volume-task.html["すべてのSnapMirrorアクティブ同期ボリュームを_単一_の高可用性（HA）ペアに移動する"]。
. link:../system-admin/remove-nodes-cluster-concept.html["未使用のノードをクラスタから削除する"]。
. link:../system-admin/add-nodes-cluster-concept.html["新しいノードをクラスタに追加する"]。
. link:../volumes/move-volume-task.html["すべてのボリュームを移動する"]新しいノードに移動します。
. link:../system-admin/remove-nodes-cluster-concept.html["未使用のノードをクラスタから削除する"]次にそれらを置き換えますlink:../system-admin/add-nodes-cluster-concept.html["新しいノードで"]。




== SnapMirrorアクティブ同期を使用したONTAPのアップグレード

SnapMirrorアクティブ同期を使用するには、ソース クラスタとデスティネーション クラスタのすべてのノードでONTAP 9.9.1以降が実行されている必要があります。

アクティブなSnapMirrorアクティブ同期関係を持つONTAPをアップグレードする場合は、xref:../upgrade/automated-upgrade-task.html[自動無停止アップグレード（ANDU）]を使用する必要があります。ANDUを使用すると、アップグレードプロセス中にSnapMirrorアクティブ同期関係が同期され、正常な状態が維持されます。

ONTAPのアップグレードに向けてSnapMirrorアクティブ同期構成を準備するための設定手順はありません。ただし、アップグレードの前後に次の点を確認することを推奨します。

* SnapMirrorアクティブ同期関係が同期されている
* SnapMirrorに関連するエラーがイベント ログに記録されていない
* 両方のクラスタからMediatorがオンラインで、正常な状態である
* LUNを保護するために、すべてのホストがすべてのパスを正しく認識できる



NOTE: クラスタをONTAP 9.9.1または9.9.1からONTAP 9.10.1以降にアップグレードすると、ONTAPは、System Managerを使用して設定できるSnapMirrorアクティブ同期関係のソース クラスタとデスティネーション クラスタの両方に新しいxref:../consistency-groups/index.html[整合性グループ]を作成します。


NOTE:  `snapmirror quiesce`コマンドと `snampirror resume`コマンドはSnapMirror Active Sync ではサポートされません。



== ONTAP 9.10.1からONTAP 9.9.1へのリバート

9.10.1から9.9.1に関係を戻すには、SnapMirrorアクティブ同期関係を削除してから、9.10.1のコンシステンシ・グループ・インスタンスを削除する必要があります。アクティブなSnapMirrorアクティブ同期関係を持つコンシステンシ・グループは削除できません。9.9.1以前のバージョンで別のスマートコンテナまたはエンタープライズアプリケーションに関連付けられていたFlexVolボリュームを9.10.1にアップグレードした場合、それらのボリュームは、戻した時点で関連付けが解除されます。コンシステンシ・グループを削除しても、構成ボリュームやボリュームの細分スナップショットは削除されません。link:../consistency-groups/delete-task.html["整合性グループの削除"]ONTAP 9.10.1以降でのこのタスクの詳細については、「」を参照してください。



== ONTAP 9.9.1からのリバート


NOTE: SnapMirrorアクティブ同期は、ONTAP 9.9.1より前のリリースが混在するONTAPクラスタではサポートされません。

ONTAP 9.9.1から以前のリリースのONTAPにリバートする場合は、次の点に注意してください。

* クラスタがSnapMirrorアクティブ同期デスティネーションをホストしている場合、関係を解除して削除するまでONTAP 9.8以前にリバートすることはできません。
* クラスタがSnapMirrorアクティブ同期ソースをホストしている場合、関係を解放するまでONTAP 9.8以前にリバートすることはできません。
* ユーザが作成したカスタムのSnapMirrorアクティブ同期ポリシーは、ONTAP 9.8以前にリバートする前にすべて削除する必要があります。


これらの要件を満たすには、link:remove-configuration-task.html["SnapMirrorアクティブ同期設定の削除"]を参照してください。

.手順
. SnapMirrorアクティブ同期関係にあるいずれかのクラスタで次のコマンドを入力して、リバートの準備状況を確認します。
+
`cluster::> system node revert-to -version 9.7 -check-only`

+
次の出力例では、リバートする準備ができていないクラスタとクリーンアップ手順が示されています。

+
[listing]
----
cluster::> system node revert-to -version 9.7 -check-only
Error: command failed: The revert check phase failed. The following issues must be resolved before revert can be completed. Bring the data LIFs down on running vservers. Command to list the running vservers: vserver show -admin-state running Command to list the data LIFs that are up: network interface show -role data -status-admin up Command to bring all data LIFs down: network interface modify {-role data} -status-admin down
Disable snapshot policies.
    Command to list snapshot policies: "snapshot policy show".
    Command to disable snapshot policies: "snapshot policy modify -vserver
   * -enabled false"

   Break off the initialized online data-protection (DP) volumes and delete
   Uninitialized online data-protection (DP) volumes present on the local
   node.
    Command to list all online data-protection volumes on the local node:
   volume show -type DP -state online -node <local-node-name>
    Before breaking off the initialized online data-protection volumes,
   quiesce and abort transfers on associated SnapMirror relationships and
   wait for the Relationship Status to be Quiesced.
    Command to quiesce a SnapMirror relationship: snapmirror quiesce
    Command to abort transfers on a SnapMirror relationship: snapmirror
   abort
    Command to see if the Relationship Status of a SnapMirror relationship
   is Quiesced: snapmirror show
    Command to break off a data-protection volume: snapmirror break
    Command to break off a data-protection volume which is the destination
   of a SnapMirror relationship with a policy of type "vault": snapmirror
   break -delete-snapshots
    Uninitialized data-protection volumes are reported by the "snapmirror
   break" command when applied on a DP volume.
    Command to delete volume: volume delete

   Delete current version snapshots in advanced privilege level.
    Command to list snapshots: "snapshot show -fs-version 9.9.1"
    Command to delete snapshots: "snapshot prepare-for-revert -node
   <nodename>"

   Delete all user-created policies of the type active-strict-sync-mirror
   and active-sync-mirror.
   The command to see all active-strict-sync-mirror and active-sync-mirror
   type policies is:
    snapmirror policy show -type
   active-strict-sync-mirror,active-sync-mirror
   The command to delete a policy is :
    snapmirror policy delete -vserver <SVM-name> -policy <policy-name>
----
. 元に戻すチェックの要件を満たしたら、link:../revert/index.html["ONTAPのリバート"]を参照してください。


.関連情報
* link:https://docs.netapp.com/us-en/ontap-cli/search.html?q=network+interface["ネットワーク インターフェイス"^]
* link:https://docs.netapp.com/us-en/ontap-cli/snapmirror-break.html["snapmirror break"^]
* link:https://docs.netapp.com/us-en/ontap-cli/snapmirror-policy-delete.html["snapmirror policy delete"^]
* link:https://docs.netapp.com/us-en/ontap-cli/snapmirror-policy-show.html["snapmirror policy show"^]
* link:https://docs.netapp.com/us-en/ontap-cli/snapmirror-quiesce.html["snapmirror quiesce"^]
* link:https://docs.netapp.com/us-en/ontap-cli/snapmirror-show.html["snapmirror show"^]

