---
sidebar: sidebar 
permalink: snapmirror-active-sync/use-cases-concept.html 
keywords: SM-BC, SMBC, overview, benefits, use cases, architecture, snapmirror active sync 
summary: SnapMirror Active Syncを使用してアプリケーションをLUNで保護し、アプリケーションが透過的にフェイルオーバーできるようにして、災害発生時のビジネス継続性を確保します。 
---
= SnapMirrorアクティブ同期のユースケース
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
グローバルに接続されたビジネス環境が求められる中、サイバー攻撃、停電、自然災害などのシステム停止が発生した場合に、データ損失をゼロに抑えながら、ビジネスクリティカルなアプリケーションデータを迅速にリカバリすることが求められています。こうした要求は、金融などの分野や、一般データ保護規則（GDPR）などの規制要件を遵守する分野で高まっています。

SnapMirrorアクティブ同期には、次のようなユースケースがあります。

.アプリケーションの導入による目標復旧時間（RTO）ゼロ
SnapMirror Active Sync環境では、プライマリクラスタとセカンダリクラスタがあります。プライマリクラスタ内のLUN `1LP`）には(`L1s`セカンダリにミラーがあります。両方のLUNは同じシリアルIDを共有し、ホストに読み取り/書き込みLUNとして報告されます。ただし、読み取りおよび書き込み処理はプライマリLUNに対してのみ実行されます `1LP`。ミラーへの書き込みはすべて `L1S`プロキシによって処理されます。

.RTOゼロまたは透過的なアプリケーションフェイルオーバー（TAF）のためのアプリケーション導入
TAFは、ストレージへの無停止アクセスを実現するために、ホストのMPIOソフトウェアベースのパスフェイルオーバーに基づいています。プライマリ（L1P）とミラーコピー（L1S）の両方のLUNコピーは同じID（シリアル番号）を持ち、読み取り/書き込み可能としてホストに報告されます。ただし、読み取りと書き込みはプライマリボリュームでのみ処理されます。ミラーコピーに対して実行されたI/Oはプライマリコピーにプロキシされます。ホストからL1への優先パスはVS1：N1です。これは、Asymmetric Logical Unit Access（ALUA；非対称論理ユニットアクセス）のアクセス状態がActive Optimized（A/O；アクティブ最適化）に基づいています。ONTAP Mediatorは、環境の一部として必要です。主に、プライマリでストレージが停止した場合に（計画的または計画外の）フェイルオーバーを実行するために必要です。

SnapMirrorアクティブ同期では、ALUAが使用されます。ALUAは、アプリケーションホストのマルチパスソフトウェアに対して、優先順位およびアクセス可用性を指定してアドバタイズされたパスを使用して、アプリケーションホストとストレージアレイの通信を行うためのメカニズムです。ALUAは、LUNを所有するコントローラへのアクティブな最適パスおよびその他のパスをアクティブな非最適パスとしてマークします。このパスは、プライマリパスで障害が発生した場合にのみ使用されます。

.クラスタアプリケーション
VMware Metro Storage Cluster、Oracle RAC、Windows Failover Clustering with SQLなどのクラスタ化されたアプリケーションでは、パフォーマンスのオーバーヘッドなしでVMを他のサイトにフェイルオーバーできるように、同時アクセスが必要です。SnapMirrorアクティブ同期対称アクティブ/アクティブは、クラスタ化されたアプリケーションの要件を満たすために、双方向レプリケーションによってローカルでIOを提供します。ONTAP 9.16.1以降では、対称アクティブ/アクティブ構成が4ノードクラスタ構成でサポートされ、ONTAP 9.15.1の2ノードクラスタの制限から拡張されました。

.災害シナリオ
地理的に分散したサイト間で、アプリケーション用の複数のボリュームを同期的にレプリケートします。プライマリが停止した場合に自動的にセカンダリ コピーにフェイルオーバーできるため、ティア1アプリケーションのビジネス継続性を確保できます。プライマリ クラスタをホストしているサイトで災害が発生すると、ホストのマルチパス ソフトウェアはそのクラスタを経由するすべてのパスを停止とマークし、セカンダリ クラスタからのパスを使用します。その結果、ONTAP Mediatorによる無停止でのミラー コピーへのフェイルオーバーが可能になります。

.Windowsフェイルオーバー
SnapMirrorアクティブ同期は柔軟性に優れ、使いやすいアプリケーションレベルのきめ細かい対応と自動フェイルオーバーを実現します。SnapMirrorアクティブ同期では、実績のあるIPネットワーク経由のSnapMirror同期レプリケーションを使用して、LANまたはWAN経由でデータを高速でレプリケートします。これにより、仮想環境と物理環境の両方で、OracleやMicrosoft SQL Serverなどのビジネスクリティカルなアプリケーションのデータ可用性と高速なデータレプリケーションを実現できます。

SnapMirrorのアクティブな同期により、TAFからセカンダリコピーに至るまで、サイト全体に障害が発生してもミッションクリティカルなビジネスサービスの運用を継続できます。このフェイルオーバーをトリガーするための手動操作や追加のスクリプト作成は必要ありません。
