---
permalink: smb-hyper-v-sql/configure-shares-continuous-availability-task.html 
sidebar: sidebar 
keywords: configure, shares, continuous, availability, hyper, v, sql, server, virutal, machine, database, file 
summary: 共有を継続的可用性を確保するように変更します。Hyper-VおよびSQL Serverアプリケーションサーバで無停止アクセスを実現 
---
= 継続的可用性を確保するための既存の共有の設定
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
既存の共有を変更して、継続的可用性を備えた共有にすることができます。この共有は、Hyper-VおよびSQL ServerアプリケーションサーバがHyper-V仮想マシンおよび構成ファイルおよびSQL Serverデータベースファイルに無停止でアクセスするために使用します。

.タスクの内容
既存の共有に次の特徴がある場合、SMBを介したアプリケーションサーバでノンストップオペレーションを実現する継続的可用性を備えた共有として使用することはできません。

* その共有に共有プロパティが設定されている場合 `homedirectory`
* 共有に有効なシンボリックリンクまたはワイドリンクが含まれている場合
* 共有のルートの下にジャンクションされたボリュームが含まれている場合


次の2つの共有パラメータが正しく設定されていることを確認する必要があります。

*  `-offline-files`パラメータは（デフォルト）または `none`に設定されます `manual`。
* シンボリックリンクを無効にする必要があります。


次の共有プロパティを設定する必要があります。

* `continuously-available`
* `oplocks`


次の共有プロパティは設定しないでください。現在の共有プロパティのリストに含まれている場合は、継続的可用性を備えた共有から削除する必要があります。

* `attributecache`
* `branchcache`


.手順
. 現在の共有パラメータの設定と、設定済みの共有プロパティの現在のリストを表示します。
+
[source, cli]
----
vserver cifs share show -vserver <vserver_name> -share-name <share_name>
----
. 必要に応じて、コマンドを使用して共有パラメータを変更し、シンボリックリンクを無効にし、オフラインファイルをmanualに設定し `vserver cifs share modify` ます。
+
** シンボリックリンクを無効にするには、パラメータの値をに `""`設定し `-symlink`ます。
** を指定すると、パラメータを正しい設定に `manual`設定できます `-offline-files`。


. 共有プロパティを追加し、必要に応じて共有プロパティを追加し `continuously-available` `oplocks` ます。
+
[source, cli]
----
vserver cifs share properties add -vserver <vserver_name> -share-name <share_name> -share-properties continuously-available[,oplock]
----
+
共有プロパティがまだ設定されていない場合は `oplocks`、共有プロパティと一緒に追加する必要があります `continuously-available`。

. 継続的な可用性が確保された共有でサポートされていない共有プロパティを削除します。
+
[source, cli]
----
vserver cifs share properties remove -vserver <vserver_name> -share-name <share_name> -share-properties properties[,...]
----
+
共有プロパティをカンマで区切って指定すると、1つ以上の共有プロパティを削除できます。

. パラメータと `-offline-files`パラメータが正しく設定されていることを確認し `-symlink`ます。
+
[source, cli]
----
vserver cifs share show -vserver <vserver_name> -share-name <share_name> -fields symlink-properties,offline-files
----
. 設定済みの共有プロパティのリストが正しいことを確認します。
+
[source, cli]
----
vserver cifs share properties show -vserver <vserver_name> -share-name <share_name>
----


.例
次の例は、Storage Virtual Machine（SVM）「vs1」に「share1」という名前の既存の共有をSMBを介したアプリケーションサーバでのNDO用に設定する方法を示しています。

* パラメータをに設定すると、共有でシンボリックリンクが無効になります `-symlink` `""`。
*  `-offline-file`パラメータが変更され、に設定され `manual`ます。
*  `continuously-available`共有プロパティが共有に追加されます。
*  `oplocks`共有プロパティはすでに共有プロパティのリストに含まれているため、追加する必要はありません。
*  `attributecache`共有プロパティが共有から削除されます。
*  `browsable`共有プロパティは、SMBを介したアプリケーションサーバでのNDOに使用される継続的可用性を備えた共有では省略可能で、共有プロパティの1つとして保持されます。


[listing]
----
cluster1::> vserver cifs share show -vserver vs1 -share-name share1

                      Vserver: vs1
                        Share: share1
     CIFS Server NetBIOS Name: vs1
                         Path: /data
             Share Properties: oplocks
                               browsable
                               attributecache
           Symlink Properties: enable
      File Mode Creation Mask: -
 Directory Mode Creation Mask: -
                Share Comment: -
                    Share ACL: Everyone / Full Control
File Attribute Cache Lifetime: 10s
                  Volume Name: data
                Offline Files: documents
Vscan File-Operations Profile: standard

cluster1::> vserver cifs share modify -vserver vs1 -share-name share1 -offline-file manual -symlink ""

cluster1::> vserver cifs share properties add -vserver vs1 -share-name share1 -share-properties continuously-available

cluster1::> vserver cifs share properties remove -vserver vs1 -share-name share1 -share-properties attributecache

cluster1::> vserver cifs share show -vserver vs1 -share-name share1 -fields symlink-properties,offline-files
vserver  share-name symlink-properties offline-files
-------- ---------- ------------------ -------------
vs1      share1    -                  manual

cluster1::> vserver cifs share properties show -vserver vs1 -share-name share1

         Vserver: vs1
           Share: share1
Share Properties: oplocks
                  browsable
                  continuously-available
----