---
permalink: smb-hyper-v-sql/continuously-available-share-sql-concept.html 
sidebar: sidebar 
keywords: continuously, share, requirements, considerations, sql, server, smb, nondisuptive, snapcenter plug-in 
summary: ノンストップ オペレーションをサポートするSQL Server over SMB構成で継続的可用性を備えた共有を設定する場合は、一定の要件と考慮事項に注意する必要があります。 
---
= SQL Server over SMBでの継続的可用性を備えた共有の要件と考慮事項
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
ノンストップ オペレーションをサポートするSQL Server over SMB構成で継続的可用性を備えた共有を設定する場合は、一定の要件と考慮事項に注意する必要があります。



== 共有の要件

* 仮想マシン ファイルを格納するためのボリュームは、NTFSセキュリティ形式のボリュームとして作成されている必要があります。
+
継続的可用性を備えたSMB接続を使用してアプリケーション サーバのノンストップ オペレーションを実現するには、共有が含まれるボリュームがNTFSボリュームである必要があります。さらに、そのボリュームが以前から一貫してNTFSボリュームであることも必要です。mixedセキュリティ形式のボリュームまたはUNIXセキュリティ形式のボリュームをNTFSセキュリティ形式のボリュームに変更し、そのボリュームをSMB共有を介したノンストップ オペレーションに直接使用することはできません。mixedセキュリティ形式のボリュームをNTFSセキュリティ形式のボリュームに変更し、そのボリュームをSMB共有を介したノンストップ オペレーションに使用する場合は、ボリュームの一番上にACLを手動で配置し、格納されているすべてのファイルおよびフォルダにそのACLを適用する必要があります。そうしないと、仮想マシンの移行またはデータベース ファイルのエクスポート / インポートでファイルを別のボリュームに移動する際に、ソース ボリュームとデスティネーション ボリュームのどちらかが最初はmixedまたはUNIXセキュリティ形式のボリュームとして作成され、あとでNTFSセキュリティ形式に変更された場合、処理が失敗する可能性があります。

* アプリケーション サーバが使用する共有には、継続的可用性が設定されている必要があります。
+
継続的可用性を備えた共有に接続するアプリケーション サーバは永続的ハンドルを受け取ります。永続的ハンドルを使用すると、テイクオーバー、ギブバック、アグリゲートの再配置などの停止イベントのあとにSMB共有に無停止で再接続し、ファイル ロックを再取得することができます。

* データベース ファイルが格納されたボリュームにジャンクションを含めることはできますが、SQL Serverはデータベース ディレクトリ構造の作成時にジャンクションを横断しません。
* SnapCenter Plug-in for Microsoft SQL Serverの処理を正常に実行するには、ボリュームに十分な利用可能スペースが必要です。
+
SQL Serverデータベース ファイルを配置するボリュームには、共有内にあるデータベース ディレクトリ構造と、格納されているすべてのファイルを保持できる十分な容量が必要です。

* アプリケーション サーバが使用する継続的可用性を備えた共有では、次の共有プロパティを設定しないでください。
+
** ホーム ディレクトリ
** 属性のキャッシュ
** BranchCache






== 共有の考慮事項

* クォータは継続的可用性を備えた共有でサポートされます。
* SQL Server over SMB構成では、次の機能はサポートされません。
+
** 監査
** FPolicy


*  `continuously-availability` 共有プロパティが設定されている SMB 共有ではウイルス スキャンは実行されません。

