---
permalink: smb-hyper-v-sql/display-open-smb-files-task.html 
sidebar: sidebar 
keywords: display, information, open, smb, file, session, id, nondisruptive, protection, level 
summary: 開いているSMBファイルに関する情報（SMB接続とセッションID、ホスティング ボリューム、共有名、共有パスなど）を表示できます。また、ファイルの継続的可用性保護レベルに関する情報も表示できます。これは、開いているファイルが無停止運用をサポートできる状態にあるかどうかを判断するのに役立ちます。 
---
= ONTAP でオープンしている SMB ファイルに関する情報を表示する
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
開いているSMBファイルに関する情報（SMB接続とセッションID、ホスティング ボリューム、共有名、共有パスなど）を表示できます。また、ファイルの継続的可用性保護レベルに関する情報も表示できます。これは、開いているファイルが無停止運用をサポートできる状態にあるかどうかを判断するのに役立ちます。

.タスク概要
確立されたSMBセッションで開いているファイルに関する情報を表示できます。これは、SMBセッション内の特定のファイルに関するSMBセッション情報を確認する必要がある場合に役立ちます。

たとえば、一部の開いているファイルが継続的に利用可能な保護で開かれており、一部のファイルが継続的に利用可能な保護で開かれていない SMB セッションがある場合（ `vserver cifs session show`コマンド出力の `-continuously-available`フィールドの値が `Partial`）、このコマンドを使用して、継続的に利用可能でないファイルを判別できます。

 `vserver cifs session file show`コマンドをオプション パラメータなしで使用すると、ストレージ仮想マシン（SVM）上で確立されたSMBセッションで開いているすべてのファイルの情報を概要形式で表示できます。

ただし、多くの場合、大量の出力が返されます。オプションのパラメータを指定すると、出力に表示される情報をカスタマイズできます。これは、開いているファイルの一部のみに関する情報を表示する場合に便利です。

* オプションの `-fields`パラメータを使用して、選択したフィールドに出力を表示できます。
+
このパラメータは、単独で、または他のオプションのパラメータと組み合わせて使用できます。

*  `-instance`パラメータを使用すると、開いている SMB ファイルに関する詳細情報を表示できます。
+
このパラメータは、単独で、または他のオプションのパラメータと組み合わせて使用できます。



.手順
. 次のいずれかを実行します。
+
|===
| 開いている SMB ファイルを表示する場合： | 入力するコマンド 


 a| 
SVM（概要）
 a| 
`*vserver cifs session file show -vserver _vserver_name_*`



 a| 
指定したノード
 a| 
`*vserver cifs session file show -vserver _vserver_name_ -node {node_name|local}*`



 a| 
指定したファイルID
 a| 
`*vserver cifs session file show -vserver _vserver_name_ -file-id integer*`



 a| 
指定したSMB接続ID
 a| 
`*vserver cifs session file show -vserver _vserver_name_ -connection-id integer*`



 a| 
指定したSMBセッションID
 a| 
`*vserver cifs session file show -vserver _vserver_name_ -session-id integer*`



 a| 
指定したホスティング アグリゲート
 a| 
`*vserver cifs session file show -vserver _vserver_name_ -hosting-aggregate _aggregate_name_*`



 a| 
指定したボリューム
 a| 
`*vserver cifs session file show -vserver _vserver_name_ -hosting-volume _volume_name_*`



 a| 
指定したSMB共有
 a| 
`*vserver cifs session file show -vserver _vserver_name_ -share _share_name_*`



 a| 
指定したSMBパス
 a| 
`*vserver cifs session file show -vserver _vserver_name_ -path _path_*`



 a| 
指定したレベルの継続的可用性の保護
 a| 
`*vserver cifs session file show -vserver _vserver_name_ -continuously-available _continuously_available_status_*`

 `-continuously-available`の値は次のいずれかになります：

** `No`
** `Yes`
+
[NOTE]
====
継続的可用性ステータスが `No`の場合、これらのオープンファイルはテイクオーバーおよびギブバックから無停止でリカバリできないことを意味します。また、高可用性関係にあるパートナー間の一般的なアグリゲートの再配置からもリカバリできません。

====




 a| 
指定した再接続状態
 a| 
`*vserver cifs session file show -vserver _vserver_name_ -reconnected _reconnected_state_*`

 `-reconnected`の値は次のいずれかになります：

** `No`
** `Yes`
+
[NOTE]
====
再接続状態が `No`の場合、開いているファイルは切断イベント後に再接続されていません。これは、ファイルが切断されなかったか、ファイルが切断された後に再接続に失敗したことを意味します。再接続状態が `Yes`の場合、開いているファイルは切断イベント後に正常に再接続されたことを意味します。

====


|===
+
出力結果を絞り込むために使用できる追加のオプションパラメータがあります。この手順で説明されているコマンドの詳細については、link:https://docs.netapp.com/us-en/ontap-cli/["ONTAPコマンド リファレンス"^]を参照してください。



.例
次の例は、SVM vs1の開いているファイルに関する情報を表示します。

[listing]
----
cluster1::> vserver cifs session file show -vserver vs1
Node:       node1
Vserver:    vs1
Connection: 3151274158
Session:    1
File    File      Open Hosting               Continuously
ID      Type      Mode Volume    Share       Available
------- --------- ---- --------- ----------- ------------
41      Regular   r    data      data        Yes
Path: \mytest.rtf
----
次の例は、SVM vs1のファイルID 82の開いているSMBファイルに関する詳細情報を表示します。

[listing]
----
cluster1::> vserver cifs session file show -vserver vs1 -file-id 82 -instance

                  Node: node1
               Vserver: vs1
               File ID: 82
         Connection ID: 104617
            Session ID: 1
             File Type: Regular
             Open Mode: rw
Aggregate Hosting File: aggr1
   Volume Hosting File: data1
            CIFS Share: data1
  Path from CIFS Share: windows\win8\test\test.txt
            Share Mode: rw
           Range Locks: 1
Continuously Available: Yes
           Reconnected: No
----