---
permalink: smb-hyper-v-sql/licensing-requirements-concept.html 
sidebar: sidebar 
keywords: ontap, license, requirement, nondisruptive, hyper, v, smb, sql, server 
summary: SVM でノンストップオペレーションを実現する SQL Server over SMB または Hyper-V over SMB ソリューションを作成するときは、 ONTAP とライセンスの特定の要件について理解しておく必要があります。 
---
= ONTAP とライセンスの要件
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
SVM でノンストップオペレーションを実現する SQL Server over SMB または Hyper-V over SMB ソリューションを作成するときは、 ONTAP とライセンスの特定の要件について理解しておく必要があります。



== ONTAP のバージョンの要件

* Hyper-V over SMB
+
ONTAP では、 Windows Server 2012 以降で実行される Hyper-V での SMB 共有を介したノンストップオペレーションがサポートされます。

* SQL Server over SMB
+
ONTAP では、 Windows Server 2012 以降で実行される SQL Server 2012 以降での SMB 共有を介したノンストップオペレーションがサポートされます。



SMB 共有を介したノンストップオペレーションがサポートされる ONTAP 、 Windows Server 、および SQL Server のバージョンの最新情報については、 Interoperability Matrix を参照してください。

https://["NetApp Interoperability Matrix Tool で確認できます"^]



== ライセンス要件

次のライセンスが必要です。

* CIFS
* FlexClone （ Hyper-V over SMB のみ）
+
このライセンスは、バックアップにリモート VSS を使用する場合に必要になります。シャドウコピーサービスでは、バックアップの作成時に使用されるファイルのポイントインタイムコピーを作成するために FlexClone が使用されます。

+
リモート VSS を使用しないバックアップ方式を使用する場合、 FlexClone ライセンスはオプションです。


