---
permalink: smb-hyper-v-sql/network-data-lif-requirements-concept.html 
sidebar: sidebar 
keywords: network, data, lif, requirements, hyper, v, sql, server, protocol 
summary: ノンストップオペレーション用に SQL Server または Hyper-V over SMB 構成を作成する場合、一定のネットワークとデータ LIF 要件について理解しておく必要があります。 
---
= ネットワークとデータ LIF の要件
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
ノンストップオペレーション用に SQL Server または Hyper-V over SMB 構成を作成する場合、一定のネットワークとデータ LIF 要件について理解しておく必要があります。



== ネットワークプロトコルの要件

* IPv4 および IPv6 のネットワークがサポートされています。
* SMB 3.0 以降が必要です。
+
SMB 3.0 には、ノンストップオペレーションを実現するために必要となる継続的可用性を備えた SMB 接続の確立に欠かせない機能が備わっています。

* DNS サーバには、 CIFS サーバ名を Storage Virtual Machine （ SVM ）上のデータ LIF に割り当てられた IP アドレスにマッピングするエントリが格納されている必要があります。
+
通常、 Hyper-V または SQL Server アプリケーションサーバは、仮想マシンまたはデータベースファイルへのアクセス時に複数のデータ LIF を介して複数の接続を確立します。正常に機能するには、アプリケーションサーバは、複数の一意の IP アドレスへの複数の接続を確立するのではなく、 CIFS サーバ名を使用してこのような複数の SMB 接続を確立する必要があります。

+
監視でも、個々の LIF の IP アドレスではなく CIFS サーバの DNS 名を使用する必要があります。

+
ONTAP 9.4 以降では、 SMB マルチチャネルを有効にすることで、 Hyper-V over SMB 構成と SQL Server over SMB 構成のスループットとフォールトトレランスを向上させることができます。そのためには、クラスタとクライアントに 1G 、 10G 、またはそれ以上の NIC を複数導入しておく必要があります。





== データ LIF の要件

* SMB 解決策経由のアプリケーションサーバをホストする SVM には、クラスタ内のすべてのノードに稼働しているデータ LIF が少なくとも 1 つ必要です。
+
SVM データ LIF は、アプリケーションサーバがアクセスするデータを現在ホストしていないノードを含む、クラスタ内の他のデータポートにフェイルオーバーできます。さらに、監視ノードは常に、アプリケーションサーバが接続されているノードの SFO パートナーであるため、クラスタ内のどのノードも監視ノードになる可能性があります。

* データ LIF は、自動リバートするように設定されていない必要があります。
+
テイクオーバーまたはギブバックの発生後は、データ LIF をホームポートに手動でリバートする必要があります。

* データ LIF のすべての IP アドレスが DNS 内にエントリを保持する必要があり、すべてのエントリが CIFS サーバ名に解決される必要があります。
+
アプリケーションサーバは、 CIFS サーバ名を使用して SMB 共有に接続する必要があります。LIF IP アドレスを使用して接続を確立するようにアプリケーションサーバを設定しないでください。

* CIFS サーバ名が SVM 名と異なる場合は、 DNS エントリが CIFS サーバ名に解決される必要があります。

