---
permalink: smb-hyper-v-sql/odx-copy-offload-requirements-concept.html 
sidebar: sidebar 
keywords: odx, copy, offload, requirements, sql, server, hyper, v, smb, virtual 
summary: アプリケーションサーバーを経由せずに仮想マシンファイルを移行する場合、またはデータベースファイルをソースからターゲットストレージに直接エクスポートおよびインポートする場合は、ODXコピー オフロードを有効にする必要があります。SQL ServerおよびHyper-V over SMBソリューションでODXコピー オフロードを使用するには、理解しておくべき特定の要件があります。 
---
= SQL ServerおよびHyper-V over SMB用のODXコピー オフロード要件
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
アプリケーションサーバーを経由せずに仮想マシンファイルを移行する場合、またはデータベースファイルをソースからターゲットストレージに直接エクスポートおよびインポートする場合は、ODXコピー オフロードを有効にする必要があります。SQL ServerおよびHyper-V over SMBソリューションでODXコピー オフロードを使用するには、理解しておくべき特定の要件があります。

ODXコピー オフロードを使用すると、パフォーマンスが大幅に向上します。このCIFSサーバー オプションはデフォルトで有効になっています。

* ODXコピー オフロードを使用するには、SMB 3.0を有効にする必要があります。
* ソース ボリュームは1.25GB以上でなければなりません。
* コピー オフロードに使用するボリュームで重複排除を有効にする必要があります。
* 圧縮されたボリュームを使用する場合は、圧縮形式をアダプティブにする必要があります。サポートされる圧縮グループ サイズは8Kのみです。
+
二次圧縮タイプはサポートされていません

* ODXコピー オフロードを使用してディスク内およびディスク間でHyper-Vゲストを移行するには、SCSIディスクを使用するようにHyper-Vサーバーを構成する必要があります。
+
デフォルトでは IDE ディスクが構成されますが、IDE ディスクを使用してディスクが作成されている場合、ゲストの移行時に ODX コピー オフロードは機能しません。


