---
permalink: smb-hyper-v-sql/remote-vss-concepts-concept.html 
sidebar: sidebar 
keywords: remove, vss, concepts, volume, shadow, copy, service, hyper, v, smb, configuration 
summary: ここでは、リモートVSS（ボリューム シャドウ コピー サービス）の概念について説明します。リモートVSSがHyper-V over SMB構成でバックアップ サービスによってどのように使用されるかを理解するには、これらの概念を理解しておく必要があります。 
---
= リモートVSSの概念
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
ここでは、リモートVSS（ボリューム シャドウ コピー サービス）の概念について説明します。リモートVSSがHyper-V over SMB構成でバックアップ サービスによってどのように使用されるかを理解するには、これらの概念を理解しておく必要があります。

* *VSS（Volume Shadow Copy Service）*
+
特定のボリューム上のデータの特定の時点におけるバックアップ コピー（スナップショット）を作成するMicrosoftのテクノロジです。データ サーバ、バックアップ アプリケーション、およびストレージ管理ソフトウェアを調整して、整合性のあるバックアップの作成と管理をサポートします。

* *リモート VSS（Remote Volume Shadow Copy Service）*
+
SMB 3.0共有経由でデータにアクセスした際に、特定の時点におけるデータの整合性が保たれた状態にあるデータの共有ベースのバックアップコピーを作成するために使用されるMicrosoftテクノロジー。_Volume Shadow Copy Service_とも呼ばれます。

* *shadow copy*
+
共有に含まれるデータセットの明確に定義された特定の時点における複製です。シャドウ コピーを使用すると、システムやアプリケーションによる元のボリュームのデータ更新を継続したまま、整合性が取れたポイントインタイム バックアップを作成できます。

* *シャドウ コピー セット*
+
1つ以上のシャドウ コピーの集合です。各シャドウ コピーが1つの共有に対応します。シャドウ コピー セット内のシャドウ コピーに対応する共有は、すべて同じ処理でバックアップする必要があります。セットに含めるシャドウ コピーは、VSSに対応したアプリケーションのVSSクライアントで識別されます。

* *シャドウ コピー セットの自動リカバリ*
+
リモートVSSに対応したバックアップ アプリケーションのバックアップ プロセスの一部で、シャドウ コピーを格納するレプリカ ディレクトリのある時点での整合性が確保されます。バックアップの開始時に、アプリケーションのVSSクライアントで、バックアップ対象としてスケジュールされたデータ（Hyper-Vの場合は仮想マシン ファイル）にソフトウェア チェックポイントを設定する処理が開始されます。その後、VSSクライアントでアプリケーションの実行を継続できます。シャドウ コピー セットが作成されると、リモートVSSによってシャドウ コピー セットが書き込み可能にされ、書き込み可能なコピーがアプリケーションに公開されます。アプリケーションでは、シャドウ コピー セットをバックアップする準備として、前の処理で作成されたソフトウェア チェックポイントを使用して自動リカバリを実行します。自動リカバリでは、チェックポイントの作成後にファイルやフォルダに対して行われた変更を元に戻すことで、シャドウ コピーを整合性が取れた状態にします。自動リカバリは、VSSに対応したバックアップ向けのオプションの手順です。

* *シャドウ コピーID*
+
シャドウ コピーを一意に識別するGUIDです。

* *シャドウ コピー セットID*
+
同じサーバに対する一連のシャドウ コピーIDを一意に識別するGUIDです。

* *SnapManager for Hyper-V*
+
Microsoft Windows Server 2012 Hyper-Vのバックアップ / リストア処理を自動化して簡易化するソフトウェアです。リモートVSSと自動リカバリを使用して、SMB共有経由でHyper-Vファイルをバックアップします。



.関連情報
xref:nondisruptive-operations-glossary-concept.adoc[Hyper-VおよびSQL Server over SMBでのノンストップ オペレーションの主要な概念]

xref:share-based-backups-remote-vss-concept.adoc[リモートVSSによる共有ベースのバックアップ]
