---
permalink: smb-hyper-v-sql/server-volume-requirements-sql-serve-concept.html 
sidebar: sidebar 
keywords: smb, cifs, server, volume, requirement, sql, nondisruptive, operation 
summary: ノンストップオペレーション用に SQL Server over SMB 構成を作成する場合、 SMB サーバとボリュームの要件について理解しておく必要があります。 
---
= SQL Server over SMB 用の SMB サーバとボリュームの要件
:icons: font
:imagesdir: ../media/


[role="lead"]
ノンストップオペレーション用に SQL Server over SMB 構成を作成する場合、 SMB サーバとボリュームの要件について理解しておく必要があります。



== SMB サーバの要件

* SMB 3.0 が有効になっている必要があります。
+
これはデフォルトで有効になっています。

* デフォルトの UNIX ユーザの CIFS サーバオプションが、有効な UNIX ユーザアカウントを使用して設定されている必要があります。
+
アプリケーションサーバでは、 SMB 接続を確立する際にマシンアカウントが使用されます。すべての SMB アクセスで、 Windows ユーザが任意の UNIX ユーザアカウントまたはデフォルトの UNIX ユーザアカウントに正常にマッピングされる必要があるため、 ONTAP は、アプリケーションサーバのマシンアカウントをデフォルトの UNIX ユーザアカウントにマッピングできる必要があります。

+
さらに、 SQL Server はドメインユーザを SQL Server サービスアカウントとして使用します。サービスアカウントは、デフォルトの UNIX ユーザにもマッピングする必要があります。

* 自動ノードリファーラルを無効にする必要があります（この機能はデフォルトで無効になります）。
+
SQL Server データベースファイル以外のデータへのアクセスに自動ノードリファーラルを使用する場合、そのデータ用の SVM を個別に作成する必要があります。

* ONTAP への SQL Server のインストールに使用する Windows ユーザアカウントには、 SeSecurityPrivilege 権限を割り当てる必要があります。
+
この権限は、 SMB サーバのローカル BUILTIN\Administrators グループに割り当てられます。





== ボリューム要件：

* 仮想マシンファイルを格納するためのボリュームは、 NTFS セキュリティ形式のボリュームとして作成されている必要があります。
+
継続的な可用性が確保された SMB 接続を使用してアプリケーションサーバの NDO を実現するには、共有を含むボリュームが NTFS ボリュームである必要があります。さらに、そのボリュームが常に NTFS ボリュームである必要があります。mixed セキュリティ形式のボリュームまたは UNIX セキュリティ形式のボリュームを NTFS セキュリティ形式のボリュームに変更し、そのボリュームを SMB 共有を介して直接 NDO に使用することはできません。mixed セキュリティ形式のボリュームを NTFS セキュリティ形式のボリュームに変更し、 SMB 共有を介して NDO に使用する場合は、ボリュームの一番上に ACL を手動で配置し、格納されているすべてのファイルおよびフォルダにその ACL を適用する必要があります。そうしないと、ソースボリュームまたはデスティネーションボリュームが最初は mixed セキュリティ形式または UNIX セキュリティ形式のボリュームとして作成され、あとで NTFS セキュリティ形式に変更された場合は、ファイルを別のボリュームに移動する仮想マシンの移行またはデータベースファイルのエクスポートとインポートに失敗する可能性があります。

* データベースファイルが格納されたボリュームにジャンクションを含めることはできますが、 SQL Server はデータベースディレクトリ構造の作成時にジャンクションを横断しません。
* SnapManager for Microsoft SQL Server のバックアップ処理を正常に実行するには、ボリュームに十分な利用可能スペースが必要です。
+
SQL Server データベースファイルを格納するボリュームには、共有内にあるデータベースディレクトリ構造と、格納されているすべてのファイルを格納できる十分な容量が必要です。



* 関連情報 *

http://technet.microsoft.com/en-us/library/["Microsoft TechNet ライブラリ： technet.microsoft.com/en-us/library/"]
