---
permalink: smb-hyper-v-sql/server-volume-requirements-sql-serve-concept.html 
sidebar: sidebar 
keywords: smb, cifs, server, volume, requirement, sql, nondisruptive, operation, snapcenter plug-in 
summary: ノンストップ オペレーション用にSQL Server over SMB構成を作成する場合、SMBサーバとボリュームの要件について理解しておく必要があります。 
---
= SQL Server over SMB用のSMBサーバとボリュームの要件
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
ノンストップ オペレーション用にSQL Server over SMB構成を作成する場合、SMBサーバとボリュームの要件について理解しておく必要があります。



== SMBサーバの要件

* SMB 3.0が有効になっている必要があります。
+
この機能は、デフォルトで有効に設定されています。

* デフォルトのUNIXユーザのCIFSサーバ オプションが、有効なUNIXユーザ アカウントを使用して設定されている必要があります。
+
アプリケーション サーバでは、SMB接続を確立する際にマシン アカウントが使用されます。すべてのSMBアクセスで、Windowsユーザが任意のUNIXユーザ アカウントまたはデフォルトのUNIXユーザ アカウントに正常にマッピングされる必要があるため、ONTAPは、アプリケーション サーバのマシン アカウントをデフォルトのUNIXユーザ アカウントにマッピングできる必要があります。

+
さらに、SQL Serverはドメイン ユーザをSQL Serverサービス アカウントとして使用します。サービス アカウントは、デフォルトUNIXユーザにもマッピングする必要があります。

* 自動ノード リファーラルを無効にする必要があります（この機能はデフォルトで無効になります）。
+
SQL Serverデータベース ファイル以外のデータへのアクセスに自動ノード リファーラルを使用する場合、そのデータ用のSVMを個別に作成する必要があります。

* ONTAPへのSQL Serverのインストールに使用するWindowsユーザ アカウントには、SeSecurityPrivilege権限を割り当てる必要があります。
+
この権限は、SMBサーバのローカルBUILTIN\Administratorsグループに割り当てられています。





== ボリュームの要件

* 仮想マシン ファイルを格納するためのボリュームは、NTFSセキュリティ形式のボリュームとして作成されている必要があります。
+
継続的可用性を備えたSMB接続を使用してアプリケーション サーバのNDOを実現するには、共有を含むボリュームがNTFSボリュームである必要があります。さらに、そのボリュームが以前から一貫してNTFSボリュームであることも必要です。mixedセキュリティ形式のボリュームまたはUNIXセキュリティ形式のボリュームをNTFSセキュリティ形式のボリュームに変更し、そのボリュームをSMB共有を介して直接NDOに使用することはできません。mixedセキュリティ形式のボリュームをNTFSセキュリティ形式のボリュームに変更し、SMB共有を介してNDOに使用する場合は、ボリュームの最上位にACLを手動で配置し、格納されているすべてのファイルおよびフォルダにそのACLを適用する必要があります。そうしないと、仮想マシンの移行またはデータベース ファイルのエクスポート / インポートでファイルを別のボリュームに移動する際に、ソース ボリュームとデスティネーション ボリュームのどちらかが最初はmixedまたはUNIXセキュリティ形式のボリュームとして作成され、あとでNTFSセキュリティ形式に変更された場合、処理が失敗する可能性があります。

* データベース ファイルが格納されたボリュームにジャンクションを含めることはできますが、SQL Serverはデータベース ディレクトリ構造の作成時にジャンクションを横断しません。
* SnapCenter Plug-in for Microsoft SQL Serverのバックアップ処理を正常に実行するには、ボリュームに十分な利用可能スペースが必要です。
+
SQL Serverデータベース ファイルを配置するボリュームには、共有内にあるデータベース ディレクトリ構造と、格納されているすべてのファイルを保持できる十分な容量が必要です。



.関連情報
http://technet.microsoft.com/en-us/library/["Microsoft TechNetライブラリ：technet.microsoft.com/ja-jp/library/"]
