---
permalink: smb-hyper-v-sql/smb-30-supports-nondisruptive-operations-concept.html 
sidebar: sidebar 
keywords: smb, functionality, support, nondisruptive, operations, shares, clients, hyper, v, sql, server 
summary: SMB 3.0 には、 Hyper-V over SMB および SQL Server over SMB 共有のノンストップオペレーションをサポートするためのきわめて重要な機能があります。これには、継続的可用性を備えた共有プロパティや、ファイルオープン状態を再要求して SMB 接続を透過的に再確立できる永続的ハンドルと呼ばれるファイルハンドルが含まれます。 
---
= SMB 3.0 の機能が SMB 共有を介したノンストップオペレーションをサポートする仕組み
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
SMB 3.0 には、 Hyper-V over SMB および SQL Server over SMB 共有のノンストップオペレーションをサポートするためのきわめて重要な機能があります。これには 'continuously-available 共有プロパティと 'a_persistent handle_として 知られるファイル・ハンドルのタイプが含まれますこれにより SMB クライアントは ' ファイル・オープン状態を再要求して SMB 接続を透過的に再確立できます

永続的ハンドルは、継続的な可用性が設定された共有に接続する SMB 3.0 対応のクライアントに付与できます。SMB セッションが切断された場合、 CIFS サーバは永続的ハンドルの状態に関する情報を保持します。CIFS サーバは、クライアントが再接続できる 60 秒間は他のクライアント要求をブロックするため、永続的ハンドルを持つクライアントは、ネットワークの切断後にハンドルを再要求できます。永続的ハンドルを持つクライアントは、 Storage Virtual Machine （ SVM ）のデータ LIF のいずれかを使用して、同じ LIF または別の LIF を介して再接続できます。

アグリゲートの再配置、テイクオーバー、およびギブバックはすべて、 SFO ペア間で行われます。永続的ハンドルを持つファイルを使用したセッションの切断と再接続をシームレスに管理するために、パートナーノードでは、すべての永続的ハンドルのロック情報のコピーが保持されます。イベントが計画的か計画外かに関係なく、 SFO パートナーは、永続的ハンドルの再接続を無停止で管理できます。この新機能を使用すると、従来では業務が停止する状況となるイベントでも、 CIFS サーバへの SMB 3.0 接続を、 SVM に割り当てられた別のデータ LIF に透過的に無停止でフェイルオーバーできます。

永続的ハンドルを使用すると、 CIFS サーバで SMB 3.0 接続を透過的にフェイルオーバーできるようになりますが、障害が発生したために Hyper-V アプリケーションが Windows Server クラスタ内の別のノードにフェイルオーバーされる場合、クライアントは切断されたハンドルのファイルハンドルを再要求できません。このシナリオでは、切断された状態のファイルハンドルによって、別のノードで再起動した Hyper-V アプリケーションのアクセスがブロックされる可能性があります。「フェイルオーバークラスタリング」は、 SMB 3.0 の一部で、古い競合するハンドルを無効にするメカニズムを提供して、このシナリオに対処します。このメカニズムを使用すると、 Hyper-V クラスタノードに障害が発生した場合に、 Hyper-V クラスタを迅速にリカバリできます。
