---
permalink: smb-hyper-v-sql/smb-share-config-worksheet-reference.html 
sidebar: sidebar 
keywords: complete, smb, share, configuration, worksheet, information, settings 
summary: このワークシートを使用して、SQL ServerおよびHyper-V over SMB構成用の継続的可用性を備えたSMB共有を作成する際に必要となる値を記録してください。 
---
= SMB共有設定ワークシートに記入する
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
このワークシートを使用して、SQL ServerおよびHyper-V over SMB構成用の継続的可用性を備えたSMB共有を作成する際に必要となる値を記録してください。



== SMB共有のプロパティと設定に関する情報

共有ごとに、次の情報を指定する必要があります。

* Storage Virtual Machine（SVM）名
+
SVM 名はすべての共有で同じです

* 共有名
* パス
* 共有プロパティ
+
次の2つの共有プロパティを設定する必要があります。

+
** `oplocks`
** `continuously-available`




次の共有プロパティは設定しないでください。

* `homedirectory attributecache`
* `branchcache`
* `access-based-enumeration`
+
** シンボリックリンクを無効にする必要があります（パラメータの値 `-symlink-properties`はnull [""]にする必要があります）。






== 共有パスに関する情報

リモートVSSを使用してHyper-Vファイルをバックアップする場合は、Hyper-Vサーバから仮想マシンファイルの格納場所へのSMB接続を確立する際に使用する共有パスの選択が重要になります。共有はネームスペース内の任意のポイントに作成できますが、Hyper-Vサーバで使用される共有のパスに結合されたボリュームを含めることはできません。ジャンクションポイントを含む共有パスでシャドウコピー処理を実行することはできません。

データベースディレクトリ構造を作成する場合、SQL Serverはジャンクションを横断できません。ジャンクションポイントを含むSQL Serverの共有パスは作成しないでください。

たとえば、次に示すネームスペースを例にとると、仮想マシンファイルまたはデータベースファイルをボリューム「vol1」、「vol2」、「vol3」、および「vol4」に格納する場合、アプリケーションサーバの共有をパス、、 `/data1/vol2`、 `/data2/vol3`およびに `/data2/vol4`作成する必要があります `/data1/vol1`。

[listing]
----

                     Junction                       Junction
Vserver Volume       Active   Junction Path         Path Source
------- ------------ -------- -------------------   -----------
vs1     data1         true     /data1               RW_volume
vs1     vol1          true     /data1/vol1          RW_volume
vs1     vol2          true     /data1/vol2          RW_volume
vs1     data2         true     /data2               RW_volume
vs1     vol3          true     /data2/vol3          RW_volume
vs1     vol4          true     /data2/vol4          RW_volume
----
[NOTE]
====
管理用にパスと `/data2`パスに共有を作成することはできます `/data1`が、データの格納にこれらの共有を使用するようにアプリケーションサーバを設定しないでください。

====


== 計画ワークシート

|===
| 情報の種類 | 値 


 a| 
_ボリューム1：SMB共有名とパス_
 a| 



 a| 
_ボリューム2：SMB共有名とパス_
 a| 



 a| 
_ボリューム3：SMB共有名とパス_
 a| 



 a| 
_ボリューム4：SMB共有名とパス_
 a| 



 a| 
_ボリューム5：SMB共有名とパス_
 a| 



 a| 
_ボリューム6：SMB共有名とパス_
 a| 



 a| 
_ボリューム7：SMB共有名とパス_
 a| 



 a| 
追加ボリューム： SMB 共有名およびパス _
 a| 

|===