---
permalink: smb-hyper-v-sql/smb-share-config-worksheet-reference.html 
sidebar: sidebar 
keywords: complete, smb, share, configuration, worksheet, information, settings 
summary: このワークシートを使用して、SQL ServerおよびHyper-V over SMB構成用に継続的な可用性を実装したSMB共有を作成する際に必要となる値を記録してください。 
---
= SMB共有設定ワークシートへの記入
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
このワークシートを使用して、SQL ServerおよびHyper-V over SMB構成用に継続的な可用性を実装したSMB共有を作成する際に必要となる値を記録してください。



== SMB共有のプロパティおよび設定に関する情報

共有ごとに、次の情報を指定する必要があります。

* Storage Virtual Machine（SVM）名
+
SVM 名はすべての共有で同じです

* 共有名
* パス
* 共有プロパティ
+
次の2つの共有プロパティを設定する必要があります。

+
** `oplocks`
** `continuously-available`




次の共有プロパティは設定しないでください。

* `homedirectory attributecache`
* `branchcache`
* `access-based-enumeration`
+
** シンボリックリンクを無効にする必要があります（ `-symlink-properties`パラメータの値は null [""] にする必要があります）。






== 共有パスに関する情報

リモートVSSを使用してHyper-Vファイルをバックアップする場合は、Hyper-Vサーバから仮想マシン ファイルの格納場所へのSMB接続を確立する際に使用する共有パスの選択が重要になります。共有はネームスペース内の任意のポイントに作成できますが、Hyper-Vサーバで使用される共有のパスに結合されたボリュームを含めることはできません。ジャンクション ポイントを含む共有パスでシャドウ コピー処理を実行することはできません。

データベース ディレクトリ構造を作成する場合、SQL Serverはジャンクションを横断できません。ジャンクション ポイントを含むSQL Serverの共有パスは作成しないでください。

たとえば、示されている名前空間の場合、仮想マシン ファイルまたはデータベース ファイルをボリューム「`vol1`」、「`vol2`」、「`vol3`」、および「`vol4`」に保存するには、アプリケーション サーバーの共有を次のパスに作成する必要があります： `/data1/vol1`、 `/data1/vol2`、 `/data2/vol3`、および `/data2/vol4`。

[listing]
----

                     Junction                       Junction
Vserver Volume       Active   Junction Path         Path Source
------- ------------ -------- -------------------   -----------
vs1     data1         true     /data1               RW_volume
vs1     vol1          true     /data1/vol1          RW_volume
vs1     vol2          true     /data1/vol2          RW_volume
vs1     data2         true     /data2               RW_volume
vs1     vol3          true     /data2/vol3          RW_volume
vs1     vol4          true     /data2/vol4          RW_volume
----
[NOTE]
====
管理用に `/data1`および `/data2`パス上に共有を作成することはできますが、それらの共有を使用してデータを保存するようにアプリケーション サーバーを構成しないでください。

====


== 計画ワークシート

|===
| 情報の種類 | 値 


 a| 
_ボリューム1：SMB共有名とパス_
 a| 



 a| 
_ボリューム2：SMB共有名とパス_
 a| 



 a| 
_ボリューム3: SMB共有名とパス_
 a| 



 a| 
_ボリューム4：SMB共有名とパス_
 a| 



 a| 
_ボリューム5：SMB共有名とパス_
 a| 



 a| 
_ボリューム6：SMB共有名とパス_
 a| 



 a| 
_ボリューム7：SMB共有名とパス_
 a| 



 a| 
_追加ボリューム：SMB共有名とパス_
 a| 

|===