---
permalink: smb-hyper-v-sql/verify-domain-accounts-map-default-unix-user-task.html 
sidebar: sidebar 
keywords: verfiy, domain, account, default, unix, server, smb, share, user 
summary: Hyper-V と SQL Server では、SMB アクセスのためにドメイン コンピュータ アカウントを UNIX ユーザーにマッピングする必要があります。最も簡単な方法は、デフォルトの UNIX ユーザーにマッピングすることです。 
---
= ONTAPでドメインアカウントがデフォルトのUNIXユーザにマッピングされていることを確認する
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Hyper-V および SQL Server では、継続的可用性を備えた共有への SMB 接続を作成する際にドメインアカウントを使用します。接続を作成するには、コンピュータアカウントが UNIX ユーザに正しくマッピングされている必要があります。そのための最も便利な方法は、コンピュータアカウントをデフォルトの UNIX ユーザにマッピングすることです。

.タスクの内容
Hyper-V および SQL Server は、ドメインコンピュータアカウントを使用して SMB 接続を作成します。また、 SQL Server は、 SMB 接続を作成するサービスアカウントとしてドメインユーザアカウントを使用します。

ストレージ仮想マシン（SVM）を作成すると、ONTAPは自動的に次の名前のデフォルトユーザーを作成します。  `pcuser` （UIDは `65534` ）と名付けられたグループ `pcuser` （GIDは `65534` ）に追加し、デフォルトのユーザーを `pcuser`グループ。クラスタを Data ONTAP 8.2 にアップグレードする前に存在していた SVM 上で Hyper-V over SMB ソリューションを構成する場合、デフォルトのユーザーとグループが存在しない可能性があります。デフォルトの UNIX ユーザを設定していない場合は、 CIFS サーバのデフォルトの UNIX ユーザを設定する前に、デフォルトのユーザとグループを作成する必要があります。

.手順
. デフォルトの UNIX ユーザが存在するかどうかを確認します。
+
[source, cli]
----
vserver cifs options show -vserver <vserver_name>
----
. デフォルトユーザオプションが設定されていない場合は、デフォルトの UNIX ユーザとして指定できる UNIX ユーザが存在するかどうかを確認します。
+
[source, cli]
----
vserver services unix-user show -vserver <vserver_name>
----
. デフォルト ユーザー オプションが設定されておらず、デフォルト UNIX ユーザーとして指定できる UNIX ユーザーがいない場合は、デフォルト グループとデフォルト UNIX ユーザーを作成し、デフォルト ユーザーをグループに追加します。
+
、デフォルトのグループには通常グループに割り当てるGIDはである必要があり `65534`ます。

+
.. デフォルトグループを作成します。
+
[source, cli]
----
vserver services unix-group create -vserver <vserver_name> -name pcuser -id 65534
----
.. デフォルトユーザを作成し、デフォルトグループに追加します。
+
[source, cli]
----
vserver services unix-user create -vserver <vserver_name> -user pcuser -id 65534 -primary-gid 65534
----
.. デフォルトのユーザとデフォルトグループが正しく設定されていることを確認します。
+
[source, cli]
----
vserver services unix-user show -vserver <vserver_name>
----
+
[source, cli]
----
vserver services unix-group show -vserver <vserver_name> -members
----


. CIFS サーバのデフォルトのユーザが設定されていない場合は、次の手順を実行します。
+
.. デフォルトユーザを設定します。
+
[source, cli]
----
vserver cifs options modify -vserver <vserver_name> -default-unix-user pcuser
----
.. デフォルトの UNIX ユーザが正しく設定されていることを確認します。
+
[source, cli]
----
vserver cifs options show -vserver <vserver_name>
----


. アプリケーションサーバのコンピュータアカウントがデフォルトのユーザに正しくマッピングされていることを確認するには、SVMの共有にドライブをマッピングし、コマンドを使用してWindowsユーザとUNIXユーザのマッピングを確認します `vserver cifs session show`。
+
の詳細については `vserver cifs options`、をlink:https://docs.netapp.com/us-en/ontap-cli/search.html?q=vserver+cifs+options["ONTAPコマンド リファレンス"^]参照してください。



.例
が存在します。 `pcuser`ユーザーは、SVM vs1 上の CIFS サーバのデフォルト ユーザーとして割り当てられます。

[listing]
----
cluster1::> vserver cifs options show

Vserver: vs1

  Client Session Timeout : 900
  Default Unix Group     : -
  Default Unix User      : -
  Guest Unix User        : -
  Read Grants Exec       : disabled
  Read Only Delete       : disabled
  WINS Servers           : -



cluster1::> vserver services unix-user show
          User            User   Group  Full
Vserver   Name            ID     ID     Name
--------- --------------- ------ ------ ----------------
vs1       nobody          65535  65535  -
vs1       pcuser          65534  65534  -
vs1       root            0      1      -

cluster1::> vserver services unix-group show -members
Vserver        Name                ID
vs1            daemon              1
       Users: -
vs1            nobody              65535
       Users: -
vs1            pcuser              65534
       Users: -
vs1            root                0
       Users: -

cluster1::> vserver cifs options modify -vserver vs1 -default-unix-user pcuser

cluster1::> vserver cifs options show

Vserver: vs1

  Client Session Timeout : 900
  Default Unix Group     : -
  Default Unix User      : pcuser
  Guest Unix User        : -
  Read Grants Exec       : disabled
  Read Only Delete       : disabled
  WINS Servers           : -
----