---
permalink: smb-hyper-v-sql/verify-smb-server-options-task.html 
sidebar: sidebar 
keywords: verify, cifs, server, option, configured, hyper, v, sql, server, smb 
summary: Hyper-V および SQL Server over SMB のノンストップオペレーションを実行する場合、必要な CIFS サーバオプションが有効になっており、要件に従って適切に設定されていることを確認する必要があります。 
---
= 必要な CIFS サーバオプションが設定されていることを確認する
:icons: font
:imagesdir: ../media/


[role="lead"]
Hyper-V および SQL Server over SMB のノンストップオペレーションを実行する場合、必要な CIFS サーバオプションが有効になっており、要件に従って適切に設定されていることを確認する必要があります。

.このタスクについて
* SMB 2.x と SMB 3.0 が有効になっている必要があります。
* パフォーマンスが向上したコピーオフロードを使用するには、 ODX コピーオフロードが有効になっている必要があります。
* Hyper-V over SMB 解決策でリモート VSS に対応したバックアップサービスを使用する場合は、 VSS シャドウコピーサービスが有効になっている必要があります（ Hyper-V のみ）。


.手順
. Storage Virtual Machine （ SVM ）で必要な CIFS サーバオプションが有効になっていることを確認します。
+
.. 権限レベルを advanced に設定します。
+
「 * set -privilege advanced * 」のように指定します

.. 次のコマンドを入力します。
+
「 * vserver cifs options show -vserver vserver_name _ * 」のように指定します

+
次のオプションは 'true' に設定する必要があります

+
*** 「 -smb2-enabled 」と入力します
*** 「 -smb3-enabled 」と表示されます
*** 「 -copy-offer-enabled 」です
*** `-shadowcopy-enabled` (Hyper-V のみ )




. いずれかのオプションが「 true 」に設定されていない場合は、次の手順を実行します。
+
.. vserver cifs options modify コマンドを使用して、これらのパラメータを「 true 」に設定します。
.. vserver cifs options show コマンドを使用して、オプションが「 true 」に設定されていることを確認します。


. admin 権限レベルに戻ります。
+
'*set -privilege admin*



次に、 SVM vs1 について、 Hyper-V over SMB 構成の必要なオプションが有効になっていることを確認するコマンドの例を示します。この例の要件では、 ODX コピーオフロードのオプションを有効にする必要があります。

[listing]
----
cluster1::> set -privilege advanced
Warning: These advanced commands are potentially dangerous; use them
only when directed to do so by technical support personnel.
Do you wish to continue? (y or n): y

cluster1::*> vserver cifs options show -vserver vs1 -fields smb2-enabled,smb3-enabled,copy-offload-enabled,shadowcopy-enabled
vserver smb2-enabled smb3-enabled copy-offload-enabled shadowcopy-enabled
------- ------------ ------------ -------------------- ------------------
vs1     true         true         false                true

cluster-1::*> vserver cifs options modify -vserver vs1 -copy-offload-enabled true

cluster-1::*> vserver cifs options show -vserver vs1 -fields copy-offload-enabled
vserver  copy-offload-enabled
-------- --------------------
vs1      true

cluster1::*> set -privilege admin
----