---
permalink: smb-hyper-v-sql/verify-security-style-svm-root-volume-ntfs-task.html 
sidebar: sidebar 
keywords: verify, security, style, svm, root, volume, ntfs, storage, virtual, machine 
summary: Hyper-VおよびSQL Server over SMBのノンストップオペレーションを確実に成功させるには、ボリュームをNTFSセキュリティ形式で作成する必要があります。Storage Virtual Machine（SVM）上に作成されたボリュームにはルートボリュームのセキュリティ形式がデフォルトで適用されるため、ルートボリュームのセキュリティ形式はNTFSに設定する必要があります。 
---
= SVMルート ボリュームのセキュリティ形式がNTFSに設定されていることの確認
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Hyper-VおよびSQL Server over SMBのノンストップオペレーションを確実に成功させるには、ボリュームをNTFSセキュリティ形式で作成する必要があります。Storage Virtual Machine（SVM）上に作成されたボリュームにはルートボリュームのセキュリティ形式がデフォルトで適用されるため、ルートボリュームのセキュリティ形式はNTFSに設定する必要があります。

.タスク概要
* SVM を作成するときに、ルート ボリュームのセキュリティ スタイルを指定できます。
* SVM がルート ボリュームを NTFS セキュリティ スタイルに設定して作成されていない場合は、後で `volume modify`コマンドを使用してセキュリティ スタイルを変更できます。


.手順
. SVM ルート ボリュームの現在のセキュリティ スタイルを確認します：
+
`*volume show -vserver _vserver_name_ -fields vserver,volume,security-style*`

. ルート ボリュームが NTFS セキュリティ形式のボリュームでない場合は、セキュリティ形式を NTFS に変更します：
+
`*volume modify -vserver _vserver_name_ -volume root_volume_name -security-style ntfs*`

. SVM ルート ボリュームが NTFS セキュリティ スタイルに設定されていることを確認します：
+
`*volume show -vserver _vserver_name_ -fields vserver,volume,security-style*`



.例
次のコマンドは、SVM vs1のルート ボリュームのセキュリティ形式がNTFSになっていることを確認します。

[listing]
----
cluster1::> volume show -vserver vs1 -fields vserver,volume,security-style
vserver  volume     security-style
-------- ---------- --------------
vs1      vs1_root   unix

cluster1::> volume modify -vserver vs1 -volume vs1_root -security-style ntfs

cluster1::> volume show -vserver vs1 -fields vserver,volume,security-style
vserver  volume     security-style
-------- ---------- --------------
vs1      vs1_root   ntfs
----