---
permalink: smb-hyper-v-sql/verify-lif-status-task.html 
sidebar: sidebar 
keywords: verify, lif, status, storage, virtual, machine, hyper, v, sql, server, smb, configuration, cluster 
summary: Hyper-V および SQL Server over SMB 構成でストレージ仮想マシン（SVM）を構成し、クラスタ内の各ノードに LIF を配置した場合でも、日常的な運用中に一部の LIF が別のノードのポートに移動することがあります。LIF のステータスを確認し、必要な修正措置を講じる必要があります。 
---
= LIFステータスの確認
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Hyper-V および SQL Server over SMB 構成でストレージ仮想マシン（SVM）を構成し、クラスタ内の各ノードに LIF を配置した場合でも、日常的な運用中に一部の LIF が別のノードのポートに移動することがあります。LIF のステータスを確認し、必要な修正措置を講じる必要があります。

.タスク概要
シームレスで無停止の運用をサポートするには、クラスタ内の各ノードにSVM用のLIFが少なくとも1つあり、すべてのLIFがホームポートに関連付けられている必要があります。設定済みのLIFの一部が現在ホームポートに関連付けられていない場合は、ポートの問題を修正してから、LIFをホームポートに戻す必要があります。

.手順
. SVM に設定されている LIF に関する情報を表示します：
+
`*network interface show -vserver _vserver_name_*`

+
この例では、「`lif1`」はホーム ポート上にありません。

+
`network interface show -vserver vs1`

+
[listing]
----

            Logical    Status     Network          Current    Current Is
Vserver     Interface  Admin/Oper Address/Mask     Node       Port    Home
----------- ---------- ---------- ---------------- ---------- ------- ----
vs1
            lif1         up/up    10.0.0.128/24    node2      e0d     false
            lif2         up/up    10.0.0.129/24    node2      e0d     true
----
+
 `network interface show`の詳細については、link:https://docs.netapp.com/us-en/ontap-cli/network-interface-show.html["ONTAPコマンド リファレンス"^]を参照してください。

. 一部の LIF がホーム ポート上にない場合は、次の手順を実行します：
+
.. 各 LIF について、LIF のホーム ポートを特定します：
+
`*network interface show -vserver _vserver_name_ -lif _lif_name_ -fields home-node,home-port*`

+
`*network interface show -vserver vs1 -lif lif1 -fields home-node,home-port*`

+
[listing]
----

vserver lif  home-node  home-port
------- ---- ---------- ---------
vs1     lif1 node1      e0d
----
.. 各 LIF について、LIF のホーム ポートが稼働しているかどうかを確認します：
+
`*network port show -node _node_name_ -port _port_ -fields port,link*`

+
`network port show -node node1 -port e0d -fields port,link`

+
[listing]
----

node       port link
---------- ---- ----
node1      e0d  up
----
+
この例では、「`lif1`」をホーム ポート `node1:e0d`に移行し直す必要があります。

+
 `network port show`の詳細については、link:https://docs.netapp.com/us-en/ontap-cli/network-port-show.html["ONTAPコマンド リファレンス"^]を参照してください。



. LIF が関連付けられているホームポートのネットワークインターフェイスのいずれかが `up`状態になっていない場合は、これらのインターフェイスが稼働状態になるように問題を解決してください。 `up`の詳細については、link:https://docs.netapp.com/us-en/ontap-cli/up.html["ONTAPコマンド リファレンス"^]を参照してください。
. 必要に応じて、LIF をホーム ポートに戻します：
+
`*network interface revert -vserver _vserver_name_ -lif _lif_name_*`

+
`*network interface revert -vserver vs1 -lif lif1*`

+
 `network interface revert`の詳細については、link:https://docs.netapp.com/us-en/ontap-cli/network-interface-revert.html["ONTAPコマンド リファレンス"^]を参照してください。

. クラスタ内の各ノードに SVM のアクティブな LIF があることを確認します：
+
`*network interface show -vserver _vserver_name_*`

+
`*network interface show -vserver vs1*`

+
[listing]
----

            Logical    Status     Network          Current    Current Is
Vserver     Interface  Admin/Oper Address/Mask     Node       Port    Home
----------- ---------- ---------- ---------------- ---------- ------- ----
vs1
            lif1         up/up    10.0.0.128/24    node1      e0d     true
            lif2         up/up    10.0.0.129/24    node2      e0d     true
----

