---
sidebar: sidebar 
permalink: file-system-analytics/considerations-concept.html 
keywords: file system analytics, performance, SVM 
summary: File System Analyticsは、アクティブなNASデータを含むボリュームの可視性を提供するために設計されています。使用には制限と制限事項があります。 
---
= ONTAP ファイル システム分析に関する考慮事項
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
ファイルシステム分析の実装に伴う使用制限とパフォーマンスへの潜在的な影響を理解しておく必要があります。



== SVMの保護関係

ファイルシステム分析を有効にしたボリュームが格納されているSVMで保護関係が確立されている場合、デスティネーションSVMには分析データはレプリケートされません。リカバリ処理でソースSVMを再同期した場合は、リカバリ後に必要なボリュームについて分析を手動で再度有効にする必要があります。



== パフォーマンスに関する考慮事項

ファイルシステム分析を有効にすると、メタデータの初回収集時のパフォーマンスが低下することがあります。多くの場合、この状況は利用率が最大になっているシステムで発生します。このようなシステムでは、代わりにONTAP System Managerのパフォーマンス監視ツールを使用できます。

遅延が顕著に増加した場合は、link:https://kb.netapp.com/Advice_and_Troubleshooting/Data_Storage_Software/ONTAP_OS/High_or_fluctuating_latency_after_turning_on_NetApp_ONTAP_File_System_Analytics["NetApp ナレッジベース：NetApp ONTAP File System Analytics をオンにした後のレイテンシの上昇または変動"^]を参照してください。



== スキャンに関する考慮事項

容量分析を有効にすると、ONTAPは容量分析の初期化スキャンを実行します。このスキャンでは、容量分析が有効になっているボリューム内のすべてのファイルのメタデータにアクセスします。スキャン中はファイルデータは読み込まれません。ONTAP 9.14.1以降では、REST API、System Managerの**Explorer**タブ、または `volume analytics show`CLIコマンドを使用して、スキャンの進行状況を追跡できます。スロットリングイベントが発生した場合、ONTAPは通知を提供します。

ボリュームに対してファイルシステム分析を有効にする場合は、ボリュームの使用可能なスペースの少なくとも5～8%が空きスペースであることを確認してください。ボリュームでオートサイズが有効になっている場合は、自動拡張時の最大サイズに基づいて使用可能なサイズを計算します。ONTAP 9.15.1以降では、ボリュームに対してファイルシステム分析を有効にしている場合に、使用可能なスペースが不足すると、ONTAPにエラー メッセージが表示されます。

スキャンの完了後、ファイルシステムに変更があるたびにファイルシステム分析はリアルタイムで更新されます。

スキャンの所要時間は、ボリューム上のディレクトリとファイルの数に比例して長くなります。このスキャンではメタデータが収集されるため、ファイル サイズがスキャン時間に影響することはありません。

初期化スキャンの詳細については、link:https://www.netapp.com/pdf.html?item=/media/20707-tr-4867.pdf["TR-4867：File System Analyticsのベスト プラクティス ガイドライン"^]を参照してください。



=== ベストプラクティス

アグリゲートを共有しないボリュームでスキャンを開始する必要があります。現在どのアグリゲートがどのボリュームをホストしているかを確認するには、次のコマンドを使用します。

`volume show -volume _comma-separated-list_of_volumes_ -fields aggr-list`

スキャン中もボリュームはクライアント トラフィックを処理します。クライアント トラフィックが少ない時間帯にスキャンを開始することを推奨します。

クライアント トラフィックが増加すると、システム リソースが消費され、スキャンにかかる時間が長くなります。

ONTAP 9.12.1 以降では、System Manager および ONTAP CLI を使用してデータ収集を一時停止できます。

* ONTAP CLIを使用する場合の処理：
+
** 次のコマンドでデータ収集を一時停止できます： `volume analytics initialization pause -vserver _svm_name_ -volume _volume_name_`
** クライアント トラフィックが低下したら、次のコマンドでデータ収集を再開できます： `volume analytics initialization resume -vserver _svm_name_ -volume _volume_name_`


* System Managerを使用している場合は、ボリューム メニューの*Explorer*ビューで、*Pause Data Collection*ボタンと*Resume Data Collection*ボタンを使用してスキャンを管理します。

