---
permalink: antivirus/apply-scanner-policies-disaster-recovery-mcc-task.html 
sidebar: sidebar 
keywords: apply, scanner policies, metrocluster, configurations 
summary: スキャナ ポリシーは、スキャナ プールがアクティブかどうかを定義します。MetroCluster構成では、各クラスタのプライマリとセカンダリのスキャナ プールにスキャナ ポリシーを適用する必要があります。 
---
= MetroCluster ONTAP Vscan構成でスキャナポリシーを適用する
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
スキャナ ポリシーは、スキャナ プールがアクティブかどうかを定義します。MetroCluster構成では、各クラスタのプライマリとセカンダリのスキャナ プールにスキャナ ポリシーを適用する必要があります。

.タスク概要
* 1つのスキャナ プールには1つのスキャナ ポリシーのみを適用できます。
* クラスタ内のすべてのSVM用のスキャナ プールを作成した場合は、各SVMにスキャナ ポリシーを個別に適用する必要があります。
* ディザスタ リカバリ構成およびMetroCluster構成では、ローカル クラスタとリモート クラスタのすべてのスキャナ プールにスキャナ ポリシーを適用する必要があります。
* ローカルクラスタ用に作成するポリシーでは、 `cluster`パラメータにローカルクラスタを指定する必要があります。リモートクラスタ用に作成するポリシーでは、 `cluster`パラメータにリモートクラスタを指定する必要があります。これにより、災害発生時にリモートクラスタがウイルススキャン処理を引き継ぐことができます。


.手順
. スキャナ ポリシーを適用します。
+
`vserver vscan scanner-pool apply-policy -vserver _data_SVM_ -scanner-pool _scanner_pool_ -scanner-policy primary|secondary|idle -cluster _cluster_to_apply_policy_on_`

+
 `vserver vscan scanner-pool apply-policy`の詳細については、link:https://docs.netapp.com/us-en/ontap-cli/vserver-vscan-scanner-pool-apply-policy.html["ONTAPコマンド リファレンス"^]を参照してください。

+
スキャナ ポリシーには次のいずれかの値が設定されます。

+
** `Primary`スキャナープールがアクティブであることを指定します。
** `Secondary`プライマリスキャナプール内のVscanサーバーがいずれも接続されていない場合にのみ、スキャナプールがアクティブになるように指定します。
** `Idle`スキャナープールが非アクティブであることを指定します。
+
[NOTE]
====
スキャナ ポリシーの適用は、すべてプライマリSVMを含むクラスタから実行する必要があります。

====
+
次のコマンドは、MetroCluster構成の各クラスタのプライマリとセカンダリのスキャナ プールにスキャナ ポリシーを適用します。

+
[listing]
----
cluster1::>vserver vscan scanner-pool apply-policy -vserver cifssvm1
-scanner-pool pool1_for_site1 -scanner-policy primary -cluster cluster1

cluster1::>vserver vscan scanner-pool apply-policy -vserver cifssvm1
-scanner-pool pool2_for_site1 -scanner-policy secondary -cluster cluster1

cluster1::>vserver vscan scanner-pool apply-policy -vserver cifssvm1
-scanner-pool pool2_for_site2 -scanner-policy primary -cluster cluster2

cluster1::>vserver vscan scanner-pool apply-policy -vserver cifssvm1
-scanner-pool pool1_for_site2 -scanner-policy secondary -cluster cluster2
----


. スキャナ プールがアクティブなことを確認します。
+
`vserver vscan scanner-pool show -vserver data_SVM|cluster_admin_SVM -scanner-pool scanner_pool`

+
 `vserver vscan scanner-pool show`の詳細については、link:https://docs.netapp.com/us-en/ontap-cli/vserver-vscan-scanner-pool-show.html["ONTAPコマンド リファレンス"^]を参照してください。

+
次のコマンドは、スキャナプール `pool1`の詳細を表示します：

+
[listing]
----
cluster1::> vserver vscan scanner-pool show -vserver cifssvm1 -scanner-pool pool1_for_site1

                                    Vserver: cifssvm1
                               Scanner Pool: pool1_for_site1
                             Applied Policy: primary
                             Current Status: on
         Cluster on Which Policy Is Applied: cluster1
                  Scanner Pool Config Owner: vserver
       List of IPs of Allowed Vscan Servers:
List of Host Names of Allowed Vscan Servers: scan1
                   List of Privileged Users: cifs\u1,cifs\u2
----
+
 `vserver vscan scanner-pool show-active`コマンドを使用して、SVM上のアクティブなスキャナプールを表示できます。link:https://docs.netapp.com/us-en/ontap-cli/vserver-vscan-scanner-pool-show-active.html["ONTAPコマンド リファレンス"^]の `vserver vscan scanner-pool show-active`の詳細をご覧ください。


