---
permalink: antivirus/architecture-concept.html 
sidebar: sidebar 
keywords: antivirus, architecture 
summary: ネットアップのウィルス対策アーキテクチャは、 Vscan サーバと一連の ONTAP 設定項目で構成されます。 
---
= ウィルス対策アーキテクチャ
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
ネットアップのウィルス対策アーキテクチャは、 Vscan サーバと一連の ONTAP 設定項目で構成されます。



== Vscan サーバ

次のコンポーネントを Vscan サーバにインストールする必要があります。

* * ONTAP Antivirus Connector *
+
ネットアップが提供する ONTAP Antivirus Connector は、 ONTAP と Vscan サーバ間の通信を処理します。

* * アンチウイルスソフトウェア *
+
ONTAP 対応のサードパーティ製ウィルス対策ソフトウェアは、ファイルにウィルスなどの悪意のあるプログラムがないかをスキャンします。ソフトウェアを設定する際に、感染したファイルに対して実行する処理を指定します。





== ONTAP の設定項目

ネットアップストレージシステムで次の項目を設定する必要があります。

* * スキャナプール *
+
スキャナプールは、 SVM に接続できる Vscan サーバと特権ユーザを定義します。また、スキャン要求のタイムアウト時間も定義します。この時間が経過すると、代わりの Vscan サーバがある場合はそのサーバにスキャン要求が送信されます。

+
[NOTE]
====
Vscan サーバのウィルス対策ソフトウェアのタイムアウト時間は、スキャナプールの要求タイムアウト時間よりも 5 秒ほど短く設定することを推奨します。 ソフトウェアのタイムアウト時間がスキャン要求のタイムアウト時間よりも長いため、ファイルアクセスが遅延または完全に拒否される状況を回避する。

====
* * 特権ユーザ *
+
特権ユーザは、 Vscan サーバが SVM への接続に使用するドメインユーザアカウントです。スキャナプールに定義されている特権ユーザのリストに含まれている必要があります。

* * スキャナポリシー *
+
スキャナポリシーは、スキャナプールがアクティブかどうかを決定します。スキャナポリシーには次のいずれかの値が設定されます。

+
** `Primary` スキャナプールをアクティブにします。
** `Secondary` プライマリスキャナプールのVscanサーバが1つも接続されていない場合にのみスキャナプールをアクティブにします。
** `Idle` スキャナプールを非アクティブにします。スキャナポリシーはシステムで定義されます。カスタムのスキャナポリシーを作成することはできません。


* * オンアクセスポリシー *
+
オンアクセスポリシーはオンアクセススキャンの範囲を定義します。スキャンするファイルの最大サイズ、スキャン対象に含めるファイルの拡張子、およびスキャン対象から除外するファイルの拡張子とパスを指定できます。

+
デフォルトでは、読み取り / 書き込みボリュームのみがスキャンされます。読み取り専用ボリュームのスキャンを有効にするフィルタや、実行アクセス権で開かれたファイルのみにスキャンを制限するフィルタを指定することができます。

+
** `scan-ro-volume` 読み取り専用ボリュームのスキャンを有効にします。
** `scan-execute-access` 実行アクセス権で開かれたファイルにスキャンを制限します。
+
[NOTE]
====
「 Execute access 」は「 execute permission 」と同じではありません。 指定されたクライアントには ' 実行アクセス権が付与されますが ' 実行目的でファイルを開いた場合にのみ ' 実行アクセス権が付与されます

====


+
を設定できます `scan-mandatory` オフにすると、ウィルススキャンに使用できるVscanサーバがない場合にファイルアクセスが許可されます。

* * オンデマンドタスク *
+
オンデマンドタスクは、オンデマンドスキャンの範囲を定義します。スキャンするファイルの最大サイズ、スキャン対象に含めるファイルの拡張子とパス、およびスキャン対象から除外するファイルの拡張子とパスを指定できます。デフォルトでは、サブディレクトリ内のファイルがスキャンされます。

+
cron スケジュールを使用していつタスクを実行するかを指定できます。を使用できます `vserver vscan on-demand-task run` タスクをすぐに実行するコマンド。

* * Vscan ファイル処理プロファイル（オンアクセススキャンのみ） *
+
。 `-vscan-fileop-profile` のパラメータ `vserver cifs share create` コマンドは、ウィルススキャンをトリガーするSMB共有での処理を定義します。デフォルトでは、パラメータはに設定されています `standard`をクリックします。これはネットアップのベストプラクティスです。

+
このパラメータは、 SMB 共有を作成または変更するときに必要に応じて調整できます。

+
** `no-scan` 共有に対してウィルススキャンを一切トリガーしません。
** `standard` 開く、閉じる、および名前変更の各処理でウィルススキャンをトリガーします。
** `strict` 開く、読み取る、閉じる、名前変更の各処理でウィルススキャンをトリガーします。
+
。 `strict` プロファイルを使用すると、複数のクライアントが同時に1つのファイルにアクセスする状況でセキュリティが強化されます。あるクライアントがウィルスを書き込んだあとにファイルを閉じたときに、別のクライアントで同じファイルが開いたままになっている場合は、 `strict` 2番目のクライアントでの読み取り処理で、ファイルが閉じる前にスキャンがトリガーされるようにします。

+
の制限に注意する必要があります `strict` 同時にアクセスされる可能性があるファイルを含む共有にプロファイルを設定します。プロファイルは他のプロファイルよりも多くのスキャン要求を生成するため、パフォーマンスの低下を招く可能性があります。

** `writes-only` 変更されたファイルが閉じられたときにのみウィルススキャンをトリガーします。
+
[NOTE]
====
クライアントアプリケーションが名前変更操作を実行すると、ファイルは新しい名前で閉じられ、スキャンされません。このような処理がセキュリティ上の問題になる場合は、を使用してください `standard` または `strict` プロファイル（Profile）：

====
+
理由 `writes-only` 生成されるスキャン要求は、他のプロファイルよりも少なくなります（を除く） `no-scan`通常はパフォーマンスが向上します。

+
ただし、このプロファイルを共有に使用する場合は、修復不可能な感染ファイルを削除または隔離するようにスキャナを設定し、以降クライアントがアクセスできないようにする必要があります。たとえば、あるクライアントがウィルスを書き込んだあとにファイルを閉じ、そのファイルが修復、削除、または隔離されていない場合、 file_deleton_writing にアクセスするクライアントはすべて感染します。




