---
permalink: antivirus/commands-manage-on-access-policies-reference.html 
sidebar: sidebar 
keywords: commands, manage, on-access, policies 
summary: オンアクセス ポリシーを変更、無効化、削除できます。また、ポリシーの概要と詳細を表示できます。 
---
= オンアクセス ポリシーを管理するための ONTAP Vscan コマンド
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
オンアクセス ポリシーを変更、無効化、削除できます。また、ポリシーの概要と詳細を表示できます。

|===


| 状況 | 入力するコマンド 


 a| 
オンアクセス ポリシーの作成
 a| 
`vserver vscan on-access-policy create`



 a| 
オンアクセス ポリシーを変更する
 a| 
`vserver vscan on-access-policy modify`



 a| 
オンアクセス ポリシーの有効化
 a| 
`vserver vscan on-access-policy enable`



 a| 
オンアクセス ポリシーを無効にする
 a| 
`vserver vscan on-access-policy disable`



 a| 
オンアクセス ポリシーを削除する
 a| 
`vserver vscan on-access-policy delete`



 a| 
オンアクセス ポリシーの概要と詳細を表示する
 a| 
`vserver vscan on-access-policy show`



 a| 
対象から除外するパスをリストに追加する
 a| 
`vserver vscan on-access-policy paths-to-exclude add`



 a| 
対象から除外するパスをリストから削除する
 a| 
`vserver vscan on-access-policy paths-to-exclude remove`



 a| 
対象から除外するパスのリストを表示する
 a| 
`vserver vscan on-access-policy paths-to-exclude show`



 a| 
対象から除外するファイル拡張子をリストに追加する
 a| 
`vserver vscan on-access-policy file-ext-to-exclude add`



 a| 
対象から除外するファイル拡張子をリストから削除する
 a| 
`vserver vscan on-access-policy file-ext-to-exclude remove`



 a| 
対象から除外するファイル拡張子のリストを表示する
 a| 
`vserver vscan on-access-policy file-ext-to-exclude show`



 a| 
対象に含めるファイル拡張子をリストに追加する
 a| 
`vserver vscan on-access-policy file-ext-to-include add`



 a| 
対象に含めるファイル拡張子をリストから削除する
 a| 
`vserver vscan on-access-policy file-ext-to-include remove`



 a| 
対象に含めるファイル拡張子のリストを表示する
 a| 
`vserver vscan on-access-policy file-ext-to-include show`

|===
この手順で説明されているコマンドの詳細については、link:https://docs.netapp.com/us-en/ontap-cli/["ONTAPコマンド リファレンス"^]を参照してください。
