---
permalink: antivirus/commands-manage-scanner-pools-reference.html 
sidebar: sidebar 
keywords: commands, manage, scanner pools 
summary: スキャナプールを変更および削除したり、スキャナプールの特権ユーザやVscanサーバを管理したりできます。また、スキャナプールに関する概要情報を確認することもできます。 
---
= Vscan でスキャナ プールを管理するための ONTAP コマンド
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
スキャナプールを変更および削除したり、スキャナプールの特権ユーザやVscanサーバを管理したりできます。また、スキャナプールに関する概要情報を確認することもできます。

|===


| 状況 | 入力するコマンド 


 a| 
スキャナプールを変更する
 a| 
`vserver vscan scanner-pool modify`



 a| 
スキャナプールを削除する
 a| 
`vserver vscan scanner-pool delete`



 a| 
スキャナプールに特権ユーザを追加する
 a| 
`vserver vscan scanner-pool privileged-users add`



 a| 
スキャナプールから特権ユーザを削除する
 a| 
`vserver vscan scanner-pool privileged-users remove`



 a| 
スキャナプールにVscanサーバを追加する
 a| 
`vserver vscan scanner-pool servers add`



 a| 
スキャナプールからVscanサーバを削除する
 a| 
`vserver vscan scanner-pool servers remove`



 a| 
スキャナプールの概要と詳細を表示する
 a| 
`vserver vscan scanner-pool show`



 a| 
スキャナプールの特権ユーザを表示する
 a| 
`vserver vscan scanner-pool privileged-users show`



 a| 
すべてのスキャナプールのVscanサーバを表示する
 a| 
`vserver vscan scanner-pool servers show`

|===
この手順で説明されているコマンドの詳細については、をlink:https://docs.netapp.com/us-en/ontap-cli/["ONTAPコマンド リファレンス"^]参照してください。
