---
permalink: antivirus/create-on-demand-task-task.html 
sidebar: sidebar 
keywords: create, on-demand, task 
summary: オンデマンドタスクは、オンデマンドスキャンの範囲を定義します。スキャンするファイルの最大サイズ、スキャン対象に含めるファイルの拡張子とパス、およびスキャン対象から除外するファイルの拡張子とパスを指定できます。デフォルトでは、サブディレクトリ内のファイルがスキャンされます。 
---
= オンデマンドタスクを作成する
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
オンデマンドタスクは、オンデマンドスキャンの範囲を定義します。スキャンするファイルの最大サイズ、スキャン対象に含めるファイルの拡張子とパス、およびスキャン対象から除外するファイルの拡張子とパスを指定できます。デフォルトでは、サブディレクトリ内のファイルがスキャンされます。

.手順
. オンデマンドタスクを作成します。
+
`vserver vscan on-demand-task create -vserver data_SVM -task-name task_name -scan-paths paths_of_files_to_scan -report-directory report_directory_path -report-expiry-time expiration_time_for_report -schedule cron_schedule -max-file-size max_size_of_files_to_scan -paths-to-exclude paths_of_files_to_exclude -file-ext-to-exclude extensions_of_files_to_exclude -file-ext-to-include extensions_of_files_to_include -scan-files-with-no-ext true|false -directory-recursion true|false`

+
** 。 `-file-ext-to-exclude` 設定は、より優先されます `-file-ext-to-include` 設定：
** 設定 `-scan-files-with-no-ext` をtrueに設定すると、拡張子がないファイルがスキャンされますすべてのオプションの一覧については、コマンドのマニュアルページを参照してください。


+
次のコマンドは、という名前のオンアクセスタスクを作成します `Task1` をクリックします ``vs1``SVM：

+
[listing]
----
cluster1::> vserver vscan on-demand-task create -vserver vs1 -task-name Task1 -scan-paths "/vol1/","/vol2/cifs/" -report-directory "/report" -schedule daily -max-file-size 5GB -paths-to-exclude "/vol1/cold-files/" -file-ext-to-include "vmdk?","mp*" -file-ext-to-exclude "mp3","mp4" -scan-files-with-no-ext false
[Job 126]: Vscan On-Demand job is queued. Use the "job show -id 126" command to view the status.
----
+
[NOTE]
====
を使用できます `job show` ジョブのステータスを表示するためのコマンドです。を使用できます `job pause` および `job resume` ジョブを一時停止および再開するコマンド、またはを指定します `job stop` ジョブを終了するためのコマンドです。

====
. オンデマンドタスクが作成されたことを確認します。 `vserver vscan on-demand-task show -instance data_SVM -task-name task_name`
+
すべてのオプションの一覧については、コマンドのマニュアルページを参照してください。

+
次のコマンドでは、の詳細が表示されます `Task1` タスク：

+
[listing]
----
cluster1::> vserver vscan on-demand-task show -instance vs1 -task-name Task1

                           Vserver: vs1
                         Task Name: Task1
                List of Scan Paths: /vol1/, /vol2/cifs/
             Report Directory Path: /report
                      Job Schedule: daily
Max File Size Allowed for Scanning: 5GB
            File Paths Not to Scan: /vol1/cold-files/
       File Extensions Not to Scan: mp3, mp4
           File Extensions to Scan: vmdk?, mp*
      Scan Files with No Extension: false
           Request Service Timeout: 5m
                    Cross Junction: true
               Directory Recursion: true
                     Scan Priority: low
                  Report Log Level: info
        Expiration Time for Report: -
----


.完了後
タスクの実行をスケジュールする前に、 SVM でスキャンを有効にする必要があります。
