---
permalink: antivirus/create-on-access-policy-task.html 
sidebar: sidebar 
keywords: create, on-access, policy 
summary: オンアクセスポリシーはオンアクセススキャンの範囲を定義します。スキャンするファイルの最大サイズ、スキャン対象に含めるファイルの拡張子、およびスキャン対象から除外するファイルの拡張子とパスを指定できます。オンアクセスポリシーは、個々の SVM 用またはクラスタ内のすべての SVM 用に作成できます。 
---
= オンアクセスポリシーを作成します
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
オンアクセスポリシーはオンアクセススキャンの範囲を定義します。スキャンするファイルの最大サイズ、スキャン対象に含めるファイルの拡張子、およびスキャン対象から除外するファイルの拡張子とパスを指定できます。オンアクセスポリシーは、個々の SVM 用またはクラスタ内のすべての SVM 用に作成できます。

.このタスクについて
デフォルトでは、 ONTAP は「デフォルト CIFS 」という名前のオンアクセスポリシーを作成し、クラスタ内のすべての SVM に対して有効にします。

を設定できます `scan-mandatory` オフにすると、ウィルススキャンに使用できるVscanサーバがない場合にファイルアクセスが許可されます。に基づいてスキャン除外の対象となるすべてのファイルがあることに注意してください `paths-to-exclude`、 `file-ext-to-exclude`または `max-file-size` パラメータは、であってもスキャン対象として考慮されません `scan-mandatory` オプションがonに設定されている。

[NOTE]
====
を参照してください `scan-mandatory` オプションを参照してください xref:vscan-server-connection-concept.adoc[scan-mandatory オプションの使用時に発生する可能性がある接続の問題]。

====
デフォルトでは、読み取り / 書き込みボリュームのみがスキャンされます。読み取り専用ボリュームのスキャンを有効にするフィルタや、実行アクセス権で開かれたファイルのみにスキャンを制限するフィルタを指定することができます。

.手順
. オンアクセスポリシーを作成します。
+
`vserver vscan on-access-policy create -vserver _data_SVM|cluster_admin_SVM_ -policy-name _policy_name_ -protocol CIFS -max-file-size _max_size_of_files_to_scan_ –filters [scan-ro-volume,][scan-execute-access] -file-ext-to-include _extensions_of_files_to_include_ -file-ext-to-exclude _extensions_of_files_to_exclude_ -scan-files-with-no-ext true|false -paths-to-exclude _paths_of_files_to_exclude_ -scan-mandatory on|off`

+
** 個々の SVM 用のポリシーの場合はデータ SVM 、クラスタ内のすべての SVM 用のポリシーの場合はクラスタ管理 SVM を指定します。
** 。 `-file-ext-to-exclude` を設定すると、が上書きされます `-file-ext-to-include` 設定：
** 設定 `-scan-files-with-no-ext` trueに設定すると、拡張子のないファイルがスキャンされます。次のコマンドは、という名前のオンアクセスポリシーを作成します `Policy1` をクリックします ``vs1``SVM：


+
[listing]
----
cluster1::> vserver vscan on-access-policy create -vserver vs1 -policy-name Policy1 -protocol CIFS -filters scan-ro-volume -max-file-size 3GB -file-ext-to-include “mp*”,"tx*" -file-ext-to-exclude "mp3","txt" -scan-files-with-no-ext false -paths-to-exclude "\vol\a b\","\vol\a,b\"
----
. オンアクセスポリシーが作成されたことを確認します。 `vserver vscan on-access-policy show -instance _data_SVM|cluster_admin_SVM_ -policy-name policy_name`
+
すべてのオプションの一覧については、コマンドのマニュアルページを参照してください。

+
次のコマンドは、の詳細を表示します `Policy1` ポリシー：

+
[listing]
----
cluster1::> vserver vscan on-access-policy show -instance vs1 -policy-name Policy1

                           Vserver: vs1
                            Policy: Policy1
                     Policy Status: off
               Policy Config Owner: vserver
              File-Access Protocol: CIFS
                           Filters: scan-ro-volume
                    Mandatory Scan: on
Max File Size Allowed for Scanning: 3GB
            File Paths Not to Scan: \vol\a b\, \vol\a,b\
       File Extensions Not to Scan: mp3, txt
           File Extensions to Scan: mp*, tx*
      Scan Files with No Extension: false
----

