---
permalink: antivirus/install-ontap-antivirus-connector-task.html 
sidebar: sidebar 
keywords: install, ontap, task, antivirus connector 
summary: VscanサーバにONTAP Antivirus Connectorをインストールして、ONTAPを実行しているシステムとVscanサーバの間の通信を確立します。 
---
= ONTAP Antivirus Connectorのインストール
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
ONTAP Antivirus ConnectorをVscanサーバにインストールして、ONTAPを実行しているシステムとVscanサーバの間の通信を有効にします。ONTAP Antivirus Connectorをインストールすると、ウィルス対策ソフトウェアは1つ以上のStorage Virtual Machine（SVM）と通信できるようになります。

.このタスクについて
* link:../antivirus/vscan-partner-solutions.html["Vscanパートナーソリューション"]サポートされるプロトコル、ウィルス対策ベンダーのソフトウェアのバージョン、ONTAPのバージョン、相互運用性の要件、およびWindowsサーバについては、ページを参照してください。
* .NET 4.5.1以降がインストールされている必要があります。
* ONTAP Antivirus Connectorは仮想マシンで実行できます。ただし、パフォーマンスを最大限に高めるために、NetAppではアンチウイルススキャンに専用の仮想マシンを使用することを推奨しています。
* ONTAP Antivirus Connectorをインストールして実行するWindowsサーバでSMB 2.0が有効になっている必要があります。


.作業を開始する前に
* サポートサイトからONTAP Antivirus Connectorセットアップファイルをダウンロードし、ハードドライブのディレクトリに保存します。
* ONTAP Antivirus Connectorをインストールするための要件を満たしていることを確認します。
* Antivirus Connectorをインストールするための管理者権限があることを確認します。


.手順
. 適切なセットアップファイルを実行して、Antivirus Connectorインストールウィザードを開始します。
. ［次へ］を選択します。[インストール先フォルダ]ダイアログボックスが開きます。
. 表示されているフォルダにAntivirus Connectorをインストールするには、_Next_を選択します。別のフォルダにインストールするには、_Change__を選択します。
. [Windows AV Connector ONTAPサービスのクレデンシャル]ダイアログボックスが開きます。
. Windowsサービスのクレデンシャルを入力するか、*[追加]*を選択してユーザを選択します。ONTAPシステムの場合、このユーザは有効なドメインユーザであり、SVMのスキャナプール設定に存在している必要があります。
. 「 * 次へ * 」を選択します。[プログラムをインストールする準備ができました]ダイアログボックスが開きます。
. インストールを開始するには*[インストール]*を選択します。設定を変更する場合は*[戻る]*を選択します。
ステータス・ボックスが開き'インストールの進行状況が表示され'InstallShield Wizard Completedダイアログ・ボックスが表示されます
. ONTAP ONTAP管理LIFまたはデータLIFの設定を続行する場合は、[LIFの設定]チェックボックスを選択します。
このVscanサーバを使用するには、ONTAP管理LIFまたはデータLIFを少なくとも1つ設定する必要があります。
. インストールログを表示する場合は、[Windowsインストーラログを表示する]チェックボックスをオンにします。
. [完了]*を選択してインストールを終了し、InstallShieldウィザードを閉じます。
ONTAP LIFを設定するための*[Configure ONTAP LIFs]*アイコンがデスクトップに保存されます。
. Antivirus ConnectorにSVMを追加します。
SVMをAntivirus Connectorに追加するには、データLIFのリストを取得するようにポーリングされるONTAP管理LIFを追加するか、またはデータLIFを直接設定します。
ONTAP管理LIFが設定されている場合は、ポーリング情報とONTAP管理者アカウントのクレデンシャルも指定する必要があります。
+
** SVMの管理LIFまたはIPアドレスが `management-https`。これは、データLIFのみを設定する場合は必要ありません。
** HTTPアプリケーション用のユーザアカウントを作成し、（少なくとも読み取り専用）アクセスを持つロールを割り当てたことを確認します。 `/api/network/ip/interfaces` REST API：
ユーザの作成の詳細については、を参照してください。 link:https://docs.netapp.com/us-en/ontap-cli/security-login-role-create.html["Security login role create を実行します"^] および link:https://docs.netapp.com/us-en/ontap-cli/security-login-create.html["security login create を実行します"^] ONTAPのマニュアルページ





NOTE: 管理SVM用に認証トンネルSVMを追加して、ドメインユーザをアカウントとして使用することもできます。詳細については、を参照してください link:https://docs.netapp.com/us-en/ontap-cli/security-login-domain-tunnel-create.html["security login domain-tunnel createのように設定します"^] ONTAPのマニュアルページまたは `/api/security/acccounts` および `/api/security/roles` adminアカウントとロールを設定するためのREST API。

.手順
. Antivirus Connectorのインストールの完了時にデスクトップに保存されていた*[Configure ONTAP LIFs]*アイコンを右クリックし、*[Run as Administrator]*を選択します。
. [Configure ONTAP LIFs]ダイアログボックスで、優先する設定タイプを選択し、次の操作を実行します。
+
[cols="35,65"]
|===


| 作成するLIFのタイプ | 実行する手順 


 a| 
データ LIF
 a| 
.. 「role」を「data」に設定
.. 「data protocol」を「cifs」に設定
.. 「firewall policy」を「data」に設定する
.. 「service policy」を「default-data-files」に設定




 a| 
管理LIF
 a| 
.. 「role *」を「data」に設定
.. 「data protocol」を「none」に設定します。
.. 「firewall policy」を「mgmt」に設定
.. 「service policy」を「default-management」に設定


|===
+
詳細については、をご覧くださいlink:../networking/create_a_lif.html["LIFの作成"]。

+
LIFを作成したら、追加するSVMのデータLIF、管理LIF、またはIPアドレスを入力します。クラスタ管理LIFを入力することもできます。クラスタ管理LIFを指定すると、そのクラスタ内でSMBを提供しているすべてのSVMがVscanサーバを使用できます。

+
[NOTE]
====
VscanサーバでKerberos認証が必要な場合は、各SVMデータLIFに一意のDNS名を付ける必要があり、その名前をWindows Active DirectoryでServer Principal Name（SPN；サーバプリンシパル名）として登録する必要があります。各データLIFで一意のDNS名を使用できない場合、またはSPNとして登録されていない場合、VscanサーバはNT LAN Managerメカニズムを使用して認証します。Vscanサーバを接続したあとにDNS名とSPNを追加または変更した場合は、VscanサーバでAntivirus Connectorサービスを再起動して変更を適用する必要があります。

====
. 管理LIFを設定するには、ポーリング期間を秒単位で入力します。ポーリング期間は、Antivirus ConnectorがSVMまたはクラスタのLIF設定に対する変更をチェックする頻度です。デフォルトのポーリング間隔は60秒です。
. ONTAP管理者アカウント名とパスワードを入力して、管理LIFを設定します。
. [テスト]*をクリックして接続を確認し、認証を確認します。認証は管理LIFの設定でのみ検証されます。
. ポーリングまたは接続先のLIFのリストにLIFを追加するには、*[更新]*をクリックします。
. [保存]*をクリックして、レジストリへの接続を保存します。
. 接続のリストをレジストリインポートまたはレジストリエクスポートファイルにエクスポートする場合は、*エクスポート*をクリックします。これは、複数のVscanサーバが同じ管理LIFまたはデータLIFのセットを使用する場合に便利です。


を参照してください link:configure-ontap-antivirus-connector-task.html["ONTAP Antivirus Connectorページの設定"] を参照してください。
