---
permalink: antivirus/schedule-on-demand-task-task.html 
sidebar: sidebar 
keywords: schedule, on-demand, task 
summary: 'スケジュールを割り当てずにタスクを作成し、 `vserver vscan on-demand-task schedule` コマンドを使用してスケジュールを割り当てるか、タスクの作成時にスケジュールを追加します。' 
---
= オンデマンドタスクのスケジュールを設定します
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
スケジュールを割り当てずにタスクを作成し、 `vserver vscan on-demand-task schedule` コマンドを使用してスケジュールを割り当てるか、タスクの作成時にスケジュールを追加します。

.このタスクについて
で割り当てられたスケジュール `vserver vscan on-demand-task schedule` このコマンドは、ですでに割り当てられているスケジュールを上書きします `vserver vscan on-demand-task create` コマンドを実行します

.手順
. オンデマンドタスクのスケジュールを設定します。
+
`vserver vscan on-demand-task schedule -vserver _data_SVM_ -task-name _task_name_ -schedule cron_schedule`

+
次のコマンドは、という名前のオンアクセスタスクをスケジュールします `Task2` をクリックします `vs2` SVM：

+
[listing]
----
cluster1::> vserver vscan on-demand-task schedule -vserver vs2 -task-name Task2 -schedule daily
[Job 142]: Vscan On-Demand job is queued. Use the "job show -id 142" command to view the status.
----
+
ジョブのステータスを表示するには、 `job show` コマンドを実行します。 `job pause` および `job resume` ジョブをそれぞれ一時停止および再開するコマンド。 `job stop` コマンドを実行すると、ジョブが終了します。

. オンデマンドタスクがスケジュールされていることを確認します。
+
`vserver vscan on-demand-task show -instance _data_SVM_ -task-name _task_name_`

+
すべてのオプションの一覧については、コマンドのマニュアルページを参照してください。

+
次のコマンドは、の詳細を表示します `Task 2` タスク：

+
[listing]
----
cluster1::> vserver vscan on-demand-task show -instance vs2 -task-name Task2

                           Vserver: vs2
                         Task Name: Task2
                List of Scan Paths: /vol1/, /vol2/cifs/
             Report Directory Path: /report
                      Job Schedule: daily
Max File Size Allowed for Scanning: 5GB
            File Paths Not to Scan: /vol1/cold-files/
       File Extensions Not to Scan: mp3, mp4
           File Extensions to Scan: vmdk, mp*
      Scan Files with No Extension: false
           Request Service Timeout: 5m
                    Cross Junction: true
               Directory Recursion: true
                     Scan Priority: low
                  Report Log Level: info
----


.完了後
タスクの実行をスケジュールする前に、 SVM でスキャンを有効にする必要があります。
