---
permalink: antivirus/schedule-on-demand-task-task.html 
sidebar: sidebar 
keywords: schedule, on-demand, task 
summary: 'スケジュールを割り当てずにタスクを作成し、 `vserver vscan on-demand-task schedule` コマンドを使用してスケジュールを割り当てることも、タスクの作成中にスケジュールを追加することもできます。' 
---
= ONTAP Vscanでオンデマンドタスクをスケジュールする
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
スケジュールを割り当てずにタスクを作成し、 `vserver vscan on-demand-task schedule` コマンドを使用してスケジュールを割り当てることも、タスクの作成中にスケジュールを追加することもできます。

.タスク概要
 `vserver vscan on-demand-task schedule`コマンドで割り当てられたスケジュールは、 `vserver vscan on-demand-task create`コマンドですでに割り当てられているスケジュールを上書きします。

.手順
. オンデマンド タスクのスケジュールを設定します。
+
`vserver vscan on-demand-task schedule -vserver _data_SVM_ -task-name _task_name_ -schedule cron_schedule`

+
次のコマンドは、 `vs2` SVM で  `Task2` という名前のオンアクセス タスクをスケジュールします：

+
[listing]
----
cluster1::> vserver vscan on-demand-task schedule -vserver vs2 -task-name Task2 -schedule daily
[Job 142]: Vscan On-Demand job is queued. Use the "job show -id 142" command to view the status.
----
+
 `vserver vscan on-demand-task schedule`の詳細については、link:https://docs.netapp.com/us-en/ontap-cli/vserver-vscan-on-demand-task-schedule.html["ONTAPコマンド リファレンス"^]をご覧ください。

+

NOTE: ジョブのステータスを表示するには、 `job show`コマンドを使用します。 `job pause`コマンドと `job resume`コマンドはそれぞれジョブを一時停止および再開します。 `job stop`コマンドはジョブを終了します。link:https://docs.netapp.com/us-en/ontap-cli/search.html?q=job["ONTAPコマンド リファレンス"^]の `job`の詳細をご覧ください。

. オンデマンド タスクがスケジュールされていることを確認します。
+
`vserver vscan on-demand-task show -instance _data_SVM_ -task-name _task_name_`

+
 `vserver vscan on-demand-task show`の詳細については、link:https://docs.netapp.com/us-en/ontap-cli/vserver-vscan-on-demand-task-show.html["ONTAPコマンド リファレンス"^]をご覧ください。

+
次のコマンドは `Task 2`タスクの詳細を表示します：

+
[listing]
----
cluster1::> vserver vscan on-demand-task show -instance vs2 -task-name Task2

                           Vserver: vs2
                         Task Name: Task2
                List of Scan Paths: /vol1/, /vol2/cifs/
             Report Directory Path: /report
                      Job Schedule: daily
Max File Size Allowed for Scanning: 5GB
            File Paths Not to Scan: /vol1/cold-files/
       File Extensions Not to Scan: mp3, mp4
           File Extensions to Scan: vmdk, mp*
      Scan Files with No Extension: false
           Request Service Timeout: 5m
                    Cross Junction: true
               Directory Recursion: true
                     Scan Priority: low
                  Report Log Level: info
----


.終了後の操作
タスクの実行をスケジュールする前に、SVMでスキャンを有効にする必要があります。
