---
permalink: antivirus/schedule-on-demand-task-task.html 
sidebar: sidebar 
keywords: schedule, on-demand, task 
summary: 'スケジュールを割り当てずにタスクを作成し、コマンドを使用してスケジュールを割り当てることも、タスクの作成時にスケジュールを追加することもできます `vserver vscan on-demand-task schedule`。' 
---
= ONTAPでオンデマンドタスクのスケジュールを設定
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
スケジュールを割り当てずにタスクを作成し、コマンドを使用してスケジュールを割り当てることも、タスクの作成時にスケジュールを追加することもできます `vserver vscan on-demand-task schedule`。

.タスクの内容
コマンドで割り当てたスケジュール `vserver vscan on-demand-task schedule`は、コマンドですでに割り当てられているスケジュールよりも優先され `vserver vscan on-demand-task create`ます。

.手順
. オンデマンドタスクのスケジュールを設定します。
+
`vserver vscan on-demand-task schedule -vserver _data_SVM_ -task-name _task_name_ -schedule cron_schedule`

+
次のコマンドは、SVMに `vs2`という名前のオンアクセスタスクをスケジュールし `Task2`ます。

+
[listing]
----
cluster1::> vserver vscan on-demand-task schedule -vserver vs2 -task-name Task2 -schedule daily
[Job 142]: Vscan On-Demand job is queued. Use the "job show -id 142" command to view the status.
----
+
ジョブのステータスを表示するには、コマンドを使用し `job show`ます。 `job pause`コマンドと `job resume`コマンドは、それぞれジョブを一時停止して再開します。コマンドはジョブを終了します。 `job stop`

. オンデマンドタスクがスケジュールされていることを確認します。
+
`vserver vscan on-demand-task show -instance _data_SVM_ -task-name _task_name_`

+
の詳細については `vserver vscan on-demand-task show`、をlink:https://docs.netapp.com/us-en/ontap-cli/vserver-vscan-on-demand-task-show.html["ONTAPコマンド リファレンス"^]参照してください。

+
次のコマンドは、タスクの詳細を表示し `Task 2`ます。

+
[listing]
----
cluster1::> vserver vscan on-demand-task show -instance vs2 -task-name Task2

                           Vserver: vs2
                         Task Name: Task2
                List of Scan Paths: /vol1/, /vol2/cifs/
             Report Directory Path: /report
                      Job Schedule: daily
Max File Size Allowed for Scanning: 5GB
            File Paths Not to Scan: /vol1/cold-files/
       File Extensions Not to Scan: mp3, mp4
           File Extensions to Scan: vmdk, mp*
      Scan Files with No Extension: false
           Request Service Timeout: 5m
                    Cross Junction: true
               Directory Recursion: true
                     Scan Priority: low
                  Report Log Level: info
----


.終了後
タスクの実行をスケジュールする前に、SVMでスキャンを有効にする必要があります。
