---
permalink: antivirus/vscan-server-install-config-concept.html 
sidebar: sidebar 
keywords: vscan, server installation, configuration 
summary: ウィルススキャンを有効にするには、1つ以上のVscanサーバをセットアップして設定する必要があります。 
---
= Vscan サーバのインストールと設定
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
1つ以上のVscanサーバを設定して、システム上のファイルがウィルススキャンされるようにします。サーバにウィルス対策ソフトウェアをインストールして設定するには、ベンダーからの指示に従ってください。

NetAppが提供するREADMEファイルの手順に従って、ONTAP Antivirus Connectorをインストールして設定します。または、 link:install-ontap-antivirus-connector-task.html["[Install ONTAP Antivirus Connector]ページ"]。

[NOTE]
====
ディザスタリカバリおよびMetroCluster構成の場合は、プライマリ/ローカルおよびセカンダリ/パートナーのONTAPクラスタ用に個別のVscanサーバをセットアップして設定する必要があります。

====


== ウィルス対策ソフトウェアの要件

* ウィルス対策ソフトウェアの要件については、ベンダーのドキュメントを参照してください。
* Vscan でサポートされるベンダー、ソフトウェア、およびバージョンについては、を参照してください link:https://docs.netapp.com/us-en/ontap/antivirus/vscan-partner-solutions.html["Vscanパートナーソリューション"^] ページ




== ONTAP Antivirus Connector の要件

* ONTAP Antivirus Connectorは、NetApp Support Siteの*ソフトウェアダウンロード*ページからダウンロードできます。 link:http://mysupport.netapp.com/NOW/cgi-bin/software["ネットアップのダウンロード：ソフトウェア"]
* ONTAP Antivirus ConnectorでサポートされるWindowsのバージョンと相互運用性の要件については、を参照してください。 link:https://docs.netapp.com/us-en/ontap/antivirus/vscan-partner-solutions.html["Vscanパートナーソリューション"^]。
+
[NOTE]
====
クラスタ内の Vscan サーバによってインストールする Windows サーバのバージョンは同じでなくても構いません。

====
* Windows サーバに .NET 3.0 以降がインストールされている必要があります。
* Windows サーバで SMB 2.0 が有効になっている必要があります。

