---
permalink: antivirus/vscan-server-connection-concept.html 
sidebar: sidebar 
keywords: potential connectivity, issues, involve, scan-mandatory, option 
summary: オンアクセススキャンに scan-mandatory オプションを指定した場合、デフォルトでは、スキャンに使用できる Vscan サーバ接続がないとファイルアクセスが拒否されます。このオプションは重要な安全機能を備えていますが、いくつかの状況で問題が発生する可能性があります。 
---
= scan-mandatory オプションの使用時に発生する可能性がある接続の問題
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
を使用できます `vserver vscan connection-status show` 接続の問題のトラブルシューティングに役立つVscanサーバ接続に関する情報を表示するコマンド。

デフォルトでは、が表示されます `scan-mandatory` オンアクセススキャンのオプションを指定すると、Vscanサーバ接続がスキャンに使用できない場合にファイルアクセスが拒否されます。このオプションは重要な安全機能を備えていますが、いくつかの状況で問題が発生する可能性があります。

* クライアントアクセスを有効にする前に、 LIF が設定された各ノードの SVM に少なくとも 1 つの Vscan サーバが接続されていることを確認する必要があります。クライアントアクセスを有効にしたあとにSVMにサーバを接続する必要がある場合は、をオフにする必要があります `scan-mandatory` Vscanサーバ接続を使用できないためにファイルアクセスが拒否されないようにするためのSVMのオプション。サーバの接続が完了したら、オプションをオンに戻すことができます。
* 1 つのターゲット LIF で SVM のすべての Vscan サーバ接続をホストしている場合、その LIF を移行するとサーバと SVM の間の接続が失われます。Vscanサーバ接続を使用できないことが原因でファイルアクセスが拒否されないようにするには、をオフにする必要があります `scan-mandatory` LIFを移行する前に選択します。LIF の移行が完了したら、オプションをオンに戻すことができます。


各 SVM に少なくとも 2 つの Vscan サーバを割り当てる必要があります。ストレージシステムへの Vscan サーバの接続には、クライアントアクセスとは別のネットワークを使用することを推奨します。
