---
permalink: revert/concept_reversion_requirements_for_snapmirror_and_snapvault_relationships.html 
sidebar: sidebar 
keywords: ontap, revert, reverting, reversion, requirements, snapmirror, snapvault, relationships 
summary: system node revert-to コマンドは、リバートプロセスを完了するために削除または再設定が必要な SnapMirror および SnapVault 関係を通知します。ただし、リバートを開始する前にこれらの要件を理解しておく必要があります。 
---
= SnapMirror関係とSnapVault関係のONTAP復帰要件
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
この `system node revert-to`コマンドは、復元プロセスを完了するために削除または再構成する必要があるSnapMirrorおよびSnapVault関係を通知します。ただし、復元を開始する前にこれらの要件を理解しておく必要があります。

* すべてのSnapVaultおよびデータ保護ミラー関係を静止させてから解除する必要があります。
+
リバートが完了したら、共通のSnapshotが存在する場合は、これらの関係を再同期して再開できます。

* SnapVault関係には次のSnapMirrorポリシータイプを含めることはできません：
+
** async-mirror
+
このポリシータイプを使用する関係をすべて削除する必要があります。

** MirrorAndVault
+
これらの関係のいずれかが存在する場合は、SnapMirrorポリシーをmirror-vaultに変更する必要があります。



* すべての負荷共有ミラー関係とデスティネーションボリュームを削除する必要があります。
* FlexClone デスティネーションボリュームとの SnapMirror 関係は削除する必要があります。
* 各SnapMirrorポリシーでネットワーク圧縮を無効にする必要があります。
* all_source_snapshot ルールは、すべての async-mirror タイプの SnapMirror ポリシーから削除する必要があります。
+

NOTE: ルート ボリュームでは、Single File Snapshot Restore（SFSR）操作と Partial File Snapshot Restore（PFSR）操作は非推奨です。

* リバート処理を続行する前に、現在実行中のシングルファイルリストアおよび Snapshot リストア処理をすべて完了しておく必要があります。
+
復元処理が完了するまで待つか、中止することができます。

* 不完全な単一ファイルおよび Snapshot のリストア処理は、 `snapmirror restore`コマンドを使用して削除する必要があります。
+
 `snapmirror restore`の詳細については、link:https://docs.netapp.com/us-en/ontap-cli/snapmirror-restore.html["ONTAPコマンド リファレンス"^]を参照してください。


