---
permalink: revert/task_verifying_storage_health_before_revert.html 
sidebar: sidebar 
keywords: ontap, revert, verify, verifying, storage, health, before, revert, reverting 
summary: クラスタのアップグレード、リバート、またはダウングレードを行う際は、実行前と実行後に、ディスク、アグリゲート、およびボリュームのステータスを確認する必要があります。 
---
= リバート前にストレージの健全性を確認する
:icons: font
:imagesdir: ../media/


[role="lead"]
クラスタをリバートまたはダウングレードする際は、実行前と実行後に、ディスク、アグリゲート、およびボリュームのステータスを確認する必要があります。

. ディスクのステータスを確認します。
+
[cols="2*"]
|===
| 確認する項目 | 手順 


 a| 
破損ディスク
 a| 
.. 破損ディスクを表示します。「 storage disk show -state broken 」
.. 破損ディスクを取り外すか交換します。




 a| 
メンテナンス中または再構築中のディスク
 a| 
.. 「 storage disk show -state maintenance 」という状態のディスクを表示します




| 保留中です | 再構築中メンテナンスまたは再構築の処理が完了するまで待ってから次に進みます。[+] 
|===
. ストレージアグリゲート「 storage aggregate show -state ！ online 」を含む物理ストレージと論理ストレージの状態を表示して、すべてのアグリゲートがオンラインであることを確認します
+
このコマンドを実行すると、オンラインでないアグリゲートが表示されます。メジャーリバートの実行前と実行後には、すべてのアグリゲートがオンラインになっている必要があります。

+
[listing]
----
cluster1::> storage aggregate show -state !online
There are no entries matching your query.
----
. すべてのボリュームがオンラインであることを確認するには 'volume show -state ！ online ' のようなボリュームを表示します
+
メジャーリバートの実行前と実行後には、すべてのボリュームがオンラインになっている必要があります。

+
[listing]
----
cluster1::> volume show -state !online
There are no entries matching your query.
----
. 整合性のないボリュームがないことを確認します。 volume show -is-inconsistent true
+
整合性のないボリュームが返された場合は、の前にネットアップサポートにお問い合わせください。



link:../disks-aggregates/index.html["ディスクおよびアグリゲートの管理"]
