---
permalink: revert/task_preparing_snapshot_copies_before_reverting.html 
sidebar: sidebar 
keywords: ontap, revert, reverting, reversion, snapshot, copies, prepare, preparing, disable, delete 
summary: 以前の ONTAP リリースに戻す前に、すべてのスナップショット ポリシーを無効にし、現在のリリースにアップグレードした後に作成されたスナップショットをすべて削除する必要があります。 
---
= ONTAPクラスタをリバートする前にSnapshotを準備
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
ONTAP クラスタを ONTAP 9 の任意のバージョンから戻す前に、すべての Snapshot ポリシーを無効にし、現在のリリースにアップグレードした後に作成された Snapshot をすべて削除する必要があります。

SnapMirror環境内で元に戻す場合は、まず次のミラー関係を削除する必要があります：

* すべての負荷分散ミラー関係
* ONTAP 8.3.xで作成されたデータ保護ミラー関係
* クラスタが ONTAP 8.3.x で再作成された場合のすべてのデータ保護ミラー関係


.手順
. すべてのデータSVMのSnapshotポリシーを無効にします：
+
[source, cli]
----
volume snapshot policy modify -vserver * -enabled false
----
. 各ノードのアグリゲートのスナップショットポリシーを無効にします：
+
.. ノードのアグリゲートを特定します：
+
[source, cli]
----
run -node <nodename> -command aggr status
----
.. 各アグリゲートのスナップショットポリシーを無効にします：
+
[source, cli]
----
run -node <nodename> -command aggr options aggr_name nosnap on
----
.. 残りの各ノードについて、この手順を繰り返します。


. 各ノードのルートボリュームのスナップショットポリシーを無効にします：
+
.. ノードのルートボリュームを特定します：
+
[source, cli]
----
run -node <node_name> -command vol status
----
+
ルート ボリュームは、 `vol status`コマンド出力の *Options* 列の root という単語で識別します。

+
[listing]
----
vs1::> run -node node1 vol status

         Volume State           Status            Options
           vol0 online          raid_dp, flex     root, nvfail=on
                                64-bit
----
.. ルート ボリュームのスナップショット ポリシーを無効にします：
+
[source, cli]
----
run -node <node_name> vol options root_volume_name nosnap on
----
.. 残りの各ノードについて、この手順を繰り返します。


. 現在のリリースにアップグレードした後に作成されたすべてのスナップショットを削除します：
+
.. 権限レベルをadvancedに設定します。
+
[source, cli]
----
set -privilege advanced
----
.. スナップショットを無効にします：
+
[source, cli]
----
snapshot policy modify -vserver * -enabled false
----
.. ノードの新しいバージョンのスナップショットを削除します：
+
[source, cli]
----
volume snapshot prepare-for-revert -node <node_name>
----
+
このコマンドは、各データボリューム、ルートアグリゲート、およびルートボリューム上の新しいバージョンのSnapshotを削除します。

+
スナップショットを削除できない場合、コマンドは失敗し、スナップショットを削除する前に実行する必要があるアクションが通知されます。必要なアクションを完了してから `volume snapshot prepare-for-revert`コマンドを再実行し、次の手順に進んでください。

+
[listing]
----
cluster1::*> volume snapshot prepare-for-revert -node node1

Warning: This command will delete all snapshots that have the format used by the current version of ONTAP. It will fail if any snapshot policies are enabled, or
         if any snapshots have an owner. Continue? {y|n}: y
----
.. スナップショットが削除されたことを確認します：
+
[source, cli]
----
volume snapshot show -node nodename
----
.. 新しいバージョンのスナップショットが残っている場合は、強制的に削除します：
+
[source, cli]
----
volume snapshot delete {-fs-version 9.0 -node nodename -is-constituent true} -ignore-owners -force
----
.. 残りの各ノードについて、これらの手順を繰り返します。
.. admin権限レベルに戻ります。
+
[source, cli]
----
set -privilege admin
----





NOTE: MetroCluster構成内の両方のクラスターでこれらの手順を実行する必要があります。
