---
permalink: revert/task_reverting_password_hash_function.html 
sidebar: sidebar 
keywords: revert, reverting, reversion, password, hash, function, supported, encryption, type 
summary: ONTAP 9 のいずれかのバージョンを以前のリリースにリバートすると、 SHA-2 アカウントユーザは元のパスワードで認証できなくなります。そのため、ユーザがあらかじめパスワードをリセットして、リバート後のリリースでサポートされる暗号化タイプ \ （ MD5\ ）を使用するようにしておく必要があります。 
---
= パスワードのハッシュ関数をサポートされる暗号化タイプにリバートします
:icons: font
:imagesdir: ../media/


[role="lead"]
ONTAP 9 のいずれかのバージョンを以前のリリースにリバートすると、 SHA-2 アカウントユーザは元のパスワードで認証できなくなります。そのため、ユーザがあらかじめパスワードをリセットして、リバート後のリリースでサポートされる暗号化タイプ（ MD5 ）のパスワードに変更しておく必要があります。

. リバートを実行する前に、 SHA-2 ハッシュ関数を使用しているユーザアカウントを特定します（ advanced 権限レベル）。 security login show -vserver * -username * -application * -authentication-method password-hash-function ！ md5`
+
コマンドの出力は残しておく必要があります。リバート後にアカウント情報が必要になります。

. リバート中に、 advanced 権限レベルのコマンド security login password-prepare-to-downgrade を実行して、 MD5 ハッシュ関数を使用して自分のパスワードをリセットするように求められます。
+
パスワードが MD5 で暗号化されていない場合は、新しいパスワードを入力するように求められ、 MD5 で暗号化されます。これにより、リバート後にクレデンシャルが認証されるようになります。

. リバートしたら、 SHA-2 アカウントを MD5 にリセットします。
+
.. 特定した SHA-2 アカウントごとに、パスワードを一時パスワードに変更します。「 security login password -username user_name -vserver vserver_name 」
+
変更したパスワードは MD5 ハッシュ関数を使用します。

.. 影響を受けるユーザに一時パスワードを送信します。ユーザに、コンソールまたは SSH セッションからログインして、表示される指示に従ってパスワードを変更するよう指示します。



