---
permalink: revert/task_enabling_and_reverting_lifs_to_home_ports_completing_post_reversion_tasks.html 
sidebar: sidebar 
keywords: ontap, revert, reverting, reversion, downgrade, downgrading, enable, enabling, lifs, home, ports 
summary: リブート時に、一部のLIFが関連付けられているフェイルオーバー ポートに移行されることがあります。クラスタをリバートしたら、ホーム ポートにないLIFを有効にしてリバートする必要があります。 
---
= ONTAP のリバート後に LIF を有効にしてホームポートに戻す
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
再起動中に、一部のLIFが割り当てられたフェイルオーバーポートに移行されている可能性があります。ONTAPクラスタをリバートした後、ホームポートにないLIFをすべて有効化してリバートする必要があります。

network interface revertコマンドを実行すると、対応するホーム ポートにないLIFがホーム ポートにリバートされます（ホーム ポートが稼働している場合）。LIFのホーム ポートはLIFの作成時に指定されます。指定されたホーム ポートはnetwork interface showコマンドで確認できます。

.手順
. すべてのLIFのステータスを表示します。
+
[source, cli]
----
network interface show
----
+
Storage Virtual Machine（SVM）のすべてのLIFのステータスを表示する例を次に示します。

+
[listing]
----
cluster1::> network interface show -vserver vs0
            Logical    Status     Network            Current       Current Is
Vserver     Interface  Admin/Oper Address/Mask       Node          Port    Home
----------- ---------- ---------- ------------------ ------------- ------- ----
vs0
            data001    down/down  192.0.2.120/24     node0         e0e     true
            data002    down/down  192.0.2.121/24     node0         e0f     true
            data003    down/down  192.0.2.122/24     node0         e2a     true
            data004    down/down  192.0.2.123/24     node0         e2b     true
            data005    down/down  192.0.2.124/24     node0         e0e     false
            data006    down/down  192.0.2.125/24     node0         e0f     false
            data007    down/down  192.0.2.126/24     node0         e2a     false
            data008    down/down  192.0.2.127/24     node0         e2b     false
8 entries were displayed.
----
+
Status AdminステータスがdownになっているLIFや、Is homeステータスがfalseになっているLIFがある場合は、次の手順に進みます。

. データLIFを有効にします。
+
[source, cli]
----
network interface modify {-role data} -status-admin up
----
. LIFをそれぞれのホーム ポートにリバートします。
+
[source, cli]
----
network interface revert *
----
. すべてのLIFがそれぞれのホーム ポートにあることを確認します。
+
[source, cli]
----
network interface show
----
+
次の例では、SVM vs0のすべてのLIFがそれぞれのホーム ポートにあります。

+
[listing]
----
cluster1::> network interface show -vserver vs0
            Logical    Status     Network            Current       Current Is
Vserver     Interface  Admin/Oper Address/Mask       Node          Port    Home
----------- ---------- ---------- ------------------ ------------- ------- ----
vs0
            data001      up/up    192.0.2.120/24     node0         e0e     true
            data002      up/up    192.0.2.121/24     node0         e0f     true
            data003      up/up    192.0.2.122/24     node0         e2a     true
            data004      up/up    192.0.2.123/24     node0         e2b     true
            data005      up/up    192.0.2.124/24     node1         e0e     true
            data006      up/up    192.0.2.125/24     node1         e0f     true
            data007      up/up    192.0.2.126/24     node1         e2a     true
            data008      up/up    192.0.2.127/24     node1         e2b     true
8 entries were displayed.
----


.関連情報
* link:https://docs.netapp.com/us-en/ontap-cli/search.html?q=network+interface["ネットワーク インターフェイス"^]

