---
permalink: revert/task_preparing_snapshot_copies_before_reverting.html 
sidebar: sidebar 
keywords: ontap, revert, reverting, reversion, snapshot, copies, prepare, preparing, disable, delete 
summary: 以前の ONTAP リリースにリバートする前に、すべての Snapshot コピーポリシーを無効にして、現在のリリースへのアップグレード後に作成された Snapshot コピーを削除する必要があります。 
---
= リバート前に Snapshot コピーを準備する
:icons: font
:imagesdir: ../media/


[role="lead"]
以前の ONTAP リリースにリバートする前に、すべての Snapshot コピーポリシーを無効にして、現在のリリースへのアップグレード後に作成された Snapshot コピーを削除する必要があります。

SnapMirror 環境でリバートを実行する場合は、次のミラー関係を事前に削除しておく必要があります。

* すべての負荷共有ミラー関係
* ONTAP 8.3.x で作成したすべてのデータ保護ミラー関係
* ONTAP 8.3.x でクラスタが再作成された場合は、すべてのデータ保護ミラー関係
+
.. すべてのデータ SVM に対して Snapshot コピーポリシーを無効にします。 volume snapshot policy modify -vserver * -enabled false
.. 各ノードのアグリゲートに対して Snapshot コピーポリシーを無効にします。
+
... run -nodeodnameaggr status コマンドを使用して、ノードのアグリゲートを特定します。
... 各アグリゲートに対して Snapshot コピーポリシーを無効にします。「 run -node nodename aggr options aggr_name nosnap on
... 残りのノードそれぞれに対して同じ手順を繰り返します。


.. 各ノードのルートボリュームに対して Snapshot コピーポリシーを無効にします。
+
... run -nodeodevenostatus コマンドを使用して、ノードのルートボリュームを特定します。
+
ルートボリュームは、 vol status コマンドの出力で Options 列に root として表記されます。

+
[listing]
----
vs1::> run -node node1 vol status

         Volume State           Status            Options
           vol0 online          raid_dp, flex     root, nvfail=on
                                64-bit
----
... ルートボリュームの Snapshot コピーポリシーを無効にします。「 run -node nodename vol options root_volume_name nosnap on
... 残りのノードそれぞれに対して同じ手順を繰り返します。


.. 現在のリリースへのアップグレード後に作成された Snapshot コピーをすべて削除します。
+
... 権限レベルを advanced に設定します。「 set -privilege advanced 」
... スナップショットを無効にします。「 'Snapshotpolicy modify -vserver * -enabled false 」
... ノードの新しいバージョンの Snapshot コピーを削除します。 volume snapshot prepare-for-revert -node nodename
+
このコマンドは、各データボリューム、ルートアグリゲート、およびルートボリュームの新しいバージョンの Snapshot コピーを削除します。

+
いずれかの Snapshot コピーを削除できない場合、コマンドは失敗し、 Snapshot コピーの削除前に実施する必要があるアクションがあれば通知されます。必要なアクションを完了し、 volume snapshot prepare-for-revert コマンドを再実行してから、次の手順に進んでください。

+
[listing]
----
cluster1::*> volume snapshot prepare-for-revert -node node1

Warning: This command will delete all Snapshot copies that have the format used by the current version of ONTAP. It will fail if any Snapshot copy polices are enabled, or
         if any Snapshot copies have an owner. Continue? {y|n}: y
----
... Snapshot コピーが削除されたことを確認します。 volume snapshot show -node nodename
+
新しいバージョンの Snapshot コピーが残っている場合は、強制的に削除します。 volume snapshot delete ｛ -fs-version 9.0 -node nodename -is-constituent true ｝ -ignore-owners -force

... 残りのノードそれぞれについて、手順 c を繰り返します。
... admin 権限レベルに戻ります。「 set -privilege admin 」




+

NOTE: これらの手順を MetroCluster 構成内の両方のクラスタで実行する必要があります。


