---
permalink: revert/task_enabling_and_reverting_lifs_to_home_ports_completing_post_reversion_tasks.html 
sidebar: sidebar 
keywords: ontap, revert, reverting, reversion, downgrade, downgrading, enable, enabling, lifs, home, ports 
summary: リブート時に、割り当てられているフェイルオーバーポートに一部のLIFが移行されることがあります。クラスタをリバートしたあと、ホームポートにないLIFを有効にしてリバートする必要があります。 
---
= リバート後にLIFを有効にしてホームポートにリバートする
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
リブート時に、割り当てられているフェイルオーバーポートに一部のLIFが移行されることがあります。クラスタをリバートしたあと、ホームポートにないLIFを有効にしてリバートする必要があります。

network interface revertコマンドを実行すると、ホームポートにないLIFがホームポートにリバートされます（ホームポートが稼働している場合）。LIFのホームポートはLIFの作成時に指定します。指定されているホームポートは、network interface showコマンドを使用して確認できます。

. すべてのLIFのステータスを表示します。 `network interface show`
+
Storage Virtual Machine（SVM）のすべてのLIFのステータスを表示する例を次に示します。

+
[listing]
----
cluster1::> network interface show -vserver vs0
            Logical    Status     Network            Current       Current Is
Vserver     Interface  Admin/Oper Address/Mask       Node          Port    Home
----------- ---------- ---------- ------------------ ------------- ------- ----
vs0
            data001    down/down  192.0.2.120/24     node0         e0e     true
            data002    down/down  192.0.2.121/24     node0         e0f     true
            data003    down/down  192.0.2.122/24     node0         e2a     true
            data004    down/down  192.0.2.123/24     node0         e2b     true
            data005    down/down  192.0.2.124/24     node0         e0e     false
            data006    down/down  192.0.2.125/24     node0         e0f     false
            data007    down/down  192.0.2.126/24     node0         e2a     false
            data008    down/down  192.0.2.127/24     node0         e2b     false
8 entries were displayed.
----
+
Status AdminステータスがdownになっているLIFやIs homeステータスがfalseになっているLIFがある場合は、次の手順に進みます。

. データLIFを有効にします。 `network interface modify {-role data} -status-admin up`
+
[listing]
----
cluster1::> network interface modify {-role data} -status-admin up
8 entries were modified.
----
. LIFをそれぞれのホームポートにリバートします。 `network interface revert *`
+
このコマンドを実行すると、すべてのLIFがそれぞれのホームポートにリバートされます。

+
[listing]
----
cluster1::> network interface revert *
8 entries were acted on.
----
. すべてのLIFがそれぞれのホームポートにあることを確認します。 `network interface show`
+
次の例では、SVM vs0のすべてのLIFがそれぞれのホームポートにあります。

+
[listing]
----
cluster1::> network interface show -vserver vs0
            Logical    Status     Network            Current       Current Is
Vserver     Interface  Admin/Oper Address/Mask       Node          Port    Home
----------- ---------- ---------- ------------------ ------------- ------- ----
vs0
            data001      up/up    192.0.2.120/24     node0         e0e     true
            data002      up/up    192.0.2.121/24     node0         e0f     true
            data003      up/up    192.0.2.122/24     node0         e2a     true
            data004      up/up    192.0.2.123/24     node0         e2b     true
            data005      up/up    192.0.2.124/24     node1         e0e     true
            data006      up/up    192.0.2.125/24     node1         e0f     true
            data007      up/up    192.0.2.126/24     node1         e2a     true
            data008      up/up    192.0.2.127/24     node1         e2b     true
8 entries were displayed.
----

