---
permalink: smb-admin/access-snapshot-directories-clients-smb2-concept.html 
sidebar: sidebar 
keywords: method, access, snapshot, directory, windows, client, smb, data, store, copies, copy, how to access the snapshot directory from windows clients using smb 2.x 
summary: SMB 2.x を使用する Windows クライアントからの ~snapshot ディレクトリへのアクセスに使用する方法は、 SMB 1.0 の場合に使用する方法とは異なります。SMB 2.x 接続を使用して Snapshot コピーに格納されたデータに正常にアクセスするために ~snapshot ディレクトリにアクセスする方法について理解しておく必要があります。 
---
= SMB 2.x を使用する Windows クライアントから ~snapshot ディレクトリにアクセスします
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
へのアクセスに使用する方法 `~snapshot` SMB 2.xを使用するWindowsクライアントのディレクトリは、SMB 1.0の場合に使用する方法とは異なります。にアクセスする方法を理解しておく必要があります `~snapshot` SMB 2.x接続を使用してSnapshotコピーに格納されたデータに正常にアクセスする場合のディレクトリ。

SVM管理者は、Windowsクライアントのユーザがを表示してにアクセスできるかどうかを制御します `~snapshot` を有効または無効にして、共有上のディレクトリを指定します `showsnapshot` vserver cifs share propertiesファミリーのコマンドを使用して共有プロパティを指定します。

をクリックします `showsnapshot` 共有プロパティが無効になっているため、SMB 2.xを使用するWindowsクライアントのユーザはを表示できません `~snapshot` ディレクトリとでSnapshotコピーにアクセスできません `~snapshot` ディレクトリ。へのパスを手動で入力した場合も同様です `~snapshot` ディレクトリまたはディレクトリ内の特定のSnapshotコピー

をクリックします `showsnapshot` 共有プロパティが有効になっている場合、SMB 2.xを使用するWindowsクライアントのユーザは、を表示できません `~snapshot` ディレクトリは共有のルート、または共有のルートより下の任意のジャンクションまたはディレクトリ内にあります。ただし、共有に接続すると、非表示にアクセスできるようになります `~snapshot` 手動で追加したディレクトリ `\~snapshot` 共有パスの末尾に移動します。非表示 `~snapshot` ディレクトリには、次の2つのエントリポイントからアクセスできます。

* を共有のルートに追加します
* を共有スペースのすべてのジャンクションポイントでクリックします


非表示 `~snapshot` 共有内のジャンクション以外のサブディレクトリからディレクトリにアクセスすることはできません。

.例
次の例の構成では、「eng」共有へのSMB 2.x接続を使用するWindowsクライアントのユーザがにアクセスできます `~snapshot` 手動で追加したディレクトリ `\~snapshot` 共有のルート、およびパス内のすべてのジャンクションポイントにある共有パスへのパス。非表示 `~snapshot` ディレクトリには、次の3つのパスからアクセスできます。

* `\\vs1\eng\~snapshot`
* `\\vs1\eng\projects1\~snapshot`
* `\\vs1\eng\projects2\~snapshot`


[listing]
----
cluster1::> volume show -vserver vs1 -fields volume,junction-path
vserver volume       junction-path
------- ------------ ----------------------------------------
vs1     vs1_root      /
vs1     vs1_vol1      /eng
vs1     vs1_vol2      /eng/projects1
vs1     vs1_vol3      /eng/projects2

cluster1::> vserver cifs share show
Vserver  Share   Path     Properties    Comment  ACL
-------- ------  -------  ----------    -------- ----------
vs1      eng     /eng     oplocks       -        Everyone / Full Control
                          changenotify
                          browsable
                          showsnapshot
----