---
permalink: smb-admin/access-snapshot-directories-clients-smb2-concept.html 
sidebar: sidebar 
keywords: method, access, snapshot, directory, windows, client, smb, data, store, copies, copy, how to access the snapshot directory from windows clients using smb 2.x 
summary: SMB 2.x を使用する Windows クライアントからの ~snapshot ディレクトリへのアクセスに使用する方法は、 SMB 1.0 の場合に使用する方法とは異なります。SMB 2.x 接続を使用して Snapshot コピーに格納されたデータに正常にアクセスするために ~snapshot ディレクトリにアクセスする方法について理解しておく必要があります。 
---
= SMB 2.x を使用する Windows クライアントから ~snapshot ディレクトリにアクセスします
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
へのアクセスに使用する方法 `~snapshot` SMB 2.xを使用するWindowsクライアントのディレクトリは、SMB 1.0の場合とは異なります。にアクセスする方法を理解しておく必要があります `~snapshot` SMB 2.x接続を使用してSnapshotコピーに格納されたデータに正常にアクセスする場合のディレクトリ。

SVM管理者は、Windowsクライアントのユーザがに表示およびアクセスできるかどうかを制御します `~snapshot` 共有上のディレクトリを有効または無効にします `showsnapshot` vserver cifs share properties familiesコマンドを使用した共有プロパティ。

をクリックします `showsnapshot` 共有プロパティが無効になっているため、SMB 2.xを使用するWindowsクライアントのユーザはを表示できません `~snapshot` ディレクトリにあり、内のSnapshotコピーにはアクセスできません `~snapshot` ディレクトリ（へのパスを手動で入力した場合も含む） `~snapshot` またはディレクトリ内の特定のSnapshotコピーにコピーします。

をクリックします `showsnapshot` 共有プロパティが有効になっています。SMB 2.xを使用するWindowsクライアントのユーザは引き続きを表示できません `~snapshot` 共有のルート、または共有のルートより下のジャンクションまたはディレクトリ内のディレクトリ。ただし、共有に接続したユーザは非表示のにアクセスできます `~snapshot` ディレクトリを手動で追加します `\~snapshot` 共有パスの末尾に移動します。隠れた者だ `~snapshot` ディレクトリには、次の2つのエントリポイントからアクセスできます。

* を共有のルートに追加します
* を共有スペースのすべてのジャンクションポイントでクリックします


隠れた者だ `~snapshot` 共有内のジャンクション以外のサブディレクトリからディレクトリにアクセスすることはできません。

.例
次の例に示す設定では、「eng'」共有へのSMB 2.x接続を使用するWindowsクライアントのユーザがにアクセスできます `~snapshot` ディレクトリを手動で追加します `\~snapshot` を共有パス（共有のルート、およびパス内のすべてのジャンクションポイント）に設定します。隠れた者だ `~snapshot` ディレクトリには、次の3つのパスからアクセスできます。

* `\\vs1\eng\~snapshot`
* `\\vs1\eng\projects1\~snapshot`
* `\\vs1\eng\projects2\~snapshot`


[listing]
----
cluster1::> volume show -vserver vs1 -fields volume,junction-path
vserver volume       junction-path
------- ------------ ----------------------------------------
vs1     vs1_root      /
vs1     vs1_vol1      /eng
vs1     vs1_vol2      /eng/projects1
vs1     vs1_vol3      /eng/projects2

cluster1::> vserver cifs share show
Vserver  Share   Path     Properties    Comment  ACL
-------- ------  -------  ----------    -------- ----------
vs1      eng     /eng     oplocks       -        Everyone / Full Control
                          changenotify
                          browsable
                          showsnapshot
----