---
permalink: smb-admin/add-privileges-local-domain-users-groups-task.html 
sidebar: sidebar 
keywords: manage, right, user, local, domain, add, privilege, override, default, object, enhance, customize, user, group, add privileges to local or domain users or groups 
summary: 権限を追加することで、ローカルまたはドメインのユーザーやグループのユーザー権限を管理できます。追加した権限は、これらのオブジェクトに割り当てられたデフォルトの権限をオーバーライドします。これにより、ユーザーまたはグループの権限をカスタマイズできるため、セキュリティが強化されます。 
---
= ONTAP SMB のローカルまたはドメイン ユーザーまたはグループに権限を追加する
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
権限を追加することで、ローカルまたはドメインのユーザーやグループのユーザー権限を管理できます。追加した権限は、これらのオブジェクトに割り当てられたデフォルトの権限をオーバーライドします。これにより、ユーザーまたはグループの権限をカスタマイズできるため、セキュリティが強化されます。

.開始する前に
権限を追加するローカルまたはドメインのユーザーまたはグループがすでに存在している必要があります。

.タスク概要
オブジェクトに権限を追加すると、そのユーザーまたはグループのデフォルトの権限が上書きされます。権限を追加しても、以前に追加された権限は削除されません。

ローカルまたはドメインのユーザーまたはグループに権限を追加するときは、次の点に留意する必要があります：

* 1 つ以上の権限を追加できます。
* ドメイン ユーザまたはグループへの権限の追加時、ONTAPでは、ドメイン コントローラに接続してそのドメイン ユーザまたはグループを検証することがあります。
+
ONTAPがドメイン コントローラに接続できない場合、コマンドが失敗する可能性があります。



.手順
. ローカルまたはドメインのユーザーまたはグループに 1 つ以上の権限を追加します： `+vserver cifs users-and-groups privilege add-privilege -vserver _vserver_name_ -user-or-group-name name -privileges _privilege_[,...]+`
. 必要な権限がオブジェクトに適用されていることを確認します： `vserver cifs users-and-groups privilege show -vserver _vserver_name_ ‑user-or-group-name _name_`


.例
次の例では、ストレージ仮想マシン（SVM、旧称Vserver）vs1上のユーザー「`CIFS_SERVER\sue`」に権限「`SeTcbPrivilege`」および「`SeTakeOwnershipPrivilege`」を追加します：

[listing]
----
cluster1::> vserver cifs users-and-groups privilege add-privilege -vserver vs1 -user-or-group-name CIFS_SERVER\sue -privileges SeTcbPrivilege,SeTakeOwnershipPrivilege

cluster1::> vserver cifs users-and-groups privilege show -vserver vs1
Vserver   User or Group Name    Privileges
--------- --------------------- ---------------
vs1       CIFS_SERVER\sue       SeTcbPrivilege
                                SeTakeOwnershipPrivilege
----