---
permalink: smb-admin/add-remove-share-properties-existing-share-task.html 
sidebar: sidebar 
keywords: customize, exist, smb, share, add, remove, removing, properties, useful, configuration, changing, change, requirement, environment, add or remove share properties on an existing smb share 
summary: 共有プロパティを追加または削除することで、既存のSMB共有をカスタマイズできます。この方法は、環境内での要件の変化に合わせて共有の設定を変更する場合に役立ちます。 
---
= 既存のONTAP SMB共有の共有プロパティを追加または削除する
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
共有プロパティを追加または削除することで、既存のSMB共有をカスタマイズできます。

使用可能な共有プロパティは次のとおりです：

[cols="2,4"]
|===
| 共有プロパティ | 概要 


 a| 
`oplocks`
 a| 
共有が便宜的ロック（クライアント側キャッシュ）を使用することを指定します。



 a| 
`browsable`
 a| 
Windowsクライアントに共有を参照することを許可します。



 a| 
`showsnapshot`
 a| 
このプロパティは、スナップショットをクライアントが表示および移動できることを指定します。



 a| 
`changenotify`
 a| 
このプロパティは、共有がChange Notifyリクエストをサポートすることを指定します。SVM上の共有の場合、これはデフォルトの初期プロパティです。



 a| 
`attributecache`
 a| 
このプロパティは、SMB 共有上のファイル属性キャッシュを有効にし、属性へのアクセスを高速化します。デフォルトでは、属性キャッシュは無効になっています。このプロパティは、SMB 1.0 経由で共有に接続するクライアントがいる場合にのみ有効にしてください。クライアントが SMB 2.x または SMB 3.0 経由で共有に接続している場合、この共有プロパティは適用されません。



 a| 
`continuously-available`
 a| 
SMBクライアントが永続的な方法でファイルを開くことを許可します。この方法で開いたファイルは、フェイルオーバーやギブバックなど、システムを停止させるイベントから保護されます。



 a| 
`branchcache`
 a| 
このプロパティは、共有内のファイルに対するBranchCacheハッシュの要求をクライアに許可することを指定します。このオプションは、CIFSBranchCache設定で動作モードとして「`per-share`」を指定した場合にのみ有効です。



 a| 
`access-based-enumeration`
 a| 
このプロパティは、この共有で _Access Based Enumeration_ （ABE）が有効になっていることを指定します。ABEでフィルタリングされた共有フォルダは、個々のユーザーのアクセス権に基づいてユーザーに表示されます。これにより、ユーザーがアクセス権を持たないフォルダやその他の共有リソースは表示されなくなります。



 a| 
`namespace-caching`
 a| 
このプロパティは、この共有に接続するSMBクライアントがCIFSサーバーから返されるディレクトリ列挙結果をキャッシュできることを指定します。これにより、パフォーマンスが向上します。デフォルトでは、SMB 1クライアントはディレクトリ列挙結果をキャッシュしません。SMB 2およびSMB 3クライアントはデフォルトでディレクトリ列挙結果をキャッシュするため、この共有プロパティを指定すると、SMB 1クライアント接続にのみパフォーマンス上のメリットがもたらされます。



 a| 
`encrypt-data`
 a| 
このプロパティは、この共有にアクセスするときに SMB 暗号化を使用する必要があることを指定します。SMB データへのアクセス時に暗号化をサポートしていない SMB クライアントは、この共有にアクセスできません。

|===


[[add-share-properties-on-existing-ontap-smb-shares]]
== 既存の ONTAP SMB 共有に共有プロパティを追加する

既存のSMB共有は、共有プロパティを追加することでカスタマイズできます。これは、環境における変化する要件に合わせて共有構成を変更したい場合に役立ちます。

.開始する前に
プロパティを変更する共有が存在している必要があります。

.タスク概要
* 複数の共有プロパティを追加するには、カンマで区切って指定します。
* 以前に指定した共有プロパティは有効なままです。
+
新たに追加したプロパティは、共有プロパティの既存のリストに追加されます。

* 共有にすでに適用されている共有プロパティに新しい値を指定した場合は、元の値が新たに指定した値に置き換えられます。
*  `vserver cifs share properties add`コマンドを使用して共有プロパティを削除することはできません。
+
 `vserver cifs share properties remove`コマンドを使用して共有プロパティを削除できます。



.手順
. 共有プロパティを追加：
+
[source, cli]
----
vserver cifs share properties add -vserver <SVM_name> -share-name <share_name> -share-properties <properties>,...
----
. 共有プロパティの設定を確認します。
+
[source, cli]
----
vserver cifs share show -vserver vserver_name -share-name share_name
----


.例
次のコマンドは、SVM vs1 上の「`share1`」という名前の共有に `showsnapshot`共有プロパティを追加します：

[listing]
----
cluster1::> vserver cifs share properties add -vserver vs1 -share-name share1 -share-properties showsnapshot

cluster1::> vserver cifs share show -vserver vs1
Vserver    Share   Path      Properties   Comment    ACL
---------  ------  --------  ----------   --------   -----------
vs1        share1  /share1   oplocks      -          Everyone / Full Control
                             browsable
                             changenotify
                             showsnapshot
----


[[remove-share-properties-on-existing-ontap-smb-shares]]
== 既存の ONTAP SMB 共有の共有プロパティを削除する

既存のSMB共有は、共有プロパティを削除することでカスタマイズできます。これは、環境における変化する要件に合わせて共有構成を変更したい場合に役立ちます。

.タスク概要
* 複数の共有プロパティを削除するには、カンマで区切って指定します。
* 以前に指定した共有プロパティは、削除しないかぎり有効なままです。


.手順
. 共有プロパティを削除する：
+
[source, cli]
----
vserver cifs share properties remove -vserver <SVM_name> -share-name <share_name> -share-properties <properties>,...
----
. 共有プロパティの設定を確認します。
+
[source, cli]
----
vserver cifs share show -vserver <SVM_name> -share-name <share_name>
----


.例
次のコマンドは、SVM vs1 上の「`share2`」という名前の共有から `browsable`共有プロパティを削除します：

[listing]
----
cluster1::> vserver cifs share properties remove -vserver vs1 -share-name share2 -share-properties browsable

cluster1::> vserver cifs share show -vserver vs1
Vserver    Share   Path      Properties   Comment    ACL
---------  ------  --------  ----------   --------   -----------
vs1        share2  /share2   oplocks      -          Everyone / Full Control
                             changenotify
----
.関連情報
xref:commands-manage-shares-reference.adoc[共有を管理するためのコマンド]
