---
permalink: smb-admin/add-remove-share-properties-existing-share-task.html 
sidebar: sidebar 
keywords: customize, exist, smb, share, add, remove, removing, properties, useful, configuration, changing, change, requirement, environment, add or remove share properties on an existing smb share 
summary: 共有プロパティを追加または削除することで、既存のSMB共有をカスタマイズできます。この方法は、環境内での要件の変化に合わせて共有の設定を変更する場合に役立ちます。 
---
= 既存のONTAP SMB共有の共有プロパティを追加または削除する
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
共有プロパティを追加または削除することで、既存のSMB共有をカスタマイズできます。この方法は、環境内での要件の変化に合わせて共有の設定を変更する場合に役立ちます。

.開始する前に
プロパティを変更する共有が存在している必要があります。

.タスク概要
共有プロパティの追加に関するガイドラインは次のとおりです。

* 複数の共有プロパティを追加するには、カンマで区切って指定します。
* 以前に指定した共有プロパティは有効なままです。
+
新たに追加したプロパティは、共有プロパティの既存のリストに追加されます。

* 共有にすでに適用されている共有プロパティに新しい値を指定した場合は、元の値が新たに指定した値に置き換えられます。
*  `vserver cifs share properties add`コマンドを使用して共有プロパティを削除することはできません。
+
 `vserver cifs share properties remove`コマンドを使用して共有プロパティを削除できます。



共有プロパティの削除に関するガイドラインは次のとおりです。

* 複数の共有プロパティを削除するには、カンマで区切って指定します。
* 以前に指定した共有プロパティは、削除しないかぎり有効なままです。


.手順
. 該当するコマンドを入力します。
+
|===
| 状況 | コマンドを入力してください... 


 a| 
共有プロパティを追加する
 a| 
`+vserver cifs share properties add -vserver _vserver_name_ -share-name _share_name_ -share-properties _properties_,...+`



 a| 
共有プロパティを削除する
 a| 
`+vserver cifs share properties remove -vserver _vserver_name_ -share-name _share_name_ -share-properties _properties_,...+`

|===
. 共有プロパティの設定を確認します： `vserver cifs share show -vserver vserver_name -share-name share_name`


.例
次のコマンドは、SVM vs1 上の「`share1`」という名前の共有に `showsnapshot`共有プロパティを追加します：

[listing]
----
cluster1::> vserver cifs share properties add -vserver vs1 -share-name share1 -share-properties showsnapshot

cluster1::> vserver cifs share show -vserver vs1
Vserver    Share   Path      Properties   Comment    ACL
---------  ------  --------  ----------   --------   -----------
vs1        share1  /share1   oplocks      -          Everyone / Full Control
                             browsable
                             changenotify
                             showsnapshot
----
次のコマンドは、SVM vs1 上の「`share2`」という名前の共有から `browsable`共有プロパティを削除します：

[listing]
----
cluster1::> vserver cifs share properties remove -vserver vs1 -share-name share2 -share-properties browsable

cluster1::> vserver cifs share show -vserver vs1
Vserver    Share   Path      Properties   Comment    ACL
---------  ------  --------  ----------   --------   -----------
vs1        share2  /share2   oplocks      -          Everyone / Full Control
                             changenotify
----
.関連情報
xref:commands-manage-shares-reference.adoc[共有を管理するためのコマンド]
