---
permalink: smb-admin/add-list-netbios-aliases-server-task.html 
sidebar: sidebar 
keywords: smb, client, connect, cifs, server, alias, create, list, netbios 
summary: エイリアスを使用して SMB クライアントを CIFS サーバに接続する場合、 NetBIOS エイリアスのリストを作成するか、 NetBIOS エイリアスの既存のリストに NetBIOS エイリアスを追加します。 
---
= SMBサーバにNetBIOSエイリアスのリストを追加する
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
エイリアスを使用してSMBサーバに接続できるようにするには、NetBIOSエイリアスのリストを作成するか、既存のNetBIOSエイリアスのリストにNetBIOSエイリアスを追加します。

.このタスクについて
* NetBIOS エイリアス名は 15 文字以内にする必要があります。
* SMBサーバには最大200個のNetBIOSエイリアスを設定できます。
* 次の文字は使用できません。
+
@#*（）=+[]|；："、<>\/？



.手順
. NetBIOSエイリアスを追加します。+
`vserver cifs add-netbios-aliases -vserver _vserver_name_ -netbios-aliases _NetBIOS_alias_,...`
+
`vserver cifs add-netbios-aliases -vserver vs1 -netbios-aliases alias_1,alias_2,alias_3`

+
** 1 つ以上の NetBIOS エイリアスをカンマで区切って指定します。
** 指定した NetBIOS エイリアスが既存のリストに追加されます。
** 現在のリストが空である場合、 NetBIOS エイリアスの新しいリストが作成されます。


. NetBIOSエイリアスが正しく追加されたことを確認します。 `vserver cifs show -vserver vserver_name -display-netbios-aliases`
+
`vserver cifs show -vserver vs1 -display-netbios-aliases`

+
[listing]
----
Vserver: vs1

         Server Name: CIFS_SERVER
         NetBIOS Aliases: ALIAS_1, ALIAS_2, ALIAS_3
----


.関連情報
xref:remove-netbios-aliases-from-list-task.adoc[NetBIOS エイリアスリストからの NetBIOS エイリアスの削除]

xref:display-list-netbios-aliases-task.adoc[CIFS サーバの NetBIOS エイリアスのリストを表示する]
