---
permalink: smb-admin/assign-privileges-concept.html 
sidebar: sidebar 
keywords: assign, privilege, direct, local, user, domain, group, capabilities, capability, how to assign privileges, supported privileges, list of supported privileges, smb 
summary: ローカル ユーザまたはドメイン ユーザに権限を直接割り当てることができます。または、ユーザに付与したい権限と同じ権限が割り当てられているローカル グループにユーザを割り当てることもできます。 
---
= ONTAP SMB権限について学ぶ
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
ローカル ユーザまたはドメイン ユーザに権限を直接割り当てることができます。または、ユーザに付与したい権限と同じ権限が割り当てられているローカル グループにユーザを割り当てることもできます。

* 作成したグループに一連の権限を割り当てることができます。
+
その後、ユーザに付与したい権限が割り当てられているグループにユーザを追加します。

* ユーザに付与したい権限と同じデフォルトの権限が割り当てられている事前定義のグループに、ローカル ユーザとドメイン ユーザを割り当てることもできます。


.関連情報
* xref:manage-local-privileges.adoc[ローカルユーザまたはドメインユーザまたはグループに権限を追加、削除、またはリセットする]
* xref:configure-bypass-traverse-checking-concept.adoc[バイパス トラバース チェックの設定について学ぶ]




== サポートされているONTAP SMB権限のリスト

ONTAPには、一連のサポートされる権限が事前に定義されています。特定の事前定義されたローカル グループには、これらの権限の一部がデフォルトで設定されています。事前定義グループの権限は追加、削除できます。また、新規のローカル ユーザまたはローカル グループを作成して、そのグループや、既存のドメイン ユーザおよびグループに権限を追加することもできます。

次の表に、Storage Virtual Machine（SVM）でサポートされる権限の一覧と、その権限が割り当てられている事前定義グループを示します。

|===
| 権限名 | デフォルトのセキュリティ設定 | 概要 


 a| 
`SeTcbPrivilege`
 a| 
なし
 a| 
オペレーティング システムの一部として動作する



 a| 
`SeBackupPrivilege`
 a| 
`BUILTIN\Administrators`, `BUILTIN\Backup Operators`
 a| 
ACL を上書きしてファイルとディレクトリをバックアップする



 a| 
`SeRestorePrivilege`
 a| 
`BUILTIN\Administrators`, `BUILTIN\Backup Operators`
 a| 
ファイルとディレクトリを復元し、ACLをすべて上書きします。有効なユーザまたはグループのSIDをファイル所有者として設定します



 a| 
`SeTakeOwnershipPrivilege`
 a| 
`BUILTIN\Administrators`
 a| 
ファイルなどのオブジェクトの所有権を取得します。



 a| 
`SeSecurityPrivilege`
 a| 
`BUILTIN\Administrators`
 a| 
監査の管理

セキュリティ ログの表示、ダンプ、消去など。



 a| 
`SeChangeNotifyPrivilege`
 a| 
`BUILTIN\Administrators`、 `BUILTIN\Backup Operators`、 `BUILTIN\Power Users`、 `BUILTIN\Users`、 `Everyone`
 a| 
トラバース チェックのバイパス

この権限を持つユーザは、フォルダ、シンボリックリンク、ジャンクションを経由するためのトラバース（x）権限は必要ありません。

|===
.関連情報
* xref:assign-privileges-concept.adoc[権限の割り当てについて]
* xref:configure-bypass-traverse-checking-concept.adoc[バイパス トラバース チェックの設定について学ぶ]

