---
permalink: smb-admin/branchcache-cache-share-content-branch-office-concept.html 
sidebar: sidebar 
keywords: branchcache, develop, microsoft, enable, caching, cache, content, computer, local, request, client, ontap, implementation, reduce, wide-area, network, wan, utilization, response, svm, smb, use branchcache to cache smb share content at a branch office 
summary: BranchCacheは、要求元のクライアントのローカルコンピュータにコンテンツをキャッシュできるようにするためにMicrosoftが開発したものです。ONTAPにBranchCacheを実装すると、Storage Virtual Machine（SVM）に格納されたコンテンツにSMBを使用してブランチオフィスのユーザがアクセスする際に、広域ネットワーク（WAN）の使用量を抑え、アクセス応答時間を短縮できます。 
---
= BranchCache を使用してブランチ オフィスで ONTAP SMB 共有コンテンツをキャッシュする方法について説明します。
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
BranchCacheは、要求元のクライアントのローカルコンピュータにコンテンツをキャッシュできるようにするためにMicrosoftが開発したものです。ONTAPにBranchCacheを実装すると、Storage Virtual Machine（SVM）に格納されたコンテンツにSMBを使用してブランチオフィスのユーザがアクセスする際に、広域ネットワーク（WAN）の使用量を抑え、アクセス応答時間を短縮できます。

BranchCacheを設定すると、Windows BranchCacheクライアントはまずSVMのコンテンツを取得し、次にそのコンテンツをブランチオフィスのコンピュータにキャッシュします。ブランチオフィスの別のBranchCache対応クライアントが同じコンテンツを要求すると、SVMは最初に要求元ユーザの認証と許可を行います。次にSVMは、キャッシュされたコンテンツが最新のものであるかどうかを確認し、最新のものである場合はそのコンテンツに関するメタデータをクライアントに送信します。クライアントは、そのメタデータを使用して、ローカルのキャッシュから直接コンテンツを取得します。

.関連情報
xref:offline-files-allow-caching-concept.adoc[オフラインファイルを使用して、オフラインで使用するためにファイルをキャッシュできるようにする方法について学習します。]
