---
permalink: smb-admin/builtin-groups-default-privileges-reference.html 
sidebar: sidebar 
keywords: assign, membership, local, user, domain, predefined, builtin, ontap, predefined builtin groups and default privileges 
summary: ローカルユーザまたはドメインユーザのメンバーシップを、ONTAPの事前定義された一連のBUILTINグループに割り当てることができます。事前定義グループには事前定義Privilegesが割り当てられています。 
---
= 事前定義のBUILTINグループとデフォルトのPrivileges
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
ローカルユーザまたはドメインユーザのメンバーシップを、ONTAPの事前定義された一連のBUILTINグループに割り当てることができます。事前定義グループには事前定義Privilegesが割り当てられています。

次の表に、事前定義グループを示します。

|===
| 事前定義の BUILTIN グループ | デフォルトの権限 


 a| 
``BUILTIN\Administrators``RID 544

最初に作成されたときに、RID 500のローカル `Administrator`アカウントが自動的にこのグループのメンバーになります。Storage Virtual Machine（SVM）がドメインに参加すると、 `domain\Domain Admins`グループがグループに追加されます。SVMがドメインから削除されると `domain\Domain Admins`、グループはグループから削除されます。
 a| 
* `SeBackupPrivilege`
* `SeRestorePrivilege`
* `SeSecurityPrivilege`
* `SeTakeOwnershipPrivilege`
* `SeChangeNotifyPrivilege`




 a| 
``BUILTIN\Power Users``RID 547

このグループには、最初に作成された時点ではメンバーがありません。このグループのメンバーには、次のような特徴があります。

* ローカルユーザとローカルグループを作成および管理できます。
* 自分自身や他のオブジェクトをグループに追加することはできません `BUILTIN\Administrators`。

 a| 
`SeChangeNotifyPrivilege`



 a| 
``BUILTIN\Backup Operators``RID 551

このグループには、最初に作成された時点ではメンバーがありません。このグループのメンバーは、バックアップ目的で開いたファイルやフォルダの読み取りおよび書き込み権限を上書きできます。
 a| 
* `SeBackupPrivilege`
* `SeRestorePrivilege`
* `SeChangeNotifyPrivilege`




 a| 
``BUILTIN\Users``RID 545

最初に作成された時点では、このグループには（暗黙的な特殊グループ以外に）メンバーはありませ `Authenticated Users`ん。SVMがドメインに参加すると、 `domain\Domain Users`グループがこのグループに追加されます。SVMがドメインから削除されると、 `domain\Domain Users`グループはこのグループから削除されます。
 a| 
`SeChangeNotifyPrivilege`



 a| 
``Everyone``SID S-1-1-0

このグループには、ゲストを含むすべてのユーザが含まれます（匿名ユーザは含まれません）。このグループは、暗黙のメンバーシップを持つ暗黙のグループです。
 a| 
`SeChangeNotifyPrivilege`

|===
.関連情報
xref:builtin-groups-local-administrator-account-concept.adoc[BUILTINグループとローカル管理者アカウントの使用に関するガイドライン]

xref:list-supported-privileges-reference.adoc[サポートされるPrivilegesのリスト]

xref:configure-bypass-traverse-checking-concept.adoc[トラバースチェックのバイパスの設定]
