---
permalink: smb-admin/case-sensitivity-file-directory-multiprotocol-concept.html 
sidebar: sidebar 
keywords: file, directory, name, case-sensitive, nfs, client, case-preserving, preserve, implication, multiprotocol, environment, action, case-sensitivity of file and directory names in a multiprotocol environment 
summary: ファイル名とディレクトリ名について、 NFS クライアントでは大文字と小文字が区別されますが、 SMB クライアントでは大文字と小文字が区別されず、同じ文字として扱われます。この違いがマルチプロトコル環境に及ぼす影響と、 SMB 共有の作成時にパスを指定するときや、共有内のデータにアクセスするときにどのような対処が必要になるかを理解しておく必要があります。 
---
= マルチプロトコル環境でのファイル名とディレクトリ名の大文字と小文字の区別
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
ファイル名とディレクトリ名について、 NFS クライアントでは大文字と小文字が区別されますが、 SMB クライアントでは大文字と小文字が区別されず、同じ文字として扱われます。この違いがマルチプロトコル環境に及ぼす影響と、 SMB 共有の作成時にパスを指定するときや、共有内のデータにアクセスするときにどのような対処が必要になるかを理解しておく必要があります。

SMBクライアントがという名前のディレクトリを作成する場合 `testdir`SMBクライアントとNFSクライアントのどちらでも、ファイル名はと表示されます `testdir`。ただし、SMBユーザがあとでディレクトリ名を作成しようとした場合 `TESTDIR`を指定することはできません。SMBクライアントでは、その名前がすでに存在しているとみなされます。NFSユーザがあとでという名前のディレクトリを作成する場合 `TESTDIR`では、NFSクライアントとSMBクライアントで表示されるディレクトリ名は次のように異なります。

* NFSクライアントでは、両方のディレクトリ名が作成したとおりに表示されます（例：） `testdir` および `TESTDIR`ディレクトリ名では大文字と小文字が区別されるためです。
* SMB クライアントでは、 2 つのディレクトリを区別するために 8.3 形式の名前が使用されます。1 つのディレクトリにはベースファイル名が付けられます。追加のディレクトリには 8.3 形式のファイル名が割り当てられます。
+
** SMBクライアントでは、が表示されます `testdir` および `TESTDI~1`。
** ONTAP によってが作成されます `TESTDI~1` 2つのディレクトリを区別するディレクトリ名。
+
この場合、 Storage Virtual Machine （ SVM ）での共有の作成時または変更時に共有パスを指定するときは、 8.3 形式の名前を使用する必要があります。





ファイルについても、SMBクライアントでが作成された場合と同様です `test.txt`SMBクライアントとNFSクライアントのどちらでも、ファイル名はと表示されます `text.txt`。ただし、SMBユーザがあとでを作成しようとした場合 `Test.txt`を指定することはできません。SMBクライアントでは、その名前がすでに存在しているとみなされます。NFSユーザがあとでという名前のファイルを作成した場合 `Test.txt`では、NFSクライアントとSMBクライアントで表示されるファイル名は次のように異なります。

* NFSクライアントでは、両方のファイル名が作成されたとおりに表示され、 `test.txt` および `Test.txt`ファイル名では大文字と小文字が区別されるためです。
* SMB クライアントでは、 2 つのファイルを区別するために 8.3 形式の名前が使用されます。1 つのファイルにはベースファイル名が付けられます。追加のファイルには 8.3 形式のファイル名が割り当てられます。
+
** SMBクライアントでは、が表示されます `test.txt` および `TEST~1.TXT`。
** ONTAP によってが作成されます `TEST~1.TXT` 2つのファイルを区別するためのファイル名。




[NOTE]
====
SVM cifs character-mapping コマンドを使用して文字マッピングを有効または変更した場合、通常、大文字と小文字は区別されない Windows ルックアップは大文字と小文字が区別されます。

====