---
permalink: smb-admin/client-signing-policies-communication-concept.html 
sidebar: sidebar 
keywords: addition, cifs, server, smb, sign, security, windows, client, control, digital, communication, business, requirement, how smb signing policies affect communication with a cifs server 
summary: CIFS サーバの SMB 署名セキュリティ設定に加えて、クライアントと CIFS サーバ間の通信のデジタル署名を制御する Windows クライアント上の SMB 署名ポリシーが 2 つあります。ビジネス要件に合わせて設定を行うことができます。 
---
= SMB署名ポリシーがCIFSサーバとの通信に与える影響
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
CIFS サーバの SMB 署名セキュリティ設定に加えて、クライアントと CIFS サーバ間の通信のデジタル署名を制御する Windows クライアント上の SMB 署名ポリシーが 2 つあります。ビジネス要件に合わせて設定を行うことができます。

クライアント SMB ポリシーは、 Microsoft 管理コンソール（ MMC ）または Active Directory の GPO を使用して設定した Windows ローカルセキュリティポリシー設定で制御されます。クライアントの SMB 署名とセキュリティ問題の詳細については、 Microsoft Windows のマニュアルを参照してください。

ここでは、 Microsoft クライアントの 2 つの SMB 署名ポリシーについて説明します。

* `Microsoft network client: Digitally sign communications (if server agrees)`
+
この設定は、クライアントのSMB署名機能を有効にするかどうかを制御します。デフォルトでは有効になっています。この設定がクライアントで無効になっている場合、クライアントのCIFSサーバとの通信は、CIFSサーバのSMB署名の設定によって異なります。

* `Microsoft network client: Digitally sign communications (always)`
+
この設定は、クライアントがサーバとの通信に SMB 署名を必要とするかどうかを制御します。デフォルトでは無効になっています。この設定がクライアントで無効になっている場合、SMB署名の動作は、のポリシー設定とCIFSサーバの設定に基づき `Microsoft network client: Digitally sign communications (if server agrees)`ます。

+
[NOTE]
====
ご使用の環境に、 SMB 署名を必要とするように設定された Windows クライアントが含まれる場合、 CIFS サーバ上の SMB 署名を有効にする必要があります。有効にしないと、 CIFS サーバはこれらのシステムにデータを提供できません。

====


クライアントとCIFSサーバのSMB署名設定の有効な結果は、SMBセッションでSMB 1.0が使用されるかSMB 2.x以降が使用されるかによって異なります。

次の表に、セッションでSMB 1.0が使用される場合の有効なSMB署名の動作を示します。

|===
| クライアント | ONTAP -- 署名は不要 | ONTAP -- 署名が必要 


 a| 
署名は無効になっており、不要です
 a| 
署名されません
 a| 
署名済み



 a| 
署名が有効になっており、不要である
 a| 
署名されません
 a| 
署名済み



 a| 
署名が無効になっており、必要です
 a| 
署名済み
 a| 
署名済み



 a| 
署名が有効になっており、必要です
 a| 
署名済み
 a| 
署名済み

|===
[NOTE]
====
古いバージョンのWindowsのSMB 1クライアントや一部のWindows以外のSMB 1クライアントでは、署名がクライアントでは無効になっていてCIFSサーバでは必要な場合、接続に失敗することがあります。

====
次の表に、セッションでSMB 2.xまたはSMB 3.0が使用される場合の有効なSMB署名の動作を示します。

[NOTE]
====
SMB 2.x クライアントと SMB 3.0 クライアントでは、 SMB 署名は常に有効になります。無効にすることはできません。

====
|===
| クライアント | ONTAP -- 署名は不要 | ONTAP -- 署名が必要 


 a| 
署名は不要です
 a| 
署名されません
 a| 
署名済み



 a| 
署名が必要です
 a| 
署名済み
 a| 
署名済み

|===
次の表に、 Microsoft クライアントおよびサーバの SMB 署名のデフォルト動作を示します。

|===
| プロトコル | ハッシュアルゴリズム | 有効 / 無効を切り替えられます | 必須 / 不要 | クライアントのデフォルト | サーバのデフォルト | DC のデフォルト 


 a| 
SMB 1.0
 a| 
MD5
 a| 
〇
 a| 
〇
 a| 
有効（不要）
 a| 
無効（不要）
 a| 
必須



 a| 
SMB 2.x
 a| 
HMAC SHA-256
 a| 
いいえ
 a| 
〇
 a| 
不要
 a| 
不要
 a| 
必須



 a| 
SMB 3.0
 a| 
AES-CMAC ：
 a| 
いいえ
 a| 
〇
 a| 
不要
 a| 
不要
 a| 
必須

|===
[NOTE]
====
Microsoftでは、または `Digitally sign communications (if server agrees)`グループポリシー設定の使用を推奨していません `Digitally sign communications (if client agrees)`。Microsoftでは、レジストリ設定の使用も推奨していません `EnableSecuritySignature`。これらのオプションはSMB 1の動作にのみ影響し、グループポリシー設定または `RequireSecuritySignature`レジストリ設定に置き換えることができます。 `Digitally sign communications (always)`詳細については、Microsoftのブログを参照してください。http://blogs.technet.com/b/josebda/archive/2010/12/01/the-basics-of-smb-signing-covering-both-smb1-and-smb2.aspx[The SMB署名の基礎（SMB1とSMB2の両方をカバー）]

====