---
permalink: smb-admin/command-options-limit-client-resource-concept.html 
sidebar: sidebar 
keywords: option, vserver, cifs, modify, command, enable, control, resource, consumption, windows, client, bound, notify, request, command options to limit excessive windows client resource consumption 
summary: vserver cifs options modify コマンドのオプションを使用すると、 Windows クライアントのリソース消費を制御できます。ファイルオープン、セッションオープン、変更通知要求が異常に多い場合など、正常な範囲を超えてリソースを消費しているクライアントがある場合に便利です。 
---
= Windows クライアントの過剰なリソース消費を制限するコマンドオプション
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
オプションをに設定します `vserver cifs options modify` コマンドを使用すると、Windowsクライアントのリソース消費を制御できます。ファイルオープン、セッションオープン、変更通知要求が異常に多い場合など、正常な範囲を超えてリソースを消費しているクライアントがある場合に便利です。

には次のオプションがあります `vserver cifs options modify` Windowsクライアントのリソース消費を制御するコマンドが追加されました。これらのオプションの最大値を超えると、要求は拒否され、 EMS メッセージが送信されます。これらのオプションで設定された上限の 80% に達したときにも EMS 警告メッセージが送信されます。

* `-max-opens-same-file-per-tree`
+
CIFS ツリーあたりの同じファイルの最大オープン数

* `-max-same-user-sessions-per-connection`
+
同じユーザが接続ごとに開いたセッションの最大数

* `-max-same-tree-connect-per-session`
+
同じ共有に対するセッションあたりの最大ツリー接続数

* `-max-watches-set-per-tree`
+
ツリーごとに確立されるウォッチの最大数（別名 _change notifier_）



デフォルトの制限および現在の設定を表示する方法については、マニュアルページを参照してください。

ONTAP 9.4 以降では、 SMB バージョン 2 以降を実行しているサーバで、クライアントからサーバに SMB 接続で送信できる未処理要求（ _SMB クレジット _ ）の数を制限することができます。SMB クレジットの管理はクライアント側で開始され、サーバ側で制御されます。

SMB接続で付与できる未処理要求の最大数は、で制御されます `-max-credits` オプションこのオプションのデフォルト値は 128 です。
