---
permalink: smb-admin/commands-oplocks-volumes-qtrees-reference.html 
sidebar: sidebar 
keywords: oplock, client, lock, file, cache, performance, operation, qtree, command, enabling, enable, disabling, disable, volume, commands for enabling or disabling oplocks on volumes and qtrees 
summary: oplockを使用すると、クライアントによりファイルがロックされてコンテンツがローカルにキャッシュされるため、ファイル操作のパフォーマンスを向上できます。ボリュームやqtreeのoplockを有効または無効にするコマンドについて説明します。また、いつボリュームおよびqtreeでoplockを有効化または無効化できるかについても理解しておく必要があります。 
---
= SMBボリュームおよびqtreeでoplockを有効または無効にするONTAPコマンド
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
oplockを使用すると、クライアントによりファイルがロックされてコンテンツがローカルにキャッシュされるため、ファイル操作のパフォーマンスを向上できます。ボリュームやqtreeのoplockを有効または無効にするコマンドについて説明します。また、いつボリュームおよびqtreeでoplockを有効化または無効化できるかについても理解しておく必要があります。

* ボリュームではデフォルトでoplockが有効になっています。
* ボリュームを作成する際にoplockを無効化することはできません。
* 既存のSVMのボリュームでは、oplockをいつでも有効または無効にすることができます。
* SVMのqtreeではoplockを有効にできます。
+
oplockモードは、すべてのボリュームにあるデフォルトのqtree（qtree ID 0）のプロパティで指定します。qtreeの作成時にoplock設定を指定しない場合、qtreeは親ボリュームのoplock設定（デフォルトでは有効）を継承します。ただし、新しいqtreeにoplock設定を指定した場合、ボリュームのoplock設定よりも優先されます。



|===
| 状況 | 使用するコマンド 


 a| 
ボリュームまたはqtreeのoplockを有効にする
 a| 
`volume qtree oplocks` と  `-oplock-mode` パラメータを  `enable` に設定



 a| 
ボリュームまたはqtreeのoplockを無効にする
 a| 
`volume qtree oplocks` と  `-oplock-mode` パラメータを  `disable` に設定

|===
.関連情報
xref:monitor-oplock-status-task.adoc[oplockステータスの監視]
