---
permalink: smb-admin/command-options-limit-client-resource-concept.html 
sidebar: sidebar 
keywords: option, vserver, cifs, modify, command, enable, control, resource, consumption, windows, client, bound, notify, request, command options to limit excessive windows client resource consumption 
summary: vserver cifs options modify コマンドのオプションを使用すると、 Windows クライアントのリソース消費を制御できます。これは、ファイルオープン、セッションオープン、Change Notify要求が異常に多い場合など、通常の範囲を超えてリソースを消費するクライアントがある場合に役立ちます。 
---
= Windowsクライアントの過剰なリソース消費を制限するONTAPコマンドオプション
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
コマンドのオプションを `vserver cifs options modify`使用すると、Windowsクライアントのリソース消費を制御できます。これは、ファイルオープン、セッションオープン、Change Notify要求が異常に多い場合など、通常の範囲を超えてリソースを消費するクライアントがある場合に役立ちます。

Windowsクライアントのリソース消費を制御するために、コマンドに次のオプション `vserver cifs options modify`が追加されました。いずれかのオプションの最大値を超えると、要求は拒否され、EMSメッセージが送信されます。これらのオプションに設定されている制限の80%に達したときにも、EMS警告メッセージが送信されます。

* `-max-opens-same-file-per-tree`
+
CIFSツリーあたりの同一ファイルに対する最大オープン数

* `-max-same-user-sessions-per-connection`
+
接続ごとに同じユーザが開いたセッションの最大数

* `-max-same-tree-connect-per-session`
+
同じ共有に対するセッションあたりの最大ツリー接続数

* `-max-watches-set-per-tree`
+
ツリーごとに確立されるウォッチの最大数（別名 _change notifier_）



の詳細については `vserver cifs options modify`、をlink:https://docs.netapp.com/us-en/ontap-cli/vserver-cifs-options-modify.html["ONTAPコマンド リファレンス"^]参照してください。

ONTAP 9.4 以降では、 SMB バージョン 2 以降を実行しているサーバで、クライアントからサーバに SMB 接続で送信できる未処理要求（ _SMB クレジット _ ）の数を制限することができます。SMBクレジットの管理はクライアントによって開始され、サーバによって制御されます。

SMB接続で許可できる未処理要求の最大数は、オプションで制御され `-max-credits`ます。このオプションのデフォルト値は128です。
