---
permalink: smb-admin/commands-manage-servers-reference.html 
sidebar: sidebar 
keywords: command, creating, create, display, modify, stop, start, deleting, delete 
summary: SMBサーバを作成、表示、変更、停止、開始、削除するコマンドについて説明します。また、サーバのリセットと再検出、マシン アカウント パスワードの変更またはリセット、マシン アカウント パスワードのスケジュール変更、NetBIOSエイリアスの追加や削除を行うコマンドもあります。 
---
= SMBサーバーを管理するためのONTAPコマンド
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
SMBサーバを作成、表示、変更、停止、開始、削除するコマンドについて説明します。また、サーバのリセットと再検出、マシン アカウント パスワードの変更またはリセット、マシン アカウント パスワードのスケジュール変更、NetBIOSエイリアスの追加や削除を行うコマンドもあります。

|===


| 状況 | 使用するコマンド 


 a| 
SMBサーバーを作成する
 a| 
`vserver cifs create`



 a| 
SMBサーバに関する情報を表示する
 a| 
`vserver cifs show`



 a| 
SMBサーバを変更する
 a| 
`vserver cifs modify`



 a| 
SMBサーバを別のドメインに移動する
 a| 
`vserver cifs modify`



 a| 
SMBサーバを停止する
 a| 
`vserver cifs stop`



 a| 
SMBサーバを起動する
 a| 
`vserver cifs start`



 a| 
SMBサーバを削除する
 a| 
`vserver cifs delete`



 a| 
SMBサーバ用にサーバをリセットおよび再検出する
 a| 
`vserver cifs domain discovered-servers reset-servers`



 a| 
SMBサーバのマシン アカウント パスワードを変更する
 a| 
`vserver cifs domain password change`



 a| 
SMBサーバのマシン アカウント パスワードをリセットする
 a| 
`vserver cifs domain password change`



 a| 
SMBサーバのマシン アカウントの自動パスワード変更をスケジュールする
 a| 
`vserver cifs domain password schedule modify`



 a| 
SMBサーバ用のNetBIOSエイリアスを追加する
 a| 
`vserver cifs add-netbios-aliases`



 a| 
SMBサーバ用のNetBIOSエイリアスを削除する
 a| 
`vserver cifs remove-netbios-aliases`

|===
 `vserver cifs`の詳細については、link:https://docs.netapp.com/us-en/ontap-cli/search.html?q=vserver+cifs["ONTAPコマンド リファレンス"^]をご覧ください。

.関連情報
link:local-users-groups-when-deleting-servers-concept.html["SMBサーバを削除したときにローカル ユーザとローカル グループが受ける影響"]
