---
permalink: smb-admin/configure-branchcache-enabled-shares-concept.html 
sidebar: sidebar 
keywords: configure, branchcache, smb server, office, enable, smb, share, content, client, configure branchache-enabled smb shares 
summary: SMBサーバとブランチ オフィスでBranchCacheを設定したら、ブランチ オフィスのクライアントによるコンテンツのキャッシュを許可するSMB共有でBranchCacheを有効にすることができます。 
---
= BranchCache対応ONTAP SMB共有の設定について学ぶ
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
SMBサーバとブランチ オフィスでBranchCacheを設定したら、ブランチ オフィスのクライアントによるコンテンツのキャッシュを許可するSMB共有でBranchCacheを有効にすることができます。

BranchCacheキャッシュは、SMBサーバ上のすべてのSMB共有で有効にするか、共有ごとに有効にすることができます。

* 共有ごとにBranchCacheを有効にする場合は、共有の作成時にBranchCacheを有効にするか、既存の共有を変更することで有効にできます。
+
既存の SMB 共有でキャッシュを有効にすると、ONTAP はその共有でBranchCacheを有効にするとすぐにハッシュを計算し、コンテンツを要求しているクライアントにメタデータを送信し始めます。

* 共有への既存の SMB 接続を持つクライアントは、その共有でBranchCacheが後で有効になっても、BranchCacheサポートを受けられません。
+
ONTAPは、SMBセッションのセットアップ時に共有のBranchCacheサポートをアドバタイズします。BranchCacheが有効になったときに既にセッションを確立しているクライアントは、この共有のキャッシュされたコンテンツを使用するために切断してから再接続する必要があります。



[NOTE]
====
SMB共有でBranchCacheがその後無効になった場合、ONTAPは要求元のクライアントへのメタデータの送信を停止します。データを必要とするクライアントは、コンテンツサーバ（SMBサーバ）から直接データを取得します。

====