---
permalink: smb-admin/configure-unix-symbolic-link-support-shares-task.html 
sidebar: sidebar 
keywords: configure, unix, symbol, link, support, smb, share, share-property, setting, create, modify, exist, configure unix symbolic link support, on smb shares 
summary: SMB共有の作成時に、または既存のSMB共有の変更によっていつでも、シンボリックリンクの共有プロパティ設定を指定することで、SMB共有でUNIXシンボリックリンクのサポートを設定できます。UNIXシンボリックリンクのサポートはデフォルトで有効になっています。共有でUNIXシンボリックリンクのサポートを無効にすることもできます。 
---
= SMB共有でのUNIXシンボリックリンクサポートの設定
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
SMB共有の作成時に、または既存のSMB共有の変更によっていつでも、シンボリックリンクの共有プロパティ設定を指定することで、SMB共有でUNIXシンボリックリンクのサポートを設定できます。UNIXシンボリックリンクのサポートはデフォルトで有効になっています。共有でUNIXシンボリックリンクのサポートを無効にすることもできます。

.タスクの内容
SMB共有に対してUNIXシンボリックリンクのサポートを設定する場合は、次のいずれかの設定を選択できます。

|===
| 設定 | 説明 


 a| 
`enable`（廃止予定*）
 a| 
読み取り/書き込みアクセスに対してシンボリックリンクを有効にします。



 a| 
`read_only`（廃止予定*）
 a| 
読み取り専用アクセスに対してシンボリックリンクを有効にします。この設定はワイドリンクには適用されません。Widelinkアクセスは常に読み取り/書き込みです。



 a| 
`hide`（廃止予定*）
 a| 
SMBクライアントにシンボリックリンクが表示されないように指定します。



 a| 
`no-strict-security`
 a| 
クライアントが共有の範囲外でシンボリックリンクを参照するように指定します。



 a| 
`symlinks`
 a| 
読み取り/書き込みアクセスに対してローカルシンボリックリンクを有効にします。CIFSオプションがに設定されて `true`いても、DFS通知は生成されません `is-advertise-dfs-enabled`。これがデフォルト設定です。



 a| 
`symlinks-and-widelinks`
 a| 
読み取り/書き込みアクセスに対してローカルシンボリックリンクとワイドリンクの両方を指定します。CIFSオプションがに設定されて `false`いる場合でも、DFS通知はローカルシンボリックリンクとワイドリンクの両方に対して生成され `is-advertise-dfs-enabled`ます。



 a| 
`disable`
 a| 
シンボリックリンクとワイドリンクを無効にします。CIFSオプションがに設定されて `true`いても、DFS通知は生成されません `is-advertise-dfs-enabled`。



 a| 
`""`（null、未設定）
 a| 
シンボリックリンクを共有で無効にします。



 a| 
`-`（未設定）
 a| 
シンボリックリンクを共有で無効にします。

|===
[NOTE]
====
* ONTAP の今後のリリースでは、 _enable_,_hide_,_read-only パラメータは廃止されており、削除される可能性があります。

====
.手順
. シンボリックリンクのサポートを設定または無効にします。
+
|===
| 条件 | 入力するコマンド 


 a| 
新しいSMB共有
 a| 
`+vserver cifs share create -vserver vserver_name -share-name share_name -path path -symlink-properties {enable|hide|read-only|""|-|symlinks|symlinks-and-widelinks|disable},...]+`



 a| 
既存のSMB共有
 a| 
`+vserver cifs share modify -vserver vserver_name -share-name share_name -symlink-properties {enable|hide|read-only|""|-|symlinks|symlinks-and-widelinks|disable},...]+`

|===
. SMB共有の設定が正しいことを確認します。 `vserver cifs share show -vserver vserver_name -share-name share_name -instance`


.例
次のコマンドでは、UNIXシンボリックリンク設定をに設定して、「data1」という名前のSMB共有を作成し `enable`ます。

[listing]
----
cluster1::> vserver cifs share create -vserver vs1 -share-name data1 -path /data1 -symlink-properties enable

cluster1::> vserver cifs share show -vserver vs1 -share-name data1 -instance

                          Vserver: vs1
                            Share: data1
         CIFS Server NetBIOS Name: VS1
                             Path: /data1
                 Share Properties: oplocks
                                   browsable
                                   changenotify
               Symlink Properties: enable
          File Mode Creation Mask: -
     Directory Mode Creation Mask: -
                    Share Comment: -
                        Share ACL: Everyone / Full Control
    File Attribute Cache Lifetime: -
                      Volume Name: -
                    Offline Files: manual
    Vscan File-Operations Profile: standard
Maximum Tree Connections on Share: 4294967295
       UNIX Group for File Create: -
----
.関連情報
xref:create-symbolic-link-mappings-task.adoc[SMB共有のシンボリックリンクマッピングの作成]
