---
permalink: smb-admin/configure-roaming-profiles-task.html 
sidebar: sidebar 
keywords: automatic, user, profile, available, log, computer, network, configure, roam, active, directory, mmc, snap-in, configuring, roam, windows, server, administration, center, configure roam profile 
summary: 'ユーザーがネットワーク上の任意のコンピュータにログオンしたときにユーザーのプロファイルを自動的に使用可能にするには、[Active Directoryユーザーとコンピュータ] MMCスナップインを使用して移動プロファイルを構成します。Windows Serverで移動プロファイルを構成する場合は、Active Directory管理センターを使用できます。' 
---
= Active Directory ユーザーとコンピューター MMC を通じてローミング ONTAP SMB プロファイルを構成する
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
ユーザがネットワーク上の任意のコンピュータにログオンしたときにそのユーザのプロファイルを自動的に使用可能にするには、[Active Directoryユーザーとコンピュータ]MMCスナップインで移動プロファイルを設定します。Windows Serverで移動プロファイルを設定する場合は、Active Directory管理センターを使用します。

.手順
. Windowsサーバーで、Active DirectoryユーザーとコンピュータMMC（またはWindowsサーバーのActive Directory管理センター）を開きます。
. 移動プロファイルを設定するユーザを見つけます。
. ユーザーを右クリックし、 * プロパティ * をクリックします。
. [プロファイル]*タブで、ユーザの移動プロファイルを保存する共有のプロファイルパスを入力し、続けてを入力します `%username%`。
+
たとえば、プロファイルパスは次のようになります `\\vs1.example.com\profiles\%username%`。ユーザが初めてログインすると、 `%username%`はそのユーザの名前に置き換えられます。

+
[NOTE]
====
パスの `\\vs1.example.com\profiles\%username%` `profiles`は、すべてのメンバーにフルコントロール権限が割り当てられているStorage Virtual Machine（SVM）vs1上の共有の共有名です。

====
. [OK]*をクリックします。

