---
permalink: smb-admin/configure-unix-symbolic-link-support-shares-task.html 
sidebar: sidebar 
keywords: configure, unix, symbol, link, support, smb, share, share-property, setting, create, modify, exist, configure unix symbolic link support, on smb shares 
summary: SMB 共有の作成時に、または既存の SMB 共有の変更によっていつでも、シンボリックリンクの共有プロパティ設定を指定することによって、 SMB 共有で UNIX シンボリックリンクのサポートを設定できます。UNIX シンボリックリンクのサポートはデフォルトで有効になっています。UNIX シンボリックリンクのサポートを共有で無効にすることもできます。 
---
= SMB 共有で UNIX シンボリックリンクサポートを設定する
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
SMB 共有の作成時に、または既存の SMB 共有の変更によっていつでも、シンボリックリンクの共有プロパティ設定を指定することによって、 SMB 共有で UNIX シンボリックリンクのサポートを設定できます。UNIX シンボリックリンクのサポートはデフォルトで有効になっています。UNIX シンボリックリンクのサポートを共有で無効にすることもできます。

SMB 共有で UNIX シンボリックリンクのサポートを設定する場合は、次の設定のいずれかを選択できます。

|===
| 設定 | 説明 


 a| 
'enable' （廃止予定 * ）
 a| 
読み取り / 書き込みアクセスに対してシンボリックリンクを有効にします。



 a| 
`re ad_only` ( 廃止 *)
 a| 
読み取り専用アクセスに対してシンボリックリンクを有効にします。この設定はワイドリンクには適用されません。ワイドリンクアクセスは常に読み取り / 書き込みです。



 a| 
`hide` ( 非推奨 *)
 a| 
SMB クライアントにシンボリックリンクが表示されないようにします。



 a| 
'no-strict-security
 a| 
クライアントに共有の範囲を越えるシンボリックリンクの参照を許可します。



 a| 
'ymlinks'
 a| 
読み取り / 書き込みアクセスに対してローカルシンボリックリンクを有効にします。CIFS オプションの is-advertise-dfs-enabled が「 true 」に設定されている場合でも、 DFS 通知は生成されません。これがデフォルト設定です。



 a| 
「 ymlinks-and-widelinks 」というように指定します
 a| 
読み取り / 書き込みアクセスに対してローカルシンボリックリンクとワイドリンクの両方を有効にします。CIFS オプションの is-advertise-dfs-enabled が「 false 」に設定されている場合でも、 DFS 通知はローカルシンボリックリンクとワイドリンクの両方に対して生成されます。



 a| 
「不可能」
 a| 
シンボリックリンクとワイドリンクを無効にします。CIFS オプションの is-advertise-dfs-enabled が「 true 」に設定されている場合でも、 DFS 通知は生成されません。



 a| 
""( ヌル、未設定 )
 a| 
シンボリックリンクを共有で無効にします。



 a| 
`-` ( 未設定 )
 a| 
シンボリックリンクを共有で無効にします。

|===
[NOTE]
====
* ONTAP の今後のリリースでは、 _enable_,_hide_,_read-only パラメータは廃止されており、削除される可能性があります。

====
.手順
. シンボリックリンクのサポートを設定または無効化します。
+
|===
| 条件 | 入力するコマンド 


 a| 
新しい SMB 共有
 a| 
「 + vserver cifs share create -vserver vserver_name -share-name share_name -path path -symlink-properties ｛ enable | hide | read-only | "" | -| symlinks | symlinks - and -widelinks | disable ｝ 、…… ] + 」を指定します



 a| 
既存の SMB 共有
 a| 
「 + vserver cifs share modify -vserver vserver_name -share-name share_name -symlink-properties ｛ enable | hide | read-only | "" | -| symlinks | symlinks - and -widelinks | disable ｝ 、 ...]+` 」を指定します

|===
. SMB 共有の設定が正しいことを確認します。 vserver cifs share show -vserver vserver_name -share-name share_name -instance


次のコマンドでは、 UNIX シンボリックリンク設定を「 enable 」に設定して、「 `data` 」という名前の SMB 共有を作成します。

[listing]
----
cluster1::> vserver cifs share create -vserver vs1 -share-name data1 -path /data1 -symlink-properties enable

cluster1::> vserver cifs share show -vserver vs1 -share-name data1 -instance

                          Vserver: vs1
                            Share: data1
         CIFS Server NetBIOS Name: VS1
                             Path: /data1
                 Share Properties: oplocks
                                   browsable
                                   changenotify
               Symlink Properties: enable
          File Mode Creation Mask: -
     Directory Mode Creation Mask: -
                    Share Comment: -
                        Share ACL: Everyone / Full Control
    File Attribute Cache Lifetime: -
                      Volume Name: -
                    Offline Files: manual
    Vscan File-Operations Profile: standard
Maximum Tree Connections on Share: 4294967295
       UNIX Group for File Create: -
----
xref:create-symbolic-link-mappings-task.adoc[SMB 共有のシンボリックリンクマッピングの作成]
