---
permalink: smb-admin/configure-home-directories-u-variable-task.html 
sidebar: sidebar 
keywords: 'create, home, directory, configuration, designate, share, name, variable, user, windows, dynamic, configure, configure home directories using the %u variable' 
summary: 'ホームディレクトリ設定を作成する際、 %w 変数を使用して共有名を指定し、 %u 変数を使用してホームディレクトリ共有の相対パスを指定することができます。これにより、ユーザは、ホームディレクトリの実際の名前やパスを意識することなく、 Windows ユーザ名を使用して動的に作成された共有を使用してホームディレクトリ共有に接続できます。' 
---
= %u 変数を使用してホームディレクトリを設定します
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
を使用して共有名を指定するホームディレクトリ設定を作成できます `%w` 変数ですが、を使用します `%u` ホームディレクトリ共有の相対パスを指定する変数。これにより、ユーザは、ホームディレクトリの実際の名前やパスを意識することなく、 Windows ユーザ名を使用して動的に作成された共有を使用してホームディレクトリ共有に接続できます。

.手順
. ユーザのホームディレクトリを含むqtreeを作成します。 `volume qtree create -vserver vserver_name -qtree-path qtree_path`
. qtreeで正しいセキュリティ形式が使用されていることを確認します。 `volume qtree show`
. 適切なセキュリティ形式がqtreeで使用されていない場合は、を使用してセキュリティ形式を変更します `volume qtree security` コマンドを実行します
. ホームディレクトリ共有を追加します。 `+vserver cifs share create -vserver vserver -share-name %w -path %u -share-properties homedirectory ,...]+`
+
`-vserver` `vserver` 検索パスを追加するCIFS対応のStorage Virtual Machine（SVM）を指定します。

+
`-share-name` `%w` ホームディレクトリの共有名を指定します。ユーザがホームディレクトリに接続すると、ユーザごとに _windows_user_name の形式で共有名が動的に作成されます。

+
[NOTE]
====
を使用することもできます `%u` の変数 `-share-name` オプションこれにより、マッピング先の UNIX ユーザ名を使用して相対共有パスが作成されます。

====
+
`-path` `%u` ホームディレクトリの相対パスを指定します。ユーザがホームディレクトリに接続すると、ユーザごとに _mapped_UNIX_user_name の形式で共有名が動的に作成されます。

+
[NOTE]
====
このオプションの値には静的な要素も含めることができます。例： `eng/%u`。

====
+
`-share-properties` `+homedirectory\[,...\]+` その共有の共有プロパティを指定します。を指定する必要があります `homedirectory` 価値。追加の共有プロパティをカンマで区切って指定できます。

. を使用して、共有の設定が適切であることを確認します `vserver cifs share show` コマンドを実行します
. ホームディレクトリ検索パスを追加します。 `vserver cifs home-directory search-path add -vserver vserver -path path`
+
`-vserver` `vserver` 検索パスを追加するCIFS対応のSVMを指定します。

+
`-path` `path` 検索パスの絶対ディレクトリパスを指定します。

. を使用して検索パスが追加されたことを確認します `vserver cifs home-directory search-path show` コマンドを実行します
. UNIXユーザが存在しない場合は、を使用してUNIXユーザを作成します `vserver services unix-user create` コマンドを実行します
+
[NOTE]
====
ユーザをマッピングするには、 Windows ユーザ名のマッピング先となる UNIX ユーザ名があらかじめ存在している必要があります。

====
. 次のコマンドを使用して、UNIXユーザへのWindowsユーザのネームマッピングを作成します。 `vserver name-mapping create -vserver vserver_name -direction win-unix -priority integer -pattern windows_user_name -replacement unix_user_name`
+
[NOTE]
====
Windows ユーザを UNIX ユーザにマッピングするネームマッピングがすでに存在する場合は、このマッピング手順を実行する必要はありません。

====
+
Windows ユーザ名は対応する UNIX ユーザ名にマッピングされます。Windows ユーザは、ホームディレクトリ共有に接続すると、 Windows ユーザ名に対応する共有名を使用して動的に作成されたホームディレクトリに接続することになります。その際、ディレクトリ名が UNIX ユーザ名に対応していることはユーザにはわかりません。

. ユーザにホームディレクトリがある場合は、ホームディレクトリを含むように指定した qtree またはボリュームに対応するディレクトリを作成します。
+
たとえば、というパスのqtreeを作成したとします `/vol/vol1/users` ディレクトリを作成するユーザのマッピング先UNIXユーザ名は「unixuser1」です。この場合、ディレクトリの作成には次のパスを使用します。 `/vol/vol1/users/unixuser1`。

+
にマウントされる「home1」という名前のボリュームを作成した場合 `/home1`を指定すると、次のパスでディレクトリが作成されます。 `/home1/unixuser1`。

. ドライブをマッピングするか、 UNC パスを使用して、ユーザがホームディレクトリ共有に正常に接続できることを確認します。
+
たとえば、ユーザmydomain\user1がUNIXユーザunixuser1にマッピングされ、SVM vs1にある手順10で作成されたディレクトリに接続する場合、user1はUNCパスを使用して接続します `\\vs1\user1`。



.例
次の例のコマンドでは、次の設定を使用してホームディレクトリの設定を作成します。

* 共有名は %w です
* 相対ホームディレクトリパスは %u です
* ホームディレクトリを含めるために使用する検索パス。 `/home1`は、UNIXセキュリティ形式が設定されたボリュームです。
* 設定は SVM vs1 上に作成されます。


ユーザが Windows ホストから、または Windows ホストと UNIX ホストからホームディレクトリにアクセスし、ファイルシステム管理者が UNIX ベースのユーザおよびグループを使用してファイルシステムへのアクセスを制御する場合には、このようなホームディレクトリ設定を使用できます。

[listing]
----
cluster::> vserver cifs share create -vserver vs1 -share-name %w -path %u ‑share-properties oplocks,browsable,changenotify,homedirectory

cluster::> vserver cifs share show -vserver vs1 -share-name %u

                      Vserver: vs1
                        Share: %w
     CIFS Server NetBIOS Name: VS1
                         Path: %u
             Share Properties: oplocks
                               browsable
                               changenotify
                               homedirectory
           Symlink Properties: enable
      File Mode Creation Mask: -
 Directory Mode Creation Mask: -
                Share Comment: -
                    Share ACL: Everyone / Full Control
File Attribute Cache Lifetime: -
                  Volume Name: -
                Offline Files: manual
Vscan File-Operations Profile: standard

cluster::> vserver cifs home-directory search-path add -vserver vs1 ‑path /home1

cluster::> vserver cifs home-directory search-path show -vserver vs1
Vserver     Position Path
----------- -------- -----------------
vs1         1        /home1

cluster::> vserver name-mapping create -vserver vs1 -direction win-unix ‑position 5 -pattern user1 -replacement unixuser1

cluster::> vserver name-mapping show -pattern user1
Vserver        Direction Position
-------------- --------- --------
vs1            win-unix  5        Pattern: user1
                              Replacement: unixuser1
----
.関連情報
xref:create-home-directory-config-w-d-variables-task.adoc[%w 変数と %d 変数を使用したホームディレクトリ設定の作成]

xref:home-directory-config-concept.adoc[追加のホームディレクトリの設定]

xref:display-user-home-directory-path-task.adoc[SMB ユーザのホームディレクトリパスに関する情報を表示する]
