---
permalink: smb-admin/configure-guest-unix-user-task.html 
sidebar: sidebar 
keywords: configuring, configure, guest, unix, user, untrusted, domain, map, connect, cifs, server, configure the guest unix user 
summary: ゲストUNIXユーザーオプションを設定すると、信頼されていないドメインからログインしたユーザーはゲストUNIXユーザーにマッピングされ、CIFSサーバーに接続できるようになります。一方、信頼されていないドメインのユーザーの認証を失敗させたい場合は、ゲストUNIXユーザーを設定しないでください。デフォルトでは、信頼されていないドメインのユーザーはCIFSサーバーに接続できません（ゲストUNIXアカウントは設定されていません）。 
---
= ゲストONTAP SMB UNIXユーザーを構成する
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
ゲストUNIXユーザーオプションを設定すると、信頼されていないドメインからログインしたユーザーはゲストUNIXユーザーにマッピングされ、CIFSサーバーに接続できるようになります。一方、信頼されていないドメインのユーザーの認証を失敗させたい場合は、ゲストUNIXユーザーを設定しないでください。デフォルトでは、信頼されていないドメインのユーザーはCIFSサーバーに接続できません（ゲストUNIXアカウントは設定されていません）。

.タスク概要
ゲスト UNIX アカウントを構成するときは、次の点に留意してください：

* CIFSサーバがホーム ドメインまたは信頼できるドメインのドメイン コントローラ、もしくはローカル データベースに対してユーザを認証できず、このオプションが有効である場合、CIFSサーバはユーザをゲスト ユーザとみなし、そのユーザを指定したUNIXユーザにマッピングします。
* このオプションがヌル文字列に設定されている場合、ゲストUNIXユーザーは無効になります。
* いずれかのStorage Virtual Machine（SVM）ネーム サービス データベースで、ゲストUNIXユーザとして使用するUNIXユーザを作成する必要があります。
* ゲスト ユーザーとしてログインしたユーザーは、自動的に CIFS サーバー上の BUILTIN\guests グループのメンバーになります。
* 「homedirs-public」オプションは認証されたユーザーにのみ適用されます。ゲストユーザーとしてログインしたユーザーにはホームディレクトリがないため、他のユーザーのホームディレクトリにアクセスできません。


.手順
. 次のいずれかを実行します。
+
|===
| 状況 | 入力する内容 


 a| 
ゲストUNIXユーザを設定する
 a| 
`vserver cifs options modify -guest-unix-user _unix_name_`



 a| 
ゲスト UNIX ユーザーを無効にする
 a| 
`vserver cifs options modify -guest-unix-user ""`

|===
+
`vserver cifs options modify -guest-unix-user pcuser`

. ゲスト UNIX ユーザーが正しく設定されていることを確認します： `vserver cifs options show -vserver _vserver_name_`
+
次の例では、SVM vs1 上のデフォルトの UNIX ユーザーとゲスト UNIX ユーザーの両方が、UNIX ユーザー「`pcuser`」を使用するように設定されています：

+
`vserver cifs options show -vserver vs1`

+
[listing]
----

Vserver: vs1

  Client Session Timeout : 900
  Default Unix Group     : -
  Default Unix User      : pcuser
  Guest Unix User        : pcuser
  Read Grants Exec       : disabled
  Read Only Delete       : disabled
  WINS Servers           : -
----

