---
permalink: smb-admin/configure-branchcache-task.html 
sidebar: sidebar 
keywords: configure, branchcache, service, per-share, basis, smb, share, configure branchcache on the cifs server 
summary: BranchCacheサービスを共有ごとに提供するようにBranchCacheを設定できます。また、すべてのSMB共有でキャッシュを自動的に有効にするようにBranchCacheを設定することもできます。 
---
= ONTAP SMBサーバーでBranchCacheを構成する
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
BranchCacheサービスを共有ごとに提供するようにBranchCacheを設定できます。また、すべてのSMB共有でキャッシュを自動的に有効にするようにBranchCacheを設定することもできます。

.タスクの内容
BranchCacheはSVMで設定できます。

* CIFSサーバ上のすべてのSMB共有に格納されたすべてのコンテンツに対してキャッシュサービスを提供する場合は、すべての共有のBranchCache設定を作成できます。
* CIFSサーバ上の選択したSMB共有に格納されたコンテンツに対してキャッシュサービスを提供する場合は、共有ごとのBranchCache設定を作成できます。


BranchCacheの設定時には、次のパラメータを指定する必要があります。

|===
| 必須パラメータ | 説明 


 a| 
SVM 名 _
 a| 
BranchCacheはSVM単位で設定します。BranchCacheサービスを設定するCIFS対応SVMを指定する必要があります。



 a| 
ハッシュストアへのパス _
 a| 
BranchCacheハッシュは、SVMボリューム上の通常のファイルに格納されます。ONTAPにハッシュデータを格納する既存のディレクトリのパスを指定する必要があります。BranchCacheハッシュパスは読み取り/書き込み可能である必要があります。Snapshotディレクトリなどの読み取り専用パスは指定できません。他のデータを含むボリュームにハッシュデータを格納することも、ハッシュデータを格納するための別のボリュームを作成することもできます。

SVMがSVMディザスタリカバリソースの場合、ハッシュパスをルートボリュームに配置することはできません。これは、ルートボリュームがディザスタリカバリデスティネーションにレプリケートされないためです。

ハッシュパスには、空白とファイル名の有効な文字を含めることができます。

|===
必要に応じて、次のパラメータを指定できます。

|===
| オプションのパラメータ | 説明 


 a| 
サポートされているバージョン _
 a| 
ONTAPでは、BranchCache 1および2がサポートされます。バージョン1、バージョン2、またはその両方を有効にできます。デフォルトでは、両方のバージョンが有効になります。



 a| 
_ ハッシュストアの最大サイズ _
 a| 
ハッシュデータストアに使用するサイズを指定できます。ハッシュデータがこの値を超えると、ONTAPは古いハッシュを削除して新しいハッシュ用のスペースを確保します。ハッシュストアのデフォルトサイズは1GBです。ハッシュが過度に破棄されない場合、BranchCacheのパフォーマンスは向上します。ハッシュストアがいっぱいになったためにハッシュが頻繁に破棄されると判断した場合は、BranchCacheの設定を変更してハッシュストアのサイズを大きくすることができます。



 a| 
_ サーバキー _
 a| 
クライアントがBranchCacheサーバを偽装できないようにするためにBranchCacheサービスで使用されるサーバキーを指定できます。指定しない場合、BranchCacheの設定の作成時にサーバキーがランダムに生成されます。サーバキーを特定の値に設定すると、複数のサーバが同じファイルのBranchCacheデータを提供している場合に、クライアントが同じサーバキーを使用して任意のサーバのハッシュを使用できるようになります。サーバキーにスペースを含める場合は、サーバキーを引用符で囲む必要があります。



 a| 
オペレーティングモード _
 a| 
デフォルトでは、BranchCacheは共有ごとに有効になります。

* BranchCacheを共有ごとに有効にするBranchCacheの設定を作成するには、このオプションパラメータを指定しないか、を指定します `per-share`。
* すべての共有でBranchCacheを自動的に有効にするには、動作モードをに設定する必要があります `all-shares`。


|===
.手順
. 必要に応じてSMB 2.1および3.0を有効にします。
+
.. 権限レベルをadvancedに設定します。 `set -privilege advanced`
.. SVMのSMB設定を確認して、必要なすべてのバージョンのSMBが有効になっているかどうかを確認します。 `vserver cifs options show -vserver _vserver_name_`
.. 必要に応じて、SMB 2.1を有効にします。 `vserver cifs options modify -vserver _vserver_name_ -smb2-enabled true`
+
コマンドは、SMB 2.0とSMB 2.1の両方を有効にします。

.. 必要に応じて、SMB 3.0を有効にします。 `vserver cifs options modify -vserver _vserver_name_ -smb3-enabled true`
.. admin権限レベルに戻ります。 `set -privilege admin`


. BranchCacheを設定します。 `vserver cifs branchcache create -vserver _vserver_name_ -hash-store-path path [-hash-store-max-size {integer[KB|MB|GB|TB|PB]}] [-versions {v1-enable|v2-enable|enable-all] [-server-key text] -operating-mode {per-share|all-shares}`
+
指定したハッシュストレージのパスが存在し、SVMによって管理されているボリューム上にある必要があります。また、パスは読み取り / 書き込み可能なボリュームにある必要があります。パスが読み取り専用であるか、または存在しない場合、コマンドは失敗します。

+
SVM BranchCacheの追加設定で同じサーバキーを使用する場合は、サーバキーとして入力した値を記録しておきます。BranchCacheの設定に関する情報を表示しても、サーバキーは表示されません。

. BranchCacheの設定が正しいことを確認します。 `vserver cifs branchcache show -vserver _vserver_name_`


.例
次のコマンドは、SMB 2.1と3.0の両方が有効になっていることを確認し、SVM vs1のすべてのSMB共有でキャッシュを自動的に有効にするようにBranchCacheを設定します。

[listing]
----
cluster1::> set -privilege advanced
Warning: These advanced commands are potentially dangerous; use them
only when directed to do so by technical support personnel.
Do you wish to continue? (y or n): y

cluster1::*> vserver cifs options show -vserver vs1 -fields smb2-enabled,smb3-enabled
vserver smb2-enabled smb3-enabled
------- ------------ ------------
vs1     true         true


cluster1::*> set -privilege admin

cluster1::> vserver cifs branchcache create -vserver vs1 -hash-store-path /hash_data -hash-store-max-size 20GB -versions enable-all -server-key "my server key" -operating-mode all-shares

cluster1::> vserver cifs branchcache show -vserver vs1

                                 Vserver: vs1
          Supported BranchCache Versions: enable_all
                      Path to Hash Store: /hash_data
          Maximum Size of the Hash Store: 20GB
Encryption Key Used to Secure the Hashes: -
        CIFS BranchCache Operating Modes: all_shares
----
次のコマンドは、SMB 2.1と3.0の両方が有効になっていることを確認し、SVM vs1の共有ごとにキャッシュを有効にするようにBranchCacheを設定し、BranchCacheの設定を確認します。

[listing]
----
cluster1::> set -privilege advanced
Warning: These advanced commands are potentially dangerous; use them
only when directed to do so by technical support personnel.
Do you wish to continue? (y or n): y

cluster1::*> vserver cifs options show -vserver vs1 -fields smb2-enabled,smb3-enabled
vserver smb2-enabled smb3-enabled
------- ------------ ------------
vs1     true         true

cluster1::*> set -privilege admin

cluster1::> vserver cifs branchcache create -vserver vs1 -hash-store-path /hash_data -hash-store-max-size 20GB -versions enable-all -server-key "my server key"

cluster1::> vserver cifs branchcache show -vserver vs1

                                 Vserver: vs1
          Supported BranchCache Versions: enable_all
                      Path to Hash Store: /hash_data
          Maximum Size of the Hash Store: 20GB
Encryption Key Used to Secure the Hashes: -
        CIFS BranchCache Operating Modes: per_share
----
.関連情報
* xref:branchcache-version-support-concept.html[BranchCacheのバージョンサポートについて]
* xref:configure-branchcache-remote-office-concept.adoc[リモートオフィスでのBranchCacheの構成について学ぶ]
* xref:create-branchcache-enabled-share-task.adoc[BranchCacheが有効なSMB共有を作成する]
* xref:enable-branchcache-existing-share-task.adoc[既存の共有でBranchCacheを有効にする]
* xref:modify-branchcache-config-task.html[共有上の BranchCache 構成を変更する]
* xref:disable-branchcache-shares-concept.html[共有上のBranchCacheを無効にする方法について]
* xref:delete-branchcache-config-task.html[共有上のBranchCache構成を削除する]

