---
permalink: smb-admin/configure-default-unix-user-task.html 
sidebar: sidebar 
keywords: configure, unix, user, map, fail, individual, windows, authentication, non-mapped, configure the default unix user 
summary: 特定のユーザーに対する他のすべてのマッピング試行が失敗した場合、またはUNIXとWindows間で個々のユーザーをマッピングしたくない場合は、デフォルトのUNIXユーザーを設定できます。一方、マッピングされていないユーザーの認証を失敗させたい場合には、デフォルトのUNIXユーザーを設定しないでください。 
---
= デフォルトのONTAP SMB UNIXユーザーを設定する
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
特定のユーザーに対する他のすべてのマッピング試行が失敗した場合、またはUNIXとWindows間で個々のユーザーをマッピングしたくない場合は、デフォルトのUNIXユーザーを設定できます。一方、マッピングされていないユーザーの認証を失敗させたい場合には、デフォルトのUNIXユーザーを設定しないでください。

.タスク概要
デフォルトでは、デフォルトUNIXユーザの名前は「`pcuser`」です。これは、デフォルトUNIXユーザへのユーザマッピングがデフォルトで有効になっていることを意味します。デフォルトUNIXユーザとして使用する別の名前を指定することもできます。指定する名前は、Storage Virtual Machine（SVM）用に設定されたネームサービスデータベースに存在している必要があります。このオプションがNULL文字列に設定されている場合、UNIXデフォルトユーザとしてCIFSサーバにアクセスすることはできません。つまり、各ユーザはCIFSサーバにアクセスする前に、パスワードデータベースにアカウントを持っている必要があります。

ユーザーがデフォルトの UNIX ユーザー アカウントを使用して CIFS サーバーに接続するには、次の前提条件を満たしている必要があります：

* ユーザーは認証されています。
* ユーザーは、CIFS サーバーのローカル Windows ユーザー データベース、CIFS サーバーのホーム ドメイン、または信頼されたドメイン（CIFS サーバーでマルチドメイン名マッピング検索が有効になっている場合）に存在します。
* ユーザー名は明示的に null 文字列にマップされていません。


.手順
. デフォルトのUNIXユーザを設定します。
+
|===
| 状況 | コマンド 


 a| 
デフォルトのUNIXユーザー「`pcuser`」を使用する
 a| 
`vserver cifs options modify -default-unix-user pcuser`



 a| 
別のUNIXユーザーアカウントをデフォルトユーザーとして使用する
 a| 
`vserver cifs options modify -default-unix-user _user_name_`



 a| 
デフォルトのUNIXユーザを無効にする
 a| 
`vserver cifs options modify -default-unix-user ""`

|===
+
`vserver cifs options modify -default-unix-user pcuser`

. デフォルトの UNIX ユーザーが正しく設定されていることを確認します： `vserver cifs options show -vserver _vserver_name_`
+
次の例では、SVM vs1 上のデフォルトの UNIX ユーザーとゲスト UNIX ユーザーの両方が、UNIX ユーザー「`pcuser`」を使用するように設定されています：

+
`vserver cifs options show -vserver vs1`

+
[listing]
----

Vserver: vs1

  Client Session Timeout : 900
  Default Unix Group     : -
  Default Unix User      : pcuser
  Guest Unix User        : pcuser
  Read Grants Exec       : disabled
  Read Only Delete       : disabled
  WINS Servers           : -
----

