---
permalink: smb-admin/configure-nis-ldap-name-services-svm-task.html 
sidebar: sidebar 
keywords: smb, access, map, unix, user, perform, data, ntfs, security-style, volume, windows, correspond, unix, information, nis, ldap, directory, store, name, configure nis or ldap name services on the svm 
summary: SMB アクセスでは、 NTFS セキュリティ形式のボリューム内のデータにアクセスする場合でも、 UNIX ユーザへのユーザマッピングが常に実行されます。NIS または LDAP ディレクトリストアにその情報が格納されている UNIX ユーザに Windows ユーザをマッピングする場合や、ネームマッピングに LDAP を使用する場合は、 SMB のセットアップ時にこのネームサービスを設定する必要があります。 
---
= SVM に NIS または LDAP ネームサービスを設定します
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
SMB アクセスでは、 NTFS セキュリティ形式のボリューム内のデータにアクセスする場合でも、 UNIX ユーザへのユーザマッピングが常に実行されます。NIS または LDAP ディレクトリストアにその情報が格納されている UNIX ユーザに Windows ユーザをマッピングする場合や、ネームマッピングに LDAP を使用する場合は、 SMB のセットアップ時にこのネームサービスを設定する必要があります。

.作業を開始する前に
ネームサービスデータベース設定をネームサービスインフラに合わせてカスタマイズしておく必要があります。

.このタスクについて
SVMは、ネームサービスns-switchデータベースを使用して、指定されたネームサービスデータベースを検索するソースの順序を決定します。ns-switchソースには、、 `nis`、または `ldap`を任意に組み合わせて指定できます `files`。グループデータベースの場合、ONTAPは設定されているすべてのソースからグループメンバーシップを取得しようとし、統合されたグループメンバーシップ情報をアクセスチェックに使用します。UNIXグループ情報の取得時にこれらのソースのいずれかが使用できないと、ONTAPは完全なUNIXクレデンシャルを取得できず、以降のアクセスチェックが失敗することがあります。そのため、ns-switch設定でグループデータベースのすべてのns-switchソースが設定されていることを常に確認する必要があります。

デフォルトでは、SMBサーバは、すべてのWindowsユーザをローカルに格納されているデフォルトのUNIXユーザにマッピングします `passwd` データベース：デフォルトの設定を使用する場合、 SMB アクセスに対する、 NIS または LDAP UNIX ユーザおよびグループのネームサービスまたは LDAP ユーザマッピングの設定は省略可能です。

.手順
. UNIX ユーザ、グループ、ネットグループ情報が NIS ネームサービスによって管理されている場合、 NIS ネームサービスを次のように設定します。
+
.. を使用して、ネームサービスの現在の順序を確認します `vserver services name-service ns-switch show` コマンドを実行します
+
この例では、3つのデータベースを示します (`group`、 `passwd`および `netgroup`を使用できます `nis` ネームサービスソースがのみを使用している `files` 情報源として

+
`vserver services name-service ns-switch show -vserver vs1`

+
[listing]
----

                                               Source
Vserver         Database       Enabled         Order
--------------- ------------   ---------       ---------
vs1             hosts          true            dns,
                                               files
vs1             group          true            files
vs1             passwd         true            files
vs1             netgroup       true            files
vs1             namemap        true            files
----
+
を追加する必要があります `nis` を参照してください `group` および `passwd` データベース、およびオプションでにアクセスできます `netgroup` データベース：

.. を使用して、ネームサービスns-switchデータベースを必要な順序で調整します `vserver services name-service ns-switch modify` コマンドを実行します
+
パフォーマンスを最大にするためには、 SVM に設定する予定のないネームサービスデータベースにはネームサービスを追加しないでください。

+
複数のネームサービスデータベースの設定を変更する場合、変更するそれぞれのネームサービスデータベースに対して別々にコマンドを実行する必要があります。

+
この例では、 `nis` および `files` は、のソースとして設定されています `group` および `passwd` この順番でデータベースを作成します。その他のネームサービスデータベースは変更されません。

+
`vserver services name-service ns-switch modify -vserver vs1 -database group -sources nis,files` `vserver services name-service ns-switch modify -vserver vs1 -database passwd -sources nis,files`

.. を使用して、ネームサービスの順序が正しいことを確認します `vserver services name-service ns-switch show` コマンドを実行します
+
`vserver services name-service ns-switch show -vserver vs1`

+
[listing]
----

                                               Source
Vserver         Database       Enabled         Order
--------------- ------------   ---------       ---------
vs1             hosts          true            dns,
                                               files
vs1             group          true            nis,
                                               files
vs1             passwd         true            nis,
                                               files
vs1             netgroup       true            files
vs1             namemap        true            files
----
.. NISネームサービス設定を作成します。+
`vserver services name-service nis-domain create -vserver <vserver_name> -domain <NIS_domain_name> -servers <NIS_server_IPaddress>,...`
+
`vserver services name-service nis-domain create -vserver vs1 -domain example.com -servers 10.0.0.60`

+
[NOTE]
====
ONTAP 9.2以降では、フィールドが表示されます `-nis-servers` フィールドを置き換えます `-servers`。この新しいフィールドには、NISサーバのホスト名またはIPアドレスを指定できます。

====
.. NISネームサービスが適切に設定されていることを確認します。 `vserver services name-service nis-domain show vserver <vserver_name>`
+
`vserver services name-service nis-domain show vserver vs1`

+
[listing]
----

Vserver       Domain              Server
------------- ------------------- ---------------
vs1           example.com         10.0.0.60
----


. UNIX ユーザ、グループ、ネットグループ情報またはネームマッピングが LDAP ネームサービスによって管理されている場合は、格納されている情報を使用して LDAP ネームサービスを設定します link:../nfs-admin/index.html["NFS の管理"]。

