---
permalink: smb-admin/configure-branchcache-enabled-shares-concept.html 
sidebar: sidebar 
keywords: configure, branchcache, smb server, office, enable, smb, share, content, client, configure branchache-enabled smb shares 
summary: SMB サーバとブランチオフィスで BranchCache を設定したら、ブランチオフィスのクライアントによるコンテンツのキャッシュを許可する SMB 共有で BranchCache を有効にすることができます。 
---
= BranchCache が有効な SMB 共有の概要を設定
:icons: font
:imagesdir: ../media/


[role="lead"]
SMB サーバとブランチオフィスで BranchCache を設定したら、ブランチオフィスのクライアントによるコンテンツのキャッシュを許可する SMB 共有で BranchCache を有効にすることができます。

BranchCache キャッシュは、 SMB サーバ上のすべての SMB 共有で有効にするか、共有ごとに有効にすることができます。

* BranchCache を共有ごとに有効にする場合、 BranchCache は共有の作成時に有効にするか、既存の共有を変更して有効にすることができます。
+
既存の SMB 共有でキャッシュを有効にすると、その共有で BranchCache を有効にした時点で、 ONTAP によるハッシュの計算と要求元クライアントへのメタデータの送信が開始されます。

* 共有への SMB 接続をすでに確立しているクライアントは、それ以降にその共有で BranchCache が有効になった場合、 BranchCache のサポートを得ることができません。
+
ONTAP は、 SMB セッションがセットアップされたときに共有の BranchCache のサポートを通知します。BranchCache が有効なときにすでにセッションを確立していたクライアントは、キャッシュされている内容をこの共有で使用するために、いったん切断してから再接続する必要があります。



[NOTE]
====
その後 SMB 共有に対する BranchCache を無効にすると、 ONTAP による要求元クライアントへのメタデータの送信が中止されます。データが必要なクライアントは、コンテンツサーバ（ SMB サーバ）から直接データを取得します。

====