---
permalink: smb-admin/configure-unix-symbolic-link-support-shares-task.html 
sidebar: sidebar 
keywords: configure, unix, symbol, link, support, smb, share, share-property, setting, create, modify, exist, configure unix symbolic link support, on smb shares 
summary: SMB共有の作成時に、または既存のSMB共有の変更によりいつでも、シンボリック リンクの共有プロパティ設定を指定することによって、SMB共有でUNIXシンボリック リンクのサポートを設定できます。UNIXシンボリック リンクのサポートはデフォルトで有効になっています。UNIXシンボリック リンクのサポートを共有で無効にすることもできます。 
---
= ONTAP SMB 共有で UNIX シンボリック リンクのサポートを設定する
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
SMB共有の作成時に、または既存のSMB共有の変更によりいつでも、シンボリック リンクの共有プロパティ設定を指定することによって、SMB共有でUNIXシンボリック リンクのサポートを設定できます。UNIXシンボリック リンクのサポートはデフォルトで有効になっています。UNIXシンボリック リンクのサポートを共有で無効にすることもできます。

.タスク概要
SMB共有でUNIXシンボリック リンクのサポートを設定する場合は、次の設定のいずれかを選択できます。

|===
| 設定 | 概要 


 a| 
`enable` （非推奨*）
 a| 
読み取り / 書き込みアクセスに対してシンボリック リンクを有効にします。



 a| 
`read_only` （非推奨*）
 a| 
読み取り専用アクセスに対してシンボリック リンクを有効にします。この設定はワイドリンクには適用されません。ワイドリンク アクセスは常に読み取り / 書き込みです。



 a| 
`hide` （非推奨*）
 a| 
SMBクライアントにシンボリック リンクが表示されないようにします。



 a| 
`no-strict-security`
 a| 
クライアントに共有の範囲を越えるシンボリック リンクの参照を許可します。



 a| 
`symlinks`
 a| 
シンボリック リンクの読み取り / 書き込みアクセスをローカルで有効にすることを指定します。CIFS オプション `is-advertise-dfs-enabled`が `true`に設定されていても、DFS アドバタイズメントは生成されません。これがデフォルト設定です。



 a| 
`symlinks-and-widelinks`
 a| 
読み取り / 書き込みアクセスに対して、ローカル シンボリック リンクとワイドリンクの両方を指定します。CIFS オプション `is-advertise-dfs-enabled`が `false`に設定されている場合でも、ローカル シンボリック リンクとワイドリンクの両方に対して DFS アドバタイズメントが生成されます。



 a| 
`disable`
 a| 
シンボリック リンクとワイドリンクを無効にすることを指定します。CIFS オプション `is-advertise-dfs-enabled`が `true`に設定されている場合でも、DFS アドバタイズメントは生成されません。



 a| 
`""` (null、未設定)
 a| 
シンボリック リンクを共有で無効にします。



 a| 
`-`（未設定）
 a| 
シンボリック リンクを共有で無効にします。

|===
[NOTE]
====
*_enable_、_hide_、および_read-only_パラメータは非推奨であり、ONTAPの今後のリリースで削除される可能性があります。

====
.手順
. シンボリック リンク サポートを設定または無効化します。
+
|===
| もしそうだとしたら… | 入力する内容 


 a| 
新しいSMB共有
 a| 
`+vserver cifs share create -vserver vserver_name -share-name share_name -path path -symlink-properties {enable|hide|read-only|""|-|symlinks|symlinks-and-widelinks|disable},...]+`



 a| 
既存のSMB共有
 a| 
`+vserver cifs share modify -vserver vserver_name -share-name share_name -symlink-properties {enable|hide|read-only|""|-|symlinks|symlinks-and-widelinks|disable},...]+`

|===
. SMB 共有の設定が正しいことを確認します： `vserver cifs share show -vserver vserver_name -share-name share_name -instance`


.例
次のコマンドは、UNIXシンボリック リンク構成を `enable`に設定した「`data1`」という名前のSMB共有を作成します：

[listing]
----
cluster1::> vserver cifs share create -vserver vs1 -share-name data1 -path /data1 -symlink-properties enable

cluster1::> vserver cifs share show -vserver vs1 -share-name data1 -instance

                          Vserver: vs1
                            Share: data1
         CIFS Server NetBIOS Name: VS1
                             Path: /data1
                 Share Properties: oplocks
                                   browsable
                                   changenotify
               Symlink Properties: enable
          File Mode Creation Mask: -
     Directory Mode Creation Mask: -
                    Share Comment: -
                        Share ACL: Everyone / Full Control
    File Attribute Cache Lifetime: -
                      Volume Name: -
                    Offline Files: manual
    Vscan File-Operations Profile: standard
Maximum Tree Connections on Share: 4294967295
       UNIX Group for File Create: -
----
.関連情報
xref:create-symbolic-link-mappings-task.adoc[共有のシンボリック リンク マッピングを作成する]
