---
permalink: smb-admin/configure-home-directories-u-variable-task.html 
sidebar: sidebar 
keywords: 'create, home, directory, configuration, designate, share, name, variable, user, windows, dynamic, configure, configure home directories using the %u variable' 
summary: '%w 変数を使用して共有名を指定し、%u 変数を使用してホームディレクトリ共有への相対パスを指定するホームディレクトリ設定を作成できます。ユーザーは、ホームディレクトリの実際の名前やパスを意識することなく、Windows ユーザー名を使用して動的に作成された共有に接続できます。' 
---
= %u変数を使用してONTAP SMBホームディレクトリを構成する
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
 `%w`変数を使用して共有名を指定するホームディレクトリ設定を作成できますが、 `%u`変数を使用してホームディレクトリ共有への相対パスを指定します。これにより、ユーザーはホームディレクトリの実際の名前やパスを意識することなく、Windowsユーザー名を使用して動的に作成された共有を使用してホーム共有に接続できます。

.手順
. ユーザーのホーム ディレクトリを格納する qtree を作成します。 `volume qtree create -vserver vserver_name -qtree-path qtree_path`
. qtreeが正しいセキュリティ スタイルを使用していることを確認します。 `volume qtree show`
. qtreeが目的のセキュリティ スタイルを使用していない場合は、 `volume qtree security`コマンドを使用してセキュリティ スタイルを変更します。
. ホームディレクトリ共有を追加します： `+vserver cifs share create -vserver vserver -share-name %w -path %u -share-properties homedirectory ,...]+`
+
`-vserver` `vserver`検索パスを追加する CIFS 対応のストレージ仮想マシン（SVM）を指定します。

+
`-share-name` `%w`ホームディレクトリの共有名を指定します。共有名は各ユーザーがホームディレクトリに接続するたびに動的に作成され、_windows_user_name_という形式になります。

+
[NOTE]
====
 `-share-name`オプションに `%u`変数を使用することもできます。これにより、マッピングされた UNIX ユーザー名を使用した相対共有パスが作成されます。

====
+
`-path` `%u`ホームディレクトリへの相対パスを指定します。相対パスは各ユーザーがホームディレクトリに接続するたびに動的に作成され、_mapped_UNIX_user_name_という形式になります。

+
[NOTE]
====
このオプションの値には静的要素も含めることができます。例えば、 `eng/%u`。

====
+
`-share-properties` `+homedirectory\[,...\]+` はその共有の共有プロパティを指定します。 `homedirectory` 値を指定する必要があります。追加の共有プロパティは、カンマ区切りのリストで指定できます。

.  `vserver cifs share show`コマンドを使用して、共有が目的の構成になっていることを確認します。
. ホームディレクトリの検索パスを追加します： `vserver cifs home-directory search-path add -vserver vserver -path path`
+
`-vserver` `vserver`検索パスを追加する CIFS 対応 SVM を指定します。

+
`-path` `path`検索パスへの絶対ディレクトリパスを指定します。

.  `vserver cifs home-directory search-path show`コマンドを使用して検索パスが正常に追加されたことを確認します。
. UNIX ユーザーが存在しない場合は、 `vserver services unix-user create` コマンドを使用して UNIX ユーザーを作成します。
+
[NOTE]
====
ユーザをマッピングするには、Windowsユーザ名のマッピング先となるUNIXユーザ名があらかじめ存在している必要があります。

====
. 次のコマンドを使用して、Windows ユーザーから UNIX ユーザーへの名前マッピングを作成します： `vserver name-mapping create -vserver vserver_name -direction win-unix -priority integer -pattern windows_user_name -replacement unix_user_name`
+
[NOTE]
====
WindowsユーザをUNIXユーザにマッピングするネーム マッピングがすでに存在する場合は、このマッピング手順を実行する必要はありません。

====
+
Windowsユーザ名は対応するUNIXユーザ名にマッピングされます。Windowsユーザは、ホーム ディレクトリ共有に接続すると、Windowsユーザ名に対応する共有名を使用して動的に作成されたホーム ディレクトリに接続することになります。その際、ディレクトリ名がUNIXユーザ名に対応していることはユーザにはわかりません。

. ユーザにホーム ディレクトリがある場合は、ホーム ディレクトリを含むように指定したqtreeまたはボリュームに対応するディレクトリを作成します。
+
たとえば、 `/vol/vol1/users`のパスで qtree を作成し、ディレクトリを作成するユーザーのマップされた UNIX ユーザー名が "`unixuser1`" である場合、次のパスでディレクトリを作成します： `/vol/vol1/users/unixuser1`

+
「`home1`」という名前のボリュームを `/home1`にマウントした場合、次のパスを持つディレクトリが作成されます： `/home1/unixuser1`

. ドライブをマッピングするか、UNCパスを使用して、ユーザがホーム ディレクトリ共有に正常に接続できることを確認します。
+
たとえば、ユーザー mydomain\user1 が UNIX ユーザー unixuser1 にマッピングされ、手順 10 で作成された SVM vs1 上のディレクトリに接続する場合、user1 は UNC パス `\\vs1\user1`を使用して接続します。



.例
次の例の各コマンドは、以下の内容でホーム ディレクトリ設定を作成します。

* 共有名は%wです。
* 相対ホーム ディレクトリ パスは%uです。
* ホーム ディレクトリを格納するために使用される検索パス `/home1`は、UNIX セキュリティ スタイルで構成されたボリュームです。
* 設定はSVM vs1上に作成されます。


ユーザがWindowsホストから、またはWindowsホストとUNIXホストからホーム ディレクトリにアクセスし、ファイルシステム管理者がUNIXベースのユーザおよびグループを使用してファイルシステムへのアクセスを制御する場合には、このようなホーム ディレクトリ設定を使用できます。

[listing]
----
cluster::> vserver cifs share create -vserver vs1 -share-name %w -path %u ‑share-properties oplocks,browsable,changenotify,homedirectory

cluster::> vserver cifs share show -vserver vs1 -share-name %u

                      Vserver: vs1
                        Share: %w
     CIFS Server NetBIOS Name: VS1
                         Path: %u
             Share Properties: oplocks
                               browsable
                               changenotify
                               homedirectory
           Symlink Properties: enable
      File Mode Creation Mask: -
 Directory Mode Creation Mask: -
                Share Comment: -
                    Share ACL: Everyone / Full Control
File Attribute Cache Lifetime: -
                  Volume Name: -
                Offline Files: manual
Vscan File-Operations Profile: standard

cluster::> vserver cifs home-directory search-path add -vserver vs1 ‑path /home1

cluster::> vserver cifs home-directory search-path show -vserver vs1
Vserver     Position Path
----------- -------- -----------------
vs1         1        /home1

cluster::> vserver name-mapping create -vserver vs1 -direction win-unix ‑position 5 -pattern user1 -replacement unixuser1

cluster::> vserver name-mapping show -pattern user1
Vserver        Direction Position
-------------- --------- --------
vs1            win-unix  5        Pattern: user1
                              Replacement: unixuser1
----
.関連情報
* xref:create-home-directory-config-w-d-variables-task.adoc[%w および %d 変数を使用してホームディレクトリ構成を作成します]
* xref:home-directory-config-concept.adoc[追加のホームディレクトリ設定について学ぶ]
* xref:display-user-home-directory-path-task.adoc[ユーザーのホームディレクトリパスに関する情報を表示します]

