---
permalink: smb-admin/configure-bypass-traverse-checking-concept.html 
sidebar: sidebar 
keywords: bypass, traverse, user, privilege, permission, directory, allow, check, configure, storage, virtual, machine, svm, configure bypass traverse checking 
summary: トラバースチェックのバイパスは、トラバースするディレクトリに対する権限がユーザにない場合でも、ファイルのパスに含まれるすべてのディレクトリをユーザがトラバースできるかどうかを判断するユーザ権限です。トラバースチェックのバイパスを許可または拒否した場合の動作と、 Storage Virtual Machine （ SVM ）でのユーザに対するトラバースチェックのバイパスの設定方法を理解しておく必要があります。 
---
= トラバースチェックのバイパスの設定の概要
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
トラバースチェックのバイパスは、トラバースするディレクトリに対する権限がユーザにない場合でも、ファイルのパスに含まれるすべてのディレクトリをユーザがトラバースできるかどうかを判断するユーザ権限です。トラバースチェックのバイパスを許可または拒否した場合の動作と、 Storage Virtual Machine （ SVM ）でのユーザに対するトラバースチェックのバイパスの設定方法を理解しておく必要があります。



== トラバースチェックのバイパスを許可または拒否した場合の動作

* 許可した場合、ユーザがファイルにアクセスしようとすると、中間ディレクトリのトラバース権限が ONTAP でチェックされないで、ファイルへのアクセスの可否が判別されます。
* 拒否した場合、 ONTAP はファイルのパスにあるすべてのディレクトリでトラバース（実行）権限をチェックします。
+
中間ディレクトリのいずれかに「 X 」（トラバース権限）がない場合、 ONTAP はファイルへのアクセスを拒否します。





== トラバースチェックのバイパスを設定する

ONTAP CLI を使用するか、 Active Directory グループポリシーにこのユーザ権限を設定すると、トラバースチェックのバイパスを設定できます。

。 `SeChangeNotifyPrivilege` 権限は、ユーザにトラバースチェックのバイパスを許可するかどうかを制御します。

* この権限を SVM のローカル SMB ユーザまたはグループ、ドメインユーザまたはグループに追加すると、トラバースチェックのバイパスを許可できます。
* この権限を SVM のローカル SMB ユーザまたはグループ、ドメインユーザまたはグループから削除すると、トラバースチェックのバイパスを拒否できます。


SVM の次の BUILTIN グループには、デフォルトでトラバースチェックのバイパス権限が割り当てられています。

* `BUILTIN\Administrators`
* `BUILTIN\Power Users`
* `BUILTIN\Backup Operators`
* `BUILTIN\Users`
* `Everyone`


これらのいずれかのグループのメンバーにトラバースチェックのバイパスを許可したくない場合は、グループからこの権限を削除する必要があります。

CLI を使用して SVM のローカル SMB ユーザおよびグループのトラバースチェックのバイパスを設定する場合は、次の点に注意する必要があります。

* カスタムのローカルグループまたはドメイングループのメンバーにトラバースチェックのバイパスを許可する場合は、を追加する必要があります `SeChangeNotifyPrivilege` そのグループへの特権。
* ローカルユーザまたはドメインユーザにトラバースチェックのバイパスを個別に許可する場合に、そのユーザがその権限を持つグループのメンバーでないときは、を追加できます `SeChangeNotifyPrivilege` そのユーザアカウントに対する権限。
* ローカルまたはドメインのユーザまたはグループのトラバースチェックのバイパスを無効にするには、を削除します `SeChangeNotifyPrivilege` いつでも特権。
+
[NOTE]
====
特定のローカルまたはドメインのユーザまたはグループに対してトラバースチェックのバイパスを無効にするには、も削除する必要があります `SeChangeNotifyPrivilege` 権限を取得します `Everyone` グループ：

====


.関連情報
xref:allow-users-groups-bypass-directory-traverse-task.adoc[ユーザまたはグループにディレクトリのトラバースチェックのバイパスを許可する]

xref:disallow-users-groups-bypass-directory-traverse-task.adoc[ユーザまたはグループに対してディレクトリのトラバースチェックのバイパスを禁止します]

xref:configure-character-mappings-file-name-translation-task.adoc[ボリュームでの SMB ファイル名の変換のための文字マッピングを設定します]

xref:create-share-access-control-lists-task.html[SMB 共有のアクセス制御リストを作成]

xref:secure-file-access-storage-level-access-guard-concept.html[ストレージレベルのアクセス保護を使用してファイルアクセスを保護]

xref:list-supported-privileges-reference.adoc[サポートされる権限のリスト]

xref:add-privileges-local-domain-users-groups-task.html[ローカルまたはドメインのユーザまたはグループに権限を追加します]
