---
permalink: smb-admin/configure-ntfs-file-permissions-concept.html 
sidebar: sidebar 
keywords: configure, ntfs, file, permission, directories, directory, ontap, cli, enable, windows, client, how to configure ntfs file permissions using the ontap cli 
summary: ONTAP CLIを使用して、ファイルおよびディレクトリに対してNTFSファイル権限を設定できます。これにより、WindowsクライアントでSMB共有を使用してデータに接続することなくNTFSファイル権限を設定できます。 
---
= ONTAP CLIを使用したNTFSファイル権限の設定
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
ONTAP CLIを使用して、ファイルおよびディレクトリに対してNTFSファイル権限を設定できます。これにより、WindowsクライアントでSMB共有を使用してデータに接続することなくNTFSファイル権限を設定できます。

NTFSファイル権限を設定するには、NTFSセキュリティ記述子に関連付けられているNTFS Discretionary Access Control List（DACL；随意アクセス制御リスト）にエントリを追加します。その後、セキュリティ記述子がNTFSファイルおよびディレクトリに適用されます。

コマンドラインを使用して設定できるのはNTFSファイル権限のみです。CLIを使用してNFSv4 ACLを設定することはできません。

.手順
. NTFSセキュリティ記述子を作成します。
+
`vserver security file-directory ntfs create -vserver _svm_name_ -ntfs-sd _ntfs_security_descriptor_name_ -owner _owner_name_ -group _primary_group_name_ -control-flags-raw _raw_control_flags_`

. NTFSセキュリティ記述子にDACLを追加します。
+
`vserver security file-directory ntfs dacl add -vserver _svm_name_ -ntfs-sd _ntfs_security_descriptor_name_ -access-type {deny|allow} -account _account_name_ -rights {no-access|full-control|modify|read-and-execute|read|write} -apply-to {this-folder|sub-folders|files}`

. ファイルやディレクトリのセキュリティポリシーを作成します。
+
`vserver security file-directory policy create -vserver _svm_name_ -policy-name _policy_name_`


