---
permalink: smb-admin/configure-nis-ldap-name-services-svm-task.html 
sidebar: sidebar 
keywords: smb, access, map, unix, user, perform, data, ntfs, security-style, volume, windows, correspond, unix, information, nis, ldap, directory, store, name, configure nis or ldap name services on the svm 
summary: SMBアクセスでは、NTFSセキュリティ形式のボリューム内のデータにアクセスする場合でも、UNIXユーザへのユーザマッピングが常に実行されます。NISまたはLDAPディレクトリストアに情報が格納されているUNIXユーザにWindowsユーザをマッピングする場合や、ネームマッピングにLDAPを使用する場合は、SMBのセットアップ時にこれらのネームサービスを設定する必要があります。 
---
= ONTAP SMB SVMでのNISまたはLDAPネームサービスの設定
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
SMBアクセスでは、NTFSセキュリティ形式のボリューム内のデータにアクセスする場合でも、UNIXユーザへのユーザマッピングが常に実行されます。NISまたはLDAPディレクトリストアに情報が格納されているUNIXユーザにWindowsユーザをマッピングする場合や、ネームマッピングにLDAPを使用する場合は、SMBのセットアップ時にこれらのネームサービスを設定する必要があります。

.開始する前に
ネームサービスインフラに合わせてネームサービスデータベース設定をカスタマイズしておく必要があります。

.タスクの内容
SVMは、ネームサービスns-switchデータベースを使用して、指定されたネームサービスデータベースを検索するソースの順序を決定します。ns-switchソースには、、 `nis`、または `ldap`を任意に組み合わせて指定できます `files`。グループデータベースの場合、ONTAPは設定されているすべてのソースからグループメンバーシップを取得しようとし、統合されたグループメンバーシップ情報をアクセスチェックに使用します。UNIXグループ情報の取得時にこれらのソースのいずれかが使用できないと、ONTAPは完全なUNIXクレデンシャルを取得できず、以降のアクセスチェックが失敗することがあります。そのため、ns-switch設定でグループデータベースのすべてのns-switchソースが設定されていることを常に確認する必要があります。

デフォルトでは、SMBサーバは、すべてのWindowsユーザをローカルデータベースに格納されているデフォルトのUNIXユーザにマッピングし `passwd`ます。デフォルトの設定を使用する場合、SMBアクセスに対するNISまたはLDAP UNIXユーザおよびグループのネームサービスまたはLDAPユーザマッピングの設定はオプションです。

.手順
. UNIXユーザ、グループ、およびネットグループ情報がNISネームサービスによって管理されている場合は、NISネームサービスを次のように設定します。
+
.. コマンドを使用して、ネームサービスの現在の順番を確認します `vserver services name-service ns-switch show`。
+
この例では、ネームサービスソースとして使用できる3つのデータベース(`group`、 `passwd`および `netgroup`） `nis`がソースとしてのみを使用しています `files`。

+
`vserver services name-service ns-switch show -vserver vs1`

+
[listing]
----

                                               Source
Vserver         Database       Enabled         Order
--------------- ------------   ---------       ---------
vs1             hosts          true            dns,
                                               files
vs1             group          true            files
vs1             passwd         true            files
vs1             netgroup       true            files
vs1             namemap        true            files
----
+
ソースを `group`データベースと `passwd`データベースに追加する必要があります。必要に応じてデータベースにも `netgroup`追加できます `nis`。

.. コマンドを使用して、ネームサービスns-switchデータベースを必要な順番に調整します `vserver services name-service ns-switch modify`。
+
パフォーマンスを最大限に高めるには、SVMで設定する予定でないネームサービスデータベースにネームサービスを追加しないでください。

+
複数のネームサービスデータベースの設定を変更する場合は、変更する各ネームサービスデータベースに対して個別にコマンドを実行する必要があります。

+
この例では、 `nis`および `files`がデータベースおよび `passwd`のソースとしてこの順序で設定されてい `group`ます。残りのネームサービスデータベースは変更されません。

+
`vserver services name-service ns-switch modify -vserver vs1 -database group -sources nis,files` `vserver services name-service ns-switch modify -vserver vs1 -database passwd -sources nis,files`

.. コマンドを使用して、ネームサービスの順序が正しいことを確認し `vserver services name-service ns-switch show`ます。
+
`vserver services name-service ns-switch show -vserver vs1`

+
[listing]
----

                                               Source
Vserver         Database       Enabled         Order
--------------- ------------   ---------       ---------
vs1             hosts          true            dns,
                                               files
vs1             group          true            nis,
                                               files
vs1             passwd         true            nis,
                                               files
vs1             netgroup       true            files
vs1             namemap        true            files
----
.. NISネームサービス設定を作成します。+
`vserver services name-service nis-domain create -vserver <vserver_name> -domain <NIS_domain_name> -servers <NIS_server_IPaddress>,...`
+
`vserver services name-service nis-domain create -vserver vs1 -domain example.com -servers 10.0.0.60`

+
[NOTE]
====
ONTAP 9 .2以降では、 `-nis-servers`フィールドがフィールドに置き換わります `-servers`。この新しいフィールドには、NISサーバのホスト名またはIPアドレスを指定できます。

====
.. NISネームサービスが適切に設定されていることを確認します。 `vserver services name-service nis-domain show vserver <vserver_name>`
+
`vserver services name-service nis-domain show vserver vs1`

+
[listing]
----

Vserver       Domain              Server
------------- ------------------- ---------------
vs1           example.com         10.0.0.60
----


. UNIXユーザ、グループ、ネットグループ情報またはネームマッピングがLDAPネームサービスによって管理されている場合は、場所にある情報を使用してLDAPネームサービスを設定しますlink:../nfs-admin/index.html["NFSの管理"]。

