---
permalink: smb-admin/configure-access-restrictions-anonymous-users-task.html 
sidebar: sidebar 
keywords: anonymous, unauthenticated, user, information, network, cifs, server, option, configure, access, restriction, user, configure access restrictions for anonymous users 
summary: デフォルトでは、認証されていない匿名ユーザ（ null ユーザとも呼ばれます）は、ネットワーク上の特定の情報にアクセスできます。SMBサーバオプションを使用して、匿名ユーザに対するアクセス制限を設定できます。 
---
= 匿名ユーザに対するONTAP SMBアクセス制限の設定
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
デフォルトでは、認証されていない匿名ユーザ（ _null ユーザ）はネットワーク上の特定の情報にアクセスできます。SMBサーバオプションを使用して、匿名ユーザに対するアクセス制限を設定できます。

.タスクの内容
 `-restrict-anonymous`SMBサーバオプションは、Windowsのレジストリエントリに対応し `RestrictAnonymous`ます。

匿名ユーザは、ユーザ名と詳細、アカウントポリシー、共有名など、ネットワーク上のWindowsホストから特定のタイプのシステム情報をリストまたは列挙できます。匿名ユーザのアクセスを制御するには、次の3つのアクセス制限設定のいずれかを指定します。

|===
| 値 | 説明 


 a| 
`no-restriction` （デフォルト）
 a| 
匿名ユーザに対するアクセス制限を指定しません。



 a| 
`no-enumeration`
 a| 
匿名ユーザに対して列挙だけを制限します。



 a| 
`no-access`
 a| 
匿名ユーザに対してアクセスを制限します。

|===
.手順
. 権限レベルをadvancedに設定します。 `set -privilege advanced`
. restrict anonymousを設定します。 `vserver cifs options modify -vserver _vserver_name_ -restrict-anonymous {no-restriction|no-enumeration|no-access}`
. オプションが目的の値に設定されていることを確認します。 `vserver cifs options show -vserver _vserver_name_`
. admin権限レベルに戻ります。 `set -privilege admin`


.関連情報
xref:server-options-reference.adoc[使用できるSMBサーバオプション]
