---
permalink: smb-admin/control-domain-controller-discovery-task.html 
sidebar: sidebar 
keywords: ontap, modify, default, process, domain, controller, dc, enable, limit, site, pool, performance, improvement, environment, manage, manage domain controller discovery 
summary: ONTAP 9.3 以降では、ドメインコントローラ（ DC ）の検出に使用するデフォルトプロセスを変更できます。サイトまたは優先 DC のプールに検出を制限できるため、環境によってはパフォーマンスの向上につながります。 
---
= ドメインコントローラの検出を管理します
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
ONTAP 9.3 以降では、ドメインコントローラ（ DC ）の検出に使用するデフォルトプロセスを変更できます。サイトまたは優先 DC のプールに検出を制限できるため、環境によってはパフォーマンスの向上につながります。

.このタスクについて
デフォルトでは、任意の優先 DC 、ローカルサイト内のすべての DC 、およびすべてのリモート DC を含めて、使用可能なすべての DC が検出されます。そのため、一部の環境では、認証時および共有へのアクセス時にレイテンシが発生する可能性があります。使用する DC のプールが決まっている場合、またはリモート DC が不適切またはアクセスできない場合は、検出方法を変更できます。

ONTAP 9.3以降のリリースでは、 `discovery-mode` のパラメータ `cifs domain discovered-servers` コマンドでは、次のいずれかの検出オプションを選択できます。

* ドメイン内のすべての DC が検出されます。
* ローカルサイト内の DC だけが検出されます。
+
。 `default-site` SMBサーバのパラメータは、sites-and-servicesでサイトに割り当てられていないLIFでこのモードを使用するように定義できます。

* サーバの検出は実行せず、優先 DC のみを使用するように SMB サーバを設定します。
+
このモードを使用するには、最初に SMB サーバに対して優先 DC を定義する必要があります。



.ステップ
. 目的の検出オプションを指定します。 `vserver cifs domain discovered-servers discovery-mode modify -vserver _vserver_name_ -mode {all|site|none}`
+
のオプション `mode` パラメータ：

+
** `all`
+
使用可能なすべての DC を検出します（デフォルト）。

** `site`
+
DC の検出対象をサイトに制限します。

** `none`
+
優先 DC のみを使用し、検出は実行しません。




