---
permalink: smb-admin/create-share-access-control-lists-task.html 
sidebar: sidebar 
keywords: configuring, configure, permission, share, creating, create, control, list, acl, smb, enable, level, access, user, group, create smb share access control lists 
summary: SMB 共有の Access Control List （ ACL ；アクセス制御リスト）を作成して共有権限を設定すると、ユーザとグループの共有へのアクセスレベルを制御できます。 
---
= SMB 共有のアクセス制御リストを作成
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
SMB 共有の Access Control List （ ACL ；アクセス制御リスト）を作成して共有権限を設定すると、ユーザとグループの共有へのアクセスレベルを制御できます。

.このタスクについて
ローカルまたはドメインの Windows ユーザまたはグループ名、あるいは UNIX ユーザまたはグループ名を使用して共有レベルの ACL を設定できます。

新しいACLを作成する前に、デフォルトの共有ACLを削除する必要があります `Everyone / Full Control`セキュリティリスクの原因になります。

ワークグループモードでは、ローカルドメイン名は SMB サーバ名です。

.手順
. デフォルトの共有ACLを削除します。``vserver cifs share access-control delete -vserver _vserver_name_ -share _share_name_ -user-or-group everyone``
. 新しい ACL を設定します。
+
|===
| 設定する ACL に使用するアカウント | 入力するコマンド 


 a| 
Windows ユーザ
 a| 
`vserver cifs share access-control create -vserver _vserver_name_ -share _share_name_ -user-group-type windows -user-or-group _Windows_domain_name\\user_name_ -permission _access_right_`



 a| 
Windows グループ
 a| 
`vserver cifs share access-control create -vserver _vserver_name_ -share _share_name_ -user-group-type windows -user-or-group _Windows_group_name_ -permission _access_right_`



 a| 
UNIX ユーザ
 a| 
`vserver cifs share access-control create -vserver _vserver_name_ -share _share_name_ -user-group-type _unix-user_ -user-or-group _UNIX_user_name_ -permission access_right`



 a| 
UNIX グループ
 a| 
`vserver cifs share access-control create -vserver _vserver_name_ -share _share_name_ -user-group-type _unix-group_ -user-or-group _UNIX_group_name_ -permission access_right`

|===
. を使用して、共有に適用されたACLが正しいことを確認します `vserver cifs share access-control show` コマンドを実行します


.例
次のコマンドを実行すると `Change` 「vs1.example.com`"SVM:」の「sales」共有に対する「Sales Team」Windowsグループへのアクセス権

[listing]
----
cluster1::> vserver cifs share access-control create -vserver vs1.example.com -share sales -user-or-group "Sales Team" -permission Change

cluster1::> vserver cifs share access-control show
                 Share       User/Group              User/Group  Access
Vserver          Name        Name                    Type        Permission
---------------- ----------- --------------------    ---------   -----------
vs1.example.com  c$          BUILTIN\Administrators  windows     Full_Control
vs1.example.com  sales       DOMAIN\"Sales Team"     windows     Change
----
次のコマンドを実行すると `Read` 「vs2.example.com`"SVM:」上の「eng」共有に対する「engineering」UNIXグループの権限

[listing]
----
cluster1::> vserver cifs share access-control create -vserver vs2.example.com -share eng -user-group-type unix-group -user-or-group  eng -permission Read

cluster1::> vserver cifs share access-control show
                 Share       User/Group               User/Group  Access
Vserver          Name        Name                     Type        Permission
---------------- ----------- -------------------      ----------- -----------
vs2.example.com  c$          BUILTIN\Administrators   windows     Full_Control
vs2.example.com  eng         engineering              unix-group  Read
----
次のコマンドを実行すると、が表示さ `Change` 「Tiger Team」という名前のローカルWindowsグループおよびへのアクセス権 `Full_Control` 「vs1」SVM上の「datavol5」共有に対する「Sue Chang」という名前のローカルWindowsユーザへの権限：

[listing]
----
cluster1::> vserver cifs share access-control create -vserver vs1 -share datavol5 -user-group-type windows -user-or-group "Tiger Team" -permission Change

cluster1::> vserver cifs share access-control create -vserver vs1 -share datavol5 -user-group-type windows -user-or-group "Sue Chang" -permission Full_Control

cluster1::> vserver cifs share access-control show -vserver vs1
               Share       User/Group                  User/Group  Access
Vserver        Name        Name                        Type        Permission
-------------- ----------- --------------------------- ----------- -----------
vs1            c$          BUILTIN\Administrators      windows     Full_Control
vs1            datavol5    DOMAIN\"Tiger Team"         windows     Change
vs1            datavol5    DOMAIN\"Sue Chang"          windows     Full_Control
----