---
permalink: smb-admin/create-snapshot-config-previous-versions-access-task.html 
sidebar: sidebar 
keywords: previous, version, functionality, available, client, access, snapshot, copies, copy, enable, snapshot, exist, configuration, requirement, create a snapshot configuration to enable previous versions access 
summary: Snapshot コピーへのクライアントアクセスが有効で、 Snapshot コピーが存在する場合は、常に以前のバージョン機能を使用できます。Snapshot コピーの設定がこれらの要件を満たしていない場合は、要件を満たすように Snapshot コピーの設定を作成できます。 
---
= 以前のバージョン機能のアクセスを有効にする Snapshot 設定を作成します
:icons: font
:imagesdir: ../media/


[role="lead"]
Snapshot コピーへのクライアントアクセスが有効で、 Snapshot コピーが存在する場合は、常に以前のバージョン機能を使用できます。Snapshot コピーの設定がこれらの要件を満たしていない場合は、要件を満たすように Snapshot コピーの設定を作成できます。

.手順
. 以前のバージョン機能からのアクセスを許可する共有が格納されているボリュームに、 Snapshot ポリシーが関連付けられていない場合は、 Snapshot ポリシーをボリュームに関連付け、 volume modify コマンドを使用して有効にします。
+
volume modify コマンドの使用方法の詳細については ' マニュアル・ページを参照してください

. volume modify コマンドを使用して '-snap-dir' オプションを true に設定することにより ' スナップショット・コピーへのアクセスを有効にします
+
volume modify コマンドの使用方法の詳細については ' マニュアル・ページを参照してください

. volume show コマンドと volume snapshot policy show コマンドを使用して、 Snapshot ポリシーが有効になっていること、および Snapshot ディレクトリへのアクセスが有効になっていることを確認します。
+
volume show コマンドと volume snapshot policy show コマンドの使用の詳細については ' マニュアル・ページを参照してください

+
Snapshot ポリシーおよび Snapshot スケジュールの設定と管理の詳細については、を参照してください link:../data-protection/index.html["データ保護"]。



* 関連情報 *

link:../data-protection/index.html["データ保護"]
