---
permalink: smb-admin/create-volumes-without-specifying-junction-task.html 
sidebar: sidebar 
keywords: create, data, volume, junction, point, resultant, automatic, mount, nas, access, configure, smb, share, nfs, create data volumes without specifying junction points 
summary: ジャンクション ポイントを指定せずにデータ ボリュームを作成できます。作成したボリュームは、自動的にはマウントされず、NASアクセス用の設定に使用することはできません。このボリュームに対してSMB共有またはNFSエクスポートを設定するには、まず、ボリュームをマウントする必要があります。 
---
= ジャンクション ポイントを指定せずにONTAP SMBデータ ボリュームを作成する
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
ジャンクション ポイントを指定せずにデータ ボリュームを作成できます。作成したボリュームは、自動的にはマウントされず、NASアクセス用の設定に使用することはできません。このボリュームに対してSMB共有またはNFSエクスポートを設定するには、まず、ボリュームをマウントする必要があります。

.開始する前に
ボリュームを作成するアグリゲートがすでに存在している必要があります。

.手順
. 次のコマンドを使用して、ジャンクション ポイントのないボリュームを作成します： `volume create -vserver _vserver_name_ -volume _volume_name_ -aggregate _aggregate_name_ -size {integer[KB|MB|GB|TB|PB]} -security-style {ntfs|unix|mixed}`
+
ボリュームのセキュリティ形式の指定は省略可能です。セキュリティ形式を指定しない場合、Storage Virtual Machine（SVM）のルート ボリュームと同じセキュリティ形式を使用してボリュームが作成されます。ただし、ルート ボリュームのセキュリティ形式が、データ ボリュームには適切でないセキュリティ形式である場合もあります。解決が困難なファイル アクセスの問題ができるだけ発生しないように、ボリュームの作成時にセキュリティ形式を指定することを推奨します。

+
データボリュームをカスタマイズするために使用できるオプションパラメータは多数あります。link:https://docs.netapp.com/us-en/ontap-cli/volume-create.html["ONTAPコマンド リファレンス"^]の `volume create`の詳細をご覧ください。

. ボリュームがジャンクション ポイントなしで作成されたことを確認します： `volume show -vserver _vserver_name_ -volume _volume_name_ -junction`


.例
次の例では、ジャンクション ポイントにマウントされていない SVM vs1 上に「`sales`」という名前のボリュームを作成します：

[listing]
----
cluster1::> volume create -vserver vs1 -volume sales -aggregate aggr3 -size 20GB
[Job 3406] Job succeeded: Successful

cluster1::> volume show -vserver vs1 -junction
                     Junction                 Junction
Vserver   Volume     Active   Junction Path   Path Source
--------- ---------- -------- --------------- -----------
vs1       data       true     /data           RW_volume
vs1       home4      true     /eng/home       RW_volume
vs1       vs1_root   -        /               -
vs1       sales      -        -               -
----