---
permalink: smb-admin/create-branchcache-enabled-share-task.html 
sidebar: sidebar 
keywords: enable, branchcache, smb, create, share, setting, property, create a bracnhcache-enabled smb share 
summary: SMB 共有を作成するときに、 branchcache 共有プロパティを設定して、共有で BranchCache を有効にすることができます。 
---
= BranchCache が有効な SMB 共有を作成
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
SMB共有を作成するときに、を設定してBranchCacheを有効にすることができます `branchcache` 共有プロパティ。

.このタスクについて
* SMB 共有で BranchCache を有効にする場合は、共有のオフラインファイル設定を手動キャッシュに設定する必要があります。
+
これは、共有を作成するときのデフォルト設定です。

* BranchCache が有効な共有を作成するときに、オプションの共有パラメータを追加で指定することもできます。
* を設定できます `branchcache` Storage Virtual Machine（SVM）でBranchCacheが設定されておらず、有効になっていない場合でも、共有のプロパティ。
+
ただし、共有でキャッシュされたコンテンツを提供するには、 SVM で BranchCache を設定して有効にする必要があります。

* を使用する場合、共有に適用されるデフォルトの共有プロパティはないため `-share-properties` パラメータを使用する場合は、に加えて、共有に適用する他のすべての共有プロパティを指定する必要があります `branchcache` カンマで区切ったリストを使用して共有プロパティを指定します。
* 詳細については、のマニュアルページを参照してください `vserver cifs share create` コマンドを実行します


.ステップ
. BranchCacheが有効なSMB共有を作成します。+
`vserver cifs share create -vserver _vserver_name_ -share-name _share_name_ -path _path_ -share-properties branchcache[,...]`
. を使用して、SMB共有に対してBranchCache共有プロパティが設定されていることを確認します `vserver cifs share show` コマンドを実行します


.例
次のコマンドでは、パス「data」という名前のBranchCacheが有効なSMB共有を作成します `/data` SVM vs1。デフォルトでは、オフラインファイルの設定はに設定されます `manual`：

[listing]
----
cluster1::> vserver cifs share create -vserver vs1 -share-name data -path /data -share-properties branchcache,oplocks,browsable,changenotify

cluster1::> vserver cifs share show -vserver vs1 -share-name data
                      Vserver: vs1
                        Share: data
     CIFS Server NetBIOS Name: VS1
                         Path: /data
             Share Properties: branchcache
                               oplocks
                               browsable
                               changenotify
           Symlink Properties: enable
      File Mode Creation Mask: -
 Directory Mode Creation Mask: -
                Share Comment: -
                    Share ACL: Everyone / Full Control
File Attribute Cache Lifetime: -
                  Volume Name: data
                Offline Files: manual
Vscan File-Operations Profile: standard
----
.関連情報
xref:disable-branchcache-single-share-task.adoc[単一の SMB 共有での BranchCache の無効化]
