---
permalink: smb-admin/create-snapshot-config-previous-versions-access-task.html 
sidebar: sidebar 
keywords: previous, version, functionality, available, client, access, snapshot, copies, copy, enable, snapshot, exist, configuration, requirement, create a snapshot configuration to enable previous versions access 
summary: Snapshot コピーへのクライアントアクセスが有効で、 Snapshot コピーが存在する場合は、常に以前のバージョン機能を使用できます。Snapshot コピーの設定がこれらの要件を満たしていない場合は、要件を満たすように Snapshot コピーの設定を作成できます。 
---
= 以前のバージョン機能のアクセスを有効にする Snapshot 設定を作成します
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Snapshot コピーへのクライアントアクセスが有効で、 Snapshot コピーが存在する場合は、常に以前のバージョン機能を使用できます。Snapshot コピーの設定がこれらの要件を満たしていない場合は、要件を満たすように Snapshot コピーの設定を作成できます。

.手順
. 以前のバージョン機能からのアクセスを許可する共有が格納されているボリュームに、Snapshotポリシーが関連付けられていない場合は、を使用して、Snapshotポリシーをボリュームに関連付け、ポリシーを有効にします `volume modify` コマンドを実行します
+
を使用する方法の詳細については、を参照してください `volume modify` コマンドのマニュアルページを参照してください。

. を使用して、Snapshotコピーへのアクセスを有効にします `volume modify` コマンドを使用してを設定します `-snap-dir` オプションをに設定します `true`。
+
を使用する方法の詳細については、を参照してください `volume modify` コマンドのマニュアルページを参照してください。

. を使用して、Snapshotポリシーが有効になっていること、およびSnapshotディレクトリへのアクセスが有効になっていることを確認します `volume show` および `volume snapshot policy show` コマンド
+
を使用する方法の詳細については、を参照してください `volume show` および `volume snapshot policy show` コマンドについては、マニュアルページを参照してください。

+
Snapshot ポリシーおよび Snapshot スケジュールの設定と管理の詳細については、を参照してください link:../data-protection/index.html["データ保護"]。



.関連情報
link:../data-protection/index.html["データ保護"]
