---
permalink: smb-admin/default-administrative-shares-concept.html 
sidebar: sidebar 
keywords: create, cifs, server, storage, virtual, machine, svm, default, administrative, share, automatic, what the default administrative shares are 
summary: Storage Virtual Machine（SVM）上にCIFSサーバを作成すると、デフォルトの管理共有が自動的に作成されます。これらのデフォルトの共有とその用途について理解しておく必要があります。 
---
= デフォルトの管理用ONTAP SMB共有について学ぶ
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Storage Virtual Machine（SVM）上にCIFSサーバを作成すると、デフォルトの管理共有が自動的に作成されます。これらのデフォルトの共有とその用途について理解しておく必要があります。

CIFSサーバを作成すると、ONTAPによって次のデフォルトの管理共有が作成されます。


NOTE: ONTAP 9.8以降では、デフォルトでadmin$共有は作成されなくなりました。

* ipc$
* admin$（ONTAP 9.7以前のみ）
* c$


末尾が$の共有は非表示の共有で、デフォルトの管理共有はマイ コンピュータには表示されませんが、共有フォルダを使用して表示することができます。



== ipc$およびadmin$デフォルト管理共有の用途

ipc$およびadmin$共有はONTAPが使用する共有で、Windows管理者がSVM上にあるデータにアクセスするために使用することはできません。

* ipc$共有
+
ipc$共有は、プログラム間通信に必要な名前付きパイプを共有するリソースです。ipc$共有はコンピュータのリモート管理や、コンピュータの共有リソースを表示する際に使用されます。ipc$共有の共有設定、共有プロパティ、ACLは変更できません。また、ipc$共有は名前を変更することも削除することもできません。

* admin$共有（ONTAP 9.7以前のみ）
+

NOTE: ONTAP 9.8以降では、デフォルトでadmin$共有は作成されなくなりました。

+
admin$共有は、SVMのリモート管理に使用されます。このリソースのパスは、常にSVMルートへのパスです。admin$共有の共有設定、共有プロパティ、ACLは変更できません。また、admin$共有は名前を変更することも削除することもできません。





== c$デフォルト共有の用途

c$共有は、クラスタまたはSVMの管理者がSVMのルート ボリュームへのアクセスおよび管理に使用できる管理共有です。

c$共有には、次のような特徴があります。

* この共有へのパスは、常にSVMルート ボリュームへのパスで、変更することはできません。
* c$共有のデフォルトACLは、Administrator / Full Controlです。
+
このユーザは、BUILTIN\administratorです。デフォルトで、BUILTIN\administratorを共有にマッピングでき、マッピングされたルート ディレクトリ内のファイルやフォルダの表示、作成、変更、削除が可能です。このディレクトリ内のファイルやフォルダを管理すると、警告されます。

* c$共有のACLは変更できます。
* c$共有の設定や共有プロパティは変更できます。
* c$共有は削除できません。
* SVM管理者は、ネームスペース ジャンクションを横断することによって、マッピングされたc$共有から残りのSVMネームスペースにアクセスできます。
* c$共有には、Microsoft管理コンソールを使用してアクセスできます。


.関連情報
xref:configure-ntfs-windows-security-tab-task.adoc[Windows セキュリティ タブを使用して詳細なファイル権限を構成する]
