---
permalink: smb-admin/deploy-offline-files-concept.html 
sidebar: sidebar 
keywords: important, guideline, understand, deploy, offline, file, home, directory, share, showsnapshot, property, set, home, directories, directory, guidelines for deploying offline files 
summary: ホーム ディレクトリに showsnapshot 共有プロパティが設定されているホーム ディレクトリ共有にオフライン ファイルを展開するときに理解しておく必要がある重要なガイドラインがいくつかあります。 
---
= オフラインONTAP SMBファイルの導入に関するガイドライン
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
ホーム ディレクトリに `showsnapshot`共有プロパティが設定されているホーム ディレクトリ共有にオフライン ファイルを展開する場合に理解しておく必要がある重要なガイドラインがいくつかあります。

 `showsnapshot`共有プロパティがオフライン ファイルが構成されているホーム ディレクトリ共有に設定されている場合、Windows クライアントはユーザーのホーム ディレクトリ内の `~snapshot`フォルダーの下にあるすべてのスナップショットをキャッシュします。

Windows クライアントは、次のいずれか 1 つ以上の条件に該当する場合、ホーム ディレクトリの下のすべてのスナップショットをキャッシュします：

* ユーザーは、クライアントからホーム ディレクトリをオフラインで利用できるようにします。
+
ホーム ディレクトリ内の `~snapshot`フォルダーの内容が含まれ、オフラインで利用できるようになります。

* ユーザーは、フォルダー リダイレクトを構成して、 `My Documents`などのフォルダーをCIFSサーバー共有上にあるホーム ディレクトリのルートにリダイレクトします。
+
一部のWindowsクライアントでは、リダイレクトされたフォルダが自動的にオフラインで利用可能になる場合があります。フォルダがホームディレクトリのルートにリダイレクトされた場合、 `~snapshot`フォルダはキャッシュされたオフラインコンテンツに含まれます。



[NOTE]
====
 `~snapshot`フォルダがオフラインファイルに含まれるオフラインファイルの展開は避けるべきです。 `~snapshot`フォルダ内のスナップショットには、ONTAPがスナップショットを作成した時点のボリューム上のすべてのデータが含まれています。そのため、 `~snapshot`フォルダのオフラインコピーを作成すると、クライアントのローカルストレージが大量に消費され、オフラインファイルの同期中にネットワーク帯域幅が消費され、オフラインファイルの同期にかかる時間が長くなります。

====