---
permalink: smb-admin/deploy-offline-files-concept.html 
sidebar: sidebar 
keywords: important, guideline, understand, deploy, offline, file, home, directory, share, showsnapshot, property, set, home, directories, directory, guidelines for deploying offline files 
summary: ホームディレクトリに showsnapshot 共有プロパティが設定されているホームディレクトリ共有でオフラインファイルを導入する場合は、以下の重要なガイドラインについて理解しておく必要があります。 
---
= オフライン ONTAP SMB ファイルの導入に関するガイドライン
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
ホームディレクトリに共有プロパティが設定されているホームディレクトリ共有にオフラインファイルを導入する場合は、いくつかの重要なガイドラインについて理解しておく必要があり `showsnapshot`ます。

オフラインファイルが設定されているホームディレクトリ共有で共有プロパティが設定されている場合、 `showsnapshot`WindowsクライアントはすべてのSnapshotをユーザのホームディレクトリ内のフォルダの下にキャッシュします `~snapshot`。

次のいずれかに該当する場合、Windowsクライアントでは、すべてのSnapshotがホームディレクトリの下にキャッシュされます。

* ユーザが、ホームディレクトリをクライアントからオフラインで利用できるようにしている。
+
ホームディレクトリ内のフォルダの内容 `~snapshot`も含まれ、オフラインで使用できるようになります。

* ユーザが、などのフォルダをCIFSサーバ共有にあるホームディレクトリのルートにリダイレクトするようにフォルダリダイレクトを設定している `My Documents`。
+
Windows クライアントによっては、リダイレクトされたフォルダが自動的にオフラインで利用できるようになる場合があります。フォルダがホームディレクトリのルートにリダイレクトされる場合、その `~snapshot`フォルダはキャッシュされたオフラインコンテンツに含まれます。



[NOTE]
====
フォルダがオフラインファイルに含まれているオフラインファイルの展開 `~snapshot`は避ける必要があります。フォルダ内のSnapshot `~snapshot`には、ONTAPがSnapshotを作成した時点のボリューム上のすべてのデータが含まれています。そのため、フォルダのオフラインコピーを作成すると `~snapshot`、クライアントのローカルストレージが大量に消費され、オフラインファイルの同期中にネットワーク帯域幅が消費され、オフラインファイルの同期にかかる時間が長くなります。

====