---
permalink: smb-admin/deploy-offline-files-concept.html 
sidebar: sidebar 
keywords: important, guideline, understand, deploy, offline, file, home, directory, share, showsnapshot, property, set, home, directories, directory, guidelines for deploying offline files 
summary: ホームディレクトリに showsnapshot 共有プロパティが設定されているホームディレクトリ共有でオフラインファイルを導入する場合は、以下の重要なガイドラインについて理解しておく必要があります。 
---
= オフラインファイルの導入に関するガイドラインを参照してください
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
が搭載されたホームディレクトリ共有にオフラインファイルを導入する場合は、いくつかの重要なガイドラインについて理解しておく必要があります `showsnapshot` ホームディレクトリに設定された共有プロパティ。

状況に応じて `showsnapshot` オフラインファイルが設定されているホームディレクトリ共有で共有プロパティが設定されている場合、WindowsクライアントはすべてのSnapshotコピーをの下にキャッシュします `~snapshot` ユーザのホームディレクトリ内のフォルダ。

次のいずれかに該当する場合、 Windows クライアントでは、すべての Snapshot コピーがホームディレクトリの下にキャッシュされます。

* ユーザが、ホームディレクトリをクライアントからオフラインで利用できるようにしている。
+
の内容 `~snapshot` ホームディレクトリ内のフォルダが含まれ、オフラインで使用できるようになります。

* ユーザは、などのフォルダをリダイレクトするようにフォルダリダイレクトを設定します `My Documents` CIFSサーバ共有上のホームディレクトリのルートに移動します。
+
Windows クライアントによっては、リダイレクトされたフォルダが自動的にオフラインで利用できるようになる場合があります。フォルダがホームディレクトリのルートにリダイレクトされる場合は `~snapshot` フォルダは、キャッシュされたオフラインコンテンツに含まれます。



[NOTE]
====
ファイル導入をオフラインにします `~snapshot` フォルダはオフラインファイルに含まれないようにしてください。内のSnapshotコピー `~snapshot` フォルダには、ONTAP がSnapshotコピーを作成した時点のボリューム上のすべてのデータが格納されます。そのため、のオフラインコピーを作成します `~snapshot` フォルダは、クライアント上のローカルストレージを大量に消費し、オフラインファイルの同期中にネットワーク帯域幅を消費します。また、オフラインファイルの同期にかかる時間も長くなります。

====