---
permalink: smb-admin/deploy-offline-files-concept.html 
sidebar: sidebar 
keywords: important, guideline, understand, deploy, offline, file, home, directory, share, showsnapshot, property, set, home, directories, directory, guidelines for deploying offline files 
summary: ホームディレクトリに showsnapshot 共有プロパティが設定されているホームディレクトリ共有でオフラインファイルを導入する場合は、以下の重要なガイドラインについて理解しておく必要があります。 
---
= オフラインファイルの導入に関するガイドラインを参照してください
:icons: font
:imagesdir: ../media/


[role="lead"]
ホームディレクトリに 'howsnapshot' 共有プロパティが設定されているホームディレクトリ共有にオフラインファイルを展開する場合には ' 理解しておく必要がある重要なガイドラインがいくつかあります

オフラインファイルが構成されているホーム・ディレクトリ共有で 'howsnapshot' 共有プロパティが設定されている場合 'Windows クライアントは ' すべての Snapshot コピーを ' ユーザーのホーム・ディレクトリ内の ~snapshot フォルダの下にキャッシュします

次のいずれかに該当する場合、 Windows クライアントでは、すべての Snapshot コピーがホームディレクトリの下にキャッシュされます。

* ユーザが、ホームディレクトリをクライアントからオフラインで利用できるようにしている。
+
ホーム・ディレクトリ内の「 ~snapshot 」フォルダのコンテンツも含まれ、オフラインで利用できるようになります。

* ユーザが、「 My Documents 」などのフォルダを CIFS サーバ共有にあるホームディレクトリのルートにリダイレクトするようにフォルダリダイレクトを設定している。
+
Windows クライアントによっては、リダイレクトされたフォルダが自動的にオフラインで利用できるようになる場合があります。フォルダがホーム・ディレクトリのルートにリダイレクトされる場合 '~snapshot フォルダは ' キャッシュされるオフライン・コンテンツに含まれます



[NOTE]
====
オフライン・ファイルに '~snapshot フォルダが含まれるオフライン・ファイルの導入は避ける必要があります「 ~snapshot 」フォルダ内の Snapshot コピーには、 ONTAP が Snapshot コピーを作成した時点のボリューム上のすべてのデータが含まれます。したがって '~snapshot フォルダのオフライン・コピーを作成すると ' クライアント上のローカル・ストレージが大量に消費され ' オフライン・ファイルの同期中にネットワーク帯域幅が消費され ' オフライン・ファイルの同期にかかる時間が長くなります

====