---
permalink: smb-admin/disallow-users-groups-bypass-directory-traverse-task.html 
sidebar: sidebar 
keywords: user, traverse, directories, directory, path, file, permission, sechangenotifyprivilege, privilege, local, smb, group, storage, virtual, machine, svm, disallow users or groups from bypassing directory traverse checking 
summary: ユーザーがトラバースするディレクトリに対する権限を持っていないため、ファイルへのパス内のすべてのディレクトリをトラバースできないようにしたい場合は、Storage Virtual Machine（SVM）上のローカルSMBユーザーまたはグループからSeChangeNotifyPrivilege権限を削除できます。 
---
= ユーザーまたはグループがONTAP SMBディレクトリトラバースチェックをバイパスすることを禁止します
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
ユーザーがトラバースするディレクトリに対する権限を持っていないため、ファイルへのパス内のすべてのディレクトリをトラバースできないようにしたい場合は、ストレージ仮想マシン（SVM）上のローカルSMBユーザーまたはグループから `SeChangeNotifyPrivilege`権限を削除できます。

.開始する前に
権限を削除するローカルまたはドメインのユーザまたはグループがすでに存在している必要があります。

.タスク概要
ドメインのユーザまたはグループの権限を削除する場合、ONTAPでそれらのユーザやグループを検証するために、ドメイン コントローラに接続することがあります。ONTAPがドメイン コントローラに照会できない場合、コマンドが失敗することがあります。

.手順
. バイパストラバースチェックを禁止する： `vserver cifs users-and-groups privilege remove-privilege -vserver _vserver_name_ -user-or-group-name _name_ -privileges SeChangeNotifyPrivilege`
+
このコマンドは、 `-user-or-group-name _name_`パラメータの値で指定したローカルまたはドメインのユーザーまたはグループから `SeChangeNotifyPrivilege`権限を削除します。

. 指定されたユーザーまたはグループで走査チェックのバイパスが無効になっていることを確認します： `vserver cifs users-and-groups privilege show -vserver _vserver_name_ ‑user-or-group-name _name_`


.例
次のコマンドは、「`EXAMPLE\eng`」グループに属するユーザーがディレクトリトラバースチェックをバイパスすることを禁止します：

[listing]
----
cluster1::> vserver cifs users-and-groups privilege show -vserver vs1
Vserver   User or Group Name    Privileges
--------- --------------------- -----------------------
vs1       EXAMPLE\eng           SeChangeNotifyPrivilege

cluster1::> vserver cifs users-and-groups privilege remove-privilege -vserver vs1 -user-or-group-name EXAMPLE\eng -privileges SeChangeNotifyPrivilege

cluster1::> vserver cifs users-and-groups privilege show -vserver vs1
Vserver   User or Group Name    Privileges
--------- --------------------- -----------------------
vs1       EXAMPLE\eng           -
----
.関連情報
xref:allow-users-groups-bypass-directory-traverse-task.adoc[ユーザまたはグループに対するディレクトリのトラバース チェックのバイパスの許可]
