---
permalink: smb-admin/display-central-access-policy-rules-task.html 
sidebar: sidebar 
keywords: display, detail, information, central, access, policy, rule, policies, define, active, directory, group, object, display information about central access policy rules 
summary: Active Directory で定義されている集約型アクセスポリシーに関連付けられた集約型アクセスポリシールールに関する詳細情報を表示できます。また、集約型アクセスポリシーの GPO （グループポリシーオブジェクト）を介して CIFS サーバに適用されている集約型アクセスポリシールールに関する情報も表示できます。 
---
= 集約型アクセスポリシールールに関する情報を表示します
:icons: font
:imagesdir: ../media/


[role="lead"]
Active Directory で定義されている集約型アクセスポリシーに関連付けられた集約型アクセスポリシールールに関する詳細情報を表示できます。また、集約型アクセスポリシーの GPO （グループポリシーオブジェクト）を介して CIFS サーバに適用されている集約型アクセスポリシールールに関する情報も表示できます。

定義および適用されている集約型アクセスポリシールールに関する詳細情報を表示できます。デフォルトでは、次の情報が表示されます。

* SVM 名です
* 集約型アクセスルールの名前
* 説明
* 作成時間
* 修正日時
* 現在の権限
* 推奨される権限
* ターゲットリソース


|===
| 集約型アクセスポリシーに関連付けられた、情報を表示するすべての集約型アクセスポリシールール | 入力するコマンド 


 a| 
Active Directory で定義されています
 a| 
vserver cifs group-policy central-access-rule show-defined -vserver vserver_name ’



 a| 
CIFS サーバに適用されます
 a| 
vserver cifs group-policy central-access-rule show-applied -vserver vserver_name `

|===
次の例は、 Active Directory で定義されている集約型アクセスポリシーに関連付けられたすべての集約型アクセスポリシールールの情報を表示します。

[listing]
----
cluster1::> vserver cifs group-policy central-access-rule show-defined

Vserver    Name
---------- --------------------
vs1        r1
           Description: rule #1
         Creation Time: Tue Oct 22 09:33:48 2013
     Modification Time: Tue Oct 22 09:33:48 2013
   Current Permissions: O:SYG:SYD:AR(A;;FA;;;WD)
  Proposed Permissions: O:SYG:SYD:(A;;FA;;;OW)(A;;FA;;;BA)(A;;FA;;;SY)

vs1        r2
           Description: rule #2
         Creation Time: Tue Oct 22 10:27:57 2013
     Modification Time: Tue Oct 22 10:27:57 2013
   Current Permissions: O:SYG:SYD:AR(A;;FA;;;WD)
  Proposed Permissions: O:SYG:SYD:(A;;FA;;;OW)(A;;FA;;;BA)(A;;FA;;;SY)
----
次の例は、クラスタ上で Storage Virtual Machine （ SVM ）に適用されている集約型アクセスポリシーに関連付けられたすべての集約型アクセスポリシールールの情報を表示します。

[listing]
----
cluster1::> vserver cifs group-policy central-access-rule show-applied

Vserver    Name
---------- --------------------
vs1        r1
           Description: rule #1
         Creation Time: Tue Oct 22 09:33:48 2013
     Modification Time: Tue Oct 22 09:33:48 2013
   Current Permissions: O:SYG:SYD:AR(A;;FA;;;WD)
  Proposed Permissions: O:SYG:SYD:(A;;FA;;;OW)(A;;FA;;;BA)(A;;FA;;;SY)

vs1        r2
           Description: rule #2
         Creation Time: Tue Oct 22 10:27:57 2013
     Modification Time: Tue Oct 22 10:27:57 2013
   Current Permissions: O:SYG:SYD:AR(A;;FA;;;WD)
  Proposed Permissions: O:SYG:SYD:(A;;FA;;;OW)(A;;FA;;;BA)(A;;FA;;;SY)
----
xref:secure-file-access-dynamic-access-control-concept.adoc[DAC （ダイナミックアクセス制御）を使用したファイルアクセスの保護]

xref:display-gpo-config-task.adoc[GPO 設定に関する情報を表示します]

xref:display-central-access-policies-task.adoc[集約型アクセスポリシーに関する情報を表示します]
