---
permalink: smb-admin/display-restricted-group-gpos-task.html 
sidebar: sidebar 
keywords: display, detail, information, restrict, group, define, group, policy, object, gpo, active, directory, applied, apply, cifs, server, display detailed information about restricted group gpos 
summary: Active Directoryでグループポリシーオブジェクト（GPO）として定義されている制限されたグループ、およびCIFSサーバに適用されている制限されたグループに関する詳細情報を表示できます。 
---
= ONTAP SMB制限されたグループのGPOに関する情報を表示する
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Active Directoryでグループポリシーオブジェクト（GPO）として定義されている制限されたグループ、およびCIFSサーバに適用されている制限されたグループに関する詳細情報を表示できます。

.タスクの内容
デフォルトでは、次の情報が表示されます。

* グループポリシー名
* グループポリシーバージョン
* リンク
+
グループポリシーが設定されているレベルを指定します。指定可能な出力値は次のとおりです。

+
** `Local`グループポリシーがONTAPで設定されている状況
** `Site`グループポリシーがドメインコントローラのサイトレベルで設定されている場合
** `Domain`グループポリシーがドメインコントローラのドメインレベルで設定されている場合
** `OrganizationalUnit`グループポリシーがドメインコントローラのOrganizational Unit（OU；組織単位）レベルで設定されている場合
** `RSOP`さまざまなレベルで定義されたすべてのグループポリシーから派生した一連のポリシー


* 制限されたグループ名
* 制限されたグループに属するユーザとグループ、および属さないユーザとグループ
* 制限されたグループが追加されているグループのリスト
+
グループは、ここにリストされているグループ以外のグループのメンバーになることができます。



.ステップ
. 次のいずれかの操作を実行して、制限されたグループのすべてのGPOに関する情報を表示します。
+
|===
| 情報を表示する制限されたグループのすべての GPO | 入力するコマンド 


 a| 
Active Directoryデテイギ
 a| 
`vserver cifs group-policy restricted-group show-defined -vserver vserver_name`



 a| 
CIFSサアハニテキヨウ
 a| 
`vserver cifs group-policy restricted-group show-applied -vserver vserver_name`

|===


.例
次の例は、CIFS対応のvs1という名前のSVMが属するActive Directoryドメインで定義されている、制限されたグループのGPOに関する情報を表示します。

[listing]
----
cluster1::> vserver cifs group-policy restricted-group show-defined -vserver vs1

Vserver: vs1
-------------

     Group Policy Name: gpo1
               Version: 16
                  Link: OrganizationalUnit
            Group Name: group1
               Members: user1
              MemberOf: EXAMPLE\group9

     Group Policy Name: Resultant Set of Policy
               Version: 0
                  Link: RSOP
            Group Name: group1
               Members: user1
              MemberOf: EXAMPLE\group9
----
次の例では、CIFS対応のSVM vs1に適用されている、制限されたグループのGPOに関する情報を表示します。

[listing]
----
cluster1::> vserver cifs group-policy restricted-group show-applied -vserver vs1

Vserver: vs1
-------------

     Group Policy Name: gpo1
               Version: 16
                  Link: OrganizationalUnit
            Group Name: group1
               Members: user1
              MemberOf: EXAMPLE\group9

     Group Policy Name: Resultant Set of Policy
               Version: 0
                  Link: RSOP
            Group Name: group1
               Members: user1
              MemberOf: EXAMPLE\group9
----
.関連情報
xref:display-gpo-config-task.adoc[GPO設定に関する情報の表示]
