---
permalink: smb-admin/display-privilege-overrides-task.html 
sidebar: sidebar 
keywords: display, information, custom, privilege, assign, domain, local, user, account, group, desire, right, applied, apply, display information about privilege overrides 
summary: ドメインまたはローカルのユーザアカウントまたはグループに割り当てられているカスタムPrivilegesに関する情報を表示できます。この情報は、必要なユーザー権限が適用されているかどうかを判断するのに役立ちます。 
---
= ONTAPの権限の上書きに関する情報を表示する
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
ドメインまたはローカルのユーザアカウントまたはグループに割り当てられているカスタムPrivilegesに関する情報を表示できます。この情報は、必要なユーザー権限が適用されているかどうかを判断するのに役立ちます。

.ステップ
. 次のいずれかを実行します。
+
|===
| 表示する情報 | 入力するコマンド 


 a| 
Storage Virtual Machine（SVM）のすべてのドメインおよびローカルのユーザとグループ用のカスタムPrivileges
 a| 
`vserver cifs users-and-groups privilege show -vserver _vserver_name_`



 a| 
SVMの特定のドメインまたはローカルのユーザとグループのカスタムPrivileges
 a| 
`vserver cifs users-and-groups privilege show -vserver _vserver_name_ -user-or-group-name _name_`

|===
+
このコマンドを実行するときに選択できるオプションのパラメータがほかにもあります。の詳細については `vserver cifs users-and-groups privilege show`、をlink:https://docs.netapp.com/us-en/ontap-cli/vserver-cifs-users-and-groups-privilege-show.html["ONTAPコマンド リファレンス"^]参照してください。



.例
次のコマンドは、SVM vs1のローカルまたはドメインのユーザとグループに明示的に関連付けられているすべてのPrivilegesを表示します。

[listing]
----
cluster1::> vserver cifs users-and-groups privilege show -vserver vs1
Vserver    User or Group Name     Privileges
--------- ---------------------   ---------------
vs1       BUILTIN\Administrators  SeTakeOwnershipPrivilege
                                  SeRestorePrivilege
vs1       CIFS_SERVER\sue         SeTcbPrivilege
                                  SeTakeOwnershipPrivilege
----