---
permalink: smb-admin/display-session-task.html 
sidebar: sidebar 
keywords: display, information, establish, smb, session, connection, session, id, ip, address, workstation, protection, level, nondisruptive, operation, display smb session information 
summary: SMB接続、SMB Session ID、セッションを使用しているワークステーションのIPアドレスなど、確立されているSMBセッションに関する情報を表示できます。セッションの SMB プロトコルバージョンおよび継続的可用性を備えた保護レベルに関する情報を表示できます。この情報は、セッションでノンストップオペレーションがサポートされているかどうかを確認するのに役立ちます。 
---
= ONTAP SMBセッション情報を表示する
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
SMB接続、SMB Session ID、セッションを使用しているワークステーションのIPアドレスなど、確立されているSMBセッションに関する情報を表示できます。セッションのSMBプロトコルバージョンや継続的可用性を備えた保護のレベルに関する情報を表示できます。この情報は、セッションでノンストップオペレーションがサポートされているかどうかを確認するのに役立ちます。

.タスクの内容
SVM上のすべてのセッションに関する情報を要約形式で表示できます。ただし、多くの場合、大量の出力が返されます。オプションのパラメータを指定すると、出力に表示される情報をカスタマイズできます。

* オプションのパラメータを使用すると、選択したフィールドに関する出力を表示できます `-fields`。
+
と入力して、使用できるフィールドを指定できます `-fields ?`。

* パラメータを使用すると、確立されたSMBセッションに関する詳細情報を表示できます `-instance`。
* パラメータまたは `-instance`パラメータは、単独で使用することも、他のオプションのパラメータと組み合わせて使用することもできます `-fields`。


.ステップ
. 次のいずれかを実行します。
+
|===
| 表示する SMB セッション情報 | 入力するコマンド 


 a| 
SVM上のすべてのセッション（要約形式）
 a| 
`vserver cifs session show -vserver vserver_name`



 a| 
指定した接続IDのファイル
 a| 
`vserver cifs session show -vserver vserver_name -connection-id integer`



 a| 
指定したワークステーションのIPアドレスから
 a| 
`vserver cifs session show -vserver vserver_name -address workstation_IP_address`



 a| 
指定したLIF IPアドレスのファイル
 a| 
`vserver cifs session show -vserver vserver_name -lif-address LIF_IP_address`



 a| 
指定したノードのオブジェクト
 a| 
`vserver cifs session show -vserver vserver_name -node {node_name|local}`



 a| 
指定したWindowsユーザからのセッション
 a| 
`vserver cifs session show -vserver vserver_name -windows-user domain_name\\user_name`



 a| 
指定した認証メカニズムを使用している場合
 a| 
`vserver cifs session show -vserver vserver_name -auth-mechanism {NTLMv1|NTLMv2|Kerberos|Anonymous}`



 a| 
指定したプロトコルバージョンを使用している場合
 a| 
`vserver cifs session show -vserver vserver_name -protocol-version {SMB1|SMB2|SMB2_1|SMB3|SMB3_1}`

[NOTE]
====
継続的可用性を備えた保護とSMBマルチチャネルは、SMB 3.0以降のセッションでのみ使用できます。該当するすべてのセッションのステータスを表示するには、このパラメータの値を以降に設定します。 `SMB3`

====


 a| 
指定したレベルの継続的可用性を備えた保護を使用しているセッション
 a| 
`vserver cifs session show -vserver vserver_name -continuously-available {No|Yes|Partial}`

[NOTE]
====
継続的可用性のステータスがの場合は `Partial`、継続的可用性を備えた開いているファイルがセッションに少なくとも1つ含まれていますが、継続的可用性を備えた保護を使用して開かれていないファイルがセッションに含まれています。コマンドを使用すると、確立されたセッションのファイルのうち、継続的可用性を備えた保護を使用して開かれていないファイルを確認できます `vserver cifs sessions file show`。

====


 a| 
指定したSMB署名セッションステータスのセッション
 a| 
`vserver cifs session show -vserver vserver_name -is-session-signed {true|false}`

|===


.例
次のコマンドを実行すると、IPアドレスが10.1.1.1のワークステーションから確立されたSVM vs1上のセッションに関するセッション情報が表示されます。

[listing]
----
cluster1::> vserver cifs session show -address 10.1.1.1
Node:    node1
Vserver: vs1
Connection Session                                    Open         Idle
ID          ID      Workstation      Windows User    Files         Time
----------  ------- ---------------- ------------- ------- ------------
3151272279,
3151272280,
3151272281  1       10.1.1.1         DOMAIN\joe          2          23s
----
次のコマンドを実行すると、SVM vs1上の継続的可用性を備えた保護を使用するセッションに関する詳細なセッション情報が表示されます。接続はドメインアカウントを使用して行われました。

[listing]
----
cluster1::> vserver cifs session show -instance -continuously-available Yes

                        Node: node1
                     Vserver: vs1
                  Session ID: 1
               Connection ID: 3151274158
Incoming Data LIF IP Address: 10.2.1.1
      Workstation IP address: 10.1.1.2
    Authentication Mechanism: Kerberos
                Windows User: DOMAIN\SERVER1$
                   UNIX User: pcuser
                 Open Shares: 1
                  Open Files: 1
                  Open Other: 0
              Connected Time: 10m 43s
                   Idle Time: 1m 19s
            Protocol Version: SMB3
      Continuously Available: Yes
           Is Session Signed: false
       User Authenticated as: domain-user
                NetBIOS Name: -
       SMB Encryption Status: Unencrypted
----
次のコマンドを実行すると、SVM vs1上のSMB 3.0とSMBマルチチャネルを使用しているセッションに関するセッション情報が表示されます。この例では、ユーザはLIF IPアドレスを使用してSMB 3.0対応のクライアントからこの共有に接続しています。そのため、認証メカニズムはデフォルトのNTLMv2になっています。継続的可用性を備えた保護を使用して接続するには、Kerberos認証を使用して接続を確立する必要があります。

[listing]
----
cluster1::> vserver cifs session show -instance -protocol-version SMB3

                        Node: node1
                     Vserver: vs1
                  Session ID: 1
              **Connection IDs: 3151272607,31512726078,3151272609
            Connection Count: 3**
Incoming Data LIF IP Address: 10.2.1.2
      Workstation IP address: 10.1.1.3
    Authentication Mechanism: NTLMv2
                Windows User: DOMAIN\administrator
                   UNIX User: pcuser
                 Open Shares: 1
                  Open Files: 0
                  Open Other: 0
              Connected Time: 6m 22s
                   Idle Time: 5m 42s
            Protocol Version: SMB3
      Continuously Available: No
           Is Session Signed: false
       User Authenticated as: domain-user
                NetBIOS Name: -
       SMB Encryption Status: Unencrypted
----
.関連情報
xref:display-open-files-task.adoc[開いているSMBファイルに関する情報の表示]
