---
permalink: smb-admin/display-local-users-task.html 
sidebar: sidebar 
keywords: display, list, local, user, summary, form, determine, account, setting, configure, specific, user, detail, troubleshoot, authentication, file, access, issue, display information about local users 
summary: すべてのローカルユーザのリストを要約形式で表示できます。特定のユーザに対して設定されているアカウント設定を確認するには、そのユーザの詳細なアカウント情報、および複数のユーザのアカウント情報を表示します。この情報は、ユーザの設定を変更する必要があるかどうかを判断する場合や、認証やファイルアクセスに関する問題のトラブルシューティングを行う場合にも役立ちます。 
---
= ローカルユーザに関する情報を表示します
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
すべてのローカルユーザのリストを要約形式で表示できます。特定のユーザに対して設定されているアカウント設定を確認するには、そのユーザの詳細なアカウント情報、および複数のユーザのアカウント情報を表示します。この情報は、ユーザの設定を変更する必要があるかどうかを判断する場合に加えて、認証やファイルアクセスに関する問題のトラブルシューティングを行う場合にも役立ちます。

.このタスクについて
ユーザのパスワードに関する情報は表示されません。

.ステップ
. 次のいずれかを実行します。
+
|===
| 状況 | 入力するコマンド 


 a| 
Storage Virtual Machine （ SVM ）のすべてのユーザに関する情報を表示する
 a| 
vserver cifs users-and-groups local-user show -vserver _vserver_name _



 a| 
特定のユーザの詳細なアカウント情報を表示する
 a| 
vserver cifs users-and-groups local-user show -instance -vserver vserver_name __ user-name _user_name

|===
+
コマンドの実行時に選択できるオプションのパラメータがほかにもあります。詳細については、のマニュアルページを参照してください。



.例
次の例は、 SVM vs1 のすべてのローカルユーザに関する情報を表示します。

[listing]
----
cluster1::> vserver cifs users-and-groups local-user show -vserver vs1
Vserver  User Name                   Full Name     Description
-------- --------------------------- ------------- -------------
vs1      CIFS_SERVER\Administrator   James Smith   Built-in administrator account
vs1      CIFS_SERVER\sue             Sue   Jones
----