---
permalink: smb-admin/display-types-users-connected-task.html 
sidebar: sidebar 
keywords: display, information, type, connect, smb, session, appropriate, type, storage, virtual, machine, svm 
summary: SMBセッション経由で接続しているユーザのタイプを表示できます。これは、適切なタイプのユーザのみがStorage Virtual Machine（SVM）上のSMBセッション経由で接続していることを確認するのに役立ちます。 
---
= ONTAP SMBセッションを介して接続されるユーザーの種類に関する情報を表示します
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
SMBセッション経由で接続しているユーザのタイプを表示できます。これは、適切なタイプのユーザのみがStorage Virtual Machine（SVM）上のSMBセッション経由で接続していることを確認するのに役立ちます。

.タスク概要
SMBセッション経由で接続できるのは、次のタイプのユーザです。

* `local-user`
+
ローカル CIFS ユーザーとして認証

* `domain-user`
+
ドメイン ユーザーとして認証されている（CIFS サーバーのホーム ドメインまたは信頼されたドメインのいずれかから）

* `guest-user`
+
ゲスト ユーザーとして認証されました

* `anonymous-user`
+
匿名またはnullユーザーとして認証されました



.手順
. SMB セッションを介して接続されているユーザーのタイプを判別します： `vserver cifs session show -vserver _vserver_name_ -windows-user _windows_user_name_ -fields windows-user,address,lif-address,user-type`
+
|===
| 確立されたセッションのユーザー タイプ情報を表示する場合： | 入力するコマンド 


 a| 
指定されたユーザー タイプのすべてのセッション
 a| 
`vserver cifs session show -vserver _vserver_name_ -user-type {local-user|domain-user|guest-user|anonymous-user}`



 a| 
特定のユーザーの場合
 a| 
`vserver cifs session show -vserver _vserver_name_ -windows-user _windows_user_name_ -fields windows-user,address,lif-address,user-type`

|===


.例
次のコマンドは、ユーザー「` iepubs\user1`」によって確立された SVM vs1 上のセッションのユーザー タイプに関するセッション情報を表示します：

[listing]
----
cluster1::> vserver cifs session show -vserver pub1 -windows-user iepubs\user1 -fields windows-user,address,lif-address,user-type
node      vserver session-id connection-id lif-address  address       windows-user         user-type
--------- ------- ---------- ------------- ------------ ------------- -------------------- -----------
pub1node1 pub1    1          3439441860    10.0.0.1     10.1.1.1      IEPUBS\user1         domain-user
----