---
permalink: smb-admin/display-group-memberships-local-users-task.html 
sidebar: sidebar 
keywords: display, information, local, group, user, belong, folder, determine, access, file, useful, troubleshoot, display information about group memberships for local users 
summary: ローカル ユーザが属しているローカル グループに関する情報を表示できます。この情報を使用して、ファイルやフォルダに対してユーザにどのレベルのアクセスを付与するかを決定できます。この情報は、ファイルやフォルダに対してユーザに付与すべきアクセス権を決定する際や、ファイル アクセスに関する問題のトラブルシューティングを行う際に役立ちます。 
---
= ローカル ユーザのONTAP SMBグループ メンバーシップに関する情報を表示します
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
ローカル ユーザが属しているローカル グループに関する情報を表示できます。この情報を使用して、ファイルやフォルダに対してユーザにどのレベルのアクセスを付与するかを決定できます。この情報は、ファイルやフォルダに対してユーザに付与すべきアクセス権を決定する際や、ファイル アクセスに関する問題のトラブルシューティングを行う際に役立ちます。

.タスク概要
コマンドをカスタマイズして、必要な情報のみを表示することができます。

.手順
. 次のいずれかを実行します。
+
|===
| 状況 | コマンドを入力してください... 


 a| 
指定したローカル ユーザのローカル ユーザ メンバーシップに関する情報を表示する
 a| 
`vserver cifs users-and-groups local-user show-membership -user-name _user_name_`



 a| 
このローカル ユーザが属しているローカル グループのローカル ユーザ メンバーシップに関する情報を表示する
 a| 
`vserver cifs users-and-groups local-user show-membership -membership _group_name_`



 a| 
指定したStorage Virtual Machine（SVM）に関連付けられているローカル ユーザのユーザ メンバーシップに関する情報を表示する
 a| 
`vserver cifs users-and-groups local-user show-membership -vserver _vserver_name_`



 a| 
指定したSVM上のすべてのローカル ユーザに関する詳細情報を表示する
 a| 
`vserver cifs users-and-groups local-user show-membership -instance ‑vserver _vserver_name_`

|===


.例
次の例では、SVM vs1 上のすべてのローカル ユーザのメンバーシップ情報を表示します。ユーザ「`CIFS_SERVER\Administrator`」は「`BUILTIN\Administrators`」グループのメンバーであり、「`CIFS_SERVER\sue`」は「`CIFS_SERVER\g1`」グループのメンバーです：

[listing]
----
cluster1::> vserver cifs users-and-groups local-user show-membership -vserver vs1
Vserver    User Name                    Membership
---------- ---------------------------- ------------------------
vs1        CIFS_SERVER\Administrator    BUILTIN\Administrators
           CIFS_SERVER\sue              CIFS_SERVER\g1
----