---
permalink: smb-admin/display-statistics-task.html 
sidebar: sidebar 
keywords: display, various, statistic, cifs, smb, audit, branchcache, has, monitor, performance, diagnose, issue 
summary: CIFS と SMB 、監査、および BranchCache ハッシュに関する統計など、さまざまな統計を表示して、パフォーマンスを監視し、問題を診断することができます。 
---
= 統計情報を表示します
:icons: font
:imagesdir: ../media/


[role="lead"]
CIFS と SMB 、監査、および BranchCache ハッシュに関する統計など、さまざまな統計を表示して、パフォーマンスを監視し、問題を診断することができます。

オブジェクトに関する情報を表示する前に、 [ 統計の開始 ] コマンドと [ 統計の停止 ] コマンドを使用してデータサンプルを収集しておく必要があります。

.手順
. 権限レベルを advanced に設定します。「 set -privilege advanced 」
. 次のいずれかを実行します。
+
|===
| 統計を表示する対象 | 入力するコマンド 


 a| 
SMB のすべてのバージョン
 a| 
'tstatistics show -object CIFS' のように表示されます



 a| 
SMB 1.0
 a| 
'statistics show -object smb1'



 a| 
SMB 2.x と SMB 3.0
 a| 
統計表示オブジェクト smb2



 a| 
ノードの CIFS サブシステム
 a| 
'tstatistics show -object nblade_cifs'



 a| 
マルチプロトコルの監査
 a| 
'statistics show -object audit_ng



 a| 
BranchCache ハッシュサービス
 a| 
'statistics show-object hashd



 a| 
動的 DNS
 a| 
'tstatistics show -object ddns_update'

|===
+
詳細については、各コマンドのマニュアルページを参照してください。

. admin 権限レベルに戻ります。「 set -privilege admin 」


xref:determine-statistics-objects-counters-available-task.adoc[使用可能な統計オブジェクトと統計カウンタの確認]

xref:monitor-signed-session-statistics-task.adoc[SMB 署名済みセッションの統計の監視]

xref:display-branchcache-statistics-task.adoc[BranchCache 統計を表示します]

xref:statistics-monitor-automatic-node-referral-task.adoc[統計を使用した自動ノードリファーラルのアクティビティの監視]

link:../smb-hyper-v-sql/index.html["Microsoft Hyper-V および SQL Server 向けの SMB の設定"]

link:../performance-config/index.html["パフォーマンス監視のセットアップ"]
