---
permalink: smb-admin/display-file-security-ntfs-style-volumes-task.html 
sidebar: sidebar 
keywords: display, information, file, directory, security, ntfs, security-style, volume, style, effective, permission, applied, apply, information, dos, attribute, result, validate, security, configuration, troubleshoot, issues, display information about file security on ntfs security-style volumes 
summary: セキュリティ形式と有効なセキュリティ形式、適用されている権限、DOS属性に関する情報など、NTFSセキュリティ形式のボリューム上にあるファイルやディレクトリのセキュリティに関する情報を表示できます。この結果を使用して、セキュリティ設定の検証や、ファイル アクセスに関する問題のトラブルシューティングを行うことができます。 
---
= ONTAP SMBファイルセキュリティに関する情報をNTFSセキュリティ形式のボリューム上に表示します
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
セキュリティ形式と有効なセキュリティ形式、適用されている権限、DOS属性に関する情報など、NTFSセキュリティ形式のボリューム上にあるファイルやディレクトリのセキュリティに関する情報を表示できます。この結果を使用して、セキュリティ設定の検証や、ファイル アクセスに関する問題のトラブルシューティングを行うことができます。

.タスク概要
Storage Virtual Machine（SVM）の名前、およびファイルまたはフォルダのセキュリティ情報を表示するデータのパスを入力する必要があります。出力には要約または詳細な一覧を表示できます。

* NTFSセキュリティ形式のボリュームとqtreeでは、NTFSファイル権限およびWindowsのユーザとグループのみを使用してファイルのアクセス権を判断するため、UNIX関連の出力フィールドのUNIXファイル権限情報は表示のみです。
* ACL出力は、NTFSセキュリティが適用されたファイルとフォルダについて表示されます。
* ストレージレベルのアクセス保護セキュリティは、ボリュームのルートまたはqtreeで設定できるので、ストレージレベルのアクセス保護が設定されているボリュームまたはqtreeパスの出力には、通常のファイルACLとストレージレベルのアクセス保護ACLの両方が表示されることがあります。
* そのファイルまたはディレクトリ パスにダイナミック アクセス制御が設定されていれば、ダイナミック アクセス制御ACEに関する情報も出力に表示されます。


.手順
. ファイルとディレクトリのセキュリティ設定を必要な詳細レベルで表示します。
+
|===
| 情報を表示する場合... | 入力するコマンド 


 a| 
要約形式
 a| 
`vserver security file-directory show -vserver _vserver_name_ -path _path_`



 a| 
詳細
 a| 
`vserver security file-directory show -vserver _vserver_name_ -path _path_ -expand-mask true`

|===


.例
次の例では、SVM vs1 内のパス `/vol4`に関するセキュリティ情報を表示します：

[listing]
----
cluster::> vserver security file-directory show -vserver vs1 -path /vol4

                                 Vserver: vs1
                               File Path: /vol4
                       File Inode Number: 64
                          Security Style: ntfs
                         Effective Style: ntfs
                          DOS Attributes: 10
                  DOS Attributes in Text: ----D---
                 Expanded Dos Attributes: -
                            Unix User Id: 0
                           Unix Group Id: 0
                          Unix Mode Bits: 777
                  Unix Mode Bits in Text: rwxrwxrwx
                                    ACLs: NTFS Security Descriptor
                                          Control:0x8004
                                          Owner:BUILTIN\Administrators
                                          Group:BUILTIN\Administrators
                                          DACL - ACEs
                                          ALLOW-Everyone-0x1f01ff
                                          ALLOW-Everyone-0x10000000-OI|CI|IO
----
次の例では、SVM vs1 内のパス `/data/engineering`に関する拡張マスク付きのセキュリティ情報を表示します：

[listing]
----
cluster::> vserver security file-directory show -vserver vs1 -path -path /data/engineering -expand-mask true

                Vserver: vs1
              File Path: /data/engineering
      File Inode Number: 5544
         Security Style: ntfs
        Effective Style: ntfs
         DOS Attributes: 10
 DOS Attributes in Text: ----D---
Expanded Dos Attributes: 0x10
     ...0 .... .... .... = Offline
     .... ..0. .... .... = Sparse
     .... .... 0... .... = Normal
     .... .... ..0. .... = Archive
     .... .... ...1 .... = Directory
     .... .... .... .0.. = System
     .... .... .... ..0. = Hidden
     .... .... .... ...0 = Read Only
           Unix User Id: 0
          Unix Group Id: 0
         Unix Mode Bits: 777
 Unix Mode Bits in Text: rwxrwxrwx
                   ACLs: NTFS Security Descriptor
                         Control:0x8004

                             1... .... .... .... = Self Relative
                             .0.. .... .... .... = RM Control Valid
                             ..0. .... .... .... = SACL Protected
                             ...0 .... .... .... = DACL Protected
                             .... 0... .... .... = SACL Inherited
                             .... .0.. .... .... = DACL Inherited
                             .... ..0. .... .... = SACL Inherit Required
                             .... ...0 .... .... = DACL Inherit Required
                             .... .... ..0. .... = SACL Defaulted
                             .... .... ...0 .... = SACL Present
                             .... .... .... 0... = DACL Defaulted
                             .... .... .... .1.. = DACL Present
                             .... .... .... ..0. = Group Defaulted
                             .... .... .... ...0 = Owner Defaulted

                         Owner:BUILTIN\Administrators
                         Group:BUILTIN\Administrators
                         DACL - ACEs
                           ALLOW-Everyone-0x1f01ff
                             0... .... .... .... .... .... .... .... = Generic Read
                             .0.. .... .... .... .... .... .... .... = Generic Write
                             ..0. .... .... .... .... .... .... .... = Generic Execute
                             ...0 .... .... .... .... .... .... .... = Generic All
                             .... ...0 .... .... .... .... .... .... = System Security
                             .... .... ...1 .... .... .... .... .... = Synchronize
                             .... .... .... 1... .... .... .... .... = Write Owner
                             .... .... .... .1.. .... .... .... .... = Write DAC
                             .... .... .... ..1. .... .... .... .... = Read Control
                             .... .... .... ...1 .... .... .... .... = Delete
                             .... .... .... .... .... ...1 .... .... = Write Attributes
                             .... .... .... .... .... .... 1... .... = Read Attributes
                             .... .... .... .... .... .... .1.. .... = Delete Child
                             .... .... .... .... .... .... ..1. .... = Execute
                             .... .... .... .... .... .... ...1 .... = Write EA
                             .... .... .... .... .... .... .... 1... = Read EA
                             .... .... .... .... .... .... .... .1.. = Append
                             .... .... .... .... .... .... .... ..1. = Write
                             .... .... .... .... .... .... .... ...1 = Read

                           ALLOW-Everyone-0x10000000-OI|CI|IO
                             0... .... .... .... .... .... .... .... = Generic Read
                             .0.. .... .... .... .... .... .... .... = Generic Write
                             ..0. .... .... .... .... .... .... .... = Generic Execute
                             ...1 .... .... .... .... .... .... .... = Generic All
                             .... ...0 .... .... .... .... .... .... = System Security
                             .... .... ...0 .... .... .... .... .... = Synchronize
                             .... .... .... 0... .... .... .... .... = Write Owner
                             .... .... .... .0.. .... .... .... .... = Write DAC
                             .... .... .... ..0. .... .... .... .... = Read Control
                             .... .... .... ...0 .... .... .... .... = Delete
                             .... .... .... .... .... ...0 .... .... = Write Attributes
                             .... .... .... .... .... .... 0... .... = Read Attributes
                             .... .... .... .... .... .... .0.. .... = Delete Child
                             .... .... .... .... .... .... ..0. .... = Execute
                             .... .... .... .... .... .... ...0 .... = Write EA
                             .... .... .... .... .... .... .... 0... = Read EA
                             .... .... .... .... .... .... .... .0.. = Append
                             .... .... .... .... .... .... .... ..0. = Write
                             .... .... .... .... .... .... .... ...0 = Read
----
次の例では、SVM vs1 内のパス `/datavol1`を持つボリュームのセキュリティ情報（ストレージレベルのアクセス ガードのセキュリティ情報を含む）を表示します：

[listing]
----
cluster::> vserver security file-directory show -vserver vs1 -path /datavol1

                Vserver: vs1
              File Path: /datavol1
      File Inode Number: 77
         Security Style: ntfs
        Effective Style: ntfs
         DOS Attributes: 10
 DOS Attributes in Text: ----D---
Expanded Dos Attributes: -
           Unix User Id: 0
          Unix Group Id: 0
         Unix Mode Bits: 777
 Unix Mode Bits in Text: rwxrwxrwx
                   ACLs: NTFS Security Descriptor
                         Control:0x8004
                         Owner:BUILTIN\Administrators
                         Group:BUILTIN\Administrators
                         DACL - ACEs
                           ALLOW-Everyone-0x1f01ff
                           ALLOW-Everyone-0x10000000-OI|CI|IO


                         Storage-Level Access Guard security
                         SACL (Applies to Directories):
                           AUDIT-EXAMPLE\Domain Users-0x120089-FA
                           AUDIT-EXAMPLE\engineering-0x1f01ff-SA
                         DACL (Applies to Directories):
                           ALLOW-EXAMPLE\Domain Users-0x120089
                           ALLOW-EXAMPLE\engineering-0x1f01ff
                           ALLOW-NT AUTHORITY\SYSTEM-0x1f01ff
                         SACL (Applies to Files):
                           AUDIT-EXAMPLE\Domain Users-0x120089-FA
                           AUDIT-EXAMPLE\engineering-0x1f01ff-SA
                         DACL (Applies to Files):
                           ALLOW-EXAMPLE\Domain Users-0x120089
                           ALLOW-EXAMPLE\engineering-0x1f01ff
                           ALLOW-NT AUTHORITY\SYSTEM-0x1f01ff
----
.関連情報
* xref:display-file-security-mixed-style-volumes-task.adoc[mixedセキュリティ形式のボリュームのファイル セキュリティに関する情報の表示]
* xref:display-file-security-unix-style-volumes-task.adoc[UNIXセキュリティ形式のボリュームのファイル セキュリティに関する情報の表示]

