---
permalink: smb-admin/display-file-security-audit-policies-concept.html 
sidebar: sidebar 
keywords: display, information, file, security, directories, directory, contain, volume, storage, virtual, machine, svm, audit, policies, policy, flexvol, configure, storage-level, access, guard, dynamic, access, control, display information about file security and audit policies 
summary: Storage Virtual Machine （ SVM ）上のボリュームに格納されたファイルとディレクトリのファイルセキュリティに関する情報を表示できます。FlexVol の監査ポリシーに関する情報を表示できます。設定されている場合、 FlexVol ボリュームのストレージレベルのアクセス保護およびダイナミックアクセス制御セキュリティの設定に関する情報を表示できます。 
---
= ファイルセキュリティと監査ポリシーの概要に関する情報を表示します
:icons: font
:imagesdir: ../media/


[role="lead"]
Storage Virtual Machine （ SVM ）上のボリュームに格納されたファイルとディレクトリのファイルセキュリティに関する情報を表示できます。FlexVol の監査ポリシーに関する情報を表示できます。設定されている場合、 FlexVol ボリュームのストレージレベルのアクセス保護およびダイナミックアクセス制御セキュリティの設定に関する情報を表示できます。



== ファイルセキュリティに関する情報を表示する

次のセキュリティ形式のボリュームと（ FlexVol の） qtree に格納されたデータに適用されているファイルセキュリティに関する情報を表示できます。

* NTFS
* 「 UNIX 」
* 混在




== 監査ポリシーに関する情報を表示する

次の NAS プロトコルを介した FlexVol ボリューム上のアクセスイベントを監査する監査ポリシーに関する情報を表示できます。

* SMB （すべてのバージョン）
* NFSv4.x に対応している




== Storage-Level Access Guard （ SLAG ；ストレージレベルのアクセス保護）セキュリティに関する情報を表示する

ストレージレベルのアクセス保護セキュリティは、次のセキュリティ形式の FlexVol および qtree オブジェクトに適用できます。

* NTFS
* 混在
* UNIX （ボリュームが含まれる SVM で CIFS サーバが設定されている場合）




== ダイナミックアクセス制御（ DAC ）セキュリティに関する情報を表示する

ダイナミックアクセス制御セキュリティは、次のセキュリティ形式の FlexVol ボリューム内のオブジェクトに適用できます。

* NTFS
* Mixed （オブジェクトに NTFS 対応のセキュリティが設定されている場合）


* 関連情報 *

xref:secure-file-access-storage-level-access-guard-concept.adoc[ストレージレベルのアクセス保護を使用したファイルアクセスの保護]

xref:display-storage-level-access-guard-task.adoc[ストレージレベルのアクセス保護に関する情報の表示]
