---
permalink: smb-admin/display-group-memberships-local-users-task.html 
sidebar: sidebar 
keywords: display, information, local, group, user, belong, folder, determine, access, file, useful, troubleshoot, display information about group memberships for local users 
summary: ローカルユーザが属しているローカルグループに関する情報を表示できます。この情報を使用して、ファイルやフォルダに対するユーザのアクセス権を決定できます。この情報は、ファイルやフォルダに対するユーザのアクセス権を決定する場合や、ファイルアクセスに関する問題のトラブルシューティングを行う場合に役立ちます。 
---
= ローカルユーザのグループメンバーシップに関する情報を表示する
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
ローカルユーザが属しているローカルグループに関する情報を表示できます。この情報を使用して、ファイルやフォルダに対するユーザのアクセス権を決定できます。この情報は、ファイルやフォルダに対するユーザのアクセス権を決定する場合や、ファイルアクセスに関する問題のトラブルシューティングを行う場合に役立ちます。

.タスクの内容
コマンドをカスタマイズして、必要な情報のみを表示することができます。

.ステップ
. 次のいずれかを実行します。
+
|===
| 状況 | 入力するコマンド 


 a| 
指定したローカルユーザのローカルユーザメンバーシップ情報を表示する
 a| 
`vserver cifs users-and-groups local-user show-membership -user-name _user_name_`



 a| 
このローカルユーザが属しているローカルグループのローカルユーザメンバーシップ情報を表示する
 a| 
`vserver cifs users-and-groups local-user show-membership -membership _group_name_`



 a| 
指定したStorage Virtual Machine（SVM）に関連付けられているローカルユーザのユーザメンバーシップ情報を表示する
 a| 
`vserver cifs users-and-groups local-user show-membership -vserver _vserver_name_`



 a| 
指定したSVM上のすべてのローカルユーザに関する詳細情報を表示する
 a| 
`vserver cifs users-and-groups local-user show-membership -instance ‑vserver _vserver_name_`

|===


.例
次の例は、 SVM vs1 上のすべてのローカルユーザのメンバーシップ情報を表示します。ユーザ「 CIFS_SERVER\Administrator 」は「 BUILTIN\Administrators 」グループのメンバーで、「 CIFS_SERVER\sue 」は「 CIFS_SERVER\g1 」グループのメンバーです。

[listing]
----
cluster1::> vserver cifs users-and-groups local-user show-membership -vserver vs1
Vserver    User Name                    Membership
---------- ---------------------------- ------------------------
vs1        CIFS_SERVER\Administrator    BUILTIN\Administrators
           CIFS_SERVER\sue              CIFS_SERVER\g1
----