---
permalink: smb-admin/display-statistics-task.html 
sidebar: sidebar 
keywords: display, various, statistic, cifs, smb, audit, branchcache, has, monitor, performance, diagnose, issue 
summary: パフォーマンスの監視と問題の診断を行うために、CIFSとSMB、監査、BranchCacheハッシュに関する統計など、さまざまな統計を表示できます。 
---
= ONTAP SMB統計を表示する
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
パフォーマンスの監視と問題の診断を行うために、CIFSとSMB、監査、BranchCacheハッシュに関する統計など、さまざまな統計を表示できます。

.開始する前に
オブジェクトに関する情報を表示する前に、コマンドと `statistics stop`コマンドを使用してデータサンプルを収集しておく必要があり `statistics start`ます。

.手順
. 権限レベルをadvancedに設定します。 `set -privilege advanced`
. 次のいずれかを実行します。
+
|===
| 統計を表示する対象 | 入力するコマンド 


 a| 
SMBのすべてのバージョン
 a| 
`statistics show -object cifs`



 a| 
SMB 1.0
 a| 
`statistics show -object smb1`



 a| 
SMB 2.xおよびSMB 3.0
 a| 
`statistics show -object smb2`



 a| 
ノードのCIFSサブシステム
 a| 
`statistics show -object nblade_cifs`



 a| 
マルチプロトコルの監査
 a| 
`statistics show -object audit_ng`



 a| 
BranchCacheハッシュサービス
 a| 
`statistics show -object hashd`



 a| 
動的DNS
 a| 
`statistics show -object ddns_update`

|===
+
の詳細については `statistics show`、をlink:https://docs.netapp.com/us-en/ontap-cli/statistics-show.html["ONTAPコマンド リファレンス"^]参照してください。

. admin権限レベルに戻ります。 `set -privilege admin`


.関連情報
* xref:determine-statistics-objects-counters-available-task.adoc[サーバー上で利用可能な統計、オブジェクト、カウンターを決定する]
* xref:monitor-signed-session-statistics-task.adoc[SMB署名済みセッションの統計の監視]
* xref:display-branchcache-statistics-task.adoc[BranchCache統計を表示する]
* xref:statistics-monitor-automatic-node-referral-task.adoc[統計を使用して自動ノード参照アクティビティを監視する]
* link:../smb-hyper-v-sql/index.html["Microsoft Hyper-VオヨヒSQL ServerヨウノSMBノセツテイ"]
* link:../performance-config/index.html["パフォーマンス監視のセットアップ"]

