---
permalink: smb-admin/dynamic-access-control-concept.html 
sidebar: sidebar 
keywords: consideration, dynamic, access, control, dac, central, policies, policy, secure, file, folder, cifs, server, consideration when using dynamic access control and central access policies with cifs servers 
summary: Dynamic Access Control（DAC）と集中アクセス ポリシーを使用して CIFS サーバー上のファイルとフォルダーを保護する場合には、留意すべき点がいくつかあります。 
---
= ONTAP SMB サーバーで DAC と集中アクセス ポリシーを使用する方法について学習します
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Dynamic Access Control（DAC）と集中アクセス ポリシーを使用して CIFS サーバー上のファイルとフォルダーを保護する場合には、留意すべき点がいくつかあります。



== ポリシールールがdomain\administratorユーザーに適用される場合、NFSアクセスはrootに対して拒否される可能性があります

特定の状況下では、rootユーザーがアクセスしようとしているデータに集約型アクセスポリシーのセキュリティが適用されている場合、rootへのNFSアクセスが拒否されることがあります。この問題は、集約型アクセスポリシーにdomain\administratorに適用されるルールが含まれており、rootアカウントがdomain\administratorアカウントにマッピングされている場合に発生します。

ルールを domain\administrator ユーザーに適用するのではなく、domain\administrators グループなどの管理者権限を持つグループに適用する必要があります。これにより、root を domain\administrator アカウントにマッピングしても、この問題の影響を受けることはありません。



== 適用された集中アクセス ポリシーが Active Directory に見つからない場合、CIFS サーバーの BUILTIN\Administrators グループはリソースにアクセスできます

CIFSサーバー内のリソースに集約型アクセス ポリシーが適用されているものの、CIFSサーバーがActive Directoryから情報を取得する際に集約型アクセス ポリシーのSIDを使用しても、そのSIDがActive Directory内の既存の集約型アクセス ポリシーのSIDと一致しない場合があります。このような場合、CIFSサーバーは当該リソースに対してローカルのデフォルト復旧ポリシーを適用します。

ローカルのデフォルト回復ポリシーでは、CIFS サーバーの BUILTIN\Administrators グループがそのリソースにアクセスできるようになります。
