---
permalink: smb-admin/dynamic-home-directories-concept.html 
sidebar: sidebar 
keywords: ontap, home, directories, directory, configure, smb, share, map, base, connect, set, variable, creating, create, separate, share, user, define, home, relationship, entry, point, svm, how ontap enables dynamic home directories 
summary: ONTAP ホームディレクトリを使用すると、 SMB 共有を設定し、ユーザと一連の変数に基づいてさまざまなディレクトリにマッピングすることができます。ユーザごとに別個の共有を作成するのではなく、 1 つの共有を設定し、いくつかのホームディレクトリパラメータを指定して、エントリポイント（共有）とホームディレクトリ（ SVM 上のディレクトリ）間の関係をユーザ単位で定義します。 
---
= ONTAP で動的ホームディレクトリを有効にする方法
:icons: font
:imagesdir: ../media/


[role="lead"]
ONTAP ホームディレクトリを使用すると、 SMB 共有を設定し、ユーザと一連の変数に基づいてさまざまなディレクトリにマッピングすることができます。ユーザごとに別個の共有を作成するのではなく、 1 つの共有を設定し、いくつかのホームディレクトリパラメータを指定して、エントリポイント（共有）とホームディレクトリ（ SVM 上のディレクトリ）間の関係をユーザ単位で定義します。

ゲストユーザとしてログインしたユーザは、ホームディレクトリを持ちません。また、他のユーザのホームディレクトリにアクセスすることはできません。ユーザとディレクトリのマッピング方法を決定する 4 つの変数があります。

* * 共有名 *
+
ユーザの接続先として作成する共有の名前です。この共有にはホームディレクトリのプロパティを設定する必要があります。

+
共有名には、次の動的な名前を使用できます。

+
** `%w ( ユーザーの Windows ユーザー名 )
** `%d( ユーザーの Windows ドメイン名 )
** `%u ( ユーザのマッピングされた UNIX ユーザ名 ) すべてのホームディレクトリで一意になるように ' 共有名には '%w または %u 変数を含める必要があります共有名には '%d' 変数と '%w 変数の両方を使用することも ( 例 : %d'`%w ) ' 固定部分と変数部分で構成することもできます ( 例 : home_`%w ')


* * 共有パス *
+
共有によって定義される、つまり、共有名の 1 つに関連付けられる相対パスです。各検索パスに付加されて、 SVM のルートからのユーザのホームディレクトリの完全パスを生成します。静的 ( 例 : 'home) ' 動的 ( 例 : '%w') ' またはその 2 つの組み合わせ ( 例 : 'eng/%w`) を使用できます

* * 検索パス *
+
SVM のルートからの絶対パスのセットで、 ONTAP ではこのパスに基づいてホームディレクトリが検索されます。vserver cifs home-directory search-path add コマンドを使用して 1 つ以上の検索パスを指定できます。複数 ONTAP の検索パスを指定すると、有効なパスが見つかるまで、指定された順に各検索パスが試行されます。

* * ディレクトリ *
+
ユーザに対して作成する、そのユーザのホームディレクトリです。通常、ディレクトリ名はユーザの名前です。ホームディレクトリは、検索パスで定義されるいずれかのディレクトリに作成する必要があります。



たとえば、次のように設定します。

* ユーザ： John Smith
* ユーザのドメイン： acme
* ユーザ名： jsmith
* SVM 名： vs1
* ホームディレクトリ共有名 #1 ： home_`%w 共有パス： %w
* ホームディレクトリ共有名 #2:`%w 共有パス :%d/%w
* 検索パス #1 ：「 /vol0HOME/home 」
* 検索パス #2 ： '/vol1home/ ホーム
* 検索パス #3 ： //vol2home/ ホーム
* ホームディレクトリ :`/vol1home/home/jsmith`


シナリオ 1 ：ユーザは \\vs1\home_jsmith' に接続します。これは ' 最初のホーム・ディレクトリ共有名に一致し ' 相対パス 'jsmith' を生成しますONTAP は ' 各検索パスを順に確認して 'jsmith という名前のディレクトリを検索します

* 「 /vol0home/home/jsmith 」は存在しないので、検索パス #2 に進みます。
* 「 /vol1home/home/jsmith 」は存在します。したがって、検索パス #3 は確認されません。これでユーザは自分のホームディレクトリに接続されました。


シナリオ 2 ：ユーザは \\vs1\jsmith' に接続します。これは '2 番目のホーム・ディレクトリの共有名に一致し ' 相対パス 'acme/jsmith が生成されますONTAP は ' 各検索パスを順に確認して 'acme/jsmith という名前のディレクトリを検索します

* 「 /vol0home/home/acme/jsmith は存在しないので、検索パス #2 に進みます。
* 「 /vol1home/home/acme/jsmith は存在しないので、検索パス #3 に進みます。
* 「 /vol2home/home/acme/jsmith 」は存在しません。ホームディレクトリが存在しないため、接続は失敗します。

