---
permalink: smb-admin/enable-disable-oplocks-when-creating-shares-task.html 
sidebar: sidebar 
keywords: oplock, client, lock, file, cache, content, local, performance, operation, storage, virtual, machine, svm, circumstance, disable, share-by-share, basis, enable, disable, enable or disable oplocks when creating smb shares 
summary: oplock を使用すると、クライアントによってファイルがロックされてコンテンツがローカルにキャッシュされるため、ファイル操作のパフォーマンスが向上します。Storage Virtual Machine （ SVM ）上にある SMB 共有では、 oplock が有効になっています。場合によっては、 oplock の無効化が必要になることがあります。oplock は共有ごとに有効または無効にできます。 
---
= SMB 共有の作成時に oplock を有効または無効にします
:icons: font
:imagesdir: ../media/


[role="lead"]
oplock を使用すると、クライアントによってファイルがロックされてコンテンツがローカルにキャッシュされるため、ファイル操作のパフォーマンスが向上します。Storage Virtual Machine （ SVM ）上にある SMB 共有では、 oplock が有効になっています。場合によっては、 oplock の無効化が必要になることがあります。oplock は共有ごとに有効または無効にできます。

共有を含むボリュームで oplock が有効になっているが、その共有の oplock 共有プロパティが無効になっている場合、その共有の oplock は無効になります。共有での oplock の無効化は、ボリュームの oplock の設定よりも優先されます。共有で oplock を無効にすると、便宜的 oplock と oplock リースの両方が無効になります。

oplock 共有プロパティに加えて、その他の共有プロパティをカンマで区切って指定できます。その他の共有パラメータを指定することもできます。

.手順
. 該当する操作を実行します。
+
|===
| 状況 | 作業 


 a| 
共有の作成時に共有で oplock を有効にします
 a| 
次のコマンドを入力します。 ` + vserver cifs share create -vserver vserver_name __ -share-name share_name -path path_to_share -share-properties [oplocks 、 ...] + `

[NOTE]
====
共有でデフォルトの共有プロパティ oplocks 、 browsable 、および changenotify のみを有効にする場合は、 SMB 共有の作成時に「 -share-properties 」パラメータを指定する必要はありません。デフォルト以外の共有プロパティを組み合わせて使用する場合は、その共有に使用する共有プロパティのリストで、「 -share-properties 」パラメータを指定する必要があります。

====


 a| 
共有の作成時に共有で oplock を無効にします
 a| 
次のコマンドを入力します。 ` + vserver cifs share create -vserver _vserver_name __ -share-name share_name -path path_to_share -share-properties [other_share_property 、 ...] + `

[NOTE]
====
oplock を無効にする場合は、共有の作成時に共有プロパティのリストを指定する必要がありますが、 oplocks プロパティは指定しないでください。

====
|===


xref:enable-disable-oplocks-existing-shares-task.adoc[既存の SMB 共有で oplock を有効または無効にします]

xref:monitor-oplock-status-task.adoc[oplock ステータスを監視しています]
