---
permalink: smb-admin/enable-disable-automatic-node-referrals-task.html 
sidebar: sidebar 
keywords: enable, smb, automatic, node, referral, client, access, performance, disable, ontap, enable or disable smb automatic node referrals 
summary: SMB自動ノード リファーラルを有効にして、SMBクライアント アクセスのパフォーマンスを向上させることができます。ONTAPでSMBクライアントを参照しないようにするには、自動ノード リファーラルを無効にします。 
---
= ONTAP SMB自動ノード照会を有効または無効にする
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
SMB自動ノード リファーラルを有効にして、SMBクライアント アクセスのパフォーマンスを向上させることができます。ONTAPでSMBクライアントを参照しないようにするには、自動ノード リファーラルを無効にします。

.開始する前に
Storage Virtual Machine（SVM）でCIFSサーバが設定されて実行されている必要があります。

.タスク概要
SMB自動ノード リファーラル機能は、デフォルトでは無効になっています。必要に応じて、各SVMで有効または無効にすることができます。

このオプションは、advanced権限レベルで使用できます。

.手順
. 権限レベルをadvancedに設定します： `set -privilege advanced`
. SMB自動ノード リファーラルを必要に応じて有効または無効にします。
+
|===
| SMB 自動ノード リファーラルを有効にする場合... | 入力するコマンド 


 a| 
有効
 a| 
`vserver cifs options modify -vserver vserver_name -is-referral-enabled true`



 a| 
無効
 a| 
`vserver cifs options modify -vserver vserver_name -is-referral-enabled false`

|===
+
このオプション設定は新しいSMBセッションで有効になります。既存の接続を持つクライアントは、既存のキャッシュ タイムアウトが経過した場合にのみノード リファラルを使用できます。

. admin権限レベルに切り替えます： `set -privilege admin`


.関連情報
xref:server-options-reference.adoc[利用可能なサーバー オプション]
