---
permalink: smb-admin/enable-disable-oplocks-existing-shares-task.html 
sidebar: sidebar 
keywords: oplock, enable, smb, share, storage, virtual, machine, svm, default, circumstance, disable, alternative, enable or disable oplocks on existing smb shares 
summary: Storage Virtual Machine（SVM）上のSMB共有では、oplockがデフォルトで有効になっています。状況によっては、oplockの無効化が必要になることがあります。また、以前に共有でoplockを無効にしたことがある場合は、oplockを再度有効にすることもできます。 
---
= 既存のONTAP SMB共有でのoplockの有効化または無効化
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Storage Virtual Machine（SVM）上のSMB共有では、oplockがデフォルトで有効になっています。状況によっては、oplockの無効化が必要になることがあります。また、以前に共有でoplockを無効にしたことがある場合は、oplockを再度有効にすることもできます。

.タスクの内容
共有を含むボリュームでoplockが有効になっているが、その共有のoplock共有プロパティが無効になっている場合、その共有のoplockは無効になります。共有でのoplockの無効化は、ボリュームでのoplockの有効化よりも優先されます。共有でoplockを無効にすると、便宜的oplockとoplockリースの両方が無効になります。既存の共有では、oplockをいつでも有効または無効にできます。

.ステップ
. 該当する操作を実行します。
+
|===
| 状況 | そしたら...。 


 a| 
既存の共有を変更して共有でoplockを有効にする
 a| 
次のコマンドを入力します。 `vserver cifs share properties add -vserver _vserver_name_ -share-name share_name -share-properties oplocks`

[NOTE]
====
追加する共有プロパティをカンマで区切って追加指定できます。

====
新しく追加したプロパティは、既存の共有プロパティのリストに追加されます。以前に指定した共有プロパティは有効なままです。



 a| 
既存の共有を変更して共有でoplockを無効にする
 a| 
次のコマンドを入力します。 `vserver cifs share properties remove -vserver _vserver_name_ -share-name _share_name_ -share-properties oplocks`

[NOTE]
====
削除する共有プロパティをカンマで区切って追加指定できます。

====
削除した共有プロパティは既存の共有プロパティリストから削除されますが、削除しない設定済みの共有プロパティは有効なままです。

|===


.例
次のコマンドは、 Storage Virtual Machine （ SVM 、旧 Vserver ） vs1 上の「 Engineering 」という名前の共有の oplock を有効にします。

[listing]
----
cluster1::> vserver cifs share properties add -vserver vs1 -share-name Engineering -share-properties oplocks

cluster1::> vserver cifs share properties show
Vserver          Share            Properties
---------------- ---------------- -----------------
vs1              Engineering      oplocks
                                  browsable
                                  changenotify
                                  showsnapshot
----
次のコマンドは、 SVM vs1 上の「 Engineering 」という名前の共有の oplock を無効にします。

[listing]
----
cluster1::> vserver cifs share properties remove -vserver vs1 -share-name Engineering -share-properties oplocks

cluster1::> vserver cifs share properties show
Vserver          Share            Properties
---------------- ---------------- -----------------
vs1              Engineering      browsable
                                  changenotify
                                  showsnapshot
----
.関連情報
* xref:enable-disable-oplocks-when-creating-shares-task.adoc[SMB共有を作成するときにoplocksを有効または無効にする]
* xref:monitor-oplock-status-task.adoc[oplock ステータスを監視する]
* xref:add-remove-share-properties-existing-share-task.adoc[既存の共有の共有プロパティを追加または削除する]

