---
permalink: smb-admin/enable-disable-dynamic-access-control-task.html 
sidebar: sidebar 
keywords: option, enable, dynamic, access, control, dac, secure, object, cifs, server, disable, default, enable or disable dynamic access control 
summary: Dynamic Access Control （ DAC ；ダイナミックアクセス制御）を使用して CIFS サーバ上のオブジェクトを保護するオプションは、デフォルトでは無効になっています。CIFS サーバでダイナミックアクセス制御を使用する場合は、このオプションを有効にする必要があります。CIFS サーバに格納されたオブジェクトの保護にダイナミックアクセス制御を使用する必要がなくなった場合は、このオプションを無効にすることができます。 
---
= ダイナミックアクセス制御の概要を有効または無効にします
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Dynamic Access Control （ DAC ；ダイナミックアクセス制御）を使用して CIFS サーバ上のオブジェクトを保護するオプションは、デフォルトでは無効になっています。CIFS サーバでダイナミックアクセス制御を使用する場合は、このオプションを有効にする必要があります。CIFS サーバに格納されたオブジェクトの保護にダイナミックアクセス制御を使用する必要がなくなった場合は、このオプションを無効にすることができます。

ダイナミックアクセス制御を有効にすると、ダイナミックアクセス制御関連のエントリを使用する ACL をファイルシステムに含めることができます。ダイナミックアクセス制御を無効にすると、現在のダイナミックアクセス制御エントリは無視され、新しいエントリは許可されません。

このオプションは、 advanced 権限レベルでのみ使用できます。

.ステップ
. 権限レベルを advanced に設定します。「 set -privilege advanced 」
. 次のいずれかを実行します。
+
|===


| ダイナミックアクセス制御の設定 | 入力するコマンド 


 a| 
有効
 a| 
vserver cifs options modify -vserver _vserver_name -is-DAC -enabled true を指定します



 a| 
無効
 a| 
vserver cifs options modify -vserver vserver_name -is-DAC -enabled false です

|===
. 管理者特権レベルの「 set -privilege admin 」に戻ります


xref:configure-central-access-policies-secure-data-task.adoc[CIFS サーバ上のデータを保護する集約型アクセスポリシーの設定]
