---
permalink: smb-admin/enable-smb2-connections-domain-controllers-task.html 
sidebar: sidebar 
keywords: ontap, enable, smb, version, connect, domain, controller, default, smb2, enable smb2 connections to domain controllers 
summary: ONTAP 9.1 以降では、 SMB バージョン 2.0 からドメインコントローラへの接続を有効にすることができます。これは、ドメインコントローラで SMB 1.0 を無効にしている場合は必須です。ONTAP 9.2 以降では、 SMB2 がデフォルトで有効になります。 
---
= ドメインコントローラへの SMB2 接続を有効にします
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
ONTAP 9.1 以降では、 SMB バージョン 2.0 からドメインコントローラへの接続を有効にすることができます。これは、ドメインコントローラで SMB 1.0 を無効にしている場合は必須です。ONTAP 9.2 以降では、 SMB2 がデフォルトで有効になります。

「 smb2-enabled-for -dDC-connections 」コマンドオプションを使用すると、使用している ONTAP のリリースに応じたシステムデフォルトが有効になります。ONTAP 9.1 のシステムデフォルトでは、 SMB 1.0 が有効、 SMB 2.0 が無効になります。ONTAP 9.2 のシステムデフォルトでは、 SMB 1.0 が有効になり、 SMB 2.0 が有効になります。ドメインコントローラは、最初に SMB 2.0 をネゴシエートし、失敗した場合は SMB 1.0 を使用します。

SMB 1.0 は、 ONTAP からドメインコントローラに対して無効にすることができます。ONTAP 9.1 では、 SMB 1.0 を無効にした場合、ドメインコントローラと通信するために SMB 2.0 を有効にする必要があります。

[NOTE]
====
「 -smb1-enabled for-dc-connections 」が「 false 」に設定されていて、「 -smb1-enabled 」が「 true 」に設定されている場合、 ONTAP はクライアントとしての SMB 1.0 接続を拒否しますが、サーバとしての SMB 1.0 のインバウンド接続は引き続き受け入れます。SMB バージョンの有効化と無効化に関するトピックを参照してください。

====
.手順
. SMB セキュリティ設定を変更する前に、有効になっている SMB のバージョンを確認してください。「 vserver cifs security show 」
. リストを下にスクロールして SMB のバージョンを確認します。
. 「 smb2-enabled-for -dc-connections 」オプションを使用して、適切なコマンドを実行します。
+
|===
| SMB2 の設定 | 入力するコマンド 


 a| 
有効
 a| 
「 vserver cifs security modify -vserver _vserver_name _smb2-enabled-for -dc_connections true 」のように指定します



 a| 
無効
 a| 
「 vserver cifs security modify -vserver _vserver_name _smb2-enabled-for -dc_connections false 」の形式で指定します

|===


xref:supported-versions-functionality-concept.adoc[サポートされる SMB のバージョンと機能]
