---
permalink: smb-admin/enable-ldap-signing-sealing-task.html 
sidebar: sidebar 
keywords: cifs, server, sign, seal, secure, communication, active, directory, ldap, modify, security, setting, sign, seal, enable, enable ldap signing and sealing on the cifs server 
summary: CIFS サーバで Active Directory LDAP サーバとのセキュアな通信に署名と封印を使用するためには、 CIFS サーバのセキュリティ設定を変更して LDAP の署名と封印を有効にする必要があります。 
---
= ONTAP SMBサーバでのLDAPの署名と封印の有効化
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
CIFS サーバで Active Directory LDAP サーバとのセキュアな通信に署名と封印を使用するためには、 CIFS サーバのセキュリティ設定を変更して LDAP の署名と封印を有効にする必要があります。

.開始する前に
AD サーバ管理者に問い合わせて、適切なセキュリティ設定値を決定する必要があります。

.手順
. Active Directory LDAPサーバとのトラフィックの署名と封印を有効にするCIFSサーバのセキュリティ設定を行います。 `vserver cifs security modify -vserver _vserver_name_ -session-security-for-ad-ldap {none|sign|seal}`
+
署名(`sign`、データ整合性）、署名と封印(`seal`、データの整合性と暗号化を有効にすることができます。また、 `none`署名と封印のどちらも有効にしないことも可能です。デフォルト値はです `none`。

. LDAPの署名と封印のセキュリティ設定が正しく設定されていることを確認します。 `vserver cifs security show -vserver _vserver_name_`
+
[NOTE]
====
SVMがネームマッピングやその他のUNIX情報（ユーザ、グループ、ネットグループなど）の照会に同じLDAPサーバを使用する場合は、コマンドのオプション `vserver services name-service ldap client modify`で対応する設定を有効にする必要があります。 `-session-security`

====

