---
permalink: smb-admin/enable-client-access-unix-symbolic-links-concept.html 
sidebar: sidebar 
keywords: smybol, link, file, create, unix, environment, reference, directory, client, access, redirect, target, absolute, widelinks, local, file, system, how ontap enables you to provide smb client access to unix symbolic links 
summary: シンボリックリンクは UNIX 環境で作成されるファイルで、別のファイルまたはディレクトリへの参照が含まれます。シンボリックリンクにアクセスしたクライアントは、シンボリックリンクが参照するターゲットファイルまたはディレクトリにリダイレクトされます。ONTAP は、ワイドリンク（ローカルファイルシステムの外部にあるターゲットとの絶対リンク）を含む、相対および絶対シンボリックリンクをサポートしています。 
---
= ONTAP を使用して UNIX シンボリックリンクへの SMB クライアントアクセスを提供する方法
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
シンボリックリンクは UNIX 環境で作成されるファイルで、別のファイルまたはディレクトリへの参照が含まれます。シンボリックリンクにアクセスしたクライアントは、シンボリックリンクが参照するターゲットファイルまたはディレクトリにリダイレクトされます。ONTAP は、ワイドリンク（ローカルファイルシステムの外部にあるターゲットとの絶対リンク）を含む、相対および絶対シンボリックリンクをサポートしています。

ONTAP には、 SMB クライアントが SVM で設定されている UNIX のシンボリックリンクをたどるための機能が用意されています。この機能はオプションであり、「 vserver cifs share create 」コマンドの「 -symlink-properties 」オプションを使用して、共有ごとに設定できます。次の設定のいずれかを使用できます。

* 読み取り / 書き込みアクセスで有効化
* 読み取り専用アクセスで有効化
* SMB クライアントに対してシンボリックリンクを非表示にして無効にしました
* SMB クライアントからシンボリックリンクへのアクセス権なしで無効になりました


共有でシンボリックリンクを有効にした場合、相対シンボリックリンクは追加の設定なしで機能します。

共有でシンボリックリンクを有効にしただけでは、絶対シンボリックリンクは機能しません。最初に、シンボリックリンクの UNIX パスからデスティネーション SMB パスへのマッピングを作成する必要があります。絶対シンボリックリンクのマッピングを作成する場合、ローカルリンクか a_widelink ；ワイドリンクを他のストレージデバイス上のファイルシステムにリンクするか、同じ ONTAP システム上の別々の SVM でホストされているファイルシステムにリンクするかを指定できます。widelink を作成するときは、そのクライアントが参照するための情報を含める必要があります。つまり、クライアントがディレクトリのリパースジャンクションポイントを検出するためのポイントを作成します。ローカル共有外のファイルまたはディレクトリへの絶対シンボリックリンクを作成しても、局所性をローカルに設定すると、 ONTAP はターゲットへのアクセスを許可しません。

[NOTE]
====
クライアントがローカルシンボリックリンク（絶対または相対）を削除しようとした場合、シンボリックリンクのみが削除され、ターゲットファイルまたはターゲットディレクトリは削除されません。それに対して、クライアントがワイドリンクを削除しようとした場合には、ワイドリンクが参照する実際のターゲットファイルやターゲットディレクトリが削除されることがあります。クライアントは SVM 外のターゲットファイルまたはディレクトリを明示的に開いて削除できるため、 ONTAP ではこの操作を制御できません。

====
* * リパースポイントと ONTAP ファイルシステムサービス *
+
a_reparse point_ は、オプションでファイルとともにボリュームに格納できる NTFS ファイルシステムオブジェクトです。リパースポイントは、 SMB クライアントが NTFS 形式のボリュームで作業する際に、拡張ファイルシステムサービスを受け取る機能を提供します。リパースポイントは、リパースポイントのタイプを識別する標準のタグと、クライアントがさらに処理するために SMB クライアントが取得できるリパースポイントのコンテンツで構成されます。ファイルシステムの拡張機能で使用できるオブジェクトタイプの中で、 ONTAP は、リパースポイントタグを使用した NTFS シンボリックリンクとディレクトリジャンクションポイントのサポートを実装しています。リパースポイントの内容を認識できない SMB クライアントは、単に無視し、リパースポイントで有効になる可能性がある拡張ファイルシステムサービスを提供しません。

* * ディレクトリジャンクションポイントおよびシンボリックリンクの ONTAP サポート *
+
ディレクトリジャンクションポイントは、ファイルが格納されている別の場所（別のパス（シンボリックリンク）または別のストレージデバイス（ワイドリンク）を参照できる、ファイルシステムディレクトリ構造内の場所です。ONTAP SMB サーバでは、ディレクトリのジャンクションポイントをリパースポイントとして Windows クライアントに公開し、ディレクトリのジャンクションポイントがトラバースされたときに対応したクライアントが ONTAP からリパースポイントのコンテンツを取得できるようにします。その結果、異なるパスやストレージデバイスを、同じファイルシステムに属しているかのように移動して接続することができます。

* * リパースポイントオプションを使用したワイドリンクサポートの有効化 *
+
ONTAP 9 では 'is-use-junctions as reparse-points-enabled オプションがデフォルトで有効になっていますすべての SMB クライアントがワイドリンクをサポートしているわけではないため、情報を有効にするオプションはプロトコルバージョンごとに設定可能であり、サポート対象とサポート対象外の両方の SMB クライアントに対応できるようにします。ONTAP 9.2 以降のリリースでは、 widelink を使用して共有にアクセスするクライアントプロトコルごとに、オプションの「 -widelink-as-reparse-point-versions 」を有効にする必要があります。デフォルトは SMB1 です。以前のリリースでは、デフォルトの SMB1 を使用してアクセスされるワイドリンクのみがレポートされ、 SMB2 または SMB3 を使用するシステムはワイドリンクにアクセスできませんでした。



詳細については、 Microsoft NTFS のマニュアルを参照してください。

https://docs.microsoft.com/en-us/windows/win32/fileio/reparse-points["Microsoft のドキュメント：「 Reparse Points"]
