---
permalink: smb-admin/enable-disable-gpo-support-task.html 
sidebar: sidebar 
keywords: enable, disable, group, policy, object, gpo, support, cifs, server, applicable, define, policy, organizational, unit, ou, enable or disable gpo support on a cifs server 
summary: CIFSサーバでGroup Policy Object（GPO；グループポリシーオブジェクト）のサポートを有効または無効にすることができます。CIFS サーバ上で GPO のサポートを有効にすると、グループポリシー（ CIFS サーバコンピュータオブジェクトを含む組織単位に適用されるポリシー）に定義されている該当する GPO が CIFS サーバに適用されます。 
---
= CIFSサーバ上でのGPOサポートの有効化と無効化
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
CIFSサーバでGroup Policy Object（GPO；グループポリシーオブジェクト）のサポートを有効または無効にすることができます。CIFSサーバでGPOのサポートを有効にすると、グループポリシー（CIFSサーバコンピュータオブジェクトを含む組織単位（OU）に適用されるポリシー）で定義されている該当するGPOがCIFSサーバに適用されます。

[NOTE]
.タスクの内容
====
GPOは、ワークグループモードのCIFSサーバでは有効にできません。

====
.手順
. 次のいずれかを実行します。
+
|===
| 状況 | 入力するコマンド 


 a| 
GPOを有効にする
 a| 
`vserver cifs group-policy modify -vserver _vserver_name_ -status enabled`



 a| 
GPOを無効にする
 a| 
`vserver cifs group-policy modify -vserver _vserver_name_ -status disabled`

|===
. GPOサポートが目的の状態になっていることを確認します。 `vserver cifs group-policy show -vserver +vserver_name_`
+
ワークグループモードの CIFS サーバのグループポリシーステータスは「 disabled 」と表示されます。



.例
次の例では、Storage Virtual Machine（SVM）vs1でGPOサポートを有効にします。

[listing]
----
cluster1::> vserver cifs group-policy modify -vserver vs1 -status enabled

cluster1::> vserver cifs group-policy show -vserver vs1

            Vserver: vs1
Group Policy Status: enabled
----
.関連情報
xref:supported-gpos-concept.adoc[サポートされるGPO]

xref:requirements-gpos-concept.adoc[CIFSサーバでGPOを使用するための要件]

xref:gpos-updated-server-concept.adoc[CIFSサーバでのGPOの更新方法]

xref:manual-update-gpo-settings-task.adoc[CIFSサーバでのGPO設定の手動更新]

xref:display-gpo-config-task.adoc[GPO設定に関する情報の表示]
