---
permalink: smb-admin/enable-disable-password-complexity-local-users-task.html 
sidebar: sidebar 
keywords: password, complex, enhance, security, local, smb, user, storage, virtual, machine, svm, reenable, enable, disable, enable or disable required password complexity for local smb users 
summary: パスワードの複雑さの要件を有効にすると、Storage Virtual Machine（SVM）上のローカルSMBユーザに対するセキュリティを強化できます。パスワードの複雑さの要件はデフォルトでは有効になっています。この要件の有効と無効はいつでも切り替えることができます。 
---
= ローカルSMBユーザのONTAPパスワードの複雑さを設定する
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
パスワードの複雑さの要件を有効にすると、Storage Virtual Machine（SVM）上のローカルSMBユーザに対するセキュリティを強化できます。パスワードの複雑さの要件はデフォルトでは有効になっています。この要件の有効と無効はいつでも切り替えることができます。

.開始する前に
CIFSサーバでローカル ユーザ、ローカル グループ、およびローカル ユーザ認証が有効になっている必要があります。

[NOTE]
.タスク概要
====
ワークグループ モードの CIFS サーバーでは `vserver cifs security modify`コマンドを使用しないでください。一部のオプションが無効です。

====
.手順
. 次のいずれかを実行します。
+
|===
| ローカルSMBユーザに対するパスワードの複雑さの要件の設定 | コマンドを入力してください... 


 a| 
有効
 a| 
`vserver cifs security modify -vserver _vserver_name_ -is-password-complexity-required true`



 a| 
無効
 a| 
`vserver cifs security modify -vserver _vserver_name_ -is-password-complexity-required false`

|===
. 必要なパスワードの複雑さのセキュリティ設定を確認します `vserver cifs security show -vserver _vserver_name_`


.例
次の例は、SVM vs1のローカルSMBユーザに対してパスワードの複雑さの要件を有効にします。

[listing]
----
cluster1::> vserver cifs security modify -vserver vs1 -is-password-complexity-required true

cluster1::> vserver cifs security show -vserver vs1 -fields is-password-complexity-required
vserver is-password-complexity-required
------- -------------------------------
vs1     true
----
.関連情報
* xref:display-server-security-settings-task.adoc[サーバーのセキュリティ設定に関する情報を表示する]
* xref:local-users-groups-concepts-concept.adoc[ローカル ユーザとグループについて]
* xref:requirements-local-user-passwords-concept.adoc[ローカル ユーザのパスワードの要件]
* xref:change-local-user-account-passwords-task.adoc[ローカル ユーザのアカウント パスワードの変更]

