---
permalink: smb-admin/enable-ldap-signing-sealing-task.html 
sidebar: sidebar 
keywords: cifs, server, sign, seal, secure, communication, active, directory, ldap, modify, security, setting, sign, seal, enable, enable ldap signing and sealing on the cifs server 
summary: CIFS サーバで Active Directory LDAP サーバとのセキュアな通信に署名と封印を使用するためには、 CIFS サーバのセキュリティ設定を変更して LDAP の署名と封印を有効にする必要があります。 
---
= CIFS サーバで LDAP の署名と封印を有効にする
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
CIFS サーバで Active Directory LDAP サーバとのセキュアな通信に署名と封印を使用するためには、 CIFS サーバのセキュリティ設定を変更して LDAP の署名と封印を有効にする必要があります。

.作業を開始する前に
AD サーバ管理者に問い合わせて、適切なセキュリティ設定値を決定する必要があります。

.手順
. CIFSサーバのセキュリティ設定で、Active Directory LDAPサーバとの間のトラフィックの署名と封印の有効化に関する設定を行います。 `vserver cifs security modify -vserver _vserver_name_ -session-security-for-ad-ldap {none|sign|seal}`
+
署名を有効にできます (`sign`、データの整合性）、署名と封印 (`seal`、データの整合性と暗号化）、またはどちらもサポートされていません  `none`、署名も封印もなし）。デフォルト値はです `none`。

. LDAPの署名と封印のセキュリティ設定が正しく設定されていることを確認します。 `vserver cifs security show -vserver _vserver_name_`
+
[NOTE]
====
SVMでネームマッピングやユーザ、グループ、ネットグループなどのUNIX情報の照会に同じLDAPサーバを使用する場合は、で対応する設定を有効にする必要があります `-session-security` のオプション `vserver services name-service ldap client modify` コマンドを実行します

====

