---
permalink: smb-admin/enable-ldap-signing-sealing-task.html 
sidebar: sidebar 
keywords: cifs, server, sign, seal, secure, communication, active, directory, ldap, modify, security, setting, sign, seal, enable, enable ldap signing and sealing on the cifs server 
summary: CIFSサーバがActive Directory LDAPサーバとの安全な通信に署名とシーリングを使用するには、事前にCIFSサーバのセキュリティ設定を変更してLDAP署名とシーリングを有効にする必要があります。 
---
= ONTAP SMBサーバでLDAP署名とシーリングを有効にする
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
CIFSサーバがActive Directory LDAPサーバとの安全な通信に署名とシーリングを使用するには、事前にCIFSサーバのセキュリティ設定を変更してLDAP署名とシーリングを有効にする必要があります。

.開始する前に
適切なセキュリティ構成値を決定するには、ADサーバ管理者に相談する必要があります。

.手順
. Active Directory LDAPサーバとの署名およびシールされたトラフィックを有効にするCIFSサーバ セキュリティ設定を構成します（：） `vserver cifs security modify -vserver _vserver_name_ -session-security-for-ad-ldap {none|sign|seal}`
+
署名(`sign`（データ整合性）、署名とシーリング(`seal`（データ整合性と暗号化）、またはどちらも有効にしない `none`（署名もシーリングも有効にしない）ことができます。デフォルト値は `none`です。

. LDAP署名および封印のセキュリティ設定が正しく設定されていることを確認します： `vserver cifs security show -vserver _vserver_name_`
+
[NOTE]
====
SVMが名前マッピングやその他のUNIX情報（ユーザ、グループ、ネットグループなど）を照会するために同じLDAPサーバを使用する場合は、 `vserver services name-service ldap client modify`コマンドの `-session-security`オプションを使用して対応する設定を有効にする必要があります。

====

