---
permalink: smb-admin/enable-disable-export-policies-task.html 
sidebar: sidebar 
keywords: enable, disable, export, policies, policy, smb, access, storage, virtual, machine, svm, control, resource, enable or disable export policies for smb access 
summary: ストレージ仮想マシン（SVM）上のSMBアクセスに関するエクスポート ポリシーを有効または無効にすることができます。エクスポート ポリシーを使用してリソースへのSMBアクセスを制御するかどうかは任意です。 
---
= SMB アクセスの ONTAP エクスポート ポリシーを有効または無効にする
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
ストレージ仮想マシン（SVM）上のSMBアクセスに関するエクスポート ポリシーを有効または無効にすることができます。エクスポート ポリシーを使用してリソースへのSMBアクセスを制御するかどうかは任意です。

.開始する前に
SMB のエクスポート ポリシーを有効にするための要件は次のとおりです：

* クライアントのエクスポート ルールを作成する前に、クライアントの DNS に「PTR」レコードが存在している必要があります。
* SVM が NFS クライアントへのアクセスを提供し、NFS アクセスに使用するホスト名が CIFS サーバ名と異なる場合は、ホスト名の「A」レコードと「PTR」レコードの追加セットが必要です。


.タスク概要
SVMに新しいCIFSサーバをセットアップする際、SMBアクセス用のエクスポート ポリシーの使用はデフォルトで無効になっています。認証プロトコル、クライアントIPアドレス、またはホスト名に基づいてアクセスを制御する場合は、SMBアクセス用のエクスポート ポリシーを有効にできます。SMBアクセス用のエクスポート ポリシーはいつでも有効または無効にできます。


NOTE: NFS 対応 SVM で CIFS/SMB のエクスポート ポリシーを有効にすると、Linux クライアントは SVM 上で `showmount -e`コマンドを使用して、関連付けられているエクスポート ポリシー ルールを持つすべての SMB ボリュームのジャンクション パスを表示できるようになります。

.手順
. 権限レベルをadvancedに設定します： `set -privilege advanced`
. エクスポート ポリシーを有効または無効にします：
+
** エクスポート ポリシーを有効にする： `vserver cifs options modify -vserver _vserver_name_ -is-exportpolicy-enabled true`
** エクスポート ポリシーを無効にする： `vserver cifs options modify -vserver _vserver_name_ -is-exportpolicy-enabled false`


. admin権限レベルに戻ります： `set -privilege admin`


.例
次の例は、エクスポート ポリシーを使用したSVM vs1上のリソースへのSMBクライアント アクセスの制御を有効にします。

[listing]
----
cluster1::> set -privilege advanced
Warning: These advanced commands are potentially dangerous; use them
only when directed to do so by technical support personnel.
Do you wish to continue? (y or n): y

cluster1::*> vserver cifs options modify -vserver vs1 -is-exportpolicy-enabled true

cluster1::*> set -privilege admin
----