---
permalink: smb-admin/enable-smb2-connections-domain-controllers-task.html 
sidebar: sidebar 
keywords: ontap, enable, smb, version, connect, domain, controller, default, smb2, enable smb2 connections to domain controllers 
summary: SMB.1以降では、ONTAP 9バージョン2.0からドメインコントローラへの接続を有効にすることができます。この処理は、ドメインコントローラでSMB 1.0を無効にしている場合に必要です。ONTAP 9 .2以降では、SMB2がデフォルトで有効になっています。 
---
= ドメインコントローラへのSMB2接続を有効にする
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
SMB.1以降では、ONTAP 9バージョン2.0からドメインコントローラへの接続を有効にすることができます。この処理は、ドメインコントローラでSMB 1.0を無効にしている場合に必要です。ONTAP 9 .2以降では、SMB2がデフォルトで有効になっています。

.タスクの内容
コマンドオプションを使用すると、 `smb2-enabled-for-dc-connections`使用しているONTAPのリリースに応じたシステムデフォルトが有効になります。ONTAP 9 .1のシステムデフォルトでは、SMB 1.0では有効になり、SMB 2.0では無効になります。ONTAP 9 .2のシステムデフォルトは、SMB 1.0では有効、SMB 2.0では有効です。ドメインコントローラが最初にSMB 2.0をネゴシエートできない場合は、SMB 1.0を使用します。

SMB 1.0は、ONTAPからドメインコントローラに対して無効にすることができます。ONTAP 9 .1でSMB 1.0が無効になっている場合は、ドメインコントローラと通信するためにSMB 2.0を有効にする必要があります。

詳細については以下を参照してください。

* link:../smb-config/verify-enabled-versions-task.html["有効なSMBのバージョンの確認"]です。
* link:supported-versions-functionality-concept.html["サポートされるSMBのバージョンと機能"]です。


[NOTE]
====
がwhileに `-smb1-enabled`設定されて `false`いる場合 `-smb1-enabled-for-dc-connections` `true`、ONTAPはクライアントとしてのSMB 1.0の接続を拒否しますが、サーバとしてのSMB 1.0のインバウンド接続は引き続き受け入れます。

====
.手順
. SMBセキュリティ設定を変更する前に、有効になっているSMBのバージョンを確認します。 `vserver cifs security show`
. リストを下にスクロールしてSMBのバージョンを確認します。
. オプションを使用して、該当するコマンドを実行し `smb2-enabled-for-dc-connections`ます。
+
|===
| SMB2 の設定 | 入力するコマンド 


 a| 
有効
 a| 
`vserver cifs security modify -vserver _vserver_name_ -smb2-enabled-for-dc-connections true`



 a| 
無効にする
 a| 
`vserver cifs security modify -vserver _vserver_name_ -smb2-enabled-for-dc-connections false`

|===

