---
permalink: smb-admin/file-locking-between-protocols-concept.html 
sidebar: sidebar 
keywords: file, lock, method, use, client, application, prevent, user, access, open, ontap, protocol, about file locking between protocols 
summary: ファイルロックは、別のユーザが以前に開いていたファイルにユーザがアクセスできないようにするためにクライアントアプリケーションで使用される方法です。ONTAPでファイルをロックする方法は、クライアントのプロトコルによって異なります。 
---
= プロトコル間のファイルロックについて
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
ファイルロックは、別のユーザが以前に開いていたファイルにユーザがアクセスできないようにするためにクライアントアプリケーションで使用される方法です。ONTAPでファイルをロックする方法は、クライアントのプロトコルによって異なります。

クライアントがNFSクライアントの場合はロックを推奨します。クライアントがSMBクライアントの場合はロックは必須です。

NFSファイルとSMBファイルのロックの違いのため、SMBアプリケーションで以前に開いたファイルにNFSクライアントからアクセスすると失敗することがあります。

NFSクライアントがSMBアプリケーションでロックされているファイルにアクセスしようとすると、次の状況が発生します。

* mixed形式またはNTFS形式のボリュームでは、、 `rmdir`などのファイル操作を `rm` `mv`行うと、NFSアプリケーションが失敗することがあります。
* NFSの読み取り処理と書き込み処理は、SMBの読み取り拒否および書き込み拒否のオープンモードによってそれぞれ拒否されます。
* ファイルの書き込み範囲が排他的なSMBバイトロックでロックされている場合、NFSの書き込み処理が失敗します。
* リンク解除
+
** NTFSファイルシステムでは、SMBとCIFSの削除処理がサポートされています。
+
ファイルは最後に閉じたあとで削除されます。

** NFSのリンク解除処理は、サポートされていません。
+
サポートされていない理由は、NTFSとSMBのセマンティクスが必要であり、NFSではLast Delete-On-Close処理がサポートされていないためです。

** UNIXファイルシステムでは、リンク解除操作がサポートされています。
+
サポートされている理由は、NFSとUNIXのセマンティクスが必要だからです。



* 名前変更
+
** NTFSファイルシステムでは、デスティネーション ファイルがSMBかCIFSから開かれている場合には、デスティネーション ファイルの名前を変更できます。
** NFSの名前変更はサポートされていません。
+
サポートされていない理由は、NTFSとSMBのセマンティクスが必要だからです。





UNIXセキュリティ形式のボリュームでは、NFSのリンク解除および名前変更処理でSMBのロック状態が無視され、ファイルへのアクセスが許可されます。UNIXセキュリティ形式のボリューム上の他のすべてのNFS処理では、SMBロック状態が維持されます。
