---
permalink: smb-admin/folder-redirection-store-data-concept.html 
sidebar: sidebar 
keywords: ontap, support, microsoft, folder, redirection, enable, administrator, redirect, location, cifs, server, windows, client, store, smb, share, use folder redirection to store data on a cifs server 
summary: ONTAP では、 Microsoft のフォルダリダイレクトをサポートしています。ユーザや管理者は、この機能を使用して、ローカルフォルダのパスを CIFS サーバの場所にリダイレクトできます。リダイレクトされたフォルダは、データが SMB 共有に格納されていても、ローカルの Windows クライアントに格納されたフォルダのように扱うことができます。 
---
= フォルダリダイレクトを使用して、 SMB サーバの概要にデータを格納します
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
ONTAP では、 Microsoft のフォルダリダイレクトをサポートしています。ユーザや管理者は、この機能を使用して、ローカルフォルダのパスを CIFS サーバの場所にリダイレクトできます。リダイレクトされたフォルダは、データが SMB 共有に格納されていても、ローカルの Windows クライアントに格納されたフォルダのように扱うことができます。

フォルダリダイレクトは、主に、ホームディレクトリをすでに導入しており、既存のホームディレクトリ環境との互換性を維持したい組織を対象としています。

* 「ドキュメント」、「デスクトップ」、「スタートメニュー」は、リダイレクトできるフォルダの例です。
* ユーザは、各自の Windows クライアントからフォルダをリダイレクトできます。
* 管理者は、 Active Directory で GPO を設定することで、フォルダリダイレクトを一元的に設定および管理できます。
* 移動プロファイルを設定している場合は、管理者がユーザデータとプロファイルデータを分けることができます。
* 管理者は、フォルダリダイレクトとオフラインファイルを使用して、ローカルフォルダのデータストレージを CIFS サーバにリダイレクトし、ユーザはコンテンツをローカルにキャッシュできます。


xref:offline-files-allow-caching-concept.adoc[オフラインファイルを使用したオフラインで使用するファイルのキャッシュ]

xref:roaming-profiles-store-user-profiles-concept.adoc[移動プロファイルを使用した SVM に関連付けられた CIFS サーバへのユーザプロファイルの一元的な格納]
