---
permalink: smb-admin/gpos-updated-server-concept.html 
sidebar: sidebar 
keywords: default, ontap, retrieve, applies, apply, group, policy, object, gpo, minute, security, refresh, update, automatic, manual, cifs, server, command, how gpos are updated on the cifs server 
summary: デフォルトでは、ONTAPはグループポリシーオブジェクト（GPO）の変更を90分ごとに取得して適用します。セキュリティ設定は16時間ごとに更新されます。ONTAPで自動的に更新される前にGPOを更新して新しいGPOポリシー設定を適用する場合は、ONTAPコマンドを使用してCIFSサーバで手動更新をトリガーできます。 
---
= CIFSサアハテノGPOノコウシンノカイヨウ
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
デフォルトでは、ONTAPはグループポリシーオブジェクト（GPO）の変更を90分ごとに取得して適用します。セキュリティ設定は16時間ごとに更新されます。ONTAPで自動的に更新される前にGPOを更新して新しいGPOポリシー設定を適用する場合は、ONTAPコマンドを使用してCIFSサーバで手動更新をトリガーできます。

* デフォルトでは、すべてのGPOが90分ごとに検証され、必要に応じて更新されます。
+
この間隔は設定可能で、および `Random offset`GPO設定を使用して設定できます `Refresh interval`。

+
ONTAPは、GPOの変更がないかどうかをActive Directoryに照会します。Active Directoryに記録されているGPOのバージョン番号がCIFSサーバ上のGPOのバージョン番号より大きい場合、ONTAPは新しいGPOを取得して適用します。バージョン番号が同じ場合、CIFSサーバ上のGPOは更新されません。

* セキュリティ設定のGPOは16時間ごとに更新されます。
+
ONTAPは、変更の有無にかかわらず、16時間ごとにセキュリティ設定のGPOを取得して適用します。

+
[NOTE]
====
デフォルト値の16時間は、現在のONTAPバージョンでは変更できません。これはWindowsクライアントのデフォルト設定です。

====
* ONTAPコマンドを使用して、すべてのGPOを手動で更新できます。
+
このコマンドは、Windowsの/force'コマンドをシミュレートし `gpupdate.exe``ます。



.関連情報
xref:manual-update-gpo-settings-task.adoc[CIFSサーバでのGPO設定の手動更新]
