---
permalink: smb-admin/improve-client-response-node-referrals-concept.html 
sidebar: sidebar 
keywords: auto, location, smb, automatic, node, referral, increase, client, performance, storage, virtual, machine, svm, request, host, response, improve, improve client response time by providing smb automatic node referrals with auto location 
summary: Auto Locationは、SMB自動ノード リファーラルを使用してStorage Virtual Machine（SVM）でのSMBクライアントのパフォーマンスを向上させます。自動ノード リファーラルは、要求しているクライアントを、データが存在するFlexVolをホストしているノードSVM上のLIFに自動的にリダイレクトします。これにより、クライアントの応答時間を短縮できます。 
---
= Auto LocationによるONTAP SMB自動ノード リファーラルの提供により、クライアントの応答時間を改善する方法について説明します。
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Auto Locationは、SMB自動ノード リファーラルを使用してStorage Virtual Machine（SVM）でのSMBクライアントのパフォーマンスを向上させます。自動ノード リファーラルは、要求しているクライアントを、データが存在するFlexVolをホストしているノードSVM上のLIFに自動的にリダイレクトします。これにより、クライアントの応答時間を短縮できます。

SMBクライアントがSVM上でホストされているSMB共有に接続するときに、要求しているデータを所有していないノード上のLIFを使用して接続することがあります。クライアントが接続しているノードは、クラスタ ネットワークを使用して別のノードが所有しているデータにアクセスします。SMB接続が要求されたデータを含むノード上にあるLIFを使用している場合、クライアントへの応答時間が短縮されます。

* ONTAPでは、MicrosoftのDFSリファーラルを使用して、要求されたファイルやフォルダがネームスペース内の別の場所でホストされていることをSMBクライアントに通知することで、この機能を実現します。
+
ノードがリファーラルを作成するのは、データを含むノード上にSVMのLIFがあることを特定した場合です。

* 自動ノード リファーラルでは、IPv4とIPv6のLIFのIPアドレスがサポートされます。
* リファーラルは、クライアント接続が経由する、共有のルートの場所に基づいて作成されます。
* リファーラルは、SMBネゴシエーション中に発生します。
+
リファーラルは、接続が確立される前に作成されます。ONTAPがターゲット ノードに参照先のSMBクライアントを通知したあと、接続が確立され、それ以降、クライアントはその参照先LIFパスを介してデータにアクセスします。これにより、クライアントにはより高速なデータ アクセスが提供され、クラスタの余分な通信も回避されます。

+
[NOTE]
====
共有が複数のジャンクション ポイントにまたがっていて、ジャンクションの一部が他のノードに格納されているボリュームを参照する場合、共有内のデータは複数のノードに分散されます。ONTAPは共有のルートに対してローカルなリファーラルを提供するため、これらのローカルでないボリュームに含まれるデータを取得するには、クラスタ ネットワークを使用する必要があります。このタイプのネームスペース アーキテクチャでは、自動ノード リファーラルによる大幅なパフォーマンス向上は望めない場合があります。

====


データをホストするノードに使用可能なLIFがない場合、ONTAPは、クライアントが選択したLIFを使用して接続を確立します。ファイルがSMBクライアントによって開かれると、クライアントは参照された同じ接続を介してファイルへのアクセスを継続します。

何らかの理由でCIFSサーバがリファーラルを作成できない場合でも、SMBサービスが中断されることはありません。自動ノード リファーラルが有効でない場合と同様にSMB接続が確立されます。

.関連情報
xref:improve-microsoft-remote-copy-performance-concept.adoc[Microsoftリモート コピーのパフォーマンスの向上]
