---
permalink: smb-admin/improve-client-response-node-referrals-concept.html 
sidebar: sidebar 
keywords: auto, location, smb, automatic, node, referral, increase, client, performance, storage, virtual, machine, svm, request, host, response, improve, improve client response time by providing smb automatic node referrals with auto location 
summary: Auto Location は、 SMB 自動ノードリファーラルを使用して Storage Virtual Machine （ SVM ）での SMB クライアントのパフォーマンスを向上します。自動ノードリファーラルは、要求しているクライアントを、データが存在するボリュームをホストしているノード SVM 上の LIF に自動的にリダイレクトします。これにより、クライアントの応答時間を改善できます。 
---
= Auto Location の概要を示す SMB 自動ノードリファーラルを提供することで、クライアントの応答時間を改善します
:icons: font
:imagesdir: ../media/


[role="lead"]
Auto Location は、 SMB 自動ノードリファーラルを使用して Storage Virtual Machine （ SVM ）での SMB クライアントのパフォーマンスを向上します。自動ノードリファーラルは、要求しているクライアントを、データが存在するボリュームをホストしているノード SVM 上の LIF に自動的にリダイレクトします。これにより、クライアントの応答時間を改善できます。

SMB クライアントが SVM 上でホストされている SMB 共有に接続するときに、要求されたデータを所有していないノード上の LIF を使用して接続することがあります。クライアントが接続しているノードは、クラスタネットワークを使用して別のノードが所有しているデータにアクセスします。SMB 接続が要求されたデータを含むノード上にある LIF を使用している場合、クライアントへの応答時間が短縮されます。

* ONTAP では、 Microsoft の DFS リファーラルを使用して、要求されたファイルやフォルダがネームスペース内の別の場所でホストされていることを SMB クライアントに通知することで、この機能を実現します。
+
ノードがリファーラルを作成するのは、データを含むノード上に SVM の LIF が 1 つあることを特定した場合です。

* 自動ノードリファーラルでは、 IPv4 と IPv6 の LIF の IP アドレスがサポートされます。
* リファーラルは、クライアントの接続に使用されている共有のルートの場所に基づいて作成されます。
* リファーラルは SMB ネゴシエーション中に発生します。
+
リファーラルは、接続が確立される前に作成されます。ONTAP がターゲットノードに参照先の SMB クライアントを通知したあと、接続が確立され、それ以降、クライアントはその参照先 LIF パスを介してデータにアクセスします。これにより、クライアントにはより高速なデータアクセスが提供され、クラスタの余分な通信も回避されます。

+
[NOTE]
====
共有が複数のジャンクションポイントにまたがっていて、ジャンクションの一部が他のノードに格納されているボリュームを参照する場合、共有内のデータは複数のノードに分散されます。ONTAP は共有のルートに対してローカルなリファーラルを提供するため、 ONTAP では、これらのローカルでないボリュームに含まれるデータを取得する際にクラスタネットワークを使用する必要があります。このタイプのネームスペースアーキテクチャでは、自動ノードリファーラルによる大幅なパフォーマンス向上は望めない場合があります。

====


データをホストするノードに使用可能な LIF がない場合、 ONTAP は、クライアントが選択した LIF を使用して接続を確立します。ファイルが SMB クライアントによって開かれると、クライアントは参照された同じ接続を介してファイルへのアクセスを継続します。

何らかの理由で CIFS サーバがリファーラルを作成できない場合でも、 SMB サービスが中断されることはありません。自動ノードリファーラルが有効でない場合と同様に SMB 接続が確立されます。

xref:improve-microsoft-remote-copy-performance-concept.adoc[Microsoft リモートコピーのパフォーマンスの向上]
