---
permalink: smb-admin/improve-microsoft-remote-copy-performance-concept.html 
sidebar: sidebar 
keywords: microsoft, offload, data, transfer, odx, copy, offload, enable, direct, compatible, computer, improve microsoft remote copy performance 
summary: Microsoft Offloaded Data Transfer（ODX）は、コピー オフロードとも呼ばれ、ホスト コンピューター経由でデータを転送せずに、互換性のあるストレージ デバイス内またはストレージ デバイス間で直接データを転送できます。 
---
= ONTAPSMBサーバーにおけるMicrosoftリモート コピーのパフォーマンス向上について学習します。
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Microsoft Offloaded Data Transfer（ODX）は、_copy offload_ とも呼ばれ、ホスト コンピューター経由でデータを転送せずに、互換性のあるストレージ デバイス内またはストレージ デバイス間で直接データを転送することを可能にします。

ONTAPでは、SMBプロトコルとSANプロトコルの両方でODXをサポートしています。ソースとデスティネーションのどちらについても、CIFSサーバとLUNの両方に対応しています。

ODX以外のファイル転送では、ソースからデータが読み取られ、ネットワーク経由でクライアント コンピュータに転送されます。クライアント コンピュータは、データをネットワーク経由でデスティネーションに転送します。つまり、クライアント コンピュータがソースからデータを読み取り、デスティネーションに書き込みます。ODXファイル転送では、データはソースからデスティネーションに直接コピーされます。

ODXオフロード コピーはソース ストレージとデスティネーション ストレージの間で直接実行されるため、パフォーマンスが大幅に向上します。実現するパフォーマンスの向上には、ソースとデスティネーションの間のコピー時間の短縮、クライアントでのリソース使用量（CPU、メモリ）の削減、ネットワークI/O帯域幅の使用量の削減などが挙げられます。

SMB環境では、この機能は、クライアントとストレージ サーバの両方でSMB 3.0およびODX機能がサポートされている場合にのみ使用できます。SAN環境では、この機能は、クライアントとストレージ サーバの両方でODX機能がサポートされている場合にのみ使用できます。ODXがサポートされていて有効になっているクライアント コンピュータでは、ファイルの移動やコピーを行う際に、オフロード ファイル転送が自動的かつ透過的に使用されます。ODXは、ファイルをエクスプローラでドラッグ アンド ドロップしたか、コマンドラインのファイル コピー コマンドを使用したか、クライアント アプリケーションによってファイル コピー要求が開始されたかに関係なく使用されます。

.関連情報
* xref:improve-client-response-node-referrals-concept.adoc[Auto Locationによる自動ノード紹介の提供によりクライアント応答時間を改善する方法について学習します]
* link:../smb-hyper-v-sql/index.html["Microsoft Hyper-VおよびSQL Server向けのSMBの設定"]

