---
permalink: smb-admin/install-self-signed-root-ca-certificate-svm-task.html 
sidebar: sidebar 
keywords: ldap, authentication, tls, bind, server, install, self-signed, root, ca, certificate, svm, install the self-signed root ca certificate on the svm 
summary: LDAPサーバにバインドするときにTLSを使用したLDAP認証が必要な場合は、まず自己署名されたルートCA証明書をSVMにインストールする必要があります。 
---
= ONTAP SMB SVMに自己署名ルートCA証明書をインストールする
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
LDAPサーバにバインドするときにTLSを使用したLDAP認証が必要な場合は、まず自己署名されたルートCA証明書をSVMにインストールする必要があります。

.タスク概要
TLS通信を使用するONTAP内のすべてのアプリケーションは、Online Certificate Status Protocol（OCSP）を使用してデジタル証明書のステータスを確認できます。LDAP over TLSでOCSPが有効になっている場合、失効した証明書は拒否され、接続は失敗します。

.手順
. 自己署名ルートCA証明書をインストールします。
+
.. 証明書のインストールを開始します： `security certificate install -vserver vserver_name -type server-ca`
+
コンソール出力に次のメッセージが表示されます： `Please enter Certificate: Press <Enter> when done`

.. 証明書 `.pem`ファイルをテキスト エディターで開き、 `-----BEGIN CERTIFICATE-----`で始まり `-----END CERTIFICATE-----`で終わる行を含む証明書をコピーして、コマンド プロンプトの後に貼り付けます。
.. 証明書が正しく表示されることを確認します。
.. Enterキーを押して、インストールを完了します。


. 証明書がインストールされていることを確認します： `security certificate show -vserver _vserver_name_`


.関連情報
* link:https://docs.netapp.com/us-en/ontap-cli/security-certificate-install.html["security certificate install"^]
* link:https://docs.netapp.com/us-en/ontap-cli/security-certificate-show.html["セキュリティ証明書の表示"^]

