---
permalink: smb-admin/join-svm-active-directory-domain-task.html 
sidebar: sidebar 
keywords: join, storage, virtual, machine, svm, active, directory, domain, delete, deleting, exist, smb, cifs, server, modify, domain, vserver, cifs, rejoin, join a svm to an active directory domain 
summary: vserver cifs modify コマンドでドメインを変更すると、既存の SMB サーバを削除することなく Storage Virtual Machine （ SVM ）を Active Directory ドメインに追加することができます。現在のドメインに参加しなおすことも、新しいドメインに参加することもできます。 
---
= SVM を Active Directory ドメインに追加します
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
を使用してドメインを変更すると、既存のSMBサーバを削除することなくStorage Virtual Machine（SVM）をActive Directoryドメインに追加することができます `vserver cifs modify` コマンドを実行します現在のドメインに参加しなおすことも、新しいドメインに参加することもできます。

.作業を開始する前に
* SVM の DNS 設定が完了している必要があります。
* SVM の DNS 設定がターゲットドメインを提供できる必要があります。
+
DNS サーバには、ドメイン LDAP およびドメインコントローラサーバのサービスロケーションレコード（ SRV ）が含まれている必要があります。



.このタスクについて
* Active Directory ドメインの変更を続行するには、 CIFS サーバの管理ステータスを「所有」に設定する必要があります。
* コマンドが正常に完了すると、管理ステータスは自動的に「 up 」に設定されます。
* ドメインに参加する場合、このコマンドの実行には数分かかることがあります。


.手順
. SVMをCIFSサーバドメインに追加します。 `vserver cifs modify -vserver _vserver_name_ -domain _domain_name_ -status-admin down`
+
詳細については、のマニュアルページを参照してください `vserver cifs modify` コマンドを実行します新しいドメイン用にDNSを再設定する必要がある場合は、のマニュアルページを参照してください `vserver dns modify` コマンドを実行します

+
SMBサーバ用のActive Directoryマシンアカウントを作成するには、にコンピュータを追加するための十分な権限があるWindowsアカウントの名前とパスワードを指定する必要があります `ou= _example_ ou` 内のコンテナ `_example_`.comドメイン

+
ONTAP 9.7 以降では、権限がある Windows アカウントの名前とパスワードの代わりに、 keytab ファイルの URI を AD 管理者から提供される場合があります。URIを受け取ったら、に含めます `-keytab-uri` パラメータと `vserver cifs` コマンド

. CIFSサーバが目的のActive Directoryドメイン内にあることを確認します。 `vserver cifs show`


.例
次の例では、 SVM vs1 上にある SMB サーバ「 CIFSSERVER1 」を keytab 認証を使用して example.com ドメインに追加します。

[listing]
----

cluster1::> vserver cifs modify -vserver vs1 -domain example.com -status-admin down -keytab-uri http://admin.example.com/ontap1.keytab

cluster1::> vserver cifs show

          Server       Status       Domain/Workgroup  Authentication
Vserver   Name         Admin        Name              Style
--------- -----------  ---------    ----------------  --------------
vs1       CIFSSERVER1  up           EXAMPLE          domain
----