---
permalink: smb-admin/list-supported-privileges-reference.html 
sidebar: sidebar 
keywords: ontap, predefined, support, privilege, local, group, add, user, exist, domain, list of supported privileges 
summary: ONTAP には、一連のサポートされる権限があらかじめ定義されています特定の事前定義されたローカルグループには、これらの権限の一部がデフォルトで追加されています。事前定義グループの権限は追加または削除できます。また、新しいローカルユーザまたはローカルグループを作成して、そのグループや、既存のドメインユーザおよびグループに権限を追加することもできます。 
---
= サポートされる権限のリスト
:icons: font
:imagesdir: ../media/


[role="lead"]
ONTAP には、一連のサポートされる権限があらかじめ定義されています特定の事前定義されたローカルグループには、これらの権限の一部がデフォルトで追加されています。事前定義グループの権限は追加または削除できます。また、新しいローカルユーザまたはローカルグループを作成して、そのグループや、既存のドメインユーザおよびグループに権限を追加することもできます。

次の表に、 Storage Virtual Machine （ SVM ）でサポートされる権限の一覧と、その権限が割り当てられている BUILTIN グループを示します。

|===
| 権限の名前 | デフォルトのセキュリティ設定 | 説明 


 a| 
'eTcbPrivilege]
 a| 
なし
 a| 
オペレーティングシステムの一部として機能します



 a| 
'ebackupPrivilege] を選択します
 a| 
'BUILTIN\Administrators''BUILTIN\Backup Operators' です
 a| 
ACL を無視してファイルとディレクトリをバックアップします



 a| 
'eRestorePrivilege] を選択します
 a| 
'BUILTIN\Administrators''BUILTIN\Backup Operators' です
 a| 
ファイルおよびディレクトリをリストアし、 ACL を上書きすべての有効なユーザまたはグループの SID をファイル所有者として設定します



 a| 
'eTakeOwnershipPrivilege]
 a| 
「 BUILTIN\Administrators 」
 a| 
ファイルまたはその他のオブジェクトの所有権を取得します



 a| 
「エレズ・ナイン」
 a| 
「 BUILTIN\Administrators 」
 a| 
監査の管理これには ' セキュリティ・ログの表示 ' ダンプ ' 消去が含まれます



 a| 
「エレズ・ナイン」
 a| 
「 BUILTIN\Administrators 」、「 BUILTIN\Backup Operators 」、「 BUILTIN\Power Users 」、「 BUILTIN\Users 」、「 Everyone 」
 a| 
トラバースチェックのバイパスこの権限を持つユーザは、フォルダ、シンボリックリンク、またはジャンクションをトラバースするためのトラバース（ x ）権限は必要ありません。

|===
* 関連情報 *

xref:manage-local-privileges-concept.adoc[ローカル権限の管理]

xref:configure-bypass-traverse-checking-concept.adoc[トラバースチェックのバイパスの設定]
