---
permalink: smb-admin/local-users-groups-concepts-concept.html 
sidebar: sidebar 
keywords: local, user, group, basic, information, determine, determining, configure, environment, local users and groups concepts 
summary: ローカルユーザとローカルグループを設定して使用するかどうかを決定する前に、ローカルユーザとローカルグループの定義を理解し、基本的ないくつかの情報を理解しておく必要があります。 
---
= ローカルユーザとローカルグループの概念
:icons: font
:imagesdir: ../media/


[role="lead"]
ローカルユーザとローカルグループを設定して使用するかどうかを決定する前に、ローカルユーザとローカルグループの定義を理解し、基本的ないくつかの情報を理解しておく必要があります。

* * ローカルユーザー *
+
一意の Security Identifier （ SID ；セキュリティ識別子）を持つユーザアカウント。そのユーザアカウントを作成した Storage Virtual Machine （ SVM ）上でのみ認識されます。ローカルユーザアカウントには、ユーザ名や SID などの一連の属性があります。ローカルユーザアカウントは、 NTLM 認証を使用して CIFS サーバ上でローカルに認証します。

+
ユーザアカウントには次のような用途があります。

+
** ユーザに _ ユーザ権限の管理 _ 権限を付与するために使用します。
** SVM が所有するファイルリソースおよびフォルダリソースに対する共有レベルとファイルレベルのアクセスを制御する。


* * ローカルグループ *
+
一意の SID を持つグループ。そのグループを作成した SVM 上でのみ認識が可能です。グループには一連のメンバーが含まれます。メンバーは、ローカルユーザ、ドメインユーザ、ドメイングループ、およびドメインマシンアカウントです。グループは、作成、変更、または削除できます。

+
グループにはいくつかの用途があります。

+
** メンバーに _User Rights Management_Privileges を付与するために使用します。
** SVM が所有するファイルリソースおよびフォルダリソースに対する共有レベルとファイルレベルのアクセスを制御する。


* * ローカルドメイン *
+
ローカルスコープを持つドメイン。 SVM によりバインドされています。ローカルドメインの名前は CIFS サーバの名前です。ローカルユーザとローカルグループはローカルドメインに含まれています。

* * Security Identifier （ SID ；セキュリティ識別子） *
+
SID は、 Windows 形式のセキュリティプリンシパルを識別する可変長の数値です。たとえば、通常の SID の場合は、次のような形式になります。 S-1-5-21-3139654847-1303905135-2517279418-123456 。

* * NTLM 認証 *
+
CIFS サーバ上のユーザの認証で使用される、 Microsoft Windows のセキュリティ方式。

* * 複製されたクラスタデータベース（ RDB ） *
+
クラスタ内の各ノードのインスタンスを持つ複製されたデータベース。ローカルユーザとローカルグループのオブジェクトは、 RDB に格納されます。


