---
permalink: smb-admin/manage-file-security-clients-unix-style-concept.html 
sidebar: sidebar 
keywords: present, file, security, smb, client, unix, security-style, data, disabling, disable, presentation, ntfs, acl, client, advantage, setting, business, requirement, manage how file security is presented to smb clients for unix security-style data 
summary: SMBクライアントへのNTFS ACLの提供を有効または無効にすることによって、UNIXセキュリティ形式のデータに対するファイル セキュリティのSMBクライアントへの提供方法を選択できます。それぞれの設定の利点を理解して、ビジネス要件に適した方を選ぶようにしてください。 
---
= UNIXセキュリティ形式のデータに対して、SMBクライアントにONTAPファイルセキュリティを提供する方法について説明します。
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
SMBクライアントへのNTFS ACLの提供を有効または無効にすることによって、UNIXセキュリティ形式のデータに対するファイル セキュリティのSMBクライアントへの提供方法を選択できます。それぞれの設定の利点を理解して、ビジネス要件に適した方を選ぶようにしてください。

デフォルトでは、UNIXセキュリティ形式のボリュームに対するUNIXアクセス権がNTFS ACLとしてSMBクライアントに提供されます。これは次のような場合に適しています。

* Windows のプロパティ ボックスの *セキュリティ* タブを使用して、UNIX 権限を表示および編集します。
+
処理がUNIXシステムで許可されていなければ、Windowsクライアントからアクセス権を変更することはできません。たとえば、所有していないファイルの所有権を変更することはできません。これは、UNIXシステムではこうした処理が許可されていないためです。この制限により、SMBクライアントは、ファイルやフォルダに対して設定されたUNIXアクセス権をバイパスできないようになっています。

* UNIXセキュリティ形式のボリュームに格納されたファイルの編集や保存に特定のWindowsアプリケーション（Microsoft Officeなど）を使用しており、ONTAPでの保存時にUNIXアクセス権を維持する必要がある場合。
* 使用するファイルのNTFS ACLを読み取ることを想定した特定のWindowsアプリケーションが環境にある場合。


状況に応じて、NTFS ACLとしてのUNIXアクセス権の提供を無効にすることもできます。この機能を無効にすると、UNIXセキュリティ形式のボリュームがFATボリュームとしてSMBクライアントに提供されます。UNIXセキュリティ形式のボリュームをFATボリュームとしてSMBクライアントに提供するのは、次のような場合です。

* UNIXアクセス権の変更は、マウントを使用してUNIXクライアントでしか行わない場合。
+
UNIXセキュリティ形式のボリュームがSMBクライアントでマッピングされている場合、[セキュリティ]タブで操作することはできません。マッピングされたドライブは、ファイル権限がない、FATファイルシステムでフォーマットされたドライブとして表示されます。

* SMBを使用するアプリケーションでアクセスするファイルやフォルダにNTFS ACLを設定しており、データがUNIXセキュリティ形式のボリュームにあると失敗する可能性がある場合。
+
ONTAPではボリュームがFATとして報告され、アプリケーションでACLの変更は試行されません。



.関連情報
* xref:configure-security-styles-task.adoc[FlexVolでのセキュリティ形式の設定]
* xref:configure-security-styles-qtrees-task.adoc[qtreeでのセキュリティ形式の設定]

