---
permalink: smb-admin/manage-local-group-membership-task.html 
sidebar: sidebar 
keywords: manage, local, group, membership, add, removing, remove, local, domain, user, domain, group, control, access, place, privilege, associate, manage local group membership 
summary: ローカル グループ メンバーシップの管理では、ローカル ユーザやドメイン ユーザの追加と削除、ドメイン グループの追加と削除ができます。この機能は、特定のグループに対するアクセス制御に基づいてデータへのアクセスを制御したり、グループに関連した権限をユーザに付与したりするうえで役に立ちます。 
---
= ローカルONTAP SMBグループメンバーシップを管理する
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
ローカル グループ メンバーシップの管理では、ローカル ユーザやドメイン ユーザの追加と削除、ドメイン グループの追加と削除ができます。この機能は、特定のグループに対するアクセス制御に基づいてデータへのアクセスを制御したり、グループに関連した権限をユーザに付与したりするうえで役に立ちます。

.タスク概要
ローカル グループへのメンバーの追加に関するガイドラインを次に示します。

* 特別な _Everyone_ グループにユーザーを追加することはできません。
* ローカル グループにユーザを追加する前に、あらかじめそのグループが存在している必要があります。
* ローカル グループにユーザを追加する前に、あらかじめそのユーザが存在している必要があります。
* 別のローカル グループにローカル グループを追加することはできません。
* ローカル グループにドメイン ユーザまたはグループを追加するには、Data ONTAPでSIDを名前解決できる必要があります。


ローカル グループからのメンバーの削除に関するガイドラインを次に示します。

* 特別な _Everyone_ グループからメンバーを削除することはできません。
* メンバーを削除するグループが存在している必要があります。
* グループから削除するメンバーの名前を、対応するSIDに対して、ONTAPで解決できる必要があります。


.手順
. グループのメンバーを追加または削除します。
+
|===
| 状況 | 次に、コマンドを使用します... 


 a| 
グループへのメンバーの追加
 a| 
`+vserver cifs users-and-groups local-group add-members -vserver _vserver_name_ -group-name _group_name_ -member-names name[,...]+`指定したローカルグループに追加するローカルユーザー、ドメインユーザー、またはドメイングループのコンマ区切りリストを指定できます。



 a| 
グループからのメンバーの削除
 a| 
`+vserver cifs users-and-groups local-group remove-members -vserver _vserver_name_ -group-name _group_name_ -member-names name[,...]+`指定したローカル グループから削除するローカル ユーザー、ドメイン ユーザー、またはドメイン グループのコンマ区切りリストを指定できます。

|===
+
次の例では、SVM vs1上のローカルグループ「`SMB_SERVER\engineering`」に、ローカルユーザー「`SMB_SERVER\sue`」とドメイングループ「`AD_DOM\dom_eng`」を追加します：

+
[listing]
----
cluster1::> vserver cifs users-and-groups local-group add-members -vserver vs1 -group-name SMB_SERVER\engineering -member-names SMB_SERVER\sue,AD_DOMAIN\dom_eng
----
+
次の例では、SVM vs1上のローカルグループ"`SMB_SERVER\engineering`"からローカルユーザー"`SMB_SERVER\sue`"と"`SMB_SERVER\james`"を削除します：

+
[listing]
----
cluster1::> vserver cifs users-and-groups local-group remove-members -vserver vs1 -group-name SMB_SERVER\engineering -member-names SMB_SERVER\sue,SMB_SERVER\james
----


.関連情報
xref:display-members-local-groups-task.adoc[ローカル グループのメンバーに関する情報の表示]
