---
permalink: smb-admin/map-administrators-group-root-task.html 
sidebar: sidebar 
keywords: cifs, client, environment, storage, virtual, machine, svm, multiprotocol, storage, system, windows, account, root, privilege, svm, sufficient, user, right, map the administrators group to root 
summary: 環境内のクライアントがすべて CIFS クライアントで、 Storage Virtual Machine （ SVM ）がマルチプロトコルストレージシステムとしてセットアップされている場合は、 SVM 上のファイルにアクセスするための root 権限を持つ Windows アカウントが少なくとも 1 つ必要です。 十分なユーザ権限がないため、この SVM を管理できません。 
---
= Administrators グループをルートにマッピングします
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
環境内のクライアントがすべて CIFS クライアントで、 Storage Virtual Machine （ SVM ）がマルチプロトコルストレージシステムとしてセットアップされている場合は、 SVM 上のファイルにアクセスするための root 権限を持つ Windows アカウントが少なくとも 1 つ必要です。 十分なユーザ権限がないため、この SVM を管理できません。

.このタスクについて
ただし ' ストレージ・システムが NTFS 専用として設定されている場合 '/etc ディレクトリにはファイル・レベルの ACL があり ' この ACL によって 'Administrators グループは ONTAP 構成ファイルにアクセスできます

.手順
. 権限レベルを advanced に設定します。「 set -privilege advanced 」
. 必要に応じて、 Administrators グループをルートにマッピングする CIFS サーバオプションを設定します。
+
|===
| 状況 | 作業 


 a| 
管理者グループメンバーをルートにマッピングします
 a| 
「 vserver cifs options modify -vserver _vserver_name __ is-admin-users-mapped -to-root-enabled true 」 -administrators グループ内のすべてのアカウントは、アカウントを root にマッピングする「 /etc/usermap.cfg 」エントリがない場合でも root とみなされます。Administrators グループに属するアカウントを使用してファイルを作成する場合、 UNIX クライアントからファイルを表示するときに、ファイルはルートによって所有されます。



 a| 
Administrators グループメンバーのルートへのマッピングを無効にします
 a| 
「 vserver cifs options modify -vserver _vserver_name -is-admin-users-mapped -to-root-enabled false 」 Administrators グループ内の「 Accounts 」がルートにマッピングされなくなりました。ルートへのマッピングは、単一のユーザに対して明示的にのみ実行できます。

|===
. オプションが目的の値に設定されていることを確認します。 vserver cifs options show -vserver vserver_name _`
. admin 権限レベルに戻ります。「 set -privilege admin 」

