---
permalink: smb-admin/modify-branchcache-config-task.html 
sidebar: sidebar 
keywords: modify, configuration, branchcache, service, svm, store, directory, path, hash, maximum, size, operating, mode, version, modify branchcache configurations 
summary: SVM上のBranchCacheサービスの設定では、ハッシュ ストア ディレクトリのパス、最大サイズ、動作モード、サポートするBranchCachetのバージョンなどの設定を変更できます。また、ハッシュ ストアを含めるボリュームのサイズを拡張することもできます。 
---
= ONTAP SMB共有のBranchCache構成を変更する
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
SVM上のBranchCacheサービスの設定では、ハッシュ ストア ディレクトリのパス、最大サイズ、動作モード、サポートするBranchCachetのバージョンなどの設定を変更できます。また、ハッシュ ストアを含めるボリュームのサイズを拡張することもできます。

.手順
. 適切な処理を実行します。
+
|===
| 状況 | 入力するコマンド 


 a| 
ハッシュ ストア ディレクトリのサイズ変更
 a| 
`vserver cifs branchcache modify -vserver vserver_name -hash-store-max-size {integer[KB|MB|GB|TB|PB]}`



 a| 
ハッシュ ストアを含むボリューム サイズの拡張
 a| 
`volume size -vserver vserver_name -volume volume_name -new-size new_size[k|m|g|t]`ハッシュストアを含むボリュームがいっぱいになった場合、ボリュームのサイズを増やすことができる場合があります。新しいボリュームサイズは、数値と単位指定で指定できます。

link:../volumes/commands-manage-flexvol-volumes-reference.html["FlexVolボリュームの管理"]の詳細はこちら



 a| 
ハッシュ ストア ディレクトリのパス変更
 a| 
`vserver cifs branchcache modify -vserver vserver_name -hash-store-path path -flush-hashes {true|false}` SVM が SVM ディザスタリカバリソースである場合、ハッシュパスをルートボリューム上に配置することはできません。これは、ルートボリュームがディザスタリカバリ先にレプリケートされないためです。

BranchCacheハッシュ パスには、ファイル名に使用できる文字と空白を含めることができます。

ハッシュパスを変更する場合、 `-flush-hashes`は必須パラメータであり、ONTAPが元のハッシュストアの場所からハッシュをフラッシュするかどうかを指定します。 `-flush-hashes`パラメータには以下の値を設定できます：

**  `true`を指定すると、ONTAPは元の場所にあるハッシュを削除し、BranchCache対応クライアントから新しい要求があったときに新しい場所に新しいハッシュを作成します。
**  `false`を指定した場合、ハッシュはフラッシュされません。
+
この場合、後で、ハッシュ ストア ディレクトリのパスを元の場所に戻して、既存のハッシュを再利用することができます。





 a| 
動作モードの変更
 a| 
`vserver cifs branchcache modify -vserver vserver_name -operating-mode {per-share|all-shares|disable}`

動作モードを変更する場合は、以下の点に注意してください。

** SMBセッションのセットアップ時に、ONTAPによって、BranchCacheの共有のサポートが通知されます。
** BranchCacheが有効化されたときにすでにセッションを確立していたクライアントは、キャッシュされていた内容をこの共有で使用するために、接続をいったん解除したあとに再度接続する必要があります。




 a| 
サポートするBranchCacheバージョンの変更
 a| 
`vserver cifs branchcache modify -vserver vserver_name -versions {v1-enable|v2-enable|enable-all}`

|===
.  `vserver cifs branchcache show`コマンドを使用して構成の変更を確認します。

