---
permalink: smb-admin/modify-server-kerberos-security-settings-task.html 
sidebar: sidebar 
keywords: modify, cifs, server, kerberos, security, setting, clock, skew, time, ticket, lifetime, renewal, modify the cifs server kerberos security ticket settings 
summary: 許可されるKerberosクロックスキューの最大時間、Kerberosチケットの有効期間、チケットを更新する最大日数など、CIFSサーバのKerberosセキュリティ設定を変更できます。 
---
= CIFSサーバのKerberosセキュリティ設定を変更します。
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
許可されるKerberosクロックスキューの最大時間、Kerberosチケットの有効期間、チケットを更新する最大日数など、CIFSサーバのKerberosセキュリティ設定を変更できます。

.タスクの内容
コマンドによるCIFSサーバのKerberos設定の変更では `vserver cifs security modify`、パラメータで指定した単一のStorage Virtual Machine（SVM）の設定のみを変更 `-vserver`できます。Active Directoryのグループポリシーオブジェクト（GPO）を使用すると、同じActive Directoryドメインに属するクラスタ上のすべてのSVMのKerberosセキュリティ設定を一元管理できます。

.手順
. 次の操作を1つ以上実行します。
+
|===


| 状況 | 入力するコマンド 


 a| 
Kerberosクロックスキューの許容最大時間を分（9.13.1以降）または秒（9.12.1以前）で指定します。
 a| 
`vserver cifs security modify -vserver _vserver_name_ -kerberos-clock-skew _integer_in_minutes_`

デフォルト設定は5分です。



 a| 
Kerberosチケットの有効期間を時間単位で指定します。
 a| 
`vserver cifs security modify -vserver _vserver_name_ -kerberos-ticket-age integer_in_hours`

デフォルト設定は10時間です。



 a| 
チケットの最大更新日数を指定します。
 a| 
`vserver cifs security modify -vserver _vserver_name_ -kerberos-renew-age _integer_in_days_`

デフォルトの設定は7日です。



 a| 
KDC上のソケットのタイムアウトを指定します。このタイムアウトを過ぎると、すべてのKDCが到達不能としてマークされます。
 a| 
`vserver cifs security modify -vserver _vserver_name_ -kerberos-kdc-timeout _integer_in_seconds_`

デフォルト設定は3秒です。

|===
. Kerberosセキュリティ設定を確認します。
+
`vserver cifs security show -vserver _vserver_name_`



.例
次の例では、 SVM vs1 の Kerberos セキュリティ設定を「 Kerberos Clock Skew 」に 3 分、「 Kerberos Ticket Age 」に 8 時間に変更しています。

[listing]
----
cluster1::> vserver cifs security modify -vserver vs1 -kerberos-clock-skew 3 -kerberos-ticket-age 8

cluster1::> vserver cifs security show -vserver vs1

Vserver: vs1

                    Kerberos Clock Skew:                   3 minutes
                    Kerberos Ticket Age:                   8 hours
                   Kerberos Renewal Age:                   7 days
                   Kerberos KDC Timeout:                   3 seconds
                    Is Signing Required:               false
        Is Password Complexity Required:                true
   Use start_tls For AD LDAP connection:               false
              Is AES Encryption Enabled:               false
                 LM Compatibility Level:  lm-ntlm-ntlmv2-krb
             Is SMB Encryption Required:               false
----
.関連情報
link:display-server-security-settings-task.html["CIFSサーバのセキュリティ設定に関する情報の表示"]

link:supported-gpos-concept.html["サポートされるGPO"]

link:applying-group-policy-objects-concept.html["CIFSサーバへのグループ ポリシー オブジェクトの適用"]
