---
permalink: smb-admin/modify-servers-task.html 
sidebar: sidebar 
keywords: move, smb, server, workgroup, active, directory, domain, vserver, cifs, modify, command, modify smb servers 
summary: vserver cifs modify コマンドを使用して、SMB サーバをワークグループから Active Directory ドメイン、ワークグループから別のワークグループ、または Active Directory ドメインからワークグループに移動できます。 
---
= ONTAP SMBサーバーの変更
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
 `vserver cifs modify`コマンドを使用して、SMBサーバをワークグループからActive Directoryドメイン、ワークグループから別のワークグループ、またはActive Directoryドメインからワークグループに移動できます。

.タスク概要
SMBサーバーのその他の属性（SMBサーバー名や管理ステータスなど）を変更することもできます。link:https://docs.netapp.com/us-en/ontap-cli/vserver-cifs-modify.html["ONTAPコマンド リファレンス"^]の `vserver cifs modify`の詳細をご覧ください。

.オプション
* SMB サーバーをワークグループから Active Directory ドメインに移動します：
+
.. SMB サーバーの管理ステータスを `down`に設定します。
+
[listing]
----
Cluster1::>vserver cifs modify -vserver vs1 -status-admin down
----
.. SMB サーバーをワークグループから Active Directory ドメインに移動します： `vsserver cifs modify -vserver _vserver_name_ -domain _domain_name_`
+
[listing]
----
Cluster1::>vserver cifs modify -vserver vs1 -domain example.com
----
+
SMB サーバーの Active Directory マシン アカウントを作成するには、 `_example_`.com ドメイン内の `ou=_example_ ou`コンテナーにコンピューターを追加するための十分な権限を持つ Windows アカウントの名前とパスワードを入力する必要があります。

+
ONTAP 9.7以降、AD管理者は、特権Windowsアカウントの名前とパスワードを提供する代わりに、キータブ ファイルへのURIを提供できるようになりました。URIを受け取ったら、 `vserver cifs`コマンドの `-keytab-uri`パラメータに含めてください。



* SMB サーバーをワークグループから別のワークグループに移動します：
+
.. SMB サーバーの管理ステータスを `down`に設定します。
+
[listing]
----
Cluster1::>vserver cifs modify -vserver vs1 -status-admin down
----
.. SMB サーバーのワークグループを変更します： `vserver cifs modify -vserver _vserver_name_ -workgroup _new_workgroup_name_`
+
[listing]
----
Cluster1::>vserver cifs modify -vserver vs1 -workgroup workgroup2
----


* SMB サーバーを Active Directory ドメインからワークグループに移動します：
+
.. SMB サーバーの管理ステータスを `down`に設定します。
+
[listing]
----
Cluster1::>vserver cifs modify -vserver vs1 -status-admin down
----
.. SMB サーバーを Active Directory ドメインからワークグループに移動します： `vserver cifs modify -vserver _vserver_name_ -workgroup _workgroup_name_`
+
[listing]
----
cluster1::> vserver cifs modify -vserver vs1 -workgroup workgroup1
----
+
[NOTE]
====
ワークグループモードに入るには、継続的可用性共有、シャドウコピー、AESなど、すべてのドメインベースの機能を無効にし、その設定をシステムによって自動的に削除する必要があります。ただし、「EXAMPLE.COM\userName」などのドメイン設定された共有ACLは正常に動作しませんが、ONTAPでは削除できません。コマンド完了後、外部ツールを使用してできるだけ早くこれらの共有ACLを削除してください。AESが有効になっている場合は、「EXAMPLE.COM」ドメインでAESを無効にするための十分な権限を持つWindowsアカウントの名前とパスワードの入力を求められる場合があります。

====
+
***  `vserver cifs modify`コマンドの適切なパラメータを使用して、他の属性を変更します。





