---
permalink: smb-admin/monitor-signed-session-statistics-task.html 
sidebar: sidebar 
keywords: monitor, smb, session, statistic, establish, sign, monitor smb signed session statistics 
summary: SMBセッションの統計を監視し、確立されたセッションのうち、署名されたセッションと署名されていないセッションを区別できます。 
---
= ONTAP SMB署名セッション統計を監視する
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
SMBセッションの統計を監視し、確立されたセッションのうち、署名されたセッションと署名されていないセッションを区別できます。

.タスク概要
 `statistics`上級権限レベルのコマンドは、署名済みSMBセッションの数を監視するために使用できる `signed_sessions`カウンタを提供します。 `signed_sessions`カウンタは、以下の統計オブジェクトで使用できます：

* `cifs`を使用すると、すべての SMB セッションの SMB 署名を監視できます。
* `smb1`を使用すると、SMB 1.0 セッションの SMB 署名を監視できます。
* `smb2`では、SMB 2.x および SMB 3.0 セッションの SMB 署名を監視できます。
+
 `smb2`オブジェクトの出力には SMB 3.0 統計が含まれます。



署名されたセッションの数とセッションの合計数を比較する場合は、 `signed_sessions`カウンターの出力と `established_sessions`カウンターの出力を比較できます。

データを取得して表示するには、統計サンプルの収集を開始する必要があります。データ収集を停止しなければ、サンプルからデータを表示できます。データ収集を停止すると、固定のサンプル データが表示されます。データ収集を停止しなければ、以前のクエリとの比較に使用できる更新されたデータを入手できます。この比較は、パフォーマンスの傾向を確認するのに役立ちます。

.手順
. 権限レベルを詳細に設定します：+
`set -privilege advanced`
. データ収集を開始する：+
`statistics start -object {cifs|smb1|smb2} -instance instance -sample-id _sample_ID_ [-node _node_name_]`
+
 `-sample-id`パラメータを指定しない場合、コマンドはサンプル識別子を生成し、このサンプルをCLIセッションのデフォルト サンプルとして定義します。 `-sample-id`の値はテキスト文字列です。同じCLIセッション中にこのコマンドを実行し、 `-sample-id`パラメータを指定しない場合、コマンドは以前のデフォルト サンプルを上書きします。

+
オプションで、統計情報を収集するノードを指定できます。ノードを指定しない場合、サンプルは、クラスタ内のすべてのノードについて統計情報を収集します。

+
 `statistics start`の詳細については、link:https://docs.netapp.com/us-en/ontap-cli/statistics-start.html["ONTAPコマンド リファレンス"^]を参照してください。

.  `statistics stop`コマンドを使用して、サンプルのデータ収集を停止します。
+
 `statistics stop`の詳細については、link:https://docs.netapp.com/us-en/ontap-cli/statistics-stop.html["ONTAPコマンド リファレンス"^]を参照してください。

. 次のコマンドによりSMB署名統計を表示します。
+
|===
| ...の情報を表示する場合は | 入力する内容 


 a| 
署名されたセッション
 a| 
`show -sample-id sample_ID -counter signed_sessions|_node_name_ [-node _node_name_]`



 a| 
署名されたセッションおよび確立されたセッション
 a| 
`show -sample-id _sample_ID_ -counter signed_sessions|established_sessions|_node_name_ [-node node_name]`

|===
+
1 つのノードのみの情報を表示する場合は、オプションの `-node`パラメータを指定します。

+
 `statistics show`の詳細については、link:https://docs.netapp.com/us-en/ontap-cli/statistics-show.html["ONTAPコマンド リファレンス"^]をご覧ください。

. admin権限レベルに戻ります：+
`set -privilege admin`


.例
[%collapsible]
====
次の例は、「vs1」というStorage Virtual Machine（SVM）について、SMB 2.xとSMB 3.0のそれぞれの署名統計情報を監視する方法を示します。

次のコマンドは、advanced権限レベルへの変更を行います。

[listing]
----
cluster1::> set -privilege advanced

Warning: These advanced commands are potentially dangerous; use them only when directed to do so by support personnel.
Do you want to continue? {y|n}: y
----
次のコマンドは、新しいサンプルのデータ収集を開始します。

[listing]
----
cluster1::*> statistics start -object smb2 -sample-id smbsigning_sample -vserver vs1
Statistics collection is being started for Sample-id: smbsigning_sample
----
次のコマンドは、サンプルのデータ収集を停止します。

[listing]
----
cluster1::*> statistics stop -sample-id smbsigning_sample
Statistics collection is being stopped for Sample-id: smbsigning_sample
----
次のコマンドでは、ノードが署名、確立した各SMBセッションをサンプルから表示します。

[listing]
----
cluster1::*> statistics show -sample-id smbsigning_sample -counter signed_sessions|established_sessions|node_name

Object: smb2
Instance: vs1
Start-time: 2/6/2013 01:00:00
End-time: 2/6/2013 01:03:04
Cluster: cluster1

    Counter                                              Value
    -------------------------------- -------------------------
    established_sessions                                     0
    node_name                                           node1
    signed_sessions                                          0
    established_sessions                                     1
    node_name                                           node2
    signed_sessions                                          1
    established_sessions                                     0
    node_name                                           node3
    signed_sessions                                          0
    established_sessions                                     0
    node_name                                           node4
    signed_sessions                                          0
----
次のコマンドでは、ノード2が署名したSMBセッションをサンプルから表示します。

[listing]
----
cluster1::*> statistics show -sample-id smbsigning_sample -counter signed_sessions|node_name -node node2

Object: smb2
Instance: vs1
Start-time: 2/6/2013 01:00:00
End-time: 2/6/2013 01:22:43
Cluster: cluster1

    Counter                                              Value
    -------------------------------- -------------------------
    node_name                                            node2
    signed_sessions                                          1
----
次のコマンドで、admin権限レベルに戻ります。

[listing]
----
cluster1::*> set -privilege admin
----
====
.関連情報
* xref:determine-sessions-signed-task.adoc[SMBセッションが署名されているかどうかの確認]
* link:../performance-admin/index.html["パフォーマンスの監視と管理 - 概要"]

