---
permalink: smb-admin/mount-unmount-existing-volumes-nas-namespace-task.html 
sidebar: sidebar 
keywords: volume, mount, nas, namespace, configure, client, access, data, contain, storage, virtual, machine, svm, junction, point, mount, unmount, mount or unmount existing volumes in the nas namespace 
summary: Storage Virtual Machine （ SVM ）ボリュームに格納されたデータへの NAS クライアントアクセスを設定するには、ボリュームが NAS ネームスペースにマウントされている必要があります。現在マウントされていないボリュームは、ジャンクションポイントにマウントできます。ボリュームはアンマウントすることもできます。 
---
= NAS ネームスペース内の既存のボリュームをマウントまたはアンマウントします
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Storage Virtual Machine （ SVM ）ボリュームに格納されたデータへの NAS クライアントアクセスを設定するには、ボリュームが NAS ネームスペースにマウントされている必要があります。現在マウントされていないボリュームは、ジャンクションポイントにマウントできます。ボリュームはアンマウントすることもできます。

.このタスクについて
ボリュームをアンマウントしてオフラインにすると、アンマウントしたボリュームのネームスペース内に含まれたジャンクションポイントのあるボリューム内のデータも含め、ジャンクションポイント内のすべてのデータに NAS クライアントからアクセスできなくなります。

[NOTE]
====
NAS クライアントからのボリュームへのアクセスを中止するには、ボリュームを単純にアンマウントするだけでは不十分です。ボリュームをオフラインにするか、クライアント側のファイルハンドルのキャッシュが無効になるように他の手順を実行する必要があります。詳細については、次の技術情報アーティクル「https://kb.netapp.com/Advice_and_Troubleshooting/Data_Storage_Software/ONTAP_OS/NFSv3_clients_still_have_access_to_a_volume_after_being_removed_from_the_namespace_in_ONTAP[NFSv3 clients still have access to a volume after being removed from the namespace in ONTAP」を参照してください。

====
ボリュームをアンマウントしてオフラインにしても、そのボリューム内のデータは失われません。また、既存のボリュームエクスポートポリシーおよびボリュームまたはディレクトリ上に作成された SMB 共有、およびアンマウントされたボリューム内のジャンクションポイントは保持されます。アンマウントしたボリュームを再マウントすれば、 NAS クライアントは既存のエクスポートポリシーと SMB 共有を使用してボリューム内のデータにアクセスできるようになります。

.手順
. 必要な操作を実行します。
+
|===
| 状況 | 入力するコマンド 


 a| 
ボリュームをマウント
 a| 
`volume mount -vserver _svm_name_ -volume _volume_name_ -junction-path _junction_path_`



 a| 
ボリュームをアンマウントします
 a| 
`volume unmount -vserver _svm_name_ -volume _volume_name_ volume offline -vserver _svm_name_ -volume _volume_name_`

|===
. ボリュームが目的のマウント状態になっていることを確認します。 `volume show -vserver _vserver_name_ -volume _volume_name_ -fields state,junction-path,junction-active`


.例
次の例は、SVM vs1にある「sales」という名前のボリュームをジャンクションポイントにマウントします `/sales`：

[listing]
----
cluster1::> volume mount -vserver vs1 -volume sales -junction-path /sales

cluster1::> volume show -vserver vs1 state,junction-path,junction-active

vserver   volume     state     junction-path   junction-active
--------- ---------- -------- --------------- ----------------
vs1       data       online    /data           true
vs1       home4      online    /eng/home       true
vs1       sales      online    /sales          true
----
次の例は、 SVM vs1 にある「 `d ATA` 」という名前のボリュームをアンマウントしてオフラインにします。

[listing]
----
cluster1::> volume unmount -vserver vs1 -volume data
cluster1::> volume offline -vserver vs1 -volume data

cluster1::> volume show -vserver vs1 -fields state,junction-path,junction-active

vserver   volume     state     junction-path   junction-active
--------- ---------- --------- --------------- ---------------
vs1       data       offline   -               -
vs1       home4      online    /eng/home       true
vs1       sales      online    /sales          true
----