---
permalink: smb-admin/multi-byte-file-directory-qtree-names-concept.html 
sidebar: sidebar 
keywords: ontap, suppot, byte, utf, encode, name, enable, creation, display, file, directory, tree, unicode, supplement, character, multilingual, plane, bmp, release, display, environment, how ontap handles multi-byte file, qtree 
summary: ONTAP 9.5以降では、4バイトのUTF-8エンコード形式の名前がサポートされるようになり、Basic Multilingual Plane（BMP;基本多言語面）以外のUnicode補助文字を含むファイル、ディレクトリ、ツリーの名前を作成および表示できるようになりました。以前のリリースでは、これらの補助文字はマルチプロトコル環境では正しく表示されませんでした。 
---
= ONTAPのSMBマルチバイト ファイル名、ディレクトリ名、qtree名について学習します。
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
ONTAP 9.5以降では、4バイトのUTF-8エンコード形式の名前がサポートされるようになり、Basic Multilingual Plane（BMP;基本多言語面）以外のUnicode補助文字を含むファイル、ディレクトリ、ツリーの名前を作成および表示できるようになりました。以前のリリースでは、これらの補助文字はマルチプロトコル環境では正しく表示されませんでした。

4バイトのUTF-8でエンコードされた名前のサポートを有効にするために、 `vserver`および `volume`コマンドファミリで新しい_utf8mb4_言語コードが使用可能です。

次のいずれかの方法で新しいボリュームを作成する必要があります。

* ボリューム `-language`オプションを明示的に設定する： `volume create -language utf8mb4 {…}`
* オプションで作成または変更されたSVMからボリューム `-language`オプションを継承する場合： `vserver [create|modify] -language utf8mb4 {…}``volume create {…}`
* ONTAP 9.6以前では、既存のボリュームをutf8mb4をサポートするように変更することはできません。utf8mb4対応の新しいボリュームを作成し、クライアントベースのコピー ツールを使用してデータを移行する必要があります。
+
SVM を utf8mb4 サポート用に更新できますが、既存のボリュームでは元の言語コードが保持されます。

+
ONTAP 9.7P1以降をご利用の場合は、サポートリクエストを送信することで、既存のボリュームをutf8mb4に変更できます。詳細については、link:https://kb.netapp.com/onprem/ontap/da/NAS/Can_the_volume_language_be_changed_after_creation_in_ONTAP["ONTAPでボリューム言語を作成後に変更できますか？"^]をご覧ください。



* ONTAP 9.8以降では、 `[-language <Language code>]`パラメータを使用してボリュームの言語を*.UTF-8からutf8mb4に変更できます。ボリュームの言語を変更するには、link:http://mysupport.netapp.com/["NetAppサポート"^]にお問い合わせください。



NOTE: 現在のところ、4バイトのUTF-8文字を含むLUN名はサポートされていません。

* 一般に、Unicode文字データは、Windowsファイルシステム アプリケーションでは16-bit Unicode Transformation Format（UTF-16）、NFSファイルシステムでは8-bit Unicode Transformation Format（UTF-8）を使用して表現されます。
+
ONTAP 9.5よりも前のリリースでは、Windowsクライアントで作成されたUTF-16の補助文字を含む名前は、他のWindowsクライアントには正しく表示されましたが、NFSクライアントではUTF-8に正しく変換されませんでした。同様に、NFSクライアントで作成されたUTF-8の補助文字を含む名前は、WindowsクライアントでUTF-16に正しく変換されませんでした。

* ONTAP 9.4以前を実行するシステムで補助文字を（有効か無効かにかかわらず）含むファイル名を作成すると、ONTAPはそのファイル名を拒否し、ファイル名が無効であることを示すエラーを返します。
+
この問題を回避するには、ファイル名にBMP文字のみを使用して補助文字は使用しないようにするか、ONTAPを9.5以降にアップグレードしてください。



ONTAP 9以降では、Unicode文字をqtree名に使用できます。

*  `volume qtree`コマンド ファミリまたは System Manager のいずれかを使用して、qtree 名を設定または変更できます。
* 日本語や中国語などのUnicode形式のマルチバイト文字をqtree名に含めることができます。
* ONTAP 9.5よりも前のリリースでは、BMP文字（つまり3バイトで表現可能な文字）のみがサポートされます。
+

NOTE: ONTAP 9.5より前のリリースでは、qtreeの親ボリュームのジャンクションパスに、Unicode文字を使用したqtree名とディレクトリ名を含めることができます。 `volume show`コマンドは、親ボリュームの言語設定がUTF-8の場合、これらの名前を正しく表示します。ただし、親ボリュームの言語がUTF-8言語設定のいずれにも該当しない場合、ジャンクションパスの一部は数値のNFS代替名で表示されます。

* 9.5以降のリリースでは、qtreeがutf8mb4に対応したボリュームに含まれていれば、qtree名で4バイト文字がサポートされます。

