---
permalink: smb-admin/name-service-switch-config-concept.html 
sidebar: sidebar 
keywords: ontap, store, name, service, configuration, information, table, equivalent, unix, system, appropriate, environment, how ontap name service switch configuration works 
summary: ONTAP では、 UNIX システムの /etc/nsswitch.conf ファイルに相当するテーブルにネームサービス設定情報が格納されます。このテーブルを環境に合わせて適切に設定できるように、このテーブルの機能とONTAPでの使用方法を理解しておく必要があります。 
---
= ONTAPネームサービススイッチ設定の仕組み
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
ONTAPでは、UNIXシステムのファイルに相当するテーブルにネームサービス設定情報が格納されます `/etc/nsswitch.conf`。このテーブルを環境に合わせて適切に設定できるように、このテーブルの機能とONTAPでの使用方法を理解しておく必要があります。

ONTAPネームサービススイッチテーブルは、ONTAPが特定の種類のネームサービス情報を取得する際にどのネームサービスソースをどの順序で参照するかを決定します。ネームサービススイッチテーブルは、SVMごとにONTAPで管理されます。



== データベースタイプ

このテーブルには、次のデータベースタイプごとにネームサービスのリストが格納されます。

|===
| データベースタイプ | ネームサービスソースの用途 | 有効なソース 


 a| 
ホスト
 a| 
ホスト名からIPアドレスへの変換
 a| 
フアイル、DNS



 a| 
グループ
 a| 
ユーザグループ情報の検索
 a| 
フアイル、NIS、LDAP



 a| 
パスワード
 a| 
ユーザ情報の検索
 a| 
フアイル、NIS、LDAP



 a| 
ネットグループ
 a| 
ネットグループ情報の検索
 a| 
フアイル、NIS、LDAP



 a| 
namemap
 a| 
ユーザ名のマッピング
 a| 
フアイル、LDAP

|===


== ソースタイプ

ソースによって、適切な情報の取得に使用するネームサービスソースが指定されます。

|===
| ソースタイプ | 情報の検索先 | 使用するコマンド 


 a| 
ファイル
 a| 
ローカルソースファイル
 a| 
`vserver services name-service unix-user` `vserver services name-service unix-group`

`vserver services name-service netgroup`

`vserver services name-service dns hosts`



 a| 
NIS
 a| 
SVMのNISドメイン設定で指定された外部のNISサーバ
 a| 
`vserver services name-service nis-domain`



 a| 
LDAP
 a| 
SVMのLDAPクライアント設定で指定された外部のLDAPサーバ
 a| 
`vserver services name-service ldap`



 a| 
DNS
 a| 
SVMのDNS設定で指定された外部のDNSサーバ
 a| 
`vserver services name-service dns`

|===
データアクセスとSVM管理者の両方の認証にNISまたはLDAPを使用する場合でも、NISまたはLDAP認証が失敗した場合に備えて、ローカルユーザをフォールバックとして含めて設定しておく必要があります `files`。



== 外部ソースへのアクセスに使用するプロトコル

ONTAPでは、外部ソースのサーバにアクセスするために、次のプロトコルを使用します。

|===
| 外部のネームサービスソース | アクセスに使用するプロトコル 


| NIS | UDP 


| DNS | UDP 


| LDAP | TCP 
|===


== 例

次の例は、SVMのネームサービススイッチ設定を表示します `svm_1`。

[listing]
----
cluster1::*> vserver services name-service ns-switch show -vserver svm_1
                               Source
Vserver         Database       Order
--------------- ------------   ---------
svm_1           hosts          files,
                               dns
svm_1           group          files
svm_1           passwd         files
svm_1           netgroup       nis,
                               files
----
ユーザーまたはグループ情報を検索するために、ONTAPはローカルソースファイルのみを参照します。結果が返されない場合、検索は失敗します。

ネットグループ情報を検索するために、ONTAPは最初に外部NISサーバを参照します。クエリから結果が返されない場合は、次にローカルネットグループファイルがチェックされます。

SVM svm_1のテーブルには、ネームマッピング用のネームサービスエントリはありません。したがって、ONTAPはデフォルトでローカルソースファイルのみを参照します。
