---
permalink: smb-admin/network-protocol-support-requirements-concept.html 
sidebar: sidebar 
keywords: network, protocol, requirement, implement, ontap, branchcache, support, network protocol support requirement 
summary: ONTAP BranchCache を実装するときは、ネットワークプロトコルの要件を考慮する必要があります。 
---
= ネットワークプロトコルのサポート要件
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
ONTAP BranchCache を実装するときは、ネットワークプロトコルの要件を考慮する必要があります。

ONTAP BranchCache 機能は、 SMB 2.1 以降を使用して、 IPv4 および IPv6 のネットワークに実装できます。

BranchCache の実装に含まれるすべての CIFS サーバとブランチオフィスのマシンで、 SMB 2.1 以降のプロトコルを有効にする必要があります。SMB 2.1 では、プロトコルの機能拡張により、クライアントを BranchCache 環境に含めることができます。SMB プロトコルとして BranchCache をサポートするために必要な最小バージョンを指定してください。SMB 2.1 は、 BranchCache バージョン 1 をサポートします。

BranchCache バージョン 2 を使用する場合は、サポートする SMB の最小バージョンは SMB 3.0 になります。BranchCache 2 の実装に含まれるすべての CIFS サーバとブランチオフィスのマシンで、 SMB 3.0 以降を有効にする必要があります。

リモートオフィスで SMB2.1 のみサポートするクライアント、 SMB3.0 をサポートするクライアントが混在する場合は、 BranchCache 1 と BranchCache 2 の両方のキャッシングをサポートする CIFS サーバに BranchCache 構成を実装することができます。

[NOTE]
====
Microsoft BranchCache 機能ではファイルアクセスプロトコルとして HTTP / HTTPS と SMB プロトコルの両方がサポートされますが、 ONTAP BranchCache でサポートされるのは SMB のみです。

====