---
permalink: smb-admin/offline-files-allow-caching-concept.html 
sidebar: sidebar 
keywords: ontap, support, microsoft, offline, file, feature, client-side, caching, cache, file, local, host, offline, disconnect, network, use offline files to allow caching of files for offline use 
summary: ONTAP では、 Microsoft のオフラインファイル機能、またはクライアント側キャッシュをサポートしています。これにより、オフラインで使用するファイルをローカルホストにキャッシュできます。オフラインファイル機能を使用すると、ネットワークから切断されているファイルでも作業を継続できます。 
---
= オフラインファイルを使用して、オフラインで使用するためのファイルのキャッシュの概要を確認します
:icons: font
:imagesdir: ../media/


[role="lead"]
ONTAP では、 Microsoft のオフラインファイル機能（ _ クライアント側キャッシュ _ ）をサポートしています。これにより、オフラインで使用するファイルをローカルホストにキャッシュできます。オフラインファイル機能を使用すると、ネットワークから切断されているファイルでも作業を継続できます。

Windows のユーザドキュメントやプログラムを共有に自動的にキャッシュするかどうか、またはキャッシュするファイルを手動で選択するかどうかを指定できます。新しい共有では、手動キャッシュがデフォルトで有効になります。オフラインで利用可能となったファイルは、 Windows クライアントのローカルディスクと同期されます。同期は、特定のストレージシステム共有へのネットワーク接続がリストアされたときに実行されます。

オフラインのファイルおよびフォルダに対するアクセス権限は CIFS サーバに保存されているファイルおよびフォルダと同じであるため、オフラインのファイルおよびフォルダに対して処理を実行するには、 CIFS サーバに保存されているファイルおよびフォルダに対する十分な権限が必要です。

ユーザとネットワーク上の他のユーザが同じファイルに変更を加えた場合、ユーザはネットワークにローカルバージョンのファイルを保存するか、別のバージョンを保持するか、または両方を保存できます。両方のバージョンを残す場合は、ローカルユーザが変更した新しいファイルがローカルに保存され、キャッシュされたファイルは CIFS サーバに保存されたバージョンの変更が反映されて上書きされます。

オフラインファイルは、共有ごとに共有の設定を行うことができます。共有を作成または変更するときに、次の 4 つのオフラインフォルダ設定のいずれかを選択できます。

* キャッシュなし
+
共有のクライアント側キャッシュを無効にします。クライアントのローカルにファイルやフォルダが自動的にキャッシュされず、ユーザがファイルやフォルダをローカルにキャッシュすることもできません。

* 手動キャッシュ
+
共有にキャッシュするファイルを手動で選択できるようにします。これがデフォルト設定です。デフォルトでは、ファイルやフォルダはローカルクライアントにキャッシュされません。オフラインで使用するためにローカルにキャッシュするファイルやフォルダをユーザが選択できます。

* ドキュメントの自動キャッシュ
+
ユーザのドキュメントが共有に自動的にキャッシュされるようにします。ローカルにキャッシュされるのは、アクセスしたファイルとフォルダだけです。

* プログラムの自動キャッシュ
+
プログラムとユーザのドキュメントが共有に自動的にキャッシュされるようにします。ローカルにキャッシュされるのは、アクセスしたファイル、フォルダ、およびプログラムだけです。また、この設定を有効にすると、ネットワークに接続されている場合でも、クライアントはローカルにキャッシュされた実行ファイルを実行できます。



Windows サーバおよびクライアントでのオフラインファイルの設定の詳細については、 Microsoft TechNet ライブラリを参照してください。

* 関連情報 *

xref:roaming-profiles-store-user-profiles-concept.adoc[移動プロファイルを使用した SVM に関連付けられた CIFS サーバへのユーザプロファイルの一元的な格納]

xref:folder-redirection-store-data-concept.adoc[フォルダリダイレクトを使用した CIFS サーバへのデータの格納]

xref:branchcache-cache-share-content-branch-office-concept.adoc[BranchCache を使用したブランチオフィスでの SMB 共有のコンテンツのキャッシュ]

http://technet.microsoft.com/en-us/library/["Microsoft TechNet ライブラリ： technet.microsoft.com/en-us/library/"]
