---
permalink: smb-admin/offline-files-allow-caching-concept.html 
sidebar: sidebar 
keywords: ontap, support, microsoft, offline, file, feature, client-side, caching, cache, file, local, host, offline, disconnect, network, use offline files to allow caching of files for offline use 
summary: ONTAPは、Microsoftオフラインファイル機能（クライアント側キャッシュ）をサポートしています。この機能により、ファイルをローカルホストにキャッシュし、オフラインで使用することができます。ユーザはオフラインファイル機能を使用することで、ネットワークから切断された状態でもファイルの操作を継続できます。 
---
= オフラインファイルを使用して、オフラインで使用するためにONTAP SMBファイルをキャッシュできるようにする方法について説明します。
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
ONTAPは、Microsoftオフラインファイル機能（_クライアント側キャッシュ_）をサポートしており、ファイルをローカルホストにキャッシュしてオフラインで使用できます。ユーザーはオフラインファイル機能を使用することで、ネットワークから切断された場合でもファイルの操作を継続できます。

Windowsのユーザ ドキュメントやプログラムを共有に自動でキャッシュするのか、キャッシュするファイルを手動で選択するのかを指定することができます。新規の共有では、手動キャッシュがデフォルトで有効になります。オフラインで利用可能となったファイルは、Windowsクライアントのローカル ディスクと同期されます。同期は、所定のストレージ システム共有へのネットワーク接続が復元した時点で実行されます。

オフラインのファイルおよびフォルダに対するアクセス権限はCIFSサーバに保存されているファイルおよびフォルダと同じになるため、オフラインのファイルおよびフォルダに対して処理を行うときは、CIFSサーバに保存されているファイルおよびフォルダに対する十分な権限が必要になります。

ネットワーク上の他のユーザが同じファイルに対して変更を行った場合、ネットワークにローカル バージョンのファイルを保存するか、別のバージョンを保存するか、または両方を保存するかを選択できます。両方のバージョンを残す場合は、ローカル ユーザが変更した新しいファイルがローカルに保存され、キャッシュされたファイルはCIFSサーバに保存されたバージョンの変更が反映されて上書きされます。

オフライン ファイルについては、共有ごとに共有の設定を行えます。共有を作成または変更するときに、次の4つのオフライン フォルダ設定の中からいずれかを選択できます。

* キャッシュしない
+
共有のクライアント側キャッシュを無効にします。クライアントのローカルにファイルやフォルダが自動的にキャッシュされず、ユーザがファイルやフォルダをローカルにキャッシュすることもできません。

* 手動キャッシュ
+
共有にキャッシュするファイルを手動で選択できるようにします。これがデフォルト設定です。デフォルトでは、ファイルやフォルダはローカル クライアントにキャッシュされません。オフラインで使用するためにローカルにキャッシュするファイルやフォルダをユーザが選択できます。

* ドキュメントの自動キャッシュ
+
ユーザのドキュメントが共有に自動的にキャッシュされるようにします。ローカルにキャッシュされるのは、アクセスしたファイルとフォルダだけです。

* プログラムの自動キャッシュ
+
プログラムおよびユーザのドキュメントが共有に自動的にキャッシュされるようにします。ローカルにキャッシュされるのは、アクセスしたファイル、フォルダ、およびプログラムだけです。また、この設定を選択した場合、クライアントがネットワークに接続されていても、ローカルにキャッシュされた実行ファイルが実行されます。



Windowsサーバおよびクライアントでのオフライン ファイルの設定の詳細については、Microsoft TechNetライブラリを参照してください。

.関連情報
* xref:roaming-profiles-store-user-profiles-concept.adoc[移動プロファイルを使用したSVMに関連付けられたCIFSサーバへのユーザ プロファイルの一元的な格納]
* xref:folder-redirection-store-data-concept.adoc[フォルダーリダイレクトを使用してサーバーにデータを保存する方法について説明します]
* xref:branchcache-cache-share-content-branch-office-concept.adoc[BranchCacheを使用してブランチオフィスで共有コンテンツをキャッシュする方法について学習します]
* http://technet.microsoft.com/en-us/library/["Microsoft TechNetライブラリ：technet.microsoft.com/ja-jp/library/"]

