---
permalink: smb-admin/previous-versions-view-manage-snapshot-data-task.html 
sidebar: sidebar 
keywords: windows, client, machine, previous, version, tab, properties, restore, data, store, snapshot, copies, copy, storage, virtual, machine, svm, administrator, use the previous versions tab to view and manage snapshot copy data 
summary: Windowsクライアントマシンのユーザーは、Windowsの［プロパティ］ウィンドウの［以前のバージョン］タブを使用して、Storage Virtual Machine（SVM）管理者の介入なしにSnapshotに保存されているデータを復元できます。 
---
= Windows の [以前のバージョン] タブを使用して ONTAP SMB Snapshot データを表示および管理します。
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Windowsクライアントマシンのユーザーは、Windowsの［プロパティ］ウィンドウの［以前のバージョン］タブを使用して、Storage Virtual Machine（SVM）管理者の介入なしにSnapshotに保存されているデータを復元できます。

.タスク概要
管理者が共有を含むボリューム上でSnapshotを有効にし、共有がSnapshotを表示するように設定している場合にのみ、[以前のバージョン] タブを使用して、SVM に保存されているデータのSnapshot内のデータを表示および管理できます。

.手順
. エクスプローラで、CIFSサーバに格納されたデータのマッピングされたドライブの内容を表示します。
. Snapshotを表示または管理するマップされたネットワークドライブ内のファイルまたはフォルダーを右クリックします。
. *プロパティ*をクリックします。
+
選択したファイルまたはフォルダのプロパティが表示されます。

. *Previous Versions*タブをクリックします。
+
選択したファイルまたはフォルダの利用可能なスナップショットのリストが「フォルダバージョン：」ボックスに表示されます。リストされたスナップショットは、スナップショット名のプレフィックスと作成タイムスタンプで識別されます。

. *フォルダーのバージョン：*ボックスで、管理するファイルまたはフォルダーのコピーを右クリックします。
. 適切な処理を実行します。
+
|===
| 状況 | 操作 


 a| 
そのSnapshotからデータを表示する
 a| 
*Open*をクリックします。



 a| 
そのSnapshotからデータのコピーを作成する
 a| 
*Copy*をクリックします。

|===
+
Snapshot内のデータは読み取り専用です。「以前のバージョン」タブに表示されているファイルやフォルダに変更を加える場合は、変更したいファイルやフォルダのコピーを書き込み可能な場所に保存し、そのコピーに対して変更を加える必要があります。

. Snapshotデータの管理が完了したら、*OK*をクリックして*プロパティ*ダイアログボックスを閉じます。
+
[以前のバージョン]タブを使用してSnapshotデータを表示および管理する方法の詳細については、Microsoft TechNetライブラリを参照してください。



.関連情報
http://technet.microsoft.com/en-us/library/["Microsoft TechNetライブラリ：technet.microsoft.com/ja-jp/library/"]
