---
permalink: smb-admin/previous-versions-view-manage-snapshot-data-task.html 
sidebar: sidebar 
keywords: windows, client, machine, previous, version, tab, properties, restore, data, store, snapshot, copies, copy, storage, virtual, machine, svm, administrator, use the previous versions tab to view and manage snapshot copy data 
summary: 'Windowsクライアントマシンでは、Windowsの[プロパティ]ウィンドウの[以前のバージョン]タブを使用して、Storage Virtual Machine（SVM）管理者の手を借りなくても、Snapshotに格納されたデータをユーザがリストアできます。' 
---
= [以前のバージョン]タブを使用してSnapshotデータを表示および管理
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Windowsクライアントマシンでは、Windowsの[プロパティ]ウィンドウの[以前のバージョン]タブを使用して、Storage Virtual Machine（SVM）管理者の手を借りなくても、Snapshotに格納されたデータをユーザがリストアできます。

.タスクの内容
SVMに格納されたデータのSnapshotのデータを[以前のバージョン]タブで表示および管理できるのは、管理者が共有を含むボリュームでSnapshotを有効にし、Snapshotを表示するように共有を設定している場合のみです。

.手順
. エクスプローラで、CIFSサーバに格納されているデータのマッピングされたドライブの内容を表示します。
. スナップショットを表示または管理するマッピングされたネットワークドライブ内のファイルまたはフォルダを右クリックします。
. * プロパティ * をクリックします。
+
選択したファイルまたはフォルダのプロパティが表示されます。

. [ 以前のバージョン *] タブをクリックします。
+
選択したファイルまたはフォルダの使用可能なスナップショットのリストが[フォルダバージョン：（Folder Versions：）]ボックスに表示されます。表示されたSnapshotは、Snapshot名のプレフィックスと作成時のタイムスタンプで識別されます。

. [ * フォルダーバージョン： * ] ボックスで、管理するファイルまたはフォルダーのコピーを右クリックします。
. 適切な操作を実行します。
+
|===
| 状況 | 操作 


 a| 
スナップショットのデータを表示する
 a| 
* 開く * をクリックします。



 a| 
そのSnapshotからデータのコピーを作成する
 a| 
[* コピー（ Copy ） ] をクリックします

|===
+
Snapshotのデータは読み取り専用です。[以前のバージョン]タブに表示されているファイルやフォルダに変更を加える場合は、変更するファイルやフォルダのコピーを書き込み可能な場所に保存し、コピーに変更を加える必要があります。

. スナップショットデータの管理が終了したら、* OK *をクリックして*プロパティ*ダイアログボックスを閉じます。
+
[以前のバージョン]タブを使用したSnapshotデータの表示と管理の詳細については、Microsoft TechNetライブラリを参照してください。



.関連情報
http://technet.microsoft.com/en-us/library/["Microsoft TechNetライブラリ：technet.microsoft.com/en-us/library/"]
