---
permalink: smb-admin/reasons-creating-local-users-groups-concept.html 
sidebar: sidebar 
keywords: creating, create, local, user, group, storage, virtual, machine, svm, access, smb, domain, controllers, dc, assign, privilege, workgroup, server, reasons for creating local users and local groups 
summary: Storage Virtual Machine （ SVM ）でローカルユーザやローカルグループを作成する理由はいくつかあります。たとえば、ドメインコントローラ（ DC ）を使用できないときでも、ローカルユーザアカウントを使用して SMB サーバにアクセスできます。ローカルグループを使用して権限を割り当てる場合や、 SMB サーバがワークグループにある場合もあります。 
---
= ローカルユーザおよびローカルグループを作成する理由
:icons: font
:imagesdir: ../media/


[role="lead"]
Storage Virtual Machine （ SVM ）でローカルユーザやローカルグループを作成する理由はいくつかあります。たとえば、ドメインコントローラ（ DC ）を使用できないときでも、ローカルユーザアカウントを使用して SMB サーバにアクセスできます。ローカルグループを使用して権限を割り当てる場合や、 SMB サーバがワークグループにある場合もあります。

ローカルユーザアカウントを作成する理由には、次のようなものがあります。

* SMB サーバがワークグループにあり、ドメインユーザを使用できない。
+
ワークグループ設定にはローカルユーザが必要です。

* ドメインコントローラを使用できないときに、 SMB サーバで認証してログインできるようにする。
+
ドメインコントローラがダウンしている場合や、ネットワークの問題によって SMB サーバからドメインコントローラに接続できない場合でも、ローカルユーザであれば、 NTLM 認証を使用して SMB サーバに認証できます。

* ローカル・ユーザに _ ユーザ権限の管理 _ 権限を割り当てる
+
_User Rights Management_ は、ユーザとグループに付与する SVM の権限を SMB サーバ管理者が制御できる機能です。ユーザに権限を割り当てるには、ユーザのアカウントにそれらの権限を割り当てるか、ユーザをそれらの権限が割り当てられたローカルグループのメンバーにします。



ローカルグループを作成する理由には、次のようなものがあります。

* SMB サーバがワークグループにあり、ドメイングループを使用できない。
+
ワークグループにローカルグループを設定する必要はありませんが、設定するとローカルワークグループユーザのアクセス権限を管理するのに役立ちます。

* 共有やファイルアクセスの制御にローカルグループを使用して、ファイルやフォルダのリソースへのアクセスを制御する。
* カスタマイズした _ ユーザ権限の管理 _ 権限を持つローカルグループを作成する。
+
権限があらかじめ定義された組み込みのユーザグループがいくつか用意されています。カスタマイズした一連の権限を割り当てるには、ローカルグループを作成し、そのグループに必要な権限を割り当てます。その後、ローカルグループにローカルユーザ、ドメインユーザ、およびドメイングループを追加します。



* 関連情報 *

xref:local-user-authentication-concept.adoc[ローカルユーザ認証の仕組み]

xref:local-privileges-concept.adoc[ローカル権限とは]
