---
permalink: smb-admin/reasons-creating-local-users-groups-concept.html 
sidebar: sidebar 
keywords: creating, create, local, user, group, storage, virtual, machine, svm, access, smb, domain, controllers, dc, assign, privilege, workgroup, server, reasons for creating local users and local groups 
summary: Storage Virtual Machine（SVM）でローカルユーザやローカルグループを作成する理由はいくつかあります。たとえば、ドメインコントローラ（DC）を使用できない場合でも、ローカルユーザアカウントを使用してSMBサーバにアクセスできます。また、ローカルグループを使用してPrivilegesを割り当てたり、SMBサーバがワークグループに含まれている場合もあります。 
---
= ローカル ONTAP SMB ユーザーとローカル グループを作成する理由
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Storage Virtual Machine（SVM）でローカルユーザやローカルグループを作成する理由はいくつかあります。たとえば、ドメインコントローラ（DC）を使用できない場合でも、ローカルユーザアカウントを使用してSMBサーバにアクセスできます。また、ローカルグループを使用してPrivilegesを割り当てたり、SMBサーバがワークグループに含まれている場合もあります。

ローカルユーザアカウントを作成する理由は次のとおりです。

* SMBサーバがワークグループに含まれており、ドメインユーザを使用できません。
+
ワークグループを設定するにはローカルユーザが必要です。

* ドメインコントローラを使用できない場合に、SMBサーバで認証してログインできるようにする。
+
ドメインコントローラがダウンしている場合や、ネットワークの問題によってSMBサーバからドメインコントローラに接続できない場合は、ローカルユーザはNTLM認証を使用してSMBサーバに認証できます。

* ローカル・ユーザに _ ユーザ権限の管理 _ 権限を割り当てる
+
_User Rights Management_ は、ユーザとグループに付与する SVM の権限を SMB サーバ管理者が制御できる機能です。ユーザにPrivilegesを割り当てるには、ユーザのアカウントにPrivilegesを割り当てるか、ユーザをそのPrivilegesを含むローカルグループのメンバーにします。



ローカルグループを作成する理由は次のとおりです。

* SMBサーバがワークグループに含まれており、ドメイングループを使用できません。
+
ローカルグループはワークグループ構成では必要ありませんが、ローカルワークグループユーザのアクセスPrivilegesの管理に役立ちます。

* 共有とファイルアクセスの制御にローカルグループを使用して、ファイルおよびフォルダリソースへのアクセスを制御する。
* カスタマイズした _ ユーザ権限の管理 _ 権限を持つローカルグループを作成する。
+
一部の組み込みユーザグループには、Privilegesが事前に定義されています。カスタマイズしたPrivilegesセットを割り当てるには、ローカルグループを作成し、そのグループに必要なPrivilegesを割り当てます。その後、ローカルユーザ、ドメインユーザ、およびドメイングループをそのローカルグループに追加できます。



.関連情報
xref:local-user-authentication-concept.adoc[ローカルユーザ認証の仕組み]

xref:list-supported-privileges-reference.html[サポートされるPrivilegesのリスト]
