---
permalink: smb-admin/recover-files-folders-previous-versions-concept.html 
sidebar: sidebar 
keywords: ability, microsoft, previous, version, applicable, file, system, support, snapshot, copies, copy, form, enable, technolofy, integral, ontap, recover, file, recover files and folders using previous versions 
summary: 'Microsoftの以前のバージョンを使用する機能は"何らかの形でスナップショットをサポートし"スナップショットが有効になっているファイル・システムに適用されますSnapshot テクノロジは ONTAP に不可欠なテクノロジの 1 つです。ユーザーは、Microsoftの以前のバージョン機能を使用して、Windowsクライアントからスナップショットからファイルやフォルダをリカバリできます。' 
---
= 以前のバージョンを使用して ONTAP SMB ファイルとフォルダをリカバリする方法について説明します。
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Microsoftの以前のバージョンを使用する機能は'何らかの形でスナップショットをサポートし'スナップショットが有効になっているファイル・システムに適用されますSnapshot テクノロジは ONTAP に不可欠なテクノロジの 1 つです。ユーザーは、Microsoftの以前のバージョン機能を使用して、Windowsクライアントからスナップショットからファイルやフォルダをリカバリできます。

以前のバージョン機能を使用すると、ストレージ管理者の介入なしに、ユーザがスナップショットを参照したり、スナップショットからデータをリストアしたりすることができます。以前のバージョン機能は設定できません。常に有効になります。ストレージ管理者が共有でSnapshotを使用できるようにしている場合、ユーザは[以前のバージョン]機能を使用して次のタスクを実行できます。

* 誤って削除したファイルをリカバリする。
* 誤って上書きしたファイルをリカバリする。
* 作業中にファイルのバージョンを比較します。


Snapshotに格納されるデータは読み取り専用です。ファイルに変更を加えるには、ファイルのコピーを別の場所に保存する必要があります。スナップショットは定期的に削除されるため、ユーザーが以前のバージョンのファイルを無期限に保持するには、以前のバージョンに含まれていたファイルのコピーを作成する必要があります。
