---
permalink: smb-admin/remove-privileges-local-domain-users-groups-task.html 
sidebar: sidebar 
keywords: manage, user, right, local, domain, group, removing, remove, privilege, enhance, security, allow, customize, maximum, remove privileges from local or domain users or groups 
summary: ローカルまたはドメインのユーザやグループのユーザ権限を管理するには、権限を削除します。これにより、ユーザとグループに付与される最大権限をカスタマイズして、セキュリティを強化できます。 
---
= ローカルまたはドメインのユーザまたはグループから権限を削除します
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
ローカルまたはドメインのユーザやグループのユーザ権限を管理するには、権限を削除します。これにより、ユーザとグループに付与される最大権限をカスタマイズして、セキュリティを強化できます。

.作業を開始する前に
権限を削除する対象となるローカルまたはドメインのユーザまたはグループがすでに存在している必要があります。

.このタスクについて
ローカルまたはドメインのユーザやグループの権限を削除するときは、次の点に注意してください。

* 1 つ以上の権限を削除できます。
* ドメインのユーザまたはグループの権限を削除する場合、 ONTAP でそれらのユーザやグループを検証するために、ドメインコントローラに接続することがあります。
+
ONTAP からドメインコントローラに接続できない場合、コマンドが失敗することがあります。



.手順
. ローカルまたはドメインのユーザまたはグループから権限を削除します。 `+vserver cifs users-and-groups privilege remove-privilege -vserver _vserver_name_ -user-or-group-name _name_ -privileges _privilege_[,...]+`
. 指定したユーザまたはグループから指定した権限が削除されていることを確認します。 `vserver cifs users-and-groups privilege show -vserver _vserver_name_ ‑user-or-group-name _name_`


.例
次の例は、 Storage Virtual Machine （ SVM 、旧 Vserver ） vs1 上のユーザ「 CIFS_SERVER\suueo 」から「 `s eTcbPrivilege 」および「 `s eTakeOwnershipPrivilege 」権限を削除します。

[listing]
----
cluster1::> vserver cifs users-and-groups privilege show -vserver vs1
Vserver   User or Group Name    Privileges
--------- --------------------- ---------------
vs1       CIFS_SERVER\sue       SeTcbPrivilege
                                SeTakeOwnershipPrivilege

cluster1::> vserver cifs users-and-groups privilege remove-privilege -vserver vs1 -user-or-group-name CIFS_SERVER\sue -privileges SeTcbPrivilege,SeTakeOwnershipPrivilege

cluster1::> vserver cifs users-and-groups privilege show -vserver vs1
Vserver   User or Group Name    Privileges
--------- --------------------- -------------------
vs1       CIFS_SERVER\sue       -
----