---
permalink: smb-admin/remove-netbios-aliases-from-list-task.html 
sidebar: sidebar 
keywords: netbios, alias, cifs, server, remove, list, remove netbios aliases from the netbios alias list 
summary: CIFS サーバで特定の NetBIOS エイリアスが不要な場合、その NetBIOS エイリアスをリストから削除できます。リストからすべての NetBIOS エイリアスを削除することもできます。 
---
= NetBIOS エイリアスリストから NetBIOS エイリアスを削除します
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
CIFS サーバで特定の NetBIOS エイリアスが不要な場合、その NetBIOS エイリアスをリストから削除できます。リストからすべての NetBIOS エイリアスを削除することもできます。

複数の NetBIOS エイリアスを削除するには、カンマで区切って指定します。CIFS サーバ上のすべての NetBIOS エイリアスを削除するには '-netbios-aliases パラメータの値に -' を指定します

.手順
. 次のいずれかを実行します。
+
|===
| 削除する項目 | 入力するコマンド 


 a| 
リスト内の特定の NetBIOS エイリアス
 a| 
+vserver cifs remove-netbios-aliases -vserver _vserver_name -netbios-aliases -netbios-aliases _ NetBIOS_alias _ 、… +`



 a| 
リスト内のすべての NetBIOS エイリアス
 a| 
vserver cifs remove-netbios-aliases -vserver _vserver_name -netbios-aliases -`

|===
+
「 vserver cifs remove-netbios-aliases -vserver vs1 -netbios-aliases alias_1 」

. 指定した NetBIOS エイリアスが削除されたことを確認します。 vserver cifs show -vserver vserver_name -display-netbios-aliases
+
vserver cifs show -vserver vs1 -display-netbios-aliases

+
[listing]
----
Vserver: vs1

         Server Name: CIFS_SERVER
         NetBIOS Aliases: ALIAS_2, ALIAS_3
----

