---
permalink: smb-admin/remove-privileges-local-domain-users-groups-task.html 
sidebar: sidebar 
keywords: manage, user, right, local, domain, group, removing, remove, privilege, enhance, security, allow, customize, maximum, remove privileges from local or domain users or groups 
summary: 権限を削除することで、ローカルまたはドメインのユーザーまたはグループのユーザー権限を管理できます。これにより、ユーザーとグループが持つ権限の上限をカスタマイズできるため、セキュリティが強化されます。 
---
= ONTAP SMBのローカルまたはドメインユーザーまたはグループから権限を削除します
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
権限を削除することで、ローカルまたはドメインのユーザーまたはグループのユーザー権限を管理できます。これにより、ユーザーとグループが持つ権限の上限をカスタマイズできるため、セキュリティが強化されます。

.開始する前に
権限を削除するローカルまたはドメインのユーザまたはグループがすでに存在している必要があります。

.タスク概要
ローカルまたはドメインのユーザーまたはグループから権限を削除するときは、次の点に留意する必要があります：

* 1つ以上の権限を削除できます。
* ドメインのユーザまたはグループの権限を削除する場合、ONTAPでそれらのユーザやグループを検証するために、ドメイン コントローラに接続することがあります。
+
ONTAPがドメイン コントローラに接続できない場合、コマンドが失敗する可能性があります。



.手順
. ローカルまたはドメインのユーザーまたはグループから1つ以上の権限を削除します： `+vserver cifs users-and-groups privilege remove-privilege -vserver _vserver_name_ -user-or-group-name _name_ -privileges _privilege_[,...]+`
. 目的の権限がオブジェクトから削除されていることを確認します。 `vserver cifs users-and-groups privilege show -vserver _vserver_name_ ‑user-or-group-name _name_`


.例
次の例では、ストレージ仮想マシン（SVM、旧称Vserver）vs1上のユーザー「`CIFS_SERVER\sue`」から権限「`SeTcbPrivilege`」および「`SeTakeOwnershipPrivilege`」を削除します：

[listing]
----
cluster1::> vserver cifs users-and-groups privilege show -vserver vs1
Vserver   User or Group Name    Privileges
--------- --------------------- ---------------
vs1       CIFS_SERVER\sue       SeTcbPrivilege
                                SeTakeOwnershipPrivilege

cluster1::> vserver cifs users-and-groups privilege remove-privilege -vserver vs1 -user-or-group-name CIFS_SERVER\sue -privileges SeTcbPrivilege,SeTakeOwnershipPrivilege

cluster1::> vserver cifs users-and-groups privilege show -vserver vs1
Vserver   User or Group Name    Privileges
--------- --------------------- -------------------
vs1       CIFS_SERVER\sue       -
----