---
permalink: smb-admin/reset-privileges-local-domain-users-groups-task.html 
sidebar: sidebar 
keywords: reset, privilege, local, domain, user, group, modification, reset privilege for local or domain users and groups 
summary: ローカルまたはドメインのユーザーとグループの権限をリセットできます。これは、ローカルまたはドメインのユーザーまたはグループの権限を変更した後、その変更が不要になった場合に役立ちます。 
---
= ONTAP SMBのローカルまたはドメインユーザーとグループの権限をリセットする
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
ローカルまたはドメインのユーザーとグループの権限をリセットできます。これは、ローカルまたはドメインのユーザーまたはグループの権限を変更した後、その変更が不要になった場合に役立ちます。

.タスク概要
ローカルまたはドメインのユーザーまたはグループの権限をリセットすると、そのオブジェクトの権限エントリがすべて削除されます。

.手順
. ローカルまたはドメインのユーザーまたはグループの権限をリセットします： `vserver cifs users-and-groups privilege reset-privilege -vserver _vserver_name_ -user-or-group-name _name_`
. オブジェクトの権限がリセットされていることを確認します `vserver cifs users-and-groups privilege show -vserver _vserver_name_ ‑user-or-group-name _name_`


.例
次の例は、Storage Virtual Machine（SVM、旧Vserver）vs1上のユーザー「`CIFS_SERVER\sue`」の権限をリセットします。デフォルトでは、通常のユーザーにはアカウントに関連付けられた権限がありません：

[listing]
----
cluster1::> vserver cifs users-and-groups privilege show
Vserver   User or Group Name    Privileges
--------- --------------------- ---------------
vs1       CIFS_SERVER\sue       SeTcbPrivilege
                                SeTakeOwnershipPrivilege

cluster1::> vserver cifs users-and-groups privilege reset-privilege -vserver vs1 -user-or-group-name CIFS_SERVER\sue

cluster1::> vserver cifs users-and-groups privilege show
This table is currently empty.
----
次の例では、グループ "`BUILTIN\Administrators`" の権限をリセットし、権限エントリを実質的に削除します：

[listing]
----
cluster1::> vserver cifs users-and-groups privilege show
Vserver   User or Group Name       Privileges
--------- ------------------------ -------------------
vs1       BUILTIN\Administrators   SeRestorePrivilege
                                   SeSecurityPrivilege
                                   SeTakeOwnershipPrivilege

cluster1::> vserver cifs users-and-groups privilege reset-privilege -vserver vs1 -user-or-group-name BUILTIN\Administrators

cluster1::> vserver cifs users-and-groups privilege show
This table is currently empty.
----