---
permalink: smb-admin/roaming-profiles-store-user-profiles-concept.html 
sidebar: sidebar 
keywords: ontap, support, storing, store, windows, roam, profile, cifs, server, associate, storage, virtual, machine, svm, configuring, configure, automatic, resource, availability, available, regardless, use roaming profiles to store user profiles centrally on a cifs server associated with the svm 
summary: ONTAP では、 Windows の移動プロファイルの格納をサポートしており、それらを Storage Virtual Machine （ SVM ）に関連付けられた CIFS サーバに格納することができます。ユーザ移動プロファイルを設定すると、ユーザはログイン先に関係なく自動でリソースを利用できるようになります。また、移動プロファイルを使用すると、ユーザプロファイルの管理と管理が簡単になります。 
---
= 移動プロファイルを使用すると、 SVM の概要に関連付けられた SMB サーバにユーザプロファイルを一元的に格納できます
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
ONTAP では、 Windows の移動プロファイルの格納をサポートしており、それらを Storage Virtual Machine （ SVM ）に関連付けられた CIFS サーバに格納することができます。ユーザ移動プロファイルを設定すると、ユーザはログイン先に関係なく自動でリソースを利用できるようになります。また、移動プロファイルを使用すると、ユーザプロファイルの管理と管理が簡単になります。

移動ユーザプロファイルには、次のような利点があります。

* 自動でリソースを利用できる
+
Windows 8 、 Windows 7 、 Windows 2000 、または Windows XP を実行しているコンピュータであれば、ネットワーク上のどのコンピュータにログインしても、各ユーザの一意のプロファイルを自動的に利用できます。ネットワーク上で使用するコンピュータごとにプロファイルを作成する必要はありません。

* コンピュータの交換が簡単
+
ユーザのプロファイル情報はすべてネットワークに別途保存されるため、交換後の新しいコンピュータにユーザのプロファイルを簡単にダウンロードできます。ユーザが新しいコンピュータに初めてログインしたときに、サーバに保存されているユーザのプロファイルが新しいコンピュータにコピーされます。



.関連情報
xref:offline-files-allow-caching-concept.adoc[オフラインファイルを使用したオフラインで使用するファイルのキャッシュ]

xref:folder-redirection-store-data-concept.adoc[フォルダリダイレクトを使用した CIFS サーバへのデータの格納]
