---
permalink: smb-admin/security-descriptors-apply-file-folder-security-concept.html 
sidebar: sidebar 
keywords: security, descriptor, contain, access, control, list, file, folder, audit, user, how security descriptors are used to apply file and folder security 
summary: セキュリティ記述子には、ユーザがファイルやフォルダに対して実行できる操作、およびユーザがファイルやフォルダにアクセスするときに監査される内容を決定するアクセス制御リストが含まれます。 
---
= セキュリティ記述子を使用して ONTAP SMB ファイルおよびフォルダのセキュリティを適用する
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
セキュリティ記述子には、ユーザがファイルやフォルダに対して実行できる操作、およびユーザがファイルやフォルダにアクセスするときに監査される内容を決定するアクセス制御リストが含まれます。

* *権限*
+
権限はオブジェクトの所有者によって許可または拒否され、オブジェクト（ユーザ、グループ、またはコンピュータ オブジェクト）が指定されたファイルまたはフォルダに対して実行できる操作を決定します。

* *セキュリティ記述子*
+
セキュリティ記述子は、ファイルまたはフォルダに関連付けられた権限を定義するセキュリティ情報を含むデータ構造です。

* *アクセス制御リスト（ACL）*
+
アクセス制御リストは、セキュリティ記述子内に含まれるリストです。セキュリティ記述子が適用されるファイルまたはフォルダに対してユーザ、グループ、またはコンピュータ オブジェクトが実行できる操作に関する情報が含まれます。セキュリティ記述子には、次の2種類のACLを含めることができます。

+
** 任意アクセス制御リスト（DACL）
** システム アクセス制御リスト（SACL）


* *任意アクセス制御リスト（DACL）*
+
DACLには、ユーザ、グループ、およびコンピュータ オブジェクトのSIDリストと、ファイルまたはフォルダに対する操作アクセスの許可または拒否設定が含まれています。DACLには、0個以上のアクセス制御エントリ（ACE）が含まれます。

* *システム アクセス制御リスト（SACL）*
+
SACLには、成功または失敗した監査イベントがログに記録されるユーザ、グループ、およびコンピュータ オブジェクトのSIDリストが含まれます。SACLには、0個以上のアクセス制御エントリ（ACE）が含まれます。

* *Access Control Entries（ACE）*
+
ACEは、DACLまたはSACL内の個々のエントリです。

+
** DACL アクセス制御エントリは、特定のユーザー、グループ、またはコンピューター オブジェクトに対して許可または拒否されるアクセス権を指定します。
** SACL アクセス制御エントリは、特定のユーザー、グループ、またはコンピューター オブジェクトによって実行された指定されたアクションを監査するときにログに記録する成功イベントまたは失敗イベントを指定します。


* *権限の継承*
+
権限の継承とは、セキュリティ記述子で定義された権限が親オブジェクトからオブジェクトにどのように伝播されるかを表します。継承可能な権限のみが子オブジェクトに継承されます。親オブジェクトの権限を設定する際に、「`Apply to `this-folder` `sub-folders`、および `files``」を使用して、フォルダ、サブフォルダ、およびファイルに権限を継承するかどうかを指定できます。



.関連情報
* link:../nas-audit/index.html["SMBおよびNFS監査とセキュリティトレース"]
* xref:configure-apply-audit-policies-ntfs-files-folders-task.adoc[ファイルとフォルダに監査ポリシーを設定および適用するためのコマンド]

