---
permalink: smb-admin/security-styles-their-effects-concept.html 
sidebar: sidebar 
keywords: unix, ntfs, mixed, unified, security, style, effect, permission, handle, data, what the security styles and their effects are 
summary: セキュリティ形式には、 UNIX 、 NTFS 、 mixed 、および unified の 4 種類があり、セキュリティ形式ごとにデータに対する権限の処理方法が異なります。目的に応じて適切なセキュリティ形式を選択できるように、それぞれの影響について理解しておく必要があります。 
---
= セキュリティ形式とその影響とは
:icons: font
:imagesdir: ../media/


[role="lead"]
セキュリティ形式には、 UNIX 、 NTFS 、 mixed 、および unified の 4 種類があり、セキュリティ形式ごとにデータに対する権限の処理方法が異なります。目的に応じて適切なセキュリティ形式を選択できるように、それぞれの影響について理解しておく必要があります。

セキュリティ形式はデータにアクセスできるクライアントの種類には影響しないことに注意してください。セキュリティ形式で決まるのは、データアクセスの制御に ONTAP で使用される権限の種類と、それらの権限を変更できるクライアントの種類だけです。

たとえば、ボリュームで UNIX セキュリティ形式を使用している場合でも、 ONTAP はマルチプロトコルに対応しているため、 SMB クライアントから引き続きデータにアクセスできます（認証と許可が適切な場合）。ただし、 ONTAP では、 UNIX クライアントのみが標準のツールを使用して変更できる UNIX 権限が使用されます。

|===
| セキュリティ形式 | 権限を変更できるクライアント | クライアントが使用できる権限 | 有効になるセキュリティ形式 | ファイルにアクセスできるクライアント 


 a| 
「 UNIX 」
 a| 
NFS
 a| 
NFSv3 モードビット
 a| 
「 UNIX 」
 a| 
NFS と SMB



 a| 
NFSv4.x ACL
 a| 
「 UNIX 」



 a| 
NTFS
 a| 
SMB
 a| 
NTFS ACL
 a| 
NTFS



 a| 
混在
 a| 
NFS または SMB
 a| 
NFSv3 モードビット
 a| 
「 UNIX 」



 a| 
NFSv4.x ACL
 a| 
「 UNIX 」



 a| 
NTFS ACL
 a| 
NTFS
 a| 
統合：
 a| 
NFS または SMB



 a| 
NFSv3 モードビット
 a| 
「 UNIX 」



 a| 
NFSv4.1 ACL
 a| 
「 UNIX 」
 a| 
NTFS ACL
 a| 
NTFS

|===
FlexVol では、 UNIX 、 NTS 、および mixed のセキュリティ形式がサポートされます。セキュリティ形式が mixed または unified の場合は、ユーザがセキュリティ形式を各自設定するため、権限を最後に変更したクライアントの種類によって有効になる権限が異なります。権限を最後に変更したクライアントが NFSv3 クライアントの場合、権限は UNIX NFSv3 モードビットになります。最後のクライアントが NFSv4 クライアントの場合、権限は NFSv4 ACL になります。最後のクライアントが SMB クライアントの場合、権限は Windows NTFS ACL になります。

ONTAP 9.2 以降では、「 vserver security file-directory 」コマンドの「 how Effective permissions 」パラメータを使用して、指定したファイルまたはフォルダパス上の Windows ユーザまたは UNIX ユーザに付与されている有効な権限を表示できます。また、オプションのパラメータである「 -share-name 」を使用すると、有効な共有権限を表示できます。

[NOTE]
====
ONTAP で、最初にデフォルトのファイル権限がいくつか設定されます。デフォルトでは、 UNIX 、 mixed 、および unified のセキュリティ形式のボリュームにあるデータについては、セキュリティ形式は UNIX 、権限の種類は UNIX モードビット（特に指定しないかぎり 0755 ）が有効になります。これは、デフォルトのセキュリティ形式で許可されたクライアントで設定するまで変わりません。NTFS セキュリティ形式のボリュームにあるデータについては、デフォルトで NTFS セキュリティ形式が有効になり、すべてのユーザにフルコントロール権限を許可する ACL が割り当てられます。

====