---
permalink: smb-admin/signing-multiple-data-lifs-concept.html 
sidebar: sidebar 
keywords: enable, disable, require, smb, sign, server, guideline, lifs, configuration, svm, guidelines for smb signing when multiple data lifs are configured 
summary: SMB サーバーで必要な SMB 署名を有効または無効にする場合は、SVM の複数のデータ LIF 構成に関するガイドラインに注意する必要があります。 
---
= 複数のデータLIFに対するONTAP SMB署名設定について学習します
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
SMB サーバーで必要な SMB 署名を有効または無効にする場合は、SVM の複数のデータ LIF 構成に関するガイドラインに注意する必要があります。

SMBサーバを設定する場合、複数のデータLIFが設定されている場合があります。その場合、DNSサーバには、CIFSサーバの `A`レコード エントリが複数含まれます。これらのレコード エントリはすべて同じSMBサーバ ホスト名を使用していますが、IPアドレスはそれぞれ異なります。たとえば、2つのデータLIFが設定されているSMBサーバの場合、DNS `A`レコード エントリは次のようになります：

[listing]
----
10.1.1.128 A VS1.IEPUB.LOCAL VS1
10.1.1.129 A VS1.IEPUB.LOCAL VS1
----
通常の動作では、必要なSMB署名設定を変更すると、クライアントからの新規接続のみがSMB署名設定の変更の影響を受けます。ただし、この動作には例外があります。クライアントが既に共有に接続しており、設定変更後に元の接続を維持しながら、同じ共有への新規接続を作成する場合があります。この場合、新規接続と既存のSMB接続の両方に新しいSMB署名要件が適用されます。

次の例を考えてみましょう。

. Client1 は、パス `O:\`を使用して、必要な SMB 署名なしで共有に接続します。
. ストレージ管理者は、SMB 署名を要求するように SMB サーバー構成を変更します。
. Client1 は、パス `S:\`を使用して必要な SMB 署名で同じ共有に接続します（パス `O:\`を使用した接続を維持しながら）。
. その結果、 `O:\`ドライブと `S:\`ドライブの両方を介してデータにアクセスするときに SMB 署名が使用されます。

