---
permalink: smb-admin/statistics-monitor-automatic-node-referral-task.html 
sidebar: sidebar 
keywords: smb, connection, refer, monitor, automatic, node, referral, extent, locating, locate, host, redistribute, lif, local, access, cifs, use statistics to monitor automatic node referral activity 
summary: 参照される SMB 接続の数を確認するには、 statistics コマンドを使用して自動ノードリファーラルのアクティビティを監視します。リファーラルを監視することで、自動リファーラルによって共有をホストするノードに対して接続が割り当てられている範囲を把握し、データ LIF を再配分して CIFS サーバの共有へのローカルアクセスを向上させるべきかどうかを判断することができます。 
---
= 統計を使用して、自動ノードリファーラルのアクティビティを監視します
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
参照されるSMB接続の数を確認するには、を使用して自動ノードリファーラルのアクティビティを監視します `statistics` コマンドを実行しますリファーラルを監視することで、自動リファーラルによって共有をホストするノードに対して接続が割り当てられている範囲を把握し、データ LIF を再配分して CIFS サーバの共有へのローカルアクセスを向上させるべきかどうかを判断することができます。

.このタスクについて
。 `cifs` オブジェクトには、SMB自動ノードリファーラルの監視に役立つadvanced権限レベルのカウンタがいくつか用意されています。

* `node_referral_issued`
+
共有のルートとは別のノードでホストされる LIF を使用して接続したクライアントのうち、共有のルートのノードへのリファーラルが発行されたクライアントの数。

* `node_referral_local`
+
共有のルートと同じノードでホストされる LIF を使用して接続したクライアントの数。一般に、ローカルアクセスを使用するとパフォーマンスが最適化され

* `node_referral_not_possible`
+
共有のルートとは別のノードでホストされる LIF を使用して接続したクライアントのうち、共有のルートをホストするノードへのリファーラルが発行されていないクライアントの数。これは、共有のルートのノードに対するアクティブなデータ LIF が見つからないためです。

* `node_referral_remote`
+
共有のルートとは別のノードでホストされる LIF を使用して接続したクライアントの数。リモートアクセスを使用するとパフォーマンスが低下する可能性があります。



一定期間内のデータ（サンプル）を収集して表示することにより、 Storage Virtual Machine （ SVM ）の自動ノードリファーラル統計を監視できます。データ収集を停止しなければ、サンプルからデータを表示できます。データ収集を停止すると、サンプルが固定された状態になります。データ収集を停止しないと、以前のクエリとの比較に使用できる更新されたデータを取得できます。この比較は、パフォーマンスの傾向を確認するのに役立ちます。

[NOTE]
====
から収集した情報を評価および使用するため `statistics` コマンドを使用する場合は、環境内でのクライアントの分散状況について理解しておく必要があります。

====
.手順
. 権限レベルを advanced に設定します。 `set -privilege advanced`
. を使用して、自動ノードリファーラルの統計を表示します `statistics` コマンドを実行します
+
次に、一定のサンプリング時間におけるデータを収集して表示することにより、自動ノードリファーラルの統計を表示する例を示します。

+
.. 収集を開始します。 `statistics start -object cifs -instance vs1 -sample-id sample1`
+
[listing]
----
Statistics collection is being started for Sample-id: sample1
----
.. 目的の収集時間が経過するまで待ちます。
.. 収集を停止します。 `statistics stop -sample-id sample1`
+
[listing]
----
Statistics collection is being stopped for Sample-id: sample1
----
.. 自動ノードリファーラルの統計を表示します。 `statistics show -sample-id sample1 -counter *node*`
+
[listing]
----
Object: cifs
Instance: vs1
Start-time: 2/4/2013 19:27:02
End-time: 2/4/2013 19:30:11
Cluster: cluster1

    Counter                                             Value
    ----------------------------- ---------------------------
    node_name                                          node1
    node_referral_issued                                    0
    node_referral_local                                     1
    node_referral_not_possible                              2
    node_referral_remote                                    2
    ...

    node_name                                          node2
    node_referral_issued                                    2
    node_referral_local                                     1
    node_referral_not_possible                              0
    node_referral_remote                                    2
    ...
----
+
出力には、 SVM vs1 に含まれるすべてのノードのカウンタが表示されます。この例では、わかりやすいように、自動ノードリファーラルの統計に関連する出力フィールドだけを示しています。



. admin 権限レベルに戻ります。 `set -privilege admin`


.関連情報
xref:display-statistics-task.adoc[統計情報を表示します]

link:../performance-config/index.html["パフォーマンス監視のセットアップ"]
