---
permalink: smb-admin/supported-dynamic-access-control-reference.html 
sidebar: sidebar 
keywords: dynamic, access, control, dac, cifs, server, understand, ontap, support, functionality, active, directory, environment, supported dynamic access control functionality 
summary: CIFS サーバ上で DAC （ダイナミックアクセス制御）を使用する場合、 Active Directory 環境での ONTAP によるダイナミックアクセス制御機能のサポートについて理解しておく必要があります。 
---
= サポートされるダイナミックアクセス制御機能
:icons: font
:imagesdir: ../media/


[role="lead"]
CIFS サーバ上で DAC （ダイナミックアクセス制御）を使用する場合、 Active Directory 環境での ONTAP によるダイナミックアクセス制御機能のサポートについて理解しておく必要があります。



== ダイナミックアクセス制御でサポートされます

CIFS サーバでダイナミックアクセス制御が有効になっている場合、 ONTAP は次の機能をサポートします。

|===
| 機能性 | コメント 


 a| 
ファイルシステムへの請求
 a| 
請求とは、ユーザに関する何らかの真実を表す単純な名前と値のペアです。ユーザクレデンシャルに請求情報が含まれるようになり、ファイルのセキュリティ記述子は請求チェックを含むアクセスチェックを実行できるようになりました。これにより、管理者は誰がファイルにアクセスできるかを細かく制御できます。



 a| 
ファイルアクセスチェック用の条件式
 a| 
ファイルのセキュリティパラメータを変更するときに、ユーザは任意の複雑な条件式をファイルのセキュリティ記述子に追加できるようになりました。条件式には、クレームのチェックを含めることができます。



 a| 
集約型アクセスポリシーによるファイルアクセスの集中管理
 a| 
集約型アクセスポリシーは、ファイルへのタグ付けが可能な Active Directory 内に格納される一種の ACL です。ファイルへのアクセスは、ディスク上のセキュリティ記述子とタグ付きの集約型アクセスポリシーの両方のアクセスチェックでアクセスが許可されている場合にのみ許可されます。これにより、管理者はディスク上のセキュリティ記述子を変更することなく、一元的な場所（ AD ）からファイルへのアクセスを制御できます。



 a| 
集約型アクセスポリシーのステージング
 a| 
集約型アクセスポリシーへの変更を「集約型アクセスポリシー」し、監査レポートで変更の影響を確認することで、実際のファイルアクセスに影響を与えずにセキュリティの変更を試す機能を追加します。



 a| 
ONTAP CLI を使用した集約型アクセスポリシーセキュリティに関する情報の表示のサポート
 a| 
vserver security file-directory show コマンドを拡張し、適用される集約型アクセスポリシーについての情報を表示します。



 a| 
集約型アクセスポリシーを含むセキュリティトレース
 a| 
vserver security trace コマンドファミリーを拡張し、適用される集約型アクセスポリシーについての情報を含む結果を表示します。

|===


== ダイナミックアクセス制御ではサポートされません

CIFS サーバでダイナミックアクセス制御が有効になっている場合、 ONTAP は次の機能をサポートしません。

|===
| 機能性 | コメント 


 a| 
NTFS ファイルシステムオブジェクトの自動分類
 a| 
これは、 ONTAP でサポートされていない Windows ファイル分類インフラストラクチャの拡張機能です。



 a| 
集約型アクセスポリシーのステージング以外の高度な監査
 a| 
高度な監査では、集約型アクセスポリシーのステージングのみがサポートされます。

|===