---
permalink: smb-admin/supported-dynamic-access-control-reference.html 
sidebar: sidebar 
keywords: dynamic, access, control, dac, cifs, server, understand, ontap, support, functionality, active, directory, environment, supported dynamic access control functionality 
summary: CIFSサーバ上でダイナミック アクセス制御（DAC）を使用する場合、Active Directory環境でのONTAPによるダイナミック アクセス制御機能のサポートについて理解しておく必要があります。 
---
= ONTAP SMBサーバでサポートされているDAC機能
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
CIFSサーバ上でダイナミック アクセス制御（DAC）を使用する場合、Active Directory環境でのONTAPによるダイナミック アクセス制御機能のサポートについて理解しておく必要があります。



== サポートされるダイナミック アクセス制御

CIFSサーバでダイナミック アクセス制御が有効になっている場合、ONTAPは次の機能をサポートします。

|===
| 機能 | コメント 


 a| 
ファイルシステムへのクレーム（主張）
 a| 
クレームは、ユーザについての何らかの事実を表す名前と値のペアです。ユーザ クレデンシャルにはクレーム情報が含まれており、ファイルに対するセキュリティ記述子はクレーム チェックを含むアクセス チェックを実行できます。これによって、管理者は誰がファイルにアクセスできるかを細かく制御できます。



 a| 
ファイル アクセス チェック用の条件式
 a| 
ファイルのセキュリティ パラメータを変更する場合、ユーザは任意の複雑な条件式をファイルのセキュリティ記述子に追加できます。条件式には、クレーム チェックを含めることができます。



 a| 
集約型アクセス ポリシーによるファイル アクセスの集中管理
 a| 
集約型アクセス ポリシーは、ファイルへのタグ付けが可能なActive Directory内に格納される一種のACLです。ファイルへのアクセスは、ディスクに対するセキュリティ記述子とタグ付けされた集約型アクセス ポリシーの両方でアクセスが許可された場合にのみ許可されます。これにより、管理者はディスクに対するセキュリティ記述子を変更せずに一元的な場所（AD）からファイルへのアクセスを制御できます。



 a| 
集約型アクセス ポリシーのステージング
 a| 
集中アクセス ポリシーの変更を「`ステージング`」し、監査レポートで変更の効果を確認することで、実際のファイル アクセスに影響を与えずにセキュリティの変更を試す機能を追加します。



 a| 
ONTAP CLIを使用した集約型アクセス ポリシー セキュリティについての情報表示のサポート
 a| 
 `vserver security file-directory show`コマンドを拡張して、適用された中央アクセス ポリシーに関する情報を表示します。



 a| 
集約型アクセス ポリシーを含むセキュリティ トレース
 a| 
 `vserver security trace`コマンド ファミリを拡張して、適用された中央アクセス ポリシーに関する情報を含む結果を表示します。

|===


== サポートされないダイナミック アクセス制御

CIFSサーバでダイナミック アクセス制御が有効になっている場合、ONTAPは次の機能をサポートしません。

|===
| 機能 | コメント 


 a| 
NTFSファイルシステム オブジェクトの自動分類
 a| 
これは、ONTAPでサポートされないWindows File Classification Infrastructure拡張です。



 a| 
集約型アクセス ポリシーのステージング以外の高度な監査
 a| 
高度な監査では、集約型アクセス ポリシーのステージングのみがサポートされます。

|===