---
permalink: smb-admin/supported-versions-functionality-concept.html 
sidebar: sidebar 
keywords: server, message, block, smb, remote, file-sharing, protocol, microsoft, windows, client, server, ontap, functionality, environment, supported smb versions and functionality 
summary: Server Message Block （ SMB ；サーバメッセージブロック）は、 Microsoft Windows クライアントおよびサーバで使用されるリモートファイル共有プロトコルです。ONTAP 9 ではすべての SMB のバージョンがサポートされますが、デフォルトである SMB 1.0 がサポートされるかどうかは ONTAP のバージョンによって異なります。ONTAP SMB サーバが、ご使用の環境で必要なクライアントと機能をサポートしていることを確認する必要があります。 
---
= サポートされる SMB のバージョンと機能
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Server Message Block （ SMB ；サーバメッセージブロック）は、 Microsoft Windows クライアントおよびサーバで使用されるリモートファイル共有プロトコルです。ONTAP 9 ではすべての SMB のバージョンがサポートされますが、デフォルトである SMB 1.0 がサポートされるかどうかは ONTAP のバージョンによって異なります。ONTAP SMB サーバが、ご使用の環境で必要なクライアントと機能をサポートしていることを確認する必要があります。

ONTAP がサポートする SMB クライアントおよびドメインコントローラの最新情報については、 Interoperability Matrix Tool を参照してください。

SMB 2.0 以降のバージョンは ONTAP 9 の SMB サーバではデフォルトで有効になっており、必要に応じて有効または無効を切り替えることができます。次の表に、 SMB 1.0 のサポートとデフォルト設定を示します。

|===
| SMB 1.0 の機能： 4+| ONTAP 9 のリリース： 


 a| 
 a| 
9.0
 a| 
9.1
 a| 
9.2.
 a| 
9.3以降



 a| 
はデフォルトで有効になっています
 a| 
はい。
 a| 
はい。
 a| 
はい。
 a| 
いいえ



 a| 
有効または無効にすることができます
 a| 
いいえ
 a| 
はい * 9.1 P8 以降が必要です。
 a| 
はい。
 a| 
はい。

|===
[NOTE]
====
SMB 1.0 および 2.0 のドメインコントローラへの接続に関するデフォルト設定も ONTAP のバージョンによって異なります。詳細については、を参照してください `vserver cifs security modify` のマニュアルページ。既存の CIFS サーバで SMB 1.0 を実行している環境では、できるだけ早く最新の SMB バージョンに移行して、セキュリティとコンプライアンスを強化する必要があります。詳細については、ネットアップの担当者にお問い合わせください。

====
次の表に、 SMB でサポートされる機能と対応するバージョンを示します。SMB の機能には、デフォルトで有効になるものと追加の設定が必要なものがあります。

|===
| * この機能： * | * 有効化が必要： * 5+| * ONTAP 9 では、以下のバージョンの SMB がサポートされています。 * 


 a| 
 a| 
 a| 
1.0
 a| 
"2.0"
 a| 
2.1
 a| 
3.0
 a| 
3.1.1



 a| 
従来の SMB 1.0 の機能
 a| 
 a| 
X
 a| 
X
 a| 
X
 a| 
X
 a| 
X



 a| 
永続性ハンドル
 a| 
 a| 
 a| 
X
 a| 
X
 a| 
X
 a| 
X



 a| 
複合操作
 a| 
 a| 
 a| 
X
 a| 
X
 a| 
X
 a| 
X



 a| 
非同期操作
 a| 
 a| 
 a| 
X
 a| 
X
 a| 
X
 a| 
X



 a| 
読み取り / 書き込みバッファのサイズが増加します
 a| 
 a| 
 a| 
X
 a| 
X
 a| 
X
 a| 
X



 a| 
拡張性の向上
 a| 
 a| 
 a| 
X
 a| 
X
 a| 
X
 a| 
X



 a| 
SMB 署名
 a| 
X
 a| 
X
 a| 
X
 a| 
X
 a| 
X
 a| 
X



 a| 
代替データストリーム（ ADS ）ファイル形式
 a| 
X
 a| 
X
 a| 
X
 a| 
X
 a| 
X
 a| 
X



 a| 
Large MTU （ ONTAP 9.7 以降ではデフォルトで有効）
 a| 
X
 a| 
 a| 
 a| 
X
 a| 
X
 a| 
X



 a| 
oplock リース
 a| 
 a| 
 a| 
 a| 
X
 a| 
X
 a| 
X



 a| 
共有の継続的な可用性
 a| 
X
 a| 
 a| 
 a| 
 a| 
X
 a| 
X



 a| 
永続的ハンドル
 a| 
 a| 
 a| 
 a| 
 a| 
X
 a| 
X



 a| 
監視
 a| 
 a| 
 a| 
 a| 
 a| 
X
 a| 
X



 a| 
SMB 暗号化： AES-128-CCM
 a| 
X
 a| 
 a| 
 a| 
 a| 
X
 a| 
X



 a| 
スケールアウト（ CA 共有で必要）
 a| 
 a| 
 a| 
 a| 
 a| 
X
 a| 
X



 a| 
透過的なフェイルオーバー
 a| 
 a| 
 a| 
 a| 
 a| 
X
 a| 
X



 a| 
SMB マルチチャネル（ ONTAP 9.4 以降）
 a| 
X
 a| 
 a| 
 a| 
 a| 
X
 a| 
X



 a| 
事前認証の整合性
 a| 
 a| 
 a| 
 a| 
 a| 
 a| 
X



 a| 
クラスタ・クライアント・フェイルオーバー v.2 （ CCFv2 ）
 a| 
 a| 
 a| 
 a| 
 a| 
 a| 
X



 a| 
SMB 暗号化： AES-128-GCM （ ONTAP 9.1 以降）
 a| 
X
 a| 
 a| 
 a| 
 a| 
 a| 
X

|===
.関連情報
xref:signing-enhance-network-security-concept.adoc[SMB 署名を使用したネットワークセキュリティの強化]

xref:set-server-minimum-authentication-security-level-task.adoc[SMBサーバの最小認証セキュリティレベルの設定]

xref:configure-required-encryption-concept.adoc[SMB を介したデータ転送での SMB サーバの SMB 暗号化要求の設定]

http://www.netapp.com/us/media/tr-4543.pdf["ネットアップテクニカルレポート 4543 ：『 SMB Protocol Best Practices 』"]

https://mysupport.netapp.com/NOW/products/interoperability["ネットアップの相互運用性"^]
