---
permalink: smb-admin/support-ipv6-concept.html 
sidebar: sidebar 
keywords: ipv6, cifs, server, ontap, smb, network, communication, service, support for ipv6 with smb access and cifs services 
summary: CIFSサーバ上でIPv6を使用する場合は、ONTAPによるSMBアクセスやCIFSサービスとのネットワーク通信でのIPv6のサポートについて確認しておく必要があります。 
---
= ONTAP SMBアクセスおよびCIFSサービスによるIPv6のサポートについて学習します
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
CIFSサーバ上でIPv6を使用する場合は、ONTAPによるSMBアクセスやCIFSサービスとのネットワーク通信でのIPv6のサポートについて確認しておく必要があります。



== Windowsクライアントおよびサーバのサポート

ONTAPでは、IPv6をサポートするWindowsサーバおよびクライアントをサポートしています。Microsoft WindowsクライアントおよびサーバによるIPv6のサポートは次のとおりです。

* Windows 7、Windows 8、Windows Server 2008、Windows Server 2012、およびそれ以降のリリースでは、SMBファイル共有とActive Directoryサービス（DNS、LDAP、CLDAP、Kerberosなどのサービス）の両方でIPv6がサポートされます。
+
IPv6アドレスが設定されている場合、Windows 7、Windows Server 2008、およびそれ以降のリリースでは、Active Directoryサービスに対してデフォルトでIPv6が使用されます。IPv6接続によるNTLM認証とKerberos認証の両方がサポートされます。

+
ONTAPでサポートされるWindowsクライアントでは、いずれもIPv6アドレスを使用してSMB共有にアクセスできます。



ONTAPがサポートするWindowsクライアントの最新情報については、link:https://mysupport.netapp.com/matrix["Interoperability Matrix"^]を参照してください。

[NOTE]
====
NTドメインはIPv6ではサポートされません。

====


== その他のCIFSサービスのサポート

ONTAPでは、SMBファイル共有とActive Directoryサービスに加え、以下に対してもIPv6をサポートしています。

* クライアント側のサービス：オフライン フォルダ、移動プロファイル、フォルダ リダイレクト、以前のバージョン機能など
* サーバ側のサービス：動的ホーム ディレクトリの有効化（ホーム ディレクトリ機能）、シンボリックリンクとワイドリンク、BranchCache、ODXコピー オフロード、自動ノード リファーラル、以前のバージョン機能など
* ファイル アクセス管理用のサービス：Windowsのローカル ユーザやローカル グループを使用したアクセス制御と権限の管理、CLIを使用したファイル権限や監査ポリシーの設定、セキュリティ トレース、ファイル ロックの管理、SMBアクティビティの監視など
* NASのマルチプロトコルの監査
* FPolicy
* 共有の継続的な可用性、監視プロトコル、およびリモートVSS（Hyper-V over SMB構成で使用）




== ネーム サービスと認証サービスのサポート

次のネーム サービスを使用した通信がIPv6でサポートされます。

* ドメイン コントローラ
* DNSサーバ
* LDAPサーバ
* KDCサーバ
* NISサーバ

