---
permalink: smb-admin/unix-file-permissions-provide-access-control-concept.html 
sidebar: sidebar 
keywords: flexvol, volume, security, style, ntfs, unix, mixed, access, data, smb, regardless, access, effective, how unix file permissions provide access control when accessing files over smb 
summary: FlexVol ボリュームのセキュリティ形式は、 NTFS 、 UNIX 、 mixed の 3 種類のいずれかにすることができます。セキュリティ形式に関係なく SMB 経由でデータにアクセスできますが、 UNIX 対応のセキュリティを使用するデータにアクセスするには、適切な UNIX ファイル権限が必要になります。 
---
= SMB 経由でファイルにアクセスする際の UNIX ファイルアクセス権によるアクセス制御方法
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
FlexVol ボリュームのセキュリティ形式は、 NTFS 、 UNIX 、 mixed の 3 種類のいずれかにすることができます。セキュリティ形式に関係なく SMB 経由でデータにアクセスできますが、 UNIX 対応のセキュリティを使用するデータにアクセスするには、適切な UNIX ファイル権限が必要になります。

SMB 経由でのデータへのアクセス時には、いくつかのアクセス制御を使用して、要求した操作を実行する権限がユーザにあるかどうかが判断されます。

* エクスポート権限
+
SMB アクセスに関するエクスポート権限の設定はオプションです。

* 共有権限
* ファイル権限
+
ユーザが操作を実行するデータには、次のタイプのファイル権限を適用できます。

+
** NTFS
** UNIX NFSv4 ACL
** UNIX モードビット




NFSv4 ACL または UNIX モードビットが設定されたデータの場合は、 UNIX 形式のアクセス権を使用してデータへのファイルアクセス権が決定されます。SVM 管理者は、適切なファイル権限を設定して、ユーザに目的のアクションを実行する権限が付与されるようにする必要があります。

[NOTE]
====
mixed セキュリティ形式のボリューム内のデータでは、 NTFS または UNIX 対応のセキュリティ形式を使用できます。UNIX 対応のセキュリティ形式を使用するデータの場合は、データに対するファイル権限を判断するときに NFSv4 権限または UNIX モードビットが使用されます。

====