---
permalink: smb-admin/use-cases-odx-concept.html 
sidebar: sidebar 
keywords: use, case, odx, svm, determine, circumstance, odx, performance, benefit, use cases for odx 
summary: SVM で ODX を使用する前に、どのような場合にパフォーマンスを向上できるかを判断できるようにユースケースについて確認しておく必要があります。 
---
= ODX のユースケース
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
SVM で ODX を使用する前に、どのような場合にパフォーマンスを向上できるかを判断できるようにユースケースについて確認しておく必要があります。

ODX をサポートする Windows サーバおよびクライアントでは、リモートサーバ間でデータをコピーする際に、デフォルトでコピーオフロードが使用されます。Windows サーバまたはクライアントで ODX がサポートされていない場合や、 ODX コピーオフロードが任意の時点で失敗した場合は、コピーまたは移動処理が従来の読み取りと書き込みの処理を使用して実行されます。

ODX コピーおよび移動の使用は、以下のユースケースでサポートされます。

* ボリューム内
+
ソースとデスティネーションのファイルまたは LUN は、同じボリューム内にあります。

* ボリュームが異なり、ノードと SVM は同じです
+
ソースとデスティネーションのファイルまたは LUN は、同じノード上の異なるボリュームにあります。データは同じ SVM に所有されます。

* ボリュームとノードが異なり、 SVM は同じです
+
ソースとデスティネーションのファイルまたは LUN は、異なるノード上の異なるボリュームにあります。データは同じ SVM に所有されます。

* SVM が異なり、ノードは同じです
+
ソースとデスティネーションのファイルまたは LUN は、同じノード上の異なるボリュームにあります。データは異なる SVM に所有されます。

* SVM とノードが異なります
+
ソースとデスティネーションのファイルまたは LUN は、異なるノード上の異なるボリュームにあります。データは異なる SVM に所有されます。

* クラスタ間
+
ソース LUN とデスティネーション LUN は、異なるクラスタの異なるノード上の異なるボリュームにあります。これは SAN でのみサポートされ、 CIFS では機能しません。



その他にも、いくつかの特殊なユースケースがあります。

* ONTAP の ODX の実装で ODX を使用すると、 SMB 共有と FC / iSCSI で接続された仮想ドライブとの間でファイルをコピーできます。
+
SMB 共有と LUN が同じクラスタにある場合は、 Windows エクスプローラ、 Windows CLI または PowerShell 、 Hyper-V 、または ODX をサポートするその他のアプリケーションを使用して、 SMB 共有と接続された LUN 間の ODX コピーオフロードを使用してファイルをシームレスにコピーまたは移動できます。

* Hyper-V では、さらに次のようなユースケースでも ODX コピーオフロードが使用されます。
+
** Hyper-V で ODX コピーオフロードのパススルーを使用して、仮想ハードディスク（ VHD ）ファイル内および VHD ファイル間でのデータのコピー、または同じクラスタ内のマッピングされた SMB 共有と接続された iSCSI LUN の間でのデータのコピーを実行できます。
+
これにより、ゲストオペレーティングシステムからのコピーを基盤となるストレージに渡すことができます。

** 容量固定 VHD を作成する際に、 ODX を使用して、既知の初期化済みトークンによってディスクを初期化します。
** ソースとデスティネーションのストレージが同じクラスタにある場合に、 ODX コピーオフロードを使用して、仮想マシンのストレージを移行します。


+
[NOTE]
====
Hyper-V での ODX コピーオフロードのパススルーの用途を活用するには、ゲストオペレーティングシステムで ODX がサポートされている必要があります。また、ゲストオペレーティングシステムのディスクが、 ODX をサポートするストレージ（ SMB または SAN ）から作成された SCSI ディスクである必要があります。ゲストオペレーティングシステムのディスクが IDE ディスクの場合、 ODX のパススルーはサポートされません。

====

