---
permalink: smb-admin/view-shares-mmc-task.html 
sidebar: sidebar 
keywords: information, smb, share, svm, perform, management, task, microsoft, management, console, mmc, view, share, connect, svm, view information about smb shares using the mmc 
summary: Microsoft管理コンソール（MMC）を使用して、SVM上のSMB共有に関する情報を表示し、いくつかの管理タスクを実行できます。共有を表示する前に、MMCをSVMに接続する必要があります。 
---
= MMCを使用してONTAP SMB共有に関する情報を表示する
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Microsoft管理コンソール（MMC）を使用して、SVM上のSMB共有に関する情報を表示し、いくつかの管理タスクを実行できます。共有を表示する前に、MMCをSVMに接続する必要があります。

.タスク概要
MMC を使用して、SVM 内に含まれる共有に対して次のタスクを実行できます：

* 共有を表示
* アクティブなセッションを表示
* 開いているファイルを表示する
* システム内のセッション、ファイル、ツリー接続のリストを列挙する
* システム内の開いているファイルを閉じる
* 開いているセッションを閉じる
* 共有の作成/管理


[NOTE]
====
上記の機能によって表示されるビューはノード固有であり、クラスタ固有ではありません。そのため、MMCを使用してSMBサーバのホスト名（つまり、cifs01.domain.local）に接続すると、DNSの設定に基づいて、クラスタ内の単一のLIFにルーティングされます。

====
次の機能は、ONTAP用のMMCではサポートされていません：

* 新しいローカル ユーザー/グループの作成
* 既存のローカル ユーザー/グループの管理/表示
* イベントまたはパフォーマンス ログの表示
* ストレージ
* サービスとアプリケーション


操作がサポートされていない場合は、 `remote procedure call failed`エラーが発生する可能性があります。

https://kb.netapp.com/Advice_and_Troubleshooting/Data_Storage_Software/ONTAP_OS/FAQ%3A_Using_Windows_MMC_with_ONTAP["FAQ：ONTAP での Windows MMC の使用"]

.手順
. 任意の Windows サーバーでコンピューターの管理 MMC を開くには、*コントロール パネル*で、*管理ツール*>*コンピューターの管理*を選択します。
. *アクション* > *別のコンピュータに接続* を選択します。
+
[コンピューターの選択] ダイアログ ボックスが表示されます。

. ストレージ システムの名前を入力するか、*参照*をクリックしてストレージ システムを見つけます。
. *OK*をクリックします。
+
MMC は SVM に接続します。

. ナビゲーション ペインで、*共有フォルダー* > *共有* をクリックします。
+
SVM 上の共有のリストが右側の表示ペインに表示されます。

. 共有の共有プロパティを表示するには、共有をダブルクリックして [プロパティ] ダイアログ ボックスを開きます。
. MMC を使用してストレージ システムに接続できない場合は、ストレージ システムで次のいずれかのコマンドを使用して、ユーザーを BUILTIN\Administrators グループまたは BUILTIN\Power Users グループに追加できます：
+
[listing]
----

cifs users-and-groups local-groups add-members -vserver <vserver_name> -group-name BUILTIN\Administrators -member-names <domainuser>

cifs users-and-groups local-groups add-members -vserver <vserver_name> -group-name "BUILTIN\Power Users" -member-names <domainuser>
----

