---
permalink: svm-migrate/migrate-svm-task.html 
sidebar: sidebar 
keywords: svm, migrate, defaults, cutover, cleanup 
summary: SVM の移行が完了すると、クライアントがデスティネーションクラスタに自動的にカットオーバーされ、不要な SVM がソースクラスタから削除されます。自動カットオーバーとソースの自動クリーンアップはデフォルトで有効になっています。必要に応じて、カットオーバーの発生前にクライアントの自動カットオーバーを無効にして移行を一時停止することもできます。また、ソース SVM の自動クリーンアップを無効にすることもできます。 
---
= SVM を移行する
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
SVM の移行が完了すると、クライアントがデスティネーションクラスタに自動的にカットオーバーされ、不要な SVM がソースクラスタから削除されます。自動カットオーバーとソースの自動クリーンアップはデフォルトで有効になっています。必要に応じて、カットオーバーの発生前にクライアントの自動カットオーバーを無効にして移行を一時停止することもできます。また、ソース SVM の自動クリーンアップを無効にすることもできます。

* を使用できます `-auto-cutover false` クライアントの自動カットオーバーが通常発生したときに移動を一時停止し、あとで手動でカットオーバーを実行するオプションです。
+
xref:manual-client-cutover-task.adoc[SVM 移行後にクライアントを手動でカットオーバーする]

* advanced権限を使用できます `-auto-source-cleanup false` カットオーバー後にソースSVMの削除を無効にし、カットオーバー後にソースのクリーンアップを手動で開始するオプション。
+
xref:manual-source-removal-task.adoc[カットオーバー後にソース SVM を手動で削除]





== 自動カットオーバーを有効にして SVM を移行します

デフォルトでは、移行の完了時にクライアントがデスティネーションクラスタに自動的にカットオーバーされ、不要な SVM がソースクラスタから削除されます。

.手順
. デスティネーションクラスタから、移行の事前確認を実行します。
+
`dest_cluster> vserver migrate start -vserver _SVM_name_ -source-cluster _cluster_name_ -check-only true`

. デスティネーションクラスタから、 SVM 移行を開始します。
+
`dest_cluster> vserver migrate start -vserver _SVM_name_ -source-cluster _cluster_name_`

. 移行ステータスを確認します。
+
`dest_cluster> vserver migrate show`

+
SVM の移行が完了すると、ステータスに「 migrate-complete 」と表示されます。





== クライアントの自動カットオーバーを無効にして SVM を移行します

自動クライアントカットオーバーが正常に実行されたときに移行を一時停止してから、あとから手動でカットオーバーを実行するには、 -auto-cutover false オプションを使用します。「 SVM 移行後のクライアントの手動カットオーバー」を参照してください。

.手順
. デスティネーションクラスタから、移行の事前確認を実行します。
+
`dest_cluster> vserver migrate start -vserver _SVM_name_ -source-cluster _cluster_name_ -check-only true`

. デスティネーションクラスタから、 SVM 移行を開始します。
+
`dest_cluster> vserver migrate start -vserver _SVM_name_ -source-cluster _cluster_name_ -auto-cutover false`

. 移行ステータスを確認します。
+
`dest_cluster> vserver migrate show`
SVM 移行が非同期データ転送を完了し、カットオーバー処理の準備が完了した時点で、ステータスには「カットオーバー準備完了」と表示されます。





== ソースのクリーンアップが無効になっている SVM を移行します

カットオーバー後にソース SVM の削除を無効にしてから、カットオーバー後にソースのクリーンアップを手動でトリガーするには、 advanced 権限の -auto-giveback false オプションを使用します。「カットオーバー後のソースの手動クリーンアップ」を参照してください。

.手順
. デスティネーションクラスタから、移行の事前確認を実行します。
+
`dest_cluster*> vserver migrate start -vserver _SVM_name_ -source-cluster _cluster_name_ -check-only true`

. デスティネーションクラスタから、 SVM 移行を開始します。
+
`dest_cluster*> vserver migrate start -vserver _SVM_name_ -source-cluster _cluster_name_ -auto-source-cleanup false`

. 移行ステータスを確認します。
+
`dest_cluster*> vserver migrate show`

+
SVM 移行のカットオーバーが完了し、ソースクラスタの SVM を削除する準備ができている場合は、ステータスに「 ready for -source-cleanup 」と表示されます。


