---
permalink: svm-migrate/pause-task.html 
sidebar: sidebar 
keywords: svm, migrate, pause, resume, restart 
summary: '移行のカットオーバーを開始する前に、 SVM 移行を一時停止することができます。を使用してSVMの移行を一時停止できます `vserver migrate pause` コマンドを実行します' 
---
= SVM 移行を一時停止して再開します
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
移行のカットオーバーを開始する前に、 SVM 移行を一時停止することができます。を使用してSVMの移行を一時停止できます `vserver migrate pause` コマンドを実行します



== 移行を一時停止

を使用すると、クライアントのカットオーバーを開始する前にSVMの移行を一時停止できます `vserver migrate pause` コマンドを実行します

移行処理の実行中は、一部の設定変更が制限されます。ただし、ONTAP 9.12.1以降では、移行を一時停止して制限された設定や一部の失敗した状態を修正することで、障害の原因となった可能性のある設定の問題を修正できます。SVMの移行を一時停止するときに解決できる失敗状態には、次のようなものがあります。

* setup-configuration - failed（セットアップ-設定-失敗
* migrate -失敗しました


.手順
. デスティネーションクラスタから、移行を一時停止します。
+
`dest_cluster> vserver migrate pause -vserver <vserver name>`





== 移行を再開

一時停止したSVMの移行を再開する準備ができたら、またはSVMの移行が失敗した場合は、を使用できます `vserver migrate resume` コマンドを実行します

.ステップ
. SVM の移行を再開します。
+
`dest_cluster> vserver migrate resume`

. SVM の移行が再開されたことを確認し、進捗状況を監視します。
+
`dest_cluster> vserver migrate show`


