---
permalink: mediator/enable-access-repos-task.html 
sidebar: sidebar 
keywords: mediator, new, release, update, install, 
summary: リポジトリへのアクセスを有効にして、ONTAP Mediator がインストールプロセス中に必要なパッケージにアクセスできるようにします。 
---
= ONTAP Mediatorのインストールにリポジトリアクセスを提供する
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
ONTAP Mediator がインストール プロセス中に必要なパッケージにアクセスできるように、リポジトリへのアクセスを有効にする必要があります。

.手順
. 次の表を参照して、アクセスする必要があるリポジトリを特定します。
+
[cols="35,65"]
|===


| オペレーティング システム | アクセスが必要なリポジトリ 


 a| 
RHEL 10.x
 a| 
** rhel-10-for-x86_64-baseos-rpms
** rhel-10-for-x86_64-appstream-rpms




 a| 
RHEL 9.x
 a| 
** rhel-9-for-x86_64-baseos-rpms
** rhel-9-for-x86_64-appstream-rpms




 a| 
RHEL 8.x
 a| 
** rhel-8-for-x86_64-baseos-rpms
** rhel-8-for-x86_64-appstream-rpms




 a| 
RHEL 7.x
 a| 
** rhel-7-server-optional-rpms




 a| 
CentOS 7.x
 a| 
** C7.6.1810 - Baseリポジトリ




 a| 
Rocky Linux 10
 a| 
** appstream
** baseos




 a| 
Rocky Linux 9
 a| 
** appstream
** baseos




 a| 
Rocky Linux 8
 a| 
** appstream
** baseos


|===
. インストール中にONTAP Mediatorが必要なパッケージにアクセスできるように、次のいずれかの手順を実行して上記のリポジトリへのアクセスを有効にします。



NOTE: ONTAP Mediator が「extras」リポジトリと「optional」リポジトリにある Python モジュールに依存している場合は、 `rhel-X-for-x86_64-extras-rpms`および `rhel-X-for-x86_64-optional-rpms`ファイルにアクセスする必要がある場合があります。

.RHEL 10.xオペレーティング システムの手順
[#rhel10x%collapsible]
====
オペレーティング システムが *RHEL 10.x* の場合、リポジトリへのアクセスを有効にするには、次の手順を使用します：

.手順
. 必要なリポジトリにサブスクライブします。
+
[source, cli]
----
subscription-manager repos --enable rhel-10-for-x86_64-baseos-rpms
----
+
[source, cli]
----
subscription-manager repos --enable rhel-10-for-x86_64-appstream-rpms
----
+
次の例は、このコマンドの実行例を示しています。

+
[listing]
----
[root@localhost ~]# subscription-manager repos --enable rhel-10-for-x86_64-baseos-rpms
Repository 'rhel-10-for-x86_64-baseos-rpms' is enabled for this system.
[root@localhost ~]# subscription-manager repos --enable rhel-10-for-x86_64-appstream-rpms
Repository 'rhel-10-for-x86_64-appstream-rpms' is enabled for this system.
----
.  `yum repolist`コマンドを実行します。
+
新しくサブスクライブしたリポジトリがリストに表示されます。



====
.RHEL 9.xオペレーティング システムの手順
[#rhel9x%collapsible]
====
オペレーティング システムが *RHEL 9.x* の場合、リポジトリへのアクセスを有効にするには、次の手順を使用します：

.手順
. 必要なリポジトリにサブスクライブします。
+
[source, cli]
----
subscription-manager repos --enable rhel-9-for-x86_64-baseos-rpms
----
+
[source, cli]
----
subscription-manager repos --enable rhel-9-for-x86_64-appstream-rpms
----
+
次の例は、このコマンドの実行例を示しています。

+
[listing]
----
[root@localhost ~]# subscription-manager repos --enable rhel-9-for-x86_64-baseos-rpms
Repository 'rhel-9-for-x86_64-baseos-rpms' is enabled for this system.
[root@localhost ~]# subscription-manager repos --enable rhel-9-for-x86_64-appstream-rpms
Repository 'rhel-9-for-x86_64-appstream-rpms' is enabled for this system.
----
.  `yum repolist`コマンドを実行します。
+
新しくサブスクライブしたリポジトリがリストに表示されます。



====
.RHEL 8.xオペレーティング システムの手順
[#rhel8x%collapsible]
====
オペレーティング システムが *RHEL 8.x* の場合、リポジトリへのアクセスを有効にするには、次の手順を使用します：

.手順
. 必要なリポジトリにサブスクライブします。
+
[source, cli]
----
subscription-manager repos --enable rhel-8-for-x86_64-baseos-rpms
----
+
[source, cli]
----
subscription-manager repos --enable rhel-8-for-x86_64-appstream-rpms
----
+
次の例は、このコマンドの実行例を示しています。

+
[listing]
----
[root@localhost ~]# subscription-manager repos --enable rhel-8-for-x86_64-baseos-rpms
Repository 'rhel-8-for-x86_64-baseos-rpms' is enabled for this system.
[root@localhost ~]# subscription-manager repos --enable rhel-8-for-x86_64-appstream-rpms
Repository 'rhel-8-for-x86_64-appstream-rpms' is enabled for this system.
----
.  `yum repolist`コマンドを実行します。
+
新しくサブスクライブしたリポジトリがリストに表示されます。



====
.RHEL 7.xオペレーティング システムの手順
[#rhel7x%collapsible]
====
オペレーティング システムが *RHEL 7.x* の場合、リポジトリへのアクセスを有効にするには、次の手順を使用します：

.手順
. 必要なリポジトリにサブスクライブします。
+
[source, cli]
----
subscription-manager repos --enable rhel-7-server-optional-rpms
----
+
次の例は、このコマンドの実行例を示しています。

+
[listing]
----
[root@localhost ~]# subscription-manager repos --enable rhel-7-server-optional-rpms
Repository 'rhel-7-server-optional-rpms' is enabled for this system.
----
.  `yum repolist`コマンドを実行します。
+
次の例は、このコマンドの実行例を示しています。「rhel-7-server-optional-rpms」リポジトリがリストに表示されます。

+
[listing]
----
[root@localhost ~]# yum repolist
Loaded plugins: product-id, search-disabled-repos, subscription-manager
rhel-7-server-optional-rpms | 3.2 kB  00:00:00
rhel-7-server-rpms | 3.5 kB  00:00:00
(1/3): rhel-7-server-optional-rpms/7Server/x86_64/group              |  26 kB  00:00:00
(2/3): rhel-7-server-optional-rpms/7Server/x86_64/updateinfo         | 2.5 MB  00:00:00
(3/3): rhel-7-server-optional-rpms/7Server/x86_64/primary_db         | 8.3 MB  00:00:01
repo id                                      repo name                                             status
rhel-7-server-optional-rpms/7Server/x86_64   Red Hat Enterprise Linux 7 Server - Optional (RPMs)   19,447
rhel-7-server-rpms/7Server/x86_64            Red Hat Enterprise Linux 7 Server (RPMs)              26,758
repolist: 46,205
[root@localhost ~]#
----


====
.CentOS 7.xオペレーティング システムの手順
[#centos7x%collapsible]
====
オペレーティング システムが *CentOS 7.x* の場合、リポジトリへのアクセスを有効にするには、次の手順に従います：


NOTE: 次の例は、CentOS 7.6用のリポジトリを示しており、その他のCentOSバージョンでは使用できない可能性があります。お使いのバージョンのCentOS用のBaseリポジトリを使用してください。

.手順
. C7.6.1810 - Baseリポジトリを追加します。C7.6.1810 - Base保管用リポジトリには、ONTAP Mediatorに必要な「kernel-devel」パッケージが含まれています。
. /etc/yum.repos.d/CentOS-Vault.repoに次の行を追加します。
+
[source, cli]
----
[C7.6.1810-base]
name=CentOS-7.6.1810 - Base
baseurl=http://vault.centos.org/7.6.1810/os/$basearch/
gpgcheck=1
gpgkey=file:///etc/pki/rpm-gpg/RPM-GPG-KEY-CentOS-7
enabled=1
----
.  `yum repolist`コマンドを実行します。
+
次の例は、このコマンドの実行例を示しています。CentOS-7.6.1810 - Baseリポジトリがリストに表示されます。

+
[listing]
----
Loaded plugins: fastestmirror
Loading mirror speeds from cached hostfile
 * base: distro.ibiblio.org
 * extras: distro.ibiblio.org
 * updates: ewr.edge.kernel.org
C7.6.1810-base                                 | 3.6 kB  00:00:00
(1/2): C7.6.1810-base/x86_64/group_gz          | 166 kB  00:00:00
(2/2): C7.6.1810-base/x86_64/primary_db        | 6.0 MB  00:00:04
repo id                      repo name               status
C7.6.1810-base/x86_64        CentOS-7.6.1810 - Base  10,019
base/7/x86_64                CentOS-7 - Base         10,097
extras/7/x86_64              CentOS-7 - Extras       307
updates/7/x86_64             CentOS-7 - Updates      1,010
repolist: 21,433
[root@localhost ~]#
----


====
.Rocky Linux 10、9、または8オペレーティングシステムの手順
[#rocky-linux-10-9-8%collapsible]
====
オペレーティング システムが *Rocky Linux 10*、*Rocky Linux 9*、または *Rocky Linux 8* の場合、リポジトリへのアクセスを有効にするには、次の手順に従います：

.手順
. 必要なリポジトリにサブスクライブします。
+
[source, cli]
----
dnf config-manager --set-enabled baseos
----
+
[source, cli]
----
dnf config-manager --set-enabled appstream
----
.  `clean`操作を実行します：
+
[source, cli]
----
dnf clean all
----
. リポジトリのリストを確認します。
+
[source, cli]
----
dnf repolist
----


....
[root@localhost ~]# dnf config-manager --set-enabled baseos
[root@localhost ~]# dnf config-manager --set-enabled appstream
[root@localhost ~]# dnf clean all
[root@localhost ~]# dnf repolist
repo id                        repo name
appstream                      Rocky Linux 10 - AppStream
baseos                         Rocky Linux 10 - BaseOS
[root@localhost ~]#
....
....
[root@localhost ~]# dnf config-manager --set-enabled baseos
[root@localhost ~]# dnf config-manager --set-enabled appstream
[root@localhost ~]# dnf clean all
[root@localhost ~]# dnf repolist
repo id                        repo name
appstream                      Rocky Linux 9 - AppStream
baseos                         Rocky Linux 9 - BaseOS
[root@localhost ~]#
....
....
[root@localhost ~]# dnf config-manager --set-enabled baseos
[root@localhost ~]# dnf config-manager --set-enabled appstream
[root@localhost ~]# dnf clean all
[root@localhost ~]# dnf repolist
repo id                        repo name
appstream                      Rocky Linux 8 - AppStream
baseos                         Rocky Linux 8 - BaseOS
[root@localhost ~]#
....
====