---
permalink: mediator/index.html 
sidebar: sidebar 
keywords: ontap mediator service, install requirements, mediator requirements 
summary: ONTAP メディエーターサービスをインストールするには、すべての前提条件を満たしていることを確認してから、インストールパッケージを取得してホストでインストーラを実行する必要があります。 
---
= ONTAP メディエーターサービスのインストールまたはアップグレードを準備します
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
ONTAPメディエーターサービスをインストールするには、すべての前提条件を満たしていることを確認し、インストールパッケージを読み込んでホストでインストーラを実行する必要があります。この手順は、既存の環境のインストールまたはアップグレードに使用します。

.このタスクについて
* ONTAP 9.7以降では、任意のバージョンのONTAP メディエーターを使用してMetroCluster IP構成を監視できます。
* ONTAP 9.8以降では、任意のバージョンのONTAPメディエーターを使用して、SnapMirrorのアクティブな同期関係を監視できます。


.作業を開始する前に
次の前提条件を満たしている必要があります。

[cols="30,70"]
|===


| ONTAP メディエーターのバージョン | サポートされている Linux バージョン 


 a| 
1.7
 a| 
* Red Hat Enterprise Linux：8.5、8.6、8.7、8.8、8.9、 9.0、9.1、9.2、9.3
* Rocky Linux 8および9




 a| 
1.6
 a| 
* Red Hat Enterprise Linux：8.4、8.5、8.6、8.7、8.8、 9.0、9.1、9.2
* Rocky Linux 8および9




 a| 
1.5
 a| 
* Red Hat Enterprise Linux：7.6、7.7、7.8、7.9、8.1、 8.2、8.3、8.4、8.5
* CentOS ： 7.6 、 7.7 、 7.8 、 7.9




 a| 
1.4
 a| 
* Red Hat Enterprise Linux：7.6、7.7、7.8、7.9、8.1、 8.2、8.3、8.4、8.5
* CentOS ： 7.6 、 7.7 、 7.8 、 7.9




 a| 
1.3
 a| 
* Red Hat Enterprise Linux：7.6、7.7、7.8、7.9、8.1、 8.2、8.3
* CentOS ： 7.6 、 7.7 、 7.8 、 7.9




 a| 
1/2
 a| 
* Red Hat Enterprise Linux：7.6、7.7、7.8、8.1
* CentOS ： 7.6 、 7.7 、 7.8


|===

NOTE: カーネルのバージョンがオペレーティングシステムのバージョンと一致している必要があります。

* 64 ビットの物理インストールまたは仮想マシン
* 8GB の RAM
* 1 GBのディスクスペース（アプリケーションのインストール、サーバログ、およびデータベースに使用）
* ユーザ：ルートアクセス


カーネル以外のライブラリパッケージは安全に更新できますが、ONTAP メディエーターアプリケーション内で有効にするにはリブートが必要になる場合があります。  再起動が必要な場合は、サービスウィンドウを使用することをお勧めします。

をインストールした場合 `yum-utils` パッケージの場合は、を使用できます `needs-restarting` コマンドを実行します

カーネルコアは、ONTAP メディエーターのバージョンマトリックスでサポートされているバージョンに更新することができます。再起動は必須であるため、サービスウィンドウが必要です。

リブートの前にSCSTカーネルモジュールをアンインストールし、リブート後に再インストールする必要があります。


NOTE: 特定のONTAPメディエーターリリースでは、サポートされているOSリリース以降のカーネルにアップグレードすることはできません。(これは、テストしたSCSTモジュールがコンパイルされないことを示している可能性があります)。



== UEFIセキュアブートが有効になっている場合のセキュリティキーの登録

UEFIセキュアブートが有効になっている場合、ONTAPメディエーターをインストールするには、ONTAPメディエーターサービスを開始する前にセキュリティキーを登録する必要があります。システムがUEFI対応で、セキュアブートがオンになっているかどうかを確認するには、次の手順に従います。

.手順
. mokutilがインストールされていない場合は、次のコマンドを実行します。
+
`yum install mokutil`

. システムでUEFIセキュアブートが有効になっているかどうかを確認するには、次のコマンドを実行します。
+
`mokutil --sb-state`

+
結果は、このシステムでUEFIセキュアブートが有効になっているかどうかを示します。

+

NOTE: ONTAPメディエーター1.2.0以前のバージョンでは、このモードはサポートされていません。





== UEFIセキュアブートを無効にする

ONTAPメディエーターをインストールする前に、UEFIセキュアブートを無効にすることもできます。

.手順
. 物理マシンのBIOS設定で、「UEFIセキュアブート」オプションを無効にします。
. VMのVMware設定で、vSphere 6.xの場合は[Safe Start]オプション、vSphere 7.xの場合は[Secure Boot]オプションを無効にします。

