---
sidebar: sidebar 
permalink: ontap-security-hardening/lif-security.html 
keywords: tr-4569, ontap hardening guide, Data LIF, Cluster LIF, Node management LIF, Cluster management LIF, Intercluster LIF, requires private IP subnet, requires secure network, default firewall policy, is the firewall customizable, under no circumstance should any LIF roles be exposed to the internet 
summary: 各LIFロールのセキュリティ特性を理解します。 
---
= LIF セキュリティ
:hardbreaks:
:allow-uri-read: 
:icons: font
:linkattrs: 
:imagesdir: ../media


[role="lead"]
LIFは、ロール、ホームポート、ホームノード、フェイルオーバー先のポートのリスト、ファイアウォールポリシーなどの特性が関連付けられているIPアドレスまたはWorld Wide Port Name（WWPN）です。LIFは、クラスタでネットワーク経由の通信の送受信に使用するポートに設定できます。LIFの各ロールのセキュリティ特性を理解することが重要です。



== LIFロール

LIFのロールは次のとおりです。

* *データLIF *：SVMに関連付けられ、クライアントとの通信に使用されるLIFです。
* *クラスタLIF *：クラスタ内のノード間のトラフィックの伝送に使用されるLIFです。
* *ノード管理LIF *：クラスタ内の特定のノードを管理するための専用IPアドレスを提供するLIFです。
* *クラスタ管理LIF *：クラスタ全体に対して単一の管理インターフェイスを提供するLIFです。
* *クラスタ間LIF *：クラスタ間の通信、バックアップ、およびレプリケーションに使用されるLIFです。




== 各LIFロールのセキュリティ特性

[cols="21%,13%,14%,18%,18%,16%"]
|===
|  | データ LIF | クラスタ LIF | ノード管理 LIF | クラスタ管理LIF | クラスタ間 LIF 


| プライベートIPサブネットが必要 | いいえ | はい。 | いいえ | いいえ | いいえ 


| セキュアなネットワークが必要 | いいえ | はい。 | いいえ | いいえ | はい。 


| デフォルトのファイアウォールポリシー | 非常に厳しい | 完全にオープン | 中 | 中 | 非常に厳しい 


| ファイアウォールをカスタマイズ可能 | はい。 | いいえ | はい。 | はい。 | はい。 
|===
[IMPORTANT]
====
* クラスタLIFは完全にオープンで設定可能なファイアウォール ポリシーがないため、分離されたセキュアなネットワークのプライベートIPサブネットに配置する必要があります。
* どのような状況下でも、LIFのロールをインターネットに公開しないでください。


====
LIFの保護の詳細については、を参照して link:../networking/configure_firewall_policies_for_lifs.html["LIF のファイアウォールポリシーを設定します"]ください。
