---
permalink: update/index.html 
sidebar: sidebar 
keywords: ontap, upgrade, update, automatic, automated, firmware, bmc, sp, system, timezone database, timezone 
summary: ONTAPのバージョンによっては、自動ファームウェアおよびシステム更新を有効にすることができます。 
---
= ファームウェアとシステムの更新の概要
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
ONTAPのバージョンによっては、自動ファームウェアおよびシステム更新を有効にすることができます。

[cols="25,75"]
|===
| ONTAPバージョン | ジドウコウシンノナイヨウ 


| 9.13.1以降  a| 
* ONTAPタイムゾーンデータベース
* ストレージデバイス、ディスク、およびディスクシェルフのストレージファームウェア
* サービスプロセッサおよびBMCモジュール用のSP / BMCファームウェア




| 9.10.1以降  a| 
* ストレージデバイス、ディスク、およびディスクシェルフのストレージファームウェア
* サービスプロセッサおよびBMCモジュール用のSP / BMCファームウェア




| 9.9.1以前 | サポート対象外 
|===
ONTAP 9 9.1以前を実行している場合、またはを有効にしていない場合link:enable-automatic-updates-task.html["システムの自動更新"]は実行できますlink:firmware-task.html["ファームウェアを手動で更新します"]。

ONTAP 9 12.1以前を実行している場合、またはを有効にしていない場合はlink:enable-automatic-updates-task.html["システムの自動更新"]、タイムゾーンデータベースを手動で更新できます。link:https://kb.netapp.com/Advice_and_Troubleshooting/Data_Storage_Software/ONTAP_OS/How_to_update_time_zone_information_in_ONTAP_9["ONTAP 9でタイムゾーン情報を更新する方法"^]詳細については、ナレッジベースの記事を参照してください。



== ビデオ:自動ファームウェアアップデート機能

ONTAP 9 10.1以降で利用可能なファームウェアの自動更新機能を確認してください。

video::GoABILT85hQ[youtube,width=848,height=480]