---
permalink: update/pre-stage-system-firmware.html 
sidebar: sidebar 
keywords: ontap, upgrade, andu, bios, loader, firmware, pre-stage, single reboot, slipstream, system firmware, boot media, cluster image update 
summary: ONTAP 9.17.1以降では、ONTAPのアップグレード前に新しいBIOSまたはLOADERファームウェアをノードに事前にステージングすることで、両方のアップデートを1回の再起動サイクルで完了させることができます。 
---
= ONTAPソフトウェアのアップグレード前にシステムファームウェアを事前ステージングする
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
ONTAP 9.17.1 以降、自動無停止アップグレード（ANDU）を実行する前に、ノードのブートデバイスに新しい BIOS または LOADER ファームウェアが既に存在する場合、アップグレードプロセスは、ONTAP イメージにバンドルされているバージョンで上書きするのではなく、新しいファームウェアを保持します。これにより、ONTAP ソフトウェアのアップグレードとファームウェアのアップデートを、1 回の再起動サイクルで完了できます。

ONTAP 9.16.1以前のバージョンでは、ANDUは常にターゲットのONTAPイメージにバンドルされているBIOSとLOADERファームウェアをインストールします。これは、ブートデバイスに既にインストールされているファームウェアのバージョンに関係なく適用されます。新しいBIOSまたはLOADERサービスイメージが個別にダウンロードされている場合は、新しいファームウェアを有効にするために、ONTAPアップグレード後に別途テイクオーバーとギブバックのサイクルを実行する必要があります。

ONTAP 9.17.1 以降、ONTAP は各ノードのブートデバイス上の BIOS および LOADER ファームウェアのバージョンを、ターゲット ONTAP イメージにバンドルされているバージョンと比較します。ブートデバイスにバンドルされているバージョンよりも新しいファームウェアが既に含まれている場合、バンドルされているファームウェアはインストールされません。既存の新しいファームウェアは保持されます。バンドルされているバージョンがブートデバイス上のバージョンと同等かそれ以上である場合、バンドルされているファームウェアがインストールされます。

通常の ANDU ワークフローの一部としてノードが再起動すると、ブートデバイス上のファームウェアがアクティブ化され、ONTAP のアップグレードとファームウェアのアップデートが1回の再起動で完了します。

.開始する前に
* クラスタのすべてのノードでONTAP 9.17.1以降が実行されている必要があります。
* 新しいBIOSまたはLOADERサービスイメージをlink:https://mysupport.netapp.com/site/downloads/firmware/system-firmware-diagnostics["NetAppサポート サイト"^]からダウンロードしておく必要があります。
+
ノードのブートデバイスにファームウェアをダウンロードするには、高度な権限レベルが必要です。



.手順
. 権限レベルをadvancedに設定します。
+
[source, cli]
----
set -privilege advanced
----
. 各ノードのブートデバイスに新しいサービスイメージをダウンロードします。
+
[source, cli]
----
system node firmware download -node <node_name> -package
----
+
新しいファームウェアを受信する必要のあるクラスター内の各ノードに対して、この手順を繰り返してください。

. 管理者権限に戻る：
+
[source, cli]
----
set -privilege admin
----
. 各ノードのブートデバイスに現在インストールされているファームウェアのバージョンを確認します。
+
[source, cli]
----
system node firmware bootmedia show
----
+
事前にステージングされたファームウェアのバージョンは、ターゲット ONTAP イメージにバンドルされているバージョンよりも新しい必要があります。



.次の手順
* ファームウェアを事前にステージングしたら、link:../upgrade/automated-upgrade-task.html["自動 ONTAP アップグレードを実行する"]する準備が整います。
+
アップグレード中、ONTAP はブートデバイスに既により新しい BIOS および LOADER ファームウェアが含まれていることを検出し、それを保持します。同梱されているファームウェアは、既に上位バージョンがインストールされているノードにはインストールされません。


