---
sidebar: sidebar 
permalink: data-protection/cloud-backup-using-cbs-task.html 
keywords: cloud, data, backup, back up, storage, volume, lun, connector, secret key, access key, bluexp back and recovery service, Cloud Backup service, CBS, restore data, protect volumes, ipspace, storagegrid, storage grid, archive, archival, archiving, cost, calculator, glacier, deep archive 
summary: ONTAP 9.19.1以降、System ManagerではNetApp Backup and Recoveryサービスを使用したクラウドでのデータのバックアップがサポートされなくなりました。代わりに、NetApp Consoleを使用してNetApp Backup and Recoveryサービスを設定し、クラウドデスティネーションへのSnapMirror関係を作成する必要があります。 
---
= NetApp Backup and Recoveryを使用してデータをバックアップする
:hardbreaks:
:toclevels: 1
:allow-uri-read: 
:toclevels: 1
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
ONTAP 9.19.1以降、System ManagerではNetApp Backup and Recoveryサービスを使用したクラウドでのデータのバックアップがサポートされなくなりました。代わりに、NetApp Consoleを使用してNetApp Backup and Recoveryサービスを設定し、クラウドデスティネーションへのSnapMirror関係を作成する必要があります。

バックアップとリカバリはFlexVol読み取り/書き込みボリュームとデータ保護（DP）ボリュームをサポートします。ONTAP 9.12.1以降では、バックアップとリカバリはFlexGroupボリュームとSnapLockボリュームをサポートします。

link:https://docs.netapp.com/us-en/data-services-backup-recovery/index.html["NetApp Backup and Recovery"^]についての詳細をご覧ください。

.開始する前に
NetApp Consoleでアカウントを作成するには、次の手順を実行してください。サービスアカウントの場合、ロールを「Account Admin」として作成する必要があります。

. link:https://docs.netapp.com/us-en/console-setup-admin/task-logging-in.html["NetApp Consoleでアカウントを作成する"^]。
. link:https://docs.netapp.com/us-en/console-setup-admin/concept-connectors.html["NetApp ConsoleでConsoleエージェントを作成する"^]次のいずれかのクラウド プロバイダを使用：
+
** Microsoft Azure
** Amazon Web Services（AWS）
** Google Cloud Platform（GCP）
** StorageGRID（ONTAP 9.10.1）
+

NOTE: ONTAP 9.10.1以降では、StorageGRIDをクラウドバックアッププロバイダーとして選択できますが、NetApp Consoleがオンプレミスで導入されている場合に限ります。Consoleエージェントはオンプレミスにインストールされ、NetApp ConsoleのSoftware-as-a-Service（SaaS）アプリケーションから利用できる必要があります。



. link:https://docs.netapp.com/us-en/data-services-backup-recovery/concept-backup-to-cloud.html["NetApp ConsoleでNetApp Backup and Recoveryを購読する"^]（適切なライセンスが必要です）。
. link:https://docs.netapp.com/us-en/console-setup-admin/concept-identity-and-access-management.html["NetApp Consoleを使用してアクセスキーとシークレットキーを生成する"^]。




== NetApp ConsoleとNetApp Backup and Recoveryを使用してONTAPバックアップを管理

ONTAP 9.19.1以降、System ManagerはNetApp Backup and Recoveryをサポートしなくなりました。NetApp Backup and RecoveryをNetApp Consoleで使用する方法の詳細については、link:https://docs.netapp.com/us-en/data-services-backup-recovery/prev-ontap-backup-manage.html["NetApp Backup and Recoveryを使用してONTAPシステムのバックアップを管理"^]を参照してください。



== バックアップ ファイルからのデータのリストア

データの復元、リレーションシップの更新、リレーションシップの削除などのバックアップ管理操作は、NetApp Consoleを使用している場合にのみ実行できます。詳細については、link:https://docs.netapp.com/us-en/data-services-backup-recovery/prev-ontap-backup-manage.html["バックアップファイルからデータを復元する"^]を参照してください。
