---
permalink: data-protection/create-load-sharing-mirror-task.html 
sidebar: sidebar 
keywords: create, initialize, load-sharing, mirror, relationship 
summary: クラスタ内のそれぞれのルートボリュームについて、 Load-Sharing Mirror （ LSM ；負荷共有ミラー）を作成する必要があります。LSM は、ルートボリュームを含むノード（ HA ペアのパートナーノードなど）以外のノード、またはできれば別の HA ペア内のノードに作成できます。2 ノードクラスタの場合は、ルートボリュームがあるノードのパートナーに LSM を作成する必要があります。 
---
= 負荷共有ミラー関係を作成して初期化
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
クラスタ内の NAS データを提供する各 SVM ルートボリュームについて、負荷共有ミラー（ LSM ）を作成する必要があります。LSM は、ルートボリュームを含むノード（ HA ペアのパートナーノードなど）以外のノード、またはできれば別の HA ペア内のノードに作成できます。

LSMは単一のHAクラスタには適していません。複数のHAペアクラスタに対して設定し、ルートボリュームを含むノードと別のHAペアの別のノードの間でLSMを設定する必要があります。

.このタスクについて
同じノードで LSM を作成した場合は、ノードが使用できなくなると単一点障害が発生します。クライアントから引き続きデータにアクセスできるようにするためのコピーをもう 1 つ作成する必要はありません。ただし、ルートボリュームを含むノード以外のノードや別の HA ペアに LSM を作成しても、停止してもデータにアクセスできます。

たとえば、 4 ノードクラスタの 3 つのノードにルートボリュームがある場合、次のようになります。

* HA 1 のノード 1 のルートボリュームについて、 HA 2 のノード 1 または HA 2 のノード 2 に LSM を作成します。
* HA 1 のノード 2 のルートボリュームについて、 HA 2 のノード 1 または HA 2 のノード 2 に LSM を作成します。
* HA 2 のノード 1 のルートボリュームについて、 HA 1 のノード 1 または HA 1 のノード 2 に LSM を作成します。


.手順
. LSM のデスティネーションボリュームを作成します。
+
`volume create -vserver _SVM_ -volume volume -aggregate _aggregate_ -type DP -size size`

+
デスティネーションボリュームのサイズは、ルートボリュームと同じかそれ以上である必要があります。

+
ルートボリュームとデスティネーションボリュームの名前にサフィックス（など）を付けることを推奨します `_root` および `_m1`。

+
コマンド構文全体については、マニュアルページを参照してください。

+
次の例は、ルートボリューム用の負荷共有ミラーボリュームを作成します `svm1_root` インチ `cluster_src`：

+
[listing]
----
cluster_src:> volume create -vserver svm1 -volume svm1_m1 -aggregate aggr_1 -size 1gb -state online -type DP
----
. の説明に従って、レプリケーションジョブスケジュールを作成します link:create-replication-job-schedule-task.html["レプリケーションジョブスケジュールを作成します"]。
. SVM ルートボリュームと LSM のデスティネーションボリュームの間に負荷共有ミラー関係を作成します。
+
`snapmirror create -source-path _SVM:volume_|_cluster://SVM/volume_ -destination-path _SVM:volume_|_cluster://SVM/volume_ -type LS -schedule _schedule_`

+
コマンド構文全体については、マニュアルページを参照してください。

+
次の例は、ルートボリューム間に負荷共有ミラー関係を作成します `svm1_root` および負荷共有ミラーボリューム `svm1_m1`：

+
[listing]
----
cluster_src::> snapmirror create -source-path svm1:svm1_root -destination-path svm1:svm1_m1 -type LS -schedule hourly
----
+
負荷共有ミラーのtype属性がから変更されます `DP` 終了： `LS`。

. 負荷共有ミラーを初期化します。
+
`snapmirror initialize-ls-set -source-path _SVM:volume_|_cluster://SVM/volume_`

+
初期化には時間がかかる場合があります。ベースライン転送はオフピークの時間帯に実行することを推奨します。

+
コマンド構文全体については、マニュアルページを参照してください。

+
次の例は、ルートボリュームの負荷共有ミラーを初期化します `svm1_root`：

+
[listing]
----
cluster_src::> snapmirror initialize-ls-set -source-path svm1:svm1_root
----

