---
permalink: data-protection/create-custom-replication-policy-concept.html 
sidebar: sidebar 
keywords: create, custom, replication, policy 
summary: 関係のデフォルトポリシーが適切でない場合は、カスタムレプリケーションポリシーを作成できます。たとえば、ネットワーク転送時にデータを圧縮したり、 Snapshot コピーを転送するための SnapMirror の試行回数を変更したりできます。 
---
= カスタムレプリケーションポリシーを作成する
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
関係のデフォルトポリシーが適切でない場合は、カスタムレプリケーションポリシーを作成できます。たとえば、ネットワーク転送時にデータを圧縮したり、 Snapshot コピーを転送するための SnapMirror の試行回数を変更したりできます。

レプリケーション関係の作成時には、デフォルトまたはカスタムのポリシーを使用できます。カスタムアーカイブ（旧 SnapVault ）またはユニファイドレプリケーションポリシーの場合は、初期化と更新の際に転送する Snapshot コピーを決定する 1 つ以上の _ rules_ を定義する必要があります。また、デスティネーションでローカル Snapshot コピーを作成するスケジュールを定義することもできます。

レプリケーションポリシーの _policy type_of によって、サポートされる関係のタイプが決まります。次の表は、使用可能なポリシータイプを示しています。

[cols="2*"]
|===


| ポリシータイプ | 関係タイプ 


 a| 
非同期ミラー
 a| 
SnapMirror DR



 a| 
バックアップ
 a| 
SnapVault



 a| 
ミラー - バックアップ
 a| 
ユニファイドレプリケーション



 a| 
strict-sync-mirror のようになります
 a| 
StrictSync モードの SnapMirror Synchronous （ ONTAP 9.5 以降でサポート）



 a| 
SyncMirror
 a| 
Sync モードの SnapMirror Synchronous （ ONTAP 9.5 以降でサポート）

|===
[TIP]
====
カスタムレプリケーションポリシーを作成する場合は、デフォルトポリシーをモデルとすることを推奨します。

====
.ステップ
. カスタムレプリケーションポリシーを作成します。
+
`snapmirror policy create -vserver _SVM_ -policy _policy_ -type async-mirror|vault|mirror-vault|strict-sync-mirror|sync-mirror -comment _comment_ -tries _transfer_tries_ -transfer-priority low|normal -is-network-compression-enabled true|false`

+
コマンド構文全体については、マニュアルページを参照してください。

+
ONTAP 9.5以降では、を使用して、SnapMirror Synchronous関係の共通のSnapshotコピースケジュールを作成するスケジュールを指定できます `-common-snapshot-schedule` パラメータデフォルトでは、 SnapMirror Synchronous 関係の共通の Snapshot コピースケジュールは 1 時間です。SnapMirror Synchronous 関係の Snapshot コピースケジュールの値は、 30 分から 2 時間までの範囲で指定できます。

+
次の例は、データ転送のためにネットワーク圧縮を有効にする、 SnapMirror DR 用のカスタムレプリケーションポリシーを作成します。

+
[listing]
----
cluster_dst::> snapmirror policy create -vserver svm1 -policy DR_compressed -type async-mirror -comment “DR with network compression enabled” -is-network-compression-enabled true
----
+
次の例は、 SnapVault 用のカスタムレプリケーションポリシーを作成します。

+
[listing]
----
cluster_dst::> snapmirror policy create -vserver svm1 -policy my_snapvault -type vault
----
+
次の例は、ユニファイドレプリケーション用のカスタムレプリケーションポリシーを作成します。

+
[listing]
----
cluster_dst::> snapmirror policy create -vserver svm1 -policy my_unified -type mirror-vault
----
+
次の例は、 StrictSync モードの SnapMirror Synchronous 関係用のカスタムレプリケーションポリシーを作成します。

+
[listing]
----
cluster_dst::> snapmirror policy create -vserver svm1 -policy my_strictsync -type strict-sync-mirror -common-snapshot-schedule my_sync_schedule
----


.完了後
「 vault 」および「 `m mirror vault 」ポリシータイプの場合は、初期化および更新時に転送する Snapshot コピーを決定するルールを定義する必要があります。

を使用します `snapmirror policy show` SnapMirrorポリシーが作成されたことを確認するコマンド。コマンド構文全体については、マニュアルページを参照してください。
