---
permalink: data-protection/create-snapshot-policy-task.html 
sidebar: sidebar 
keywords: create, snapshot, policy 
summary: Snapshot ポリシーは、 Snapshot コピーを作成するタイミング、保持するコピーの数、および Snapshot コピーに名前を付ける方法を指定します。たとえば、毎日午前 12 時 10 分に 1 つの Snapshot コピーを作成し、直近の 2 つのコピーを保持して、「 daily. timestamp 」という名前を付けることができます。 Snapshot ポリシーには最大 5 つのジョブスケジュールを含めることができます。 
---
= Snapshot ポリシーを作成します
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Snapshot ポリシーは、 Snapshot コピーを作成するタイミング、保持するコピーの数、および Snapshot コピーに名前を付ける方法を指定します。たとえば、毎日午前12時10分に1つのSnapshotコピーを作成し、最新の2つのコピーを保持して、「毎日」という名前を付けることができます.`_timestamp_`.`" Snapshotポリシーには最大5つのジョブスケジュールを含めることができます。

.このタスクについて
デフォルトでは、 ONTAP が Snapshot コピーの名前を作成する際には、ジョブスケジュール名にタイムスタンプを追加します。

[listing]
----
daily.2017-05-14_0013/              hourly.2017-05-15_1106/
daily.2017-05-15_0012/              hourly.2017-05-15_1206/
hourly.2017-05-15_1006/             hourly.2017-05-15_1306/
----
必要に応じて、プレフィックスをジョブスケジュール名に置き換えることができます。

。 `snapmirror-label` オプションはSnapMirrorレプリケーション用です。詳細については、を参照してください link:define-rule-policy-task.html["ポリシーのルールを定義する"]。

.ステップ
. Snapshot ポリシーを作成します
+
`volume snapshot policy create -vserver _SVM_ -policy _policy_name_ -enabled true|false -schedule1 _schedule1_name_ -count1 _copies_to_retain_ -prefix1 _snapshot_prefix_ -snapmirror-label1 _snapshot_label_ ... -schedule1 _schedule5_name_ -count5 _copies_to_retain_-prefix5 _snapshot_prefix_ -snapmirror-label5 _snapshot_label_`

+
次の例は、という名前のSnapshotポリシーを作成します `snap_policy_daily` これはAで実行されます `daily` スケジュール：このポリシーには最大5つのSnapshotコピーが含まれ、それぞれにという名前が付けられます `daily`.`_timestamp_` およびSnapMirrorラベル `daily`：

+
[listing]
----
cluster1::> volume snapshot policy create -vserver vs0 -policy snap_policy_daily -schedule1 daily -count1 5 -snapmirror-label1 daily
----

