---
permalink: data-protection/define-rule-policy-task.html 
sidebar: sidebar 
keywords: define, rule, policy, data protection 
summary: 「vault」または「mirror-vault」ポリシー タイプのカスタム ポリシーでは、初期化および更新時に転送するスナップショットを決定するルールを少なくとも1つ定義する必要があります。また、「vault」または「mirror-vault」ポリシー タイプのデフォルト ポリシーにもルールを定義することができます。 
---
= ONTAP SnapMirrorポリシーのルールを定義する
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
 `vault`または `mirror-vault`ポリシー タイプのカスタム ポリシーでは、初期化および更新時に転送されるスナップショットを決定するルールを少なくとも1つ定義する必要があります。 `vault`または `mirror-vault`ポリシー タイプのデフォルト ポリシーにもルールを定義できます。

.タスク概要
 `vault`または `mirror-vault`ポリシー タイプを持つすべてのポリシーには、レプリケートするSnapshotを指定するルールが必要です。たとえば、ルール `bi-monthly`は、SnapMirrorラベル `bi-monthly`が割り当てられたSnapshotのみをレプリケートすることを示します。SnapMirrorラベルは、ソースでSnapshotポリシーを設定するときに指定します。

各ポリシー タイプは、システム定義の1つ以上のルールに関連付けられています。これらのルールは、ポリシー タイプの指定時にポリシーに自動的に割り当てられます。次の表は、システム定義のルールを示しています。

[cols="3*"]
|===


| システム定義のルール | ポリシー タイプで使用 | 結果 


 a| 
sm_created
 a| 
async-mirror、mirror-vault、Sync、StrictSync
 a| 
SnapMirrorによって作成されたスナップショットは、初期化および更新時に転送されます。



 a| 
all_source_snapshots
 a| 
async-mirror
 a| 
ソース上の新しいスナップショットは、初期化および更新時に転送されます。



 a| 
daily
 a| 
vault、mirror-vault
 a| 
SnapMirrorラベルの付いたソース上の新しいスナップショット `daily`は、初期化および更新時に転送されます。



 a| 
weekly
 a| 
vault、mirror-vault
 a| 
SnapMirrorラベルの付いたソース上の新しいスナップショット `weekly`は、初期化および更新時に転送されます。



 a| 
monthly
 a| 
mirror-vault
 a| 
SnapMirrorラベルの付いたソース上の新しいスナップショット `monthly`は、初期化および更新時に転送されます。



 a| 
app_consistent
 a| 
Sync、StrictSync
 a| 
SnapMirrorラベル `app_consistent`が付いたソース上のスナップショットは、同期的にデスティネーションに複製されます。ONTAP 9.7以降でサポートされます。

|===
「`async-mirror`」ポリシータイプを除き、必要に応じて、デフォルトポリシーまたはカスタムポリシーに追加のルールを指定できます。例：

* デフォルト `MirrorAndVault`ポリシーの場合、 `bi-monthly`というルールを作成して、ソース上のスナップショットを `bi-monthly` SnapMirrorラベルと一致させることができます。
*  `mirror-vault`ポリシー タイプのカスタム ポリシーの場合、 `bi-weekly` SnapMirrorラベルを持つソース上のスナップショットと一致させる `bi-weekly`というルールを作成できます。


.手順
. ポリシーのルールを定義します。
+
`snapmirror policy add-rule -vserver _SVM_ -policy _policy_for_rule_ -snapmirror-label _snapmirror-label_ -keep _retention_count_`

+
次の例では、SnapMirrorラベル `bi-monthly`付きのルールをデフォルト `MirrorAndVault`ポリシーに追加します：

+
[listing]
----
cluster_dst::> snapmirror policy add-rule -vserver svm1 -policy MirrorAndVault -snapmirror-label bi-monthly -keep 6
----
+
次の例では、SnapMirrorラベル `bi-weekly`を持つルールをカスタム `my_snapvault`ポリシーに追加します：

+
[listing]
----
cluster_dst::> snapmirror policy add-rule -vserver svm1 -policy my_snapvault -snapmirror-label bi-weekly -keep 26
----
+
次の例では、SnapMirrorラベル `app_consistent`を持つルールをカスタム `Sync`ポリシーに追加します：

+
[listing]
----
cluster_dst::> snapmirror policy add-rule -vserver svm1 -policy Sync -snapmirror-label app_consistent -keep 1
----
+
 `snapmirror policy add-rule`の詳細については、link:https://docs.netapp.com/us-en/ontap-cli/snapmirror-policy-add-rule.html["ONTAPコマンド リファレンス"^]をご覧ください。

+
次に、このSnapMirrorラベルに一致するソース クラスタからスナップショットを複製できます：

+
[listing]
----
cluster_src::> snapshot create -vserver vs1 -volume vol1 -snapshot snapshot1 -snapmirror-label app_consistent
----

