---
permalink: data-protection/define-schedule-create-local-copy-destination-task.html 
sidebar: sidebar 
keywords: define, schedule, create, local copy, destination 
summary: SnapVault 関係とユニファイドレプリケーション関係の場合は、最後に転送された Snapshot コピーのコピーをデスティネーションで作成することによって、更新した Snapshot コピーが破損する可能性を防ぐことができます。この「ローカルコピー」はソース上の保持ルールに関係なく保持されるため、元は SnapMirror によって転送された Snapshot がソースで使用できなくなった場合でも、そのコピーをデスティネーションで使用できます。 
---
= デスティネーションでローカルコピーを作成するスケジュールを定義します
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
SnapVault 関係とユニファイドレプリケーション関係の場合は、最後に転送された Snapshot コピーのコピーをデスティネーションで作成することによって、更新した Snapshot コピーが破損する可能性を防ぐことができます。この「ローカル・コピー」はソース上の保持ルールに関係なく保持されるため、元は SnapMirror によって転送された Snapshot がソースで使用できなくなった場合でも、そのコピーをデスティネーションで使用できます。

ローカル・コピーを作成するスケジュールは 'snapmirror policy add-rule コマンドの -schedule オプションで指定します

.ステップ
. デスティネーションでローカルコピーを作成するスケジュールを定義します。
+
「 napmirror policy add-rule - vserver_svm_policy_policy_policy_on_rule_snapmirror-label_label_label_schedule_` 」を指定します

+
コマンド構文全体については、マニュアルページを参照してください。ジョブスケジュールの作成方法の例については、を参照してください link:create-replication-job-schedule-task.html["レプリケーションジョブスケジュールを作成します"]。

+
次の例では、ローカルコピーを作成するスケジュールをデフォルトの「 M irrorborts 」ポリシーに追加します。

+
[listing]
----
cluster_dst::> snapmirror policy add-rule -vserver svm1 -policy MirrorAndVault -snapmirror-label my_monthly -schedule my_monthly
----
+
次の例では、ローカルコピーを作成するスケジュールをカスタムの「 y_unified 」ポリシーに追加します。

+
[listing]
----
cluster_dst::> snapmirror policy add-rule -vserver svm1 -policy my_unified -snapmirror-label my_monthly -schedule my_monthly
----

