---
permalink: data-protection/dpo-systems-feature-enhancements-reference.html 
sidebar: sidebar 
keywords: dpo, systems, feature, enhancements, snapmirror, dp optimized, optimised, backoff, back off, deduplication, deduplicate, snapshot blocks, donors, compact, flexvol, license 
summary: ONTAP 9.6以降では、DP_Optimized（DPO）ライセンスをインストールすると、サポートされるFlexVolの最大数が増加します。ONTAP 9.4以降では、DPOライセンスのあるシステムでSnapMirrorバックオフ、ボリューム間のバックグラウンド重複排除、ドナーとしてのSnapshotブロックの使用、およびコンパクションがサポートされます。 
---
= ONTAP DPOシステムの機能拡張
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
ONTAP 9.6以降では、DP_Optimized（DPO）ライセンスをインストールすると、サポートされるFlexVolの最大数が増加します。ONTAP 9.4以降では、DPOライセンスのあるシステムでSnapMirrorバックオフ、ボリューム間のバックグラウンド重複排除、ドナーとしてのSnapshotブロックの使用、およびコンパクションがサポートされます。

ONTAP 9.6 以降では、セカンダリシステムまたはデータ保護システムでサポートされる FlexVol の最大数が増加し、 FlexVol ボリュームをノードあたり最大 2 、 500 個まで、フェイルオーバーモードでは最大 5 、 000 個まで拡張できるようになりました。FlexVolボリュームの増加はで有効になりますlink:../data-protection/snapmirror-licensing-concept.html#data-protection-optimized-license["DP_Optimized（DPO）ライセンス"]。ソースノードとデスティネーションノードの両方には引き続きがlink:../system-admin/manage-license-task.html#view-details-about-a-license["SnapMirrorライセンス"]必要です。

DPO .4以降では、ONTAP 9システムの次の機能拡張が行われています。

* SnapMirror バックオフ： DPO システムでは、レプリケーショントラフィックにクライアントのワークロードと同じ優先度が与えられます。
+
SnapMirrorバックオフは、DPOシステムではデフォルトで無効になっています。

* ボリュームのバックグラウンド重複排除とボリューム間のバックグラウンド重複排除： DPO システムでは、ボリュームのバックグラウンド重複排除とボリューム間のバックグラウンド重複排除が有効になります。
+
既存データを重複排除するには、コマンドを実行し `storage aggregate efficiency cross-volume-dedupe start -aggregate _aggregate_name_ -scan-old-data true`ます。パフォーマンスへの影響を少なくするために、このコマンドはピーク時を避けて実行することを推奨します。

+
の詳細については `storage aggregate efficiency cross-volume-dedupe start`、をlink:https://docs.netapp.com/us-en/ontap-cli/storage-aggregate-efficiency-cross-volume-dedupe-start.html["ONTAPコマンド リファレンス"^]参照してください。

* Snapshotブロックをドナーとして使用することによる削減効果：アクティブなファイルシステムでは使用できないがSnapshotに含まれているデータブロックは、ボリューム重複排除のドナーとして使用されます。
+
Snapshotにトラップされたデータと新しいデータを重複排除することができるため、Snapshotブロックを効率的に共有することもできます。ドナースペースを増やすと、特にボリュームに多数のSnapshotがある場合は、削減効果が高まります。

* コンパクション： DPO システムでは、データコンパクションはデフォルトで有効になります。

