---
permalink: data-protection/long-term-retention-snapshots-concept.html 
sidebar: sidebar 
keywords: local, snapshot, retention, snapmirror, vault 
summary: vaultまたはmirror-vaultポリシータイプを使用して、SnapMirror関係のセカンダリ ボリューム上に長期保存スナップショットを直接作成できます。これらのスナップショットは、バックアップとしてデスティネーションに保持されます。 
---
= ONTAP長期保存スナップショットについて学ぶ
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
SnapMirrorポリシータイプが「vault」または「mirror-vault」である関係では、SnapMirror関係のセカンダリ ボリュームに直接スナップショットを作成できます。これらのスナップショットは、バックアップとしてデスティネーションに保持されます。これらのスナップショットは長期保存を目的として作成されることが多く、長期保存スナップショットと呼ばれます。

長期保存スナップショットを作成するには、SnapMirrorポリシー ルールでスナップショット作成スケジュール、スナップショット名のプレフィックス、SnapMirrorラベル、および保存回数を指定します。このスナップショットは、ソースの保存ルールに関係なく、SnapMirrorデスティネーション ボリュームに保持されます。

長期保存SnapshotはFlexVol SnapMirror構成に対してのみ使用できます。FlexGroup SnapMirror構成に対して長期保存Snapshotを作成することはできません。

SnapMirrorカスケード関係では、長期保存Snapshotはカスケードの最後のボリュームにのみ作成できます。



== 関連情報

* link:supported-deployment-config-concept.html#how-cascade-deployments-work["カスケード展開の仕組みについて学ぶ"]
* link:define-schedule-create-local-copy-destination-task.html["ONTAP SnapMirrorスケジュールを定義して、デスティネーションにローカル コピーを作成します"]

