---
permalink: data-protection/manage-storage-efficiency-task.html 
sidebar: sidebar 
keywords: manage, storage, efficiency, snapmirror, snap mirror, compression, compress, postporcess, update relationship, volume 
summary: SnapMirror は、ソースボリュームとデスティネーションボリュームでストレージ効率を維持します。ただし、例外が 1 つあり、デスティネーションでポストプロセスデータ圧縮が有効になっている場合、ストレージ効率は維持されません。その場合、デスティネーションではすべてのストレージ効率が失われます。この問題を修正するには、デスティネーションでポストプロセス圧縮を無効にして、関係を手動で更新し、 Storage Efficiency を再度有効にする必要があります。 
---
= ストレージ効率の管理
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
SnapMirror は、ソースボリュームとデスティネーションボリュームでストレージ効率を維持します。ただし、例外が 1 つあり、デスティネーションでポストプロセスデータ圧縮が有効になっている場合、ストレージ効率は維持されません。その場合、デスティネーションではすべてのストレージ効率が失われます。この問題を修正するには、デスティネーションでポストプロセス圧縮を無効にして、関係を手動で更新し、 Storage Efficiency を再度有効にする必要があります。

.必要なもの
* ソースクラスタとデスティネーションクラスタ、および SVM のピア関係が確立されている必要があります。
+
https://docs.netapp.com/us-en/ontap-sm-classic/peering/index.html["クラスタと SVM のピアリング"]

* デスティネーションでポストプロセス圧縮を無効にする必要があります。


.このタスクについて
を使用できます `volume efficiency show` コマンドを使用して、ボリュームで効率化が有効になっているかどうかを確認します。詳細については、マニュアルページを参照してください。

SnapMirror 監査ログを表示し、転送概要を特定することで、 SnapMirror によるストレージ効率化が維持されているかどうかを確認できます。転送概要 が表示されている場合 `transfer_desc=Logical Transfer`SnapMirrorではストレージ効率は維持されません。転送概要 が表示されている場合 `transfer_desc=Logical Transfer with Storage Efficiency`SnapMirrorはストレージ効率を維持します。例：

[listing]
----
Fri May 22 02:13:02 CDT 2020 ScheduledUpdate[May 22 02:12:00]:cc0fbc29-b665-11e5-a626-00a09860c273 Operation-Uuid=39fbcf48-550a-4282-a906-df35632c73a1 Group=none Operation-Cookie=0 action=End source=<sourcepath> destination=<destpath> status=Success bytes_transferred=117080571 network_compression_ratio=1.0:1 transfer_desc=Logical Transfer - Optimized Directory Mode
----
ストレージを使用した論理転送

ONTAP 9.3 以降では、 Storage Efficiency を再度有効にするための手動更新が不要になりました。SnapMirror では、ポストプロセス圧縮が無効になったことを検出すると、スケジュールされた次回の更新時に Storage Efficiency を自動的に再度有効にします。ソースとデスティネーションの両方で ONTAP 9.3 を実行している必要があります。

ONTAP 9.3 以降では、デスティネーションボリュームが書き込み可能になったあとで、 AFF システムが Storage Efficiency の設定を FAS システムとは異なる方法で管理します。

* を使用してデスティネーションボリュームを書き込み可能にしたあと `snapmirror break` コマンドを実行した場合、ボリュームのキャッシングポリシーは自動的に「auto」（デフォルト）に設定されます。
+
[NOTE]
====
この動作は FlexVol ボリュームにのみ該当し、 FlexGroup ボリュームには適用されません。

====
* 再同期時に、キャッシングポリシーは自動的に「 none 」に設定され、重複排除およびインライン圧縮は、元の設定に関係なく自動的に無効になります。必要に応じて、設定を手動で変更する必要があります。


[NOTE]
====
Storage Efficiency が有効な状態での手動更新には時間がかかる場合があります。この処理はオフピークの時間帯に実行することを推奨します。

====
.ステップ
. レプリケーション関係を更新して、 Storage Efficiency を再度有効にします。
+
`snapmirror update -source-path _SVM:volume_|_cluster://SVM/volume_, ... -destination-path _SVM:volume_|_cluster://SVM/volume_, ... -enable-storage-efficiency true`

+
コマンド構文全体については、マニュアルページを参照してください。

+
[NOTE]
====
このコマンドはデスティネーション SVM またはデスティネーションクラスタから実行する必要があります。ソースとデスティネーションに共通の Snapshot コピーが存在しない場合、このコマンドは失敗します。使用 `snapmirror initialize` 関係を再初期化してください。

====
+
次の例は、ソースボリューム間の関係を更新します `volA` オン `svm1` デスティネーションボリュームを指定します `volA_dst` オン `svm_backup`Storage Efficiencyを再度有効にします。

+
[listing]
----
cluster_dst::> snapmirror update -source-path svm1:volA -destination-path svm_backup:volA_dst -enable-storage-efficiency true
----

