---
permalink: data-protection/reactivate-original-source-volume-task.html 
sidebar: sidebar 
keywords: reactivate, original, source, volume 
summary: デスティネーションからデータを提供する必要がなくなった場合は、ソース ボリュームとデスティネーション ボリュームの間で元のデータ保護関係を再確立できます。 
---
= 元のONTAP SnapMirrorソースボリュームを再アクティブ化する
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
デスティネーションからデータを提供する必要がなくなった場合は、ソース ボリュームとデスティネーション ボリュームの間で元のデータ保護関係を再確立できます。

.タスク概要
* 次の手順は、元のソース ボリュームにあるベースラインが損なわれていないことを前提としています。ベースラインが損なわれている場合は、この手順を実行する前に、データの提供元のボリュームと元のソース ボリュームの間の関係を作成して初期化する必要があります。
* XDP SnapMirror関係のバックグラウンドでの準備とデータの保存処理に時間がかかります。長時間にわたってSnapMirror関係のステータスが「preparing」と表示されることも珍しくありません。


.手順
. 元のデータ保護関係を反転します。
+
`snapmirror resync -source-path _SVM:volume_ -destination-path _SVM:volume_`

+
 `snapmirror resync`の詳細については、link:https://docs.netapp.com/us-en/ontap-cli/snapmirror-resync.html["ONTAPコマンド リファレンス"^]を参照してください。

+
[NOTE]
====
このコマンドは、元のソースSVMまたは元のソースクラスタから実行する必要があります。再同期にはベースライン転送は必要ありませんが、時間がかかる場合があります。再同期はオフピーク時に実行することをお勧めします。ソースとデスティネーションに共通のSnapshotが存在しない場合、コマンドは失敗します。 `snapmirror initialize`を使用して関係を再初期化します。 `snapmirror initialize`の詳細については、link:https://docs.netapp.com/us-en/ontap-cli/snapmirror-initialize.html["ONTAPコマンド リファレンス"^]を参照してください。

====
+
次の例では、 `svm1`上の元のソース ボリューム `volA`と、 `svm_backup`上のデータ提供元ボリューム `volA_dst`の関係を反転します：

+
[listing]
----
cluster_src::> snapmirror resync -source-path svm_backup:volA_dst -destination-path svm1:volA
----
. 元のソースへのデータ アクセスを再確立する準備ができたら、元のデスティネーション ボリュームへのアクセスを停止します。その方法の1つが、元のデスティネーションSVMを停止することです。
+
`vserver stop -vserver _SVM_`

+
[NOTE]
====
このコマンドは元のデスティネーションSVMまたは元のデスティネーション クラスタから実行する必要があります。このコマンドは、元のデスティネーションSVM全体へのユーザ アクセスを停止します。他の方法を使用して元のデスティネーション ボリュームへのアクセスを停止することもできます。

====
+
次の例は、元のデスティネーションSVMを停止します。

+
[listing]
----
cluster_dst::> vserver stop svm_backup
----
+
 `vserver stop`の詳細については、link:https://docs.netapp.com/us-en/ontap-cli/vserver-stop.html["ONTAPコマンド リファレンス"^]を参照してください。

. 反転した関係を更新します。
+
`snapmirror update -source-path _SVM:volume_ -destination-path _SVM:volume_`

+
[NOTE]
====
このコマンドは元のソースSVMまたは元のソース クラスタから実行する必要があります。

====
+
次の例では、 `svm_backup`上のデータの提供元ボリューム `volA_dst`と、 `svm1`上の元のソース ボリューム `volA`との関係を更新します：

+
[listing]
----
cluster_src::> snapmirror update -source-path svm_backup:volA_dst -destination-path svm1:volA
----
+
 `snapmirror update`の詳細については、link:https://docs.netapp.com/us-en/ontap-cli/snapmirror-update.html["ONTAPコマンド リファレンス"^]をご覧ください。

. 元のソースSVMまたは元のソース クラスタから、反転した関係のスケジュールされた転送を停止します。
+
`snapmirror quiesce -source-path _SVM:volume_ -destination-path _SVM:volume_`

+
[NOTE]
====
このコマンドは元のソースSVMまたは元のソース クラスタから実行する必要があります。

====
+
次の例では、 `svm_backup`上の元のデスティネーション ボリューム `volA_dst`と `svm1`上の元のソース ボリューム `volA`間のスケジュールされた転送を停止します：

+
[listing]
----
cluster_src::> snapmirror quiesce -source-path svm_backup:volA_dst -destination-path svm1:volA
----
+
 `snapmirror quiesce`の詳細については、link:https://docs.netapp.com/us-en/ontap-cli/snapmirror-quiesce.html["ONTAPコマンド リファレンス"^]を参照してください。

. 最終更新が完了し、関係のステータスが「Quiesced」と表示されたら、元のソース SVM または元のソース クラスタから次のコマンドを実行して、反転された関係を解除します：：
+
`snapmirror break -source-path _SVM:volume_ -destination-path _SVM:volume_`

+
[NOTE]
====
このコマンドは元のソースSVMまたはソース クラスタから実行する必要があります。

====
+
次の例では、 `svm_backup`上の元のデスティネーション ボリューム `volA_dst`と、 `svm1`上の元のソース ボリューム `volA`の関係を解除します：

+
[listing]
----
cluster_scr::> snapmirror break -source-path svm_backup:volA_dst -destination-path svm1:volA
----
+
 `snapmirror break`の詳細については、link:https://docs.netapp.com/us-en/ontap-cli/snapmirror-break.html["ONTAPコマンド リファレンス"^]を参照してください。

. 元のソースSVMまたは元のソース クラスタから、反転したデータ保護関係を削除します。
+
`snapmirror delete -source-path _SVM:volume_ -destination-path _SVM:volume_`

+
[NOTE]
====
このコマンドは元のソースSVMまたは元のソース クラスタから実行する必要があります。

====
+
次の例では、 `svm1`上の元のソース ボリューム `volA`と、 `svm_backup`上のデータ提供元ボリューム `volA_dst`との間の逆の関係を削除します：

+
[listing]
----
cluster_src::> snapmirror delete -source-path svm_backup:volA_dst -destination-path svm1:volA
----
+
 `snapmirror delete`の詳細については、link:https://docs.netapp.com/us-en/ontap-cli/snapmirror-delete.html["ONTAPコマンド リファレンス"^]をご覧ください。

. 元のデスティネーションSVMまたは元のデスティネーション クラスタから反転した関係をリリースします。
+
`snapmirror release -source-path _SVM:volume_ -destination-path _SVM:volume_`

+
[NOTE]
====
このコマンドは元のデスティネーションSVMまたは元のデスティネーション クラスタから実行する必要があります。

====
+
次の例では、 `svm_backup`上の元のデスティネーション ボリューム `volA_dst`と、 `svm1`上の元のソース ボリューム `volA`間の逆の関係を解除します：

+
[listing]
----
cluster_dst::> snapmirror release -source-path svm_backup:volA_dst -destination-path svm1:volA
----
+
 `snapmirror release`の詳細については、link:https://docs.netapp.com/us-en/ontap-cli/snapmirror-release.html["ONTAPコマンド リファレンス"^]を参照してください。

. 元のデスティネーションから元のデータ保護関係を再確立します。
+
`snapmirror resync -source-path _SVM:volume_ -destination-path _SVM:volume_`

+
次の例では、 `svm1`上の元のソース ボリューム `volA`と、 `svm_backup`上の元のデスティネーション ボリューム `volA_dst`との関係を再確立します：

+
[listing]
----
cluster_dst::> snapmirror resync -source-path svm1:volA -destination-path svm_backup:volA_dst
----
+
 `snapmirror resync`の詳細については、link:https://docs.netapp.com/us-en/ontap-cli/snapmirror-resync.html["ONTAPコマンド リファレンス"^]を参照してください。

. 必要に応じて、元のデスティネーションSVMを起動します。
+
`vserver start -vserver _SVM_`

+
次の例は、元のデスティネーションSVMを起動します。

+
[listing]
----
cluster_dst::> vserver start svm_backup
----
+
 `vserver start`の詳細については、link:https://docs.netapp.com/us-en/ontap-cli/vserver-start.html["ONTAPコマンド リファレンス"^]を参照してください。



.終了後の操作
 `snapmirror show`コマンドを使用して、SnapMirror関係が作成されたことを確認します。

 `snapmirror show`の詳細については、link:https://docs.netapp.com/us-en/ontap-cli/snapmirror-show.html["ONTAPコマンド リファレンス"^]を参照してください。
