---
permalink: data-protection/restore-part-file-snapshot-task.html 
sidebar: sidebar 
keywords: restore, part, file, snapshot copy 
summary: データの開始バイトオフセットとバイト数がわかっている場合は、volume snapshot partial-restore-fileコマンドを使用して、一定範囲のデータをSnapshotコピーからLUN、NFSまたはSMBコンテナファイルにリストアできます。このコマンドでは、同じ LUN 内に複数のデータベースを格納するホスト上のいずれかのデータベースをリストアできます。 
---
= Snapshot コピーからファイルの一部をリストアします
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
を使用できます `volume snapshot partial-restore-file` SnapshotコピーからLUN、NFSまたはSMBコンテナファイルに一定の範囲のデータをリストアするコマンド。データの開始バイトオフセットとバイト数がわかっていることが前提です。このコマンドでは、同じ LUN 内に複数のデータベースを格納するホスト上のいずれかのデータベースをリストアできます。

ONTAP 9.12.1以降では、次のコマンドを使用するボリュームに対して部分リストアを実行できます。 xref:../snapmirror-active-sync/index.html[SnapMirrorアクティブ同期]。

.手順
. ボリューム内の Snapshot コピーの一覧を表示します。
+
`volume snapshot show -vserver _SVM_ -volume _volume_`

+
コマンド構文全体については、マニュアルページを参照してください。

+
次の例は、のSnapshotコピーを示しています `vol1`：

+
[listing]
----

clus1::> volume snapshot show -vserver vs1 -volume vol1

Vserver Volume Snapshot                State    Size  Total% Used%
------- ------ ---------- ----------- ------   -----  ------ -----
vs1	 vol1   hourly.2013-01-25_0005  valid   224KB     0%    0%
               daily.2013-01-25_0010   valid   92KB      0%    0%
               hourly.2013-01-25_0105  valid   228KB     0%    0%
               hourly.2013-01-25_0205  valid   236KB     0%    0%
               hourly.2013-01-25_0305  valid   244KB     0%    0%
               hourly.2013-01-25_0405  valid   244KB     0%    0%
               hourly.2013-01-25_0505  valid   244KB     0%    0%

7 entries were displayed.
----
. Snapshot コピーからファイルの一部をリストアします。
+
`volume snapshot partial-restore-file -vserver _SVM_ -volume _volume_ -snapshot _snapshot_ -path _file_path_ -start-byte _starting_byte_ -byte-count _byte_count_`

+
開始バイトオフセットとバイト数は 4 、 096 の倍数でなければなりません。

+
次に、ファイルの最初の4、096バイトをリストアする例を示します `myfile.txt`：

+
[listing]
----
cluster1::> volume snapshot partial-restore-file -vserver vs0 -volume vol1 -snapshot daily.2013-01-25_0010 -path /myfile.txt -start-byte 0 -byte-count 4096
----

