---
permalink: data-protection/snapmirror-global-throttling-concept.html 
sidebar: sidebar 
keywords: using snapmirror, global, throttling 
summary: グローバルネットワークスロットルは、ノード単位のすべての SnapMirror および SnapVault 転送で使用できます。 
---
= SnapMirror グローバルスロットルを使用します
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
グローバルネットワークスロットルは、ノード単位のすべての SnapMirror および SnapVault 転送で使用できます。

.このタスクについて
SnapMirror グローバルスロットルは、送受信される SnapMirror 転送および SnapVault 転送で使用する帯域幅を制限します。この制限は、クラスタ内のすべてのノードで適用されます。

たとえば、送信スロットルを100Mbpsに設定した場合は、クラスタ内の各ノードで送信帯域幅が100Mbpsに設定されます。グローバルスロットルを無効にすると、すべてのノードで無効になります。

データ転送速度は多くの場合ビット / 秒（ bps ）で表されますが、スロットル値はキロバイト / 秒（ KBps ）で入力する必要があります。

[NOTE]
====
ONTAP 9.9.1以前のリリースでは、スロットルはに影響しません `volume move` 転送または負荷共有ミラー転送。ONTAP 9.10.0以降では、ボリューム移動処理をスロットルするオプションを指定できます。詳細については、を参照してください link:https://kb.netapp.com/Advice_and_Troubleshooting/Data_Storage_Software/ONTAP_OS/How_to_throttle_volume_move_in_ONTAP_9.10_or_later["ONTAP 9.10以降でボリューム移動のスロットルを行う方法"]

====
グローバルスロットルは、 SnapMirror 転送および SnapVault 転送の関係ごとのスロットル機能と連動します。関係ごとのスロットルは、関係ごとの転送の帯域幅の合計がグローバルスロットルの値を超えるまで有効で、超えたあとはグローバルスロットルが有効になります。スロットル値 `0` グローバルスロットルが無効になっていることを示します。

[NOTE]
====
SnapMirror グローバルスロットルは、 SnapMirror Synchronous 関係が In-Sync になっている場合は効果がありません。ただし、初期化処理や Out of Sync イベントなどの非同期転送フェーズを実行した場合は、スロットルは SnapMirror Synchronous 関係に影響しません。そのため、 SnapMirror Synchronous 関係でグローバルスロットルを有効にすることは推奨されません。

====
.手順
. グローバルスロットルを有効にします。
+
`options -option-name replication.throttle.enable on|off`

+
次の例は、でSnapMirrorグローバルスロットルを有効にする方法を示しています `cluster_dst`：

+
[listing]
----
cluster_dst::> options -option-name replication.throttle.enable on
----
. デスティネーションクラスタで受信転送に使用される総帯域幅について最大値を指定します。
+
`options -option-name replication.throttle.incoming.max_kbs _KBps_`

+
推奨される最小スロットル帯域幅は 4KBps で、最大値は 2TBps です。このオプションのデフォルト値はです `unlimited`つまり、使用する総帯域幅に制限はありません。

+
次の例は、受信転送で使用される総帯域幅について最大値を 100Mbps に設定する方法を示しています。

+
[listing]
----
cluster_dst::> options -option-name replication.throttle.incoming.max_kbs 12500
----
+
[NOTE]
====
100 Mbps = 12500 kbps

====
. ソースクラスタで送信転送に使用される総帯域幅について最大値を指定します。
+
`options -option-name replication.throttle.outgoing.max_kbs _KBps_`

+
KBps は、 1 秒あたりの最大転送速度です。有効な転送速度の値は 1~125000 です。このオプションのデフォルト値はです `unlimited`つまり、使用する総帯域幅に制限はありません。

+
次の例は、送信転送で使用される総帯域幅について最大値を 100Mbps に設定する方法を示しています。

+
[listing]
----
cluster_src::> options -option-name replication.throttle.outgoing.max_kbs 12500
----

