---
permalink: data-protection/snapmirror-synchronous-disaster-recovery-basics-concept.html 
sidebar: sidebar 
keywords: snapmirror, synchronous, disaster, recovery 
summary: ONTAP 9.5 以降では、 16GB 以上のメモリを搭載したすべての FAS プラットフォームと AFF プラットフォーム、およびすべての ONTAP Select プラットフォームで SnapMirror Synchronous （ SM-S ）テクノロジがサポートされます。SnapMirror Synchronous テクノロジは、ノード単位のライセンスされる機能で、ボリュームレベルの同期データレプリケーションを提供します。 
---
= SnapMirror Synchronous ディザスタリカバリの基本
:hardbreaks:
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
ONTAP 9.5 以降では、 16GB 以上のメモリを搭載したすべての FAS プラットフォームと AFF プラットフォーム、およびすべての ONTAP Select プラットフォームで SnapMirror Synchronous （ SM-S ）テクノロジがサポートされます。SnapMirror Synchronous テクノロジは、ノード単位のライセンスされる機能で、ボリュームレベルの同期データレプリケーションを提供します。

この機能は、データ損失ゼロが求められる金融や医療などの業種で、同期レプリケーションに関する規制や国の規定に対応します。

SnapMirror Synchronous レプリケーションの HA ペアあたりの最大処理数は、コントローラのモデルによって異なります。

次の表に、プラットフォームの種類とONTAP のリリース別にHAペアで実行できるSnapMirror Synchronous処理の数を示します。

|===


| プラットフォーム | ONTAP 9.9.1より前のリリース | ONTAP 9.9.1 | ONTAP 9.10.1 | ONTAP 9.11.1からONTAP 9.14.1まで 


 a| 
AFF
 a| 
8時80分
 a| 
一六 〇
 a| 
200です
 a| 
400だ



 a| 
ASA
 a| 
8時80分
 a| 
一六 〇
 a| 
200です
 a| 
400だ



 a| 
FAS
 a| 
40
 a| 
8時80分
 a| 
8時80分
 a| 
8時80分



 a| 
ONTAP Select の場合
 a| 
20
 a| 
40
 a| 
40
 a| 
40

|===


== サポートされている機能

次の表に、SnapMirror SynchronousおよびONTAPの各リリースでサポートされる機能を示します。

[cols="3,1,4"]
|===


| フィーチャー（ Feature ） | 最初にサポートされたリリース | 追加情報 


| SnapMirror Synchronous 関係のプライマリボリュームに対するウィルス対策 | ONTAP 9.6 |  


| アプリケーションで作成されたSnapshotコピーのレプリケーション | ONTAP 9.7 | Snapshotコピーに適切なラベルでタグ付けされている場合は、 `snapshot create` SnapMirror Synchronousは、CLIまたはONTAP APIを使用して、アプリケーションを休止すると、ユーザが作成したSnapshotコピーと外部スクリプトで作成したSnapshotコピーの両方をレプリケートします。Snapshot ポリシーを使用して作成され、スケジュール設定された Snapshot コピーはレプリケートされません。アプリケーションで作成されたSnapshotコピーのレプリケートの詳細については、ナレッジベースの記事： link:https://kb.netapp.com/Advice_and_Troubleshooting/Data_Protection_and_Security/SnapMirror/How_to_replicate_application_created_snapshots_with_SnapMirror_Synchronous["アプリケーションで作成されたSnapshotをSnapMirror Synchronousでレプリケートする方法"^]。 


| クローンの自動削除 | ONTAP 9.6 |  


| 階層化ポリシーが「なし」、「Snapshot」、または「自動」のFabricPoolアグリゲートは、SnapMirror Synchronousのソースとデスティネーションでサポートされます。 | ONTAP 9.5 | FabricPool アグリゲートのデスティネーションボリュームを「すべて」の階層化ポリシーに設定することはできません。 


| FC | ONTAP 9.5 | レイテンシが10ミリ秒を超えないすべてのネットワーク 


| FC-NVMe | ONTAP 9.7 |  


| SnapMirror Synchronous 関係のプライマリボリュームに対する FPolicy | ONTAP 9.6 |  


| SnapMirror Synchronous関係のプライマリボリュームに対するハードクォータとソフトクォータ | ONTAP 9.6 | クォータルールはデスティネーションにレプリケートされないため、クォータデータベースはデスティネーションにレプリケートされません。 


| iSCSI | ONTAP 9.5 |  


| LUN クローンと NVMe ネームスペースクローン | ONTAP 9.7 |  


| アプリケーションで作成されたSnapshotコピーによってバックアップされるLUNクローン | ONTAP 9.7 |  


| 混在プロトコルアクセス（NFS v3とSMB） | ONTAP 9.6 |  


| NDMP / NDMPリストア | ONTAP 9.13.1 | SnapMirror SynchronousでNDMPを使用するには、ソースクラスタとデスティネーションクラスタの両方でONTAP 9.13.1以降が実行されている必要があります。詳細については、を参照してください xref:../tape-backup/transfer-data-ndmpcopy-task.html[NDMPコピーを使用してデータを転送します]。 


| AFF / ASAプラットフォームでのみ、無停止のSnapMirror Synchronous Operations（NDO；SnapMirror Synchronous Operations）を実行できます。 | ONTAP 9.12.1 | ノンストップオペレーションをサポートしているため、ダウンタイムをスケジュールせずに、一般的なメンテナンスタスクを多数実行できます。サポートされる処理には、テイクオーバーとギブバック、およびボリュームの移動があります。ただし、1つのノードが2つのクラスタのそれぞれで稼働している必要があります。 


| NFS v4.2 | ONTAP 9.10.1 |  


| NFS v4.3 | ONTAP 9.5 |  


| NFS v4.0 | ONTAP 9.6 |  


| NFS v4.1 | ONTAP 9.6 |  


| NVMe/FC | 9.10.1 |  


| メタデータ処理頻度の上限の削除 | ONTAP 9.6 |  


| TLS 1.2 暗号化を使用した機密データ転送時のセキュリティ | ONTAP 9.6 |  


| 単一ファイルおよび部分ファイルのリストア | ONTAP 9.13.1 |  


| SMB 2.0以降 | ONTAP 9.6 |  


| SnapMirror Synchronous ミラー - ミラーカスケード | ONTAP 9.6 | SnapMirror Synchronous 関係のデスティネーションボリュームからの関係は非同期 SnapMirror 関係である必要があります。 


| SVM ディザスタリカバリ | ONTAP 9.6 | * SnapMirror Synchronousソースは、SVMディザスタリカバリソースにすることもできます。たとえば、SnapMirror Synchronousを一方のレッグとして、SVMディザスタリカバリをもう一方のレッグとして使用するファンアウト構成などです。

* SnapMirror Synchronousはデータ保護ソースのカスケードをサポートしていないため、SnapMirror SynchronousソースをSVMディザスタリカバリデスティネーションにすることはできません。
デスティネーションクラスタでSVMディザスタリカバリのフリップ再同期を実行する前に、同期関係を解放する必要があります。

* SVMディザスタリカバリではDPボリュームのレプリケーションがサポートされないため、SnapMirror SynchronousデスティネーションをSVMディザスタリカバリソースにすることはできません。
同期ソースの逆再同期を実行すると、SVMディザスタリカバリでデスティネーションクラスタのDPボリュームが除外されます。 


| NAS のソースボリュームとデスティネーションボリュームの間のタイムスタンプパリティ | ONTAP 9.6 | ONTAP 9.5 から ONTAP 9.6 にアップグレードした場合、タイムスタンプはソースボリューム内の新規および変更されたファイルについてのみレプリケートされます。ソースボリューム内の既存のファイルのタイムスタンプは同期されません。 
|===


== サポートされない機能です

Synchronous SnapMirror 関係では、次の機能はサポートされません。

* 整合グループ
* DP_Optimized （ DPO ）システム
* FlexGroup ボリューム
* FlexCache ボリューム
* グローバルスロットル
* ファンアウト構成で確立できる SnapMirror Synchronous 関係は 1 つだけで、ソースボリュームからの残りの関係はすべて非同期 SnapMirror 関係にする必要があります。
* LUNノイトウ
* LUNクローン/ファイルクローン
* MetroCluster 構成
* SAN アクセスと NVMe アクセスが混在しています
LUN と NVMe ネームスペースは、同じボリュームまたは SVM ではサポートされません。
* SnapCenter
* SnapLock ボリューム
* 改ざん防止Snapshotコピー
* デスティネーションボリュームでのダンプおよび SMTape を使用したテープバックアップまたはリストア
* ソースボリュームへのテープベースのリストア
* ソースボリュームのしきい値の下限（最小 QoS ）
* ボリュームSnapRestore
* VVol




== 動作モード

SnapMirror Synchronous には、使用する SnapMirror ポリシーに基づいて 2 つの動作モードがあります。

* * 同期モード *
Syncモードでは、アプリケーションI/O処理がプライマリとセカンダリに並行して送信されます。
ストレージシステム何らかの理由でセカンダリストレージへの書き込みが完了しない場合、アプリケーションはプライマリストレージへの書き込みを継続できます。エラー状態が解消されると、 SnapMirror Synchronous テクノロジは自動的にセカンダリストレージを再同期し、プライマリストレージからセカンダリストレージへの同期モードでのレプリケーションを再開します。
Sync モードでは、セカンダリレプリケーションに障害問題が発生するまで RPO=0 と非常に低い RTO を実現できます。この場合、 RPO と RTO は不確定になりますが、セカンダリレプリケーションが失敗し、再同期が完了するまでの時間と同じになります。
* * StrictSync モード *
SnapMirror Synchronous は、必要に応じて StrictSync モードで実行できます。何らかの理由でセカンダリストレージへの書き込みが完了しない場合、アプリケーション I/O が失敗し、プライマリストレージとセカンダリストレージが同一に保たれます。プライマリへのアプリケーションI/Oは、SnapMirror関係がに戻るまで再開されません `InSync` ステータス。プライマリストレージで障害が発生した場合は、フェイルオーバー後にセカンダリストレージでアプリケーション I/O を再開できます。データ損失は発生しません。
StrictSync モードの RPO は常にゼロで、 RTO も非常に低く抑えられます。




== 関係のステータス

SnapMirror Synchronous関係のステータスは、常ににあります `InSync` 通常動作中のステータス。何らかの理由でSnapMirror転送に失敗した場合、デスティネーションはソースと同期されておらず、に移動できます `OutofSync` ステータス。

SnapMirror Synchronous関係については、関係のステータスが自動的にチェックされます  `InSync` または `OutofSync`）を一定の間隔で入力します。関係のステータスがの場合 `OutofSync`ONTAP は自動再同期プロセスを自動的にトリガーして、関係をに戻します `InSync` ステータス。再同期が実行されるのは、ソースまたはデスティネーションでの計画外のストレージフェイルオーバーやネットワークの停止などによって転送に失敗した場合のみです。など、ユーザが開始した処理 `snapmirror quiesce` および `snapmirror break` 自動再同期はトリガーしないでください。

関係のステータスがになる場合 `OutofSync` StrictSyncモードのSnapMirror Synchronous関係では、プライマリボリュームに対するI/O処理がすべて停止されます。。 `OutofSync` SyncモードでのSnapMirror Synchronous関係の状態はプライマリへの影響を受けず、プライマリボリュームでI/O処理が許可されます。

.関連情報
http://www.netapp.com/us/media/tr-4733.pdf["ネットアップテクニカルレポート4733：『SnapMirror Synchronous config ration and best bests.』"^]
