---
permalink: data-protection/snapmirror-svm-replication-concept.html 
sidebar: sidebar 
keywords: understand, snapmirror, svm, replication, SVM disaster recovery storage limits 
summary: SnapMirrorを使用して、SVM間のデータ保護関係を作成できます。このタイプのデータ保護関係では、 SVM のすべてまたは一部の設定が NFS エクスポートおよび SMB 共有から RBAC にレプリケートされます。また、 SVM が所有するボリューム内のデータもレプリケートされます。 
---
= ONTAP SnapMirror SVMレプリケーションの詳細
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
SnapMirrorを使用すると、SVM間のデータ保護関係を作成できます。このタイプのデータ保護関係では、SVMのすべてまたは一部の設定がNFSエクスポートおよびSMB共有からRBACにレプリケートされます。また、SVMが所有するボリューム内のデータもレプリケートされます。



== サポートされている関係タイプ

レプリケート可能なのはデータ提供用SVMのみです。サポートされているデータ保護関係タイプは次のとおりです。

* _ SnapMirror DR、_。通常、デスティネーションにはソース上に現在あるSnapshotのみが含まれます。
+
ONTAP 9.9.1以降では、mirror-vaultポリシーを使用している場合にこの動作が変更されます。ONTAP 9.9.1以降では、ソースとデスティネーションで異なるSnapshotポリシーを作成できます。デスティネーションのSnapshotはソースのSnapshotで上書きされません。

+
** スケジュールされた通常の処理、更新、および再同期の実行中に、ソースからデスティネーションに上書きされることはありません
** 解除処理の実行中に削除されることはありません。
** 逆再同期処理の実行中は削除されません。ONTAP 9 .9.1以降を使用するmirror-vaultポリシーを使用してSVMディザスタ関係を設定する場合、ポリシーは次のように動作します。
** ソースのユーザ定義のSnapshotポリシーはデスティネーションにコピーされません。
** システム定義のSnapshotポリシーはデスティネーションにコピーされません。
** ユーザ定義およびシステム定義のSnapshotポリシーとのボリュームの関連付けはデスティネーションにコピーされません。+ SVM


* _SnapMirror 統合レプリケーション_ では、宛先は DR と長期保存の両方に対して構成されます。


SnapMirrorユニファイドレプリケーションの詳細については、を参照してくださいlink:snapmirror-unified-replication-concept.html["SnapMirrorユニファイドレプリケーションの基本"]。

レプリケーションポリシーの _policy type_of によって、サポートされる関係のタイプが決まります。次の表に、使用可能なポリシータイプを示します。

[cols="2*"]
|===


| ポリシータイプ | 関係タイプ 


 a| 
非同期ミラー
 a| 
SnapMirror DR



 a| 
ミラー-バックアップ
 a| 
ユニファイドレプリケーション

|===


== ONTAP 9では、SVMレプリケーションのデフォルトはDPからXDPに変更されます。4

ONTAP 9 .4以降では、SVMデータ保護関係のデフォルトがXDPモードに変更されました。ONTAP 9 .3以前のSVMデータ保護関係のデフォルトは引き続きDPモードです。

XDPのデフォルト値は既存の関係には影響しません。すでにDPタイプの関係は、引き続きDPタイプになります。次の表に、想定される動作を示します。

[cols="3*"]
|===


| 指定するモード | タイプ | デフォルトポリシー（ポリシーを指定しない場合） 


 a| 
DP
 a| 
XDP
 a| 
MirrorAllSnapshots（SnapMirror DR）



 a| 
なし
 a| 
XDP
 a| 
MirrorAllSnapshots（SnapMirror DR）



 a| 
XDP
 a| 
XDP
 a| 
MirrorAndVault（ユニファイドレプリケーション）

|===
DP関係からXDP関係への変換に関する情報およびその他の詳細については、を参照してください。link:convert-snapmirror-version-flexible-task.html["既存のONTAP DPタイプの関係をXDPに変換する"]

[NOTE]
====
バージョンに依存しないレプリケーションはSVMレプリケーションではサポートされません。SVMディザスタリカバリ設定では、フェイルオーバーおよびフェイルバック処理をサポートするために、デスティネーションSVMがソースSVMクラスタと同じバージョンのONTAPを実行しているクラスタである必要があります。

====
link:compatible-ontap-versions-snapmirror-concept.html["SnapMirror関係に互換性があるONTAPのバージョン"]



== SVMの設定のレプリケート方法

SVMレプリケーション関係の内容は、次のフィールドの組み合わせによって決まります。

* コマンドのオプション `snapmirror create`は `-identity-preserve true`、SVMの設定全体をレプリケートします。
+
オプションは `-identity-preserve false`、SVMのボリュームと認証と許可の設定、およびに記載されているプロトコルとネームサービスの設定のみをレプリケートしますlink:snapmirror-svm-replication-concept.html#configurations-replicated-in-svm-disaster-recovery-relationships["SVMディザスタリカバリ関係でレプリケートされる設定"]。

* コマンドのオプションを `snapmirror policy create`使用する `-discard-configs network`と、ソースとデスティネーションのSVMが異なるサブネットにある場合に使用するLIFと関連ネットワークの設定がSVMレプリケーション対象から除外されます。
* コマンドのオプションを `volume modify`使用すると `-vserver-dr-protection unprotected`、指定したボリュームがSVMレプリケーション対象から除外されます。


それ以外の場合、SVMレプリケーションはボリュームレプリケーションとほぼ同じです。SVMレプリケーションには、ボリュームレプリケーションとほぼ同じワークフローを使用できます。



== サポートの詳細

次の表は、SnapMirror SVMレプリケーションのサポートの詳細を示しています。

[cols="2*"]
|===


| リソースまたは機能 | サポートの詳細 


 a| 
ドウニュウタイプ
 a| 
* 単一のソースから単一のデスティネーション
* ONTAP 9 .4以降、ファンアウト。ファンアウトできるのは2つのデスティネーションのみです。
+
デフォルトでは、-identity-preserve trueの関係はソースSVMごとに1つだけ指定できます。





 a| 
関係タイプ
 a| 
* SnapMirrorディザスタ リカバリ
* SnapMirrorユニファイド レプリケーション




 a| 
レプリケーションの範囲
 a| 
クラスタ間のみ。同じクラスタ内のSVMをレプリケートすることはできません。



 a| 
自律型ランサムウェア対策
 a| 
* ONTAP 9.12.1以降でサポート。詳細については、を参照してください link:../anti-ransomware/index.html["自律型ランサムウェア対策"]。




 a| 
整合グループの非同期サポート
 a| 
ONTAP 9 14.1以降では、整合グループが存在する場合に、SVMディザスタリカバリ関係が最大32個サポートされます。詳細については、およびを参照してください link:../consistency-groups/protect-task.html["整合グループの保護"] link:../consistency-groups/limits.html["整合グループの制限"] 。



 a| 
FabricPool
 a| 
ONTAP 9.6以降では、FabricPoolでSnapMirror SVMレプリケーションがサポートされます。SVM DR関係では、ソースボリュームとデスティネーションボリュームでFabricPoolアグリゲートを使用する必要はありませんが、同じ階層化ポリシーを使用する必要があります。

ONTAP 9.12.1以降では、FabricPoolボリュームとFlexGroupボリュームが連動してSnapMirror SVMレプリケーションがサポートされます。9.12.1より前のバージョンでは、これらの機能のいずれか2つが連携して動作していましたが、3つすべてが連携するわけではありませ



 a| 
MetroCluster
 a| 
ONTAP 9.11.1以降では、MetroCluster構成内のSVMディザスタ リカバリ関係のソースとデスティネーション両方を、追加のSVMディザスタ リカバリ構成のソースにすることができます。

ONTAP 9.5以降のMetroCluster構成では、SnapMirror SVMレプリケーションがサポートされます。

* ONTAP 9.10.Xより前のリリースでは、MetroCluster構成をSVMディザスタ リカバリ関係のデスティネーションにすることはできません。
* ONTAP 9 .10.1以降のリリースでは、MetroCluster構成を移行目的でのみSVMディザスタリカバリ関係のデスティネーションにすることができます。この構成は、に記載されている必要なすべての要件を満たしている必要があります https://www.netapp.com/pdf.html?item=/media/83785-tr-4966.pdf["TR-4966：『Migrating a SVM into a MetroCluster 解決策』"^]。
* SVMディザスタリカバリ関係のソースとして使用できるのは、MetroCluster構成のアクティブなSVMだけです。
+
スイッチオーバー前の同期元のSVMと、スイッチオーバー後の同期先のSVMがソースになります。

* MetroCluster構成が安定した状態のときはMetroClusterの同期先のSVMがオンラインでないため、同期先のSVMをSVMディザスタリカバリ関係のソースにすることはできません。
* 同期元のSVMがSVMディザスタリカバリ関係のソースである場合は、ソースのSVMディザスタリカバリ関係の情報がMetroClusterパートナーにレプリケートされます。
* スイッチオーバーおよびスイッチバックの処理中に、SVMディザスタリカバリデスティネーションへのレプリケーションが失敗することがあります。
+
ただし、スイッチオーバーまたはスイッチバックのプロセスが完了すると、SVMディザスタリカバリの次回のスケジュールされた更新は成功します。





 a| 
整合グループ
 a| 
ONTAP 9 14.1以降でサポートされています。詳細については、を参照してください xref:../consistency-groups/protect-task.html[整合グループの保護]。



 a| 
ONTAP S3
 a| 
SVMディザスタ リカバリではサポートされません。



 a| 
SnapMirror Synchronous
 a| 
SVMディザスタ リカバリではサポートされません。



 a| 
バージョンに依存しない
 a| 
サポートされません。



 a| 
ボリューム暗号化
 a| 
* ソースで暗号化されたボリュームがデスティネーションで暗号化されます。
* オンボード キー マネージャまたはKMIPサーバをデスティネーションで設定する必要があります。
* 新しい暗号化キーはデスティネーションで生成されます。
* ボリューム暗号化をサポートするノードがデスティネーションに含まれていない場合、レプリケーションは成功しますが、デスティネーション ボリュームは暗号化されません。


|===


== SVMディザスタリカバリ関係でレプリケートされる設定

次の表に、オプションと `snapmirror policy create -discard-configs network`オプションの相互作用を示し `snapmirror create -identity-preserve`ます。

[cols="5*"]
|===


2+| レプリケートされる設定 2+| `*‑identity‑preserve true*` | `*‑identity‑preserve false*` 


|  |  | *設定されていないポリシー `-discard-configs network`* | *セット付きポリシー `-discard-configs network`* |  


 a| 
ネットワーク
 a| 
NAS LIF
 a| 
〇
 a| 
いいえ
 a| 
いいえ



 a| 
LIFのKerberos設定
 a| 
〇
 a| 
いいえ
 a| 
いいえ



 a| 
SAN LIF
 a| 
いいえ
 a| 
いいえ
 a| 
いいえ



 a| 
ファイアウォールポリシー
 a| 
〇
 a| 
〇
 a| 
いいえ



 a| 
サービスポリシー
 a| 
〇
 a| 
〇
 a| 
いいえ



 a| 
ルート
 a| 
〇
 a| 
いいえ
 a| 
いいえ



 a| 
ブロードキャストドメイン
 a| 
いいえ
 a| 
いいえ
 a| 
いいえ



 a| 
サブネット
 a| 
いいえ
 a| 
いいえ
 a| 
いいえ



 a| 
IPspace
 a| 
いいえ
 a| 
いいえ
 a| 
いいえ



 a| 
SMB
 a| 
SMB サーバ
 a| 
〇
 a| 
〇
 a| 
いいえ



 a| 
ローカルグループとローカルユーザ
 a| 
〇
 a| 
〇
 a| 
〇



 a| 
権限
 a| 
〇
 a| 
〇
 a| 
〇



 a| 
シャドウコピー
 a| 
〇
 a| 
〇
 a| 
〇



 a| 
BranchCache
 a| 
〇
 a| 
〇
 a| 
〇



 a| 
サーバオプション
 a| 
〇
 a| 
〇
 a| 
〇



 a| 
サーバセキュリティ
 a| 
〇
 a| 
〇
 a| 
いいえ



 a| 
ホームディレクトリ、共有
 a| 
〇
 a| 
〇
 a| 
〇



 a| 
シンボリックリンク
 a| 
〇
 a| 
〇
 a| 
〇



 a| 
FPolicyポリシー、fsecurityポリシー、およびfsecurity NTFS
 a| 
〇
 a| 
〇
 a| 
〇



 a| 
ネームマッピングとグループマッピング
 a| 
〇
 a| 
〇
 a| 
〇



 a| 
監査情報
 a| 
〇
 a| 
〇
 a| 
〇



 a| 
NFS
 a| 
エクスポートポリシー
 a| 
〇
 a| 
〇
 a| 
いいえ



 a| 
エクスポートポリシールール
 a| 
〇
 a| 
〇
 a| 
いいえ



 a| 
NFSサーバ
 a| 
〇
 a| 
〇
 a| 
いいえ



 a| 
RBAC
 a| 
セキュリティ証明書
 a| 
〇
 a| 
〇
 a| 
いいえ



 a| 
ログインユーザ、公開鍵、ロール、およびロールの設定
 a| 
〇
 a| 
〇
 a| 
〇



 a| 
SSL
 a| 
〇
 a| 
〇
 a| 
いいえ



 a| 
ネームサービス
 a| 
DNSおよびDNSホスト
 a| 
〇
 a| 
〇
 a| 
いいえ



 a| 
UNIXユーザおよびUNIXグループ
 a| 
〇
 a| 
〇
 a| 
〇



 a| 
Kerberos RealmとKerberosキーブロック
 a| 
〇
 a| 
〇
 a| 
いいえ



 a| 
LDAPおよびLDAPクライアント
 a| 
〇
 a| 
〇
 a| 
いいえ



 a| 
ネットグループ
 a| 
〇
 a| 
〇
 a| 
いいえ



 a| 
NIS
 a| 
〇
 a| 
〇
 a| 
いいえ



 a| 
WebおよびWebアクセス
 a| 
〇
 a| 
〇
 a| 
いいえ



 a| 
ボリューム
 a| 
オブジェクト
 a| 
〇
 a| 
〇
 a| 
〇



 a| 
SnapshotとSnapshotポリシー
 a| 
〇
 a| 
〇
 a| 
〇



 a| 
自動削除ポリシー
 a| 
いいえ
 a| 
いいえ
 a| 
いいえ



 a| 
効率化ポリシー
 a| 
〇
 a| 
〇
 a| 
〇



 a| 
クォータポリシーとクォータポリシールール
 a| 
〇
 a| 
〇
 a| 
〇



 a| 
リカハリキユウ
 a| 
〇
 a| 
〇
 a| 
〇



 a| 
ルートボリューム
 a| 
ネームスペース
 a| 
〇
 a| 
〇
 a| 
〇



 a| 
ユーザデータ
 a| 
いいえ
 a| 
いいえ
 a| 
いいえ



 a| 
qtree
 a| 
いいえ
 a| 
いいえ
 a| 
いいえ



 a| 
クォータ
 a| 
いいえ
 a| 
いいえ
 a| 
いいえ



 a| 
ファイルレベルのQoS
 a| 
いいえ
 a| 
いいえ
 a| 
いいえ



 a| 
属性：ルートボリュームの状態、スペースギャランティ、サイズ、オートサイズ、およびファイル総数
 a| 
いいえ
 a| 
いいえ
 a| 
いいえ



 a| 
ストレージQoS
 a| 
QoSポリシーグループ
 a| 
〇
 a| 
〇
 a| 
〇



 a| 
ファイバチャネル（FC）
 a| 
いいえ
 a| 
いいえ
 a| 
いいえ



 a| 
iSCSI
 a| 
いいえ
 a| 
いいえ
 a| 
いいえ



 a| 
LUN
 a| 
オブジェクト
 a| 
〇
 a| 
〇
 a| 
〇



 a| 
igroup
 a| 
いいえ
 a| 
いいえ
 a| 
いいえ



 a| 
ポートセット
 a| 
いいえ
 a| 
いいえ
 a| 
いいえ



 a| 
シリアル番号
 a| 
いいえ
 a| 
いいえ
 a| 
いいえ



 a| 
SNMP
 a| 
v3ユーザ
 a| 
〇
 a| 
〇
 a| 
いいえ

|===


== SVMディザスタリカバリのストレージ制限

次の表に、ストレージオブジェクトごとにサポートされる推奨されるボリュームおよびSVMディザスタリカバリ関係の最大数を示します。制限は多くの場合プラットフォームに依存することに注意してください。特定の構成の制限については、を参照してlink:https://hwu.netapp.com/["Hardware Universe"^]ください。

[cols="2*"]
|===


| ストレージオブジェクト | 制限 


 a| 
SVM
 a| 
300個のフレキシブルボリューム



 a| 
HAペア
 a| 
フレキシブルボリューム×1、000



 a| 
クラスタ
 a| 
128個のSVMディザスタ関係

|===
.関連情報
* link:https://docs.netapp.com/us-en/ontap-cli/snapmirror-create.html["スナップミラー作成"^]
* link:https://docs.netapp.com/us-en/ontap-cli/snapmirror-policy-create.html["snapmirror policy create"^]

