---
permalink: data-protection/snapmirror-licensing-concept.html 
sidebar: sidebar 
keywords: snapmirror, licensing, snapvault, vault, mirror, relationship, replication, backup, back up, disaster recovery, dr 
summary: ONTAP 9.3 以降では、 ONTAP インスタンス間のレプリケーションが簡易化されています。ONTAP 9 リリースでは、 SnapMirror ライセンスでバックアップ関係とミラー関係の両方がサポートされます。バックアップとディザスタリカバリどちらのユースケースでも ONTAP レプリケーションをサポートする SnapMirror ライセンスを購入できるようになりました。 
---
= SnapMirror のライセンスの概要
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
ONTAP 9.3 以降では、 ONTAP インスタンス間のレプリケーションが簡易化されています。ONTAP 9 リリースでは、 SnapMirror ライセンスでバックアップ関係とミラー関係の両方がサポートされます。バックアップとディザスタリカバリどちらのユースケースでも ONTAP レプリケーションをサポートする SnapMirror ライセンスを購入できるようになりました。

ONTAP 9.3 よりも前のリリースでは、 2 つのライセンスを使用して異なるレプリケーション事例をサポートしていました。ONTAP インスタンス間に vault _ 関係を設定するには、 SnapVault ライセンスが必要でした。この場合、保持期限が長くなるバックアップユースケースに対応するために、 DP インスタンスで保持できる Snapshot コピーの数が多くなります。ONTAP インスタンス間に SnapMirror ライセンスを設定し、クラスタフェイルオーバーが可能なディザスタリカバリのユースケースに備えて、各 ONTAP インスタンスで保持する Snapshot コピーの数（つまり、 _mirror_image ）を同じにする必要がありました。SnapMirror と SnapVault のライセンスは、どちらも ONTAP 8.x および 9.x リリースで引き続き使用およびサポートされます。

SnapVault ライセンスは引き続き機能し、 ONTAP 8.x リリースと 9.x リリースの両方でサポートされますが、現在は販売されていません。SnapMirror ライセンスは引き続き使用でき、 SnapVault の代わりに使用でき、ミラーとバックアップ構成に使用できます。

ONTAP 非同期レプリケーションでは、 ONTAP 9.3 以降、単一のユニファイドレプリケーションエンジンを使用して拡張データ保護モード（ XDP ）ポリシーを設定します。このポリシーでは、ミラーポリシー、バックアップポリシー、またはミラーバックアップポリシーに対して SnapMirror ライセンスを設定できます。ソースとデスティネーションの両方のクラスタに SnapMirror ライセンスが必要です。SnapVault ライセンスは、すでにインストールされている場合は必要ありません。SnapMirrorの非同期永続ライセンスは、ONTAP クラスタ用に購入できるデータ保護バンドルに含まれています。データ保護バンドルの価格はクラスタの物理容量に基づきます。

データ保護構成の上限は、 ONTAP のバージョン、ハードウェアプラットフォーム、インストールされているライセンスなど、いくつかの要因で決まります。詳細については、を参照してください https://hwu.netapp.com/["Hardware Universe"^]。



== SnapMirror Synchronous ライセンス

ONTAP 9.5 以降では、 SnapMirror Synchronous 関係がサポートされます。SnapMirror Synchronous 関係を作成するには、次のライセンスが必要です。

* ソースクラスタとデスティネーションクラスタの両方に SnapMirror Synchronous ライセンスが必要です。
+
SnapMirror Synchronous ライセンスは、 Premium Bundle または Data Protection Bundle のどちらかで有効にします。

+
Premium Bundle または Flash Bundle の 2019 年 6 月より前に購入したシステムの場合、ネットアップマスターキーをダウンロードして、必要な SnapMirror Synchronous ライセンスをNetApp Support Siteから入手できます。 https://mysupport.netapp.com/NOW/knowledge/docs/olio/guides/master_lickey/["マスターライセンスキー"]

* ソースクラスタとデスティネーションクラスタの両方に SnapMirror ライセンスが必要です。




== SnapMirror Cloud ライセンス

ONTAP 9.8 以降では、 SnapMirror クラウドライセンスにより、 ONTAP インスタンスからオブジェクトストレージエンドポイントへの Snapshot コピーの非同期レプリケーションが可能になりました。レプリケーションターゲットは、オンプレミスのオブジェクトストアと、 S3 および S3 と互換性のあるパブリッククラウドのオブジェクトストレージサービスの両方を使用して設定できます。SnapMirror クラウド関係は、 ONTAP システムから、事前修飾されたオブジェクトストレージターゲットへとサポートされます。ONTAP 9.8 で承認されているオブジェクトストレージターゲットには、 ONTAP S3 、 StorageGRID 、 AWS S3 標準、 S3 標準 -IA 、および S3 1 ゾーン -IA 、 Microsoft Azure Blob Premium 、ホットおよびクール、 GCP 標準およびニアラインストレージがあります。

SnapMirror Cloud はスタンドアロンライセンスとしては提供されておらず、 Hybrid Cloud Bundle の購入時にのみ提供されます。Hybrid Cloud Bundleは、容量に基づいて料金が設定されたタームベースのサブスクリプションライセンスです。ONTAP クラスタごとに必要なライセンスは1つだけです。容量は、SnapMirrorクラウドによって保護されているどのボリュームでも、（物理容量ではなく）「使用済み」容量として定義されます。ユーザは、SnapMirror Cloudでバックアップするクラスタ上のボリュームの合計使用容量に基づいてこのライセンスを購入します。2021年10月時点で、Hybrid Cloud BundleにはSnapMirrorクラウドライセンスのみが含まれています（以前のHybrid Cloud BundleにはFabricPool ライセンスが含まれており、2021年10月に発効するバンドルから削除されました）。SnapMirror Cloudに加えて、非同期SnapMirrorライセンスも必要です。このライセンスは、Data Protection Bundleの購入によってのみ利用できます。

SnapMirror クラウド関係を作成するには、次のライセンスが必要です。

* オブジェクトストアエンドポイントに直接レプリケートするには、SnapMirrorライセンス（Data Protection BundleまたはPremium Bundleから購入）とSnapMirror Cloudライセンス（Hybrid Cloud Bundleから購入）の両方が必要です。
* マルチポリシーレプリケーションワークフロー（ディスクツーディスクツークラウドなど）を設定する場合は、すべての ONTAP インスタンスに SnapMirror ライセンスが必要です。一方、 SnapMirror クラウドライセンスが必要なのは、オブジェクトストレージエンドポイントに直接レプリケートするソースクラスタだけです。


SnapMirror クラウドは、ネットアップまたはネットアップの認定代理店パートナーから購入できるエンドユーザライセンスです。SnapMirror クラウドライセンスではエンドユーザが使用できますが、オブジェクトストレージへの非同期 ONTAP のレプリケーションは有効になりません。ONTAP API for SnapMirror Cloud を呼び出すには、許可されたアプリケーションから一意の API キーが必要です。SnapMirror Cloud レプリケーションのオーケストレーションに使用される、許可およびライセンスが付与されたアプリケーションには System Manager が含まれています。また、複数のサードパーティ製アプリケーションプロバイダからも使用できます。これらの許可されたアプリケーションには、 ONTAP API を呼び出すための固有の API キーが組み込まれています。SnapMirror クラウドレプリケーションをオーケストレーションして有効にするには、 SnapMirror クラウドのエンドユーザライセンスと、許可されたサードパーティのバックアップアプリケーションを組み合わせて使用する必要があります。

ONTAP 9.9.1以降では、SnapMirror CloudレプリケーションにSystem Managerを使用できます。詳細については、を参照してください https://docs.netapp.com/us-en/ontap/task_dp_back_up_to_cloud.html["クラウドへのバックアップ"]。

SnapMirror Cloud のサードパーティ製アプリケーションの許可を受けた一覧は、ネットアップの Web サイトで公開されています。



== Data Protection Optimized（DPO）

ONTAP 9.1 以降では、新しい ONTAP データ保護機能が解決策バンドルと呼ばれる に含まれるようになりました。この新しいハードウェアおよびソフトウェアバンドルには、セカンダリワークロードに独自の ONTAP 機能を提供した新しい DP_Optimized （ DPO ）ライセンスが含まれています。ONTAP 9.3 の導入に伴い、 DPO ライセンスでノードあたりのボリューム数が 1 、 000 から 1 、 500 に増えました。ONTAP 9.3 で導入された今回のリリースでは、 FAS2620 の構成に基づいてデータ保護バンドルの構成が新しくなりました。

DPO ライセンスは、 SnapMirror レプリケーションのセカンダリターゲットとして使用される ONTAP クラスタ専用に設計されたライセンスです。DPO コントローラのノードあたりの最大ボリューム数の増加に加えて、 DPO ライセンスは、アプリケーション I/O を犠牲にしてレプリケーショントラフィックの増加をサポートするために、コントローラの QoS 設定も変更しましたこのため、アプリケーションのパフォーマンスに影響が出る可能性があるため、 DPO ライセンスをアプリケーション I/O をサポートするクラスタにインストールしないでください。FAS8200 と FAS2620 に基づくデータ保護バンドルは、解決策として提供され、お客様の環境に基づくプログラム可能な無償ライセンスが付属しています。解決策バンドルを購入すると、 DPO セカンダリにレプリケートされた一部の古いクラスタの SnapMirror の空きライセンスが提供されます。Data Protection 解決策クラスタには DPO ライセンスが必要ですが、次のプラットフォームリストのプライマリクラスタには無料の SnapMirror ライセンスが提供されます。このリストに含まれていないプライマリクラスタには、 SnapMirror ライセンスを購入する必要があります。DPOハードウェアとソフトウェアのバンドルは、FAS2620とFAS8200の両方のシステムに基づいています。これらはEOAステータスであり、現在は提供されていません。

* FAS3000シリーズ
* FAS6000シリーズ
* FAS8000シリーズ




== Data Protection Optimized （ DPO ）ライセンス

ONTAP 9.1 および 9.3 で導入されたデータ保護ハードウェアとソフトウェアの解決策バンドルは、 FAS8200 と FAS2620 のみを基盤としています。これらのプラットフォームが成熟し、新しいプラットフォームが登場したことで、セカンダリレプリケーションのユースケースで ONTAP 機能をサポートするようになったのです。その結果、ONTAP 9.5リリースでは、2018年11月に新しいスタンドアロンのDPOライセンスが導入されました。

スタンドアロンの DPO ライセンスは、 FAS と AFF の両方のプラットフォームでサポートされており、新規クラスタが設定されているか、現場でソフトウェアアップグレードとして導入済みのクラスタに追加された時点で購入できます。これらの新しいDPOライセンスはハードウェアとソフトウェアの解決策 バンドルに含まれていないため、低価格であり、プライマリクラスタの無料のSnapMirrorライセンスは提供されませんでした。DPO ライセンスで個別に設定されたセカンダリクラスタでも SnapMirror ライセンスを購入する必要があり、 DPO セカンダリクラスタにレプリケートするすべてのプライマリクラスタで SnapMirror ライセンスを購入する必要があります。

DPO は、複数の ONTAP リリースで ONTAP の追加機能が提供されています。

[cols="6*"]
|===


| フィーチャー（ Feature ） | 9.3 | 9.4 | 9.5 | 9.6 | 9.7+ 


| ノードあたりの最大ボリューム数  a| 
1 、 500
 a| 
1 、 500
 a| 
1 、 500
 a| 
1500 / 2500
 a| 
1500 / 2500



 a| 
最大同時実行 repl セッション数
 a| 
100です
 a| 
200です
 a| 
200です
 a| 
200です
 a| 
200です



 a| 
ワークロードバイアス *
 a| 
クライアントアプリケーション
 a| 
APPS/SM
 a| 
SnapMirror
 a| 
SnapMirror
 a| 
SnapMirror



 a| 
HDD のボリューム間でのアグリゲート重複排除
 a| 
いいえ
 a| 
はい。
 a| 
はい。
 a| 
はい。
 a| 
はい。

|===
* SnapMirror バックオフ（ワークロードバイアス）機能の優先度に関する詳細：
* クライアント：クラスタの I/O 優先度は、 SnapMirror トラフィックではなく、クライアントのワークロード（本番アプリケーション）に設定されます。
* 同等の機能： SnapMirror レプリケーション要求は、本番アプリケーションの I/O と同じ優先度があります。
* SnapMirror ：すべての SnapMirror I/O 要求は、本番アプリケーションの I/O よりも優先されます。


* 表 1 ：各 ONTAP リリースのノードあたりの FlexVol の最大数 *

[cols="7*"]
|===


|  | DPO なしで 9.3 ~ 9.5 | DPO で 9.3 ~ 9.5 | DPO なしで 9.6 | DPO で 9.6 | 9.7 -- DPO なしで 9.9.1 | DPO で 9.7 ～ 9.9.1 


 a| 
FAS2620
 a| 
1000
 a| 
1 、 500
 a| 
1000
 a| 
1 、 500
 a| 
1000
 a| 
1 、 500



 a| 
FAS2650
 a| 
1000
 a| 
1 、 500
 a| 
1000
 a| 
1 、 500
 a| 
1000
 a| 
1 、 500



 a| 
FAS2720
 a| 
1000
 a| 
1 、 500
 a| 
1000
 a| 
1 、 500
 a| 
1000
 a| 
1 、 500



 a| 
FAS2750
 a| 
1000
 a| 
1 、 500
 a| 
1000
 a| 
1 、 500
 a| 
1000
 a| 
1 、 500



 a| 
A200
 a| 
1000
 a| 
1 、 500
 a| 
1000
 a| 
1 、 500
 a| 
1000
 a| 
1 、 500



 a| 
A220
 a| 
1000
 a| 
1 、 500
 a| 
1000
 a| 
1 、 500
 a| 
1000
 a| 
1 、 500



 a| 
FAS8200/8300
 a| 
1000
 a| 
1 、 500
 a| 
1000
 a| 
2、500
 a| 
1000
 a| 
2、500



 a| 
A300 の比較
 a| 
1000
 a| 
1 、 500
 a| 
1000
 a| 
2、500
 a| 
2、500
 a| 
2、500



 a| 
A400
 a| 
1000
 a| 
1 、 500
 a| 
1000
 a| 
2、500
 a| 
2、500
 a| 
2、500



 a| 
FAS8700/9000 の場合
 a| 
1000
 a| 
1 、 500
 a| 
1000
 a| 
2、500
 a| 
1000
 a| 
2、500



 a| 
A700
 a| 
1000
 a| 
1 、 500
 a| 
1000
 a| 
2、500
 a| 
2、500
 a| 
2、500



 a| 
A700s
 a| 
1000
 a| 
1 、 500
 a| 
1000
 a| 
2、500
 a| 
2、500
 a| 
2、500



 a| 
A800
 a| 
1000
 a| 
1 、 500
 a| 
1000
 a| 
2、500
 a| 
2、500
 a| 
2、500

|===
ご使用の構成でサポートされる FlexVol の最大数については、を参照してください https://hwu.netapp.com/["Hardware Universe"^]。



== DPO のすべての新規インストールに関する考慮事項

* DPO ライセンスを有効にしたあとは、無効にしたり元に戻したりすることはできません。
* DPO ライセンスをインストールするには、 ONTAP の再ブートまたはフェイルオーバーが必要です。
* DPO 解決策はセカンダリストレージのワークロード用であり、 DPO クラスタのアプリケーションワークロードのパフォーマンスに影響する可能性があります
* DPO ライセンスは、ネットアップストレージプラットフォームモデルの選択リストでサポートされます。
* DPO の機能は ONTAP のリリースによって異なります。詳細については、互換性の表を参照してください。
* 新しいFAS システムおよびAFF システムはDPOでは認定されていません。DPOライセンスは、上記以外のクラスタでは購入できません。

