---
permalink: data-protection/snapmirror-licensing-concept.html 
sidebar: sidebar 
keywords: snapmirror, licensing, snapvault, vault, mirror, relationship, replication, backup, back up, disaster recovery, dr 
summary: ONTAP 9 .3以降では、ONTAPインスタンス間のレプリケーションのライセンスが簡易化されました。ONTAP 9リリースでは、SnapMirrorライセンスでバックアップ関係とミラー関係の両方がサポートされます。SnapMirrorライセンスを購入して、バックアップとディザスタリカバリの両方のユースケースでONTAPレプリケーションをサポートできるようになりました。 
---
= ONTAP SnapMirrorのライセンスについて
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
ONTAP 9 .3以降では、ONTAPインスタンス間のレプリケーションのライセンスが簡易化されました。ONTAP 9リリースでは、SnapMirrorライセンスでバックアップ関係とミラー関係の両方がサポートされます。SnapMirrorライセンスを使用すると、バックアップとディザスタリカバリの両方のユースケースでONTAPレプリケーションをサポートできます。

ONTAP 9.3より前のリリースでは、ONTAPインスタンス間の_vault_relationshipsには別のSnapVault ONTAPライセンスが必要でした。この場合、DPインスタンスが保持期間の長いバックアップユースケースに対応するためにより多くのSnapshotを保持できるように、ONTAPインスタンス間の_mirror_relationshipsにはSnapMirrorライセンスが必要でした。ONTAP 8.xおよび9.xリリースでは、SnapMirrorライセンスとSnapVaultライセンスの両方が引き続き使用され、サポートされます。

SnapVaultライセンスは引き続き機能し、ONTAP 8.xと9.xの両方のリリースでサポートされますが、SnapMirrorライセンスをSnapVaultライセンスの代わりに使用して、ミラー構成とバックアップ構成の両方に使用できます。

ONTAP非同期レプリケーションの場合、ONTAP 9 .3以降では、単一のユニファイドレプリケーションエンジンを使用して拡張データ保護モード（XDP）ポリシーがSnapMirror設定されます。XDPライセンスは、ミラーポリシー、バックアップポリシー、またはミラーバックアップポリシーに対して設定できます。ソースとデスティネーションの両方のクラスタにSnapMirrorライセンスが必要です。SnapVaultライセンスは、SnapMirrorライセンスがすでにインストールされている場合は必要ありません。SnapMirror非同期永久ライセンスは、新しいAFFおよびFASシステムにインストールされるONTAP ONEソフトウェアスイートに含まれています。

データ保護設定の制限は、ONTAPのバージョン、ハードウェアプラットフォーム、インストールされているライセンスなど、いくつかの要因で決まります。詳細については、を参照してください https://hwu.netapp.com/["Hardware Universe"^]。



== SnapMirror同期ライセンス

ONTAP 9 .5以降では、SnapMirror同期関係がサポートされます。SnapMirror同期関係を作成するには、次のライセンスが必要です。

* ソースクラスタとデスティネーションクラスタの両方にSnapMirror同期ライセンスが必要です。
+
SnapMirror同期ライセンスはに含まれていlink:../system-admin/manage-licenses-concept.html["ONTAP Oneライセンススイート"]ます。

+
2019年6月より前にPremium BundleまたはFlash Bundleでシステムを購入した場合は、NetAppサポートサイトからNetAppマスターキーをダウンロードして、必要なSnapMirror同期ライセンスを取得できます https://mysupport.netapp.com/NOW/knowledge/docs/olio/guides/master_lickey/["マスターライセンスキー"^]。

* ソースクラスタとデスティネーションクラスタの両方にSnapMirrorライセンスが必要です。




== SnapMirrorクラウドライセンス

ONTAP 9.8以降では、SnapMirrorクラウドライセンスが、ONTAPインスタンスからオブジェクトストレージエンドポイントへのSnapshotの非同期レプリケーションを提供します。レプリケーションターゲットは、オンプレミスのオブジェクトストアとS3およびS3互換のパブリッククラウドオブジェクトストレージサービスの両方を使用して設定できます。SnapMirrorのクラウド関係は、ONTAPシステムから認定済みのオブジェクトストレージターゲットへサポートされます。

SnapMirror Cloudはスタンドアロンライセンスとしては提供されていません。1つのONTAPクラスタに必要なライセンスは1つだけです。SnapMirrorクラウドライセンスに加えて、SnapMirror非同期ライセンスも必要です。

SnapMirrorクラウド関係を作成するには、次のライセンスが必要です。

* オブジェクトストアエンドポイントに直接レプリケートするためのSnapMirrorライセンスとSnapMirrorクラウドライセンスの両方。
* マルチポリシーレプリケーションワークフロー（ディスクツーディスクツークラウドなど）を設定する場合は、すべてのONTAPインスタンスにSnapMirrorライセンスが必要です。一方、SnapMirrorクラウドライセンスは、オブジェクトストレージエンドポイントに直接レプリケートするソースクラスタにのみ必要です。


ONTAP 9 .9.1以降では、この https://docs.netapp.com/us-en/ontap/task_dp_back_up_to_cloud.html["System Managerを使用したSnapMirrorクラウドレプリケーション"]機能を使用できます。

認定されたSnapMirrorクラウドサードパーティアプリケーションのリストは、NetAppのWebサイトで公開されています。



== Data Protection Optimizedライセンス

Data Protection Optimized（DPO）ライセンスの販売は終了し、現在のプラットフォームではDPOはサポートされません。ただし、サポート対象のプラットフォームにDPOライセンスがインストールされている場合、NetAppはそのプラットフォームの販売終了までサポート提供を継続します。

DPOはONTAP Oneライセンス バンドルには含まれていないため、DPOライセンスがシステムにインストールされている場合はONTAP Oneライセンス バンドルにアップグレードできません。

サポートされるプラットフォームの詳細については、を参照してください https://hwu.netapp.com/["Hardware Universe"^]。
