---
permalink: data-protection/update-replication-relationship-manual-task.html 
sidebar: sidebar 
keywords: update, replication, relationship, manual, snap mirror, snapmirror, synchronous 
summary: ソース ボリュームの移動が原因で更新に失敗した場合、レプリケーション関係を手動で更新する必要があります。 
---
= ONTAP SnapMirrorレプリケーション関係を手動で更新する
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
ソース ボリュームの移動が原因で更新に失敗した場合、レプリケーション関係を手動で更新する必要があります。

.タスク概要
レプリケーション関係を手動で更新するまで、SnapMirrorは移動されたソース ボリュームからの転送をすべて中止します。

ONTAP 9.5以降では、SnapMirror同期関係がサポートされています。これらの関係では、ソース ボリュームとデスティネーション ボリュームは常に同期されていますが、セカンダリ クラスタからのビューはプライマリと1時間ごとに同期されます。デスティネーションのポイントインタイム データを表示するには、 `snapmirror update`コマンドを実行して手動で更新する必要があります。

.手順
. レプリケーション関係を手動で更新します。
+
`snapmirror update -source-path <SVM:volume>|<cluster://SVM/volume>, ... -destination-path <SVM:volume>|<cluster://SVM/volume>, ...`

+
[NOTE]
====
このコマンドは、デスティネーションSVMまたはデスティネーション クラスタから実行する必要があります。ソースとデスティネーションに共通のスナップショットが存在しない場合、コマンドは失敗します。 `snapmirror initialize`を使用して関係を再初期化してください。link:https://docs.netapp.com/us-en/ontap-cli/snapmirror-initialize.html["ONTAPコマンド リファレンス"^]の `snapmirror initialize`の詳細を確認してください。

====
+
次の例では、 `svm1`のソース ボリューム `volA`と `svm_backup`のデスティネーション ボリューム `volA_dst`間の関係を更新します：

+
[listing]
----
cluster_src::> snapmirror update -source-path svm1:volA -destination-path svm_backup:volA_dst
----
+
 `snapmirror update`の詳細については、link:https://docs.netapp.com/us-en/ontap-cli/snapmirror-update.html["ONTAPコマンド リファレンス"^]をご覧ください。


