---
permalink: data-protection/update-replication-relationship-manual-task.html 
sidebar: sidebar 
keywords: update, replication, relationship, manual, snap mirror, snapmirror, synchronous 
summary: ソースボリュームが移動されたために更新が失敗した場合は、レプリケーション関係を手動で更新しなければならないことがあります。 
---
= レプリケーション関係を手動で更新
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
ソースボリュームが移動されたために更新が失敗した場合は、レプリケーション関係を手動で更新しなければならないことがあります。

.このタスクについて
レプリケーション関係を手動で更新するまで、 SnapMirror は移動されたソースボリュームからの転送をすべて中止します。

ONTAP 9 .5以降では、SnapMirror同期関係がサポートされます。これらの関係ではソースボリュームとデスティネーションボリュームは常に同期されていますが、セカンダリクラスタのビューは1時間ごとにのみプライマリと同期されます。デスティネーションのポイントインタイムデータを表示する場合は、 `snapmirror update`コマンドを実行して手動更新を実行する必要があります。

.ステップ
. レプリケーション関係を手動で更新します。
+
`snapmirror update -source-path <SVM:volume>|<cluster://SVM/volume>, ... -destination-path <SVM:volume>|<cluster://SVM/volume>, ...`

+
コマンド構文全体については、マニュアルページを参照してください。

+
[NOTE]
====
このコマンドはデスティネーション SVM またはデスティネーションクラスタから実行する必要があります。ソースとデスティネーションに共通の Snapshot コピーが存在しない場合、このコマンドは失敗します。使用 `snapmirror initialize` 関係を再初期化してください。

====
+
次の例は、ソースボリューム間の関係を更新します `volA` オン `svm1` デスティネーションボリュームを指定します `volA_dst` オン `svm_backup`：

+
[listing]
----
cluster_src::> snapmirror update -source-path svm1:volA -destination-path svm_backup:volA_dst
----

