---
permalink: data-protection/version-flexible-snapmirror-default-concept.html 
sidebar: sidebar 
keywords: xdp, replace, dp, snapmirror, default, snap mirror, data protection, replication, replicate, snap lock, snaplock 
summary: ONTAP 9.3 以降では、 SnapMirror 拡張データ保護（ XDP ）モードが SnapMirror データ保護（ DP ）モードに代わって SnapMirror のデフォルトになりました。 
---
= XDP は、 DP を SnapMirror のデフォルトとして置き換えます
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
ONTAP 9.3 以降では、 SnapMirror 拡張データ保護（ XDP ）モードが SnapMirror データ保護（ DP ）モードに代わって SnapMirror のデフォルトになりました。

ONTAP 9.12.1 ONTAP 以降のリリースにアップグレードする前に、既存のDPタイプの関係をXDPに変換する必要があります。詳細については、を参照してください link:convert-snapmirror-version-flexible-task.html["既存の DP タイプの関係を XDP に変換します"]。

ONTAP 9.3 までは、 DP モードで起動する SnapMirror と XDP モードで起動する SnapMirror は異なるレプリケーションエンジンを使用しており、バージョン依存性に対するアプローチも異なります。

* DP モードで起動する SnapMirror では、プライマリストレージとセカンダリストレージの ONTAP バージョンを同じにする必要がある、バージョンに依存するレプリケーションエンジンを使用していました。
+
[listing]
----
cluster_dst::>  snapmirror create -type DP -source-path ... -destination-path ...
----
* XDP モードで起動する SnapMirror では、バージョンに依存しないレプリケーションエンジンを使用していました。そのため、プライマリストレージとセカンダリストレージの ONTAP バージョンが異なっていてもかまいませんでした。
+
[listing]
----
cluster_dst::>  snapmirror create -type XDP -source-path ... -destination-path ...
----


パフォーマンスの向上に伴い、レプリケーションスループットではバージョンに依存するモードの方がわずかに優れてはいるものの、バージョンに依存しない SnapMirror の方がはるかに大きなメリットが得られます。そのため、 ONTAP 9.3 以降では XDP モードが新しいデフォルト値となり、コマンドラインまたは新規 / 既存のスクリプトにおける DP モードの起動は自動的に XDP モードに変換されます。

既存の関係には影響しません。DP タイプの既存の関係は引き続き DP タイプになります。ONTAP 9.5 以降では、データ保護モードを指定しなかった場合、および XDP モードを関係のタイプとして指定した場合、デフォルトポリシーが MirrorAndVault に変更になりました。次の表は、想定される動作を示しています。

[cols="3*"]
|===


| 指定するモード | タイプ | デフォルトポリシー（ポリシーを指定しない場合） 


 a| 
DP
 a| 
XDP
 a| 
MirrorAllSnapshots （ SnapMirror DR ）



 a| 
なし
 a| 
XDP
 a| 
MirrorAndVault （ユニファイドレプリケーション）



 a| 
XDP
 a| 
XDP
 a| 
MirrorAndVault （ユニファイドレプリケーション）

|===
次の表に示すように、それぞれの状況で XDP に割り当てられるデフォルトポリシーでは、変換後も古いタイプと同等の機能が保証されます。もちろん、ユニファイドレプリケーションのポリシーなど、必要に応じて異なるポリシーを使用することもできます。

[cols="3*"]
|===


| 指定するモード | ポリシー | 結果 


 a| 
DP
 a| 
MirrorAllSnapshots
 a| 
SnapMirror DR



 a| 
XDPDefault
 a| 
SnapVault



 a| 
MirrorAndVault の場合
 a| 
ユニファイドレプリケーション



 a| 
XDP
 a| 
MirrorAllSnapshots
 a| 
SnapMirror DR



 a| 
XDPDefault
 a| 
SnapVault



 a| 
MirrorAndVault の場合
 a| 
ユニファイドレプリケーション

|===
変換の唯一の例外は次のとおりです。

* ONTAP 9.3 以前の SVM データ保護関係のデフォルトは引き続き DP モードです。
+
ONTAP 9.4 以降では、 SVM データ保護関係のデフォルトが XDP モードに変更されました。

* ルートボリュームの負荷共有データ保護関係のデフォルトは引き続き DP モードです。
* ONTAP 9.4 以前の SnapLock データ保護関係のデフォルトは引き続き DP モードです。
+
ONTAP 9.5 以降では、 SnapLock データ保護関係のデフォルトが XDP モードに変更されました。

* 次のクラスタ全体のオプションを設定した場合、 DP を明示的に指定した場合のデフォルトは引き続き DP モードです。
+
[listing]
----
options replication.create_data_protection_rels.enable on
----
+
DP を明示的に指定しない場合、このオプションは無視されます。


