---
permalink: data-protection/vol-placement-criteria-svm-dest-reference.html 
sidebar: sidebar 
keywords: snapmirror, svm, replication, disaster recovery, aggregate, volume 
summary: ソースSVMからデスティネーションSVMにボリュームをレプリケートするときは、アグリゲートの選択基準を理解しておくことが重要です。 
---
= ボリュームをデスティネーションSVMに配置する際の基準
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
ソースSVMからデスティネーションSVMにボリュームをレプリケートするときは、アグリゲートの選択基準を理解しておくことが重要です。

アグリゲートは次の基準に基づいて選択されます。

* ボリュームは常にルート以外のアグリゲートに配置されます。
* ルート以外のアグリゲートの中から、利用可能な空きスペースとホストしている既存のボリュームの数に基づいてアグリゲートが選択されます。
+
空きスペースが多くボリュームが少ないアグリゲートが優先されます。最も優先順位が高いアグリゲートが選択されます。

* FabricPoolアグリゲートのソースボリュームは、同じ階層化ポリシーを使用するデスティネーションのFabricPoolアグリゲートに配置されます。
* ソース SVM のボリュームが Flash Pool アグリゲートにある場合、デスティネーション SVM に Flash Pool アグリゲートがあり、そのアグリゲートに十分な空きスペースがあれば、そのアグリゲートにボリュームが配置されます。
* レプリケートするボリュームのオプションがに設定されている `volume`場合 `-space-guarantee`は、空きスペースがボリュームサイズよりも大きいアグリゲートのみが考慮されます。
* ボリュームのサイズは、ソースボリュームのサイズに基づいて、レプリケーション時にデスティネーション SVM で自動的に拡張されます。
+
デスティネーション SVM のサイズを事前にリザーブする場合は、ボリュームのサイズを変更する必要があります。ソース SVM に基づいて、デスティネーション SVM でボリュームのサイズが自動的に縮小されることはありません。



ボリュームをアグリゲート間で移動する場合は、デスティネーションSVMでコマンドを使用できます `volume move`。
