---
permalink: data-protection/vol-placement-criteria-svm-dest-reference.html 
sidebar: sidebar 
keywords: snapmirror, svm, replication, disaster recovery, aggregate, volume 
summary: ソースSVMからデスティネーションSVMにボリュームをレプリケートするときは、アグリゲートの選択基準を理解しておくことが重要です。 
---
= ONTAP SnapMirrorデスティネーション SVMにボリュームを配置するための基準
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
ソースSVMからデスティネーションSVMにボリュームをレプリケートするときは、アグリゲートの選択基準を理解しておくことが重要です。

アグリゲートは次の基準に基づいて選択されます。

* ボリュームは常に非ルート アグリゲートに配置されます。
* 非ルートアグリゲートは、使用可能な空き領域と、アグリゲート上ですでにホストされているボリュームの数に基づいて選択されます。
+
空きスペースが多く、ボリューム数が少ないアグリゲートが優先されます。優先度が最も高いアグリゲートが選択されます。

* FabricPoolアグリゲートのソース ボリュームは、デスティネーションのFabricPoolアグリゲートに同じ階層化ポリシーで配置されます。
* ソース SVM 上のボリュームが Flash Pool アグリゲート上にある場合、そのようなアグリゲートが存在し、十分な空き領域があれば、ボリュームは宛先 SVM 上の Flash Pool アグリゲート上に配置されます。
* 複製されるボリュームの `-space-guarantee`オプションが `volume`に設定されている場合、ボリュームサイズよりも大きい空き領域を持つアグリゲートのみが考慮されます。
* レプリケーション中に、ソースボリュームのサイズに基づいて、デスティネーションSVMのボリュームサイズが自動的に増加します。
+
デスティネーションSVMでサイズを事前に予約したい場合は、ボリュームのサイズを変更する必要があります。ソースSVMに基づいてデスティネーションSVMのボリュームサイズが自動的に縮小されることはありません。



ボリュームをあるアグリゲートから別のアグリゲートに移動する場合は、宛先 SVM で `volume move`コマンドを使用できます。
