---
permalink: release-notes/9151-reference.html 
sidebar: sidebar 
keywords: 'what"s new, release notes, 9.15.1' 
summary: ONTAP 9.15.1の新機能について説明します。 
---
= ONTAP 9.15.1の新機能
:allow-uri-read: 


[role="lead"]
ONTAP 9.15.1の新機能について説明します。

最近のONTAP 9リリースの既知の問題、制限事項、およびアップグレードに関する注意事項の詳細については、 https://library.netapp.com/ecm/ecm_download_file/ECMLP2492508["ONTAP 9リリースノート"^]。リリースノートにアクセスするには、NetAppアカウントでサインインするか、アカウントを作成する必要があります。

最新バージョンのONTAPにアップグレードするには、を参照してください。 link:../upgrade/prepare.html["ONTAPをアップグレードする準備"]。



== データ保護

[cols="30%,70%"]
|===
| 更新 | 説明 


 a| 
xref:../snapmirror-active-sync/index.html[SnapMirror Active Syncは対称アクティブ/アクティブ構成をサポート]
 a| 
SnapMirror Active Sync（旧SnapMirrorビジネス継続性）で対称アクティブ/アクティブ構成がサポートされるようになり、保護対象LUNの両方のコピーからの読み取り/書き込みI/O処理が可能になり、双方向の同期レプリケーションが可能になりました。



 a| 
SnapMirror非同期を使用した整合性グループ内のボリューム数の増加
 a| 
SnapMirror非同期保護を使用する整合グループでは、整合グループ内で最大80個のボリュームがサポートされるようになりました。



 a| 
xref:../consistency-groups/configure-task.html[整合グループを使用したREST APIおよびCLI処理の管理者権限レベルのサポート]
 a| 
整合グループに対するCLI処理とREST API処理が管理者権限レベルでサポートされるようになりました。



 a| 
xref:../concepts/ontap-and-vmware.html[Windows Serverフェイルオーバークラスタリングを使用したVMware仮想ボリュームの永続的予約]
 a| 
ONTAPは現在、VMwareのVirtual Volume（VVOL）と従来のLUNでの永続的予約をサポートしています。ONTAP 9.15.1以降では、VVolを使用して永続的予約を作成することもできます。この機能のサポートは、ONTAP Tools for VMware vSphere 9で実装されています。クラスタ化されたWindows仮想マシンのグループであるWindows Server Failover Cluster（WSFC）でのみサポートされます。

|===


== セキュリティ

[cols="30%,70%"]
|===
| 更新 | 説明 


 a| 
xref:../nas-audit/create-persistent-stores.html[FPolicy永続的ストアの作成と設定の簡易化]
 a| 
FPolicy永続ストアを作成し、ボリュームの作成と設定を同時に自動化するには、 `persistent-store create` コマンドを実行します

拡張された `persistent-store create` また、autosize-modeパラメータを使用して、使用済みスペースの量に応じてボリュームのサイズを拡張または縮小できます。



 a| 
xref:../nfs-rdma/index.html[RDMAニヨルNFSv3ノサホオト]
 a| 
NFS over RDMA構成でNFSv3がサポートされるようになりました。



 a| 
xref:../nas-audit/supported-file-operation-filter-fpolicy-nfsv4-concept.html[FPolicyはNFS 4.1プロトコルをサポートしています。]
 a| 
FPolicyはNFS 4.1プロトコルをサポートしています。



 a| 
xref:../nas-audit/plan-fpolicy-external-engine-config-concept.html[FPolicyのProtobufエンジン形式のサポート]
 a| 
Protobufは、構造化データをシリアライズするためのGoogleの言語に依存しないメカニズムである。XMLに比べてサイズが小さく、速度が速く、シンプルであるため、FPolicyのパフォーマンスが向上します。

protobuf外部エンジン形式を使用できます。protobufに設定すると、通知メッセージはGoogle Protobufを使用してバイナリ形式でエンコードされます。外部エンジン形式をprotobufに設定する前に、FPolicyサーバでもprotobufデシリアライゼーションがサポートされていることを確認してください。



 a| 
xref:../authentication/dynamic-authorization-overview.html[SSH接続の動的許可]
 a| 
ONTAP 9.15.1には、動的認証の初期フレームワークが用意されています。動的認証では、管理者ユーザにセキュリティ信頼スコアを割り当て、アクティビティが疑わしい場合に追加の認証チェックで確認することができるため、ONTAPシステムの管理のセキュリティが強化されます。  動的認証は、データ主体のゼロトラストセキュリティアーキテクチャの一部として使用できます。



 a| 
S3ストレージ、FlexCache、クラスタピアリングの暗号化でTLS 1.3をサポート
 a| 
ONTAP 9.11.1以降では管理アクセス用にTLS 1.3がサポートされていますが、ONTAP 9.15.1ではS3ストレージ、FlexCache、およびクラスタピアリングの暗号化がサポートされるようになりました。FabricPool、Microsoft Azure Page Blobストレージ、SnapMirror Cloudなどの一部のアプリケーションでは、9.15.1リリースで引き続きTLS 1.2が使用されます。



 a| 
xref:../nfs-admin/tls-nfs-strong-security-concept.html[NFS接続でのTLSのサポート]
 a| 
ONTAP 9.15.1では、NFS over TLSがパブリックプレビューとして提供されています。プレビュー版として、ONTAP 9.15.1では本番ワークロードでNFS over TLSはサポートされていません。

NFS over TLSを使用すると、ストレージデバイスからクライアントへの転送中のデータを暗号化できます。TLSはKerberosよりも最新で便利なため、設定と管理が簡単になります。



 a| 
xref:../multi-admin-verify/index.html#rule-protected-commands[マルチ管理者検証用に拡張されたルール保護されたコマンドセット]
 a| 
管理者は、マルチ管理者検証ルールを作成して、クラスタ構成、LUN削除、システム構成、IPsecおよびSAMLのセキュリティ構成、ボリュームSnapshot処理、vServer構成、およびその他のコマンドを保護できます。



 a| 
xref:../system-admin/requirements-autosupport-reference.html[SMTPとTLSを使用したAutoSupportメッセージの配信]
 a| 
NetAppへのAutoSupportメッセージの転送にはHTTPSが推奨されますが、暗号化されていないSMTPも使用できます。ONTAP 9.15.1では、SMTPでTLSを使用するオプションが用意されています。SMTPSプロトコルは、EメールトラフィックとオプションのEメールサーバクレデンシャルを暗号化することで、セキュアな転送チャネルを確立します。明示的なTLSが使用されるため、TCP接続の作成後にTLSがアクティブになります。メッセージのコピーがローカルメールアドレスに送信される場合は、同じ設定が使用されます。

|===


== ストレージ効率

[cols="30%,70%"]
|===
| 更新 | 説明 


 a| 
xref:../volumes/determine-space-usage-volume-aggregate-concept.html[ボリュームスペース指標のレポートに対する変更]
 a| 
使用中のメタデータのみを表示する2つの新しいカウンタが導入されました。また、既存のカウンタのいくつかが調整され、メタデータが削除されてユーザデータのみが表示されるようになりました。これらの変更を組み合わせることで、2種類のデータに分けられたメトリックがより明確に表示されます。お客様はこれらのカウンタを使用して、実際のユーザデータのみを考慮してメタデータを合計から割り引いて、より正確なチャージバックモデルを実装できます。

|===


== ストレージリソース管理の機能拡張

[cols="30%,70%"]
|===
| 更新 | 説明 


 a| 
xref:../flexcache/flexcache-writeback-enable-task.html[FlexCacheライトバックのサポート]
 a| 
キャッシュボリュームでライトバックが有効になっている場合、書き込み要求は元のボリュームではなくローカルキャッシュに送信されるため、エッジコンピューティング環境や書き込み負荷の高いワークロードのキャッシュのパフォーマンスが向上します。



 a| 
xref:../task_nas_file_system_analytics_enable.html[ファイルシステム分析のパフォーマンスの強化]
 a| 
ONTAPでは、ファイルシステム分析を有効にする際にボリュームの容量の5~8%を空けておく必要があるため、ボリュームやファイルシステム分析に関する潜在的なパフォーマンスの問題を軽減できます。

|===


== System Manager の略

[cols="30%,70%"]
|===
| 更新 | 説明 


 a| 
xref:../snaplock/commit-snapshot-copies-worm-concept.html[System ManagerでのSnapLockバックアップ関係の設定のサポート]
 a| 
SnapLockバックアップ関係は、ソースとデスティネーションの両方でONTAP 9.15.1以降を実行している場合、System Managerを使用して設定できます。



 a| 
xref:../task_cp_dashboard_tour.html[System Managerダッシュボードのパフォーマンスの強化]
 a| 
System Managerダッシュボードの[健常性]、[容量]、[ネットワーク]、[パフォーマンス]の各ビューには、レイテンシやパフォーマンスの問題の特定とトラブルシューティングに役立つパフォーマンス指標の強化など、より詳細な説明が表示されます。

|===


== アップグレード

[cols="30%,70%"]
|===
| 更新 | 説明 


 a| 
xref:../upgrade/automated-upgrade-task.html[自動無停止アップグレード時におけるHAパートナーノードへのLIFの移行のサポート]
 a| 
自動無停止アップグレードの実行中に他のバッチグループへのLIFの移行が失敗した場合、LIFは同じバッチグループ内のHAパートナーノードに移行されます。

|===