---
permalink: release-notes/index.html 
sidebar: sidebar 
keywords: release notes, new features, ontap 9, digital advisor 
summary: ONTAP 9の新機能について説明します。 
---
= ONTAP 9リリースのハイライト
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
ONTAP 9データ管理ソフトウェアの各リリースには、ONTAPの機能、管理性、パフォーマンス、セキュリティを強化する新機能と強化された機能が搭載されています。

これらのハイライトに加えて、最近のONTAPリリースで導入されたすべての新機能と強化された機能をバージョンごとに包括的にカバーしています。

* 詳細はこちらをご覧ください https://docs.netapp.com/us-en/ontap-metrocluster/releasenotes/mcc-new-features.html["ONTAP MetroClusterの新機能と強化された機能"^]。
* 詳細はこちらをご覧ください https://docs.netapp.com/us-en/ontap-systems/whats-new.html["FAS、ASA、AFFのプラットフォームとサポートされるスイッチの新規サポートと強化されたサポート"^]。
* の更新について説明します。 https://docs.netapp.com/us-en/ontap-automation/whats_new.html["ONTAP REST API"^]


最近のONTAP 9リリースの既知の問題、制限事項、およびアップグレードに関する注意事項の詳細については、を参照して https://library.netapp.com/ecm/ecm_download_file/ECMLP2492508["ONTAP 9 リリース ノート"^]ください。リリースノートにアクセスするには、NetAppアカウントでサインインするか、アカウントを作成する必要があります。

ONTAPの最新リリースにアップグレードするには、およびを参照してください。xref:../upgrade/prepare.html[ONTAPの最新バージョンへのアップグレード]xref:../upgrade/when-to-upgrade.html[ONTAPはいつアップグレードすればよいですか。]



== ONTAP 9 .16.1の特長

ONTAP 9 .16.1は、セキュリティ管理、データ保護、ネットワーク、SAN管理、ストレージ管理の分野で新機能と拡張機能を提供します。新機能と拡張機能の一覧については、を参照してくださいxref:whats-new-9161.adoc[ONTAP 9.16.1の新機能]。



== ONTAP 9 .15.1の特長

ONTAP 9 .15.1は、セキュリティ管理、データ保護、NASワークロードサポートの分野で新機能と強化された機能を提供します。新機能と拡張機能の一覧については、を参照してくださいxref:whats-new-9151.adoc[ONTAP 9.15.1の新機能]。

* https://www.netapp.com/data-storage/aff-a-series/["新しいAFF Aシリーズシステムをサポート、AI向けに構築"^]
+
ONTAP 9 .15.1は、AI / MLのトレーニングや推論などの次世代のビジネスワークロード向けに設計された、新しいハイパフォーマンスAFF A1K、AFF A90、AFF A70システムをサポートしています。この新しいクラスのシステムは、既存のAFF Aシリーズ製品の最大2倍のパフォーマンスを提供し、「常時稼働」の優れたストレージ効率を提供します。パフォーマンスを犠牲にする必要はありません。

* xref:../smb-admin/windows-backup-symlinks.html[WindowsバックアップアプリケーションとUNIX形式のシンボリックリンク]
+
ONTAP 9.15.1以降では、シンボリックリンクが指すデータではなくシンボリックリンク自体をバックアップするオプションも用意されています。これにより、バックアップアプリケーションのパフォーマンスの向上など、いくつかの利点が得られます。この機能は、ONTAP CLIまたはREST APIを使用して有効にできます。

* xref:../authentication/dynamic-authorization-overview.html[動的許可]
+
ONTAP 9.15.1では、動的許可の初期フレームワークが導入されています。これは、管理者アカウントによるコマンドを拒否するかどうか、追加の認証を要求するかどうか、プロセスの続行を許可するかどうかを判断できるセキュリティ機能です。その判断は、時間帯、場所、IPアドレス、信頼されたデバイスの使用状況、ユーザの認証と許可の履歴などの要因を考慮しながら、ユーザ アカウントの信頼スコアに基づいて行われます。

* xref:../multi-admin-verify/index.html#rule-protected-commands[マルチ管理者認証の影響範囲の拡大]
+
悪意のある侵入者からの保護を強化するために、ONTAP 9.15.1 RC1では、MAVフレームワークに100個以上の新しいコマンドが追加されました。

* xref:../nfs-admin/tls-nfs-strong-security-concept.html[TLS経由のNFS]
+
IPSecやNFS Kerberosなどの他のテクノロジよりもシンプルな設定により、プロトコルレイヤでデータを「ネットワークを介して」保護します。この機能は、現時点ではパブリックプレビューとして含まれています。この機能の詳細については、営業チームにお問い合わせください。

* クラスタピアリングなどでのTLS 1.3暗号化のサポート
+
ONTAP 9 .15.1では、S3ストレージ、FlexCache、SnapMirror、およびクラスタピアリングの暗号化でTLS 1.3暗号化がサポートされるようになりました。FabricPool、Microsoft Azureページブロブストレージ、SnapMirrorクラウドなどのアプリケーションでは、9.15.1リリースで引き続きTLS 1.2が使用されます。

* TLS経由のSMTPトラフィックのサポート
+
TLSをサポートすることで、AutoSupportデータをEメールでセキュアに送信できます。

* xref:../snapmirror-active-sync/index.html[対称アクティブ / アクティブ構成のSnapMirrorアクティブ同期]
+
この新機能により、ビジネス継続性とディザスタ リカバリに対応した双方向同期レプリケーションが可能になります。複数の障害ドメインにわたるデータへの同時読み取り / 書き込みアクセスを使用して、重要なSANワークロードに対するデータ アクセスを保護します。これにより、災害やシステム障害の発生時にも運用の中断を回避し、ダウンタイムを最小限に抑えられます。

* xref:../flexcache-writeback/flexcache-writeback-enable-task.html[FlexCacheのライトバック]
+
FlexCacheのライトバックでは、クライアントがローカルでFlexCacheボリュームに書き込むことができます。元のボリュームに直接書き込む場合に比べてレイテンシを短縮でき、パフォーマンスが向上します。新たに書き込んだデータは、非同期レプリケーションによって元のボリュームに反映されます。

* xref:../nfs-rdma/index.html[NFSv3 over RDMA]
+
NFSv3 over RDMAのサポートにより、TCP経由で低レイテンシで広帯域幅のアクセスが提供され、ハイパフォーマンス要件に対応するのに役立ちます。





== ONTAP 9.14.1のハイライト

ONTAP 9 .14.1は、FabricPool、ランサムウェア対策、OAuthなどの分野で新機能と強化された機能を提供します。新機能と拡張機能の一覧については、を参照してくださいxref:whats-new-9141.adoc[ONTAP 9.14.1の新機能]。

* xref:../volumes/determine-space-usage-volume-aggregate-concept.html[WAFL予約の削減]
+
ONTAP 9 .14.1では、30TB以上のアグリゲートのWAFLリザーブが削減されることで、FASシステムとCloud Volumes ONTAPシステムで使用可能スペースが5%増加しました。

* xref:../fabricpool/enable-disable-volume-cloud-write-task.html[FabricPoolの機能拡張]
+
FabricPoolを使用するxref:../fabricpool/enable-disable-aggressive-read-ahead-task.html[読み取りパフォーマンス]と、クラウドへの直接書き込みが可能になり、コールドデータを低コストのストレージ階層に移動することで、スペース不足のリスクが軽減され、ストレージコストが削減されます。

* link:../authentication/oauth2-deploy-ontap.html["OAuth 2.0のサポート"]
+
ONTAPは、System Managerを使用して設定できるOAuth 2.0フレームワークをサポートしています。OAuth 2.0を使用すると、ユーザIDとパスワードをプレーン テキスト スクリプトやランブックに作成したり公開したりすることなく、自動化フレームワークのためのONTAPへのセキュアなアクセスを実現できます。

* link:../anti-ransomware/manage-parameters-task.html["自律型ランサムウェア対策（ARP）の機能拡張"]
+
ARPを使用すると、イベントのセキュリティをより細かく制御できるようになり、アラートの作成条件を調整して誤検出の可能性を減らすことができます。

* xref:../data-protection/create-delete-snapmirror-failover-test-task.html[System ManagerでのSnapMirrorディザスタ リカバリのリハーサル]
+
System Managerのシンプルなワークフローを使用して、リモート サイトでディザスタ リカバリを簡単にテストしたり、テスト後にクリーンアップしたりできます。この機能により、テストをより簡単かつ頻繁に実施し、目標復旧時間の信頼性を高めることができます。

* xref:../s3-config/index.html[S3オブジェクト ロックのサポート]
+
ONTAP S3ではobject-lock APIコマンドがサポートされています。このコマンドを使用すると、S3でONTAPに書き込まれたデータを標準のS3 APIコマンドを使用して削除から保護し、重要なデータを適切な期間にわたって保護できます。

* xref:../assign-tags-cluster-task.html[クラスタ]xref:../assign-tags-volumes-task.html[ボリューム]タグ付け
+
メタデータタグをボリュームとクラスタに追加します。メタデータタグは、オンプレミスからクラウドにデータを移動したり、データを反転したりするときに追従します。





== ONTAP 9 .13.1の特長

ONTAP 9 .13.1は、ランサムウェア対策、整合グループ、サービス品質（QoS）、テナント容量管理などの分野で新機能と強化された機能を提供します。新機能と拡張機能の一覧については、を参照してくださいxref:whats-new-9131.adoc[ONTAP 9.13.1の新機能]。

* Autonomous Ransomware Protection（ARP）の機能強化：
+
** xref:../anti-ransomware/enable-default-task.adoc[シトウユウコウカ]
+
ONTAP 9 .13.1では、十分な学習データが得られると、ARPは自動的にトレーニングモードから本番モードに移行します。これにより、管理者が30日間有効にする必要がなくなります。

** xref:../anti-ransomware/use-cases-restrictions-concept.html#multi-admin-verification-with-volumes-protected-with-arp[マルチ管理者検証のサポート]
+
ARP disableコマンドはマルチ管理者検証でサポートされているため、1人の管理者がARPを無効にしてデータを潜在的なランサムウェア攻撃にさらすことはできません。

** xref:../anti-ransomware/use-cases-restrictions-concept.html[FlexGroupのサポート]
+
ONTAP 9.13.1から、ARPでFlexGroupがサポートされます。ARPでは、クラスタ内の複数のボリュームとノードにまたがるFlexGroupを監視および保護できるため、大規模なデータセットでもARPを使用して保護できます。



* xref:../consistency-groups/index.html[System Managerでの整合グループのパフォーマンスと容量の監視]
+
パフォーマンスと容量を監視することで、整合グループごとの詳細な監視が可能になり、データ オブジェクト レベルにとどまらずアプリケーション レベルで、潜在的な問題をすばやく特定して報告できます。

* xref:../volumes/manage-svm-capacity.html[テナントの容量管理]
+
マルチテナントのお客様やサービス プロバイダは、SVMごとに容量の上限を設定できます。このため、テナントがセルフサービス プロビジョニングを実行しても、1つのテナントがクラスタの容量を過剰に消費するリスクがなくなります。

* xref:../performance-admin/adaptive-policy-template-task.html[サービス品質の上限と下限]
+
ONTAP 9.13.1では、ボリューム、LUN、ファイルなどのオブジェクトをグループ化してQoSの上限（最大IOPS）または下限（最小IOPS）を割り当てることで、アプリケーションに期待されるパフォーマンスを向上できます。





== ONTAP 9.12.1のハイライト

ONTAP 9 12.1は、セキュリティ強化、保持、パフォーマンスなどの分野で新機能と拡張機能を提供します。新機能と拡張機能の一覧については、を参照してくださいxref:whats-new-9121.adoc[ONTAP 9.12.1の新機能]。

* xref:../snaplock/snapshot-lock-concept.html[Snapshotの改ざんを防止]
+
SnapLockテクノロジを使用すると、ソースまたはデスティネーションでSnapshotコピーが削除されないように保護できます。

+
プライマリストレージとセカンダリストレージのSnapshotをランサムウェア攻撃者や不正な管理者による削除から保護することで、より多くのリカバリポイントを保持できます。

* xref:../anti-ransomware/index.html[自律型ランサムウェア対策（ARP）の機能拡張]
+
プライマリストレージのスクリーニングモデルに基づいて、インテリジェントな自律型ランサムウェア対策をセカンダリストレージで即座に実現します。

+
フェイルオーバー後、セカンダリストレージに対するランサムウェア攻撃の可能性を瞬時に特定影響を受け始めたデータのSnapshotが即座に取得され、管理者に通知されるため、攻撃を阻止してリカバリを強化できます。

* xref:../nas-audit/plan-fpolicy-event-config-concept.html[FPolicy]
+
ONTAP FPolicyをワンクリックでアクティブ化して既知の悪意のあるファイルを自動的にブロックシンプルなアクティブ化により、一般的な既知のファイル拡張子を使用する一般的なランサムウェア攻撃から保護できます。

* xref:../system-admin/ontap-implements-audit-logging-concept.html[セキュリティ強化：改ざん防止保持ロギング]
+
ONTAPでの改ざん防止保持ロギング侵害された管理者アカウントを確実に保護することで、悪意のある操作を隠すことはできません。システムの知識がなければ、管理者およびユーザの履歴を変更または削除することはできません。

+
発生元に関係なく、すべての管理者操作のログと監査情報を取得することで、データに影響を与えるすべての操作が確実にキャプチャされます。システム監査ログが何らかの形で改ざんされると、アラートが生成され、管理者に変更が通知されます。

* xref:../authentication/setup-ssh-multifactor-authentication-task.html[セキュリティの強化：多要素認証の拡張]
+
CLI（SSH）の多要素認証（MFA）は、Yubikey物理ハードウェアトークンデバイスをサポートしています。これにより、攻撃者は、盗まれたクレデンシャルや侵害されたクライアントシステムを使用してONTAPシステムにアクセスできなくなります。Cisco Duoは、System Managerを搭載したMFAでサポートされています。

* ファイルとオブジェクトの二重性（マルチプロトコルアクセス）
+
ファイルとオブジェクトの二重性により、S3プロトコルによる標準の読み取り/書き込みアクセスが、すでにNASプロトコルでアクセスされているデータソースと同じデータソースに可能になります。同じデータソースからファイルまたはオブジェクトとしてストレージに同時にアクセスできるため、オブジェクトデータを使用する分析など、さまざまなプロトコル（S3またはNAS）で使用するデータのコピーを重複して作成する必要がありません。

* xref:../flexgroup/manage-flexgroup-rebalance-task.html[FlexGroupリバランシング]
+
FlexGroupコンスティチュエントの負荷がアンバランスになった場合は、FlexGroupを無停止でリバランシングし、CLI、REST API、およびSystem Managerから管理できます。最適なパフォーマンスを実現するには、FlexGroup内のコンスティチュエントメンバーに使用容量を均等に分散させる必要があります。

* ストレージ容量の拡張
+
WAFLのスペース リザベーションを大幅に抑制したことで、1アグリゲートあたりで使用可能な容量が最大で400TiB増えました。





== ONTAP 9.11.1のハイライト

ONTAP 9 .11.1は、セキュリティ、保持、パフォーマンスなどの分野で新機能と強化された機能を提供します。新機能と拡張機能の一覧については、を参照してくださいxref:whats-new-9111.adoc[ONTAP 9.11.1の新機能]。

* xref:../multi-admin-verify/index.html[マルチ管理者認証]
+
Multi-admin verification（MAV；マルチ管理者認証）は、業界初のネイティブな検証アプローチであり、Snapshotやボリュームの削除など、機密性の高い管理タスクに対して複数の承認を必要とします。MAVの実装で必要とされる承認は、悪意のある攻撃やデータへの偶発的な変更を防止します。

* xref:../anti-ransomware/index.html[自律型ランサムウェア対策の強化]
+
Autonomous Ransomware Protection（ARP）は、機械学習を使用してランサムウェアの脅威をきめ細かく検出し、脅威を迅速に特定し、侵害発生時のリカバリを高速化します。

* xref:../flexgroup/supported-unsupported-config-concept.html#features-supported-beginning-with-ontap-9-11-1[SnapLock Compliance for FlexGroupボリューム]
+
WORMファイルロックでデータを保護し、変更や削除を防止することで、電子設計の自動化やメディア/エンターテイメントなどのワークロード向けに数ペタバイト規模のデータセットを保護します。

* xref:../flexgroup/fast-directory-delete-asynchronous-task.html[非同期ディレクトリの削除]
+
ONTAP 9 .11.1では、ONTAPシステムのバックグラウンドでファイルが削除されるため、大規模なディレクトリを簡単に削除しながら、ホストI/Oへのパフォーマンスやレイテンシの影響を排除できます。

* xref:../s3-config/index.html[S3の機能拡張]
+
ONTAPに追加されたAPIエンドポイントおよびバケット レベルのオブジェクト バージョン管理機能により、S3のオブジェクト データ管理機能が簡易化および拡張され、オブジェクトの複数のバージョンを同じバケットに格納できるようになりました。

* System Managerの機能拡張
+
System Managerは、ストレージ リソースを最適化し、監査管理を強化するための高度な機能をサポートしています。今回の更新には、ストレージ アグリゲートの管理と設定の強化、システム分析のさらなる可視化、FASシステムのハードウェア可視化などが含まれます。





== ONTAP 9.10.1のハイライト

ONTAP 9 .10.1は、セキュリティ強化、パフォーマンス分析、NVMeプロトコルのサポート、オブジェクトストレージのバックアップオプションに関する新機能と強化された機能を提供します。新機能と拡張機能の一覧については、を参照してくださいxref:whats-new-9101.adoc[ONTAP 9.10.1の新機能]。

* xref:../anti-ransomware/index.html[自律型ランサムウェア対策]
+
Autonomous Ransomware Protectionは、ボリュームのSnapshotコピーを自動的に作成し、異常なアクティビティが検出されたときに管理者にアラートを送信します。これにより、ランサムウェア攻撃を迅速に検出し、より迅速にリカバリすることができます。

* System Managerの機能拡張
+
System Managerは、Active IQデジタルアドバイザ（デジタルアドバイザ）、BlueXP 、および証明書管理と新たに統合された機能に加えて、ディスク、シェルフ、サービスプロセッサのファームウェアアップデートを自動的にダウンロードします。これらの機能強化により、管理が簡素化され、ビジネス継続性が維持

* xref:../concept_nas_file_system_analytics_overview.html[ファイルシステム分析の機能拡張]
+
ファイルシステム分析では、ファイル共有内の上位のファイル、ディレクトリ、ユーザを特定するための追加のテレメトリが提供されます。これにより、ワークロードのパフォーマンスの問題を特定し、リソース プランニングとQoSの実装を改善できます。

* xref:../nvme/support-limitations.html[AFFシステムでのNVMe over TCP（NVMe / TCP）のサポート]
+
既存のイーサネット ネットワークでNVMe / TCPを使用すると、AFFシステムでのエンタープライズSANと最新のワークロードのパフォーマンスを向上させ、TCOを削減できます。

* xref:../nvme/support-limitations.html[NetApp FASシステムでのNVMe over Fibre Channel（NVMe / FC）のサポート]
+
ハイブリッド アレイでNVMe / FCプロトコルを使用することで、NVMeへの均等な移行を実現します。

* xref:../s3-snapmirror/index.html[オブジェクト ストレージ向けのハイブリッド クラウド ネイティブ バックアップ]
+
ご希望のオブジェクト ストレージ ターゲットを使用して、ONTAP S3データを保護できます。SnapMirrorレプリケーションを使用して、StorageGRIDではオンプレミス ストレージ、Amazon S3ではクラウド、NetApp AFFシステムおよびFASシステムでは別のONTAP S3バケットにバックアップできます。

* xref:../flexcache/global-file-locking-task.html[FlexCacheによるグローバル ファイルロック]
+
FlexCacheを使用したグローバル ファイルロックにより、元のソース ファイルの更新時にキャッシュの場所のファイルの整合性を確保できます。この機能拡張により、強化されたロックが必要なワークロードに対して、元の場所とキャッシュの関係における排他的なファイル読み取りロックが有効になります。





== ONTAP 9.9.1のハイライト

ONTAP 9 .91.1は、ストレージ効率化、多要素認証、ディザスタリカバリなどの分野で新機能と強化された機能を提供します。新機能と拡張機能の一覧については、を参照してくださいxref:whats-new-991.adoc[ONTAP 9.9.1の新機能]。

* CLIによるリモートアクセス管理のセキュリティの強化
+
SHA512およびSSH A512パスワードハッシュのサポートにより、システムアクセスを取得しようとする悪意のある攻撃者から管理者アカウントのクレデンシャルを保護します。

* https://docs.netapp.com/us-en/ontap-metrocluster/install-ip/task_install_and_cable_the_mcc_components.html["MetroCluster IPの機能拡張:8ノードクラスタのサポート"^]
+
この新しい制限は、以前の制限の2倍になり、MetroCluster構成をサポートし、継続的なデータ可用性を実現します。

* xref:../snapmirror-active-sync/index.html[SnapMirrorアクティブ同期]
+
NASワークロード向けの大規模データコンテナ向けに、バックアップとディザスタリカバリのためのより多くのレプリケーションオプションを提供します。

* xref:../san-admin/storage-virtualization-vmware-copy-offload-concept.html[SANのパフォーマンスの向上]
+
VMwareデータストアなどの単一のLUNアプリケーションのSANパフォーマンスが最大4倍に向上するため、SAN環境で高いパフォーマンスを実現できます。

* xref:../task_cloud_backup_data_using_cbs.html[ハイブリッド クラウド向けの新しいオブジェクト ストレージのオプション]
+
StorageGRIDをNetApp Cloud Backup Serviceのデスティネーションとして使用できるようにし、オンプレミスのONTAPデータのバックアップを簡易化および自動化できます。



.次のステップ
* xref:../upgrade/prepare.html[ONTAPの最新バージョンへのアップグレード]
* xref:../upgrade/when-to-upgrade.html[ONTAPはいつアップグレードすればよいですか。]

