---
permalink: release-notes/index.html 
sidebar: sidebar 
keywords: release notes, new features, ontap 9 
summary: ONTAP 9の新機能について説明します。 
---
= ONTAP 9リリースのハイライト
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
ONTAP 9データ管理ソフトウェアの各リリースには、ONTAPの機能、管理性、パフォーマンス、セキュリティを強化する新機能と強化された機能が搭載されています。

これらのハイライトに加えて、最近のONTAPリリースで導入されたすべての新機能と強化された機能をバージョンごとに包括的にカバーしています。

* 詳細はこちら https://docs.netapp.com/us-en/ontap-metrocluster/releasenotes/mcc-new-features.html["ONTAP MetroClusterの新機能と強化された機能"^]。
* 詳細はこちら https://docs.netapp.com/us-en/ontap-systems/whats-new.html["FAS、ASA、AFFのプラットフォームとサポートされるスイッチの新規サポートと強化されたサポート"^]。
* の更新については、 https://docs.netapp.com/us-en/ontap-automation/whats_new.html["ONTAP REST API"^]。


最近のONTAP 9リリースの既知の問題、制限事項、およびアップグレードに関する注意事項の詳細については、 https://library.netapp.com/ecm/ecm_download_file/ECMLP2492508["ONTAP 9リリースノート"^]。リリースノートにアクセスするには、NetAppアカウントでサインインするか、アカウントを作成する必要があります。

ONTAPの最新リリースにアップグレードするには、を参照してください。 xref:../upgrade/prepare.html[ONTAPの最新バージョンへのアップグレード] および xref:../upgrade/when-to-upgrade.html[ONTAPはいつアップグレードすればよいですか。]



== ONTAP 9.15.1の特長

ONTAP 9.15.1は、セキュリティ管理、データ保護、NASワークロードサポートの分野で新機能と強化された機能を提供します。新機能と拡張機能の一覧については、を参照してください。 xref:whats-new-9151.adoc[ONTAP 9.15.1の新機能]。

* https://www.netapp.com/data-storage/aff-a-series/["新しいAFF Aシリーズシステムをサポート、AI向けに構築"^]
+
ONTAP 9.15.1は、AI / MLのトレーニングや推論などの次世代のビジネスワークロード向けに設計された、新しいハイパフォーマンスAFF A1K、AFF A90、AFF A70システムをサポートします。この新しいクラスのシステムは、既存のAFF Aシリーズ製品の最大2倍のパフォーマンスを提供し、「常時稼働」の優れたストレージ効率を提供します。パフォーマンスを犠牲にする必要はありません。

* xref:../smb-admin/windows-backup-symlinks.html[WindowsバックアップアプリケーションとUNIX形式のシンボリックリンク]
+
ONTAP 9.15.1以降では、シンボリックリンクが指すデータではなくシンボリックリンク自体をバックアップするオプションも用意されています。これにより、バックアップアプリケーションのパフォーマンスの向上など、いくつかの利点が得られます。この機能は、ONTAP CLIまたはREST APIを使用して有効にできます。

* xref:../authentication/dynamic-authorization-overview.html[動的許可]
+
ONTAP 9.15.1では、動的許可の初期フレームワークが導入されています。動的許可は、管理者アカウントによって発行されたコマンドを拒否するか、追加の認証を要求するか、続行を許可するかを決定するセキュリティ機能です。決定は、時刻、場所、IPアドレス、信頼できるデバイスの使用状況、ユーザーの認証および承認履歴などの要因を考慮して、ユーザーアカウントの信頼スコアに基づいて行われます。

* xref:../multi-admin-verify/index.html#rule-protected-commands[マルチ管理者検証の影響範囲の拡大]
+
ONTAP 9.15.1 RC1では、悪意のある内部ユーザからの保護を強化するために、100を超える新しいコマンドがMAVフレームワークに追加されています。

* xref:../nfs-admin/tls-nfs-strong-security-concept.html[TLS経由のNFS]
+
IPSecやNFS Kerberosなどの他のテクノロジよりもシンプルな設定により、プロトコルレイヤでデータを「ネットワークを介して」保護します。この機能は、現時点ではパブリックプレビューとして含まれています。この機能の詳細については、営業チームに追加情報についてお問い合わせください。

* クラスタピアリングなどでのTLS 1.3暗号化のサポート
+
ONTAP 9.15.1では、S3ストレージ、FlexCache、SnapMirror、クラスタピアリングの暗号化でTLS 1.3暗号化がサポートされるようになりました。FabricPool、Microsoft Azure Page Blobストレージ、SnapMirror Cloudなどのアプリケーションでは、9.15.1リリースで引き続きTLS 1.2が使用されます。

* TLS経由のSMTPトラフィックのサポート
+
TLSをサポートしているため、AutoSupportデータをEメールで安全に転送できます。

* xref:../snapmirror-active-sync/index.html[対称アクティブ/アクティブ構成のSnapMirrorアクティブ同期]
+
この新しい機能は、ビジネス継続性とディザスタリカバリのための同期双方向レプリケーションを提供します。複数の障害ドメインにわたってデータへの読み取り/書き込みアクセスを同時に行うことで、重要なSANワークロードのデータアクセスを保護し、業務の中断を防ぎ、災害やシステム障害時のダウンタイムを最小限に抑えることができます。

* xref:../flexcache-writeback/flexcache-writeback-enable-task.html[FlexCacheライトバック]
+
FlexCacheライトバックにより、クライアントはFlexCacheボリュームにローカルで書き込むことができるため、元のボリュームに直接書き込む場合に比べてレイテンシが低減し、パフォーマンスが向上します。新しく書き込まれたデータは非同期で元のボリュームにレプリケートされます。

* xref:../nfs-rdma/index.html[RDMA経由のNFSv3]
+
NFSv3 over RDMAのサポートは、TCP経由で低レイテンシで広帯域幅のアクセスを提供することで、ハイパフォーマンス要件に対応するのに役立ちます。





== ONTAP 9.14.1の特長

ONTAP 9.14.1は、FabricPool、ランサムウェア対策、OAuthなどの分野で新機能と強化された機能を提供します。新機能と拡張機能の一覧については、を参照してください。 xref:whats-new-9141.adoc[ONTAP 9.14.1の新機能]。

* xref:../volumes/determine-space-usage-volume-aggregate-concept.html[WAFL予約の削減]
+
ONTAP 9.14.1では、30TB以上のアグリゲートのWAFLリザーブが削減されることで、FASシステムとCloud Volumes ONTAPシステムで使用可能スペースが即座に5%増加しました。

* xref:../fabricpool/enable-disable-volume-cloud-write-task.html[FabricPoolの機能拡張]
+
FabricPoolは、 xref:../fabricpool/enable-disable-aggressive-read-ahead-task.html[読み取りパフォーマンス] また、クラウドへの直接書き込みが可能なため、コールドデータを低コストのストレージ階層に移動することで、スペース不足のリスクを軽減し、ストレージコストを削減できます。

* link:../authentication/oauth2-deploy-ontap.html["OAuth 2.0のサポート"]
+
ONTAPは、System Managerを使用して設定できるOAuth 2.0フレームワークをサポートしています。OAuth 2.0を使用すると、ユーザIDとパスワードをプレーンテキストスクリプトやランブックに作成したり公開したりすることなく、自動化フレームワーク用のONTAPへの安全なアクセスを提供できます。

* link:../anti-ransomware/manage-parameters-task.html["Autonomous Ransomware Protection（ARP）の機能拡張"]
+
ARPを使用すると、イベントのセキュリティをより細かく制御できるようになり、アラートを生成する条件を調整して、誤検出の可能性を減らすことができます。

* xref:../data-protection/create-delete-snapmirror-failover-test-task.html[System ManagerでのSnapMirrorディザスタリカバリのリハーサル]
+
System Managerのシンプルなワークフローを使用して、リモートサイトでディザスタリカバリを簡単にテストしたり、テスト後にクリーンアップしたりできます。この機能により、テストをより簡単かつ頻繁に実施し、目標復旧時間の信頼性を高めることができます。

* xref:../s3-config/index.html[S3オブジェクトロックのサポート]
+
ONTAP S3では、object-lock APIコマンドがサポートされており、S3でONTAPに書き込まれたデータを削除から保護できます。
S3 APIの標準コマンドとを使用して、重要なデータを適切な期間にわたって保護します。

* xref:../assign-tags-cluster-task.html[クラスタ] および xref:../assign-tags-volumes-task.html[ボリューム] タグ付け
+
メタデータタグをボリュームとクラスタに追加します。メタデータタグは、オンプレミスからクラウドにデータを移動したり、データを反転したりするときに追従します。





== ONTAP 9.13.1の特長

ONTAP 9.13.1は、ランサムウェア対策、整合グループ、サービス品質（QoS）、テナント容量管理などの分野で新機能と強化された機能を提供します。新機能と拡張機能の一覧については、を参照してください。 xref:whats-new-9131.adoc[ONTAP 9.13.1の新機能]。

* Autonomous Ransomware Protection（ARP）の機能強化：
+
** xref:../anti-ransomware/enable-default-task.adoc[シトウユウコウカ]
+
ONTAP 9.13.1では、十分な学習データが得られると、ARPは自動的にトレーニングモードから本番モードに移行します。これにより、管理者が30日間有効にする必要がなくなります。

** xref:../anti-ransomware/use-cases-restrictions-concept.html#multi-admin-verification-with-volumes-protected-with-arp[マルチ管理者検証のサポート]
+
ARP disableコマンドはマルチ管理者検証でサポートされているため、1人の管理者がARPを無効にしてデータを潜在的なランサムウェア攻撃にさらすことはできません。

** xref:../anti-ransomware/use-cases-restrictions-concept.html[FlexGroupのサポート]
+
ONTAP 9.13.1以降では、ARPでFlexGroupがサポートされます。ARPでは、クラスタ内の複数のボリュームとノードにまたがるFlexGroupを監視および保護できるため、大規模なデータセットでもARPを使用して保護できます。



* xref:../consistency-groups/index.html[System Managerでの整合性グループのパフォーマンスと容量の監視]
+
パフォーマンスと容量を監視することで、整合性グループごとの詳細な監視が可能になり、データオブジェクトレベルではなくアプリケーションレベルで潜在的な問題をすばやく特定して報告することができます。

* xref:../volumes/manage-svm-capacity.html[テナントの容量管理]
+
マルチテナントのお客様やサービスプロバイダは、SVMごとに容量の上限を設定できるため、テナントがセルフサービスプロビジョニングを実行しても、1つのテナントがクラスタの容量を過剰に消費するリスクはありません。

* xref:../performance-admin/adaptive-policy-template-task.html[サービス品質（QoS）の天井と床]
+
ONTAP 9.13.1では、ボリューム、LUN、ファイルなどのオブジェクトをグループにグループ化してQoSの上限（最大IOPS）または下限（最小IOPS）を割り当てることで、アプリケーションに求められるパフォーマンスを向上させることができます。





== ONTAP 9.12.1の特長

ONTAP 9.12.1は、セキュリティ強化、保持、パフォーマンスなどの分野で新機能と強化された機能を提供します。新機能と拡張機能の一覧については、を参照してください。 xref:whats-new-9121.adoc[ONTAP 9.12.1の新機能]。

* xref:../snaplock/snapshot-lock-concept.html[Snapshotの改ざんを防止]
+
SnapLockテクノロジを使用すると、ソースまたはデスティネーションでSnapshotコピーが削除されないように保護できます。

+
プライマリストレージとセカンダリストレージのSnapshotをランサムウェア攻撃者や不正な管理者による削除から保護することで、より多くのリカバリポイントを保持できます。

* xref:../anti-ransomware/index.html[Autonomous Ransomware Protection（ARP）の機能拡張]
+
プライマリストレージのスクリーニングモデルに基づいて、インテリジェントな自律型ランサムウェア対策をセカンダリストレージで即座に実現します。

+
フェイルオーバー後、セカンダリストレージに対するランサムウェア攻撃の可能性を瞬時に特定影響を受け始めたデータのSnapshotが即座に取得され、管理者に通知されるため、攻撃を阻止してリカバリを強化できます。

* xref:../nas-audit/plan-fpolicy-event-config-concept.html[FPolicy の]
+
ONTAP FPolicyをワンクリックでアクティブ化して既知の悪意のあるファイルを自動的にブロックシンプルなアクティブ化により、一般的な既知のファイル拡張子を使用する一般的なランサムウェア攻撃から保護できます。

* xref:../system-admin/ontap-implements-audit-logging-concept.html[セキュリティ強化：改ざん防止保持ロギング]
+
ONTAPでの改ざん防止保持ロギング侵害された管理者アカウントを確実に保護することで、悪意のある操作を隠すことはできません。システムの知識がなければ、管理者およびユーザの履歴を変更または削除することはできません。

+
発生元に関係なく、すべての管理操作をログに記録して監査することで、データに影響を与えるすべての操作が確実にキャプチャされます。システム監査ログが改ざんされて管理者に変更が通知されると、アラートが生成されます。

* xref:../authentication/setup-ssh-multifactor-authentication-task.html[セキュリティの強化：多要素認証の拡張]
+
CLI（SSH）の多要素認証（MFA）は、Yubikey物理ハードウェアトークンデバイスをサポートしています。これにより、攻撃者は、盗まれたクレデンシャルや侵害されたクライアントシステムを使用してONTAPシステムにアクセスできなくなります。Cisco Duoは、System Managerを使用したMFAでサポートされています。

* ファイルとオブジェクトの二重性（マルチプロトコルアクセス）
+
ファイルとオブジェクトの二重性により、S3プロトコルによる標準の読み取り/書き込みアクセスが、すでにNASプロトコルでアクセスされているデータソースと同じデータソースに可能になります。同じデータソースからファイルまたはオブジェクトとしてストレージに同時にアクセスできるため、オブジェクトデータを使用する分析など、さまざまなプロトコル（S3またはNAS）で使用するデータのコピーを重複して作成する必要がありません。

* xref:../flexgroup/manage-flexgroup-rebalance-task.html[FlexGroup のリバランシング]
+
FlexGroupコンスティチュエントの負荷がアンバランスになった場合は、FlexGroupを無停止でリバランシングし、
CLI、REST API、およびSystem Managerを使用できます。最適なパフォーマンスを実現するには、FlexGroup内のコンスティチュエントメンバーに使用容量を均等に分散させる必要があります。

* ストレージ容量の拡張
+
WAFLのスペースリザベーションが大幅に削減され、アグリゲートあたりの使用可能容量が最大400TiB増えました。





== ONTAP 9.11.1の特長

ONTAP 9.11.1は、セキュリティ、保持、パフォーマンスなどの分野で新機能と強化された機能を提供します。新機能と拡張機能の一覧については、を参照してください。 xref:whats-new-9111.adoc[ONTAP 9.11.1の新機能]。

* xref:../multi-admin-verify/index.html[管理者による検証が複数必要です]
+
Multi-admin verification（MAV；マルチ管理者認証）は、業界初のネイティブな検証アプローチであり、Snapshotやボリュームの削除など、機密性の高い管理タスクに対して複数の承認を必要とします。MAVの実装で必要とされる承認は、悪意のある攻撃やデータへの偶発的な変更を防止します。

* xref:../anti-ransomware/index.html[自律型ランサムウェア対策の強化]
+
Autonomous Ransomware Protection（ARP）は、機械学習を使用してランサムウェアの脅威をきめ細かく検出し、脅威を迅速に特定し、侵害発生時のリカバリを高速化します。

* xref:../flexgroup/supported-unsupported-config-concept.html#features-supported-beginning-with-ontap-9-11-1[FlexGroupボリュームのSnapLock準拠]
+
WORMファイルロックでデータを保護し、変更や削除を防止することで、電子設計の自動化やメディア/エンターテイメントなどのワークロード向けに数ペタバイト規模のデータセットを保護します。

* xref:../flexgroup/fast-directory-delete-asynchronous-task.html[非同期ディレクトリの削除]
+
ONTAP 9.11.1では、ONTAPシステムのバックグラウンドでファイルが削除されるため、大規模なディレクトリを簡単に削除しながら、ホストI/Oへのパフォーマンスやレイテンシの影響を排除できます。

* xref:../s3-config/index.html[S3の機能拡張]
+
ONTAPの追加のAPIエンドポイントとバケットレベルのオブジェクトバージョン管理により、S3のオブジェクトデータ管理機能を簡易化、拡張し、オブジェクトの複数のバージョンを同じバケットに格納できるようになります。

* System Manager の機能拡張
+
System Managerは、ストレージリソースを最適化し、監査管理を強化する高度な機能をサポートしています。この更新には、ストレージアグリゲートの管理と構成の強化、システム分析の可視化の強化、FASシステムのハードウェア可視化などが含まれます。





== ONTAP 9.10.1の特長

ONTAP 9.10.1は、セキュリティ強化、パフォーマンス分析、NVMeプロトコルのサポート、オブジェクトストレージのバックアップオプションに関する新機能と強化された機能を提供します。新機能と拡張機能の一覧については、を参照してください。 xref:whats-new-9101.adoc[ONTAP 9.10.1の新機能]。

* xref:../anti-ransomware/index.html[自律的なランサムウェア防御]
+
Autonomous Ransomware Protectionは、ボリュームのSnapshotコピーを自動的に作成し、異常なアクティビティが検出されたときに管理者にアラートを送信します。これにより、ランサムウェア攻撃を迅速に検出し、より迅速にリカバリすることができます。

* System Manager の機能拡張
+
System Managerは、NetApp Active IQデジタルアドバイザ、BlueXP、および証明書管理と新たに統合された機能に加え、ディスク、シェルフ、サービスプロセッサのファームウェアの更新を自動的にダウンロードします。これらの機能強化により、管理が簡素化され、ビジネス継続性が維持

* xref:../concept_nas_file_system_analytics_overview.html[ファイルシステム分析の機能拡張]
+
ファイルシステム分析では、ファイル共有内の上位のファイル、ディレクトリ、ユーザを特定するための追加のテレメトリが提供されます。これにより、ワークロードのパフォーマンスの問題を特定し、リソースプランニングとQoSの実装を改善できます。

* xref:../nvme/support-limitations.html[AFFシステムでのNVMe over TCP（NVMe/TCP）のサポート]
+
既存のイーサネットネットワークでNVMe/TCPを使用すると、AFFシステムでエンタープライズSANと最新のワークロードのパフォーマンスを向上し、TCOを削減できます。

* xref:../nvme/support-limitations.html[NetApp FASシステムでNVMe over Fibre Channel（NVMe/FC）をサポート]
+
ハイブリッドアレイでNVMe/FCプロトコルを使用して、NVMeへの均一な移行を実現します。

* xref:../s3-snapmirror/index.html[オブジェクトストレージ向けのハイブリッドクラウドネイティブバックアップ]
+
任意のオブジェクトストレージターゲットを使用して、ONTAP S3データを保護できます。SnapMirrorレプリケーションを使用して、StorageGRIDではオンプレミスストレージ、Amazon S3ではクラウド、NetApp AFFシステムやFASシステムでは別のONTAP S3バケットにバックアップできます。

* xref:../flexcache/global-file-locking-task.html[FlexCacheによるグローバルファイルロック]
+
FlexCacheを使用したグローバルファイルロックにより、元のソースファイルの更新時にキャッシュの場所でファイルの整合性を確保できます。この機能拡張により、強化されたロックが必要なワークロードに対して、オリジンとキャッシュの関係で排他的なファイル読み取りロックが有効になります。





== ONTAP 9.9.1の特長

ONTAP 9.91.1は、ストレージ効率化、多要素認証、ディザスタリカバリなどの分野で新機能と強化された機能を提供します。新機能と拡張機能の一覧については、を参照してください。 xref:whats-new-991.adoc[ONTAP 9.9.1の新機能]。

* CLIによるリモートアクセス管理のセキュリティの強化
+
SHA512およびSSH A512パスワードハッシュのサポートにより、システムアクセスを取得しようとする悪意のある攻撃者から管理者アカウントのクレデンシャルを保護します。

* https://docs.netapp.com/us-en/ontap-metrocluster/install-ip/task_install_and_cable_the_mcc_components.html["MetroCluster IPの機能拡張:8ノードクラスタのサポート"^]
+
この新しい制限は、以前の制限の2倍になり、MetroCluster構成をサポートし、継続的なデータ可用性を実現します。

* xref:../snapmirror-active-sync/index.html[SnapMirrorアクティブ同期]
+
NASワークロード向けの大規模データコンテナ向けに、バックアップとディザスタリカバリのためのより多くのレプリケーションオプションを提供します。

* xref:../san-admin/storage-virtualization-vmware-copy-offload-concept.html[SANのパフォーマンスの向上]
+
VMwareデータストアなどの単一LUNアプリケーションに対して最大4倍のSANパフォーマンスを提供するため、SAN環境で高いパフォーマンスを実現できます。

* xref:../task_cloud_backup_data_using_cbs.html[ハイブリッドクラウド向けの新しいオブジェクトストレージオプション]
+
StorageGRIDをNetApp Cloud Backup Serviceのデスティネーションとして使用し、オンプレミスのONTAPデータのバックアップを簡易化、自動化できます。



.次のステップ
* xref:../upgrade/prepare.html[ONTAPの最新バージョンへのアップグレード]
* xref:../upgrade/when-to-upgrade.html[ONTAPはいつアップグレードすればよいですか。]

