---
permalink: release-notes/whats-new-9181.html 
sidebar: sidebar 
keywords: 'what"s new, release notes, 9.18.1' 
summary: ONTAP 9.18.1で利用できる新機能について説明します。 
---
= ONTAP 9.18.1の新機能
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
ONTAP 9.18.1で利用できる新機能について説明します。

最近のONTAP 9リリースの既知の問題、制限事項、およびアップグレードに関する注意事項の詳細については、を参照して https://library.netapp.com/ecm/ecm_download_file/ECMLP2492508["ONTAP 9 リリース ノート"^]ください。リリースノートにアクセスするには、NetAppアカウントでサインインするか、アカウントを作成する必要があります。

* 新しい機能と強化された機能について説明します https://docs.netapp.com/us-en/ontap-metrocluster/releasenotes/mcc-new-features.html["ONTAP MetroClusterの機能"^]。
* 学ぶ https://docs.netapp.com/us-en/ontap-afx/release-notes/whats-new-9171.html["NetApp AFXストレージシステム向けの新しいONTAPソフトウェア機能と強化された機能"^] 。
* 学ぶ https://docs.netapp.com/us-en/asa-r2/release-notes/whats-new-9171.html["NetApp ASA r2 ストレージ システム向けの新しい ONTAP ソフトウェア機能と強化されたONTAPソフトウェア機能"^] 。
* 学ぶ https://docs.netapp.com/us-en/ontap-systems/whats-new.html["AFF、 ASA、 FASシステムおよびサポート対象スイッチに対する新規および強化されたサポート"^] 。
* の更新について説明します。 https://docs.netapp.com/us-en/ontap-automation/whats_new.html["ONTAP REST API"^]


ONTAPを最新バージョンにアップグレードするには、を参照してくださいlink:../upgrade/create-upgrade-plan.html["ONTAPをアップグレードする準備"]。



== ネットワーク

[cols="30%,70%"]
|===
| 更新 | 説明 


 a| 
xref:../networking/ipsec-prepare.html[IPsec ハードウェア オフロード IPv6 サポート]
 a| 
IPsec ハードウェア オフロードのサポートが IPv6 に拡張されました。



 a| 
xref:../networking/configure_network_security_using_federal_information_processing_standards_fips.html[OpenSSL PQCアルゴリズム]
 a| 
ONTAP は、SSL 用のポスト量子コンピューティング暗号化アルゴリズムをサポートしています。これらのアルゴリズムは、将来の潜在的な量子コンピューティング攻撃に対する追加の保護を提供し、SSL FIPS モードが無効になっている場合に利用できます。



 a| 
xref:../networking/configure-backend-encryption.html[ONTAPバックエンドクラスタネットワーク暗号化]
 a| 
ONTAPバックエンド クラスタ ネットワーク上の転送中のデータに対して TLS 暗号化を有効にすることができます。



 a| 
xref:../high-availability/ha-pair-encryption.html[ONTAP HAトラフィックネットワーク暗号化]
 a| 
高可用性 (HA) ペアのノード間のトラフィックの暗号化を有効にすることができます。

|===


== SAN

[cols="30%,70%"]
|===
| 更新 | 説明 


 a| 
xref:../san-admin/nvme-copy-offload.html[NVMeコピーオフロード]
 a| 
NVMe コピー オフロードにより、NVMe ホストはコピー操作をその CPU からONTAPストレージ コントローラの CPU にオフロードできるようになります。ホストは、CPU リソースをアプリケーション ワークロード用に予約しながら、ある NVMe 名前空間から別の NVMe 名前空間にデータをコピーできます。

|===


== S3オブジェクトストレージ

[cols="30%,70%"]
|===
| 更新 | 説明 


 a| 
xref:../s3-snapshots/list-restore-s3-snapshot.html[ポイントインタイムの S3 スナップショット復元のサポート]
 a| 
S3 バケット内の破損したオブジェクトを復元したり、既存のバケットにバケット全体を復元したりする機能を提供します。

|===


== セキュリティ

[cols="30%,70%"]
|===
| 更新 | 説明 


 a| 
xref:../anti-ransomware/use-cases-restrictions-concept.html#supported-configurations[ARP/AI のFlexGroupボリューム サポート]
 a| 
NetApp FlexGroupボリュームは ARP/AI をサポートし、高度な機械学習ベースのランサムウェア検出と保護を提供します。  ONTAP 9.17.1 以前では、 FlexGroupボリュームでは第 1 世代の ARP のみが使用可能でした。 ONTAP 9.18.1 以降、 FlexGroupボリュームは、オンプレミスのONTAPプラットフォーム (AFFおよびFAS) と仮想ONTAPデプロイメント ( Cloud Volumes ONTAPおよびONTAP Select を含む) の両方でFlexVolボリュームと同等になります。その結果、ARP/AI はFlexVolとFlexGroupボリュームの両方のデフォルトの ARP テクノロジーになります。

|===


== ストレージリソース管理の機能拡張

[cols="30%,70%"]
|===
| 更新 | 説明 


 a| 
xref:../performance-admin/adaptive-qos-policy-groups-task.html[SVMおよびボリューム上の2レベルのネストされたQoSポリシーグループのサポート]
 a| 
QoS ポリシーを SVM と SVM の下のボリュームに同時に割り当てることができます。



 a| 
xref:../flexcache/create-volume-task.html[SVM-DR関係で元のボリュームのSVM FlexCacheボリュームを作成する]
 a| 
SVM-DR 関係の一部である元のボリュームの SVM FlexCacheボリュームを作成できます。

|===