---
permalink: release-notes/whats-new-9161.html 
sidebar: sidebar 
keywords: 'what"s new, release notes, 9.16.1' 
summary: ONTAP 9.16.1で利用できる新機能について説明します。 
---
= ONTAP 9.16.1の新機能
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
ONTAP 9.16.1で利用できる新機能について説明します。

最近のONTAP 9リリースにおける既知の問題、制限事項、およびアップグレードに関する注意事項の詳細については、 https://library.netapp.com/ecm/ecm_download_file/ECMLP2492508["ONTAP 9 リリース ノート"^]を参照してください。リリース ノートにアクセスするには、NetAppアカウントでサインインするか、アカウントを作成する必要があります。

* 新しい機能と強化された機能について学びます https://docs.netapp.com/us-en/ontap-metrocluster/releasenotes/mcc-new-features.html["ONTAP MetroCluster機能"^]。
*  https://docs.netapp.com/us-en/asa-r2/release-notes/whats-new-9171.html["NetApp ASA r2ストレージシステム向けの新しいONTAPソフトウェア機能と強化されたONTAPソフトウェア機能"^]について学びましょう。
*  https://docs.netapp.com/us-en/ontap-systems/whats-new.html["AFF、ASA、FASシステムおよびサポート対象スイッチに対する新規および強化されたサポート"^]について学びましょう。
*  https://docs.netapp.com/us-en/ontap-automation/whats_new.html["ONTAP REST API"^]のアップデートについて学習します。


ONTAPの最新バージョンにアップグレードするには、link:../upgrade/create-upgrade-plan.html["ONTAPのアップグレードの準備"]を参照してください。



== データ保護

[cols="30%,70%"]
|===
| 更新 | 概要 


 a| 
xref:../snapmirror-active-sync/index.html[SnapMirrorアクティブ同期のマルチノードサポート]
 a| 
以前の2ノードの制限から拡張され、SnapMirror Active Syncは4ノードのクラスターをサポートし、より大きなワークロードのデータ複製を可能にします。



 a| 
xref:../data-protection/cloud-backup-with-snapmirror-task.html[SnapMirror クラウドでのファンアウト関係の作成のサポート]
 a| 
SnapMirrorクラウドは、同一のソースボリュームまたはFlexGroupから2つの異なるオブジェクトストアへのファンアウト関係をサポートします。ファンアウトは、2つのオブジェクトストア、およびオブジェクトストア内の1つまたは2つのバケットに行うことができます。



 a| 
xref:../data-protection/cloud-backup-with-snapmirror-task.html[移行済みボリュームからのSnapMirrorクラウド バックアップをサポート]
 a| 
SnapMirror クラウドは、既存の ONTAP REST API を使用してクラウドに移行されたボリュームのバックアップをサポートします。この新機能では、再ベースライン操作を実行することなく、クラウドに移行されたボリュームから同じ宛先オブジェクト ストア エンドポイントへの SnapMirror クラウド バックアップをサポートします。FlexVol ボリュームと FlexGroup ボリュームの両方がサポートされます。

|===


== ネットワーク

[cols="30%,70%"]
|===
| 更新 | 概要 


 a| 
xref:../networking/configure_virtual_ip_vip_lifs.html#set-up-border-gateway-protocol-bgp[BGPピア グループのMD5認証をサポート]
 a| 
ONTAPは、BGPセッションを保護するために、BGPピアグループでMD5認証をサポートしています。MD5を有効にすると、BGPセッションは承認されたピア間でのみ確立および処理されるため、攻撃者がBGPアップデートを偽装してネットワークに偽のルーティング情報を挿入しようとするルートハイジャックなどの攻撃を防止できます。



 a| 
xref:../networking/ipsec-prepare.html[IPSecハードウェア オフロードをサポート]
 a| 
IPセキュリティ（IPsec）は、移動中データのセキュリティ オプションで、これを使用することでクライアントとONTAPノード間のすべてのIPトラフィックを保護できます。ONTAP 9.8から使用できるようになったこのプロトコルは、ソフトウェアとしてのみ実装されています。ONTAP 9.16.1以降では、暗号化や整合性チェックなど一部の計算負荷が高い処理を、ストレージ ノードに取り付けられたサポート対象のネットワーク インターフェイス コントローラ（NIC）カードにオフロードするオプションがあります。このハードウェア オフロード オプションを使用すると、IPsecで保護されたネットワーク トラフィックのパフォーマンスとスループットが大幅に向上します。

|===


== S3オブジェクト ストレージ

[cols="30%,70%"]
|===
| 更新 | 概要 


 a| 
S3 オブジェクトのメタデータとタグ付けに対応したマルチプロトコル S3 バケットのサポート
 a| 
ONTAP 9.16.1以降、S3オブジェクトのタグ付けは、非マルチプロトコルONTAP S3バケットからNASおよびS3マルチプロトコルONTAP S3バケットに拡張されました。タグはS3プロトコルでのみ表示されます。S3クライアントを使用してS3オブジェクトに https://docs.aws.amazon.com/AmazonS3/latest/userguide/object-tagging.html["タグとメタデータ"^]を適用すると、ONTAPにオブジェクトまたはファイルとして保存されたデータのライフサイクル、課金、データカテゴリ、カスタムワークフローを定義できます。BedrockやAthenaなどのAWSデータサービスと統合すると、タグ付けとメタデータは、これらのサービスが提供するデータ処理の中心となります。


NOTE: ネイティブ S3 バケットのタグとユーザー定義メタデータのサポートは ONTAP 9.9.1 から開始されました。



 a| 
xref:../s3-multiprotocol/index.html[マルチプロトコルS3バケットでマルチパート アップロードをサポート]
 a| 
マルチパートアップロードは、S3のコア機能であり、当初からマルチプロトコル非対応のONTAP S3バケットで利用可能でした。ONTAP 9.16.1以降、このコア機能はNASおよびS3マルチプロトコル対応のONTAP S3バケットにも拡張されます。



 a| 
xref:../s3-config/cors-integration.html[ONTAP S3バケットのCross-Origin Resource Sharing（CORS）をサポート]
 a| 
Cross-Origin Resource Sharing（CORS）により、Webアプリケーションの可能性を最大限に引き出せます。CORSを使用すると、あるドメインのクライアント アプリケーションと別のドメインのリソースが、シームレスにやり取りできます。CORSサポートを統合することで、リソースへの選択的クロスオリジン アクセスにより、ONTAP S3ベースのWebアプリケーションを強化できます。



 a| 
xref:../s3-snapshots/index.html[ONTAPでONTAP S3バケットのSnapshotの作成をサポート]
 a| 
ONTAP S3バケットの読み取り専用ポイントインタイムSnapshotを生成できます。S3 Snapshot機能を使用すると、Snapshotを手動で作成したり、Snapshotポリシーを通じて自動的に生成したりできます。また、S3クライアントを介して、S3 Snapshotを表示、参照、削除したり、Snapshotのコンテンツをリストアしたりできます。

|===


== SAN

[cols="30%,70%"]
|===
| 更新 | 概要 


 a| 
xref:../san-admin/enable-space-allocation.html[NVMeスペース割り当て解除をデフォルトで有効化]
 a| 
NVMe名前空間では、スペースの割り当て解除（「ホールパンチ」または「アンマップ」とも呼ばれます）がデフォルトで有効になっています。スペースの割り当て解除により、ホストは名前空間から未使用のブロックを解放し、スペースを再利用できるようになります。これにより、特にデータの入れ替え頻度が高いファイルシステムでは、全体的なストレージ効率が大幅に向上します。

|===


== セキュリティ

[cols="30%,70%"]
|===
| 更新 | 概要 


 a| 
xref:../multi-admin-verify/index.html#rule-protected-commands[マルチ管理者検証用に拡張された適格なルール保護コマンド セット]
 a| 
管理者は、マルチ管理者認証ルールを作成して整合グループを保護できます。作成できるルールには、作成、削除、変更の処理、整合グループのSnapshotの作成と削除、その他のコマンドなどに関するものがあります。



 a| 
xref:../anti-ransomware/index.html[Autonomous Ransomware Protection with AI（ARP / AI）の機能拡張]
 a| 
ARPが新しいAI機能によってアップグレードされ、ランサムウェア攻撃を99%の精度と再現率で検出して対応できるようになりました。AIは包括的なデータセットでトレーニングされているため、FlexVolでARPを実行するのに必要な学習期間がなくなり、ARP / AIはすぐにアクティブ モードで開始されます。またARP / AIには自動更新機能もあり、最新の脅威に対する継続的な保護と耐障害性が確保されます。


NOTE: 現在、ARP / AI機能ではNASのみがサポートされます。自動更新機能では、System Managerでの導入に使用できる新しいセキュリティ ファイルが表示されますが、これらの更新内容はNASワークロードの保護にのみ適用されます。



 a| 
xref:../nvme/set-up-tls-secure-channel-nvme-task.html[NVMe / TCP over TLS 1.3]
 a| 
IPSecよりもシンプルな構成と優れたパフォーマンスで、NVMe / TCPをプロトコル層で「ネットワーク転送中に」保護します。



 a| 
FabricPoolオブジェクト ストアの通信でTLS 1.3をサポート
 a| 
ONTAPで、FabricPoolオブジェクト ストアの通信にTLS 1.3を使用できるようになりました。



 a| 
xref:../authentication/overview-oauth2.html[Microsoft Entra ID用のOAuth 2.0]
 a| 
ONTAP 9 14.1で初めて導入されたOAuth 2.0のサポートが拡張され、標準のOAuth 2.0要求を使用するMicrosoft Entra ID許可サーバ（旧称Azure AD）に対応しました。加えて、UUIDスタイル値に基づくEntra ID標準グループ要求が、新しいグループとロールのマッピング機能を介してサポートされます。新たに外部ロールのマッピング機能も導入されました。この機能はEntra IDでテストされていますが、サポートされている任意の許可サーバで使用できます。

|===


== ストレージ効率

[cols="30%,70%"]
|===
| 更新 | 概要 


 a| 
xref:../volumes/qtrees-partition-your-volumes-concept.html[qtreeのパフォーマンス監視にレイテンシの指標と過去の統計を追加]
 a| 
以前のリリースのONTAPでは、読み取りや書き込みなど、いくつかのカテゴリについて、1秒あたりのI/O処理数やスループットなど、qtreeの使用状況を堅牢なリアルタイム指標で確認できました。ONTAP 9 .16.1以降では、リアルタイムのレイテンシ統計へのアクセスや、アーカイブされた履歴データの表示も可能になります。これらの新機能により、ITストレージ管理者は、システムのパフォーマンスをより詳細に把握し、より長期間にわたる傾向を分析できます。これにより、データセンターとクラウド ストレージ リソースの運用と計画に関して、より多くの情報に基づくデータ主体の意思決定を行えます。

|===


== ストレージ リソース管理の機能拡張

[cols="30%,70%"]
|===
| 更新 | 概要 


 a| 
xref:../volumes/manage-svm-capacity.html[ストレージ制限が有効になっている SVM でのデータ保護ボリュームのサポート]
 a| 
ストレージ制限が有効になっている SVM には、データ保護ボリュームを含めることができます。カスケードのない非同期ディザスタ リカバリ関係、同期ディザスタ リカバリ関係、およびリストア関係にある FlexVol ボリュームがサポートされています。

[NOTE]
====
ONTAP 9.15.1 以前のリリースでは、データ保護ボリューム、SnapMirror 関係内のボリューム、または MetroCluster 構成内のボリュームを含む SVM に対してストレージ制限を設定することはできません。

====


 a| 
xref:../flexgroup/enable-adv-capacity-flexgroup-task.html[FlexGroupの高度な容量分散をサポート]
 a| 
高度な容量バランス調整を有効にすると、非常に大きなファイルが増えて 1 つのメンバー ボリューム上のスペースを消費する場合に、FlexGroupメンバー ボリューム間でファイル内のデータが分散されます。



 a| 
xref:../svm-migrate/index.html[MetroCluster構成移行時のSVMデータ移動をサポート]
 a| 
ONTAPは次のMetroCluster SVM移行をサポートしています：

* 非MetroCluster構成とMetroCluster IP構成間でのSVMの移行
* 2つのMetroCluster IP構成間でのSVMの移行
* MetroCluster FC構成からMetroCluster IP構成へのSVMの移行


|===


== System Manager

[cols="30%,70%"]
|===
| 更新 | 概要 


 a| 
xref:../authentication-access-control/webauthn-mfa-overview.html[System Managerでフィッシング耐性があるWebAuthn多要素認証をサポート]
 a| 
ONTAP 9.16.1でWebAuthn MFAログインがサポートされ、System Managerにログインする際に、2つ目の認証方法としてハードウェア セキュリティ キーを使用できるようになりました。

|===