---
sidebar: sidebar 
permalink: fabricpool/add-connection-to-cloud-task.html 
keywords: netapp, ontap, connection, cloud, cloud insights, cloud agent 
summary: ONTAP 9.9.9..0 以降では、 System Manager を使用してクラウドへの接続を追加できます。 
---
= クラウドへの接続を追加します
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
ONTAP 9.9.9..0 以降では、 System Manager を使用してクラウドへの接続を追加できます。

まず、 NetApp Cloud Insights を使用してコレクタを設定します。設定プロセスでは、 Cloud Insights で生成されたペアリングコードをコピーし、 System Manager を使用してクラスタにログオンします。そこで、そのペアリングコードを使用してクラウド接続を追加します。残りのプロセスは Cloud Insights で実行します。

[NOTE]
====
Cloud Volumes ONTAP からCloud Insights サービスへの接続を追加するときにプロキシサーバを使用するオプションを選択する場合は、URLを確認してください https://example.com[] プロキシサーバからアクセスできます。には、「HTTPプロキシ設定が無効です」というメッセージが表示されます https://example.com[] にアクセスできません。

====
.手順
. Cloud Insights で、コレクタを設定するプロセス中に、生成されたペアリングコードをコピーします。
. ONTAP 9.9.0 以降の System Manager を使用して、クラスタにログオンします。
. [ クラスタ ]>[ 設定 *] を選択します。
. [ クラウド接続 ] セクションで、 [ * 追加 ] を選択して接続を追加します。
. 接続の名前を入力し、表示されたスペースにペアリングコードを貼り付けます。
. 「 * 追加」を選択します。
. Cloud Insights に戻り、コレクタの設定を完了します。


追加情報 About Cloud Insights については、を参照してください link:https://docs.netapp.com/us-en/cloudinsights/task_dc_na_cloud_connection.html["Cloud Insights のドキュメント"^]。
