---
permalink: fabricpool/commands-manage-aggregates-reference.html 
sidebar: sidebar 
keywords: commands, managing, aggregates, storage aggregate object-store config 
summary: FabricPool のオブジェクトストアを管理するには、 storage aggregate object-store コマンドを使用します。FabricPool のアグリゲートを管理するには、 storage aggregate コマンドを使用します。FabricPool 用のボリュームを管理するには、 volume コマンドを使用します。 
---
= FabricPool を使用したアグリゲートの管理用コマンド
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
を使用します `storage aggregate object-store` FabricPool のオブジェクトストアを管理するコマンドです。を使用します `storage aggregate` FabricPool のアグリゲートを管理するコマンドです。を使用します `volume` FabricPool 用のボリュームを管理するコマンドです。

|===


| 状況 | 使用するコマンド 


 a| 
オブジェクトストアの設定を定義して、 ONTAP からアクセスできるようにします
 a| 
`storage aggregate object-store config create`



 a| 
オブジェクトストア設定の属性を変更する
 a| 
`storage aggregate object-store config modify`



 a| 
既存のオブジェクトストア設定の名前を変更する
 a| 
`storage aggregate object-store config rename`



 a| 
オブジェクトストアの設定を削除する
 a| 
`storage aggregate object-store config delete`



 a| 
オブジェクトストア設定のリストを表示します
 a| 
`storage aggregate object-store config show`



 a| 
新規または既存の FabricPool にミラーとして 2 つ目のオブジェクトストアを接続します
 a| 
`storage aggregate object-store mirror` を使用 `-aggregate` および `-name` admin権限レベルのパラメータ



 a| 
既存の FabricPool ミラーからオブジェクトストアミラーを削除する
 a| 
`storage aggregate object-store unmirror` を使用 `-aggregate` および `-name` admin権限レベルのパラメータ



 a| 
FabricPool ミラー再同期ステータスを監視します
 a| 
`storage aggregate object-store show-resync-status`



 a| 
FabricPool ミラーの詳細を表示します
 a| 
`storage aggregate object-store show`



 a| 
FabricPool ミラー構成でオブジェクトストアミラーを昇格してプライマリオブジェクトストアを置き換えます
 a| 
`storage aggregate object-store modify` を使用 `-aggregate` admin権限レベルのパラメータ



 a| 
オブジェクトストアをアグリゲートに接続せずにオブジェクトストアのレイテンシとパフォーマンスをテストする
 a| 
`storage aggregate object-store profiler start` を使用 `-object-store-name` および `-node` advanced権限レベルのパラメータ



 a| 
オブジェクトストアプロファイラのステータスを監視する
 a| 
`storage aggregate object-store profiler show` を使用 `-object-store-name` および `-node` advanced権限レベルのパラメータ



 a| 
実行中のオブジェクトストアプロファイラを中止します
 a| 
`storage aggregate object-store profiler abort` を使用 `-object-store-name` および `-node` advanced権限レベルのパラメータ



 a| 
FabricPool を使用するために、オブジェクトストアをアグリゲートに接続します
 a| 
`storage aggregate object-store attach`



 a| 
FabricPool を使用するために、 FlexGroup ボリュームを含むアグリゲートにオブジェクトストアを接続します
 a| 
`storage aggregate object-store attach` を使用 `allow-flexgroup` `true`



 a| 
FabricPool 対応アグリゲートに接続されているオブジェクトストアの詳細を表示します
 a| 
`storage aggregate object-store show`



 a| 
階層化スキャンで使用されるアグリゲートのスペース不足しきい値を表示します
 a| 
`storage aggregate object-store show` を使用 `-fields tiering-fullness-threshold` advanced権限レベルのパラメータ



 a| 
FabricPool 対応アグリゲートに接続されているオブジェクトストアのスペース使用量を表示します
 a| 
`storage aggregate object-store show-space`



 a| 
FabricPool で使用されていないアグリゲートで Inactive Data Reporting を有効にする
 a| 
`storage aggregate modify` を使用 `-is-inactive-data-reporting-enabled true` パラメータ



 a| 
アグリゲートでアクセス頻度の低いデータのレポートが有効になっているかどうかを表示する
 a| 
`storage aggregate show` を使用 `-fields is-inactive-data-reporting-enabled` パラメータ



 a| 
アグリゲート内のコールドユーザデータの量に関する情報を表示します
 a| 
`storage aggregate show-space` を使用 `-fields performance-tier-inactive-user-data,performance-tier-inactive-user-data-percent` パラメータ



 a| 
次の項目を指定して、 FabricPool 用のボリュームを作成します。

* 階層化ポリシー
* 階層化の最小クーリング期間（の `snapshot-only` または `auto` 階層化ポリシー）

 a| 
`volume create`

* を使用します `-tiering-policy` 階層化ポリシーを指定するパラメータ。
* を使用します `-tiering-minimum-cooling-days` 階層化の最小クーリング期間を指定するには、advanced権限レベルのパラメータを使用します。




 a| 
FabricPool のボリュームを変更し、以下を変更する

* 階層化ポリシー
* 階層化の最小クーリング期間（の `snapshot-only` または `auto` 階層化ポリシー）

 a| 
`volume modify`

* を使用します `-tiering-policy` 階層化ポリシーを指定するパラメータ。
* を使用します `-tiering-minimum-cooling-days` 階層化の最小クーリング期間を指定するには、advanced権限レベルのパラメータを使用します。




 a| 
次のような、ボリュームに関連する FabricPool 情報を表示する

* 階層化の最小クーリング期間
* コールドユーザデータの量

 a| 
`volume show`

* を使用します `-fields tiering-minimum-cooling-days` 階層化の最小クーリング期間を表示するための、advanced権限レベルのパラメータ。
* を使用します `-fields performance-tier-inactive-user-data,performance-tier-inactive-user-data-percent` コールドユーザデータの量を表示するためのパラメータ。




 a| 
ボリュームを FabricPool の内外に移動します
 a| 
`volume move start` を使用します `-tiering-policy` ボリュームの階層化ポリシーを指定するオプションのパラメータ。



 a| 
FabricPool で参照されていないスペースを再生するしきい値（デフラグしきい値）を変更します
 a| 
`storage aggregate object-store modify` を使用 `-unreclaimed-space-threshold` advanced権限レベルのパラメータ



 a| 
階層化スキャンで FabricPool のデータ階層化を開始する前に、アグリゲートの使用率のしきい値を変更します

FabricPool は、ローカル階層の容量が 98% に達するまで、コールドデータをクラウド階層に階層化し続けます。
 a| 
`storage aggregate object-store modify` を使用 `-tiering-fullness-threshold` advanced権限レベルのパラメータ



 a| 
FabricPool で参照されていないスペースを再生するしきい値を表示します
 a| 
`storage aggregate object-store show` または `storage aggregate object-store show-space` コマンドにを指定します `-unreclaimed-space-threshold` advanced権限レベルのパラメータ

|===