---
permalink: fabricpool/create-mirror-task.html 
sidebar: sidebar 
keywords: creating, fabricpool, mirror 
summary: FabricPool ミラーを作成するには、2つのオブジェクトストアを1つの FabricPool に接続します。既存の単一オブジェクトストア FabricPool 構成に2つ目のオブジェクトストアを接続することで FabricPool ミラーを作成することも、新しい単一オブジェクトストア FabricPool 構成を作成してから2つ目のオブジェクトストアを接続することもできます。MetroCluster 構成でも FabricPool ミラーを作成できます。 
---
= ONTAP FabricPoolミラーを作成する
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
FabricPool ミラーを作成するには、2つのオブジェクトストアを1つの FabricPool に接続します。既存の単一オブジェクトストア FabricPool 構成に2つ目のオブジェクトストアを接続することで FabricPool ミラーを作成することも、新しい単一オブジェクトストア FabricPool 構成を作成してから2つ目のオブジェクトストアを接続することもできます。MetroCluster 構成でも FabricPool ミラーを作成できます。

.開始する前に
*  `storage aggregate object-store config`コマンドを使用して2つのオブジェクト ストアをすでに作成しておく必要があります。
* オンプレミスのMetroCluster構成でFabricPoolミラーを作成する場合：
+
** MetroClusterのセットアップと設定がすでに完了している必要があります
** 選択したクラスターにオブジェクト ストア構成を作成しておく必要があります。
+
両方のクラスタでMetroCluster構成のFabricPoolミラーを作成する場合、両方のクラスタでオブジェクトストア構成を作成している必要があります。

** MetroCluster構成にオンプレミスのオブジェクト ストアを使用していない場合は、次のいずれかのシナリオが存在することを確認する必要があります：
+
*** オブジェクト ストアは異なるアベイラビリティ ゾーンに存在します
*** オブジェクト ストアは、複数のアベイラビリティ ゾーンにオブジェクトのコピーを保存するように構成されている
+
link:setup-object-stores-mcc-task.html["MetroCluster構成でのFabricPool用オブジェクト ストアのセットアップ"]







.タスク概要
FabricPoolミラーに使用するオブジェクト ストアは、プライマリ オブジェクト ストアとは異なる必要があります。

FabricPoolミラーを作成する手順は、MetroCluster構成と非MetroCluster構成の両方で同じです。

.手順
. 既存のFabricPool構成を使用していない場合は、 `storage aggregate object-store attach`コマンドを使用してオブジェクト ストアをローカル層に接続し、新しい構成を作成します。
+
この例では、オブジェクト ストアをローカル層に接続して新しいFabricPoolを作成します。

+
[listing]
----
cluster1::> storage aggregate object-store attach -aggregate aggr1 -name my-store-1
----
.  `storage aggregate object-store mirror`コマンドを使用して、2番目のオブジェクト ストアをローカル層に接続します。
+
この例では、2 番目のオブジェクト ストアをローカル階層に接続してFabricPoolミラーを作成します。

+
[listing]
----
cluster1::> storage aggregate object-store mirror -aggregate aggr1 -name my-store-2
----


.関連情報
* link:https://docs.netapp.com/us-en/ontap-cli/storage-aggregate-object-store-attach.html["storage aggregate object-store attach"^]
* link:https://docs.netapp.com/us-en/ontap-cli/search.html?q=storage+aggregate+object-store+config["ストレージ アグリゲート オブジェクトストア設定"^]
* link:https://docs.netapp.com/us-en/ontap-cli/storage-aggregate-object-store-mirror.html["ストレージ アグリゲート オブジェクトストア ミラー"^]

