---
permalink: fabricpool/enable-disable-volume-cloud-write-task.html 
sidebar: sidebar 
keywords: creating, volume, fabricpool, cloud write, enable, disable 
summary: ONTAP 9.14.1以降では、FabricPoolの新規または既存のボリュームに対してクラウド書き込みモードを有効または無効にすることで、NFSクライアントがクラウドにデータを直接書き込むことができます。 
---
= ボリュームをクラウドに直接書き込むための有効化と無効化
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
ONTAP 9 14.1以降では、FabricPoolの新規または既存のボリュームに対してクラウドへの直接書き込みを有効または無効にすることで、NFSクライアントが階層化スキャンを待たずにクラウドに直接データを書き込むことができます。SMBクライアントは、クラウドの書き込みが有効なボリュームの高パフォーマンス階層に引き続き書き込みます。cloud-writeモードはデフォルトで無効になっています。

クラウドに直接書き込む機能は、ローカル階層でクラスタでサポートできない大量のデータがクラスタに転送されるなど、移行のような場合に役立ちます。cloud-writeモードを使用しない場合は、移行中に少量のデータが転送されてから階層化され、移行が完了するまで再び転送されて階層化されます。cloud-writeモードを使用すると、データがローカル階層に転送されないため、この種の管理は不要になります。

.開始する前に
* クラスタ管理者またはSVM管理者である必要があります。
* advanced権限レベルが必要です。
* 読み取り/書き込みタイプのボリュームである必要があります。
* ボリュームの階層化ポリシーが「すべて」である必要があります。




== ボリューム作成時のクラウドへの直接書き込みを可能にする

.手順
. 権限レベルをadvancedに設定します。
+
[source, cli]
----
set -privilege advanced
----
. ボリュームを作成し、cloud-writeモードを有効にします。
+
[source, cli]
----
volume create -volume <volume name> -is-cloud-write-enabled <true|false> -aggregate <local tier name>
----
+
次の例は、FabricPoolローカル階層（aggr1）に、クラウド書き込みを有効にしてvol1という名前のボリュームを作成します。

+
[listing]
----
volume create -volume vol1 -is-cloud-write-enabled true -aggregate aggr1
----




== 既存のボリュームのクラウドへの直接書き込みを可能にする

.手順
. 権限レベルをadvancedに設定します。
+
[source, cli]
----
set -privilege advanced
----
. ボリュームを変更してcloud-writeモードを有効にします。
+
[source, cli]
----
volume modify -volume <volume name> -is-cloud-write-enabled <true|false> -aggregate <local tier name>
----
+
次の例は、FabricPoolローカル階層（aggr1）でクラウド書き込みを有効にしたvol1という名前のボリュームを変更します。

+
[listing]
----
volume modify -volume vol1 -is-cloud-write-enabled true -aggregate aggr1
----




== ボリュームのクラウドへの直接書き込みを無効にする

.手順
. 権限レベルをadvancedに設定します。
+
[source, cli]
----
set -privilege advanced
----
. cloud-writeモードを無効にします。
+
[source, cli]
----
volume modify -volume <volume name> -is-cloud-write-enabled <true|false> -aggregate <aggregate name>
----
+
次の例は、vol1という名前のボリュームを作成し、クラウド書き込みを有効にします。

+
[listing]
----
volume modify -volume vol1 -is-cloud-write-enabled false -aggregate aggr1
----

