---
permalink: fabricpool/fabricpool-object-deletion.html 
sidebar: sidebar 
keywords: fabricpool, fabric pool, tiering, delete, defrag, unreclaimed, threshold 
summary: FabricPoolは、オブジェクト内のブロックの一定割合がONTAPによって参照されなくなった後に、そのオブジェクトを削除します。 
---
= ONTAP FabricPoolオブジェクトの削除とデフラグをカスタマイズする
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
FabricPoolは、接続されているオブジェクトストアからブロックを削除しません。代わりに、FabricPoolは、オブジェクト内のブロックの一定割合がONTAPによって参照されなくなった後にオブジェクトを削除します。

たとえば、Amazon S3に階層化された4MBのオブジェクトには、1,024個の4KBブロックがあります。デフラグと削除は、205個未満の4KBブロック（1,024個の20％）がONTAPによって参照されるまで発生しません。十分な数のブロック（1,024個）に参照がない場合、元の4MBオブジェクトが削除され、新しいオブジェクトが作成されます。

未回収領域のしきい値（パーセンテージ）をカスタマイズし、オブジェクトストアごとに異なるデフォルトレベルを設定できます。デフォルト設定は次のとおりです：

|===


| オブジェクト ストア | ONTAP 9.8以降 | ONTAP 9.7から9.4 | ONTAP 9.3以前 | Cloud Volumes ONTAP 


 a| 
Amazon S3
 a| 
20%
 a| 
20%
 a| 
0%
 a| 
30%



 a| 
Google Cloud Storage
 a| 
20%
 a| 
12%
 a| 
N/A
 a| 
35%



 a| 
Microsoft Azure Blob Storage
 a| 
25%
 a| 
15%
 a| 
N/A
 a| 
35%



 a| 
NetApp ONTAP S3
 a| 
40%
 a| 
N/A
 a| 
N/A
 a| 
N/A



 a| 
NetApp StorageGRID
 a| 
40%
 a| 
40%
 a| 
0%
 a| 
N/A

|===


== 未回収スペースのしきい値

デフォルトの未回収領域のしきい値設定を変更すると、許容されるオブジェクトの断片化の量が増減します。断片化を軽減すると、追加のオブジェクト ストア リソース（読み取りと書き込み）を犠牲にして、クラウド階層で使用される物理容量が削減されます。



=== しきい値の削減

追加費用を回避するには、ストレージコストは削減されるものの読み取りコストは増加するオブジェクトストアの料金体系を利用する際に、未回収領域のしきい値を下げることを検討してください。例としては、Amazon の Standard-IA や Azure Blob Storage の Cool などが挙げられます。

例えば、法的な理由で保存されている10年前のプロジェクトのボリュームを階層化する場合、Standard-IAやCoolなどの料金体系を使用すると、標準料金体系を使用する場合よりもコストが低くなる可能性があります。このようなボリュームでは、オブジェクトのデフラグに必要な読み取りなど、読み取りコストは高くなりますが、頻繁に発生する可能性は低いでしょう。



=== しきい値の増加

あるいは、オブジェクトの断片化により、ONTAPが参照しているデータに必要な容量よりも大幅に多くのオブジェクト ストア容量が使用される場合は、未利用スペースのしきい値を増やすことを検討してください。例えば、すべてのオブジェクトが最大許容範囲まで均等に断片化されている最悪のシナリオで、未利用スペースのしきい値を 20% に設定すると、クラウド層の総容量の 80% がONTAPによって参照されない可能性があります。例：

ONTAPで参照される2TBとONTAPで参照されない8TBを合わせて、クラウド階層で使用される総容量は10TBになります。

このような状況では、再利用されない領域のしきい値を増やすか、ボリュームの最小冷却日数を増やして、参照されていないブロックによって使用される容量を減らすことが有利になる可能性があります。

[NOTE]
====
システムがオブジェクトをデフラグし、ストレージ効率を向上させると、参照ブロックをより効率的な新しいオブジェクトに書き込むことで、基盤となるファイルが断片化される可能性があります。未回収領域のしきい値を大幅に増やすと、ストレージ効率は向上しますが、シーケンシャル リード のパフォーマンスは低下します。

この追加アクティビティにより、AWS、Azure、Google などのサードパーティの Amazon S3 プロバイダーからのコストが増加します。

NetAppは、未回収領域のしきい値を60%以上に増やさないようにすることを推奨します。

====


== 未回収領域のしきい値を変更する

さまざまなオブジェクト ストアの未再利用領域のしきい値のパーセンテージをカスタマイズできます。

.開始する前に
Advanced権限レベルが必要です。

.手順
. デフォルトの未再利用領域のしきい値を変更するには、次のコマンドをカスタマイズして実行します：
+
[source, cli]
----
storage aggregate object-store modify -aggregate <name> -object-store-name <name> -unreclaimed-space-threshold <%> (0%-99%)
----


.関連情報
* link:https://docs.netapp.com/us-en/ontap-cli/storage-aggregate-object-store-modify.html["ストレージ アグリゲート オブジェクトストアの変更"^]

