---
permalink: fabricpool/install-license-aws-azure-ibm-task.html 
sidebar: sidebar 
keywords: installing, fabricpool, license 
summary: 新規に購入した AFF システムには、 FabricPool でネットアップ以外のオブジェクトストア（ AWS S3 、 Azure Blob Storage 、 IBM Cloud Object Storage 、 Alibaba Cloud Object Storage 、 Google Cloud Storage ）を使用する場合のために 10TB の空き容量を含むタームベースライセンスが含まれています。AFF システムで追加の容量が必要な場合、 AFF 以外のシステムでネットアップ以外のオブジェクトストアを使用する場合、または既存のクラスタからアップグレードする場合は、 FabricPool ライセンスが必要になります。 
---
= FabricPool ライセンスをインストールする。
:icons: font
:imagesdir: ../media/


[role="lead"]
新規に購入した AFF システムには、 FabricPool でネットアップ以外のオブジェクトストア（ AWS S3 、 Azure Blob Storage 、 IBM Cloud Object Storage 、 Alibaba Cloud Object Storage 、 Google Cloud Storage ）を使用する場合のために 10TB の空き容量を含むタームベースライセンスが含まれています。AFF システムで追加の容量が必要な場合、 AFF 以外のシステムでネットアップ以外のオブジェクトストアを使用する場合、または既存のクラスタからアップグレードする場合は、 FabricPool ライセンスが必要になります。

FabricPool ライセンスはクラスタ規模のライセンスです。このライセンスには、クラスタ内の FabricPool に関連付けられた AWS S3 、 Azure Blob Storage 、 IBM Cloud Object Storage 、 Alibaba Cloud Object Storage 、または Google Cloud Storage のクラウド階層用に購入する使用容量が設定されています。クラスタ全体での使用量がこの容量を超えないようにする必要があります。ライセンスの使用量の制限を増やす必要がある場合は、営業担当者にお問い合わせください。

FabricPool ライセンスには、恒久ライセンスとタームベースライセンス、 1 年または 3 年ライセンスがあります。

既存のクラスタ用に初めて FabricPool を購入する場合は、 10TB の空き容量を含むタームベースの FabricPool ライセンスが付随します。無期限のライセンスには空き容量は含まれていません。

クラウド階層に NetApp StorageGRID または ONTAP S3 を使用する場合は、ライセンスは必要ありません。使用しているプロバイダに関係なく、 Cloud Volumes ONTAP には FabricPool ライセンスは必要ありません。

このタスクは、 System Manager を使用してクラスタにライセンスファイルをアップロードすることでのみサポートされます。

.手順
. ネットアップサポートサイトから FabricPool ライセンスのネットアップライセンスファイル（ NLF ）をダウンロードします。
+
https://mysupport.netapp.com/site/global/dashboard["ネットアップサポート"]

. System Manager を使用して、 FabricPool ライセンスをクラスタにアップロードします。
+
.. ストレージシステムで実行している ONTAP のリリースに応じて、次の操作を実行します。
+
|===


| 実行内容 | 次の操作を実行します。 


 a| 
ONTAP 9.4 以前
 a| 
[* 構成 *>* ライセンス *] をクリックします。



 a| 
ONTAP 9.5 以降
 a| 
[* Configuration * （設定 * ） ] > [* Cluster * （クラスタ * ） ] > [* Licenses * （ライセンス *

|===
.. [* Cluster Settings （クラスタ設定） ] ペインで、 [* Licenses （ライセンス） ] をクリックします。
.. [ * パッケージ * ] ウィンドウで、 [ * 追加 ] をクリックします。
.. [ * ライセンスパッケージの追加 * ] ダイアログボックスで、 [ * ファイルの選択 * ] をクリックしてダウンロードした NLF を選択し、 [ * 追加 * ] をクリックしてファイルをクラスタにアップロードします。




https://kb.netapp.com/Advice_and_Troubleshooting/Data_Storage_Software/ONTAP_OS/ONTAP_FabricPool_(FP)_Licensing_Overview["ONTAP FabricPool （ FP ）ライセンスの概要"]

http://mysupport.netapp.com/licenses["ネットアップソフトウェアライセンスの検索"]
