---
permalink: fabricpool/move-volume-task.html 
sidebar: sidebar 
keywords: aggregate, local tier, moving, volume, fabricpool, fabric pool, tiering, policy, policies, block, capacity, cold data, 
summary: ローカル階層、接続されたクラウド階層、およびボリューム（ボリューム階層化ポリシー）の両方で行われる変更は、機能に大きな影響を与える可能性があるため、ボリューム移動とFabricPoolの連携について理解しておくことが重要です。 
---
= FabricPool対応のONTAPローカル階層にボリュームを移動する
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
は、link:../volumes/move-volume-task.html["ボリューム移動"]ONTAPがボリュームをあるローカル階層（ソース）から別のローカル階層（デスティネーション）に無停止で移動する方法です。ボリュームの移動はさまざまな理由に基づいて実行できますが、最も一般的な理由はハードウェア ライフサイクル管理、クラスタ拡張、および負荷分散です。

ローカル階層、接続されたクラウド階層、およびボリューム（ボリューム階層化ポリシー）の両方で行われる変更は、機能に大きな影響を与える可能性があるため、ボリューム移動とFabricPoolの連携について理解しておくことが重要です。


NOTE: ONTAP 9.7より前のバージョンでは、ローカル階層を表すために_aggregate_という用語が使用されていました。ONTAPのバージョンに関係なく、ONTAP CLIでは_aggregate_という用語が使用されます。ローカル階層の詳細については、を参照してくださいlink:../disks-aggregates/index.html["ディスクとローカル階層"]。



== デスティネーションローカル階層

ボリューム移動のデスティネーションローカル階層に接続されたクラウド階層がない場合、クラウド階層に格納されているソースボリュームのデータはデスティネーションローカル階層のローカル階層に書き込まれます。

ONTAP 9.8以降では、ボリュームが有効になっている場合、link:determine-data-inactive-reporting-task.html["Inactive Data Reporting"]FabricPoolはボリュームのヒートマップを使用してコールドデータをただちにキューに入れ、デスティネーションローカル階層に書き込まれるとすぐに階層化を開始します。

ONTAP 9.8より前のバージョンでは、ボリュームを別のローカル階層に移動すると、ローカル階層のブロックの非アクティブ期間がリセットされます。たとえば、20日間非アクティブでまだ階層化されていないデータがローカル階層にある「自動」ボリューム階層化ポリシーを使用するボリュームでは、ボリューム移動後、データの温度が0日にリセットされます。



== ボリューム移動の最適化

ONTAP 9.6以降では、ボリューム移動のデスティネーションローカル階層がソースローカル階層と同じバケットを使用する場合、バケットに格納されているソースボリューム上のデータがローカル階層に戻されません。階層化されたデータは保存されたままになり、ローカル階層間で移動しなければならないのはホットデータだけです。この最適化されたボリューム移動により、ネットワーク効率が大幅に向上します。

ボリュームの移動が最適化されていない場合、ネットワークとコンピューティングのトラフィック（読み取り/取得と書き込み/プット）が増加し、ONTAPクラスタとオブジェクトストアの需要が増加します。パブリックオブジェクトストアへの階層化のコストが上昇する可能性があります。

[NOTE]
====
一部の構成は最適化されたボリューム移動と互換性がありません

* ボリューム移動時の階層化ポリシーの変更
* 異なる暗号化キーを使用するソースとデスティネーションのローカル階層
* FlexCloneボリューム
* FlexCloneノオヤホリユウム
* MetroCluster（ONTAP 9.8以降での最適化されたボリューム移動をサポート）
* 非同期FabricPoolミラーバケット


====
ボリューム移動のデスティネーションローカル階層にクラウド階層が接続されている場合は、クラウド階層に格納されているソースボリューム上のデータが最初にデスティネーションローカル階層のローカル階層に書き込まれます。このアプローチがボリューム階層化ポリシーに適している場合は、デスティネーションローカル階層のクラウド階層に書き込まれます。

最初にローカル階層にデータを書き込むと、ボリューム移動のパフォーマンスが向上し、カットオーバー時間が短縮されます。ボリューム移動の実行時にボリューム階層化ポリシーが指定されていない場合、デスティネーション ボリュームはソース ボリュームの階層化ポリシーを使用します。

ボリューム移動の実行時に別の階層化ポリシーを指定した場合、指定した階層化ポリシーでデスティネーションボリュームが作成され、ボリューム移動は最適化されません。



=== ボリュームメタデータ

ONTAPには、ボリューム移動が最適化されているかどうかに関係なく、すべてのデータの場所に関する情報（ローカルデータと階層化データの両方）が格納されます。ボリュームをあるローカル階層から別のローカル階層に移動する場合は、この情報をデスティネーションローカル階層にも移動する必要があります。このメタデータは常にローカル階層に残りますが、階層化されたデータの量によっては、ボリューム移動プロセスの所要時間が想定よりも長くなることがあります。

たとえば、300TBのボリューム移動が最適化された場合、300TBのコールドデータをあるローカル階層から別のローカル階層に移動する必要はありません（または、オブジェクトストアに対して300TBの読み取りと300TBの書き込みがトリガーされます）。ただし、300TBのデータ（この例では約15TBのデータ）に関連付けられたメタデータをデスティネーションローカル階層に書き込む必要があります。

コマンドで報告される「スループット」は `volume move show`、クラウド階層から移動されるデータのスループットではなく、メタデータがローカルで更新されるスループットを表している点に注意してください。


NOTE: SVM DR関係では、ソースボリュームとデスティネーションボリュームで同じ階層化ポリシーを使用する必要があります。

.手順
. コマンドを使用して `volume move start`、ソースローカル階層からデスティネーションローカル階層にボリュームを移動します。


.ボリューム移動例
次の例は、 `vs1`SVMという名前のボリュームをFabricPool対応のローカル階層に `dest_FabricPool`移動します `myvol2`。

[listing]
----
cluster1::> volume move start -vserver vs1 -volume myvol2
-destination-aggregate dest_FabricPool
----