---
permalink: fabricpool/replace-existing-object-store-mirror-task.html 
sidebar: sidebar 
keywords: replacing, existing, object, store, fabricpool, mirror 
summary: FabricPool ミラーテクノロジを使用して、あるオブジェクトストアを別のオブジェクトストアに置き換えることができます。新しいオブジェクトストアは、元のオブジェクトストアと同じクラウドプロバイダを使用する必要はありません。 
---
= FabricPool ミラーを使用して既存のオブジェクトストアを置き換えます
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
FabricPool ミラーテクノロジを使用して、あるオブジェクトストアを別のオブジェクトストアに置き換えることができます。新しいオブジェクトストアは、元のオブジェクトストアと同じクラウドプロバイダを使用する必要はありません。

.このタスクについて
元のオブジェクトストアを、別のクラウドプロバイダを使用するオブジェクトストアに置き換えることができます。たとえば、 AWS をクラウドプロバイダとして使用しているオブジェクトストアが Azure を使用するオブジェクトストアに置き換えることも、その逆も可能です。ただし、オブジェクトサイズは新しいオブジェクトストアと元のオブジェクトストアで同じである必要があります。

.手順
. 「 storage aggregate object-store mirror 」コマンドを使用して、既存の FabricPool に新しいオブジェクトストアを追加して、 FabricPool ミラーを作成します。
+
[listing]
----
cluster1::> storage aggregate object-store mirror -aggregate aggr1 -name my-AZURE-store
----
. 「 storage aggregate object-store show-resync-status 」コマンドを使用して、ミラー再同期ステータスを監視します。
+
[listing]
----
cluster1::> storage aggregate object-store show-resync-status -aggregate aggr1
----
+
[listing]
----
                                                  Complete
      Aggregate    Primary          Mirror        Percentage
      ---------    -----------      ----------    ----------
      aggr1        my-AWS-store     my-AZURE-store     40%
----
. 「 storage aggregate object-store > show -fields mirror-type 、 is -mirror degraded 」コマンドを使用して、ミラーが同期されていることを確認します。
+
[listing]
----
cluster1::> storage aggregate object-store show -fields mirror-type,is-mirror-degraded
----
+
[listing]
----
aggregate      object-store-name mirror-type     is-mirror-degraded
-------------- ----------------- ------------- ------------------
aggr1          my-AWS-store        primary           -
               my-AZURE-store      mirror          false
----
. 「 storage aggregate object-store modify 」コマンドを使用して、プライマリオブジェクトストアをミラーオブジェクトストアとスワップします。
+
[listing]
----
cluster1::> storage aggregate object-store modify -aggregate aggr1 -name my-AZURE-store -mirror-type primary
----
. 「 storage aggregate object-store show -fields mirror-type 、 is -mirror degraded 」コマンドを使用して、 FabricPool ミラーの詳細を表示します。
+
この例は、 FabricPool ミラーに関する情報を表示したもので、ミラーがデグレード状態（同期されていない状態）になっているかどうかも含まれます。

+
[listing]
----
cluster1::> storage aggregate object-store show -fields mirror-type, is-mirror-degraded
----
+
[listing]
----
aggregate      object-store-name mirror-type     is-mirror-degraded
-------------- ----------------- ------------- ------------------
aggr1          my-AZURE-store      primary           -
               my-AWS-store        mirror          false
----
. 「 storage aggregate object-store unmirror 」コマンドを使用して、 FabricPool ミラーを削除します。
+
[listing]
----
cluster1::> storage aggregate object-store unmirror -aggregate aggr1
----
. 「 storage aggregate object-store show -fields mirror-type 、 is -mirror degraded 」コマンドを使用して、 FabricPool が単一のオブジェクトストア設定に戻っていることを確認します。
+
[listing]
----
cluster1::> storage aggregate object-store show -fields mirror-type,is-mirror-degraded
----
+
[listing]
----
aggregate      object-store-name mirror-type     is-mirror-degraded
-------------- ----------------- ------------- ------------------
aggr1          my-AZURE-store      primary           -
----

