---
permalink: fabricpool/replace-existing-object-store-mirror-task.html 
sidebar: sidebar 
keywords: replacing, existing, object, store, fabricpool, mirror 
summary: FabricPoolミラー テクノロジを使用して、あるオブジェクト ストアを別のオブジェクト ストアに置き換えることができます。新しいオブジェクト ストアは元のオブジェクト ストアと同じクラウド プロバイダを使用している必要はありません。 
---
= 既存のオブジェクト ストアをONTAP FabricPoolミラーに置き換える
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
FabricPoolミラー テクノロジを使用して、あるオブジェクト ストアを別のオブジェクト ストアに置き換えることができます。新しいオブジェクト ストアは元のオブジェクト ストアと同じクラウド プロバイダを使用している必要はありません。

.タスク概要
別のクラウド プロバイダを使用するオブジェクト ストアで置き換えることができます。たとえば、AWSをクラウド プロバイダとして使用しているオブジェクト ストアがAzureを使用するオブジェクト ストアに置き換えることも、その逆も可能です。ただし、オブジェクト サイズは新しいオブジェクト ストアと元のオブジェクト ストアで同じである必要があります。

.手順
.  `storage aggregate object-store mirror`コマンドを使用して、既存のFabricPoolに新しいオブジェクト ストアを追加してFabricPoolミラーを作成します。
+
[listing]
----
cluster1::> storage aggregate object-store mirror -aggregate aggr1 -object-store-name my-AZURE-store
----
.  `storage aggregate object-store show-resync-status`コマンドを使用してミラーの再同期ステータスを監視します。
+
[listing]
----
cluster1::> storage aggregate object-store show-resync-status -aggregate aggr1
----
+
[listing]
----
                                                  Complete
      Aggregate    Primary          Mirror        Percentage
      ---------    -----------      ----------    ----------
      aggr1        my-AWS-store     my-AZURE-store     40%
----
.  `storage aggregate object-store> show -fields mirror-type,is-mirror-degraded`コマンドを使用して、ミラーが同期されていることを確認します。
+
[listing]
----
cluster1::> storage aggregate object-store show -fields mirror-type,is-mirror-degraded
----
+
[listing]
----
aggregate      object-store-name mirror-type     is-mirror-degraded
-------------- ----------------- ------------- ------------------
aggr1          my-AWS-store        primary           -
               my-AZURE-store      mirror          false
----
.  `storage aggregate object-store modify`コマンドを使用して、プライマリ オブジェクト ストアをミラー オブジェクト ストアと交換します。
+
[listing]
----
cluster1::> storage aggregate object-store modify -aggregate aggr1 -object-store-name my-AZURE-store -mirror-type primary
----
.  `storage aggregate object-store show -fields mirror-type,is-mirror-degraded`コマンドを使用して、FabricPoolミラーの詳細を表示します。
+
次の例はFabricPoolミラーに関する情報を表示したもので、ミラーがデグレード状態（同期されていない状態）になっているかどうかも含まれます。

+
[listing]
----
cluster1::> storage aggregate object-store show -fields mirror-type, is-mirror-degraded
----
+
[listing]
----
aggregate      object-store-name mirror-type     is-mirror-degraded
-------------- ----------------- ------------- ------------------
aggr1          my-AZURE-store      primary           -
               my-AWS-store        mirror          false
----
.  `storage aggregate object-store unmirror`コマンドを使用してFabricPoolミラーを削除します。
+
[listing]
----
cluster1::> storage aggregate object-store unmirror -aggregate aggr1
----
.  `storage aggregate object-store show -fields mirror-type,is-mirror-degraded`コマンドを使用して、FabricPoolが単一オブジェクト ストア構成に戻っていることを確認します。
+
[listing]
----
cluster1::> storage aggregate object-store show -fields mirror-type,is-mirror-degraded
----
+
[listing]
----
aggregate      object-store-name mirror-type     is-mirror-degraded
-------------- ----------------- ------------- ------------------
aggr1          my-AZURE-store      primary           -
----


.関連情報
* link:https://docs.netapp.com/us-en/ontap-cli/storage-aggregate-object-store-mirror.html["ストレージ アグリゲート オブジェクトストア ミラー"^]
* link:https://docs.netapp.com/us-en/ontap-cli/storage-aggregate-object-store-modify.html["ストレージ アグリゲート オブジェクトストアの変更"^]
* link:https://docs.netapp.com/us-en/ontap-cli/storage-aggregate-object-store-show-resync-status.html["storage aggregate object-store show-resync-status"^]
* link:https://docs.netapp.com/us-en/ontap-cli/storage-aggregate-object-store-show.html["storage aggregate object-store show"^]
* link:https://docs.netapp.com/us-en/ontap-cli/storage-aggregate-object-store-unmirror.html["storage aggregate object-store unmirror"^]

