---
permalink: fabricpool/requirements-concept.html 
sidebar: sidebar 
keywords: considerations, requirements, using, fabricpool 
summary: FabricPool構成を最適化するには、FabricPoolの使用に関するいくつかの考慮事項と要件を理解しておく必要があります。 
---
= FabricPool を使用する際の考慮事項と要件
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
FabricPool構成を最適化するには、FabricPoolの使用に関するいくつかの考慮事項と要件を理解しておく必要があります。



== 一般的な考慮事項と要件



=== ONTAP 9.2

ONTAP 9.2以降のFabricPoolを実行している必要があります。



=== ONTAP 9.4

* 次の FabricPool 機能を使用するには、 ONTAP 9.4 以降のリリースが必要です。
+
** 。 `auto` link:tiering-policies-concept.html#types-of-fabricpool-tiering-policies["階層化ポリシー"]
** 階層化の最小クーリング期間の指定
** Inactive Data Reporting（IDR）
** FabricPool のクラウド階層としての Microsoft Azure Blob Storage の使用
** ONTAP Select で FabricPool を使用する






=== ONTAP 9.5

* 次の FabricPool 機能を使用するには、 ONTAP 9.5 以降のリリースが実行されている必要があります。
+
** 階層化の使用率しきい値を指定してい
** FabricPool のクラウド階層として IBM Cloud Object Storage を使用している
** クラウド階層の NetApp Volume Encryption （ NVE ）（デフォルトで有効）






=== ONTAP 9.6

* FabricPoolの次の機能を使用するには、ONTAP 9.6以降のリリースが必要です。
+
** 。 `all` 階層化ポリシー
** HDD アグリゲートでアクセス頻度の低いデータのレポートを手動で有効にした
** ONTAP 9.6 にアップグレードし、アグリゲートを作成すると、 SSD アグリゲートに対して Inactive Data Reporting が自動的に有効になります。ただし、 CPU が 4 個未満、 RAM が 6GB 未満、または WAFL バッファキャッシュサイズが 3GB 未満のローエンドシステムでは例外です。
+
ONTAP でシステムの負荷が監視され、負荷が高い状態が 4 分間続くと、 IDR は無効になり自動的には有効になりません。IDR を手動で再度有効にすることはできますが、手動で有効にした IDR は自動的には無効になりません。

** FabricPool のクラウド階層としての Alibaba Cloud Object Storage の使用
** FabricPool のクラウド階層として Google Cloud Platform を使用する
** クラウド階層のデータコピーを使用せずにボリュームを移動する






=== ONTAP 9.7

* FabricPoolの次の機能を使用するには、ONTAP 9.7以降のリリースが必要です。
+
** 非透過型 HTTP および HTTPS プロキシ：ホワイトリストに登録されたアクセスポイントにのみアクセスを提供し、監査およびレポート機能を提供します。
** FabricPool ミラーリング：コールドデータを 2 つのオブジェクトストアに同時に階層化します
** MetroCluster ミラーは FabricPool 構成にあります
** FabricPool に接続されたアグリゲートでは、 NDMP ダンプおよびリストアがデフォルトで有効になっています。
+
[NOTE]
====
バックアップアプリケーションでNDMP以外のプロトコル（NFSやSMBなど）を使用すると、高パフォーマンス階層にバックアップされているすべてのデータがホットになり、そのデータのクラウド階層への階層化に影響する可能性があります。NDMP 以外の読み取りでは、クラウド階層からパフォーマンス階層への原因データの移行が可能です。

====
+
https://kb.netapp.com/Advice_and_Troubleshooting/Data_Storage_Software/ONTAP_OS/NDMP_Backup_and_Restore_supported_for_FabricPool%3F["FabricPool での NDMP バックアップおよびリストアのサポート"]







=== ONTAP 9.8

* 次の FabricPool 機能を使用するには、 ONTAP 9.8 以降が実行されている必要があります。
+
** クラウド読み出し
** FabricPool with SnapLock Enterprise.FabricPool with SnapLock Enterpriseには、Feature Product Variance Request（FPVR）が必要です。FPVRを作成するには、営業チームにお問い合わせください。
** 最小冷却期間は 183 日です
** ユーザが作成したカスタムタグを使用したオブジェクトタグ付け
** HDD FabricPoolアグリゲート
+
HDD FabricPoolは、CPUコアを6つ以上搭載したシステムでのみ、SAS、FSAS、BSAS、MSATAディスクでサポートされます。

+
チェックしてください https://hwu.netapp.com/Home/Index["Hardware Universe"^] サポートされている最新のモデルについては、を参照







=== ONTAP 9.10.1

* FabricPoolの次の機能を使用するには、ONTAP 9.10.1以降が実行されている必要があります。
+
** PUTスロットル
** 温度識別型Storage Efficiency（TSSE）。






=== ONTAP 9.12.1

* 次のFabricPool機能を使用するには、ONTAP 9.12.1以降が実行されている必要があります。
+
** SVMの移行
** FabricPool、FlexGroup、SVM-DRの連携がサポートされます。（9.12.1より前のバージョンでは、これらの機能のいずれか2つが連携して動作しましたが、3つすべてが連携して動作するわけではありません）






=== ONTAP 9.14.1

* FabricPoolの次の機能を使用するには、ONTAP 9.14.1以降が実行されている必要があります。
+
** クラウド書き込み
** 積極的な先読み






== プラットフォーム

* FabricPool は、次の点を除いて、 ONTAP 9.2 を実行可能なすべてのプラットフォームでサポートされます。
+
** FAS8020
** FAS2554
** FAS2552
** FAS2520






== ローカル階層（アグリゲート）

FabricPool でサポートされるアグリゲートタイプは次のとおりです。

* AFFシステムでは、FabricPoolにSSDアグリゲートのみを使用できます。
* FASシステムでは、FabricPoolにSSDアグリゲートまたはHDDアグリゲートのいずれかを使用できます。
* Cloud Volumes ONTAP および ONTAP Select では、 FabricPool に SSD アグリゲートまたは HDD アグリゲートのいずれかを使用できます。SSDアグリゲートを使用することを推奨します。


[NOTE]
====
SSDとHDDの両方を含むFlash Poolアグリゲートはサポートされていません。

====


== クラウド階層

FabricPool では、次のオブジェクトストアをクラウド階層として使用できます。

* Alibaba Cloud Object Storage Service（標準、低頻度アクセス）
* Amazon S3（Standard、Standard-IA、One Zone-IA、Intelligent-Tiering、Glacier Instant Retrieval）
* Amazon Commercial Cloud Services（C2S）
* Google Cloud Storage（マルチリージョナル、リージョナル、ニアライン、コールドライン、アーカイブ）
* IBM Cloud Object Storage（Standard、Vault、Cold Vault、Flex）
* Microsoft Azure Blob Storage（ホットおよびクール）
* NetApp ONTAP S3 （ ONTAP 9.8 以降）
* NetApp StorageGRID（StorageGRID 10.3以降）


[NOTE]
====
Glacier Flexible RetrievalとGlacier Deep Archiveはサポートされていません。

====
* 使用するオブジェクトストア "`bucket`" ( コンテナ ) はすでに設定されている必要がありますまた ' 少なくとも 10 GB のストレージスペースが必要であり ' 名前を変更することはできません
* FabricPool を使用する HA ペアがオブジェクトストアと通信するには、クラスタ間 LIF が必要です。
* 接続後にローカル階層からクラウド階層の接続を解除することはできませんが、 link:create-mirror-task.html["FabricPoolミラー"] をクリックして、別のクラウド階層にローカル階層を接続します。




== ONTAP の Storage Efficiency 機能

データをクラウド階層に移動する際に圧縮、重複排除、コンパクションなどのStorage Efficiencyが維持されるため、必要なオブジェクトストレージ容量と転送コストを削減できます。


NOTE: ONTAP 9.15.1以降では、FabricPoolはインテルQuickAssistテクノロジー（QAT4）をサポートしています。これにより、より積極的でパフォーマンスの高いストレージ効率を実現できます。

アグリゲートインライン重複排除はローカル階層でサポートされますが、関連するStorage Efficiencyはクラウド階層に格納されているオブジェクトに引き継がれません。

「すべて」のボリューム階層化ポリシーを使用している場合、追加のストレージ効率化を適用する前にデータが階層化される可能性があるため、バックグラウンドの重複排除プロセスに関連するStorage Efficiencyが低下することがあります。



== BlueXP階層化ライセンス

FabricPoolでサードパーティのオブジェクトストレージプロバイダ（Amazon S3など）をAFFおよびFASシステムのクラウド階層として接続するには、容量ベースのライセンスが必要です。StorageGRIDまたはONTAP S3をクラウド階層として使用している場合や、Cloud Volumes ONTAP、Amazon FSx for NetApp ONTAP、Azure NetApp Filesで階層化する場合は、BlueXP階層化ライセンスは必要ありません。

BlueXPライセンス（既存のFabricPoolライセンスのアドオンや拡張機能を含む）は、でアクティブ化されます link:https://docs.netapp.com/us-en/bluexp-tiering/concept-cloud-tiering.html["BlueXPのデジタルウォレット"^]。



== StorageGRID整合性制御

StorageGRIDの整合性制御は、StorageGRIDがオブジェクトの追跡に使用するメタデータに影響します。
ノード間で分散され、クライアント要求に対するオブジェクトの可用性が確保されます。NetAppでは、
FabricPoolターゲットとして使用されるバケットのデフォルトのread-after-new-write整合性制御。


NOTE: FabricPoolターゲットとして使用するバケットにはAvailable整合性制御を使用しないでください。



== SAN プロトコルがアクセスするデータの階層化に関するその他の考慮事項

SANプロトコルでアクセスされるデータを階層化する場合、接続に関する考慮事項があるため、NetAppではONTAP S3やStorageGRIDなどのプライベートクラウドを使用することを推奨しています。


IMPORTANT: Windowsホストを使用するSAN環境でFabricPoolを使用している場合、データをクラウドに階層化する際にオブジェクトストレージを長時間使用できなくなると、Windowsホスト上のNetApp LUN上のファイルにアクセスできなくなるか、表示されなくなることがあります。サポート技術情報の記事を参照してください link:https://kb.netapp.com/onprem/ontap/os/During_FabricPool_S3_object_store_unavailable_Windows_SAN_host_reported_filesystem_corruption["FabricPool S3オブジェクトストアを使用できないときに、Windows SANホストでファイルシステムの破損が報告されました"^]。



== サービス品質（QoS

* スループットの下限（最小QoS）を使用する場合は、ボリュームの階層化ポリシーをに設定する必要があります `none` アグリゲートをFabricPool に接続する前に、
+
それ以外の階層化ポリシーに設定されていると、アグリゲートを FabricPool に接続できません。FabricPoolが有効な場合、QoSポリシーではスループットの下限は適用されません。





== FabricPool でサポートされていない機能

* WORM とオブジェクトのバージョン管理が有効なオブジェクトストア
* オブジェクトストアバケットに適用される情報ライフサイクル管理（ ILM ）ポリシー
+
FabricPoolは、クラウド階層のデータを障害から保護するために、データレプリケーションとイレイジャーコーディングに関してのみStorageGRIDの情報ライフサイクル管理ポリシーをサポートしています。ただし、FabricPoolは、ユーザメタデータやタグに基づくフィルタリングなどの高度なILMルールをサポートしていません。通常、 ILM には移動と削除に関するさまざまなポリシーが含まれています。これらのポリシーは、 FabricPool のクラウド階層内のデータに影響を与える可能性があります。オブジェクトストアで設定されている ILM ポリシーと FabricPool を同時に使用すると、データが失われる可能性があります。

* ONTAP CLI コマンドまたは 7-Mode Transition Tool を使用した 7-Mode のデータ移行
* FlexArray 仮想化
* SyncMirror 構成を除く RAID MetroCluster
* ONTAP 9.7 以前のリリースを使用している場合、 SnapLock ボリュームが必要です
* FabricPool 対応アグリゲート用の SMTape を使用したテープバックアップ
* 自動負荷分散機能
* 以外のスペースギャランティを使用しているボリューム `none`
+
ルートSVMボリュームとCIFS監査ステージングボリュームを除き、FabricPool では、以外のスペースギャランティを使用するボリュームを含むアグリゲートにクラウド階層を接続することはサポートされていません `none`。たとえば、スペースギャランティがに設定されたボリュームなどです `volume` (`-space-guarantee` `volume`）はサポートされていません。

* クラスタ link:../data-protection/snapmirror-licensing-concept.html#data-protection-optimized-license["DP_Optimizedライセンス"]
* Flash Pool アグリゲート

