---
permalink: fabricpool/setup-ontap-s3-cloud-tier-task.html 
sidebar: sidebar 
keywords: setting up, ontap s3, cloud tier 
summary: ONTAP 9.8 以降を実行している場合は、 ONTAP S3 を FabricPool のクラウド階層としてセットアップできます。 
---
= クラウド階層として ONTAP S3 をセットアップします
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
ONTAP 9.8 以降を実行している場合は、 ONTAP S3 を FabricPool のクラウド階層としてセットアップできます。

リモートクラスタの ONTAP S3 サーバ名とその LIF に関連付けられている IP アドレスが必要です。

ローカルクラスタとリモートクラスタの両方にクラスタ間 LIF が必要です。

https://docs.netapp.com/ontap-9/topic/com.netapp.doc.pow-s3-cg/GUID-47BBD9BF-7C3A-4902-8E41-88E54A0FDB44.html["リモートの FabricPool 階層化用にクラスタ間 LIF を作成しています"]

ONTAP 9.8 以降では、 ONTAP S3 サーバのロードバランシングが有効になっています。サーバのホスト名が複数の IP アドレスに解決される場合、 ONTAP は、返されるすべての IP アドレス（最大 16 個の IP アドレス）とのクライアント接続を確立します。接続が確立されると、 IP アドレスはラウンドロビン方式でピックアップされます。

.手順
. S3 サーバと LIF のエントリを DNS サーバに追加します。
+
|===


| オプション | 説明 


 a| 
* 外部 DNS サーバーを使用する場合 *
 a| 
S3 サーバの名前と IP アドレスを DNS サーバ管理者に渡します。



 a| 
* ローカルシステムの DNS hosts テーブル * を使用している場合
 a| 
次のコマンドを入力します。

「 dns host create -vserver svm_name -address IP_address -hostname s3_server_name 」という名前になります

|===
. 「 -provider-type `ONTAP_s3' 」パラメータを指定して「 storage aggregate object-store config create 」コマンドを使用し、 ONTAP S3 の設定情報を指定します。
+
** ローカル ONTAP システムが指定された情報で ONTAP S3 サーバにアクセスできない場合、「 storage aggregate object-store config create 」コマンドが失敗します。
** access-key' パラメータを使用して、 ONTAP S3 サーバへの要求を認証するためのアクセスキーを指定します。
** 「 -secret-password 」パラメータを使用して、 ONTAP S3 サーバへの要求を認証するためのパスワード（シークレットアクセスキー）を指定します。
** ONTAP S3 サーバのパスワードが変更された場合は、ローカルの ONTAP システムに格納されている対応するパスワードをただちに更新する必要があります。
+
これにより、 ONTAP S3 オブジェクトストア内のデータに中断なくアクセスできます。

** 「 -is-certificate-validation-enabled 」パラメータを「 false 」に設定すると、 ONTAP S3 の証明書チェックが無効になります。


+
[listing]
----
cluster1::> storage aggregate object-store config create
-object-store-name myS3 -provider-type ONTAP_S3 -server myS3server
-container-name myS3container -access-key myS3key
-secret-password myS3pass
----
. 「 storage aggregate object-store config show 」コマンドを使用して、 ONTAP_S3 の設定情報を表示して確認します。
+
「 storage aggregate object-store config modify 」コマンドを使用すると、 FabricPool の「 ONTAP_S3 」の設定情報を変更できます。


