---
permalink: fabricpool/setup-ontap-s3-cloud-tier-task.html 
sidebar: sidebar 
keywords: tr-4814, fabricpool, setting up, ontap s3, cloud tier, local tier, tiering, storage tiering, storage tier, lif 
summary: ONTAP 9.8以降を実行している場合は、ONTAP S3をFabricPoolのクラウド階層としてセットアップできます。 
---
= ONTAP S3をFabricPoolクラウド階層として設定
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
ONTAP 9.8以降を実行している場合は、ONTAP S3をFabricPoolのクラウド階層としてセットアップできます。

.開始する前に
* ONTAP S3サーバの名前およびリモート クラスタにあるその関連LIFのIPアドレスを確認しておく必要があります。
+

NOTE: サーバ名は、クライアント アプリケーションで完全修飾ドメイン名（FQDN）として使用されます。ONTAP外で、使用中のSVMデータLIFを指しているDNSレコードを確認します。

* ローカル クラスター上に<<create-lif,クラスタ内LIF>>が存在している必要があります。
+
ローカル クラスタ階層化用に設定すると、ローカル階層（ONTAP CLI ではストレージ アグリゲートとも呼ばれます）がローカル バケットに接続されます。FabricPool は、クラスタ内トラフィックにクラスタ LIF を使用します。

+

NOTE: クラスタLIFリソースが飽和状態になると、パフォーマンスが低下する可能性があります。これを回避するため、NetAppでは、ローカルバケットへの階層化を行う場合は、ローカル階層用のHAペアとローカルバケット用のHAペアを使用して、4ノード以上のクラスタを使用することを推奨しています。単一のHAペアでローカルバケットへの階層化を行うことは推奨されません。

* ONTAP S3 を使用してリモート FabricPool 容量（クラウド）階層化を有効にするには、FabricPool クライアントで link:../s3-config/create-intercluster-lifs-remote-fabricpool-tiering-task.html["クラスタ間LIFを設定する"] を実行し、オブジェクト ストア サーバーで link:../s3-config/create-data-lifs-task.html["データ LIF を設定"] を実行する必要があります。


.タスク概要
ONTAP 9.8以降では、ONTAP S3サーバの負荷分散が有効になっています。サーバのホスト名が複数のIPアドレスに解決される場合、ONTAPは、返されたすべてのIPアドレス（最大16個のIPアドレス）とクライアント接続を確立します。接続が確立されると、IPアドレスはラウンドロビン方式で選択されます。



[[set-up-the-ontap-s3-cloud-tier-for-fabricpool]]
== ONTAP S3 クラウド階層を FabricPool 用に設定する

.手順
ONTAP System ManagerまたはONTAP CLIを使用して、ONTAP S3をFabricPoolのクラウド階層としてセットアップできます。

[role="tabbed-block"]
====
.System Manager
--
. *ストレージ > 階層 > クラウド階層の追加* をクリックし、オブジェクト ストア プロバイダーとして ONTAP S3 を選択します。
. 必要な情報を入力します。
. クラウドミラーを作成する場合は、*FabricPoolミラーとして追加*をクリックします。


FabricPoolミラーを使用するとデータ ストアをシームレスに置き換えることができるため、災害発生時でもデータを使用できるようになります。

--
.CLI
--
. S3サーバとLIFのエントリをDNSサーバに追加します。
+
|===


| オプション | 概要 


 a| 
* 外部 DNS サーバーを使用する場合 *
 a| 
S3サーバの名前とIPアドレスをDNSサーバ管理者に渡します。



 a| 
*ローカルシステムのDNSホストテーブルを使用する場合*
 a| 
次のコマンドを入力します。

[listing]
----
dns host create -vserver <svm_name> -address ip_address -hostname <s3_server_name>
----
|===
.  `storage aggregate object-store config create`コマンドに `-provider-type` `ONTAP_S3`パラメータを指定して、ONTAP S3 構成情報を指定します。
+
**  `storage aggregate object-store config create`ローカルONTAPシステムが提供された情報を使用してONTAP S3サーバにアクセスできない場合、コマンドは失敗します。
**  `-access-key`パラメータを使用して、ONTAP S3サーバへの要求を承認するためのアクセスキーを指定します。
**  `-secret-password`パラメータを使用して、ONTAP S3サーバへの要求を認証するためのパスワード（シークレットアクセスキー）を指定します。
** ONTAP S3サーバのパスワードが変更された場合は、ローカルのONTAPシステムに格納されている対応するパスワードをただちに更新する必要があります。
+
これにより、中断なくONTAP S3オブジェクト ストア内のデータにアクセスできます。

**  `-is-certificate-validation-enabled`パラメータを `false`に設定すると、ONTAP S3の証明書チェックが無効になります。サードパーティの証明機関からの署名付き証明書(`-is-certificate-validation-enabled true`を使用することが推奨されるベストプラクティスです。


+
[listing]
----
cluster1::> storage aggregate object-store config create
-object-store-name myS3 -provider-type ONTAP_S3 -server myS3server
-container-name myS3container -access-key myS3key
-secret-password myS3pass
----
.  `storage aggregate object-store config show`コマンドを使用して、ONTAP_S3設定情報を表示および確認します。
+
 `storage aggregate object-store config modify`コマンドを使用すると、FabricPoolの `ONTAP_S3`構成情報を変更できます。



--
====


[[change-the-ontap-s3-fqdn-for-fabricpool-tiering]]
== FabricPool階層化用のONTAP S3 FQDNを変更する

FQDN の更新を含むネットワークの変更が必要な場合は、ネットワーク障害を回避するために、FabricPool 階層化に使用される ONTAP S3 FQDN を変更する必要があります。

.手順
. FabricPool ティアの証明書検証を無効にする：
+
`storage aggregate object-store config modify -object-store-name <object store> -is-certificate-validation-enabled false`

. ONTAP S3 サーバーの FQDN を変更する：
+
`vserver object-store-server modify -vserver <vserver> -object-store-server <new fqdn>`

. （オプション）証明書の検証が必要でホスト名が変更された場合、link:../s3-config/create-install-ca-certificate-svm-task.html["証明書を更新する"]。
. 新しい FQDN を使用して FabricPool 階層を更新します：
+
`storage aggregate object-store config modify -object-store-name <object_store_name> -server <new fqdn>`

. すべてのオブジェクトストア、およびミラーが存在する場合はそのミラーが、FabricPool ティアで利用可能であることを確認します：
+
`storage aggregate object-store show -fields object-store-availability,mirror-type,is-mirror-degraded`

+
詳細については、link:https://docs.netapp.com/us-en/ontap-cli/storage-aggregate-object-store-show.html#description["storage aggregate object-store show"^]を参照してください。

. 追加のオブジェクトストアについても、これらの手順を繰り返してください。
. ONTAP S3サーバーで証明書を更新し、FabricPool階層で証明書を更新した場合は、証明書の検証を再度有効にしてください：
+
`storage aggregate object-store config modify -object-store-name <object store> -is-certificate-validation-enabled true`



[[create-lif]]
.関連情報
* link:../smb-config/create-lif-task.html["SMB用のLIFを作成する"]
* link:../nfs-config/create-lif-task.html["NFS用のLIFを作成する"]
* link:https://docs.netapp.com/us-en/ontap-cli/storage-aggregate-object-store-config-create.html["storage aggregate object-store config create"^]
* link:https://docs.netapp.com/us-en/ontap-cli/snapmirror-object-store-config-modify.html["storage aggregate object-store config modify"^]
* link:https://docs.netapp.com/us-en/ontap-cli/storage-aggregate-object-store-config-show.html["storage aggregate object-store config show"^]

