---
permalink: fabricpool/setup-google-storage-cloud-tier-task.html 
sidebar: sidebar 
keywords: setting up, google cloud storage, cloud tier 
summary: ONTAP 9.6 以降を実行している場合は、 Google Cloud Storage を FabricPool のクラウド階層としてセットアップできます。 
---
= クラウド階層として Google Cloud Storage をセットアップします
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
ONTAP 9.6 以降を実行している場合は、 Google Cloud Storage を FabricPool のクラウド階層としてセットアップできます。



== FabricPool で Google Cloud Storage を使用する場合のその他の考慮事項を示します

* FabricPool ライセンスが必要な場合があります。
+
新規に購入した AFF システムには、 FabricPool を使用するための 10TB の空き容量が含まれています。AFFシステムで追加の容量が必要な場合、AFF以外のシステムでGoogle Cloud Storageを使用する場合、または既存のクラスタからアップグレードする場合は、 https://docs.netapp.com/us-en/ontap/fabricpool/install-license-aws-azure-ibm-task.html["FabricPool ライセンス"]。

* ONTAP がGoogle Cloud Storageオブジェクトサーバとの接続に使用するLIFは10Gbpsポートに配置することを推奨します。
* AFF および FAS システムと ONTAP Select では、 FabricPool で次の Google Cloud Object ストレージクラスがサポートされます。
+
** Google Cloud Multi-Regional の場合
** Google Cloud リージョナル
** Google Cloud Nearline
** Google Cloud Coldline
+
https://cloud.google.com/storage/docs/storage-classes["Google Cloud ：ストレージクラス"^]





.手順
. を使用して、Google Cloud Storageの設定情報を指定します `storage aggregate object-store config create` コマンドにを指定します `-provider-type` `GoogleCloud` パラメータ
+
** 。 `storage aggregate object-store config create` 指定された情報でONTAP がGoogle Cloud Storageにアクセスできない場合は、コマンドが失敗します。
** を使用します `-access-key` パラメータを使用して、Google Cloud Storageオブジェクトストアへの要求を認証するためのアクセスキーを指定します。
** Google Cloud Storage のパスワードが変更された場合は、 ONTAP に格納されている対応するパスワードをただちに更新する必要があります。
+
これにより、 ONTAP は引き続き Google Cloud Storage 内のデータにアクセスできます。



+
[listing]
----
storage aggregate object-store config create my_gcp_store_1 -provider-type GoogleCloud  -container-name my-gcp-bucket1 -access-key GOOGAUZZUV2USCFGHGQ511I8
----
. を使用して、Google Cloud Storageの設定情報を表示して確認します `storage aggregate object-store config show` コマンドを実行します
+
。 `storage aggregate object-store config modify` コマンドを使用して、FabricPool のGoogle Cloud Storageの設定情報を変更できます。


