---
permalink: fabricpool/setup-ibm-object-storage-cloud-tier-task.html 
sidebar: sidebar 
keywords: setting up, ibm cloud, object storage, cloud tier 
summary: ONTAP 9 .5以降を実行している場合は、IBM Cloud Object StorageをFabricPoolのクラウド階層としてセットアップできます。 
---
= ONTAP FabricPoolクラウド階層としてのIBM Cloud Object Storageのセットアップ
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
ONTAP 9 .5以降を実行している場合は、IBM Cloud Object StorageをFabricPoolのクラウド階層としてセットアップできます。

.FabricPoolでIBM Cloud Object Storageを使用する場合の考慮事項
* IBM Cloud Object Storageに階層化する場合は、がlink:https://bluexp.netapp.com/cloud-tiering["BlueXP階層化ライセンス"]必要です。
* ONTAPがIBM Cloudオブジェクトサーバとの接続に使用するLIFは10Gbpsポートに配置することを推奨します。


.手順
. コマンドでパラメータを `-provider-type` `IBM_COS`使用して、IBM Cloud Object Storageの設定情報を指定し `storage aggregate object-store config create`ます。
+
**  `storage aggregate object-store config create`指定された情報でONTAPがIBM Cloud Object Storageにアクセスできない場合、コマンドは失敗します。
** パラメータを使用し `-access-key`て、IBM Cloud Object Storageオブジェクトストアへの要求を認証するためのアクセスキーを指定します。
** パラメータを使用し `-secret-password`て、IBM Cloud Object Storageオブジェクトストアへの要求を認証するためのパスワード（シークレットアクセスキー）を指定します。
** IBM Cloud Object Storageのパスワードが変更された場合は、ONTAPに格納されている対応するパスワードをただちに更新する必要があります。
+
これにより、ONTAPは引き続きIBM Cloud Object Storage内のデータにアクセスできます。



+
[listing]
----
storage aggregate object-store config create
-object-store-name MyIBM -provider-type IBM_COS
-server s3.us-east.objectstorage.softlayer.net
-container-name my-ibm-cos-bucket -access-key DXJRXHPXHYXA9X31X3JX
----
. コマンドを使用して、IBM Cloud Object Storageの設定情報を表示して確認します `storage aggregate object-store config show`。
+
 `storage aggregate object-store config modify`コマンドを使用して、FabricPoolのIBMクラウドオブジェクトストレージの設定情報を変更できます。



.関連情報
* link:https://docs.netapp.com/us-en/ontap-cli/storage-aggregate-object-store-config-create.html["ストレージ集約オブジェクトストア構成の作成"^]
* link:https://docs.netapp.com/us-en/ontap-cli/snapmirror-object-store-config-modify.html["ストレージ集約オブジェクトストア構成の変更"^]
* link:https://docs.netapp.com/us-en/ontap-cli/storage-aggregate-object-store-config-show.html["ストレージ集約オブジェクトストア構成表示"^]

