---
permalink: fabricpool/setup-object-stores-mcc-task.html 
sidebar: sidebar 
keywords: setting up, object, stores, fabricpool, metrocluster, configuration 
summary: ONTAP 9.7 以降を実行している場合、 MetroCluster 構成にミラーリングされた FabricPool をセットアップして、 2 つの異なる障害ゾーンにあるオブジェクトストアにコールドデータを階層化できます。 
---
= MetroCluster 構成で FabricPool のオブジェクトストアを設定する
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
ONTAP 9.7 以降を実行している場合、 MetroCluster 構成にミラーリングされた FabricPool をセットアップして、 2 つの異なる障害ゾーンにあるオブジェクトストアにコールドデータを階層化できます。

.必要なもの
* MetroCluster 構成がセットアップされ、適切に設定されている。
* 2 つのオブジェクトストアが適切な MetroCluster サイトにセットアップされている。
* 各オブジェクトストアにコンテナが設定されている。
* 2 つの MetroCluster 構成に IP スペースが作成または識別され、それらの名前が一致している。


.このタスクについて
* MetroCluster の FabricPool では、基盤となるミラーアグリゲートと関連するオブジェクトストア設定が同じ MetroCluster 構成に所属している必要があります。
* リモートの MetroCluster サイトで作成されたオブジェクトストアにアグリゲートを接続することはできません。
* アグリゲートが所属する MetroCluster 構成にオブジェクトストアを設定する必要があります。


.ステップ
. 「 storage object-store config create 」コマンドを使用して、各 MetroCluster サイトのオブジェクトストア設定情報を指定します。
+
この例では、 MetroCluster 構成の一方のクラスタにのみ FabricPool が必要です。オブジェクトストアバケットごとに 1 つずつ、計 2 つのオブジェクトストア設定をそのクラスタに作成します。

+
[listing]
----
storage aggregate
    object-store config create -object-store-name mcc1-ostore-config-s1 -provider-type SGWS -server
    <SGWS-server-1> -container-name <SGWS-bucket-1> -access-key <key> -secret-password <password> -encrypt
    <true|false> -provider <provider-type> -is-ssl-enabled <true|false> ipspace
    <IPSpace>
----
+
[listing]
----
storage aggregate object-store config create -object-store-name mcc1-ostore-config-s2
    -provider-type SGWS -server <SGWS-server-2> -container-name <SGWS-bucket-2> -access-key <key> -secret-password <password> -encrypt <true|false> -provider <provider-type>
    -is-ssl-enabled <true|false> ipspace <IPSpace>
----
+
この例では、 MetroCluster 構成のもう一方のクラスタに FabricPool をセットアップします。

+
[listing]
----
storage aggregate
    object-store config create -object-store-name mcc2-ostore-config-s1 -provider-type SGWS -server
    <SGWS-server-1> -container-name <SGWS-bucket-3> -access-key <key> -secret-password <password> -encrypt
    <true|false> -provider <provider-type> -is-ssl-enabled <true|false> ipspace
    <IPSpace>
----
+
[listing]
----
storage aggregate
    object-store config create -object-store-name mcc2-ostore-config-s2 -provider-type SGWS -server
    <SGWS-server-2> -container-name <SGWS-bucket-4> -access-key <key> -secret-password <password> -encrypt
    <true|false> -provider <provider-type> -is-ssl-enabled <true|false> ipspace
    <IPSpace>
----

