---
permalink: fabricpool/setup-aws-s3-cloud-tier-task.html 
sidebar: sidebar 
keywords: setting up, aws, s3, cloud tier 
summary: ONTAP 9.2 以降を実行している場合は、 AWS S3 を FabricPool のクラウド階層としてセットアップできます。ONTAP 9.5 以降を実行している場合は、 AWS Commercial クラウドサービス（ C2S ）を FabricPool 用にセットアップできます。 
---
= AWS S3 をクラウド階層としてセットアップします
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
ONTAP 9.2 以降を実行している場合は、 AWS S3 を FabricPool のクラウド階層としてセットアップできます。ONTAP 9.5 以降を実行している場合は、 AWS Commercial クラウドサービス（ C2S ）を FabricPool 用にセットアップできます。

.FabricPool でAWS S3を使用する場合の考慮事項
* FabricPool ライセンスが必要な場合があります。
+
** 新規に購入した AFF システムには、 FabricPool を使用するための 10TB の空き容量が含まれています。
+
AFF システムで追加の容量が必要な場合、 AFF 以外のシステムで AWS S3 を使用する場合、または既存のクラスタからアップグレードする場合は、 FabricPool ライセンスが必要になります。

+
既存のクラスタ用に FabricPool を初めて購入した場合は、 10TB の空き容量を含む FabricPool ライセンスが付随します。



* ONTAP がAWS S3オブジェクトサーバとの接続に使用するLIFは10Gbpsポートに配置することを推奨します。
* AFF および FAS システムと ONTAP Select では、 FabricPool で次の Amazon S3 ストレージクラスがサポートされます。
+
** Amazon S3 Standard の略
** Amazon S3 標準 - 低頻度アクセス（標準 -IA ）
** Amazon S3 ONE ゾーン - アクセス頻度が低い（ 1 ゾーン -IA ）
** Amazon S3 インテリジェント階層化
** Amazon Commercial クラウドサービスの略
+
https://aws.amazon.com/s3/storage-classes/["Amazon Web Services （ AWS ）ドキュメント：「 Amazon S3 Storage Classes"]



+
上記以外のストレージクラスについては、営業担当者にお問い合わせください。

* Cloud Volumes ONTAP では、 FabricPool が Amazon Elastic Block Store （ EBS ）の汎用 SSD （ gp2 ）ボリュームおよびスループット最適化 HDD （ st1 ）ボリュームからの階層化をサポートします。


.手順
. を使用して、AWS S3の設定情報を指定します。 `storage aggregate object-store config create` コマンドにを指定します `-provider-type` `AWS_S3` パラメータ
+
** を使用します `-auth-type` `CAP` C2Sアクセスのクレデンシャルを取得するためのパラメータ。
+
を使用する場合 `-auth-type` `CAP` パラメータを使用する必要があります `-cap-url` C2Sアクセス用の一時的なクレデンシャルを要求する完全なURLを指定するパラメータ。

** 。 `storage aggregate object-store config create` 指定された情報でONTAP がAWS S3にアクセスできない場合は、コマンドが失敗します。
** を使用します `-access-key` AWS S3オブジェクトストアへの要求を認証するためのアクセスキーを指定するパラメータ。
** を使用します `-secret-password` AWS S3オブジェクトストアへの要求を認証するためのパスワード（シークレットアクセスキー）を指定するパラメータ。
** AWS S3 のパスワードが変更された場合は、 ONTAP に格納されている対応するパスワードをただちに更新する必要があります。
+
これにより、 ONTAP は引き続き AWS S3 内のデータにアクセスできます。

+
[listing]
----
cluster1::> storage aggregate object-store config create
-object-store-name my_aws_store -provider-type AWS_S3
-server s3.amazonaws.com -container-name my-aws-bucket
-access-key DXJRXHPXHYXA9X31X3JX
----
+
[listing]
----
cluster1::> storage aggregate object-store config create -object-store-name my_c2s_store -provider-type AWS_S3 -auth-type CAP -cap-url https://123.45.67.89/api/v1/credentials?agency=XYZ&mission=TESTACCT&role=S3FULLACCESS -server my-c2s-s3server-fqdn -container my-c2s-s3-bucket
----


. を使用して、AWS S3の設定情報を表示して確認します `storage aggregate object-store config show` コマンドを実行します
+
。 `storage aggregate object-store config modify` コマンドを使用して、FabricPool に使用するAWS S3の設定情報を変更できます。


