---
permalink: fabricpool/setup-object-stores-mcc-task.html 
sidebar: sidebar 
keywords: setting up, object, stores, fabricpool, metrocluster, configuration 
summary: ONTAP 9 .7以降を実行している場合は、MetroCluster構成にミラーされたFabricPoolをセットアップして、2つの異なる障害ゾーンにあるオブジェクトストアにコールドデータを階層化できます。 
---
= MetroCluster構成でONTAP FabricPoolのオブジェクトストアを設定する
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
ONTAP 9 .7以降を実行している場合は、MetroCluster構成にミラーされたFabricPoolをセットアップして、2つの異なる障害ゾーンにあるオブジェクトストアにコールドデータを階層化できます。

.タスクの内容
* MetroClusterのFabricPoolを使用するには、基盤となるミラーアグリゲートと関連するオブジェクトストア設定が同じMetroCluster設定に所有されている必要があります。
* リモートMetroClusterサイトで作成されたオブジェクトストアにアグリゲートを接続することはできません。
* オブジェクトストア設定は、アグリゲートが属するMetroCluster構成に作成する必要があります。


.開始する前に
* MetroCluster構成がセットアップされ、適切に設定されている。
* 2つのオブジェクトストアが適切なMetroClusterサイトにセットアップされている。
* コンテナは各オブジェクトストアで設定されます。
* 2つのMetroCluster構成でIPスペースが作成または識別され、名前が一致している。


.ステップ
. コマンドを使用して、各MetroClusterサイトのオブジェクトストア設定情報を指定し `storage object-store config create`ます。
+
この例では、MetroCluster構成の一方のクラスタにのみFabricPoolが必要です。オブジェクトストアバケットごとに1つずつ、2つのオブジェクトストア設定をそのクラスタ用に作成します。

+
[listing]
----
storage aggregate
    object-store config create -object-store-name mcc1-ostore-config-s1 -provider-type SGWS -server
    <SGWS-server-1> -container-name <SGWS-bucket-1> -access-key <key> -secret-password <password> -encrypt
    <true|false> -provider <provider-type> -is-ssl-enabled <true|false> ipspace
    <IPSpace>
----
+
[listing]
----
storage aggregate object-store config create -object-store-name mcc1-ostore-config-s2
    -provider-type SGWS -server <SGWS-server-2> -container-name <SGWS-bucket-2> -access-key <key> -secret-password <password> -encrypt <true|false> -provider <provider-type>
    -is-ssl-enabled <true|false> ipspace <IPSpace>
----
+
この例では、MetroCluster構成の2つ目のクラスタにFabricPoolをセットアップします。

+
[listing]
----
storage aggregate
    object-store config create -object-store-name mcc2-ostore-config-s1 -provider-type SGWS -server
    <SGWS-server-1> -container-name <SGWS-bucket-3> -access-key <key> -secret-password <password> -encrypt
    <true|false> -provider <provider-type> -is-ssl-enabled <true|false> ipspace
    <IPSpace>
----
+
[listing]
----
storage aggregate
    object-store config create -object-store-name mcc2-ostore-config-s2 -provider-type SGWS -server
    <SGWS-server-2> -container-name <SGWS-bucket-4> -access-key <key> -secret-password <password> -encrypt
    <true|false> -provider <provider-type> -is-ssl-enabled <true|false> ipspace
    <IPSpace>
----

