---
permalink: fabricpool/setup-storagegrid-cloud-tier-task.html 
sidebar: sidebar 
keywords: setting up, storagegrid, cloud tier 
summary: ONTAP 9 .2以降を実行している場合は、StorageGRIDをFabricPoolのクラウド階層としてセットアップできます。 
---
= クラウド階層としてのStorageGRIDのセットアップ
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
ONTAP 9 .2以降を実行している場合は、StorageGRIDをFabricPoolのクラウド階層としてセットアップできます。SANプロトコルでアクセスされるデータを階層化する場合、接続に関する考慮事項があるため、NetAppではStorageGRIDなどのプライベートクラウドを使用することを推奨しています。

.FabricPoolでStorageGRIDを使用する場合の考慮事項
* 証明書のチェックを明示的に無効にした場合を除き、StorageGRIDのCA証明書をインストールする必要があります。
* オブジェクトストアバケットでStorageGRIDオブジェクトのバージョン管理を有効にしないでください。
* FabricPoolライセンスは必要ありません。
* NetApp AFFシステムからストレージが割り当てられた仮想マシンにStorageGRIDノードが導入されている場合は、ボリュームでFabricPool階層化ポリシーが有効になっていないことを確認してください。
+
StorageGRIDノードで使用するボリュームでFabricPool階層化を無効にすると、トラブルシューティングとストレージの処理が簡単になります。

+
[NOTE]
====
FabricPoolを使用して、StorageGRIDに関連するデータをStorageGRID自体に階層化しないでください。StorageGRIDデータをStorageGRIDに階層化すると、トラブルシューティングや運用が複雑になります。

====


.タスクの内容
ONTAP 9 .8以降では、StorageGRIDのロードバランシングが有効になっています。サーバのホスト名が複数のIPアドレスに解決されると、ONTAPは返されたすべてのIPアドレス（最大16個のIPアドレス）を使用してクライアント接続を確立します。接続が確立されると、ラウンドロビン方式でIPアドレスが取得されます。

.手順
ONTAP System ManagerまたはONTAP CLIを使用して、StorageGRIDをFabricPoolのクラウド階層としてセットアップできます。

[role="tabbed-block"]
====
.System Manager
--
. [*ストレージ]、[階層]、[クラウド階層の追加]の順にクリックし、オブジェクトストアプロバイダとして[ StorageGRID ]を選択します。
. 必要な情報を入力します。
. CloudMirror を作成する場合は、 * FabricPool ミラーとして追加 * をクリックします。


FabricPoolミラーを使用すると、データストアをシームレスに置き換えることができ、災害発生時にデータを利用できるようになります。

--
.CLI
--
. コマンドでパラメータを指定して `-provider-type` `SGWS`、StorageGRIDの設定情報を指定し `storage aggregate object-store config create`ます。
+
**  `storage aggregate object-store config create`指定された情報でONTAPがStorageGRIDにアクセスできない場合、コマンドは失敗します。
** パラメータを使用し `-access-key`て、StorageGRIDオブジェクトストアへの要求を認証するためのアクセスキーを指定します。
** パラメータを使用し `-secret-password`て、StorageGRIDオブジェクトストアへの要求を認証するためのパスワード（シークレットアクセスキー）を指定します。
** StorageGRID パスワードが変更された場合は、 ONTAP に格納されている対応するパスワードをただちに更新する必要があります。
+
これにより、ONTAPは引き続きStorageGRID内のデータにアクセスできます。

** パラメータをに `false`設定する `-is-certificate-validation-enabled`と、StorageGRIDの証明書チェックが無効になります。署名付き証明書を使用する(`-is-certificate-validation-enabled true`ことを推奨します）。サードパーティの認証局から取得した証明書を使用することを推奨します。


+
[listing]
----
cluster1::> storage aggregate object-store config create
-object-store-name mySGWS -provider-type SGWS -server mySGWSserver
-container-name mySGWScontainer -access-key mySGWSkey
-secret-password mySGWSpass
----
. コマンドを使用して、StorageGRIDの設定情報を表示して確認します `storage aggregate object-store config show`。
+
 `storage aggregate object-store config modify`コマンドを使用して、FabricPoolのStorageGRID設定情報を変更できます。



--
====