---
permalink: nfs-config/additional-information-reference.html 
sidebar: sidebar 
keywords: additional, information, nfs, configuration, networking, san protocol, root volume, protection 
summary: NFS クライアントアクセスをテストしたあと、 NFS の追加設定を行ったり、 SAN アクセスを追加したりできます。プロトコルアクセスが完了したら、 Storage Virtual Machine （ SVM ）のルートボリュームを保護する必要があります。 
---
= 追加情報の参照先
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
NFS クライアントアクセスをテストしたあと、 NFS の追加設定を行ったり、 SAN アクセスを追加したりできます。プロトコルアクセスが完了したら、 Storage Virtual Machine （ SVM ）のルートボリュームを保護する必要があります。



== NFS の設定

NFS アクセスについてさらに詳しく設定するには、以下の情報とテクニカルレポートを参照してください。

* link:../nfs-admin/index.html["NFS の管理"]
+
NFS を使用したファイルアクセスを設定および管理する方法について説明しています。

* http://www.netapp.com/us/media/tr-4067.pdf["ネットアップテクニカルレポート 4067 ：『 NFS Best Practice and Implementation Guide 』"^]
+
NFSv3 および NFSv4 の運用ガイドであり、 NFSv4 を中心に ONTAP オペレーティングシステムの概要を説明しています。

* http://www.netapp.com/us/media/tr-4073.pdf["ネットアップテクニカルレポート 4073 ：『 Secure Unified Authentication 』"]
+
NFS ストレージ認証用に UNIX ベースの Kerberos バージョン 5 （ krb5 ）サーバを使用する ONTAP の設定方法と、 KDC および Lightweight Directory Access Protocol （ LDAP ）のアイデンティティプロバイダとして Windows Server Active Directory （ AD ）を使用するための の設定方法について説明しています。

* http://www.netapp.com/us/media/tr-3580.pdf["ネットアップテクニカルレポート 3580 ：『 NFSv4 の拡張内容とベスト・プラクティス・ガイド - Data ONTAP での実装』"]
+
ONTAP を実行するシステムに接続された AIX 、 Linux 、または Solaris クライアントに NFSv4 のコンポーネントを実装する際のベストプラクティスを紹介しています。





== ネットワーク構成

ネットワーク機能とネームサービスについてさらに詳しく設定するには、次の情報とテクニカルレポートを参照してください。

* link:../nfs-admin/index.html["NFS の管理"]
+
ONTAP ネットワークを設定および管理する方法について説明しています。

* http://www.netapp.com/us/media/tr-4182.pdf["ネットアップテクニカルレポート 4182 ：『 clustered Data ONTAP 構成でのイーサネットストレージのベストプラクティス』"]
+
ONTAP ネットワーク設定の実装について説明し、一般的なネットワーク導入シナリオおよびベストプラクティスの推奨事項を提供しています。

* https://www.netapp.com/pdf.html?item=/media/16328-tr-4668pdf.pdf["ネットアップテクニカルレポート 4668 ：『 Name Services Best Practices Guide 』"^]
+
認証用に LDAP 、 NIS 、 DNS 、およびローカルファイルの設定を行う方法について説明します。





== SAN プロトコルの設定

新しい SVM に対する SAN アクセスを提供または変更する場合は、 FC または iSCSI の設定情報を使用できます。この情報は、複数のホストオペレーティングシステムに対応しています。



== ルートボリュームの保護

SVM でプロトコルを設定したら、ルートボリュームを保護してください。

* link:../data-protection/index.html["データ保護"]
+
負荷共有ミラーを作成して SVM ルートボリュームを保護する方法について説明しています。これは、 NAS 対応の SVM に対するネットアップのベストプラクティスです。また、 SVM ルートボリュームを負荷共有ミラーから昇格させてボリュームの障害や消失からリカバリする簡単な方法についても説明しています。


