---
permalink: nfs-config/assess-networking-requirements-task.html 
sidebar: sidebar 
keywords: assess, networking, requirements 
summary: クライアントにNFSストレージを提供する前に、ネットワークが正しく設定されてNFSのプロビジョニング要件を満たしていることを確認する必要があります。 
---
= ネットワーク要件の評価
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
クライアントにNFSストレージを提供する前に、ネットワークが正しく設定されてNFSのプロビジョニング要件を満たしていることを確認する必要があります。

.必要なもの
次のクラスタネットワークオブジェクトを設定する必要があります。

* 物理ポートと論理ポート
* ブロードキャストドメイン
* サブネット（必要な場合）
* IPspace（必要に応じて、デフォルトのIPspaceに追加）
* フェイルオーバー グループ（必要に応じて、各ブロードキャスト ドメインのデフォルトのフェイルオーバー グループに追加）
* 外部ファイアウォール


.手順
. 使用可能な物理ポートと仮想ポートを表示します。
+
`network port show`

+
** 可能な場合は、データネットワークの速度が最も速いポートを使用してください。
** 最大限のパフォーマンスを実現するには、データネットワーク内のすべてのコンポーネントのMTU設定を同じにする必要があります。


. サブネット名を使用して LIF の IP アドレスとネットワークマスク値を割り当てる場合は、そのサブネットが存在し、十分な数のアドレスが使用可能であることを確認してください： +
+
`network subnet show`

+
サブネットには、同じレイヤ3サブネットに属するIPアドレスのプールが含まれています。サブネットは、コマンドを使用して作成し `network subnet create`ます。

. 使用可能なIPspaceを表示します。
+
`network ipspace show`

+
デフォルトのIPspaceまたはカスタムのIPspaceを使用できます。

. IPv6アドレスを使用する場合は、IPv6がクラスタで有効になっていることを確認します。
+
`network options ipv6 show`

+
必要に応じて、コマンドを使用してIPv6を有効にできます `network options ipv6 modify`。


