---
permalink: nfs-config/comparison-exports-7-mode-concept.html 
sidebar: sidebar 
keywords: comparison, exports, 7-mode ontap 
summary: ONTAP でのエクスポートは、定義方法と使用方法が 7-Mode 環境とは異なります。 
---
= 7-Mode と ONTAP のエクスポートの比較
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
ONTAP でのエクスポートは、定義方法と使用方法が 7-Mode 環境とは異なります。

|===


| 相違点 | 7-Mode | ONTAP 


 a| 
エクスポートの定義方法
 a| 
エクスポートは、で定義されます `/etc/exports` ファイル。
 a| 
エクスポートは、 SVM 内でエクスポートポリシーを作成することによって定義されます。SVM には複数のエクスポートポリシーを含めることができます。



 a| 
エクスポートの範囲
 a| 
* エクスポートは指定したファイルパスまたは qtree に適用されます。
* に別のエントリを作成する必要があります `/etc/exports` をクリックします。
* エクスポートは、で定義されている場合にのみ永続的になります `/etc/exports` ファイル。

 a| 
* エクスポートポリシーは、ボリューム内のすべてのファイルパスおよび qtree を含むボリューム全体に適用されます。
* エクスポートポリシーは、必要に応じて複数のボリュームに適用できます。
* システムの再起動後も、すべてのエクスポートポリシーが永続します。




 a| 
フェンシング（特定のクライアントに対して同じリソースへの別のアクセスを指定すること）
 a| 
特定のクライアントに、単一のエクスポートされたリソースへの別のアクセスを許可するには、で各クライアントと、許可されているアクセスをリストする必要があります `/etc/exports` ファイル。
 a| 
エクスポートポリシーは、多数のエクスポートルールで構成されています。エクスポートルールごとに、リソースに対する特定のアクセス権限が定義され、該当する権限を持つクライアントが一覧表示されます。特定のクライアントに対して異なるアクセスを指定するには、特定のアクセス権限セットごとにエクスポートルールを作成し、それらの権限を持つクライアントをリストして、エクスポートポリシーにルールを追加する必要があります。



 a| 
名前のエイリアス設定
 a| 
エクスポートを定義するときに、エクスポートの名前として、ファイルパスとは異なる名前を選択できます。を使用する必要があります `-actual` でこのようなエクスポートを定義するときのパラメータ `/etc/exports` ファイル。
 a| 
エクスポートされたボリュームの名前として、実際のボリューム名とは異なる名前を選択できます。そのためには、カスタムジャンクションパス名を持つボリュームをSVMネームスペース内でマウントする必要があります。


NOTE: デフォルトでは、ボリュームは、それぞれのボリューム名でマウントされます。ボリュームのジャンクションパス名をカスタマイズするには、マウント解除し、名前を変更してから、再マウントする必要があります。

|===