---
permalink: nfs-config/configure-dns-host-name-resolution-task.html 
sidebar: sidebar 
keywords: enabling, dns, host-name, resolution, enable, host, name, resolve, automatic configuration validation 
summary: vserver services name-service dns コマンドを使用して、SVM で DNS を有効にし、ホスト名の解決に DNS を使用するように設定できます。ホスト名は外部 DNS サーバを使用して解決されます。 
---
= ONTAP NFS SVMホスト名解決のためにDNSを有効にする
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
 `vserver services name-service dns`コマンドを使用してSVMでDNSを有効にし、ホスト名の解決にDNSを使用するように設定できます。ホスト名は外部DNSサーバを使用して解決されます。

.開始する前に
ホスト名を検索するために、サイト規模のDNSサーバが使用できなければなりません。

単一障害点を回避するため、複数のDNSサーバーを設定する必要があります。 `vserver services name-service dns create`コマンドは、DNSサーバー名を1つだけ入力した場合に警告を発します。

.タスク概要
link:../networking/configure_dynamic_dns_services.html["SVM でのダイナミック DNS の設定"]についての詳細をご覧ください。

.手順
. SVMでDNSを有効にします。
+
`vserver services name-service dns create -vserver _vserver_name_ -domains _domain_name_ -name-servers _ip_addresses_ -state enabled`

+
次のコマンドは、vs1というSVMで外部DNSサーバを有効にします。

+
[listing]
----
vserver services name-service dns create -vserver vs1.example.com -domains example.com -name-servers 192.0.2.201,192.0.2.202 -state enabled
----
+
[NOTE]
====
この `vserver services name-service dns create`コマンドは自動構成検証を実行し、ONTAPがネームサーバに接続できない場合はエラーメッセージを報告します。

====
.  `vserver services name-service dns show`コマンドを使用してDNSドメイン構成を表示します。
+
次のコマンドは、クラスタ内のすべてのSVMのDNS設定を表示します。

+
[listing]
----
vserver services name-service dns show
                                             Name
Vserver           State     Domains             Servers
----------------- --------- ------------------- -------------
cluster1          enabled   example.com         192.0.2.201,
                                                192.0.2.202
vs1.example.com   enabled   example.com         192.0.2.201,
                                                192.0.2.202
----
+
次のコマンドは、SVM vs1のDNS設定の詳細を表示します。

+
[listing]
----
vserver services name-service dns show -vserver vs1.example.com
               Vserver: vs1.example.com
               Domains: example.com
          Name Servers: 192.0.2.201, 192.0.2.202
    Enable/Disable DNS: enabled
        Timeout (secs): 2
      Maximum Attempts: 1
----
.  `vserver services name-service dns check`コマンドを使用してネームサーバーのステータスを検証します。
+
[listing]
----
vserver services name-service dns check -vserver vs1.example.com

Vserver           Name Server     Status       Status Details
----------------  -------------   ----------   --------------------------
vs1.example.com   10.0.0.50         up         Response time (msec): 2
vs1.example.com   10.0.0.51         up         Response time (msec): 2
----

