---
permalink: nfs-config/configure-dns-host-name-resolution-task.html 
sidebar: sidebar 
keywords: enabling, dns, host-name, resolution, enable, host, name, resolve, automatic configuration validation 
summary: SVM で DNS を有効にし、ホスト名解決に DNS を使用するように設定するには、 vserver services name-service dns コマンドを使用します。ホスト名は外部DNSサーバを使用して解決されます。 
---
= ONTAP NFS SVMのホスト名解決にDNSを有効にする
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
コマンドを使用して、SVMでDNSを有効にし、ホスト名解決にDNSを使用するように設定でき `vserver services name-service dns`ます。ホスト名は外部DNSサーバを使用して解決されます。

.開始する前に
ホスト名検索にサイト規模のDNSサーバが使用できる必要があります。

単一点障害を回避するには、複数のDNSサーバを設定する必要があります。 `vserver services name-service dns create`入力したDNSサーバ名が1つだけの場合は、コマンドによって警告が表示されます。

.タスクの内容
詳細については、をご覧ください link:../networking/configure_dynamic_dns_services.html["SVM でのダイナミック DNS の設定"]。

.手順
. SVMでDNSを有効にします。
+
`vserver services name-service dns create -vserver _vserver_name_ -domains _domain_name_ -name-servers _ip_addresses_ -state enabled`

+
次のコマンドは、vs1というSVMで外部DNSサーバを有効にします。

+
[listing]
----
vserver services name-service dns create -vserver vs1.example.com -domains example.com -name-servers 192.0.2.201,192.0.2.202 -state enabled
----
+
[NOTE]
====
コマンドは `vserver services name-service dns create`設定の自動検証を実行し、ONTAPがネームサーバに接続できない場合はエラーメッセージを報告します。

====
. コマンドを使用して、DNSドメイン設定を表示します `vserver services name-service dns show`。
+
次のコマンドは、クラスタ内のすべてのSVMのDNS設定を表示します。

+
[listing]
----
vserver services name-service dns show
                                             Name
Vserver           State     Domains             Servers
----------------- --------- ------------------- -------------
cluster1          enabled   example.com         192.0.2.201,
                                                192.0.2.202
vs1.example.com   enabled   example.com         192.0.2.201,
                                                192.0.2.202
----
+
次のコマンドを実行すると、SVM vs1のDNS設定の詳細が表示されます。

+
[listing]
----
vserver services name-service dns show -vserver vs1.example.com
               Vserver: vs1.example.com
               Domains: example.com
          Name Servers: 192.0.2.201, 192.0.2.202
    Enable/Disable DNS: enabled
        Timeout (secs): 2
      Maximum Attempts: 1
----
. コマンドを使用して、ネームサーバのステータスを検証し `vserver services name-service dns check`ます。
+
[listing]
----
vserver services name-service dns check -vserver vs1.example.com

Vserver           Name Server     Status       Status Details
----------------  -------------   ----------   --------------------------
vs1.example.com   10.0.0.50         up         Response time (msec): 2
vs1.example.com   10.0.0.51         up         Response time (msec): 2
----

