---
permalink: nfs-config/create-nis-domain-config-task.html 
sidebar: sidebar 
keywords: create, nis, domain, configuration, configure 
summary: 環境でネームサービス用に Network Information Service （ NIS ）が使用されている場合は、 vserver services name-service nis-domain create コマンドを使用して、 SVM 用の NIS ドメイン設定を作成する必要があります。 
---
= NISドメイン設定を作成する
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
環境でNetwork Information Service（NIS；ネットワーク情報サービス）がネームサービスに使用されている場合は、コマンドを使用して、SVMのNISドメイン設定を作成する必要があります `vserver services name-service nis-domain create`。

.開始する前に
SVMにNISドメインを設定するには、設定済みのすべてのNISサーバが使用可能で到達可能である必要があります。

ディレクトリ検索での NIS の使用を予定している場合、 NIS サーバ内のマップに 1 、 024 文字を超えるエントリを持たせることはできません。この制限に従っていないNISサーバを指定しないでください。そうしないと、NISエントリに依存するクライアントアクセスが失敗する可能性があります。

.タスクの内容
NISデータベースにマップが含まれている場合 `netgroup.byhost`、ONTAPはこのマップを使用して検索を高速化できます。 `netgroup.byhost`ディレクトリ内のマップと `netgroup`マップは、クライアントアクセスに関する問題を回避するために、常に同期されている必要があります。nis.7以降では、コマンドを使用してONTAP 9 `netgroup.byhost`エントリをキャッシュでき `vserver services name-service nis-domain netgroup-database`ます。

ホスト名解決にNISを使用することはサポートされていません。

.手順
. NISドメイン設定を作成します。
+
`vserver services name-service nis-domain create -vserver vs1 -domain <domain_name> -nis-servers <IP_addresses>`

+
最大10台のNISサーバを指定できます。

+
[NOTE]
====
ONTAP 9 .2以降では、 `-nis-servers`フィールドがフィールドに置き換わります `-servers`。この新しいフィールドには、NISサーバのホスト名またはIPアドレスを指定できます。

====
. ドメインが作成されたことを確認します。
+
`vserver services name-service nis-domain show`



.例
次のコマンドは、という名前のSVM上に、IPアドレスのNISサーバを使用して `192.0.2.180`、という名前の `vs1`NISドメインのNISドメイン設定を作成し `nisdomain`ます。

[listing]
----
vs1::> vserver services name-service nis-domain create -vserver vs1 -domain nisdomain -nis-servers 192.0.2.180
----