---
permalink: nfs-config/create-svms-data-access-task.html 
sidebar: sidebar 
keywords: create, svm 
summary: クラスタ内にNFSクライアントにデータ アクセスを提供するSVMが1つもない場合は、作成する必要があります。 
---
= SVMの作成
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
クラスタ内にNFSクライアントにデータ アクセスを提供するSVMが1つもない場合は、作成する必要があります。

.開始する前に
* ONTAP 9.13.1以降では、Storage VMに最大容量を設定できます。また、SVMの容量レベルがしきい値に近づいたときにアラートを設定することもできます。詳細については、を参照してください xref:../volumes/manage-svm-capacity.html[SVM容量の管理]。


.手順
. SVMを作成します。
+
`vserver create -vserver _vserver_name_ -rootvolume _root_volume_name_ -aggregate _aggregate_name_ -rootvolume-security-style unix -language C.UTF-8 -ipspace _ipspace_name_`

+
** オプションにはUNIX設定を使用し `-rootvolume-security-style`ます。
** デフォルトのC.UTF-8オプションを使用し `-language`ます。
** この `ipspace`設定はオプションです。


. 新しく作成したSVMの設定とステータスを確認します。
+
`vserver show -vserver _vserver_name_`

+
 `Allowed Protocols`フィールドにはnfsを指定する必要があります。このリストは後で編集できます。

+
 `Vserver Operational State`フィールドには状態が表示されている必要があり `running`ます。状態が表示された場合は `initializing`、ルートボリュームの作成などの中間処理が失敗したため、SVMを削除して再作成する必要があります。



.例
次のコマンドは、データアクセス用のSVMをIPspace ipspaceAに作成します。

[listing]
----
cluster1::> vserver create -vserver vs1.example.com -rootvolume root_vs1 -aggregate aggr1
-rootvolume-security-style unix -language C.UTF-8 -ipspace ipspaceA

[Job 2059] Job succeeded:
Vserver creation completed
----
次のコマンドは、1GBのルートボリュームでSVMが作成され、自動的に起動されて状態になっていることを示しています `running`。ルートボリュームには、ルールが含まれていないデフォルトのエクスポートポリシーがあるため、ルートボリュームは作成時にエクスポートされません。

[listing]
----
cluster1::> vserver show -vserver vs1.example.com
                                    Vserver: vs1.example.com
                               Vserver Type: data
                            Vserver Subtype: default
                               Vserver UUID: b8375669-19b0-11e5-b9d1-00a0983d9736
                                Root Volume: root_vs1
                                  Aggregate: aggr1
                                 NIS Domain: -
                 Root Volume Security Style: unix
                                LDAP Client: -
               Default Volume Language Code: C.UTF-8
                            Snapshot Policy: default
                                    Comment:
                               Quota Policy: default
                List of Aggregates Assigned: -
 Limit on Maximum Number of Volumes allowed: unlimited
                        Vserver Admin State: running
                  Vserver Operational State: running
   Vserver Operational State Stopped Reason: -
                          Allowed Protocols: nfs, cifs, fcp, iscsi, ndmp
                       Disallowed Protocols: -
                           QoS Policy Group: -
                                Config Lock: false
                               IPspace Name: ipspaceA
----

NOTE: ONTAP 9.13.1以降では、アダプティブQoSポリシーグループテンプレートを設定して、SVM内のボリュームにスループットの下限と上限の制限を適用できます。このポリシーはSVMの作成後にのみ適用できます。このプロセスの詳細については、を参照してくださいxref:../performance-admin/adaptive-policy-template-task.html[アダプティブポリシーグループテンプレートの設定]。
