---
permalink: nfs-config/create-kerberos-realm-config-task.html 
sidebar: sidebar 
keywords: create, nfs, kerberos, realm, configuration 
summary: ONTAPで環境内の外部Kerberosサーバにアクセスする場合は、まず既存のKerberosレルムを使用するようにSVMを設定する必要があります。そのためには、Kerberos KDCサーバの設定値を収集してから、vserver nfs kerberos realm createコマンドを使用してSVM上にKerberosレルム設定を作成する必要があります。 
---
= ONTAP SVMでNFS Kerberosレルム構成を作成する
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
ONTAPで環境内の外部Kerberosサーバにアクセスする場合は、まず既存のKerberosレルムを使用するようにSVMを設定する必要があります。そのためには、Kerberos KDCサーバの設定値を収集してから、 `vserver nfs kerberos realm create`コマンドを使用してSVM上にKerberosレルム設定を作成する必要があります。

.開始する前に
認証の問題を回避するため、クラスタ管理者はストレージ システム、クライアント、およびKDCサーバにNTPを設定する必要があります。クライアントとサーバ間の時刻差（クロック スキュー）は、認証失敗の一般的な原因です。

.手順
. Kerberos管理者に相談して、 `vserver nfs kerberos realm create`コマンドに指定する適切な構成値を決定してください。
. SVM に Kerberos レルム設定を作成します：
+
`vserver nfs kerberos realm create -vserver _vserver_name_ -realm _realm_name_ _{AD_KDC_server_values |AD_KDC_server_values}_ -comment "_text_"`

. Kerberos Realm設定が正常に作成されたことを確認します。
+
`vserver nfs kerberos realm show`



.例
次のコマンドは、SVM vs1のNFS Kerberosレルム設定を作成します。この設定では、Microsoft Active DirectoryサーバをKDCサーバとして使用します。Kerberosレルムは AUTH.EXAMPLE.COM です。Active Directoryサーバの名前は ad-1、IPアドレスは 10.10.8.14 です。許容クロックスキューは 300 秒（デフォルト）です。KDCサーバのIPアドレスは 10.10.8.14、ポート番号は 88（デフォルト）です。コメントは「Microsoft Kerberos config」です。

[listing]
----
vs1::> vserver nfs kerberos realm create -vserver vs1 -realm AUTH.EXAMPLE.COM -adserver-name ad-1
-adserver-ip 10.10.8.14 -clock-skew 300 -kdc-ip 10.10.8.14 -kdc-port 88 -kdc-vendor Microsoft
-comment "Microsoft Kerberos config"
----
次のコマンドは、MIT KDCを使用するSVM vs1のNFS Kerberosレルム設定を作成します。Kerberosレルムは SECURITY.EXAMPLE.COM です。許容クロック スキューは300秒です。KDCサーバのIPアドレスは10.10.9.1、ポート番号は88です。KDCベンダーはUNIXベンダーを示す「Other」です。管理サーバのIPアドレスは10.10.9.1、ポート番号は749（デフォルト）です。パスワード サーバのIPアドレスは10.10.9.1、ポート番号は464（デフォルト）です。コメントは「UNIX Kerberos config」です。

[listing]
----
vs1::> vserver nfs kerberos realm create -vserver vs1 -realm SECURITY.EXAMPLE.COM. -clock-skew 300
-kdc-ip 10.10.9.1 -kdc-port 88 -kdc-vendor Other -adminserver-ip 10.10.9.1 -adminserver-port 749
-passwordserver-ip 10.10.9.1 -passwordserver-port 464 -comment "UNIX Kerberos config"
----