---
permalink: nfs-config/index.html 
sidebar: sidebar 
keywords: NFS, configuration, overview 
summary: このコンテンツでは、 ONTAP 9 の CLI コマンドを使用して、新規または既存の SVM の新しいボリュームまたは qtree に格納されているファイルへの NFS クライアントアクセスを設定する方法を説明します。 
---
= CLI を使用した NFS の設定の概要
:icons: font
:imagesdir: ../media/


[role="lead"]
このコンテンツでは、 ONTAP 9 の CLI コマンドを使用して、新規または既存の Storage Virtual Machine （ SVM ）の新しいボリュームまたは qtree に格納されているファイルへの NFS クライアントアクセスを設定する方法を説明します。例と高度な設定オプションが含まれています。

このコンテンツは、ボリュームまたは qtree へのアクセスを設定する場合に使用します。想定している状況は次のとおりです。

* ONTAP で現在サポートされている次のいずれかのバージョンを使用する必要がある： NFSv3 、 NFSv4 、 NFSv4.1 、 NFSv4.2 、または pNFS を使用する NFSv4.1 。
* System Manager や自動スクリプトツールではなく、コマンドラインインターフェイス（ CLI ）を使用する必要がある。
* すべての選択肢について検討するのではなく、ベストプラクティスに従う。
+
コマンド構文の詳細については、 CLI ヘルプおよび ONTAP のマニュアルページを参照してください。

* 背景にある概念について詳しく確認する必要はありません。
+
ONTAP 追加情報テクノロジおよび外部サービスとのやり取りについては、 ONTAP リファレンスライブラリおよびテクニカルレポート（ TR ）を参照してください。

* 新しいボリュームを UNIX ファイル権限を使用して保護する。
* SVM 管理者権限ではなくクラスタ管理者権限を持っている。


ONTAP NFS プロトコルの機能の範囲に関する詳細を確認する場合は、次の資料を参照してください。

* link:../nfs-admin/index.html["NFS のリファレンスの概要"]

