---
permalink: nfs-config/load-local-unix-users-uri-task.html 
sidebar: sidebar 
keywords: load, local, unix, users, uri 
summary: SVM で個々のローカル UNIX ユーザーを手動で作成する代わりに、URI（Uniform Resource Identifier）からローカル UNIX ユーザーのリストを SVM にロードすることでタスクを簡素化できます（vserver services name-service unix-user load-from-uri）。 
---
= ONTAP NFS SVMにローカルUNIXユーザーリストをロードする
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
SVM で個々のローカル UNIX ユーザーを手動で作成する代わりに、Uniform Resource Identifier（URI(`vserver services name-service unix-user load-from-uri`）からローカル UNIX ユーザーのリストを SVM にロードすることで、タスクを簡素化できます。

.手順
. ロードするローカル UNIX ユーザーのリストを含むファイルを作成します。
+
ファイルには、UNIX `/etc/passwd` 形式のユーザー情報が含まれている必要があります：

+
`_user_name: password: user_ID: group_ID: full_name_`

+
このコマンドは、 `_password_`フィールドの値と、 `_full_name_`フィールドの後のフィールドの値（(`_home_directory_`および `_shell_`）を破棄します。

+
サポートされるファイルの最大サイズは2.5MBです。

. リストに重複する情報が含まれていないことを確認します。
+
リストに重複したエントリが含まれている場合、リストの読み込みは失敗し、エラーメッセージが表示されます。

. ファイルをサーバーにコピーします。
+
サーバーは、HTTP、HTTPS、FTP、または FTPS 経由でストレージ システムからアクセスできる必要があります。

. ファイルの URI を確認します。
+
URI は、ファイルが配置されている場所を示すためにストレージシステムに提供するアドレスです。

. ローカル UNIX ユーザーのリストを含むファイルを URI から SVM にロードします：
+
`vserver services name-service unix-user load-from-uri -vserver _vserver_name_ -uri {ftp|http|ftps|https}://_uri_ -overwrite {true|false}`

+
`-overwrite` {`true` `false`} はエントリを上書きするかどうかを指定します。デフォルトは `false`です。



.例
次のコマンドは、URI `+ftp://ftp.example.com/passwd+`からローカルUNIXユーザーのリストをvs1という名前のSVMにロードします。SVM上の既存のユーザーは、URIの情報によって上書きされません。

[listing]
----
node::> vserver services name-service unix-user load-from-uri -vserver vs1
-uri ftp://ftp.example.com/passwd -overwrite false
----