---
permalink: nfs-config/test-access-client-systems-task.html 
sidebar: sidebar 
keywords: testing, nfs, access, client, systems 
summary: 新しいストレージ オブジェクトへのNFSアクセスを確認したら、NFS管理ホストにログインし、SVMとの間でデータの読み取りと書き込みを実行して設定をテストする必要があります。その後、クライアント システム上で非rootユーザとしてこのプロセスを繰り返します。 
---
= クライアント システムからのONTAP NFSアクセスをテストする
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
新しいストレージ オブジェクトへのNFSアクセスを確認したら、NFS管理ホストにログインし、SVMとの間でデータの読み取りと書き込みを実行して設定をテストする必要があります。その後、クライアント システム上で非rootユーザとしてこのプロセスを繰り返します。

.開始する前に
* クライアント システムには、先ほど指定したエクスポート ルールで許可されているIPアドレスが必要です。
* rootユーザのログイン情報が必要です。


.手順
. クラスター上で、新しいボリュームをホストしている LIF の IP アドレスを確認します：
+
`network interface show –vserver _svm_name_`

+
 `network interface show`の詳細については、link:https://docs.netapp.com/us-en/ontap-cli/network-interface-show.html["ONTAPコマンド リファレンス"^]を参照してください。

. 管理ホスト クライアント システムに root ユーザとしてログインします。
. ディレクトリをマウント フォルダーに変更します：
+
`cd /mnt/`

. SVM の IP アドレスを使用して新しいフォルダを作成してマウントします：
+
.. 新しいフォルダを作成：+
`mkdir /mnt/_folder_`
.. 新しいボリュームをこの新しいディレクトリにマウントします：+
`mount -t nfs -o hard _IPAddress_:/_volume_name_ /mnt/_folder_`
.. ディレクトリを新しいフォルダに変更します：+
`cd _folder_`
+
次のコマンドは、test1という名前のフォルダを作成し、test1マウント フォルダのIPアドレス192.0.2.130にvol1ボリュームをマウントし、新しいtest1ディレクトリに変更します：

+
[listing]
----
host# mkdir /mnt/test1
host# mount -t nfs -o hard 192.0.2.130:/vol1 /mnt/test1
host# cd /mnt/test1
----


. 新しいファイルを作成し、それが存在することを確認して、そこにテキストを書き込みます：
+
.. テストファイルを作成します：+
`touch _filename_`
.. ファイルが存在することを確認してください：+
`ls -l _filename_`
.. 入力：+
`cat > _filename_`
+
テキストを入力し、Ctrl+Dを押してテスト ファイルにテキストを書き込みます。

.. テストファイルの内容を表示します。+
`cat _filename_`
.. テストファイルを削除します：+
`rm _filename_`
.. 親ディレクトリに戻る：+
`cd ..`
+
[listing]
----
host# touch myfile1
host# ls -l myfile1
-rw-r--r-- 1 root root 0 Sep 18 15:58 myfile1
host# cat >myfile1
This text inside the first file
host# cat myfile1
This text inside the first file
host# rm -r myfile1
host# cd ..
----


. root として、マウントされたボリュームに必要な UNIX 所有権と権限を設定します。
. エクスポート ルールで識別された UNIX クライアント システムで、新しいボリュームへのアクセス権を持つ承認済みユーザーの 1 人としてログインし、手順 3 ～ 5 を繰り返して、ボリュームをマウントしてファイルを作成できることを確認します。

