---
permalink: nfs-config/verify-protocol-enabled-svm-task.html 
sidebar: sidebar 
keywords: verify, nfs, protocol, enabled, svm 
summary: SVMでNFSを設定して使用する前に、このプロトコルが有効になっていることを確認する必要があります。 
---
= SVMでNFSプロトコルが有効になっていることの確認
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
SVMでNFSを設定して使用する前に、このプロトコルが有効になっていることを確認する必要があります。

.タスクの内容
この作業は通常、SVMのセットアップ時に実行します。ただし、セットアップ時にプロトコルを有効にしなかった場合でも、コマンドを使用してあとから有効にすることができます `vserver add-protocols`。

[NOTE]
====
作成したプロトコルは、 LIF から追加または削除することはできません。

====
コマンドを使用して、SVMのプロトコルを無効にすることもできます `vserver remove-protocols`。

.手順
. 現在 SVM で有効になっているプロトコルと無効になっているプロトコルを確認します。
+
`vserver show -vserver _vserver_name_ -protocols`

+
コマンドを使用して、クラスタ内のすべてのSVMで現在有効になっているプロトコルを表示することもできます `vserver show-protocols`。

. 必要に応じて、プロトコルを有効または無効にします。
+
** NFSプロトコルを有効にするには+
`vserver add-protocols -vserver _vserver_name_ -protocols nfs`
** プロトコルを無効にするには：+
`vserver remove-protocols -vserver    _vserver_name_ -protocols _protocol_name_[,_protocol_name_,...]`


. 有効 / 無効なプロトコルが正しく更新されたことを確認します。
+
`vserver show -vserver _vserver_name_ -protocols`



.例
次のコマンドは、 vs1 という SVM で現在有効 / 無効（許可 / 不許可）になっているプロトコルを表示します。

[listing]
----
vs1::> vserver show -vserver vs1.example.com -protocols
Vserver           Allowed Protocols         Disallowed Protocols
-----------       ----------------------    -----------------------
vs1.example.com   nfs                       cifs, fcp, iscsi, ndmp
----
次のコマンドは、vs1というSVMで有効になっているプロトコルのリストにを追加することで、NFS経由のアクセスを許可し `nfs`ます。

[listing]
----
vs1::> vserver add-protocols -vserver vs1.example.com -protocols nfs
----