---
permalink: nfs-config/work-netgroups-task.html 
sidebar: sidebar 
keywords: work, netgroups 
summary: ネットグループは、ユーザ認証に使用したり、エクスポートポリシールールでクライアントを照合したりするために使用できます。外部ネームサーバ（ LDAP または NIS ）からネットグループへのアクセスを提供できるほか、 vserver services name-service netgroup load コマンドを使用して、 Uniform Resource Identifier （ URI ）を使用して SVM にネットグループをロードすることもできます。 
---
= ネットグループの使用の概要
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
ネットグループは、ユーザ認証に使用したり、エクスポートポリシールールでクライアントを照合したりするために使用できます。外部ネームサーバ（LDAPまたはNIS）からネットグループへのアクセスを提供することも、コマンドを使用してUniform Resource Identifier（URI）からSVMへネットグループをロードすることもできます `vserver services name-service netgroup load`。

.必要なもの
ネットグループを使用する前に、次の条件を満たしていることを確認する必要があります。

* ネットグループ内のすべてのホストは、ソース（NIS、LDAP、またはローカルファイル）に関係なく、フォワードおよびリバースDNSルックアップの一貫性を提供するために、フォワード（A）およびリバース（PTR）の両方のDNSレコードを持つ必要があります。
+
さらに、クライアントのIPアドレスに複数のPTRレコードがある場合、それらのホスト名はすべてネットグループのメンバーであり、対応するAレコードを持っている必要があります。

* ソース（NIS、LDAP、またはローカルファイル）に関係なく、ネットグループ内のすべてのホストの名前のスペルが正しく、大文字と小文字が正しい必要があります。ネットグループで使用されているホスト名に大文字と小文字の不一致があると、予期しない動作（エクスポートチェックの失敗など）が発生する可能性があります。
* ネットグループに指定されているすべてのIPv6アドレスは、RFC 5952の指定に従って短縮および圧縮する必要があります。
+
たとえば、 2011 ： hu9 ： 0 ： 0 ： 0 ： 0 ： 3 ： 1 は 2011 ： hu9 ： 3 ： 1 に短縮する必要があります。



.タスクの内容
ネットグループについては次の処理を実行できます。

* コマンドを使用すると、クライアントIPが特定のネットグループのメンバーであるかどうかを確認できます `vserver export-policy netgroup check-membership`。
* コマンドを使用すると、クライアントがネットグループの一部であるかどうかを確認できます `vserver services name-service getxxbyyy netgrp`。
+
検索を実行するための基盤となるサービスは、設定されているネームサービススイッチの順序に基づいて選択されます。


