---
permalink: system-admin/access-nodeshell-commands-options-clustershell-concept.html 
sidebar: sidebar 
keywords: nodeshell, command, access, option, clustershell 
summary: 'ノードシェルのコマンドとオプションには、ノードシェル（ system node run – nodenodename) ）を使用してアクセスできます。よく使用されるノードシェルコマンドとオプションの多くは、クラスタシェルにトンネリングまたはエイリアスされ、クラスタシェルから実行することもできます。' 
---
= クラスタシェルでのノードシェルのコマンドおよびオプションへのアクセス
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
ノードシェルのコマンドとオプションには、ノードシェルからアクセスできます。

`system node run –node _nodename_`

よく使用されるノードシェルコマンドとオプションの多くは、クラスタシェルにトンネリングまたはエイリアスされ、クラスタシェルから実行することもできます。

クラスタシェルでサポートされているノードシェルオプションには、を使用してアクセスできます `vserver options clustershell` コマンドを実行しますこれらのオプションを表示するには、次のいずれかを実行します。

* を使用してクラスタシェルCLIを照会します `vserver options -vserver _nodename_or_clustername_ -option-name`?
* にアクセスします `vserver options` を使用したクラスタシェルCLIのマニュアルページ `man vserver options`


クラスタシェルでノードシェルまたはレガシー ONTAP のコマンドまたはオプションを入力した場合、そのコマンドまたはオプションに相当するクラスタシェルコマンドがある場合には該当するクラスタシェルコマンドを使用するように通知されます。

クラスタシェルでノードシェルまたはレガシーのコマンドまたはオプションを入力した場合、そのコマンドまたはオプションについて「 not supported 」ステータスが ONTAP から通知されます。
