---
permalink: system-admin/access-cluster-telnet-task.html 
sidebar: sidebar 
keywords: access, cluster, telnet, administrative, tasks, disbale, default 
summary: 管理タスクを実行するために、クラスタへの問題 Telnet 要求を行うことができます。Telnet はデフォルトでは無効になっています。 
---
= Telnet を使用してクラスタにアクセスします
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
管理タスクを実行するために、クラスタへの問題 Telnet 要求を行うことができます。Telnet はデフォルトでは無効になっています。

.必要なもの
Telnet を使用してクラスタにアクセスするには、次の条件を満たしている必要があります。

* アクセス方法として Telnet を使用するように設定されたクラスタローカルユーザアカウントを持っている必要があります。
+
。 `-application` のパラメータ `security login` コマンドは、ユーザアカウントのアクセス方法を指定します。詳細については、を参照してください `security login` マニュアルページ

* Telnet 要求がファイアウォールを通過できるように、クラスタ管理 LIF またはノード管理 LIF によって使用される管理ファイアウォールポリシーで Telnet が有効になっている必要があります。
+
デフォルトでは、 Telnet は無効になっています。。 `system services firewall policy show` コマンドにを指定します `-service telnet` パラメータは、ファイアウォールポリシーでTelnetが有効になっているかどうかを表示します。詳細については、を参照してください `system services firewall policy` マニュアルページ

* IPv6 接続を使用する場合は、クラスタで IPv6 が設定されて有効になっている必要があります。また、ファイアウォールポリシーに IPv6 アドレスが設定されている必要があります。
+
。 `network options ipv6 show` IPv6が有効になっているかどうかを表示します。。 `system services firewall policy show` コマンドは、ファイアウォールポリシーを表示します。



.このタスクについて
* Telnet はセキュアなプロトコルではありません。
+
クラスタにアクセスするときは、 SSH を使用することを検討してください。SSH は、セキュアなリモートシェルと対話型のネットワークセッションを提供します。

* ONTAP では、 1 つのノードについて同時に最大 50 の Telnet セッションがサポートされています。
+
クラスタ管理 LIF がノード上に存在する場合、クラスタ管理 LIF はこの制限をノード管理 LIF と共有します。

+
着信接続数が 1 秒あたり 10 を超えると、サービスは一時的に 60 秒間無効になります。

* ONTAP CLI に Windows ホストからアクセスする場合は、 PuTTY などのサードパーティのユーティリティを使用できます。


.手順
. 管理ホストで次のコマンドを入力します。
+
`*telnet _hostname_or_IP_*`

+
`_hostname_or_IP_` は、クラスタ管理LIFまたはノード管理LIFのホスト名またはIPアドレスです。クラスタ管理 LIF を使用することを推奨します。IPv4 または IPv6 アドレスを使用できます。



.Telnet要求の例
次の例は、 Telnet アクセスを使用するように設定された「 joe 」というユーザが、クラスタ管理 LIF が 10.72.137.28 であるクラスタにアクセスする Telnet 要求を問題に送信する方法を示しています。

[listing]
----
admin_host$ telnet 10.72.137.28
Data ONTAP
login: joe
Password:
cluster1::>
----