---
permalink: system-admin/accessg-node-log-core-dump-mib-files-task.html 
sidebar: sidebar 
keywords: service, processor, infrastructure, spi, web, service, node, log, core, dump, mib, file, browser 
summary: サービスプロセッサインフラストラクチャ（ spi ） Web サービスはデフォルトで有効になり、クラスタ内のノードのログファイル、コアダンプファイル、 MIB ファイルに Web ブラウザでアクセスできます。ノードが停止しても（パートナーにテイクオーバーされていれば）ファイルに引き続きアクセスできます。 
---
= Webブラウザを使用してONTAPノードログ、コアダンプ、MIBファイルにアクセスする
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
サービスプロセッサインフラ(`spi`）Webサービスはデフォルトで有効になっており、クラスタ内のノードのログファイル、コアダンプファイル、MIBファイルにWebブラウザからアクセスできます。ノードが停止しても（パートナーにテイクオーバーされていれば）ファイルに引き続きアクセスできます。

.開始する前に
* クラスタ管理LIFが稼働している必要があります。
+
Webサービスには、クラスタまたはノードの管理LIFを使用してアクセスできます `spi`。ただし、クラスタ管理LIFを使用することを推奨します。

+
 `network interface show`コマンドは、クラスタ内のすべてのLIFのステータスを表示します。

+
の詳細については `network interface show`、をlink:https://docs.netapp.com/us-en/ontap-cli/network-interface-show.html["ONTAPコマンド リファレンス"^]参照してください。

* Webサービスにアクセスするにはローカルユーザアカウントを使用する必要があり `spi`ます。ドメインユーザアカウントはサポートされません。
* ユーザーアカウントに `admin`ロール（  `spi`デフォルトではウェブサービスにアクセスできませんが、アクセス制御ロールに `spi`ウェブサービス。
+
 `vserver services web access show`コマンドは、どのロールにどのWebサービスへのアクセスが許可されているかを表示します。

* 使用していない場合 `admin`ユーザーアカウント（  `http`デフォルトのアクセス方法を使用する場合、ユーザーアカウントは `http`アクセス方法。
+
 `security login show`コマンドは、ユーザアカウントのアクセス方法とログイン方法、およびアクセス制御ロールを表示します。

+
の詳細については `security login show`、をlink:https://docs.netapp.com/us-en/ontap-cli/security-login-show.html["ONTAPコマンド リファレンス"^]参照してください。

* セキュアなWebアクセスにHTTPSを使用する場合は、SSLを有効にし、デジタル証明書をインストールする必要があります。
+
 `system services web show`コマンドは、クラスタレベルのWebプロトコルエンジンの設定を表示します。



.タスクの内容
 `spi`Webサービスはデフォルトで有効になっており、サービスは手動で無効にすることができ(`vserver services web modify -vserver * -name spi -enabled false`ます）。

その `admin`役割には、  `spi`デフォルトではウェブサービスであり、アクセスは手動で無効にすることができます(`services web access delete -vserver _cluster_name_ -name spi -role admin` ）。

.手順
. Webブラウザで、次のいずれかの形式でWebサービスURLを指定し `spi`ます。
+
** `http://_cluster-mgmt-LIF_/spi/`
** `https://_cluster-mgmt-LIF_/spi/`
+
`cluster-mgmt-LIF`は、クラスタ管理LIFのIPアドレスです。



. ブラウザにプロンプトが表示されたら、ユーザアカウントとパスワードを入力します。
+
アカウントが認証されると、クラスタ内の各ノードの、 `/mroot/etc/crash/`および `/mroot/etc/mib/`ディレクトリへのリンクがブラウザに表示されます `/mroot/etc/log/`。


