---
permalink: system-admin/access-system-console-node-task.html 
sidebar: sidebar 
keywords: access, system, console, node, serial, ssh, sp, boot 
summary: ブートメニューまたはブート環境のプロンプトでハングしているノードには、システムコンソール（シリアルコンソールとも呼ばれる）を介してのみアクセスできます。ノードのシステムコンソールには、ノードの SP またはクラスタへの SSH 接続からアクセスできます。 
---
= ノードのシステムコンソールにアクセスします
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
ブートメニューまたはブート環境のプロンプトでハングしているノードには、システムコンソール（ _serial console_） 経由でのみアクセスできます。ノードのシステムコンソールには、ノードの SP またはクラスタへの SSH 接続からアクセスできます。

.このタスクについて
SP と ONTAP はどちらもシステムコンソールにアクセスするためのコマンドを提供しています。ただし、 SP からはそのノードのシステムコンソールにしかアクセスできません。クラスタからはクラスタ内の任意のノードのシステムコンソールにアクセスできます。

.手順
. ノードのシステムコンソールにアクセスします。
+
|===
| 使用する環境 | 入力するコマンド 


 a| 
ノードの SP CLI
 a| 
`system console`



 a| 
ONTAP CLI
 a| 
`system node run-console`

|===
. プロンプトが表示されたら、システムコンソールにログインします。
. システムコンソールを終了するには、 Ctrl+D を押します


.システムコンソールへのアクセスの例
次の例は、を入力した場合の出力結果を示しています `system console` 「SP node2」プロンプトでコマンドを実行します。システムコンソールに、 node2 がブート環境のプロンプトでハングしていることが示されています。。 `boot_ontap` コンソールでコマンドを入力してノードをONTAP でブートし、続いて Ctrl+D を押してコンソールを終了し、 SP に戻ります。

[listing]
----
SP node2> system console
Type Ctrl-D to exit.

LOADER>
LOADER> boot_ontap
...
*******************************
*                             *
* Press Ctrl-C for Boot Menu. *
*                             *
*******************************
...
----
（ Ctrl+D を押してシステムコンソールを終了しています）

[listing]
----

Connection to 123.12.123.12 closed.
SP node2>
----
次の例は、を入力した場合の出力結果を示しています `system node run-console` ONTAP からコマンドを実行してnode2のシステムコンソールにアクセスします。このコンソールはブート環境のプロンプトでハングします。。 `boot_ontap` コンソールでコマンドを入力してnode2をONTAP でブートし、続いて Ctrl+D を押してコンソールを終了し、 ONTAP に戻ります。

[listing]
----
cluster1::> system node run-console -node node2
Pressing Ctrl-D will end this session and any further sessions you might open on top of this session.
Type Ctrl-D to exit.

LOADER>
LOADER> boot_ontap
...
*******************************
*                             *
* Press Ctrl-C for Boot Menu. *
*                             *
*******************************
...
----
（ Ctrl+D を押してシステムコンソールを終了しています）

[listing]
----

Connection to 123.12.123.12 closed.
cluster1::>
----