---
permalink: system-admin/access-system-console-node-task.html 
sidebar: sidebar 
keywords: access, system, console, node, serial, ssh, sp, boot 
summary: ブートメニューまたはブート環境のプロンプトでハングしているノードには、システムコンソール（シリアルコンソールとも呼ばれる）を介してのみアクセスできます。ノードのシステムコンソールには、ノードの SP またはクラスタへの SSH 接続からアクセスできます。 
---
= ノードのシステムコンソールにアクセスします
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
ブートメニューまたはブート環境のプロンプトでハングしているノードには、システムコンソール（ _serial console_） 経由でのみアクセスできます。ノードのシステムコンソールには、ノードの SP またはクラスタへの SSH 接続からアクセスできます。

SP と ONTAP はどちらもシステムコンソールにアクセスするためのコマンドを提供しています。ただし、 SP からはそのノードのシステムコンソールにしかアクセスできません。クラスタからはクラスタ内の任意のノードのシステムコンソールにアクセスできます。

.手順
. ノードのシステムコンソールにアクセスします。
+
|===
| 使用する環境 | 入力するコマンド 


 a| 
ノードの SP CLI
 a| 
「システムコンソール」



 a| 
ONTAP CLI
 a| 
「 system node run-console 」というメッセージが表示されます

|===
. プロンプトが表示されたら、システムコンソールにログインします。
. システムコンソールを終了するには、 Ctrl+D を押します


次の例は、「 `S P node2 ` 」プロンプトで「 system console 」コマンドを入力した結果を示しています。システムコンソールに、 node2 がブート環境のプロンプトでハングしていることが示されています。コンソールで「 boot_ontap 」コマンドを入力し、ノードを ONTAP でブートします。続いて Ctrl+D を押してコンソールを終了し、 SP に戻ります。

[listing]
----
SP node2> system console
Type Ctrl-D to exit.

LOADER>
LOADER> boot_ontap
...
*******************************
*                             *
* Press Ctrl-C for Boot Menu. *
*                             *
*******************************
...
----
（ Ctrl+D を押してシステムコンソールを終了しています）

[listing]
----

Connection to 123.12.123.12 closed.
SP node2>
----
次の例は、 ONTAP から「 system node run-console 」コマンドを入力し、 node2 のシステムコンソールにアクセスした結果です。このコンソールはブート環境のプロンプトでハングしています。コンソールで「 boot_ontap 」コマンドを入力し、 node2 を ONTAP でブートします。続いて Ctrl+D を押してコンソールを終了し、 ONTAP に戻ります。

[listing]
----
cluster1::> system node run-console -node node2
Pressing Ctrl-D will end this session and any further sessions you might open on top of this session.
Type Ctrl-D to exit.

LOADER>
LOADER> boot_ontap
...
*******************************
*                             *
* Press Ctrl-C for Boot Menu. *
*                             *
*******************************
...
----
（ Ctrl+D を押してシステムコンソールを終了しています）

[listing]
----

Connection to 123.12.123.12 closed.
cluster1::>
----