---
permalink: system-admin/accounts-access-sp-concept.html 
sidebar: sidebar 
keywords: account, access, sp, cluster, user, cli, node 
summary: SP にアクセスする際には、クレデンシャルを求められます。アプリケーションタイプ service-processor で作成されたクラスタユーザアカウントは、クラスタの任意のノード上の SP CLI にアクセスできます。SP ユーザアカウントは、 ONTAP から管理され、パスワードによって認証されます。ONTAP 9.9.1以降では、SPユーザアカウントにadminロールが必要です。 
---
= SP にアクセスできるアカウント
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
SP にアクセスする際には、クレデンシャルを求められます。で作成したクラスタユーザアカウント `service-processor` アプリケーションタイプは、クラスタの任意のノードのSP CLIにアクセスできます。SP ユーザアカウントは、 ONTAP から管理され、パスワードによって認証されます。ONTAP 9.9.1以降では、SPユーザアカウントにが必要です `admin` ロール。

SP にアクセスするためのユーザアカウントは、 SP CLI ではなく ONTAP で管理します。で作成されたクラスタユーザアカウントは、SPにアクセスできます `-application` のパラメータ `security login create` コマンドをに設定します `service-processor` および `-authmethod` パラメータをに設定します `password`。SP ではパスワード認証のみサポートされます。

を指定する必要があります `-role` SPユーザアカウント作成時のパラメータ。

* ONTAP 9.9.1以降のリリースでは、を指定する必要があります `admin` をクリックします `-role` パラメータを使用し、アカウントを変更するにはを使用する必要があります `admin` ロール。セキュリティ上の理由から、他のロールは使用できなくなりました。
+
** ONTAP 9.9.1以降のリリースにアップグレードする場合は、を参照してください link:../upgrade/sp-user-accounts-change-concept.html["サービスプロセッサにアクセスできるユーザアカウントが変更されました"]。
** ONTAP 9.8以前のリリースに戻す場合は、を参照してください link:../revert/verify-sp-user-accounts-task.html["サービスプロセッサにアクセスできるユーザアカウントを確認します"]。


* ONTAP 9.8以前のリリースでは、すべてのロールがSPにアクセスできますが `admin` が推奨されます。


デフォルトでは、「admin」という名前のクラスタユーザアカウントにはが含まれています `service-processor` アプリケーションタイプであり、SPへのアクセス権があります。

ONTAP では、システム用に予約されている名前（「 root 」や「 naroot 」など）を使用したユーザアカウントを作成できないようになっています。システム用に予約されている名前を使用してクラスタまたは SP にアクセスすることはできません。

を使用して、現在のSPユーザアカウントを表示できます `-application service-processor` のパラメータ `security login show` コマンドを実行します
