---
permalink: system-admin/add-nodes-cluster-concept.html 
sidebar: sidebar 
keywords: add, node, cluster, create, expand 
summary: クラスタを作成したら、ノードを追加してクラスタを拡張できます。一度に追加できるノードは1つだけです。 
---
= ONTAPクラスタへのノードの追加
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
クラスタを作成したら、ノードを追加してクラスタを拡張できます。一度に追加できるノードは1つだけです。

.開始する前に
* 複数ノードクラスタにノードを追加する場合は、クラスタ内のすべての既存ノードが正常である必要があります（で確認可能 `cluster show`）。の詳細については `cluster show`、をlink:https://docs.netapp.com/us-en/ontap-cli/cluster-show.html["ONTAPコマンド リファレンス"^]参照してください。
* 2ノードスイッチレスクラスタにノードを追加する場合は、NetAppでサポートされるクラスタスイッチを使用して、2ノードスイッチレスクラスタをスイッチ接続クラスタに変換する必要があります。
+
スイッチレスクラスタ機能は、2ノードクラスタでのみサポートされます。

* シングルノードクラスタに2つ目のノードを追加する場合は、2つ目のノードがインストールされていて、クラスタネットワークが設定されている必要があります。
* クラスタでSPの自動設定が有効になっている場合、追加するノードが指定したサブネットを使用してSPを自動的に設定できるように、SP用に指定したサブネットに使用可能なリソースがある必要があります。
* 新しいノードのノード管理LIFに関する次の情報を収集しておく必要があります。
+
** ポート
** IPアドレス
** ネットマスク
** デフォルトゲートウェイ




.タスクの内容
ノードは、HAペアを形成できるように偶数である必要があります。クラスタへのノードの追加を開始したら、その処理を完了する必要があります。別のノードの追加を開始するには、そのノードがクラスタに属している必要があります。

.手順
. クラスタに追加するノードに電源を入れます。
+
ノードがブートし、ノードのセットアップウィザードがコンソールで起動されます。

+
[listing]
----
Welcome to node setup.

You can enter the following commands at any time:
  "help" or "?" - if you want to have a question clarified,
  "back" - if you want to change previously answered questions, and
  "exit" or "quit" - if you want to quit the setup wizard.
     Any changes you made before quitting will be saved.

To accept a default or omit a question, do not enter a value.

Enter the node management interface port [e0M]:
----
. ノードのセットアップウィザードを終了します。 `exit`
+
ノードのセットアップウィザードが終了し、セットアップタスクが完了していないという警告がログインプロンプトに表示されます。

+
の詳細については `exit`、をlink:https://docs.netapp.com/us-en/ontap-cli/exit.html["ONTAPコマンド リファレンス"^]参照してください。

. ユーザ名を使用してadminアカウントにログインし `admin`ます。
. クラスタセットアップウィザードを開始します。
+
`*cluster setup*`

+
[listing]
----
::> cluster setup

Welcome to the cluster setup wizard.

You can enter the following commands at any time:
 "help" or "?" - if you want to have a question clarified,
 "back" - if you want to change previously answered questions, and
 "exit" or "quit" - if you want to quit the cluster setup wizard.
 Any changes you made before quitting will be saved.

You can return to cluster setup at any time by typing "cluster setup".
To accept a default or omit a question, do not enter a value....

Use your web browser to complete cluster setup by accessing
https://<node_mgmt_or_e0M_IP_address>

Otherwise, press Enter to complete cluster setup using the
command line interface:
----
+
[NOTE]
====
セットアップGUIを使用したクラスタのセットアップの詳細については、オンラインヘルプを参照してlink:https://docs.netapp.com/us-en/ontap/task_admin_add_nodes_to_cluster.html["System Manager"]ください。の詳細については `cluster setup`、をlink:https://docs.netapp.com/us-en/ontap-cli/cluster-setup.html["ONTAPコマンド リファレンス"^]参照してください。

====
. CLIを使用してこのタスクを完了するには、Enterキーを押します。新しいクラスタを作成するか既存のクラスタに参加するかを確認するメッセージが表示されたら、と入力し `*join*`ます。
+
[listing]
----
Do you want to create a new cluster or join an existing cluster? {create, join}:
join
----
+
新しいノードで実行されているONTAPのバージョンが既存のクラスタで実行されているバージョンと異なる場合は、エラーが報告され `System checks Error: Cluster join operation cannot be performed at this time`ます。これは想定される動作です。続行するには、クラスタ内の既存のノードからadvanced権限レベルでコマンドを実行し `add-node -allow-mixed-version-join new_node_name`ます。

. プロンプトに従ってノードをセットアップし、クラスタに追加します。
+
** プロンプトのデフォルト値を受け入れるには、Enterキーを押します。
** プロンプトに独自の値を入力するには、値を入力してEnterキーを押します。


. 追加するノードごとに前述の手順を繰り返します。


.終了後
クラスタにノードを追加したら、各HAペアのストレージフェイルオーバーを有効にする必要があります。

.関連情報
link:../upgrade/concept_mixed_version_requirements.html#requirements-for-mixed-version-ontap-clusters["バージョンが混在したONTAPクラスタ"]
