---
permalink: system-admin/audit-display-log-contents-task.html 
sidebar: sidebar 
keywords: audit, log, cluster, display 
summary: ONTAP CLI、System Manager、またはWebブラウザを使用して、/mroot/etc/log/mlog/audit.logファイルの内容を表示することができます。 
---
= 監査ログの内容を表示します
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
クラスタの内容を表示できます `/mroot/etc/log/mlog/audit.log` ONTAP CLI、System Manager、またはWebブラウザを使用して実行します。

クラスタのログファイルには、次のエントリが含まれます。

時間:: ログエントリのタイムスタンプ。
アプリケーション:: クラスタへの接続に使用するアプリケーション。指定可能な値の例はです `internal, console, ssh, http, ontapi, snmp, rsh, telnet,` および `service-processor`。
ユーザ:: リモートユーザのユーザ名。
状態:: 監査要求の現在の状態 `success, pending,` または `error`。
メッセージ:: コマンドのステータスに関するエラーまたは追加情報 を含むオプションのフィールド。
セッションID:: 要求を受信したセッションID。各SSH_SESSION_ISにはセッションIDが割り当てられ、各HTTP、ONTAPI、またはSNMP_REQUESTには一意のセッションIDが割り当てられます。
Storage VM:: ユーザの接続に使用するSVM。
適用範囲:: 表示されます `svm` 要求がデータStorage VM上にある場合。それ以外の場合はと表示されます `cluster`。
コマンドID:: CLIセッションで受信した各コマンドのID。これにより、要求と応答を関連付けることができます。ZAPI、HTTP、SNMPの各要求にはコマンドIDはありません。


クラスタのログエントリは、ONTAP CLIから、Webブラウザから、ONTAP 9.11.1以降のSystem Managerから表示できます。

[role="tabbed-block"]
====
.System Manager の略
--
* インベントリを表示するには、[* Events & Jobs]>[Audit Logs]を選択します。[+]
各列には、カテゴリのフィルタ、並べ替え、検索、表示、およびインベントリを制御できます。インベントリの詳細は、Excelブックとしてダウンロードできます。
* フィルタを設定するには、右上の*[Filter]*ボタンをクリックし、目的のフィールドを選択します。[+]
セッションIDリンクをクリックして、障害が発生したセッションで実行されたすべてのコマンドを表示することもできます。


--
.CLI の使用
--
クラスタ内の複数のノードからマージされた監査エントリを表示するには、+と入力します
`security audit log show _[parameters]_`

を使用できます `security audit log show` 個 々 のノードの監査エントリを表示するコマンド、またはクラスタ内の複数のノードの監査エントリをマージするコマンド。の内容を表示することもできます `/mroot/etc/log/mlog` Webブラウザを使用して、単一のノード上のディレクトリを作成します。
詳細については、のマニュアルページを参照してください。

--
.Web ブラウザ
--
の内容を表示できます `/mroot/etc/log/mlog` Webブラウザを使用して、単一のノード上のディレクトリを作成します。 link:accessg-node-log-core-dump-mib-files-task.html["Webブラウザを使用してノードのログファイル、コアダンプファイル、MIBファイルにアクセスする方法について説明します"]。

--
====