---
permalink: system-admin/autosupport-creates-sends-event-messages-concept.html 
sidebar: sidebar 
keywords: autosupport, event, triggered, messages, ems, data, example 
summary: AutoSupportは、EMSがトリガーイベントを処理すると、イベントトリガーAutoSupportメッセージを作成します。イベントトリガーAutoSupportメッセージは、修正措置が必要な問題を受信者に警告し、問題に関連する情報のみを格納します。メッセージに含めるコンテンツと受信者はカスタマイズできます。 
---
= ONTAP AutoSupportイベントトリガーメッセージについて学ぶ
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
AutoSupportは、EMSがトリガーイベントを処理すると、イベントトリガーAutoSupportメッセージを作成します。イベントトリガーAutoSupportメッセージは、修正措置が必要な問題を受信者に警告し、問題に関連する情報のみを格納します。メッセージに含めるコンテンツと受信者はカスタマイズできます。

AutoSupportは、次のプロセスを使用してイベントトリガー型AutoSupportメッセージを作成し、送信します。

. EMSがトリガー イベントを処理すると、EMSからAutoSupportに要求が送信されます。
+
トリガー イベントは、AutoSupport 宛先と `callhome.`プレフィックスで始まる名前を持つ EMS イベントです。

. AutoSupportは、イベントトリガーAutoSupportメッセージを作成します。
+
AutoSupportは、トリガーに関連付けられたサブシステムから基本的な情報とトラブルシューティング情報を収集し、トリガー イベントに関連する情報のみが含まれたメッセージを作成します。

+
各トリガーには、デフォルトのサブシステムセットが関連付けられています。ただし、 `system node autosupport trigger modify` コマンドを使用して、トリガーに追加のサブシステムを関連付けることもできます。

. AutoSupportは、 `system node autosupport modify`コマンドで `-to`、 `-noteto`、 `-partner-address`、および `-support`パラメータを使用して定義された受信者に、イベントトリガーAutoSupportメッセージを送信します。
+
AutoSupportメッセージの配信を特定のトリガーに対して有効または無効にするには、 `system node autosupport trigger modify`コマンドに `-to`および `-noteto`パラメータを指定して使用します。



.特定のイベントに関して送信されるデータの例
 `storage shelf PSU failed`EMSイベントは、必須、ログファイル、ストレージ、RAID、HA、プラットフォーム、およびネットワークサブシステムからの基本データと、必須、ログファイル、およびストレージサブシステムからのトラブルシューティングデータを含むメッセージをトリガーします。

今後の `storage shelf PSU failed`イベントへの応答として送信されるAutoSupportメッセージに、NFSに関するデータを含めることにしました。 `callhome.shlf.ps.fault`イベントのNFSに関するトラブルシューティングレベルのデータを有効にするには、次のコマンドを入力します：

[listing]
----

        cluster1::\>
        system node autosupport trigger modify -node node1 -autosupport-message shlf.ps.fault -troubleshooting-additional nfs
----
 `callhome.`プレフィックスは、 `system node autosupport trigger`コマンドを使用する場合、またはCLIでAutoSupportおよびEMSイベントによって参照される場合、 `callhome.shlf.ps.fault`イベントから削除されることに注意してください。
