---
permalink: system-admin/autosupport-active-iq-digital-advisor-concept.html 
sidebar: sidebar 
keywords: autosupport, active iq, digital advisor, active, iq, digital, advisor, telemetry, artificial, intelligence 
summary: ONTAPのAutoSupportコンポーネントはテレメトリを収集し、分析用に送信します。Digital Advisorは、AutoSupportからのデータを分析し、プロアクティブなサポートと最適化を提供します。Digital Advisorは、人工知能を使用して潜在的な問題を特定し、ビジネスに影響が及ぶ前に問題を解決できるよう支援します。 
---
= Digital AdvisorとAutoSupportについて
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
ONTAPのAutoSupportコンポーネントはテレメトリを収集し、分析用に送信します。Digital Advisorは、AutoSupportからのデータを分析し、プロアクティブなサポートと最適化を提供します。Digital Advisorは、人工知能を使用して潜在的な問題を特定し、ビジネスに影響が及ぶ前に問題を解決できるよう支援します。

Digital Advisorは、クラウドベースのポータルとモバイルアプリを通じて、実用的な予測分析とプロアクティブなサポートを提供することで、グローバルハイブリッドクラウド全体にわたってデータインフラを最適化します。SupportEdgeと有効な契約を結んでいるNetAppのすべてのお客様が、デジタルアドバイザによるデータ主体の分析情報と推奨事項を利用できます（機能は製品やサポートレベルによって異なります）。

Digital Advisorでできることは次のとおりです。

* アップグレードを計画する。Digital Advisorは、新しいバージョンのONTAPにアップグレードすることで解決できる環境内の問題を特定し、Upgrade Advisorコンポーネントがアップグレードの計画を支援します。
* システムの健全性を表示します。デジタルアドバイザのダッシュボードが健全性に関する問題を報告し、問題の修正を支援します。システム容量を監視して、ストレージスペースが不足しないようにします。システムのサポートケースを表示します。
* パフォーマンスの管理Digital Advisorでは、System Managerよりも長い期間のシステムパフォーマンスが表示されます。パフォーマンスに影響している構成やシステムの問題を特定します。
* 効率性の最大化Storage Efficiency 指標を表示し、より多くのデータをより少ないスペースに格納する方法を特定します。
* インベントリと構成を表示します。Digital Advisorは、完全なインベントリおよびソフトウェアとハードウェアの構成情報を表示します。サービス契約の有効期限を確認し、サポートを継続できるように更新してください。


.関連情報
https://docs.netapp.com/us-en/active-iq/["NetAppのドキュメント：デジタルアドバイザ"^]

https://aiq.netapp.com/custom-dashboard/search["Digital Advisorを起動"^]

https://www.netapp.com/us/services/support-edge.aspx["SupportEdge サービス"^]
