---
permalink: system-admin/commands-manage-web-protocol-engine-reference.html 
sidebar: sidebar 
keywords: command, manage, web, protocol, engine, firewall, system, services 
summary: Web プロトコルエンジンを管理するには、 system services web コマンドを使用します。Web アクセス要求がファイアウォールを通過できるようにするには、 system services firewall policy create および network interface modify コマンドを使用します。 
---
= Web プロトコルエンジンを管理するためのコマンド
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Web プロトコルエンジンを管理するには、「 system services web 」コマンドを使用します。Web アクセス要求がファイアウォールを通過できるようにするには、「 system services firewall policy create 」および「 network interface modify 」コマンドを使用します。

|===
| 状況 | 使用するコマンド 


 a| 
クラスタレベルで Web プロトコルエンジンを設定します。

* クラスタの Web プロトコルエンジンを有効または無効にします
* クラスタの SSLv3 を有効または無効にします
* セキュアな Web サービス（ HTTPS ）に対する FIPS 140-2 準拠を有効または無効にする

 a| 
「 system services web modify 」を参照してください



 a| 
クラスタレベルの Web プロトコルエンジンの設定を表示し、 Web プロトコルがクラスタ全体で機能しているかどうかを確認し、 FIPS 140-2 準拠が有効でオンラインになっているかどうかを表示します
 a| 
「 system services web show 」をご覧ください



 a| 
ノードレベルの Web プロトコルエンジンの設定と、クラスタ内のノードに対する Web サービス処理のアクティビティを表示します
 a| 
「 system services web node show 」を参照してください



 a| 
ファイアウォールポリシーを作成するか、既存のファイアウォールポリシーに HTTP または HTTPS プロトコルサービスを追加して、 Web アクセス要求がファイアウォールを通過できるようにします
 a| 
「システムサービスファイアウォールポリシー作成」を参照してください

「 -service 」パラメータを「 http 」または「 https 」に設定すると、 Web アクセス要求がファイアウォールを通過できるようになります。



 a| 
ファイアウォールポリシーを LIF と関連付ける
 a| 
「 network interface modify 」を参照してください

LIF のファイアウォールポリシーを変更するには、「 -firewall-policy 」パラメータを使用します。

|===