---
permalink: system-admin/commands-manage-feature-licenses-reference.html 
sidebar: sidebar 
keywords: command, manage, license, command, cluster, system, feature, usage, usage 
summary: クラスタの機能のライセンスを管理するには、 system license コマンドを使用します。機能の使用状況を監視するには、 system feature-usage コマンドを使用します。 
---
= ライセンスを管理するためのコマンド
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
を使用します `system license` クラスタの機能ライセンスを管理するコマンド。を使用します `system feature-usage` 機能の使用状況を監視するコマンド。

|===
| 状況 | 使用するコマンド 


 a| 
1 つ以上のライセンスを追加します
 a| 
`system license add`



 a| 
インストール済みのライセンスに関する次のような情報を表示する。

* ライセンスパッケージ名と概要
* ライセンスタイプ (`site`、 `license`または `demo`)
* 有効期限（該当する場合）
* パッケージのライセンス対象であるクラスタまたはノード
* ライセンスがData ONTAP 8.2より前にインストールされているかどうか (`legacy`)
* 顧客 ID

 a| 
`system license show`

[NOTE]
====
一部の情報は、を使用した場合にのみ表示されます `–instance` パラメータ

====


 a| 
ライセンスが必要なパッケージすべてと、次のようなパッケージの現在のライセンスステータスを表示する

* パッケージ名
* ライセンス方式
* 有効期限（該当する場合）

 a| 
`system license status show`



 a| 
シリアル番号を指定してクラスタまたはノードからパッケージのライセンスを削除します
 a| 
`system license delete`



 a| 
期限切れのライセンスまたは未使用のライセンスを表示または削除します
 a| 
`system license clean-up`



 a| 
クラスタでの機能の使用状況の概要をノード単位で表示します
 a| 
`system feature-usage show-summary`



 a| 
クラスタでの機能の使用ステータスをノード単位および週単位で表示します
 a| 
`system feature-usage show-history`



 a| 
各ライセンスパッケージのライセンス使用権リスクステータスを表示します
 a| 
`system license entitlement-risk show`

[NOTE]
====
一部の情報は、を使用した場合にのみ表示されます `-detail` および `-instance` パラメータ

====
|===
.関連情報
http://["ONTAP 9コマンド"^]
