---
permalink: system-admin/commands-manage-jobs-reference.html 
sidebar: sidebar 
keywords: command, manage, jobs, queue, cluster, resources 
summary: ジョブはジョブキューに配置され、リソースが使用可能になるとバックグラウンドで実行されます。ジョブで使用するクラスタリソースが多すぎる場合は、そのジョブを停止するか、クラスタに対する要求が少なくなるまで一時停止できます。ジョブを監視および再開することもできます。 
---
= ジョブの管理用コマンド
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
ジョブはジョブキューに配置され、リソースが使用可能になるとバックグラウンドで実行されます。ジョブで使用するクラスタリソースが多すぎる場合は、そのジョブを停止するか、クラスタに対する要求が少なくなるまで一時停止できます。ジョブを監視および再開することもできます。

あるジョブを呼び出すコマンドを入力すると、通常、ジョブがキューに登録されたことが通知され、 CLI のコマンドプロンプトに戻ります。ただし、一部のコマンドではジョブの進捗状況が表示され、ジョブが完了するまで CLI のコマンドプロンプトに戻りません。このような場合は、 Ctrl+C キーを押してジョブをバックグラウンドに移動できます。

|===
| 状況 | 使用するコマンド 


 a| 
すべてのジョブに関する情報を表示します
 a| 
「 job show 」をクリックします



 a| 
ジョブに関する情報をノード単位で表示します
 a| 
「 job show bynode



 a| 
クラスタ関連ジョブに関する情報を表示します
 a| 
「 job show -cluster 」です



 a| 
完了したジョブに関する情報を表示します
 a| 
「 job show -completed 」のように表示されます



 a| 
ジョブ履歴に関する情報を表示します
 a| 
「 job history show 」と表示されます

クラスタ内の各ノードには、最大 25 、 000 個のジョブレコードが格納されます。そのため、ジョブ履歴全体を表示しようとすると時間がかかることがあります。待ち時間が長くならないようにするには、ジョブをノード、 Storage Virtual Machine （ SVM ）、またはレコード ID ごとに表示します。



 a| 
プライベートジョブのリストを表示します
 a| 
job private show （ advanced 権限レベル）



 a| 
完了したプライベートジョブに関する情報を表示します
 a| 
job private show-completed （ advanced 権限レベル）



 a| 
ジョブマネージャの初期化状態に関する情報を表示します
 a| 
job initstate show （ advanced 権限レベル）



 a| 
ジョブの進捗状況を監視します
 a| 
「 job watch-progress 」を参照してください



 a| 
プライベートジョブの進捗状況を監視する
 a| 
job private watch-progress （ advanced 権限レベル）



 a| 
ジョブを一時停止します
 a| 
「 job pause 」を参照してください



 a| 
プライベートジョブを一時停止します
 a| 
「 job private pause 」（ advanced 権限レベル）



 a| 
一時停止したジョブを再開します
 a| 
「 job resume 」と入力します



 a| 
一時停止したプライベートジョブを再開します
 a| 
「 job private resume 」（ advanced 権限レベル）



 a| 
ジョブを停止します
 a| 
「 job stop 」と入力します



 a| 
プライベートジョブを停止します
 a| 
「 job private stop 」（ advanced 権限レベル）



 a| 
ジョブを削除します
 a| 
「 job delete 」と入力します



 a| 
プライベートジョブを削除します
 a| 
「 job private delete 」（ advanced 権限レベル）



 a| 
クラスタ関連ジョブと、そのジョブが所有する使用できないノードとの関連付けを解除し、別のノードがジョブの所有権を取得できるようにします
 a| 
「 job unclaim 」（ advanced 権限レベル）

|===
[NOTE]
====
「 event log show 」コマンドを使用して、完了したジョブの結果を確認できます。

====
http://docs.netapp.com/ontap-9/topic/com.netapp.doc.dot-cm-cmpr/GUID-5CB10C70-AC11-41C0-8C16-B4D0DF916E9B.html["ONTAP 9コマンド"^]
