---
permalink: system-admin/commands-manage-config-backup-schedules-reference.html 
sidebar: sidebar 
keywords: command, manage, configuration, backup, schedule, settings 
summary: 構成バックアップスケジュールを管理するには、 system configuration backup settings コマンドを使用します。 
---
= 構成バックアップスケジュールの管理用コマンド
:icons: font
:imagesdir: ../media/


[role="lead"]
「システム構成バックアップ設定」コマンドを使用して、構成バックアップスケジュールを管理できます。

これらのコマンドは advanced 権限レベルで使用できます。

|===
| 状況 | 使用するコマンド 


 a| 
構成バックアップスケジュールの設定を変更します。

* クラスタ内のデフォルトの場所に加えて構成バックアップファイルがアップロードされるリモート URL （ HTTP 、 HTTPS 、または FTP ）を指定する
* リモート URL へのログインに使用するユーザ名を指定します
* 各構成バックアップスケジュールで保持するバックアップ数を設定します

 a| 
「システム構成バックアップ設定の変更」

リモート URL で HTTPS を使用する場合は、「 -validate-certification 」オプションを使用してデジタル証明書の検証を有効または無効にします。証明書の検証はデフォルトでは無効になっています。

[NOTE]
====
構成バックアップファイルのアップロード先の Web サーバで、 HTTP の場合は PUT 処理、 HTTPS の場合は POST 処理が有効になっている必要があります。詳細については、 Web サーバのマニュアルを参照してください。

====


 a| 
リモート URL へのログインに使用するパスワードを設定します
 a| 
「システム構成のバックアップ設定 - パスワード」



 a| 
構成バックアップスケジュールの設定を表示します
 a| 
「システム構成のバックアップ設定」が表示されます

[NOTE]
====
ユーザー名と各スケジュールについて保持するバックアップ数を表示するには '-instance パラメータを設定します

====
|===