---
permalink: system-admin/commands-monitor-health-system-reference.html 
sidebar: sidebar 
keywords: command, monitor, health, system, display, status, cli, software, version, switches, alert 
summary: system health コマンドを使用すると、システムリソースのヘルスに関する情報の表示、アラートへの応答、以後のアラートの設定を行うことができます。CLI コマンドを使用すると、ヘルスモニタの設定に関する詳細情報を表示できます。詳細については、各コマンドのマニュアルページを参照してください。 
---
= システムの健常性を監視するためのコマンドです
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
を使用できます `system health` システムリソースの健常性に関する情報を表示し、アラートに応答し、以後のアラートを設定するためのコマンドです。CLI コマンドを使用すると、ヘルスモニタの設定に関する詳細情報を表示できます。詳細については、各コマンドのマニュアルページを参照してください。



== システムヘルスのステータスを表示します

|===
| 状況 | 使用するコマンド 


 a| 
個々のヘルスモニタの全体的なステータスを反映した、システムのヘルスステータスを表示する
 a| 
`system health status show`



 a| 
ヘルス監視が可能なサブシステムのヘルスステータスを表示する
 a| 
`system health subsystem show`

|===


== ノード接続のステータスを表示します

|===
| 状況 | 使用するコマンド 


 a| 
ノードからストレージシェルフへの接続に関する詳細を表示します。これには、ポート情報、 HBA ポート速度、 I/O スループット、 1 秒あたりの I/O 処理数などの情報が含まれます
 a| 
`storage shelf show -connectivity`

を使用します `-instance` 各シェルフに関する詳細な情報を表示するためのパラメータ。



 a| 
使用可能なスペース、シェルフとベイの番号、所有ノード名など、ドライブとアレイ LUN に関する情報を表示します
 a| 
`storage disk show`

を使用します `-instance` 各ドライブに関する詳細な情報を表示するためのパラメータ。



 a| 
ポートのタイプ、速度、ステータスなど、ストレージシェルフポートに関する詳細情報を表示します
 a| 
`storage port show`

を使用します `-instance` 各アダプタに関する詳細情報を表示するためのパラメータ。

|===


== クラスタ、ストレージ、および管理ネットワークスイッチの検出を管理します

[cols="3*"]
|===
| 状況 | 使用するコマンド（ONTAP 9.8以降） | 使用するコマンド（ONTAP 9.7以前） 


 a| 
クラスタが監視するスイッチを表示します
 a| 
`system switch ethernet show`
 a| 
`system cluster-switch show`



 a| 
削除したスイッチ（コマンド出力の Reason 列に表示）を含む、クラスタが現在監視しているスイッチ、およびクラスタや管理ネットワークスイッチへのネットワークアクセスに必要な設定情報を表示します。

このコマンドは、 advanced 権限レベルで使用できます。
 a| 
`system switch ethernet show-all`
 a| 
`system cluster-switch show-all`



 a| 
未検出のスイッチの検出を設定します
 a| 
`system switch ethernet create`
 a| 
`system cluster-switch create`



 a| 
クラスタが監視するスイッチに関する情報（デバイス名、 IP アドレス、 SNMP バージョン、コミュニティストリングなど）を変更する
 a| 
`system switch ethernet modify`
 a| 
`system cluster-switch modify`



 a| 
スイッチの監視を無効にします
 a| 
`system switch ethernet modify -disable-monitoring`
 a| 
`system cluster-switch modify -disable-monitoring`



 a| 
スイッチの検出と監視を無効にし、スイッチの設定情報を削除します
 a| 
`system switch ethernet delete`
 a| 
`system cluster-switch delete`



 a| 
データベースに格納されているスイッチ設定情報を完全に削除する（これにより、スイッチの自動検出が再度有効になる）
 a| 
`system switch ethernet delete -force`
 a| 
`system cluster-switch delete -force`



 a| 
AutoSupport メッセージで送信するには、自動ロギングを有効にします。
 a| 
`system switch ethernet log`
 a| 
`system cluster-switch log`

|===


== 生成されたアラートに対応する

|===
| 状況 | 使用するコマンド 


 a| 
アラートがトリガーされたリソースやノード、アラートの重大度や原因など、生成されたアラートに関する情報を表示する
 a| 
`system health alert show`



 a| 
生成された各アラートの情報を表示する
 a| 
`system health alert show -instance`



 a| 
アラートに対して作業中であることを示します
 a| 
`system health alert modify`



 a| 
アラートを確認します
 a| 
`system health alert modify -acknowledge`



 a| 
サブシステムのヘルスステータスに影響しないように、以降のアラートを抑制する
 a| 
`system health alert modify -suppress`



 a| 
自動的に消去されなかったアラートを削除します
 a| 
`system health alert delete`



 a| 
あるアラートで AutoSupport メッセージがトリガーされたかどうかを確認するためなど、過去 1 週間にアラートによってトリガーされた AutoSupport メッセージに関する情報を表示する
 a| 
`system health autosupport trigger history show`

|===


== 以後のアラートを設定

|===
| 状況 | 使用するコマンド 


 a| 
リソースの状態に応じて特定のアラートを発行するかどうかを制御するポリシーを有効または無効にします
 a| 
`system health policy definition modify`

|===


== ヘルスモニタの設定に関する情報を表示します

|===
| 状況 | 使用するコマンド 


 a| 
ヘルスモニタについて、ノード、名前、サブシステム、ステータスなどの情報を表示する
 a| 
`system health config show`

[NOTE]
====
を使用します `-instance` 各ヘルスモニタに関する詳細情報を表示するためのパラメータ。

====


 a| 
ヘルスモニタで生成される可能性があるアラートの情報を表示する
 a| 
`system health alert definition show`

[NOTE]
====
を使用します `-instance` 各アラート定義に関する詳細情報を表示するためのパラメータ。

====


 a| 
アラートが発行されるタイミングを決定する、ヘルスモニタのポリシーに関する情報を表示する
 a| 
`system health policy definition show`

[NOTE]
====
を使用します `-instance` 各ポリシーに関する詳細情報を表示するためのパラメータ。ポリシーのステータス（有効または無効）、ヘルスモニタ、アラートなどによってアラートのリストをフィルタリングするには、その他のパラメータを使用します。

====
|===