---
permalink: system-admin/commands-manage-system-time-reference.html 
sidebar: sidebar 
keywords: command, manage, cluster, time, ntp, server, date, ntp, time, manually 
summary: クラスタの NTP サーバを管理するには、 cluster time-service ntp server コマンドを使用します。クラスタ時間を手動で管理するには、 cluster date コマンドを使用します。 
---
= クラスタ時間の管理用コマンド
:icons: font
:imagesdir: ../media/


[role="lead"]
クラスタの NTP サーバを管理するには 'cluster time-service ntp server コマンドを使用しますクラスタ時間を手動で管理するには 'cluster date コマンドを使用します

ONTAP 9.5 以降では、対称認証を使用して NTP サーバを設定できます。

次のコマンドによって、クラスタの NTP サーバを管理できます。

|===
| 状況 | 使用するコマンド 


 a| 
クラスタを外部 NTP サーバと対称認証を使用せずに関連付ける
 a| 
cluster time-service ntp server create -server server_name を選択します



 a| 
ONTAP 9.5 以降では、クラスタを外部 NTP サーバと対称認証を使用できるように関連付けます
 a| 
cluster time-service ntp server create -server server_ip_address -key-id key_id

[NOTE]
====
「 key_id 」は、「 cluster time-service ntp key 」で設定された既存の共有キーを参照する必要があります。

====


 a| 
既存の NTP サーバに対して対称認証を有効にする必要なキー ID を追加することで、既存の NTP サーバを変更して認証を有効にすることができます

ONTAP 9.5 以降で利用できます
 a| 
cluster time-service ntp server modify -server server_name -key_id key_id `



 a| 
対称認証を無効にします
 a| 
「 cluster time-service ntp server modify -server server_name -authentication disabled 」の形式で指定します



 a| 
共有 NTP キーを設定する
 a| 
cluster time-service ntp key create -id shared_key_id -type shared_key_type - value shared_key_value

[NOTE]
====
共有キーは ID で参照されます。ID 、そのタイプ、および値が、ノードと NTP サーバで同じである必要があります

====


 a| 
クラスタに関連付けられている NTP サーバに関する情報を表示する
 a| 
cluster time-service ntp server show



 a| 
クラスタに関連付けられた外部 NTP サーバの設定を変更する
 a| 
「 cluster time-service ntp server modify 」のように変更されます



 a| 
クラスタと NTP サーバの関連付けを解除します
 a| 
「 cluster time-service ntp server delete 」のように表示されます



 a| 
すべての外部 NTP サーバのクラスタとの関連付けを消去して設定をリセットします
 a| 
「 cluster time-service ntp server reset 」のように設定します

[NOTE]
====
このコマンドには、 advanced 権限レベルが必要です。

====
|===
次のコマンドによって、手動でクラスタ時間を管理できます。

|===
| 状況 | 使用するコマンド 


 a| 
タイムゾーン、日付、および時刻を設定または変更します
 a| 
'cluster date modify'



 a| 
クラスタのタイムゾーン、日付、および時刻の設定を表示します
 a| 
cluster date show

|===
http://docs.netapp.com/ontap-9/topic/com.netapp.doc.dot-cm-cmpr/GUID-5CB10C70-AC11-41C0-8C16-B4D0DF916E9B.html["ONTAP 9 のコマンド"]
