---
permalink: system-admin/commands-manage-feature-licenses-reference.html 
sidebar: sidebar 
keywords: command, manage, license, cli, command, cluster, system, feature, usage, usage 
summary: ONTAP CLI の system license コマンドを使用して、クラスタの機能ライセンスを管理できます。機能の使用状況を監視するには、system feature-usage コマンドを使用します。 
---
= ONTAP でライセンスを管理するためのコマンド
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
ONTAP CLI `system license`コマンドを使用して、クラスタの機能ライセンスを管理できます。 `system feature-usage`コマンドを使用して、機能の使用状況を監視できます。

このトピックで説明されているコマンドの詳細については、link:https://docs.netapp.com/us-en/ontap-cli/["ONTAPコマンド リファレンス"^]を参照してください。

次の表に、ライセンスを管理するための一般的なCLIコマンドの一部を示します。詳細については、リンクからコマンドのマニュアル ページを参照してください。

[cols="2,4"]
|===
| 状況 | 使用するコマンド 


 a| 
ライセンスが必要なパッケージすべてと、次のようなパッケージの現在のライセンス ステータスを表示する

* パッケージ名
* ライセンス方式
* 有効期限（存在する場合）

 a| 
link:https://docs.netapp.com/us-en/ontap-cli/system-license-show-status.html["system license show-status"]



 a| 
期限切れのライセンスまたは未使用のライセンスを表示または削除する
 a| 
link:https://docs.netapp.com/us-en/ontap-cli/system-license-clean-up.html["system license clean-up"]



 a| 
クラスタでの機能の使用状況の概要をノード単位で表示する
 a| 
https://docs.netapp.com/us-en/ontap-cli/system-feature-usage-show-summary.html["system feature-usage show-summary"]



 a| 
クラスタでの機能の使用ステータスをノード単位および週単位で表示する
 a| 
https://docs.netapp.com/us-en/ontap-cli/system-feature-usage-show-history.html["system feature-usage show-history"]



 a| 
各ライセンス パッケージのライセンス使用権リスク ステータスを表示する
 a| 
https://docs.netapp.com/us-en/ontap-cli/system-license-entitlement-risk-show.html["system license entitlement-risk show"]

|===
.関連情報
* link:../concepts/manual-pages.html["ONTAPコマンド リファレンス"]
* link:https://kb.netapp.com/onprem/ontap/os/ONTAP_9.10.1_and_later_licensing_overview["NetApp ナレッジベース：ONTAP 9.10.1 以降のライセンスの概要"^]
* link:install-license-task.html["System Managerを使用したNetAppライセンス ファイルのインストール"]
* link:https://docs.netapp.com/us-en/ontap-cli/search.html?q=system+feature["システム機能"^]

