---
permalink: system-admin/commands-manage-autosupport-reference.html 
sidebar: sidebar 
keywords: command, manage, autosupport, node, message, send, resend, cancel, configure, display, information 
summary: system node autosupport コマンドを使用して、AutoSupport 構成の変更または表示、以前の AutoSupport メッセージに関する情報の表示、AutoSupport メッセージの送信、再送信、またはキャンセルを行います。 
---
= ONTAP AutoSupport を管理するためのコマンド
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
 `system node autosupport`コマンドを使用して、AutoSupport構成の変更や表示、以前のAutoSupportメッセージに関する情報の表示、AutoSupportメッセージの送信、再送信、またはキャンセルを行うことができます。



== AutoSupportを設定する

|===
| 状況 | 使用するコマンド 


 a| 
AutoSupportメッセージを送信するかどうかを制御する
 a| 
`system node autosupport modify` と `-state`パラメータ



 a| 
AutoSupportメッセージがテクニカル サポートに送信されるかどうかを制御する
 a| 
`system node autosupport modify` と `-support`パラメータ



 a| 
AutoSupportをセットアップするか、AutoSupportの設定を変更する
 a| 
`system node autosupport modify`



 a| 
個々のトリガー イベントについて、AutoSupportメッセージを社内のサポート部門に送信するかどうかを指定する。また、各トリガー イベントで送信されるメッセージに含める追加のサブシステム レポートを指定する
 a| 
`system node autosupport trigger modify`

|===


== AutoSupportの設定に関する情報を表示する

|===
| 状況 | 使用するコマンド 


 a| 
AutoSupportの設定を表示する
 a| 
`system node autosupport show` と `-node`パラメータ



 a| 
AutoSupportメッセージを受信するすべてのアドレスとURLの概要を表示する
 a| 
`system node autosupport destinations show`



 a| 
個々のトリガー イベントについて社内のサポート部門に送信されるAutoSupportメッセージを表示する
 a| 
`system node autosupport trigger show`



 a| 
AutoSupportの設定およびさまざまな宛先への配信のステータスを表示する
 a| 
`system node autosupport check show`



 a| 
AutoSupportの設定およびさまざまな宛先への配信の詳細なステータスを表示する
 a| 
`system node autosupport check show-details`

|===


== 過去のAutoSupportメッセージに関する情報を表示する

|===
| 状況 | 使用するコマンド 


 a| 
過去50件のうち、1つ以上のAutoSupportメッセージに関する情報を表示する
 a| 
`system node autosupport history show`



 a| 
テクニカル サポート サイトまたは指定のURIにコア ダンプ ファイルまたはパフォーマンス アーカイブ ファイルをアップロードするために生成された最新のAutoSupportメッセージに関する情報を表示する
 a| 
`system node autosupport history show-upload-details`



 a| 
AutoSupportメッセージ内の情報を表示する。メッセージ用に収集された各ファイルの名前とサイズのほか、エラーがある場合はその情報も含まれる
 a| 
`system node autosupport manifest show`

|===


== AutoSupportメッセージを送信、再送信、またはキャンセルする

|===
| 状況 | 使用するコマンド 


 a| 
ローカルに保存されていて、そのAutoSupportシーケンス番号で特定されるAutoSupportメッセージを再転送する


NOTE: AutoSupportメッセージを再転送し、サポート部門がすでにそのメッセージを受信している場合、サポート システムは重複するケースを作成しません。一方、サポート部門がそのメッセージを受信しなかった場合には、AutoSupportシステムはメッセージを分析し、必要に応じてケースを作成します。
 a| 
`system node autosupport history retransmit`



 a| 
テスト目的などでAutoSupportメッセージを生成し送信する
 a| 
`system node autosupport invoke`


NOTE:  `-force`パラメータを使用して、AutoSupportが無効になっている場合でもメッセージを送信します。 `-uri`パラメータを使用して、設定された送信先ではなく、指定した送信先にメッセージを送信します。



 a| 
AutoSupportメッセージをキャンセルする
 a| 
`system node autosupport history cancel`

|===
 `system node autosupport`の詳細については、link:https://docs.netapp.com/us-en/ontap-cli/search.html?q=system+node+autosupport["ONTAPコマンド リファレンス"^]をご覧ください。

.関連情報
link:../concepts/manual-pages.html["ONTAPコマンド リファレンス"]
