---
permalink: system-admin/config-backup-file-concept.html 
sidebar: sidebar 
keywords: configuration, backup, files, archive, files 
summary: 構成バックアップファイルはアーカイブファイル（.7z）で、クラスタおよびクラスタ内のノードが適切に動作するために必要な、設定可能なすべてのオプションの情報が含まれています。 
---
= ONTAP構成バックアップファイルの詳細
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
構成バックアップファイルはアーカイブファイル（.7z）で、クラスタおよびクラスタ内のノードが適切に動作するために必要な、設定可能なすべてのオプションの情報が含まれています。

これらのファイルには、各ノードのローカル設定に加えて、クラスタ全体でレプリケートされる設定が格納されます。クラスタの構成をバックアップおよびリストアするには、構成バックアップファイルを使用します。

構成バックアップファイルには、次の2種類があります。

* * ノード構成バックアップファイル *
+
クラスタ内の正常な各ノードには、ノード構成バックアップファイルが含まれています。このファイルには、ノードがクラスタ内で正常に動作するために必要な設定情報とメタデータがすべて含まれています。

* * クラスタ構成バックアップファイル *
+
これらのファイルには、クラスタ内のすべてのノード構成バックアップファイルのアーカイブと、レプリケートされたクラスタ構成情報（レプリケートされたデータベース（RDBファイル））が含まれます。クラスタ構成バックアップファイルを使用すると、クラスタ全体またはクラスタ内の任意のノードの構成をリストアできます。クラスタ構成バックアップスケジュールでは、これらのファイルが自動的に作成され、クラスタ内の複数のノードに格納されます。



[NOTE]
====
構成バックアップファイルには構成情報のみが含まれています。ユーザデータは含まれません。ユーザデータのリストアについては、を参照してくださいlink:../data-protection/index.html["データ保護"]。

====