---
permalink: system-admin/create-motd-task.html 
sidebar: sidebar 
keywords: create, motd, cli, user, clustershell, ssh, session, cluster, access, message, day 
summary: Message Of The Day （ MOTD ）を作成して、認証された CLI ユーザに情報を提供することができます。MOTD は、ユーザの認証後、クラスタシェルプロンプトが表示される前に、コンソールセッション（クラスタアクセスのみ）または SSH セッション（クラスタアクセスまたは SVM アクセス）に表示されます。 
---
= MOTD を作成します。
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Message Of The Day （ MOTD ）を作成して、認証された CLI ユーザに情報を提供することができます。MOTD は、ユーザの認証後、クラスタシェルプロンプトが表示される前に、コンソールセッション（クラスタアクセスのみ）または SSH セッション（クラスタアクセスまたは SVM アクセス）に表示されます。

.手順
. を使用します `security login motd modify` クラスタまたはSVMのMOTDを作成するコマンドは次のとおりです。
+
|===
| 状況 | 作業 


 a| 
1 行のメッセージを指定します
 a| 
を使用します `-message` "[.code]``text``"パラメータを使用してテキストを指定します。



 a| 
改行（ EOL ）を使用する
 a| 
コマンドは、を使用せずに使用します `-message` または `-uri` MOTDを編集する対話型モードを起動するためのパラメータ。



 a| 
MOTD に使用する内容を特定の場所からアップロードします
 a| 
を使用します `-uri` コンテンツのFTPまたはHTTPの場所を指定するパラメータ。

|===
+
MOTD の最大サイズは、改行も含めて 2 、 048 バイトまでです。

+
。 `security login motd modify` のマニュアルページに、動的に生成される内容をMOTDに表示するためのエスケープシーケンスが記載されています。

+
を使用して作成したMOTD `-uri` パラメータは静的です。以降にソースコンテンツが変更されても、自動では反映されません。

+
クラスタ用に作成した MOTD は、デフォルトでは、各 SVM に対して個別に作成した SVM レベルの MOTD と一緒に、すべての SVM ログインに対しても表示されます。を設定します `-is-cluster-message-enabled` パラメータの値 `false` SVMの場合、そのSVMに対するクラスタレベルのMOTDは表示されません。

. を使用して、作成したMOTDが表示されていることを確認します `security login motd show` コマンドを実行します
+
を指定する `-message` 空の文字列を持つパラメータ (`""`）には、未設定または内容がないMOTDが表示されます。

+
を参照してください https://["security login motd modify のように変更します"] 動的に生成される内容を MOTD に表示するために使用するパラメータのリストについては、コマンドのマニュアルページを参照してください。ONTAP のバージョンに固有のマニュアルページを確認してください。



.MOTDの作成例
次の例では、非対話型モードを使用して「 cluster1 」クラスタ用の MOTD を作成しています。

[listing]
----
cluster1::> security login motd modify -message "Greetings!"
----
次の例では、対話型モードを使用して「 `vm1 」 SVM 用の MOTD を作成しています。この MOTD では、エスケープシーケンスを使用して、動的に生成される内容を表示します。

[listing]
----
cluster1::> security login motd modify -vserver svm1

Enter the message of the day for Vserver "svm1".
Max size: 2048. Enter a blank line to terminate input. Press Ctrl-C to abort.
0        1         2         3         4         5         6         7         8
12345678901234567890123456789012345678901234567890123456789012345678901234567890
Welcome to the \n SVM.  Your user ID is '\N'. Your last successful login was \L.
----
次の例では、作成した MOTD を表示しています。

[listing]
----
cluster1::> security login motd show
Vserver: cluster1
Is the Cluster MOTD Displayed?: true
Message
-----------------------------------------------------------------------------
Greetings!

Vserver: svm1
Is the Cluster MOTD Displayed?: true
Message
-----------------------------------------------------------------------------
Welcome to the \n SVM.  Your user ID is '\N'. Your last successful login was \L.

2 entries were displayed.
----