---
permalink: system-admin/create-motd-task.html 
sidebar: sidebar 
keywords: create, motd, cli, user, clustershell, ssh, session, cluster, access, message, day 
summary: 認証されたCLIユーザーに情報を伝達するためのMessage of the Day（MOTD）を作成できます。MOTDは、ユーザーが認証された後、クラスタシェルプロンプトが表示される前に、コンソールセッション（クラスタアクセスのみ）またはSSHセッション（クラスタまたはSVMアクセス）に表示されます。 
---
= ONTAPユーザー向けの今日のメッセージテキストを作成する
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
認証されたCLIユーザーに情報を伝達するためのMessage of the Day（MOTD）を作成できます。MOTDは、ユーザーが認証された後、クラスタシェルプロンプトが表示される前に、コンソールセッション（クラスタアクセスのみ）またはSSHセッション（クラスタまたはSVMアクセス）に表示されます。

.手順
.  `security login motd modify`コマンドを使用して、クラスタまたはSVMのMOTDを作成します：
+
|===
| 状況 | 操作 


 a| 
1行のメッセージを指定する
 a| 
テキストを指定するには、 `-message`「[.code]``text``」パラメータを使用します。



 a| 
改行（EOL）を使用する
 a| 
 `-message`または `-uri`パラメータなしでコマンドを使用して、MOTDを編集するための対話型モードを起動します。



 a| 
MOTDに使用する内容を特定の場所からアップロードする
 a| 
 `-uri`パラメータを使用して、コンテンツのFTPまたはHTTPの場所を指定します。

|===
+
MOTDの最大サイズは、改行も含めて2,048バイトまでです。

+
`Security login motd modify`MOTDが動的に生成されたコンテンツを表示できるようにするために使用できるエスケープシーケンスについて説明します。

+
 `-uri`パラメータを使用して作成されたMOTDは静的です。ソースコンテンツの後続の変更を反映するために自動的に更新されることはありません。

+
クラスタ用に作成されたMOTDは、デフォルトですべてのSVMログインにも表示されます。また、特定のSVMに対して個別に作成できるSVMレベルのMOTDも表示されます。SVMに対して `-is-cluster-message-enabled`パラメータを `false`に設定すると、そのSVMのクラスタレベルのMOTDは表示されなくなります。

.  `security login motd show`コマンドを使用してMOTDを表示し、作成されたことを確認します。
+
 `-message`パラメータに空の文字列（``）を指定すると、構成されていないMOTDまたはコンテンツのないMOTDが表示されます。

+
 `security login motd modify`およびパラメータの詳細を確認して、MOTDが動的に生成されたコンテンツをlink:https://docs.netapp.com/us-en/ontap-cli/security-login-motd-modify.html["ONTAPコマンド リファレンス"^]に表示できるようにしてください。



.MOTDの作成例
次の例では、非対話型モードを使用して `cluster1`クラスタのMOTDを作成します：

[listing]
----
cluster1::> security login motd modify -message "Greetings!"
----
次の例では、対話型モードを使用して、 `svm1` SVMのエスケープシーケンスを使用して動的に生成されたコンテンツを表示するMOTDを作成します：

[listing]
----
cluster1::> security login motd modify -vserver svm1

Enter the message of the day for Vserver "svm1".
Max size: 2048. Enter a blank line to terminate input. Press Ctrl-C to abort.
0        1         2         3         4         5         6         7         8
12345678901234567890123456789012345678901234567890123456789012345678901234567890
Welcome to the \n SVM.  Your user ID is '\N'. Your last successful login was \L.
----
次の例では、作成したMOTDを表示しています。

[listing]
----
cluster1::> security login motd show
Vserver: cluster1
Is the Cluster MOTD Displayed?: true
Message
-----------------------------------------------------------------------------
Greetings!

Vserver: svm1
Is the Cluster MOTD Displayed?: true
Message
-----------------------------------------------------------------------------
Welcome to the \n SVM.  Your user ID is '\N'. Your last successful login was \L.

2 entries were displayed.
----
 `security login motd show`の詳細については、link:https://docs.netapp.com/us-en/ontap-cli/security-login-motd-show.html["ONTAPコマンド リファレンス"^]をご覧ください。
