---
permalink: system-admin/create-motd-task.html 
sidebar: sidebar 
keywords: create, motd, cli, user, clustershell, ssh, session, cluster, access, message, day 
summary: Message Of The Day（MOTD）を作成して、認証されたCLIユーザに情報を伝達できます。MOTD は、ユーザの認証後、クラスタシェルプロンプトが表示される前に、コンソールセッション（クラスタアクセスのみ）または SSH セッション（クラスタアクセスまたは SVM アクセス）に表示されます。 
---
= MOTDの作成
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Message Of The Day（MOTD）を作成して、認証されたCLIユーザに情報を伝達できます。MOTD は、ユーザの認証後、クラスタシェルプロンプトが表示される前に、コンソールセッション（クラスタアクセスのみ）または SSH セッション（クラスタアクセスまたは SVM アクセス）に表示されます。

.手順
. コマンドを使用し `security login motd modify`て、クラスタまたはSVMのMOTDを作成します。
+
|===
| 状況 | そしたら...。 


 a| 
1行のメッセージを指定する
 a| 
[.code]``text``パラメータを使用し `-message`てテキストを指定します。



 a| 
改行を含める(行末とも呼ばれる)
 a| 
または `-uri`パラメータを指定せずにコマンドを実行する `-message`と、対話型モードでMOTDを編集できます。



 a| 
MOTDに使用するコンテンツを場所からアップロードする
 a| 
パラメータを使用し `-uri`て、コンテンツのFTPまたはHTTPの場所を指定します。

|===
+
MOTDの最大サイズは、改行を含めて2、048バイトです。

+
のマニュアルページに、 `security login motd modify`動的に生成される内容をMOTDに表示するためのエスケープシーケンスが記載されています。

+
パラメータを使用して作成されたMOTD `-uri`は静的です。ソースコンテンツのその後の変更を反映して自動的に更新されることはありません。

+
クラスタ用に作成した MOTD は、デフォルトでは、各 SVM に対して個別に作成した SVM レベルの MOTD と一緒に、すべての SVM ログインに対しても表示されます。SVMのパラメータをに `false`設定する `-is-cluster-message-enabled`と、そのSVMに対するクラスタレベルのMOTDは表示されません。

. コマンドを使用して、作成されたMOTDが表示されることを確認します `security login motd show`。
+
パラメータに空の文字列を指定する `-message`(`""`と、未設定または内容が含まれていないMOTDが表示されます。

+
動的に生成される内容をMOTDに表示するためのパラメータの一覧については、コマンドのマニュアルページを参照して https://docs.netapp.com/ontap-9/topic/com.netapp.doc.dot-cm-cmpr-980/security%5F%5Flogin%5F%5Fmotd%5F%5Fmodify.html["security login motd modify のように変更します"]ください。使用しているONTAPのバージョンに固有のマニュアルページを確認してください。



.MOTDの作成例
次の例では、非対話型モードを使用して「 cluster1 」クラスタ用の MOTD を作成しています。

[listing]
----
cluster1::> security login motd modify -message "Greetings!"
----
次の例では、対話型モードを使用して「 `vm1 」 SVM 用の MOTD を作成しています。この MOTD では、エスケープシーケンスを使用して、動的に生成される内容を表示します。

[listing]
----
cluster1::> security login motd modify -vserver svm1

Enter the message of the day for Vserver "svm1".
Max size: 2048. Enter a blank line to terminate input. Press Ctrl-C to abort.
0        1         2         3         4         5         6         7         8
12345678901234567890123456789012345678901234567890123456789012345678901234567890
Welcome to the \n SVM.  Your user ID is '\N'. Your last successful login was \L.
----
次の例は、作成したMOTDを表示します。

[listing]
----
cluster1::> security login motd show
Vserver: cluster1
Is the Cluster MOTD Displayed?: true
Message
-----------------------------------------------------------------------------
Greetings!

Vserver: svm1
Is the Cluster MOTD Displayed?: true
Message
-----------------------------------------------------------------------------
Welcome to the \n SVM.  Your user ID is '\N'. Your last successful login was \L.

2 entries were displayed.
----