---
permalink: system-admin/create-banner-task.html 
sidebar: sidebar 
keywords: create, banner, svm, access, cluster, ssh, session 
summary: コンソールまたはSSHセッションでクラスタまたはSVMにアクセスしようとするユーザーにメッセージを表示するバナーを作成できます。 
---
= ONTAPログインバナーを作成する
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
バナーを作成して、クラスタまたはSVMへのアクセスを試行したユーザにメッセージを表示することができます。バナーは、ユーザに認証を要求する前に、コンソール セッション（クラスタ アクセスのみ）またはSSHセッション（クラスタ アクセスまたはSVMアクセス）に表示されます。

.手順
.  `security login banner modify`コマンドを使用して、クラスタまたはSVMのバナーを作成します：
+
|===
| 状況 | 操作 


 a| 
1行のメッセージを指定する
 a| 
テキストを指定するには、 `-message`「[.code]``<text>``」パラメータを使用します。



 a| 
メッセージで改行（EOL）を使用する
 a| 
 `-message`または `-uri`パラメータなしでコマンドを使用して、バナーを編集するための対話型モードを起動します。



 a| 
バナーに使用する内容を特定の場所からアップロードする
 a| 
 `-uri`パラメータを使用して、コンテンツのFTPまたはHTTPの場所を指定します。

|===
+
バナーの最大サイズは、改行を含めて2,048バイトです。

+
 `-uri`パラメータを使用して作成されたバナーは静的です。ソースコンテンツのその後の変更を反映して自動的に更新されることはありません。

+
クラスタ用に作成されたバナーは、既存のバナーがないすべてのSVMにも表示されます。その後にSVMに作成されたバナーは、そのSVMのクラスタレベルのバナーを上書きします。 `-message`パラメータに二重引用符で囲んだハイフン（(`"-"`）を指定すると、SVMはクラスタレベルのバナーを使用するようにリセットされます。

.  `security login banner show`コマンドでバナーを表示して、バナーが作成されたことを確認します。
+
 `-message`パラメータに空の文字列（(`""`）を指定すると、コンテンツのないバナーが表示されます。

+
 `-message`パラメータを `"-"`で指定すると、バナーが設定されていないすべての（管理またはデータ）SVMが表示されます。



.バナーの作成例
次の例では、非対話型モードを使用して「`cluster1`」クラスタのバナーを作成します：

[listing]
----
cluster1::> security login banner modify -message "Authorized users only!"

cluster1::>
----
次の例では、対話型モードを使用して `svm1` SVMのバナーを作成します：

[listing]
----
cluster1::> security login banner modify -vserver svm1

Enter the message of the day for Vserver "svm1".
Max size: 2048. Enter a blank line to terminate input. Press Ctrl-C to abort.
0        1         2         3         4         5         6         7         8
12345678901234567890123456789012345678901234567890123456789012345678901234567890
The svm1 SVM is reserved for authorized users only!


cluster1::>
----
次の例では、作成したバナーを表示しています。

[listing]
----
cluster1::> security login banner show
Vserver: cluster1
Message
-----------------------------------------------------------------------------
Authorized users only!

Vserver: svm1
Message
-----------------------------------------------------------------------------
The svm1 SVM is reserved for authorized users only!

2 entries were displayed.

cluster1::>
----
.関連情報
* xref:manage-banner-reference.adoc[バナーの管理]
* link:https://docs.netapp.com/us-en/ontap-cli/security-login-banner-modify.html["セキュリティログインバナーの変更"^]
* link:https://docs.netapp.com/us-en/ontap-cli/security-login-banner-show.html["セキュリティログインバナーの表示"^]

