---
permalink: system-admin/different-shells-cli-commands-concept-cluster-admin.html 
sidebar: sidebar 
keywords: diag, secd, different, shells, cli, commands, cluster, administrators, clustershell, nodeshell, systemshell, display, list, help 
summary: クラスタには、 CLI コマンド用の異なる 3 つのシェルとして、クラスタシェル、ノードシェル、システムシェルがあります。シェルは目的が異なり、それぞれに異なるコマンドセットがあります。 
---
= CLIコマンド用シェルの概要（クラスタ管理者のみ）
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
クラスタには、 CLI コマンド用の異なる 3 つのシェルとして、 _clustershell _ 、 _nodeshell _ 、 _systemshell _ があります。シェルは目的が異なり、それぞれに異なるコマンドセットがあります。

* クラスタシェルは、クラスタにログインすると自動的に開始されるネイティブシェルです。
+
クラスタの設定と管理に必要なコマンドがすべて含まれています。クラスタシェルのCLIヘルプ（クラスタシェルプロンプトでと入力するとトリガーされる `?`）には、使用可能なクラスタシェルコマンドが表示されます。クラスタシェルのコマンドは `man _command_name_`、指定したクラスタシェルコマンドのマニュアルページを表示します。

* ノードシェルは、ノードレベルでのみ有効になるコマンド用の特別なシェルです。
+
ノードシェルには、コマンドを使用してアクセスでき `system node run`ます。

+
ノードシェルのCLIヘルプ（または `help`でトリガー）に `?`は、使用可能なノードシェルコマンドが表示されます。ノードシェルのコマンドは `man _command_name_`、指定したノードシェルコマンドのマニュアルページを表示します。

+
よく使用されるノードシェルのコマンドとオプションの多くは、クラスタシェルにトンネリングまたはエイリアスされ、クラスタシェルからも実行できます。

* システムシェルは、診断とトラブルシューティングの目的でのみ使用される下位レベルのシェルです。
+
システムシェルおよび関連する「タグ」アカウントは、下位レベルの診断用です。アクセスにはdiagnostic権限レベルが必要で、テクニカルサポートがトラブルシューティングタスクを実行するためにのみ予約されています。





== クラスタシェルでのノードシェルのコマンドおよびオプションへのアクセス

ノードシェルのコマンドとオプションには、ノードシェルからアクセスできます。

`system node run –node _nodename_`

よく使用されるノードシェルのコマンドとオプションの多くは、クラスタシェルにトンネリングまたはエイリアスされ、クラスタシェルからも実行できます。

クラスタシェルでサポートされているノードシェルオプションには、コマンドを使用してアクセスでき `vserver options clustershell`ます。これらのオプションを表示するには、次のいずれかを実行します。

* を使用してクラスタシェルCLIを照会する `vserver options -vserver _nodename_or_clustername_ -option-name ?`
* を使用してクラスタシェルCLIのマニュアルページにアクセスします `vserver options`。 `man vserver options`


クラスタシェルでノードシェルまたはレガシーのコマンドまたはオプションを入力し、そのコマンドまたはオプションに相当するクラスタシェルコマンドがある場合は、そのクラスタシェルコマンドを使用するようにONTAPから通知されます。

クラスタシェルでノードシェルまたはレガシーのコマンドまたはオプションを入力した場合、そのコマンドまたはオプションについて「 not supported 」ステータスが ONTAP から通知されます。



== 使用可能なノードシェルコマンドを表示します。

ノードシェルからCLIヘルプを使用すると、使用可能なノードシェルコマンドのリストを取得できます。

.手順
. ノードシェルにアクセスするには、クラスタシェルのシステムプロンプトで次のコマンドを入力します。
+
`*system node run -node {_nodename_|local}*`

+
`local`は、クラスタへのアクセスに使用したノードです。

+
[NOTE]
====
この `system node run`コマンドには、エイリアスコマンド、が `run`あります。

====
. 使用可能なノードシェルコマンドの一覧を表示するには、ノードシェルで次のコマンドを入力します。
+
`*[_commandname_] help*`

+
 `_commandname_`は、可用性を表示するコマンドの名前です。を指定しないと、 `_commandname_`使用可能なすべてのノードシェルコマンドが表示されます。

+
クラスタシェルCLIに戻るには、Ctrl+Dを入力するか入力し `exit`ます。



.利用可能なノードシェルコマンドを表示する例
次の例は、node2という名前のノードのノードシェルにアクセスし、ノードシェルコマンドの情報を表示します `environment`。

[listing]
----
cluster1::> system node run -node node2
Type 'exit' or 'Ctrl-D' to return to the CLI

node2> environment help
Usage: environment status |
     [status] [shelf [<adapter>[.<shelf-number>]]] |
     [status] [shelf_log] |
     [status] [shelf_stats] |
     [status] [shelf_power_status] |
     [status] [chassis [all | list-sensors | Temperature | PSU 1 |
     PSU 2 | Voltage | SYS FAN | NVRAM6-temperature-3 | NVRAM6-battery-3]]
----