---
permalink: system-admin/download-nlf-task.html 
sidebar: sidebar 
keywords: install, license, convert, download, add, record, software, entitlement, keys, codes, cluster, administrator, nlf, ontap one 
summary: ONTAP 9.10.1以降を実行しているシステムでは、NetApp Support SiteからONTAP OneまたはONTAP Core用のNLFをダウンロードすることで、既存のシステムでライセンスファイルまたは28文字のライセンスキーをアップグレードできます。 
---
= NetAppサポートサイトからNetAppライセンスファイル（NLF）をダウンロードします。
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
ONTAP 9 .10.1以降を実行しているシステムの場合は、NetAppサポートサイトからONTAP OneまたはONTAP Core用NLFをダウンロードして、既存のシステムのバンドルライセンスファイルをアップグレードできます。


NOTE: SnapMirrorクラウドとSnapMirror S3のライセンスは、ONTAP ONEには含まれていません。これらはONTAP One Compatibilityバンドルの一部であり、ONTAP Oneとをお持ちの場合は無料で入手できますlink:../data-protection/install-snapmirror-cloud-license-task.html["個別にリクエスト"]。

.手順
ONTAP ONEライセンスファイルは、既存のNetAppライセンスファイルバンドルがあるシステム、および28文字のライセンスキーがONTAP 9 .10.1以降を実行するシステムでNetAppライセンスファイルに変換されたシステム用にダウンロードできます。また、ONTAPベースからONTAP Oneにシステムをアップグレードすることもできます。

[role="tabbed-block"]
====
.既存のNLFをアップグレード
--
. アップグレードまたは変換するライセンスファイルバンドル（ONTAP BaseからONTAP One、Core Bundleおよびデータ保護バンドルからONTAP Oneなど）は、NetApp営業チームにお問い合わせください。
+
リクエストが処理されると、件名が「SO#[SO番号]のNetAppソフトウェアライセンス通知」と記載されたメールがnetappsw@netapp.comから送信されます。メールには、ライセンスのシリアル番号が記載されたPDF添付ファイルが添付されています。

. にログインし link:https://mysupport.netapp.com/site/["NetAppサポートサイト"^]ます。
. [システム]>[ソフトウェアライセンス]*を選択します。
. メニューから*シリアル番号*を選択し、受け取ったシリアル番号を入力して*新規検索*をクリックします。
. 変換するライセンスバンドルを探します。
. 各ライセンスバンドルの[Get NetApp License File]*をクリックし、NLFが利用可能になったらダウンロードします。
. link:../system-admin/install-license-task.html["インストール"]ONTAP Oneファイル。


--
.ライセンスキーから変換されたNLFのアップグレード
--
. にログインし link:https://mysupport.netapp.com/site/["NetAppサポートサイト"^]ます。
. [システム]>[ソフトウェアライセンス]*を選択します。
. メニューから*シリアル番号*を選択し、システムのシリアル番号を入力して*新規検索*をクリックします。
. 変換するライセンスを探し、* Eligibility *列で* Check *をクリックします。
. [Check Eligibility]フォーム*で、*[Generate Licenses for 9.10.x and later]*をクリックします。
. [Check Eligibility]フォーム*を閉じます。
+
ライセンスが生成されるまで少なくとも2時間待つ必要があります。

. 手順1～3を繰り返します。
. ONTAP Oneライセンスを探し、*[Get NetApp License File]*をクリックして配信方法を選択します。
. link:../system-admin/install-license-task.html["インストール"]ONTAP Oneファイル。


--
====