---
permalink: system-admin/enable-sp-bmc-automatic-network-config-task.html 
sidebar: sidebar 
keywords: enable, sp, bmc, automatic, network, configuration 
summary: SP ネットワークを手動で設定するよりも、自動ネットワーク設定を使用するように SP を設定することを推奨します。SPの自動ネットワーク設定はクラスタ全体で行われるため、個 々 のノードのSPネットワークを手動で管理する必要はありません。 
---
= ONTAP SP / BMCの自動ネットワーク設定を有効にする
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
SP ネットワークを手動で設定するよりも、自動ネットワーク設定を使用するように SP を設定することを推奨します。SPの自動ネットワーク設定はクラスタ全体で行われるため、個 々 のノードのSPネットワークを手動で管理する必要はありません。

[NOTE]
====
このタスクは、SPとBMCの両方に適用されます。

====
* SPの自動ネットワーク設定に使用するサブネットは、クラスタで定義済みであり、SPネットワークインターフェイスとリソースが競合していない必要があります。
+
コマンドは `network subnet show`、クラスタのサブネット情報を表示します。

+
の詳細については `network subnet show`、をlink:https://docs.netapp.com/us-en/ontap-cli/network-subnet-show.html["ONTAPコマンド リファレンス"^]参照してください。

+
サブネットの関連付けを強制するパラメータ（ `-force-update-lif-associations`コマンドのパラメータ `network subnet`）は、ネットワークLIFでのみサポートされ、SPネットワークインターフェイスではサポートされません。

* SP に IPv6 接続を設定する場合、 ONTAP に対して IPv6 が設定済みで、有効になっている必要があります。
+
 `network options ipv6 show`コマンドは、ONTAPのIPv6設定の現在の状態を表示します。の詳細については `network options ipv6 show`、をlink:https://docs.netapp.com/us-en/ontap-cli/network-options-ipv6-show.html["ONTAPコマンド リファレンス"^]参照してください。



.手順
. コマンドを使用して、SPで使用するサブネットのIPv4またはIPv6アドレスファミリーと名前を指定します `system service-processor network auto-configuration enable`。
. コマンドを使用して、SPの自動ネットワーク設定を表示します `system service-processor network auto-configuration show`。
. その後、クォーラム内のすべてのノードに対してSP IPv4またはIPv6ネットワークインターフェイスを無効または再度有効にする場合は、コマンドで [`IPv4`|`IPv6`] [`true`|`false`パラメータと `-enable`]パラメータを指定して `-address-family`使用し `system service-processor network modify`ます。
+
SP 自動ネットワーク設定が有効になっている場合、クォーラム内のノードの SP IP アドレスを変更することはできません。実行できるのは、 SP IPv4 または IPv6 ネットワークインターフェイスの有効化または無効化だけです。

+
ノードがクォーラムのメンバーでない場合は、ノードからを実行し、そのノードのSP自動ネットワーク設定を上書きすることを確認して、SP IPアドレスを含むノードのSPネットワーク設定を変更できます。 `system service-processor network modify`ただし、ノードがクォーラムに参加すると、指定したサブネットに基づいてノードに対して SP の自動再設定が実行されます。


