---
permalink: system-admin/find-config-backup-file-recovering-node-task.html 
sidebar: sidebar 
keywords: configuration, backup, file, recovering, node, remote, url, cluster 
summary: ノード構成をリカバリするには、リモート URL またはクラスタ内のノードにある構成バックアップファイルを使用します。 
---
= ノードのリカバリに使用する構成バックアップファイルを検索します
:icons: font
:imagesdir: ../media/


[role="lead"]
ノード構成をリカバリするには、リモート URL またはクラスタ内のノードにある構成バックアップファイルを使用します。

ノード構成をリストアするには、クラスタまたはノード構成バックアップファイルのいずれかを使用します。

.ステップ
. 構成のリストアに必要なノードに構成バックアップファイルを利用できるようにします。
+
|===
| 構成バックアップファイルの場所 | 作業 


 a| 
リモート URL
 a| 
リカバリ・ノードにシステム構成バックアップをダウンロードするには、 advanced 権限レベルで「 system configuration backup download 」コマンドを使用します。



 a| 
クラスタのノード
 a| 
.. リカバリするノードの構成を含むクラスタで利用可能な構成バックアップファイルのリストを表示するには、「 system configuration backup show 」コマンドを advanced 権限レベルで使用します。
.. 特定した構成バックアップファイルがリカバリノードに存在しない場合は、「 system configuration backup copy 」コマンドを使用して、リカバリノードにコピーします。


|===
+
以前にクラスタを作成し直したことがある場合は、クラスタの再作成後に作成した構成バックアップファイルを選択します。クラスタの再作成の前に作成した構成バックアップファイルを使用する必要がある場合は、ノードをリカバリしたあとで、クラスタを再度作成する必要があります。


