---
permalink: system-admin/find-config-recover-cluster-task.html 
sidebar: sidebar 
keywords: cluster, configuration, recover, node, backup, file 
summary: クラスタ内のノード、またはクラスタ構成バックアップファイルのいずれかの構成を使用してクラスタをリカバリできます。 
---
= クラスタのリカバリに使用する構成を検索します
:icons: font
:imagesdir: ../media/


[role="lead"]
クラスタ内のノード、またはクラスタ構成バックアップファイルのいずれかの構成を使用してクラスタをリカバリできます。

.手順
. クラスタのリカバリに使用する構成の種類を選択します。
+
** クラスタ内のノード
+
クラスタが複数のノードで構成されていて、クラスタが適切な構成であった時点からのクラスタ構成がいずれかのノードにある場合は、そのノードに格納された構成を使用してクラスタをリカバリできます。

+
ほとんどの場合、クラスタ構成のリストアには、最新のトランザクション ID を持つレプリケーションリングが含まれているノードが最適です。advanced 権限レベルで cluster ring show コマンドを使用すると、クラスタ内の各ノードで利用可能な一連のレプリケーションリングを表示できます。

** クラスタ構成バックアップファイル
+
適切なクラスタ構成を持つノードが特定できない場合、またはクラスタがシングルノードで構成されている場合は、クラスタ構成バックアップファイルを使用してクラスタをリカバリできます。

+
構成バックアップファイルからクラスタをリカバリするには、診断ツールを使用して、リカバリするノード上のバックアップとクラスタ構成との間の矛盾を解決しなければならないことがあります。そのため、構成バックアップファイルを使用する場合は、テクニカルサポートに連絡することを計画しておく必要があります。



. クラスタ構成バックアップファイルを使用する場合は、クラスタのリカバリに使用するノードでそのファイルを利用できるようにします。
+
|===
| 構成バックアップファイルの場所 | 作業 


 a| 
リモート URL
 a| 
リカバリ・ノードにシステム構成バックアップをダウンロードするには、 advanced 権限レベルで「 system configuration backup download 」コマンドを使用します。



 a| 
クラスタのノード
 a| 
.. advanced 権限レベルで「 system configuration backup show 」コマンドを使用し、クラスタが適切な構成であったときに作成されたクラスタ構成バックアップファイルを検索します。
.. クラスタのリカバリに使用するノード上にクラスタ構成バックアップファイルがない場合は、「 system configuration backup copy 」コマンドを使用して、リカバリするノードにコピーします。


|===

