---
permalink: system-admin/health-monitors-concept.html 
sidebar: sidebar 
keywords: available, cluster, health, monitors, errors, detect, events, alerts, delete 
summary: ヘルスモニタは複数あり、それぞれがクラスタの異なる部分を監視します。ヘルスモニタは、イベント検出、アラート送信、およびクリアされたイベントの削除を行い、 ONTAP システム内で発生したエラーからのリカバリに役立ちます。 
---
= シヨウカノウナクラスタヘルスモニタ
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
ヘルスモニタは複数あり、それぞれがクラスタの異なる部分を監視します。ヘルスモニタは、イベント検出、アラート送信、およびクリアされたイベントの削除を行い、 ONTAP システム内で発生したエラーからのリカバリに役立ちます。

|===
| ヘルスモニタ名（識別子） | サブシステム名（識別子） | 目的 


 a| 
クラスタスイッチ（cluster-switch）
 a| 
スイッチ（Switch-Health）
 a| 
温度、利用率、インターフェイスの設定、冗長性（クラスタネットワークスイッチのみ）、ファンおよび電源の動作に関して、クラスタネットワークスイッチと管理ネットワークスイッチを監視します。クラスタスイッチヘルスモニタは SNMP でスイッチと通信します。デフォルトの設定は SNMPv2c です。

[NOTE]
====
ONTAP 9.2 以降では、最後のポーリング期間以降のクラスタスイッチのリブートをこのモニタで検出して報告できるようになりました。

====


 a| 
MetroClusterファブリック
 a| 
スイッチ
 a| 
MetroCluster 構成のバックエンドファブリックトポロジを監視して、間違ったケーブル接続およびゾーニングなどの設定ミスや、 ISL の障害を検出します。



 a| 
MetroClusterの健常性
 a| 
インターコネクト、 RAID 、ストレージ
 a| 
FC-VI アダプタ、 FC イニシエータアダプタ、取り残されたアグリゲートやディスク、およびクラスタ間ポートを監視します



 a| 
ノード接続（node-connect）
 a| 
CIFS のノンストップオペレーション（ CIFS-NDO ）
 a| 
SMB 接続を監視して、 Hyper-V アプリケーションへのノンストップオペレーションを実現します。



 a| 
ストレージ（SAS-connect）
 a| 
ノードレベルでシェルフ、ディスク、およびアダプタを監視して、適切なパスと接続を維持します。



 a| 
システム
 a| 
該当なし
 a| 
他のヘルスモニタからの情報を集約します。



 a| 
システム接続（system-connect）
 a| 
ストレージ（SAS-connect）
 a| 
クラスタレベルでシェルフを監視して、 2 つの HA クラスタノードへの適切なパスを維持します。

|===