---
permalink: system-admin/health-monitors-concept.html 
sidebar: sidebar 
keywords: available, cluster, health, monitors, errors, detect, events, alerts, delete 
summary: ヘルスモニタは複数あり、それぞれがクラスタの異なる部分を監視します。ヘルスモニタは、イベント検出、アラート送信、およびクリアされたイベントの削除を行い、 ONTAP システム内で発生したエラーからのリカバリに役立ちます。 
---
= 使用可能なONTAPクラスタヘルスモニタの詳細
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
ヘルスモニタは複数あり、それぞれがクラスタの異なる部分を監視します。ヘルスモニタは、イベント検出、アラート送信、およびクリアされたイベントの削除を行い、 ONTAP システム内で発生したエラーからのリカバリに役立ちます。

|===
| ヘルスモニタ名（識別子） | サブシステム名（識別子） | 目的 


 a| 
イーサネット スイッチ
 a| 
スイッチ（Switch-Health）
 a| 
ONTAPイーサネットスイッチヘルスモニタ（CSHM）は、分析用のログを収集しながら、クラスタとストレージネットワークスイッチのステータスを監視します。デフォルトでは、CSHMは5分ごとにSNMPv2c経由で各スイッチをポーリングし、サポート性、監視ステータス、温度センサー、CPU利用率、インターフェイスの設定と接続、クラスタスイッチの冗長性、ファンと電源の動作に関する情報を含むリソーステーブルを更新します。また、設定されている場合、CSHMは1時間ごとにSSH/SCP経由でログを収集し、さらに分析するためにAutoSupport経由で送信します。要求に応じて、CSHMはSSH/SCPを使用して、より詳細なテクニカルサポートログ収集を実行することもできます。

詳細については、を参照してください link:https://docs.netapp.com/us-en/ontap-systems-switches/switch-cshm/config-overview.html["スイッチヘルスの監視"^] 。



 a| 
MetroClusterファブリック
 a| 
スイッチ
 a| 
MetroCluster 構成のバックエンドファブリックトポロジを監視して、間違ったケーブル接続およびゾーニングなどの設定ミスや、 ISL の障害を検出します。



 a| 
MetroClusterの健常性
 a| 
インターコネクト、 RAID 、ストレージ
 a| 
FC-VI アダプタ、 FC イニシエータアダプタ、取り残されたアグリゲートやディスク、およびクラスタ間ポートを監視します



 a| 
ノード接続（node-connect）
 a| 
CIFS のノンストップオペレーション（ CIFS-NDO ）
 a| 
SMB 接続を監視して、 Hyper-V アプリケーションへのノンストップオペレーションを実現します。



 a| 
ストレージ（SAS-connect）
 a| 
ノードレベルでシェルフ、ディスク、およびアダプタを監視して、適切なパスと接続を維持します。



 a| 
システム
 a| 
該当なし
 a| 
他のヘルスモニタからの情報を集約します。



 a| 
システム接続（system-connect）
 a| 
ストレージ（SAS-connect）
 a| 
クラスタレベルでシェルフを監視して、 2 つの HA クラスタノードへの適切なパスを維持します。

|===