---
permalink: system-admin/health-alerts-autosupport-messages-events-concept.html 
sidebar: sidebar 
keywords: system, health, alerts, trigger, autosupport, ems, event, management, message, event 
summary: システムヘルスアラートは、AutoSupportメッセージおよびイベント管理システム（EMS）内のイベントをトリガーします。これにより、ヘルスモニタシステムを直接使用するだけでなく、AutoSupportメッセージおよびEMSを使用してシステムの健全性を監視できます。 
---
= ONTAP AutoSupport健全性アラートのトリガーについて
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
システムヘルスアラートは、AutoSupportメッセージおよびイベント管理システム（EMS）内のイベントをトリガーします。これにより、ヘルスモニタシステムを直接使用するだけでなく、AutoSupportメッセージおよびEMSを使用してシステムの健全性を監視できます。

アラートから5分以内にAutoSupportメッセージが送信されます。AutoSupportメッセージには、前のAutoSupportメッセージ以降に生成されたすべてのアラートが含まれます。ただし、同じリソースおよび考えられる原因について前の週にアラートが重複するアラートは除きます。

一部のアラートでは、AutoSupportメッセージがトリガーされません。ヘルスポリシーでAutoSupportメッセージの送信が無効になっている場合、アラートはAutoSupportメッセージをトリガーしません。たとえば、問題の発生時にAutoSupportですでにメッセージが生成されているため、ヘルスポリシーによってAutoSupportメッセージがデフォルトで無効になる場合があります。コマンドを使用すると、AutoSupportメッセージをトリガーしないようにポリシーを設定でき `system health policy definition modify`ます。

コマンドを使用すると、前の週に送信されたアラートトリガー型AutoSupportメッセージのすべてのリストを表示できます `system health autosupport trigger history show`。

また、アラートによってEMSに対するイベントの生成もトリガーされます。イベントは、アラートが作成されるたび、およびアラートがクリアされるたびに生成されます。
