---
permalink: system-admin/install-ca-signed-server-certificate-cluster-task.html 
sidebar: sidebar 
keywords: install, ca, signed, server, certificate, cluster, ssl, svm, sotrage, virtual, machine, administrator 
summary: SSL サーバでクラスタまたは Storage Virtual Machine （ SVM ）を SSL クライアントとして認証するためには、 client タイプのデジタル証明書をクラスタまたは SVM にインストールします。次に、 client-ca 証明書をその SSL サーバの管理者に渡してインストールしてもらいます。 
---
= ONTAPクラスタ用のCA署名サーバ証明書をインストールする
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
SSL サーバでクラスタまたは Storage Virtual Machine （ SVM ）を SSL クライアントとして認証するためには、 client タイプのデジタル証明書をクラスタまたは SVM にインストールします。次に、 client-ca 証明書をその SSL サーバの管理者に渡してインストールしてもらいます。

.開始する前に
SSLサーバのルート証明書を、証明書タイプのクラスタまたはSVMにインストールしておく必要があります `server-ca`。

.手順
. クライアント認証に自己署名デジタル証明書を使用するには、 `security certificate create`コマンドでパラメータを指定し `type client`ます。
+
の詳細については `security certificate create`、をlink:https://docs.netapp.com/us-en/ontap-cli/security-certificate-create.html["ONTAPコマンド リファレンス"^]参照してください。

. クライアント認証に CA 署名デジタル証明書を使用するには、次の手順を実行します。
+
.. security certificateコマンドを使用して、デジタル証明書署名要求（CSR）を生成します `generate-csr`。
+
証明書要求と秘密鍵を含む CSR 出力が表示され、今後の参照用にファイルにコピーするよう求められます。 ONTAP

.. CSR 出力の証明書要求をデジタル形式（ E メールなど）で信頼できる CA に送信し、署名を求めます。
+
秘密鍵と CA 署名証明書のコピーは今後の参照用として保管しておいてください。

+
要求が処理されると、署名済みのデジタル証明書がCAから送信されます。

.. コマンドでパラメータを指定して `-type client`、CA署名証明書をインストールし `security certificate install`ます。
.. プロンプトが表示されたら証明書と秘密鍵を入力し、 * Enter * キーを押します。
.. プロンプトが表示されたら追加のルート証明書または中間証明書を入力し、 * Enter * キーを押します。
+
信頼できるルート CA から発行された SSL 証明書に至る証明書チェーンに中間証明書がない場合は、クラスタまたは SVM に中間証明書をインストールします。中間証明書は、問題のエンドエンティティのサーバ証明書専用に信頼できるルートから発行される、副次的な証明書です。この結果、信頼できるルート CA から始まり、中間証明書を経て、発行された SSL 証明書で終わる証明書チェーンが形成されます。



. クラスタまたはSVMの証明書をSSLサーバの管理者に渡してインストールしてもらいます `client-ca`。
+
security certificate showコマンドと `-type client-ca`パラメータを指定して実行すると、 `-instance`証明書の情報が表示されます `client-ca`。



.関連情報
* link:https://docs.netapp.com/us-en/ontap-cli/security-certificate-install.html["セキュリティ証明書のインストール"^]
* link:https://docs.netapp.com/us-en/ontap-cli/security-certificate-show.html["security certificate show"^]

