---
permalink: system-admin/keyboard-shortcuts-edit-cli-commands-reference.html 
sidebar: sidebar 
keywords: keyboard, shortcuts, edit, cli, commands, unix, tcsh, shell, emacs, editor, active 
summary: 現在のコマンドプロンプトのコマンドは、アクティブなコマンドです。キーボードショートカットを使用して、アクティブなコマンドをすばやく編集できます。UNIX tsch シェルや Emacs エディタと同様のショートカットを使用できます。 
---
= CLIコマンドを編集するためのONTAPキーボードショートカット
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
現在のコマンドプロンプトのコマンドは、アクティブなコマンドです。キーボードショートカットを使用して、アクティブなコマンドをすばやく編集できます。UNIX tsch シェルや Emacs エディタと同様のショートカットを使用できます。

次の表に、CLIコマンドを編集するためのキーボードショートカットを示します。 `Ctrl-`Ctrlキーを押したまま、そのあとに指定した文字を入力することを示します。 `Esc-`Escキーを押して放し、その後に指定した文字を入力することを示します。

[cols="4a,4a"]
|===
| 状況 | 使用するキーボードショートカット 


 a| 
カーソルを 1 文字左に移動します
 a| 
* Ctrl+B キーを押下
* 戻る矢印




 a| 
カーソルを 1 文字右に移動します
 a| 
* Ctrl+F
* 右矢印




 a| 
カーソルを 1 単語分左に移動します
 a| 
ESC-B



 a| 
カーソルを 1 単語分右に移動します
 a| 
ESC-F



 a| 
カーソルを行頭に移動します
 a| 
Ctrl+A



 a| 
カーソルを行末へ移動します
 a| 
Ctrl+E



 a| 
行の先頭からカーソルまでコマンドラインの内容を削除し、カットバッファに保存します。切り取りバッファは ' 一部のプログラムでは _clipboard_ と呼ばれるのと同様に ' 一時的なメモリのように機能します
 a| 
Ctrl+U キーを押下



 a| 
カーソルから行末までの入力内容を切り取ってバッファに保存する
 a| 
Ctrl+K キーを押下



 a| 
カーソルから次の単語の末尾までを切り取ってバッファに保存する
 a| 
ESC-D



 a| 
カーソルの前の単語を削除し、切り取りバッファに保存します。
 a| 
Ctrl+W キーを押下



 a| 
切り取りバッファの内容を取得し、カーソルのコマンドラインに挿入します
 a| 
Ctrl+Y キーを押下



 a| 
カーソルの前の文字を削除します
 a| 
* Ctrl+H
* バックスペース




 a| 
カーソル位置の文字を削除します
 a| 
Ctrl+D を使用します



 a| 
行をクリアします
 a| 
Ctrl+C キーを押します



 a| 
画面をクリアします
 a| 
Ctrl+L キーを押下



 a| 
コマンドラインの現在の内容を、履歴リストの前のエントリに置き換えます。

このキーボードショートカットを押すたびに履歴カーソルが 1 つ前のエントリに移動します。
 a| 
* Ctrl+P キーを押下
* ESC-P
* 上矢印




 a| 
コマンドラインの現在の内容を、履歴リストの次のエントリに置き換えます。このキーボードショートカットを押すたびに履歴カーソルが次のエントリに移動します。
 a| 
* Ctrl+N キーを押下
* ESC-N
* 下矢印




 a| 
部分的に入力されたコマンドを展開するか、現在の編集位置から有効な入力のリストを表示します
 a| 
* タブ
* Ctrl+I




 a| 
状況に応じたヘルプを表示します
 a| 
?



 a| 
疑問符 `?`）文字の特殊マッピングをエスケープします。たとえば、コマンドの引数に疑問符を入力するには、Escキーを押してから文字を押し `?`ます。
 a| 
ESC - ？



 a| 
TTY 出力を開始します
 a| 
Ctrl+Q キーを押下



 a| 
TTY 出力を停止します
 a| 
Ctrl+S

|===