---
permalink: system-admin/keyboard-shortcuts-edit-cli-commands-reference.html 
sidebar: sidebar 
keywords: keyboard, shortcuts, edit, cli, commands, unix, tcsh, shell, emacs, editor, active 
summary: 現在のコマンドプロンプトに表示されているコマンドがアクティブコマンドです。キーボードショートカットを使用すると、アクティブコマンドを素早く編集できます。これらのキーボードショートカットは、UNIXのtcshシェルやEmacsエディタのショートカットに似ています。 
---
= CLI コマンドを編集するための ONTAP キーボード ショートカット
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
現在のコマンドプロンプトに表示されているコマンドがアクティブコマンドです。キーボードショートカットを使用すると、アクティブコマンドを素早く編集できます。これらのキーボードショートカットは、UNIXのtcshシェルやEmacsエディタのショートカットに似ています。

次の表は、CLI コマンドを編集するためのキーボード ショートカットを示しています。 `Ctrl-`は、Ctrl キーを押したまま、その後に指定された文字を入力することを示します。 `Esc-`は、Esc キーを押して放し、その後に指定された文字を入力することを示します。

[cols="4a,4a"]
|===
| 状況 | 次のいずれかのキーボード ショートカットを使用します... 


 a| 
カーソルを1文字分後ろに移動
 a| 
* Ctrl-B
* 戻る矢印




 a| 
カーソルを1文字分前進させる
 a| 
* Ctrl-F
* 前進矢印




 a| 
カーソルを1単語分後ろに移動
 a| 
Esc-B



 a| 
カーソルを1単語分前進させる
 a| 
Esc-F



 a| 
カーソルを行頭に移動する
 a| 
Ctrl-A



 a| 
カーソルを行末に移動する
 a| 
Ctrl-E



 a| 
コマンドラインの先頭からカーソル位置までのコンテンツを削除し、カットバッファに保存します。カットバッファは、一部のプログラムで_クリップボード_と呼ばれるものと同様の一時メモリとして機能します。
 a| 
Ctrl-U



 a| 
カーソルから行末までのコマンドラインの内容を削除し、カットバッファに保存します。
 a| 
Ctrl-K



 a| 
カーソルから次の単語の末尾までのコマンドラインの内容を削除し、カットバッファに保存します
 a| 
Esc-D



 a| 
カーソルの左側の単語を切り取ってバッファに保存する
 a| 
Ctrl-W



 a| 
切り取ったバッファの内容をヤンクし、カーソルのあるコマンドラインにプッシュします
 a| 
Ctrl-Y



 a| 
カーソルの前の文字を削除します
 a| 
* Ctrl-H
* バックスペース




 a| 
カーソルがある文字を削除します
 a| 
Ctrl-D



 a| 
ラインをクリア
 a| 
Ctrl-C



 a| 
画面をクリアする
 a| 
Ctrl-L



 a| 
コマンドライン上の現在の内容を、履歴リストの前のエントリに置き換える。

キーボードショートカットを繰り返すたびに、履歴カーソルが前のエントリに移動します。
 a| 
* Ctrl-P
* Esc-P
* 上矢印




 a| 
コマンドラインの現在の内容を履歴リストの次のエントリに置き換えます。キーボードショートカットを繰り返すたびに、履歴カーソルが次のエントリに移動します。
 a| 
* Ctrl-N
* Esc-N
* 下矢印




 a| 
部分的に入力されたコマンドを展開するか、現在の編集位置から有効な入力を一覧表示します
 a| 
* タブ
* Ctrl-I




 a| 
状況依存ヘルプを表示する
 a| 
?



 a| 
疑問符 `?`文字の特殊マッピングをエスケープします。例えば、コマンドの引数に疑問符を入力するには、Escキーを押してから `?`文字を入力します。
 a| 
Esc-？



 a| 
TTY出力を開始する
 a| 
Ctrl-Q



 a| 
TTY出力を停止する
 a| 
Ctrl-S

|===