---
permalink: concepts/licensing-concept.html 
sidebar: sidebar 
keywords: licensing, ONTAP, enable features 
summary: ライセンスには、ソフトウェアの使用権が 1 つ以上記録されています。2023年5月以降、すべてのAFFシステム（AシリーズとCシリーズの両方）とFASシステムは、ONTAP ONEソフトウェアスイートまたはONTAP Baseソフトウェアスイートのいずれかとともに販売されます。 
---
= ONTAPライセンスの概要
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
ライセンスには、ソフトウェアの使用権が 1 つ以上記録されています。ONTAP 9.10.1以降では、すべてのライセンスがNetAppライセンスファイル（NLF）として提供されます。これは、複数の機能を有効にする単一のファイルです。  2023年5月以降、すべてのAFFシステム（AシリーズとCシリーズの両方）とFASシステムは、ONTAP ONEソフトウェアスイートまたはONTAP Baseソフトウェアスイートのいずれかとともに販売されます。これらのソフトウェアスイートはそれぞれ1つのNLFとして提供され、ONTAP 9.10.1で最初に導入された個別のNLFバンドルに置き換わります。



== ONTAP Oneに含まれるライセンス

ONTAP Oneには、使用可能なライセンス機能がすべて含まれています以前のCore Bundle、Data Protection Bundle、Security and Compliance Bundle、Hybrid Cloud Bundle、Encryption Bundleの内容が次の表にまとめられています。暗号化は制限された国では使用できません。

|===


| 以前のバンドル名 | ONTAP Oneキー付属 


.5+| Core Bundle | FlexClone 


| SnapRestore 


| NFS、SMB、S3 


| FC、iSCSI 


| NVMe-oF 


.3+| Security and Compliance Bundle | 自律的なランサムウェア防御 


| MTKM 


| SnapLock 


.3+| Data Protection Bundle | SnapMirror（非同期、同期、ビジネス継続性） 


| SnapCenter 


| NetAppターゲット用のS3 SnapMirror 


.2+| Hybrid Cloud Bundle | SnapMirror クラウド 


| ネットアップ以外のターゲット用のS3 SnapMirror 


.3+| 暗号化バンドル | NetApp Volume Encryption の略 


| Trusted Platformモジュール 


| 保存データの暗号化 
|===


== ONTAP Oneに含まれていないライセンス

ONTAP Oneには、以下を含むネットアップのクラウド提供サービスは含まれていません。

* BlueXPの階層化
* Cloud Insights の機能です
* BlueXPバックアップ
* データガバナンス




== 既存システム用のONTAP One

現在NetAppのサポートを受けているが、ONTAP Oneにアップグレードされていない既存のシステムがある場合、これらのシステムの既存のライセンスは引き続き有効であり、期待どおりに機能します。たとえば、既存のシステムにSnapMirrorライセンスがすでにインストールされている場合、ONTAP ONEにアップグレードして新しいSnapMirrorライセンスを取得する必要はありません。ただし、既存のシステムにSnapMirrorライセンスがインストールされていない場合は、追加料金でONTAP ONEにアップグレードするしかありません。

2023年6月以降、28文字のライセンスキー（LICKEY）を使用するONTAPシステムでは、ONTAP ONEまたはONTAP Base互換バンドルへのアップグレードを要求できます。



== ONTAP Baseに含まれるライセンス

ONTAP Baseは、ONTAPシステム用のONTAP Oneに代わるオプションのソフトウェアスイートです。専用のテスト環境や開発環境に対応した非本番システムなど、SnapMirrorやSnapCenterなどのデータ保護テクノロジや、Autonomous Ransomwareなどのセキュリティ機能が不要な特定のユースケースを対象としています。ONTAP Baseにライセンスを追加することはできません。SnapMirrorなどの追加ライセンスが必要な場合は、ONTAP ONEにアップグレードする必要があります。

|===


| 以前のバンドル名 | ONTAP Oneキー付属 


.5+| Core Bundle | FlexClone 


| SnapRestore 


| NFS、SMB、S3 


| FC、iSCSI 


| NVMe-oF 


.3+| 暗号化バンドル | NetApp Volume Encryption の略 


| Trusted Platformモジュール 


| 保存データの暗号化 
|===


== その他のライセンス提供方法

ONTAP ONTAP 9.9.1では、ライセンスキーは28文字の文字列として提供され、ONTAP 機能ごとに1つのキーがあります。
