---
permalink: system-admin/manage-cluster-time-concept.html 
sidebar: sidebar 
keywords: manage, cluster, time, administrator, ntp, network, time, protocol, zone 
summary: クラスタ時間が不正確だと問題が発生する可能性があります。ONTAP ではクラスタのタイムゾーン、日付、時刻を手動で設定できますが、クラスタ時間を同期する場合はネットワークタイムプロトコル（ NTP ）サーバを設定する必要があります。 
---
= クラスタ時間の管理（クラスタ管理者のみ）
:icons: font
:imagesdir: ../media/


[role="lead"]
クラスタ時間が不正確だと問題が発生する可能性があります。ONTAP ではクラスタのタイムゾーン、日付、時刻を手動で設定できますが、クラスタ時間を同期する場合はネットワークタイムプロトコル（ NTP ）サーバを設定する必要があります。

ONTAP 9.5 以降では、対称認証を使用して NTP サーバを設定できます。

NTP は常に有効です。ただし、クラスタを外部の時間ソースと同期するには、引き続き設定が必要です。ONTAP では、次の方法でクラスタの NTP 設定を管理できます。

* 最大 10 台の外部 NTP サーバをクラスタに関連付けることができます（「 cluster time-service ntp server create 」）。
+
** タイムサービスの冗長性と品質を高めるためには、最低 3 台の外部 NTP サーバをクラスタに関連付ける必要があります。
** NTP サーバは、 IPv4 または IPv6 アドレス、あるいは完全修飾ホスト名を使用して指定できます。
** 使用する NTP バージョン（ v3 または v4 ）を手動で指定できます。
+
デフォルトでは、 ONTAP は指定された外部 NTP サーバでサポートされている NTP バージョンを自動的に選択します。

+
指定した NTP バージョンが NTP サーバでサポートされていない場合は、時間を同期できません。

** advanced 権限レベルでは、クラスタに関連付けられている外部 NTP サーバを、クラスタ時間を修正、調整するための主要時間ソースとして指定できます。


* クラスタに関連付けられている NTP サーバを表示できます（ cluster time-service ntp server show ）。
* クラスタの NTP 設定を変更できます（ cluster time-service ntp server modify ）。
* クラスタと外部 NTP サーバの関連付けを解除できます（「 cluster time-service ntp server delete 」）。
* advanced 権限レベルでは、クラスタに関連付けられているすべての外部 NTP サーバをクリアすることで、設定をリセットできます（「 cluster time-service ntp server reset 」）。


クラスタを統合しているノードは、自動的にクラスタの NTP 設定を取り込みます。

ONTAP では、 NTP を使用できるだけでなく、クラスタ時間を手動で管理できます。この機能は、間違った時間を修正する場合に便利です（リブート後にノードの時間が著しくずれた場合など）。その場合は、 NTP が外部の時間サーバと同期できるようになるまで、クラスタのおおよその時間を指定します。手動で設定した時間は、クラスタ上のすべてのノードに反映されます。

クラスタ時間を手動で管理するには、次の方法があります。

* クラスタのタイム・ゾーン ' 日付 ' 時刻を設定または変更できます（ cluster date modify ）
* クラスタの現在のタイム・ゾーン、日付、および時刻設定を表示できます（ cluster date show ）。


[NOTE]
====
手動でのクラスタの日付や時刻変更は、ジョブスケジュールには反映されません。ジョブは、ジョブが作成された時点または最後に実行された時点のクラスタの時刻に基づいて実行されます。したがって、クラスタの日付または時刻を手動で変更する場合は、「 job show 」コマンドおよび「 job history show 」コマンドを使用して、スケジュール済みのすべてのジョブが必要に応じてキューに格納され、完了していることを確認する必要があります。

====