---
permalink: system-admin/manage-licenses-concept.html 
sidebar: sidebar 
keywords: manage, license, enable, add, record, software, entitlement, keys, codes, risk, usage, cluster, administrator, nlf 
summary: ライセンスには、ソフトウェアの使用権が 1 つ以上記録されています。ONTAP 8.2 から ONTAP 9.9.8.1 では、ライセンスは 28 文字の文字列として提供され、 ONTAP 機能ごとに 1 つのキーがあります。ネットアップライセンスファイル（ NLF ）と呼ばれる新しいライセンス形式が、 FabricPool などのクラスタ全体の機能のみを対象に ONTAP 9.2 で導入されました。 
---
= ライセンスの管理の概要（クラスタ管理者のみ）
:icons: font
:imagesdir: ../media/


[role="lead"]
ライセンスには、ソフトウェアの使用権が 1 つ以上記録されています。ONTAP 8.2 から ONTAP 9.9.8.1 では、ライセンスキーは 28 文字の文字列として提供され、 ONTAP 機能ごとに 1 つのキーが存在します。ネットアップライセンスファイル（ NLF ）と呼ばれる新しいライセンスキー形式が、 FabricPool などのクラスタ全体の機能に対してのみ ONTAP 9.2 で導入されました。

ONTAP 9.10.1 以降、すべてのライセンスが NLF として提供されるようになりました。NLF ライセンスでは、購入内容に応じて、 1 つ以上の ONTAP 機能を有効にできます。ネットアップサポートサイトから NLF ライセンスを取得するには、システム（コントローラ）のシリアル番号を検索します。

初回購入のソフトウェアまたはアドオンソフトウェアのライセンスは、ネットアップサポートサイトの「 * My Support * > * Software Licenses * 」にあります（ログインが必要です）。Software Licenses ページにライセンスキーが表示されない場合は、営業またはサポート担当者にお問い合わせください。

ONTAP では、次の方法で機能ライセンスを管理できます。

* インストールされているライセンスに関する情報を表示する（「 system license show 」）
* ライセンスが必要なパッケージと、クラスタ上でのそのパッケージの現在のライセンスステータスを表示する（「 system license status show 」）
* シリアル番号を指定してクラスタまたはノードからライセンスを削除する（「 system license delete 」）
* 期限切れのライセンスまたは未使用のライセンスを表示または削除する（「システムライセンスのクリーンアップ」）


ONTAP では、次の方法で機能の使用状況やライセンス使用権のリスクを監視できます。

* クラスタでの機能の使用状況の概要をノード単位で表示する（「 system feature-usage show-summary 」）
+
この概要には、機能の使用週数、機能の最後の使用日時などのカウンタ情報が含まれます。

* クラスタでの機能の使用ステータスをノード単位および週単位で表示する（「 system feature-usage show-history 」）
+
機能の使用状況は、「 not-used 」、「 configured 」、「 in-use 」のいずれかになります。使用状況の情報がない場合は ' ステータスには利用不可と表示されます

* 各ライセンスパッケージのライセンス使用権リスクのステータスを表示します（ 'system license entitlement-risk show' ）
+
リスクステータスは、「 low 」、「 medium 」、「 high 」、「 unlicensed 」、「 unknown 」のいずれかです。リスクステータスは AutoSupport メッセージにも含まれます。ライセンス使用権のリスクは基本ライセンスパッケージには該当しません。

+
ライセンス使用権のリスクは、次に挙げるような複数の要因に基づいて評価されます。

+
** 各パッケージのライセンスの状態
** 各ライセンスのタイプと有効期限ステータス、およびクラスタ全体でのライセンスの統一性
** ライセンスパッケージに関連付けられている機能の使用状況評価プロセスでクラスタにライセンス使用権のリスクがあると判断された場合、推奨される対処方法も出力されます。




[NOTE]
====
注： ONTAP 9.10.1 では、 System Manager または CLI を使用する 28 文字のライセンスキーもサポートされます。ただし、 1 つの機能に NLF ライセンスがインストールされている場合、同じ機能に対して 28 文字のライセンスキーを NLF ライセンス経由でインストールすることはできません。System Manager を使用して NLF またはライセンスキーをインストールする方法については、「新機能を有効にする」を参照してください。

====
https://kb.netapp.com/Advice_and_Troubleshooting/Data_Storage_Software/ONTAP_OS/What_are_Data_ONTAP_8.2_and_8.3_licensing_overview_and_references%3F["Data ONTAP 8.2 および 8.3 のライセンスの概要とリファレンスを教えてください。"]

https://kb.netapp.com/Advice_and_Troubleshooting/Data_Storage_Software/ONTAP_OS/How_to_verify_Data_ONTAP_Software_Entitlements_and_related_License_Keys_using_the_Support_Site["サポートサイトを使用して、 Data ONTAP ソフトウェアのエンタイトルメントと関連するライセンスキーを検証する方法"]

https://kb.netapp.com/Advice_and_Troubleshooting/Data_Storage_Software/ONTAP_OS/FAQ%3A_Licensing_updates_in_Data_ONTAP_9.2["FAQ ： Data ONTAP 9.2 のライセンスに関する更新情報"]

http://mysupport.netapp.com/licensing/ontapentitlementriskstatus["ネットアップ： Data ONTAP Entitlement Risk Status"]
