---
permalink: system-admin/manage-autosupport-concept.html 
sidebar: sidebar 
keywords: manage, autosupport, support, technical, message 
summary: AutoSupportは、システムヘルスをプロアクティブに監視し、NetAppテクニカルサポート、社内のサポート部門、およびサポートパートナーにメッセージを自動的に送信するメカニズムです。テクニカルサポートへのAutoSupportメッセージの送信はデフォルトで有効になりますが、メッセージを社内のサポート部門に送信するには、適切なオプションを設定し、有効なメールホストを指定する必要があります。 
---
= ONTAP AutoSupportの詳細
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
AutoSupportは、システムヘルスをプロアクティブに監視し、NetAppテクニカルサポート、社内のサポート部門、およびサポートパートナーにメッセージを自動的に送信するメカニズムです。テクニカルサポートへのAutoSupportメッセージの送信はデフォルトで有効になりますが、メッセージを社内のサポート部門に送信するには、適切なオプションを設定し、有効なメールホストを指定する必要があります。

AutoSupport管理を実行できるのはクラスタ管理者だけです。Storage Virtual Machine（SVM）管理者にはAutoSupportへのアクセス権はありません。

AutoSupportは、ストレージシステムの初回設定時にデフォルトで有効になります。AutoSupportは、AutoSupportが有効になってから24時間後にテクニカルサポートへのメッセージ送信を開始します。この24時間を短縮するには、システムをアップグレードまたはリバートするか、AutoSupport設定を変更するか、システム時間を24時間以外に変更します。

[NOTE]
====
AutoSupportはいつでも無効にできますが、有効のままにしておく必要があります。AutoSupportを有効にすると、ストレージシステムに問題が発生した場合に、迅速に原因を特定して解決することができます。デフォルトでは、AutoSupportを無効にした場合でも、AutoSupportの情報が収集されてローカルに格納されます。

====
AutoSupportの詳細については、NetAppサポートサイトを参照してください。

.関連情報
* https://support.netapp.com/["NetAppのサポート"^]
* link:../concepts/manual-pages.html["ONTAPコマンド リファレンス"]

