---
permalink: system-admin/manage-web-services-concept.html 
sidebar: sidebar 
keywords: manage, web, services, svm, storage, virtual, machine, cluster, controler, user 
summary: クラスタまたは Storage Virtual Machine （ SVM ）の Web サービスを有効または無効にしたり、 Web サービスの設定を表示したり、ロールのユーザが Web サービスにアクセスできるかどうかを管理したりできます。 
---
= Manage Web Services の概要
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
クラスタまたは Storage Virtual Machine （ SVM ）の Web サービスを有効または無効にしたり、 Web サービスの設定を表示したり、ロールのユーザが Web サービスにアクセスできるかどうかを管理したりできます。

クラスタまたは SVM の Web サービスは次の方法で管理できます。

* 特定の Web サービスを有効または無効にします
* Web サービスへのアクセスを暗号化された HTTP （ SSL ）のみに制限するかどうかを指定する
* Web サービスの可用性を表示します
* あるロールのユーザに Web サービスへのアクセスを許可するかどうか
* Web サービスへのアクセスが許可されているロールを表示する


ユーザが Web サービスにアクセスするには、次の条件をすべて満たしている必要があります。

* ユーザが認証されている必要があります。
+
たとえば、 Web サービスからユーザ名とパスワードの入力を求められる場合があります。ユーザの応答は有効なアカウントと一致する必要があります。

* ユーザに正しいアクセス方法が設定されていること。
+
指定された Web サービスの正しいアクセス方法が設定されたユーザのみが正常に認証されます。ONTAP API Webサービス用  `ontapi`）を使用する場合は、を使用する必要があります `ontapi` アクセス方法。その他のすべてのWebサービスの場合は、が必要です `http` アクセス方法。

+
[NOTE]
====
を使用します `security login` ユーザのアクセス方法と認証方法を管理するコマンド。

====
* Web サービスがユーザのアクセス制御ロールを許可するように設定されている必要があります。
+
[NOTE]
====
を使用します `vserver services web access` ロールのWebサービスへのアクセスを制御するコマンド。

====


ファイアウォールが有効になっている場合は、 Web サービスに使用する LIF のファイアウォールポリシーを設定して、 HTTP または HTTPS を許可する必要があります。

Web サービスアクセスに HTTPS を使用する場合は、 Web サービスを提供するクラスタまたは SVM の SSL を有効にし、そのクラスタまたは SVM のデジタル証明書を提供する必要もあります。
