---
permalink: system-admin/manage-autosupport-concept.html 
sidebar: sidebar 
keywords: manage, autosupport, support, technical, message 
summary: AutoSupport は、システムヘルスをプロアクティブに監視し、ネットアップテクニカルサポート、社内のサポート部門、およびサポートパートナーにメッセージを自動的に送信します。テクニカルサポートへの AutoSupport メッセージの送信はデフォルトで有効になりますが、メッセージを社内のサポート部門に送信する場合は、適切なオプションを設定し、有効なメールホストを指定する必要があります。 
---
= Manage AutoSupport の概要
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
AutoSupport は、システムヘルスをプロアクティブに監視し、ネットアップテクニカルサポート、社内のサポート部門、およびサポートパートナーにメッセージを自動的に送信します。テクニカルサポートへの AutoSupport メッセージの送信はデフォルトで有効になりますが、メッセージを社内のサポート部門に送信する場合は、適切なオプションを設定し、有効なメールホストを指定する必要があります。

AutoSupport 管理を実行できるのはクラスタ管理者だけです。Storage Virtual Machine （ SVM ）管理者には AutoSupport へのアクセス権はありません。

AutoSupport は、ストレージシステムの初回設定時にデフォルトで有効になります。AutoSupport は、 AutoSupport が有効になってから 24 時間後にテクニカルサポートへのメッセージ送信を開始します。この間隔を 24 時間よりも短くするには、システムをアップグレードまたはリバートするか、 AutoSupport 設定を変更するか、システムの時間を 24 時間以外の時間に変更します。

[NOTE]
====
AutoSupport はいつでも無効にできますが、常に有効にしておく必要があります。AutoSupport を有効にしておくと、ストレージ・システムに問題が発生したときに、迅速に原因を判断し解決できます。デフォルトでは、 AutoSupport を無効にした場合でも、 AutoSupport の情報が収集されてローカルに格納されます。

====
AutoSupport の詳細については、NetApp Support Siteを参照してください。

.関連情報
* https://support.netapp.com/["ネットアップサポート"^]
* http://docs.netapp.com/ontap-9/topic/com.netapp.doc.dot-cm-cmpr/GUID-5CB10C70-AC11-41C0-8C16-B4D0DF916E9B.html["ONTAP コマンドの詳細については、 AutoSupport の CLI を参照してください"^]

