---
permalink: system-admin/manage-licenses-concept.html 
sidebar: sidebar 
keywords: manage, license, ontap one, enable, add, record, software, entitlement, keys, codes, risk, usage, cluster, administrator, nlf 
summary: ライセンスには、ソフトウェアの使用権が 1 つ以上記録されています。ONTAP 9.10.1以降では、すべてのライセンスがNetAppライセンスファイル（NLF）として提供されます。これは、複数の機能を有効にする単一のファイルです。  2023年5月以降、すべてのAFFシステム（AシリーズとCシリーズの両方）とFASシステムは、ONTAP ONEソフトウェアスイートまたはONTAP Baseソフトウェアスイートのいずれかとともに販売され、2023年6月以降は、すべてのASAシステムがONTAP ONE for SANとともに販売されます。 
---
= ONTAPライセンスの概要
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
ライセンスには、ソフトウェアの使用権が 1 つ以上記録されています。ONTAP 9.10.1以降では、すべてのライセンスがNetAppライセンスファイル（NLF）として提供されます。これは、複数の機能を有効にする単一のファイルです。  2023年5月以降、すべてのAFFシステム（AシリーズとCシリーズの両方）とFASシステムは、ONTAP ONEソフトウェアスイートまたはONTAP Baseソフトウェアスイートのいずれかとともに販売され、2023年6月以降は、すべてのASAシステムがONTAP ONE for SANとともに販売されます。各ソフトウェアスイートは単一のNLFとして提供され、ONTAP 9.10.1で最初に導入された個別のNLFバンドルを置き換えます。



== ONTAP Oneに含まれるライセンス

ONTAP Oneには、使用可能なライセンス機能がすべて含まれています以前のCore Bundle、Data Protection Bundle、Security and Compliance Bundle、Hybrid Cloud Bundle、Encryption Bundleの内容が次の表にまとめられています。暗号化は制限された国では使用できません。

|===


| 以前のバンドル名 | 含まれるONTAPキー 


.5+| Core Bundle | FlexClone 


| SnapRestore 


| NFS、SMB、S3 


| FC、iSCSI 


| NVMe-oF 


.3+| Security and Compliance Bundle | 自律的なランサムウェア防御 


| MTKM 


| SnapLock 


.3+| Data Protection Bundle | SnapMirror（非同期、同期、ビジネス継続性） 


| SnapCenter 


| NetAppターゲット用のSnapMirror S3 


.2+| Hybrid Cloud Bundle | SnapMirrorクラウド 


| NetApp以外のターゲット用のSnapMirror S3 


.2+| 暗号化バンドル | NetApp Volume Encryption の略 


| Trusted Platformモジュール 
|===


== ONTAP Oneに含まれていないライセンス

ONTAP Oneには、以下を含むネットアップのクラウド提供サービスは含まれていません。

* BlueXPの階層化
* Cloud Insights の機能です
* BlueXPバックアップ
* データガバナンス




== 既存システム用のONTAP One

現在NetAppのサポートを受けているが、ONTAP Oneにアップグレードされていない既存のシステムがある場合、これらのシステムの既存のライセンスは引き続き有効であり、期待どおりに機能します。たとえば、既存のシステムにSnapMirrorライセンスがすでにインストールされている場合、ONTAP ONEにアップグレードして新しいSnapMirrorライセンスを取得する必要はありません。ただし、既存のシステムにSnapMirrorライセンスがインストールされていない場合は、追加料金でONTAP ONEにアップグレードするしかありません。

2023年6月以降、28文字のライセンスキーを使用するONTAPシステムでも、 link:https://kb.netapp.com/onprem/ontap/os/How_to_get_an_ONTAP_One_license_when_the_system_has_28_character_keys["ONTAP OneまたはONTAP Base互換性バンドルへのアップグレード"]。



== ONTAP Baseに含まれるライセンス

ONTAP Baseは、ONTAPシステム用のONTAP Oneに代わるオプションのソフトウェアスイートです。専用のテスト環境や開発環境に対応した非本番システムなど、SnapMirrorやSnapCenterなどのデータ保護テクノロジや、Autonomous Ransomwareなどのセキュリティ機能が不要な特定のユースケースを対象としています。ONTAP Baseにライセンスを追加することはできません。SnapMirrorなどの追加ライセンスが必要な場合は、ONTAP ONEにアップグレードする必要があります。

|===


| 以前のバンドル名 | 含まれるONTAPキー 


.5+| Core Bundle | FlexClone 


| SnapRestore 


| NFS、SMB、S3 


| FC、iSCSI 


| NVMe-oF 


.2+| 暗号化バンドル | NetApp Volume Encryption の略 


| Trusted Platformモジュール 
|===


== ONTAP One for SANに含まれるライセンス

ONTAP One for SANは、ASA AシリーズおよびCシリーズのシステムで使用できます。SANで使用できる唯一のソフトウェアスイートです。ONTAP One for SANには、次のライセンスが含まれています。

|===


| 含まれるONTAPキー 


| FlexClone 


| SnapRestore 


| FC、iSCSI 


| NVMe-oF 


| MTKM 


| SnapLock 


| SnapMirror（非同期、同期、ビジネス継続性） 


| SnapCenter 


| SnapMirrorクラウド 


| NetApp Volume Encryption の略 


| Trusted Platformモジュール 
|===


== その他のライセンス提供方法

ONTAP ONTAP 9.9.1では、ライセンスキーは28文字の文字列として提供され、ONTAP 機能ごとに1つのキーがあります。ONTAP ONTAP 9.9.1を使用している場合は、ONTAP CLIを使用してライセンスキーをインストールします。

[NOTE]
====
ONTAP 9.10.1では、System ManagerまたはCLIを使用した28文字のライセンスキーのインストールがサポートされています。ただし、機能用にNLFライセンスがインストールされている場合、同じ機能用のNetAppライセンスファイルに28文字のライセンスキーをインストールすることはできません。System Managerを使用したNLFまたはライセンスキーのインストールについては、を参照してください。 link:https://docs.netapp.com/us-en/ontap/system-admin/install-license-task.html["ONTAPライセンスのインストール"]。

====
.関連情報
https://kb.netapp.com/onprem/ontap/os/How_to_get_an_ONTAP_One_license_when_the_system_has_NLFs_already["システムにすでにNLFがある場合にONTAP Oneライセンスを取得する方法"]

https://kb.netapp.com/Advice_and_Troubleshooting/Data_Storage_Software/ONTAP_OS/How_to_verify_Data_ONTAP_Software_Entitlements_and_related_License_Keys_using_the_Support_Site["サポートサイトを使用してONTAPソフトウェアの使用権と関連ライセンスキーを確認する方法"^]

http://mysupport.netapp.com/licensing/ontapentitlementriskstatus["NetApp：ONTAP使用権リスクステータス"^]
