---
permalink: system-admin/manage-core-dumps-concept.html 
sidebar: sidebar 
keywords: manage, core, dump, cluster, administrator, node, panic, configure, attributes, save, display, segment, upload, delete 
summary: ノード コア ダンプの属性を設定または表示し、ノード コア ダンプ ファイルを管理できます。 
---
= ONTAPクラスタのノード コア ダンプを管理する（クラスタ管理者のみ）
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
ノードに何らかの障害が発生すると、コア ダンプが発生し、システムによってコア ダンプ ファイルが作成されます。テクニカル サポートはこのファイルを問題解決に使用できます。コア ダンプの属性は、設定または表示できます。また、コア ダンプ ファイルは保存、表示、分割、アップロード、または削除できます。

コア ダンプ ファイルは、次の方法で管理できます。

* コア ダンプの設定および設定の表示
* コア ダンプの基本情報、ステータス、および属性の表示
+
コアダンプファイルとレポートは、ノードの `/mroot/etc/crash/`ディレクトリに保存されます。 `system node coredump`コマンドまたはWebブラウザを使用して、ディレクトリの内容を表示できます。

* コア ダンプの内容の保存と、指定された場所またはテクニカル サポートへの保存済みファイルのアップロード
+
ONTAPでは、テイクオーバー、アグリゲートの再配置、またはギブバック中にコア ダンプ ファイルの保存を開始することはできません。

* 必要がなくなったコア ダンプ ファイルの削除




== コア ダンプの管理用コマンド

 `system node coredump config`コマンドを使用してコア ダンプの構成を管理し、 `system node coredump`コマンドを使用してコア ダンプ ファイルを管理し、 `system node coredump reports`コマンドを使用してアプリケーション コア レポートを管理します。

このトピックで説明されているコマンドの詳細については、link:https://docs.netapp.com/us-en/ontap-cli/["ONTAPコマンド リファレンス"]を参照してください。

|===
| 状況 | 使用するコマンド 


 a| 
コア ダンプを設定する
 a| 
`system node coredump config modify`



 a| 
コア ダンプの構成設定を表示する
 a| 
`system node coredump config show`



 a| 
コア ダンプに関する基本情報を表示する
 a| 
`system node coredump show`



 a| 
ノードをリブートする際にコア ダンプを手動でトリガーする
 a| 
`system node reboot` `-dump`と `-skip-lif-migration-before-reboot`パラメータの両方を使用

[NOTE]
====
https://docs.netapp.com/us-en/ontap-cli//system-node-reboot.html#parameters[`skip-lif-migration-before-reboot`^] パラメータは、再起動前の LIF 移行をスキップすることを指定します。

====


 a| 
ノードをシャットダウンする際にコア ダンプを手動でトリガーする
 a| 
`system node halt` `-dump`と `-skip-lif-migration-before-shutdown`パラメータの両方を使用

[NOTE]
====
https://docs.netapp.com/us-en/ontap-cli/system-node-halt.html#parameters[`skip-lif-migration-before-shutdown`^] パラメータは、シャットダウン前の LIF 移行をスキップすることを指定します。

====


 a| 
指定したコア ダンプを保存する
 a| 
`system node coredump save`



 a| 
指定したノード上で保存されていないすべてのコア ダンプを保存する
 a| 
`system node coredump save-all`



 a| 
AutoSupportメッセージを生成し、指定したコア ダンプ ファイルと一緒に送信する
 a| 
`system node autosupport invoke-core-upload`

[NOTE]
====
 `-uri`オプション パラメータは、AutoSupportメッセージの代替の宛先を指定します。

====


 a| 
コア ダンプに関するステータス情報を表示する
 a| 
`system node coredump status`



 a| 
指定したコア ダンプを削除する
 a| 
`system node coredump delete`



 a| 
ノード上で保存されていないすべてのコア ダンプ、または保存されているすべてのコア ファイルを削除する
 a| 
`system node coredump delete-all`



 a| 
アプリケーション コア ダンプ レポートを表示する
 a| 
`system node coredump reports show`



 a| 
アプリケーション コア ダンプ レポートを削除する
 a| 
`system node coredump reports delete`

|===
.関連情報
link:../concepts/manual-pages.html["ONTAPコマンド リファレンス"]
