---
permalink: system-admin/manage-banner-reference.html 
sidebar: sidebar 
keywords: manage, banner, svm, cluster, configure 
summary: バナーはクラスタレベルまたは SVM レベルで管理できます。クラスタ用に設定したバナーは、バナーメッセージが定義されていない SVM に対しても表示されます。以降に SVM 用のバナーを作成すると、その SVM に対しては、クラスタ用のバナーではなくそのバナーが表示されます。 
---
= バナーの管理
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
バナーはクラスタレベルまたは SVM レベルで管理できます。クラスタ用に設定したバナーは、バナーメッセージが定義されていない SVM に対しても表示されます。以降に SVM 用のバナーを作成すると、その SVM に対しては、クラスタ用のバナーではなくそのバナーが表示されます。

.選択肢
* クラスタレベルのバナーの管理タスクを次に示します。
+
|===
| 状況 | 作業 


 a| 
すべての CLI ログインセッションに対して表示するバナーを作成します
 a| 
クラスタレベルのバナーを設定します。

`*security login banner modify -vserver _cluster_name_ { [-message "text"] | [_-uri ftp_or_http_addr_] }*`



 a| 
すべてのログイン（クラスタと SVM の両方）に対するバナーを削除する
 a| 
バナーを空の文字列に設定します (`""`）：

`*security login banner modify -vserver * -message ""*`



 a| 
SVM 管理者が作成したバナーを変更する
 a| 
SVM のバナーメッセージを変更します。

`*security login banner modify -vserver _svm_name_ { [-message "_text_"] | [-uri _ftp_or_http_addr_] }*`

|===
* SVM レベルのバナーの管理タスクを次に示します。
+
を指定します `-vserver _svm_name_` SVMのコンテキストでは必要ありません。

+
|===
| 状況 | 作業 


 a| 
クラスタ管理者が指定したバナーの代わりに SVM 用の別のバナーを表示する
 a| 
SVM 用のバナーを作成します。

`*security login banner modify -vserver _svm_name_ { [-message "text"] | [-uri ftp_or_http_addr] }*`



 a| 
クラスタ管理者が指定したバナーも含め、いずれのバナーも SVM に対して表示されないようにする
 a| 
SVM のバナーを空の文字列に設定します。

`*security login banner modify -vserver _svm_name_ -message ""*`



 a| 
現在 SVM レベルのバナーを使用している SVM でクラスタレベルのバナーを使用している場合
 a| 
SVMのバナーをに設定します `"-"`：

`*security login banner modify -vserver _svm_name_ -message "-"*`

|===

