---
permalink: system-admin/manage-motd-reference.html 
sidebar: sidebar 
keywords: manage, motd, message, day, cluster, svm, administrator 
summary: Message Of The Day（MOTD）はクラスタレベルまたはSVMレベルで管理できます。クラスタに設定したMOTDは、デフォルトですべてのSVMに対しても有効になります。さらに、SVMごとにSVMレベルのMOTDを設定できます。クラスタレベルのMOTDは、クラスタ管理者が各SVMに対して有効または無効にできます。 
---
= ONTAPクラスタレベルおよびSVMレベルで表示されるMessage-of-The-Dayテキストを管理します。
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Message Of The Day（MOTD）はクラスタレベルまたはSVMレベルで管理できます。クラスタに設定したMOTDは、デフォルトですべてのSVMに対しても有効になります。さらに、SVMごとにSVMレベルのMOTDを設定できます。クラスタレベルのMOTDは、クラスタ管理者が各SVMに対して有効または無効にできます。

MOTDのコンテンツを動的に生成するために使用できるの詳細についてはlink:https://docs.netapp.com/us-en/ontap-cli//security-login-motd-modify.html#parameters["エスケープシーケンス"^]、ONTAPのコマンドリファレンスを参照してください。

.選択肢
* クラスタレベルでMOTDを管理します。
+
|===
| 状況 | そしたら...。 


 a| 
既存のMOTDがない場合にすべてのログインに対するMOTDを作成する
 a| 
クラスタレベルのMOTDを設定します。

`security login motd modify -vserver <cluster_name> { [-message "<text>"] | [-uri <ftp_or_http_addr>] }`



 a| 
SVMレベルのMOTDが設定されていない場合にすべてのログインに対するMOTDを変更する
 a| 
クラスタレベルのMOTDを変更します。

`security login motd modify -vserver <cluster_name> { [-message "<text>"] } | [-uri <ftp_or_http_addr>] }`



 a| 
SVMレベルのMOTDが設定されていない場合にすべてのログインに対するMOTDを削除する
 a| 
クラスタレベルのMOTDを空の文字列に設定し(`""`ます）。

`security login motd modify -vserver <cluster_name> -message ""`



 a| 
すべてのSVMで、SVMレベルのMOTDを使用するのではなく、クラスタレベルのMOTDを表示する
 a| 
クラスタレベルのMOTDを設定してから、SVMレベルのすべてのMOTDを空の文字列に設定し、クラスタレベルのMOTDを有効にします。

.. `security login motd modify -vserver <cluster_name> { [-message "<text>"] | [-uri <ftp_or_http_addr>] }`
.. `security login motd modify { -vserver !"<cluster_name>" } -message "" -is-cluster-message-enabled true`




 a| 
クラスタレベルのMOTDを使用せずに、選択したSVMについてのみMOTDを表示する
 a| 
クラスタレベルのMOTDを空の文字列に設定し、選択したSVMに対するSVMレベルのMOTDを設定します。

.. `security login motd modify -vserver <cluster_name> -message ""`
.. `security login motd modify -vserver <svm_name> { [-message "<text>"] | [-uri <ftp_or_http_addr>] }`
+
この手順は、必要に応じてSVMごとに繰り返すことができます。





 a| 
すべてのSVM（データと管理）に対して同じSVMレベルのMOTDを使用する
 a| 
同じMOTDを使用するようにクラスタとすべてのSVMを設定します。

`security login motd modify -vserver * { [-message "<text>"] | [-uri <ftp_or_http_addr>] }`

[NOTE]
====
CLIの対話型モードでは、クラスタと各SVMについてMOTDを個別に入力するように求められます。プロンプトが表示されたら、各インスタンスに同じMOTDを貼り付けることができます。

====


 a| 
クラスタレベルのMOTDをすべてのSVMで必要に応じて表示できるようにし、クラスタログイン時に表示されないようにする
 a| 
クラスタレベルのMOTDを設定し、クラスタに対する表示を無効にします。

`security login motd modify -vserver <cluster_name> { [-message "<text>"] | [-uri <ftp_or_http_addr>] } -is-cluster-message-enabled false`



 a| 
一部のSVMだけでクラスタレベルとSVMレベルの両方のMOTDが設定されている場合は、クラスタレベルとSVMレベルのすべてのMOTDを削除する
 a| 
MOTDに空の文字列を使用するようにクラスタとすべてのSVMを設定します。

`security login motd modify -vserver * -message ""`



 a| 
他のSVMで空の文字列が使用されている場合、およびクラスタレベルで別のMOTDが使用されている場合にのみ、文字列が空でないSVMのMOTDを変更する
 a| 
拡張クエリを使用して選択したMOTDを変更します。

`security login motd modify { -vserver !"<cluster_name>" -message !"" } { [-message "<text>"] | [-uri <ftp_or_http_addr>] }`



 a| 
単一行または複数行のメッセージ内の任意の場所に特定のテキスト（たとえば、「January」の後に「2015」が続く）を含むすべての MOTD を表示します（テキストが複数の行に分割されている場合でも）。
 a| 
クエリを使用してMOTDを表示します。

[listing]
----
security login motd show -message *"January"*"2015"*
----


 a| 
複数の連続する改行（EOL）を含むMOTDを対話型モードで作成する
 a| 
対話型モードでは、スペースバーを押してからEnterキーを押して、MOTDの入力を終了せずに空白行を作成します。

|===
* SVMレベルのMOTDを管理します。
+
SVMのコンテキストでは、を指定する `-vserver <svm_name>`必要はありません。

+
|===
| 状況 | そしたら...。 


 a| 
すでにSVMレベルのMOTDが設定されている場合は、別のSVMレベルのMOTDを使用する
 a| 
SVMレベルのMOTDを変更します。

`security login motd modify -vserver <svm_name> { [-message "<text>"] | [-uri <ftp_or_http_addr>] }`



 a| 
すでにSVMレベルのMOTDが設定されている場合は、SVMでクラスタレベルのMOTDのみを使用する
 a| 
SVMレベルのMOTDを空の文字列に設定し、そのSVMに対してクラスタレベルのMOTDを有効にするようにクラスタ管理者に依頼します。

.. `security login motd modify -vserver <svm_name> -message ""`
.. （クラスタ管理者） `security login motd modify -vserver <svm_name> -is-cluster-message-enabled true`




 a| 
現在クラスタレベルとSVMレベルの両方のMOTDが表示されているSVMに対して、SVMにどのMOTDも表示されないようにする
 a| 
SVMレベルのMOTDを空の文字列に設定し、そのSVMに対してクラスタレベルのMOTDを無効にするようにクラスタ管理者に依頼します。

.. `security login motd modify -vserver <svm_name> -message ""`
.. （クラスタ管理者） `security login motd modify -vserver <svm_name> -is-cluster-message-enabled false`


|===


.関連情報
* link:https://docs.netapp.com/us-en/ontap-cli/security-login-motd-modify.html["security login motd modify のように変更します"^]
* link:https://docs.netapp.com/us-en/ontap-cli/security-login-motd-show.html["security login motd showのコマンドを使用します"^]

