---
permalink: system-admin/manage-ssl-concept.html 
sidebar: sidebar 
keywords: manage, command, ssl, cluster, storage, svm, security, web, access, digital, certificate, encrypted, connection, server, browser 
summary: ssl コマンドを使用して SSL プロトコルを管理し、デジタル証明書を使用して暗号化された接続を確立することで、Webアクセスのセキュリティを強化します。 
---
= ONTAPでのSSLの管理
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
 `security ssl`コマンドを使用して、クラスタまたはストレージ仮想マシン（SVM）のSSLプロトコルを管理します。SSLプロトコルは、デジタル証明書を使用してWebサーバーとブラウザ間の暗号化された接続を確立することで、Webアクセスのセキュリティを強化します。

クラスタまたはStorage Virtual Machine（SVM）のSSLは次の方法で管理できます。

* SSLを有効にする
* デジタル証明書を生成してインストールし、クラスタまたはSVMと関連付ける
* SSL設定を表示してSSLが有効かどうかを確認し、可能な場合はSSL証明書名を確認する
* クラスタまたはSVMのファイアウォール ポリシーを設定して、Webアクセス要求が通過できるようにする
* 使用できるSSLのバージョンを定義する
* WebサービスのHTTPS要求のみにアクセスを制限する




== SSLの管理用コマンド

 `security ssl`コマンドを使用して、クラスタまたはStorage Virtual Machine（SVM）のSSLプロトコルを管理します。

|===
| 状況 | 使用するコマンド 


 a| 
クラスタまたはSVMのSSLを有効にし、デジタル証明書と関連付ける
 a| 
`security ssl modify`



 a| 
クラスタまたはSVMのSSL設定と証明書名を表示する
 a| 
`security ssl show`

|===
 `security ssl modify`および `security ssl show`の詳細については、link:https://docs.netapp.com/us-en/ontap-cli/search.html?q=security+ssl["ONTAPコマンド リファレンス"^]をご覧ください。
