---
permalink: system-admin/manage-motd-reference.html 
sidebar: sidebar 
keywords: manage, motd, message, day, cluster, svm, administrator 
summary: Message Of The Day （ MOTD ）はクラスタレベルまたは SVM レベルで管理できます。クラスタ用に設定した MOTD は、デフォルトですべての SVM に対しても有効になります。また、 SVM ごとに SVM レベルの MOTD を設定できます。クラスタレベルの MOTD を有効にするか無効にするかは、クラスタ管理者が SVM ごとに設定できます。 
---
= MOTD を管理します
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Message Of The Day （ MOTD ）はクラスタレベルまたは SVM レベルで管理できます。クラスタ用に設定した MOTD は、デフォルトですべての SVM に対しても有効になります。また、 SVM ごとに SVM レベルの MOTD を設定できます。クラスタレベルの MOTD を有効にするか無効にするかは、クラスタ管理者が SVM ごとに設定できます。

MOTDの内容を動的に生成するために使用できるエスケープシーケンスのリストについては、を参照してください link:https://docs.netapp.com/us-en/ontap-cli-9141//security-login-motd-modify.html#parameters["コマンドリファレンス"]。

.選択肢
* クラスタレベルの MOTD の管理タスクを次に示します。
+
|===
| 状況 | 作業 


 a| 
既存の MOTD がない場合にすべてのログインに対する MOTD を作成する
 a| 
クラスタレベルの MOTD を設定します。

`*security login motd modify -vserver _cluster_name_ { [-message "_text_"] | [-uri _ftp_or_http_addr_] }*`



 a| 
SVM レベルの MOTD が設定されていない場合にすべてのログインに対する MOTD を変更する
 a| 
クラスタレベルの MOTD を変更します。

`*security login motd modify -vserver _cluster_name_ { [-message "_text_"] } | [-uri ftp_or_http_addr] }*`



 a| 
SVM レベルの MOTD が設定されていない場合にすべてのログインに対する MOTD を削除する
 a| 
クラスタレベルのMOTDを空の文字列に設定します (`""`）：

`*security login motd modify -vserver _cluster_name_ -message ""*`



 a| 
すべての SVM で、 SVM レベルの MOTD を使用する代わりに、クラスタレベルの MOTD を表示するように設定します
 a| 
クラスタレベルの MOTD を設定してから、 SVM レベルのすべての MOTD を空の文字列に設定し、クラスタレベルの MOTD を有効にします。

.. `*security login motd modify -vserver _cluster_name_ { [-message "_text_"] | [-uri _ftp_or_http_addr_] }*`
.. `*security login motd modify { -vserver !"_cluster_name_" } -message "" -is-cluster-message-enabled true*`




 a| 
クラスタレベルの MOTD を使用せずに、選択した SVM に対してのみ MOTD を表示する
 a| 
クラスタレベルの MOTD を空の文字列に設定し、選択した SVM に対する SVM レベルの MOTD を設定します。

.. `*security login motd modify -vserver _cluster_name_ -message ""*`
.. `*security login motd modify -vserver _svm_name_ { [-message "_text_"] | [-uri _ftp_or_http_addr_] }*`
+
この手順は、必要に応じて、各 SVM に対して繰り返し実行できます。





 a| 
すべての SVM （データと管理の両方）に対して同じ SVM レベルの MOTD を使用します
 a| 
同じ MOTD を使用するようにクラスタとすべての SVM を設定します。

`*security login motd modify _-vserver_ * { [-message "_text_"] | [-uri _ftp_or_http_addr_] }*`

[NOTE]
====
CLI の対話型モードでは、クラスタと各 SVM について MOTD を個別に入力するように求められます。それぞれのプロンプトに同じ MOTD を貼り付けることができます。

====


 a| 
クラスタレベルの MOTD をすべての SVM で必要に応じて表示できるようにし、クラスタログインに対しては表示されないようにする
 a| 
クラスタレベルの MOTD を設定し、クラスタに対する表示を無効にします。

`*security login motd modify -vserver _cluster_name_ { [-message "_text_"] | [-uri _ftp_or_http_addr_] } -is-cluster-message-enabled false*`



 a| 
一部の SVM のみクラスタレベルと SVM レベルの両方の MOTD が設定されている場合は、クラスタレベルと SVM レベルのすべての MOTD を削除します
 a| 
MOTD に空の文字列を使用するようにクラスタとすべての SVM を設定します。

`*security login motd modify -vserver * -message ""*`



 a| 
他の SVM で空の文字列が使用されている場合やクラスタレベルで別の MOTD が使用されている場合に、文字列が空でない SVM の MOTD だけを変更します
 a| 
拡張クエリを使用して選択した MOTD を変更します。

`*security login motd modify { -vserver !"_cluster_name_" -message !"" } { [-message "_text_"] | [-uri _ftp_or_http_addr_] }*`



 a| 
該当するテキストが複数行にまたがる場合でも、メッセージ内の任意の場所に特定のテキスト（「 January 」、「 2015 」など）を含むすべての MOTD を表示する
 a| 
クエリを使用して MOTD を表示します。

`*security login motd show -message *"January"\***"2015"**`



 a| 
複数の連続する改行（ EOL ）を含む MOTD を対話型モードで作成する
 a| 
対話型モードで、スペースキーのあとに続けて Enter キーを押します。 MOTD の入力を終了せずに空白行を入力できます。

|===
* SVM レベルの MOTD の管理タスクを次に示します。
+
を指定します `-vserver _svm_name_` SVMのコンテキストでは必要ありません。

+
|===
| 状況 | 作業 


 a| 
すでに SVM レベルの MOTD が設定された SVM で、別の SVM レベルの MOTD を使用します
 a| 
SVM レベルの MOTD を変更します。

`*security login motd modify -vserver _svm_name_ { [-message "_text_"] | [-uri _ftp_or_http_addr_] }*`



 a| 
すでに SVM レベルの MOTD が設定された SVM で、クラスタレベルの MOTD だけを使用します
 a| 
SVM レベルの MOTD を空の文字列に設定し、その SVM に対してクラスタレベルの MOTD を有効にするようにクラスタ管理者に依頼します。

.. `*security login motd modify -vserver _svm_name_ -message ""*`
.. （クラスタ管理者） `*security login motd modify -vserver _svm_name_ -is-cluster-message-enabled true*`




 a| 
現在クラスタレベルと SVM レベルの両方の MOTD が表示されている SVM で、いずれの MOTD も表示されないようにする
 a| 
SVM レベルの MOTD を空の文字列に設定し、その SVM に対してクラスタレベルの MOTD を無効にするようにクラスタ管理者に依頼します。

.. `*security login motd modify -vserver _svm_name_ -message ""*`
.. （クラスタ管理者） `*security login motd modify -vserver _svm_name_ -is-cluster-message-enabled false*`


|===

