---
permalink: system-admin/manage-jobs-schedules.html 
sidebar: sidebar 
keywords: job, categories, server, cluster, affiliated, private, commands, managing, show jobs, job schedule, stop a job, delete a job, pause a job, display private jobs, modify, cron, interval, delete, interval schedule, manage jobs and schedule, manage jobs, manage schedule 
summary: ジョブはジョブキューに配置され、リソースが使用可能になるとバックグラウンドで実行されます。ジョブで使用するクラスタリソースが多すぎる場合は、そのジョブを停止するか、クラスタに対する要求が少なくなるまで一時停止できます。ジョブを監視および再開することもできます。 
---
= ジョブとスケジュールの管理
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
ジョブはジョブキューに配置され、リソースが使用可能になるとバックグラウンドで実行されます。ジョブで使用するクラスタリソースが多すぎる場合は、そのジョブを停止するか、クラスタに対する要求が少なくなるまで一時停止できます。ジョブを監視および再開することもできます。



== ジョブのカテゴリ

管理できるジョブには、サーバ関連、クラスタ関連、およびプライベートの 3 つのカテゴリがあります。

ジョブは、次のいずれかのカテゴリに分類されます。

* * サーバ関連ジョブ *
+
このジョブは、実行する特定のノードに対して、管理フレームワークによってキューに登録されます。

* * クラスタ関連ジョブ *
+
このジョブは、実行するクラスタ内の任意のノードに対して、管理フレームワークによってキューに登録されます。

* * プライベートジョブ *
+
このジョブはノードに固有で、レプリケートされたデータベース（ RDB ）またはその他のクラスタメカニズムを使用しません。プライベートジョブの管理用コマンドには、 advanced 権限レベル以上が必要です。





== ジョブの管理用コマンド

あるジョブを呼び出すコマンドを入力すると、通常、ジョブがキューに登録されたことが通知され、 CLI のコマンドプロンプトに戻ります。ただし、一部のコマンドではジョブの進捗状況が表示され、ジョブが完了するまで CLI のコマンドプロンプトに戻りません。このような場合は、 Ctrl+C キーを押してジョブをバックグラウンドに移動できます。

|===
| 状況 | 使用するコマンド 


 a| 
すべてのジョブに関する情報を表示します
 a| 
`job show`



 a| 
ジョブに関する情報をノード単位で表示します
 a| 
`job show bynode`



 a| 
クラスタ関連ジョブに関する情報を表示します
 a| 
`job show-cluster`



 a| 
完了したジョブに関する情報を表示します
 a| 
`job show-completed`



 a| 
ジョブ履歴に関する情報を表示します
 a| 
`job history show`

クラスタ内の各ノードには、最大 25 、 000 個のジョブレコードが格納されます。そのため、ジョブ履歴全体を表示しようとすると時間がかかることがあります。待ち時間が長くならないようにするには、ジョブをノード、 Storage Virtual Machine （ SVM ）、またはレコード ID ごとに表示します。



 a| 
プライベートジョブのリストを表示します
 a| 
`job private show` （ advanced 権限レベル）



 a| 
完了したプライベートジョブに関する情報を表示します
 a| 
`job private show-completed` （ advanced 権限レベル）



 a| 
ジョブマネージャの初期化状態に関する情報を表示します
 a| 
`job initstate show` （ advanced 権限レベル）



 a| 
ジョブの進捗状況を監視します
 a| 
`job watch-progress`



 a| 
プライベートジョブの進捗状況を監視する
 a| 
`job private watch-progress` （ advanced 権限レベル）



 a| 
ジョブを一時停止します
 a| 
`job pause`



 a| 
プライベートジョブを一時停止します
 a| 
`job private pause` （ advanced 権限レベル）



 a| 
一時停止したジョブを再開します
 a| 
`job resume`



 a| 
一時停止したプライベートジョブを再開します
 a| 
`job private resume` （ advanced 権限レベル）



 a| 
ジョブを停止します
 a| 
`job stop`



 a| 
プライベートジョブを停止します
 a| 
`job private stop` （ advanced 権限レベル）



 a| 
ジョブを削除します
 a| 
`job delete`



 a| 
プライベートジョブを削除します
 a| 
`job private delete` （ advanced 権限レベル）



 a| 
クラスタ関連ジョブと、そのジョブが所有する使用できないノードとの関連付けを解除し、別のノードがジョブの所有権を取得できるようにします
 a| 
`job unclaim` （ advanced 権限レベル）

|===
[NOTE]
====
を使用できます `event log show` 完了したジョブの結果を確認するコマンド。

====
.関連情報
http://docs.netapp.com/ontap-9/topic/com.netapp.doc.dot-cm-cmpr/GUID-5CB10C70-AC11-41C0-8C16-B4D0DF916E9B.html["ONTAP 9コマンド"^]



== ジョブスケジュールの管理用コマンド

多くのタスク（ボリュームのSnapshotコピーなど）は、指定したスケジュールで実行するように設定できます。特定の時間に実行されるスケジュールは、_cron_schedulesと呼ばれます（UNIXに似ています） `cron` スケジュール）。一定間隔で実行されるスケジュールは、 _interval_schedules と呼ばれます。を使用します `job schedule` ジョブスケジュールを管理するコマンド。

手動でのクラスタの日付や時刻の変更は、ジョブスケジュールには反映されません。ジョブは、ジョブが作成された時点または最後に実行された時点のクラスタの時刻に基づいて実行されます。そのため、クラスタの日付や時刻を手動で変更する場合は、を使用する必要があります `job show` および `job history show` コマンドを使用して、スケジュールされたすべてのジョブが必要に応じてキューに格納されて完了していることを確認します。

クラスタが MetroCluster 構成に含まれている場合は、両方のクラスタのジョブスケジュールが同じである必要があります。したがって、ジョブスケジュールを作成、変更、または削除する場合は、リモートクラスタでも同じ処理を実行する必要があります。

|===
| 状況 | 使用するコマンド 


 a| 
すべてのスケジュールに関する情報を表示する
 a| 
`job schedule show`



 a| 
ジョブのリストをスケジュール別に表示します
 a| 
`job schedule show-jobs`



 a| 
cron スケジュールに関する情報を表示します
 a| 
`job schedule cron show`



 a| 
インターバルスケジュールに関する情報を表示します
 a| 
`job schedule interval show`



 a| 
cron スケジュールを作成します
 a| 
`job schedule cron create`

ONTAP 9.10.1以降では、SVMをジョブスケジュールに含めることができます。



 a| 
インターバルスケジュールを作成します
 a| 
`job schedule interval create`

次のパラメータの少なくとも1つを指定する必要があります。 `-days`、 `-hours`、 `-minutes`または `-seconds`。



 a| 
cron スケジュールを変更します
 a| 
`job schedule cron modify`



 a| 
インターバルスケジュールを変更します
 a| 
`job schedule interval modify`



 a| 
スケジュールを削除します
 a| 
`job schedule delete`



 a| 
cron スケジュールを削除します
 a| 
`job schedule cron delete`



 a| 
インターバルスケジュールを削除します
 a| 
`job schedule interval delete`

|===
.関連情報
http://docs.netapp.com/ontap-9/topic/com.netapp.doc.dot-cm-cmpr/GUID-5CB10C70-AC11-41C0-8C16-B4D0DF916E9B.html["ONTAP 9コマンド"^]
