---
permalink: system-admin/manage-licenses-concept.html 
sidebar: sidebar 
keywords: manage, license, ontap one, enable, add, record, software, entitlement, keys, codes, risk, usage, cluster, administrator, nlf, bundle 
summary: ライセンスには、ソフトウェアの使用権が1つ以上記録されています。ONTAP 9.10.1以降では、すべてのライセンスがNetAppライセンス ファイル（NLF）として提供されます。これは、複数の機能を有効にする単一のファイルです。2023年5月以降、すべてのAFFシステム（AシリーズとCシリーズの両方）とFASシステムが、ONTAP ONEソフトウェア スイートまたはONTAP Baseソフトウェア スイートのいずれかとともに販売され、2023年6月以降、すべてのASAシステムがONTAP ONE for SANとともに販売されています。 
---
= ONTAPライセンスの概要
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
ライセンスには、ソフトウェアの使用権が1つ以上記録されています。ONTAP 9.10.1以降では、すべてのライセンスがNetAppライセンス ファイル（NLF）として提供されます。これは、複数の機能を有効にする単一のファイルです。2023年5月以降、すべてのAFFシステム（AシリーズとCシリーズの両方）とFASシステムが、ONTAP ONEソフトウェア スイートまたはONTAP Baseソフトウェア スイートのいずれかとともに販売され、2023年6月以降、すべてのASAシステムがONTAP ONE for SANとともに販売されています。ONTAP 9.10.1で初めて導入された個別のNLFバンドルに代わって、各ソフトウェア スイートが単一のNLFとして提供されています。



== ONTAP Oneに含まれるライセンス

ONTAP Oneには、すべての利用可能なライセンス機能が含まれています。表に示すように、従来のCore Bundle、Data Protection Bundle、Security and Compliance Bundle、Hybrid Cloud Bundle、Encryption Bundleで提供していた内容の組み合わせが含まれています。Encryptionは一部の国では使用できません。

|===


| 以前のバンドル名 | ONTAPキーが含まれています 


.5+| コアバンドル | FlexClone 


| SnapRestore 


| NFS、SMB、S3 


| FC、iSCSI 


| NVMe-oF 


.3+| セキュリティとコンプライアンスバンドル | 自律型ランサムウェア対策 


| MTKM 


| SnapLock 


.3+| データ保護バンドル | SnapMirror（非同期、同期、アクティブ同期） 


| SnapCenter 


| NetAppのターゲット用のSnapMirror S3 


.2+| ハイブリッドクラウドバンドル | SnapMirrorクラウド 


| NetApp以外のターゲット用のSnapMirror S3 


.2+| 暗号化バンドル | NetApp Volume Encryption 


| Trusted Platform Module 
|===


== ONTAP Oneに含まれていないライセンス

ONTAP Oneには、以下をはじめとするNetAppのクラウド提供サービスは含まれていません。

* NetApp Cloud Tiering
* Data Infrastructure Insights
* NetApp Backup and Recovery
* データ ガバナンス




== 既存システム向けのONTAP One

現在NetAppのサポートは受けているもののONTAP Oneにアップグレードされていない既存のシステムがある場合、これらのシステムの既存のライセンスは引き続き有効であり、期待どおりに機能します。たとえば、既存のシステムにSnapMirrorライセンスがすでにインストールされている場合、ONTAP Oneにアップグレードして新しいSnapMirrorライセンスを取得する必要はありません。ただし、既存のシステムにSnapMirrorライセンスがインストールされていない場合、そのライセンスを取得するには、追加料金でONTAP Oneにアップグレードする必要があります。

2023 年 6 月以降、28 文字のライセンス キーを使用する ONTAP システムでもlink:https://kb.netapp.com/onprem/ontap/os/How_to_get_an_ONTAP_One_license_when_the_system_has_28_character_keys["ONTAP OneまたはONTAP Base互換性バンドルにアップグレードする"]できます。



== ONTAP Baseに含まれるライセンス

ONTAP BaseはONTAPシステム向けのオプション ソフトウェア スイートで、ONTAP Oneの代替として提供されます。SnapMirrorやSnapCenterなどのデータ保護テクノロジが不要で、自律型ランサムウェア対策のようなセキュリティ機能も要求されないユースケース（テスト / 開発専用環境などの非本番システム）に特化したバンドルです。ONTAP Baseにライセンスを追加することはできません。SnapMirrorなどの追加ライセンスが必要な場合は、ONTAP Oneにアップグレードする必要があります。

|===


| 以前のバンドル名 | ONTAPキーが含まれています 


.5+| コアバンドル | FlexClone 


| SnapRestore 


| NFS、SMB、S3 


| FC、iSCSI 


| NVMe-oF 


.2+| 暗号化バンドル | NetApp Volume Encryption 


| Trusted Platform Module 
|===


== ONTAP One for SANに含まれるライセンス

ONTAP One for SANは、ASA AシリーズおよびCシリーズのシステムで使用できます。これは、SANで使用できる唯一のソフトウェア スイートです。ONTAP One for SANには、次のライセンスが含まれています。

|===


| ONTAPキーが含まれています 


| FlexClone 


| SnapRestore 


| FC、iSCSI 


| NVMe-oF 


| MTKM 


| SnapLock 


| SnapMirror（非同期、同期、アクティブ同期） 


| SnapCenter 


| SnapMirrorクラウド 


| NetApp Volume Encryption 


| Trusted Platform Module 
|===


== その他のライセンス提供方法

ONTAP 8.2～9.9.1では、ライセンス キーは28文字の文字列の形で提供され、ONTAPの機能ごとに1つのキーが存在します。ONTAP 8.2からONTAP 9.9.1を使用している場合は、ONTAP CLIを使用してライセンス キーをインストールします。

[NOTE]
====
ONTAP 9.10.1では、System ManagerまたはCLIを使用した28文字のライセンスキーのインストールがサポートされています。ただし、ある機能に対してNLFライセンスがインストールされている場合、同じ機能のNetAppライセンスファイルに28文字のライセンスキーを上書きインストールすることはできません。System Managerを使用したNLFまたはライセンスキーのインストールについては、link:../system-admin/install-license-task.html["ONTAPライセンスのインストール"]を参照してください。

====
.関連情報
https://kb.netapp.com/onprem/ontap/os/How_to_get_an_ONTAP_One_license_when_the_system_has_NLFs_already["システムにすでにNLFがある場合にONTAP Oneライセンスを取得する方法"]

https://kb.netapp.com/Advice_and_Troubleshooting/Data_Storage_Software/ONTAP_OS/How_to_verify_Data_ONTAP_Software_Entitlements_and_related_License_Keys_using_the_Support_Site["サポートサイトを使用して ONTAP ソフトウェアのエンタイトルメントと関連するライセンスキーを確認する方法"^]

http://mysupport.netapp.com/licensing/ontapentitlementriskstatus["NetApp：ONTAP資格リスクステータス"^]
