---
permalink: system-admin/manage-node-root-volumes-aggregates-task.html 
sidebar: sidebar 
keywords: node, governing, root, volume, aggregate, files, special, directories, free, space, full, delete, file, core, dump 
summary: ノードのルートボリュームは、工場出荷時またはセットアップソフトウェアによってインストールされた FlexVol ボリュームです。 
---
= ノードのルートボリュームとルートアグリゲートを管理します。
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
ノードのルートボリュームは、工場出荷時またはセットアップソフトウェアによってインストールされた FlexVol ボリュームです。システムファイル、ログファイル、コアファイル用に予約されています。ディレクトリ名はです `/mroot`にアクセスします。これには、テクニカルサポートがシステムシェルからのみアクセスできます。ノードのルートボリュームの最小サイズは、プラットフォームモデルによって異なります。



== ノードのルートボリュームとルートアグリゲートに関するルールの概要

ノードのルートボリュームには、そのノードの特別なディレクトリとファイルが格納されています。ルートボリュームはルートアグリゲートに含まれています。ノードのルートボリュームとルートアグリゲートには、いくつかのルールが適用されます。

* ノードのルートボリュームには次のルールが適用されます。
+
** テクニカルサポートから指示がないかぎり、ルートボリュームの構成またはコンテンツを変更しないでください。
** ユーザデータはルートボリュームに格納しないでください。
+
ユーザデータをルートボリュームに格納すると、 HA ペアのノード間でのストレージのギブバックに時間がかかります。

** ルートボリュームを別のアグリゲートに移動できます。  を参照してください <<relocate-root>>。


* ルートアグリゲートは、ノードのルートボリューム専用になります。
+
ONTAP では、ルートアグリゲートに他のボリュームを作成することはできません。



https://hwu.netapp.com["NetApp Hardware Universe の略"^]



== ノードのルートボリュームのスペースを解放する

ノードのルートボリュームがいっぱい、またはほぼいっぱいになると、警告メッセージが表示されます。ルートボリュームがいっぱいになると、ノードは正常に動作できません。コアダンプファイル、パケットトレースファイル、およびルートボリュームの Snapshot コピーを削除することにより、ノードのルートボリュームのスペースを解放できます。

.手順
. ノードのコアダンプファイルとその名前を表示します。
+
`system node coredump show`

. 不要なコアダンプファイルをノードから削除します。
+
`system node coredump delete`

. ノードシェルにアクセスします。
+
`*system node run -node _nodename_*`

+
`_nodename_` は、ルートボリュームのスペースを解放するノードの名前です。

. ノードシェルからノードシェルの advanced 権限レベルに切り替えます。
+
`*priv set advanced*`

. ノードのパケットトレースファイルは、次のようにノードシェルから表示、削除を行います。
+
.. ノードのルートボリュームにあるすべてのファイルを表示します。
+
`*ls /etc*`

.. パケットトレースファイルがある場合 (`*.trc`）がノードのルートボリュームに含まれている場合は、個 々 に削除します。
+
`*rm /etc/log/packet_traces/_file_name.trc_*`



. ノードのルートボリュームの Snapshot コピーは、次のようにノードシェルから特定、および削除を行います。
+
.. ルートボリューム名を特定します。
+
`*vol status*`

+
ルートボリュームは、の[Options]列に「root」と表示されます `vol status` コマンド出力。

+
次の例では、ルートボリュームはです `vol0`：

+
[listing]
----
node1*> vol status

         Volume State           Status            Options
           vol0 online          raid_dp, flex     root, nvfail=on
                                64-bit
----
.. ルートボリュームの Snapshot コピーを表示します。
+
`*snap list root_vol_name*`

.. 不要なルートボリュームの Snapshot コピーを削除します。
+
`*snap delete root_vol_namesnapshot_name*`



. ノードシェルを終了してクラスタシェルに戻ります。
+
`*exit*`





== ルートボリュームを新しいアグリゲートに再配置します

ルート交換用手順は、現在のルートアグリゲートをシステム停止なしで別のディスクセットに移行します。

.このタスクについて
ルートボリュームを再配置するには、ストレージフェイルオーバーを有効にする必要があります。を使用できます `storage failover modify -node _nodename_ -enable true` フェイルオーバーを有効にするコマンド。

次のシナリオで、ルートボリュームの場所を新しいアグリゲートに変更できます。

* ルートアグリゲートが希望するディスク上にない場合
* ノードに接続されているディスクの配置を変更する場合
* EOS ディスクシェルフを交換する場合


.手順
. 権限レベルを advanced に設定します。
+
`*set privilege advanced*`

. ルートアグリゲートを再配置します。
+
`*system node migrate-root -node _nodename_ -disklist _disklist_ -raid-type _raid-type_*`

+
** * -node *
+
移行するルートアグリゲートを所有しているノードを指定します。

** *-disklist *
+
新しいルートアグリゲートを作成するディスクのリストを指定します。すべてのディスクはスペアであり、同じノードが所有している必要があります。必要なディスクの最小数は RAID タイプによって異なります。

** * -raid-type *
+
ルートアグリゲートの RAID タイプを指定します。デフォルト値はです `raid-dp`。



. ジョブの進捗状況を監視します。
+
`*job show -id _jobid_ -instance*`



.結果
すべての事前確認が完了すると、ルートボリューム交換ジョブが開始されてコマンドが終了します。ノードが再起動するようにします。
