---
permalink: system-admin/methods-specifying-queries-concept.html 
sidebar: sidebar 
keywords: method, use, query, operator, interface, management, unix, patterns, wildcards, command, parameter, argument 
summary: 管理インターフェイスでは、クエリ、UNIX形式のパターンおよびワイルドカードがサポートされており、コマンドパラメータ引数の複数の値を照合できます。 
---
= クエリ演算子の使用方法
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
管理インターフェイスでは、クエリ、UNIX形式のパターンおよびワイルドカードがサポートされており、コマンドパラメータ引数の複数の値を照合できます。

次の表に、サポートされるクエリ演算子を示します。

[cols="10,90"]
|===
| 運用者 | 説明 


 a| 
*
 a| 
すべてのエントリに一致するワイルドカード。

たとえば、コマンドを `volume show -volume \*tmp*`実行すると、名前にが含まれるすべてのボリュームのリストが表示され `tmp`ます。



 a| 
なんだ?
 a| 
NOT演算子。

一致しない値を示します。たとえば、は値と一致しないことを `vs0`示します。 `*!vs0*`



 a| 
|
 a| 
OR演算子。

比較する2つの値を区切ります。たとえば、は `*vs0 | vs2*`vs0またはvs2のいずれかに一致します。複数のORステートメントを指定できます。たとえば、は `a | b* | \*c*`エントリ、で始まるエントリ `b`、を含むエントリに `c`一致します `a`。



 a| 
..
 a| 
範囲演算子。

たとえば、は `*5..10*`任意の値のfromから `10`inclusiveに一致します `5`。



 a| 
<
 a| 
less-than演算子。

たとえば、は、 `*<20*`より小さい任意の値に一致します `20`。



 a| 
>
 a| 
greater-than演算子。

たとえば、は、 `*>5*`より大きい任意の値に一致します `5`。



 a| 
\<=
 a| 
less-than-or-equal-to演算子。

たとえば、は `*<=5*`次の値以下の値に一致します `5`。



 a| 
>=
 a| 
以上演算子。

たとえば、は、 `*>=5*`以上の任意の値に一致します `5`。



 a| 
{`query`}
 a| 
拡張クエリ。

拡張クエリは、コマンド名に続けて、他のパラメータの前に最初の引数として指定する必要があります。

たとえば、コマンドは `volume modify {-volume \*tmp*} -state offline`、名前に文字列が含まれるすべてのボリュームをオフラインに設定し `tmp`ます。

|===
クエリ文字をリテラルとして解析する場合は、 `"\*abc*"`正しい結果が返されるように、文字を二重引用符（、、 `"0..100"`、、など `"a|b"`）で囲む必要があります `"<10"`。

特殊文字が解釈されないように、rawファイル名は二重引用符で囲む必要があります。これは、クラスタシェルで使用される特殊文字にも当てはまります。

1つのコマンドラインで複数のクエリ演算子を使用できます。たとえば、 `volume show -size >1GB -percent-used <50 -vserver !vs1`「vs1」という名前のStorage Virtual Machine（SVM）に含まれていない、サイズが1GBを超え、使用率が50%未満のすべてのボリュームが表示されます。

.関連情報
link:../system-admin/keyboard-shortcuts-edit-cli-commands-reference.html["CLIコマンドを編集するためのキーボードショートカット"]
