---
permalink: system-admin/methods-specifying-queries-concept.html 
sidebar: sidebar 
keywords: method, use, query, operator, interface, management, unix, patterns, wildcards, command, parameter, argument 
summary: 管理インターフェイスでは、クエリと UNIX 形式のパターンおよびワイルドカードがサポートされており、コマンドパラメータ引数の複数の値を照合できます。 
---
= クエリ演算子の使用方法
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
管理インターフェイスでは、クエリと UNIX 形式のパターンおよびワイルドカードがサポートされており、コマンドパラメータ引数の複数の値を照合できます。

次の表に、サポートされるクエリ演算子を示します。

[cols="10,90"]
|===
| 演算子 | 説明 


 a| 
*
 a| 
すべてのエントリに一致するワイルドカード。

たとえば、コマンドを入力します `volume show -volume \*tmp*` 名前に文字列が含まれるすべてのボリュームのリストを表示します `tmp`。



 a| 
！
 a| 
NOT 演算子。

一致しない値を示します。たとえば、次のように指定します。 `*!vs0*` 値と一致しないことを示します `vs0`。



 a| 
|
 a| 
OR 演算子。

比較する2つの値を区切ります。次に例を示します。 `*vs0 | vs2*` vs0またはvs2のいずれかに一致します。複数のOR文を指定できます。例： `a | b* | \*c*` エントリに一致します `a`で始まるエントリ `b`を含むエントリが含まれます `c`。



 a| 
。
 a| 
範囲演算子。

例： `*5..10*` からの任意の値に一致します `5` 終了： `10`、含んでいる。



 a| 
<
 a| 
less-than 演算子。

例： `*<20*` より小さい値に一致します `20`。



 a| 
>
 a| 
greater-than 演算子。

例： `*>5*` より大きい値に一致します `5`。



 a| 
>=
 a| 
less-than-or-equal-to 演算子。

例： `*<=5*` が次の値以下の値と一致します `5`。



 a| 
>=
 a| 
greater-than-or-equal-to 演算子。

例： `*>=5*` が次の値以上の値に一致します `5`。



 a| 
{`query`｝
 a| 
拡張クエリ。

拡張クエリは、コマンド名のあとで、他のパラメータの前の最初の引数として指定する必要があります。

たとえば、コマンドを入力します `volume modify {-volume \*tmp*} -state offline` 名前に文字列が含まれるすべてのボリュームをオフラインに設定します `tmp`。

|===
クエリ文字をリテラルとして解析する場合は、二重引用符で文字列を囲む必要があります（例えば、"`{care}`","`）.`", "`*`", or "`$`")を返して、正しい結果を返します。

1 つのコマンドラインで複数のクエリ演算子を使用できます。たとえば、コマンドを入力します `volume show -size >1GB -percent-used <50 -vserver !vs1` 「vs1」という名前のStorage Virtual Machine（SVM）ではなく、サイズが1GBを超え、使用率が50%未満のすべてのボリュームを表示します。
