---
permalink: system-admin/methods-manage-sp-bmc-firmware-updates-concept.html 
sidebar: sidebar 
keywords: methods, manage, sp, bmc, firmware, update, image, baseline, download 
summary: ONTAPには、ベースラインイメージと呼ばれるSPファームウェアイメージが含まれています。その後、SPファームウェアの新しいバージョンが利用可能になった場合は、そのバージョンをダウンロードして、ONTAPバージョンをアップグレードせずに、SPファームウェアをダウンロードしたバージョンに更新することができます。 
---
= ONTAP SP/BMCファームウェアアップデートの管理
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
ONTAPには、_ベースライン イメージ_と呼ばれるSPファームウェア イメージが含まれています。その後、SPファームウェアの新しいバージョンが利用可能になった場合は、そのバージョンをダウンロードして、ONTAPバージョンをアップグレードせずに、SPファームウェアをダウンロードしたバージョンに更新することができます。

[NOTE]
====
このトピックは、SPとBMCの両方に適用されます。

====
ONTAPでは、次の方法でSPファームウェアの更新を管理できます。

* SP自動更新機能がデフォルトで有効になっており、次のシナリオでSPファームウェアを自動的に更新できます。
+
** 新しいバージョンのONTAPにアップグレードする場合
+
ONTAPにバンドルされているSPファームウェアのバージョンがノードで実行されているSPファームウェアのバージョンよりも新しい場合、ONTAPのアップグレード プロセスでSPファームウェアの更新も自動的に実行されます。

+
[NOTE]
====
ONTAPはSP自動更新の失敗を検出すると、修正アクションをトリガーしてSP自動更新を最大3回まで再試行します。3回の再試行がすべて失敗した場合は、link:https://kb.netapp.com/Advice_and_Troubleshooting/Data_Storage_Software/ONTAP_OS/Health_Monitor_SPAutoUpgradeFailedMajorAlert__SP_upgrade_fails_-_AutoSupport_Message["NetAppナレッジベース：ヘルスモニター SPAutoUpgradeFailedMajorAlert SPアップグレードが失敗しました - AutoSupportメッセージ"^]を参照してください。

====
** NetApp Support SiteからSPファームウェアのバージョンをダウンロードし、ダウンロードしたバージョンがSPが現在実行しているバージョンよりも新しい場合
** ONTAPを以前のバージョンにダウングレードまたはリバートする場合
+
SPファームウェアは、リバートまたはダウングレード後のONTAPのバージョンでサポートされている最新の互換バージョンに自動的に更新されます。SPファームウェアの手動更新は必要ありません。



+
SPの自動更新機能を無効にするには、 `system service-processor image modify`コマンドを使用します。ただし、この機能は有効のままにしておくことを推奨します。この機能を無効にすると、ONTAPイメージとSPファームウェアイメージの組み合わせが最適でなくなったり、不適切になったりする可能性があります。

* ONTAPでは、 `system service-processor image update`コマンドを使用してSP更新を手動でトリガーし、更新の実行方法を指定できます。
+
次のいずれかのオプションを指定します。

+
** 使用するSPファームウェアパッケージ(`-package`)
+
パッケージファイル名を指定することで、SPファームウェアをダウンロードしたパッケージにアップデートできます。advance `system image package show`コマンドは、ノードで利用可能なすべてのパッケージファイル（SPファームウェアパッケージのファイルを含む）を表示します。

** SPアップデートにベースラインSPファームウェアパッケージを使用するかどうか(`-baseline`）
+
SPファームウェアを、現在実行しているバージョンのONTAPに付属しているベースラインのバージョンに更新できます。



+
[NOTE]
====
更新用の一部の高度なオプションやパラメータを使用した場合、BMCの構成設定が一時的にクリアされます。リブート後、ONTAPでBMCの構成がリストアされるまでに最大で10分かかることがあります。

====
* ONTAP では、 `system service-processor image update-progress show`コマンドを使用して、ONTAP からトリガーされた最新の SP ファームウェア更新のステータスを表示できます。


SPへの既存の接続は、SPファームウェアを更新するときに切断されます。これは、SPファームウェア更新が自動的にまたは手動で開始される場合に該当します。

.関連情報
https://mysupport.netapp.com/site/downloads/firmware/system-firmware-diagnostics["NetAppのダウンロード：システム ファームウェアおよび診断"^]
