---
permalink: system-admin/modify-sp-api-service-config-task.html 
sidebar: sidebar 
keywords: modify, sp, api, service, configuration, network 
summary: SP API は、 ONTAP がネットワークを介して SP と通信できるようにするセキュアなネットワーク API です。SP API サービスで使用されるポートを変更したり、サービスが内部通信に使用する証明書を更新したり、サービス全体を無効にしたりできます。設定の変更が必要になることはほとんどありません。 
---
= SP API サービス設定を変更する
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
SP API は、 ONTAP がネットワークを介して SP と通信できるようにするセキュアなネットワーク API です。SP API サービスで使用されるポートを変更したり、サービスが内部通信に使用する証明書を更新したり、サービス全体を無効にしたりできます。設定の変更が必要になることはほとんどありません。

.このタスクについて
* SP API サービスは ' デフォルトでポート 50000 を使用します
+
ポート 50000 が別のネットワーク・アプリケーションの通信に使用されているネットワーク環境の場合や ' 他のアプリケーションからのトラフィックと SP API サービスが生成するトラフィックを区別する場合などは ' ポート値を変更できます

* SP API サービスが使用する SSL 証明書および SSH 証明書は、クラスタ内専用であり、外部に配布されることはありません。
+
証明書のセキュリティが侵害されることはほとんどありませんが、侵害された場合には証明書を更新できます。

* SP API サービスは、デフォルトで有効になっています。
+
SP API サービスを無効にする必要があるのは、 SP が設定または使用されていないプライベート LAN でサービスを無効にする場合など、例外的な場合だけです。

+
SP API サービスを無効にすると、 API は着信接続を受け付けません。また ' ネットワーク・ベースの SP ファームウェア・アップデートやネットワーク・ベースの SP ログ収集などの機能は使用できなくなりますシステムはシリアルインターフェイスの使用に切り替わります。



.手順
. 「 set -privilege advanced 」コマンドを使用して、 advanced 権限レベルに切り替えます。
. SP API サービス設定を変更します。
+
|===
| 状況 | 使用するコマンド 


 a| 
SP API サービスで使用されるポートを変更する
 a| 
'system service-processor api-service modify' には '-port '{`49152'.`65535`} パラメータを指定します



 a| 
SP API サービスの内部通信に使用される SSL 証明書および SSH 証明書を更新する
 a| 
** ONTAP 9.5 以降では、「 system service-processor api-service renew-internal-certificate-」 を使用します
** ONTAP 9.4 以前で使用
** 「システムサービス - プロセッサ API - サービス更新 - 証明書」
+
パラメータを指定しない場合は、ホスト証明書（クライアント証明書とサーバ証明書を含む）のみが更新されます。

+
-renew-all true パラメータを指定すると、ホスト証明書とルート CA 証明書の両方が更新されます。





 a| 
連絡手段
 a| 



 a| 
SP API サービスを無効または再度有効にします
 a| 
'system service-processor api-service modify' には '-is-enabled `{`true|`false'} パラメータを指定します

|===
. 「 system service-processor api-service show 」コマンドを使用して SP API サービス設定を表示します。

