---
permalink: system-admin/ontap-implements-audit-logging-concept.html 
sidebar: sidebar 
keywords: ontap, implement, audit, logging, management, autosupport, ems, messages, log, cli, web, browser 
summary: 監査ログに記録された管理アクティビティは標準の AutoSupport レポートに、特定のログアクティビティは EMS メッセージに含まれています。監査ログを指定の場所に転送したり、 CLI や Web ブラウザを使用して監査ログファイルを表示することもできます。 
---
= ONTAP での監査ログの実装方法
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
監査ログに記録された管理アクティビティは標準の AutoSupport レポートに、特定のログアクティビティは EMS メッセージに含まれています。監査ログを指定の場所に転送したり、 CLI や Web ブラウザを使用して監査ログファイルを表示することもできます。

ONTAP 9.11.1以降では、System Managerを使用して監査ログの内容を表示できます。

9.12.1以降、監査ログは改ざん防止機能を備えています。つまり、adminアクションを記録したログファイルは、クラスタ管理者アカウントであっても変更や削除はできません。

ONTAP では、クラスタで実行された管理アクティビティについて、発行された要求、要求を発行したユーザ、ユーザのアクセス方法、要求が発行された時間などの情報が記録されます。

管理アクティビティには次のタイプがあります。

* set要求。通常は表示以外のコマンドや操作が該当します
+
** これらの要求は、例えば、「 create 」、「 mody 」、または「 delete 」コマンドを実行したときに発行されます。
** set 要求はデフォルトで記録されます。


* get要求。情報を取得して管理インターフェイスに表示します
+
** これらの要求は 'how コマンドを実行するときに発行されますたとえば '
** get要求はデフォルトではログに記録されませんが、ONTAP CLI（`-cliget`）またはONTAP API（`-ontapiget`）から送信されるget要求をログファイルに記録するかどうかを制御できます。




ONTAP は、管理アクティビティをノードの /mroot/etc/log/mlog/audit.log ファイルに記録します。CLI コマンドの 3 つのシェル（クラスタシェル、ノードシェル、および非対話型システムシェル）からのコマンドに加え、 API コマンドがここに記録されます（対話型システムシェルのコマンドは記録されません）。監査ログには、クラスタ内のすべてのノードの時刻が同期しているかどうかを示すタイムスタンプが含まれています。

「 audit.log 」ファイルは、 AutoSupport ツールによって指定された受信者に送信されます。また、 Splunk や syslog サーバなど、指定した外部の送信先にコンテンツを安全に転送することもできます。

「 audit.log 」ファイルは、毎日ローテーションされます。また、サイズが 100MB に達したときにもローテーションが実行されます。以前の 48 個のコピーは保持されます（最大合計 49 個のファイル）。監査ファイルが 1 日単位のローテーションを実行するときは、 EMS メッセージは生成されません。監査ファイルのサイズが上限を超えたためにローテーションが実行された場合は、 EMS メッセージが生成されます。
