---
permalink: system-admin/remov-nodes-cluster-concept.html 
sidebar: sidebar 
keywords: remove, node, cluster, failover, partner, erase, inaccessible 
summary: クラスタから不要なノードを一度に 1 つずつ削除できます。ノードを削除したら、フェイルオーバーパートナーも削除する必要があります。ノードを削除すると、そのノードのデータはアクセスできなくなるか、消去されます。 
---
= クラスタからノードを削除します
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
クラスタから不要なノードを一度に 1 つずつ削除できます。ノードを削除したら、フェイルオーバーパートナーも削除する必要があります。ノードを削除すると、そのノードのデータはアクセスできなくなるか、消去されます。

.作業を開始する前に
クラスタからノードを削除するには、次の条件を満たしている必要があります。

* クラスタ内のノードのうち半数を上回るノードが正常である必要があります。
* 削除するノード上のすべてのデータを退避しておく必要があります。
+
** これには、などが含まれます link:../encryption-at-rest/secure-purge-data-encrypted-volume-concept.html["暗号化されたボリュームからのデータのパージ"]。


* すべてのボリュームが削除されています link:../volumes/move-volume-task.html["移動しました"] または link:../volumes/delete-flexvol-task.html["削除済み"] ノードが所有するアグリゲートから作成します。
* すべてのアグリゲートが完了しました link:../disks-aggregates/commands-manage-aggregates-reference.html["削除済み"] をクリックします。
* ノードが Federal Information Processing Standard （ FIPS ；連邦情報処理標準）ディスクまたは Self-Encrypting Disk （ SED ；自己暗号化ディスク）を所有している場合は、 link:../encryption-at-rest/return-seds-unprotected-mode-task.html["ディスク暗号化が削除されました"] ディスクを非保護モードに戻します。
+
** 必要に応じて、を実行することもできます link:../encryption-at-rest/sanitize-fips-drive-sed-task.html["FIPS ドライブまたは SED を完全消去します"]。


* データ LIF が作成されました link:../networking/delete_a_lif.html["削除済み"] または link:../networking/migrate_a_lif.html["再配置済み"] をクリックします。
* クラスタ管理 LIF が作成されました link:../networking/migrate_a_lif.html["再配置済み"] ノードから、ホームポートが変更されました。
* すべてのクラスタ間 LIF を確認しておきます link:../networking/delete_a_lif.html["削除されました"]。
+
** クラスタ間 LIF を削除するときに表示される警告は無視してかまいません。


* ストレージフェイルオーバーは実行されています link:../high-availability/ha_commands_for_enabling_and_disabling_storage_failover.html["無効"] をクリックします。
* すべての LIF フェイルオーバールールが適用されていることを確認し link:../networking/commands_for_managing_failover_groups_and_policies.html["変更されました"] をクリックしてノードのポートを削除します。
* ノードのすべての VLAN を設定しておきます link:../networking/configure_vlans_over_physical_ports.html#delete-a-vlan["削除済み"]。
* 削除するノードにLUNがある場合は、適切な手順を実行してください link:https://docs.netapp.com/us-en/ontap/san-admin/modify-slm-reporting-nodes-task.html["選択的LUNマップ（SLM）のレポートノードリストを変更します"] ノードを削除する前に、
+
SLMのレポートノードリストからノードとそのHAパートナーを削除しないと、LUNを含むボリュームが別のノードに移動された場合でも、ノードに以前格納されていたLUNへのアクセスが失われる可能性があります。



ノードを削除中であることをネットアップテクニカルサポートに通知する AutoSupport メッセージを問題 で送信することを推奨します。

* 注：自動 ONTAP アップグレードの実行中は 'cluster remove-node' 'cluster unjoin ' および 'node rename などの操作を実行しないでください

.このタスクについて
バージョンが混在したクラスタを実行している場合は、 ONTAP 9.3 以降の advanced 権限のコマンドのいずれかを使用して、バージョンが低い最後のノードを削除できます。

* ONTAP 9.3: cluster unjoin -skip-last-low-version-node-check
* ONTAP 9.4 以降： cluster remove-node-skip-last-low-version-node-check


*注：*ノードをクラスタから削除する前に、ノードに接続されたすべてのディスクのすべてのシステムデータとユーザデータにアクセスできないようにする必要があります。ノードが誤ってクラスタから参加解除された場合は、ネットアップサポートにリカバリのオプションを問い合わせてください。

.手順
. 権限レベルを advanced に変更します。
+
「 * set -privilege advanced * 」のように指定します

. 削除するノードが現在のマスターノードである場合は、マスターノードのクラスタ資格を「 false 」に変更して、クラスタ内の別のノードでマスターノードとして選出できるようにします。
+
*cluster modify – eligibility false *

+
マスターノードとは、「 `m GMT` 」、「 vldb 」、「 vifmgr 」、「 bcomd 」、「 crs 」などのプロセスを保持するノードです。advanced 権限レベルの cluster ring show コマンドを使用すると、現在のマスターノードが表示されます。

+
[listing]
----
cluster::*> cluster modify -node node1 -eligibility false
----
. クラスタからノードを削除します。
+
|===
| ONTAP バージョン | 使用するコマンド 


 a| 
ONTAP 9.3
 a| 
'*cluster unjoin *



 a| 
ONTAP 9.4 以降
 a| 
*cluster remove-node *

|===
+
バージョンが混在したクラスタで ' バージョンが古いノードを削除する場合は ' これらのコマンドで '-skip-last-low-version-node-check パラメータを使用します

+
次の内容が表示されます。

+
** また、ノードのフェイルオーバーパートナーをクラスタから削除する必要があります。
** ノードを削除してクラスタに再追加する前に、ブートメニューオプション（ 4 ）クリーン構成を使用してすべてのディスクまたはオプションを初期化する（ 9 ）アドバンストドライブパーティショニングの設定を消去してすべてのディスクを初期化する必要があります。
+
ノードを削除する前に対処が必要な条件がある場合は、エラーメッセージが生成されます。メッセージの内容は、たとえば、削除が必要なノードに共有リソースがある、あるいはノードのクラスタ HA 構成またはストレージフェイルオーバー構成を無効にする必要があるなどの場合があります。

+
ノードがクォーラムマスターの場合、クラスタのクォーラムがいったん失われて、すぐに戻ります。クォーラムが失われるのは一時的であり、データの操作には影響しません。



. エラー・メッセージにエラー状態が示された場合は ' その状態に対処し 'cluster remove-node' または cluster unjoin コマンドを再実行します
+
ノードは、クラスタから正常に削除されると自動的にリブートされます。

. ノードを転用する場合は、ノードの設定を消去し、すべてのディスクを初期化します。
+
.. ブートプロセス時に、プロンプトが表示されたら Ctrl+C キーを押してブートメニューを表示します。
.. ブートメニューオプション * （ 4 ） Clean configuration and initialize all disks * を選択します。


. admin 権限レベルに戻ります。
+
'*set -privilege admin*

. クラスタからフェイルオーバーパートナーを削除するには、前述の手順を繰り返します。


.完了後
シングルノードクラスタにするためにノードを削除した場合は、データトラフィックを処理するようにクラスタポートを変更します。それには、クラスタポートがデータポートになるように変更し、そのデータポートにデータ LIF を作成します。
