---
permalink: system-admin/respond-degraded-system-health-task.html 
sidebar: sidebar 
keywords: respond, degraded, system, health, status, show, alerts, corrective, probable, cause 
summary: システムのヘルスステータスがデグレードした場合は、アラートの表示、考えられる原因および対処方法の確認、デグレードしたサブシステムに関する情報の表示、問題の解決を行うことができます。抑制されたアラートも表示されるため、変更して承認済みかどうかを確認できます。 
---
= デグレードしたシステムヘルスに対応する
:icons: font
:imagesdir: ../media/


[role="lead"]
システムのヘルスステータスがデグレードした場合は、アラートを表示して考えられる原因および対処方法について一読し、デグレードしたサブシステムに関する情報を表示して、問題を解決できます。抑制されたアラートも表示されるため、変更して承認済みかどうかを確認できます。

AutoSupport メッセージや EMS イベントを表示するか、「 system health 」コマンドを使用すると、アラートが生成されたことを確認できます。

.手順
. 「 system health alert show 」コマンドを使用して、システムヘルスを侵害しているアラートを表示します。
. アラートに示された原因の考えられる影響、考えられる影響、および対処方法を一読し、問題を解決できるか、または詳細情報が必要かを判断します。
. 詳細情報が必要な場合は、「 system health alert show -instance 」コマンドを使用して、アラートに使用できる追加情報を表示してください。
. 「 system health alert modify 」コマンドと「 -acknowledge 」パラメータを使用して、特定のアラートに対して作業中であることを示します。
. アラートの Corrective Actions フィールドに説明されている対処方法を実行し、問題を解決します。
+
対処方法にはシステムのリブートが含まれている場合があります。

+
問題が解決すると、アラートは自動的にクリアされます。サブシステムに他のアラートがない場合 ' サブシステムのヘルスは OK に変わりますすべてのサブシステムのヘルスが OK の場合、システム全体のヘルスステータスは「 OK 」に変わります。

. 「 system health status show 」コマンドを使用して、システムヘルスステータスが「 ok 」であることを確認します。
+
システムの正常性ステータスが「 OK 」でない場合は、この手順を繰り返します。


