---
permalink: system-admin/rules-specifying-values-concept.html 
sidebar: sidebar 
keywords: rules, specifying, values, cli, parameters, required, optional 
summary: ほとんどのコマンドには、1つ以上の必須またはオプションのパラメータが含まれます。多くのパラメータでは、値を指定する必要があります。CLIで値を指定するには、いくつかのルールがあります。 
---
= ONTAP CLIで値を指定するためのルールを理解する
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
ほとんどのコマンドには、1つ以上の必須またはオプションのパラメータが含まれます。多くのパラメータでは、値を指定する必要があります。CLIで値を指定するには、いくつかのルールがあります。

* 値には、数値、ブール値指定子、定義済み値の列挙リストからの選択、またはテキスト文字列を指定できます。
+
一部のパラメータでは、2つ以上の値をカンマで区切って指定できます。カンマで区切られた値のリストは、引用符（" "）で囲む必要はありません。テキスト、スペース、またはクエリ文字（クエリとして意図されていない場合）、または小なり記号または大なり記号で始まるテキストを指定する場合は、必ずそのエンティティを引用符で囲む必要があります。

* CLI は疑問符（(`?`）を特定のコマンドのヘルプ情報を表示するコマンドとして解釈します。
* コマンド名、パラメータ、特定の値など、CLI に入力する一部のテキストでは、大文字と小文字は区別されません。
+
たとえば、 `vserver cifs`コマンドのパラメータ値を入力する際、大文字と小文字は区別されません。ただし、ノード、Storage Virtual Machine（SVM）、アグリゲート、ボリューム、論理インターフェイスの名前など、ほとんどのパラメータ値では大文字と小文字が区別されます。

* 文字列またはリストを受け取るパラメータの値をクリアする場合は、空の引用符（""）またはダッシュ（"-"）を指定します。
* ハッシュ記号(`#`（ポンド記号とも呼ばれます）は、コマンドライン入力のコメントを示します。使用する場合は、コマンドラインの最後のパラメータの後に表示される必要があります。
+
CLI は `#`と行の終わりまでのテキストを無視します。



次の例では、テキストコメントを含むSVMを作成します。その後、SVMを変更してコメントを削除します：

[listing]
----
cluster1::> vserver create -vserver vs0 -subtype default -rootvolume root_vs0
-aggregate aggr1 -rootvolume-security-style unix -language C.UTF-8 -is-repository false -ipspace ipspaceA -comment "My SVM"
cluster1::> vserver modify -vserver vs0 -comment ""
----
次の例では、 `#`記号を使用するコマンドラインコメントは、コマンドが実行する内容を示しています。

[listing]
----
cluster1::> security login create -vserver vs0 -user-or-group-name new-admin
-application ssh -authmethod password #This command creates a new user account
----
 `security login create`の詳細については、link:https://docs.netapp.com/us-en/ontap-cli/security-login-create.html["ONTAPコマンド リファレンス"^]をご覧ください。
