---
permalink: system-admin/rules-node-root-volumes-aggregates-concept.html 
sidebar: sidebar 
keywords: node, governing, root, volume, aggregate, riles, special, directories 
summary: ノードのルートボリュームには、そのノードの特別なディレクトリとファイルが格納されています。ルートボリュームはルートアグリゲートに含まれています。ノードのルートボリュームとルートアグリゲートには、いくつかのルールが適用されます。 
---
= ノードのルートボリュームとルートアグリゲートに関するルールの概要
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
ノードのルートボリュームには、そのノードの特別なディレクトリとファイルが格納されています。ルートボリュームはルートアグリゲートに含まれています。ノードのルートボリュームとルートアグリゲートには、いくつかのルールが適用されます。

ノードのルートボリュームは、工場出荷時またはセットアップソフトウェアによってインストールされた FlexVol ボリュームです。システムファイル、ログファイル、コアファイル用に予約されています。ディレクトリ名はです `/mroot`にアクセスします。これには、テクニカルサポートがシステムシェルからのみアクセスできます。ノードのルートボリュームの最小サイズは、プラットフォームモデルによって異なります。

* ノードのルートボリュームには次のルールが適用されます。
+
** テクニカルサポートから指示がないかぎり、ルートボリュームの構成またはコンテンツを変更しないでください。
** ユーザデータはルートボリュームに格納しないでください。
+
ユーザデータをルートボリュームに格納すると、 HA ペアのノード間でのストレージのギブバックに時間がかかります。

** ルートボリュームを別のアグリゲートに移動できます。
+
xref:relocate-root-volumes-new-aggregates-task.adoc[ルートボリュームを新しいアグリゲートに再配置します]



* ルートアグリゲートは、ノードのルートボリューム専用になります。
+
ONTAP では、ルートアグリゲートに他のボリュームを作成することはできません。



https://["NetApp Hardware Universe の略"^]
