---
permalink: system-admin/rules-specifying-values-concept.html 
sidebar: sidebar 
keywords: rules, specifying, values, cli, parameters, required, optional 
summary: ほとんどのコマンドには、 1 つ以上の必須またはオプションのパラメータが含まれています。多くのパラメータでは、値を指定する必要があります。CLI で値を指定するには、いくつかのルールがあります。 
---
= CLIで値を指定する際のルール
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
ほとんどのコマンドには、 1 つ以上の必須またはオプションのパラメータが含まれています。多くのパラメータでは、値を指定する必要があります。CLI で値を指定するには、いくつかのルールがあります。

* 値には、数値、ブール指定子、事前に定義された値の列挙リストからの選択、またはテキスト文字列を指定できます。
+
一部のパラメータでは、 2 つ以上の値をカンマで区切って指定できます。値をカンマで区切って指定したリストは、引用符（ "" ）で囲む必要はありません。テキスト、スペース、またはクエリ文字（クエリを意図していない場合、または小なり記号または大なり記号で始まるテキスト）を指定する場合は、必ずエンティティを引用符で囲む必要があります。

* CLIは疑問符(`?`）をコマンドと解釈し、特定のコマンドのヘルプ情報を表示します。
* コマンド名、パラメータ、特定の値などの CLI に入力するテキストの一部では、大文字と小文字が区別されません。
+
たとえば、コマンドのパラメータ値を入力した場合、 `vserver cifs`大文字と小文字の区別は無視されます。ただし、ノード、Storage Virtual Machine（SVM）、アグリゲート、ボリューム、論理インターフェイスの名前などのほとんどのパラメータ値では大文字と小文字が区別されます。

* 文字列またはリストをとるパラメータの値をクリアする場合は、空の一連の引用符（ "" ）またはダッシュ（ "-" ）を指定します。
* ハッシュ記号(`#`）はシャープ記号とも呼ばれ、コマンドライン入力のコメントを示します。使用する場合は、コマンドラインの最後のパラメータのあとに表示されます。
+
CLIでは、と行末の間のテキストは無視され `#`ます。



次の例では、テキストコメント付きでSVMが作成されます。次に、 SVM が変更されてコメントが削除されます。

[listing]
----
cluster1::> vserver create -vserver vs0 -subtype default -rootvolume root_vs0
-aggregate aggr1 -rootvolume-security-style unix -language C.UTF-8 -is-repository false -ipspace ipspaceA -comment "My SVM"
cluster1::> vserver modify -vserver vs0 -comment ""
----
次の例では、記号を使用したコマンドラインコメント `#`は、コマンドの動作を示しています。

[listing]
----
cluster1::> security login create -vserver vs0 -user-or-group-name new-admin
-application ssh -authmethod password #This command creates a new user account
----