---
permalink: system-admin/setup-autosupport-task.html 
sidebar: sidebar 
keywords: set, up, autosupport, technical, support, organization, internal, configuration, test 
summary: テクニカルサポートまたは社内のサポート部門に AutoSupport 情報を送信するかどうかおよびその方法を管理し、その設定が正しいことをテストできます。 
---
= AutoSupport をセットアップする
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
テクニカルサポートまたは社内のサポート部門に AutoSupport 情報を送信するかどうかおよびその方法を管理し、その設定が正しいことをテストできます。

.このタスクについて
ONTAP 9.5 以降のリリースでは、クラスタのすべてのノードで AutoSupport を有効にし、その設定を同時に変更できます。新しいノードがクラスタに追加されると、そのノードは AutoSupport クラスタ設定を自動的に継承します。各ノードの設定を個別に更新する必要はありません。

[NOTE]
====
ONTAP 9.5以降では、の範囲がに追加されています `system node autosupport modify` コマンドはクラスタ全体に適用されます。AutoSupport の設定は、クラスタ内のすべてのノードで、があっても変更されます `-node` オプションを指定します。このオプションは無視されますが、 CLI の下位互換性を維持するために保持されています。

ONTAP 9.4 以前のリリースでは、「 system node AutoSupport modify 」コマンドの範囲はノードに固有です。クラスタ内の各ノードで AutoSupport 設定を変更する必要があります。

====
デフォルトでは、各ノードで AutoSupport が有効になっており、 HTTPS 転送プロトコルを使用してテクニカルサポートにメッセージを送信できます。

.手順
. AutoSupport が有効になっていることを確認します。
+
[listing]
----
system node autosupport modify -state enable
----
. テクニカルサポートに AutoSupport メッセージを送信するには、次のコマンドを使用します。
+
[listing]
----
system node autosupport modify -support enable
----
+
AutoSupport を AutoSupport OnDemand と連携できるようにする場合、またはコアダンプファイルやパフォーマンスアーカイブファイルなどの大容量ファイルをテクニカルサポートまたは指定の URL にアップロードする場合は、このオプションを有効にする必要があります。

. テクニカルサポートが AutoSupport メッセージを受信できるようになっている場合は、メッセージに使用する転送プロトコルを指定します。
+
次のオプションから選択できます。

+
|===


| 状況 | 次に、の次のパラメータを設定します `system node autosupport modify` コマンド... 


 a| 
デフォルトの HTTPS プロトコルを使用します
 a| 
.. 設定 `-transport` 終了： `https`。
.. プロキシを使用する場合は、を設定します `-proxy-url` プロキシのURLに設定します。この設定では、 AutoSupport OnDemand との通信および大容量ファイルのアップロードがサポートされます。




 a| 
SMTP よりも推奨される HTTP を使用します
 a| 
.. 設定 `-transport` 終了： `http`。
.. プロキシを使用する場合は、を設定します `-proxy-url` プロキシのURLに設定します。この設定では、大容量ファイルのアップロードがサポートされますが、 AutoSupport OnDemand はサポートされません。




 a| 
SMTP を使用する
 a| 
設定 `-transport` 終了： `smtp`。

この設定では、 AutoSupport OnDemand や大容量ファイルのアップロードはサポートされません。

|===
. 社内のサポート部門またはサポートパートナーに AutoSupport メッセージを送信するには、次の操作を実行します。
+
.. の次のパラメータを設定して、組織内の受信者を特定します `system node autosupport modify` コマンドを実行します
+
|===


| 設定するパラメータ | パラメータの値 


 a| 
`-to`
 a| 
重要な AutoSupport メッセージを受け取る社内サポート部門の、カンマで区切った 5 つまでの個別 E メールアドレスまたは配信リスト



 a| 
`-noteto`
 a| 
重要な AutoSupport メッセージの携帯電話やその他のモバイルデバイス用の短縮版を受け取る社内サポート部門の、カンマで区切った 5 つまでの個別 E メールアドレスまたは配信リスト



 a| 
`-partner-address`
 a| 
すべての AutoSupport メッセージを受け取るサポートパートナー部門の、カンマで区切った 5 つまでの個別 E メールアドレスまたは配信リスト

|===
.. アドレスが正しく設定されていることを確認するには、を使用します `system node autosupport destinations show` コマンドを実行します


. メッセージを社内のサポート部門に送信するか、テクニカルサポートへのメッセージにSMTP転送を選択する場合は、の次のパラメータを設定してSMTPを設定します `system node autosupport modify` コマンドを実行します
+
** 設定 `-mail-hosts` をカンマで区切って1つ以上のメールホストに送信します。
+
最大 5 つのを設定できます。

+
各メールホストのポートを設定するには、メールホスト名のあとにコロンとポート番号を入力します。次に例を示します。 `mymailhost.example.com:5678`5678はメール・ホストのポートです

** 設定 `-from` からAutoSupport メッセージを送信するEメールアドレスに送信します。


. DNS を設定します。
. （オプション）特定の設定を変更する場合は、コマンドオプションを追加します。
+
|===


| 実行する処理 | 次に、の次のパラメータを設定します `system node autosupport modify` コマンド... 


 a| 
メッセージ内の機密データを削除、マスキング、またはエンコードすることによって、プライベートデータを非表示にします
 a| 
設定 `-remove-private-data` 終了： `true`。から変更した場合 `false` 終了： `true`をクリックすると、AutoSupport の履歴と関連するファイルがすべて削除されます。



 a| 
定期的な AutoSupport メッセージでのパフォーマンスデータの送信を停止します
 a| 
設定 `-perf` 終了： `false`。

|===
. を使用して、全体的な構成を確認します `system node autosupport show` コマンドにを指定します `-node` パラメータ
. を使用してAutoSupport の動作を確認します `system node autosupport check show` コマンドを実行します
+
問題が報告された場合は、を使用します `system node autosupport check show-details` コマンドを実行すると、詳細が表示されます。

. AutoSupport メッセージが送受信されていることをテストします。
+
.. を使用します `system node autosupport invoke` コマンドにを指定します `-type` パラメータをに設定します `test`。
+
[listing]
----
cluster1::> system node autosupport invoke -type test -node node1
----
.. ネットアップが AutoSupport メッセージを受信していることを確認します。
+
system node AutoSupport history show -node local コマンドを実行します

+
最新の発信AutoSupport メッセージのステータスは、最終的にはに変わります `sent-successful` すべての適切なプロトコルの宛先。

.. （オプション）AutoSupport メッセージが社内のサポート部門またはサポートパートナーに送信されていることを確認するには、に対して設定したアドレスのEメールを確認します `-to`、 `-noteto`または `-partner-address` のパラメータ `system node autosupport modify` コマンドを実行します



