---
sidebar: sidebar 
permalink: system-admin/setup-autosupport-task.html 
keywords: autosupport, set up autosupport, technical support 
summary: AutoSupportメッセージをNetAppテクニカルサポートに配信し、社内のサポート部門にEメールコピーを送信するようにONTAPクラスタを設定します。 
---
= AutoSupport をセットアップする
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
AutoSupportメッセージをNetAppテクニカルサポートに配信し、社内のサポート部門にEメールコピーを送信するようにONTAPクラスタを設定できます。その一環として、本番環境で使用する前に構成をテストすることもできます。

.このタスクについて
ONTAP 9.5以降では、クラスタのすべてのノードに対して同時にAutoSupportを有効にして設定することができます。新しいノードがクラスタに追加されると、同じAutoSupport設定が自動的に継承されます。これをサポートするには、CLIコマンドの範囲 `system node autosupport modify` はクラスタレベルです。。 `-node` コマンドオプションは下位互換性のために保持されていますが、無視されます。


NOTE: ONTAP 9.4以前のリリースでは、コマンド `system node autosupport modify` は各ノードに固有です。クラスタでONTAP 9.4以前を実行している場合は、クラスタ内の各ノードでAutoSupportを有効にして設定する必要があります。

.作業を開始する前に
AutoSupportメッセージをNetAppに配信するための推奨される転送設定はHTTPS（TLSを使用したHTTP）です。このオプションは、最も堅牢な機能と最高のセキュリティを提供します。

レビュー link:requirements-autosupport-reference.html["AutoSupportを使用する準備"] を参照してくださいONTAP。

.手順
. AutoSupport が有効になっていることを確認します。
+
[listing]
----
system node autosupport modify -state enable
----
. NetAppテクニカルサポートにAutoSupportメッセージを送信するには、次のコマンドを使用します。
+
[listing]
----
system node autosupport modify -support enable
----
+
AutoSupport を AutoSupport OnDemand と連携できるようにする場合、またはコアダンプファイルやパフォーマンスアーカイブファイルなどの大容量ファイルをテクニカルサポートまたは指定の URL にアップロードする場合は、このオプションを有効にする必要があります。

. NetAppテクニカルサポートがAutoSupportメッセージを受信できるようになっている場合は、メッセージに使用する転送プロトコルを指定します。
+
次のオプションから選択できます。

+
|===


| 状況 | 次に、の次のパラメータを設定します `system node autosupport modify` コマンド... 


 a| 
デフォルトの HTTPS プロトコルを使用します
 a| 
.. 設定 `-transport` 終了： `https`。
.. プロキシを使用する場合は、を設定します `-proxy-url` にプロキシのURLを入力します。
この設定では、 AutoSupport OnDemand との通信および大容量ファイルのアップロードがサポートされます。




 a| 
SMTP を使用する
 a| 
設定 `-transport` 終了： `smtp`。

この設定では、 AutoSupport OnDemand や大容量ファイルのアップロードはサポートされません。

|===
. 社内のサポート部門またはサポートパートナーに AutoSupport メッセージを送信するには、次の操作を実行します。
+
.. 組織内の受信者を特定するには、の次のパラメータを設定します `system node autosupport modify` コマンドを実行します
+
|===


| 設定するパラメータ | パラメータの値 


 a| 
`-to`
 a| 
重要な AutoSupport メッセージを受け取る社内サポート部門の、カンマで区切った 5 つまでの個別 E メールアドレスまたは配信リスト



 a| 
`-noteto`
 a| 
重要な AutoSupport メッセージの携帯電話やその他のモバイルデバイス用の短縮版を受け取る社内サポート部門の、カンマで区切った 5 つまでの個別 E メールアドレスまたは配信リスト



 a| 
`-partner-address`
 a| 
すべての AutoSupport メッセージを受け取るサポートパートナー部門の、カンマで区切った 5 つまでの個別 E メールアドレスまたは配信リスト

|===
.. を使用して送信先をリストし、アドレスが正しく設定されていることを確認します `system node autosupport destinations show` コマンドを実行します


. メッセージを社内のサポート部門に送信するか、テクニカルサポートへのメッセージにSMTP転送を選択した場合は、の次のパラメータを設定してSMTPを設定します `system node autosupport modify` コマンドを実行します
+
** 設定 `-mail-hosts` をカンマで区切って1つ以上のメールホストに転送します。
+
最大 5 つのを設定できます。

+
メールホスト名のあとにコロンとポート番号を指定することで、各メールホストのポート値を設定できます。次に例を示します。 `mymailhost.example.com:5678`では、5678はメールホストのポートです。

** 設定 `-from` AutoSupport メッセージを送信するEメールアドレスに送信します。


. DNS を設定します。
. 特定の設定を変更する場合は、必要に応じてコマンドオプションを追加します。
+
|===


| 実行する処理 | 次に、の次のパラメータを設定します `system node autosupport modify` コマンド... 


 a| 
メッセージ内の機密データを削除、マスキング、またはエンコードすることによって、プライベートデータを非表示にします
 a| 
設定 `-remove-private-data` 終了： `true`。から変更した場合 `false` 終了： `true`をクリックすると、すべてのAutoSupport 履歴とすべての関連ファイルが削除されます。



 a| 
定期的な AutoSupport メッセージでのパフォーマンスデータの送信を停止します
 a| 
設定 `-perf` 終了： `false`。

|===
. SMTPを使用してAutoSupportメッセージをNetAppに配信する場合は、オプションでTLSを有効にしてセキュリティを強化できます。
+
.. 新しいパラメータに使用可能な値を表示します。
+
[listing]
----
cluster1::> system node autosupport modify -smtp-encryption ?
----
.. SMTPメッセージ配信のTLSを有効にします。
+
[listing]
----
cluster1::> system node autosupport modify -smtp-encryption start_tls
----
.. 現在の設定を表示します。
+
[listing]
----
cluster1::> system node autosupport show -fields smtp-encryption
----


. を使用して設定全体を確認します `system node autosupport show` コマンドにを指定します `-node` パラメータ
. を使用してAutoSupport の動作を確認します `system node autosupport check show` コマンドを実行します
+
問題が報告された場合は、を使用してください `system node autosupport check show-details` コマンドを使用して詳細情報を表示します。

. AutoSupport メッセージが送受信されていることをテストします。
+
.. を使用します `system node autosupport invoke` コマンドにを指定します `-type` パラメータをに設定します `test`：
+
[listing]
----
cluster1::> system node autosupport invoke -type test -node node1
----
.. ネットアップが AutoSupport メッセージを受信していることを確認します。
+
[listing]
----
system node autosupport history show -node local
----
+
最新の発信AutoSupport メッセージのステータスは、最終的ににに変わります `sent-successful` すべての適切なプロトコルの宛先に対して。

.. 必要に応じて、AutoSupportメッセージが社内のサポート部門またはサポートパートナーに送信されていることを確認するために、 `-to`、 `-noteto`または `-partner-address`  のパラメータ `system node autosupport modify` コマンドを実行します



