---
permalink: system-admin/sp-bmc-network-interface--firmware-updates-concept.html 
sidebar: sidebar 
keywords: sp, bmc, network, interface, firmware, update 
summary: バージョン 1.5 、 2.5 、 3.1 、またはそれ以降の SP を搭載した ONTAP から実行される SP ファームウェアの更新では、 SP ネットワークインターフェイス経由の IP ベースのファイル転送メカニズムの使用がサポートされます。 
---
= SP / BMC がネットワークインターフェイスを使用してファームウェアを更新する場合
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
バージョン 1.5 、 2.5 、 3.1 、またはそれ以降の SP を搭載した ONTAP から実行される SP ファームウェアの更新では、 SP ネットワークインターフェイス経由の IP ベースのファイル転送メカニズムの使用がサポートされます。

[NOTE]
====
このトピック環境では、 SP と BMC の両方について説明します。

====
ネットワークインターフェイス経由の SP ファームウェアの更新は、シリアルインターフェイス経由の更新よりも高速です。そのため、 SP ファームウェアを更新中のメンテナンス時間が短縮され、 ONTAP の処理が停止されることもありません。この機能をサポートするバージョンの SP は、 ONTAP に含まれています。また、これらの SP をネットアップサポートサイトから入手して、互換性のあるバージョンの ONTAP を実行しているコントローラにインストールすることもできます。

SP バージョン 1.5 、 2.5 、 3.1 以降を実行している場合、ファームウェアのアップグレードは次のように動作します。

* ONTAP によって自動でトリガーされる SP ファームウェア更新では、デフォルトでネットワークインターフェイスが使用されます。ただし、次のいずれかの条件に該当する場合、 SP 自動更新はシリアルインターフェイス経由に切り替わります。
+
** SP ネットワークインターフェイスが設定されていないか、使用できません。
** IP ベースのファイル転送に失敗する。
** SP API サービスが無効になっている。




SP CLI からトリガーされる SP ファームウェア更新では、実行している SP のバージョンに関係なく、常に SP ネットワークインターフェイスが使用されます。

https://mysupport.netapp.com/site/downloads/firmware/system-firmware-diagnostics["ネットアップのダウンロード：システムファームウェアおよび診断"]
