---
permalink: system-admin/ssh-login-security-concept.html 
sidebar: sidebar 
keywords: ssh, login, security, information, view, changes, privileges, unsuccessful, attempts, previous, successful, restrictions, considerations 
summary: ONTAP 9 .5以降では、過去のログイン、失敗したログイン、および前回のログイン後のPrivilegesに対する変更に関する情報を表示できます。 
---
= ONTAP SSHログインのセキュリティ
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
ONTAP 9 .5以降では、過去のログイン、失敗したログイン、および前回のログイン後のPrivilegesに対する変更に関する情報を表示できます。

セキュリティ関連の情報は、SSH adminユーザとしてログインした場合に表示されます。次の状態に関するアラートが表示されます。

* アカウント名が最後にログインされた時刻。
* 前回のログイン成功後にログインに失敗した回数。
* 前回のログイン後にロールが変更されたかどうか（adminアカウントのロールが「admin」から「backup」に変更された場合など）。
* 前回のログイン後にロールの追加、変更、または削除機能が変更されたかどうか。


[NOTE]
====
疑わしい情報が表示された場合は、ただちにセキュリティ部門に連絡してください。

====
ログイン時にこの情報を取得するには、次の前提条件を満たしている必要があります。

* SSHユーザアカウントがONTAPでプロビジョニングされている必要があります。
* SSHセキュリティログインが作成されている必要があります。
* ログインに成功する必要があります。




== SSHログインのセキュリティに関する制限事項およびその他の考慮事項

SSHログインのセキュリティ情報には、次の制限事項と考慮事項が適用されます。

* この情報は、SSHベースのログインの場合にのみ表示されます。
* グループベースの管理者アカウント（LDAP / NISおよびADアカウントなど）の場合、自分が属しているグループがONTAPで管理者アカウントとしてプロビジョニングされていれば、ユーザはSSHログイン情報を表示できます。
+
ただし、これらのユーザについては、ユーザアカウントのロールの変更に関するアラートを表示できません。また、ONTAPで管理者アカウントとしてプロビジョニングされたADグループに属するユーザは、前回のログイン以降にログインに失敗した回数を表示できません。

* ユーザについて保持されている情報は、ユーザアカウントがONTAPから削除されると削除されます。
* SSH以外のアプリケーションへの接続に関する情報は表示されません。




== SSHログインのセキュリティ情報の例

次の例は、ログイン後に表示される情報の種類を示しています。

* 次のメッセージは、ログインに成功するたびに表示されます。
+
[listing]
----

Last Login : 7/19/2018 06:11:32
----
* 前回のログインに成功してからログインに失敗した場合は、次のメッセージが表示されます。
+
[listing]
----

Last Login : 4/12/2018 08:21:26
Unsuccessful login attempts since last login - 5
----
* 前回のログイン後に失敗したログインがあり、権限が変更されている場合、次のメッセージが表示されます。
+
[listing]
----

Last Login : 8/22/2018 20:08:21
Unsuccessful login attempts since last login - 3
Your privileges have changed since last login
----

