---
permalink: system-admin/structure-autosupport-messages-sent-email-concept.html 
sidebar: sidebar 
keywords: structure, autosupport, messages, sent, email, subject, standard, brief, body, large, attachment, 7z, file, data 
summary: AutoSupport メッセージが電子メールで送信されると、メッセージには標準の件名、短い本文、およびデータを含む 7z ファイル形式の大きな添付ファイルが含まれます。 
---
= Eメールで送信されるONTAP AutoSupportメッセージの構造について説明します
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
AutoSupport メッセージが電子メールで送信されると、メッセージには標準の件名、短い本文、およびデータを含む 7z ファイル形式の大きな添付ファイルが含まれます。

[NOTE]
====
AutoSupportがプライベートデータを非表示にするように設定されている場合、ヘッダー、件名、本文、添付ファイルでホスト名などの特定の情報が省略またはマスクされます。

====


== Subject

AutoSupportメカニズムによって送信されるメッセージの件名には、通知の理由を示すテキスト文字列が含まれます。件名の形式は次のとおりです：

_System_Name_ からの HA グループ通知（_Message_）_Severity_

* _System_Name_は、AutoSupport設定に応じてホスト名またはシステムIDのいずれかになります。




== 本文

AutoSupportメッセージの本文には次の情報が含まれます：

* メッセージの日付と時間
* メッセージを生成したノード上のONTAPのバージョン
* メッセージを生成したノードのシステムID、シリアル番号、およびホスト名
* AutoSupportシーケンス番号
* SNMP 連絡先名と場所（指定されている場合）
* HAパートナーノードのシステムIDとホスト名




== 添付ファイル

AutoSupportメッセージ内の重要な情報は、 `body.7z`という7zファイルに圧縮され、メッセージに添付されたファイルに含まれています。

添付ファイルに含まれるファイルは、AutoSupport メッセージの種類に固有です。
