---
permalink: system-admin/troubleshoot-web-access-problems-concept.html 
sidebar: sidebar 
keywords: troubleshoot, web, services, access, problems, lif, firewall, policy, protocol, engin, digital, certificate, user, access, authorization 
summary: 設定エラー原因 Web サービスへのアクセスに関する問題が発生します。このエラーに対応するには、 LIF 、ファイアウォールポリシー、 Web プロトコルエンジン、 Web サービス、デジタル証明書、 すべてのユーザアクセス許可が正しく設定されていることを確認します。 
---
= Web サービスへのアクセスに関する問題のトラブルシューティングを行う
:icons: font
:imagesdir: ../media/


[role="lead"]
設定エラー原因 Web サービスへのアクセスに関する問題が発生します。このエラーに対応するには、 LIF 、ファイアウォールポリシー、 Web プロトコルエンジン、 Web サービス、デジタル証明書、 すべてのユーザアクセス許可が正しく設定されていることを確認します。

次の表は、 Web サービスの設定エラーを特定して対処する際に役立ちます。

|===
| アクセスに関する問題 | 原因となる設定エラー | エラーに対処する方法 


 a| 
Web サービスにアクセスしようとすると ' 接続できない ' または接続を確立できないというエラーが Web ブラウザから返されます
 a| 
LIF が正しく設定されていない可能性があります。
 a| 
Web サービスを配信する LIF に ping を送信できることを確認します。

[NOTE]
====
LIF に ping を送信するには、「 network ping 」コマンドを使用します。ネットワーク設定の詳細については、『ネットワーク管理ガイド』を参照してください。

====


 a| 
ファイアウォールが正しく設定されていない可能性があります。
 a| 
HTTP または HTTPS をサポートするようにファイアウォールポリシーが設定されていて、ポリシーが Web サービスを配信する LIF に割り当てられていることを確認します。

[NOTE]
====
ファイアウォールポリシーを管理するには、「 system services firewall policy 」コマンドを使用します。ポリシーと LIF を関連付けるには、「 network interface modify 」コマンドと「 -firewall-policy 」パラメータを使用します。

====


 a| 
Web プロトコルエンジンが無効になっている可能性があります。
 a| 
Web プロトコルエンジンが有効になっていて、 Web サービスがアクセス可能であることを確認します。

[NOTE]
====
クラスタの Web プロトコルエンジンを管理するには、「 system services web 」コマンドを使用します。

====


 a| 
Web サービスにアクセスしようとすると、 Web ブラウザから「見つかりません」エラーが返されます。
 a| 
Web サービスが無効になっている可能性があります。
 a| 
アクセスを許可する各 Web サービスが個別に有効になっていることを確認します。

[NOTE]
====
Web サービスへのアクセスを有効にするには、「 vserver services web modify 」コマンドを使用します。

====


 a| 
Web ブラウザで、ユーザのアカウント名とパスワードを使用して Web サービスにログインできない。
 a| 
ユーザを認証できない、アクセス方法が正しくない、またはユーザに Web サービスへのアクセスが許可されていない
 a| 
ユーザアカウントが存在し、正しいアクセス方法と認証方法が設定されていることを確認します。また、ユーザのロールに Web サービスへのアクセスが許可されていることを確認します。

[NOTE]
====
ユーザアカウントとそのアクセス方法および認証方法を管理するには、「 securitylogin 」コマンドを使用します。ONTAP API Web サービスにアクセスするには 'ontapi-access メソッドが必要ですその他のすべての Web サービスにアクセスするには 'http' アクセス方法が必要ですロールの Web サービスへのアクセスを管理するには 'vserver services web access コマンドを使用します

====


 a| 
HTTPS を使用して Web サービスに接続すると、接続が中断されたことが Web ブラウザに表示されます。
 a| 
Web サービスを配信するクラスタまたは Storage Virtual Machine （ SVM ）で SSL が有効になっていない可能性がある
 a| 
クラスタまたは SVM で SSL が有効になっていて、デジタル証明書が有効であることを確認します。

[NOTE]
====
「 securityssl 」コマンドを使用して HTTP サーバの SSL 設定を管理し、「 securitycertificate show 」コマンドを使用してデジタル証明書情報を表示します。

====


 a| 
HTTPS を使用して Web サービスに接続すると、信頼されていない接続であると Web ブラウザに表示されます。
 a| 
自己署名デジタル証明書を使用している可能性があります。
 a| 
クラスタまたは SVM に関連付けられているデジタル証明書が、信頼された CA によって署名されていることを確認します。

[NOTE]
====
デジタル証明書署名要求を生成するには 'securitycertificate generate-csr コマンドを使用し 'CA 署名のデジタル証明書をインストールするには 'securitycertificate install コマンドを使用しますWeb サービスを提供するクラスタまたは SVM の SSL 設定を管理するには、「 securitySSL 」コマンドを使用します。

====
|===