---
permalink: system-admin/troubleshoot-autosupport-messages-not-received-task.html 
sidebar: sidebar 
keywords: troubleshoot, autosupport, messagem receive, deliver, generate 
summary: システムがAutoSupportメッセージを送信しない場合には、それがAutoSupportがメッセージを生成できないためであるか、配信できないためであるかを判別できます。 
---
= ONTAP AutoSupportメッセージが受信されない場合のトラブルシューティング
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
システムがAutoSupportメッセージを送信しない場合には、それがAutoSupportがメッセージを生成できないためであるか、配信できないためであるかを判別できます。

.手順
.  `system node autosupport history show`コマンドを使用してメッセージの配信ステータスを確認します。
. ステータスを読み取ります。
+
[cols="25,75"]
|===
| このステータス | 意味 


 a| 
初期化中
 a| 
収集プロセスが開始しています。この状態が一時的なものであれば問題はありません。ただしこの状態が持続する場合は、問題が発生しています。



 a| 
collection-failed
 a| 
AutoSupportは、スプールディレクトリにAutoSupportコンテンツを作成できません。 `system node autosupport history show -detail`コマンドを入力すると、AutoSupportが収集しようとしている内容を確認できます。



 a| 
collection-in-progress
 a| 
AutoSupportはAutoSupportコンテンツを収集しています。 `system node autosupport manifest show`コマンドを入力すると、AutoSupportが収集している内容を確認できます。



 a| 
queued
 a| 
AutoSupportメッセージが配信のためにキューに登録されていますが、まだ配信されていません。



 a| 
transmitting
 a| 
AutoSupportが現在メッセージを配信しています。



 a| 
sent-successful
 a| 
AutoSupportはメッセージを正常に配信しました。 `system node autosupport history show -delivery`コマンドを入力すると、AutoSupportがメッセージをどこに配信したかを確認できます。



 a| 
ignore
 a| 
AutoSupportメッセージの送信先がありません。 `system node autosupport history show -delivery`コマンドを入力すると、配信の詳細を確認できます。



 a| 
re-queued
 a| 
AutoSupportはメッセージの配信を試みましたが、失敗しました。その結果、AutoSupportはメッセージを配信キューに戻して再試行しました。 `system node autosupport history show`コマンドを入力すると、エラーを確認できます。



 a| 
transmission-failed
 a| 
AutoSupportは指定された回数のメッセージの配信に失敗し、配信を中止しました。 `system node autosupport history show`コマンドを入力するとエラーが表示されます。



 a| 
ondemand-ignore
 a| 
AutoSupportメッセージは正常に処理されましたが、AutoSupport OnDemandサービスによって無視されました。

|===
. 次のいずれかを実行します。
+
|===
| このステータスの場合 | これを実行します 


 a| 
initializingまたはcollection-failed
 a| 
AutoSupportがメッセージを生成できません。NetAppサポートに問い合わせてください。次のナレッジ ベースの記事を伝えてください。

link:https://kb.netapp.com/Advice_and_Troubleshooting/Data_Storage_Software/ONTAP_OS/AutoSupport_is_failing_to_deliver%3A_status_is_stuck_in_initializing["AutoSupportの配信に失敗しています：ステータスが初期化中のままです"^]



 a| 
ignore、re-queued、またはtransmission failed
 a| 
AutoSupportがメッセージを配信できないため、SMTP、HTTP、またはHTTPSのデスティネーションが正しく設定されていることを確認します。

|===

