---
permalink: system-admin/types-autosupport-messages-reference.html 
sidebar: sidebar 
keywords: active, iq, autosupport, messages, content, support, subsystems 
summary: AutoSupport メッセージには、サポートされているサブシステムに関するステータス情報が含まれていAutoSupport メッセージの内容を把握しておくと、 E メールで受信したメッセージまたは Active IQ （旧 My AutoSupport ） Web サイトに表示されたメッセージを解釈したり、応答したりするときに役立ちます。 
---
= AutoSupport メッセージの種類とその内容
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
AutoSupport メッセージには、サポートされているサブシステムに関するステータス情報が含まれていAutoSupport メッセージの内容を把握しておくと、 E メールで受信したメッセージまたは Active IQ （旧 My AutoSupport ） Web サイトに表示されたメッセージを解釈したり、応答したりするときに役立ちます。

|===
| メッセージのタイプ | メッセージに含まれるデータのタイプ 


 a| 
イベントトリガー型
 a| 
イベントが発生した特定のサブシステムに関するコンテキスト依存データが含まれるファイル



 a| 
毎日
 a| 
ログファイル



 a| 
パフォーマンス
 a| 
過去 24 時間以内にサンプリングされたパフォーマンスデータ



 a| 
毎週
 a| 
設定データおよびステータスデータ



 a| 
によってトリガーされます `system node autosupport invoke` コマンドを実行します
 a| 
で指定した値によって異なります `-type` パラメータ：

* `test` いくつかの基本データを含むユーザトリガー型メッセージを送信します。
+
また、を使用して、テクニカルサポートからの自動応答Eメールが指定したEメールアドレス宛てに送信されます `-to` オプション。AutoSupport メッセージが受信されていることを確認できます。

* `performance` パフォーマンスデータを送信します。
* `all` 各サブシステムのトラブルシューティングデータを含む、週次メッセージと同様の一連のデータを含むユーザトリガー型メッセージを送信します。
+
通常、テクニカルサポートからはこのメッセージが要求されます。





 a| 
によってトリガーされます `system node autosupport invoke-core-upload` コマンドを実行します
 a| 
ノードのコアダンプファイル



 a| 
によってトリガーされます `system node autosupport invoke-performance-archive` コマンドを実行します
 a| 
指定された期間のパフォーマンスアーカイブファイル



 a| 
AutoSupport OnDemand によってトリガーされます
 a| 
AutoSupport OnDemand では、新しいメッセージまたは過去のメッセージを要求できます。

* 新しいメッセージは、AutoSupport 収集のタイプに応じてにすることができます `test`、 `all`または `performance`。
* 過去のメッセージは、再送信されるメッセージの種類によって異なります。


AutoSupport OnDemand では、NetApp Support Siteに次のファイルをアップロードする新しいメッセージを要求できます http://["mysupport.netapp.com"]：

* コアダンプ
* パフォーマンスアーカイブ


|===