---
permalink: system-admin/types-autosupport-messages-reference.html 
sidebar: sidebar 
keywords: active, iq, active iq, digital advisor, autosupport, messages, content, support, subsystems 
summary: AutoSupportメッセージには、サポートされているサブシステムに関するステータス情報が含まれています。AutoSupportメッセージの内容を把握しておくと、Eメールで受信したメッセージまたはDigital Advisor Webサイトに表示されたメッセージを解釈したり、応答したりするときに役立ちます。 
---
= ONTAP AutoSupportメッセージのタイプとその内容
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
AutoSupportメッセージには、サポートされているサブシステムに関するステータス情報が含まれています。AutoSupportメッセージの内容を把握しておくと、Eメールで受信したメッセージまたはDigital Advisor Webサイトに表示されたメッセージを解釈したり、応答したりするときに役立ちます。

|===
| メッセージのタイプ | メッセージに含まれるデータのタイプ 


 a| 
イベントトリガー型
 a| 
イベントが発生した特定のサブシステムについての状況に応じたデータが含まれるファイル



 a| 
日次
 a| 
ログ ファイル



 a| 
パフォーマンス
 a| 
過去24時間以内にサンプリングされたパフォーマンス データ



 a| 
週次
 a| 
設定データおよびステータス データ



 a| 
 `system node autosupport invoke`コマンドによって起動
 a| 
 `-type`パラメータで指定された値によって異なります：

* `test`は、いくつかの基本データを含むユーザートリガーメッセージを送信します。
+
このメッセージは、 `-to` オプションを使用して、指定された電子メール アドレスにテクニカル サポートから自動電子メール応答を送信することもトリガーするため、AutoSupport メッセージが受信されていることを確認できます。

* `performance`パフォーマンス データを送信します。
* `all`各サブシステムからのトラブルシューティング データを含む、週次メッセージと同様の完全なデータ セットを持つ、ユーザがトリガするメッセージを送信します。
+
一般に、テクニカル サポートからはこのメッセージが要求されます。





 a| 
 `system node autosupport invoke-core-upload`コマンドによって起動
 a| 
ノードのコア ダンプ ファイル



 a| 
 `system node autosupport invoke-performance-archive`コマンドによって起動
 a| 
指定された期間のパフォーマンス アーカイブ ファイル



 a| 
AutoSupport OnDemandによるトリガー型
 a| 
AutoSupport OnDemandは、新しいメッセージや過去のメッセージを要求できます。

* 新しいメッセージは、AutoSupportコレクションの種類に応じて `test`、 `all`、または `performance`になります。
* 過去のメッセージは、再送信するメッセージの種類によって異なります。


AutoSupport OnDemandは、次のファイルをNetApp Support Siteにアップロードする新しいメッセージをリクエストできます http://mysupport.netapp.com/["mysupport.netapp.com"^]：

* コア ダンプ
* パフォーマンス アーカイブ


|===