---
permalink: system-admin/upload-performance-archive-files-task.html 
sidebar: sidebar 
keywords: upload, performance, archive, files, autosupport, message, technical 
summary: パフォーマンスアーカイブを含むAutoSupportメッセージを生成して送信できます。デフォルトでは、NetAppテクニカルサポートにAutoSupportメッセージが送信され、パフォーマンスアーカイブがNetAppサポートサイトにアップロードされます。メッセージの送信先とアップロード先には別の場所を指定できます。 
---
= ONTAP AutoSupportパフォーマンスアーカイブファイルのアップロード
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
パフォーマンスアーカイブを含むAutoSupportメッセージを生成して送信できます。デフォルトでは、NetAppテクニカルサポートにAutoSupportメッセージが送信され、パフォーマンスアーカイブがNetAppサポートサイトにアップロードされます。メッセージの送信先とアップロード先には別の場所を指定できます。

.必要なもの
* 次の設定を使用してAutoSupportをセットアップしておく必要があります。
+
** ノードでAutoSupportが有効になっている。
** AutoSupportは、テクニカルサポートにメッセージを送信するように設定されています。
** AutoSupportは、HTTPまたはHTTPS転送プロトコルを使用するように設定されています。
+
大容量ファイル（パフォーマンスアーカイブファイルなど）を含むメッセージを送信する場合、SMTP転送プロトコルはサポートされません。





.タスクの内容
アップロードするパフォーマンスアーカイブデータの開始日を指定する必要があります。ほとんどのストレージシステムでは、パフォーマンスアーカイブが2週間保持されるため、2週間前までの開始日を指定できます。たとえば、今日が1月15日の場合は、1月2日の開始日を指定できます。

.ステップ
. コマンドを使用して、AutoSupportメッセージを生成し、パフォーマンスアーカイブファイルをアップロードし `system node autosupport invoke-performance-archive`ます。
+
次の例では、2015年1月12日から4時間分のパフォーマンスアーカイブファイルがAutoSupportメッセージに追加され、デフォルトの場所（NetAppサポートサイト）にアップロードされます。

+
[listing]
----
cluster1::> system node autosupport invoke-performance-archive -node local -start-date 1/12/2015 13:42:09 -duration 4h
----
+
次の例では、2015年1月12日から4時間分のパフォーマンスアーカイブファイルがAutoSupportメッセージに追加され、URIで指定した場所にアップロードされます。

+
[listing]
----
cluster1::> system node autosupport invoke-performance-archive -node local -start-date 1/12/2015 13:42:09 -duration 4h -uri https://files.company.com
----

