---
permalink: system-admin/view-default-certificates-tls-based-applications-task.html 
sidebar: sidebar 
keywords: view, default, certificates, tls, applications, transport 
summary: ONTAPは、トランスポート層セキュリティ（TLS）を使用するONTAPアプリケーションに、信頼できるルート証明書のデフォルト セットを提供します。 
---
= ONTAPのTLSベースアプリケーションのデフォルト証明書を表示する
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
ONTAPは、トランスポート層セキュリティ（TLS）を使用するONTAPアプリケーションに、信頼できるルート証明書のデフォルト セットを提供します。

.開始する前に
デフォルトの証明書は、管理SVMの作成時またはアップグレード時にのみ管理SVMにインストールされます。

.タスク概要
現在、クライアントとして機能し、証明書の検証を必要とするアプリケーションはAutoSupport、EMS、LDAP、監査ログ、FabricPool、および KMIP です。

証明書の有効期限が切れると、ユーザーに証明書の削除を要求するEMSメッセージが呼び出されます。デフォルトの証明書は、上級権限レベルでのみ削除できます。

[NOTE]
====
デフォルトの証明書を削除すると、一部のONTAPアプリケーション（AutoSupportや監査ログなど）が期待どおりに機能しなくなる可能性があります。

====
.手順
. 管理SVMにインストールされているデフォルトの証明書を表示するには、security certificate showコマンドを使用します。
+
`*security certificate show -vserver –type server-ca*`

+
[listing]
----
cluster1::> security certificate show

Vserver    Serial Number   Certificate Name                          Type
---------- --------------- ----------------------------------------- ---------
vs0        4F4E4D7B         www.example.com                            server
    Certificate Authority:  www.example.com
          Expiration Date: Thu Feb 28 16:08:28 2013
----
+
 `security certificate show`の詳細については、link:https://docs.netapp.com/us-en/ontap-cli/security-certificate-show.html?q=show["ONTAPコマンド リファレンス"^]を参照してください。


