---
permalink: system-admin/when-where-autosupport-messages-sent-concept.html 
sidebar: sidebar 
keywords: active, iq, digital advisor, active iq, autosupport, messages, email, manual, scheduled, event, triggered 
summary: AutoSupport は、メッセージの種類に応じた宛先にメッセージを送信します。AutoSupportがメッセージを送信するタイミングと場所を把握しておくと、電子メールで受信するメッセージやデジタルアドバイザWebサイトに表示されるメッセージを理解するのに役立ちます。 
---
= ONTAP AutoSupportメッセージが送信されるタイミングと場所を確認する
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
AutoSupport は、メッセージの種類に応じた宛先にメッセージを送信します。AutoSupportがメッセージを送信するタイミングと場所を把握しておくと、電子メールで受信するメッセージやデジタルアドバイザWebサイトに表示されるメッセージを理解するのに役立ちます。

特に指定がないかぎり、次の表に示す設定はコマンドのパラメータです `system node autosupport modify`。



== イベントトリガー型メッセージ

対処が必要なシステムでイベントが発生すると、AutoSupportはイベントトリガー型メッセージを自動的に送信します。

|===
| メッセージが送信されたとき | メッセージの送信先 


 a| 
AutoSupportがEMSのトリガーイベントに応答する
 a| 
および `-noteto`で指定されたアドレス `-to`。（送信されるのはサービスに影響する重要なイベントのみ）。

で指定されたアドレス `-partner-address`

テクニカルサポート（がに設定されている `enable`場合） `-support`

|===


== スケジュールされたメッセージ

AutoSupport は、定期的に複数のメッセージを自動的に送信します。

|===
| メッセージが送信されたとき | メッセージの送信先 


 a| 
毎日（デフォルトでは、午前12時から午前1時の間にログメッセージとして送信されます）
 a| 
で指定されたアドレス `-partner-address`

テクニカルサポート（がに設定されている `enable`場合） `-support`



 a| 
Daily（デフォルトでは、パフォーマンスメッセージとして午前12：00から午前1：00の間に送信されます）（パラメータがに設定されて `true`いる場合） `-perf`
 a| 
partner-address で指定されているアドレス

テクニカルサポート（がに設定されている `enable`場合） `-support`



 a| 
毎週（デフォルトでは、日曜日の午前12時から午前1時まで送信されます）
 a| 
で指定されたアドレス `-partner-address`

テクニカルサポート（がに設定されている `enable`場合） `-support`

|===


== 手動でトリガーされるメッセージ

AutoSupportメッセージは、手動で開始または再送信できます。

|===
| メッセージが送信されたとき | メッセージの送信先 


 a| 
コマンドを使用して、手動でメッセージを送信したとき `system node autosupport invoke`
 a| 
コマンドでパラメータを `system node autosupport invoke`使用してURIを指定する `-uri`と、そのURIにメッセージが送信されます。

 `-uri`を省略すると、および `-partner-address`で指定したアドレスにメッセージが送信され `-to`ます。をに設定し `enable`た場合は、テクニカルサポートにもメッセージが送信され `-support`ます。



 a| 
コマンドを使用して、手動でメッセージを送信したとき `system node autosupport invoke-core-upload`
 a| 
コマンドでパラメータ `system node autosupport invoke-core-upload`を使用してURIを指定する `-uri`と、そのURIにメッセージが送信され、コアダンプファイルがアップロードされます。

 `-uri`コマンドでを省略する `system node autosupport invoke-core-upload`と、テクニカルサポートにメッセージが送信され、テクニカルサポートサイトにコアダンプファイルがアップロードされます。

どちらのシナリオでも、がに設定され `enable`、 `-transport`がまたはに `http`設定されている `https`必要があります `-support`。

コアダンプファイルはサイズが大きいため、パラメータおよび `-partner-addresses`パラメータで指定したアドレスにメッセージが送信されません `-to`。



 a| 
コマンドを使用して、手動でメッセージを送信したとき `system node autosupport invoke-performance-archive`
 a| 
コマンドでパラメータを `system node autosupport invoke-performance-archive`使用してURIを指定する `-uri`と、そのURIにメッセージが送信され、パフォーマンスアーカイブファイルがアップロードされます。

 `-uri`でを省略する `system node autosupport invoke-performance-archive`と、テクニカルサポートにメッセージが送信され、テクニカルサポートサイトにパフォーマンスアーカイブファイルがアップロードされます。

どちらのシナリオでも、がに設定され `enable`、 `-transport`がまたはに `http`設定されている `https`必要があります `-support`。

パフォーマンスアーカイブファイルはサイズが大きいため、パラメータと `-partner-addresses`パラメータで指定したアドレスにメッセージが送信されません `-to`。



 a| 
コマンドを使用して、過去のメッセージを手動で再送信した場合 `system node autosupport history retransmit`
 a| 
コマンドのパラメータ `system node autosupport history retransmit`で指定したURIのみに送信されます。 `-uri`

|===


== テクニカルサポートによってトリガーされるメッセージです

テクニカルサポートは、 AutoSupport OnDemand 機能を使用して、 AutoSupport からのメッセージを要求できます。

|===
| メッセージが送信されたとき | メッセージの送信先 


 a| 
AutoSupport が新しい AutoSupport メッセージを生成するという送信指示を取得したとき
 a| 
で指定されたアドレス `-partner-address`

テクニカルサポート（がに設定され、がに設定 `enable`されて `-transport`いる `https`場合） `-support`



 a| 
過去の AutoSupport メッセージを再送信するという送信指示を AutoSupport が受け取ったとき
 a| 
テクニカルサポート（がに設定され、がに設定 `enable`されて `-transport`いる `https`場合） `-support`



 a| 
コアダンプファイルまたはパフォーマンスアーカイブファイルをアップロードする新しい AutoSupport メッセージを生成するという送信指示を AutoSupport が受け取ったとき
 a| 
がに設定され、がに設定 `enable`され `https`て `-transport`いる場合は、テクニカルサポート `-support`。テクニカルサポートサイトにコアダンプファイルまたはパフォーマンスアーカイブファイルがアップロードされます。

|===