---
permalink: authentication/change-login-password-task.html 
sidebar: sidebar 
keywords: reset password, administrator, security login password 
summary: 初期パスワードは、システムに初めてログインした直後に変更する必要があります。 
---
= ONTAPでの管理者パスワードの変更
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
初期パスワードは、システムへの初回ログイン後すぐに変更してください。SVM管理者は、コマンドを使用して自分のパスワードを変更できます `security login password`。クラスタ管理者は、コマンドを使用して管理者のパスワードを変更できます `security login password`。

.タスクの内容
新しいパスワードは次のルールに従う必要があります。

* ユーザ名を含めることはできません。
* 8文字以上である必要があります。
* 英文字と数字がそれぞれ1文字以上含まれている必要があります。
* 直近の6つのパスワードと同じパスワードは使用できません。



NOTE: コマンドを使用すると、指定したロールに関連付けられたアカウントのパスワードルールを変更できます[`security login role config modify`。リンクhttps://docsの詳細については、ONTAPコマンドリファレンスを参照してください。NetApp .com /us-en/ ONTAP -CLI/ security-login-role-config-modify.html[`security login role config modify`^]コマンドを参照してください。

.開始する前に
* 自分のパスワードを変更するには、クラスタ管理者またはSVM管理者である必要があります。
* 他の管理者のパスワードを変更するには、クラスタ管理者である必要があります。


.ステップ
. 管理者パスワードを変更します。 `security login password -vserver _svm_name_ -username _user_name_`
+
次のコマンドは、SVMの``vs1.example.com``管理者のパスワードを変更し `admin1`ます。プロンプトが表示されたら、現在のパスワードを入力し、新しいパスワードを入力して再入力します。

+
[listing]
----
vs1.example.com::>security login password -vserver engData -username admin1
Please enter your current password:
Please enter a new password:
Please enter it again:
----

