---
permalink: authentication/change-login-password-task.html 
sidebar: sidebar 
keywords: change, administrator password 
summary: 初期パスワードは、システムへの初回ログイン後すぐに変更してください。SVM 管理者の場合は、 security login password コマンドを使用して自分のパスワードを変更できます。クラスタ管理者の場合は、 security login password コマンドを使用して管理者のパスワードを変更できます。 
---
= 管理者パスワードを変更します
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
初期パスワードは、システムへの初回ログイン後すぐに変更してください。SVM管理者は、を使用できます `security login password` コマンドを使用して自分のパスワードを変更します。クラスタ管理者は、を使用できます `security login password` コマンドを使用して管理者のパスワードを変更します。

.必要なもの
* 自分のパスワードを変更するには、クラスタ管理者または SVM 管理者である必要があります。
* 他の管理者のパスワードを変更するには、クラスタ管理者である必要があります。


.このタスクについて
新しいパスワードは次のルールに従う必要があります。

* ユーザ名を含めることはできません
* 8 文字以上である必要があります
* アルファベットと数字がそれぞれ 1 文字以上含まれている必要があります
* 直近の 6 つのパスワードと同じパスワードは使用できません


[NOTE]
====
を使用できます.`security login role config modify` コマンドを使用して、特定のロールに関連付けられているアカウントのパスワードルールを変更します。詳細については、のマニュアルページを参照してください.`security login role config modify`

====
.ステップ
. 管理者パスワードを変更します。 `security login password -vserver SVM_name -username user_name`
+
管理者のパスワードを変更するコマンドの例を次に示します `admin1` SVM用``vs1.example.com``。現在のパスワードの入力を求められたら、新しいパスワードを入力して、もう一度入力します。

+
[listing]
----
vs1.example.com::>security login password -vserver engData -username admin1
Please enter your current password:
Please enter a new password:
Please enter it again:
----

