---
permalink: authentication/configure-nis-server-access-task.html 
sidebar: sidebar 
keywords: configure, nis server, access 
summary: NIS アカウントが SVM にアクセスするためには、 NIS サーバから SVM へのアクセスを設定しておく必要があります。SVM に NIS ドメイン設定を作成するには、 vserver services name-service nis-domain create コマンドを使用します。 
---
= NIS サーバアクセスの設定
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
NIS アカウントが SVM にアクセスするためには、 NIS サーバから SVM へのアクセスを設定しておく必要があります。を使用できます `vserver services name-service nis-domain create` コマンドを使用してSVMにNISドメイン設定を作成します。

.必要なもの
* SVM に NIS ドメインを設定するためには、設定済みのすべてのサーバが使用可能でアクセスできる状態になっている必要があります。
* このタスクを実行するには、クラスタ管理者または SVM の管理者である必要があります。


.このタスクについて
複数の NIS ドメインを作成できます。に設定できるNISドメインは1つだけです `active` 一度に。

.ステップ
. SVMにNISドメイン設定を作成します。 `vserver services name-service nis-domain create -vserver SVM_name -domain client_configuration -active true|false -nis-servers NIS_server_IPs`
+
コマンド構文全体については、を参照してください link:config-worksheets-reference.html["ワークシート"]。

+
[NOTE]
====
ONTAP 9.2以降では、フィールドが表示されます `-nis-servers` フィールドを置き換えます `-servers`。この新しいフィールドには、 NIS サーバのホスト名または IP アドレスを指定できます。

====
+
次のコマンドは、SVMにNISドメイン設定を作成します ``engData``。NISドメイン `nisdomain` は作成時にアクティブになり、IPアドレスを使用してNISサーバと通信します `192.0.2.180`。

+
[listing]
----
cluster1::>vserver services name-service nis-domain create
-vserver engData -domain nisdomain -active true -nis-servers 192.0.2.180
----

