---
permalink: authentication/create-svm-user-accounts-task.html 
sidebar: sidebar 
keywords: create, login accounts 
summary: クラスタおよび SVM の管理者アカウントは、ローカルまたはリモートのいずれかとして有効にできます。ローカルアカウントでは、アカウント情報、公開鍵、セキュリティ証明書がストレージシステムに格納されます。AD アカウント情報はドメインコントローラに格納されます。LDAP および NIS アカウントは LDAP サーバおよび NIS サーバ上に存在します。 
---
= ログインアカウントの作成の概要
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
クラスタおよび SVM の管理者アカウントは、ローカルまたはリモートのいずれかとして有効にできます。ローカルアカウントでは、アカウント情報、公開鍵、セキュリティ証明書がストレージシステムに格納されます。AD アカウント情報はドメインコントローラに格納されます。LDAP および NIS アカウントは LDAP サーバおよび NIS サーバ上に存在します。



== クラスタ管理者と SVM 管理者

クラスタ管理者は、クラスタの管理 SVM にアクセスします。管理SVMと予約名を持つクラスタ管理者 `admin` クラスタのセットアップ時に自動的に作成されます。

デフォルトのクラスタ管理者 `admin` ロールは、クラスタ全体とそのリソースを管理できます。クラスタ管理者は、必要に応じて別のロールを割り当てた別のクラスタ管理者を作成することができます。

SVM administrator は、データ SVM にアクセスします。クラスタ管理者は、必要に応じてデータ SVM と SVM 管理者を作成します。

SVM管理者は、に割り当てられます `vsadmin` デフォルトでは、ロールです。クラスタ管理者は、必要に応じて SVM 管理者に別のロールを割り当てることができます。

[NOTE]
====
リモートクラスタおよび SVM の管理者アカウントには、「 adm 」、「 bin 」、「 cli 」、「 daemon 」、「 ftp 」、 "games " 、 "halt" 、 "lp " 、 "mail" 、 "man" 、 「 naroot 」、「 netapp 」、「 news 」、「 nobody 」、「 operator 」、 "root" 、 "shutdown" 、 "sshd" 、 "sync" 、 "sys" 、 "uucp" 、および "www" 。

====


== マージされたロール

同じユーザに対して複数のリモートアカウントを有効にすると、そのユーザには各アカウントに対して指定されたロールがすべて割り当てられます。つまり、LDAPまたはNISアカウントが割り当てられている場合です `vsadmin` ロールおよび同じユーザのADグループアカウントがに割り当てられます `vsadmin-volume` ロールが大きいほど、ADユーザはより包括的な権限でログインします `vsadmin` 機能：ロールは、 _ merged__ と呼ばれます。
