---
permalink: authentication/create-svm-user-accounts-task.html 
sidebar: sidebar 
keywords: create, login accounts 
summary: クラスタおよび SVM の管理者アカウントは、ローカルまたはリモートのいずれかとして有効にできます。ローカルアカウントでは、アカウント情報、公開鍵、セキュリティ証明書がストレージシステムに格納されます。ADアカウント情報はドメインコントローラに保存されます。LDAPおよびNISアカウントは、LDAPサーバおよびNISサーバ上に存在します。 
---
= ログインアカウントの作成の概要
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
クラスタおよび SVM の管理者アカウントは、ローカルまたはリモートのいずれかとして有効にできます。ローカルアカウントでは、アカウント情報、公開鍵、セキュリティ証明書がストレージシステムに格納されます。ADアカウント情報はドメインコントローラに保存されます。LDAPおよびNISアカウントは、LDAPサーバおよびNISサーバ上に存在します。



== クラスタ管理者とSVM管理者

クラスタ管理者は、クラスタの管理 SVM にアクセスします。管理SVMと予約された名前のクラスタ管理者は `admin`、クラスタのセットアップ時に自動的に作成されます。

デフォルトのロールを持つクラスタ管理者は、 `admin`クラスタとそのリソース全体を管理できます。クラスタ管理者は、必要に応じて別のロールを割り当てた別のクラスタ管理者を作成することができます。

SVM administrator は、データ SVM にアクセスします。クラスタ管理者は、必要に応じてデータ SVM と SVM 管理者を作成します。

SVM管理者には、デフォルトでロールが割り当てられ `vsadmin`ます。クラスタ管理者は、必要に応じて SVM 管理者に別のロールを割り当てることができます。



=== 命名規則

リモートクラスタおよびSVMの管理者アカウントには、次の汎用名は使用できません。

* "adm"
* "ビン"
* "CLI"
* "デーモン"
* "ftp"
* "ゲーム"
* "停止"
* "LP"
* "メール"
* "男"
* "naroot"
* " NetApp "
* "ニュース"
* "誰もいない"
* "演算子"
* "ルート"
* "シャットダウン"
* "sshd"
* "同期"
* "sys"
* " uucp"
* "WWW"




== マージされたロール

同じユーザに対して複数のリモートアカウントを有効にすると、そのユーザには各アカウントに対して指定されたロールがすべて割り当てられます。つまり、LDAPまたはNISアカウントにロールが割り当てられ、同じユーザのADグループアカウントにロールが割り当てられている `vsadmin-volume`場合、 `vsadmin`ADユーザはより包括的な機能を使用してログインし `vsadmin`ます。ロールは、 _ merged__ と呼ばれます。
