---
permalink: authentication/grant-access-active-directory-users-groups-task.html 
sidebar: sidebar 
keywords: enable, active directory, account access 
summary: Active Directory （ AD ）のユーザアカウントまたはグループアカウントが管理またはデータ SVM にアクセスできるようにするには、 security login create コマンドを使用します。AD グループのすべてのユーザは、グループに割り当てられたロールを使用して SVM にアクセスできます。 
---
= Active Directory アカウントアクセスを有効にします
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
を使用できます `security login create` コマンドを使用して、Active Directory（AD）ユーザまたはグループアカウントが管理またはデータSVMにアクセスできるようにします。AD グループのすべてのユーザは、グループに割り当てられたロールを使用して SVM にアクセスできます。

.必要なもの
* クラスタ時間と AD ドメインコントローラの時刻を、誤差が 5 分以内となるように同期する必要があります。
* このタスクを実行するには、クラスタ管理者である必要があります。


.このタスクについて
* アカウントが SVM にアクセスするためには、 AD ドメインコントローラからクラスタまたは SVM へのアクセスを設定しておく必要があります。
+
xref:enable-ad-users-groups-access-cluster-svm-task.adoc[Active Directory ドメインコントローラアクセスを設定しています]

+
このタスクは、アカウントアクセスを有効にする前後どちらでも実行できます。

* ONTAP 9.11.1以降では、を使用できます link:../nfs-admin/ldap-fast-bind-nsswitch-authentication-task.html["nsswitch認証のためのLDAP高速バインド"] AD LDAPサーバでサポートされている場合。
* ログインアカウントに割り当てるアクセス制御ロールが不明な場合は、を使用します `security login modify` コマンドを使用してあとでロールを追加します。
+
xref:modify-role-assigned-administrator-task.adoc[管理者に割り当てられているロールの変更]



[NOTE]
====
ADグループアカウントへのアクセスは、でのみサポートされます `SSH` および `ontapi` アプリケーション：

====
.ステップ
. AD のユーザまたはグループ管理者アカウントが SVM にアクセスできるようにします。
+
`security login create -vserver SVM_name -user-or-group-name user_or_group_name -application application -authmethod domain -role role -comment comment [-is-ldap-fastbind true]`

+
コマンド構文全体については、を参照してください link:config-worksheets-reference.html["ワークシート"]。

+
link:config-worksheets-reference.html["ログインアカウントを作成または変更する"]

+
次のコマンドは、ADクラスタ管理者アカウントを有効にします `DOMAIN1\guest1` を使用します `backup` 管理SVMにアクセスするためのロール``engCluster``。

+
[listing]
----
cluster1::>security login create -vserver engCluster -user-or-group-name DOMAIN1\guest1 -application ssh -authmethod domain -role backup
----
+
次のコマンドは、ADグループアカウントのSVM管理者アカウントを有効にします `DOMAIN1\adgroup` を使用します `vsadmin-volume` SVMにアクセスするためのロール``engData``。

+
[listing]
----
cluster1::>security login create -vserver engData -user-or-group-name DOMAIN1\adgroup -application ssh -authmethod domain -role vsadmin-volume
----


.完了後
AD ドメインコントローラからクラスタまたは SVM へのアクセスを設定していない場合は、アカウントが SVM にアクセスする前に設定しておく必要があります。

xref:enable-ad-users-groups-access-cluster-svm-task.adoc[Active Directory ドメインコントローラアクセスを設定しています]
