---
permalink: authentication/index.html 
sidebar: sidebar 
keywords: decide, overview, administrator, authentication, rbac, role-based, access, control 
summary: ONTAPのクラスタ管理者およびStorage Virtual Machine（SVM）管理者のログイン アカウントを有効にすることができます。管理者が実行できる機能をロールベース アクセス制御（RBAC）を使用して定義することもできます。 
---
= ONTAPの管理者認証とRBACについて学ぶ
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
ONTAPのクラスタ管理者およびStorage Virtual Machine（SVM）管理者のログイン アカウントを有効にすることができます。管理者が実行できる機能をロールベース アクセス制御（RBAC）を使用して定義することもできます。

ローカルの管理者アカウントには、次の種類の認証を使用した管理Storage Virtual Machine（SVM）またはデータSVMへのアクセスを許可できます。

* link:enable-password-account-access-task.html["パスワード"]
* link:enable-ssh-public-key-accounts-task.html["SSH公開鍵"]
* link:enable-ssl-certificate-accounts-task.html["SSL証明書"]
* link:mfa-overview.html["SSH多要素認証（MFA）"]
+
ONTAP 9.3以降では、パスワードと公開鍵による認証がサポートされています。



リモートの管理者アカウントには、次の種類の認証を使用した管理SVMまたはデータSVMへのアクセスを許可できます。

* link:grant-access-active-directory-users-groups-task.html["Active Directory"]
+
ONTAP 9.13.1以降では、Active Directoryユーザのプライマリ認証方式またはセカンダリ認証方式としてSSH公開キーを使用できます。

* link:../system-admin/configure-saml-authentication-task.html["SAML認証（管理SVMのみ）"]
+
ONTAP 9.3以降では、Service Processor Infrastructure、ONTAP API、またはSystem Managerのいずれかのwebサービスを使用して管理SVMにアクセスするために、Security Assertion Markup Language（SAML）認証を使用できます。

* link:grant-access-nis-ldap-user-accounts-task.html["LDAP または NIS"]
+
ONTAP 9.4以降では、LDAPサーバまたはNISサーバ上のリモート ユーザにSSH MFAを使用できます。nsswitchと公開鍵による認証がサポートされます。


