---
permalink: authentication/manage-public-key-authentication-concept.html 
sidebar: sidebar 
keywords: associate, public key, administrator account 
summary: SSH 公開鍵認証を使用する場合、アカウントが SVM にアクセスするためには、管理者アカウントに公開鍵を関連付ける必要があります。security login publickey create コマンドを使用して、管理者アカウントにキーを関連付けることができます。 
---
= 管理者アカウントに公開鍵を関連付けます
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
SSH 公開鍵認証を使用する場合、アカウントが SVM にアクセスするためには、管理者アカウントに公開鍵を関連付ける必要があります。を使用できます `security login publickey create` 管理者アカウントにキーを関連付けるコマンド。

.作業を開始する前に
* SSH キーを生成しておく必要があります。
* このタスクを実行するには、クラスタ管理者または SVM の管理者である必要があります。


.このタスクについて
SSH でのアカウントの認証にパスワードと SSH 公開鍵の両方を使用する場合、アカウントはまず公開鍵を使用して認証されます。

.手順
. 管理者アカウントに公開鍵を関連付けます。
+
`security login publickey create -vserver _SVM_name_ -username _user_name_ -index _index_ -publickey _certificate_ -comment _comment_`

+
コマンド構文全体については、のワークシートリファレンスを参照してください link:config-worksheets-reference.html["ユーザアカウントへの公開鍵の関連付け"^]。

. 公開鍵を表示して変更を確認します。
+
`security login publickey show -vserver _SVM_name_ -username _user_name_ -index _index_`



.例
次のコマンドは、SVM管理者アカウントに公開鍵を関連付けます `svmadmin1` SVM用 `engData1`。公開鍵のインデックス番号は 5 です。

[listing]
----
cluster1::> security login publickey create -vserver engData1 -username svmadmin1 -index 5 -publickey
"<key text>"
----