---
permalink: authentication/reset-totp-configuration-task.html 
sidebar: sidebar 
keywords: enable, ssh, multifactor authentication, mfa, hardware authentication device 
summary: アカウントのセキュリティを確保するために、TOTPシークレット キーが侵害されたり、キーを紛失した場合、既存のキーを無効にして新しいシークレット キーを作成する必要があります。 
---
= ONTAPユーザーアカウントのTOTP秘密キーをリセットします
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
アカウントのセキュリティを確保するために、TOTPシークレット キーが侵害されたり、キーを紛失した場合、既存のキーを無効にして新しいシークレット キーを作成する必要があります。



== キー侵害時のTOTPのリセット

TOTPシークレット キーが侵害されたが引き続きアクセスできる場合は、侵害されたキーを削除して新しいキーを作成できます。

. ユーザ パスワードまたはSSH公開鍵と、侵害されたTOTPシークレット キーを使用して、ユーザ アカウントにログインします。
. 侵害されたTOTPシークレット キーを削除します。
+
[source, cli]
----
security login totp delete -vserver <svm_name> -username <account_username>
----
. 新しいTOTPシークレット キーを作成します。
+
[source, cli]
----
security login totp create -vserver <svm_name> -username <account_username>
----
. アカウントでTOTP設定が有効になっていることを確認します。
+
[source, cli]
----
security login totp show -vserver <svm_name> -username <account_username>
----




== キー紛失時のTOTPのリセット

TOTP 秘密キーを紛失した場合は、ストレージ管理者に連絡してlink:disable-totp-secret-key-task.html["キーが無効になっている"]してください。キーが無効になったら、最初の認証方法を使用してログインし、新しい TOTP を設定できます。

.開始する前に
ストレージ管理者が、TOTPシークレット キーを無効にする必要があります。ストレージ管理者でない場合は、ストレージ管理者にキーの無効化を依頼してください。

.手順
. ストレージ管理者がTOTPシークレットを無効にしたら、第1の認証方式を使用してローカル アカウントにログインします。
. 新しいTOTPシークレット キーを作成します。
+
[source, cli]
----
security login totp create -vserver <svm_name> -username <account_username >
----
. アカウントでTOTP設定が有効になっていることを確認します。
+
[source, cli]
----
security login totp show -vserver <svm_name> -username <account_username>
----


.関連情報
* link:https://docs.netapp.com/us-en/ontap-cli/security-login-totp-create.html["セキュリティログイン TOTP 作成"^]
* link:https://docs.netapp.com/us-en/ontap-cli/security-login-totp-delete.html["セキュリティログイン TOTP 削除"^]
* link:https://docs.netapp.com/us-en/ontap-cli/security-login-totp-show.html["security login totp show"^]

